-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_CITASASIGNADAS
-- Extracted by Fabric SQL Extractor SPN v3.9.0






CREATE VIEW [Report].[View_HDSAP_CITASASIGNADAS]
AS

SELECT
	   aga.IPCODPACI DOCUMENTO,
	   inp.IPNOMCOMP [NOMBRE PACIENTE],
	   aga.FECHORAIN FECHA,
	   aga.OBSERVACI OBSERVACIÓN,
	   PRO.NOMUSUARI 'USUARIO ASIGNA',
	   CUPS.Description PROCEDIMIENTO,
	   INE.NOMENTIDA EPS



 FROM  dbo.AGASICITA AS AGA
     INNER JOIN dbo.SEGusuaru AS PRO ON AGA.CODUSUASI = PRO.CODUSUARI
     INNER JOIN dbo.INPACIENT AS INP ON AGA.IPCODPACI = INP.IPCODPACI
	 INNER JOIN INENTIDAD INE ON INE.CODENTIDA = INP.CODENTIDA
     INNER JOIN dbo.INPROFSAL AS PRO1 ON AGA.CODPROSAL = PRO1.CODPROSAL
	 INNER JOIN Contract.CUPSEntity CUPS ON CUPS.Code = AGA.CODSERIPS

 WHERE  not AGA.IPCODPACI in ( '123456', '12345' ) and TIPSOLICITU = 1
  

