-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_CENSO_HOSPITALARIO
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE VIEW [Report].[View_HDSAP_CENSO_HOSPITALARIO]
AS

SELECT  E.REGUSUARI AS CodUsuario, US.NOMUSUARI AS Usuario, UF.UFUDESCRI AS Servicio, C.DESCCAMAS AS Cama, I.NUMINGRES AS NumeroIngreso, I.IFECHAING AS FechaIngreso, DATEDIFF(d, I.IFECHAING, 
    GETDATE()) AS DiasHospital,           
	CASE p.IPTIPODOC
        WHEN '1'
        THEN 'CC'
        WHEN '2'
        THEN 'CE '
        WHEN '3'
        THEN 'TI'
        WHEN '4'
        THEN 'RC'
        WHEN '5'
        THEN 'PA'
        WHEN '6'
        THEN 'AS'
        WHEN '7'
        THEN 'MS'
        WHEN '8'
        THEN 'NU'
		WHEN 9
		THEN 'CN'
		WHEN 11
		THEN 'SC'
		WHEN 12
		THEN 'PE'
		WHEN 13
		THEN 'PT'
		WHEN 14
		THEN 'DE'
		WHEN 15
		THEN 'SI'
    END AS 'Tipo Documento',
	E.IPCODPACI AS Identificación, P.IPPRINOMB PNombre, p.IPSEGNOMB SNombre, p.IPPRIAPEL PApellido, p.ipsegapel Sapellido, (datediff (year,P.IPFECNACI, getdate ())) EDAD,
    CASE WHEN P.IPSEXOPAC = '1' THEN 'Masculino' WHEN P.IPSEXOPAC = '2' THEN 'Femenino' END AS Sexo, D.CODDIAGNO AS CodDiag, V.NOMDIAGNO AS DiagnosticoPpal, P.IPDIRECCI AS Direccion, 
    P.IPTELEFON AS Telefono, P.IPTELMOVI AS Movil, CONVERT(varchar, E.FECINIEST, 100) AS IngresoCama, DATEDIFF(d, E.FECINIEST, GETDATE()) AS DiasCama, A.NOMENTIDA AS Entidad, 
    I.IAUTORIZA AS NumeroAutorizacion, I.IOBSERVAC AS Observaciones,INESPECIA.DESESPECI AS EspecialidadTratante
FROM CHCAMASHO AS C INNER JOIN
    ADCENATEN AS CA ON CA.CODCENATE = C.CODCENATE INNER JOIN
    INUNIFUNC AS UF ON UF.UFUCODIGO = C.UFUCODIGO INNER JOIN
    CHREGESTA AS E ON E.CODICAMAS = C.CODICAMAS AND E.REGESTADO = '1' INNER JOIN
    CHTIPESTA AS TE ON TE.CODTIPEST = E.CODTIPEST INNER JOIN
    ADINGRESO AS I ON I.NUMINGRES = E.NUMINGRES INNER JOIN
    INPACIENT AS P ON P.IPCODPACI = E.IPCODPACI INNER JOIN
    INENTIDAD AS A ON A.CODENTIDA = I.CODENTIDA LEFT OUTER JOIN
    INDIAGNOP AS D ON D.NUMINGRES = E.NUMINGRES AND D.IPCODPACI = E.IPCODPACI AND D.CODDIAPRI = 'True' LEFT OUTER JOIN
    INDIAGNOS AS V ON V.CODDIAGNO = D.CODDIAGNO INNER JOIN
    SEGusuaru AS US ON US.CODUSUARI = E.REGUSUARI INNER JOIN
    INESPECIA ON I.CODESPTRA =INESPECIA.CODESPECI
WHERE        (C.CODCENATE = '001') AND (C.ESTADCAMA = '2')

