-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_OPORTUNIDAD_LABORATORIO
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE VIEW [Report].[View_HDSAP_OPORTUNIDAD_LABORATORIO]
AS

 select 
     ord.IPCODPACI DocumentoPaciente,
	 RTRIM(pac.IPNOMCOMP) Paciente,
	 ord.CODPROSAL CodigoMedico,
	 RTRIM(s.NOMMEDICO) NombreMedico,
	 RTRIM(UNI.UFUDESCRI) UnidadFuncional,
	 CUPS.CODE CodigoCups,
	 CUPS.Description NombreCups,
	 ORD.FECORDMED as [FECHA SOLICITUD]
	,ORD.FECRECMUE as [FECHA MUESTRA]
	,IIF(ORD.FECORDMED>ORD.FECRECMUE,0,DATEDIFF(MINUTE,ORD.FECORDMED,ORD.FECRECMUE)) AS[MINUTOS ENTRE SOLICITUD Y MUESTRA]
	,IIF(ORD.FECORDMED>RES.FECREGIST,0,DATEDIFF(MINUTE,ORD.FECORDMED,RES.FECREGIST)) AS[MINUTOS ENTRE SOLICITUD Y FECHA RESULTADO]
	,ISNULL(ORD.FECHARESULT,RES.FECREGIST) AS [FECHA RESULTADO]

FROM hcordlabo ord
	JOIN inpacient pac on pac.ipcodpaci = ord.ipcodpaci
	JOIN INUNIFUNC UNI ON UNI.UFUCODIGO = ORD.UFUCODIGO
	JOIN CONTRACT.CUPSEntity CUPS ON CUPS.Code = ORD.CODSERIPS
	JOIN DBO.INPROFSAL s on s.CODPROSAL = ord.CODPROSAL
	LEFT JOIN dbo.INTERCTRL RES ON ORD.AUTO=RES.AUTOLABOR AND RES.AUTO=(SELECT MAX(RE.AUTO) FROM INTERCTRL RE WHERE ORD.AUTO=RE.AUTOLABOR)

