-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_OPORTUNIDAD_IMAGENOLOGIA
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE VIEW [Report].[View_HDSAP_OPORTUNIDAD_IMAGENOLOGIA]
AS
   select ROW_NUMBER() OVER (ORDER BY agc.IPCODPACI) AS 'N°',-- CODSERIPS,
			inp.IPNOMCOMP as'NOMBRE DEL PACIENTE',
			agc.IPCODPACI as 'IDENTIFICACIÓN',
			inc.DESSERIPS as 'TIPO DE EXAMEN',
			1 as'CANTIDAD',
			case IDSALA
			when 1 then 'RADIOLOGIA'
			when 2 then 'TAC'
			WHEN 3 THEN 'PERINATOLOGIA'
			WHEN 4 THEN 'ECOGRAFIA'
			WHEN 5 THEN 'ECOGRAFIA'
			WHEN 6 THEN 'RESONANCIA' END
			 as'SERVICIO',
			AGC.FECREGSIS AS 'FECHA DE SOLICITUD DEL EXAMEN',
			AGC.FECHORAIN AS FECHAEXAMEN,
			DATEDIFF(day, AGC.FECREGSIS, AGC.FECHORAIN) AS'OPORTUNIDAD EN LA ATENCIÓN - DIAS',
			''AS'TÉCNICO',
			'' AS'RADIÓLOGO',
			CASE AGC.CODESTCIT
			WHEN 0 THEN 'Asignada'
			WHEN 1 THEN 'Cumplida'
			WHEN 2 THEN 'Incumplida'
			WHEN 3 THEN 'PreAsignada'
			WHEN 4 THEN 'Cita Cancelada'
			END AS 'ESTADO'
			from AGASICITA as agc inner join
			INPACIENT as inp on inp.IPCODPACI=agc.IPCODPACI inner join
			INCUPSIPS as inc on inc.CODSERIPS=agc.CODSERIPS

