-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_INGRESOS_ABIERTOS_TERAPIA
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[View_HDSAP_INGRESOS_ABIERTOS_TERAPIA]
AS


		SELECT        ADINGRESO.IPCODPACI AS [DOC PACIENTE], INPACIENT.IPNOMCOMP AS [NOMBRE PACIENTE], ADINGRESO.NUMINGRES AS INGRESO, 
                         CASE WHEN ADINGRESO.IESTADOIN = ' ' THEN 'Abierto' WHEN ADINGRESO.IESTADOIN = 'F' THEN 'Facturado' WHEN ADINGRESO.IESTADOIN = 'A' THEN 'Anulado'
                          END AS [ESTADO INGRESO], ADINGRESO.IFECHAING AS FECHAINGRESO, ADINGRESO.CODUSUCRE AS [COD USUARIO CREA], 
                         SEGusuaru_2.NOMUSUARI AS [USUARIO CREA]
                       
FROM            ADINGRESO INNER JOIN
                         INPACIENT ON ADINGRESO.IPCODPACI = INPACIENT.IPCODPACI INNER JOIN
                         INENTIDAD ON ADINGRESO.CODENTIDA = INENTIDAD.CODENTIDA LEFT OUTER JOIN
                         SEGusuaru ON ADINGRESO.CODUSUANU = SEGusuaru.CODUSUARI LEFT OUTER JOIN
                         SEGusuaru AS SEGusuaru_2 ON ADINGRESO.CODUSUCRE = SEGusuaru_2.CODUSUARI LEFT OUTER JOIN
                         SEGusuaru AS SEGusuaru_1 ON ADINGRESO.CODUSUMOD = SEGusuaru_1.CODUSUARI 

 where ADINGRESO.IESTADOIN ='  '

