-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_QUIROFANO
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[View_HDSAP_QUIROFANO]
AS
     SELECT  TOP (100)  PERCENT Q.FECHORINI Fecha, P.CODESPEC1 AS CodEspecialidad, E.DESESPECI AS Especialidad, Q2.CODSERIPS, C2.DESSERIPS AS Descripción, COUNT(Q2.CODSERIPS) 
                      AS CANTIDAD,CASE WHEN Q.URGECIRUG = 'TRUE' THEN 'URGENCIA' WHEN Q.URGECIRUG = 'FALSE' THEN 'PROGRAMADA' END AS Tipo
FROM         dbo.HCQXINFOR AS Q INNER JOIN
                      dbo.INPROFSAL AS P ON Q.CODPROSAL = P.CODPROSAL INNER JOIN
                      dbo.INESPECIA AS E ON P.CODESPEC1 = E.CODESPECI INNER JOIN
                      dbo.HCQXREALI AS Q2 ON Q.NUMEFOLIO = Q2.NUMEFOLIO AND Q.IPCODPACI = Q2.IPCODPACI AND Q.NUMINGRES = Q2.NUMINGRES INNER JOIN
                      dbo.INCUPSIPS AS C2 ON Q2.CODSERIPS = C2.CODSERIPS

GROUP BY P.CODESPEC1, E.DESESPECI, Q2.CODSERIPS, C2.DESSERIPS,Q.URGECIRUG, Q.FECHORINI


