-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_URGENCIASTRIAGEPRIMERTRIAGE
-- Extracted by Fabric SQL Extractor SPN v3.9.0






CREATE VIEW [Report].[View_HDSAP_URGENCIASTRIAGEPRIMERTRIAGE]
AS

WITH 
CTE_HCHISPACA AS (
    SELECT 
        h.IPCODPACI,
        h.NUMINGRES,
        h.FECHISPAC,
        h.CODPROSAL,
        ROW_NUMBER() OVER (PARTITION BY h.IPCODPACI, h.NUMINGRES ORDER BY h.FECHISPAC) AS RowNum
    FROM dbo.HCHISPACA AS h
),
PrimerRegistroTriage AS (
    SELECT 
        T.*,
        ROW_NUMBER() OVER (PARTITION BY T.IPCODPACI, T.NUMINGRES ORDER BY T.TRIAFECHA) AS RowNum
    FROM dbo.ADTRIAGEU AS T
)
SELECT DISTINCT
    'TIPO DE IDENTIFICACION' = CASE INP.IPTIPODOC
        WHEN '1' THEN 'Cédula de Ciudadanía'
        WHEN '2' THEN 'Cédula de Extranjería'
        WHEN '3' THEN 'Tarjeta de Identidad'
        WHEN '4' THEN 'Registro Civil'
        WHEN '5' THEN 'Pasaporte'
        WHEN '6' THEN 'Adulto Sin Identificación'
        ELSE 'Menor Sin Identificación'
    END,
    CAST(INP.IPFECNACI AS DATE) AS 'FECHA DE NACIMIENTO',
    'SEXO PACIENTE' = CASE INP.IPSEXOPAC
        WHEN '1' THEN 'HOMBRE'
        WHEN '2' THEN 'MUJER'
        ELSE 'INDEFINIDO'
    END,
    INP.IPPRIAPEL AS 'PRIMER APELLIDO',
    INP.IPSEGAPEL AS 'SEGUNDO APELLIDO',
    INP.IPPRINOMB AS 'PRIMER NOMBRE',
    INP.IPSEGNOMB AS 'SEGUNDO NOMBRE',
    CONCAT(INE.CODENTIDA, ' ', INE.NOMENTIDA) AS 'NOMBRE DE LA EAPB',
    T.IPCODPACI AS Documento,
    C.IPCODPACI AS IdControl,
    CAST(T.TRIAFECHA AS DATE) AS 'Clasificacion triage fecha',
    CONVERT(VARCHAR, T.TRIAFECHA, 108) AS 'Clasificacion triage hora',
    CAST(dbo.HCURGING1.FECHINIHI AS DATE) AS 'Fecha consulta',
    CONVERT(VARCHAR, dbo.HCURGING1.FECHINIHI, 108) AS 'Hora consulta',
    C.IPFECLLEGA AS 'ArriboUrgencias(F1)',
    T.TRIAFECHA AS 'Triage(F2)',
    dbo.HCURGING1.FECHINIHI AS 'LlamadoConsulta(F3)',
    H.FECHISPAC AS 'FinConsulta(F4)',
    t2.FECHA1 AS 'Revaloracion(F5)',
    t3.FECHA2 AS 'SegundaRevaloracion(F6)',
    DATEDIFF(MINUTE, C.IPFECLLEGA, T.TRIAFECHA) AS 'F1-F2',
    DATEDIFF(MINUTE, T.TRIAFECHA, H.FECHISPAC) AS 'F2-F4',
    DATEDIFF(MINUTE, T.TRIAFECHA, dbo.HCURGING1.FECHINIHI) AS 'F2-F3',
    DATEDIFF(MINUTE, C.IPFECLLEGA, H.FECHISPAC) AS 'F1-F4',
    DATEDIFF(MINUTE, C.IPFECLLEGA, dbo.HCURGING1.FECHINIHI) AS 'F1-F3',
    DATEDIFF(MINUTE, dbo.HCURGING1.FECHINIHI, H.FECHISPAC) AS 'F3-F4',
    DATEDIFF(HOUR, H.FECHISPAC, t2.FECHA1) AS 'F4-F5',
    DATEDIFF(HOUR, t2.FECHA1, t3.FECHA2) AS 'F5-F6',
    T.TRIAGEDAD AS Edad,
    CASE
        WHEN C.CONESTADO = 1 THEN 'Sin Atender'
        WHEN C.CONESTADO = 2 THEN 'Ausente en Clasificacion TRIAGE'
        WHEN C.CONESTADO = 3 THEN 'Clasificado sin Ingreso'
        WHEN C.CONESTADO = 4 THEN 'Clasificado con Ingreso'
        WHEN C.CONESTADO = 5 THEN 'Atendido'
        WHEN C.CONESTADO = 6 THEN 'Ausente en Atencion Inicial Urgencias'
        WHEN C.CONESTADO = 7 THEN 'Anulado por error de Parametrizacion'
    END AS Estado,
    CASE
        WHEN T.TRIUNIEDA = 1 THEN 'Años'
        WHEN T.TRIUNIEDA = 2 THEN 'Meses'
        WHEN T.TRIUNIEDA = 3 THEN 'Días'
    END AS UnidadEdad,
    T.TRIAGECLA AS Clasificación,
    CASE
        WHEN T.TRIAGECLA = 1 THEN 'Emergencia'
        WHEN T.TRIAGECLA = 2 THEN 'Urgencia Médica'
        WHEN T.TRIAGECLA = 3 THEN 'Urgencia Diferida'
        WHEN T.TRIAGECLA = 4 THEN 'No Urgente'
    END AS Descripción,
    T.CODPROSAL AS CódigoMedicoTriage,
    P.NOMMEDICO AS NombreMedicoTriage,
    P2.NOMMEDICO AS NombreMedicoReva,
    T3.NOMMEDICO AS MedicoConsulta,
    C.UFUCODIGO AS CodigoUnidad,
    UF.UFUDESCRI AS UnidadFuncional,
    dbo.HCURGING1.FECINIATE AS FechaInicioAten,
    T.TRIACAUIN AS CausaIngreso,
    h.IDETIPHIS

FROM dbo.ADTRIAGEU AS T
INNER JOIN dbo.INPACIENT AS INP ON INP.IPCODPACI = T.IPCODPACI
JOIN dbo.INENTIDAD AS INE ON INE.CODENTIDA = INP.CODENTIDA
INNER JOIN Contract.CareGroup AS car ON car.id = INP.GENCAREGROUP
LEFT OUTER JOIN dbo.HCHISPACA AS H ON T.IPCODPACI = H.IPCODPACI AND T.NUMINGRES = H.NUMINGRES
INNER JOIN dbo.INPROFSAL AS P ON T.CODPROSAL = P.CODPROSAL
LEFT JOIN dbo.ADCONTURG AS C ON T.CODCONCEC = C.CODCONCEC
INNER JOIN dbo.INUNIFUNC AS UF ON C.UFUCODIGO = UF.UFUCODIGO
INNER JOIN dbo.INPACIENT ON T.IPCODPACI = dbo.INPACIENT.IPCODPACI
INNER JOIN dbo.HCURGING1 ON H.NUMEFOLIO = dbo.HCURGING1.NUMEFOLIO AND H.NUMINGRES = dbo.HCURGING1.NUMINGRES AND H.IPCODPACI = dbo.HCURGING1.IPCODPACI
LEFT JOIN (
    SELECT 
        IPCODPACI,
        NUMINGRES,
        FECHISPAC AS FECHA1,
        CODPROSAL
    FROM CTE_HCHISPACA
    WHERE RowNum = 2
) AS t2 ON T.IPCODPACI = t2.IPCODPACI AND T.NUMINGRES = t2.NUMINGRES
LEFT JOIN (
    SELECT 
        IPCODPACI,
        NUMINGRES,
        FECHISPAC AS FECHA2,
        pro.NOMMEDICO
    FROM CTE_HCHISPACA his
	join INPROFSAL pro on pro.CODPROSAL = his.CODPROSAL
    WHERE RowNum = 1
) AS t3 ON T.IPCODPACI = t3.IPCODPACI AND T.NUMINGRES = t3.NUMINGRES
JOIN dbo.INPROFSAL AS P2 ON t2.CODPROSAL = P2.CODPROSAL
LEFT JOIN (
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY IPCODPACI, NUMINGRES ORDER BY TRIAFECHA) AS RowNum
    FROM dbo.ADTRIAGEU
) AS FirstTriage ON T.IPCODPACI = FirstTriage.IPCODPACI AND T.NUMINGRES = FirstTriage.NUMINGRES
WHERE C.UFUCODIGO IN ('01', '038', '037')
AND H.TIPHISPAC = 'I'
AND dbo.HCURGING1.FECINIATE > CONVERT(DATETIME, '2015-12-31 00:00:00', 102)
AND FirstTriage.RowNum = 1

  

