-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_TRIAGE_VS_PRIMER_LLAMADO
-- Extracted by Fabric SQL Extractor SPN v3.9.0





CREATE VIEW [Report].[View_HDSAP_TRIAGE_VS_PRIMER_LLAMADO]
AS



WITH CTE_HCHISPACA AS (
    SELECT 
        hc.IPCODPACI,
        hc.NUMINGRES,
        hc.FECHISPAC,
		HC.NUMEFOLIO,
        hc.CODPROSAL,

	
        ROW_NUMBER() OVER (PARTITION BY IPCODPACI, NUMINGRES ORDER BY FECHISPAC) AS RowNum
    FROM 
        HCHISPACA hc

)
SELECT DISTINCT
    cte.IPCODPACI DocumentoPaciente,
	INP.IPPRIAPEL AS 'Primer Apellido',
    INP.IPSEGAPEL AS 'Segundo Apellido',
    INP.IPPRINOMB AS 'Primer Nombre',
    INP.IPSEGNOMB AS 'Segundo Nombre',
    cte.NUMINGRES Ingreso,
    cte.FECHISPAC FechaConsulta,
	TRI.TRIAFECHA FechaTriage,
	HCG.FECHINIHI AS 'LlamadoConsulta(F3)',
	DATEDIFF(MINUTE,TRI.TRIAFECHA,HCG.FECHINIHI) FechaTriageVSPrimerLlamado,
    cte.CODPROSAL CodigoMedico,
    P.NOMMEDICO MedicoConsulta,
	UNI.UFUDESCRI UnidadFuncional,
	ad.IFECHAING FechaIngresoPaciente,
	TRI.TRIAGECLA ClasificacionTriage

FROM 
    CTE_HCHISPACA cte
	INNER JOIN ADTRIAGEU TRI ON TRI.NUMINGRES = CTE.NUMINGRES
	INNER JOIN dbo.HCURGING1 HCG ON HCG.NUMEFOLIO = CTE.NUMEFOLIO AND CTE.NUMINGRES = HCG.NUMINGRES AND CTE.IPCODPACI = HCG.IPCODPACI
    INNER JOIN dbo.INPROFSAL AS P ON cte.CODPROSAL = P.CODPROSAL
	INNER JOIN dbo.INPACIENT AS INP ON INP.IPCODPACI = cte.IPCODPACI
	INNER JOIN ADINGRESO AD ON AD.NUMINGRES = CTE.NUMINGRES
	INNER JOIN dbo.INUNIFUNC uni on uni.UFUCODIGO = AD.UFUINGMED
WHERE 
    cte.RowNum = 1-- AND TRI.IPCODPACI = '83258347';

  

