-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewDailyCensus
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE view [Report].[ViewDailyCensus] as

/*******************************************************************************************************************
Nombre: [Report].[ViewDailyCensus]
Tipo:Procedimiento Vista
Observacion:Informe del censo diario
Profesional: 
Fecha:
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha:30-03-2023
Ovservaciones: Se crea un nuevo cte_ingreso y se cometarean tablas ya que no se utilizan para el reporte, esto con el fin de darle mas
			   rendimiento a la vista en mas de un 99%
-----------------------------------------------------------------------------------------------------------------------------------------
Version 2
Persona que modifico:Nilsson Miguel Galindo lopez
Fecha: 19-05-2023
Observacion: Se modifica el cte_ingreso cambiando la tabla DBO.CHREGESTA por el CTE_CAMAS_OCUPADA para mejorar la velocidad de la consulta ademas tambien se edita
			 el CTE_ESPECIALIDAD_FINAL tambien para mejorar la velocidad, tambien en el cte_ingreso se modifica en la relación con la entidad administradora por codigo
			 esto ultimo solicitado por HOMI en el ticket 9745
***********************************************************************************************************************************/

--------- SCRIPS DEL CENSO DIARIO VALORIZADO--------*/

--CTE PARA IDENTIFICAR LAS CAMAS ACTIVAS EN HOSPITALIZACION
WITH CTE_CAMAS_OCUPADA AS
 (
  SELECT  
   FUN.UFUDESCRI AS 'UNIDAD FUNCIONAL',
   C.IPCODPACI 'IDENTIFICACION',
   C.NUMINGRES 'INGRESO',
   A.NUMCAMHOS 'CAMA',
   A.DESCCAMAS 'NOMBRE CAMA',
   G.DESTIPEST 'TIPO ESTANCIA',
   C.ID  'ID_ESTANCIA', 
   A.CODICAMAS 'ID_CAMAS',
   CEN.NOMCENATE 'CENTRO DE ATENCION',
   A.CODCLAHAB ,
   A.CODCLACAM 
  FROM 
   dbo.CHCAMASHO A
   INNER JOIN DBO.INUNIFUNC FUN ON A.UFUCODIGO =FUN.UFUCODIGO 
   LEFT JOIN dbo.CHREGESTA C ON A.CODICAMAS=C.CODICAMAS AND C.REGESTADO = 1 
   LEFT JOIN dbo.CHTIPESTA G ON G.CODTIPEST=C.CODTIPEST 
   LEFT JOIN DBO.ADCENATEN CEN ON CEN.CODCENATE =A.CODCENATE 
 ),

---CTE PARA IDENTIIFCAR LA PRIMERA FECHA DE HOSPITALIZACION
CTE_PRIMERA_HOSPITALIZACION AS
 (
  SELECT 
   EST.NUMINGRES,
   EST.IPCODPACI,
   EST.FECINIEST 'FECHA INICIAL HOSPITALIZACION'  
  FROM 
   DBO.CHREGESTA EST 
   INNER JOIN (SELECT EST.NUMINGRES ,EST.IPCODPACI ,MIN(EST.ID) ID 
               FROM DBO.CHREGESTA EST
			        INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO =EST.NUMINGRES
			   GROUP BY EST.NUMINGRES ,EST.IPCODPACI) AS G ON G.ID =EST.ID 
 ),

--CTE PARA IDENTIFICAR LA ESPECIALIDAD FINAL
CTE_ESPECIALIDAD_FINAL AS
 (
  SELECT 
   HIS.NUMINGRES,
   HIS.IPCODPACI,
   HIS.CODESPTRA,
   ESP.DESESPECI 'ESPECIALIDAD',
   SAL.CODPROSAL,
   SAL.NOMMEDICO 'PROFESIONAL'  
  FROM 
   CTE_CAMAS_OCUPADA CAM 
   INNER JOIN DBO.HCHISPACA HIS ON CAM.INGRESO=HIS.NUMINGRES AND HIS.ID=(SELECT MAX(H.ID) FROM DBO.HCHISPACA H WHERE HIS.NUMINGRES=H.NUMINGRES) 
   INNER JOIN DBO.INESPECIA ESP ON ESP.CODESPECI=HIS.CODESPTRA 
   INNER JOIN DBO.INPROFSAL SAL ON HIS.CODPROSAL=SAL.CODPROSAL 
 ),
-- GINECOOBSTETRICIA Y PERINATOLOGIA
CTE_ESPECIALIDAD AS
(
    SELECT 
        HIS.NUMINGRES,
        HIS.CODESPTRA
    FROM CTE_CAMAS_OCUPADA  AS CAM
    INNER JOIN dbo.HCHISPACA AS HIS ON HIS.NUMINGRES = CAM.[INGRESO]
    -- sólo traemos las especialidades que nos interesan
    WHERE HIS.CODESPTRA IN ('085', '341', '204')
),

CTE_PIVOT AS
(
    /*  Agrupa por NUMINGRES y calcula dos contadores
        - GINECOOBSTETRICIA: códigos 085 y 341
        - PERINATOLOGIA   : código 204
    */
    SELECT
        NUMINGRES,
        SUM(CASE WHEN CODESPTRA IN ('085','341') THEN 1 ELSE 0 END) AS GINECOOBSTETRICIA,
        SUM(CASE WHEN CODESPTRA = '204'          THEN 1 ELSE 0 END) AS PERINATOLOGIA
    FROM CTE_ESPECIALIDAD
    GROUP BY NUMINGRES
),
--CTE PARA IDENTIFICAR LAS REFERENCIAS
CTE_REFERENCIA AS
 (
  SELECT 
   REF.NUMINGRES,
   REF.AUTO,
   REF.FECSOLICIT,
   REF.FECCONFIR   
  FROM 
   DBO.HCREFCONP AS REF 
   INNER JOIN (SELECT NUMINGRES, MAX(AUTO) ID 
               FROM DBO.HCREFCONP REF
			        INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO =REF.NUMINGRES WHERE ESTADO!=4 GROUP BY NUMINGRES) AS G ON G.NUMINGRES =REF.NUMINGRES AND G.ID =REF.AUTO 
 ),

--CTE PARA IDENTIFICAR EL PLAN DE MANEJO HOSPITALARIO
CTE_PAD AS 
 (
  SELECT 
   PAD.NUMINGRES,
   PAD.ID,
   PAD.FECHAREGISTRO    
  FROM 
   DBO.PADCONTROL AS PAD 
   INNER JOIN (SELECT NUMINGRES, MAX(ID) ID 
               FROM DBO.PADCONTROL PAD  
			        INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO =PAD.NUMINGRES  WHERE ESTADO='1' GROUP BY NUMINGRES ) AS G ON G.NUMINGRES =PAD.NUMINGRES AND G.ID =PAD.ID 
 ),

---------------------*******CTE PARA CONSULTAR LO PENDIENTE DE FACTURAR DEL PACIENTE HOSPITALIZADO ***************------------------------------
CTE_SERVICIOS_PENDIENTES AS
 (
  select  
   RCD.id, RCD.Status,
   RCD.StatusFolioId,RCD.InvoiceCategoryId, RC.AdmissionNumber 'INGRESO',
   ISNULL(RC.PatientCode, 0) AS 'IDENTIFICACION'
  FROM 
   BILLING.REVENUECONTROLDETAIL AS RCD
   INNER JOIN BILLING.REVENUECONTROL AS RC ON RCD.REVENUECONTROLID = RC.ID
   INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES = RC.ADMISSIONNUMBER
   INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO =ING.NUMINGRES 
  ),

CTE_VALOR_ESTANCIA AS
 (
  SELECT 
   RCD.INGRESO,
   RCD.IDENTIFICACION, 
   SUM(ISNULL(DQ.TOTALSALESPRICE,SOD.GrandTotalSalesPrice)) 'DET_ORD_VALOR_TOTAL'
  FROM 
   CTE_SERVICIOS_PENDIENTES  AS RCD
   INNER JOIN BILLING.SERVICEORDERDETAILDISTRIBUTION AS SODD ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1', '3')
   INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD ON SODD.SERVICEORDERDETAILID = SOD.ID
   LEFT JOIN Billing.ServiceOrderDetailSurgical AS DQ ON DQ.ServiceOrderDetailId = SOD.Id AND DQ.OnlyMedicalFees = '0'
  WHERE 
   SOD.IsDelete ='0'
  GROUP 
   BY RCD.INGRESO,RCD.IDENTIFICACION
 ),

--CTE PARA IDENTIFICAR LA FECHA DE ALTA MEDICA
CTE_ALTA_MEDICA AS 
 (
  SELECT 
   EGR.NUMINGRES,
   EGR.IPCODPACI 
  FROM 
   DBO.HCREGEGRE AS EGR 
   INNER JOIN (SELECT NUMINGRES, MAX(EGR.FECALTPAC) FECALTPAC 
               FROM DBO.HCREGEGRE EGR 
			        INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO =EGR.NUMINGRES 
			   GROUP BY NUMINGRES ) AS G ON G.NUMINGRES =EGR.NUMINGRES AND G.FECALTPAC =EGR.FECALTPAC 
 ),

--IN V1
CTE_INGRESO AS 
 (
  SELECT 
   ING.NUMINGRES,
   ING.IFECHAING,
   ING.IAUTORIZA AS [NUMERO AUTORIZACIÓN], 
   ING.IOBSERVAC AS [OBSERVACIONES],
   HA.Name AS ENTIDAD,
   CASE HA.ENTITYTYPE 
    WHEN 1 THEN 'EPS CONTRIBUTIVO' 
	WHEN 2 THEN 'EPS SUBSIDIADO' 
	WHEN 3 THEN 'ET VINCULADO MUNICIPIO' 
	WHEN 4 THEN 'ET VINCULADOS DAPARTAMENTO'
	WHEN 5 THEN 'ARL RIESGO LABORALES' 
	WHEN 6 THEN 'MP MEDICINA PREPAGADA' 
	WHEN 7 THEN 'IPS PRIVADA' 
	WHEN 8 THEN 'IPS PUBLICA' 
	WHEN 9 THEN 'REGIMEN ESPECIAL' 
	WHEN 10 THEN 'ACCIDENTE DE TRANSITO'
	WHEN 11 THEN 'FOSYGA' 
	WHEN 12 THEN 'OTROS' END AS [REGIMEN],
   RTRIM(Q.CODDIAGNO) + ' - ' + RTRIM(Q.NOMDIAGNO) AS [DIAGNOSTICO PRINCIPAL]
  FROM
   CTE_CAMAS_OCUPADA EST 
   INNER JOIN DBO.ADINGRESO ING ON EST.INGRESO=ING.NUMINGRES 
   INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON  ING.GENCONENTITY=HA.ID 
   LEFT JOIN INDIAGNOP DIA ON ING.NUMINGRES=DIA.NUMINGRES AND DIA.CODDIAPRI=1 
   LEFT JOIN dbo.INDIAGNOS Q ON DIA.CODDIAGNO=Q.CODDIAGNO
  GROUP BY 
   ING.NUMINGRES,
   ING.IFECHAING,
   ING.IAUTORIZA,
   ING.IOBSERVAC,
   HA.Name,HA.ENTITYTYPE,
   Q.CODDIAGNO,Q.NOMDIAGNO
 )

SELECT 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 CAM.[CENTRO DE ATENCION],
 CAM.ID_CAMAS AS [CODIGO CAMA],
 CAM.CAMA [CAMA],
 CAM.[NOMBRE CAMA],
 EST.NUMINGRES 'INGRESO',
 CAST(EST.FECINIEST as date) [FECHA INGRESO],
 DATEDIFF(DAY,EST.FECINIEST,GETDATE()) [DIAS TRANSCURRIDOS],
 TE.DESTIPEST AS [TIPO DE ESTANCIA],
 CAM.[UNIDAD FUNCIONAL] 'SERVICIO',
 CASE CAM.CODCLAHAB 
  WHEN '1'  THEN 'SALA OBSERVACION' 
  WHEN '2'  THEN 'SALA PROCEDIMIENTO' 
  WHEN '3'  THEN 'SALA RECUPERACION' 
  WHEN '4'  THEN 'HABITACION 1 CAMA' 
  WHEN '5'  THEN 'HABITACION 2 CAMAS'  
  WHEN '6'  THEN 'HABITACION 3 CAMAS'  
  WHEN '7'  THEN 'HABITACION 4 CAMAS'  
  WHEN '8'  THEN 'SUITE' 
  WHEN '9'  THEN 'HAB.ESPECIAL' 
  WHEN '10' THEN 'UCI'  
  WHEN '11' THEN 'OTRO' 
 END AS [CLASE DE HABITACION], 
 CASE CAM.CODCLACAM 
  WHEN '1' THEN UPPER('ObservacionUrgencias')
  WHEN '2' THEN UPPER('Recuperacion Post Qx')  
  WHEN '3' THEN 'HOSPITALARIA' END AS [CLASE DE CAMA],
 CASE PAC.IPTIPODOC 
  WHEN '1'  THEN 'CC'
  WHEN '2'  THEN 'CE'
  WHEN '3'  THEN 'TI'
  WHEN '4'  THEN 'RC'
  WHEN '5'  THEN 'PA'
  WHEN '6'  THEN 'AS'
  WHEN '7'  THEN 'MS'
  WHEN '8'  THEN 'NU'
  WHEN '9'  THEN 'NV'
  WHEN '10' THEN 'CD'
  WHEN '11' THEN 'SC'
  WHEN '12' THEN 'PE' 
  WHEN '13' THEN 'PT'
  WHEN '14' THEN 'DE'
  WHEN '15' THEN 'SI' 
 END AS [TIPO DOCUMENTO],
 PAC.IPCODPACI AS [IDENTIFICACION], 
 PAC.IPNOMCOMP AS [NOMBRE DEL PACIENTE],
 PAC.IPFECNACI FechaNacimiento,
 CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END AS 'SEXO',
 CAST(PAC.IPFECNACI AS DATE) 'FECHA NACIMIENTO' ,
 CAST((datediff(m, PAC.IPFECNACI, EST.FECINIEST)/12) as varchar) + ' Años ' + CAST((DATEDIFF(m, PAC.IPFECNACI, EST.FECINIEST)%12) as varchar) + ' Meses' as EDAD,
 PAC.IPDIRECCI AS DIRECCION, PAC.IPTELEFON AS TELEFONO, 
 PAC.IPTELMOVI AS MOVIL,
 ING.ENTIDAD,
 ING.REGIMEN,
 NV.NIVDESCRI AS [CATEGORIA],
 ING.[DIAGNOSTICO PRINCIPAL],
 RTRIM(ISNULL(Prof.CODPROSAL,ESP.CODPROSAL)) + ' - ' + RTRIM(ISNULL(Prof.NOMMEDICO,ESP.PROFESIONAL)) 'MEDICO',
 RTRIM(ISNULL(K.DESESPECI,ESP.ESPECIALIDAD)) AS 'ESPECIALIDAD',
 ING.[NUMERO AUTORIZACIÓN], 
 ING.[OBSERVACIONES],
 CASE WHEN REF.NUMINGRES IS NULL THEN 'NO' ELSE 'SI' END AS REFERENCIA, 
 REF.FECSOLICIT AS [SOLICITUD REFERENCIA],
 CASE WHEN PAD.NUMINGRES IS NULL THEN 'NO' ELSE 'SI' END AS PAD,PAD.FECHAREGISTRO AS [FECHA PAD],
 CASE WHEN  ALT.NUMINGRES IS NULL THEN '1 - Pacientes en la Unidad' ELSE '2 - Pacientes Con Salida' END AS 'ESTADO',
 ING.IFECHAING as 'FECHA INGRESO ADMISION',
 HOS.[FECHA INICIAL HOSPITALIZACION],
 EST.FECINIEST 'FECHA ASIGNACION UNIDAD',
 CAM.[TIPO ESTANCIA]  [ESTANCIA] ,
 DATEDIFF(DAY,HOS.[FECHA INICIAL HOSPITALIZACION], GETDATE()) 'DIAS DE HOSPITALIZACION',
 DATEDIFF(DAY,EST.FECINIEST,GETDATE()) 'DIAS EN LA UNIDAD',
 ISNULL(VAL.DET_ORD_VALOR_TOTAL,0) 'VALOR',
 1 as 'CANTIDAD',
 CAST(EST.FECINIEST AS date) AS 'FECHA BUSQUEDA',
 YEAR(EST.FECINIEST) AS 'AÑO BUSQUEDA',
 MONTH(EST.FECINIEST) AS 'MES BUSQUEDA',
 CONCAT(FORMAT(MONTH(EST.FECINIEST), '00') ,' - ', 
	   CASE MONTH(EST.FECINIEST) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL,
     ISNULL(p.GINECOOBSTETRICIA, 0) AS GINECOOBSTETRICIA,
    ISNULL(p.PERINATOLOGIA,    0) AS PERINATOLOGIA
FROM  
 DBO.CHREGESTA EST
 INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.ID_ESTANCIA =EST.ID AND CAM.INGRESO =EST.NUMINGRES 
 LEFT JOIN CTE_INGRESO AS ING ON ING.NUMINGRES =EST.NUMINGRES 
 INNER JOIN CTE_PRIMERA_HOSPITALIZACION HOS ON HOS.NUMINGRES =EST.NUMINGRES 
 INNER JOIN dbo.INPacient PAC ON EST.IPCODPACI=PAC.IPCODPACI 
 INNER JOIN dbo.CHTIPESTA AS TE ON TE.CODTIPEST = EST.CODTIPEST
 INNER JOIN Dbo.ADNIVELES NV ON PAC.NIVCODIGO=NV.NIVCODIGO
 LEFT JOIN dbo.INESPECIA K ON EST.CODESPECI = K.CODESPECI
 LEFT  JOIN dbo.INPROFSAL Prof ON EST.CODPROSAL = Prof.CODPROSAL
 LEFT JOIN CTE_ESPECIALIDAD_FINAL ESP ON ESP.NUMINGRES =EST.NUMINGRES
 LEFT JOIN CTE_ALTA_MEDICA AS ALT ON ALT.NUMINGRES =EST.NUMINGRES 
 LEFT JOIN CTE_REFERENCIA REF ON REF.NUMINGRES=ALT.NUMINGRES
 LEFT JOIN CTE_PAD PAD ON PAD.NUMINGRES=ALT.NUMINGRES
 LEFT JOIN CTE_VALOR_ESTANCIA AS VAL ON VAL.INGRESO = EST.NUMINGRES 
 LEFT JOIN CTE_PIVOT     AS p ON p.NUMINGRES = EST.NUMINGRES;
