-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewTerapiasHospitalizados
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE view [Report].[ViewTerapiasHospitalizados] as


/*******************************************************************************************************************
Persona que modifico: Amira Esperanza Gil Meneses
Observacion: Se adiciona codigo y descripción de la cama en el CTE_ORDENES_TERAPIAS
Fecha: 15-11-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico:
Fecha:
Ovservaciones:
--------------------------------------
Version 3
Persona que modifico:
Fecha:
Ovservaciones:
***********************************************************************************************************************************/

WITH

CTE_ORDENES_TERAPIAS AS
(
SELECT 
ORD.NUMINGRES,
ORD.CODSERIPS,
ORD.CODDIAGNO,
ORD.FECORDMED,
UNF.UFUDESCRI,
ORD.UFUCODIGO,
CUPT.DESSERIPS,
EST.CODICAMAS,
CAM.DESCCAMAS,
SUM(ORD.CANSERIPS) AS CANTIDAD
FROM 
DBO.HCORDPRON ORD INNER JOIN
dbo.CHREGESTA EST ON ORD.NUMINGRES=EST.NUMINGRES AND EST.FECFINEST='1900-01-01 00:00:00.000'
INNER JOIN dbo.INCUPSIPS CUPT ON ORD.CODSERIPS=CUPT.CODSERIPS AND CUPT.TIPSERTER=1
INNER JOIN dbo.INUNIFUNC UNF ON ORD.UFUCODIGO=UNF.UFUCODIGO
INNER JOIN dbo.CHCAMASHO CAM ON EST.CODICAMAS=CAM.CODICAMAS
GROUP BY ORD.NUMINGRES, ORD.CODSERIPS, ORD.CODDIAGNO,ORD.UFUCODIGO, ORD.FECORDMED, CUPT.DESSERIPS,EST.CODICAMAS,CAM.DESCCAMAS,UNF.UFUDESCRI
),

CTE_NOTAS_TERAPIAS AS
(
SELECT 
TER.NUMINGRES,
TER.CODSERIPS,
COUNT(TER.CODCONSEC) AS CANTIDAD
FROM 
dbo.HCPROCTER TER INNER JOIN
dbo.CHREGESTA EST ON TER.NUMINGRES=EST.NUMINGRES AND EST.FECFINEST='1900-01-01 00:00:00.000'
GROUP BY TER.NUMINGRES,TER.CODSERIPS
),

CTE_ULTIMA_SOLICITUD_ORDEN AS
(
SELECT
ORD.IPCODPACI,
ORD.NUMINGRES,
ORD.CODSERIPS,
ORD.FECORDMED,
ORD.CODCENATE,
ORD.CODPROSAL,
PRO.NOMMEDICO,
ORD.NUMEFOLIO,
CUPS.DESSERIPS
FROM DBO.HCORDPRON ORD INNER JOIN
DBO.INPROFSAL PRO ON ORD.CODPROSAL=PRO.CODPROSAL AND ORD.[AUTO]=(SELECT MAX(O.[AUTO]) FROM DBO.HCORDPRON O WHERE ORD.NUMINGRES=O.NUMINGRES AND ORD.CODSERIPS=O.CODSERIPS) INNER JOIN
DBO.INCUPSIPS AS CUPS ON ORD.CODSERIPS=CUPS.CODSERIPS
),
CTE_ULTIMA_NOTA_TERAPIA AS
(
SELECT 
NT.NUMINGRES,
NT.CODSERIPS,
NT.FECREGSIS,
NT.CODPROSAL,
PRO.NOMMEDICO,
CUPS.DESSERIPS
FROM 
dbo.HCPROCTER NT INNER JOIN
DBO.INPROFSAL PRO ON NT.CODPROSAL=PRO.CODPROSAL AND NT.CODCONSEC=(SELECT MAX(N.CODCONSEC) FROM dbo.HCPROCTER N WHERE NT.NUMINGRES=N.NUMINGRES AND NT.CODSERIPS=N.CODSERIPS) INNER JOIN
DBO.INCUPSIPS AS CUPS ON NT.CODSERIPS=CUPS.CODSERIPS
),
CTE_INICIAL_NOTA_TERAPIA AS
(
SELECT 
NT.NUMINGRES,
NT.CODSERIPS,
NT.FECREGSIS,
NT.CODPROSAL, 
PRO.NOMMEDICO
FROM 
dbo.HCPROCTER NT INNER JOIN
DBO.INPROFSAL PRO ON NT.CODPROSAL=PRO.CODPROSAL AND NT.CODCONSEC=(SELECT MIN(N.CODCONSEC) FROM dbo.HCPROCTER N WHERE NT.NUMINGRES=N.NUMINGRES AND NT.CODSERIPS=N.CODSERIPS) INNER JOIN
DBO.INCUPSIPS AS CUPS ON NT.CODSERIPS=CUPS.CODSERIPS
)


SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CEN.NOMCENATE AS [CENTRO DE ATENCION],
IDE.SIGLA AS [TIPO DE IDENTIFICACION],
PAC.IPCODPACI AS IDENTIFICACION,
PAC.IPNOMCOMP AS [NOMBRE PACIENTE],
CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
DATEDIFF(YEAR,PAC.IPFECNACI,GETDATE()) AS [EDAD],
CASE PAC.IPSEXOPAC WHEN '1' THEN 'MASCULINO'
				   WHEN '2' THEN 'FEMENINO' END AS [SEXO],
EA.NAME AS [ENTIDAD ADMINISTRADORA],
GA.NAME [GRUPO ATENCION],
ORDT.NUMINGRES AS [NUMERO DE INGRESO],
USO.NUMEFOLIO AS [FOLIO],
ORDT.CODICAMAS AS [CODIGO DE CAMA],
ORDT.DESCCAMAS AS [DESCRIPCION CAMA],
ORDT.CODSERIPS AS [CODIGO CUPS],
USO.DESSERIPS AS [TERAPIA SOLICITADA],
USO.CODPROSAL AS [CODIGO PROFESIONAL DE LA ORDEN],
USO.NOMMEDICO AS [PROFESIONAL DE LA ORDEN],
ORDT.FECORDMED AS [FECHA PRIMER ORDEN],
USO.FECORDMED AS [FECHA ULTIMA ORDEN],
ORDT.CANTIDAD AS [CANTIDAD DE ORDENES],
ISNULL(NT.CANTIDAD,0) AS [CATIDAD REALIZADA],
ISNULL(ORDT.CANTIDAD-NT.CANTIDAD,ORDT.CANTIDAD) AS [CANTIDAD FALTANTE],
CINT.FECREGSIS AS [FECHA PRIMERA TERAPIA],
CINT.CODPROSAL AS [COD PROFESIONAL PRIMER TERAPIA],
CINT.NOMMEDICO AS [PROFESIONAL REALIZA PRIMER TERAPIA],
UNT.FECREGSIS AS [FECHA ULTIMA TERAPIA],
UNT.CODPROSAL AS [CDIGO PROFESIONAL TERAPIA],
UNT.NOMMEDICO AS [PROFESIONAL REALIZO ULTIMA TERAPIA],
ORDT.CODDIAGNO AS [CIE 10],
ORDT.DESSERIPS AS [DESCRIPCION],
ORDT.UFUCODIGO AS [COD UNIDAD FUNCIONAL],
ORDT.UFUDESCRI AS [UNIDAD FUNCIONAL],
1 as 'CANTIDAD',
  CAST(ORDT.FECORDMED AS date) AS 'FECHA BUSQUEDA',
  YEAR(ORDT.FECORDMED) AS 'AÑO BUSQUEDA',
  MONTH(ORDT.FECORDMED) AS 'MES BUSQUEDA',
  CONCAT(FORMAT(MONTH(ORDT.FECORDMED), '00') ,' - ', 
	   CASE MONTH(ORDT.FECORDMED) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
CTE_ORDENES_TERAPIAS ORDT INNER JOIN
CTE_ULTIMA_SOLICITUD_ORDEN USO ON ORDT.NUMINGRES=USO.NUMINGRES AND ORDT.CODSERIPS=USO.CODSERIPS INNER JOIN
dbo.INPACIENT PAC ON USO.IPCODPACI=PAC.IPCODPACI INNER JOIN
dbo.ADTIPOIDENTIFICA IDE ON PAC.IPTIPODOC=IDE.CODIGO INNER JOIN
DBO.ADCENATEN AS CEN ON USO.CODCENATE = CEN.CODCENATE INNER JOIN
CONTRACT.HEALTHADMINISTRATOR EA ON PAC.GENCONENTITY=EA.Id INNER JOIN
CONTRACT.CAREGROUP GA ON PAC.GENCAREGROUP=GA.Id LEFT JOIN
CTE_NOTAS_TERAPIAS NT ON ORDT.NUMINGRES=NT.NUMINGRES AND ORDT.CODSERIPS=NT.CODSERIPS LEFT JOIN
CTE_ULTIMA_NOTA_TERAPIA UNT ON ORDT.NUMINGRES=UNT.NUMINGRES AND ORDT.CODSERIPS=UNT.CODSERIPS LEFT JOIN
CTE_INICIAL_NOTA_TERAPIA CINT ON ORDT.NUMINGRES=CINT.NUMINGRES AND ORDT.CODSERIPS=CINT.CODSERIPS
