-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_POSTOPERATORIO
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[View_HDSAP_PostOperatorio]
AS

SELECT  Q.IPCODPACI AS IdPaciente,  RTRIM(P.IPNOMCOMP) + CONCAT(' (', P.IPTELEFON + ' - ', P.IPTELMOVI,')') AS NombrePaciente, Q.FECHORINI AS FechaQxInicio, 
		CASE WHEN Q.URGECIRUG=1 THEN 'URG' WHEN Q.URGECIRUG=0 THEN 'PROG' ELSE CAST(Q.URGECIRUG AS varchar) END TipoQx, 
		QX.CODSERIPS AS CUPS_QX, IC.DESSERIPS AS DescripcionProcedimiento,	
		CASE WHEN QX.QXPRINCIP=1 THEN 'SI' ELSE 'NO' END AS ProcPpal,  
		PS.CODPROSAL AS CodMD_QX, PS.NOMMEDICO AS NombreMD_QX, ES.CODESPECI AS CodEspQx, ES.DESESPECI AS EspecialidadQx,
		UF.UFUDESCRI AS DescripcionUF_QX, 		
		HC2.Destino, HC2.UltimaUF, HC2.FechaUF, ICo.CupsIC, ICo.Interconsulta, ICo.ObserInterconsulta,
		AG.FechaCita, AG.TipoCita, AG.EspecialistaCita, AG.EspecialidadCita, AG.EstadoCita,
		AG.ObservacionCita, AG.ObserCancela, GrA.Name AS GrupoAtencion, EntA.Name AS 'Entidad'		--03/10/2019 ADICIONA LAS DOS ULTIMAS COLUMNAS
	FROM dbo.HCQXINFOR AS Q
		INNER JOIN dbo.HCQXREALI AS QX ON Q.NUMEFOLIO=QX.NUMEFOLIO AND Q.IPCODPACI=QX.IPCODPACI
		INNER JOIN dbo.HCHISPACA AS HC ON HC.IPCODPACI=Q.IPCODPACI AND HC.NUMEFOLIO=Q.NUMEFOLIO
		INNER JOIN dbo.INPACIENT AS P ON Q.IPCODPACI=P.IPCODPACI
		INNER JOIN dbo.INCUPSIPS AS IC ON QX.CODSERIPS=IC.CODSERIPS
		INNER JOIN dbo.INPROFSAL AS PS ON Q.CODPROSAL=PS.CODPROSAL
		INNER JOIN dbo.INESPECIA AS ES ON PS.CODESPEC1=ES.CODESPECI
		INNER JOIN dbo.INUNIFUNC AS UF ON Q.UFUCODIGO=UF.UFUCODIGO
		INNER JOIN dbo.ADINGRESO AS I ON Q.NUMINGRES=I.NUMINGRES
        LEFT JOIN Contract.CareGroup AS GrA ON I.GENCAREGROUP = GrA.Id 
		LEFT JOIN Contract.HealthAdministrator AS EntA ON I.GENCONENTITY = EntA.Id					
		OUTER APPLY (SELECT TOP 1 HC2.FECHISPAC AS FechaUF, 
							CASE HC2.INDICAPAC WHEN '1' THEN 'Trasladar a Urgencias' WHEN '2' THEN 'Trasladar a Observacion' WHEN '3' THEN 'Trasladar a Hospitalizacion'
								WHEN '4' THEN 'Trasladar a UCI' WHEN '5' THEN 'Trasladar a UCI' WHEN '6' THEN 'Trasladar a UCI'
								WHEN '7' THEN 'Trasladar a Consulta Externa' WHEN '8' THEN 'Trasladar a Cirugia' WHEN '9' THEN 'Hospitalizacion en Casa'
								WHEN '10' THEN 'Referencia' WHEN '11' THEN 'Morgue' WHEN '12' THEN 'Salida'
								WHEN '13' THEN 'Continua en la Unidad' WHEN '15' THEN 'Retiro Voluntario' WHEN '16' THEN 'Fuga' END AS Destino,
								UF2.UFUDESCRI AS UltimaUF
						FROM dbo.HCHISPACA AS HC2
							INNER JOIN dbo.INUNIFUNC AS UF2 ON HC2.UFUCODIGO=UF2.UFUCODIGO 
						WHERE HC2.NUMINGRES=Q.NUMINGRES
						ORDER BY HC2.FECHISPAC DESC
					) AS HC2
		OUTER APPLY (SELECT TOP 1 I.CODSERIPS AS CupsIC, I.OBSSERIPS AS ObserInterconsulta, IC.DESSERIPS AS Interconsulta
						FROM dbo.HCORDINTE AS I
							INNER JOIN dbo.INCUPSIPS AS IC ON I.CODSERIPS=IC.CODSERIPS
						WHERE I.NUMINGRES=Q.NUMINGRES
							AND ((ES.CODESPECI='044' AND I.CODSERIPS LIKE '890%' ) OR (ES.CODESPECI='480' AND I.CODSERIPS LIKE '890%' ) OR (ES.CODESPECI='179' AND I.CODSERIPS LIKE '890%' )
									OR (ES.CODESPECI='131' AND I.CODSERIPS LIKE '890%' ) OR (ES.CODESPECI='085' AND I.CODSERIPS LIKE '890%' ) OR (ES.CODESPECI='109' AND I.CODSERIPS LIKE '890%' ))
								--FALTA OTORRINO
							AND I.OBSSERIPS IS NOT NULL
						ORDER BY I.FECORDMED DESC
					) AS ICo
		OUTER APPLY (SELECT TOP 1 AG.FECHORAIN AS FechaCita, PS2.NOMMEDICO AS EspecialistaCita, 
							CASE AG.CODTIPCIT WHEN '0' THEN 'PrimeraVez' WHEN '1' THEN 'Control' WHEN '2' THEN 'PostOperatorio'
								ELSE AG.CODTIPCIT END AS TipoCita,
							ES2.DESESPECI AS EspecialidadCita,
							CASE AG.CODESTCIT WHEN 0 THEN 'Asignada' WHEN 1 THEN 'Cumplida' WHEN 2 THEN 'Incumplida' 
								WHEN 3 THEN 'PreAsignada'	WHEN 4 THEN 'Cancelada' END AS EstadoCita, AG.OBSERVACI AS ObservacionCita,
							AG.OBSCAUCAN AS ObserCancela
						FROM dbo.AGASICITA AS AG
							INNER JOIN dbo.INPROFSAL AS PS2 ON AG.CODPROSAL=PS2.CODPROSAL
							INNER JOIN dbo.INESPECIA AS ES2 ON AG.CODESPECI=ES2.CODESPECI
						WHERE Q.IPCODPACI=AG.IPCODPACI
							AND PS.CODESPEC1=AG.CODESPECI
							AND CAST(AG.FECHORAIN AS DATE)>CAST(Q.FECHORFIN AS date)
							--AND AG.CODESTCIT<>4		--01/10/2019
						ORDER BY AG.FECHORAIN DESC		--01/10/2019
					) AS AG
	WHERE HC.ESTAFOLIO=1 
		AND QX.QXPRINCIP=1
		AND UF.UFUCODIGO IN ('191','193')
                        

