-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_CITASENESPERA
-- Extracted by Fabric SQL Extractor SPN v3.9.0





CREATE VIEW [Report].[View_HDSAP_CITASENESPERA]
AS

 SELECT CE.CODAUTONU, 
            CE.FECREGSIS AS FechaRegistroCitasEE, 
            TRY_CAST(CE.FECHACITA AS DATETIME) AS FechaDeseadaCitasEE, 
            PA.IPNOMCOMP AS Paciente, 
            PA.IPFECNACI AS FechaNacimiento, 
            CE.IPCODPACI AS Identificacion, 
            EN.NOMENTIDA AS Entidad, 
            PA.IPTELEFON AS Tel1, 
            PA.IPTELMOVI AS Tel2, 
            PA.IPDIRECCI AS Direccion, 
			MUN.MUNNOMBRE AS Municipio,
            ES.DESESPECI AS Especialidad, 
            AGAC.DESACTMED AS Actividad, 
            PS.NOMMEDICO AS Médico, 
            CE.OBSERVACI AS Observaciones,
            CASE
                WHEN(TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS     DATETIME)) IS NULL
                THEN NULL
                WHEN TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS DATETIME) < = '17530101'
                THEN NULL
                WHEN TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS DATETIME) >= '99991231'
                THEN NULL
                ELSE TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS DATETIME)
            END AS FechaVenceAutorizacion,
            CASE CE.ESTADO
                WHEN 1
                THEN 'En Espera'
                WHEN 2
                THEN 'Asignada'
                WHEN 3
                THEN 'Cancelada'
            END AS EstadoCitaEnEspera, 
            RTRIM(US.NOMUSUARI) AS Usuario, 
            DATEDIFF(DAY, CE.FECREGSIS, SYSDATETIME()) AS DiasEnEspera,
            CASE
                WHEN(TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS     DATETIME)) IS NULL
                THEN 0
                WHEN TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS DATETIME) < = '17530101'
                THEN 0
                WHEN TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS DATETIME) >= '99991231'
                THEN 0
                ELSE DATEDIFF(DAY, SYSDATETIME(), COALESCE(TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS DATETIME), SYSDATETIME()))
            END AS DiasVencimientoAut,
            CASE
                WHEN(TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS     DATETIME)) < CE.FECREGSIS
                THEN 'SI, FECHA AUTORIZACION'
                WHEN(TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS DATETIME)) IS NULL
                THEN 'SI, FECHA AUTORIZACION'
                WHEN DATEADD(DAY, 1, TRY_CAST(CE.FECHACITA AS DATETIME)) < CE.FECREGSIS
                THEN 'SI, FECHA DESEADA'
                WHEN DATEDIFF(DAY, CE.FECREGSIS, COALESCE(TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS DATETIME), SYSDATETIME())) < 30
                THEN 'SI, FECHA AUTORIZACION CORTA'
                ELSE 'NO'
            END AS InconsistenciaProbable, 
            DATENAME(MONTH, CE.FECREGSIS) + '/' + CAST(YEAR(CE.FECREGSIS) AS VARCHAR) AS MesRegistroCitasEE,
            CASE
                WHEN(TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS     DATETIME)) IS NULL
                THEN 0
                WHEN TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS DATETIME) < = '17530101'
                THEN 0
                WHEN TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS DATETIME) >= '99991231'
                THEN 0
                ELSE DATEDIFF(DAY, CE.FECREGSIS, COALESCE(TRY_CAST(REPLACE(REPLACE((SUBSTRING(CE.OBSERVACI, CHARINDEX(CHAR(10), CE.OBSERVACI), 12)), CHAR(10), ''), CHAR(13), '') AS DATETIME), SYSDATETIME()))
            END AS DiasRegistVsVencimientoAut, 
            ROW_NUMBER() OVER(PARTITION BY CE.IPCODPACI, 
                                           CE.CODESPECI
            ORDER BY CE.FECREGSIS) AS ConsecPcteEspec 

     FROM(((((AGCITAESP AS CE
              INNER JOIN INPACIENT AS PA ON CE.IPCODPACI = PA.IPCODPACI)
              INNER JOIN SEGusuaru AS US ON CE.CODUSUASI = US.CODUSUARI)
              INNER JOIN INESPECIA AS ES ON CE.CODESPECI = ES.CODESPECI)
              INNER JOIN INENTIDAD AS EN ON PA.CODENTIDA = EN.CODENTIDA)
              INNER JOIN AGACTIMED AS AGAC ON CE.CODACTMED = AGAC.CODACTMED)
              LEFT OUTER JOIN INPROFSAL AS PS ON CE.CODPROSAL = PS.CODPROSAL
			  INNER JOIN dbo.INUBICACI AS UBI ON PA.AUUBICACI=UBI.AUUBICACI
			  INNER JOIN dbo.INMUNICIP AS MUN ON UBI.DEPMUNCOD=MUN.DEPMUNCOD
     WHERE CE.ESTADO = 1;
