-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_CENSO_NUEVA_EPS
-- Extracted by Fabric SQL Extractor SPN v3.9.0








CREATE VIEW [Report].[View_HDSAP_CENSO_NUEVA_EPS]
AS



WITH CTE_CAMAS_OCUPADA AS
 (
  SELECT  
   FUN.UFUDESCRI AS 'UNIDAD FUNCIONAL',
   C.IPCODPACI 'IDENTIFICACION',
   C.NUMINGRES 'INGRESO',
   A.NUMCAMHOS 'CAMA',
   A.DESCCAMAS 'NOMBRE CAMA',
   G.DESTIPEST 'TIPO ESTANCIA',
   C.ID  'ID_ESTANCIA', 
   A.CODICAMAS 'ID_CAMAS',
   CEN.NOMCENATE 'CENTRO DE ATENCION',
   A.CODCLAHAB ,
   A.CODCLACAM 
  FROM 
   dbo.CHCAMASHO A
   INNER JOIN DBO.INUNIFUNC FUN ON A.UFUCODIGO =FUN.UFUCODIGO 
   LEFT JOIN dbo.CHREGESTA C ON A.CODICAMAS=C.CODICAMAS AND C.REGESTADO = 1 
   LEFT JOIN dbo.CHTIPESTA G ON G.CODTIPEST=C.CODTIPEST 
   LEFT JOIN DBO.ADCENATEN CEN ON CEN.CODCENATE =A.CODCENATE 
 ),

---CTE PARA IDENTIIFCAR LA PRIMERA FECHA DE HOSPITALIZACION
CTE_PRIMERA_HOSPITALIZACION AS
 (
  SELECT 
   EST.NUMINGRES,
   EST.IPCODPACI,
   EST.FECINIEST 'FECHA INICIAL HOSPITALIZACION'  
  FROM 
   DBO.CHREGESTA EST 
   INNER JOIN (SELECT EST.NUMINGRES ,EST.IPCODPACI ,MIN(EST.ID) ID 
               FROM DBO.CHREGESTA EST
			        INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO =EST.NUMINGRES
			   GROUP BY EST.NUMINGRES ,EST.IPCODPACI) AS G ON G.ID =EST.ID 
 ),

--CTE PARA IDENTIFICAR LA ESPECIALIDAD FINAL
CTE_ESPECIALIDAD_FINAL AS
 (
  SELECT 
   HIS.NUMINGRES,
   HIS.IPCODPACI,
   HIS.CODESPTRA,
   ESP.DESESPECI 'ESPECIALIDAD',
   SAL.CODPROSAL,
   SAL.NOMMEDICO 'PROFESIONAL'  
  FROM 
   CTE_CAMAS_OCUPADA CAM 
   INNER JOIN DBO.HCHISPACA HIS ON CAM.INGRESO=HIS.NUMINGRES AND HIS.ID=(SELECT MAX(H.ID) FROM DBO.HCHISPACA H WHERE HIS.NUMINGRES=H.NUMINGRES) 
   INNER JOIN DBO.INESPECIA ESP ON ESP.CODESPECI=HIS.CODESPTRA 
   INNER JOIN DBO.INPROFSAL SAL ON HIS.CODPROSAL=SAL.CODPROSAL 
 ),

--CTE PARA IDENTIFICAR LAS REFERENCIAS
CTE_REFERENCIA AS
 (
  SELECT 
   REF.NUMINGRES,
   REF.AUTO,
   REF.FECSOLICIT,
   REF.FECCONFIR   
  FROM 
   DBO.HCREFCONP AS REF 
   INNER JOIN (SELECT NUMINGRES, MAX(AUTO) ID 
               FROM DBO.HCREFCONP REF
			        INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO =REF.NUMINGRES WHERE ESTADO!=4 GROUP BY NUMINGRES) AS G ON G.NUMINGRES =REF.NUMINGRES AND G.ID =REF.AUTO 
 ),

--CTE PARA IDENTIFICAR EL PLAN DE MANEJO HOSPITALARIO
CTE_PAD AS 
 (
  SELECT 
   PAD.NUMINGRES,
   PAD.ID,
   PAD.FECHAREGISTRO    
  FROM 
   DBO.PADCONTROL AS PAD 
   INNER JOIN (SELECT NUMINGRES, MAX(ID) ID 
               FROM DBO.PADCONTROL PAD  
			        INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO =PAD.NUMINGRES  WHERE ESTADO='1' GROUP BY NUMINGRES ) AS G ON G.NUMINGRES =PAD.NUMINGRES AND G.ID =PAD.ID 
 ),

---------------------*******CTE PARA CONSULTAR LO PENDIENTE DE FACTURAR DEL PACIENTE HOSPITALIZADO ***************------------------------------
CTE_SERVICIOS_PENDIENTES AS
 (
  select  
   RCD.id, RCD.Status,
   RCD.StatusFolioId,RCD.InvoiceCategoryId, RC.AdmissionNumber 'INGRESO',
   ISNULL(RC.PatientCode, 0) AS 'IDENTIFICACION'
  FROM 
   BILLING.REVENUECONTROLDETAIL AS RCD
   INNER JOIN BILLING.REVENUECONTROL AS RC ON RCD.REVENUECONTROLID = RC.ID
   INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES = RC.ADMISSIONNUMBER
   INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO =ING.NUMINGRES 
  ),

CTE_VALOR_ESTANCIA AS
 (
  SELECT 
   RCD.INGRESO,
   RCD.IDENTIFICACION, 
   SUM(ISNULL(DQ.TOTALSALESPRICE,SOD.GrandTotalSalesPrice)) 'DET_ORD_VALOR_TOTAL'
  FROM 
   CTE_SERVICIOS_PENDIENTES  AS RCD
   INNER JOIN BILLING.SERVICEORDERDETAILDISTRIBUTION AS SODD ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1', '3')
   INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD ON SODD.SERVICEORDERDETAILID = SOD.ID
   LEFT JOIN Billing.ServiceOrderDetailSurgical AS DQ ON DQ.ServiceOrderDetailId = SOD.Id AND DQ.OnlyMedicalFees = '0'
  WHERE 
   SOD.IsDelete ='0'
  GROUP 
   BY RCD.INGRESO,RCD.IDENTIFICACION
 ),

--CTE PARA IDENTIFICAR LA FECHA DE ALTA MEDICA
CTE_ALTA_MEDICA AS 
 (
  SELECT 
   EGR.NUMINGRES,
   EGR.IPCODPACI 
  FROM 
   DBO.HCREGEGRE AS EGR 
   INNER JOIN (SELECT NUMINGRES, MAX(EGR.FECALTPAC) FECALTPAC 
               FROM DBO.HCREGEGRE EGR 
			        INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO =EGR.NUMINGRES 
			   GROUP BY NUMINGRES ) AS G ON G.NUMINGRES =EGR.NUMINGRES AND G.FECALTPAC =EGR.FECALTPAC 
 ),

--IN V1
CTE_INGRESO AS 
 (
  SELECT 
   ING.NUMINGRES,
   ING.IFECHAING,
   ING.IAUTORIZA AS [NUMERO AUTORIZACIÓN], 
   ING.IOBSERVAC AS [OBSERVACIONES],
   ha.Code Codigo,
   HA.Name AS ENTIDAD,
   CASE HA.ENTITYTYPE 
    WHEN 1 THEN 'EPS CONTRIBUTIVO' 
	WHEN 2 THEN 'EPS SUBSIDIADO' 
	WHEN 3 THEN 'ET VINCULADO MUNICIPIO' 
	WHEN 4 THEN 'ET VINCULADOS DAPARTAMENTO'
	WHEN 5 THEN 'ARL RIESGO LABORALES' 
	WHEN 6 THEN 'MP MEDICINA PREPAGADA' 
	WHEN 7 THEN 'IPS PRIVADA' 
	WHEN 8 THEN 'IPS PUBLICA' 
	WHEN 9 THEN 'REGIMEN ESPECIAL' 
	WHEN 10 THEN 'ACCIDENTE DE TRANSITO'
	WHEN 11 THEN 'FOSYGA' 
	WHEN 12 THEN 'OTROS' END AS [REGIMEN],
   RTRIM(Q.CODDIAGNO) + ' - ' + RTRIM(Q.NOMDIAGNO) AS [DIAGNOSTICO PRINCIPAL],
   ING.IINGREPOR,
   ing.ICAUSAING,
   q.CODICIE10

  FROM
   CTE_CAMAS_OCUPADA EST 
   INNER JOIN DBO.ADINGRESO ING ON EST.INGRESO=ING.NUMINGRES 
   INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON  ING.GENCONENTITY=HA.ID 
   LEFT JOIN INDIAGNOP DIA ON ING.NUMINGRES=DIA.NUMINGRES AND DIA.CODDIAPRI=1 
   LEFT JOIN dbo.INDIAGNOS Q ON DIA.CODDIAGNO=Q.CODDIAGNO
  GROUP BY 
   ING.NUMINGRES,
    ha.Code,
   ING.IFECHAING,
   ING.IAUTORIZA,
   ING.IOBSERVAC,
   HA.Name,HA.ENTITYTYPE,
   Q.CODDIAGNO,Q.NOMDIAGNO,
   ING.IINGREPOR,
   ing.ICAUSAING,
   q.CODICIE10
 )

SELECT 
GETDATE() 'Fecha del Censo',
'Hospital Departamental San Antonio de Pitalito' AS [Nombre IPS],
'Hospital Departamental San Antonio de Pitalito' AS [Sucursal IPS],
'891180134' [Nit IPS],
'415510047901 ' [Cod Habilitación],
 CASE ing.Codigo
 WHEN 'E0117'
 THEN 'POSS'
 WHEN 'E0116'
 THEN 'POSC'
 END 'Plan (Regimen)',
  CASE PAC.IPTIPODOC 
  WHEN '1'  THEN 'CC'
  WHEN '2'  THEN 'CE'
  WHEN '3'  THEN 'TI'
  WHEN '4'  THEN 'RC'
  WHEN '5'  THEN 'PA'
  WHEN '6'  THEN 'AS'
  WHEN '7'  THEN 'MS'
  WHEN '8'  THEN 'NU'
  WHEN '9'  THEN 'NV'
  WHEN '10' THEN 'CD'
  WHEN '11' THEN 'SC'
  WHEN '12' THEN 'PE' 
  WHEN '13' THEN 'PT'
  WHEN '14' THEN 'DE'
  WHEN '15' THEN 'SI' 
 END AS [Tipo Identificación],
 PAC.IPCODPACI [N° Identificación],
 CONVERT(VARCHAR, ing.IFECHAING, 103) AS [Fecha Ingreso],
 CASE ING.IINGREPOR
 WHEN 1
 THEN 'URGENCIAS'
 WHEN 2
 THEN 'CONSULTA EXTERNA'
 WHEN 3
 THEN 'NACIDO HOSPITAL'
 WHEN 4
 THEN 'REMITIDO'
 WHEN 5
 THEN 'HOSPITALIZACION URGENCIAS'
 END [Tipo Ingreso],
  CASE ING.ICAUSAING
WHEN	12	THEN	'Accidente de trabajo'
WHEN	13	THEN	'Accidente en el hogar'
WHEN	14	THEN	'Accidente de transito de origen comun'
WHEN	15	THEN	'Accidente de transito de origen laboral'
WHEN	16	THEN	'Accidente en el entorno educativo'
WHEN	17	THEN	'Otro tipo de accidente'
WHEN	18	THEN	'Evento catastrofico de origen natural'
WHEN	19	THEN	'Lesion por agresión'
WHEN	20	THEN	'Lesion auto infligida'
WHEN	21	THEN	'Sospecha de violencia fisica'
WHEN	22	THEN	'Sospecha de violencia psicologia'
WHEN	23	THEN	'sospecha de violencia sexual'
WHEN	24	THEN	'Sospecha de negligencia y abandono'
WHEN	25	THEN	'IVE relacionada con peligro a la salud o vida de la mujer'
WHEN	26	THEN	'IVE por malformacion congenita incompatible con la vida'
WHEN	27	THEN	'IVE por violencia sexual, incesto o por inseminacion artificial o transferencia de ovulo femenino'
WHEN	28	THEN	'Evento adverso en salud'
WHEN	29	THEN	'Enfermedad general'
WHEN	30	THEN	'Enfermedad Laboral'
WHEN	31	THEN	'Promocion y mantenimiento de la salud - Intervenciones individuales '
WHEN	32	THEN	'Intervención colectiva'
WHEN	33	THEN	'Atención de población materno perinaltal'
WHEN	34	THEN	'Seguridad y salud en el trabajo'
WHEN	35	THEN	'Otros eventos catastroficos'
WHEN	36	THEN	'Accidente en mina anti- personal - MAP'
WHEN	37	THEN	'Accidente de artefacto explosivo - AEI'
WHEN	38	THEN	'Accidente de munición sin explotar - MUSE'
WHEN	39	THEN	'Otra victima de conflicto armado colombiano'
WHEN	40	THEN	'Riesgo ambiental'
END 'Origen Atención',
  TE.DESTIPEST AS [Tipo Habitación],
ing.CODICIE10 [Cie 10 Ingreso]

 
FROM  
 DBO.CHREGESTA EST
 INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.ID_ESTANCIA =EST.ID AND CAM.INGRESO =EST.NUMINGRES 
 LEFT JOIN CTE_INGRESO AS ING ON ING.NUMINGRES =EST.NUMINGRES 
 INNER JOIN CTE_PRIMERA_HOSPITALIZACION HOS ON HOS.NUMINGRES =EST.NUMINGRES 
 INNER JOIN dbo.INPacient PAC ON EST.IPCODPACI=PAC.IPCODPACI 
 INNER JOIN dbo.CHTIPESTA AS TE ON TE.CODTIPEST = EST.CODTIPEST
 INNER JOIN Dbo.ADNIVELES NV ON PAC.NIVCODIGO=NV.NIVCODIGO
 LEFT JOIN dbo.INESPECIA K ON EST.CODESPECI = K.CODESPECI
 LEFT  JOIN dbo.INPROFSAL Prof ON EST.CODPROSAL = Prof.CODPROSAL
 LEFT JOIN CTE_ESPECIALIDAD_FINAL ESP ON ESP.NUMINGRES =EST.NUMINGRES
 LEFT JOIN CTE_ALTA_MEDICA AS ALT ON ALT.NUMINGRES =EST.NUMINGRES 
 LEFT JOIN CTE_REFERENCIA REF ON REF.NUMINGRES=ALT.NUMINGRES
 LEFT JOIN CTE_PAD PAD ON PAD.NUMINGRES=ALT.NUMINGRES
 LEFT JOIN CTE_VALOR_ESTANCIA AS VAL ON VAL.INGRESO = EST.NUMINGRES 
 where ing.Codigo in ('E0117 ','E0116')
