-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_Pendiente_Liquidar
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE view [Report].[View_Pendiente_Liquidar] as


WITH CTE_INGRESOS_ABIERTOS AS
 (
  SELECT 
   ING.NUMINGRES 'INGRESO', ING.IPCODPACI 'IDENTIFICACION', ING.IFECHAING 'FECHA INGRESO',CAST(ING.IFECHAING AS TIME) 'HORA INGRESO',
   CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' ELSE 'HOSPITALARIO' END 'TIPO INGRESO',
   ING.IAUTORIZA ,ING.UFUINGMED ,ING.UFUEGRMED ,ING.UFUINGHOS ,ING.UFUEGRHOS ,ING.CODPROING ,ING.CODPROEGR ,ING.CODESPTRA ,
  ING.UFUAACTMED ,ING.UFUAACTHOS ,ING.CODCAMACT ,ING.CODDIAING ,ING.CODDIAEGR ,ING.UFUACTPAC ,ING.CODICAMHO ,ING.FECHOSPIT ,ING.GENCONENTITY ,ING.GENCAREGROUP ,
  ING.FECHEGRESO 'FECHA EGRESO CAMA', CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO' ELSE 'PARCIAL' END 'ESTADO' ,
  CONCAT(RTRIM(ING.CODUSUCRE), ' - ', USU.NOMUSUARI) AS 'USUARIO CREA INGRESO',CONCAT(RTRIM(ING.CODUSUMOD), ' - ', USUM.NOMUSUARI) AS 'USUARIO MODIFICA INGRESO',
  USUA.NOMUSUARI 'USUARIO ANULO',ING.UFUCODIGO, CEN.NOMCENATE 'CENTRO ATENCION',ING.IOBSERVAC 'OBSERVACION INGRESO',HA.NAME 'ENTIDAD'
   FROM DBO.ADINGRESO ING 
   INNER JOIN DBO.ADCENATEN AS CEN ON CEN.CODCENATE =ING.CODCENATE 
   INNER JOIN Contract.HealthAdministrator AS HA ON HA.ID=ING.GENCONENTITY
   LEFT JOIN DBO.SEGusuaru AS USU ON USU.CODUSUARI =ING.CODUSUCRE 
   LEFT JOIN DBO.SEGusuaru AS USUM ON USUM.CODUSUARI =ING.CODUSUMOD
   LEFT JOIN DBO.SEGusuaru AS USUA ON USUA.CODUSUARI =ING.CODUSUANU
   WHERE ING.IESTADOIN IN ('' , 'P')
  ),

CTE_CARGOS_INGRESOS AS
 (
  SELECT 
   RC.AdmissionNumber 'INGRESO',
   CAST(SUM(RCD.TotalFolio) AS NUMERIC(20,2)) 'TOTAL FOLIO',
   RCD.Observation 'OBSERVACION FOLIO',
   CAS.DocumentDate 'FECHA RECIBO'

 FROM 
   BILLING.REVENUECONTROL RC 
   INNER JOIN CTE_INGRESOS_ABIERTOS AS ING ON RC.AdmissionNumber = ING.INGRESO  
   LEFT JOIN  Portfolio.PortfolioAdvance POR ON POR.AdmissionNumber = RC.AdmissionNumber
   LEFT JOIN  Treasury.CashReceipts cas ON cas.id = por.CashReceiptId
   INNER JOIN Billing.RevenueControlDetail AS RCD  ON RC.Id =RCD.RevenueControlId AND RCD.Status NOT IN (2,4) 
   GROUP BY RC.AdmissionNumber,RCD.Observation,CAS.DocumentDate
),

CTE_BOLETA_SALIDA
AS
(
 SELECT MAX(s.CreationDate) AS 'FECHA BOLETA SALIDA', s.AdmissionNumber,CONCAT(s.CreationUser, '-', USU.NOMUSUARI) AS 'USUARIO CREA BOLETA'
        FROM Billing.SlipOut s 
		INNER JOIN CTE_INGRESOS_ABIERTOS AS ING ON s.AdmissionNumber = ING.INGRESO
		LEFT JOIN DBO.SEGusuaru AS USU ON USU.CODUSUARI =s.CreationUser
        GROUP BY s.AdmissionNumber, s.CreationUser,CONCAT(s.CreationUser, '-', USU.NOMUSUARI)
),

CTE_OrdenServicioCTE 
AS 
(
   SELECT sd.CreationDate 'FECHA CREACION ORDEN',sd.AdmissionNumber,CONCAT(sd.CreationUser, ' - ', USU.NOMUSUARI) AS 'USUARIO CREA ORDEN SERVICIO',SD.OrderDate 'FECHA DE PRESTACIÓN DEL SERVICIO '
   FROM Billing.ServiceOrder sd
   INNER JOIN (SELECT MIN(SD.ID) id,sd.AdmissionNumber 
               FROM Billing.ServiceOrder sd
		       INNER JOIN CTE_INGRESOS_ABIERTOS AS ING ON sd.AdmissionNumber = ING.INGRESO
			   GROUP BY sd.AdmissionNumber
			   ) as G on G.id=sd.id
	LEFT JOIN DBO.SEGusuaru AS USU ON USU.CODUSUARI =sd.CreationUser
),

CTE_ALTA_MEDICA
AS
(
  SELECT EGR.NUMINGRES 'INGRESO' ,EGR.IPCODPACI 'IDENTIFICACION' ,MAX(EGR.FECALTPAC) 'FECHA ALTA MEDICA'  FROM DBO.HCREGEGRE EGR
  INNER JOIN CTE_INGRESOS_ABIERTOS AS ING  ON EGR.NUMINGRES  =ING.INGRESO 
  GROUP BY EGR.NUMINGRES,EGR.IPCODPACI
),

CTE_HISTORIAS_AMBULATORIAS
AS
(
  SELECT HIS.NUMINGRES ,HIS.IPCODPACI ,MAX(FECHISPAC) AS 'FECHA ALTA'    FROM  DBO.HCHISPACA HIS
  INNER JOIN CTE_INGRESOS_ABIERTOS  AS PEN ON PEN.INGRESO =HIS.NUMINGRES 
  WHERE HIS.GENCONEXT =1
  GROUP BY HIS.NUMINGRES ,HIS.IPCODPACI
)

 SELECT ING.IDENTIFICACION ,rtrim(PAC.IPNOMCOMP) 'PACIENTE', ING.INGRESO,ING.[FECHA INGRESO],BOL.[USUARIO CREA BOLETA],BOL.[FECHA BOLETA SALIDA],
 ING.[USUARIO CREA INGRESO],ING.[USUARIO MODIFICA INGRESO],ORD.[FECHA CREACION ORDEN],ORD.[FECHA DE PRESTACIÓN DEL SERVICIO ],ORD.[USUARIO CREA ORDEN SERVICIO],ING.[ESTADO],ING.[TIPO INGRESO],
 ING.ENTIDAD,ING.[OBSERVACION INGRESO], AD.[OBSERVACION FOLIO],AD.[FECHA RECIBO],
 CASE WHEN COALESCE(BOL.[FECHA BOLETA SALIDA], '') = ''  THEN 'Hospitalizado'
  ELSE 
        CASE 
            WHEN BOL.[FECHA BOLETA SALIDA] IS NOT NULL  THEN BOL.[USUARIO CREA BOLETA]
        END 
 END AS RESPONSABLE,ISNULL(VAL.[TOTAL FOLIO],'0') [TOTAL FOLIO], ING.IAUTORIZA AS [AUTORIZACION INGRESO], UNI.UFUCODIGO 'COD U FUNCIONAL',
 rtrim(UNI.UFUDESCRI) 'UNIDAD FUNCIONAL'

 FROM CTE_INGRESOS_ABIERTOS ING
 INNER JOIN DBO.INPACIENT AS PAC  ON PAC.IPCODPACI = ING.IDENTIFICACION
 INNER JOIN DBO.INUNIFUNC AS UNI  ON UNI.UFUCODIGO = ISNULL(ING.UFUACTPAC, ING.UFUCODIGO)
 INNER JOIN CTE_CARGOS_INGRESOS AD ON AD.INGRESO = ING.INGRESO
 LEFT JOIN CTE_BOLETA_SALIDA BOL ON BOL.AdmissionNumber=ING.INGRESO
 LEFT JOIN CTE_OrdenServicioCTE ORD ON ORD.AdmissionNumber=ING.INGRESO
 LEFT JOIN CTE_CARGOS_INGRESOS AS VAL ON VAL.INGRESO =ING.INGRESO
 LEFT JOIN CTE_ALTA_MEDICA AS ALT  ON ALT.INGRESO  =ING.INGRESO 




