-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_SOLICITUDESMATERIALOSTEOSINTESIS
-- Extracted by Fabric SQL Extractor SPN v3.9.0







CREATE VIEW [Report].[View_HDSAP_SOLICITUDESMATERIALOSTEOSINTESIS]
AS


SELECT INF.FECHAORDE FechaOrden,
       INF.IPCODPACI AS Documento, 
       PAC.IPNOMCOMP AS NombrePaciente, 
       INF.NUMINGRES AS Ingreso, 
       UF.UFUDESCRI AS UnidadFuncional, 
       INF.INDFARINT AS Material,
	   INF.NUMEFOLIO AS FolioSolicitud,
	   PRO.NOMMEDICO AS MedicoSolicita,
	   ESP.DESESPECI AS Especialidad,
	   ENT.NOMENTIDA AS Entidad,
	   CASE ING.TIPOINGRE WHEN 1 THEN 'Ambulatorio' WHEN 2 THEN 'Hospitalario' END AS TipoIngreso,
	   T2.CODDIAGNO AS DiagnosticoPrincipal,
	   ND.NOMDIAGNO AS NombreDiagnostico
FROM DBO.HCPRESCRC AS INF
      RIGHT JOIN
(
    SELECT CODCONCEC AS ID, NUMINGRES,FECHAORDE FECHA
    FROM DBO.HCPRESCRC AS INF
    WHERE INDFARINT <> '' AND INDFARINT IS NOT NULL  
    GROUP BY NUMINGRES,
	         CODCONCEC,
			 FECHAORDE

) AS T ON INF.CODCONCEC = T.ID
     INNER JOIN DBO.INPACIENT AS PAC ON INF.IPCODPACI = PAC.IPCODPACI
     INNER JOIN DBO.INUNIFUNC AS UF ON INF.UFUCODIGO = UF.UFUCODIGO
	 INNER JOIN DBO.INENTIDAD AS ENT ON PAC.CODENTIDA =ENT.CODENTIDA
	 INNER JOIN DBO.INPROFSAL AS PRO ON INF.CODPROSAL=PRO.CODPROSAL
	 INNER JOIN DBO.INESPECIA AS ESP ON PRO.CODESPEC1=ESP.CODESPECI
	 INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES=T.NUMINGRES
	 INNER JOIN (SELECT NUMINGRES, CODDIAGNO FROM DBO.INDIAGNOP WHERE CODDIAPRI=1) AS T2 ON T2.NUMINGRES=T.NUMINGRES
	 INNER JOIN DBO.INDIAGNOS AS ND ON T2.CODDIAGNO=ND.CODDIAGNO
