-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_INGRESO_ABIERTOS_AMBULATORIO
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE VIEW [Report].[View_HDSAP_INGRESO_ABIERTOS_AMBULATORIO]
AS

WITH CTE_INGRESOS_ABIERTOS AS
(
  SELECT 
   ING.NUMINGRES 'INGRESO', ING.IPCODPACI 'IDENTIFICACION', ING.IFECHAING 'FECHA INGRESO', CAST(ING.IFECHAING AS TIME) 'HORA INGRESO',
   CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' ELSE 'HOSPITALARIO' END 'TIPO INGRESO',
   ING.IAUTORIZA, ING.UFUINGMED, ING.UFUEGRMED, ING.UFUINGHOS, ING.UFUEGRHOS, ING.CODPROING, ING.CODPROEGR, ING.CODESPTRA,
   ING.UFUAACTMED, ING.UFUAACTHOS, ING.CODCAMACT, ING.CODDIAING, ING.CODDIAEGR, ING.UFUACTPAC, ING.CODICAMHO, ING.FECHOSPIT, ING.GENCONENTITY, ING.GENCAREGROUP,
   ING.FECHEGRESO 'FECHA EGRESO CAMA', CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO' ELSE 'PARCIAL' END 'ESTADO',
   CONCAT(RTRIM(ING.CODUSUCRE), ' - ', USU.NOMUSUARI) AS 'USUARIO CREA INGRESO', CONCAT(RTRIM(ING.CODUSUMOD), ' - ', USUM.NOMUSUARI) AS 'USUARIO MODIFICA INGRESO',
   USUA.NOMUSUARI 'USUARIO ANULO', ING.UFUCODIGO, CEN.NOMCENATE 'CENTRO ATENCION', ING.IOBSERVAC 'OBSERVACION INGRESO', HA.NAME 'ENTIDAD'
  FROM DBO.ADINGRESO ING 
  INNER JOIN DBO.ADCENATEN AS CEN ON CEN.CODCENATE = ING.CODCENATE 
  INNER JOIN Contract.HealthAdministrator AS HA ON HA.ID = ING.GENCONENTITY
  LEFT JOIN DBO.SEGusuaru AS USU ON USU.CODUSUARI = ING.CODUSUCRE 
  LEFT JOIN DBO.SEGusuaru AS USUM ON USUM.CODUSUARI = ING.CODUSUMOD
  LEFT JOIN DBO.SEGusuaru AS USUA ON USUA.CODUSUARI = ING.CODUSUANU
  WHERE ING.IESTADOIN IN ('' , 'P')
    AND PATINDEX('%[^0-9A-Fa-f]%', ING.NUMINGRES) = 0 
),


CTE_OrdenServicioCTE AS 
(
  SELECT 
   SD.CreationDate 'FECHA CREACION ORDEN',
   SD.AdmissionNumber,
   CONCAT(SD.CreationUser, ' - ', USU.NOMUSUARI) AS 'USUARIO CREA ORDEN SERVICIO',
   SD.OrderDate 'FECHA DE PRESTACIÓN DEL SERVICIO'
  FROM Billing.ServiceOrder SD
  INNER JOIN 
   (SELECT MIN(SD.ID) ID, SD.AdmissionNumber 
    FROM Billing.ServiceOrder SD
    INNER JOIN CTE_INGRESOS_ABIERTOS AS ING ON SD.AdmissionNumber = ING.INGRESO
    GROUP BY SD.AdmissionNumber
   ) AS G ON G.ID = SD.ID
  LEFT JOIN DBO.SEGusuaru AS USU ON USU.CODUSUARI = SD.CreationUser
),
CTE_CARGOS_INGRESOS AS
(
  SELECT 
   RC.AdmissionNumber 'INGRESO',
   CAST(SUM(RCD.TotalFolio) AS NUMERIC(20,2)) 'TOTAL FOLIO',
   RCD.Observation 'OBSERVACION FOLIO',
   CAS.CODE 'CODIGO RECIBO CAJA',
   CAS.DocumentDate 'FECHA RECIBO'
  FROM 
   BILLING.REVENUECONTROL RC 
   INNER JOIN CTE_INGRESOS_ABIERTOS AS ING ON RC.AdmissionNumber = ING.INGRESO  
   LEFT JOIN Portfolio.PortfolioAdvance POR ON POR.AdmissionNumber = RC.AdmissionNumber
   LEFT JOIN Treasury.CashReceipts CAS ON CAS.ID = POR.CashReceiptId
   INNER JOIN Billing.RevenueControlDetail AS RCD ON RC.ID = RCD.RevenueControlId 
  GROUP BY RC.AdmissionNumber, RCD.Observation, CAS.DocumentDate, CAS.CODE
)
SELECT 
 ING.IDENTIFICACION,
 RTRIM(PAC.IPNOMCOMP) 'PACIENTE',
 ING.INGRESO,
 ING.[FECHA INGRESO],
 ING.[USUARIO CREA INGRESO],
 ING.[USUARIO MODIFICA INGRESO],
 ORD.[FECHA CREACION ORDEN],
 ORD.[FECHA DE PRESTACIÓN DEL SERVICIO],
 ORD.[USUARIO CREA ORDEN SERVICIO],
 ING.[ESTADO],
 ING.[TIPO INGRESO],
 ING.ENTIDAD,
 ING.[OBSERVACION INGRESO],
 AD.[OBSERVACION FOLIO],
 AD.[CODIGO RECIBO CAJA],
 AD.[FECHA RECIBO],
 ISNULL(VAL.[TOTAL FOLIO], '0') [TOTAL FOLIO],
 ING.IAUTORIZA AS [AUTORIZACION INGRESO],
 UNI.UFUCODIGO 'COD U FUNCIONAL',
 RTRIM(UNI.UFUDESCRI) 'UNIDAD FUNCIONAL'

FROM CTE_INGRESOS_ABIERTOS ING
INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI = ING.IDENTIFICACION
INNER JOIN DBO.INUNIFUNC AS UNI ON UNI.UFUCODIGO = ISNULL(ING.UFUACTPAC, ING.UFUCODIGO)
INNER JOIN CTE_CARGOS_INGRESOS AD ON AD.INGRESO = ING.INGRESO
LEFT JOIN CTE_OrdenServicioCTE ORD ON ORD.AdmissionNumber = ING.INGRESO
LEFT JOIN CTE_CARGOS_INGRESOS AS VAL ON VAL.INGRESO = ING.INGRESO

