-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_RECIBO_CAJA_VS_FACTURA
-- Extracted by Fabric SQL Extractor SPN v3.9.0





CREATE VIEW [Report].[View_HDSAP_RECIBO_CAJA_VS_FACTURA]
AS


SELECT 
       C.DOCUMENTDATE AS FECHARECIBO,
       T.NIT AS DOCUMENTOTERCERO,
       T.NAME AS PACIENTE,
	   I.ADMISSIONNUMBER NUMEROINGRESO,
       C.CODE AS NUMERORECIBOCAJA,
       CD.VALUE AS VALORRECIBO,
       ISNULL(I.INVOICENUMBER, 'SIN FACTURA') AS FACTURA,
       P.BALANCE AS SALDOXCRUZAR
FROM TREASURY.CASHRECEIPTS C
LEFT JOIN TREASURY.CASHRECEIPTDETAILS CD ON CD.IDCASHRECEIPT = C.ID
LEFT JOIN COMMON.THIRDPARTY T ON T.ID = C.IDTHIRDPARTY
LEFT JOIN PORTFOLIO.PORTFOLIOADVANCE P ON  P.CASHRECEIPTID = C.ID 
LEFT JOIN BILLING.INVOICE I ON I.ADMISSIONNUMBER = P.ADMISSIONNUMBER
--WHERE  c.Code = '000249154'
  

