-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_RADICACION CIRUGIA_CONFIRMADOS
-- Extracted by Fabric SQL Extractor SPN v3.9.1





CREATE VIEW [Report].[View_HDSAP_RADICACION CIRUGIA_CONFIRMADOS]
AS


WITH CUPS_Agregados AS (
    SELECT 
        ra.NUMRADICACION,
        STRING_AGG(
            CONCAT(
                TRIM(COALESCE(CONCAT(CUPS1.CODSERIPS, '-', CUPS1.DESSERIPS), '')), 
                '-', 
                TRIM(COALESCE(CONCAT(CUPS.CODSERIPS, '-', CUPS.DESSERIPS), ''))
            ), 
            ', '
        ) WITHIN GROUP (ORDER BY CONCAT(
            TRIM(COALESCE(CONCAT(CUPS1.CODSERIPS, '-', CUPS1.DESSERIPS), '')), 
            '-', 
            TRIM(COALESCE(CONCAT(CUPS.CODSERIPS, '-', CUPS.DESSERIPS), ''))
        )) AS CUPS
    FROM ADRADICACIONQX RA
    LEFT JOIN ADRADICACIONQXS XS ON XS.IDRADICACIONQX = RA.ID
    LEFT JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS = XS.CODSERIPS
    LEFT JOIN INCUPSIPS CUPS1 ON CUPS1.CODSERIPS = RA.QXPRINCIPAL
    GROUP BY ra.NUMRADICACION
),
NombresNotasAdministrativas_Agregados AS (
    SELECT 
        ra.NUMRADICACION,
        ntl.NOMBRE
    FROM ADRADICACIONQX RA
    LEFT JOIN NTNOTASADMINISTRATIVASC c ON c.IPCODPACI = ra.IPCODPACI
    LEFT JOIN NTNOTASADMINISTRATIVASD d ON d.IDNTNOTASADMINISTRATIVASC = c.id
    LEFT JOIN NTVARIABLESL ntl ON ntl.IDNTVARIABLE = d.IDNTVARIABLE
    WHERE ntl.IDNTVARIABLE NOT IN ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10')
    GROUP BY ra.NUMRADICACION,
	ntl.NOMBRE
)
SELECT distinct
    ra.NUMRADICACION AS ConsecutivoRadicación, 
    RA.FECHARADIC AS FechaRadicacion,
    ra.IPCODPACI AS DocumentoPaciente,	  
    pac.IPNOMCOMP AS NombrePaciente,
    n.NOMENTIDA AS Entidad,
    ine.DESESPECI AS Especialidad,
    pro.NOMMEDICO AS Especialista, 
    COALESCE(ca.CUPS, '') AS CUPS,
    nna.NOMBRE AS NombresNotasAdministrativas
FROM ADRADICACIONQX RA
JOIN ADRADICACIONQXD RAD ON RAD.IDRADICACIONQX = RA.ID
JOIN INPACIENT pac ON pac.IPCODPACI = ra.IPCODPACI
JOIN INENTIDAD n ON n.CODENTIDA = pac.CODENTIDA
JOIN INESPECIA ine ON ine.CODESPECI = ra.CODESPECI
JOIN INPROFSAL pro ON pro.CODPROSAL = ra.CODPROSAL
LEFT JOIN CUPS_Agregados ca ON ca.NUMRADICACION = ra.NUMRADICACION
LEFT JOIN NombresNotasAdministrativas_Agregados nna ON nna.NUMRADICACION = ra.NUMRADICACION
where ra.ESTADO = 2

