-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_TOMA_MUESTRA_NEO
-- Extracted by Fabric SQL Extractor SPN v3.9.0








CREATE VIEW [Report].[View_HDSAP_TOMA_MUESTRA_NEO]
AS
SELECT DISTINCT
    hc.FECRECMUE AS FECHATOMAMUESTRA,
    'HORMONA ESTIMULANTE DEL TIROIDES' AS CUPS_904902,
    'PITALITO' AS MUNICIPIOMUESTRA, 
    CASE pac.IPTIPODOC
        WHEN '1' THEN 'CC'
        WHEN '2' THEN 'CE'
        WHEN '3' THEN 'TI'
        WHEN '4' THEN 'RC'
        WHEN '5' THEN 'PA'
        WHEN '6' THEN 'AS'
        WHEN '7' THEN 'MS'
        WHEN '8' THEN 'NU'
        WHEN '9' THEN 'CN'
        WHEN '11' THEN 'SC'
        WHEN '12' THEN 'PE'
        WHEN '13' THEN 'PT'
        WHEN '14' THEN 'DE'
        WHEN '15' THEN 'SI'
    END AS TIPO_DOCUMENTO,
    UPPER(pac.IPCODPACI) AS DOCUMENTOMADRE,
    UPPER(rec.numhijreg) AS NUMEROHIJO,
    '415510047901' AS IPSTOMA,
    UPPER(pac1.IPSEGNOMB) AS NOMBRERECIENNACIDO,
    UPPER(pac1.IPPRIAPEL) AS PRIMERAPELLIDO,
    UPPER(pac1.IPSEGAPEL) AS SEGUNDOAPELLIDO,
    CONVERT(VARCHAR(10), pac1.IPFECNACI, 120) AS FECHANACIMIENTO,
    CASE pac1.IPSEXOPAC
        WHEN 1 THEN 'MASCULINO'
        WHEN 2 THEN 'FEMENINO'
    END AS SEXO,
    UPPER(ine.NOMENTIDA) AS EPS,
    CASE
        WHEN pac.IPTIPOPAC ='1' THEN 'EPS CONTRIBUTIVO' 
        WHEN pac.IPTIPOPAC = '2' THEN 'EPS SUBSIDIADO' 
        WHEN pac.IPTIPOPAC = '3' THEN 'ET VINCULADOS MUNICIPIOS'
        WHEN pac.IPTIPOPAC = '4' THEN 'ET VINCULADOS DEPARTAMENTOS' 
        WHEN pac.IPTIPOPAC = '5' THEN 'ARL RIESGOS LABORALES' 
        WHEN pac.IPTIPOPAC = '6' THEN 'MP MEDICINA PREPAGADA' 
        WHEN pac.IPTIPOPAC = '7' THEN 'IPS PRIVADA' 
        WHEN pac.IPTIPOPAC = '8' THEN 'IPS PUBLICA' 
        WHEN pac.IPTIPOPAC = '9' THEN 'REGIMEN ESPECIAL' 
        WHEN pac.IPTIPOPAC = '10' THEN 'ACCIDENTES DE TRANSITO' 
        WHEN pac.IPTIPOPAC = '11' THEN 'FOSYGA' 
        WHEN pac.IPTIPOPAC = '12' THEN 'OTROS' 
        WHEN pac.IPTIPOPAC = '13' THEN 'ASEGURADORAS' 
        WHEN pac.IPTIPOPAC = '99' THEN 'PARTICULARES'
    END AS REGIMEN,
    UPPER(mun.MUNNOMBRE) AS MUNICIPIORESIDENCIA,
    UPPER(pac.IPTELEFON) AS TELEFONOCONTACTO,
	UPPER(pac.IPTELMOVI) AS NUMEROMOVIL,
    CASE pac1.IPTIPODOC
        WHEN '1' THEN 'CC'
        WHEN '2' THEN 'CE'
        WHEN '3' THEN 'TI'
        WHEN '4' THEN 'RC'
        WHEN '5' THEN 'PA'
        WHEN '6' THEN 'AS'
        WHEN '7' THEN 'MS'
        WHEN '8' THEN 'NU'
        WHEN '9' THEN 'CN'
        WHEN '11' THEN 'SC'
        WHEN '12' THEN 'PE'
        WHEN '13' THEN 'PT'
        WHEN '14' THEN 'DE'
        WHEN '15' THEN 'SI'
    END AS TIPO_DOCUMENTO_RECIEN_NACIDO,
    UPPER(pac1.ipcodpaci) AS DOCUMENTORECIENNACIDO,
    UPPER(rec.PESORECNA) AS PESO_RECIEN_NACIDO
FROM HCORDLABO hc
JOIN HCINGRESORECNAC hci ON hci.NUMINGRESHIJO = hc.NUMINGRES
JOIN INPACIENT pac ON pac.IPCODPACI = hci.IPCODPACI
JOIN INPACIENT pac1 ON pac1.IPCODPACI = hci.IPCODPACIHIJO
JOIN INENTIDAD ine ON ine.CODENTIDA = pac.CODENTIDA
JOIN INUBICACI inu ON inu.AUUBICACI = pac.AUUBICACI
JOIN INMUNICIP mun ON mun.DEPMUNCOD = inu.DEPMUNCOD
JOIN HCRECINAC rec ON rec.IPCODPACIHIJO = hci.IPCODPACIHIJO
WHERE hc.CODSERIPS = '904902'-- AND hci.IPCODPACI = '1007443911';

