-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_PROCEDIMIENTOSINFORMEQX
-- Extracted by Fabric SQL Extractor SPN v3.9.0







CREATE VIEW [Report].[View_HDSAP_PROCEDIMIENTOSINFORMEQX]
AS

   SELECT HIS.FECHISPAC AS [FECHA], 
            HCQXREALI.IPCODPACI AS [IDENTIFICACION], 
            INPACIENT.IPNOMCOMP AS [NOMBRE], 
            INUNIFUNC.UFUDESCRI AS [UNIDAD FUNCIONAL], 
            HCQXREALI.NUMINGRES AS [INGRESO], 
            INENTIDAD.NOMENTIDA AS [ENTIDAD], 
            HCQXREALI.CODSERIPS AS [CODIGO], 
            INCUPSIPS.DESSERIPS AS [SERVICIO], 
            HCQXREALI.CANTIDAQX AS [CANTIDAD], 
            HCQXREALI.NUMEFOLIO AS [FOLIO]
     FROM dbo.HCQXREALI
          INNER JOIN dbo.HCQXINFOR QX ON HCQXREALI.NUMEFOLIO = QX.NUMEFOLIO
                                                AND HCQXREALI.NUMINGRES = QX.NUMINGRES
          INNER JOIN dbo.INPACIENT ON HCQXREALI.IPCODPACI = INPACIENT.IPCODPACI
                                                AND QX.IPCODPACI = INPACIENT.IPCODPACI
          INNER JOIN dbo.INUNIFUNC ON HCQXREALI.UFUCODIGO = INUNIFUNC.UFUCODIGO
                                                AND QX.UFUCODIGO = INUNIFUNC.UFUCODIGO
          INNER JOIN dbo.INENTIDAD ON INPACIENT.CODENTIDA = INENTIDAD.CODENTIDA
          INNER JOIN dbo.INCUPSIPS ON HCQXREALI.CODSERIPS = INCUPSIPS.CODSERIPS
		  INNER JOIN DBO.HCHISPACA HIS ON QX.NUMEFOLIO=HIS.NUMEFOLIO AND QX.NUMINGRES=HIS.NUMINGRES
