-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_HDSAP_POBLACIÓNVICTIMACONFLICTO
-- Extracted by Fabric SQL Extractor SPN v3.9.0






CREATE VIEW [Report].[View_HDSAP_POBLACIÓNVICTIMACONFLICTO]
AS

select IP.IPNOMCOMP AS NOMBRE,
	   IP.IPCODPACI AS DOCUMENTO,
	   IP.IPDIRECCI AS DIRECCION,
	   IP.IPTELMOVI AS CELULAR,
	   IP.FECREGCRE AS FECHA,
	   IP.IPFECNACI AS FECHADENACIMIENTO,
	   DATEDIFF(YEAR,IP.IPFECNACI,GETDATE()) [Edad Actual],
	   ENT.NOMENTIDA ENTIDAD,
	   
      CASE IP.TIPCOBSAL
	  
           WHEN 1
           THEN 'CONTRIBUTIVO'
           WHEN 2
           THEN 'SUBSIDIADO PARCIAL'
           WHEN 3
           THEN 'SUBSIDIADO PARCIAL'
		   WHEN 4 
		   THEN 'POBLACION POBRE SIN ASEGURAR CON SISBEN'
		   WHEN 5
		   THEN 'POBLACION POBRE QUE TIENE SEGURO AL SISBEN'
		   WHEN 6
		   THEN 'DESPLAZADOS'
		   WHEN 7
		   THEN 'PLAN DE SALUD ADICIONAL'
		   WHEN 8
		   THEN 'OTROS'
      END AS TIPO_DE_POBLACION,
	  
	    GENERO = CASE IPSEXOPAC
		   WHEN 1
		   THEN 'MASCULINO'
		   WHEN 2
		   THEN 'FEMENINO'
		   END
	  
	  	   	    
FROM  INPACIENT as IP

INNER JOIN INENTIDAD AS ENT ON IP.CODENTIDA = ENT.CODENTIDA

WHERE IP.TIPCOBSAL = '6'



