-- Workspace: IMO
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 45d58e75-d0a4-4f2b-bd10-65e2dfeda219
-- Schema: ViewInternal
-- Object: VW_IMO_HC_PRESCRIPCIONMEDICAMENTOS_NUEVAEPS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [ViewInternal].[IMO_HC_PrescripcionMedicamentos_NuevaEPS]
AS

SELECT 
  CASE 
    WHEN B.IPTIPODOC = '1'  THEN 'CC'
    WHEN B.IPTIPODOC = '2'  THEN 'CE'
    WHEN B.IPTIPODOC = '3'  THEN 'TI'
    WHEN B.IPTIPODOC = '4'  THEN 'RC'
    WHEN B.IPTIPODOC = '5'  THEN 'PA'
    WHEN B.IPTIPODOC = '6'  THEN 'AS'
    WHEN B.IPTIPODOC = '7'  THEN 'MS'
    WHEN B.IPTIPODOC = '8'  THEN 'NU'
    WHEN B.IPTIPODOC = '9'  THEN 'NV'
    WHEN B.IPTIPODOC = '12' THEN 'PE'
    WHEN B.IPTIPODOC = '13' THEN 'PT'
  END AS TipoDocumento,
  A.IPCODPACI AS NumeroDocumento,
  CONCAT(RTRIM(LTRIM(B.IPPRINOMB)),' ',RTRIM(LTRIM(B.IPSEGNOMB))) AS Nombre_Paciente,
  CONCAT(RTRIM(LTRIM(B.IPPRIAPEL)),' ',RTRIM(LTRIM(B.IPSEGAPEL))) AS Apellidos_Paciente,
  A.CODDIAGNO AS CIE10,
  DX.NOMDIAGNO AS Diagnostico,
  DEP.nomdepart AS Departamento,
  MU.MUNNOMBRE AS Municipio,
  EA.Name AS Entidad,
  A.CODPRODUC AS Codigo_Producto,
  C.DESPRODUC AS Nombre_Producto,
  G.DESVIAADM AS Via_Administracion,
  A.DESADMINI AS Administracion,
  A.DOSISPRFN AS Dosis_Medicamento,
  A.FECINIDOS AS Fecha_Solicitud,
  CASE WHEN C.NOPOSPROD = '1' THEN 'NO PBS' WHEN C.NOPOSPROD = '0' THEN 'PBS' END AS TipoProducto
FROM
(
  SELECT MAX(CODCONCEC) AS CODCONCEC, IPCODPACI
  FROM [INDIGO035].[dbo].[HCPRESCRA]
  GROUP BY IPCODPACI
) AS AA
INNER JOIN [INDIGO035].[dbo].[HCPRESCRA] AS A
  ON AA.CODCONCEC = A.CODCONCEC
INNER JOIN [INDIGO035].[dbo].[IHLISTPRO] AS C
  ON C.CODPRODUC = A.CODPRODUC
INNER JOIN [INDIGO035].[dbo].[HCVIAADMI] AS G
  ON G.CODVIAADM = A.CODVIAADM
INNER JOIN [INDIGO035].[dbo].[INPACIENT] AS B
  ON B.IPCODPACI = A.IPCODPACI
INNER JOIN [INDIGO035].[dbo].[INUNIFUNC] AS D
  ON D.UFUCODIGO = A.UFUCODIGO
INNER JOIN [INDIGO035].[dbo].[ADCENATEN] AS CC
  ON CC.CODCENATE = A.CODCENATE
LEFT JOIN [INDIGO035].[dbo].[INUBICACI] AS UB
  ON UB.AUUBICACI = B.AUUBICACI
LEFT JOIN [INDIGO035].[dbo].[INMUNICIP] AS MU
  ON MU.DEPMUNCOD = UB.DEPMUNCOD
LEFT JOIN [INDIGO035].[dbo].[INDEPARTA] AS DEP
  ON DEP.depcodigo = MU.DEPCODIGO
LEFT JOIN [INDIGO035].[dbo].[ADINGRESO] AS I
  ON I.NUMINGRES = A.NUMINGRES
LEFT JOIN [INDIGO035].[Contract].[HealthAdministrator] AS EA
  ON EA.Id = I.GENCONENTITY
LEFT JOIN [INDIGO035].[Common].[ThirdParty] AS TP
  ON TP.Id = EA.ThirdPartyId
LEFT JOIN [INDIGO035].[dbo].[INDIAGNOS] AS DX
  ON DX.CODDIAGNO = A.CODDIAGNO
WHERE A.FECINIDOS >= '01-01-2025'
  AND EA.Name LIKE '%NUEVA%';