-- Workspace: IMO
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 45d58e75-d0a4-4f2b-bd10-65e2dfeda219
-- Schema: ViewInternal
-- Object: VW_ULTIMAEVOLUCION
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [ViewInternal].[VW_ULTIMAEVOLUCION]
AS

SELECT P.IPCODPACI, P.CODDIAGNO, DX.NOMDIAGNO, P.DATOBJETI, ES.DESESPECI
FROM (
    SELECT MAX(FECHISPAC) AS FECHA, IPCODPACI AS DOCUMENTO
    FROM [INDIGO035].[dbo].[HCHISPACA] AS P
    GROUP BY IPCODPACI
) AS R
INNER JOIN [INDIGO035].[dbo].[HCHISPACA] AS P
    ON P.IPCODPACI = R.DOCUMENTO AND P.FECHISPAC = R.FECHA
INNER JOIN [INDIGO035].[dbo].[INDIAGNOS] AS DX
    ON DX.CODDIAGNO = P.CODDIAGNO
INNER JOIN [INDIGO035].[dbo].[INESPECIA] AS ES
    ON ES.CODESPECI = P.CODESPTRA;