-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_AGENDAQX
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_AGENDAQX AS
WITH CTE_DURACION_QX AS (
    SELECT
        CODAUTONU,
        SUM(DURPROCQX) AS TIEMPO
    FROM
        INDIGO036.dbo.AGEPROGQX
    GROUP BY
        CODAUTONU
)
SELECT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    CASE
        INP.IPTIPODOC
        WHEN '1' THEN 'CEDULA DE CIUDADANIA'
        WHEN '2' THEN 'CEDULA DE EXTRANJERIA'
        WHEN '3' THEN 'TARJETA DE IDENTIDAD'
        WHEN '4' THEN 'REGISTRO CIVIL'
        WHEN '5' THEN 'PASAPORTE'
        WHEN '6' THEN 'ADULTO SIN IDENTIFICACION'
        WHEN '7' THEN 'MENOR SIN IDENTIFICACION'
        WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACIÒN'
        WHEN '9' THEN 'CERTIFICADO NACIDO VIVO'
        WHEN '10' THEN 'CARNET DIPLOMATICO'
        WHEN '11' THEN 'SALVOCONDUCTO'
        WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA'
        WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA'
        WHEN '14' THEN 'DOCUMENTO EXTRANJERO'
        WHEN '15' THEN 'SIN IDENTIFICACION'
    END AS [TIPO DOCUMENTO],
    INP.IPCODPACI AS 'ID. PACIENTE',
    INP.IPNOMCOMP AS 'NOMBRE PACIENTE',
    CAST(INP.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
    FLOOR(
        (
            CAST(CONVERT(VARCHAR(8), AGEN.FECHORAIN, 112) AS INT) - CAST(CONVERT(VARCHAR(8), INP.IPFECNACI, 112) AS INT)
        ) / 10000
    ) AS 'EDAD AÑOS',
    DATEDIFF(
        MONTH,
        CAST(INP.IPFECNACI AS varchar),
        CAST (AGEN.FECHORAIN AS DATE)
    ) AS 'EDAD MESES',
    CASE
        INP.IPSEXOPAC
        WHEN 1 THEN 'Masculino'
        WHEN 2 THEN 'Femenino'
    END AS SEXO,
    INP.IPDIRECCI AS DIRECCION,
    INP.IPTELEFON AS [TELEFONO FIJO],
    INP.IPTELMOVI AS [MOVIL],
    CASE
        INP.IPTIPOPAC
        WHEN 1 THEN 'Contributivo'
        WHEN 2 THEN 'Subsidiado'
        WHEN 3 THEN 'Vinculado'
        WHEN 4 THEN 'Particular'
        WHEN 5 THEN 'Otro'
        WHEN 6 THEN 'Desplazado Reg. Contributivo'
        WHEN 7 THEN 'Desplazado Reg. Subsidiado'
        WHEN 8 THEN 'Desplazado No Asegurado'
    END AS REGIMEN,
    RTRIM(IDE.CODENTIDA) + '-' + IDE.NOMENTIDA AS ESTIDAD,
    AGEN.CODSERIPS AS 'CUPS AGENDADO',
    AGEN.CODAUTONU AS [ID AGENDA],
    GRU.Grupoqx AS [GRUPO QX],
    PRO.NOMMEDICO AS [CIRUJANO],
    INE.DESESPECI AS [ESPECIALIDAD MEDICO],
    AGEN.FECREGSIS AS [FECHA AGENDAMIENTO],
    CASE
        AGEN.PRINCIPAL
        WHEN 1 THEN 'PRINCIPAL'
        ELSE 'SECUNDARIO'
    END AS [TIPO DE PROCEDIMIENTO],
    AGEN.CODSERIPS AS 'PROC. QX. ORDENADO',
    CUPS.DESCODCUPS AS 'NOMBRE PROCEDIMIENTO',
    CUPS2.Code AS 'CUPS PROCEDIMIENTO RELACIONADO',
    CUPS2.Description AS 'NOMBRE PROCEDIMIENTO RELACIONADO',
    CASE
        WHEN AGEN.ORIGENQX = 1 THEN 'Ambulatorio'
        ELSE 'Hospitalario'
    END AS 'AMBITO',
    CASE
        AGEN.TIPOANESTESIA
        WHEN 1 THEN 'Local'
        WHEN 2 THEN 'Regional'
        WHEN 3 THEN 'General'
        WHEN 4 THEN 'Combinada'
        WHEN 5 THEN 'No Aplica'
    END AS [TIPO ANESTESIA],
    CASE
        ORD.PRISERIPS
        WHEN 1 THEN 'EMERGENCIA'
        WHEN 2 THEN 'URGENCIA'
        WHEN 3 THEN 'NORMAL'
        WHEN 4 THEN 'DEFINIR CONDUCTA'
    END AS PRIORIDAD,
    ISNULL(
        RTRIM(FUN.UFUCODIGO) + ' - ' + FUN.UFUDESCRI,
        RTRIM(FUN2.UFUCODIGO) + '-' + FUN2.UFUDESCRI
    ) AS [UNIDAD SOLICITUD],
    CASE
        WHEN AGEN.ESTADOFARM = 1 THEN 'Pendiente Confirmacion'
        ELSE 'Solicitado a Farmacia'
    END AS 'ESTADO PAQUETE QX',
    CAST(AGEN.FECHORAIN AS DATE) AS 'FECHA CITA',
    AGEN.FECHORAIN AS 'INICIA CX',
    AGEN.FECHORAFI AS 'FIN CX',
    AGEN.DURPROCQX AS 'DURACION',
    TI.TIEMPO AS [DURACION TOTAL],
    CASE
        WHEN AGEN.CODESTPQX = 0 THEN 'Cirugia Programada'
        WHEN AGEN.CODESTPQX = 1 THEN 'Paciente admitido (Cirugia Origen Ambulatoria)'
        WHEN AGEN.CODESTPQX = 2 THEN 'Paciente en sala de espera'
        WHEN AGEN.CODESTPQX = 3 THEN 'Paciente en sala quirurgica'
        WHEN AGEN.CODESTPQX = 4 THEN 'Paciente en recuperación'
        WHEN AGEN.CODESTPQX = 5 THEN 'Paciente con alta'
        WHEN AGEN.CODESTPQX = 6 THEN 'Anulado - Cancelada'
    END AS 'ESTADO PROGRAMACION',
    AGEN.NUMAUTORI AS 'AUTORIZACION',
    AGEN.NUMINGRES AS 'INGRESO',
    CAM.NUMCAMHOS AS [CAMA ACTUAL],
    CASE
        WHEN DATEPART(HOUR, AGEN.FECHORAIN) BETWEEN 7
        AND 11 THEN 'Mañana'
        WHEN DATEPART(HOUR, AGEN.FECHORAIN) BETWEEN 12
        AND 18 THEN 'Tarde'
        WHEN DATEPART(HOUR, AGEN.FECHORAIN) BETWEEN 19
        AND 23
        OR DATEPART(HOUR, AGEN.FECHORAIN) BETWEEN 0
        AND 6 THEN 'Noche'
    END AS 'JORNADA',
    SALA.DESCRIPSAL AS 'SALA',
    AGEN.OBSERVACION,
    AGEN.FECHACAN AS 'FECHA CANCELACION',
    AGEN.CODCAUCAN AS 'COD. CAUSA CANCELACION',
    CAN.DESCAUCAN AS 'DESCRIPCION CAUSA',
    1 AS 'CANTIDAD',
    CAST(AGEN.FECHORAIN AS DATE) AS 'FECHA BUSQUEDA',
    YEAR(AGEN.FECHORAIN) AS 'AÑO FECHA BUSQUEDA',
    MONTH(AGEN.FECHORAIN) AS 'MES AÑO FECHA BUSQUEDA',
    CASE
        MONTH(AGEN.FECHORAIN)
        WHEN 1 THEN 'ENERO'
        WHEN 2 THEN 'FEBRERO'
        WHEN 3 THEN 'MARZO'
        WHEN 4 THEN 'ABRIL'
        WHEN 5 THEN 'MAYO'
        WHEN 6 THEN 'JUNIO'
        WHEN 7 THEN 'JULIO'
        WHEN 8 THEN 'AGOSTO'
        WHEN 9 THEN 'SEPTIEMBRE'
        WHEN 10 THEN 'OCTUBRE'
        WHEN 11 THEN 'NOVIEMBRE'
        WHEN 12 THEN 'DICIEMBRE'
    END AS 'MES NOMBRE FECHA BUSQUEDA',
    FORMAT(DAY(AGEN.FECHORAIN), '00') AS 'DIA FECHA BUSQUEDA',
    CONCAT(
        FORMAT(MONTH(AGEN.FECHORAIN), '00'),
        ' - ',
        CASE
            MONTH(AGEN.FECHORAIN)
            WHEN 1 THEN 'ENERO'
            WHEN 2 THEN 'FEBRERO'
            WHEN 3 THEN 'MARZO'
            WHEN 4 THEN 'ABRIL'
            WHEN 5 THEN 'MAYO'
            WHEN 6 THEN 'JUNIO'
            WHEN 7 THEN 'JULIO'
            WHEN 8 THEN 'AGOSTO'
            WHEN 9 THEN 'SEPTIEMBRE'
            WHEN 10 THEN 'OCTUBRE'
            WHEN 11 THEN 'NOVIEMBRE'
            WHEN 12 THEN 'DICIEMBRE'
        END
    ) AS MES_LABEL_INGRESO,
    CONVERT(
        DATETIME,
        GETDATE() AT TIME ZONE 'Pakistan Standard Time',
        1
    ) AS ULT_ACTUAL
FROM
    INDIGO036.dbo.AGEPROGQX AGEN
    INNER JOIN INDIGO036.dbo.INPACIENT INP ON INP.IPCODPACI = AGEN.IPCODPACI
    INNER JOIN INDIGO036.dbo.INENTIDAD IDE ON INP.CODENTIDA = IDE.CODENTIDA
    LEFT JOIN INDIGO036.dbo.ADINGRESO ING ON ING.NUMINGRES = AGEN.NUMINGRES
    AND ING.IPCODPACI = AGEN.IPCODPACI
    INNER JOIN INDIGO036.dbo.INPROFSAL PRO ON AGEN.CODPROSAL = PRO.CODPROSAL
    INNER JOIN INDIGO036.dbo.INESPECIA INE ON PRO.CODESPEC1 = INE.CODESPECI
    INNER JOIN CTE_DURACION_QX TI ON AGEN.CODAUTONU = TI.CODAUTONU
    INNER JOIN INDIGO036.dbo.INCUPSIPS CUPS ON CUPS.CODGOCUPS = AGEN.CODSERIPS
    LEFT JOIN INDIGO036.dbo.CHCAMASHO CAM ON ING.CODCAMACT = CAM.CODICAMAS
    LEFT JOIN INDIGO036.Contract.CUPSEntityContractDescriptions CUPSREL ON CUPSREL.Id = AGEN.IDDESCRIPCIONRELACIONADA
    LEFT JOIN INDIGO036.Contract.CUPSEntity CUPS2 ON CUPSREL.Id = CUPS2.Id
    LEFT JOIN INDIGO036.dbo.AGCACANQX CAN ON CAN.CODCACANQ = AGEN.CODCAUCAN
    LEFT JOIN INDIGO036.dbo.HCORDPROQ QX ON AGEN.AUTOHCORDPROQ = QX.AUTO
    LEFT JOIN INDIGO036.dbo.HCORDPRON NOQ ON AGEN.NUMINGRES = NOQ.NUMINGRES
    AND NOQ.CODSERIPS = AGEN.CODSERIPS
    AND NOQ.FECORDMED < AGEN.FECHORAIN
    LEFT JOIN INDIGO036.dbo.INUNIFUNC FUN ON QX.UFUCODIGO = FUN.UFUCODIGO
    LEFT JOIN INDIGO036.dbo.INUNIFUNC FUN2 ON FUN2.UFUCODIGO = NOQ.UFUCODIGO
    LEFT JOIN INDIGO036.dbo.AGENSALAC SALA ON SALA.CODCONCEC = AGEN.AGENSALAC
    LEFT JOIN INDIGO036.Report.GruposQX GRU ON AGEN.CODSERIPS = GRU.Code
    LEFT JOIN INDIGO036.dbo.HCORDPROQ ORD ON AGEN.AUTOHCORDPROQ = ORD.AUTO