-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_BASEDEANTIBIOTICOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE   VIEW [Report].[VW_BASEDEANTIBIOTICOS]  AS

SELECT DISTINCT
    A.[CAMA],
    B.[UNIDAD FUNCIONAL],
    B.[IDENTIFICACION],
    [NOMBRE PACIENTE],
    [DIAGNOSTICO],
    B.[MEDICAMENTO],
    CONVERT(DATE, [FECHA DE APLICACION], 103) AS [FECHA DE APLICACION],
    [PROFESIONAL DE SALUD],
    [DOSIS SOLICITADA],
    [UNIDAD],
    [DURACION],
    B.[GRUPO FARMACOLOGICO],
    B.[CODIGO MEDICAMENTO],
    [CONCETRACION],
    [VIA ADMINISTRACION],
    A.[PRESENTACION],
    [ESTADIO],
    -- [MOTIVO DE SUSPENCION], -- Campo comentado, incluir si es necesario
    [TIPO SOLICITUD],
    [CANTIDAD CALCULADA],
    [DOSIS DEL MEDICMAMENTO],
    [UNIDAD DEL MEDICAMENTO],
    [ESQUEMA],
    B.[INGRESO],
    CONVERT(VARCHAR(10), [FECHA INGRESO], 103) AS [FECHA INGRESO],
    GETDATE() AS FECHA_EJECUCION,
    A.[FECHA BUSQUEDA]
FROM (
    SELECT *
    FROM [Report].[VW_MEDICAMENTOSORDENADOS]
    WHERE CAMA IS NOT NULL
      AND MONTH([FECHA BUSQUEDA]) BETWEEN MONTH(GETDATE()) - 1 AND MONTH(GETDATE())
) A
LEFT JOIN (
    SELECT *
    FROM [Report].[VW_MEDICAMENTOSAPLICADOS]
) B ON A.ID_COMPANY = B.ID_COMPANY
    AND A.[CENTRO ATENCION] = B.[CENTRO ATENCION]
    AND A.IDENTIFICACION = B.IDENTIFICACION
    AND A.INGRESO = B.INGRESO
    AND A.[CODIGO MEDICAMENTO] = B.[CODIGO MEDICAMENTO]