-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_DIETAS_POR_PACIENTE
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_DIETAS_POR_PACIENTE
AS 

WITH CTE_CAMAS_OCUPADAS AS (
    SELECT
        TBL2.UFUCODIGO AS 'CODIGO_UNIDAD_FUNCIONAL',
        TBL2.UFUDESCRI AS 'UNIDAD_FUNCIONAL',
        TBL3.IPCODPACI AS 'IDENTIFICACION',
        TBL3.NUMINGRES AS 'INGRESO_CAMA_OCUPADA',
        TBL1.NUMCAMHOS AS 'CAMA',
        TBL4.DESTIPEST AS 'TIPO_ESTANCIA',
        TBL3.ID AS 'ID_ESTANCIA',
        TBL1.CODICAMAS AS 'ID_CAMA',
        TBL1.CODCLAHAB,
        TBL1.CODCLACAM
    FROM
        [INDIGO036].[dbo].CHCAMASHO AS TBL1
        INNER JOIN [INDIGO036].[dbo].[INUNIFUNC] AS TBL2 ON TBL1.UFUCODIGO = TBL2.UFUCODIGO
        LEFT JOIN [INDIGO036].[dbo].[CHREGESTA] AS TBL3 ON TBL1.CODICAMAS = TBL3.CODICAMAS
            AND TBL3.REGESTADO = 1
        LEFT JOIN [INDIGO036].[dbo].[CHTIPESTA] AS TBL4 ON TBL4.CODTIPEST = TBL3.CODTIPEST
        LEFT JOIN [INDIGO036].[dbo].ADCENATEN AS TBL5 ON TBL5.CODCENATE = TBL1.CODCENATE
),
CTE_PRIMERA_HOSPITALIZACION AS (
    SELECT
        TBL1.NUMINGRES,
        TBL1.IPCODPACI,
        TBL1.FECINIEST AS 'FECHA_INICIAL_HOSPITALIZACION'
    FROM
        [INDIGO036].[dbo].[CHREGESTA] AS TBL1
        INNER JOIN (
            SELECT
                SUBTBL1.NUMINGRES,
                SUBTBL1.IPCODPACI,
                MIN(SUBTBL1.ID) AS ID
            FROM
                [INDIGO036].[dbo].[CHREGESTA] AS SUBTBL1
                INNER JOIN CTE_CAMAS_OCUPADAS AS SUBTBL2 ON SUBTBL2.INGRESO_CAMA_OCUPADA = SUBTBL1.NUMINGRES
            GROUP BY
                SUBTBL1.NUMINGRES,
                SUBTBL1.IPCODPACI
        ) AS TBL2 ON TBL2.ID = TBL1.ID
),
CTE_ALTA_MEDICA AS (
    SELECT
        TBL1.NUMINGRES,
        TBL1.IPCODPACI
    FROM
        [INDIGO036].[dbo].[HCREGEGRE] AS TBL1
        INNER JOIN (
            SELECT
                SUBTBL1.NUMINGRES,
                MAX(SUBTBL1.FECALTPAC) AS FECALTPAC
            FROM
                [INDIGO036].[dbo].[HCREGEGRE] AS SUBTBL1
                INNER JOIN CTE_CAMAS_OCUPADAS AS SUBTBL2 ON SUBTBL2.INGRESO_CAMA_OCUPADA = SUBTBL1.NUMINGRES
            GROUP BY
                SUBTBL1.NUMINGRES
        ) AS TBL2 ON TBL2.NUMINGRES = TBL1.NUMINGRES
            AND TBL2.FECALTPAC = TBL1.FECALTPAC
),
CTE_INGRESO AS (
    SELECT
        TBL2.NUMINGRES,
        TBL2.IFECHAING,
        TBL2.IOBSERVAC AS 'OBSERVACIONES_INGRESO',
        TBL3.Name AS 'ENTIDAD',
        (
            CASE
                TBL3.EntityType
                WHEN 1 THEN 'EPS CONTRIBUTIVO'
                WHEN 2 THEN 'EPS SUBSIDIADO'
                WHEN 3 THEN 'ET VINCULADO MUNICIPIO'
                WHEN 4 THEN 'ET VINCULADOS DAPARTAMENTO'
                WHEN 5 THEN 'ARL RIESGO LABORALES'
                WHEN 6 THEN 'MP MEDICINA PREPAGADA'
                WHEN 7 THEN 'IPS PRIVADA'
                WHEN 8 THEN 'IPS PUBLICA'
                WHEN 9 THEN 'REGIMEN ESPECIAL'
                WHEN 10 THEN 'ACCIDENTE DE TRANSITO'
                WHEN 11 THEN 'FOSYGA'
                WHEN 12 THEN 'OTROS'
            END
        ) AS 'REGIMEN',
        RTRIM(TBL5.CODDIAGNO) + ' - ' + RTRIM(TBL5.NOMDIAGNO) AS 'DIAGNOSTICO_PRINCIPAL'
    FROM
        CTE_CAMAS_OCUPADAS AS TBL1
        INNER JOIN [INDIGO036].[dbo].[ADINGRESO] AS TBL2 ON TBL1.INGRESO_CAMA_OCUPADA = TBL2.NUMINGRES
        INNER JOIN INDIGO036.Contract.HealthAdministrator AS TBL3 ON TBL2.GENCONENTITY = TBL3.Id
        LEFT JOIN [INDIGO036].[dbo].[INDIAGNOP] AS TBL4 ON TBL2.NUMINGRES = TBL4.NUMINGRES
            AND TBL4.CODDIAPRI = 1
        LEFT JOIN [INDIGO036].[dbo].[INDIAGNOS] AS TBL5 ON TBL4.CODDIAGNO = TBL5.CODDIAGNO
    GROUP BY
        TBL2.NUMINGRES,
        TBL2.IFECHAING,
        TBL2.IOBSERVAC,
        TBL3.Name,
        TBL3.EntityType,
        TBL5.CODDIAGNO,
        TBL5.NOMDIAGNO
),
CTE_DESCRIPCION_DIETAS AS (
    SELECT
        COUNT(TBL2.DESTIPDIE) AS 'COUNT_DIETAS',
        TBL1.NUMINGRES AS 'INGRESO_DIETAS',
        TBL2.ESTADOREG AS 'ESTADO_DIETA_INDIGO',
        STRING_AGG(TRIM(TBL2.DESTIPDIE), ',') WITHIN GROUP (
            ORDER BY
                TRIM(TBL2.DESTIPDIE) ASC
        ) AS 'DESCRIPCION_DIETAS'
    FROM
        [INDIGO036].[dbo].[CHREGDIET] AS TBL1
        LEFT JOIN [INDIGO036].[dbo].[CHTIPDIET] AS TBL2 ON TBL1.CODTIPDIE = TBL2.CODTIPDIE
    GROUP BY
        TBL1.NUMINGRES,
        TBL2.ESTADOREG
),
CTE_OBSERVACIONES_DIETAS AS (
    SELECT
        TBL1.[INGRESO_DIETAS],
        STRING_AGG(TBL1.[OBSERVACIONES_DIETAS], ', ') WITHIN GROUP (
            ORDER BY
                TBL1.[OBSERVACIONES_DIETAS] ASC
        ) AS [OBSERVACIONES_DIETAS]
    FROM
        (
            SELECT
                DISTINCT SUBTBL1.NUMINGRES AS 'INGRESO_DIETAS',
                TRIM(SUBTBL1.OBSERVACI) AS 'OBSERVACIONES_DIETAS'
            FROM
                [INDIGO036].[dbo].[CHREGDIET] AS SUBTBL1
                LEFT JOIN [INDIGO036].[dbo].[CHTIPDIET] AS SUBTBL2 ON SUBTBL1.CODTIPDIE = SUBTBL2.CODTIPDIE
        ) AS TBL1
    GROUP BY
        TBL1.[INGRESO_DIETAS],
        TBL1.[OBSERVACIONES_DIETAS]
),
CTE_DIETAS AS (
    SELECT
        TBL1.[COUNT_DIETAS],
        TBL1.[INGRESO_DIETAS],
        TBL1.[ESTADO_DIETA_INDIGO],
        (
            CASE
                WHEN TBL1.[ESTADO_DIETA_INDIGO] = '0' THEN 'DIETA INACTIVA'
                ELSE TBL1.[DESCRIPCION_DIETAS]
            END
        ) AS [DESCRIPCION_DIETAS],
        (
            CASE
                WHEN TBL2.[OBSERVACIONES_DIETAS] = ', ' THEN 'NINGUNA'
                WHEN TBL2.[OBSERVACIONES_DIETAS] IS NULL THEN 'NINGUNA'
                WHEN TBL2.[OBSERVACIONES_DIETAS] = '' THEN 'NINGUNA'
                ELSE TBL2.[OBSERVACIONES_DIETAS]
            END
        ) AS [OBSERVACIONES_DIETAS]
    FROM
        CTE_DESCRIPCION_DIETAS AS TBL1
        LEFT JOIN CTE_OBSERVACIONES_DIETAS AS TBL2 ON TBL1.[INGRESO_DIETAS] = TBL2.[INGRESO_DIETAS]
),
CTE_ALERGIAS AS (
    SELECT
        TBL1.[INGRESO_ALERGIAS],
        STRING_AGG(TBL1.[ANTECEDENTES_ALERGICOS], ', ') WITHIN GROUP (
            ORDER BY
                TBL1.[ANTECEDENTES_ALERGICOS] ASC
        ) AS [ANTECEDENTES_ALERGICOS]
    FROM
        (
            SELECT
                DISTINCT TBL1.NUMINGRES 'INGRESO_ALERGIAS',
                TBL1.ANTALEPAC AS 'ANTECEDENTES_ALERGICOS'
            FROM
                [INDIGO036].[dbo].[HCANTPACI] AS TBL1
            WHERE
                TBL1.ANTALEPAC IS NOT NULL
                AND TBL1.ANTALEPAC LIKE '%Otras Alergias%'
        ) AS TBL1
    GROUP BY
        TBL1.[INGRESO_ALERGIAS],
        TBL1.[ANTECEDENTES_ALERGICOS]
),
CTE_CENSO_DIETAS_POR_PACIENTE AS (
    SELECT
        DISTINCT TBL1.NUMINGRES AS 'INGRESO',
        TBL5.IPNOMCOMP AS 'NOMBRE_COMPLETO_PACIENTE',
        TBL5.IPCODPACI AS 'IDENTIFICACION',
        (
            CASE
                TBL5.IPTIPODOC
                WHEN 1 THEN 'CC'
                WHEN 2 THEN 'CE'
                WHEN 3 THEN 'TI'
                WHEN 4 THEN 'RC'
                WHEN 5 THEN 'PA'
                WHEN 6 THEN 'AS'
                WHEN 7 THEN 'MS'
                WHEN 8 THEN 'NU'
                WHEN 9 THEN 'CN'
                WHEN 10 THEN 'CD'
                WHEN 11 THEN 'SC'
                WHEN 12 THEN 'PE'
                WHEN 13 THEN 'PT'
                WHEN 14 THEN 'DE'
                WHEN 15 THEN 'SI'
            END
        ) AS 'TIPO_IDENTIFICACION',
        TBL5.IPFECNACI AS 'FECHA_NACIMIENTO',
        DATEDIFF(MONTH, TBL5.IPFECNACI, GETDATE()) % 12 AS 'EDAD_MESES',
        FLOOR(
            (
                CAST(CONVERT(VARCHAR(8), TBL1.FECINIEST, 112) AS INT) - CAST(CONVERT(VARCHAR(8), TBL5.IPFECNACI, 112) AS INT)
            ) / 10000
        ) AS 'EDAD_A�OS',
        TBL1.FECINIEST AS 'FECHA_ASIGNACION_UNIDAD/FECHA_INICIAL_ESTANCIA',
        TBL1.FECINIEST AS 'FECHA_INGRESO',
        TBL3.IFECHAING AS 'FECHA_INGRESO_ADMISION',
        TBL4.FECHA_INICIAL_HOSPITALIZACION,
        TBL2.CODIGO_UNIDAD_FUNCIONAL,
        TBL2.UNIDAD_FUNCIONAL,
        TBL2.CAMA,
        (
            CASE
                TBL2.CODCLACAM
                WHEN '1' THEN UPPER('ObservacionUrgencias')
                WHEN '2' THEN UPPER('Recuperacion Post Qx')
                WHEN '3' THEN 'HOSPITALARIA'
            END
        ) AS 'CLASE_DE_CAMA',
        (
            CASE
                TBL2.CODCLAHAB
                WHEN '1' THEN 'SALA OBSERVACION'
                WHEN '2' THEN 'SALA PROCEDIMIENTO'
                WHEN '3' THEN 'SALA RECUPERACION'
                WHEN '4' THEN 'HABITACION 1 CAMA'
                WHEN '5' THEN 'HABITACION 2 CAMAS'
                WHEN '6' THEN 'HABITACION 3 CAMAS'
                WHEN '7' THEN 'HABITACION 4 CAMAS'
                WHEN '8' THEN 'SUITE'
                WHEN '9' THEN 'HAB.ESPECIAL'
                WHEN '10' THEN 'UCI'
                WHEN '11' THEN 'OTRO'
            END
        ) AS 'CLASE_DE_HABITACION',
        'NO' AS 'VIP',
        DATEDIFF(DAY, TBL1.FECINIEST, GETDATE()) AS 'DIAS_TRANSCURRIDOS',
        DATEDIFF(
            DAY,
            TBL4.FECHA_INICIAL_HOSPITALIZACION,
            GETDATE()
        ) AS 'DIAS_DE_HOSPITALIZACION',
        DATEDIFF(DAY, TBL1.FECINIEST, GETDATE()) AS 'DIAS_EN_LA_UNIDAD',
        TBL6.DESTIPEST AS 'TIPO_DE_ESTANCIA',
        (
            CASE
                WHEN TBL8.NUMINGRES IS NULL THEN '1 - Pacientes en la Unidad'
                ELSE '2 - Pacientes Con Salida'
            END
        ) AS 'ESTADO',
        TBL3.DIAGNOSTICO_PRINCIPAL,
        (
            CASE
                WHEN TBL9.COUNT_DIETAS IS NULL
                AND TBL9.ESTADO_DIETA_INDIGO IS NULL
                AND TBL9.DESCRIPCION_DIETAS IS NULL THEN 0
                ELSE TBL9.COUNT_DIETAS
            END
        ) AS 'COUNT_DIETAS',
        (
            CASE
                WHEN TBL9.COUNT_DIETAS IS NULL
                AND TBL9.ESTADO_DIETA_INDIGO IS NULL
                AND TBL9.DESCRIPCION_DIETAS IS NULL THEN 0
                ELSE TBL9.ESTADO_DIETA_INDIGO
            END
        ) AS 'ESTADO_DIETA_INDIGO',
        (
            CASE
                WHEN TBL9.COUNT_DIETAS IS NULL
                AND TBL9.ESTADO_DIETA_INDIGO IS NULL
                AND TBL9.DESCRIPCION_DIETAS IS NULL THEN 'SIN DIETA'
                ELSE TBL9.DESCRIPCION_DIETAS
            END
        ) AS 'DESCRIPCION_DIETAS',
        (
            CASE
                WHEN TBL9.COUNT_DIETAS IS NULL
                AND TBL9.ESTADO_DIETA_INDIGO IS NULL
                AND TBL9.DESCRIPCION_DIETAS IS NULL THEN 'SIN DIETA'
                ELSE TBL9.OBSERVACIONES_DIETAS
            END
        ) AS 'OBSERVACIONES_DIETAS',
        (
            CASE
                WHEN TBL10.ANTECEDENTES_ALERGICOS IS NULL THEN 'NINGUNA'
                WHEN TBL10.ANTECEDENTES_ALERGICOS = '' THEN 'NINGUNA'
                ELSE TBL10.ANTECEDENTES_ALERGICOS
            END
        ) AS 'ANTECEDENTES_ALERGICOS',
        '1' AS 'ESTADO_DIETA_MEDIREST',
        'NUEVOS CENSO' AS 'ITEM_CORRESPONDIENTE',
        TBL3.ENTIDAD,
        TBL3.REGIMEN,
        TBL7.NIVDESCRI AS 'CATEGORIA',
        TBL3.OBSERVACIONES_INGRESO,
        TBL1.CODPROSAL,
        PROF.NOMMEDICO
    FROM
        [INDIGO036].[dbo].[CHREGESTA] AS TBL1
        INNER JOIN CTE_CAMAS_OCUPADAS AS TBL2 ON TBL2.ID_ESTANCIA = TBL1.ID
            AND TBL2.INGRESO_CAMA_OCUPADA = TBL1.NUMINGRES
        LEFT JOIN CTE_INGRESO AS TBL3 ON TBL3.NUMINGRES = TBL1.NUMINGRES
        INNER JOIN CTE_PRIMERA_HOSPITALIZACION AS TBL4 ON TBL4.NUMINGRES = TBL1.NUMINGRES
        INNER JOIN [INDIGO036].[dbo].[INPACIENT] AS TBL5 ON TBL1.IPCODPACI = TBL5.IPCODPACI
        INNER JOIN [INDIGO036].[dbo].[CHTIPESTA] AS TBL6 ON TBL6.CODTIPEST = TBL1.CODTIPEST
        INNER JOIN [INDIGO036].[dbo].[ADNIVELES] AS TBL7 ON TBL5.NIVCODIGO = TBL7.NIVCODIGO
        LEFT JOIN CTE_ALTA_MEDICA AS TBL8 ON TBL8.NUMINGRES = TBL1.NUMINGRES
        LEFT JOIN CTE_DIETAS AS TBL9 ON TBL9.INGRESO_DIETAS = TBL1.NUMINGRES
        LEFT JOIN CTE_ALERGIAS AS TBL10 ON TBL10.INGRESO_ALERGIAS = TBL1.NUMINGRES
        LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] PROF ON TBL1.CODPROSAL = PROF.CODPROSAL
)
SELECT
    CTA_FINAL_DIETAS_POR_PACIENTE.[INGRESO],
    CTA_FINAL_DIETAS_POR_PACIENTE.[NOMBRE_COMPLETO_PACIENTE],
    CTA_FINAL_DIETAS_POR_PACIENTE.[IDENTIFICACION],
    CTA_FINAL_DIETAS_POR_PACIENTE.[TIPO_IDENTIFICACION],
    CTA_FINAL_DIETAS_POR_PACIENTE.[FECHA_NACIMIENTO],
    CTA_FINAL_DIETAS_POR_PACIENTE.[EDAD_MESES],
    CTA_FINAL_DIETAS_POR_PACIENTE.[EDAD_A�OS],
    CTA_FINAL_DIETAS_POR_PACIENTE.[EDAD],
    CTA_FINAL_DIETAS_POR_PACIENTE.[FECHA_ASIGNACION_UNIDAD/FECHA_INICIAL_ESTANCIA],
    CTA_FINAL_DIETAS_POR_PACIENTE.[FECHA_INGRESO],
    CTA_FINAL_DIETAS_POR_PACIENTE.[FECHA_INGRESO_ADMISION],
    CTA_FINAL_DIETAS_POR_PACIENTE.[FECHA_INICIAL_HOSPITALIZACION],
    CTA_FINAL_DIETAS_POR_PACIENTE.[CODIGO_UNIDAD_FUNCIONAL],
    CTA_FINAL_DIETAS_POR_PACIENTE.[UNIDAD_FUNCIONAL],
    CTA_FINAL_DIETAS_POR_PACIENTE.[CAMA],
    CTA_FINAL_DIETAS_POR_PACIENTE.[CLASE_DE_CAMA],
    CTA_FINAL_DIETAS_POR_PACIENTE.[CLASE_DE_HABITACION],
    CTA_FINAL_DIETAS_POR_PACIENTE.[VIP],
    CTA_FINAL_DIETAS_POR_PACIENTE.[DIAS_TRANSCURRIDOS],
    CTA_FINAL_DIETAS_POR_PACIENTE.[DIAS_DE_HOSPITALIZACION],
    CTA_FINAL_DIETAS_POR_PACIENTE.[DIAS_EN_LA_UNIDAD],
    CTA_FINAL_DIETAS_POR_PACIENTE.[TIPO_DE_ESTANCIA],
    CTA_FINAL_DIETAS_POR_PACIENTE.[ESTADO],
    CTA_FINAL_DIETAS_POR_PACIENTE.[DIAGNOSTICO_PRINCIPAL],
    CTA_FINAL_DIETAS_POR_PACIENTE.[COUNT_DIETAS],
    CTA_FINAL_DIETAS_POR_PACIENTE.[ESTADO_DIETA_INDIGO],
    CTA_FINAL_DIETAS_POR_PACIENTE.[DESCRIPCION_DIETAS],
    CTA_FINAL_DIETAS_POR_PACIENTE.[OBSERVACIONES_DIETAS],
    CTA_FINAL_DIETAS_POR_PACIENTE.[ANTECEDENTES_ALERGICOS],
    CTA_FINAL_DIETAS_POR_PACIENTE.[ESTADO_DIETA_MEDIREST],
    CTA_FINAL_DIETAS_POR_PACIENTE.[ITEM_CORRESPONDIENTE],
    CTA_FINAL_DIETAS_POR_PACIENTE.[ENTIDAD],
    CTA_FINAL_DIETAS_POR_PACIENTE.[REGIMEN],
    CTA_FINAL_DIETAS_POR_PACIENTE.[CATEGORIA],
    CTA_FINAL_DIETAS_POR_PACIENTE.[OBSERVACIONES_INGRESO],
    CTA_FINAL_DIETAS_POR_PACIENTE.CODPROSAL,
    CTA_FINAL_DIETAS_POR_PACIENTE.NOMMEDICO
FROM (
    SELECT
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[INGRESO]) AS [INGRESO],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[NOMBRE_COMPLETO_PACIENTE]) AS [NOMBRE_COMPLETO_PACIENTE],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[IDENTIFICACION]) AS [IDENTIFICACION],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[TIPO_IDENTIFICACION],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[FECHA_NACIMIENTO],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[EDAD_MESES],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[EDAD_A�OS],
        (
            CASE
                WHEN SUBCTA_FINAL_DIETAS_POR_PACIENTE.[EDAD_MESES] = '0'
                    AND SUBCTA_FINAL_DIETAS_POR_PACIENTE.[EDAD_A�OS] = '0' THEN '0 MESES'
                ELSE SUBCTA_FINAL_DIETAS_POR_PACIENTE.[EDAD]
            END
        ) AS [EDAD],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[FECHA_ASIGNACION_UNIDAD/FECHA_INICIAL_ESTANCIA],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[FECHA_INGRESO],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[FECHA_INGRESO_ADMISION],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[FECHA_INICIAL_HOSPITALIZACION],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[CODIGO_UNIDAD_FUNCIONAL]) AS [CODIGO_UNIDAD_FUNCIONAL],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[UNIDAD_FUNCIONAL]) AS [UNIDAD_FUNCIONAL],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[CAMA]) AS [CAMA],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[CLASE_DE_CAMA],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[CLASE_DE_HABITACION],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[VIP],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[DIAS_TRANSCURRIDOS],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[DIAS_DE_HOSPITALIZACION],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[DIAS_EN_LA_UNIDAD],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[TIPO_DE_ESTANCIA]) AS [TIPO_DE_ESTANCIA],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[ESTADO],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[DIAGNOSTICO_PRINCIPAL]) AS [DIAGNOSTICO_PRINCIPAL],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[COUNT_DIETAS],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[ESTADO_DIETA_INDIGO],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[DESCRIPCION_DIETAS]) AS [DESCRIPCION_DIETAS],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[OBSERVACIONES_DIETAS]) AS [OBSERVACIONES_DIETAS],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[ANTECEDENTES_ALERGICOS]) AS [ANTECEDENTES_ALERGICOS],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[ESTADO_DIETA_MEDIREST],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[ITEM_CORRESPONDIENTE],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[ENTIDAD]) AS [ENTIDAD],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.[REGIMEN],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[CATEGORIA]) AS [CATEGORIA],
        TRIM(SUBCTA_FINAL_DIETAS_POR_PACIENTE.[OBSERVACIONES_INGRESO]) AS [OBSERVACIONES_INGRESO],
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.CODPROSAL,
        SUBCTA_FINAL_DIETAS_POR_PACIENTE.NOMMEDICO
    FROM (
        SELECT
            SUBTBL1.[INGRESO],
            SUBTBL1.[NOMBRE_COMPLETO_PACIENTE],
            SUBTBL1.[IDENTIFICACION],
            SUBTBL1.[TIPO_IDENTIFICACION],
            SUBTBL1.[FECHA_NACIMIENTO],
            SUBTBL1.[EDAD_MESES],
            SUBTBL1.[EDAD_A�OS],
            (
                CASE
                    WHEN SUBTBL1.[EDAD_A�OS] = 1 THEN CAST(SUBTBL1.[EDAD_A�OS] AS VARCHAR(5)) + ' ' + 'A�O'
                    WHEN SUBTBL1.[EDAD_A�OS] > 1 THEN CAST(SUBTBL1.[EDAD_A�OS] AS VARCHAR(5)) + ' ' + 'A�OS'
                    WHEN SUBTBL1.[EDAD_A�OS] < 1 THEN (
                        CASE
                            WHEN DATEDIFF(MONTH, SUBTBL1.[FECHA_NACIMIENTO], GETDATE()) % 12 = 1 THEN CAST(
                                DATEDIFF(MONTH, SUBTBL1.[FECHA_NACIMIENTO], GETDATE()) % 12 AS VARCHAR(5)
                            ) + ' ' + 'MES'
                            WHEN DATEDIFF(MONTH, SUBTBL1.[FECHA_NACIMIENTO], GETDATE()) % 12 > 1 THEN CAST(
                                DATEDIFF(MONTH, SUBTBL1.[FECHA_NACIMIENTO], GETDATE()) % 12 AS VARCHAR(5)
                            ) + ' ' + 'MESES'
                            ELSE NULL
                        END
                    )
                    ELSE NULL
                END
            ) AS [EDAD],
            SUBTBL1.[FECHA_ASIGNACION_UNIDAD/FECHA_INICIAL_ESTANCIA],
            SUBTBL1.[FECHA_INGRESO],
            SUBTBL1.[FECHA_INGRESO_ADMISION],
            SUBTBL1.[FECHA_INICIAL_HOSPITALIZACION],
            SUBTBL1.[CODIGO_UNIDAD_FUNCIONAL],
            SUBTBL1.[UNIDAD_FUNCIONAL],
            SUBTBL1.[CAMA],
            SUBTBL1.[CLASE_DE_CAMA],
            SUBTBL1.[CLASE_DE_HABITACION],
            SUBTBL1.[VIP],
            SUBTBL1.[DIAS_TRANSCURRIDOS],
            SUBTBL1.[DIAS_DE_HOSPITALIZACION],
            SUBTBL1.[DIAS_EN_LA_UNIDAD],
            SUBTBL1.[TIPO_DE_ESTANCIA],
            SUBTBL1.[ESTADO],
            SUBTBL1.[DIAGNOSTICO_PRINCIPAL],
            SUBTBL1.[COUNT_DIETAS],
            SUBTBL1.[ESTADO_DIETA_INDIGO],
            SUBTBL1.[DESCRIPCION_DIETAS],
            SUBTBL1.[OBSERVACIONES_DIETAS],
            SUBTBL1.[ANTECEDENTES_ALERGICOS],
            SUBTBL1.[ESTADO_DIETA_MEDIREST],
            SUBTBL1.[ITEM_CORRESPONDIENTE],
            SUBTBL1.[ENTIDAD],
            SUBTBL1.[REGIMEN],
            SUBTBL1.[CATEGORIA],
            SUBTBL1.[OBSERVACIONES_INGRESO],
            SUBTBL1.CODPROSAL,
            SUBTBL1.NOMMEDICO
        FROM
            CTE_CENSO_DIETAS_POR_PACIENTE AS SUBTBL1
        WHERE
            SUBTBL1.[FECHA_ASIGNACION_UNIDAD/FECHA_INICIAL_ESTANCIA] = (
                SELECT
                    MAX(SUBTBL2.[FECHA_ASIGNACION_UNIDAD/FECHA_INICIAL_ESTANCIA]) AS [FECHA_MAX_ESTANCIA]
                FROM
                    CTE_CENSO_DIETAS_POR_PACIENTE AS SUBTBL2
                WHERE
                    SUBTBL1.[INGRESO] = SUBTBL2.[INGRESO]
                GROUP BY
                    SUBTBL2.[INGRESO]
            )
    ) SUBCTA_FINAL_DIETAS_POR_PACIENTE
) CTA_FINAL_DIETAS_POR_PACIENTE
