-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_HISTORICO_ESTANCIAS_CON_USUARIO
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[VW_HISTORICO_ESTANCIAS_CON_USUARIO] AS

WITH CTE_ULTIMA_CAMAS_OCUPADA AS (
    SELECT
        EGR.NUMINGRES,
        EGR.FECINIEST,
        EGR.FECFINEST,
        EGR.CODICAMAS,
        CAM.NUMCAMHOS,
        FUN.UFUDESCRI,
        FUN.UFUTIPUNI,
        FUN.UFUCODIGO,
        'EGRESO' AS TIPINGEST,
        EGR.CODTIPEST,
        TIP.DESTIPEST,
        EGR.GENESTLIQ,
        EGR.ID
    FROM INDIGO036.dbo.CHREGESTA EGR
    INNER JOIN (
        SELECT
            EGR.IPCODPACI,
            EGR.NUMINGRES,
            MAX(EGR.ID) AS ID
        FROM INDIGO036.dbo.CHREGESTA EGR
        GROUP BY EGR.IPCODPACI, EGR.NUMINGRES
    ) AS G ON G.ID = EGR.ID
    INNER JOIN INDIGO036.dbo.CHCAMASHO CAM ON CAM.CODICAMAS = EGR.CODICAMAS
    INNER JOIN INDIGO036.dbo.INUNIFUNC FUN ON CAM.UFUCODIGO = FUN.UFUCODIGO
    INNER JOIN INDIGO036.dbo.CHTIPESTA TIP ON TIP.CODTIPEST = EGR.CODTIPEST
    WHERE EGR.FECFINEST > '1989-01-01 00:00:00.000'
),

CTE_DESTINOS AS (
    SELECT
        ROW_NUMBER() OVER (PARTITION BY NUMINGRES ORDER BY FECHISPAC DESC) AS NUMERO,
        NUMINGRES,
        INDICAPAC
    FROM INDIGO036.dbo.HCHISPACA
),

CTE_DESTINO AS (
    SELECT
        EGR.ID,
        CASE H.INDICAPAC
            WHEN 8 THEN 'TRASLADAR A CIRUGIA'
            WHEN 9 THEN 'HOSPITALIZACION EN CASA'
            WHEN 10 THEN 'REFERENCIA'
            WHEN 11 THEN 'MORGUE'
            WHEN 12 THEN 'SALIDA'
            WHEN 13 THEN 'SALIDA'
            WHEN 15 THEN 'RETIRO VOLUNTARIO'
            WHEN 16 THEN 'FUGA'
        END AS DESTINO
    FROM CTE_ULTIMA_CAMAS_OCUPADA EGR
    INNER JOIN CTE_DESTINOS H ON EGR.NUMINGRES = H.NUMINGRES AND H.NUMERO = 1
)

SELECT
    CAST(DB_NAME() AS VARCHAR(20)) AS ID_COMPANY,
    ROW_NUMBER() OVER (ORDER BY P.IPTIPODOC ASC) AS RN,
    A.IPCODPACI AS [IDENTIFICACIÓN],
    CASE P.IPTIPODOC
        WHEN 1 THEN 'CC' WHEN 2 THEN 'CE' WHEN 3 THEN 'TI'
        WHEN 4 THEN 'RC' WHEN 5 THEN 'PA' WHEN 6 THEN 'AS'
        WHEN 7 THEN 'MS' WHEN 8 THEN 'NU' WHEN 9 THEN 'CN'
        WHEN 10 THEN 'CD' WHEN 11 THEN 'SC' WHEN 12 THEN 'PE'
    END AS [TIPO DE IDENTIFICACIÓN],
    RTRIM(P.IPNOMCOMP) AS PACIENTE,
    CAST(P.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
    FLOOR((CAST(CONVERT(VARCHAR(8), A.FECINIEST, 112) AS INT) - CAST(CONVERT(VARCHAR(8), P.IPFECNACI, 112) AS INT)) / 10000) AS [EDAD AÑOS],
    CASE P.IPSEXOPAC WHEN 2 THEN 'FEMENINO' WHEN 1 THEN 'MASCULINO' END AS GÉNERO,
    A.NUMINGRES AS INGRESO,
    E.NOMENTIDA AS [ENTIDAD PACIENTE],
    (
        SELECT TOP 1 DIG.CODDIAGNO + ' - ' + DIA.NOMDIAGNO
        FROM INDIGO036.dbo.INDIAGNOH DIG
        INNER JOIN INDIGO036.dbo.INDIAGNOS DIA ON DIG.CODDIAGNO = DIA.CODDIAGNO
        WHERE A.NUMINGRES = DIG.NUMINGRES AND DIG.CODDIAPRI = '1'
    ) AS [DIAGNÓSTICO PRINCIPAL],
    CASE P.IPTIPOPAC
        WHEN 1 THEN 'CONTRIBUTIVO'
        WHEN 2 THEN 'SUBSIDIADO'
        WHEN 3 THEN 'VINCULADO'
        WHEN 4 THEN 'PARTICULAR'
        ELSE 'OTRO'
    END AS COBERTURA,
    YEAR(A.FECINIEST) AS AÑO,
    MONTH(A.FECINIEST) AS MES,
    ING.IFECHAING AS [FECHA INGRESO],
    A.FECINIEST AS [FECHA INICIAL DE ESTANCIA],
    CASE WHEN A.FECFINEST > '1989-01-01 00:00:00.000' THEN A.FECFINEST ELSE NULL END AS [FECHA FINAL ESTANCIA],
    CASE WHEN A.FECFINEST > '1989-01-01 00:00:00.000' THEN DATEDIFF(DAY, A.FECINIEST, A.FECFINEST) ELSE NULL END AS [DÍAS DE ESTANCIA],
    CASE WHEN A.FECFINEST > '1989-01-01 00:00:00.000' THEN DATEDIFF(HOUR, A.FECINIEST, A.FECFINEST) ELSE NULL END AS [HORAS DE ESTANCIA],
    RTRIM(B.CODICAMAS) + ' - ' + B.DESCCAMAS AS CAMA,
    C.DESTIPEST AS [TIPO DE ESTANCIA],
    D.UFUCODIGO AS [CÓDIGO UNIDAD],
    D.UFUDESCRI AS [UNIDAD FUNCIONAL],
    CASE A.TIPINGEST
        WHEN 'NU' THEN 'NUEVA UNIDAD'
        WHEN 'TC' THEN 'TRASLADO INTERNO DE CAMA'
    END AS [TIPO INGRESO ESTANCIA],
    CO.TIPINGEST AS [ÚLTIMO ESTADO],
    DST.DESTINO AS [TIPO DE SALIDA],
    1 AS CANTIDAD,
    PR.NOMMEDICO AS USUARIO_REGISTRA,
    ESP.DESESPECI AS ESPECIALIDAD,
    CAST(A.FECREGSIS AS DATE) AS [FECHA BUSQUEDA],
    YEAR(A.FECREGSIS) AS [AÑO FECHA BUSQUEDA],
    MONTH(A.FECREGSIS) AS [MES FECHA BUSQUEDA],
    DATENAME(MONTH, A.FECREGSIS) AS [MES NOMBRE FECHA BUSQUEDA],
    FORMAT(DAY(A.FECREGSIS), '00') AS [DÍA FECHA BUSQUEDA],
    CONCAT(FORMAT(MONTH(A.FECREGSIS), '00'), ' - ', DATENAME(MONTH, A.FECREGSIS)) AS MES_LABEL_INGRESO,
    CONVERT(DATETIME, GETDATE() AT TIME ZONE 'Pakistan Standard Time', 1) AS ULT_ACTUAL
FROM INDIGO036.dbo.CHREGESTA A
INNER JOIN INDIGO036.dbo.CHCAMASHO B ON A.CODICAMAS = B.CODICAMAS
INNER JOIN INDIGO036.dbo.CHTIPESTA C ON A.CODTIPEST = C.CODTIPEST
INNER JOIN INDIGO036.dbo.INUNIFUNC D ON B.UFUCODIGO = D.UFUCODIGO
INNER JOIN INDIGO036.dbo.INPACIENT P ON A.IPCODPACI = P.IPCODPACI
INNER JOIN INDIGO036.dbo.ADINGRESO ING ON A.NUMINGRES = ING.NUMINGRES
INNER JOIN INDIGO036.dbo.INENTIDAD E ON P.CODENTIDA = E.CODENTIDA
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA CO ON A.ID = CO.ID
LEFT JOIN CTE_DESTINO DST ON CO.ID = DST.ID
LEFT JOIN INDIGO036.dbo.INPROFSAL PR ON PR.CODUSUARI = A.REGUSUARI
LEFT JOIN INDIGO036.dbo.INESPECIA ESP ON PR.CODESPEC1 = ESP.CODESPECI
-- WHERE A.IPCODPACI = '1074821091'
--ORDER BY ING.NUMINGRES, FECREGSIS;
