-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_INGRESOSHOSPITALARIOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[VW_INGRESOSHOSPITALARIOS] AS

WITH ESTANCIA_UNICA AS (
    SELECT
        EST.IPCODPACI,
        EST.NUMINGRES,
        MIN(ID) AS ID
    FROM INDIGO036.dbo.CHREGESTA AS EST
    GROUP BY
        EST.IPCODPACI,
        EST.NUMINGRES
),
CTE_INGRESOS_HOSPITALARIOS AS (
    SELECT
        CEN.NOMCENATE AS [CENTRO ATENCION],
        CASE UNI.UFUTIPUNI
            WHEN 1 THEN 'URGENCIAS'
            WHEN 2 THEN 'HOSPITALIZACION'
            WHEN 3 THEN 'APOYO DIAGNOSTICO'
            WHEN 4 THEN 'APOYO TERAPEUTICO'
            WHEN 5 THEN 'UCI'
            WHEN 6 THEN 'UCI'
            WHEN 7 THEN 'UCI'
            WHEN 8 THEN 'UCI'
            WHEN 9 THEN 'UCI'
            WHEN 10 THEN 'UCI'
            WHEN 11 THEN 'UCI'
            WHEN 12 THEN 'UNIDAD RENAL'
            WHEN 13 THEN 'UNIDAD ONCOLOGICA'
            WHEN 14 THEN 'UNIDAD MEDICINA NUCLEAR'
            WHEN 15 THEN 'CONSULTA EXTERNA'
            WHEN 16 THEN 'UNIDAD MENTAL'
            WHEN 17 THEN 'UNIDAD DE QUEMADOS'
            WHEN 18 THEN 'UNIDAD DE CUIDADOS PALATIVOS'
            WHEN 19 THEN 'CIRUGIA'
            WHEN 20 THEN 'LABORATORIOS'
            WHEN 21 THEN 'CARDIOLOGIA NO INVASIVA'
            WHEN 22 THEN 'CARDIOLOGIA INVASIVA'
            WHEN 23 THEN 'GINECO OBSTETRICIA'
            WHEN 24 THEN 'CONSULTA EXTERNA GINECO OBSTETRICIA'
            WHEN 30 THEN 'OTRAS'
            WHEN 31 THEN 'CONSULTA PRIORITARIA'
        END AS [TIPO UNIDAD],
        UNI.UFUDESCRI AS [UNIDAD FUNCIONAL],
        CASE EST.CODTIPEST
            WHEN '001' THEN 'GENERAL'
            WHEN '002' THEN 'CUIDADO BASICO'
            WHEN '003' THEN 'CUIDADO INTERMEDIO'
            ELSE 'CUIDADO INTENSIVO'
        END AS [TIPO ESTANCIA],
        HEA.Code AS [CODIGO ENTIDAD],
        HEA.Name AS [ENTIDAD],
        CGR.Name AS [GRUPO DE ATENCION],
        CASE PAC.IPTIPOPAC
            WHEN 1 THEN 'CONTRIBUTIVO'
            WHEN 2 THEN 'SUBSIDIADO'
            WHEN 3 THEN 'VINCULADO'
            WHEN 4 THEN 'PARTICULAR'
            WHEN 5 THEN 'OTRO'
            WHEN 6 THEN 'DESPLAZADO REG. CONTRIBUTIVO'
            WHEN 7 THEN 'DESPLAZADO REG. SUBSIDIADO'
            ELSE 'DESPLAZADO NO ASEGURADO'
        END AS [RÉGIMEN],
        CAM.NUMCAMHOS AS [CAMA],
        CAM.DESCCAMAS AS [DESCRIPCION CAMA],
        CASE PAC.IPTIPODOC
            WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI'
            WHEN '4' THEN 'RC' WHEN '5' THEN 'PA' WHEN '6' THEN 'AS'
            WHEN '7' THEN 'MS' WHEN '8' THEN 'NU' WHEN '9' THEN 'NV'
            WHEN '10' THEN 'CD' WHEN '11' THEN 'SC' WHEN '12' THEN 'PE'
        END AS [TIPO IDENTIFICACION],
        CASE PAC.IPTIPODOC
            WHEN '1' THEN 'CEDULA DE CIUDADANIA'
            WHEN '2' THEN 'CEDULA DE EXTRANJERIA'
            WHEN '3' THEN 'TARJETA DE IDENTIDAD'
            WHEN '4' THEN 'REGISTRO CIVIL'
            WHEN '5' THEN 'PASAPORTE'
            WHEN '6' THEN 'ADULTO SIN IDENTIFICACION'
            WHEN '7' THEN 'MENOR SIN IDENTIFICACION'
            WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACIÓN'
            WHEN '9' THEN 'CERTIFICADO NACIDO VIVO'
            WHEN '10' THEN 'CARNET DIPLOMATICO'
            WHEN '11' THEN 'SALVOCONDUCTO'
            WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA'
        END AS [DESCRIPCION IDENTIFICACION],
        EST.IPCODPACI AS [IDENTIFICACION],
        PAC.IPPRINOMB AS [PRIMER NOMBRE],
        PAC.IPSEGNOMB AS [SEGUNDO NOMBRE],
        PAC.IPPRIAPEL AS [PRIMER APELLIDO],
        PAC.IPSEGAPEL AS [SEGUNDO APELLIDO],
        PAC.IPNOMCOMP AS [NOMBRE COMPLETO PACIENTE],
        PAC.IPFECNACI AS [FECHA NACIMIENTO],
        FLOOR((CAST(CONVERT(VARCHAR(8), EST.FECINIEST, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS EDAD,
        CASE WHEN PAC.IPSEXOPAC = '1' THEN 'M' ELSE 'F' END AS SEXO,
        PAC.IPTELMOVI AS [MOVIL],
        PAC.IPTELEFON AS [TELEFONO],
        PAC.IPDIRECCI AS [DIRECCION],
        EST.NUMINGRES AS [INGRESO],
        ISNULL(DIS.DISCDESCRI, 'NINGUNO') AS [DISCAPACIDAD],
        CAST(EST.FECINIEST AS DATE) AS [FECHA INICIAL ESTANCIA],
        PRO.NOMMEDICO AS [PROFESIONAL DE LA SALUD],
        ESP.DESESPECI AS [ESPECIALIDAD],
        ING.CODDIAING AS [CIE10 INGRESO],
        DIA.NOMDIAGNO AS [DIAGNOSTICO DE INGRESO],
        ING.CODDIAEGR AS [CIE10 EGRESO],
        DIAE.NOMDIAGNO AS [DIAGNOSTICO DE EGRESO],
        1 AS [CANTIDAD],
        CAST(EST.FECINIEST AS DATE) AS [FECHA BUSQUEDA],
        YEAR(EST.FECINIEST) AS [AÑO BUSQUEDA],
        MONTH(EST.FECINIEST) AS [MES BUSQUEDA],
        CONCAT(
            FORMAT(MONTH(EST.FECINIEST), '00'), ' - ',
            DATENAME(MONTH, EST.FECINIEST)
        ) AS [MES NOMBRE BUSQUEDA],
        CONVERT(DATETIME, GETDATE() AT TIME ZONE 'Pakistan Standard Time', 1) AS ULT_ACTUAL
    FROM INDIGO036.dbo.CHREGESTA AS EST
    INNER JOIN ESTANCIA_UNICA AS EU ON EU.ID = EST.ID
    INNER JOIN INDIGO036.dbo.INPACIENT AS PAC ON PAC.IPCODPACI = EST.IPCODPACI
    LEFT JOIN INDIGO036.dbo.ADDISCAPACI DIS ON DIS.DISCCODIGO = PAC.DISCCODIGO
    INNER JOIN INDIGO036.dbo.ADINGRESO AS ING ON ING.IPCODPACI = EST.IPCODPACI AND ING.NUMINGRES = EST.NUMINGRES
    INNER JOIN INDIGO036.dbo.CHCAMASHO CAM ON EST.CODICAMAS = CAM.CODICAMAS
    INNER JOIN INDIGO036.dbo.ADCENATEN AS CEN ON CAM.CODCENATE = CEN.CODCENATE
    INNER JOIN INDIGO036.dbo.INUNIFUNC UNI ON CAM.UFUCODIGO = UNI.UFUCODIGO
    INNER JOIN INDIGO036.Contract.HealthAdministrator HEA ON ING.GENCONENTITY = HEA.Id
    INNER JOIN INDIGO036.Contract.CareGroup AS CGR ON ING.GENCAREGROUP = CGR.Id
    LEFT JOIN INDIGO036.dbo.INPROFSAL PRO ON EST.CODPROSAL = PRO.CODPROSAL
    LEFT JOIN INDIGO036.dbo.INESPECIA ESP ON ESP.CODESPECI = EST.CODESPECI
    LEFT JOIN INDIGO036.dbo.INDIAGNOS DIA ON ING.CODDIAING = DIA.CODDIAGNO
    LEFT JOIN INDIGO036.dbo.INDIAGNOS DIAE ON ING.CODDIAEGR = DIAE.CODDIAGNO
)

SELECT
    CAST(DB_NAME() AS VARCHAR(20)) AS ID_COMPANY,
    *
FROM CTE_INGRESOS_HOSPITALARIOS;