-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_INFORME_DE_ATENCIONES
-- Extracted by Fabric SQL Extractor SPN v3.9.0

/****** Script for SelectTopNRows command from SSMS ******/
CREATE VIEW [Report].[VW_INFORME_DE_ATENCIONES] AS

SELECT DISTINCT
    ING.[ID_COMPANY],
    ING.[CENTRO ATENCION],
    ING.[INGRESO],
    ING.[FECHA INGRESO],
    ING.[ESTADO INGRESO],
    ING.[TIPO INGRESO],
    ING.[TIPO IDENTIFICACION],
    ING.[SEXO],
    ING.[FECHA NACIMIENTO],
    ING.[EDAD],
    ING.[DIRECCION],
    ING.[TELEFONO],
    ING.[MOVIL],
    ING.[IDENTIFICACION],
    ING.[PACIENTE],
    ING.[COD U FUNCIONAL],
    ING.[UNIDAD FUNCIONAL],
    ING.[FECHA ALTA MEDICA],
    ING.[FECHA EGRESO CAMA],
    ING.[CAMA],
    ING.[CODIGO ENTIDAD],
    ING.[ENTIDAD],
    ING.[CODIGO GRUPO ATENCION],
    ING.[GRUPO DE ATENCION],
    ING.[TOTAL FOLIO],
    ING.[USUARIO CREO],
    ING.[USUARIO ANULO],
    ING.[CIE10],
    ING.[DIAGNOSTICO],
    ING.[CANTIDAD],
    ING.[FECHA BUSQUEDA],
    ING.[AÑO FECHA BUSQUEDA],
    ING.[MES AÑO FECHA BUSQUEDA],
    ING.[MES NOMBRE FECHA BUSQUEDA],
    ING.[DIA FECHA BUSQUEDA],
    ING.[ULT_ACTUAL],
    DAT.PESO,
    DAT.[TALLA]
FROM [Report].[VW_ESTADISTICO_INGRESOS] AS ING
LEFT JOIN (
    SELECT
        IDENTIFICACION,
        [TIPO DOCUMENTO],
        MAX([FECHA ATENCION]) AS FECHA_ATENCION,
        MAX(PESO)            AS PESO,
        MAX([TALLA ])        AS [TALLA]   -- nota: el origen tiene un espacio en el nombre
    FROM [Report].[VW_REPORTE_SISMANA]
    GROUP BY IDENTIFICACION, [TIPO DOCUMENTO]
) AS DAT
    ON  ING.IDENTIFICACION        = DAT.IDENTIFICACION
    AND ING.[TIPO IDENTIFICACION] = DAT.[TIPO DOCUMENTO]
;