-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_NONSURGICALPROCEDURESREQUESTS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[VW_NONSURGICALPROCEDURESREQUESTS] AS

WITH CTE_PROCEDIMIENTOS_NOQX AS (
    SELECT
        A.NUMINGRES,
        A.UFUCODIGO,
        A.CODPROSAL,
        CODSERIPS,
        IDDESCRIPCIONRELACIONADA,
        IDAREAPRO,
        MEDREALI,
        ESPEREALI,
        A.UFUCODIGOPRO,
        A.CODPROINT,
        A.NUMFOLINT,
        A.ESTSERIPS,
        A.MANEXTPRO,
        A.NUMEFOLIO,
        A.FECORDMED,
        A.CANSERIPS,
        A.OBSSERIPS,
        FECHREALI,
        A.FECHAPRO,
        A.GENSERVICEORDER
    FROM
        INDIGO036.dbo.HCORDPRON A
        INNER JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON A.CODSERIPS = CUPS.Code
    WHERE
        CUPS.Description NOT LIKE '%TERAPIAS%'
    UNION ALL
    SELECT
        A.NUMINGRES,
        '' AS UFUCODIGO,
        '' AS CODPROSAL,
        A.CODSERIPS,
        A.IDDESCRIPCIONRELACIONADA,
        A.IDAREAPRO,
        A.MEDICOREALI AS MEDREALI,
        HC.CODESPTRA AS ESPEREALI,
        A.UFUCODIGOPRO,
        A.CODPROSALINT AS CODPROINT,
        A.NUMEFOLIOINT AS NUMFOLINT,
        A.ESTADO AS ESTSERIPS,
        '' AS MANEXTPRO,
        '' AS NUMEFOLIO,
        A.FECHAREG AS FECORDMED,
        A.CANTIDAD AS CANSERIPS,
        '' AS OBSSERIPS,
        A.FECHAREALI,
        A.FECHAPRO,
        A.GENSERVICEORDER
    FROM
        INDIGO036.dbo.AMBORDOTROSPRO A
        INNER JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON A.CODSERIPS = CUPS.Code
        INNER JOIN INDIGO036.dbo.HCHISPACA HC ON A.NUMINGRES = HC.NUMINGRES
            AND HC.NUMEFOLIO = (
                SELECT
                    MAX(H.NUMEFOLIO)
                FROM
                    INDIGO036.dbo.HCHISPACA H
                WHERE
                    A.NUMINGRES = H.NUMINGRES
            )
    WHERE
        CUPS.Description NOT LIKE '%TERAPIAS%'
),
CTE_DIAGNOSTICOS AS (
    SELECT
        NOH.NUMINGRES,
        NOS.CODDIAGNO,
        NOS.NOMDIAGNO,
        CASE
            NOP.ESTADIO
            WHEN 0 THEN 'ESTADIO CLÍNICO (EC) 0 (TUMOR IN SITU)'
            WHEN 1 THEN 'EC I O 1'
            WHEN 2 THEN 'EC IA O 1A'
            WHEN 3 THEN 'EC IA1'
            WHEN 4 THEN 'EC IA2'
            WHEN 5 THEN 'EC IB O 1B'
            WHEN 6 THEN 'EC IB1'
            WHEN 7 THEN 'EC IB2'
            WHEN 8 THEN 'EC IC O 1C'
            WHEN 9 THEN 'EC IS O 1S'
            WHEN 10 THEN 'EC II O 2'
            WHEN 11 THEN 'EC IIA O 2A'
            WHEN 12 THEN 'EC IIA1'
            WHEN 13 THEN 'EC IIA2'
            WHEN 14 THEN 'EC IIB O 2B'
            WHEN 15 THEN 'EC IIC O 2C'
            WHEN 16 THEN 'EC III O 3'
            WHEN 17 THEN 'EC IIIA O 3A'
            WHEN 18 THEN 'EC IIIB O 3B'
            WHEN 19 THEN 'EC IIIC O 3C'
            WHEN 20 THEN 'EC IV O 4'
            WHEN 21 THEN 'EC IVA O 4A'
            WHEN 22 THEN 'EC IVB O 4B'
            WHEN 23 THEN 'EC IVC O 4C'
            WHEN 24 THEN 'EC 4S (PARA NEUROBLASTOMA)'
            WHEN 25 THEN 'EC  V O 5'
            WHEN 26 THEN 'EC ESTADIO IAB'
            WHEN 55 THEN 'PERSONA CON ASEGURAMIENTO (RÉGIMEN SUBSIDIADO O CONTRIBUTIVO Y QUE NO SON PPNA) QUE RECIBIÓ SERVICIOS DE SALUD POR PARTE DEL ENTE TERRITORIALDURANTE EL PERIODO DE REPORTE'
            WHEN 93 THEN 'SIN INFORMACIÓN DE ESTADIFICACIÓN EN HISTORIA CLÍNICA'
            WHEN 98 THEN 'NO APLICA (ES CÁNCER DE PIEL BASOCELULAR, ES CÁNCER HEMATOLÓGICO O ES CÁNCER EN SNC, EXCEPTO NEUROBLASTOMA)'
            WHEN 99 THEN 'DESCONOCIDO, EL DATO DE ESTA VARIABLE NO SE ENCUENTRA DESCRITO EN LOS SOPORTES CLÍNICOS'
            ELSE ''
        END AS ESTADIO
    FROM
        INDIGO036.dbo.INDIAGNOH NOH
        INNER JOIN INDIGO036.dbo.INDIAGNOS NOS ON NOH.CODDIAGNO = NOS.CODDIAGNO
            AND NOH.CODDIAPRI = 1
            AND NOH.NUMEFOLIO = (
                SELECT
                    MAX(DIA.NUMEFOLIO)
                FROM
                    INDIGO036.dbo.INDIAGNOH DIA
                WHERE
                    NOH.NUMINGRES = DIA.NUMINGRES
                    AND DIA.CODDIAPRI = 1
            )
        LEFT JOIN INDIGO036.dbo.INDIAGNOP NOP ON NOH.NUMINGRES = NOP.NUMINGRES
            AND NOH.NUMEFOLIO = NOP.NUMEFOLIO
            AND NOP.CODDIAPRI = 1
),
CTE_CONTRATOS AS (
    SELECT
        CG.Code,
        CE.Code AS CUPS,
        CASE
            PC.Contracted
            WHEN 1 THEN 'SI'
            ELSE 'NO'
        END AS CONTRATADO,
        CASE
            PC.Quoted
            WHEN 1 THEN 'SI'
            ELSE 'NO'
        END AS COTIZADO,
        CECD.Id AS IDRELACION
    FROM
        INDIGO036.Contract.CareGroup AS CG
        INNER JOIN INDIGO036.Contract.ProcedureTemplate AS PT ON CG.ProcedureTemplateId = PT.Id
        INNER JOIN INDIGO036.Contract.ProcedureCups AS PC ON PT.Id = PC.ProceduresTemplateId
        INNER JOIN INDIGO036.Contract.CUPSEntity AS CE ON PC.CupsId = CE.Id
        LEFT JOIN INDIGO036.Contract.CUPSEntityContractDescriptions AS CECD ON PC.CUPSEntityContractDescriptionId = CECD.Id
)
SELECT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    CEN.NOMCENATE AS [CENTRO DE ATENCION],
    IDE.SIGLA AS [TIPO DE IDENTIFICACION],
    PAC.IPCODPACI AS IDENTIFICACION,
    PAC.IPNOMCOMP AS PACIENTE,
    CAST(PAC.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
    CAST(
        (DATEDIFF(M, PAC.IPFECNACI, GETDATE()) / 12) as varchar
    ) + ' Años ' + cast(
        (DATEDIFF(M, PAC.IPFECNACI, GETDATE()) % 12) as varchar
    ) + ' Meses' as EDAD,
    CASE
        PAC.IPSEXOPAC
        WHEN '1' THEN 'MASCULINO'
        ELSE 'FEMENINO'
    END AS [SEXO],
    PAC.IPTELEFON AS [TELEFONO FIJO],
    PAC.IPTELMOVI AS [TELEFONO MOVIL],
    PAC.IPDIRECCI AS DIRECCION,
    EA.HealthEntityCode [CODIGO EPS/ENTIDAD TERRITORIAL],
    EA.Name AS [ENTIDAD ADMINISTRADORA],
    GA.Code [CODIGO GRUPO ATENCION],
    GA.Code + ' - ' + GA.Name [GRUPO ATENCION],
    CASE
        GA.LiquidationType
        WHEN 1 THEN 'PAGO POR SERVICIOS'
        WHEN 2 THEN 'PGP'
        WHEN 3 THEN 'FACTURA GLOBAL'
        WHEN 4 THEN 'CAPITACION GLOBAL'
        WHEN 5 THEN 'CONTROL'
    END [TIPO CONTRATO],
    IIF(CON.Code IS NULL, 'NO', 'SI') CUBIERTO,
    ISNULL(CON.CONTRATADO, 'NO') CONTRATADO,
    ISNULL(CON.COTIZADO, 'NO') COTIZADO,
    CASE
        ING.TIPOINGRE
        WHEN 1 THEN 'Ambulatorio'
        WHEN 2 THEN 'Hospitalario'
    END AS [AMBITO DE INGRESO],
    ISNULL(ARE.DESAREA, 'PROCEDIMIENTO NO QX') AS [TIPO ORDEN],
    RTRIM(NOQX.UFUCODIGO) + ' - ' + RTRIM(FUN.UFUDESCRI) AS [UNIDAD FUNCIONAL],
    ING.CODCAMACT AS CAMA,
    NOQX.NUMINGRES AS INGRESO,
    NOQX.NUMEFOLIO AS FOLIO,
    NOQX.CODSERIPS AS [CODIGO CUPS],
    RTRIM(CUPS.Description) AS [DESCRIPCION SERVICIO],
    CG.Code + '-' + CG.Name [GRUPO],
    CSG.Code + '-' + CSG.Name [SUBGRUPO],
    ISNULL(CD.Code + ' - ' + CD.Name, '') [DESCRIPCION RELACIONADA],
    IIF(
        NOQX.MANEXTPRO = 1,
        'Extramural',
        IIF(
            PRONOQX.NUMINGRES IS NULL,
            CASE
                WHEN NOQX.ESTSERIPS = '1'
                AND NOQX.GENSERVICEORDER IS NULL THEN 'Ordenado'
                WHEN NOQX.ESTSERIPS = '1'
                AND NOQX.GENSERVICEORDER IS NOT NULL THEN 'Completado'
                ELSE CASE
                    NOQX.ESTSERIPS
                    WHEN '2' THEN 'Completado'
                    WHEN '3' THEN 'Interpretado'
                    WHEN '4' THEN 'Realizados'
                    WHEN '5' THEN 'Anulado'
                END
            END,
            'Realizados'
        )
    ) AS ESTADO,
    NOQX.CANSERIPS AS [CANTIDAD ORDEN],
    PRO.CODPROSAL AS [ID PROFESIONAL SOLICITUD],
    PRO.NOMMEDICO AS [PROFESIONAL SOLICITUD],
    ESP.CODESPECI + ' - ' + ESP.DESESPECI AS [ESPECIALIDAD SOLICITUD],
    NOQX.OBSSERIPS AS [OBSERVACION SOLICITUD],
    DIA.CODDIAGNO AS [CODIGO DX PRINCIPAL SOLICITUD],
    DIA.NOMDIAGNO AS [DX PRINCIPAL SOLICITUD],
    DIA.ESTADIO,
    CAST(NOQX.FECORDMED AS DATE) AS [FECHA ORDEN],
    CAST(NOQX.FECORDMED AS TIME) AS [HORA ORDEN],
    ISNULL(
        CAST(HCOTR.FECHISPAC AS DATE),
        ISNULL(
            CAST(NOQX.FECHREALI AS DATE),
            CAST(NOQX.FECHAPRO AS DATE)
        )
    ) AS [FECHA REALIZACIÓN],
    ISNULL(
        CAST(HCOTR.FECHISPAC AS TIME),
        ISNULL(
            CAST(NOQX.FECHREALI AS TIME),
            CAST(NOQX.FECHAPRO AS TIME)
        )
    ) AS [HORA REALIZACIÓN],
    ISNULL(HCOTR.CODPROSAL, NOQX.MEDREALI) AS [ID PROFESIONAL REALIZACIÓN],
    ISNULL(PROTR.NOMMEDICO, PRORE.NOMMEDICO) AS [PROFESIONAL REALIZACIÓN],
    ISNULL(INEOTR.DESESPECI, INERE.DESESPECI) AS [ESPECIALIDAD REALIZACIÓN],
    ISNULL(
        RTRIM(FUNOTR.UFUCODIGO) + ' - ' + FUNOTR.UFUDESCRI,
        RTRIM(FUNRE.UFUCODIGO) + ' - ' + FUNRE.UFUDESCRI
    ) AS [UNIDAD FUNCIONAL REALIZACIÓN],
    HCOTR.NUMEFOLIO AS [FOLIO REALIZACIÓN],
    CAST(HCIN.FECHISPAC AS DATE) AS [FECHA INTERPRETACIÓN],
    CAST(HCIN.FECHISPAC AS TIME) AS [HORA INTERPRETACIÓN],
    PROIN.CODPROSAL AS [ID PROFESIONAL INTERPRETACIÓN],
    PROIN.NOMMEDICO AS [PROFESIONAL INTERPRETACIÓN],
    INEIN.DESESPECI AS [ESPECIALIDAD INTERPRETACIÓN],
    RTRIM(FUNIN.UFUCODIGO) + ' - ' + FUNIN.UFUDESCRI AS [UNIDAD FUNCIONAL INTERPRETACIÓN],
    NOQX.NUMFOLINT AS [FOLIO INTERPRETACIÓN],
    CAST(NOQX.FECORDMED AS date) AS 'FECHA BUSQUEDA',
    YEAR(NOQX.FECORDMED) AS 'AÑO BUSQUEDA',
    MONTH(NOQX.FECORDMED) AS 'MES BUSQUEDA',
    CONCAT(
        FORMAT(MONTH(NOQX.FECORDMED), '00'),
        ' - ',
        CASE
            MONTH(NOQX.FECORDMED)
            WHEN 1 THEN 'ENERO'
            WHEN 2 THEN 'FEBRERO'
            WHEN 3 THEN 'MARZO'
            WHEN 4 THEN 'ABRIL'
            WHEN 5 THEN 'MAYO'
            WHEN 6 THEN 'JUNIO'
            WHEN 7 THEN 'JULIO'
            WHEN 8 THEN 'AGOSTO'
            WHEN 9 THEN 'SEPTIEMBRE'
            WHEN 10 THEN 'OCTUBRE'
            WHEN 11 THEN 'NOVIEMBRE'
            WHEN 12 THEN 'DICIEMBRE'
        END
    ) 'MES NOMBRE BUSQUEDA',
    CONVERT(
        DATETIME,
        GETDATE() AT TIME ZONE 'Pakistan Standard Time',
        1
    ) AS ULT_ACTUAL
FROM
    CTE_PROCEDIMIENTOS_NOQX NOQX
    INNER JOIN INDIGO036.dbo.ADINGRESO ING ON NOQX.NUMINGRES = ING.NUMINGRES
    INNER JOIN INDIGO036.dbo.ADCENATEN CEN ON ING.CODCENATE = CEN.CODCENATE
    INNER JOIN INDIGO036.dbo.INPACIENT PAC ON ING.IPCODPACI = PAC.IPCODPACI
    INNER JOIN INDIGO036.dbo.ADTIPOIDENTIFICA IDE ON PAC.IPTIPODOC = IDE.CODIGO
    INNER JOIN INDIGO036.Contract.HealthAdministrator EA ON ING.GENCONENTITY = EA.Id
    INNER JOIN INDIGO036.Contract.CareGroup AS GA ON ING.GENCAREGROUP = GA.Id
    INNER JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON NOQX.CODSERIPS = CUPS.Code
    INNER JOIN INDIGO036.Contract.CupsSubgroup AS CSG ON CUPS.CUPSSubGroupId = CSG.Id
    INNER JOIN INDIGO036.Contract.CupsGroup AS CG ON CG.Id = CSG.CupsGroupId
    LEFT JOIN (
        SELECT
            A.NUMINGRES,
            B.CODSERIPS,
            A.IDHCHISPACA
        FROM
            INDIGO036.dbo.HCPLAOTRPROC A
            INNER JOIN INDIGO036.dbo.HCPLAOTRPROCUPS B on A.ID = B.IDHCPLAOTRPROC
    ) PRONOQX ON NOQX.NUMINGRES = PRONOQX.NUMINGRES
        AND NOQX.CODSERIPS = PRONOQX.CODSERIPS
        AND NOQX.MANEXTPRO != 1
        AND NOQX.ESTSERIPS = 4
    LEFT JOIN INDIGO036.Contract.CUPSEntityContractDescriptions CECD ON NOQX.IDDESCRIPCIONRELACIONADA = CECD.Id
    LEFT JOIN INDIGO036.Contract.ContractDescriptions CD ON CECD.ContractDescriptionId = CD.Id
    LEFT JOIN INDIGO036.dbo.INUNIFUNC FUN ON NOQX.UFUCODIGO = FUN.UFUCODIGO
    LEFT JOIN INDIGO036.dbo.INPROFSAL PRO ON NOQX.CODPROSAL = PRO.CODPROSAL
    LEFT JOIN INDIGO036.dbo.INESPECIA ESP ON PRO.CODESPEC1 = ESP.CODESPECI
    LEFT JOIN INDIGO036.dbo.HCAREASC ARE ON NOQX.IDAREAPRO = ARE.ID
    LEFT JOIN CTE_DIAGNOSTICOS DIA ON NOQX.NUMINGRES = DIA.NUMINGRES
    LEFT JOIN CTE_CONTRATOS CON ON GA.Code = CON.Code
        AND NOQX.CODSERIPS = CON.CUPS
        AND NOQX.IDDESCRIPCIONRELACIONADA = CON.IDRELACION
    LEFT JOIN INDIGO036.dbo.INPROFSAL PRORE ON NOQX.MEDREALI = PRORE.CODPROSAL
    LEFT JOIN INDIGO036.dbo.INESPECIA INERE ON NOQX.ESPEREALI = INERE.CODESPECI
    LEFT JOIN INDIGO036.dbo.INUNIFUNC FUNRE ON NOQX.UFUCODIGOPRO = FUNRE.UFUCODIGO
    LEFT JOIN INDIGO036.dbo.INPROFSAL PROIN ON NOQX.CODPROINT = PROIN.CODPROSAL
    LEFT JOIN INDIGO036.dbo.INESPECIA INEIN ON PROIN.CODESPEC1 = INEIN.CODESPECI
    LEFT JOIN INDIGO036.dbo.HCHISPACA HCIN ON NOQX.NUMINGRES = HCIN.NUMINGRES
        AND NOQX.NUMFOLINT = HCIN.NUMEFOLIO
    LEFT JOIN INDIGO036.dbo.INUNIFUNC FUNIN ON HCIN.UFUCODIGO = FUNIN.UFUCODIGO
    LEFT JOIN INDIGO036.dbo.HCHISPACA HCOTR ON PRONOQX.IDHCHISPACA = HCOTR.ID
    LEFT JOIN INDIGO036.dbo.INPROFSAL PROTR ON HCOTR.CODPROSAL = PROTR.CODPROSAL
    LEFT JOIN INDIGO036.dbo.INUNIFUNC FUNOTR ON HCOTR.UFUCODIGO = FUNOTR.UFUCODIGO
    LEFT JOIN INDIGO036.dbo.INESPECIA INEOTR ON HCOTR.CODESPTRA = INEOTR.CODESPECI