-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_OCUPACION_CAMAS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[VW_OCUPACION_CAMAS] AS


WITH CTE_CAMAS AS (
    SELECT
        A.IPCODPACI,
        A.NUMINGRES,
        B.UFUDESCRI,
        C.NUMCAMHOS,
        CASE A.ESTADOCAMA
            WHEN 1 THEN 'Libre'
            WHEN 2 THEN 'Asignada'
            WHEN 3 THEN 'Inactiva'
            WHEN 4 THEN 'Bloqueada'
        END AS ESTADO,
        A.FECHAINICIAL,
        A.FECHAFINAL,
        A.FECHACREACION AS FECHA_FOTO
    FROM
        INDIGO036.dbo.CHCAMATRAZA A
        LEFT JOIN INDIGO036.dbo.INUNIFUNC B ON A.UFUCODIGO = B.UFUCODIGO
        LEFT JOIN INDIGO036.dbo.CHCAMASHO C ON A.CODICAMAS = C.CODICAMAS
),
CTE_HISTORIA_CLINICA AS (
    SELECT
        ROW_NUMBER() OVER (
            PARTITION BY NUMINGRES
            ORDER BY FECHISPAC DESC
        ) AS NUMERO,
        IPCODPACI,
        NUMINGRES,
        FECHISPAC,
        INDICAPAC
    FROM INDIGO036.dbo.HCHISPACA
)
SELECT
    CAM.NUMINGRES AS INGRESO,
    CAM.IPCODPACI AS HC,
    CAM.UFUDESCRI AS UFN,
    CAM.NUMCAMHOS AS CAMA,
    CAM.ESTADO,
    CAM.FECHAINICIAL,
    CAM.FECHAFINAL,
    CAM.FECHA_FOTO,
    CASE
        WHEN HIS.INDICAPAC = 11 THEN 'FALLECIDO'
        ELSE 'VIVO'
    END AS ESTADO_PACIENTE
FROM
    CTE_CAMAS CAM
    LEFT JOIN CTE_HISTORIA_CLINICA HIS ON HIS.NUMINGRES = CAM.NUMINGRES
    AND HIS.NUMERO = 1
WHERE
    CAM.UFUDESCRI NOT IN (
        'HEMODINAMIA',
        'URGENCIAS OBSERVACION',
        'SALAS DE CIRUGIA',
        'URGENCIAS ONCOLOGIA'
    )