-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_PROCEDIMIENTOSMENORES
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_PROCEDIMIENTOSMENORES AS

WITH CTE_PROCEDIMIENTOS AS (
    SELECT
        NOQ.IPCODPACI,
        NOQ.NUMINGRES,
        NOQ.NUMEFOLIO,
        NOQ.CODSERIPS,
        NOQ.UFUCODIGO,
        NOQ.FECORDMED,
        NOQ.ESTSERIPS,
        NOQ.CODDIAGNO,
        NOQ.CODPROSAL,
        NOQ.FECHAPRO,
        NOQ.MEDREALI + ' - ' + PROF.NOMMEDICO AS [MEDICO DE REALIZACION]
    FROM INDIGO036.dbo.HCORDPRON NOQ
        LEFT JOIN INDIGO036.dbo.INPROFSAL PROF ON NOQ.MEDREALI = PROF.CODPROSAL
    WHERE NOQ.CODSERIPS IN (
        '881202', '881203', '881204', '881206', '881207', '881208',
        '881209', '881210', '881214', '894102', '895001', '895004',
        '895005', '895100'
    )

    UNION ALL

    SELECT
        QX.IPCODPACI,
        QX.NUMINGRES,
        QX.NUMEFOLIO,
        QX.CODSERIPS,
        QX.UFUCODIGO,
        QX.FECORDMED,
        QX.ESTSERIPS,
        QX.CODDIAGNO,
        QX.CODPROSAL,
        QX.FECHAPRO,
        QX.MEDREALI + ' - ' + PROF.NOMMEDICO AS [MEDICO DE REALIZACION]
    FROM INDIGO036.dbo.HCORDPROQ QX
        LEFT JOIN INDIGO036.dbo.INPROFSAL PROF ON QX.MEDREALI = PROF.CODPROSAL
    WHERE QX.CODSERIPS IN (
        '881202', '881203', '881204', '881206', '881207', '881208',
        '881209', '881210', '881214', '894102', '895001', '895004',
        '895005', '895100'
    )
)

SELECT DISTINCT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    PROCE.IPCODPACI AS [ID PACIENTE],
    INP.IPNOMCOMP AS [NOMBRE PACIENTE],
    DATEDIFF(YEAR, INP.IPFECNACI, PROCE.FECHAPRO) AS [AÑOS],
    DATEDIFF(MONTH, INP.IPFECNACI, PROCE.FECHAPRO) AS [MESES],
    PROCE.NUMINGRES AS [INGRESO/EVENTO],
    PROCE.NUMEFOLIO AS [NUMERO DE FOLIO],
    PROCE.UFUCODIGO AS [COD. UF],
    FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
    CASE
        WHEN FUN.UFUTIPUNI IN (1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 17, 18, 19, 21, 22, 35)
            THEN 'Hospitalario'
        ELSE 'Ambulatorio'
    END AS [AMBITO DE SOLICITUD],
    PROCE.FECORDMED AS [FECH. ORDEN MEDICA],
    PROCE.CODSERIPS AS [COD. CUPS],
    CUPS.DESCODCUPS AS [NOMBRE CUPS],
    CASE
        WHEN PROCE.FECHAPRO IS NOT NULL THEN 'Completado'
        ELSE 'Solicitado'
    END AS [ESTADO],
    PROCE.CODDIAGNO AS [CODIGO CIE-10],
    DIA.NOMDIAGNO AS [DESCRIPCION CIE-10],
    PROCE.CODPROSAL AS [COD. PROFESIONAL],
    PROF.NOMMEDICO AS [NOMBRE PROFESIONAL],
    PROCE.FECHAPRO AS [FECHA DE REALIZACION],
    PROCE.[MEDICO DE REALIZACION],
    CAST(PROCE.FECORDMED AS DATE) AS [FECHA BUSQUEDA],
    YEAR(PROCE.FECORDMED) AS [AÑO FECHA BUSQUEDA],
    MONTH(PROCE.FECORDMED) AS [MES AÑO FECHA BUSQUEDA],
    CASE MONTH(PROCE.FECORDMED)
        WHEN 1 THEN 'ENERO'
        WHEN 2 THEN 'FEBRERO'
        WHEN 3 THEN 'MARZO'
        WHEN 4 THEN 'ABRIL'
        WHEN 5 THEN 'MAYO'
        WHEN 6 THEN 'JUNIO'
        WHEN 7 THEN 'JULIO'
        WHEN 8 THEN 'AGOSTO'
        WHEN 9 THEN 'SEPTIEMBRE'
        WHEN 10 THEN 'OCTUBRE'
        WHEN 11 THEN 'NOVIEMBRE'
        WHEN 12 THEN 'DICIEMBRE'
    END AS [MES NOMBRE FECHA BUSQUEDA],
    FORMAT(DAY(PROCE.FECORDMED), '00') AS [DIA FECHA BUSQUEDA],
    CONVERT(DATETIME, GETDATE() AT TIME ZONE 'Pakistan Standard Time', 1) AS ULT_ACTUAL
FROM INDIGO036.dbo.INPACIENT INP
    INNER JOIN CTE_PROCEDIMIENTOS PROCE ON PROCE.IPCODPACI = INP.IPCODPACI
    LEFT JOIN INDIGO036.dbo.ADINGRESO ING ON ING.IPCODPACI = PROCE.IPCODPACI AND ING.NUMINGRES = PROCE.NUMINGRES
    LEFT JOIN INDIGO036.dbo.INDIAGNOS DIA ON DIA.CODDIAGNO = PROCE.CODDIAGNO
    LEFT JOIN INDIGO036.dbo.INPROFSAL PROF ON PROF.CODPROSAL = PROCE.CODPROSAL AND PROF.TIPPROFES IN (1, 2, 19, 24, 26, 27)
    LEFT JOIN INDIGO036.dbo.INCUPSIPS CUPS ON CUPS.CODSERIPS = PROCE.CODSERIPS
    LEFT JOIN INDIGO036.dbo.INUNIFUNC FUN ON FUN.UFUCODIGO = PROCE.UFUCODIGO;