-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_REINGRESOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_REINGRESOS AS

WITH CTE_INGRESO AS (
    SELECT
        ROW_NUMBER() OVER (
            PARTITION BY ING.IPCODPACI
            ORDER BY
                ING.IPCODPACI,
                ING.IFECHAING
        ) AS NUMERO,
        ING.IPCODPACI,
        ING.NUMINGRES,
        ING.IFECHAING,
        EGR.FECALTPAC AS FECHEGRESO,
        ING.CODDIAING,
        ING.CODDIAEGR,
        ING.UFUCODIGO,
        ING.UFUEGRMED,
        ING.CODCENATE,
        CASE
            ING.IREINGRES
            WHEN 1 THEN 'SI'
            ELSE 'NO'
        END AS IREINGRES
    FROM
        INDIGO036.dbo.ADINGRESO ING
        INNER JOIN INDIGO036.dbo.HCREGEGRE EGR ON ING.NUMINGRES = EGR.NUMINGRES
            AND EGR.FECALTPAC IS NOT NULL
    WHERE
        ING.IINGREPOR != 2
),
CTE_REINGRESOS AS (
    SELECT
        A.CODCENATE,
        A.IPCODPACI AS [IDENTIFICACION],
        A.NUMINGRES AS [NUMERO INGRESO A],
        A.IFECHAING AS [FECHA INGRESO A],
        A.FECHEGRESO AS [FECHA EGRESO A],
        A.CODDIAING AS [DIAGNOSTICO INGRESO A],
        A.CODDIAEGR AS [DIAGNOSTICO EGRESO A],
        A.UFUCODIGO AS [UNIDAD INGRESO A],
        A.UFUEGRMED AS [UNIDAD EGRESO A],
        A.IREINGRES AS [REINGRESO VIE A],
        B.NUMINGRES AS [NUMERO INGRESO B],
        B.IFECHAING AS [FECHA INGRESO B],
        B.FECHEGRESO AS [FECHA EGRESO B],
        B.CODDIAING AS [DIAGNOSTICO INGRESO B],
        B.CODDIAEGR AS [DIAGNOSTICO EGRESO B],
        B.UFUCODIGO AS [UNIDAD INGRESO B],
        B.UFUEGRMED AS [UNIDAD EGRESO B],
        B.IREINGRES AS [REINGRESO VIE B],
        DATEDIFF(HOUR, A.FECHEGRESO, B.IFECHAING) AS [HORAS EA vs IB]
    FROM
        CTE_INGRESO A
        INNER JOIN CTE_INGRESO B ON A.IPCODPACI = B.IPCODPACI
            AND A.NUMERO = '1'
            AND B.NUMERO = '2'
            AND (
                A.CODDIAEGR = B.CODDIAING
                OR A.CODDIAING = B.CODDIAING
            )
    UNION
    SELECT
        A.CODCENATE,
        A.IPCODPACI AS [IDENTIFICACION],
        A.NUMINGRES AS [NUMERO INGRESO A],
        A.IFECHAING AS [FECHA INGRESO A],
        A.FECHEGRESO AS [FECHA EGRESO A],
        A.CODDIAING AS [DIAGNOSTICO INGRESO A],
        A.CODDIAEGR AS [DIAGNOSTICO EGRESO A],
        A.UFUCODIGO AS [UNIDAD INGRESO A],
        A.UFUEGRMED AS [UNIDAD EGRESO A],
        A.IREINGRES AS [REINGRESO VIE A],
        B.NUMINGRES AS [NUMERO INGRESO B],
        B.IFECHAING AS [FECHA INGRESO B],
        B.FECHEGRESO AS [FECHA EGRESO B],
        B.CODDIAING AS [DIAGNOSTICO INGRESO B],
        B.CODDIAEGR AS [DIAGNOSTICO EGRESO B],
        B.UFUCODIGO AS [UNIDAD INGRESO B],
        B.UFUEGRMED AS [UNIDAD EGRESO B],
        B.IREINGRES AS [REINGRESO VIE B],
        DATEDIFF(HOUR, A.FECHEGRESO, B.IFECHAING) AS [HORAS EA vs IB]
    FROM
        CTE_INGRESO A
        INNER JOIN CTE_INGRESO B ON A.IPCODPACI = B.IPCODPACI
            AND A.NUMERO = '2'
            AND B.NUMERO = '3'
            AND (
                A.CODDIAEGR = B.CODDIAING
                OR A.CODDIAING = B.CODDIAING
            )
    UNION
    SELECT
        A.CODCENATE,
        A.IPCODPACI AS [IDENTIFICACION],
        A.NUMINGRES AS [NUMERO INGRESO A],
        A.IFECHAING AS [FECHA INGRESO A],
        A.FECHEGRESO AS [FECHA EGRESO A],
        A.CODDIAING AS [DIAGNOSTICO INGRESO A],
        A.CODDIAEGR AS [DIAGNOSTICO EGRESO A],
        A.UFUCODIGO AS [UNIDAD INGRESO A],
        A.UFUEGRMED AS [UNIDAD EGRESO A],
        A.IREINGRES AS [REINGRESO VIE A],
        B.NUMINGRES AS [NUMERO INGRESO B],
        B.IFECHAING AS [FECHA INGRESO B],
        B.FECHEGRESO AS [FECHA EGRESO B],
        B.CODDIAING AS [DIAGNOSTICO INGRESO B],
        B.CODDIAEGR AS [DIAGNOSTICO EGRESO B],
        B.UFUCODIGO AS [UNIDAD INGRESO B],
        B.UFUEGRMED AS [UNIDAD EGRESO B],
        B.IREINGRES AS [REINGRESO VIE B],
        DATEDIFF(HOUR, A.FECHEGRESO, B.IFECHAING) AS [HORAS EA vs IB]
    FROM
        CTE_INGRESO A
        INNER JOIN CTE_INGRESO B ON A.IPCODPACI = B.IPCODPACI
            AND A.NUMERO = '3'
            AND B.NUMERO = '4'
            AND (
                A.CODDIAEGR = B.CODDIAING
                OR A.CODDIAING = B.CODDIAING
            )
)
SELECT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    RTRIM(R.CODCENATE) + ' - ' + CEN.NOMCENATE AS [CENTRO DE ATENCION],
    ROW_NUMBER() OVER (
        PARTITION BY IDENTIFICACION
        ORDER BY
            IDENTIFICACION,
            [FECHA INGRESO A]
    ) AS [NUMERO DE REINGRESOS],
    IDENTIFICACION,
    CASE
        PAC.IPTIPODOC
        WHEN 1 THEN 'CC - CEDULA DE CIUDADANIA'
        WHEN 2 THEN 'CE - CEDULA DE EXTRANJERIA'
        WHEN 3 THEN 'TI - TARJETA DE IDENTIDAD'
        WHEN 4 THEN 'RC - REGISTRO CIVIL'
        WHEN 5 THEN 'PA - PASAPORTE'
        WHEN 6 THEN 'AS - ADULTO SIN IDENTIFICACION'
        WHEN 7 THEN 'MS - MENOR SIN IDENTIFICACION'
        WHEN 8 THEN 'NU - NUMERO UNICO DE IDENTIFICACIÒN'
        WHEN 9 THEN 'NV - CERTIFICADO NACIDO VIVO'
        WHEN 10 THEN 'CD - CARNET DIPLOMATICO'
        WHEN 11 THEN 'SC - SALVOCONDUCTO'
        WHEN 12 THEN 'PE - PERMISO ESPECIAL DE PERMANENCIA'
        ELSE 'OTRO'
    END AS [TIPO IDENTIFICACION],
    PAC.IPNOMCOMP AS [NOMBRE COMPLETO],
    PAC.IPPRINOMB AS [PRIMER NOMBRE],
    PAC.IPSEGNOMB AS [SEGUNDO NOMBRE],
    PAC.IPPRIAPEL AS [PRIMER APELLIDO],
    PAC.IPSEGAPEL AS [SEGUNDO APELLIDO],
    CASE
        PAC.IPSEXOPAC
        WHEN 1 THEN 'MASCULINO'
        ELSE 'FEMENINO'
    END AS [SEXO],
    CAST(PAC.IPFECNACI AS DATE) AS [FECHA_NACIMIENTO],
    FLOOR(
        (
            CAST(
                CONVERT(VARCHAR(8), [FECHA INGRESO A], 112) AS INT
            ) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)
        ) / 10000
    ) AS [EDAD],
    DEP.nomdepart AS DEPARTAMENTO,
    MUN.MUNNOMBRE AS MUNICIPIO,
    UB.UBINOMBRE AS UBICACION,
    PAC.IPTELEFON AS [TELEFONO],
    PAC.IPTELMOVI AS [CELULAR],
    EAPB.CODENTIDA AS [CODIGO EAPB],
    EAPB.NOMENTIDA AS [NOMBRE EAPB],
    CASE
        PAC.IPTIPOPAC
        WHEN 1 THEN 'Contributivo'
        WHEN 2 THEN 'Subsidiado'
        WHEN 3 THEN 'Vinculado'
        WHEN 4 THEN 'Particular'
        WHEN 5 THEN 'Otro'
        WHEN 6 THEN 'Desplazado Reg. Contributivo'
        WHEN 7 THEN 'Desplazado Reg. Subsidiado'
        WHEN 8 THEN 'Desplazado No Asegurado'
    END AS [REGIMEN],
    [NUMERO INGRESO A],
    [FECHA INGRESO A],
    [FECHA EGRESO A],
    [DIAGNOSTICO INGRESO A] + ' - ' + INGA.NOMDIAGNO AS [DIAGNOSTICO INGRESO A],
    [DIAGNOSTICO EGRESO A] + ' - ' + EGRA.NOMDIAGNO AS [DIAGNOSTICO EGRESO A],
    RTRIM([UNIDAD INGRESO A]) + ' - ' + FUNIA.UFUDESCRI AS [UNIDAD INGRESO A],
    RTRIM([UNIDAD EGRESO A]) + ' - ' + FUNEA.UFUDESCRI AS [UNIDAD EGRESO A],
    [NUMERO INGRESO B],
    [FECHA INGRESO B],
    [FECHA EGRESO B],
    [DIAGNOSTICO INGRESO B] + ' - ' + INGA.NOMDIAGNO AS [DIAGNOSTICO INGRESO B],
    [DIAGNOSTICO EGRESO B] + ' - ' + EGRA.NOMDIAGNO AS [DIAGNOSTICO EGRESO B],
    RTRIM([UNIDAD INGRESO B]) + ' - ' + FUNIB.UFUDESCRI AS [UNIDAD INGRESO B],
    RTRIM([UNIDAD EGRESO B]) + ' - ' + FUNEB.UFUDESCRI AS [UNIDAD EGRESO B],
    [REINGRESO VIE B],
    [HORAS EA vs IB],
    1 AS CANTIDAD,
    CAST([FECHA INGRESO A] AS DATE) AS [FECHA BUSQUEDA],
    YEAR([FECHA INGRESO A]) AS [AÑO BUSQUEDA],
    MONTH([FECHA INGRESO A]) AS [MES BUSQUEDA],
    CONCAT(
        FORMAT(MONTH([FECHA INGRESO A]), '00'),
        ' - ',
        CASE
            WHEN MONTH([FECHA INGRESO A]) = 1 THEN 'ENERO'
            WHEN MONTH([FECHA INGRESO A]) = 2 THEN 'FEBRERO'
            WHEN MONTH([FECHA INGRESO A]) = 3 THEN 'MARZO'
            WHEN MONTH([FECHA INGRESO A]) = 4 THEN 'ABRIL'
            WHEN MONTH([FECHA INGRESO A]) = 5 THEN 'MAYO'
            WHEN MONTH([FECHA INGRESO A]) = 6 THEN 'JUNIO'
            WHEN MONTH([FECHA INGRESO A]) = 7 THEN 'JULIO'
            WHEN MONTH([FECHA INGRESO A]) = 8 THEN 'AGOSTO'
            WHEN MONTH([FECHA INGRESO A]) = 9 THEN 'SEPTIEMBRE'
            WHEN MONTH([FECHA INGRESO A]) = 10 THEN 'OCTUBRE'
            WHEN MONTH([FECHA INGRESO A]) = 11 THEN 'NOVIEMBRE'
            WHEN MONTH([FECHA INGRESO A]) = 12 THEN 'DICIEMBRE'
        END
    ) AS [MES NOMBRE BUSQUEDA],
   CAST(DATEADD(HOUR, -5, GETDATE()) AS DATETIME) AS ULT_ACTUAL


FROM
    CTE_REINGRESOS R
    INNER JOIN INDIGO036.dbo.INPACIENT PAC ON R.IDENTIFICACION = PAC.IPCODPACI
    INNER JOIN INDIGO036.dbo.INUBICACI UB ON PAC.AUUBICACI = UB.AUUBICACI
    INNER JOIN INDIGO036.dbo.INMUNICIP MUN ON UB.DEPMUNCOD = MUN.DEPMUNCOD
    INNER JOIN INDIGO036.dbo.INDEPARTA DEP ON MUN.DEPCODIGO = DEP.depcodigo
        AND PAC.AUUBICACI = UB.AUUBICACI
    INNER JOIN INDIGO036.dbo.INENTIDAD EAPB ON PAC.CODENTIDA = EAPB.CODENTIDA
    INNER JOIN INDIGO036.dbo.INDIAGNOS INGA ON R.[DIAGNOSTICO INGRESO A] = INGA.CODDIAGNO
    INNER JOIN INDIGO036.dbo.INDIAGNOS EGRA ON R.[DIAGNOSTICO EGRESO A] = EGRA.CODDIAGNO
    INNER JOIN INDIGO036.dbo.INDIAGNOS INGB ON R.[DIAGNOSTICO INGRESO B] = INGB.CODDIAGNO
    INNER JOIN INDIGO036.dbo.INDIAGNOS EGRB ON R.[DIAGNOSTICO EGRESO B] = EGRB.CODDIAGNO
    INNER JOIN INDIGO036.dbo.INUNIFUNC FUNIA ON R.[UNIDAD INGRESO A] = FUNIA.UFUCODIGO
    INNER JOIN INDIGO036.dbo.INUNIFUNC FUNEA ON R.[UNIDAD EGRESO A] = FUNEA.UFUCODIGO
    INNER JOIN INDIGO036.dbo.INUNIFUNC FUNIB ON R.[UNIDAD INGRESO B] = FUNIB.UFUCODIGO
    INNER JOIN INDIGO036.dbo.INUNIFUNC FUNEB ON R.[UNIDAD EGRESO B] = FUNEB.UFUCODIGO
    INNER JOIN INDIGO036.dbo.ADCENATEN CEN ON R.CODCENATE = CEN.CODCENATE
WHERE
    (
        DATEDIFF(HOUR, [FECHA EGRESO A], [FECHA INGRESO B]) <= '360'
        AND FUNEA.UFUDESCRI NOT LIKE '%URGENCIAS%'
    )
    OR (
        DATEDIFF(HOUR, [FECHA EGRESO A], [FECHA INGRESO B]) <= '72'
        AND FUNEA.UFUDESCRI LIKE '%URGENCIAS%'
    )