-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_SOLICITUD_IMAGENES_HOMI
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE   VIEW Report.VW_SOLICITUD_IMAGENES_HOMI AS

SELECT DISTINCT
    HC.NUMINGRES AS NUMERO_DE_INGRESO,
    CASE IPC.IPTIPODOC
        WHEN 1 THEN 'CEDULA DE CIUDADANIA'
        WHEN 2 THEN 'CEDULA DE EXTRANJERIA'
        WHEN 3 THEN 'TARJETA DE IDENTIDAD'
        WHEN 4 THEN 'REGISTRO CIVIL'
        WHEN 5 THEN 'PASAPORTE'
        WHEN 6 THEN 'ADULTO SIN IDENTIFICACION'
        WHEN 7 THEN 'MENOR SIN IDENTIFICACION'
        WHEN 8 THEN 'NUMERO UNICO DE IDENTIFICACION PERSONAL'
        WHEN 9 THEN 'CERTIFICADO DE NACIDO VIVO'
        WHEN 10 THEN 'CARNET DIPLOMATICO (Aplica para extranjeros)'
        WHEN 11 THEN 'SALVOCONDUCTO (Aplica para extranjeros)'
        WHEN 12 THEN 'PERMISO ESPECIAL DE PERMANENCIA (Aplica para extranjeros)'
        WHEN 13 THEN 'PERMISO TEMPORAL DE PERMANENCIA'
        WHEN 14 THEN 'DOCUMENTO EXTRANJERO'
        WHEN 15 THEN 'SIN IDENTIFICACION'
    END AS TIPO_DE_DOCUMENTO,
    IPC.IPCODPACI AS DOCUMENTO,
    IPC.IPNOMCOMP AS NOMBRE_PACIENTE,
    IPC.IPFECNACI AS FECHA_DE_NACIMIENTO,
    CASE IPC.IPSEXOPAC
        WHEN 1 THEN 'M'
        ELSE 'F'
    END AS GENERO,
    DATEDIFF(YEAR, IPC.IPFECNACI, HC.FECORDMED) AS EDAD,
    DIA.NOMDIAGNO AS DIAGNOSTICO,
    HC.CODSERIPS,
    ICS.DESSERIPS AS PROCEDIMIENTO,
    INF.UFUDESCRI AS NOMBRE_PABELLON,
    INFC.UFUCODIGO AS CENTRO_COSTO,
    INFC.UFUDESCRI AS NOMBRE_CENTRO_COSTO,
    CASE ING.TIPOINGRE
        WHEN 1 THEN 'AMBULATORIO'
        ELSE 'HOSPITALARIO'
    END AS AMBITO,
    HC.NUMEFOLIO AS FOLIO,
    HC.FECORDMED AS FECHA_SOLIC_ORDEN,
    PRSA.NOMMEDICO AS PROFESIONAL_SALUD_ORDENA,
    ESP.DESESPECI AS ESPECIALIDAD_ORDENA,
    HC.OBSSERIPS AS OBSERVACIONES,
    CASE HC.PRISERIPS
        WHEN 1 THEN 'URGENTE'
        ELSE 'RUTINA'
    END AS PRIORIDAD_SERVICIO,
    CASE HC.ESTSERIPS
        WHEN 1 THEN 'SOLICITADO'
        WHEN 2 THEN 'ESTUDIO REALIZADO'
        WHEN 3 THEN 'IMAGEN PROCESADA'
        WHEN 4 THEN 'ESTUDIO INTERPRETADO'
        WHEN 5 THEN 'REMITIDO'
        WHEN 6 THEN 'ANULADO'
        WHEN 7 THEN 'EXTRAMURAL'
    END AS ESTADO_SERVICIO,
    HC.FECRECEXA AS FECHA_TOMA_IMAGEN,
    HC.FECTRASER AS FECHA_RESULTADO,
    PRSA2.NOMMEDICO AS MEDICO_RESULTADO,
    ESP3.DESESPECI AS ESPECIALIDAD_RESULTADO,
    HC.INTERPRET AS INTERPRETACION_DE_RESULTADO,
    HC.FECHLECT AS FECHA_LECTURA,
    PRSA3.CODPROSAL AS IDENTIFICACION_MED_LECTURA,
    PRSA3.NOMMEDICO AS MEDICO_REALIZA_LECTURA,
    ESP2.DESESPECI AS ESPECIALIDAD_MED_REALIZA_LECTURA,
    DATEDIFF(HOUR, HC.FECORDMED, HC.FECRECEXA) AS HORAS_ORDEN_VS_TOMA,
    DATEDIFF(HOUR, HC.FECRECEXA, HC.FECTRASER) AS HORAS_TOMA_VS_RESULTADO,
    DATEDIFF(HOUR, HC.FECTRASER, HC.FECHLECT) AS HORAS_RESULTADO_VS_LECTURA,
    DATEDIFF(HOUR, HC.FECRECEXA, HC.FECHLECT) AS HORAS_TOMA_VS_LECTURA
FROM INDIGO036.dbo.HCORDIMAG HC
LEFT JOIN INDIGO036.dbo.INCUPSIPS ICS ON HC.CODSERIPS = ICS.CODSERIPS
LEFT JOIN INDIGO036.dbo.INPROFSAL PRSA ON HC.CODPROSAL = PRSA.CODPROSAL
LEFT JOIN INDIGO036.dbo.INPROFSAL PRSA2 ON HC.CODPROVAL = PRSA2.CODPROSAL
LEFT JOIN INDIGO036.dbo.INPROFSAL PRSA3 ON HC.MEDREALEC = PRSA3.CODPROSAL
LEFT JOIN INDIGO036.dbo.INESPECIA ESP ON PRSA.CODESPEC1 = ESP.CODESPECI
LEFT JOIN INDIGO036.dbo.INESPECIA ESP2 ON PRSA3.CODESPEC1 = ESP2.CODESPECI
LEFT JOIN INDIGO036.dbo.INESPECIA ESP3 ON PRSA2.CODESPEC1 = ESP3.CODESPECI
LEFT JOIN INDIGO036.dbo.ADINGRESO ING ON HC.NUMINGRES = ING.NUMINGRES
LEFT JOIN INDIGO036.dbo.INDIAGNOS DIA ON HC.CODDIAGNO = DIA.CODDIAGNO
LEFT JOIN INDIGO036.dbo.INUNIFUNC INF ON HC.UFUCODIGO = INF.UFUCODIGO
LEFT JOIN INDIGO036.dbo.INUNIFUNC INFC ON ING.UFUCODIGO = INFC.UFUCODIGO
LEFT JOIN INDIGO036.dbo.INPACIENT IPC ON HC.IPCODPACI = IPC.IPCODPACI;