-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_SOLICITUD_IMAGENES
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE   VIEW Report.VW_SOLICITUD_IMAGENES AS
WITH CTE_IMAGENES AS (
    -- Hospitalaria
    SELECT
        [AUTO] AS [Id],
        IPCODPACI,
        CASE WHEN MANEXTPRO = 0 THEN 'HOSPITALARIO' ELSE 'AMBULATORIO' END AS [TIPO SOLICITUD],
        UFUCODIGO,
        NUMINGRES,
        NUMEFOLIO,
        CODSERIPS,
        FECORDMED,
        CASE ESTSERIPS
            WHEN '1' THEN 'SOLICITADO'
            WHEN '2' THEN 'ESTUDIO REALIZADO'
            WHEN '3' THEN 'ESTUDIO REALIZADO'
            WHEN '4' THEN 'ESTUDIOS REALIZADOS'
            WHEN '5' THEN 'REMITIDO'
            WHEN '6' THEN 'EXTRAMURAL'
            WHEN '7' THEN 'ANULADO'
            ELSE 'ESTUDIOS NO REALIZADOS'
        END AS ESTADO,
        OBSSERIPS AS OBSERVACION,
        FECRECEXA,
        NOMARCIMG AS [NOMBRE ARCHIVO],
        CODCENATE,
        IDDESCRIPCIONRELACIONADA,
        CODPROSAL,
        ESTSERIPS,
        ISNULL(FECTRASER, FECHLECT) AS FECTRASER
    FROM INDIGO036.dbo.HCORDIMAG

    UNION ALL

    -- Ambulatoria
    SELECT
        [AUTO] AS [Id],
        IPCODPACI,
        'AMBULATORIO' AS [TIPO SOLICITUD],
        UFUCODIGO,
        NUMINGRES,
        '' AS NUMEFOLIO,
        CODSERIPS,
        FECORDMED,
        CASE ESTSERIPS
            WHEN '1' THEN 'SOLICITADO'
            WHEN '2' THEN 'ESTUDIO REALIZADO'
            WHEN '3' THEN 'ESTUDIO REALIZADO'
            WHEN '4' THEN 'ESTUDIOS REALIZADOS'
            WHEN '5' THEN 'REMITIDO'
            WHEN '6' THEN 'EXTRAMURAL'
            WHEN '7' THEN 'ANULADO'
            ELSE 'ESTUDIOS NO REALIZADOS'
        END AS ESTADO,
        OBSERVACI AS OBSERVACION,
        FECRECEXA,
        NOMARCIMG AS [NOMBRE ARCHIVO],
        CODCENATE,
        IDDESCRIPCIONRELACIONADA,
        CODPROSAL,
        ESTSERIPS,
        ISNULL(FECTRASER, FECHLECT) AS FECTRASER
    FROM INDIGO036.dbo.AMBORDIMA
)
SELECT
    CAST(DB_NAME() AS VARCHAR(50)) AS ID_COMPANY,
    RTRIM(E.NOMCENATE) AS [CENTRO ATENCION],
    CASE I.IPTIPODOC
        WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI'
        WHEN '4' THEN 'RC' WHEN '5' THEN 'PA' WHEN '6' THEN 'AS'
        WHEN '7' THEN 'MS' WHEN '8' THEN 'NU' WHEN '9' THEN 'NV'
        WHEN '10' THEN 'CD' WHEN '11' THEN 'SC' WHEN '12' THEN 'PE'
        WHEN '13' THEN 'PT' WHEN '14' THEN 'DE' WHEN '15' THEN 'SI'
    END AS [TIPO IDENTIFICACION],
    A.IPCODPACI AS [IDENTIFICACION],
    I.IPNOMCOMP AS [PACIENTE],
    CAST(I.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
    CAST(DATEDIFF(MONTH, I.IPFECNACI, GETDATE())/12 AS VARCHAR) + ' Años ' +
    CAST(DATEDIFF(MONTH, I.IPFECNACI, GETDATE())%12 AS VARCHAR) + ' Meses' AS EDAD,
    CASE I.IPSEXOPAC WHEN '1' THEN 'MASCULINO' ELSE 'FEMENINO' END AS [SEXO],
    I.IPTELEFON AS [TELEFONO FIJO],
    I.IPTELMOVI AS [TELEFONO MOVIL],
    I.IPDIRECCI AS DIRECCION,
    EA.Code + ' - ' + EA.Name AS [ENTIDAD ADMINISTRADORA],
    GA.Code + ' - ' + GA.Name AS [GRUPO ATENCION],
    CASE GA.LiquidationType
        WHEN 1 THEN 'PAGO POR SERVICIOS'
        WHEN 2 THEN 'PGP'
        WHEN 3 THEN 'FACTURA GLOBAL'
        WHEN 4 THEN 'CAPITACION GLOBAL'
        WHEN 5 THEN 'CONTROL'
    END AS [TIPO CONTRATO],
    A.[TIPO SOLICITUD],
    'IMAGENES' AS [TIPO ORDEN],
    A.UFUCODIGO + ' - ' + RTRIM(C.UFUDESCRI) AS [UNIDAD FUNCIONAL],
    ING.CODCAMACT AS CAMA,
    A.NUMINGRES AS INGRESO,
    A.NUMEFOLIO AS FOLIO,
    A.CODSERIPS AS [CODIGO CUPS],
    CG.Code + '-' + CG.Name AS [GRUPO],
    CSG.Code + '-' + CSG.Name AS [SUBGRUPO],
    RTRIM(B.DESSERIPS) AS [DESCRIPCION SERVICIO],
    ISNULL(CD.Code + ' - ' + CD.Name, '') AS [DESCRIPCION RELACIONADA],
    GA.Code AS [CODIGO GRUPO ATENCION],
    CAST(A.FECORDMED AS DATE) AS [FECHA DE SOLICITUD ORDEN],
    FORMAT(A.FECORDMED, 'HH:mm:ss') AS [HORA DE SOLICITUD ORDEN],
    A.ESTADO,
    1 AS CANTIDAD,
    PRO.CODPROSAL AS [ID PROFESIONAL],
    PRO.NOMMEDICO AS PROFESIONAL,
    ESPMED.DESESPECI AS ESPECIALIDAD,
    A.OBSERVACION,
    CASE A.ESTSERIPS WHEN 7 THEN NULL ELSE DIAG.CODDIAGNO END AS CIE10,
    CASE A.ESTSERIPS WHEN 7 THEN NULL ELSE DIAG.NOMDIAGNO END AS DIAGNOSTICO,
    CASE ESTA.ESTADIO
        WHEN 0 THEN 'EC 0 (TUMOR IN SITU)'
        WHEN 1 THEN 'EC I O 1'
        WHEN 2 THEN 'EC IA O 1A'
        WHEN 3 THEN 'EC IA1'
        WHEN 4 THEN 'EC IA2'
        WHEN 5 THEN 'EC IB O 1B'
        WHEN 6 THEN 'EC IB1'
        WHEN 7 THEN 'EC IB2'
        WHEN 8 THEN 'EC IC O 1C'
        WHEN 9 THEN 'EC IS O 1S'
        WHEN 10 THEN 'EC II O 2'
        WHEN 11 THEN 'EC IIA O 2A'
        WHEN 12 THEN 'EC IIA1'
        WHEN 13 THEN 'EC IIA2'
        WHEN 14 THEN 'EC IIB O 2B'
        WHEN 15 THEN 'EC IIC O 2C'
        WHEN 16 THEN 'EC III O 3'
        WHEN 17 THEN 'EC IIIA O 3A'
        WHEN 18 THEN 'EC IIIB O 3B'
        WHEN 19 THEN 'EC IIIC O 3C'
        WHEN 20 THEN 'EC IV O 4'
        WHEN 21 THEN 'EC IVA O 4A'
        WHEN 22 THEN 'EC IVB O 4B'
        WHEN 23 THEN 'EC IVC O 4C'
        WHEN 24 THEN 'EC 4S (NEUROBLASTOMA)'
        WHEN 25 THEN 'EC V O 5'
        WHEN 26 THEN 'EC IAB'
        WHEN 55 THEN 'ASEGURADO ATENDIDO POR ENTIDAD TERRITORIAL'
        WHEN 93 THEN 'SIN INFORMACIÓN EN HISTORIA CLÍNICA'
        WHEN 98 THEN 'NO APLICA'
        WHEN 99 THEN 'DESCONOCIDO'
        ELSE ''
    END AS ESTADIO,
    IIF(G.CODGRUPO IS NULL, 'NO', 'SI') AS CUBIERTO,
    ISNULL(G.CONTRATADO, 'NO') AS CONTRATADO,
    ISNULL(G.COTIZADO, 'NO') AS COTIZADO,
    CAST(A.FECRECEXA AS DATE) AS [FECHA DE TOMA IMAGEN],
    FORMAT(A.FECRECEXA, 'HH:mm:ss') AS [HORA DE TOMA IMAGEN],
    CAST(A.FECTRASER AS DATE) AS [FECHA DE RESULTADO],
    FORMAT(A.FECTRASER, 'HH:mm:ss') AS [HORA DE RESULTADO],
    DATEDIFF(HOUR, A.FECRECEXA, A.FECTRASER) AS [TOMA VS RESULTADO H],
    DATEDIFF(HOUR, A.FECORDMED, A.FECTRASER) AS [SOLICITUD VS RESULTADO H],
    A.[NOMBRE ARCHIVO],
    CAST(A.FECORDMED AS DATE) AS [FECHA BUSQUEDA],
    YEAR(A.FECORDMED)  AS [AÑO FECHA BUSQUEDA],
    MONTH(A.FECORDMED) AS [MES AÑO FECHA BUSQUEDA],
    DATENAME(MONTH, A.FECORDMED) AS [MES NOMBRE FECHA BUSQUEDA],
    FORMAT(DAY(A.FECORDMED), '00') AS [DIA FECHA BUSQUEDA],
    CONVERT(DATETIME, GETDATE() AT TIME ZONE 'Pakistan Standard Time', 1) AS ULT_ACTUAL
FROM CTE_IMAGENES A
LEFT  JOIN INDIGO036.dbo.INCUPSIPS B  ON A.CODSERIPS = B.CODSERIPS
INNER JOIN INDIGO036.dbo.INUNIFUNC C  ON A.UFUCODIGO = C.UFUCODIGO
INNER JOIN INDIGO036.dbo.ADCENATEN E  ON A.CODCENATE = E.CODCENATE
INNER JOIN INDIGO036.Contract.CUPSEntity   CUPS ON CUPS.Code = B.CODSERIPS
INNER JOIN INDIGO036.Contract.CupsSubgroup CSG  ON CSG.Id   = CUPS.CUPSSubGroupId
INNER JOIN INDIGO036.Contract.CupsGroup    CG   ON CG.Id    = CSG.CupsGroupId
LEFT  JOIN INDIGO036.Contract.CUPSEntityContractDescriptions CECD ON CECD.Id = A.IDDESCRIPCIONRELACIONADA
LEFT  JOIN INDIGO036.Contract.ContractDescriptions            CD   ON CD.Id  = CECD.ContractDescriptionId
INNER JOIN INDIGO036.dbo.INPACIENT  I   ON A.IPCODPACI   = I.IPCODPACI
INNER JOIN INDIGO036.dbo.INPROFSAL  PRO ON A.CODPROSAL   = PRO.CODPROSAL
INNER JOIN INDIGO036.dbo.HCHISPACA  HIS ON A.NUMINGRES   = HIS.NUMINGRES AND A.NUMEFOLIO = HIS.NUMEFOLIO
INNER JOIN INDIGO036.dbo.INESPECIA  ESPMED ON ESPMED.CODESPECI = HIS.CODESPTRA
INNER JOIN INDIGO036.dbo.INDIAGNOS  DIAG   ON DIAG.CODDIAGNO   = HIS.CODDIAGNO
LEFT  JOIN INDIGO036.dbo.ADINGRESO  ING    ON ING.NUMINGRES    = A.NUMINGRES
LEFT  JOIN INDIGO036.Contract.CareGroup           GA ON GA.Id = ING.GENCAREGROUP
LEFT  JOIN INDIGO036.Contract.HealthAdministrator EA ON EA.Id = ING.GENCONENTITY
LEFT  JOIN (
    SELECT
        CG.Code AS CODGRUPO,
        CASE PC.Contracted WHEN 1 THEN 'SI' ELSE 'NO' END AS CONTRATADO,
        CASE PC.Quoted     WHEN 1 THEN 'SI' ELSE 'NO' END AS COTIZADO,
        CE.Code AS CUPS,
        CECD.Id AS IDRELACION
    FROM INDIGO036.Contract.CareGroup CG
    INNER JOIN INDIGO036.Contract.Contract          CON ON CG.ContractId          = CON.Id
    INNER JOIN INDIGO036.Contract.ProcedureTemplate PT  ON CG.ProcedureTemplateId = PT.Id
    INNER JOIN INDIGO036.Contract.ProcedureCups     PC  ON PT.Id                  = PC.ProceduresTemplateId
    INNER JOIN INDIGO036.Contract.CUPSEntity        CE  ON PC.CupsId              = CE.Id
    LEFT  JOIN INDIGO036.Contract.CUPSEntityContractDescriptions CECD ON PC.CUPSEntityContractDescriptionId = CECD.Id
) G ON G.CODGRUPO = GA.Code AND G.CUPS = A.CODSERIPS AND A.IDDESCRIPCIONRELACIONADA = G.IDRELACION
-- >>> JOIN QUE FALTABA (mantiene el comportamiento del query original)
LEFT  JOIN INDIGO036.dbo.INDIAGNOP AS EST
       ON  A.IPCODPACI = EST.IPCODPACI
       AND A.NUMINGRES = EST.NUMINGRES
       AND EST.NUMEFOLIO = A.NUMEFOLIO
       AND EST.ESTADIO IS NOT NULL
LEFT  JOIN (
    SELECT EST.NUMEFOLIO, EST.IPCODPACI AS PACIENTE, EST.ESTADIO
    FROM INDIGO036.dbo.INDIAGNOH EST
    INNER JOIN (
        SELECT MIN(NUMEFOLIO) AS NUMEFOLIO, IPCODPACI
        FROM INDIGO036.dbo.INDIAGNOH
        WHERE ESTADIO IS NOT NULL AND ESTADIO NOT IN (93, 98, 99)
        GROUP BY IPCODPACI
    ) FE ON EST.NUMEFOLIO = FE.NUMEFOLIO AND EST.IPCODPACI = FE.IPCODPACI
    WHERE EST.ESTADIO IS NOT NULL
) ESTA ON ING.IPCODPACI = ESTA.PACIENTE;
