-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_URGENCIAS_CRUE
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_URGENCIAS_CRUE AS 

WITH CTE_MUERTOS AS (
    SELECT
        HIS.NUMINGRES AS INGRESO,
        HIS.ID,
        EGR.FECMUEPAC AS FECHA_MUERTE
    FROM
        INDIGO036.dbo.HCHISPACA HIS
        INNER JOIN INDIGO036.dbo.HCREGEGRE AS EGR ON HIS.NUMINGRES = EGR.NUMINGRES
        AND HIS.NUMEFOLIO = EGR.NUMEFOLIO
        INNER JOIN INDIGO036.dbo.INUNIFUNC AS FUN ON EGR.UFUCODIGO = FUN.UFUCODIGO
    WHERE
        HIS.INDICAPAC = 11
        AND FUN.UFUTIPUNI = '1'
),

CTE_ORDENES_CON_ESTANCIA_RECONOCIDAS AS (
    SELECT
        RC.AdmissionNumber
    FROM
        INDIGO036.Billing.RevenueControl AS RC
        INNER JOIN INDIGO036.Billing.RevenueControlDetail AS RCD ON RC.Id = RCD.RevenueControlId
        INNER JOIN INDIGO036.Billing.ServiceOrderDetailDistribution AS SODD ON RCD.Id = SODD.RevenueControlDetailId
        AND RCD.Status IN ('1', '2', '3')
        INNER JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD ON SODD.ServiceOrderDetailId = SOD.Id
        INNER JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON SOD.CUPSEntityId = CUPS.Id
        AND CUPS.BillingGroupId IN (2)
    WHERE
        CUPS.Code IN ('890701', '890702', '890703', '890704')
    GROUP BY
        RC.AdmissionNumber
)
, CTE_ORDENES_CON_ESTANCIAS_CARGADAS AS (
    SELECT
        RC.AdmissionNumber,
        G.[CONSULTA DE URGENCIAS POR MEDICINA GENERAL],
        G.[CONSULTA DE URGENCIAS POR OTRAS ESPECIALIDADES MEDICAS],
        G.[CONSULTA DE URGENCIAS POR ODONTOLOGIA GENERAL],
        G.[CONSULTA DE URGENCIAS POR ODONTOLOGIA ESPECIALIZADA]
    FROM
        INDIGO036.Billing.RevenueControl AS RC
        INNER JOIN (
            SELECT *
            FROM (
                SELECT
                    RC.AdmissionNumber,
                    CUPS.Code AS CUPS,
                    CUPS.Description AS DESCRIPCION_CUPS
                FROM
                    INDIGO036.Billing.RevenueControlDetail AS RCD
                    INNER JOIN INDIGO036.Billing.RevenueControl AS RC ON RCD.RevenueControlId = RC.Id
                    INNER JOIN INDIGO036.Billing.ServiceOrderDetailDistribution AS SODD ON RCD.Id = SODD.RevenueControlDetailId
                    AND RCD.Status IN ('1', '2', '3')
                    INNER JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD ON SODD.ServiceOrderDetailId = SOD.Id
                    INNER JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON CUPS.Id = SOD.CUPSEntityId
                    AND CUPS.BillingGroupId IN (2)
                    INNER JOIN INDIGO036.Contract.IPSService AS IPS ON IPS.Id = SOD.IPSServiceId
                WHERE
                    CUPS.Code IN ('890701', '890702', '890703', '890704')
                GROUP BY
                    RC.AdmissionNumber,
                    CUPS.Code,
                    CUPS.Description
            ) AS SourceTable
            PIVOT (
                MAX([CUPS]) FOR [DESCRIPCION_CUPS] IN (
                    [CONSULTA DE URGENCIAS POR MEDICINA GENERAL],
                    [CONSULTA DE URGENCIAS POR OTRAS ESPECIALIDADES MEDICAS],
                    [CONSULTA DE URGENCIAS POR ODONTOLOGIA GENERAL],
                    [CONSULTA DE URGENCIAS POR ODONTOLOGIA ESPECIALIZADA]
                )
            ) AS PVTTABLE
        ) AS G ON G.AdmissionNumber = RC.AdmissionNumber
)
, CTE_ULTIMA_CAMAS_OCUPADA_OBSERVACION AS (
    SELECT
        EGR.NUMINGRES,
        CAM.NUMCAMHOS AS CAMA_OBSERVACION
    FROM
        INDIGO036.dbo.CHREGESTA EGR
        INNER JOIN (
            SELECT
                EGR.IPCODPACI,
                EGR.NUMINGRES,
                MAX(EGR.ID) AS ID
            FROM
                INDIGO036.dbo.CHREGESTA EGR
                INNER JOIN INDIGO036.dbo.CHCAMASHO AS CAM ON EGR.CODICAMAS = CAM.CODICAMAS
                INNER JOIN INDIGO036.dbo.INUNIFUNC AS FUN ON CAM.UFUCODIGO = FUN.UFUCODIGO
            WHERE
                FUN.UFUTIPUNI = '1'
            GROUP BY
                EGR.IPCODPACI,
                EGR.NUMINGRES
        ) AS G ON G.ID = EGR.ID
        INNER JOIN INDIGO036.dbo.CHCAMASHO AS CAM ON CAM.CODICAMAS = EGR.CODICAMAS
        INNER JOIN INDIGO036.dbo.INUNIFUNC AS FUN ON CAM.UFUCODIGO = FUN.UFUCODIGO
),

CTE_ULTIMA_CAMAS_OCUPADA_HOSPITALIZACION AS (
    SELECT
        EGR.NUMINGRES,
        CAM.NUMCAMHOS AS CAMA_HOSPITALIZACION
    FROM
        INDIGO036.dbo.CHREGESTA EGR
        INNER JOIN (
            SELECT
                EGR.IPCODPACI,
                EGR.NUMINGRES,
                MAX(EGR.ID) AS ID
            FROM
                INDIGO036.dbo.CHREGESTA EGR
                INNER JOIN INDIGO036.dbo.CHCAMASHO AS CAM ON CAM.CODICAMAS = EGR.CODICAMAS
                INNER JOIN INDIGO036.dbo.INUNIFUNC AS FUN ON CAM.UFUCODIGO = FUN.UFUCODIGO
            WHERE
                FUN.UFUTIPUNI <> '1'
            GROUP BY
                EGR.IPCODPACI,
                EGR.NUMINGRES
        ) AS G ON G.ID = EGR.ID
        INNER JOIN INDIGO036.dbo.CHCAMASHO AS CAM ON CAM.CODICAMAS = EGR.CODICAMAS
        INNER JOIN INDIGO036.dbo.INUNIFUNC AS FUN ON CAM.UFUCODIGO = FUN.UFUCODIGO
)
, CTE_ORDENES_CON_SALAS_CARGADAS AS (
    SELECT
        RC.AdmissionNumber,
        G.[INTERNACION COMPLEJIDAD ALTA CUATRO O MAS CAMAS],
        G.[DERECHOS DE SALA DE OBSERVACION EN URGENCIAS COMPLEJIDAD ALTA]
    FROM
        INDIGO036.Billing.RevenueControl AS RC
        INNER JOIN (
            SELECT *
            FROM (
                SELECT
                    RC.AdmissionNumber,
                    CUPS.Code AS CUPS,
                    CUPS.Description AS DESCRIPCION_CUPS
                FROM
                    INDIGO036.Billing.RevenueControlDetail AS RCD
                    INNER JOIN INDIGO036.Billing.RevenueControl AS RC ON RCD.RevenueControlId = RC.Id
                    INNER JOIN INDIGO036.Billing.ServiceOrderDetailDistribution AS SODD ON RCD.Id = SODD.RevenueControlDetailId
                    AND RCD.Status IN ('1', '2', '3')
                    INNER JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD ON SODD.ServiceOrderDetailId = SOD.Id
                    INNER JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON CUPS.Id = SOD.CUPSEntityId
                    AND CUPS.BillingGroupId IN (7, 8)
                    INNER JOIN INDIGO036.Contract.IPSService AS IPS ON IPS.Id = SOD.IPSServiceId
                WHERE
                    CUPS.Code IN ('10A004', '5DSA01')
                GROUP BY
                    RC.AdmissionNumber,
                    CUPS.Code,
                    CUPS.Description
            ) AS SourceTable
            PIVOT (
                MAX([CUPS]) FOR [DESCRIPCION_CUPS] IN (
                    [INTERNACION COMPLEJIDAD ALTA CUATRO O MAS CAMAS],
                    [DERECHOS DE SALA DE OBSERVACION EN URGENCIAS COMPLEJIDAD ALTA]
                )
            ) AS PVTTABLE
        ) AS G ON G.AdmissionNumber = RC.AdmissionNumber
),

CTE_ORDENES_CON_SALA_RECONOCIDAS AS (
    SELECT
        RC.AdmissionNumber
    FROM
        INDIGO036.Billing.RevenueControl AS RC
        INNER JOIN (
            SELECT
                RC.AdmissionNumber
            FROM
                INDIGO036.Billing.RevenueControlDetail AS RCD
                INNER JOIN INDIGO036.Billing.RevenueControl AS RC ON RCD.RevenueControlId = RC.Id
                INNER JOIN INDIGO036.Billing.ServiceOrderDetailDistribution AS SODD ON RCD.Id = SODD.RevenueControlDetailId
                AND RCD.Status IN ('1', '2', '3')
                INNER JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD ON SODD.ServiceOrderDetailId = SOD.Id
                INNER JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON CUPS.Id = SOD.CUPSEntityId
                AND CUPS.BillingGroupId IN (7, 8)
            WHERE
                CUPS.Code IN ('10A004', '5DSA01')
            GROUP BY
                RC.AdmissionNumber
        ) AS G ON G.AdmissionNumber = RC.AdmissionNumber
)
, CTE_TRIAGE_UNICO_POR_ATENCIÓN AS (
    SELECT
        A.IPCODPACI,
        A.CODCENATE,
        A.CODPROSAL,
        A.TRIANUMER,
        A.TRIACATEG,
        A.NUMINGRES,
        A.ID,
        A.TRIAFECHA,
        A.TRIAGECLA
    FROM
        INDIGO036.dbo.ADTRIAGEU A
    WHERE
        A.ID = (
            SELECT
                MAX(B.ID)
            FROM
                INDIGO036.dbo.ADTRIAGEU B
            WHERE
                A.IPCODPACI = B.IPCODPACI
                AND CAST(A.TRIAFECHA AS DATE) = CAST(B.TRIAFECHA AS DATE)
        )
),

CTE_HCURGING1 AS (
    SELECT
        K.NUMINGRES,
        K.NUMEFOLIO,
        K.CODPROSAL,
        K.UFUCODIGO,
        K.FECHINIHI,
        K.FECHFINH,
        K.INDICAPAC
    FROM
        INDIGO036.dbo.HCURGING1 K
    WHERE
        K.NUMEFOLIO = (
            SELECT
                MIN(CAST(FOL.NUMEFOLIO AS INT))
            FROM
                INDIGO036.dbo.HCURGING1 FOL
            WHERE
                K.NUMINGRES = FOL.NUMINGRES
        )
)
SELECT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    CEN.NOMCENATE AS [CENTRO DE ATENCIÓN],
    A.ID,
    RTRIM(HA.Name) AS ENTIDAD,
    RTRIM(E.Code) AS [CODIGO GRUPO ATENCION],
    RTRIM(E.Name) AS [GRUPO ATENCION],
    CASE
        HA.EntityType
        WHEN '1' THEN 'EPS Contributivo'
        WHEN '2' THEN 'EPS Subsidiado'
        WHEN '3' THEN 'ET Vinculados Municipios'
        WHEN '4' THEN 'ET Vinculados Departamentos'
        WHEN '5' THEN 'ARL Riesgos Laborales'
        WHEN '6' THEN 'MP Medicina Prepagada'
        WHEN '7' THEN 'IPS Privada'
        WHEN '8' THEN 'IPS Publica'
        WHEN '9' THEN 'Regimen Especial'
        WHEN '10' THEN 'Accidentes de transito'
        WHEN '11' THEN 'Fosyga'
        WHEN '12' THEN 'Otros'
        WHEN '13' THEN 'Aseguradoras'
    END AS REGIMEN,
    CASE
        U.IPTIPODOC
        WHEN 1 THEN 'CC'
        WHEN 2 THEN 'CE'
        WHEN 3 THEN 'TI'
        WHEN 4 THEN 'RC'
        WHEN 5 THEN 'PA'
        WHEN 6 THEN 'AS'
        WHEN 7 THEN 'MS'
        WHEN 8 THEN 'NU'
        WHEN 9 THEN 'CN'
        WHEN 10 THEN 'CD'
        WHEN 11 THEN 'SC'
        WHEN 12 THEN 'PE'
        WHEN 13 THEN 'PT'
        WHEN 14 THEN 'DE'
        WHEN 20 THEN 'OT'
    END AS [TIPO DOCUMENTO],
    A.IPCODPACI AS [IDENTIFICACION],
    U.IPPRIAPEL AS [PRIMER APELLIDO],
    U.IPSEGAPEL AS [SEGUNDO APELLIDO],
    U.IPPRINOMB AS [PRIMER NOMBRE],
    U.IPSEGNOMB AS [SEGUNDO NOMBRE],
    U.IPNOMCOMP AS PACIENTE,
    CASE WHEN U.IPSEXOPAC = '1' THEN 'M' WHEN U.IPSEXOPAC = '2' THEN 'F' END AS SEXO,
    U.IPFECNACI AS [FECHA NACIMIENTO],
    U.IPTELEFON AS TELEFONO,
    U.IPTELMOVI AS MOVIL,
    CASE
        WHEN DATEADD(YEAR, DATEDIFF(YEAR, U.IPFECNACI, ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA))), U.IPFECNACI) > ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA))
            THEN DATEDIFF(YEAR, U.IPFECNACI, ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA))) - 1
        ELSE DATEDIFF(YEAR, U.IPFECNACI, ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA)))
    END AS EDAD,
    GRU.Name AS [TIPO PACIENTE],
    A.NUMINGRES AS INGRESO,
    ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA)) AS [FECHA LLEGADA],
    CASE WHEN C.IPFECLLEGA IS NULL THEN 0 ELSE DATEDIFF(MINUTE, C.IPFECLLEGA, A.TRIAFECHA) END AS [MINUTOS ESPERA LLEGADA VS TRIAGE],
    CASE WHEN A.TRIAFECHA IS NULL THEN 'NO' ELSE 'SI' END AS ATENDIDO_TRIAGE,
    A.TRIAFECHA AS [FECHA TRIAGE],
    RTRIM(CONVERT(CHAR(8), A.TRIAFECHA, 108)) AS [HORA TRIAGE],
    CASE
        WHEN CONVERT(CHAR(8), A.TRIAFECHA, 108) BETWEEN '07:00:00' AND '12:59:59' THEN 'MAÑANA'
        WHEN CONVERT(CHAR(8), A.TRIAFECHA, 108) BETWEEN '13:00:00' AND '18:59:59' THEN 'TARDE'
        WHEN (
                (CONVERT(CHAR(8), A.TRIAFECHA, 108) BETWEEN '19:00:00' AND '23:59:59')
                OR (CONVERT(CHAR(8), A.TRIAFECHA, 108) BETWEEN '00:00:00' AND '06:59:59')
            ) AND DAY(A.TRIAFECHA) % 2 = 0 THEN 'NOCHE DÍA PAR'
        WHEN (
                (CONVERT(CHAR(8), A.TRIAFECHA, 108) BETWEEN '19:00:00' AND '23:59:59')
                OR (CONVERT(CHAR(8), A.TRIAFECHA, 108) BETWEEN '00:00:00' AND '06:59:59')
            ) AND DAY(A.TRIAFECHA) % 2 = 1 THEN 'NOCHE DÍA IMPAR'
        ELSE ''
    END AS JORNADA
    , A.TRIAGECLA AS [CLASIFICACION TRIAGE #],
    CASE A.TRIAGECLA
        WHEN 1 THEN 'I'
        WHEN 2 THEN 'II'
        WHEN 3 THEN 'III'
        WHEN 4 THEN 'IV'
        WHEN 5 THEN 'V'
    END AS CLASIFICACION_TRIAGE,
    C.OBVAUSENT AS [OBSERVACION AUSENCIA TRIAGE],
    CASE WHEN k.FECHINIHI IS NULL OR HC.FECHISPAC IS NULL THEN 'NO' ELSE 'SI' END AS ATENDIDO_CONSULTA,
    ES.DESESPECI AS [ESPECIALIDAD],
    CASE WHEN k.FECHINIHI IS NULL OR HC.FECHISPAC IS NULL THEN NULL ELSE CAST(ISNULL(k.FECHINIHI, I.IFECHAING) AS DATE) END AS [FECHA ATENCION MEDICA],
    CASE WHEN k.FECHINIHI IS NULL OR HC.FECHISPAC IS NULL THEN NULL ELSE RTRIM(CONVERT(CHAR(5), ISNULL(k.FECHINIHI, I.IFECHAING), 108)) END AS [HORA ATENCION MEDICA],
    CASE WHEN k.FECHINIHI IS NULL OR HC.FECHISPAC IS NULL THEN NULL ELSE DATEDIFF(MINUTE, A.TRIAFECHA, k.FECHINIHI) END AS [MINUTOS ESPERA TRIAGE VS CONSULTA],
    UNF.UFUCODIGO AS [CODIGO UNIDAD FUNCIONAL],
    UNF.UFUDESCRI AS [UNIDAD FUNCIONAL],
    CASE WHEN C.IPFECLLEGA IS NULL THEN 0 ELSE DATEDIFF(MINUTE, C.IPFECLLEGA, A.TRIAFECHA) END AS [OPORTUNIDAD FL vs FT (MIN)],
    CASE WHEN k.FECHINIHI IS NULL OR HC.FECHISPAC IS NULL THEN NULL ELSE DATEDIFF(MINUTE, A.TRIAFECHA, k.FECHINIHI) END AS [OPORTUNIDAD FT vs FA (MIN)],
    CASE WHEN C.IPFECLLEGA IS NULL THEN DATEDIFF(MINUTE, I.IFECHAING, A.TRIAFECHA) ELSE DATEDIFF(MINUTE, C.IPFECLLEGA, k.FECHINIHI) END AS [OPORTUNIDAD FL vs FA (MIN)],
    CASE
        WHEN C.CONESTADO = '1' THEN 'Sin Atender'
        WHEN C.CONESTADO = '2' THEN 'Ausente en Clasificacion TRIAGE'
        WHEN C.CONESTADO = '3' THEN 'Clasificado sin Ingreso'
        WHEN C.CONESTADO = '4' THEN 'Clasificado con Ingreso'
        WHEN C.CONESTADO = '5' THEN 'Atendido'
        WHEN C.CONESTADO = '6' THEN 'Ausente en Atencion Inicial Urgencias'
        WHEN C.CONESTADO = '7' THEN 'Anulado por error de Parametrizacion'
        WHEN C.CONESTADO = '8' THEN 'No atendido por Clasificacion sin Autorizacion'
        ELSE 'ATENDIDO'
    END AS [ESTADO PACIENTE],
    DX.CODDIAGNO AS [CIE10],
    DX.NOMDIAGNO AS [DIAGNOSTICO],
    ISNULL(k.FECHFINH, HC.FECHISPAC) AS [FECHA HORA FINAL CONSULTA],
    CASE WHEN k.FECHINIHI IS NULL THEN 0 ELSE DATEDIFF(MINUTE, k.FECHINIHI, k.FECHFINH) END AS [MINUTOS DE CONSULTA],
    CASE WHEN C.IPFECLLEGA IS NULL THEN DATEDIFF(MINUTE, I.IFECHAING, A.TRIAFECHA) ELSE DATEDIFF(MINUTE, C.IPFECLLEGA, k.FECHINIHI) END AS [MINUTOS LLEGADA VS ATENCION],
    CASE
        WHEN TRA.MEDIOTRASPORTE = 1 THEN 'Básica'
        WHEN TRA.MEDIOTRASPORTE = 2 THEN 'Medicalizada'
    END AS TIPO_DE_AMBULANCIA
    , DXA.CODDIAGNO AS [CODIGO EGRESO],
    DXA.NOMDIAGNO AS [DIAGNOSTICO EGRESO],
    ISNULL(I.FECHEGRESO, EGR.FECALTPAC) AS [FECHA EGRESO],
    ISNULL(
        CASE k.INDICAPAC
            WHEN 1 THEN 'Trasladar a Urgencias'
            WHEN 2 THEN 'Trasladar a Observación Urgencias'
            WHEN 3 THEN 'Trasladar a Hospitalización'
            WHEN 7 THEN 'Trasladar a Consulta Externa'
            WHEN 9 THEN 'Hospitalización en Casa'
            WHEN 10 THEN 'Referencia'
            WHEN 11 THEN 'Morgue'
            WHEN 12 THEN 'Salida'
            WHEN 13 THEN 'Continúa en la Unidad'
            WHEN 15 THEN 'Retiro Voluntario'
            WHEN 16 THEN 'Fuga'
        END,
        CASE WHEN FUNEA.UFUDESCRI IS NULL THEN 'CONTINUA EN LA UNIDAD' ELSE 'SALIDA' END
    ) AS [DESTINO PACIENTE],
    FUNEA.UFUCODIGO AS [COD. UNIDAD DE EGRESO],
    FUNEA.UFUDESCRI AS [UNIDAD DE EGRESO],
    CASE WHEN MUE.ID IS NULL THEN 'NO' ELSE 'SI' END AS FALLECIDO,
    MUE.FECHA_MUERTE,
    CASE WHEN MUE.ID IS NOT NULL AND DATEDIFF(MINUTE, C.IPFECLLEGA, C.IPFECLLEGA) < 1440 THEN 'SI' ELSE 'NO' END AS [MORTALIDAD URGENCIAS < 24],
    CASE WHEN MUE.ID IS NOT NULL AND DATEDIFF(MINUTE, C.IPFECLLEGA, C.IPFECLLEGA) > 2880 THEN 'SI' ELSE 'NO' END AS [MORTALIDAD URGENCIAS > 48],
    CASE I.IESTADOIN
        WHEN ' ' THEN 'Abierto'
        WHEN 'F' THEN 'Facturado'
        WHEN 'C' THEN 'Cerrado'
        WHEN 'A' THEN 'Anulado'
        WHEN 'P' THEN 'Parcial'
        WHEN 'B' THEN 'Bloqueado'
    END AS [ESTADO INGRESO],
    CASE I.IINGREPOR
        WHEN 1 THEN 'Urgencias'
        WHEN 2 THEN 'Urgencias'
        WHEN 3 THEN 'Urgencias'
        WHEN 4 THEN 'Remitido'
        WHEN 5 THEN 'Urgencias'
    END AS [TIPO INGRESO],
    CASE I.IREINGRES
        WHEN 1 THEN 'SI'
        WHEN 2 THEN 'NO'
        ELSE 'NO'
    END AS REINGRESO,
    I.NUMINGREI AS [NUMERO REINGRESO],
    A.CODPROSAL AS [IDE PROFESIONAL TRIAGE],
    P.NOMMEDICO AS [PROFESIONAL TRIAGE],
    PAIU.CODPROSAL AS [ID PROFESIONAL CONSULTA],
    PAIU.NOMMEDICO AS [PROFESIONAL CONSULTA],
    CASE WHEN REC.AdmissionNumber IS NULL THEN 'NO' ELSE 'SI' END AS [RECONOCIDO CONSULTA],
    EST.[CONSULTA DE URGENCIAS POR MEDICINA GENERAL],
    EST.[CONSULTA DE URGENCIAS POR OTRAS ESPECIALIDADES MEDICAS],
    EST.[CONSULTA DE URGENCIAS POR ODONTOLOGIA GENERAL],
    EST.[CONSULTA DE URGENCIAS POR ODONTOLOGIA ESPECIALIZADA],
    CAM.CAMA_OBSERVACION,
    HOS.CAMA_HOSPITALIZACION,
    SAL.[INTERNACION COMPLEJIDAD ALTA CUATRO O MAS CAMAS],
    SAL.[DERECHOS DE SALA DE OBSERVACION EN URGENCIAS COMPLEJIDAD ALTA],
    1 AS CANTIDAD,
    CAST(ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA)) AS DATE) AS [FECHA BUSQUEDA],
    YEAR(ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA))) AS [AÑO BUSQUEDA],
    MONTH(ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA))) AS [MES BUSQUEDA],
    CONCAT(
        FORMAT(MONTH(ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA))), '00'), ' - ',
        CASE MONTH(ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA)))
            WHEN 1 THEN 'ENERO'
            WHEN 2 THEN 'FEBRERO'
            WHEN 3 THEN 'MARZO'
            WHEN 4 THEN 'ABRIL'
            WHEN 5 THEN 'MAYO'
            WHEN 6 THEN 'JUNIO'
            WHEN 7 THEN 'JULIO'
            WHEN 8 THEN 'AGOSTO'
            WHEN 9 THEN 'SEPTIEMBRE'
            WHEN 10 THEN 'OCTUBRE'
            WHEN 11 THEN 'NOVIEMBRE'
            WHEN 12 THEN 'DICIEMBRE'
        END
    ) AS [MES NOMBRE BUSQUEDA],
    CAST(GETDATE() AS DATETIME) AS ULT_ACTUAL
FROM CTE_TRIAGE_UNICO_POR_ATENCIÓN A
    INNER JOIN INDIGO036.dbo.INPACIENT U ON A.IPCODPACI = U.IPCODPACI
    INNER JOIN INDIGO036.Contract.CareGroup E ON E.Id = U.GENCAREGROUP
    LEFT JOIN INDIGO036.dbo.ADCENATEN CEN ON A.CODCENATE = CEN.CODCENATE
    LEFT JOIN INDIGO036.dbo.INPROFSAL P ON P.CODPROSAL = A.CODPROSAL
    LEFT JOIN INDIGO036.dbo.ADCONTURG C ON A.TRIANUMER = C.CODCONCEC
    LEFT JOIN INDIGO036.dbo.INPROFSAL Pa ON Pa.CODPROSAL = C.PROAUSENT
    LEFT JOIN INDIGO036.dbo.INESPECIA ES ON ES.CODESPECI = P.CODESPEC1
    LEFT JOIN INDIGO036.dbo.ADCATTRIU ds ON A.TRIACATEG = ds.TRIACATEG
    LEFT JOIN CTE_HCURGING1 k ON A.NUMINGRES = k.NUMINGRES
    LEFT JOIN INDIGO036.dbo.ADINGRESO I ON A.NUMINGRES = I.NUMINGRES
    LEFT JOIN INDIGO036.Contract.HealthAdministrator HA ON HA.Id = ISNULL(I.GENCONENTITY, U.GENCONENTITY)
    LEFT JOIN INDIGO036.dbo.HCHISPACA HC ON A.NUMINGRES = HC.NUMINGRES AND HC.FECHISPAC = (SELECT MIN(H.FECHISPAC) FROM INDIGO036.dbo.HCHISPACA H WHERE A.NUMINGRES = H.NUMINGRES)
    LEFT JOIN INDIGO036.dbo.INPROFSAL PAIU ON ISNULL(k.CODPROSAL, HC.CODPROSAL) = PAIU.CODPROSAL
    LEFT JOIN INDIGO036.dbo.INDIAGNOS DX ON DX.CODDIAGNO = I.CODDIAING
    LEFT JOIN INDIGO036.dbo.INDIAGNOS DXA ON DXA.CODDIAGNO = I.CODDIAEGR
    LEFT JOIN (SELECT MAX(AUTO) AS AUTO, NUMINGRES FROM INDIGO036.dbo.HCREFCONP GROUP BY NUMINGRES) AS OTRA ON OTRA.NUMINGRES = I.NUMINGRES
    LEFT JOIN CTE_MUERTOS MUE ON A.NUMINGRES = MUE.INGRESO
    LEFT JOIN INDIGO036.dbo.HCTRASLADOS TRA ON TRA.IDHCREFCONP = OTRA.AUTO
    LEFT JOIN INDIGO036.dbo.HCREGEGRE EGR ON I.NUMINGRES = EGR.NUMINGRES AND EGR.NUMEFOLIO = (SELECT MAX(E.NUMEFOLIO) FROM INDIGO036.dbo.HCREGEGRE E WHERE I.NUMINGRES = E.NUMINGRES)
    LEFT JOIN INDIGO036.dbo.INUNIFUNC FUNEA ON EGR.UFUCODIGO = FUNEA.UFUCODIGO
    LEFT JOIN INDIGO036.dbo.INUNIFUNC UNF ON ISNULL(k.UFUCODIGO, I.UFUCODIGO) = UNF.UFUCODIGO
    LEFT JOIN INDIGO036.Admissions.TypesPopulationGroups GRU ON C.CODTIPPAC = GRU.Code
    LEFT JOIN CTE_ORDENES_CON_ESTANCIA_RECONOCIDAS REC ON REC.AdmissionNumber = I.NUMINGRES
    LEFT JOIN CTE_ORDENES_CON_ESTANCIAS_CARGADAS EST ON EST.AdmissionNumber = I.NUMINGRES
    LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA_OBSERVACION CAM ON CAM.NUMINGRES = I.NUMINGRES
    LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA_HOSPITALIZACION HOS ON HOS.NUMINGRES = I.NUMINGRES
    LEFT JOIN CTE_ORDENES_CON_SALAS_CARGADAS SAL ON SAL.AdmissionNumber = I.NUMINGRES
WHERE
    UNF.UFUCODIGO IN ('1111001','1111002') AND k.INDICAPAC = '3'