-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_VIEWNURSINGNOTES
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW Report.VW_VIEWNURSINGNOTES
AS

WITH CTE_INGRESOS AS (
    SELECT
        NUMINGRES
    FROM
        [INDIGO036].[dbo].[HCCTRNOTE]
    WHERE
        CAST(FECREGIST AS DATE) BETWEEN GETDATE() -365
        AND GETDATE()
    GROUP BY
        NUMINGRES
),
CTE_NOTAS AS (
    SELECT
        IPCODPACI,
        CAST(FECREGIST AS DATE) AS FECHA,
        DATENAME(WEEKDAY, FECREGIST) AS DIA,
        NUMINGRES,
        UFUCODIGO
    FROM
        [INDIGO036].[dbo].[HCCTRNOTE]
    WHERE
        CAST(FECREGIST AS DATE) BETWEEN GETDATE() -365
        AND GETDATE()
    GROUP BY
        IPCODPACI,
        CAST(FECREGIST AS DATE),
        DATENAME(WEEKDAY, FECREGIST),
        NUMINGRES,
        UFUCODIGO
),
CTE_NOTAS_ENFERMERIA AS (
    SELECT
        NOTE.NUMINGRES,
        FECREGIST AS FECHA,
        CASE
            TITNOTENF
            WHEN 'HISTORIA INICIAL DE ENFERMERIA' THEN 1
            WHEN 'HISTORIA FINAL DE ENFERMERIA' THEN 2
        END AS NOTA,
        NOTE.TITNOTENF AS 'OBSERVACION',
        NOTE.NOTENFOBJ AS 'DESCRIPCION NOTA'
    FROM
        [INDIGO036].[dbo].[HCCTRNOTE] NOTE
        INNER JOIN CTE_INGRESOS ING ON NOTE.NUMINGRES = ING.NUMINGRES
    WHERE
        (
            TITNOTENF = 'HISTORIA INICIAL DE ENFERMERIA'
            OR TITNOTENF = 'HISTORIA FINAL DE ENFERMERIA'
        )
)
SELECT
    NOTA.IPCODPACI AS IDENTIFICACION,
    NOTA.NUMINGRES AS INGRESO,
    NOTA.FECHA,
    UF.UFUDESCRI AS [UNIDAD FUNCIONAL],
    CAM.DESCCAMAS AS [CAMA ACTUAL],
    CASE
        NOTA.DIA
        WHEN 'MONDAY' THEN 'LUNES'
        WHEN 'TUESDAY' THEN 'MARTES'
        WHEN 'WEDNESDAY' THEN 'MIERCOLES'
        WHEN 'THURSDAY' THEN 'JUEVES'
        WHEN 'FRIDAY' THEN 'VIERNES'
        WHEN 'SATURDAY' THEN 'SABADO'
        WHEN 'SUNDAY' THEN 'DOMINGO'
    END AS DIA,
    IMA.FECHA AS [NOTA INICIAL MAÑANA],
    FMA.FECHA AS [NOTA FINAL MAÑANA],
    ITA.FECHA AS [NOTA INICIAL TARDE],
    FTA.FECHA AS [NOTA FINAL TARDE],
    INO.FECHA AS [NOTA INICIAL NOCHE],
    FNO.FECHA AS [NOTA FINAL NOCHE],
    IMA.OBSERVACION,
    IMA.[DESCRIPCION NOTA]
FROM
    CTE_NOTAS NOTA
    INNER JOIN [INDIGO036].[dbo].[INUNIFUNC] UF ON NOTA.UFUCODIGO = UF.UFUCODIGO
    INNER JOIN [INDIGO036].[dbo].[ADINGRESO] ING ON NOTA.NUMINGRES = ING.NUMINGRES
    LEFT JOIN [INDIGO036].[dbo].[CHCAMASHO] CAM ON ING.CODCAMACT = CAM.CODICAMAS
    LEFT JOIN CTE_NOTAS_ENFERMERIA IMA ON NOTA.NUMINGRES = IMA.NUMINGRES
        AND NOTA.FECHA = CAST(IMA.FECHA AS DATE)
        AND IMA.NOTA = 1
        AND CAST(IMA.FECHA AS TIME) BETWEEN '06:30:00'
        AND '07:30:00'
    LEFT JOIN CTE_NOTAS_ENFERMERIA FMA ON NOTA.NUMINGRES = FMA.NUMINGRES
        AND NOTA.FECHA = CAST(FMA.FECHA AS DATE)
        AND FMA.NOTA = 2
        AND CAST(FMA.FECHA AS TIME) BETWEEN '12:30:00'
        AND '13:30:00'
    LEFT JOIN CTE_NOTAS_ENFERMERIA ITA ON NOTA.NUMINGRES = ITA.NUMINGRES
        AND NOTA.FECHA = CAST(ITA.FECHA AS DATE)
        AND ITA.NOTA = 1
        AND CAST(ITA.FECHA AS TIME) BETWEEN '12:30:00'
        AND '13:30:00'
    LEFT JOIN CTE_NOTAS_ENFERMERIA FTA ON NOTA.NUMINGRES = FTA.NUMINGRES
        AND NOTA.FECHA = CAST(FTA.FECHA AS DATE)
        AND FTA.NOTA = 2
        AND CAST(FTA.FECHA AS TIME) BETWEEN '18:30:00'
        AND '19:30:00'
    LEFT JOIN CTE_NOTAS_ENFERMERIA INO ON NOTA.NUMINGRES = INO.NUMINGRES
        AND NOTA.FECHA = CAST(INO.FECHA AS DATE)
        AND INO.NOTA = 1
        AND CAST(INO.FECHA AS TIME) BETWEEN '18:30:00'
        AND '19:30:00'
    LEFT JOIN CTE_NOTAS_ENFERMERIA FNO ON NOTA.NUMINGRES = FNO.NUMINGRES
        AND NOTA.FECHA = CAST(FNO.FECHA AS DATE)
        AND FNO.NOTA = 2
        AND CAST(FNO.FECHA AS TIME) BETWEEN '06:30:00'
        AND '07:30:00'