-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_VIEWQXINFORME
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_VIEWQXINFORMECIRUGIA AS

WITH CTE_INFORME_QX AS (
	SELECT
		CODCENATE,
		IPCODPACI,
		NUMEFOLIO,
		UFUCODIGO,
		CODDIAPRE,
		CODDIAPOS,
		CODPROSAL,
		CODSERIPS,
		TIPOANEST,
		FECHORINI,
		FECHORFIN,
		SALACIRUG,
		CLASIFASA,
		URGECIRUG,
		TIPOINFORME,
		NUMINGRES
	FROM
		INDIGO036.dbo.HCQXINFOR INF
),
CTE_ANESTESIA AS (
	select
		ROW_NUMBER() OVER(
			PARTITION BY ANES.IPCODPACI
			ORDER BY
				ANES.NUMEFOLIO DESC
		) NUMERO,
		ANES.IPCODPACI,
		ANES.UFUCODIGO,
		ANES.NUMINGRES,
		ANES.DIAGNPREO,
		ANES.DIAGNPOSO,
		ANES.HORINICIRU,
		CAST(ANES.HORINICIRU AS DATE) FECHAINICIA,
		CAST(ANES.HORFINCIRU AS DATE) FECHAFIN,
		ANES.HORINIANES,
		ANES.HORFINANES,
		ANES.DURACIRUG,
		ANES.DURAANEST,
		ANES.CODPROSAL 'ANESTESIOLOGO',
		ANES.FECHAREGISTRO,
		ANES.IDHCHISPACA,
		ANES.TIPOREGISTRO,
		ANES.NUMEFOLIO
	from
		INDIGO036.dbo.HCREGANES ANES
	WHERE
		/*ANES.IPCODPACI='1010252346' AND*/
		TIPOREGISTRO IN (2, 3)
),
CTE_RADICACIONES AS (
	SELECT
		ID,
		IPCODPACI,
		NUMRADICACION,
		ESTADO,
		FECHACONFIRMACION,
		QXPRINCIPAL
	FROM
		INDIGO036.dbo.ADRADICACIONQX
	WHERE
		ESTADO = 2
),
CTE_ORDEN_MEDICA AS (
	SELECT
		IPCODPACI,
		NUMEFOLIO,
		NUMINGRES,
		UFUCODIGO,
		CODPROSAL,
		CODSERIPS,
		ESTSERIPS,
		FECORDMED,
		PRISERIPS
	FROM
		INDIGO036.dbo.HCORDPROQ
),
CTE_PROCEDIMIENTOS_NOQX AS (
	SELECT
		ROW_NUMBER () OVER (
			PARTITION BY CODSERIPS
			ORDER BY
				IPCODPACI ASC
		) NUMERO,
		IPCODPACI,
		NUMINGRES,
		NUMEFOLIO,
		UFUCODIGO,
		CODPROSAL,
		FECORDMED,
		CODSERIPS,
		CANSERIPS,
		OBSSERIPS
	FROM
		INDIGO036.dbo.HCORDPRON
)
SELECT
	DISTINCT CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
	CEN.NOMCENATE 'CENTRO DE ATENCION',
	INF.UFUCODIGO 'COD. UF',
	FUN.UFUDESCRI 'UNIDAD FUNCIONAL RALIZA',
	CASE
		PAC.IPTIPODOC
		WHEN '1' THEN 'CC'
		WHEN '2' THEN 'CE'
		WHEN '3' THEN 'TI'
		WHEN '4' THEN 'RC'
		WHEN '5' THEN 'PA'
		WHEN '6' THEN 'AS'
		WHEN '7' THEN 'MS'
		WHEN '8' THEN 'NU'
		WHEN '9' THEN 'CN'
		WHEN '10' THEN 'CD'
		WHEN '11' THEN 'SC'
		WHEN '12' THEN 'PE'
		WHEN '13' THEN 'PT'
		WHEN '14' THEN 'DE'
		WHEN '15' THEN 'SI'
		ELSE 'N/A'
	END 'TIPO DOCUMENTO',
	INF.IPCODPACI,
	RTRIM(PAC.IPPRINOMB) 'PRIMER NOMBRE',
	RTRIM(PAC.IPSEGNOMB) 'SEGUNDO NOMBRE',
	RTRIM(PAC.IPPRIAPEL) 'PRIMER APELLIDO',
	RTRIM(PAC.IPSEGAPEL) 'SEGUNDO APELLIDO',
	RTRIM(PAC.IPNOMCOMP) 'NOMBRE COMPLETO PACIENTE',
	PAC.IPFECNACI 'FECHA NACIMIENTO',
	FLOOR(
		(
			CAST(CONVERT(VARCHAR(8), INF.FECHORINI, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)
		) / 10000
	) AS 'EDAD',
	CASE
		WHEN PAC.IPSEXOPAC = '1' THEN 'M'
		ELSE 'F'
	END 'GENERO',
	INF.SALACIRUG 'SALA',
	RAD.FECHACONFIRMACION 'FECHA RADICACION',
	ISNULL(ORD.FECORDMED, PRON.FECORDMED) 'FECHA ORDEN (HOSPITALARIO)',
	CASE
		WHEN RAD.FECHACONFIRMACION IS NULL
		AND ORD.FECORDMED IS NULL THEN 'SI'
		ELSE 'NO'
	END 'HALAZGO QX/PROC. NO QX?',
	YEAR(INF.FECHORFIN) 'AÑO CIRUGIA',
	CASE
		MONTH(INF.FECHORFIN)
		WHEN 1 THEN 'Enero'
		WHEN 2 THEN 'Febrero'
		WHEN 3 THEN 'Marzo'
		WHEN 4 THEN 'Abril'
		WHEN 5 THEN 'Mayo'
		WHEN 6 THEN 'Junio'
		WHEN 7 THEN 'Julio'
		WHEN 8 THEN 'Agosto'
		WHEN 9 THEN 'Septiembre'
		WHEN 10 THEN 'Octubre'
		WHEN 11 THEN 'Noviembre'
		WHEN 12 THEN 'Diciembre'
	END 'MES CIRUGIA',
	DAY(INF.FECHORFIN) 'DIA CIRUGIA',
	INF.NUMEFOLIO 'FOLIO INF. QX',
	INF.FECHORINI 'INICIO CX',
	INF.FECHORFIN 'FIN CX',
	CAST(INF.FECHORINI AS DATE) FECHA_CIRUGIA,
	DATEDIFF(MINUTE, INF.FECHORINI, INF.FECHORFIN) 'DURACION CX (MINUTOS)',
	ANES.HORINIANES 'INICIA ANESTESIA',
	HORFINANES 'FIN ANESTESIA',
	DATEDIFF(MINUTE, ANES.HORINIANES, ANES.HORFINANES) 'DURACION ANESTESIA (MINUTOS)',
	INF.CODDIAPRE 'DX PREOPERATORIO',
	INF.CODDIAPOS 'DX. POSTOPERATORIO',
	DATEDIFF(DAY, RAD.FECHACONFIRMACION, INF.FECHORINI) 'OPORTUNIDAD DIAS DESDE RADICACION',
CASE
		WHEN ORD.FECORDMED IS NOT NULL THEN DATEDIFF(DAY, ORD.FECORDMED, INF.FECHORINI)
		ELSE DATEDIFF(DAY, PRON.FECORDMED, INF.FECHORINI)
	END 'OPORTUNIDAD DIAS DESDE ORDEN MEDICA',
	INF.CLASIFASA 'ASA',
	INF.CODSERIPS 'COD. CUPS',
	CUPS.DESCODCUPS 'NOMBRE SERVICIO',
	/*CASE WHEN REA1.CODSERIPS IS NOT NULL THEN 'SI' ELSE 'NO' END 'PRINCIPAL?' , */
	CASE
		INF.TIPOANEST
		WHEN 1 THEN 'Local'
		WHEN 2 THEN 'Regional'
		WHEN 3 THEN 'General'
		WHEN 4 THEN 'Combinada'
		WHEN 5 THEN 'No Aplica'
	END 'TIPO ANESTESIA',
	CASE
		WHEN INF.URGECIRUG = 0 THEN 'NO'
		ELSE 'SI'
	END 'CIRUGIA DE URGENCIA',
	INF.CODPROSAL 'COD. CIRUJANO',
	PRO1.NOMMEDICO 'CIRUJANO',
	ESP.DESESPECI 'ESPECIALIDAD',
CASE
		INF.TIPOINFORME
		WHEN 1 THEN 'Informe Qx'
		ELSE 'Informe No Qx'
	END 'TIPO INFORME',
	INF.NUMINGRES '# INGRESO',
	ANES.ANESTESIOLOGO 'COD. ANESTESIOLOGO',
	PRO2.NOMMEDICO 'ANESTESIOLOGO',
	REA1.CODSERIPS 'PROC.PRINCIPAL',
	REA2.CODSERIPS 'PROC. SECUNDARIO',
	CG.Code 'COD. GRUPO ATENCION',
	CG.Name 'GRUPO ATENCION',
	HA.HealthEntityCode 'CODIGO ENTIDAD',
	HA.Name 'ENTIDAD',
	CASE
		WHEN rtrim(convert(char(5), INF.FECHORINI, 108)) BETWEEN '07:00'
		AND '13:00' THEN 'Mañana'
		WHEN rtrim(convert(char(5), INF.FECHORINI, 108)) BETWEEN '13:00'
		AND '18:00' THEN 'Tarde'
		ELSE 'Noche'
	END 'JORNADA',
	CASE
		CX.ORIGENQX
		WHEN 1 THEN 'Ambulatorio'
		ELSE 'Hospitalario'
	END 'AMBITO',
	1 as 'CANTIDAD',
	CAST(INF.FECHORFIN AS date) AS 'FECHA BUSQUEDA',
	YEAR(INF.FECHORFIN) AS 'AÑO FECHA BUSQUEDA',
	MONTH(INF.FECHORFIN) AS 'MES AÑO FECHA BUSQUEDA',
	CASE
		MONTH(INF.FECHORFIN)
		WHEN 1 THEN 'ENERO'
		WHEN 2 THEN 'FEBRERO'
		WHEN 3 THEN 'MARZO'
		WHEN 4 THEN 'ABRIL'
		WHEN 5 THEN 'MAYO'
		WHEN 6 THEN 'JUNIO'
		WHEN 7 THEN 'JULIO'
		WHEN 8 THEN 'AGOSTO'
		WHEN 9 THEN 'SEPTIEMBRE'
		WHEN 10 THEN 'OCTUBRE'
		WHEN 11 THEN 'NOVIEMBRE'
		WHEN 12 THEN 'DICIEMBRE'
	END AS 'MES NOMBRE FECHA BUSQUEDA',
	FORMAT(DAY(INF.FECHORFIN), '00') AS 'DIA FECHA BUSQUEDA',
	CONVERT(
		DATETIME,
		GETDATE() AT TIME ZONE 'Pakistan Standard Time',
		1
	) AS ULT_ACTUAL
FROM
	CTE_INFORME_QX INF
	LEFT JOIN INDIGO036.dbo.HCQXREALI REA1 ON REA1.CODSERIPS = INF.CODSERIPS
	AND INF.IPCODPACI = REA1.IPCODPACI
	AND INF.NUMINGRES = REA1.NUMINGRES
	AND REA1.QXPRINCIP = 1
	LEFT JOIN INDIGO036.dbo.HCQXREALI REA2 ON REA2.CODSERIPS = INF.CODSERIPS
	AND INF.IPCODPACI = REA2.IPCODPACI
	AND INF.NUMINGRES = REA2.NUMINGRES
	AND REA2.QXPRINCIP NOT IN (1)
	AND REA2.CODSERIPS <> REA1.CODSERIPS
	LEFT JOIN INDIGO036.dbo.AGEPROGQX PROG ON PROG.IPCODPACI = REA1.IPCODPACI
	AND PROG.CODSERIPS = INF.CODSERIPS
	LEFT JOIN CTE_ANESTESIA ANES ON ANES.IPCODPACI = INF.IPCODPACI
	/*AND INF.NUMINGRES=ANES.NUMINGRES*/
	AND ANES.FECHAINICIA = CAST(INF.FECHORINI AS DATE) --AND NUMERO=1
	LEFT JOIN CTE_RADICACIONES RAD ON PROG.IDRADICACIONQX = RAD.ID
	AND RAD.FECHACONFIRMACION < INF.FECHORINI
	LEFT JOIN CTE_ORDEN_MEDICA ORD ON ORD.IPCODPACI = INF.IPCODPACI
	AND REA1.CODSERIPS = ORD.CODSERIPS
	AND ORD.FECORDMED < INF.FECHORINI
	LEFT JOIN CTE_PROCEDIMIENTOS_NOQX PRON ON PRON.IPCODPACI = INF.IPCODPACI
	AND PRON.CODSERIPS = INF.CODSERIPS
	AND PRON.FECORDMED < INF.FECHORINI
	AND PRON.NUMERO = 1
	LEFT JOIN INDIGO036.dbo.INCUPSIPS CUPS ON CUPS.CODSERIPS = INF.CODSERIPS
	LEFT JOIN INDIGO036.dbo.ADCENATEN CEN ON CEN.CODCENATE = INF.CODCENATE
	LEFT JOIN INDIGO036.dbo.INPACIENT PAC ON PAC.IPCODPACI = INF.IPCODPACI
	LEFT JOIN INDIGO036.dbo.INPROFSAL PRO1 ON PRO1.CODPROSAL = INF.CODPROSAL
	LEFT JOIN INDIGO036.dbo.INPROFSAL PRO2 ON PRO2.CODPROSAL = ANES.ANESTESIOLOGO
	LEFT JOIN INDIGO036.Contract.HealthAdministrator HA ON HA.Id = PAC.GENCONENTITY
	LEFT JOIN INDIGO036.Contract.CareGroup CG ON CG.Id = PAC.GENCAREGROUP
	LEFT JOIN INDIGO036.dbo.AGEPROGQX CX ON CX.IPCODPACI = INF.IPCODPACI
	AND CX.CODSERIPS = INF.CODSERIPS
	AND CX.NUMINGRES = INF.NUMINGRES
	LEFT JOIN INDIGO036.dbo.INUNIFUNC FUN ON FUN.UFUCODIGO = INF.UFUCODIGO
	LEFT JOIN INDIGO036.dbo.HCHISPACA HIS ON HIS.NUMINGRES = INF.NUMINGRES
	AND HIS.NUMEFOLIO = INF.NUMEFOLIO
	AND HIS.IPCODPACI = INF.IPCODPACI
	LEFT JOIN INDIGO036.dbo.INESPECIA ESP ON ESP.CODESPECI = HIS.CODESPTRA