-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_VIEWINVENTARIOHISTORICOPRESCRIPCION
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_ViewInventarioHistoricoPrescripcion
AS

WITH CTE_INGRESO AS
(
SELECT 
    ING.NUMINGRES,
    ING.FECHEGRESO,
    CAM.DESCCAMAS
FROM 
    [INDIGO036].[dbo].[ADINGRESO] AS ING 
INNER JOIN [INDIGO036].[dbo].[CHCAMASHO] AS CAM ON ING.CODCAMACT=CAM.CODICAMAS
),
CTE_DEVOLUCION_DISPENSACION AS
(
SELECT
    DISD.Id AS DispensacionDetalleId,
    DD.Code AS CodigoDevolucionDispensacion,
    DD.ConfirmationDate as FechaDevolucion,
    USU.NOMUSUARI AS Regente,
    DDD.Quantity AS Cantidad,
    PRO.NOMMEDICO,
    CASE PRO.TIPPROFES WHEN 1 THEN 'Medico General' 
                   WHEN 2 THEN 'Medico Especialista' 
                   WHEN 3 THEN 'Enfermera'
                   WHEN 4 THEN 'Auxiliar Enfermeria' 
                   WHEN 16 THEN 'Terapeuta'
                   WHEN 21 THEN 'Instrumentador' END PROFESION,
    FECREGISTR
FROM
    [INDIGO036].[Inventory].[PharmaceuticalDispensingDevolutionDetail] AS DDD 
INNER JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensingDetailBatchSerial] AS BAT ON DDD.PharmaceuticalDispensingDetailBatchSerialId=BAT.Id 
INNER JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensingDetail] AS DISD ON BAT.PharmaceuticalDispensingDetailId=DISD.Id 
INNER JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensingDevolution] AS DD ON DDD.PharmaceuticalDispensingDevolutionId=DD.Id AND DD.Status=2 
INNER JOIN [INDIGO036].[dbo].[SEGusuaru] AS USU ON DD.ConfirmationUser=USU.CODUSUARI 
LEFT JOIN [INDIGO036].[dbo].[HCDEVMEDC] AS DEV ON DD.EntityId=DEV.CODCONCEC 
LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] AS PRO ON DEV.CODPROSAL=PRO.CODPROSAL
),
CTE_DETALLE_FARMACIA AS
(
SELECT 
    D.CODCONCEC,A.NUMINGRES,A.CODPRODUC,D.CODUNIMED,D.ID,
    ISNULL(A.DOSISPROD,D.DOSISPROD) AS DOSISPROD,A.FRECUENCI,A.UNIFRECUE,A.DURACIDOS,D.CANPEDPRO
FROM 
    [INDIGO036].[dbo].[HCFARMEPC] AS C 
INNER JOIN [INDIGO036].[dbo].[HCFARMEPD] AS D ON C.CODCONCEC=D.CODCONCEC 
INNER JOIN [INDIGO036].[dbo].[HCPRESCRA] AS A ON A.NUMINGRES= D.NUMINGRES AND A.CODPRODUC=D.CODPRODUC AND (C.FECHAORDE>=A.FECINIDOS AND C.FECHAORDE<=A.FECFINDOS)
UNION ALL
SELECT
    D.CODCONCEC,A.NUMINGRES,A.CODPRODUC,D.CODUNIMED,D.ID,
    ISNULL(A.DOSISPROD,D.DOSISPROD) AS DOSISPROD,A.FRECUENCI,A.UNIFRECUE,A.DURACIDOS,D.CANPEDPRO
FROM 
    [INDIGO036].[dbo].[HCFARMEPC] AS C 
INNER JOIN [INDIGO036].[dbo].[HCFARMEPD] AS D ON C.CODCONCEC=D.CODCONCEC 
INNER JOIN [INDIGO036].[dbo].[HCPRESCRA] AS A ON A.NUMINGRES= D.NUMINGRES AND A.CODPRODUC=D.CODPRODUC AND C.FECHAORDE>=A.FECINIDOS AND A.PREESTADO NOT IN (2,4,5,6,7)
),
CTE_LIQUIDOS AS
(
SELECT 
    FAR.ID,
    ISNULL(FAR.FECINIDOS,A.FECHAINIC) AS FECHA,
    CASE A.PREESTADO WHEN 1 THEN 'TRATAMIENTO NUEVO'ELSE 'TRATAMIENTO ANTIGUO'END AS ESTADO,
    A.NUMINGRES,
    A.UFUCODIGO,
    A.NUMEFOLIO,
    A.IPCODPACI,
    FAR.CODPRODUC,
    FAR.DOSISPROD AS DOSIS,
    CASE WHEN D.UNIMEDBOL IS NOT NULL THEN D.UNIMEDBOL
         WHEN D.UNIMEDINF IS NOT NULL THEN D.UNIMEDINF 
         WHEN D.UNIMEDDIL IS NOT NULL THEN D.UNIMEDDIL END AS MEDIDA,
    FAR.FRECUENCI AS FRECUENCIA,
    CASE FAR.UNIFRECUE WHEN 1 THEN 'MINUTOS'
                       WHEN 2 THEN 'HORAS'
                       WHEN 3 THEN 'DIAS' END AS TIEMPO,
    'INTRAVENOSA' as ADMINISTRACION,
    ISNULL(D.DURACIINF,'Dosis Unica') as DURACION,
    CASE D.DURACIINF WHEN 'Tratamiento Continuo' THEN DATEDIFF(DAY,A.FECHAINIC,GETDATE()) END AS TRATAMIENTO,
    D.CANPROCAL AS CANTIDAD,
    A.CODPROSAL AS PROFESIONAL
FROM 
    [INDIGO036].[dbo].[HCFARMEPD] AS FAR 
INNER JOIN [INDIGO036].[dbo].[HCINFLIQA] AS A ON FAR.IdSourceTable=A.CONSECUTI AND FAR.SourceTable='HCINFLIQA' 
INNER JOIN [INDIGO036].[dbo].[HCINFLIQD] AS D ON A.CODCONCEC=D.CODCONCEC
WHERE CAST(A.FECHAINIC AS DATE) BETWEEN CAST(GETDATE()-200 AS DATE) AND CAST(GETDATE() AS DATE)
)
SELECT DISTINCT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    FAR.FECHAORDE AS [FECHA DE LA ORDEN],
    CASE FAR.ORDTRANUE WHEN 1 THEN 'TRATAMIENTO NUEVO' 
                   WHEN 2 THEN 'TRATAMIENTO ANTIGUO'
                   WHEN 3 THEN 'CODIGO AZUL' END AS [TIPO DE ORDEN],
    FAR.NUMINGRES AS [NUMERO DE INGRESO],
    FAR.NUMEFOLIO AS [NUMERO DE FOLIO],
    PAC.IPCODPACI AS [ID PACIENTE],
    PAC.IPNOMCOMP AS PACIENTE,
    FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
    ING.DESCCAMAS AS CAMA,
    FARD.CODPRODUC AS [CODIGO DE PRODUCTO],
    INV.Name AS PRODUCTO,
    TIP.Name AS [TIPO DE PRODUCTO],
    GFA.Name AS [GRUPO FARMACOLOGICO],
    ISNULL(FARD.DOSISPROD,'0.00') AS DOSIS,
    UM.Name AS MEDIDA,
    FARD.FRECUENCI AS FRECUENCIA,
    CASE UNIFRECUE WHEN 1 THEN 'MINUTOS'
                   WHEN 2 THEN 'HORAS'
                   WHEN 3 THEN 'DIAS' END AS TIEMPO,
    ADM.Name AS [VIA DE ADMINISTRACION],
    DURACIDOS AS DURACION,
    FARD.CANPEDPRO AS [CANTIDAD FORMULADA],
    CASE HC.CONCILIACIONMED WHEN 'TRUE' THEN 'SI' 
                       WHEN 'FALSE' THEN 'NO' END AS [CONCILIACION MEDICAMENTOSA],
    DISD.Quantity AS [CANTIDAD DISPENSADA],
    '' AS [CANTIDAD APLICADA],
    DD.Cantidad AS [CANTIDAD DEVUELTA],
    DIS.Code AS [CODIGO DE DISPENSACION],
    DIS.ConfirmationDate AS [FECHA Y HORA DISPENSACION],
    USU.NOMUSUARI AS [USUARIO CONFIRMACION],
    DD.NOMMEDICO AS [USUARIO DE DEVOLUCION],
    DD.PROFESION AS [CARGO DE DEVOLUCION],
    DD.FECREGISTR AS [REGISTRO DE DEVOLUCIÓN],
    DD.CodigoDevolucionDispensacion AS [CODIGO DEVOLUCION DISPENSACION],
    DD.FechaDevolucion AS [FECHA Y HORA DEVOLUCION DISPENSACION],
    DD.Regente AS [USUARIO CONFIRMA DEVOLUCION],
    ENT.NOMENTIDA AS ENTIDAD,
    CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
                   WHEN 2 THEN 'Subsidiado'
                   WHEN 3 THEN 'Vinculado'
                   WHEN 4 THEN 'Particular'
                   WHEN 5 THEN 'Otro'
                   WHEN 6 THEN 'Desplazado Reg. Contributivo'
                   WHEN 7 THEN 'Desplazado Reg. Subsidiado' 
                   WHEN 8 THEN 'Desplazado No Asegurado' END AS [GRUPO DE ATENCION],
    CASE WHEN ING.FECHEGRESO IS NULL THEN 'HOSPITALIZADO' ELSE 'EGRESADO' END AS ESTADO,
    PRO.NOMMEDICO AS [PROFESIONAL QUE ORDENO],
    INV.ProductCost AS [COSTO PROMEDIO],
    CAST(FAR.FECHAORDE AS date) AS 'FECHA BUSQUEDA',
    YEAR(FAR.FECHAORDE) AS 'AÑO FECHA BUSQUEDA',
    MONTH(FAR.FECHAORDE) AS 'MES AÑO FECHA BUSQUEDA',
    CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
                             WHEN 2 THEN 'FEBRERO'
                             WHEN 3 THEN 'MARZO'
                             WHEN 4 THEN 'ABRIL'
                             WHEN 5 THEN 'MAYO'
                             WHEN 6 THEN 'JUNIO'
                             WHEN 7 THEN 'JULIO'
                             WHEN 8 THEN 'AGOSTO'
                             WHEN 9 THEN 'SEPTIEMBRE'
                             WHEN 10 THEN 'OCTUBRE'
                             WHEN 11 THEN 'NOVIEMBRE'
                             WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
    FORMAT(DAY(FAR.FECHAORDE), '00') AS 'DIA FECHA BUSQUEDA',
    CONCAT(FORMAT(MONTH(FAR.FECHAORDE), '00') ,' - ', 
    CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
                             WHEN 2 THEN 'FEBRERO'
                             WHEN 3 THEN 'MARZO'
                             WHEN 4 THEN 'ABRIL'
                             WHEN 5 THEN 'MAYO'
                             WHEN 6 THEN 'JUNIO'
                             WHEN 7 THEN 'JULIO'
                             WHEN 8 THEN 'AGOSTO'
                             WHEN 9 THEN 'SEPTIEMBRE'
                             WHEN 10 THEN 'OCTUBRE'
                             WHEN 11 THEN 'NOVIEMBRE'
                             WHEN 12 THEN 'DICIEMBRE'END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
    [INDIGO036].[dbo].[HCFARMEPC] AS FAR 
INNER JOIN CTE_DETALLE_FARMACIA AS FARD ON FAR.CODCONCEC=FARD.CODCONCEC 
INNER JOIN [INDIGO036].[dbo].[INPACIENT] AS PAC ON FAR.IPCODPACI=PAC.IPCODPACI 
INNER JOIN [INDIGO036].[dbo].[INUNIFUNC] AS FUN ON FAR.UFUCODIGO=FUN.UFUCODIGO 
INNER JOIN [INDIGO036].[Inventory].[ATC] AS ATC ON FARD.CODPRODUC=ATC.Code 
INNER JOIN [INDIGO036].[Inventory].[InventoryProduct] AS INV ON ATC.Id= INV.ATCId AND INV.Status=1 
INNER JOIN [INDIGO036].[Inventory].[ProductType] AS TIP ON INV.ProductTypeId=TIP.Id AND TIP.Name='MEDICAMENTOS'
LEFT JOIN [INDIGO036].[Inventory].[PharmacologicalGroup] AS GFA ON ATC.PharmacologicalGroupId=GFA.Id 
LEFT JOIN [INDIGO036].[Inventory].[InventoryMeasurementUnit] AS UM ON FARD.CODUNIMED=UM.Code 
LEFT JOIN [INDIGO036].[Inventory].[AdministrationRoute] AS ADM ON ATC.AdministrationRouteId=ADM.Id 
LEFT JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensingDetail] AS DISD ON FARD.ID=DISD.EntityId 
LEFT JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensing] AS DIS ON DISD.PharmaceuticalDispensingId=DIS.Id AND DIS.Status=2 
LEFT JOIN [INDIGO036].[dbo].[SEGusuaru] AS USU ON DIS.ConfirmationUser=USU.CODUSUARI 
LEFT JOIN [INDIGO036].[dbo].[INENTIDAD] AS ENT ON PAC.CODENTIDA=ENT.CODENTIDA 
LEFT JOIN CTE_INGRESO AS ING ON FAR.NUMINGRES=ING.NUMINGRES 
LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] AS PRO ON FAR.CODPROSAL=PRO.CODPROSAL 
LEFT JOIN CTE_DEVOLUCION_DISPENSACION AS DD ON DISD.Id=DD.DispensacionDetalleId 
LEFT JOIN [INDIGO036].[dbo].[HCHISPACA] AS HC ON FAR.NUMINGRES=HC.NUMINGRES AND FAR.NUMEFOLIO=HC.NUMEFOLIO
WHERE CAST(FAR.FECHAORDE AS DATE) BETWEEN CAST(GETDATE()-200 AS DATE) AND CAST(GETDATE() AS DATE)

UNION ALL
SELECT DISTINCT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    FAR.FECHA AS [FECHA DE LA ORDEN],
    FAR.ESTADO AS [TIPO DE ORDEN],
    FAR.NUMINGRES AS [NUMERO DE INGRESO],
    FAR.NUMEFOLIO AS [NUMERO DE FOLIO],
    PAC.IPCODPACI AS [ID PACIENTE],
    PAC.IPNOMCOMP AS PACIENTE,
    FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
    ING.DESCCAMAS AS CAMA,
    FAR.CODPRODUC AS [CODIGO DE PRODUCTO],
    INV.Name AS PRODUCTO,
    'MEZCLAS/LIQUIDOS' AS [TIPO DE PRODUCTO],
    GFA.Name AS [GRUPO FARMACOLOGICO],
    FAR.DOSIS,
    UM.Name AS MEDIDA,
    FAR.FRECUENCIA,
    FAR.TIEMPO,
    ADM.Name AS [VIA DE ADMINISTRACION],
    FAR.DURACION,
    FAR.CANTIDAD AS [CANTIDAD FORMULADA],
    NULL AS [CONCILIACION MEDICAMENTOSA],
    DISD.Quantity AS [CANTIDAD DISPENSADA],
    '' AS [CANTIDAD APLICADA],
    DD.Cantidad AS [CANTIDAD DEVUELTA],
    DIS.Code AS [CODIGO DE DISPENSACION],
    DIS.ConfirmationDate AS [FECHA Y HORA DISPENSACION],
    USU.NOMUSUARI AS [USUARIO CONFIRMACION],
    DD.NOMMEDICO AS [USUARIO DE DEVOLUCION],
    DD.PROFESION AS [CARGO DE DEVOLUCION],
    DD.FECREGISTR AS [REGISTRO DE DEVOLUCIÓN],
    DD.CodigoDevolucionDispensacion AS [CODIGO DEVOLUCION DISPENSACION],
    DD.FechaDevolucion AS [FECHA Y HORA DEVOLUCION DISPENSACION],
    DD.Regente AS [USUARIO CONFIRMA DEVOLUCION],
    ENT.NOMENTIDA AS ENTIDAD,
    CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
                   WHEN 2 THEN 'Subsidiado'
                   WHEN 3 THEN 'Vinculado'
                   WHEN 4 THEN 'Particular'
                   WHEN 5 THEN 'Otro'
                   WHEN 6 THEN 'Desplazado Reg. Contributivo'
                   WHEN 7 THEN 'Desplazado Reg. Subsidiado' 
                   WHEN 8 THEN 'Desplazado No Asegurado' END AS [GRUPO DE ATENCION],
    CASE WHEN ING.FECHEGRESO IS NULL THEN 'HOSPITALIZADO' ELSE 'EGRESADO' END AS ESTADO,
    PRO.NOMMEDICO AS [PROFESIONAL QUE ORDENO],
    INV.ProductCost AS [COSTO PROMEDIO],
    CAST(FAR.FECHA AS date) AS 'FECHA BUSQUEDA',
    YEAR(FAR.FECHA) AS 'AÑO FECHA BUSQUEDA',
    MONTH(FAR.FECHA) AS 'MES AÑO FECHA BUSQUEDA',
    CASE MONTH(FAR.FECHA) WHEN 1 THEN 'ENERO'
                             WHEN 2 THEN 'FEBRERO'
                             WHEN 3 THEN 'MARZO'
                             WHEN 4 THEN 'ABRIL'
                             WHEN 5 THEN 'MAYO'
                             WHEN 6 THEN 'JUNIO'
                             WHEN 7 THEN 'JULIO'
                             WHEN 8 THEN 'AGOSTO'
                             WHEN 9 THEN 'SEPTIEMBRE'
                             WHEN 10 THEN 'OCTUBRE'
                             WHEN 11 THEN 'NOVIEMBRE'
                             WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
    FORMAT(DAY(FAR.FECHA), '00') AS 'DIA FECHA BUSQUEDA',
    CONCAT(FORMAT(MONTH(FAR.FECHA), '00') ,' - ', 
    CASE MONTH(FAR.FECHA) WHEN 1 THEN 'ENERO'
                             WHEN 2 THEN 'FEBRERO'
                             WHEN 3 THEN 'MARZO'
                             WHEN 4 THEN 'ABRIL'
                             WHEN 5 THEN 'MAYO'
                             WHEN 6 THEN 'JUNIO'
                             WHEN 7 THEN 'JULIO'
                             WHEN 8 THEN 'AGOSTO'
                             WHEN 9 THEN 'SEPTIEMBRE'
                             WHEN 10 THEN 'OCTUBRE'
                             WHEN 11 THEN 'NOVIEMBRE'
                             WHEN 12 THEN 'DICIEMBRE'END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
    CTE_LIQUIDOS AS FAR 
INNER JOIN [INDIGO036].[dbo].[INPACIENT] AS PAC ON FAR.IPCODPACI=PAC.IPCODPACI 
INNER JOIN [INDIGO036].[dbo].[INUNIFUNC] AS FUN ON FAR.UFUCODIGO=FUN.UFUCODIGO 
INNER JOIN [INDIGO036].[Inventory].[ATC] AS ATC ON FAR.CODPRODUC=ATC.Code 
INNER JOIN [INDIGO036].[Inventory].[InventoryProduct] AS INV ON ATC.Id=INV.ATCId 
INNER JOIN [INDIGO036].[Inventory].[ProductType] AS TIP ON INV.ProductTypeId=TIP.Id AND TIP.Name='MEDICAMENTOS' 
LEFT JOIN [INDIGO036].[Inventory].[PharmacologicalGroup] AS GFA ON ATC.PharmacologicalGroupId=GFA.Id 
LEFT JOIN [INDIGO036].[Inventory].[InventoryMeasurementUnit] AS UM ON FAR.MEDIDA=UM.Code 
LEFT JOIN [INDIGO036].[Inventory].[AdministrationRoute] AS ADM ON ATC.AdministrationRouteId=ADM.Id 
LEFT JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensingDetail] AS DISD ON FAR.ID=DISD.EntityId AND EntityName='HCFARMEPD' 
LEFT JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensing] AS DIS ON DISD.PharmaceuticalDispensingId=DIS.Id AND DIS.Status=2 
LEFT JOIN [INDIGO036].[dbo].[SEGusuaru] AS USU ON DIS.ConfirmationUser=USU.CODUSUARI 
LEFT JOIN [INDIGO036].[dbo].[INENTIDAD] AS ENT ON PAC.CODENTIDA=ENT.CODENTIDA 
LEFT JOIN CTE_INGRESO AS ING ON FAR.NUMINGRES=ING.NUMINGRES 
LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] AS PRO ON FAR.PROFESIONAL=PRO.CODPROSAL 
LEFT JOIN CTE_DEVOLUCION_DISPENSACION AS DD ON DISD.Id=DD.DispensacionDetalleId  

UNION ALL 
SELECT DISTINCT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    FAR.FECHAORDE AS [FECHA DE LA ORDEN],
    '' AS [TIPO DE ORDEN],
    FAR.NUMINGRES AS [NUMERO DE INGRESO],
    FAR.NUMEFOLIO AS [NUMERO DE FOLIO],
    PAC.IPCODPACI AS [ID PACIENTE],
    PAC.IPNOMCOMP AS PACIENTE,
    FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
    ING.DESCCAMAS AS CAMA,
    FARD.CODPRODUC AS [CODIGO DE PRODUCTO],
    INV.Name AS PRODUCTO,
    'SUMINISTROS' AS [TIPO DE PRODUCTO],
    '' AS [GRUPO FARMACOLOGICO],
    ISNULL(FARD.DOSISPROD,'0.00') AS DOSIS,
    '' AS MEDIDA,
    FARD.FRECUENCI AS FRECUENCIA,
    CASE UNIFRECUE WHEN 1 THEN 'MINUTOS'
                   WHEN 2 THEN 'HORAS'
                   WHEN 3 THEN 'DIAS' END AS TIEMPO,
    '' AS [VIA DE ADMINISTRACION],
    DURACIDOS AS DURACION,
    FARD.CANPEDPRO AS [CANTIDAD FORMULADA],
    NULL AS [CONCILIACION MEDICAMENTOSA],
    DISD.Quantity AS [CANTIDAD DISPENSADA],
    '' AS [CANTIDAD APLICADA],
    DD.Cantidad AS [CANTIDAD DEVUELTA],
    DIS.Code AS [CODIGO DE DISPENSACION],
    DIS.ConfirmationDate AS [FECHA Y HORA DISPENSACION],
    USU.NOMUSUARI AS [USUARIO CONFIRMACION],
    DD.NOMMEDICO AS [USUARIO DE DEVOLUCION],
    DD.PROFESION AS [CARGO DE DEVOLUCION],
    DD.FECREGISTR AS [REGISTRO DE DEVOLUCIÓN],
    DD.CodigoDevolucionDispensacion AS [CODIGO DEVOLUCION DISPENSACION],
    DD.FechaDevolucion AS [FECHA Y HORA DEVOLUCION DISPENSACION],
    DD.Regente AS [USUARIO CONFIRMA DEVOLUCION],
    ENT.NOMENTIDA AS ENTIDAD,
    CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
                   WHEN 2 THEN 'Subsidiado'
                   WHEN 3 THEN 'Vinculado'
                   WHEN 4 THEN 'Particular'
                   WHEN 5 THEN 'Otro'
                   WHEN 6 THEN 'Desplazado Reg. Contributivo'
                   WHEN 7 THEN 'Desplazado Reg. Subsidiado' 
                   WHEN 8 THEN 'Desplazado No Asegurado' END AS [GRUPO DE ATENCION],
    CASE WHEN ING.FECHEGRESO IS NULL THEN 'HOSPITALIZADO' ELSE 'EGRESADO' END AS ESTADO,
    PRO.NOMMEDICO AS [PROFESIONAL QUE ORDENO],
    INV.ProductCost AS [COSTO PROMEDIO],
    CAST(FAR.FECHAORDE AS date) AS 'FECHA BUSQUEDA',
    YEAR(FAR.FECHAORDE) AS 'AÑO FECHA BUSQUEDA',
    MONTH(FAR.FECHAORDE) AS 'MES AÑO FECHA BUSQUEDA',
    CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
                             WHEN 2 THEN 'FEBRERO'
                             WHEN 3 THEN 'MARZO'
                             WHEN 4 THEN 'ABRIL'
                             WHEN 5 THEN 'MAYO'
                             WHEN 6 THEN 'JUNIO'
                             WHEN 7 THEN 'JULIO'
                             WHEN 8 THEN 'AGOSTO'
                             WHEN 9 THEN 'SEPTIEMBRE'
                             WHEN 10 THEN 'OCTUBRE'
                             WHEN 11 THEN 'NOVIEMBRE'
                             WHEN 12 THEN 'DICIEMBRE'END AS 'MES NOMBRE FECHA BUSQUEDA',
    FORMAT(DAY(FAR.FECHAORDE), '00') AS 'DIA FECHA BUSQUEDA',
    CONCAT(FORMAT(MONTH(FAR.FECHAORDE), '00') ,' - ', 
    CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
                             WHEN 2 THEN 'FEBRERO'
                             WHEN 3 THEN 'MARZO'
                             WHEN 4 THEN 'ABRIL'
                             WHEN 5 THEN 'MAYO'
                             WHEN 6 THEN 'JUNIO'
                             WHEN 7 THEN 'JULIO'
                             WHEN 8 THEN 'AGOSTO'
                             WHEN 9 THEN 'SEPTIEMBRE'
                             WHEN 10 THEN 'OCTUBRE'
                             WHEN 11 THEN 'NOVIEMBRE'
                             WHEN 12 THEN 'DICIEMBRE'END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
    [INDIGO036].[dbo].[HCFARMEPC] AS FAR 
INNER JOIN [INDIGO036].[dbo].[HCFARMEPD] AS FARD ON FAR.CODCONCEC=FARD.CODCONCEC 
INNER JOIN [INDIGO036].[dbo].[INPACIENT] AS PAC ON FAR.IPCODPACI=PAC.IPCODPACI 
INNER JOIN [INDIGO036].[dbo].[INUNIFUNC] AS FUN ON FAR.UFUCODIGO=FUN.UFUCODIGO 
INNER JOIN [INDIGO036].[Inventory].[InventorySupplie] AS INS ON FARD.CODPRODUC=INS.Code 
INNER JOIN [INDIGO036].[Inventory].[InventoryProduct] AS INV ON INS.Id=INV.SupplieId 
LEFT JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensingDetail] AS DISD ON FARD.ID=DISD.EntityId 
LEFT JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensing] AS DIS ON DISD.PharmaceuticalDispensingId=DIS.Id AND DIS.Status=2 
LEFT JOIN [INDIGO036].[dbo].[SEGusuaru] AS USU ON DIS.ConfirmationUser=USU.CODUSUARI 
LEFT JOIN [INDIGO036].[dbo].[INENTIDAD] AS ENT ON PAC.CODENTIDA=ENT.CODENTIDA 
LEFT JOIN CTE_INGRESO AS ING ON FAR.NUMINGRES=ING.NUMINGRES 
LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] AS PRO ON FAR.CODPROSAL=PRO.CODPROSAL 
LEFT JOIN CTE_DEVOLUCION_DISPENSACION AS DD ON DISD.Id=DD.DispensacionDetalleId  
WHERE CAST(FAR.FECHAORDE AS DATE) BETWEEN CAST(GETDATE()-200 AS DATE) AND CAST(GETDATE() AS DATE)