-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_VIEWQXRADICACION
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_VIEWQXRADICACION AS

WITH CTE_ORDENES AS (
    SELECT
        ROW_NUMBER() OVER(
            PARTITION BY CODSERIPS
            ORDER BY
                IPCODPACI,
                FECORDMED DESC
        ) AS 'NUMERO',
        IPCODPACI,
        FECORDMED,
        CODSERIPS
    FROM
        INDIGO036.dbo.HCORDPROQ
),
CTE_INFORME AS (
    SELECT
        INF.IPCODPACI,
        INF.NUMINGRES,
        INF.CODSERIPS,
        FECHORINI
    FROM
        INDIGO036.dbo.HCQXINFOR INF
),
CTE_ORDEN_MEDICA_RADICACION AS (
    SELECT
        RADQXD.IDRADICACIONQX,
        CAST(RADQXD.CAMPOFECHA AS DATE) AS CAMPOFECHA
    FROM
        INDIGO036.dbo.ADRADICACIONQXD RADQXD
        INNER JOIN INDIGO036.dbo.HCLISTACD TACD ON RADQXD.IDLISTACHEQUEOD = TACD.CODCONSEC
            AND TACD.DESPREENC = 'ORDEN MEDICA'
    WHERE
        RADQXD.CAMPOFECHA IS NOT NULL
),
CTE_RADICACIONES AS (
    SELECT
        RAD.ID,
        INP.IPCODPACI AS 'ID. PACIENTE',
        INP.IPNOMCOMP AS 'NOMBRE PACIENTE',
        INP.IPTELMOVI AS 'TEL.MOVIL',
        INP.IPTELEFON AS 'TEL.FIJO',
        INP.CORELEPAC AS 'CORREO ELECTRONICO',
        FLOOR(
            (
                CAST(
                    CONVERT(VARCHAR(8), RAD.FECHAREGISTRO, 112) AS INT
                ) - CAST(CONVERT(VARCHAR(8), INP.IPFECNACI, 112) AS INT)
            ) / 10000
        ) AS 'EDAD AÑOS',
        DATEDIFF(
            MONTH,
            CAST(INP.IPFECNACI AS varchar),
            CAST(RAD.FECHAREGISTRO AS DATE)
        ) AS 'EDAD MESES',
        RAD.FECHACONFIRMACION,
        CASE
            RAD.ESTADO
            WHEN 1 THEN 'Radicado'
            WHEN 2 THEN 'Confirmado'
            WHEN 3 THEN 'Anulado'
        END AS 'ESTADO RADICACION',
        CAST(RAD.FECHARADIC AS DATE) AS 'FECHA RADICADO',
        RAD.NUMRADICACION AS '# RADICADO',
        RAD.QXPRINCIPAL AS 'CUPS PRINCIPAL',
        CUPS1.DESCODCUPS AS 'CX PRINCIPAL',
        RADD.CODSERIPS AS 'CUPS OTROS',
        CUPS2.DESCODCUPS AS 'OTROS PROC',
        RAD.CODPROSAL AS 'COD. PROFESIONAL',
        PROF.NOMMEDICO AS 'NOMBRE PROFESIONAL',
        ESP.DESESPECI AS 'ESPECIALIDAD',
        RES.CAMPOFECHA
    FROM
        INDIGO036.dbo.ADRADICACIONQX RAD
        INNER JOIN INDIGO036.dbo.INPACIENT INP ON INP.IPCODPACI = RAD.IPCODPACI
        LEFT JOIN INDIGO036.dbo.ADRADICACIONQXS RADD ON RAD.ID = RADD.IDRADICACIONQX
        LEFT JOIN INDIGO036.dbo.INCUPSIPS CUPS2 ON CUPS2.CODSERIPS = RADD.CODSERIPS
        LEFT JOIN INDIGO036.dbo.INCUPSIPS CUPS1 ON CUPS1.CODSERIPS = RAD.QXPRINCIPAL
        LEFT JOIN INDIGO036.dbo.INPROFSAL PROF ON PROF.CODPROSAL = RAD.CODPROSAL
        LEFT JOIN INDIGO036.dbo.INESPECIA ESP ON ESP.CODESPECI = RAD.CODESPECI
        LEFT JOIN CTE_ORDEN_MEDICA_RADICACION RES ON RAD.ID = RES.IDRADICACIONQX
    GROUP BY
        RAD.ID,
        INP.IPCODPACI,
        INP.IPNOMCOMP,
        RAD.FECHACONFIRMACION,
        INP.IPFECNACI,
        RAD.ESTADO,
        RAD.NUMRADICACION,
        RAD.QXPRINCIPAL,
        CUPS1.DESCODCUPS,
        RADD.CODSERIPS,
        CUPS2.DESCODCUPS,
        RAD.CODPROSAL,
        PROF.NOMMEDICO,
        ESP.DESESPECI,
        RAD.FECHAREGISTRO,
        RAD.FECHARADIC,
        INP.IPTELMOVI,
        INP.IPTELEFON,
        INP.CORELEPAC,
        RES.CAMPOFECHA
),
CTE_LISTA_CHEQUEO AS (
    SELECT
        DISTINCT FEC.FECHAREGISTRO,
        DET.IDRADICACIONQX,
        DET.IDLISTACHEQUEOD,
        DET.CAMPOFECHA,
        CASE
            WHEN LIS1.DESPREENC IS NOT NULL
                AND LIS1.DESPREENC = 'ORDEN MEDICA' THEN 'SI'
            ELSE 'NO'
        END AS 'ORDEN MEDICA',
        CASE
            WHEN LIS2.DESPREENC IS NOT NULL
                AND LIS2.DESPREENC = 'ORDEN DE INSUMOS' THEN 'SI'
            ELSE 'NO'
        END AS 'ORDEN DE INSUMOS',
        CASE
            WHEN LIS3.DESPREENC IS NOT NULL
                AND LIS3.DESPREENC = 'CONSENTIMIENTO INFORMADO' THEN 'SI'
            ELSE 'NO'
        END AS 'CONSENTIMIENTO INFORMADO',
        CASE
            WHEN LIS4.DESPREENC IS NOT NULL
                AND LIS4.DESPREENC = 'AUTORIZACION' THEN 'SI'
            ELSE 'NO'
        END AS 'AUTORIZACION',
        CASE
            WHEN LIS5.DESPREENC IS NOT NULL
                AND LIS5.DESPREENC = 'COPAGO' THEN 'SI'
            ELSE 'NO'
        END AS 'COPAGO',
        CASE
            WHEN LIS6.DESPREENC IS NOT NULL
                AND LIS6.DESPREENC = 'FECHA VIGENCIA AUTORIZACION' THEN 'SI'
            ELSE 'NO'
        END AS 'VIGENCIA AUTORIZACION'
    FROM
        INDIGO036.dbo.ADRADICACIONQX FEC
        INNER JOIN INDIGO036.dbo.ADRADICACIONQXD DET ON FEC.ID = DET.IDRADICACIONQX
        LEFT JOIN INDIGO036.dbo.HCLISTACD LIS1 ON LIS1.CODCONSEC = DET.IDLISTACHEQUEOD
            AND LIS1.DESPREENC IS NOT NULL
        LEFT JOIN INDIGO036.dbo.HCLISTACD LIS2 ON LIS2.CODCONSEC = DET.IDLISTACHEQUEOD
            AND LIS2.DESPREENC IS NOT NULL
        LEFT JOIN INDIGO036.dbo.HCLISTACD LIS3 ON LIS3.CODCONSEC = DET.IDLISTACHEQUEOD
            AND LIS3.DESPREENC IS NOT NULL
        LEFT JOIN INDIGO036.dbo.HCLISTACD LIS4 ON LIS4.CODCONSEC = DET.IDLISTACHEQUEOD
            AND LIS4.DESPREENC IS NOT NULL
        LEFT JOIN INDIGO036.dbo.HCLISTACD LIS5 ON LIS5.CODCONSEC = DET.IDLISTACHEQUEOD
            AND LIS5.DESPREENC IS NOT NULL
        LEFT JOIN INDIGO036.dbo.HCLISTACD LIS6 ON LIS6.CODCONSEC = DET.IDLISTACHEQUEOD
            AND LIS6.DESPREENC IS NOT NULL
    GROUP BY
        DET.CAMPOFECHA,
        FEC.FECHAREGISTRO,
        DET.IDRADICACIONQX,
        LIS1.DESPREENC,
        LIS2.DESPREENC,
        LIS3.DESPREENC,
        LIS4.DESPREENC,
        LIS5.DESPREENC,
        LIS6.DESPREENC,
        DET.IDLISTACHEQUEOD
)
SELECT
    DISTINCT ISNULL(RAD.[FECHA RADICADO], GETDATE()) AS 'FECHA DE BUSQUEDA',
    RAD.[ID. PACIENTE],
    RAD.[NOMBRE PACIENTE],
    RAD.[EDAD AÑOS],
    RAD.[EDAD MESES],
    RAD.[TEL.MOVIL],
    RAD.[TEL.FIJO],
    RAD.[CORREO ELECTRONICO],
    CAST(ISNULL(RAD.CAMPOFECHA, ORD.FECORDMED) AS DATE) AS 'FECHA ORDEN',
    RAD.[ESTADO RADICACION],
    RAD.[# RADICADO],
    RAD.[FECHA RADICADO],
    CAST(RAD.FECHACONFIRMACION AS DATE) AS 'FECHA CONFIRMACION',
    RAD.[CX PRINCIPAL],
    RAD.[CUPS PRINCIPAL],
    RAD.[OTROS PROC],
    RAD.[CUPS OTROS],
    RAD.[NOMBRE PROFESIONAL],
    RAD.ESPECIALIDAD,
    CASE
        WHEN LIS1.[ORDEN MEDICA] = 'SI' THEN 'SI'
        ELSE 'NO'
    END AS 'ORDEN MEDICA',
    CASE
        WHEN LIS2.[ORDEN DE INSUMOS] = 'SI' THEN 'SI'
        ELSE 'NO'
    END AS 'ORDEN DE INSUMOS',
    CASE
        WHEN LIS3.[CONSENTIMIENTO INFORMADO] = 'SI' THEN 'SI'
        ELSE 'NO'
    END AS 'CONSENTIMIENTO INFORMADO',
    CASE
        WHEN LIS4.AUTORIZACION = 'SI' THEN 'SI'
        ELSE 'NO'
    END AS 'AUTORIZACION',
    CASE
        WHEN LIS5.COPAGO = 'SI' THEN 'SI'
        ELSE 'NO'
    END AS 'COPAGO',
    CASE
        WHEN LIS6.[VIGENCIA AUTORIZACION] = 'SI' THEN 'SI'
        ELSE 'NO'
    END AS 'FECHA VIGENCIA AUTORIZACION',
    LIS6.CAMPOFECHA AS 'FECHA VIGENCIA'
FROM
    CTE_RADICACIONES RAD
    LEFT JOIN CTE_LISTA_CHEQUEO LIS1 ON LIS1.IDRADICACIONQX = RAD.ID
        AND LIS1.[ORDEN MEDICA] = 'SI'
    LEFT JOIN CTE_LISTA_CHEQUEO LIS2 ON LIS2.IDRADICACIONQX = RAD.ID
        AND LIS2.[ORDEN DE INSUMOS] = 'SI'
    LEFT JOIN CTE_LISTA_CHEQUEO LIS3 ON LIS3.IDRADICACIONQX = RAD.ID
        AND LIS3.[CONSENTIMIENTO INFORMADO] = 'SI'
    LEFT JOIN CTE_LISTA_CHEQUEO LIS4 ON LIS4.IDRADICACIONQX = RAD.ID
        AND LIS4.AUTORIZACION = 'SI'
    LEFT JOIN CTE_LISTA_CHEQUEO LIS5 ON LIS5.IDRADICACIONQX = RAD.ID
        AND LIS5.COPAGO = 'SI'
    LEFT JOIN CTE_LISTA_CHEQUEO LIS6 ON LIS6.IDRADICACIONQX = RAD.ID
        AND LIS6.[VIGENCIA AUTORIZACION] = 'SI'
    LEFT JOIN CTE_ORDENES ORD ON ORD.IPCODPACI = RAD.[ID. PACIENTE]
        AND ORD.FECORDMED < RAD.[FECHA RADICADO]
    LEFT JOIN CTE_INFORME INF ON INF.IPCODPACI = RAD.[ID. PACIENTE]
        AND INF.CODSERIPS = RAD.[CUPS PRINCIPAL]
        AND INF.FECHORINI > RAD.FECHACONFIRMACION
