-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_VIEWESTRUCTURAPROCEDIMIENTOSQX
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE View Report.VW_VIEWESTRUCTURAPROCEDIMIENTOSQX as
WITH CTE_INFORME_QX AS (
    SELECT
        CODCENATE,
        IPCODPACI,
        NUMEFOLIO,
        UFUCODIGO,
        CODDIAPRE,
        CODDIAPOS,
        CODPROSAL,
        CODSERIPS,
        TIPOANEST,
        FECHORINI,
        FECHORFIN,
        SALACIRUG,
        CLASIFASA,
        URGECIRUG,
        TIPOINFORME,
        NUMINGRES
    FROM
        INDIGO036.dbo.HCQXINFOR
),
CTE_ANESTESIA AS (
    SELECT
        ROW_NUMBER() OVER(
            PARTITION BY ANES.IPCODPACI
            ORDER BY
                ANES.NUMEFOLIO DESC
        ) NUMERO,
        ANES.IPCODPACI,
        ANES.UFUCODIGO,
        ANES.NUMINGRES,
        ANES.DIAGNPREO,
        ANES.DIAGNPOSO,
        ANES.HORINICIRU,
        ANES.HORFINCIRU,
        ANES.HORINIANES,
        ANES.HORFINANES,
        ANES.DURACIRUG,
        ANES.DURAANEST,
        ANES.CODPROSAL AS ANESTESIOLOGO,
        ANES.FECHAREGISTRO,
        ANES.IDHCHISPACA,
        ANES.TIPOREGISTRO,
        ANES.NUMEFOLIO
    FROM
        INDIGO036.dbo.HCREGANES ANES
),
CTE_RADICACIONES AS (
    SELECT
        ID,
        IPCODPACI,
        NUMRADICACION,
        ESTADO,
        FECHACONFIRMACION,
        QXPRINCIPAL,
        CODESPECI
    FROM
        INDIGO036.dbo.ADRADICACIONQX
    WHERE
        ESTADO = 2
),
CTE_ORDEN_MEDICA AS (
    SELECT
        IPCODPACI,
        NUMEFOLIO,
        NUMINGRES,
        UFUCODIGO,
        CODPROSAL,
        CODSERIPS,
        ESTSERIPS,
        FECORDMED,
        PRISERIPS
    FROM
        INDIGO036.dbo.HCORDPROQ
)
SELECT
    DISTINCT CEN.NOMCENATE AS 'CENTRO DE ATENCION',
    INF.UFUCODIGO AS 'COD. UF',
    FUN.UFUDESCRI AS 'UNIDAD FUNCIONAL',
    ESP.CODESPECI AS 'ESPECIALIDAD',
    ESP.DESESPECI AS 'DESCRIPCION ESPECIALIDAD',
    CASE
        PAC.IPTIPODOC
        WHEN '1' THEN 'CC'
        WHEN '2' THEN 'CE'
        WHEN '3' THEN 'TI'
        WHEN '4' THEN 'RC'
        WHEN '5' THEN 'PA'
        WHEN '6' THEN 'AS'
        WHEN '7' THEN 'MS'
        WHEN '8' THEN 'NU'
        WHEN '9' THEN 'CN'
        WHEN '10' THEN 'CD'
        WHEN '11' THEN 'SC'
        WHEN '12' THEN 'PE'
        WHEN '13' THEN 'PT'
        WHEN '14' THEN 'DE'
        WHEN '15' THEN 'SI'
        ELSE 'N/A'
    END AS 'TIPO DOCUMENTO',
    INF.IPCODPACI,
    RTRIM(PAC.IPPRINOMB) AS 'PRIMER NOMBRE',
    RTRIM(PAC.IPSEGNOMB) AS 'SEGUNDO NOMBRE',
    RTRIM(PAC.IPPRIAPEL) AS 'PRIMER APELLIDO',
    RTRIM(PAC.IPSEGAPEL) AS 'SEGUNDO APELLIDO',
    RTRIM(PAC.IPNOMCOMP) AS 'NOMBRE COMPLETO PACIENTE',
    PAC.IPFECNACI AS 'FECHA NACIMIENTO',
    FLOOR(
        (
            CAST(CONVERT(VARCHAR(8), INF.FECHORINI, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)
        ) / 10000
    ) AS 'EDAD',
    CASE
        WHEN PAC.IPSEXOPAC = '1' THEN 'M'
        ELSE 'F'
    END AS 'GENERO',
    INF.SALACIRUG AS 'SALA',
    RAD.FECHACONFIRMACION AS 'FECHA RADICACION',
    ORD.FECORDMED AS 'FECHA ORDEN (HOSPITALARIO)',
    YEAR(INF.FECHORFIN) AS 'AÑO CIRUGIA',
    CASE
        MONTH(INF.FECHORFIN)
        WHEN 1 THEN 'Enero'
        WHEN 2 THEN 'Febrero'
        WHEN 3 THEN 'Marzo'
        WHEN 4 THEN 'Abril'
        WHEN 5 THEN 'Mayo'
        WHEN 6 THEN 'Junio'
        WHEN 7 THEN 'Julio'
        WHEN 8 THEN 'Agosto'
        WHEN 9 THEN 'Septiembre'
        WHEN 10 THEN 'Octubre'
        WHEN 11 THEN 'Noviembre'
        WHEN 12 THEN 'Diciembre'
    END AS 'MES CIRUGIA',
    DAY(INF.FECHORFIN) AS 'DIA CIRUGIA',
    INF.NUMEFOLIO AS 'FOLIO INF. QX',
    INF.FECHORINI AS 'INICIO CX',
    INF.FECHORFIN AS 'FIN CX',
    DATEDIFF(MINUTE, INF.FECHORINI, INF.FECHORFIN) AS 'DURACION CX (MINUTOS)',
    ANES.HORINIANES AS 'INICIA ANESTESIA',
    ANES.HORFINANES AS 'FIN ANESTESIA',
    DATEDIFF(MINUTE, ANES.HORINIANES, ANES.HORFINANES) AS 'DURACION ANESTESIA (MINUTOS)',
    INF.CODDIAPRE AS 'DX PREOPERATORIO',
    INF.CODDIAPOS AS 'DX. POSTOPERATORIO',
    '' AS 'OPORTUNIDAD DIAS',
    INF.CLASIFASA AS 'ASA',
    INF.CODSERIPS AS 'COD. CUPS',
    CUPS.DESCODCUPS AS 'NOMBRE SERVICIO',
    CASE
        INF.TIPOANEST
        WHEN 1 THEN 'Local'
        WHEN 2 THEN 'Regional'
        WHEN 3 THEN 'General'
        WHEN 4 THEN 'Combinada'
        WHEN 5 THEN 'No Aplica'
    END AS 'TIPO ANESTESIA',
    CASE
        WHEN INF.URGECIRUG = 0 THEN 'NO'
        ELSE 'SI'
    END AS 'CIRUGIA DE URGENCIA',
    INF.CODPROSAL AS 'COD. CIRUJANO',
    PRO1.NOMMEDICO AS 'CIRUJANO',
    CASE
        INF.TIPOINFORME
        WHEN 1 THEN 'Informe Qx'
        ELSE 'Informe No Qx'
    END AS 'TIPO INFORME',
    INF.NUMINGRES AS '# INGRESO',
    ANES.ANESTESIOLOGO AS 'COD. ANESTESIOLOGO',
    PRO2.NOMMEDICO AS 'ANESTESIOLOGO',
    REA1.CODSERIPS AS 'PROC.PRINCIPAL',
    REA2.CODSERIPS AS 'PROC. SECUNDARIO',
    CG.Code AS 'COD. GRUPO ATENCION',
    CG.Name AS 'GRUPO ATENCION',
    HA.HealthEntityCode AS 'CODIGO ENTIDAD',
    HA.Name AS 'ENTIDAD',
    CASE
        WHEN rtrim(convert(char(5), INF.FECHORINI, 108)) BETWEEN '07:00'
        AND '13:00' THEN 'Mañana'
        WHEN rtrim(convert(char(5), INF.FECHORINI, 108)) BETWEEN '13:00'
        AND '18:00' THEN 'Tarde'
        ELSE 'Noche'
    END AS 'JORNADA',
    CASE
        CX.ORIGENQX
        WHEN 1 THEN 'Ambulatorio'
        ELSE 'Hospitalario'
    END AS 'AMBITO',
    CASE
        HIS.INDICAPAC
        WHEN 11 THEN 'Fallecido'
        ELSE 'Vivo'
    END AS 'ESTADO PACIENTE AL EGRESO',
    CAST(INF.FECHORFIN AS DATE) AS 'FECHA BUSQUEDA',
    YEAR(INF.FECHORFIN) AS 'AÑO',
    MONTH(INF.FECHORFIN) AS 'MES',
    DAY(INF.FECHORFIN) AS 'DIA'
FROM
    CTE_INFORME_QX INF
    INNER JOIN INDIGO036.dbo.HCHISPACA HIS ON HIS.NUMINGRES = INF.NUMINGRES
        AND INF.NUMEFOLIO = HIS.NUMEFOLIO
    LEFT JOIN INDIGO036.dbo.HCQXREALI REA1 ON REA1.CODSERIPS = INF.CODSERIPS
        AND INF.IPCODPACI = REA1.IPCODPACI
        AND INF.NUMINGRES = REA1.NUMINGRES
        AND REA1.QXPRINCIP = 1
    LEFT JOIN INDIGO036.dbo.HCQXREALI REA2 ON REA2.CODSERIPS = INF.CODSERIPS
        AND INF.IPCODPACI = REA2.IPCODPACI
        AND INF.NUMINGRES = REA2.NUMINGRES
        AND REA2.QXPRINCIP NOT IN (1)
    LEFT JOIN INDIGO036.dbo.AGEPROGQX PROG ON PROG.IPCODPACI = REA1.IPCODPACI
        AND PROG.CODSERIPS = INF.CODSERIPS
    LEFT JOIN CTE_ANESTESIA ANES ON ANES.IPCODPACI = INF.IPCODPACI
        AND INF.NUMINGRES = ANES.NUMINGRES
        AND NUMERO = 1
    LEFT JOIN CTE_RADICACIONES RAD ON PROG.IDRADICACIONQX = RAD.ID
    LEFT JOIN CTE_ORDEN_MEDICA ORD ON ORD.IPCODPACI = INF.IPCODPACI
        AND REA1.CODSERIPS = ORD.CODSERIPS
        AND ORD.NUMINGRES = INF.NUMINGRES
    LEFT JOIN INDIGO036.dbo.INCUPSIPS CUPS ON CUPS.CODSERIPS = INF.CODSERIPS
    LEFT JOIN INDIGO036.dbo.ADCENATEN CEN ON CEN.CODCENATE = INF.CODCENATE
    LEFT JOIN INDIGO036.dbo.INPACIENT PAC ON PAC.IPCODPACI = INF.IPCODPACI
    LEFT JOIN INDIGO036.dbo.INPROFSAL PRO1 ON PRO1.CODPROSAL = INF.CODPROSAL
    LEFT JOIN INDIGO036.dbo.INPROFSAL PRO2 ON PRO2.CODPROSAL = ANES.ANESTESIOLOGO
    LEFT JOIN INDIGO036.Contract.HealthAdministrator HA ON HA.Id = PAC.GENCONENTITY
    LEFT JOIN INDIGO036.Contract.CareGroup CG ON CG.Id = PAC.GENCAREGROUP
    LEFT JOIN INDIGO036.dbo.AGEPROGQX CX ON CX.IPCODPACI = INF.IPCODPACI
        AND CX.CODSERIPS = INF.CODSERIPS
        AND CX.NUMINGRES = INF.NUMINGRES
    LEFT JOIN INDIGO036.dbo.INUNIFUNC FUN ON FUN.UFUCODIGO = INF.UFUCODIGO
    INNER JOIN INDIGO036.dbo.INESPECIA ESP ON ESP.CODESPECI = RAD.CODESPECI