-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_VIEWINVENTARIOPRESCRIPCIONES
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW Report.VW_VIEWINVENTARIOPRESCRIPCIONES AS

WITH CTE_INGRESO AS (
    SELECT
        ING.NUMINGRES,
        ING.FECHEGRESO,
        CAM.DESCCAMAS,
        UNF.UFUDESCRI
    FROM
        [INDIGO036].[dbo].[ADINGRESO] ING
        INNER JOIN [INDIGO036].[dbo].[CHCAMASHO] CAM ON ING.CODCAMACT = CAM.CODICAMAS
        INNER JOIN [INDIGO036].[dbo].[INUNIFUNC] UNF ON CAM.UFUCODIGO = UNF.UFUCODIGO
    WHERE
        ING.FECHEGRESO IS NULL
),
CTE_FISICO AS (
    SELECT
        CONVERT(BIGINT, FIS.PESOPACIE) / 1000 AS PESO,
        ING.NUMINGRES AS INGRESO
    FROM
        CTE_INGRESO ING
        INNER JOIN [INDIGO036].[dbo].[HCEXFISIC] FIS ON ING.NUMINGRES = FIS.NUMINGRES
        AND FIS.NUMEFOLIO = (
            SELECT
                MAX(FI.NUMEFOLIO)
            FROM
                [INDIGO036].[dbo].[HCEXFISIC] FI
            WHERE
                FIS.NUMINGRES = FI.NUMINGRES
                AND FI.PESOPACIE IS NOT NULL
        )
),
CTE_DETALLE_FARMACIA AS (
    SELECT
        D.CODCONCEC,
        A.NUMINGRES,
        A.CODPRODUC,
        D.CODUNIMED,
        D.ID,
        ISNULL(A.DOSISPROD, D.DOSISPROD) AS DOSISPROD,
        A.FRECUENCI,
        A.UNIFRECUE,
        A.DURACIDOS,
        D.CANPEDPRO
    FROM
        [INDIGO036].[dbo].[HCFARMEPC] C
        INNER JOIN [INDIGO036].[dbo].[HCFARMEPD] D ON C.CODCONCEC = D.CODCONCEC
        INNER JOIN [INDIGO036].[dbo].[HCPRESCRA] A ON A.NUMINGRES = D.NUMINGRES
            AND A.CODPRODUC = D.CODPRODUC
            AND (
                C.FECHAORDE >= A.FECINIDOS
                AND C.FECHAORDE <= A.FECFINDOS
            )
        INNER JOIN CTE_INGRESO ING ON A.NUMINGRES = ING.NUMINGRES
    UNION ALL
    SELECT
        D.CODCONCEC,
        A.NUMINGRES,
        A.CODPRODUC,
        D.CODUNIMED,
        D.ID,
        ISNULL(A.DOSISPROD, D.DOSISPROD) AS DOSISPROD,
        A.FRECUENCI,
        A.UNIFRECUE,
        A.DURACIDOS,
        D.CANPEDPRO
    FROM
        [INDIGO036].[dbo].[HCFARMEPC] C
        INNER JOIN [INDIGO036].[dbo].[HCFARMEPD] D ON C.CODCONCEC = D.CODCONCEC
        INNER JOIN [INDIGO036].[dbo].[HCPRESCRA] A ON A.NUMINGRES = D.NUMINGRES
            AND A.CODPRODUC = D.CODPRODUC
            AND C.FECHAORDE >= A.FECINIDOS
            AND A.PREESTADO NOT IN (2, 4, 5, 6, 7)
        INNER JOIN CTE_INGRESO ING ON A.NUMINGRES = ING.NUMINGRES
),
CTE_LIQUIDOS AS (
    SELECT
        FAR.ID,
        ISNULL(FAR.FECINIDOS, A.FECHAINIC) AS FECHA,
        CASE
            A.PREESTADO
            WHEN 1 THEN 'TRATAMIENTO NUEVO'
            ELSE 'TRATAMIENTO ANTIGUO'
        END AS ESTADO,
        A.NUMINGRES,
        A.UFUCODIGO,
        A.NUMEFOLIO,
        A.IPCODPACI,
        FAR.CODPRODUC,
        FAR.DOSISPROD AS DOSIS,
        CASE
            WHEN D.UNIMEDBOL IS NOT NULL THEN D.UNIMEDBOL
            WHEN D.UNIMEDINF IS NOT NULL THEN D.UNIMEDINF
            WHEN D.UNIMEDDIL IS NOT NULL THEN D.UNIMEDDIL
        END AS MEDIDA,
        FAR.FRECUENCI AS FRECUENCIA,
        CASE
            FAR.UNIFRECUE
            WHEN 1 THEN 'MINUTOS'
            WHEN 2 THEN 'HORAS'
            WHEN 3 THEN 'DIAS'
        END AS TIEMPO,
        'INTRAVENOSA' AS ADMINISTRACION,
        ISNULL(D.DURACIINF, 'Dosis Unica') AS DURACION,
        CASE
            D.DURACIINF
            WHEN 'Tratamiento Continuo' THEN DATEDIFF(DAY, A.FECHAINIC, GETDATE())
        END AS TRATAMIENTO,
        D.CANPROCAL AS CANTIDAD,
        A.CODPROSAL AS PROFESIONAL
    FROM
        [INDIGO036].[dbo].[HCFARMEPD] FAR
        INNER JOIN [INDIGO036].[dbo].[HCINFLIQA] A ON FAR.IdSourceTable = A.CONSECUTI
            AND FAR.SourceTable = 'HCINFLIQA'
        INNER JOIN [INDIGO036].[dbo].[HCINFLIQD] D ON A.CODCONCEC = D.CODCONCEC
        INNER JOIN [INDIGO036].[dbo].[ADINGRESO] ING ON FAR.NUMINGRES = ING.NUMINGRES
)
SELECT
    TOP 1000 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    FAR.FECHAORDE AS [FECHA DE LA ORDEN],
    CASE
        FAR.ORDTRANUE
        WHEN 1 THEN 'TRATAMIENTO NUEVO'
        WHEN 2 THEN 'TRATAMIENTO ANTIGUO'
        WHEN 3 THEN 'CODIGO AZUL'
        ELSE 'NA'
    END AS [TIPO DE ORDEN],
    FAR.NUMINGRES AS [NUMERO DE INGRESO],
    FAR.NUMEFOLIO AS [FOLIO],
    PAC.IPCODPACI AS [ID PACIENTE],
    PAC.IPNOMCOMP AS PACIENTE,
    CAST(PAC.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
    FIS.PESO AS [PESO (KG)],
    ING.DESCCAMAS AS [CAMA ACTUAL],
    ING.UFUDESCRI AS [UNIDAD FUNCIONAL],
    FARD.CODPRODUC AS [CODIGO DE PRODUCTO],
    INV.Name AS PRODUCTO,
    TIP.Name AS [TIPO DE PRODUCTO],
    GFA.Name AS [GRUPO FARMACOLOGICO],
    CASE
        INV.POSProduct
        WHEN 1 THEN 'SI'
        ELSE 'NO'
    END AS PBS,
    CASE
        ATC.Antibiotic
        WHEN 1 THEN 'SI'
        ELSE 'NO'
    END AS ANTIBIOTICO,
    CASE
        INV.ProductControl
        WHEN 1 THEN 'SI'
        ELSE 'NO'
    END AS CONTROL,
    INV.Presentation AS PRESENTACION,
    ISNULL(FARD.DOSISPROD, '0.00') AS DOSIS,
    UM.Name AS MEDIDA,
    FARD.FRECUENCI AS FRECUENCIA,
    CASE
        UNIFRECUE
        WHEN 1 THEN 'MINUTOS'
        WHEN 2 THEN 'HORAS'
        WHEN 3 THEN 'DIAS'
    END AS TIEMPO,
    ADM.Name AS [VIA DE ADMINISTRACION],
    FARD.DURACIDOS AS DURACION,
    CASE
        FARD.DURACIDOS
        WHEN 'Tratamiento Continuo' THEN DATEDIFF(DAY, FAR.FECHAORDE, GETDATE())
    END AS [DIA DE TRATAMIENTO],
    FARD.CANPEDPRO AS [CANTIDAD FORMULADA],
    CASE
        [INDIGO036].[dbo].[HCHISPACA].CONCILIACIONMED
        WHEN 'TRUE' THEN 'SI'
        WHEN 'FALSE' THEN 'NO'
    END AS [CONCILIACION MEDICAMENTOSA],
    DISD.Quantity AS [CANTIDAD DISPENSADA],
    '' AS [CANTIDAD APLICADA],
    DIS.Code AS [CODIGO DE DISPENSACION],
    DIS.ConfirmationDate AS [FECHA Y HORA DISPENSACION],
    USU.NOMUSUARI AS [USUARIO CONFIRMACION],
    ENT.NOMENTIDA AS ENTIDAD,
    CASE
        PAC.IPTIPOPAC
        WHEN 1 THEN 'Contributivo'
        WHEN 2 THEN 'Subsidiado'
        WHEN 3 THEN 'Vinculado'
        WHEN 4 THEN 'Particular'
        WHEN 5 THEN 'Otro'
        WHEN 6 THEN 'Desplazado Reg. Contributivo'
        WHEN 7 THEN 'Desplazado Reg. Subsidiado'
        WHEN 8 THEN 'Desplazado No Asegurado'
    END AS [GRUPO DE ATENCION],
    CASE
        WHEN ING.FECHEGRESO IS NULL THEN 'HOSPITALIZADO'
        ELSE 'EGRESADO'
    END AS ESTADO,
    PRO.NOMMEDICO AS [PROFESIONAL QUE ORDENO],
    INV.ProductCost AS [COSTO PROMEDIO],
    CAST(FAR.FECHAORDE AS date) AS 'FECHA BUSQUEDA',
    YEAR(FAR.FECHAORDE) AS 'AÑO FECHA BUSQUEDA',
    MONTH(FAR.FECHAORDE) AS 'MES AÑO FECHA BUSQUEDA',
    CASE
        MONTH(FAR.FECHAORDE)
        WHEN 1 THEN 'ENERO'
        WHEN 2 THEN 'FEBRERO'
        WHEN 3 THEN 'MARZO'
        WHEN 4 THEN 'ABRIL'
        WHEN 5 THEN 'MAYO'
        WHEN 6 THEN 'JUNIO'
        WHEN 7 THEN 'JULIO'
        WHEN 8 THEN 'AGOSTO'
        WHEN 9 THEN 'SEPTIEMBRE'
        WHEN 10 THEN 'OCTUBRE'
        WHEN 11 THEN 'NOVIEMBRE'
        WHEN 12 THEN 'DICIEMBRE'
    END AS 'MES NOMBRE FECHA BUSQUEDA',
    FORMAT(DAY(FAR.FECHAORDE), '00') AS 'DIA FECHA BUSQUEDA',
    CONCAT(
        FORMAT(MONTH(FAR.FECHAORDE), '00'),
        ' - ',
        CASE
            MONTH(FAR.FECHAORDE)
            WHEN 1 THEN 'ENERO'
            WHEN 2 THEN 'FEBRERO'
            WHEN 3 THEN 'MARZO'
            WHEN 4 THEN 'ABRIL'
            WHEN 5 THEN 'MAYO'
            WHEN 6 THEN 'JUNIO'
            WHEN 7 THEN 'JULIO'
            WHEN 8 THEN 'AGOSTO'
            WHEN 9 THEN 'SEPTIEMBRE'
            WHEN 10 THEN 'OCTUBRE'
            WHEN 11 THEN 'NOVIEMBRE'
            WHEN 12 THEN 'DICIEMBRE'
        END
    ) MES_LABEL_VENCIMIENTO,
    YEAR(FAR.FECHAORDE) AS 'AÑO FECHA VENCIMIENTO',
    CONVERT(
        DATETIME,
        GETDATE() AT TIME ZONE 'Pakistan Standard Time',
        1
    ) AS ULT_ACTUAL 
FROM
    CTE_INGRESO ING
    INNER JOIN [INDIGO036].[dbo].[HCFARMEPC] FAR ON ING.NUMINGRES = FAR.NUMINGRES
    INNER JOIN CTE_DETALLE_FARMACIA FARD ON FAR.CODCONCEC = FARD.CODCONCEC
    INNER JOIN [INDIGO036].[dbo].[INPACIENT] PAC ON FAR.IPCODPACI = PAC.IPCODPACI
    INNER JOIN [INDIGO036].[Inventory].[ATC] ATC ON FARD.CODPRODUC = ATC.Code
    INNER JOIN [INDIGO036].[Inventory].[InventoryProduct] INV ON ATC.Id = INV.ATCId
    LEFT JOIN [INDIGO036].[Inventory].[ProductType] TIP ON INV.ProductTypeId = TIP.Id
        AND TIP.Name = 'MEDICAMENTOS'
    LEFT JOIN [INDIGO036].[Inventory].[PharmacologicalGroup] GFA ON ATC.PharmacologicalGroupId = GFA.Id
    LEFT JOIN [INDIGO036].[Inventory].[InventoryMeasurementUnit] UM ON FARD.CODUNIMED = UM.Code
    LEFT JOIN [INDIGO036].[Inventory].[AdministrationRoute] ADM ON ATC.AdministrationRouteId = ADM.Id
    LEFT JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensingDetail] DISD ON FARD.ID = DISD.EntityId
    LEFT JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensing] DIS ON DISD.PharmaceuticalDispensingId = DIS.Id
        AND DIS.Status = 2
    LEFT JOIN [INDIGO036].[dbo].[SEGusuaru] USU ON DIS.ConfirmationUser = USU.CODUSUARI
    LEFT JOIN [INDIGO036].[dbo].[INENTIDAD] ENT ON PAC.CODENTIDA = ENT.CODENTIDA
    LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] PRO ON FAR.CODPROSAL = PRO.CODPROSAL
    LEFT JOIN CTE_FISICO FIS ON ING.NUMINGRES = FIS.INGRESO
    LEFT JOIN [INDIGO036].[dbo].[HCHISPACA] ON FAR.NUMINGRES = [INDIGO036].[dbo].[HCHISPACA].NUMINGRES
        AND FAR.NUMEFOLIO = [INDIGO036].[dbo].[HCHISPACA].NUMEFOLIO
UNION ALL
SELECT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    FAR.FECHA AS [FECHA DE LA ORDEN],
    FAR.ESTADO AS [TIPO DE ORDEN],
    FAR.NUMINGRES AS [NUMERO DE INGRESO],
    FAR.NUMEFOLIO AS [FOLIO],
    PAC.IPCODPACI AS [ID PACIENTE],
    PAC.IPNOMCOMP AS PACIENTE,
    CAST(PAC.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
    FIS.PESO AS [PESO (KG)],
    ING.DESCCAMAS AS [CAMA ACTUAL],
    ING.UFUDESCRI AS [UNIDAD FUNCIONAL],
    FAR.CODPRODUC AS [CODIGO DE PRODUCTO],
    INV.Name AS PRODUCTO,
    'MEZCLA' AS [TIPO DE PRODUCTO],
    GFA.Name AS [GRUPO FARMACOLOGICO],
    CASE
        INV.POSProduct
        WHEN 1 THEN 'SI'
        ELSE 'NO'
    END AS PBS,
    CASE
        ATC.Antibiotic
        WHEN 1 THEN 'SI'
        ELSE 'NO'
    END AS ANTIBIOTICO,
    CASE
        INV.ProductControl
        WHEN 1 THEN 'SI'
        ELSE 'NO'
    END AS CONTROL,
    INV.Presentation AS PRESENTACION,
    FAR.DOSIS,
    UM.Name AS MEDIDA,
    FAR.FRECUENCIA,
    FAR.TIEMPO,
    ADM.Name AS [VIA DE ADMINISTRACION],
    FAR.DURACION,
    FAR.TRATAMIENTO AS [DIA DE TRATAMIENTO],
    FAR.CANTIDAD AS [CANTIDAD FORMULADA],
    NULL AS [CONCILIACION MEDICAMENTOSA],
    DISD.Quantity AS [CANTIDAD DISPENSADA],
    '' AS [CANTIDAD APLICADA],
    DIS.Code AS [CODIGO DE DISPENSACION],
    DIS.ConfirmationDate AS [FECHA Y HORA DISPENSACION],
    USU.NOMUSUARI AS [USUARIO CONFIRMACION],
    ENT.NOMENTIDA AS ENTIDAD,
    CASE
        PAC.IPTIPOPAC
        WHEN 1 THEN 'Contributivo'
        WHEN 2 THEN 'Subsidiado'
        WHEN 3 THEN 'Vinculado'
        WHEN 4 THEN 'Particular'
        WHEN 5 THEN 'Otro'
        WHEN 6 THEN 'Desplazado Reg. Contributivo'
        WHEN 7 THEN 'Desplazado Reg. Subsidiado'
        WHEN 8 THEN 'Desplazado No Asegurado'
    END AS [GRUPO DE ATENCION],
    CASE
        WHEN ING.FECHEGRESO IS NULL THEN 'HOSPITALIZADO'
        ELSE 'EGRESADO'
    END AS ESTADO,
    PRO.NOMMEDICO AS [PROFESIONAL QUE ORDENO],
    INV.ProductCost AS [COSTO PROMEDIO],
    CAST(FAR.FECHA AS date) AS 'FECHA BUSQUEDA',
    YEAR(FAR.FECHA) AS 'AÑO FECHA BUSQUEDA',
    MONTH(FAR.FECHA) AS 'MES AÑO FECHA BUSQUEDA',
    CASE
        MONTH(FAR.FECHA)
        WHEN 1 THEN 'ENERO'
        WHEN 2 THEN 'FEBRERO'
        WHEN 3 THEN 'MARZO'
        WHEN 4 THEN 'ABRIL'
        WHEN 5 THEN 'MAYO'
        WHEN 6 THEN 'JUNIO'
        WHEN 7 THEN 'JULIO'
        WHEN 8 THEN 'AGOSTO'
        WHEN 9 THEN 'SEPTIEMBRE'
        WHEN 10 THEN 'OCTUBRE'
        WHEN 11 THEN 'NOVIEMBRE'
        WHEN 12 THEN 'DICIEMBRE'
    END AS 'MES NOMBRE FECHA BUSQUEDA',
    FORMAT(DAY(FAR.FECHA), '00') AS 'DIA FECHA BUSQUEDA',
    CONCAT(
        FORMAT(MONTH(FAR.FECHA), '00'),
        ' - ',
        CASE
            MONTH(FAR.FECHA)
            WHEN 1 THEN 'ENERO'
            WHEN 2 THEN 'FEBRERO'
            WHEN 3 THEN 'MARZO'
            WHEN 4 THEN 'ABRIL'
            WHEN 5 THEN 'MAYO'
            WHEN 6 THEN 'JUNIO'
            WHEN 7 THEN 'JULIO'
            WHEN 8 THEN 'AGOSTO'
            WHEN 9 THEN 'SEPTIEMBRE'
            WHEN 10 THEN 'OCTUBRE'
            WHEN 11 THEN 'NOVIEMBRE'
            WHEN 12 THEN 'DICIEMBRE'
        END
    ) MES_LABEL_VENCIMIENTO,
    YEAR(FAR.FECHA) AS 'AÑO FECHA VENCIMIENTO',
    CONVERT(
        DATETIME,
        GETDATE() AT TIME ZONE 'Pakistan Standard Time',
        1
    ) AS ULT_ACTUAL
FROM  
    CTE_INGRESO ING
    INNER JOIN CTE_LIQUIDOS FAR ON ING.NUMINGRES = FAR.NUMINGRES
    INNER JOIN [INDIGO036].[dbo].[INPACIENT] PAC ON FAR.IPCODPACI = PAC.IPCODPACI
    INNER JOIN [INDIGO036].[Inventory].[ATC] ATC ON FAR.CODPRODUC = ATC.Code
    INNER JOIN [INDIGO036].[Inventory].[InventoryProduct] INV ON ATC.Id = INV.ATCId
    INNER JOIN [INDIGO036].[Inventory].[PharmacologicalGroup] GFA ON ATC.PharmacologicalGroupId = GFA.Id
    LEFT JOIN [INDIGO036].[Inventory].[InventoryMeasurementUnit] UM ON FAR.MEDIDA = UM.Code
    LEFT JOIN [INDIGO036].[Inventory].[AdministrationRoute] ADM ON ATC.AdministrationRouteId = ADM.Id
    LEFT JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensingDetail] DISD ON FAR.ID = DISD.EntityId
    LEFT JOIN [INDIGO036].[Inventory].[PharmaceuticalDispensing] DIS ON DISD.PharmaceuticalDispensingId = DIS.Id
        AND DIS.Status = 2
    LEFT JOIN [INDIGO036].[dbo].[SEGusuaru] USU ON DIS.ConfirmationUser = USU.CODUSUARI
    LEFT JOIN [INDIGO036].[dbo].[INENTIDAD] ENT ON PAC.CODENTIDA = ENT.CODENTIDA
    LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] PRO ON FAR.PROFESIONAL = PRO.CODPROSAL
    LEFT JOIN CTE_FISICO FIS ON ING.NUMINGRES = FIS.INGRESO