-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_VIEWPROCEDIMIENTOSQX
-- Extracted by Fabric SQL Extractor SPN v3.9.0



--SELECT COUNT (*) FROM [Report].[ViewProcedimientosQX]


/*******************************************************************************************************************
Nombre: [Report].[ViewProcedimientosQX]
Tipo:Vista
Observacion:Vista sobre los procedimientos QX realizados, siempre y cuanto cuenten con un informe QX
Profesional: Nilsson Miguel Galindo Lopez
Fecha:03-05-2022
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha: 26-04-2023
Ovservaciones:Se agrega la especialidad del cirujano principal, solicitud realizada mediante el ticket 
--------------------------------------
Version 3
Persona que modifico:Nilsson Miguel Galindo Lopez
Observacion:Se agrega el campo numero de folio, y dos procedimientos secundarios mediante un cte, esto solicitado por san andres
Fecha:26-07-2023
----------------------------------------------------------------------------------------------------------------------------------
Version 4
Persona que modifico:Nilsson Miguel Galindo Lopez
Observacion:Se agregan los campos de codigo de especialidad del cirajano principal y solicitud vs programacion dias
Fecha:08-08-2023
----------------------------------------------------------------------------------------------------------------------------------
Version 5
Persona que modifico:Nilsson Miguel Galindo Lopez
Observacion:Se agrega la condición que el numero de la sala primero tenga encuenta la sala del agendamiento y luego el numero de sala colocado por el profesional
			en el informe quirurjico, tambien se agrega el campo de id agenda 
Fecha:25-08-2023
----------------------------------------------------------------------------------------------------------------------------------
Version 6
Persona que modifico:Nilsson Miguel Galindo Lopez
Observacion:Se agrega la la tabla hchispaca para ver solo los folios activos, tambien se agrega la tabla dbo.HCQXEQUIP
			para mostrar el cx principal y no de la tabla HCQXINFOR como estaba 
Fecha:15-12-2023
----------------------------------------------------------------------------------------------------------------------------------
Version 7
Persona que modifico:Nilsson Miguel Galindo Lopez
Observacion:Se ajustan campos y se validan, ademas se deja la logica de solo procedimientos realizados con un informe qx
Fecha:16-01-2024
----------------------------------------------------------------------------------------------------------------------------------
Version 8
Persona que modifico:Nilsson Miguel Galindo Lopez
Observacion:Se ajustan campos solicitados por HOMI en el ticket 18720
Fecha:04-07-2024
----------------------------------------------------------------------------------------------------------------------------------
Version 9
Persona que modifico:Nilsson Miguel Galindo Lopez
Observacion:Se cambia la logica de la relación entre las tablas dbo.AGEPROGQX y dbo.HCORDPROQ, esto requerio por HOMI en el ticket 19325
Fecha:26-07-2024
--***********************************************************************************************************************************/

CREATE   VIEW  [Report].[VW_VIEWPROCEDIMIENTOSQX] AS


WITH CTE_ANESTESIA AS (
  SELECT
    NUMINGRES,
    HORINIANES,
    HORFINANES,
    OBSERVACIO,
    RTRIM(PRO.CODPROSAL)+' - '+PRO.NOMMEDICO AS MEDICO
  FROM
    [INDIGO036].dbo.HCREGANES ANE
    INNER JOIN [INDIGO036].dbo.INPROFSAL PRO ON PRO.CODPROSAL = ANE.CODPROSAL
    WHERE ANE.IDANESTES = (
        SELECT MIN(IDANESTES) 
        FROM [INDIGO036].dbo.HCREGANES 
        WHERE NUMINGRES = ANE.NUMINGRES
    )

   --where ANE.NUMINGRES='428447'
 ),
--IN V3

CTE_PROCEDIMIENTOS AS
(
	SELECT 
	0 AS NUMERO,
	1 AS TIPO,
	REA.NUMINGRES,
	REA.NUMEFOLIO,
	CUPS.Code,
	CUPS.Description,
	1 AS CANTIDAD
	FROM
	[INDIGO036].dbo.HCQXREALI REA INNER JOIN
	[INDIGO036].[Contract].CUPSEntity CUPS ON REA.CODSERIPS=CUPS.Code AND REA.QXPRINCIP=1
	UNION ALL
	SELECT 
	ROW_NUMBER ( )   
	OVER (PARTITION BY REA.NUMINGRES,REA.NUMEFOLIO order by REA.CONSECUQX DESC) AS NUMERO,
	2 AS TIPO, 
	REA.NUMINGRES,
	REA.NUMEFOLIO,
	CUPS.Code,
	CUPS.Description,
	1 AS CATIDAD
	FROM
	[INDIGO036].dbo.HCQXREALI REA INNER JOIN
	[INDIGO036].[Contract].CUPSEntity CUPS ON REA.CODSERIPS=CUPS.Code AND REA.QXPRINCIP=0
),
CTE_CUENTA_PROCEDIMIENTOS AS
(
SELECT 
SUM(CANTIDAD) AS CATIDAD,
NUMINGRES,
NUMEFOLIO
FROM CTE_PROCEDIMIENTOS
WHERE TIPO!=1
GROUP BY NUMINGRES,NUMEFOLIO
)
--FN V3


SELECT
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
 CASE PAC.IPTIPODOC WHEN '1'THEN 'CC'
					WHEN '2'THEN 'CE'
				    WHEN '3'THEN 'TI'
				    WHEN '4'THEN 'RC'
				    WHEN '5'THEN 'PA'
				    WHEN '6'THEN 'AS'
				    WHEN '7'THEN 'MS'
				    WHEN '8'THEN 'NU'
				    WHEN '9'THEN 'NV'
				    WHEN '10'THEN 'CD'
				    WHEN '11'THEN 'SC'
				    WHEN '12'THEN 'PE'
				    WHEN '13'THEN 'PT'
				    WHEN '14'THEN 'DE'
				    WHEN '15'THEN 'SI'
				    WHEN '16'THEN 'NI' END AS [TIPO IDENTIFICACION],
 QX.IPCODPACI AS [NUMERO_IDENTIFICACION],
 CASE IPSEXOPAC WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END AS SEXO,
 PAC.IPPRIAPEL AS 'PRIMER APELLIDO',
 PAC.IPSEGAPEL AS 'SEGUNDO APELLIDO',
 PAC.IPPRINOMB AS 'PRIMER NOMBRE',
 PAC.IPSEGNOMB AS 'SEGUNDO NOMBRE',
 PAC.IPNOMCOMP AS [PACIENTE NOMBRE COMPLETO],
 DEP.depcodigo AS [CODIGO DEPARTAMENTO], 
 DEP.nomdepart AS [NOMBRE DEPARTAMENTO RESIDENCIA], 
 PAC.IPDIRECCI AS [DIRECCION],
 MUN.MUNCODIGO [CODIGO MUNICIPIO RESIDENCIA], 
 MUN.MUNNOMBRE AS [NOMBRE MUNICIPIO RESIDENCIA], 
 CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
 PAC.IPTELEFON AS [TELEFONO FIJO],
 PAC.IPTELMOVI AS [TELEFONO MOVIL],
 EA.HealthEntityCode AS [CODIGO EPS/ENTIDAD TERRITORIAL],
 RTRIM(EA.Code) [COD. ADMINISTRADORA],
 EA.Name AS [ENTIDAD ADMINISTRADORA],
 CASE EA.EntityType WHEN 1  THEN 'EPS Contributivo'
				    WHEN 2  THEN 'EPS Subsidiado'
				    WHEN 3  THEN 'ET Vinculados Municipios'
				    WHEN 4  THEN 'ET Vinculados Departamentos'
				    WHEN 5  THEN 'ARL Riesgos Laborales'
				    WHEN 6  THEN 'MP Medicina Prepagada'
				    WHEN 7  THEN 'IPS Privada'
				    WHEN 8  THEN 'IPS Publica'
				    WHEN 9  THEN 'Regimen Especial'
				    WHEN 10 THEN 'Accidentes de transito'
				    WHEN 11 THEN 'Fosyga'
				    WHEN 12 THEN 'Otros' END AS [REGIMEN],
 CASE GA.LiquidationType WHEN 1 THEN 'PAGO POR SERVICIOS'
						 WHEN 2 THEN 'PGP'
						 WHEN 3 THEN 'FACTURA GLOBAL'
						 WHEN 4 THEN 'CAPITACION GLOBAL'
						 WHEN 5 THEN 'CONTROL' END [TIPO CONTRATO],
 CASE WHEN PR.ORIGENQX=1 THEN 'ORIGEN AMBULATORIO' 
	  WHEN PR.ORIGENQX=2 THEN 'ORIGEN HOSPITALARIO' 
	  WHEN ING.TIPOINGRE=1 THEN 'ORIGEN AMBULATORIO' 
	  WHEN ING.TIPOINGRE=2 THEN 'ORIGEN HOSPITALARIO' END AS AMBITO,
 QX.UFUCODIGO [COD. UNIDAD FUNCIONAL],
 UNI.UFUDESCRI [UNIDAD FUNCIONAL],
 QX.NUMINGRES AS NUMERO_INGRESO,
 QX.NUMEFOLIO AS [NUMERO DE FOLIO],
 CASE SOL.PRISERIPS WHEN 1 THEN 'Emergencia'
					WHEN 2 THEN 'Urgencia'
					WHEN 3 THEN 'Normal'
					WHEN 4 THEN 'Definir Conducta' ELSE SOL.PRISERIPS END AS [PRIORIDAD SOLICITUD],
 CASE QX.URGECIRUG WHEN 1 THEN 'SI'
				   WHEN 0 THEN 'NO' END AS [MARCADO URGENCIA INFORME],
 'PRINCIPAL' AS [TIPO DE PRODCEDIMIENTO QX],--IN V5
 CASE TIPOINFORME WHEN 1 THEN 'Informe QX' 
				  WHEN 2 THEN 'Informe no QX' END AS [TIPO DE INFORME],
 PRI.Code AS CODIGO_CUPS,
 PRI.[Description] AS [CUPS PROCEDIMIENTO],
 SEC1.Code +' - '+ SEC1.Description AS [PROCEDIMIENTO SECUNDARIO UNO],
 SEC2.Code +' - '+ SEC2.Description AS [PROCEDIMIENTO SECUNDARIO DOS],
 SEC3.Code +' - '+ SEC3.Description AS [PROCEDIMIENTO SECUNDARIO TRES],
 SEC4.Code +' - '+ SEC4.Description AS [PROCEDIMIENTO SECUNDARIO CUATRO],
 SEC5.Code +' - '+ SEC5.Description AS [PROCEDIMIENTO SECUNDARIO CINCO],
 SEC6.Code +' - '+ SEC6.Description AS [PROCEDIMIENTO SECUNDARIO SEIS],
 SEC7.Code +' - '+ SEC7.Description AS [PROCEDIMIENTO SECUNDARIO SIETE],
 SEC8.Code +' - '+ SEC8.Description AS [PROCEDIMIENTO SECUNDARIO OCHO],
 SEC9.Code +' - '+ SEC9.Description AS [PROCEDIMIENTO SECUNDARIO NUEVE],
 SEC10.Code +' - '+ SEC10.Description AS [PROCEDIMIENTO SECUNDARIO DIEZ],
 SEC11.Code +' - '+ SEC11.Description AS [PROCEDIMIENTO SECUNDARIO ONCE],
 SEC12.Code +' - '+ SEC12.Description AS [PROCEDIMIENTO SECUNDARIO DOCE],
 SEC13.Code +' - '+ SEC13.Description AS [PROCEDIMIENTO SECUNDARIO TRECE],
 SEC14.Code +' - '+ SEC14.Description AS [PROCEDIMIENTO SECUNDARIO CATORCE],
 SEC15.Code +' - '+ SEC15.Description AS [PROCEDIMIENTO SECUNDARIO QUINCE],
 ISNULL(CONTAR.CATIDAD,0) AS [CANTIDAD PROCEDIMIENTOS SECUNDARIOS],
 QX.DESPROCED AS [DESCRIPCION DEL PROCEDIMIENTO], 
 GRU.Grupoqx AS [GRUPO QX],
 /*V8*/RAD.NUMRADICACION AS [NUMERO RADICACION],
 --ISNULL(RAD.FECHARADIC,SOL.FECORDMED) AS [FECHA SOLICITUD ORDEN/RADICACIÓN], 
 RAD.FECHARADIC AS [FECHA RADICADO],
 RAD.FECHACONFIRMACION AS [FECHA CONFIRMACION RADICACION],
 ISNULL(SOL.FECORDMED,NONQX.FECORDMED) AS [FECHA SOLICITUD ORDEN], --V8
 QX.FECHORINI AS [FECHA INICIO CIRUGIA],
 QX.FECHORFIN AS [FECHA FINAL CIRUGIA], 
 DATEDIFF(MINUTE,QX.FECHORINI,QX.FECHORFIN) AS [DURACION QX MINUTOS],
 --DATEDIFF(MINUTE,ISNULL(RAD.FECHARADIC,SOL.FECORDMED),QX.FECHORINI) AS [ORDEN/RADICACIÓN VS INICIO QX, MINUTOS],
 DATEDIFF(MINUTE,RAD.FECHARADIC,QX.FECHORINI) AS [RADICACIÓN VS INICIO QX, MINUTOS],
 DATEDIFF(MINUTE,ISNULL(SOL.FECORDMED,NONQX.FECORDMED),QX.FECHORINI) AS [ORDEN VS INICIO QX, MINUTOS],
 CASE SAL.TIPOSALA WHEN 'Q' THEN 'Quirurgica'
				   WHEN 'D' THEN 'Apoyo Diagnostico'
				   WHEN 'U' THEN 'Urgencias'
				   WHEN 'E' THEN 'Tratamientos Especiales' ELSE 'NO APLICA' END [TIPO SALA],
 ISNULL(SAL.DESCRIPSAL,CONVERT(VARCHAR(MAX),QX.SALACIRUG)) AS [NUMERO DE SALA],
 DIG1.CODDIAGNO AS [CODIGO DX PRE OPEERATORIO],
 DIG1.NOMDIAGNO AS [DX PRE OPERATORIO],
 DIG2.CODDIAGNO AS [CODIGO DX POS OPERATORIO],
 DIG2.NOMDIAGNO AS [DX POS OPERATORIO],
 RTRIM(LTRIM(PRO.CODPROSAL))+' - '+RTRIM(PRO.NOMMEDICO) AS [CIRUJANO PRINCIPAL],
/*IN V4*/INE.CODESPECI AS [CODIGO ESPECIALIDAD CIRUJANO], --FN V4
/*IN V2*/INE.DESESPECI AS [ESPECIALIDAD CIRUJANO],--FN V2
 CASE QX.TIPHERCIR WHEN 1 THEN 'LIMPIA'
				   WHEN 2 THEN 'LIMPIA CONTAMINADA'
				   WHEN 3 THEN 'CONTAMINADA'
				   WHEN 4 THEN 'SUCIA E INFECTADA'
				   WHEN 5 THEN 'SUCIA'
				   WHEN 6 THEN 'INFECTADA'
				   WHEN 7 THEN 'NO APLICA' END AS TIPO_HERIDA,
 CASE QX.TIPOANEST WHEN 1 THEN 'LOCAL'
				   WHEN 2 THEN 'REGIONAL'
				   WHEN 3 THEN 'GENERAL'
				   WHEN 4 THEN 'COMBINADA'
				   WHEN 5 THEN 'NO APLICA'
				   WHEN 6 THEN 'RAQUIDEA'
				   WHEN 7 THEN 'PERIDUDRAL'
				   WHEN 8 THEN 'CAUDAL'
				   WHEN 9 THEN 'SEDACION'END as [TIPO DE ANESTECIA],
 ANE.HORINIANES AS [FECHA INICIO ANESTESIA],
 ANE.HORFINANES AS [FECHA FIN ANESTESIA],
 DATEDIFF(MINUTE,ANE.HORINIANES,ANE.HORFINANES) AS [DURACION MINUTOS ANESTESIA],
 ANE.MEDICO AS ANESTESIOLOGO,
 --PR.FECHACAN as [FECHA CANCELACION],
 --CAN.DESCAUCAN AS [CAUSA DE CANCELACION],
 --PR.OBSERCAN AS [DESCRIPCION DE CANCELACION],
--/*IN V4*/DATEDIFF(DAY,PR.FECREGSIS,PR.FECHORAIN) AS [SOLICITUD VS PROGRAMACION DIAS],--FN V4
 PR.IDAGENDA AS [ID AGENDA], --FN V5
 ISNULL(SOL.AUTO,NONQX.AUTO) AS [ID ORDENAMIENTO],
 1 as 'CANTIDAD',
 CAST(ISNULL(QX.FECHORINI, PR.FECHORAIN) AS date) AS 'FECHA BUSQUEDA',
 YEAR(ISNULL(QX.FECHORINI, PR.FECHORAIN)) AS 'AÑO BUSQUEDA',
 MONTH(ISNULL(QX.FECHORINI, PR.FECHORAIN)) AS 'MES BUSQUEDA',
 CONCAT(FORMAT(MONTH(ISNULL(QX.FECHORINI, PR.FECHORAIN)), '00') ,' - ', 
	   CASE MONTH(ISNULL(QX.FECHORINI, PR.FECHORAIN)) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 [INDIGO036].dbo.HCQXINFOR QX 
 INNER JOIN [INDIGO036].dbo.INPACIENT PAC ON QX.IPCODPACI=PAC.IPCODPACI 
 INNER JOIN [INDIGO036].dbo.ADINGRESO ING ON QX.NUMINGRES=ING.NUMINGRES   
 INNER JOIN [INDIGO036].dbo.INUBICACI AS UBI  ON PAC.AUUBICACI = UBI.AUUBICACI 
 INNER JOIN [INDIGO036].dbo.INMUNICIP AS MUN  ON UBI.DEPMUNCOD = MUN.DEPMUNCOD 
 INNER JOIN [INDIGO036].dbo.INDEPARTA AS DEP  ON DEP.depcodigo = MUN.DEPCODIGO 
 INNER JOIN [INDIGO036].Contract.CareGroup AS GA ON GA.Id = PAC.GENCAREGROUP 
 INNER JOIN [INDIGO036].Contract.HealthAdministrator EA ON PAC.CODENTIDA=EA.Code
 INNER JOIN [INDIGO036].dbo.INDIAGNOS DIG1 ON DIG1.CODDIAGNO=QX.CODDIAPRE 
 INNER JOIN [INDIGO036].dbo.INDIAGNOS DIG2 ON DIG2.CODDIAGNO=QX.CODDIAPOS  
 /*in v6*/INNER JOIN [INDIGO036].dbo.HCHISPACA HC ON QX.NUMINGRES=HC.NUMINGRES AND QX.NUMEFOLIO=HC.NUMEFOLIO AND HC.ESTAFOLIO=1-- se valida que el folio no este anulado
 INNER JOIN [INDIGO036].dbo.HCQXEQUIP CX ON QX.NUMINGRES=CX.NUMINGRES AND QX.NUMEFOLIO=CX.NUMEFOLIO AND CX.QXPRINCIP=1/*fn v6*/
 INNER JOIN [INDIGO036].dbo.INPROFSAL PRO ON CX.CODPROSAL=PRO.CODPROSAL
 LEFT JOIN [INDIGO036].dbo.INUNIFUNC UNI ON QX.UFUCODIGO = UNI.UFUCODIGO
 --IN V8 LEFT JOIN dbo.AGEPROGQX PR ON QX.IPCODPACI=PR.IPCODPACI AND QX.CODSERIPS=PR.CODSERIPS AND CAST(QX.FECHORINI AS DATE)=CAST(PR.FECHORAIN AS DATE)
 --LEFT JOIN dbo.HCORDPROQ SOL ON QX.NUMINGRES=SOL.NUMINGRES AND SOL.AUTO=(SELECT MAX(AUTO) FROM dbo.HCORDPROQ A WHERE A.NUMINGRES=QX.NUMINGRES AND QX.CODSERIPS=A.CODSERIPS)
 LEFT JOIN [INDIGO036].dbo.HCORDPROQ SOL ON QX.NUMINGRES=SOL.NUMINGRES AND SOL.AUTO=(SELECT MAX(A.AUTO) FROM [INDIGO036].dbo.HCORDPROQ A WHERE A.NUMINGRES=QX.NUMINGRES AND QX.CODSERIPS=A.CODSERIPS)
 LEFT JOIN [INDIGO036].dbo.HCORDPRON NONQX ON QX.NUMINGRES=NONQX.NUMINGRES AND NONQX.AUTO=(SELECT MAX(A.AUTO) FROM [INDIGO036].dbo.HCORDPRON A WHERE A.NUMINGRES=QX.NUMINGRES AND QX.CODSERIPS=A.CODSERIPS)
 LEFT JOIN [INDIGO036].dbo.AGEPROGQX PR ON SOL.AUTOCITA=PR.CODAUTONU --FN V8
 LEFT JOIN [INDIGO036].dbo.INESPECIA INE ON PRO.CODESPEC1=INE.CODESPECI 
 LEFT JOIN [INDIGO036].dbo.ADRADICACIONQX RAD ON PR.IPCODPACI=RAD.IPCODPACI AND RAD.ESTADO!=3
 --LEFT JOIN dbo.ADRADICACIONQX RAD ON PR.IDRADICACIONQX=RAD.ID AND RAD.ESTADO!=3  se realiza union por la tabla Paciente.
 LEFT JOIN /*in v3*/ CTE_PROCEDIMIENTOS PRI ON QX.NUMINGRES=PRI.NUMINGRES AND QX.NUMEFOLIO=PRI.NUMEFOLIO AND PRI.TIPO=1 
 LEFT JOIN CTE_PROCEDIMIENTOS SEC1 ON QX.NUMINGRES=SEC1.NUMINGRES AND QX.NUMEFOLIO=SEC1.NUMEFOLIO AND SEC1.TIPO=2 AND SEC1.NUMERO=1 
 LEFT JOIN CTE_PROCEDIMIENTOS SEC2 ON QX.NUMINGRES=SEC2.NUMINGRES AND QX.NUMEFOLIO=SEC2.NUMEFOLIO AND SEC2.TIPO=2 AND SEC2.NUMERO=2 
 LEFT JOIN CTE_PROCEDIMIENTOS SEC3 ON QX.NUMINGRES=SEC3.NUMINGRES AND QX.NUMEFOLIO=SEC3.NUMEFOLIO AND SEC3.TIPO=2 AND SEC3.NUMERO=3
 LEFT JOIN CTE_PROCEDIMIENTOS SEC4 ON QX.NUMINGRES=SEC4.NUMINGRES AND QX.NUMEFOLIO=SEC4.NUMEFOLIO AND SEC4.TIPO=2 AND SEC4.NUMERO=4
 LEFT JOIN CTE_PROCEDIMIENTOS SEC5 ON QX.NUMINGRES=SEC5.NUMINGRES AND QX.NUMEFOLIO=SEC5.NUMEFOLIO AND SEC5.TIPO=2 AND SEC5.NUMERO=5
 LEFT JOIN CTE_PROCEDIMIENTOS SEC6 ON QX.NUMINGRES=SEC6.NUMINGRES AND QX.NUMEFOLIO=SEC6.NUMEFOLIO AND SEC6.TIPO=2 AND SEC6.NUMERO=6
 LEFT JOIN CTE_PROCEDIMIENTOS SEC7 ON QX.NUMINGRES=SEC7.NUMINGRES AND QX.NUMEFOLIO=SEC7.NUMEFOLIO AND SEC7.TIPO=2 AND SEC7.NUMERO=7
 LEFT JOIN CTE_PROCEDIMIENTOS SEC8 ON QX.NUMINGRES=SEC8.NUMINGRES AND QX.NUMEFOLIO=SEC8.NUMEFOLIO AND SEC8.TIPO=2 AND SEC8.NUMERO=8
 LEFT JOIN CTE_PROCEDIMIENTOS SEC9 ON QX.NUMINGRES=SEC9.NUMINGRES AND QX.NUMEFOLIO=SEC9.NUMEFOLIO AND SEC9.TIPO=2 AND SEC9.NUMERO=9
 LEFT JOIN CTE_PROCEDIMIENTOS SEC10 ON QX.NUMINGRES=SEC10.NUMINGRES AND QX.NUMEFOLIO=SEC10.NUMEFOLIO AND SEC10.TIPO=2 AND SEC10.NUMERO=10
 LEFT JOIN CTE_PROCEDIMIENTOS SEC11 ON QX.NUMINGRES=SEC11.NUMINGRES AND QX.NUMEFOLIO=SEC11.NUMEFOLIO AND SEC11.TIPO=2 AND SEC11.NUMERO=11
 LEFT JOIN CTE_PROCEDIMIENTOS SEC12 ON QX.NUMINGRES=SEC12.NUMINGRES AND QX.NUMEFOLIO=SEC12.NUMEFOLIO AND SEC12.TIPO=2 AND SEC12.NUMERO=12
 LEFT JOIN CTE_PROCEDIMIENTOS SEC13 ON QX.NUMINGRES=SEC13.NUMINGRES AND QX.NUMEFOLIO=SEC13.NUMEFOLIO AND SEC13.TIPO=2 AND SEC13.NUMERO=13
 LEFT JOIN CTE_PROCEDIMIENTOS SEC14 ON QX.NUMINGRES=SEC14.NUMINGRES AND QX.NUMEFOLIO=SEC14.NUMEFOLIO AND SEC14.TIPO=2 AND SEC14.NUMERO=14
 LEFT JOIN CTE_PROCEDIMIENTOS SEC15 ON QX.NUMINGRES=SEC15.NUMINGRES AND QX.NUMEFOLIO=SEC15.NUMEFOLIO AND SEC15.TIPO=2 AND SEC15.NUMERO=15
 --LEFT JOIN [Contract].CUPSEntity CUPS ON REA.CODSERIPS=CUPS.Code AND CUPS.Status=1 fn v3
 LEFT JOIN CTE_ANESTESIA ANE ON QX.NUMINGRES = ANE.NUMINGRES
 LEFT JOIN [INDIGO036].Report.GruposQX GRU ON QX.CODSERIPS=GRU.Code /*IN V5*/
 LEFT JOIN [INDIGO036]..AGENSALAC SAL ON PR.AGENSALAC=SAL.CODCONCEC /*FN V5*/
 LEFT JOIN CTE_CUENTA_PROCEDIMIENTOS CONTAR ON QX.NUMINGRES=CONTAR.NUMINGRES AND QX.NUMEFOLIO=CONTAR.NUMEFOLIO
--WHERE QX.IPCODPACI in('1074138385','1066286327') --AND MONTH(QX.FECHORINI)=6
--order by qx.NUMEFOLIO
--,'33449558','9656052')
--WHERE CAST(FECHORINI AS DATE) BETWEEN '2023-12-01' AND '2023-12-31'
--where QX.numingres='428513'
