-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_VIEW_FAC_REPORTE_PROCEDIMIENTOS_QX_POR_RECONOCER
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_VIEW_FAC_REPORTE_PROCEDIMIENTOS_QX_POR_RECONOCER AS
WITH CTE_PROCEDIMIENTO_QX_UNICOS AS (
    SELECT
        DISTINCT A.NUMINGRES,
        A.IPCODPACI,
        ING.IESTADOIN,
        CASE
            ING.TIPOINGRE
            WHEN 1 THEN 'Ambulatorio'
            WHEN 2 THEN 'Hospitalario'
        END AMBITO
    FROM
        INDIGO036.dbo.HCQXINFOR A
        INNER JOIN INDIGO036.dbo.ADINGRESO AS ING ON ING.NUMINGRES = A.NUMINGRES
        INNER JOIN INDIGO036.dbo.INPACIENT P ON A.IPCODPACI = P.IPCODPACI
        INNER JOIN INDIGO036.dbo.HCQXREALI C ON A.NUMINGRES = C.NUMINGRES
            AND A.NUMEFOLIO = C.NUMEFOLIO
        INNER JOIN INDIGO036.Contract.CUPSEntity CCE ON A.CODSERIPS = CCE.Code
            AND CCE.ShowServiceMedicalOrder = 5
    WHERE
        A.GENSERVICEORDER IS NULL AND ING.IESTADOIN in (' ', 'P')
    UNION ALL
    SELECT
        DISTINCT A.NUMINGRES,
        A.IPCODPACI,
        ING.IESTADOIN,
        CASE
            ING.TIPOINGRE
            WHEN 1 THEN 'Ambulatorio'
            WHEN 2 THEN 'Hospitalario'
        END AMBITO
    FROM
        INDIGO036.dbo.HCQXINFOR A
        INNER JOIN INDIGO036.dbo.HCINGRESORECNAC INGMH ON A.NUMINGRES = INGMH.NUMINGRESHIJO
        INNER JOIN INDIGO036.dbo.HCRECINAC RN ON INGMH.NUMINGRESHIJO = RN.NUMINGRESHIJO
        INNER JOIN INDIGO036.dbo.ADINGRESO AS ING ON ING.NUMINGRES = INGMH.NUMINGRESHIJO
        INNER JOIN INDIGO036.dbo.HCQXREALI C ON A.IPCODPACI = C.IPCODPACI
            AND A.NUMINGRES = C.NUMINGRES
            AND A.NUMEFOLIO = C.NUMEFOLIO
        INNER JOIN INDIGO036.Contract.CUPSEntity CCE ON A.CODSERIPS = CCE.Code
            AND CCE.ShowServiceMedicalOrder = 5
    WHERE
        A.GENSERVICEORDER IS NULL AND ING.IESTADOIN in (' ', 'P')
),
CTE_ULTIMA_CAMAS_OCUPADA AS (
    SELECT
        EGR.IPCODPACI,
        EGR.NUMINGRES,
        EGR.FECINIEST,
        EGR.FECFINEST,
        EGR.CODICAMAS,
        CAM.NUMCAMHOS,
        FUN.UFUDESCRI,
        FUN.UFUTIPUNI
    FROM
        INDIGO036.dbo.CHREGESTA EGR
        INNER JOIN (
            SELECT
                EGR.IPCODPACI,
                EGR.NUMINGRES,
                MAX(EGR.ID) ID
            FROM
                INDIGO036.dbo.CHREGESTA EGR
                INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS AS UNI ON UNI.NUMINGRES = EGR.NUMINGRES
            GROUP BY
                EGR.IPCODPACI,
                EGR.NUMINGRES
        ) AS G ON G.ID = EGR.ID
        INNER JOIN INDIGO036.dbo.CHCAMASHO AS CAM ON CAM.CODICAMAS = EGR.CODICAMAS
        INNER JOIN INDIGO036.dbo.INUNIFUNC AS FUN ON CAM.UFUCODIGO = FUN.UFUCODIGO
),
CTE_EGRESO_CAMA AS (
    SELECT
        EGR.NUMINGRES,
        EGR.IPCODPACI,
        EGR.FECEGRESO
    FROM
        INDIGO036.dbo.CHREGEGRE EGR
        INNER JOIN (
            SELECT
                EGR.NUMINGRES,
                EGR.IPCODPACI,
                MAX(EGR.FECEGRESO) EGRESO
            FROM
                INDIGO036.dbo.CHREGEGRE EGR
                INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS AS UNI ON UNI.NUMINGRES = EGR.NUMINGRES
            GROUP BY
                EGR.NUMINGRES,
                EGR.IPCODPACI
        ) AS G ON G.NUMINGRES = EGR.NUMINGRES
            AND G.IPCODPACI = EGR.IPCODPACI
            AND G.EGRESO = EGR.FECEGRESO
),
CTE_ORDENES_CON_QX_CARGADAS AS (
    SELECT
        RC.AdmissionNumber,
        G.CUPS,
        G.CANTIDAD
    FROM
        INDIGO036.Billing.RevenueControl AS RC
        INNER JOIN (
            SELECT
                RC.AdmissionNumber,
                CUPS.Code CUPS,
                SUM(SOD.InvoicedQuantity) CANTIDAD
            FROM
                INDIGO036.Billing.RevenueControl AS RC
                INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS PRO ON RC.AdmissionNumber = PRO.NUMINGRES
                INNER JOIN INDIGO036.Billing.RevenueControlDetail AS RCD ON RC.Id = RCD.RevenueControlId
                INNER JOIN INDIGO036.Billing.ServiceOrderDetailDistribution AS SODD ON RCD.Id = SODD.RevenueControlDetailId
                INNER JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD ON SODD.ServiceOrderDetailId = SOD.Id
                INNER JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON CUPS.Id = SOD.CUPSEntityId
            WHERE
                RCD.Status IN ('1', '2', '3')
                AND CUPS.BillingGroupId IN (5, 6)
            GROUP BY
                RC.AdmissionNumber,
                CUPS.Code
        ) AS G ON G.AdmissionNumber = RC.AdmissionNumber
),
CTE_INGRESO_CON_QX_CARGADAS AS (
    SELECT
        RC.AdmissionNumber,
        G.CANTIDAD
    FROM
        INDIGO036.Billing.RevenueControl AS RC
        INNER JOIN (
            SELECT
                RC.AdmissionNumber,
                SUM(SOD.InvoicedQuantity) CANTIDAD
            FROM
                INDIGO036.Billing.RevenueControl AS RC
                INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS PRO ON RC.AdmissionNumber = PRO.NUMINGRES
                INNER JOIN INDIGO036.Billing.RevenueControlDetail AS RCD ON RC.Id = RCD.RevenueControlId
                INNER JOIN INDIGO036.Billing.ServiceOrderDetailDistribution AS SODD ON RCD.Id = SODD.RevenueControlDetailId
                INNER JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD ON SODD.ServiceOrderDetailId = SOD.Id
                INNER JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON CUPS.Id = SOD.CUPSEntityId
            WHERE
                RCD.Status IN ('1', '2', '3')
                AND CUPS.BillingGroupId IN (5)
            GROUP BY
                RC.AdmissionNumber
        ) AS G ON G.AdmissionNumber = RC.AdmissionNumber
),
CTE_DATOS_PROCEDIMIENTOS_QX AS (
    SELECT
        ING.NUMINGRES,
        A.NUMEFOLIO,
        A.IPCODPACI,
        P.IPNOMCOMP,
        RTRIM(A.CODSERIPS) AS CODSERIPS,
        B.DESSERIPS,
        SUM(1) AS CANSERIPS,
        G.IESTADOIN,
        G.[CANTIDAD ORDENADA],
        HA.Name ENTIDAD,
        CG.Name 'GRUPO ATENCION',
        CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
        G.AMBITO,
        CAST(A.FECHORINI AS DATE) AS [FECHA DEL PROCEDIMIENTO]
    FROM
        INDIGO036.dbo.HCQXINFOR A
        INNER JOIN INDIGO036.dbo.ADINGRESO AS ING ON ING.NUMINGRES = A.NUMINGRES
        INNER JOIN INDIGO036.dbo.INCUPSIPS B ON A.CODSERIPS = B.CODSERIPS
        INNER JOIN INDIGO036.dbo.INPACIENT P on A.IPCODPACI = P.IPCODPACI
        INNER JOIN INDIGO036.dbo.HCQXREALI C ON A.IPCODPACI = C.IPCODPACI
            AND A.NUMINGRES = C.NUMINGRES
            AND A.NUMEFOLIO = C.NUMEFOLIO
        INNER JOIN INDIGO036.Contract.HealthAdministrator AS HA ON ING.GENCONENTITY = HA.Id
        INNER JOIN INDIGO036.Contract.CareGroup AS CG ON ING.GENCAREGROUP = CG.Id
        INNER JOIN (
            SELECT
                ING.NUMINGRES,
                A.IPCODPACI,
                P.IPNOMCOMP,
                RTRIM(A.CODSERIPS) AS CODSERIPS,
                B.DESSERIPS,
                SUM(1) AS 'CANTIDAD ORDENADA',
                UNI.IESTADOIN,
                UNI.AMBITO
            FROM
                INDIGO036.dbo.HCQXINFOR A
                INNER JOIN INDIGO036.dbo.ADINGRESO AS ING ON ING.NUMINGRES = A.NUMINGRES
                INNER JOIN INDIGO036.dbo.INCUPSIPS B ON A.CODSERIPS = B.CODSERIPS
                INNER JOIN INDIGO036.dbo.INPACIENT P on A.IPCODPACI = P.IPCODPACI
                INNER JOIN INDIGO036.dbo.HCQXREALI C ON A.IPCODPACI = C.IPCODPACI
                    AND A.NUMINGRES = C.NUMINGRES
                    AND A.NUMEFOLIO = C.NUMEFOLIO
                INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS UNI ON UNI.NUMINGRES = ING.NUMINGRES
            GROUP BY
                ING.NUMINGRES,
                A.IPCODPACI,
                P.IPNOMCOMP,
                A.CODSERIPS,
                B.DESSERIPS,
                UNI.IESTADOIN,
                UNI.AMBITO
        ) AS G ON G.NUMINGRES = ING.NUMINGRES
            AND G.CODSERIPS = A.CODSERIPS
    WHERE
        A.GENSERVICEORDER IS NULL
        AND ING.IESTADOIN in (' ', 'P')
    GROUP BY
        ING.NUMINGRES,
        A.NUMEFOLIO,
        A.IPCODPACI,
        P.IPNOMCOMP,
        A.CODSERIPS,
        B.DESSERIPS,
        G.IESTADOIN,
        G.[CANTIDAD ORDENADA],
        HA.Name,
        CG.Name,
        ING.IFECHAING,
        G.AMBITO,
        CAST(A.FECHORINI AS DATE)
    UNION ALL
    SELECT
        ING.NUMINGRES,
        A.NUMEFOLIO,
        A.IPCODPACI,
        P.IPNOMCOMP,
        RTRIM(A.CODSERIPS) AS CODSERIPS,
        B.DESSERIPS,
        SUM(1) AS CANSERIPS,
        G.IESTADOIN,
        G.[CANTIDAD ORDENADA],
        HA.Name ENTIDAD,
        CG.Name 'GRUPO ATENCION',
        CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
        G.AMBITO,
        CAST(A.FECHORINI AS DATE) AS [FECHA DEL PROCEDIMIENTO]
    FROM
        INDIGO036.dbo.HCQXINFOR A
        INNER JOIN INDIGO036.dbo.HCINGRESORECNAC INGMH ON A.NUMINGRES = INGMH.NUMINGRESHIJO
        INNER JOIN INDIGO036.dbo.HCRECINAC RN ON INGMH.NUMINGRESHIJO = RN.NUMINGRESHIJO
        INNER JOIN INDIGO036.dbo.ADINGRESO AS ING ON ING.NUMINGRES = INGMH.NUMINGRESHIJO
        INNER JOIN INDIGO036.dbo.HCQXREALI C ON A.IPCODPACI = C.IPCODPACI
            AND A.NUMINGRES = C.NUMINGRES
            AND A.NUMEFOLIO = C.NUMEFOLIO
        INNER JOIN INDIGO036.dbo.INPACIENT P ON P.IPCODPACI = ING.IPCODPACI
        INNER JOIN INDIGO036.dbo.INCUPSIPS B ON A.CODSERIPS = B.CODSERIPS
        INNER JOIN INDIGO036.Contract.HealthAdministrator AS HA ON ING.GENCONENTITY = HA.Id
        INNER JOIN INDIGO036.Contract.CareGroup AS CG ON ING.GENCAREGROUP = CG.Id
        INNER JOIN (
            SELECT
                ING.NUMINGRES,
                A.IPCODPACI,
                P.IPNOMCOMP,
                RTRIM(A.CODSERIPS) AS CODSERIPS,
                B.DESSERIPS,
                SUM(1) AS 'CANTIDAD ORDENADA',
                UNI.IESTADOIN,
                UNI.AMBITO
            FROM
                INDIGO036.dbo.HCQXINFOR A
                INNER JOIN INDIGO036.dbo.HCINGRESORECNAC INGMH ON A.NUMINGRES = INGMH.NUMINGRESHIJO
                INNER JOIN INDIGO036.dbo.HCRECINAC RN ON INGMH.NUMINGRESHIJO = RN.NUMINGRESHIJO
                INNER JOIN INDIGO036.dbo.ADINGRESO AS ING ON ING.NUMINGRES = INGMH.NUMINGRESHIJO
                INNER JOIN INDIGO036.dbo.HCQXREALI C ON A.IPCODPACI = C.IPCODPACI
                    AND A.NUMINGRES = C.NUMINGRES
                    AND A.NUMEFOLIO = C.NUMEFOLIO
                INNER JOIN INDIGO036.dbo.INPACIENT P ON P.IPCODPACI = ING.IPCODPACI
                INNER JOIN INDIGO036.dbo.INCUPSIPS B ON A.CODSERIPS = B.CODSERIPS
                INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS UNI ON UNI.NUMINGRES = ING.NUMINGRES
            GROUP BY
                ING.NUMINGRES,
                A.IPCODPACI,
                P.IPNOMCOMP,
                A.CODSERIPS,
                B.DESSERIPS,
                UNI.IESTADOIN,
                UNI.AMBITO
        ) AS G ON G.NUMINGRES = ING.NUMINGRES
            AND G.CODSERIPS = A.CODSERIPS
    WHERE
        A.GENSERVICEORDER IS NULL
        AND ING.IESTADOIN in (' ', 'P')
    GROUP BY
        ING.NUMINGRES,
        A.NUMEFOLIO,
        A.IPCODPACI,
        P.IPNOMCOMP,
        A.CODSERIPS,
        B.DESSERIPS,
        G.IESTADOIN,
        G.[CANTIDAD ORDENADA],
        HA.Name,
        CG.Name,
        ING.IFECHAING,
        G.AMBITO,
        CAST(A.FECHORINI AS DATE)
)
,
CTE_QX_AMBITO AS (
    SELECT
        DISTINCT ING.NUMINGRES,
        ING.IDRADICACIONQX,
        case
            ING.ORIGENQX
            when 1 THEN 'AMBULATORIA'
            WHEN 2 THEN 'HOSPITALARIA'
            ELSE 'HOSPITALARIA'
        END AMBITO
    FROM
        CTE_PROCEDIMIENTO_QX_UNICOS UNI
        LEFT JOIN INDIGO036.dbo.AGEPROGQX ING ON UNI.NUMINGRES = ING.NUMINGRES
)
,
CTE_PROCEDIMIENTOS_QX AS (
    SELECT
        ING.NUMINGRES,
        ING.NUMEFOLIO,
        ING.IESTADOIN,
        ING.[FECHA INGRESO],
        ISNULL(AMB.AMBITO, 'HOSPITALARIA') 'AMBITO CIRUGIA',
        ING.ENTIDAD,
        ING.[GRUPO ATENCION],
        ING.IPCODPACI,
        ING.IPNOMCOMP,
        ING.CODSERIPS,
        ING.DESSERIPS,
        ING.[FECHA DEL PROCEDIMIENTO],
        ING.[CANTIDAD ORDENADA],
        ING.CANSERIPS,
        CAM.UFUDESCRI,
        CAM.NUMCAMHOS,
        EGR.FECEGRESO,
        CAR.CUPS [CUPS CARGADO],
        CAR.CANTIDAD [CANTIDAD CARGADA]
    FROM
        CTE_DATOS_PROCEDIMIENTOS_QX ING
        LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM ON ING.NUMINGRES = CAM.NUMINGRES
        LEFT JOIN CTE_EGRESO_CAMA EGR ON EGR.NUMINGRES = ING.NUMINGRES
        LEFT JOIN CTE_ORDENES_CON_QX_CARGADAS CAR ON CAR.AdmissionNumber = ING.NUMINGRES
            AND CAR.CUPS = ING.CODSERIPS
        LEFT JOIN CTE_INGRESO_CON_QX_CARGADAS CAR2 ON CAR2.AdmissionNumber = ING.NUMINGRES
        LEFT JOIN CTE_QX_AMBITO AS AMB ON AMB.NUMINGRES = ING.NUMINGRES
    WHERE
        CAR.CUPS IS NULL
        AND CAR2.CANTIDAD IS NULL
)
,
CTE_JUSTIFICACIONES AS (
    SELECT
        DISTINCT QX.NUMINGRES,
        QX.NUMEFOLIO,
        QX.CODSERIPS,
        JUS.Code
    FROM
        INDIGO036.Billing.BillingJustificationControl JUS
        INNER JOIN INDIGO036.Billing.AccountControlJustification CON ON JUS.Id = JustificationId
        INNER JOIN INDIGO036.dbo.HCQXREALI QX ON CON.EntityId = QX.CONSECUQX
            AND CON.EntityName = 'HCQXREALI'
)
SELECT
	'CIRUGIAS' AS [TIPO],
    cast(QX.NUMINGRES as numeric) AS [INGRESO],
    QX.IESTADOIN AS [ESTADO],
    CAST(QX.[FECHA INGRESO] AS date) AS [FECHA INGRESO],
    QX.ENTIDAD,
    QX.[GRUPO ATENCION],
    QX.IPCODPACI AS [IDENTIFICACION],
    QX.IPNOMCOMP AS [NOMBRE],
    QX.CODSERIPS AS [CUPS],
    QX.DESSERIPS AS [DESCRIPCION CUPS],
    QX.[FECHA DEL PROCEDIMIENTO],
    QX.[CANTIDAD ORDENADA],
    QX.CANSERIPS AS [CANTIDAD PENDIENTE DE CARGUE],
    QX.UFUDESCRI AS [UNIDAD FUNCIONAL],
    QX.NUMCAMHOS AS [CAMA],
    QX.FECEGRESO AS [FECHA EGRESO],
    QX.[AMBITO CIRUGIA],
    QX.[CUPS CARGADO],
    QX.[CANTIDAD CARGADA],
    YEAR(QX.[FECHA INGRESO]) AS [AÑO INGRESO],
    month(QX.[FECHA INGRESO]) AS [MES INGRESO],
	JUS.Code
FROM
    CTE_PROCEDIMIENTOS_QX QX
    LEFT JOIN CTE_JUSTIFICACIONES JUS ON QX.NUMINGRES = JUS.NUMINGRES
        AND QX.NUMEFOLIO = JUS.NUMEFOLIO
        AND QX.CODSERIPS = JUS.CODSERIPS
WHERE
    JUS.Code IS NULL