-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_VIEWOPPORTUNITYMEDICALAPPOINTMENTCE
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_VIEWOPPORTUNITYMEDICALAPPOINTMENTCE AS
                
WITH CTE_CONTROL AS (
    SELECT
        A.NUMCONCIT,
        A.NUMINGRES,
        A.IDHCHISPACA
    FROM
        INDIGO036.dbo.ADCONCOEX A
    WHERE
        A.IDHCHISPACA = (
            SELECT
                MAX(B.IDHCHISPACA)
            FROM
                INDIGO036.dbo.ADCONCOEX B
            WHERE
                A.NUMCONCIT = B.NUMCONCIT
        )
        AND A.NUMCONCIT IS NOT NULL
    UNION ALL
    SELECT
        A.IDCITA AS NUMCONCIT,
        A.NUMINGRES,
        HC.ID AS IDHCHISPACA
    FROM
        INDIGO036.dbo.AMBORDOTROSPRO A
        INNER JOIN INDIGO036.dbo.HCHISPACA HC ON A.NUMINGRES = HC.NUMINGRES
            AND HC.NUMEFOLIO = (
                SELECT
                    MAX(H.NUMEFOLIO)
                FROM
                    INDIGO036.dbo.HCHISPACA H
                WHERE
                    A.NUMINGRES = H.NUMINGRES
            )
),
CTE_CONTROL_CE AS (
    SELECT
        DISTINCT *
    FROM
        CTE_CONTROL
)
SELECT
    DISTINCT CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    CASE
        A.TIPSOLICITU
        WHEN 3 THEN 'Tratamientos Especiales'
        WHEN 2 THEN 'Apoyo Diagnostico'
        WHEN 1 THEN 'Cita Medica'
    END [TIPO AGENDAMIENTO],
    RTRIM(C.CODIPSSEC) AS [CODIGO IPS],
    RTRIM(C.NOMCENATE) AS [CENTRO ATENCION],
    RTRIM(ISNULL(UNICE.UFUDESCRI, UNIID.UFUDESCRI)) AS [UNIDAD FUNCIONAL],
    CASE
        RTRIM(ISNULL(UNICE.UFUTIPUNI, UNIID.UFUTIPUNI))
        WHEN 1 THEN 'URGENCIAS'
        WHEN 2 THEN 'HOSPITALIZACION'
        WHEN 3 THEN 'APOYO DIAGNOSTICO'
        WHEN 4 THEN 'APOYO TERAPEUTICO'
        WHEN 5 THEN 'UCI'
        WHEN 6 THEN 'UCI'
        WHEN 7 THEN 'UCI'
        WHEN 8 THEN 'UCI'
        WHEN 9 THEN 'UCI'
        WHEN 10 THEN 'UCI'
        WHEN 11 THEN 'UCI'
        WHEN 12 THEN 'UNIDAD RENAL'
        WHEN 13 THEN 'UNIDAD ONCOLOGICA'
        WHEN 14 THEN 'UNIDAD MEDICINA NUCLEAR'
        WHEN 15 THEN 'AMBULATORIO'
        WHEN 16 THEN 'UNIDAD MENTAL'
        WHEN 17 THEN 'UNIDAD DE QUEMADOS'
        WHEN 18 THEN 'UNIDAD DE CUIDADOS PALATIVOS'
        WHEN 19 THEN 'CIRUGIA'
        WHEN 20 THEN 'LABORATORIOS'
        WHEN 21 THEN 'CARDIOLOGIA NO INVASIVA'
        WHEN 22 THEN 'CARDIOLOGIA INVASIVA'
        WHEN 23 THEN 'GINECO OBSTETRICIA'
        WHEN 24 THEN 'CONSULTA EXTERNA GINOCO OBSTETRICIA'
        WHEN 30 THEN 'OTRAS'
        WHEN 31 THEN 'CONSULTA PRIORITARIA'
        ELSE 'CONSULTA EXTERNA'
    END [AMBITO],
    REPS.[CodigoReps] AS [CODIGO REPS ESPECIALIDAD],
    B.CODESPECI AS [CODIGO ESPECIALIDAD],
    RTRIM(B.DESESPECI) AS ESPECIALIDAD,
    RTRIM(E.CODPROSAL) AS [CODIGO MEDICO],
    RTRIM(E.NOMMEDICO) AS [MEDICO],
    RTRIM(F.DESACTMED) AS 'ACTIVIDAD AGENDAMIENTO',
    CON.DESCRICON AS CONSULTORIO,
    IIF(
        F.DURAACTIV <> 0,
        F.DURAACTIV,
        (
            SELECT
                TOP(1) FD.DURACSERVI
            FROM
                INDIGO036.dbo.AGACTMEDD AS FD
            WHERE
                A.CODACTMED = FD.CODACTMED
                AND FD.CODSERIPS = A.CODSERIPS
        )
    ) + ' ' + 'MINUTOS' 'DURACION ACTIVIDAD',
    CASE
        D.IPTIPODOC
        WHEN '1' THEN 'CC'
        WHEN '2' THEN 'CE'
        WHEN '3' THEN 'TI'
        WHEN '4' THEN 'RC'
        WHEN '5' THEN 'PA'
        WHEN '6' THEN 'AS'
        WHEN '7' THEN 'MS'
        WHEN '8' THEN 'NU'
        WHEN '9' THEN 'NV'
        WHEN '10' THEN 'CD'
        WHEN '11' THEN 'SC'
        WHEN '12' THEN 'PE'
        WHEN '13' THEN 'PT'
        WHEN '14' THEN 'DE'
        WHEN '15' THEN 'SI'
    END AS [TIPO IDENTIFICACION],
    CASE
        D.IPTIPODOC
        WHEN '1' THEN 'CEDULA DE CIUDADANIA'
        WHEN '2' THEN 'CEDULA DE EXTRANJERIA'
        WHEN '3' THEN 'TARJETA DE IDENTIDAD'
        WHEN '4' THEN 'REGISTRO CIVIL'
        WHEN '5' THEN 'PASAPORTE'
        WHEN '6' THEN 'ADULTO SIN IDENTIFICACION'
        WHEN '7' THEN 'MENOR SIN IDENTIFICACION'
        WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACIÒN'
        WHEN '9' THEN 'CERTIFICADO NACIDO VIVO'
        WHEN '10' THEN 'CARNET DIPLOMATICO'
        WHEN '11' THEN 'SALVOCONDUCTO'
        WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA'
        WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA'
        WHEN '14' THEN 'DOCUMENTO EXTRANJERO'
        WHEN '15' THEN 'SIN IDENTIFICACION'
    END AS [DESCRIPCION IDENTIFICACION],
    D.IPCODPACI AS [NRO IDENTIFICACION],
    D.ID AS [ID PACIENTE],
    CAST(D.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
    DATEDIFF(YEAR, D.IPFECNACI, GETDATE()) AS [EDAD],
    CASE
        D.IPSEXOPAC
        WHEN '1' THEN 'H'
        WHEN '2' THEN 'M'
    END AS [CODIGO SEXO],
    CASE
        D.IPSEXOPAC
        WHEN '1' THEN 'HOMBRE'
        WHEN '2' THEN 'MUJER'
    END AS [SEXO],
    RTRIM(D.IPPRIAPEL) AS [PRIMER APELLIDO],
    RTRIM(D.IPSEGAPEL) AS [SEGUNDO APELLIDO],
    RTRIM(D.IPPRINOMB) AS [PRIMER NOMBRE],
    RTRIM(D.IPSEGNOMB) AS [SEGUNDO NOMBRE],
    UPPER(D.CORELEPAC) AS CORREO,
    DEP.depcodigo AS [CODIGO DEPARTAMENTO],
    DEP.nomdepart AS [NOMBRE DEPARTAMENTO RESIDENCIA],
    MUN.MUNCODIGO [CODIGO MUNICIPIO RESIDENCIA],
    MUN.MUNNOMBRE AS [NOMBRE MUNICIPIO RESIDENCIA],
    UPPER(D.IPDIRECCI) AS [DIRECCION],
    D.IPTELMOVI AS CELULAR,
    D.IPTELEFON AS [TELEFONO FIJO],
    CASE
        WHEN A.CODTIPSOL = '0' THEN 'PRESENCIAL'
        WHEN A.CODTIPSOL = '1' THEN 'TELEFONICA'
    END AS [FORMA DE SOLICITUD],
    IIF(
        A.CODTIPCIT IS NOT NULL,
        CASE
            WHEN A.CODTIPCIT = '0' THEN 'PRIMERA VEZ'
            WHEN A.CODTIPCIT = '1' THEN 'CONTROL'
            WHEN A.CODTIPCIT = '2' THEN 'POS OPERATORIO'
            WHEN A.CODTIPCIT = '3' THEN 'CITA WEB'
            ELSE 'N/A'
        END,
        CASE
            WHEN ING1.TIPCITMED = '1' THEN 'PRIMERA VEZ'
            WHEN ING1.TIPCITMED = '2' THEN 'CONTROL'
            ELSE 'N/A'
        END
    ) AS [TIPO DE CITA],
    CASE
        A.MODALIDAD
        WHEN 0 THEN 'PRESENCIAL'
        WHEN 1 THEN 'TELECONSULTA'
        ELSE 'N/A'
    END AS [MODALIDAD],
    CASE
        WHEN HEA.Id IS NOT NULL THEN RTRIM(HEA.HealthEntityCode)
        ELSE RTRIM(ENT.CODENTIDA)
    END AS [CODIGO ENTIDAD],
    CASE
        WHEN HEA.Id IS NOT NULL THEN RTRIM(HEA.Name)
        ELSE RTRIM(ENT.NOMENTIDA)
    END AS [ENTIDAD],
    CASE
        D.IPTIPOPAC
        WHEN 1 THEN 'Contributivo'
        WHEN 2 THEN 'Subsidiado'
        WHEN 3 THEN 'Vinculado'
        WHEN 4 THEN 'Particular'
        WHEN 5 THEN 'Otro'
        WHEN 6 THEN 'Desplazado Reg. Contributivo'
        WHEN 7 THEN 'Desplazado Reg. Subsidiado'
        WHEN 8 THEN 'Desplazado No Asegurado'
    END AS [REGIMEN],
    CG.Name AS [GRUPO ATENCION],
    A.CODAUTONU AS [ID AGENDA],
    CONVERT(VARCHAR, CAST(A.FECITADES AS DATE), 23) AS [FECHA DESEADA DE CITA],
    CONVERT(VARCHAR, CAST(A.FECHAOFERTADA AS DATE), 23) AS [MEJOR CITA DISPONIBLE],
    CONVERT(VARCHAR, CAST(FECHORAIN AS DATE), 23) AS [FECHA ASIGNACION DE CITA],
    CONVERT(VARCHAR, CAST(FECHORAIN AS DATETIME), 20) AS [FECHA HORA ASIGNACION DE CITA],
    CONVERT(VARCHAR, CAST(FECHORAFI AS DATE), 23) AS [FECHA FINAL ASIGNACION DE CITA],
    CONVERT(VARCHAR, CAST(FECHORAFI AS DATETIME), 20) AS [FECHA HORA FINAL ASIGNACION DE CITA],
    CONVERT(VARCHAR, CAST(A.FECREGSIS AS DATE), 23) AS [FECHA SOLICITUD DE CITA],
    IIF(
        A.CODESTCIT = '4'
        OR A.CODESTCIT = '5',
        IIF(
            DIA.CODDIAGNO IS NULL,
            CONVERT(VARCHAR, CAST(A.FECHCANCELA AS DATETIME), 20),
            ''
        ),
        ''
    ) AS [FECHA CANCELACION DE CITA],
    CONVERT(VARCHAR, CAST(A.FECREGSIS AS DATETIME), 23) AS [FECHA REGISTRO EN BASE DE DATOS],
    DATEDIFF(DAY, A.FECREGSIS, FECHORAIN) AS [FECHA ASIGNACION vs FECHA SOLICITUD],
    DATEDIFF(DAY, A.FECITADES, FECHORAIN) AS [FECHA ASIGNACION vs FECHA DESEADA],
    DATEDIFF(DAY, A.FECREGSIS, A.FECHAOFERTADA) AS [DISPONIBILIDAD DE AGENDA],
    CASE
        WHEN A.CITAEXTRA = 1 THEN 'Si'
        ELSE 'No'
    END AS [CITA EXTRA],
    ISNULL(
        RTRIM(M.CODSERIPS),
        ISNULL(
            RTRIM(CE.Code),
            ISNULL(RTRIM(O.CODSERIPS), RTRIM(IPS3.CODSERIPS))
        )
    ) AS [CODIGO CUPS],
    ISNULL(
        RTRIM(M.DESSERIPS),
        ISNULL(
            RTRIM(CD.Name),
            ISNULL(RTRIM(IPS2.DESSERIPS), RTRIM(IPS3.DESSERIPS))
        )
    ) AS [DESCRIPCION CUPS],
    RTRIM(G.NOMUSUARI) AS [USUARIO QUE REGISTRO LA CITA],
    'ASIGNADA' AS [ESTADO INICIAL],
    CASE
        A.CODESTCIT
        WHEN 1 THEN 'CUMPLIDA'
        WHEN 2 THEN 'INCUMPLIDA'
        WHEN 3 THEN 'PREASIGNADA'
        WHEN 4 THEN 'CANCELADA'
        WHEN 5 THEN 'INATENCION'
    END AS [ESTADO ACTUAL],
    A.CODCAUCAN AS [CODIGO CANCELACION],
    CAN.DESCAUCAN AS [DESCRIPCION CANCELACION],
    A.NUMAUTORI AS [NUMERO AUTORIZACION],
    ING.NUMINGRES AS [INGRESO DE ATENCION],
    DIA.CODDIAGNO AS [CODIGO DEL DIAGNOSTICO],
    DIA.NOMDIAGNO AS [DIAGNOSTICO],
    1 as 'CANTIDAD',
    CAST(FECHORAIN AS date) AS 'FECHA BUSQUEDA',
    YEAR(FECHORAIN) AS 'AÑO BUSQUEDA',
    MONTH(FECHORAIN) AS 'MES BUSQUEDA',
    CONCAT(
        FORMAT(MONTH(FECHORAIN), '00'),
        ' - ',
        CASE
            MONTH(FECHORAIN)
            WHEN 1 THEN 'ENERO'
            WHEN 2 THEN 'FEBRERO'
            WHEN 3 THEN 'MARZO'
            WHEN 4 THEN 'ABRIL'
            WHEN 5 THEN 'MAYO'
            WHEN 6 THEN 'JUNIO'
            WHEN 7 THEN 'JULIO'
            WHEN 8 THEN 'AGOSTO'
            WHEN 9 THEN 'SEPTIEMBRE'
            WHEN 10 THEN 'OCTUBRE'
            WHEN 11 THEN 'NOVIEMBRE'
            WHEN 12 THEN 'DICIEMBRE'
        END
    ) 'MES NOMBRE BUSQUEDA',
    CONVERT(
        DATETIME,
        GETDATE() AT TIME ZONE 'Pakistan Standard Time',
        1
    ) AS ULT_ACTUAL
FROM
    INDIGO036.dbo.AGASICITA A
    INNER JOIN INDIGO036.dbo.ADCENATEN AS C ON A.CODCENATE = C.CODCENATE
    INNER JOIN INDIGO036.dbo.INPACIENT AS D ON A.IPCODPACI = D.IPCODPACI
    LEFT JOIN INDIGO036.dbo.AGCONSULT AS AGC ON A.CODIGOCON = AGC.CODIGOCON
        AND C.CODCENATE = AGC.CODCENATE
    LEFT JOIN INDIGO036.dbo.INUNIFUNC AS UNICE ON AGC.UFUCODIGO = UNICE.UFUCODIGO
    LEFT JOIN INDIGO036.dbo.AGENSALAACT AS AGAC ON A.IDSALA = AGAC.CODCONCEC
        AND A.CODACTMED = AGAC.CODACTMED
    LEFT JOIN INDIGO036.dbo.AGENSALAC AS AGS ON AGAC.CODCONCEC = AGS.CODCONCEC
    LEFT JOIN INDIGO036.dbo.INUNIFUNC AS UNIID ON AGS.UFUCODIGO = UNIID.UFUCODIGO
    LEFT JOIN INDIGO036.dbo.INESPECIA AS B ON A.CODESPECI = B.CODESPECI
    LEFT JOIN INDIGO036.dbo.AGACTIMED AS F ON A.CODACTMED = F.CODACTMED
    LEFT JOIN INDIGO036.dbo.INPROFSAL AS E ON A.CODPROSAL = E.CODPROSAL
    LEFT JOIN INDIGO036.dbo.INUBICACI AS UBI ON D.AUUBICACI = UBI.AUUBICACI
    LEFT JOIN INDIGO036.dbo.INMUNICIP AS MUN ON UBI.DEPMUNCOD = MUN.DEPMUNCOD
    LEFT JOIN INDIGO036.dbo.INDEPARTA AS DEP ON DEP.depcodigo = MUN.DEPCODIGO
    LEFT JOIN INDIGO036.dbo.INENTIDAD AS ENT ON D.CODENTIDA = ENT.CODENTIDA
    LEFT JOIN INDIGO036.Contract.HealthAdministrator AS HEA ON A.GENCONENTITY = HEA.Id
    LEFT JOIN INDIGO036.dbo.SEGusuaru AS G ON A.CODUSUASI = G.CODUSUARI
    LEFT JOIN INDIGO036.dbo.INCUPSIPS AS M ON A.CODSERIPS = M.CODSERIPS
    LEFT JOIN INDIGO036.Contract.CareGroup AS CG ON A.GENCAREGROUP = CG.Id
    LEFT JOIN INDIGO036.Contract.CUPSEntityContractDescriptions AS CECD ON CECD.Id = A.IDDESCRIPCIONRELACIONADA
    LEFT JOIN INDIGO036.Contract.CUPSEntity AS CE ON CE.Id = CECD.CUPSEntityId
    LEFT JOIN INDIGO036.Contract.ContractDescriptions AS CD ON CD.Id = CECD.ContractDescriptionId
    LEFT JOIN INDIGO036.dbo.AGCAUCANC AS CAN ON A.CODCAUCAN = CAN.CODCAUCAN
    LEFT JOIN CTE_CONTROL_CE AS GC ON A.CODAUTONU = GC.NUMCONCIT
    LEFT JOIN INDIGO036.dbo.RIASCUPS AS O ON A.IDRIASCUPS = O.ID
    LEFT JOIN INDIGO036.dbo.RIAS AS Q ON O.IDRIAS = Q.ID
    LEFT JOIN INDIGO036.dbo.INCUPSIPS AS IPS2 ON O.CODSERIPS = IPS2.CODSERIPS
    LEFT JOIN INDIGO036.dbo.INCUPSIPS AS IPS3 ON F.CODSERIPS = IPS3.CODSERIPS
    LEFT JOIN INDIGO036.dbo.ADINGRESO AS ING ON ISNULL(GC.NUMINGRES, A.NUMINGRES) = ING.NUMINGRES
    LEFT JOIN INDIGO036.dbo.HCHISPACA AS HIS ON GC.IDHCHISPACA = HIS.ID
    LEFT JOIN INDIGO036.dbo.INDIAGNOS AS DIA ON ISNULL(ING.CODDIAING, HIS.CODDIAGNO) = DIA.CODDIAGNO
    LEFT JOIN INDIGO036.dbo.HCURGING1 AS ING1 ON HIS.NUMINGRES = ING1.NUMINGRES
        AND HIS.NUMEFOLIO = ING1.NUMEFOLIO
    LEFT JOIN INDIGO036.dbo.AGCONSULT CON ON A.CODIGOCON = CON.CODIGOCON
        AND A.CODCENATE = CON.CODCENATE
    LEFT JOIN INDIGO036.Report.TablaEspecialidadesReps AS REPS ON B.CODESPECI = REPS.CodigoEspecialidad
;