-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_VIEWADMINISTRATIVENOTES
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_VIEWADMINISTRATIVENOTES
AS

SELECT
    NAD.ID AS [ID NOTAS],
    NAD.NOMBRE AS [NOMBRE NOTA],
    NTAC.FECHACREACION AS [FECHA REGISTRO],
    NTAC.IPCODPACI AS [IDENTIFICACION],
    PAC.IPNOMCOMP AS [PACIENTE],
    NTAC.NUMINGRES AS [INGRESO],
    CASE
        NTAC.NOTANOFACTURABLE
        WHEN 1 THEN 'SI'
        ELSE 'NO'
    END AS [NOTA FACTURABLE],
    GRU.NOMBRE AS [GRUPO],
    ESL.ID AS [ID VARIABLE],
    ESL.VARIABLE,
    NTAD.VALOR,
    VAL.DESCRIPCION
FROM
    [INDIGO036].[dbo].[NTADMINISTRATIVAS] NAD
    INNER JOIN [INDIGO036].[dbo].[NTNOTASADMINISTRATIVASC] NTAC ON NAD.ID = NTAC.IDNOTAADMINISTRATIVA
    INNER JOIN [INDIGO036].[dbo].[NTNOTASADMINISTRATIVASD] NTAD ON NTAC.ID = NTAD.IDNTNOTASADMINISTRATIVASC
    INNER JOIN [INDIGO036].[dbo].[INPACIENT] PAC ON NTAC.IPCODPACI = PAC.IPCODPACI
    INNER JOIN [INDIGO036].[dbo].[NTVARIABLES] ESL ON NTAD.IDNTVARIABLE = ESL.ID
    INNER JOIN [INDIGO036].[dbo].[NTGRUPOS] GRU ON NTAD.IDGRUPO = GRU.ID
    LEFT JOIN [INDIGO036].[dbo].[NTVARIABLESL] VAL ON ESL.ID = VAL.IDNTVARIABLE
        AND NTAD.VALOR = VAL.CODIGO
