-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: VW_VIEWESTRUCTURAINTERCONSULTAS
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE   VIEW [Report].[VW_VIEWESTRUCTURAINTERCONSULTAS] AS

SELECT CASE I.IPTIPODOC WHEN '1' THEN 'CC'	WHEN '2' THEN 'CE'	WHEN '3' THEN 'TI'	WHEN '4' THEN 'RC'
						WHEN '5' THEN 'PA'	WHEN '6' THEN 'AS'	WHEN '7' THEN 'MS'	WHEN '8' THEN 'NU'
						WHEN '9' THEN 'NV'	WHEN '10' THEN 'CD'	WHEN '11' THEN 'SC'	WHEN '12' THEN 'PE' 
						WHEN '13' THEN 'PT'	WHEN '14' THEN 'DE'	WHEN '15' THEN 'SI' END AS TIPO_DOCU
			,A.IPCODPACI DOCUMENTO
			,I.IPNOMCOMP NOMBRE_PACIENTE
			,CAST (I.IPFECNACI AS DATE) AS FEC_NACIMIENTO
			,cast((datediff(m, I.IPFECNACI, A.FECORDMED)/12) as varchar) + ' Años ' + cast((DATEDIFF(m, I.IPFECNACI, GETDATE())%12) as varchar) + ' Meses' as EDAD
			,CASE WHEN datediff(m, I.IPFECNACI, A.FECORDMED)/12 <=14 THEN 'INFANCIA'
				  WHEN datediff(m, I.IPFECNACI, A.FECORDMED)/12 >=15 AND datediff(m, I.IPFECNACI, A.FECORDMED)/12 <=26 THEN 'JUVENTUD' 
				  WHEN datediff(m, I.IPFECNACI, A.FECORDMED)/12 >=27 AND datediff(m, I.IPFECNACI, A.FECORDMED)/12 <=59 THEN 'ADULTEZ'
  				  WHEN datediff(m, I.IPFECNACI, A.FECORDMED)/12 >=60 THEN 'MAYOTRES'END AS GRUPO_ETAREO
			,CASE I.IPSEXOPAC WHEN '1' THEN 'MASCULINO' ELSE 'FEMENINO' END AS [SEXO]
			,EA.Code AS COD_CONTRATO
			,EA.Name AS CONTRATO
			,A.NUMINGRES INGRESO
			,NUMEFOLIO FOLIO
			,ING.CODDIAING AS COD_DXPPAL
			,DIG.NOMDIAGNO AS DXPPAL
			,CASE WHEN SUBSTRING(A.UFUCODIGO,1,4)='1111' THEN 'URGENCIAS'
			WHEN SUBSTRING(A.UFUCODIGO,1,4)='1112' THEN 'CONSULTA EXTERNA'
			WHEN SUBSTRING(A.UFUCODIGO,1,4)='1113' THEN 'HOSPITALIZACION'
			WHEN SUBSTRING(A.UFUCODIGO,1,4)='1114' THEN 'QUIROFANOS'
			WHEN SUBSTRING(A.UFUCODIGO,1,4)='1115' THEN 'APOYO DIAGNOSTICO'
			WHEN SUBSTRING(A.UFUCODIGO,1,4)='1116' THEN 'APOYO TERAPEUTICO' END AS AMBITO
			,A.UFUCODIGO AS COD_PABELLON
			,UFU.UFUDESCRI AS PABELLON
			,ING.CODICAMHO AS CAMA
			,'' AS COD_AGRDX
			,'' AS DX_AGRUP
			,CAST(A.FECORDMED AS DATE) AS F_SOLICITUD
			,CASE MONTH(A.FECORDMED) WHEN 1 THEN 'ENERO'  WHEN 2 THEN 'FEBRERO'  WHEN 3 THEN 'MARZO'
									 WHEN 4 THEN 'ABRIL'  WHEN 5 THEN 'MAYO'     WHEN 6 THEN 'JUNIO'  
									 WHEN 7 THEN 'JULIO'  WHEN 8 THEN 'AGOSTO'   WHEN 9 THEN 'SEPTIEMBRE'
									 WHEN 10 THEN 'OCTUBRE'  WHEN 11 THEN 'NOVIEMBRE'  WHEN 12 THEN 'DICIEMBRE' END AS MES_SOLICITUD
			,CASE MONTH(A.FECORDMED) WHEN 1 THEN 'ENE'  WHEN 2 THEN 'FEB' WHEN 3 THEN 'MAR'  WHEN 4 THEN 'ABR'
									 WHEN 5 THEN 'MAY'	WHEN 6 THEN 'JUN' WHEN 7 THEN 'JUL'  WHEN 8 THEN 'AGO'
									 WHEN 9 THEN 'SEP'  WHEN 10 THEN 'OCT'  WHEN 11 THEN 'NOV'  WHEN 12 THEN 'DIC' END AS MES_SOLICITUD_SHORT
			,CAST(A.FECORDMED AS TIME) AS HORA_SOLICITUD
			,CASE WHEN datepart(HOUR,A.FECORDMED)>='00' and  datepart(HOUR,A.FECORDMED)<='08' THEN 'MAÑANA' 
				  WHEN datepart(HOUR,A.FECORDMED)>='09' and  datepart(HOUR,A.FECORDMED)<='16' THEN 'TARDE' 
				  WHEN datepart(HOUR,A.FECORDMED)>='17' and  datepart(HOUR,A.FECORDMED)<='23' THEN 'NOCHE' END AS TURNO_SOLICITUD
		    ,CASE WHEN datepart(HOUR,A.FECORDMED)>='00' and  datepart(HOUR,A.FECORDMED)<='08' THEN '1' 
				  WHEN datepart(HOUR,A.FECORDMED)>='09' and  datepart(HOUR,A.FECORDMED)<='16' THEN '2' 
				  WHEN datepart(HOUR,A.FECORDMED)>='17' and  datepart(HOUR,A.FECORDMED)<='23' THEN '3' END AS ID_TURNO_SOLICITUD
			,CAST(A.FECHAINT AS DATE) AS FECHA_RESPUESTA
			,CASE MONTH(A.FECHAINT)  WHEN 1 THEN 'ENERO'  WHEN 2 THEN 'FEBRERO'  WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL'
									 WHEN 5 THEN 'MAYO'	  WHEN 6 THEN 'JUNIO'    WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO'
									 WHEN 9 THEN 'SEPTIEMBRE'  WHEN 10 THEN 'OCTUBRE'  WHEN 11 THEN 'NOVIEMBRE'	  WHEN 12 THEN 'DICIEMBRE' END AS MES_RESPUESTA
			,CASE MONTH(A.FECHAINT)  WHEN 1 THEN 'ENE'  WHEN 2 THEN 'FEB'  WHEN 3 THEN 'MAR'  WHEN 4 THEN 'ABR'
									 WHEN 5 THEN 'MAY'  WHEN 6 THEN 'JUN'  WHEN 7 THEN 'JUL'  WHEN 8 THEN 'AGO'
									 WHEN 9 THEN 'SEP'  WHEN 10 THEN 'OCT'  WHEN 11 THEN 'NOV'  WHEN 12 THEN 'DIC' END AS MES_RESPUESTA_SHORT
			,CAST(A.FECHAINT AS TIME) AS HORA_RESPUESTA
			,CASE WHEN datepart(HOUR,A.FECHAINT)>='00' and  datepart(HOUR,A.FECHAINT)<='08' THEN 'MAÑANA' 
			 	  WHEN datepart(HOUR,A.FECHAINT)>='09' and  datepart(HOUR,A.FECHAINT)<='16' THEN 'TARDE' 
				  WHEN datepart(HOUR,A.FECHAINT)>='17' and  datepart(HOUR,A.FECHAINT)<='23' THEN 'NOCHE' END AS TURNO_RESPUESTA
		    ,CASE WHEN datepart(HOUR,A.FECHAINT)>='00' and  datepart(HOUR,A.FECHAINT)<='08' THEN '1' 
			      WHEN datepart(HOUR,A.FECHAINT)>='09' and  datepart(HOUR,A.FECHAINT)<='16' THEN '2' 
				  WHEN datepart(HOUR,A.FECHAINT)>='17' and  datepart(HOUR,A.FECHAINT)<='23' THEN '3' END AS ID_TURNO_RESPUESTA
			,PRO.CODPROSAL AS COD_ESPECIALISTA_SOLICITA
			,PRO.NOMMEDICO AS ESPECIALISTA_SOLICITA
			,PRO.CODESPEC1 AS COD_ESPECIALIDAD_SOLICITA
			,ESPORD.DESESPECI AS ESPECIALIDAD_SOLICITA
			,CASE WHEN A.ESTSERIPS = '1' THEN 'SOLICITADO'
				  WHEN A.ESTSERIPS = '2' THEN 'SOLICITUD ENVIDA'
				  WHEN A.ESTSERIPS = '3' THEN 'INTERCONSULTA REALIZADA'
				  WHEN A.ESTSERIPS = '4' THEN 'SOLICITADO EXTRAMURAL'
				  WHEN A.ESTSERIPS = '5'THEN 'ANULADO'END AS ESTADO
			,A.CODPROINT AS CED_ESPECIALISTA_RESP
			,PRORES.NOMMEDICO AS ESPECIALISTA_RESP
			,ESPERES.DESESPECI AS ESPECIALIDAD_RES
			,ING.IAUTORIZA as AUTORIZACION
			,DATEDIFF(DAY,A.FECORDMED,A.FECHAINT)AS OPORTUNIDAD_DIAS
			,TRI.TRIACAUIN AS COD_CAUSA_EXT
			,CASE TRI.TRIACAUIN WHEN 1 THEN 'Heridos en combate' 
							   WHEN 2 THEN 'Enfermedad profesional' 
							   WHEN 3 THEN 'Enfermedad general adulto' 
							   WHEN 4 THEN 'Enfermedad general pediatria'
							   WHEN 5 THEN 'Odontología' 
							   WHEN 6 THEN 'Accidente de transito' 
							   WHEN 7 THEN 'Catastrofe/Fisalud'
							   WHEN 8 THEN 'Quemados' 
							   WHEN 9 THEN 'Maternidad' 
							   WHEN 10 THEN 'Accidente Laboral' END AS CAUSA_EXT
			,CASE A.PRISERIPS WHEN 1 THEN 'Urgente' ELSE 'Rutina' END AS [PRIORIDAD DEL SERVICIO]
			,CASE A.MANEXTPRO WHEN 1 THEN 'SI' ELSE 'NO' END AS ORDEN_AMBUL
			,ING.FECHEGRESO AS EGRESO
			,CASE WHEN ING.FECHEGRESO IS NULL THEN 'NO'ELSE 'SI' END AS P_EGRESO	
			,'1' AS CANT
			,GETDATE() AS FECHA_EJECUCION
FROM INDIGO036.dbo.HCORDINTE AS A 
LEFT JOIN INDIGO036.dbo.INPACIENT I  ON A.IPCODPACI = I.IPCODPACI
LEFT JOIN INDIGO036.dbo.INUNIFUNC D  ON A.UFUCODIGO = D.UFUCODIGO
LEFT JOIN INDIGO036.dbo.INPROFSAL PRO  ON A.CODPROSAL = PRO.CODPROSAL
LEFT JOIN INDIGO036.dbo.INESPECIA ESPORD ON PRO.CODESPEC1=ESPORD.CODESPECI
LEFT JOIN INDIGO036.dbo.INESPECIA ESPERES ON A.CODESPECI=ESPERES.CODESPECI
LEFT JOIN INDIGO036.dbo.INPROFSAL PRORES ON A.CODPROINT=PRORES.CODPROSAL
LEFT JOIN INDIGO036.dbo.ADINGRESO ING ON A.NUMINGRES=ING.NUMINGRES AND A.IPCODPACI=ING.IPCODPACI
LEFT JOIN INDIGO036.dbo.ADTRIAGEU TRI ON ING.NUMINGRES=TRI.NUMINGRES
LEFT JOIN INDIGO036.dbo.INUNIFUNC UFU ON A.UFUCODIGO=UFU.UFUCODIGO 
LEFT JOIN INDIGO036.Contract.HealthAdministrator AS EA  ON EA.Id = ING.GENCONENTITY 
LEFT JOIN INDIGO036.dbo.INDIAGNOS DIG ON ING.CODDIAING=DIG.CODDIAGNO
