-- Workspace: HOMI
-- Item: DataWareHouse_Finance [Warehouse]
-- ItemId: ca48608f-987a-48d9-8238-40a4987d89e5
-- Schema: Report
-- Object: VW_VIEWESTADISTICOINGRESOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_VIEWESTADISTICOINGRESOS AS
---------********* SCRIPS PARA MOSTRAR EL ESTADISTICO DE INGRESO INDEPENDIENTE DE SU ESTADO SE UTILIZA UN FILTRO DE FECHA INICIAL Y FINAL*********---------
--DECLARE	@FechaInicio Datetime ='2022-04-30';
--DECLARE	@FechaFin Datetime ='2022-05-05';

WITH CTE_INGRESOS_ABIERTOS
AS
(
SELECT 
ING.NUMINGRES 'INGRESO' ,ING.IPCODPACI 'IDENTIFICACION',
CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO' ,CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' ELSE 'HOSPITALARIO' END 'TIPO INGRESO',
ING.IAUTORIZA ,ING.UFUINGMED ,ING.UFUEGRMED ,ING.UFUINGHOS ,
ING.UFUEGRHOS ,ING.CODPROING ,ING.CODPROEGR ,ING.CODESPTRA ,
ING.UFUAACTMED ,ING.UFUAACTHOS ,ING.CODCAMACT ,ING.CODDIAING ,ING.CODDIAEGR ,ING.UFUACTPAC ,ING.CODICAMHO ,ING.FECHOSPIT ,ING.GENCONENTITY ,ING.GENCAREGROUP ,
ING.FECHEGRESO 'FECHA EGRESO CAMA',
CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO' 
				   WHEN 'F' THEN 'FACTURADO'
				   WHEN 'A' THEN 'ANULADO' 
				   WHEN 'C' THEN 'CERRADO' 
				   WHEN 'P' THEN 'FACTURADO PARCIAL' ELSE 'DESCONOCIDO' END AS 'ESTADO INGRESO' ,
ING.UFUCODIGO, CEN.NOMCENATE 'CENTRO ATENCION',
USU.NOMUSUARI 'USUARIO CREO', USUM.NOMUSUARI 'USUARIO ANULO'
FROM 
[INDIGO036].[dbo].[ADINGRESO] ING  INNER JOIN 
[INDIGO036].[dbo].[ADCENATEN] AS CEN ON CEN.CODCENATE =ING.CODCENATE LEFT JOIN 
[INDIGO036].[dbo].[SEGusuaru] AS USU ON USU.CODUSUARI =ING.CODUSUCRE LEFT JOIN 
[INDIGO036].[dbo].[SEGusuaru] AS USUM ON USUM.CODUSUARI =ING.CODUSUANU 
--WHERE  CAST(ING.IFECHAING AS DATE) BETWEEN  @FechaInicio AND @FechaFin
 ),

 CTE_CARGOS_INGRESOS
AS
(
SELECT 
AdmissionNumber 'INGRESO',SUM(RCD.TotalFolio) 'TOTAL FOLIO'  
FROM INDIGO036.Billing.RevenueControl RC  INNER JOIN 
CTE_INGRESOS_ABIERTOS AS ING  ON RC.AdmissionNumber =ING.INGRESO INNER JOIN 
INDIGO036.Billing.RevenueControlDetail AS RCD  ON RC.Id =RCD.RevenueControlId AND RCD.Status NOT IN (2,4) GROUP BY AdmissionNumber
),

CTE_ALTA_MEDICA
AS
(
SELECT EGR.NUMINGRES 'INGRESO',EGR.IPCODPACI 'IDENTIFICACION' ,EGR.FECALTPAC 'FECHA ALTA MEDICA' 
FROM [INDIGO036].[dbo].[HCREGEGRE] EGR
INNER JOIN CTE_INGRESOS_ABIERTOS AS ING  ON EGR.NUMINGRES =ING.INGRESO 
),
CTE_UBICACION AS
(
select 
UBI.AUUBICACI, DEP.DEPMUNCOD AS CODIGOMUNI,DEP.MUNNOMBRE AS NOMMUNI,DEPA.depcodigo AS CODDEP,DEPA.nomdepart AS NOMDEP
from [INDIGO036].[dbo].[INUBICACI] UBI INNER JOIN
[INDIGO036].[dbo].[INMUNICIP] DEP ON UBI.DEPMUNCOD=DEP.DEPMUNCOD INNER JOIN 
[INDIGO036].[dbo].[INDEPARTA] DEPA ON DEP.DEPCODIGO=DEPA.depcodigo
)

SELECT 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
ING.[CENTRO ATENCION] ,ING.INGRESO,
ING.[FECHA INGRESO],ING.[ESTADO INGRESO] 'ESTADO INGRESO',ING.[TIPO INGRESO],
CASE PAC.IPTIPOPAC 
  WHEN 1 THEN 'CONTRIBUTIVO' 
  WHEN 2 THEN 'SUBSIDIADO' 
  WHEN 3 THEN 'VINCULADO' 
  WHEN 4 THEN 'PARTICULAR' 
  WHEN 5 THEN 'OTRO' 
  WHEN 6 THEN 'DESPLAZADO REG. CONTRIBUTIVO' 	 
  WHEN 7 THEN 'DESPLAZADO REG. SUBSIDIADO' 
  ELSE 'DESPLAZADO NO ASEGURADO'
 END AS 'RÉGIMEN',CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' WHEN '2' THEN 'CEDULA DE EXTRANJERIA' WHEN '3' THEN 'TARJETA DE IDENTIDAD' WHEN '4' THEN 'REGISTRO CIVIL' 
	 WHEN '5' THEN 'PASAPORTE' WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' WHEN '7' THEN 'MENOR SIN IDENTIFICACION' WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION' 
	 WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO'WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
	 WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION' END AS 'TIPO IDENTIFICACION',
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END AS 'SEXO',
CAST(PAC.IPFECNACI AS DATE) 'FECHA NACIMIENTO' ,FLOOR((CAST(CONVERT(VARCHAR(8), ING.[FECHA INGRESO]  , 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS 'EDAD',
rtrim(PAC.IPDIRECCI) AS DIRECCION, PAC.IPTELEFON AS TELEFONO, PAC.IPTELMOVI AS MOVIL,ING.IDENTIFICACION ,
rtrim(PAC.IPNOMCOMP) 'PACIENTE',
UBI.CODIGOMUNI AS [CODIGO MUNICIPIO],
UBI.NOMMUNI AS [MUNICIPIO],
UBI.CODDEP AS [CODIGO DEPARTAMENTO],
UBI.NOMDEP AS [DEPARTAMENTO],
UNI.UFUCODIGO 'COD U FUNCIONAL',
rtrim(UNI.UFUDESCRI) 'UNIDAD FUNCIONAL',
ALT.[FECHA ALTA MEDICA],
ING.[FECHA EGRESO CAMA],
CAM.DESCCAMAS 'CAMA',
CASE WHEN CAM.DESCCAMAS IS NULL THEN 'NO' ELSE 'SI' END CON_CAMA_ACTIVA,
EA.Code 'CODIGO ENTIDAD' ,EA.Name 'ENTIDAD',
GA.Code 'CODIGO GRUPO ATENCION' ,GA.Name AS 'GRUPO DE ATENCION',
CASE PAC.NIVECODIGO WHEN '01' THEN 'RANGO A'
					WHEN '02' THEN 'RANGO B'
					WHEN '03' THEN 'RANGO C'
					WHEN '04' THEN 'OTROS' END AS RANGOS,
ISNULL(VAL.[TOTAL FOLIO],'0') [TOTAL FOLIO],
ING.[USUARIO CREO] ,ING.[USUARIO ANULO] ,CIE10 .CODDIAGNO 'CIE10', CIE10.NOMDIAGNO 'DIAGNOSTICO',
1 as 'CANTIDAD',
CAST([FECHA INGRESO] AS date) AS 'FECHA BUSQUEDA',
YEAR([FECHA INGRESO]) AS 'AÑO FECHA BUSQUEDA',
MONTH([FECHA INGRESO]) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH([FECHA INGRESO]) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
  END AS 'MES NOMBRE FECHA BUSQUEDA', 
FORMAT(DAY([FECHA INGRESO]), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH([FECHA INGRESO]), '00') ,' - ', 
	   CASE MONTH([FECHA INGRESO]) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM CTE_INGRESOS_ABIERTOS AS ING 
INNER JOIN INDIGO036.Contract.CareGroup AS GA  ON GA.Id = ING.GENCAREGROUP
INNER JOIN INDIGO036.Contract.HealthAdministrator AS EA  ON EA.Id = ING.GENCONENTITY
INNER JOIN [INDIGO036].[dbo].[INPACIENT] AS PAC  ON PAC.IPCODPACI = ING.IDENTIFICACION 
INNER JOIN CTE_UBICACION AS UBI ON PAC.AUUBICACI=UBI.AUUBICACI
INNER JOIN [INDIGO036].[dbo].[INUNIFUNC] AS UNI  ON UNI.UFUCODIGO = ISNULL(ING.UFUACTPAC ,ING.UFUCODIGO) 
LEFT JOIN CTE_ALTA_MEDICA AS ALT  ON ALT.INGRESO  =ING.INGRESO 
LEFT JOIN [INDIGO036].[dbo].[CHCAMASHO] AS CAM ON CAM.CODICAMAS  =ING.CODCAMACT 
LEFT JOIN CTE_CARGOS_INGRESOS AS VAL ON VAL.INGRESO =ING.INGRESO 
LEFT JOIN [INDIGO036].[dbo].[INDIAGNOS] AS CIE10  ON CIE10.CODDIAGNO = ISNULL(ING.CODDIAEGR,ING.CODDIAING)
