-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: dbo
-- Object: View_Ubicación_Pacientes_UF
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [dbo].[View_Ubicación_Pacientes_UF]
AS

WITH CTE_URGENCIAS
AS
(
SELECT URG.IPCODPACI, URG.IPFECLLEGA, URG.CONESTADO, URG.IPNOMCOMP, URG.UFUCODIGO, TRI.TRIAFECHA, TRI.TRIFECCON, TRI.TRIESTADO, ING.FECINIATE
FROM ADCONTURG URG
LEFT JOIN ADTRIAGEU TRI ON TRI.IPCODPACI=URG.IPCODPACI AND TRI.TRIAFECHA>URG.IPFECLLEGA
LEFT JOIN HCURGING1 ING ON ING.NUMINGRES=TRI.NUMINGRES

WHERE URG.UFUCODIGO IN (1005) AND CONESTADO IN (1,3,4,5) AND URG.IPFECLLEGA BETWEEN DATEADD(DAY,-1,GETDATE()) AND GETDATE()

),


CTE_QUIRURGICOS
AS
(
SELECT DISTINCT EST.CODICAMAS,FECINIEST,FECFINEST, EST.NUMINGRES, EST.IPCODPACI, PAC.IPNOMCOMP,CAM.UFUCODIGO, CAM.NUMCAMHOS 
FROM CHREGESTA EST
INNER JOIN CHCAMASHO CAM ON CAM.CODICAMAS=EST.CODICAMAS
INNER JOIN INPACIENT PAC ON PAC.IPCODPACI=EST.IPCODPACI

WHERE CAM.UFUCODIGO IN (4063,1005) AND EST.REGESTADO=1
)


SELECT DISTINCT CAST(URG.IPFECLLEGA AS DATETIME) 'FECHA/HORA DE LLEGADA',URG.IPCODPACI 'ID PACIENTE', URG.IPNOMCOMP 'NOMBRE', 
IIF( URG.CONESTADO= 1, 'En Espera de Atención TRIAGE',
	IIF(URG.CONESTADO= 3,'Clasificada en TRIAGE',
		IIF(URG.CONESTADO=4,'En Espera de Atención Incial',	
			IIF(URG.CONESTADO= 5 AND URG.FECINIATE IS NOT NULL, 'Paciente sin Definir Conducta Médica','No se encuentra en la unidad')))) AS 'UBICACION', FUN.UFUDESCRI 'SERVICIO'

FROM CTE_URGENCIAS URG
INNER JOIN INUNIFUNC FUN ON FUN.UFUCODIGO=URG.UFUCODIGO




UNION ALL

SELECT DISTINCT CAST(QX.FECINIEST AS DATETIME) 'FECHA/HORA DE LLEGADA',QX.IPCODPACI 'ID PACIENTE', QX.IPNOMCOMP 'NOMBRE', 
CASE WHEN QX.NUMCAMHOS LIKE '%PRE%' THEN 'Trasladada a Preraración Quirúrgica' ELSE 
	CASE WHEN QX.NUMCAMHOS LIKE '%SALA PAR%' THEN 'Trasladada a Sala de Partos' ELSE  
		CASE WHEN QX.NUMCAMHOS LIKE '%SALA CESA%' THEN 'Trasladada a Sala de Cesáreas' ELSE
			CASE WHEN QX.NUMCAMHOS LIKE '%CONTROL%' THEN 'Trasladada a Control Materno' ELSE
				CASE WHEN QX.NUMCAMHOS LIKE '%RECUPER%' THEN 'Trasladada a Recupreración' ELSE 'Trasladada a Observación Alto Riesgo Obstétrico' END END END END END 'UBICACION', FUN.UFUDESCRI 'SERVICIO'

FROM CTE_QUIRURGICOS QX
INNER JOIN INUNIFUNC FUN ON FUN.UFUCODIGO=QX.UFUCODIGO


