-- Workspace: SQLServer
-- Item: INDIGO022 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: ReporteIngresosAbiertos
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE view [ViewInternal].[ReporteIngresosAbiertos]
as 
(
SELECT        ADINGRESO.IPCODPACI AS [DOC PACIENTE], INPACIENT.IPNOMCOMP AS [NOMBRE PACIENTE], ADINGRESO.NUMINGRES AS INGRESO, 
                         CASE ADINGRESO.IESTADOIN WHEN ' ' THEN 'No Facturado' WHEN 'F' THEN 'Facturado' WHEN 'A' THEN 'Anulado' when 'P' then 'Facturado Parcial' when 'C' then 'Cerrado'
                          END AS [ESTADO INGRESO], ADINGRESO.IFECHAING AS [FECHA INGRESO PACIENTE], ADINGRESO.CODUSUCRE AS [COD USUARIO CREA], 
                         SEGusuaru_2.NOMUSUARI AS [USUARIO CREA], 
                         CASE WHEN ADINGRESO.UFUCODIGO = '01' THEN 'URGENCIAS CONSULTA Y PROCEDIMIENTOS' WHEN ADINGRESO.UFUCODIGO = '031' THEN 'URGENCIAS OBSERVACION PEDIATRICA'
                          WHEN ADINGRESO.UFUCODIGO = '032' THEN 'URGENCIAS OBSERVACION HOMBRES 1' WHEN ADINGRESO.UFUCODIGO = '033' THEN 'URGENCIAS OBSERVACION HOMBRES 2'
                          WHEN ADINGRESO.UFUCODIGO = '034' THEN 'URGENCIAS OBSERVACION MUJERES 1' WHEN ADINGRESO.UFUCODIGO = '035' THEN 'URGENCIAS OBSERVACION MUJERES 2'
                          WHEN ADINGRESO.UFUCODIGO = '036' THEN 'URGENCIAS OBSERVACION PASILLO' WHEN ADINGRESO.UFUCODIGO = '037' THEN 'URGENCIAS OBSERVACION REANIMACION'
                          WHEN ADINGRESO.UFUCODIGO = '12' THEN 'URGENCIAS GINECO OBSTETRICIA' WHEN ADINGRESO.UFUCODIGO = '122' THEN 'HOSPITALIZACION GINECOOBSTETRICA'
                          WHEN ADINGRESO.UFUCODIGO = '123' THEN 'OBSTETRICIA PREQUIRURGICA' WHEN ADINGRESO.UFUCODIGO = '13' THEN 'HOSPITALIZACION MEDICINA INTERNA'
                          WHEN ADINGRESO.UFUCODIGO = '14' THEN 'UNIDAD DE CUIDADOS INTERMEDIOS' WHEN ADINGRESO.UFUCODIGO = '141' THEN 'UCI ADULTOS' WHEN ADINGRESO.UFUCODIGO
                          = '15' THEN 'HOSPITALIZACION MEDICOQUIRURGICA' WHEN ADINGRESO.UFUCODIGO = '17' THEN 'HOSPITALIZACION PEDIATRIA' WHEN ADINGRESO.UFUCODIGO
                          = '18' THEN 'HOSPITALIZACION RECIEN NACIDO' WHEN ADINGRESO.UFUCODIGO = '191' THEN 'RECUPERACION QUIROFANO' WHEN ADINGRESO.UFUCODIGO = '192'
                          THEN 'RECUPERACION OBSTETRICA' WHEN ADINGRESO.UFUCODIGO = '193' THEN 'QUIROFANO PREQUIRURGICAS' WHEN ADINGRESO.UFUCODIGO = '20' THEN 'TRABAJO DE PARTOS'
                          WHEN ADINGRESO.UFUCODIGO = '48' THEN 'HOSPITALIZACION PENSION' WHEN ADINGRESO.UFUCODIGO = '04' THEN 'CONSULTA EXTERNA' WHEN ADINGRESO.UFUCODIGO
                          = '05' THEN 'CONSULTA ESPECIALIZADA' WHEN ADINGRESO.UFUCODIGO = '06' THEN 'C EXT ORTOPEDIA' WHEN ADINGRESO.UFUCODIGO = '07' THEN 'C EXT PEDIATRIA'
                          WHEN ADINGRESO.UFUCODIGO = '08' THEN 'C EXT MEDICIANA INTERNA' WHEN ADINGRESO.UFUCODIGO = '09' THEN 'C EXT CIRUGIA GRAL' WHEN ADINGRESO.UFUCODIGO
                          = '10' THEN 'C EXT UROLOGIA' WHEN ADINGRESO.UFUCODIGO = '11' THEN 'C EXT OFTALMOLOGIA' WHEN ADINGRESO.UFUCODIGO = '121' THEN 'CONSULTA EXTERNA GINECO OBSTETRICIA'
                          WHEN ADINGRESO.UFUCODIGO = '29' THEN 'C EXT NEUROLOGIA' WHEN ADINGRESO.UFUCODIGO = '51' THEN 'C EXT GASTROENTEROLOGIA' WHEN ADINGRESO.UFUCODIGO
                          = '52' THEN 'C EXT CARDIOLOGIA' WHEN ADINGRESO.UFUCODIGO = '62' THEN 'C EXT OTORRINOLARINGOLOGIA' WHEN ADINGRESO.UFUCODIGO = '19' THEN 'QUIROFANO'
                          END AS [UNIDAD FUNCIONAL], ADINGRESO.FECREGCRE AS [FEC CREACION INGRESO], ADINGRESO.CODUSUMOD AS [COD USUARIO MODIFICA], 
                         SEGusuaru_1.NOMUSUARI AS [USUARIO MODIFICA], ADINGRESO.FECREGMOD AS [FECHA MODIFICACION], ADINGRESO.CODUSUANU AS [COD USUARIO ANULA], 
                         SEGusuaru.NOMUSUARI AS [USUARIO ANULA], ADINGRESO.FECREGANU AS [FECHA ANULACION], ADINGRESO.IJUSTIFIC AS [JUSTIFICACION ANULACION], 
                         CASE WHEN ADINGRESO.IINGREPOR = '1' THEN 'URGENCIAS' WHEN ADINGRESO.IINGREPOR = '2' THEN 'CONSULTA EXTERNA' WHEN ADINGRESO.IINGREPOR = '3'
                          THEN 'NACIDO HOSPITAL' WHEN ADINGRESO.IINGREPOR = '4' THEN 'REMITIDO' WHEN ADINGRESO.IINGREPOR = '5' THEN 'HOSPITALIZACION URGENCIAS' END AS
                          [INGRESA POR], ADINGRESO.IOBSERVAC AS Observaciones, INENTIDAD.NOMENTIDA, BS.CreationDate AS Fecha_BS, bs.CreationUser AS Cod_usuario_BS,
						  (select FECEGRESO from dbo.CHREGEGRE WHERE NUMINGRES = dbo.ADINGRESO.NUMINGRES) as FechaEgreso
FROM            dbo.ADINGRESO INNER JOIN
                         dbo.INPACIENT ON ADINGRESO.IPCODPACI = INPACIENT.IPCODPACI INNER JOIN
                         dbo.INENTIDAD ON ADINGRESO.CODENTIDA = INENTIDAD.CODENTIDA LEFT OUTER JOIN
                         dbo.SEGusuaru ON ADINGRESO.CODUSUANU = SEGusuaru.CODUSUARI LEFT OUTER JOIN
                         dbo.SEGusuaru AS SEGusuaru_2 ON ADINGRESO.CODUSUCRE = SEGusuaru_2.CODUSUARI LEFT OUTER JOIN
                         dbo.SEGusuaru AS SEGusuaru_1 ON ADINGRESO.CODUSUMOD = SEGusuaru_1.CODUSUARI LEFT OUTER JOIN
						Billing.SlipOut AS BS ON ADINGRESO.NUMINGRES =BS.AdmissionNumber
)
