-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: SP_AUT_ORDENES_AMBULATORIAS_AUTORIZACIONES_RADICADAS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE PROCEDURE [Report].[SP_AUT_ORDENES_AMBULATORIAS_AUTORIZACIONES_RADICADAS]
 --DECLARE 
 @FechaInicial as DATETIME,
 @FechaFinal as DATETIME--;
--SET @FechaInicial = '2025-07-01';
--SET @FechaFinal = '2025-07-31';
AS
WITH 
CTE_ORDENES
AS
(
SELECT 'HCORDIMAG' EntityName, h.AUTO EntityId, h.CANSERIPS Quantity, h.OBSSERIPS Observations
FROM INDIGO036.dbo.HCORDIMAG h
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
SELECT 'HCORDLABO' EntityName, h.AUTO EntityId, h.CANSERIPS Quantity, h.CODSERIPS Observations
FROM INDIGO036.dbo.HCORDLABO h
WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('6')) and cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
SELECT 'HCORDPATO' EntityName, h.AUTO EntityId, h.CANSERIPS Quantity, h.OBSSERIPS Observations
FROM INDIGO036.dbo.HCORDPATO h
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
SELECT 'HCORDINTE' EntityName, h.AUTO EntityId, h.CANSERIPS Quantity, h.OBSSERIPS Observations
FROM INDIGO036.dbo.HCORDINTE h
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
SELECT 'HCORDPRON' EntityName, h.AUTO EntityId, h.CANSERIPS Quantity, h.OBSSERIPS Observations
FROM INDIGO036.dbo.HCORDPRON h
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
SELECT 'HCORDPROQ' EntityName, h.AUTO EntityId, h.CANSERIPS Quantity, h.OBSSERIPS Observations
FROM INDIGO036.dbo.HCORDPROQ h
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
SELECT 'HCORHEMCO' EntityName, h.ID EntityId, hd.Quantity Quantity, '' Observations
FROM INDIGO036.dbo.ADINGRESO ing
INNER JOIN INDIGO036.dbo.HCORHEMCO h ON ing.NUMINGRES = h.NUMINGRES
INNER JOIN 
(
    SELECT hd.HCORHEMCOID, 
        hd.CODSERIPS, 
        hd.TraceabilityPaperworkId, 
        hd.TraceabilityPaperworkEventsId, 
        hd.IDDESCRIPCIONRELACIONADA,
        COUNT(1) Quantity
    FROM INDIGO036.dbo.HCORHEMSER hd
    WHERE hd.ESTADO NOT IN (3)
    GROUP BY hd.HCORHEMCOID, hd.CODSERIPS, hd.TraceabilityPaperworkId, hd.TraceabilityPaperworkEventsId, hd.IDDESCRIPCIONRELACIONADA
) hd ON h.ID = hd.HCORHEMCOID
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
SELECT 'HCDESCOEX' EntityName, h.AUTO EntityId, 1 Quantity, hc.INDICAMED Observations
FROM INDIGO036.dbo.HCHISPACA hc
INNER JOIN INDIGO036.dbo.HCDESCOEX h ON hc.NUMINGRES = h.NUMINGRES AND hc.NUMEFOLIO = h.NUMEFOLIO
WHERE cast(hc.FECHISPAC as date) between @FechaInicial and @FechaFinal
),

CTE_AUTORIZACIONES_AMBULATORIAS_RADICADAS
AS
(
select TP.Id,
    RTRIM(ha.Name) 'ENTIDAD',
    CG.Code 'CODIGO GRUPO',
    RTRIM(CG.Name) 'GRUPO DE ATENCION',
    CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' WHEN '2' THEN 'CEDULA DE EXTRANJERIA' WHEN '3' THEN 'TARJETA DE IDENTIDAD' WHEN '4' THEN 'REGISTRO CIVIL'
            WHEN '5' THEN 'PASAPORTE' WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' WHEN '7' THEN 'MENOR SIN IDENTIFICACION' WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION'
            WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO' WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
            WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION' END AS 'TIPO IDENTIFICACION',
    TP.PatientCode 'IDENTIFICACION',
    PAC.IPNOMCOMP 'PACIENTE',
    PAC.IPTELEFON 'TELEFONO',
    PAC.IPTELMOVI 'CELULAR',
    PAC.IPDIRECCI 'DIRECCION',
    TP.AdmissionNumber 'INGRESO',
    TP.Folio 'FOLIO',
    CASE CUPS.ServiceType WHEN 1 THEN 'Laboratorios' WHEN 2 THEN 'Patologias' WHEN 3 THEN 'Imagenes Diagnosticas'
            WHEN 4 THEN 'Procedimientos no Qx' WHEN 5 THEN 'Procedimientos Qx' WHEN 6 THEN 'Interconsultas' WHEN 7 THEN 'Ninguno' WHEN 8 THEN 'Consulta Externa'
            WHEN 9 THEN 'HEMOCOMPONENTES' END 'TIPO SERVICIO',
    TP.ServiceCode 'CODIGO CUPS ORDENADO',
    CUPS.Description 'DESCRIPCION CUPS ORDENADO',
    cd.Name 'DESCRIPCION RELACIONADA',
    TP.RequestQuantity 'CANTIDAD ORDENADA',
    TP.RequestDate 'FECHA ORDEN',
    'AUTORIZACION EN PROCESO' 'ESTADO',
    CASE TP.Status WHEN 1 THEN 'SOLICITADO' WHEN 2 THEN 'RADICADO' WHEN 3 THEN 'RADICADO PENDIENTE AUTORIZACION' WHEN 4 THEN 'RADICADO NO AUTORIZADO' END 'ESTADO DETALLADO',
    CASE TPE.ReportType WHEN 1 THEN 'Llamada Telefónica' WHEN 2 THEN 'Envío Físico' WHEN 3 THEN 'Registro Página Web' WHEN 4 THEN 'Correo Electrónico'
            WHEN 5 THEN 'Tramita Paciente' END 'TIPO REPORTE',
    CASE TPE.Status WHEN 1 THEN 'Pendiente por Autorizar' WHEN 2 THEN 'Autorizado'  WHEN 3 THEN 'No Autorizado' WHEN 4 THEN 'Autorizado con Aval' END 'ESTADO EVENTO',
    IIF(TP.AdmissionNumber IS NULL, TP.DocumentDate,
        IIF(TPE.ReportType ='5', TPE.CreationDate, ISNULL(TPE.RegistrationDate, ISNULL(TPE.SendDate, ISNULL(TPE.InitialTime, ISNULL(TPE.CreationDate, TP.DocumentDate)))))) 'FECHA RADICADO',
    TPE.RadicateNumber 'NUMERO RADICADO',
    USU.NOMUSUARI 'USUARIO CREO',
    PRO.NOMMEDICO 'PROFESIONAL',
    ESP.DESESPECI 'ESPECIALIDAD',
    ISNULL(ING.CODDIAING, ING.CODDIAEGR) 'CIE10',
    DIA.NOMDIAGNO 'DIAGNOSTICO',
    ORD.Observations AS OBSERVACION
from INDIGO036.[Authorization].TraceabilityPaperwork TP
INNER JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON CUPS.Code = TP.ServiceCode
INNER JOIN INDIGO036.dbo.INPACIENT AS PAC ON PAC.IPCODPACI = TP.PatientCode 
INNER JOIN INDIGO036.dbo.INPROFSAL AS PRO ON PRO.CODPROSAL = TP.ProfessionalCode  
INNER JOIN INDIGO036.dbo.INESPECIA AS ESP ON ESP.CODESPECI = PRO.CODESPEC1
LEFT JOIN INDIGO036.dbo.ADINGRESO AS ING ON ING.NUMINGRES = TP.AdmissionNumber
LEFT JOIN INDIGO036.Contract.HealthAdministrator ha ON ha.Id = TP.HealthAdministratorId 
LEFT JOIN INDIGO036.Contract.CareGroup AS CG ON CG.Id = TP.CareGroupId 
LEFT JOIN INDIGO036.[Authorization].TraceabilityPaperworkEvents AS TPE ON TPE.TraceabilityPaperworkId = TP.Id 
LEFT JOIN INDIGO036.dbo.SEGusuaru AS USU ON USU.CODUSUARI = TPE.CreationUser 
LEFT JOIN INDIGO036.dbo.INDIAGNOS AS DIA ON DIA.CODDIAGNO = ISNULL(ING.CODDIAING, ING.CODDIAEGR)
LEFT JOIN INDIGO036.Contract.ContractDescriptions cd ON TP.ContractDescriptionId = cd.Id
LEFT JOIN CTE_ORDENES ORD ON TP.EntityName = ORD.EntityName AND TP.EntityId = ORD.EntityId
where TP.Type = 1 and TP.Status in (1,2,3) AND cast(TP.RequestDate as date) between @FechaInicial and @FechaFinal
)

SELECT * FROM 
CTE_AUTORIZACIONES_AMBULATORIAS_RADICADAS AUT
ORDER BY AUT.Id, AUT.[FECHA ORDEN]