-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: SP_HISTORICO_ESTANCIAS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE PROCEDURE Report.SP_HISTORICO_ESTANCIAS
@FECHAINICIA AS DATE,
@FECHAFINAL AS DATE
AS
--DECLARE @FECFIN as date = '" & Parametros{1}[Valor] & "';

--DECLARE @FECINI AS DATE = '2025-08-01';
--DECLARE @FECFIN AS DATE = '2025-08-31';

WITH CTE_ULTIMA_CAMAS_OCUPADA AS (
    SELECT
        EGR.NUMINGRES,
        EGR.FECINIEST,
        EGR.FECFINEST,
        EGR.CODICAMAS,
        CAM.NUMCAMHOS,
        FUN.UFUDESCRI,
        FUN.UFUTIPUNI,
        FUN.UFUCODIGO,
        'EGRESO' AS TIPINGEST,
        EGR.CODTIPEST,
        TIP.DESTIPEST,
        EGR.GENESTLIQ,
        EGR.ID
    FROM
        INDIGO036.dbo.CHREGESTA EGR
        INNER JOIN (
            SELECT
                EGR.IPCODPACI,
                EGR.NUMINGRES,
                MAX(EGR.ID) ID
            FROM
                INDIGO036.dbo.CHREGESTA EGR
            GROUP BY
                EGR.IPCODPACI,
                EGR.NUMINGRES
        ) AS G ON G.ID = EGR.ID
        INNER JOIN INDIGO036.dbo.CHCAMASHO AS CAM ON CAM.CODICAMAS = EGR.CODICAMAS
        INNER JOIN INDIGO036.dbo.INUNIFUNC AS FUN ON CAM.UFUCODIGO = FUN.UFUCODIGO
        INNER JOIN INDIGO036.dbo.CHTIPESTA TIP ON TIP.CODTIPEST = EGR.CODTIPEST
    WHERE
        EGR.FECFINEST > '1989-01-01 00:00:00.000'
),
CTE_DESTINOS AS (
    SELECT
        ROW_NUMBER () OVER (
            PARTITION BY NUMINGRES
            ORDER BY
                NUMINGRES,
                FECHISPAC DESC
        ) 'NUMERO',
        NUMINGRES,
        INDICAPAC,
        NUMEFOLIO AS NUMEROFOLIO
    FROM
        INDIGO036.dbo.HCHISPACA
),
CTE_DESTINO AS (
    SELECT
        DISTINCT EGR.ID,
        CASE
            H.INDICAPAC
            WHEN 8 THEN 'TRASLADAR A CIRUGIA'
            WHEN 9 THEN 'HOSPITALIZACION EN CASA'
            WHEN 10 THEN 'REFERENCIA'
            WHEN 11 THEN 'MORGE'
            WHEN 12 THEN 'SALIDA'
            WHEN 13 THEN 'SALIDA'
            WHEN 15 THEN 'RETITO VOLUNTARIO'
            WHEN 16 THEN 'FUGA'
        END AS DESTINO,
        H.NUMEROFOLIO
    FROM
        CTE_ULTIMA_CAMAS_OCUPADA EGR
        INNER JOIN CTE_DESTINOS H ON EGR.NUMINGRES = H.NUMINGRES
        AND H.NUMERO = 1
),
CTE_USUARIO_TRASLADO AS (
    SELECT
        US.UserCode,
        PER.Identification + ' - ' + PER.Fullname AS [USUARIO QUE TRASLADA]
    FROM
        [INDIGO036].[Security].[UserInt] US
        INNER JOIN [INDIGO036].[Security].[PersonInt] PER ON US.IdPerson = PER.Id
)
SELECT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    ROW_NUMBER() OVER(
        ORDER BY
            P.IPTIPODOC ASC
    ) AS #,
    A.IPCODPACI AS 'IDENTIFICACIÓN',
    CASE
        P.IPTIPODOC
        WHEN 1 THEN 'CC'
        WHEN 2 THEN 'CE'
        WHEN 3 THEN 'TI'
        WHEN 4 THEN 'RC'
        WHEN 5 THEN 'PA'
        WHEN 6 THEN 'AS'
        WHEN 7 THEN 'MS'
        WHEN 8 THEN 'NU'
        WHEN 9 THEN 'CN'
        WHEN 10 THEN 'CD'
        WHEN 11 THEN 'SC'
        WHEN 12 THEN 'PE'
    END AS 'TIPO DE IDENTIFICACION',
    RTRIM(P.IPNOMCOMP) 'PACIENTE',
    CAST(P.IPFECNACI AS DATE) AS 'FECHA DE NACIMIENTO',
    FLOOR(
        (
            CAST(CONVERT(VARCHAR(8), A.FECINIEST, 112) AS INT) - CAST(CONVERT(VARCHAR(8), P.IPFECNACI, 112) AS INT)
        ) / 10000
    ) AS 'EDAD AÑOS',
    CASE
        P.IPSEXOPAC
        WHEN 2 THEN 'FEMENINO'
        WHEN 1 THEN 'MASCULINO'
    END AS 'GENERO',
    P.IPTELEFON AS TELEFONO,
    P.IPTELMOVI AS CELULAR,
    A.NUMINGRES AS [INGRESO],
    DSTS.NUMEROFOLIO,
    E.NOMENTIDA AS [ENTIDAD PACIENTE],
    GA.Code + ' - ' + GA.Name [GRUPO ATENCION],
    (
        SELECT
            TOP 1 DIG.CODDIAGNO + ' - ' + DIA.NOMDIAGNO
        FROM
            INDIGO036.dbo.INDIAGNOH DIG
            INNER JOIN INDIGO036.dbo.INDIAGNOS DIA ON DIG.CODDIAGNO = DIA.CODDIAGNO
        WHERE
            A.NUMINGRES = DIG.NUMINGRES
            AND DIG.CODDIAPRI = '1'
    ) AS [DIAGNOSTICO PRINCIPAL],
    CASE
        IPTIPOPAC
        WHEN 1 THEN 'CONTRIBUTIVO'
        WHEN 2 THEN 'SUBSIDIADO'
        WHEN 3 THEN 'VINCULADO'
        WHEN 4 THEN 'PARTICULAR'
        ELSE 'Otro'
    END AS 'COBERTURA',
    YEAR(A.FECINIEST) AS AÑO,
    MONTH(A.FECINIEST) AS MES,
    ING.IFECHAING AS [FECHA INGRESO],
    A.FECINIEST AS [FECHA INICIAL DE ESTANCIA],
    CASE
        WHEN A.FECFINEST > '1989-01-01 00:00:00.000' THEN A.FECFINEST
        ELSE NULL
    END AS [FECHA FINAL ESTANCIA],
    CASE
        WHEN A.FECFINEST > '1989-01-01 00:00:00.000' THEN DATEDIFF(DAY, A.FECINIEST, A.FECFINEST)
        ELSE NULL
    END AS [DIAS DE ESTANCIA],
    CASE
        WHEN A.FECFINEST > '1989-01-01 00:00:00.000' THEN DATEDIFF(HOUR, A.FECINIEST, A.FECFINEST)
        ELSE NULL
    END AS [HORAS DE ESTANCIA],
    RTRIM(B.CODICAMAS) + ' - ' + B.DESCCAMAS AS [CAMA],
    C.DESTIPEST AS [TIPO DE ESTANCIA],
    D.UFUCODIGO AS [CODIGO UNIDAD],
    D.UFUDESCRI AS [UNIDAD FUNCIONAL],
    CASE
        A.TIPINGEST
        WHEN 'NU' THEN 'NUEVA UNIDAD'
        WHEN 'TC' THEN 'TRASLADO INTERNO DE CAMA'
    END AS [TIPO INGRESO ESTANCIA],
    CO.TIPINGEST AS [ULTIMO ESTADO],
    DST.DESTINO AS [TIPO DE SALIDA],
    PER.[USUARIO QUE TRASLADA],
    1 as CANTIDAD,
    CAST(A.FECREGSIS AS DATE) AS [FECHA BUSQUEDA],
    YEAR(A.FECREGSIS) AS [AÑO FECHA BUSQUEDA],
    MONTH(A.FECREGSIS) AS [MES AÑO FECHA BUSQUEDA],
    CASE
        MONTH(A.FECREGSIS)
        WHEN 1 THEN 'ENERO'
        WHEN 2 THEN 'FEBRERO'
        WHEN 3 THEN 'MARZO'
        WHEN 4 THEN 'ABRIL'
        WHEN 5 THEN 'MAYO'
        WHEN 6 THEN 'JUNIO'
        WHEN 7 THEN 'JULIO'
        WHEN 8 THEN 'AGOSTO'
        WHEN 9 THEN 'SEPTIEMBRE'
        WHEN 10 THEN 'OCTUBRE'
        WHEN 11 THEN 'NOVIEMBRE'
        WHEN 12 THEN 'DICIEMBRE'
    END AS [MES NOMBRE FECHA BUSQUEDA],
    FORMAT(DAY(A.FECREGSIS), '00') AS [DIA FECHA BUSQUEDA],
    CONCAT(
        FORMAT(MONTH(A.FECREGSIS), '00'),
        ' - ',
        CASE
            MONTH(A.FECREGSIS)
            WHEN 1 THEN 'ENERO'
            WHEN 2 THEN 'FEBRERO'
            WHEN 3 THEN 'MARZO'
            WHEN 4 THEN 'ABRIL'
            WHEN 5 THEN 'MAYO'
            WHEN 6 THEN 'JUNIO'
            WHEN 7 THEN 'JULIO'
            WHEN 8 THEN 'AGOSTO'
            WHEN 9 THEN 'SEPTIEMBRE'
            WHEN 10 THEN 'OCTUBRE'
            WHEN 11 THEN 'NOVIEMBRE'
            WHEN 12 THEN 'DICIEMBRE'
        END
    ) MES_LABEL_INGRESO,
    CONVERT(
        DATETIME,
        GETDATE() AT TIME ZONE 'Pakistan Standard Time',
        1
    ) AS ULT_ACTUAL
FROM
    INDIGO036.dbo.CHREGESTA A
    INNER JOIN INDIGO036.dbo.CHCAMASHO B ON A.CODICAMAS = B.CODICAMAS
    INNER JOIN INDIGO036.dbo.CHTIPESTA C ON A.CODTIPEST = C.CODTIPEST
    INNER JOIN INDIGO036.dbo.INUNIFUNC D ON B.UFUCODIGO = D.UFUCODIGO
    INNER JOIN INDIGO036.dbo.INPACIENT P ON A.IPCODPACI = P.IPCODPACI
    INNER JOIN INDIGO036.dbo.ADINGRESO ING ON A.NUMINGRES = ING.NUMINGRES
    INNER JOIN INDIGO036.dbo.INENTIDAD E ON P.CODENTIDA = E.CODENTIDA
    INNER JOIN INDIGO036.Contract.CareGroup GA ON GA.Id = ING.GENCAREGROUP
    LEFT JOIN CTE_USUARIO_TRASLADO PER ON A.REGUSUARI = PER.UserCode
    LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA CO ON A.ID = CO.ID
    LEFT JOIN CTE_DESTINO DST ON CO.ID = DST.ID
    LEFT JOIN CTE_DESTINOS DSTS ON A.NUMINGRES = DSTS.NUMINGRES
    AND DSTS.NUMERO = 1
WHERE CAST(A.FECREGSIS AS DATE) BETWEEN @FECHAINICIA AND @FECHAFINAL;