-- Workspace: HOMI
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9e4ad354-8031-4a13-8643-33b3234761ff
-- Schema: Report
-- Object: SP_VIEWEGRESOSHOSPITALARIOSBASEDEALTA_2
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE PROCEDURE Report.SP_VIEWEGRESOSHOSPITALARIOSBASEDEALTA_2
@FECINI AS DATE,
@FECFIN AS DATE
AS
--DECLARE @FECFIN as date = '" & Parametros{1}[Valor] & "';

--DECLARE @FECINI AS DATE = '2025-08-01';
--DECLARE @FECFIN AS DATE = '2025-08-31';

WITH CTE_PRIMER_INGRESO AS (
    SELECT
        EST.NUMINGRES,
        EST.IPCODPACI,
        MIN(EST.IFECHAING) AS [FECHA ADMISION]
    FROM
        INDIGO036.dbo.ADINGRESO EST
    GROUP BY
        EST.NUMINGRES,
        EST.IPCODPACI
),
CTE_ULTIMO_INGRESO AS (
    SELECT
        EST.NUMINGRES,
        EST.IPCODPACI,
        MAX(EST.FECHEGRESO) AS [FECHA EGRESO]
    FROM
        INDIGO036.dbo.ADINGRESO EST
    GROUP BY
        EST.NUMINGRES,
        EST.IPCODPACI
),
CTE_INGRESO_INICIAL AS (
    SELECT
        ES.IPCODPACI,
        ES.NUMINGRES,
        ES.FECINIEST AS [FECHA HOSPITALIZACION],
        ES.CODTIPEST
    FROM
        INDIGO036.dbo.CHREGESTA AS ES
        INNER JOIN (
            SELECT
                EST.IPCODPACI,
                EST.NUMINGRES,
                MIN(ID) ID
            FROM
                INDIGO036.dbo.CHREGESTA AS EST
            GROUP BY
                EST.IPCODPACI,
                EST.NUMINGRES
        ) AS G ON G.ID = ES.ID
),
CTE_ULTIMA_CAMAS_OCUPADA AS (
    SELECT
        EGR.NUMINGRES,
        EGR.FECINIEST,
        EGR.FECFINEST,
        EGR.CODICAMAS,
        CAM.NUMCAMHOS,
        FUN.UFUDESCRI,
        FUN.UFUTIPUNI,
        FUN.UFUCODIGO,
        'EGRESO                   ' AS TIPINGEST,
        EGR.CODTIPEST,
        TIP.DESTIPEST,
        EGR.GENESTLIQ,
        EGR.ID
    FROM
        INDIGO036.dbo.CHREGESTA EGR
        INNER JOIN (
            SELECT
                EGR.IPCODPACI,
                EGR.NUMINGRES,
                MAX(EGR.ID) ID
            FROM
                INDIGO036.dbo.CHREGESTA EGR
            GROUP BY
                EGR.IPCODPACI,
                EGR.NUMINGRES
        ) AS G ON G.ID = EGR.ID
        INNER JOIN INDIGO036.dbo.CHCAMASHO AS CAM ON CAM.CODICAMAS = EGR.CODICAMAS
        INNER JOIN INDIGO036.dbo.INUNIFUNC AS FUN ON CAM.UFUCODIGO = FUN.UFUCODIGO
        INNER JOIN INDIGO036.dbo.CHTIPESTA TIP ON TIP.CODTIPEST = EGR.CODTIPEST
    WHERE
        EGR.FECFINEST > '1989-01-01 00:00:00.000'
)
SELECT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    CEN.NOMCENATE AS [CENTRO ATENCION],
    CASE
        UNI.UFUTIPUNI
        WHEN 1 THEN 'URGENCIAS'
        WHEN 2 THEN 'HOSPITALIZACION'
        WHEN 3 THEN 'APOYO DIAGNOSTICO'
        WHEN 4 THEN 'APOYO TERAPEUTICO'
        WHEN 5 THEN 'UCI'
        WHEN 6 THEN 'UCI'
        WHEN 7 THEN 'UCI'
        WHEN 8 THEN 'UCI'
        WHEN 9 THEN 'UCI'
        WHEN 10 THEN 'UCI'
        WHEN 11 THEN 'UCI'
        WHEN 12 THEN 'UNIDAD RENAL'
        WHEN 13 THEN 'UNIDAD ONCOLOGICA'
        WHEN 14 THEN 'UNIDAD MEDICINA NUCLEAR'
        WHEN 15 THEN 'CONSULTA EXTERNA'
        WHEN 16 THEN 'UNIDAD MENTAL'
        WHEN 17 THEN 'UNIDAD DE QUEMADOS'
        WHEN 18 THEN 'UNIDAD DE CUIDADOS PALATIVOS'
        WHEN 19 THEN 'CIRUGIA'
        WHEN 20 THEN 'LABORATORIOS'
        WHEN 21 THEN 'CARDIOLOGIA NO INVASIVA'
        WHEN 22 THEN 'CARDIOLOGIA INVASIVA'
        WHEN 23 THEN 'GINECO OBSTETRICIA'
        WHEN 24 THEN 'CONSULTA EXTERNA GINOCO OBSTETRICIA'
        WHEN 30 THEN 'OTRAS'
        WHEN 31 THEN 'CONSULTA PRIORITARIA'
    END AS [TIPO UNIDAD],
    CASE
        EI.CODTIPEST
        WHEN '001' THEN 'GENERAL'
        WHEN '002' THEN 'CUIDADO BASICO'
        WHEN '003' THEN 'CUIDADO INTERMEDIO'
        ELSE 'CUIDADO INTENSIVO'
    END AS [TIPO ESTANCIA],
    HEA.Code AS [CODIGO ENTIDAD],
    RTRIM(HEA.Name) AS [ENTIDAD],
    RTRIM(CGR.Name) AS [GRUPO DE ATENCION],
    CASE
        PAC.IPTIPOPAC
        WHEN 1 THEN 'CONTRIBUTIVO'
        WHEN 2 THEN 'SUBSIDIADO'
        WHEN 3 THEN 'VINCULADO'
        WHEN 4 THEN 'PARTICULAR'
        WHEN 5 THEN 'OTRO'
        WHEN 6 THEN 'DESPLAZADO REG. CONTRIBUTIVO'
        WHEN 7 THEN 'DESPLAZADO REG. SUBSIDIADO'
        ELSE 'DESPLAZADO NO ASEGURADO'
    END AS [RÉGIMEN],
    CASE
        PAC.IPTIPODOC
        WHEN '1' THEN 'CC'
        WHEN '2' THEN 'CE'
        WHEN '3' THEN 'TI'
        WHEN '4' THEN 'RC'
        WHEN '5' THEN 'PA'
        WHEN '6' THEN 'AS'
        WHEN '7' THEN 'MS'
        WHEN '8' THEN 'NU'
        WHEN '9' THEN 'NV'
        WHEN '10' THEN 'CD'
        WHEN '11' THEN 'SC'
        WHEN '12' THEN 'PE'
    END AS [TIPO IDENTIFICACION],
    CASE
        PAC.IPTIPODOC
        WHEN '1' THEN 'CEDULA DE CIUDADANIA'
        WHEN '2' THEN 'CEDULA DE EXTRANJERIA'
        WHEN '3' THEN 'TARJETA DE IDENTIDAD'
        WHEN '4' THEN 'REGISTRO CIVIL'
        WHEN '5' THEN 'PASAPORTE'
        WHEN '6' THEN 'ADULTO SIN IDENTIFICACION'
        WHEN '7' THEN 'MENOR SIN IDENTIFICACION'
        WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACIÒN'
        WHEN '9' THEN 'CERTIFICADO NACIDO VIVO'
        WHEN '10' THEN 'CARNET DIPLOMATICO'
        WHEN '11' THEN 'SALVOCONDUCTO'
        WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA'
    END AS [DESCRIPCION IDENTIFICACION],
    HC.IPCODPACI AS [IDENTIFICACION],
    RTRIM(PAC.IPPRINOMB) AS [PRIMER NOMBRE],
    RTRIM(PAC.IPSEGNOMB) AS [SEGUNDO NOMBRE],
    RTRIM(PAC.IPPRIAPEL) AS [PRIMER APELLIDO],
    RTRIM(PAC.IPSEGAPEL) AS [SEGUNDO APELLIDO],
    RTRIM(PAC.IPNOMCOMP) AS [NOMBRE COMPLETO PACIENTE],
    UNI.UFUCODIGO AS [CODIGO UNIDAD FUNCIONAL],
    RTRIM(UNI.UFUDESCRI) AS [UNIDAD FUNCIONAL],
    PAC.IPFECNACI AS [FECHA NACIMIENTO],
    FLOOR(
        (
            CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)
        ) / 10000
    ) AS [EDAD],
    CASE
        WHEN PAC.IPSEXOPAC = '1' THEN 'M'
        ELSE 'F'
    END AS [SEXO],
    PAC.IPDIRECCI AS [DIRECCION],
    PAC.IPTELEFON AS [TELEFONO FIJO],
    PAC.IPTELMOVI AS [TELEFONO MOVIL],
    DEP.depcodigo AS [CODIGO DEPARTEMENTO],
    DEP.nomdepart AS [DEPARTAMENTO],
    MUN.DEPMUNCOD AS [CODIGO MUNICIPIO],
    MUN.MUNNOMBRE AS [MUNICIPIO],
    HC.NUMINGRES AS [INGRESO],
    CING.[FECHA ADMISION],
    EI.[FECHA HOSPITALIZACION] AS [FECHA HOSPITALIZACION],
    HC.FECALTPAC AS [FECHA ALTA MEDICA],
    CONVERT(varchar, HC.FECALTPAC, 108) AS [HORA_ALTA],
    CTUE.[FECHA EGRESO] AS [FECHA EGRESO],
    CONVERT(varchar, CTUE.[FECHA EGRESO], 108) AS [HORA_EGRESO],
    DATEDIFF(DAY, CING.[FECHA ADMISION], HC.FECALTPAC) AS [DIAS],
    HIS.FECHISPAC AS [FECHA HC],
    DATEDIFF(MINUTE, HC.FECALTPAC, HIS.FECHISPAC) AS [MINUTOS ALTA Vs HC],
    CASE
        HC.ESTPACEGR
        WHEN 1 THEN 'MEJOR'
        WHEN 2 THEN 'IGUAL Y PEOR'
        WHEN 3 THEN 'FALLECIDO'
        WHEN 4 THEN 'REMITIDO'
        WHEN 5 THEN 'HOSPITALIZACION EN CASA'
    END AS [ESTADO AL EGRESO],
    RTRIM(CAM.NUMCAMHOS) AS [CAMA ACTUAL],
    CASE
        HC.ESTPACEGR
        WHEN 3 THEN 'SI'
        ELSE 'NO'
    END AS [FALLECIDO],
    HC.FECMUEPAC AS [FECHA DE MUERTE],
    CASE
        HC.CODCAUMUE
        WHEN 001 THEN 'MUERTE NATURAL'
        WHEN 002 THEN 'MUERTE VIOLENTA'
        WHEN 003 THEN 'MUERTE EN ESTUDIO'
    END AS [CAUSA DE MUERTE],
    HC.NUMCERDEF AS [NO_CERT_DEFUNCION],
    CASE
        HIS.INDICAPAC
        WHEN 1 THEN 'Trasladar a Urgencias: Solo consulta externa'
        WHEN 2 THEN 'Trasladar a Observacion Urgencias: solo Urgencias'
        WHEN 3 THEN 'Trasladar a Hospitalizacion: Dif Misma Unidad'
        WHEN 4 THEN 'Trasladar a UCI Adulto: Dif Misma Unidad'
        WHEN 5 THEN 'Trasladar a UCI Pediatrica: Dif Misma Unidad'
        WHEN 6 THEN 'Trasladar a UCI Neonatal: Dif Misma Unidad'
        WHEN 7 THEN 'Trasladar a Consulta Externa: Dif Misma Unidad'
        WHEN 8 THEN 'Trasladar a Cirugia: Dif Misma Unidad'
        WHEN 9 THEN 'Hospitalizacion en Casa'
        WHEN 10 THEN 'Referencia'
        WHEN 11 THEN 'Morgue'
        WHEN 12 THEN 'Salida'
        WHEN 13 THEN 'Continua en la Unidad'
        WHEN 14 THEN 'Paciente en Tratamiento'
        WHEN 15 THEN 'Retiro Voluntario'
        WHEN 16 THEN 'Fuga'
        WHEN 17 THEN 'Salida Parcial'
        WHEN 18 THEN 'Estancia Con la Madre'
        WHEN 19 THEN 'U.Cuidado Intermedio'
        WHEN 20 THEN 'U.Basica'
    END AS [DESTINO PACIENTE],
    PRO.NOMMEDICO AS [PROFESIONAL DE LA SALUD],
    ESP.DESESPECI AS [ESPECIALIDAD],
    ING.CODDIAING AS [CIE10 INGRESO],
    RTRIM(DIA.NOMDIAGNO) AS [DIAGNOSTICO DE INGRESO],
    ING.CODDIAEGR AS [CIE10 EGRESO],
    RTRIM(DIAE.NOMDIAGNO) AS [DIAGNOSTICO DE EGRESO],
    CO.NUMCAMHOS AS [CAMA DE EGRESO],
    CO.UFUDESCRI AS [UNIDAD DE EGRESO],
    1 AS [CANTIDAD],
    CAST(HC.FECALTPAC AS date) AS [FECHA BUSQUEDA],
    YEAR(HC.FECALTPAC) AS [AÑO BUSQUEDA],
    MONTH(HC.FECALTPAC) AS [MES BUSQUEDA],
    CONCAT(
        FORMAT(MONTH(HC.FECALTPAC), '00'),
        ' - ',
        CASE
            MONTH(HC.FECALTPAC)
            WHEN 1 THEN 'ENERO'
            WHEN 2 THEN 'FEBRERO'
            WHEN 3 THEN 'MARZO'
            WHEN 4 THEN 'ABRIL'
            WHEN 5 THEN 'MAYO'
            WHEN 6 THEN 'JUNIO'
            WHEN 7 THEN 'JULIO'
            WHEN 8 THEN 'AGOSTO'
            WHEN 9 THEN 'SEPTIEMBRE'
            WHEN 10 THEN 'OCTUBRE'
            WHEN 11 THEN 'NOVIEMBRE'
            WHEN 12 THEN 'DICIEMBRE'
        END
    ) AS [MES NOMBRE BUSQUEDA],
    CONVERT(
        DATETIME,
        GETDATE() AT TIME ZONE 'Pakistan Standard Time',
        1
    ) AS [ULT_ACTUAL]
FROM
    INDIGO036.dbo.HCREGEGRE HC
    INNER JOIN CTE_INGRESO_INICIAL EI ON HC.NUMINGRES = EI.NUMINGRES
    INNER JOIN CTE_ULTIMO_INGRESO CTUE ON HC.NUMINGRES = CTUE.NUMINGRES
    LEFT JOIN CTE_PRIMER_INGRESO CING ON CING.NUMINGRES = HC.NUMINGRES
    INNER JOIN INDIGO036.dbo.HCHISPACA HIS ON HC.NUMINGRES = HIS.NUMINGRES
        AND HC.NUMEFOLIO = HIS.NUMEFOLIO
    INNER JOIN INDIGO036.dbo.INPACIENT AS PAC ON PAC.IPCODPACI = HC.IPCODPACI
    INNER JOIN INDIGO036.dbo.ADINGRESO AS ING ON HC.NUMINGRES = ING.NUMINGRES
    INNER JOIN INDIGO036.dbo.ADCENATEN AS CEN ON HC.CODCENATE = CEN.CODCENATE
    INNER JOIN INDIGO036.dbo.INUNIFUNC UNI ON HC.UFUCODIGO = UNI.UFUCODIGO
    INNER JOIN INDIGO036.Contract.HealthAdministrator HEA ON ING.GENCONENTITY = HEA.Id
    INNER JOIN INDIGO036.Contract.CareGroup AS CGR ON ING.GENCAREGROUP = CGR.Id
    LEFT JOIN INDIGO036.dbo.CHCAMASHO CAM ON ING.CODCAMACT = CAM.CODICAMAS
    LEFT JOIN INDIGO036.dbo.INPROFSAL PRO ON HIS.CODPROSAL = PRO.CODPROSAL
    LEFT JOIN INDIGO036.dbo.INESPECIA AS ESP ON ESP.CODESPECI = HIS.CODESPTRA
    LEFT JOIN INDIGO036.dbo.INDIAGNOS AS DIA ON ING.CODDIAING = DIA.CODDIAGNO
    LEFT JOIN INDIGO036.dbo.INDIAGNOS AS DIAE ON ING.CODDIAEGR = DIAE.CODDIAGNO
    LEFT JOIN INDIGO036.dbo.INUBICACI UBI ON PAC.AUUBICACI = UBI.AUUBICACI
    LEFT JOIN INDIGO036.dbo.INMUNICIP MUN ON UBI.DEPMUNCOD = MUN.DEPMUNCOD
    LEFT JOIN INDIGO036.dbo.INDEPARTA DEP ON MUN.DEPCODIGO = DEP.depcodigo
    LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA CO ON HC.NUMINGRES = CO.NUMINGRES
WHERE
    CAST(HC.FECALTPAC as DATE) BETWEEN @FECINI AND @FECFIN;