-- Workspace: SQLServer
-- Item: INDIGO031 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: DWH_ANTVALORES
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [ViewInternal].[DWH_ANTVALORES] 
AS
SELECT * FROM dbo.ANTVALORES202112 UNION ALL
SELECT * FROM dbo.ANTVALORES202201 UNION ALL
SELECT * FROM dbo.ANTVALORES202202 UNION ALL
SELECT * FROM dbo.ANTVALORES202203 UNION ALL
SELECT * FROM dbo.ANTVALORES202204 UNION ALL
SELECT * FROM dbo.ANTVALORES202205 UNION ALL
SELECT * FROM dbo.ANTVALORES202206 UNION ALL
SELECT * FROM dbo.ANTVALORES202207
