-- Workspace: SQLServer
-- Item: INDIGO031 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: DWH_RSVALORES
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [ViewInternal].[DWH_RSVALORES] 
AS
SELECT * FROM dbo.RSVALORES202112 UNION ALL
SELECT * FROM dbo.RSVALORES202201 UNION ALL
SELECT * FROM dbo.RSVALORES202202 UNION ALL
SELECT * FROM dbo.RSVALORES202203 UNION ALL
SELECT * FROM dbo.RSVALORES202204 UNION ALL
SELECT * FROM dbo.RSVALORES202205 UNION ALL
SELECT * FROM dbo.RSVALORES202206 UNION ALL
SELECT * FROM dbo.RSVALORES202207
