-- Workspace: SQLServer
-- Item: INDIGO031 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: DWH_EXAVALORES
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [ViewInternal].[DWH_EXAVALORES] 
AS
SELECT * FROM dbo.EXAVALORES202112 UNION ALL
SELECT * FROM dbo.EXAVALORES202201 UNION ALL
SELECT * FROM dbo.EXAVALORES202202 UNION ALL
SELECT * FROM dbo.EXAVALORES202203 UNION ALL
SELECT * FROM dbo.EXAVALORES202204 UNION ALL
SELECT * FROM dbo.EXAVALORES202205 UNION ALL
SELECT * FROM dbo.EXAVALORES202206 UNION ALL
SELECT * FROM dbo.EXAVALORES202207
