-- Workspace: SQLServer
-- Item: INDIGO031 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: HC_PerfilEpidemiologico
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [ViewInternal].[HC_PerfilEpidemiologico] AS

SELECT  
 ca.NOMCENATE AS CentroAtencion, YEAR(ingR.IFECHAING) AS Año, ing.NUMINGRES AS Ingreso, 
CASE IPTIPODOC WHEN 1 THEN 'CC' WHEN 2 THEN 'CE' WHEN 3 THEN 'TI' WHEN 4 THEN 'RC' WHEN 5 THEN 'PA' WHEN 6 THEN 'AS' WHEN 7 THEN 'MS' WHEN '8' THEN 'NU' when '9' then 'NV'  when '12' then 'PE' when '13' then 'PT' END AS TipoIdentificacion, 
A.IPCODPACI AS Identificacion,  CASE IPSEXOPAC WHEN 1 THEN 'M' WHEN 2 THEN 'F' END AS Genero, 
DATEDIFF(MONTH,A.IPFECNACI,ingR.IFECHAING)/12 AS Edad_Años,
RTRIM(LTRIM(dbo.Edad(CONVERT(varchar, A.IPFECNACI, 112), CONVERT(varchar,ing.FECALTPAC, 112)))) AS Edad, 
A.IPFECNACI AS FechaNacimiento, 
CASE IPESTADOC WHEN 1 THEN 'Soltero' WHEN 2 THEN 'Casado' WHEN 3 THEN 'Viudo' WHEN 4 THEN 'Union Libre' WHEN 5 THEN 'Separado(a)/Div' END AS [Estado Civil], 
I.NIVEDESCRI AS [Nivel Educativo], F.desactivi AS Ocupacion, ga.Name AS Entidad, 
CASE IPTIPOPAC WHEN 1 THEN 'Contributivo' WHEN 2 THEN 'Subsidiado' WHEN 3 THEN 'Vinculado' WHEN 4 THEN 'Particular' WHEN 5 THEN 'Otro' WHEN 6 THEN 'Desplazado Reg. Contributivo' WHEN 7 THEN 'Desplazado Reg. Subsidiado' WHEN 8 THEN 'Desplazado No Asegurado' END AS TipoAfiliacion, 
A.IPESTRATO AS Estrato, 
CASE A.ZONAPARTADA WHEN 'False' THEN 'Urbana' WHEN 'True' THEN 'Rural' END AS Area, 
D.UBINOMBRE AS Ubicacion, m.MUNNOMBRE AS MunicipioProcedencia, DEP.nomdepart AS Departamento, 
G.DESGRUPET AS GrupoEtnico, J.CREDDESCRI AS Religion, ps1.Secundario as [Poblacion Vulnerable], W.DISCDESCRI AS Discapacidad,
CASE INGR.IINGREPOR WHEN 1 THEN 'Urgencias' WHEN 2 THEN 'Consulta Externa' WHEN 3 THEN 'Nacido Hospital' WHEN 4 THEN 'Remitido' WHEN 5 THEN 'Hospitalizacion de Urgencias' END AS IngresoPor, 
CASE WHEN INGR.TIPOINGRE = '1' THEN 'Ambulatorio' WHEN INGR.icaUSAING ='11' and INGR.TIPOINGRE = '2' THEN 'Ambulatorio' ELSE 'Hospitalario' END as TipoIngreso,
ufh.UFUDESCRI as UnidadFuncionalIngreso,
ingR.IFECHAING AS [Fecha atencion], ES1.DESESPECI AS [Especialidad Tratante], ingR.CODDIAING AS CIE10_Ingreso, 
dx.NOMDIAGNO AS [Dx Ingreso], ps.Secundario as OtrosDx,
ingR.CODDIAEGR AS CodEgreso, dxe.NOMDIAGNO AS [Dx Egreso],    
uf.UFUDESCRI AS UnidadFuncionalEgreso, ing.FECALTPAC AS FechaEgreso, 
CASE ESTPACEGR WHEN 1 THEN 'Mejor' WHEN 2 THEN 'Igual o Peor' WHEN 3 THEN 'Fallecido' WHEN 4 THEN 'Remitido' WHEN 5 THEN 'Hospitalizacion en Casa' END AS [Condicion de Egreso],  
cm.DESCAUMUE AS [Causa Muerte], 
CASE WHEN CONVERT(char(10), ING.FECMUEPAC, 103) = '01/01/1900' THEN ingR.FECHEGRESO ELSE ING.FECMUEPAC END AS [Fecha de Defuncion]

FROM dbo.HCREGEGRE AS ing WITH (NOLOCK)
INNER JOIN dbo.ADINGRESO AS INGR WITH (NOLOCK) ON INGR.NUMINGRES=ING.NUMINGRES
INNER JOIN dbo.INUNIFUNC AS uf ON uf.UFUCODIGO = ing.UFUCODIGO AND ingR.IESTADOIN <> 'A'
INNER JOIN dbo.INPACIENT AS A WITH (NOLOCK) ON ing.IPCODPACI = A.IPCODPACI AND YEAR(ing.FECALTPAC) = '2025'
INNER JOIN dbo.INUBICACI AS D WITH (NOLOCK) ON D.AUUBICACI = A.AUUBICACI 
LEFT OUTER JOIN dbo.ADNIVELES AS E WITH (NOLOCK) ON E.NIVCODIGO = A.NIVCODIGO 
LEFT OUTER JOIN dbo.INUNIFUNC AS ufh ON ufh.UFUCODIGO = ingr.UFUCODIGO AND ingr.IESTADOIN <> 'A'
LEFT OUTER JOIN dbo.ADACTIVID AS F WITH (NOLOCK) ON F.codactivi = A.CODACTIVI 
LEFT OUTER JOIN dbo.ADGRUETNI AS G WITH (NOLOCK) ON G.CODGRUPOE = A.CODGRUPOE 
LEFT OUTER JOIN dbo.SEGusuaru AS H1 WITH (NOLOCK) ON H1.CODUSUARI = A.CODUSUCRE 
LEFT OUTER JOIN dbo.SEGusuaru AS H2 WITH (NOLOCK) ON H2.CODUSUARI = A.CODUSUMOD 
LEFT OUTER JOIN dbo.ADNIVELED AS I WITH (NOLOCK) ON I.NIVECODIGO = A.NIVECODIGO 
LEFT OUTER JOIN dbo.ADDISCAPACI AS W WITH (NOLOCK) ON W.DISCCODIGO = A.DISCCODIGO 
LEFT OUTER JOIN dbo.ADCREDO AS J WITH (NOLOCK) ON J.CREDCODIGO = A.CREDCODIGO 
LEFT OUTER JOIN dbo.INUBICACI AS u WITH (NOLOCK) ON u.AUUBICACI = A.AUUBICACI 
LEFT OUTER JOIN dbo.INMUNICIP AS m WITH (NOLOCK) ON m.DEPMUNCOD = u.DEPMUNCOD 
LEFT OUTER JOIN dbo.INDEPARTA AS DEP WITH (NOLOCK) ON m.DEPCODIGO = DEP.depcodigo 
LEFT OUTER JOIN Contract.HealthAdministrator AS ga WITH (NOLOCK) ON ga.Id = ingR.GENCONENTITY 
LEFT OUTER JOIN dbo.HCHISPACA AS HC WITH (NOLOCK) ON HC.NUMINGRES = ing.NUMINGRES AND ing.NUMEFOLIO=hc.NUMEFOLIO 
LEFT OUTER JOIN dbo.INESPECIA AS ES1 WITH (NOLOCK) ON ES1.CODESPECI = HC.CODESPTRA 
LEFT OUTER JOIN dbo.INDIAGNOS AS dx WITH (NOLOCK) ON dx.CODDIAGNO = ingR.CODDIAING 
LEFT OUTER JOIN dbo.INDIAGNOS AS dxe WITH (NOLOCK) ON dxe.CODDIAGNO = ingR.CODDIAEGR 
INNER JOIN dbo.ADCENATEN AS ca WITH (NOLOCK) ON ca.CODCENATE = ing.CODCENATE 
LEFT OUTER JOIN dbo.INCAUMUER AS cm WITH (NOLOCK) ON cm.CODCAUMUE = ING.CODCAUMUE 

LEFT OUTER JOIN (
	SELECT DISTINCT (NUMINGRES) AS Ingreso, numefolio,  
	STUFF((SELECT ', ' + rtrim(h.CODDIAGNO) + '-' + rtrim(P.NOMDIAGNO)
		   FROM dbo.INDIAGNOP AS h WITH (NOLOCK) 
		   LEFT JOIN dbo.INDIAGNOS AS P WITH (NOLOCK) ON P.CODDIAGNO = H.CODDIAGNO
		   WHERE h.FECDIAGNO >= '2025-01-01' AND H.NUMINGRES = A.NUMINGRES AND h.CODDIAPRI <> 1 
		   FOR XML PATH('')), 1, 2, '') AS Secundario
	FROM INDIAGNOP AS A WITH (NOLOCK)
) AS ps ON ps.Ingreso = ing.NUMINGRES AND ps.Secundario IS NOT NULL AND ps.NUMEFOLIO = ing.NUMEFOLIO

LEFT OUTER JOIN (
	SELECT DISTINCT IPCODPACI AS identi,  
	STUFF((SELECT ', ' + rtrim(Pe1.DESCRIPCION)
		   FROM dbo.ADPOBESPEPAC AS pe WITH (NOLOCK)  
		   INNER JOIN (SELECT IPCODPACI, YEAR(IFECHAING) AS año FROM dbo.ADINGRESO WITH (NOLOCK)
					   WHERE YEAR(IFECHAING) = 2025 GROUP BY IPCODPACI, YEAR(IFECHAING)) AS h  
		   ON h.IPCODPACI = pe.IPCODPACI 
		   INNER JOIN dbo.ADPOBESPE AS PE1 WITH (NOLOCK) ON PE1.ID = pe.IDADPOBESPE AND PE1.ESTADO = 1
		   WHERE pe.ESTADO = 1 AND pe1.ESTADO = 1 AND pe.IPCODPACI = A.IPCODPACI
		   FOR XML PATH('')), 1, 2, '') AS Secundario
	FROM dbo.ADPOBESPEPAC AS a WITH (NOLOCK) 
	WHERE a.ESTADO = 1
) AS ps1 ON ps1.identi = ing.IPCODPACI AND ps.Secundario IS NOT NULL 

WHERE 
--(ing.CODCENATE IN ('001')) AND 
(ing.FECALTPAC BETWEEN '2025-01-01 00:00:00' AND '2025-12-31 23:59:59')
