-- Workspace: SQLServer
-- Item: INDIGO031 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: HC_TrazabilidadRiesgos
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE view [ViewInternal].[HC_TrazabilidadRiesgos] as 
/* ============================
   BLOQUE 1: LABORATORIO
   ============================ */
SELECT 
  PG.NOMBRE AS TipoRiesgo,
  H.NUMINGRES AS Ingreso,
  H.IPCODPACI AS Identificacion,
  PA.IPNOMCOMP AS Paciente,
  H.CODDIAGNO AS CIE10,
  DI.NOMDIAGNO AS DiagnosticoPpal,
  CASE CI.CODESTCIT WHEN '1' THEN 'Cumplida' END AS Estado,
  H.FECHISPAC AS [Fecha Atencion],
  CI.FECHORAIN AS [Fecha Inicial Cita],
  CI.FECHORAFI AS [Fecha Final Cita],
  MHC.DESCRIPCION AS ModeloHC,
  'Laboratorio'  AS [Orden Medica],
  CUPS.CODE AS [Codigo Ordenado],
  CUPS.[DESCRIPTION] AS Descripcion,
  LA.CANTIDAD  AS Cantidad,
  '' AS FechaRegistroDispensacion,
  FACT.FECHA_INGRESO AS FechaToma,
  FACT.Factura,
  '' AS Duracion,
  CA.NOMCENATE AS Sede,
  '' AS CantDespachada,
  '' AS Cantidad_Pendiente_Real,
  CASE
    WHEN CA.codcenate IN (002,003,004,005,006,007,008,009,017,021) THEN 'BOYACA'
    WHEN CA.codcenate IN (010,011,012,013,014,018)                  THEN 'META'
    WHEN CA.codcenate IN (015,016,019,020)                          THEN 'CASANARE'
  END AS Regional
FROM (
  SELECT ID, IPCODPACI
  FROM INDIGO031.dbo.HCHISPACA
  WHERE FECHISPAC >= '2025-07-01'
) AS HC
INNER JOIN (
  SELECT d.IDHCHISPACA, e.VARIABLE, l.NOMBRE
  FROM dbo.EXAVALORES AS d
  INNER JOIN dbo.EXAVARIABLESL AS l
    ON l.IDEXAVARIABLE = d.IDEXAVARIABLE AND l.ID = d.IDITEMLISTA
  INNER JOIN dbo.EXAVARIABLES AS e
    ON e.ID = d.IDEXAVARIABLE
  WHERE d.IDEXAGRUPO = '11' AND d.IDEXAVARIABLE = '142'
) AS PG
  ON PG.IDHCHISPACA = HC.ID
INNER JOIN INDIGO031.dbo.HCHISPACA AS H  WITH (NOLOCK) ON H.ID = HC.ID
INNER JOIN INDIGO031.dbo.INDIAGNOS AS DI WITH (NOLOCK) ON DI.CODDIAGNO = H.CODDIAGNO
INNER JOIN INDIGO031.dbo.INPACIENT AS PA  WITH (NOLOCK) ON PA.IPCODPACI = H.IPCODPACI
INNER JOIN INDIGO031.dbo.ADCONCOEX AS EX WITH (NOLOCK) ON EX.IDHCHISPACA = H.ID
INNER JOIN INDIGO031.dbo.AGASICITA AS CI WITH (NOLOCK) ON CI.CODAUTONU = EX.NUMCONCIT
LEFT  JOIN INDIGO031.dbo.PRMODELOHC AS MHC WITH (NOLOCK) ON H.IDMODELOHC = MHC.ID
INNER JOIN (
  SELECT NUMINGRES, NUMEFOLIO, CODSERIPS, SUM(CANSERIPS) AS Cantidad
  FROM INDIGO031.dbo.HCORDLABO WITH (NOLOCK)
  GROUP BY NUMINGRES, NUMEFOLIO, CODSERIPS
) AS LA
  ON LA.NUMINGRES = H.NUMINGRES AND LA.NUMEFOLIO = H.NUMEFOLIO
LEFT  JOIN INDIGO031.CONTRACT.CUPSENTITY AS CUPS WITH (NOLOCK) ON CUPS.CODE = LA.CODSERIPS
LEFT  JOIN (
  SELECT IDENTIFICACION_PACIENTE, FECHA_INGRESO, CUPS, FACTURA
  FROM [ViewInternal].[VIE_Servicios_Facturados_Laboratorios] WITH (NOLOCK)
  GROUP BY IDENTIFICACION_PACIENTE, FECHA_INGRESO, CUPS, FACTURA
) AS FACT
  ON FACT.IDENTIFICACION_PACIENTE = H.IPCODPACI
 AND FACT.CUPS = CUPS.CODE
 AND FACT.FECHA_INGRESO >= DATEFROMPARTS(YEAR(H.FECHISPAC), MONTH(H.FECHISPAC), 1)
 AND FACT.FECHA_INGRESO <  DATEADD(MONTH, 1, DATEFROMPARTS(YEAR(H.FECHISPAC), MONTH(H.FECHISPAC), 1))
LEFT  JOIN INDIGO031.dbo.ADCENATEN AS CA ON H.CODCENATE = CA.CODCENATE
WHERE 
  CI.CODESTCIT = '1'
  AND (
       H.CODDIAGNO IN ('I10X','I150','I159','E780','E781','E782','E784','E785','E40','E41','E42','E43','E44','E45','E46')
    OR (H.CODDIAGNO BETWEEN 'E100' AND 'E149')
    OR (H.CODDIAGNO BETWEEN 'E660' AND 'E669')
    OR (H.CODDIAGNO BETWEEN 'N181' AND 'N189')
    OR (H.CODDIAGNO BETWEEN 'Z321' AND 'Z359')
    OR (H.CODDIAGNO BETWEEN 'C000' AND 'C999')
  )
  AND (
       (CI.CODSERIPS BETWEEN '890201' AND '890301')  -- Medicina general
    OR (CI.CODSERIPS BETWEEN '890205' AND '890305')  -- Enfermería
    OR (CI.CODSERIPS BETWEEN '890228' AND '890328')  -- Cardiología
    OR (CI.CODSERIPS BETWEEN '890263' AND '890363')  -- Medicina Familiar
    OR (CI.CODSERIPS BETWEEN '890244' AND '890344')  -- Endocrinología
    OR (CI.CODSERIPS BETWEEN '890266' AND '890366')  -- Medicina interna
  )

UNION ALL

/* ============================
   BLOQUE 2: MEDICAMENTOS
   ============================ */
SELECT 
  PG.NOMBRE AS TipoRiesgo,
  H.NUMINGRES AS Ingreso,
  H.IPCODPACI AS Identificacion,
  PA.IPNOMCOMP AS Paciente,
  H.CODDIAGNO AS CIE10,
  DI.NOMDIAGNO AS DiagnosticoPpal,
  CASE CI.CODESTCIT WHEN '1' THEN 'Cumplida' END AS Estado,
  H.FECHISPAC AS [Fecha Atencion],
  CI.FECHORAIN AS [Fecha Inicial Cita],
  CI.FECHORAFI AS [Fecha Final Cita],
  MHC.DESCRIPCION AS ModeloHC,
  'Medicamento' AS [Orden Medica],
  MA.CODPRODUC AS [Codigo Ordenado],
  MA.NAME AS Descripcion,
  MA.Cantidad,
  FACT.FechaRegistroDispensacion,
  FACT.FechaFactura AS FechaToma,
  FACT.Factura,
  CONCAT(MA.VALDURFIJ,' ',
         CASE MA.UNIDURFIJ
           WHEN 1 THEN 'Minutos' WHEN 2 THEN 'Horas' WHEN 3 THEN 'Dias'
           WHEN 4 THEN 'Semanas' WHEN 5 THEN 'Meses' WHEN 6 THEN 'Años'
         END) AS Duracion,
  CA.NOMCENATE AS Sede,
  FACT.CantDespachada,
  FACT.Cantidad_Pendiente_Real,
  CASE
    WHEN CA.codcenate IN (002,003,004,005,006,007,008,009,017,021) THEN 'BOYACA'
    WHEN CA.codcenate IN (010,011,012,013,014,018)                  THEN 'META'
    WHEN CA.codcenate IN (015,016,019,020)                          THEN 'CASANARE'
  END AS Regional
FROM (
  SELECT ID, IPCODPACI
  FROM INDIGO031.dbo.HCHISPACA
  WHERE FECHISPAC >= '2025-01-01'
) AS HC
INNER JOIN (
  SELECT d.IDHCHISPACA, e.VARIABLE, l.NOMBRE
  FROM dbo.EXAVALORES AS d
  INNER JOIN dbo.EXAVARIABLESL AS l
    ON l.IDEXAVARIABLE = d.IDEXAVARIABLE AND l.ID = d.IDITEMLISTA
  INNER JOIN dbo.EXAVARIABLES AS e
    ON e.ID = d.IDEXAVARIABLE
  WHERE d.IDEXAGRUPO = '11' AND d.IDEXAVARIABLE = '142'
) AS PG
  ON PG.IDHCHISPACA = HC.ID
INNER JOIN INDIGO031.dbo.HCHISPACA AS H  WITH (NOLOCK) ON H.ID = HC.ID
INNER JOIN INDIGO031.dbo.INDIAGNOS AS DI WITH (NOLOCK) ON DI.CODDIAGNO = H.CODDIAGNO
INNER JOIN INDIGO031.dbo.INPACIENT AS PA  WITH (NOLOCK) ON PA.IPCODPACI = H.IPCODPACI
INNER JOIN INDIGO031.dbo.ADCONCOEX AS EX WITH (NOLOCK) ON EX.IDHCHISPACA = H.ID
INNER JOIN INDIGO031.dbo.AGASICITA AS CI WITH (NOLOCK) ON CI.CODAUTONU = EX.NUMCONCIT
LEFT  JOIN INDIGO031.dbo.PRMODELOHC AS MHC WITH (NOLOCK) ON H.IDMODELOHC = MHC.ID
INNER JOIN (
  SELECT NUMINGRES, NUMEFOLIO, CODPRODUC, p.NAME, C.CANPEDPRO AS Cantidad, c.VALDURFIJ, c.UNIDURFIJ
  FROM INDIGO031.dbo.HCPRESCRA AS c WITH (NOLOCK)
  INNER JOIN INDIGO031.Inventory.ATC AS p WITH (NOLOCK) ON p.CODE = c.CODPRODUC
  GROUP BY NUMINGRES, NUMEFOLIO, CODPRODUC, p.NAME, C.CANPEDPRO, c.VALDURFIJ, c.UNIDURFIJ
) AS MA
  ON MA.NUMINGRES = H.NUMINGRES AND MA.NUMEFOLIO = H.NUMEFOLIO
LEFT  JOIN (
  SELECT Identificacion_Paciente, Factura, Cod_Medicamento_Insumo, FechaFactura, FechaRegistroDispensacion,
         CantDespachada, Cantidad_Pendiente_Real
  FROM [ViewInternal].[VIE_Servicios_Facturados_Medicamentos_Riesgo] WITH (NOLOCK)
  GROUP BY Identificacion_Paciente, Factura, Cod_Medicamento_Insumo, FechaFactura, FechaRegistroDispensacion,
           CantDespachada, Cantidad_Pendiente_Real
) AS FACT
  ON FACT.Identificacion_Paciente = H.IPCODPACI
 AND FACT.Cod_Medicamento_Insumo = MA.CODPRODUC
 AND FACT.FechaFactura >= DATEFROMPARTS(YEAR(H.FECHISPAC), MONTH(H.FECHISPAC), 1)
 AND FACT.FechaFactura <  DATEADD(MONTH, 1, DATEFROMPARTS(YEAR(H.FECHISPAC), MONTH(H.FECHISPAC), 1))
LEFT  JOIN INDIGO031.dbo.ADCENATEN AS CA ON H.CODCENATE = CA.CODCENATE
WHERE 
  CI.CODESTCIT = '1'
  AND (
       H.CODDIAGNO IN ('I10X','I150','I159','E780','E781','E782','E784','E785','E40','E41','E42','E43','E44','E45','E46')
    OR (H.CODDIAGNO BETWEEN 'E100' AND 'E149')
    OR (H.CODDIAGNO BETWEEN 'E660' AND 'E669')
    OR (H.CODDIAGNO BETWEEN 'N181' AND 'N189')
    OR (H.CODDIAGNO BETWEEN 'Z321' AND 'Z359')
    OR (H.CODDIAGNO BETWEEN 'C000' AND 'C999')
  )
  AND (
       (CI.CODSERIPS BETWEEN '890201' AND '890301')  -- Medicina general
    OR (CI.CODSERIPS BETWEEN '890205' AND '890305')  -- Enfermería
    OR (CI.CODSERIPS BETWEEN '890228' AND '890328')  -- Cardiología
    OR (CI.CODSERIPS BETWEEN '890263' AND '890363')  -- Medicina Familiar
    OR (CI.CODSERIPS BETWEEN '890244' AND '890344')  -- Endocrinología
    OR (CI.CODSERIPS BETWEEN '890266' AND '890366')  -- Medicina interna
  )

UNION ALL

/* ============================================================
   BLOQUE 3: CONSULTA (SIN ORDEN) – SOLO CITAS FILTRADAS POR CUPS
   ============================================================ */
SELECT
  PG.NOMBRE AS TipoRiesgo,
  H.NUMINGRES AS Ingreso,
  H.IPCODPACI AS Identificacion,
  PA.IPNOMCOMP AS Paciente,
  H.CODDIAGNO AS CIE10,
  DI.NOMDIAGNO AS DiagnosticoPpal,
  CASE CI.CODESTCIT WHEN '1' THEN 'Cumplida' END AS Estado,
  H.FECHISPAC AS [Fecha Atencion],
  CI.FECHORAIN AS [Fecha Inicial Cita],
  CI.FECHORAFI AS [Fecha Final Cita],
  MHC.DESCRIPCION AS ModeloHC,
  'Consulta (sin orden)' AS [Orden Medica],
  CI.CODSERIPS AS [Codigo Ordenado],              -- CUPS de la cita
  CUPSCITA.[DESCRIPTION] AS Descripcion,          -- Descripción del CUPS de la cita
  NULL AS Cantidad,
  ''   AS FechaRegistroDispensacion,
  ''   AS FechaToma,
  ''   AS Factura,
  ''   AS Duracion,
  CA.NOMCENATE AS Sede,
  ''   AS CantDespachada,
  ''   AS Cantidad_Pendiente_Real,
  CASE
    WHEN CA.codcenate IN (002,003,004,005,006,007,008,009,017,021) THEN 'BOYACA'
    WHEN CA.codcenate IN (010,011,012,013,014,018)                  THEN 'META'
    WHEN CA.codcenate IN (015,016,019,020)                          THEN 'CASANARE'
  END AS Regional
FROM (
  SELECT ID, IPCODPACI
  FROM INDIGO031.dbo.HCHISPACA
  WHERE FECHISPAC >= '2025-01-01'
) AS HC
INNER JOIN (
  SELECT d.IDHCHISPACA, e.VARIABLE, l.NOMBRE
  FROM dbo.EXAVALORES AS d
  INNER JOIN dbo.EXAVARIABLESL AS l
    ON l.IDEXAVARIABLE = d.IDEXAVARIABLE AND l.ID = d.IDITEMLISTA
  INNER JOIN dbo.EXAVARIABLES AS e
    ON e.ID = d.IDEXAVARIABLE
  WHERE d.IDEXAGRUPO = '11' AND d.IDEXAVARIABLE = '142'
) AS PG
  ON PG.IDHCHISPACA = HC.ID
INNER JOIN INDIGO031.dbo.HCHISPACA AS H  WITH (NOLOCK) ON H.ID = HC.ID
INNER JOIN INDIGO031.dbo.INDIAGNOS AS DI WITH (NOLOCK) ON DI.CODDIAGNO = H.CODDIAGNO
INNER JOIN INDIGO031.dbo.INPACIENT AS PA  WITH (NOLOCK) ON PA.IPCODPACI = H.IPCODPACI
INNER JOIN INDIGO031.dbo.ADCONCOEX AS EX WITH (NOLOCK) ON EX.IDHCHISPACA = H.ID
INNER JOIN INDIGO031.dbo.AGASICITA AS CI WITH (NOLOCK) ON CI.CODAUTONU = EX.NUMCONCIT
LEFT  JOIN INDIGO031.dbo.PRMODELOHC AS MHC WITH (NOLOCK) ON H.IDMODELOHC = MHC.ID
LEFT  JOIN INDIGO031.CONTRACT.CUPSENTITY AS CUPSCITA WITH (NOLOCK) ON CUPSCITA.CODE = CI.CODSERIPS
LEFT  JOIN INDIGO031.dbo.ADCENATEN AS CA ON H.CODCENATE = CA.CODCENATE
WHERE
  CI.CODESTCIT = '1'
  AND (
       H.CODDIAGNO IN ('I10X','I150','I159','E780','E781','E782','E784','E785','E40','E41','E42','E43','E44','E45','E46')
    OR (H.CODDIAGNO BETWEEN 'E100' AND 'E149')
    OR (H.CODDIAGNO BETWEEN 'E660' AND 'E669')
    OR (H.CODDIAGNO BETWEEN 'N181' AND 'N189')
    OR (H.CODDIAGNO BETWEEN 'Z321' AND 'Z359')
    OR (H.CODDIAGNO BETWEEN 'C000' AND 'C999')
  )
  AND (
       (CI.CODSERIPS BETWEEN '890201' AND '890301')  -- Medicina general
    OR (CI.CODSERIPS BETWEEN '890205' AND '890305')  -- Enfermería
    OR (CI.CODSERIPS BETWEEN '890228' AND '890328')  -- Cardiología
    OR (CI.CODSERIPS BETWEEN '890263' AND '890363')  -- Medicina Familiar
    OR (CI.CODSERIPS BETWEEN '890244' AND '890344')  -- Endocrinología
    OR (CI.CODSERIPS BETWEEN '890266' AND '890366')  -- Medicina interna
  )
  -- Evitar duplicados: incluir solo cuando NO hay órdenes
  AND NOT EXISTS (
        SELECT 1
        FROM INDIGO031.dbo.HCORDLABO L WITH (NOLOCK)
        WHERE L.NUMINGRES = H.NUMINGRES AND L.NUMEFOLIO = H.NUMEFOLIO
      )
  AND NOT EXISTS (
        SELECT 1
        FROM INDIGO031.dbo.HCPRESCRA M WITH (NOLOCK)
        WHERE M.NUMINGRES = H.NUMINGRES AND M.NUMEFOLIO = H.NUMEFOLIO
      );

