-- Workspace: SQLServer
-- Item: INDIGO031 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: IND_Laboratorios_Ordenados_Jersalud
-- Extracted by Fabric SQL Extractor SPN v3.9.0


create VIEW [ViewInternal].[IND_Laboratorios_Ordenados_Jersalud]
--ALTER VIEW IND_Laboratorios_Ordenados_Trimestral
AS 

SELECT  
	O.FECORDMED AS FechaOrden, O.IPCODPACI AS Documento, P.IPNOMCOMP AS Paciente, 
	--CONVERT(varchar(10), P.IPFECNACI, 101) AS FechaNacimient, 
	CAST(DATEDIFF(dd, P.IPFECNACI, GETDATE()) / 365.25 AS int) AS EDADATENCION, O.NUMINGRES AS Ingreso, CA.NOMCENATE AS CentroAtencion, U.UFUDESCRI AS Unidad, O.CODPROSAL AS CodProfesional, 
	PROF.NOMMEDICO AS Profesional, O.CODSERIPS AS CUPS, C.DESSERIPS AS Servicio, O.CANSERIPS AS Cant, O.CODDIAGNO AS Cie10, Dx.NOMDIAGNO AS Diagnostico
FROM dbo.HCORDLABO AS O  WITH (NOLOCK) INNER JOIN
	 dbo.INPACIENT AS P WITH (NOLOCK) ON P.IPCODPACI = O.IPCODPACI INNER JOIN
	 dbo.INCUPSIPS AS C WITH (NOLOCK) ON C.CODSERIPS = O.CODSERIPS INNER JOIN
	 dbo.INPROFSAL AS PROF WITH (NOLOCK) ON O.CODPROSAL = PROF.CODPROSAL INNER JOIN
	 dbo.ADCENATEN AS CA WITH (NOLOCK) ON CA.CODCENATE = O.CODCENATE INNER JOIN
	 dbo.INUNIFUNC AS U WITH (NOLOCK) ON U.UFUCODIGO = O.UFUCODIGO INNER JOIN
	 dbo.INDIAGNOS AS Dx WITH (NOLOCK) ON O.CODDIAGNO = Dx.CODDIAGNO
--WHERE O.FECORDMED >= DATEADD(MONTH, -3, GETDATE())
WHERE O.FECORDMED >='2024/01/01 00:00:00' and o.ESTSERIPS<>6

