-- Workspace: SQLServer
-- Item: INDIGO031 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: IND_ImgDX_Ordenadas
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [ViewInternal].[IND_ImgDX_Ordenadas]
as
SELECT DISTINCT   
 IMG.FECORDMED AS FechaOrden, IMG.IPCODPACI AS Documento, P.IPNOMCOMP AS Paciente, P.IPDIRECCI AS Direccion, P.IPTELEFON AS Fijo, P.IPTELMOVI AS Celular, 
 --CONVERT(varchar(10), P.IPFECNACI, 101) AS FechaNacimient,
 P.IPFECNACI AS FechaNacimient, 
 CAST(DATEDIFF(dd, P.IPFECNACI, GETDATE()) / 365.25 AS int) AS EDAD, IMG.NUMINGRES AS Ingreso, CA.NOMCENATE AS CentroAtencion, U.UFUDESCRI AS Unidad, IMG.CODPROSAL AS CodProfesional,   
 PROF.NOMMEDICO AS Profesional, E.DESESPECI AS Especialidad,
 IMG.CODSERIPS AS CUPS, C.DESSERIPS AS Servicio, IMG.CANSERIPS AS Cant, IMG.CODDIAGNO AS Cie10, Dx.NOMDIAGNO AS Diagnostico,
 IMG.OBSSERIPS AS Observaciones,
 case 
	when IMG.OBSSERIPS like '%transcripcion%' then 'Si'  
	when IMG.OBSSERIPS like '%red externa%' then 'Si'  
	when IMG.OBSSERIPS like '%reformulacion%' then 'Si'  
	when IMG.OBSSERIPS like '%especialista%' then 'Si'  
	else 'No' 
 end AS Red_Externa
FROM dbo.HCORDIMAG AS IMG INNER JOIN  
  dbo.INPACIENT AS P ON P.IPCODPACI = IMG.IPCODPACI INNER JOIN  
  dbo.INCUPSIPS AS C ON C.CODSERIPS = IMG.CODSERIPS INNER JOIN  
  dbo.INPROFSAL AS PROF ON IMG.CODPROSAL = PROF.CODPROSAL INNER JOIN  
  dbo.INESPECIA AS E  ON PROF.CODESPEC1 = E.CODESPECI  INNER JOIN 
  dbo.ADCENATEN AS CA ON CA.CODCENATE = IMG.CODCENATE INNER JOIN  
  dbo.INUNIFUNC AS U ON U.UFUCODIGO = IMG.UFUCODIGO INNER JOIN  
  dbo.INDIAGNOS AS Dx ON IMG.CODDIAGNO = Dx.CODDIAGNO  
--WHERE IMG.FECORDMED >= DATEADD(MONTH, -3, GETDATE())   
 
