-- Workspace: SQLServer
-- Item: INDIGO031 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: IND_Remisiones_Rias
-- Extracted by Fabric SQL Extractor SPN v3.9.0

/****** Object:  View [dbo].[IND_ProcedimientoNoQX_Ordenados]    Script Date: 7/21/2022 4:05:56 PM ******/


CREATE VIEW [ViewInternal].[IND_Remisiones_Rias] 
AS
SELECT DISTINCT 
    PP.CODCONCEC, 
    PP.NUMINGRES AS INGRESO, 
    PP.IPCODPACI AS IDENTIFICACION, 
    P.IPNOMCOMP AS PACIENTE, 
    P.IPDIRECCI AS DIRECCION, 
    P.IPTELEFON AS TELEFONO, 
    P.IPTELMOVI AS CECLULAR, 
    P.IPFECNACI AS FECHA_NACIMIENTO, 
    (CAST(DATEDIFF(dd, P.IPFECNACI, GETDATE()) / 365.25 AS INT)) AS EDAD, 
    PP.FECREGSIS AS FECHA_REGISTRO, 
    PP.IDRIAS AS COD_RIAS, 
    R.NOMBRE AS RIAS, 
    PP.JUSNOREPP AS JUSTIFICACION_NO_REMISION, 
    PP.CODPROSAL AS IDENTIFICACION_MEDICO, 
    PROF.NOMMEDICO AS MEDICO, 
    E.DESESPECI AS ESPECIALIDAD, 
    U.UFUDESCRI AS UNIDAD_FUNCIONAL
FROM dbo.HCPPYPPAC AS PP
    INNER JOIN dbo.RIAS AS R ON R.ID = PP.IDRIAS
    INNER JOIN dbo.INUNIFUNC AS U ON U.UFUCODIGO = PP.UFUCODIGO
    INNER JOIN dbo.INPROFSAL AS PROF ON PROF.CODPROSAL = PP.CODPROSAL
    INNER JOIN dbo.INESPECIA AS E ON PROF.CODESPEC1 = E.CODESPECI
    INNER JOIN dbo.INPACIENT AS P ON P.IPCODPACI = PP.IPCODPACI
WHERE PP.FECREGSIS >= DATEADD(MONTH, -3, GETDATE())

