-- Workspace: SQLServer
-- Item: INDIGO031 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: NA_VisitaCaracterizacionECIS-M
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [ViewInternal].[NA_VisitaCaracterizacionECIS-M] AS

     SELECT DISTINCT 
            NP.ID, 
            NP.NUMINGRES AS Ingreso,
            CASE P.IPTIPODOC
                WHEN 1 THEN 'CC'
                WHEN 2 THEN 'CE'
                WHEN 3 THEN 'TI'
                WHEN 4 THEN 'RC'
                WHEN 5 THEN 'PA'
                WHEN 6 THEN 'AS'
                WHEN 7 THEN 'MS'
                WHEN 8 THEN 'NU'
            END AS Tipo_Documento_Paciente, 
            NP.IPCODPACI AS Paciente, 
            P.IPNOMCOMP AS Nombre_Paciente, 
            P.IPDIRECCI AS Direccion, 
            P.IPTELEFON AS Telefono, 
            P.IPTELMOVI AS Celular, 
            P.IPFECNACI AS Fecha_Nacimiento, 
            (CAST(DATEDIFF(dd, P.IPFECNACI, GETDATE()) / 365.25 AS INT)) AS Edad, 
            NP.FECHACREACION AS Fecha_Nota, 
            TN.NOMBRE AS Nombre_Nota, 
            --PR.NOMMEDICO AS Medico, 
            CA.NOMCENATE AS Centro_Atencion,
			US.NOMUSUARI AS USUARIO,
     (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 103
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'Observaciones ECIS', 
     (
		 SELECT TVL.NOMBRE
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
              LEFT JOIN dbo.NTVARIABLESL AS TVL  ON TVL.CODIGO = ND.VALOR
                                                                                  AND TVL.IDNTVARIABLE = ND.IDNTVARIABLE
         WHERE ND.IDNTVARIABLE = 104
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS Grupo, 
	 (
      SELECT TVL.NOMBRE
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
              LEFT JOIN dbo.NTVARIABLESL AS TVL  ON TVL.CODIGO = ND.VALOR
                                                                                  AND TVL.IDNTVARIABLE = ND.IDNTVARIABLE
         WHERE ND.IDNTVARIABLE = 30
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'RESULTADO DE LA LLAMADA O DE LA VISITA DOCIMILIARIA',
     (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 111
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'Fecha Visita Realizada', 
     (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 112
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'Plan integral de cuidado primario', 
     (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 113
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'Educacion en salud realizada',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 4
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'ATENCIÓN AL PUERPERIO',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 5
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'ATENCIÓN AL RECIÉN NACIDO',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 6
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'PLANIFICACIÓN FAMILIAR Y ANTICONCEPCIÓN',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 7
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'PROGRAMA DE PRIMERA INFANCIA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 8
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'PROGRAMA DE INFANCIA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 9
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'PROGRAMA DE ADOLESCENCIA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 10
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'PROGRAMA DE JUVENTUD',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 11
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'PROGRAMA DE ADULTEZ',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 12
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'PROGRAMA DE VEJEZ',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 13
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'ATENCIÓN AL CUIDADO PRENATAL',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 14
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'CURSO DE PREPARACIÓN PARA LA MATERNIDAD Y LA PATERNIDAD',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 15
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'SALUD BUCAL',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 16
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'DETECCIÓN TEMPRANA DE CÁNCER DE CUELLO UTERINO',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 17
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'DETECCIÓN TEMPRANA DE CÁNCER DE MAMA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 18
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'DETECCIÓN TEMPRANA DE CÁNCER DE PRÓSTATA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 19
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'DETECCIÓN TEMPRANA DE CÁNCER DE COLON Y RECTO',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 20
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'ATENCION AL CUIDADO PRECONCEPCIONAL',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 21
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'VACUNACIÓN',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 22
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'APOYO A LA LACTANCIA MATERNA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 24
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'SINDROME METABÓLICO',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 25
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'ATENCIÓN A VÍCTIMAS DE VIOLENCIA SEXUAL',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 114
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'MEDICINA GENERAL',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 115
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'ODONTOLOGIA GENERAL',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 116
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'PSICOLOGIA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 117
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'NUTRICION',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 118
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'PEDIATRIA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 34
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR MEDICINA GENERAL',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 35
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR MEDICINA ESPECIALIZADA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 36
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR ODONTOLOGIA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 37
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR ENFERMERIA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 38
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR NUTRICION Y DIETETICA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 39
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR PSICOLOGIA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 40
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR TRABAJO SOCIAL',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 41
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR FISIOTERAPIA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 42
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR TERAPIA OCUPACIONAL',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 43
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR FONIATRIA Y FONOAUDIOLOGIA',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 44
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR AGENTE EDUCATIVO',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 45
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR HIGIENE ORAL',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 46
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR EQUIPO INTERDISCIPLINARIO',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 47
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR EQUIPO INTERDISCIPLINARIO Y COMUNICACION EN POBLACION INFANTIL Y ADOLESCENTE',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 48
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR EQUIPO INTERDISCIPLINARIO Y COMUNICACION EN POBLACION DE HOMBRES Y MUJERES EN EDAD FERTIL',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 49
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR EQUIPO INTERDISCIPLINARIO Y COMUNICACION EN POBLACION DE MUJERES GESTANTES Y LACTANTES',
	 (
         SELECT ND.VALOR
         FROM dbo.NTNOTASADMINISTRATIVASD AS ND 
         WHERE ND.IDNTVARIABLE = 50
               AND ND.IDNTNOTASADMINISTRATIVASC = NP.ID
     ) AS 'EDUCACION INDIVIDUAL EN SALUD POR EQUIPO INTERDISCIPLINARIO Y COMUNICACION EN POBLACION DE ADULTO MAYOR'

     FROM dbo.NTNOTASADMINISTRATIVASC AS NP 
          INNER JOIN dbo.NTADMINISTRATIVAS AS TN  ON TN.ID = NP.IDNOTAADMINISTRATIVA
          INNER JOIN dbo.INPACIENT AS P  ON P.IPCODPACI = NP.IPCODPACI
          INNER JOIN dbo.ADCENATEN AS CA  ON CA.CODCENATE = NP.CODCENATE
          --INNER JOIN dbo.INPROFSAL AS PR  ON PR.CODPROSAL = NP.CODUSUARI
		  INNER JOIN dbo.SEGusuaru AS US ON US.CODUSUARI = NP.CODUSUARI
     WHERE 
TN.ID='8'  --and NP.ID='233326'
--ORDER BY NP.FECHACREACION DESC


--select * from dbo.NTNOTASADMINISTRATIVASC
--where IPCODPACI='40512641' and ID='233326'
--select * from dbo.NTNOTASADMINISTRATIVASD
--where IDNTNOTASADMINISTRATIVASC='233326'
--select * from dbo.NTVARIABLES
--where ID in('103','104','111','112','113')


--select * from dbo.NTADMINISTRATIVAS
