-- Workspace: SQLServer
-- Item: INDIGO031 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: PlanesTratamientosOdontologicos_Trimestral
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [ViewInternal].[PlanesTratamientosOdontologicos_Trimestral]  
AS  
SELECT OC.ID, CA.NOMCENATE AS CentroAtencion, U.UFUDESCRI AS Unidad, OC.IPCODPACI AS Documento, P.IPNOMCOMP AS Paciente, P.IPDIRECCI AS Direccion,   
    P.IPTELEFON AS Fijo, P.IPTELMOVI AS Celular, CONVERT(varchar(10), P.IPFECNACI, 101) AS FechaNacimiento,  
    CAST(DATEDIFF(dd, P.IPFECNACI, GETDATE()) / 365.25 AS int) AS EDAD, OC.NUMINGRES AS Ingreso, OC.NUMEFOLIO AS Folio, OC.CODPROSAL AS CodProfesional,PROF.NOMMEDICO AS Profesional,  
    OC.FECHAREG AS Fecha_Registro, OC.OBSERVACIONESGENERA AS Observacion, OC.IDRIASCUPS AS RIAS, TRA.DESCRITRA AS Tratamiento_Ordenado,   
    CASE   
   WHEN PLANTRA.ESTADO = '1' THEN 'Sin realizar'  
   WHEN PLANTRA.ESTADO = '2' THEN 'Realizado'  
   WHEN PLANTRA.ESTADO = '3' THEN 'No realizado'  
   WHEN PLANTRA.ESTADO = '4' THEN 'Cancelado'  
    END AS Estado_Tratamiento,  
    PLANTRA.FECHAORDENO AS Fecha_Ordeno, (SELECT P1.NOMMEDICO FROM dbo.INPROFSAL as P1 WHERE P1.CODPROSAL=PLANTRA.PROFESIONALORDENO) AS Profesional_Ordeno,  
    PLANTRA.FECHAREALIZO AS Fecha_Realizo,(SELECT P2.NOMMEDICO FROM dbo.INPROFSAL as P2 WHERE P2.CODPROSAL=PLANTRA.PROFESIONALREALIZO) AS Profesional_Realizo,  
    PLANTRA.FECHACANCELO AS Fecha_Cancelo, (SELECT P3.NOMMEDICO FROM dbo.INPROFSAL as P3 WHERE P3.CODPROSAL=PLANTRA.PROFESIONALCANCELO) AS Profesional_Cancelo  
  FROM dbo.ODONTOCONTROL AS OC LEFT JOIN  
    dbo.ODONTOPLANTRATAMIENTOPACD AS PLANTRA ON PLANTRA.IDODONTOCONTROL=OC.ID INNER JOIN  
    dbo.ODOPARTRA AS TRA ON TRA.CONSECTRA=PLANTRA.IDODOPARTRA INNER JOIN  
    dbo.INPACIENT AS P ON P.IPCODPACI = OC.IPCODPACI INNER JOIN  
    dbo.INPROFSAL AS PROF ON OC.CODPROSAL = PROF.CODPROSAL INNER JOIN  
    dbo.ADCENATEN AS CA ON CA.CODCENATE = OC.CODCENATE INNER JOIN  
    dbo.INUNIFUNC AS U ON U.UFUCODIGO = OC.UFUCODIGO    
 WHERE PLANTRA.FECHAORDENO >= DATEADD(MONTH, -4, GETDATE())  
 --order by PLANTRA.FECHAORDENO DESC  

