-- Workspace: SQLServer
-- Item: INDIGO031 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: Ruta_OrdenCancerProstata
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE view ViewInternal.Ruta_OrdenCancerProstata as
SELECT DISTINCT  CASE
                 WHEN ca.codcenate IN(002, 003, 004, 005, 006, 007, 008, 009,017,021)
                THEN 'BOYACA'
                WHEN ca.codcenate IN(010, 011, 012, 013, 014,018)
                THEN 'META'
                WHEN ca.codcenate IN (015,016,019,020)
                THEN 'CASANARE'
            END AS Regional,  ING.IFECHAING AS FECHA_INGRESO, ING.NUMINGRES AS INGRESO, LTRIM(RTRIM(CA.NOMCENATE)) AS CENTRO_ATENCION, 
				ING.IPCODPACI AS IDENTIFICACION_PACIENTE, C.CODSERIPS AS CUPS, C.DESSERIPS AS CUPS_DESCRIPCION, H.FECORDMED AS Fecha,
				DATEDIFF(year, P.IPFECNACI, ING.IFECHAING) AS EdadEnAtencion, H.*
FROM INDIGO031.DBO.HCORDLABO AS H WITH (NOLOCK)
INNER JOIN INDIGO031.DBO.INCUPSIPS AS C WITH (NOLOCK) ON C.CODSERIPS=H.CODSERIPS
INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES=H.NUMINGRES
INNER JOIN dbo.ADCENATEN AS CA WITH (NOLOCK) ON CA.CODCENATE = ING.CODCENATE
INNER JOIN dbo.INPACIENT AS P  ON P.IPCODPACI = ING.IPCODPACI
WHERE H.CODSERIPS IN ('906611','906612','906610') AND H.ESTSERIPS<>'6'