-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_ACTIVIDADES_AGENDAMIENTO
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW ViewInternal.VW_ACTIVIDADES_AGENDAMIENTO
AS
     SELECT ACT.CODACTMED AS COD_ACT, 
            ACT.DESACTMED AS DESC_ACT, 
            ACT.ESTADOACT AS ESTADO_ACT, 
            ACT.CODSERIPS AS ACT_RIPS, 
            ACT.DURAACTIV AS 'DURACION PRIMERA VEZ', 
            ACT.CODSERIPS AS 'CUPS PRIMERA VEZ', 
            ACT.DURAACTIVCONTROL AS 'DURACION CONTROL', 
            ACT.CODSERIPSCONTROL AS 'CUPS CONTROL', 
            ACT.CTRCITASD AS 'CONTROL CITAS DIARIAS', 
            ACT.NUMCITASD AS 'NUMERO CITAS DIARIAS', 
            ACT.CTRCITASM AS 'CONTROL CITAS MENSUALES', 
            ACT.NUMCITASM AS 'NUMERO CITAS MENSUALES', 
            MHC.ID AS ID_MHC, 
            MHC.CODIGO AS COD_MHC, 
            MHC.NOMBRE AS MHC, 
            MHC.DESCRIPCION AS DESC_MHC, 
            MHC.ESTADO AS ESTADO_MHC, 
            R.NOMBRE AS RIAS
     FROM [INDIGO031].[dbo].[AGACTIMED] AS ACT
          LEFT JOIN [INDIGO031].[dbo].[PRHCXACT] AS RAM ON RAM.CODACTMED = ACT.CODACTMED
          LEFT JOIN [INDIGO031].[dbo].[PRMODELOHC] AS MHC ON MHC.ID = RAM.IDMODELOHC
          LEFT JOIN [INDIGO031].[dbo].[RIASCUPS] AS RIC ON ACT.IDRIASCUPS = RIC.ID
          LEFT OUTER JOIN [INDIGO031].[dbo].[RIAS] AS R ON RIC.IDRIAS = R.ID
     WHERE ACT.ESTADOACT = '1';
