-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_HC_TRAZABILIDADRIESGOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW ViewInternal.VW_HC_TRAZABILIDADRIESGOS 
AS 

SELECT 
 pg.NOMBRE AS TipoRiesgo,
 H.NUMINGRES AS Ingreso,
 H.IPCODPACI AS Identificacion,
 PA.IPNOMCOMP AS Paciente,
 H.CODDIAGNO AS CIE10,
 DI.NOMDIAGNO AS DiagnosticoPpal,
 CASE CI.CODESTCIT WHEN '1' THEN 'Cumplida' END AS Estado,
 H.FECHISPAC AS [Fecha Atencion],
 CI.FECHORAIN AS [Fecha Inicial Cita],
 CI.FECHORAFI AS [Fecha Final Cita],
   MHC.DESCRIPCION AS ModeloHC,
  'Laboratorio'  AS 'Orden Medica',

 CUPS.Code AS [Codigo Ordenado],
 CUPS.Description aS Descripcion,
LA.Cantidad  AS Cantidad, '' as FechaRegistroDispensacion, FACT.FECHA_INGRESO as FechaToma, FACT.FACTURA,
'' AS Duracion, ca.NOMCENATE AS Sede,
'' as CantDespachada, '' as Cantidad_Pendiente_Real,
CASE
                 WHEN ca.CODCENATE IN(002, 003, 004, 005, 006, 007, 008, 009,017,021)
                THEN 'BOYACA'
                WHEN ca.CODCENATE IN(010, 011, 012, 013, 014,018)
                THEN 'META'
                WHEN ca.CODCENATE IN (015,016,019,020)
                THEN 'CASANARE'
            END AS Regional

FROM 
(
   SELECT --MIN(Id) AS Id
   ID, IPCODPACI
   FROM [INDIGO031].[dbo].[HCHISPACA]
   WHERE FECHISPAC>='01/07/2025'
   --GROUP BY IPCODPACI
) AS HC
INNER JOIN (
    SELECT 
        d.IDHCHISPACA, 
        e.VARIABLE, 
        l.NOMBRE
		
    FROM [INDIGO031].[dbo].[EXAVALORES] AS d 
    INNER JOIN [INDIGO031].[dbo].[EXAVARIABLESL] AS l 
        ON l.IDEXAVARIABLE = d.IDEXAVARIABLE AND l.ID = d.IDITEMLISTA
    INNER JOIN [INDIGO031].[dbo].[EXAVARIABLES] AS e 
        ON e.ID = d.IDEXAVARIABLE
    WHERE d.IDEXAGRUPO = '11' AND d.IDEXAVARIABLE = '142'
) AS pg ON pg.IDHCHISPACA=HC.ID

INNER JOIN [INDIGO031].[dbo].[HCHISPACA] AS H   ON H.ID=HC.ID 
INNER JOIN [INDIGO031].[dbo].[INDIAGNOS] AS DI   ON DI.CODDIAGNO = H.CODDIAGNO
INNER JOIN [INDIGO031].[dbo].[INPACIENT] AS PA   ON PA.IPCODPACI = H.IPCODPACI
INNER JOIN [INDIGO031].[dbo].[ADCONCOEX] AS EX   ON EX.IDHCHISPACA = H.ID
INNER JOIN [INDIGO031].[dbo].[AGASICITA] AS CI   ON CI.CODAUTONU = EX.NUMCONCIT 
LEFT OUTER JOIN [INDIGO031].[dbo].[PRMODELOHC]   AS MHC  ON H.IDMODELOHC = MHC.ID
INNER JOIN (SELECT NUMINGRES, NUMEFOLIO, CODSERIPS, SUM(CANSERIPS) AS Cantidad
				 FROM [INDIGO031].[dbo].[HCORDLABO] 
				 GROUP BY NUMINGRES, NUMEFOLIO, CODSERIPS) AS LA ON LA.NUMINGRES = H.NUMINGRES AND LA.NUMEFOLIO = H.NUMEFOLIO
LEFT OUTER JOIN [INDIGO031].[Contract].[CUPSEntity] AS CUPS  ON CUPS.Code = LA.CODSERIPS
LEFT OUTER JOIN (SELECT IDENTIFICACION_PACIENTE, FECHA_INGRESO, CUPS, FACTURA
				  FROM [DataWareHouse_Finance].[ViewInternal].[VW_VIE_SERVICIOS_FACTURADOS_LABORATORIOS]
				  --where  IDENTIFICACION_PACIENTE='40416907'
				  GROUP BY IDENTIFICACION_PACIENTE, FECHA_INGRESO, CUPS, FACTURA) AS FACT ON FACT.IDENTIFICACION_PACIENTE= H.IPCODPACI AND FACT.CUPS=CUPS.Code AND FORMAT(FACT.FECHA_INGRESO, 'MM-yyyy') = FORMAT( H.FECHISPAC, 'MM-yyyy')
left join INDIGO031.dbo.ADCENATEN ca  ON H.CODCENATE = ca.CODCENATE

WHERE --H.NUMINGRES='006F754909'
  CI.CODESTCIT = '1' AND H.CODDIAGNO IN ('I10X', 'I150', 'I159','E780', 'E781', 'E782', 'E784', 'E785','E40', 'E41', 'E42', 'E43', 'E44', 'E45', 'E46') 
	  OR (H.CODDIAGNO BETWEEN 'E100' AND 'E149')
	  OR (H.CODDIAGNO BETWEEN 'E660' AND 'E669') 
	  OR (H.CODDIAGNO BETWEEN 'N181' AND 'N189')
      OR (H.CODDIAGNO BETWEEN 'Z321' AND 'Z359') 
	  OR (H.CODDIAGNO BETWEEN 'C000' AND 'C999')  


UNION ALL

--SELECT * FROM (
SELECT 

 pg.NOMBRE AS TipoRiesgo,
 H.NUMINGRES AS Ingreso,
 H.IPCODPACI AS Identificacion,
 PA.IPNOMCOMP AS Paciente,
 H.CODDIAGNO AS CIE10,
 DI.NOMDIAGNO AS DiagnosticoPpal,
 CASE CI.CODESTCIT WHEN '1' THEN 'Cumplida' END AS Estado,
 H.FECHISPAC AS [Fecha Atencion],
 CI.FECHORAIN AS [Fecha Inicial Cita],
 CI.FECHORAFI AS [Fecha Final Cita],
   MHC.DESCRIPCION AS ModeloHC,
 'Medicamento'  AS 'Orden Medica',

 MA.CODPRODUC AS [Codigo Ordenado],
 MA.Name aS Descripcion,
--'' AS Cantidad, 
MA.Cantidad, FechaRegistroDispensacion,  FACT.FechaFactura as FechaToma, FACT.Factura,
CONCAT(MA.VALDURFIJ,' ',CASE MA.UNIDURFIJ WHEN 1 THEN 'Minutos' WHEN 2 THEN 'Horas' when 3 then 'Dias' when 4 then 'Semanas' when 5 then 'Meses' when 6 then 'Años' END) AS Duracion
, ca.NOMCENATE AS Sede,
FACT.CantDespachada,FACT.Cantidad_Pendiente_Real,
CASE
                 WHEN ca.CODCENATE IN(002, 003, 004, 005, 006, 007, 008, 009,017,021)
                THEN 'BOYACA'
                WHEN ca.CODCENATE IN(010, 011, 012, 013, 014,018)
                THEN 'META'
                WHEN ca.CODCENATE IN (015,016,019,020)
                THEN 'CASANARE'
            END AS Regional

FROM 
(
   SELECT --MAX(Id) AS Id,
   ID, IPCODPACI
   FROM [INDIGO031].[dbo].[HCHISPACA]
   WHERE FECHISPAC>='01/01/2025'
   --GROUP BY IPCODPACI
) AS HC
INNER JOIN (
    SELECT 
        d.IDHCHISPACA, 
        e.VARIABLE, 
        l.NOMBRE
		
    FROM [INDIGO031].[dbo].[EXAVALORES] AS d 
    INNER JOIN [INDIGO031].[dbo].[EXAVARIABLESL] AS l 
        ON l.IDEXAVARIABLE = d.IDEXAVARIABLE AND l.ID = d.IDITEMLISTA
    INNER JOIN [INDIGO031].[dbo].[EXAVARIABLES] AS e 
        ON e.ID = d.IDEXAVARIABLE
    WHERE d.IDEXAGRUPO = '11' AND d.IDEXAVARIABLE = '142'
) AS pg ON pg.IDHCHISPACA=HC.ID


INNER JOIN [INDIGO031].[dbo].[HCHISPACA] AS H   ON H.ID=HC.ID 
INNER JOIN [INDIGO031].[dbo].[INDIAGNOS] AS DI   ON DI.CODDIAGNO = H.CODDIAGNO
INNER JOIN [INDIGO031].[dbo].[INPACIENT] AS PA   ON PA.IPCODPACI = H.IPCODPACI
INNER JOIN [INDIGO031].[dbo].[ADCONCOEX] AS EX   ON EX.IDHCHISPACA = H.ID
INNER JOIN [INDIGO031].[dbo].[AGASICITA] AS CI   ON CI.CODAUTONU = EX.NUMCONCIT 
LEFT OUTER JOIN [INDIGO031].[dbo].[PRMODELOHC]   AS MHC  ON H.IDMODELOHC = MHC.ID
INNER JOIN (SELECT  NUMINGRES, NUMEFOLIO, CODPRODUC, p.Name, c.CANPEDPRO AS Cantidad, c.VALDURFIJ, c.UNIDURFIJ
				 FROM [INDIGO031].[dbo].[HCPRESCRA] as c 
				 INNER JOIN [INDIGO031].[Inventory].[ATC] as p  on p.Code=c.CODPRODUC
				 --WHERE NUMINGRES='006F754909'
				 GROUP BY NUMINGRES, NUMEFOLIO, CODPRODUC, p.Name, c.CANPEDPRO, c.VALDURFIJ, c.UNIDURFIJ ) AS MA ON MA.NUMINGRES = H.NUMINGRES AND MA.NUMEFOLIO = H.NUMEFOLIO

LEFT JOIN (SELECT Identificacion_Paciente, Factura, Cod_Medicamento_Insumo, FechaFactura, FechaRegistroDispensacion,CantDespachada, Cantidad_Pendiente_Real
			FROM [DataWareHouse_Finance].[ViewInternal].[VW_VIE_SERVICIOS_FACTURADOS_MEDICAMENTOS_RIESGO] 
			--WHERE Identificacion_Paciente='40416907'
			group by Identificacion_Paciente, Factura, Cod_Medicamento_Insumo, FechaFactura, FechaRegistroDispensacion,CantDespachada, Cantidad_Pendiente_Real) AS FACT ON FACT.Identificacion_Paciente= H.IPCODPACI AND Cod_Medicamento_Insumo=MA.CODPRODUC 
			AND FORMAT(FACT.FechaFactura, 'MM-yyyy') = FORMAT(H.FECHISPAC, 'MM-yyyy') 
left join INDIGO031.dbo.ADCENATEN ca  ON H.CODCENATE = ca.CODCENATE

WHERE--H.NUMINGRES='006F754909'
  CI.CODESTCIT = '1' AND H.CODDIAGNO IN ('I10X', 'I150', 'I159','E780', 'E781', 'E782', 'E784', 'E785','E40', 'E41', 'E42', 'E43', 'E44', 'E45', 'E46') 
	  OR (H.CODDIAGNO BETWEEN 'E100' AND 'E149')
	  OR (H.CODDIAGNO BETWEEN 'E660' AND 'E669') 
	  OR (H.CODDIAGNO BETWEEN 'N181' AND 'N189')
      OR (H.CODDIAGNO BETWEEN 'Z321' AND 'Z359') 
	  OR (H.CODDIAGNO BETWEEN 'C000' AND 'C999')  
	  

