-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_HC_ORDENESPROCEDIMIENTOSNOQX
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW ViewInternal.VW_HC_ORDENESPROCEDIMIENTOSNOQX
AS

SELECT 
    'Orden Extramural' AS Tipo,  
    Cent.NOMCENATE AS Sede, 
    CASE
        WHEN Q.CODCENATE IN(002, 003, 004, 005, 006, 007, 008, 009,017,021) THEN 'BOYACA'
        WHEN Q.CODCENATE IN(010, 011, 012, 013, 014,018) THEN 'META'
        WHEN Q.CODCENATE IN (015,016,019,020) THEN 'CASANARE'
    END AS Regional,
    Q.NUMINGRES AS Ingreso,  
    I.IFECHAING AS FechaIngreso,
    CASE IPTIPODOC 
        WHEN 1 THEN 'CC' WHEN 2 THEN 'CE' WHEN 3 THEN 'TI' WHEN 4 THEN 'RC' WHEN 5 THEN 'PA' 
        WHEN 6 THEN 'AS' WHEN 7 THEN 'MS' WHEN 8 THEN 'NU' WHEN 9 THEN  'CN' WHEN 10 THEN 'CD' 
        WHEN 11 THEN 'SC' WHEN 12 THEN 'PE'  WHEN 13 THEN 'PT' WHEN 14 THEN 'DE'  WHEN 15 THEN 'SI' 
    END AS TipoIdentificacion, 
    Q.IPCODPACI AS Documento, 
    P.IPPRINOMB AS [PrimerNombre], 
    P.IPSEGNOMB  AS [SegundoNombre], 
    P.IPPRIAPEL AS [PrimerApellido], 
    P.IPSEGAPEL AS [SegundoApellido],
    CASE WHEN P.IPSEXOPAC = '1' THEN 'Masculino' WHEN P.IPSEXOPAC = '2' THEN 'Femenino' END AS Sexo,
    Q.CODSERIPS AS CUPS,
    S.DESSERIPS AS Desc_CUPS,
    th.Nit, 
    ha.Name AS Entidad, 
    D.CODDIAGNO AS Cie10, 
    D.NOMDIAGNO AS Diagnostico, 
    Q.FECORDMED AS FechaOrden, 
    PRO.NOMMEDICO AS ProfesionalOrdena,
    F.UFUCODIGO AS CodUFSol, 
    F.UFUDESCRI AS UnidadFuncionalSolicitud,
    CASE PRISERIPS WHEN 1 THEN 'Urgente' WHEN 2 THEN 'Rutina' END AS Prioridad, 
    Q.OBSSERIPS AS Observacion, 
    C.DESESPECI AS EspecialidadTratante,
    ga.Code AS CodGrupoAtencion,    
    ga.Name AS GrupoAtencion,
    I.IOBSERVAC AS ObservaciónIngreso,
    HCU.ENFACTUAL AS Enfermedad_Actual, 
    em.FECALTPAC AS [Fecha alta Médica], 
    '' AS ActividadCita,
    '' AS EstadoCita,
    '' AS FechaInicialCita, 
    '' AS FechaFinalCita 
FROM INDIGO031.dbo.HCORDPRON Q  
    INNER JOIN INDIGO031.dbo.INPACIENT P  ON P.IPCODPACI = Q.IPCODPACI 
    INNER JOIN INDIGO031.dbo.ADCENATEN Cent  ON Cent.CODCENATE = Q.CODCENATE 
    INNER JOIN INDIGO031.dbo.ADINGRESO I  ON I.NUMINGRES = Q.NUMINGRES 
    LEFT JOIN INDIGO031.dbo.CHCAMASHO CA  ON CA.CODICAMAS = I.CODCAMACT
    LEFT JOIN INDIGO031.dbo.ADACTIVID L  ON P.CODACTIVI = L.codactivi 
    INNER JOIN INDIGO031.dbo.INUNIFUNC F  ON F.UFUCODIGO = Q.UFUCODIGO 
    LEFT JOIN INDIGO031.dbo.INENTIDAD E  ON E.CODENTIDA = P.CODENTIDA 
    LEFT JOIN INDIGO031.dbo.INCUPSIPS S  ON S.CODSERIPS = Q.CODSERIPS 
    LEFT JOIN INDIGO031.dbo.INDIAGNOS D  ON D.CODDIAGNO = Q.CODDIAGNO 
    LEFT JOIN INDIGO031.dbo.INPROFSAL PRO  ON PRO.CODPROSAL = Q.CODPROSAL 
    LEFT JOIN INDIGO031.dbo.HCHISPACA hc ON hc.NUMINGRES = Q.NUMINGRES AND hc.NUMEFOLIO = Q.NUMEFOLIO 
    LEFT JOIN INDIGO031.dbo.HCURGING1 AS HCU ON HCU.NUMINGRES = hc.NUMINGRES AND HCU.IPCODPACI = hc.IPCODPACI AND HCU.NUMEFOLIO = hc.NUMEFOLIO 
    LEFT JOIN INDIGO031.dbo.HCREGEGRE AS em ON em.IPCODPACI = hc.IPCODPACI AND em.NUMINGRES = hc.NUMINGRES 
    LEFT OUTER JOIN INDIGO031.dbo.INESPECIA C  ON C.CODESPECI = hc.CODESPTRA  
    LEFT JOIN INDIGO031.Contract.HealthAdministrator AS ha ON ha.Id = I.GENCONENTITY
    LEFT OUTER JOIN INDIGO031.Common.ThirdParty AS th ON th.Id = ha.ThirdPartyId 
    LEFT OUTER JOIN INDIGO031.Contract.CareGroup AS ga ON ga.Id = I.GENCAREGROUP 
    LEFT OUTER JOIN INDIGO031.dbo.SEGusuaru AS us ON us.CODUSUARI = Q.PROANULADO
WHERE
    Q.SOLICITASALA = 0 
    AND S.SERIPSDASH IN (12,9,8) 
    AND Q.ESTSERIPS <> '5' 
    AND FECORDMED >= '01-01-2025' 
    AND Q.IPCODPACI <> '0123456789'

UNION ALL

SELECT 
    'Ambulatorio' AS Tipo,
    Cent.NOMCENATE AS Sede, 
    CASE
        WHEN Q.CODCENATE IN(002, 003, 004, 005, 006, 007, 008, 009,017,021) THEN 'BOYACA'
        WHEN Q.CODCENATE IN(010, 011, 012, 013, 014,018) THEN 'META'
        WHEN Q.CODCENATE IN (015,016,019,020) THEN 'CASANARE'
    END AS Regional, 
    Q.NUMINGRES AS Ingreso,  
    I.IFECHAING AS FechaIngreso,
    CASE IPTIPODOC 
        WHEN 1 THEN 'CC' WHEN 2 THEN 'CE' WHEN 3 THEN 'TI' WHEN 4 THEN 'RC' WHEN 5 THEN 'PA' 
        WHEN 6 THEN 'AS' WHEN 7 THEN 'MS' WHEN 8 THEN 'NU' WHEN 9 THEN  'CN' WHEN 10 THEN 'CD' 
        WHEN 11 THEN 'SC' WHEN 12 THEN 'PE'  WHEN 13 THEN 'PT' WHEN 14 THEN 'DE'  WHEN 15 THEN 'SI' 
    END AS TipoIdentificacion, 
    Q.IPCODPACI AS Documento, 
    P.IPPRINOMB AS [PrimerNombre], 
    P.IPSEGNOMB  AS [SegundoNombre], 
    P.IPPRIAPEL AS [PrimerApellido], 
    P.IPSEGAPEL AS [SegundoApellido],
    CASE WHEN P.IPSEXOPAC = '1' THEN 'Masculino' WHEN P.IPSEXOPAC = '2' THEN 'Femenino' END AS Sexo,
    Q.CODSERIPS AS CUPS, 
    S.DESSERIPS AS Desc_CUPS,
    th.Nit,  
    ha.Name AS Entidad, 
    '' AS Cie10,
    '' AS Diagnostico, 
    Q.FECHAREG AS FechaOrden,  
    PRO.NOMMEDICO AS ProfesionalOrdena,
    F.UFUCODIGO AS CodUFSol, 
    F.UFUDESCRI AS UnidadFuncionalSolicitud,
    '' AS Prioridad, 
    Q.OBSERVACION AS Observacion,
    C.DESESPECI AS EspecialidadTratante,
    ga.Code AS CodGrupoAtencion,  
    ga.Name AS GrupoAtencion,
    I.IOBSERVAC AS ObservaciónIngreso,
    '' AS Enfermedad_Actual, 
    '' AS [Fecha alta Médica], 
    AC.DESACTMED AS ActividadCita,
    CASE CI.CODESTCIT
        WHEN '0' THEN 'Asignada'
        WHEN '1' THEN 'Cumplida'
        WHEN '2' THEN 'Incumplida'
        WHEN '3' THEN 'Preasignada'
        WHEN '4' THEN 'Cancelada'
        WHEN '5' THEN 'Inatención'
    END AS EstadoCita,
    CI.FECHORAIN AS FechaInicialCita, 
    CI.FECHORAFI AS FechaFinalCita
FROM INDIGO031.dbo.AMBORDOTROSPRO Q  
    INNER JOIN INDIGO031.dbo.INPACIENT P  ON P.IPCODPACI = Q.IPCODPACI 
    INNER JOIN INDIGO031.dbo.ADCENATEN Cent  ON Cent.CODCENATE = Q.CODCENATE 
    INNER JOIN INDIGO031.dbo.ADINGRESO I  ON I.NUMINGRES = Q.NUMINGRES 
    LEFT JOIN INDIGO031.dbo.ADACTIVID L  ON P.CODACTIVI = L.codactivi 
    LEFT JOIN INDIGO031.dbo.INUNIFUNC F  ON F.UFUCODIGO = Q.UFUCODIGO 
    LEFT JOIN INDIGO031.dbo.INENTIDAD E  ON E.CODENTIDA = P.CODENTIDA 
    LEFT JOIN INDIGO031.dbo.INCUPSIPS S  ON S.CODSERIPS = Q.CODSERIPS 
    LEFT JOIN INDIGO031.dbo.INPROFSAL PRO  ON PRO.CODPROSAL = Q.CODPROSAL 
    LEFT JOIN INDIGO031.dbo.AGASICITA AS CI ON CI.CODAUTONU = Q.IDCITA 
    LEFT JOIN INDIGO031.dbo.AGACTIMED AS AC ON AC.CODACTMED = CI.CODACTMED 
    LEFT JOIN INDIGO031.dbo.INESPECIA C  ON C.CODESPECI = CI.CODESPECI 
    LEFT JOIN INDIGO031.Contract.HealthAdministrator AS ha ON ha.Id = I.GENCONENTITY
    LEFT OUTER JOIN INDIGO031.Common.ThirdParty AS th ON th.Id = ha.ThirdPartyId
    LEFT OUTER JOIN INDIGO031.Contract.CareGroup AS ga ON ga.Id = I.GENCAREGROUP 
    LEFT OUTER JOIN INDIGO031.dbo.SEGusuaru AS us ON us.CODUSUARI = Q.PROAUSENT
WHERE   
    S.SERIPSDASH IN (12,9,8) 
    AND Q.ESTADO <> '5' 
    AND FECHAREG >= '01-01-2025'  
    AND Q.IPCODPACI <> '0123456789'