-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_IND_AD_HC_TOTALHISTORIAS_JERSALUD
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW ViewInternal.VW_IND_AD_HC_TOTALHISTORIAS_JERSALUD 
AS

SELECT H.IPCODPACI as Documento
    , P.IPNOMCOMP AS Paciente
    , COUNT(H.NUMEFOLIO) as TotalFolios
FROM [INDIGO031].[dbo].[HCHISPACA] AS H 
JOIN [INDIGO031].[dbo].[INPACIENT] AS P ON P.IPCODPACI=H.IPCODPACI
JOIN [INDIGO031].[dbo].[ADCENATEN] AS CD ON CD.CODCENATE=H.CODCENATE
where H.IPCODPACI not in ('1234567','9999999') and H.FECHISPAC<='04-30-2024 23:59:59' 
group by H.IPCODPACI,  P.IPNOMCOMP
