-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_IND_AD_HC_NA_FORMATODEMANDAINDUCIDA
-- Extracted by Fabric SQL Extractor SPN v3.9.0

-- SI ESTE QUERY SE USA CON FRECUENCIA SERIA BUENO CONSIDERAR CAMBIRLO
-- SE PODRIAN USAR CTE en lugar de los subquerys

CREATE VIEW ViewInternal.VW_IND_AD_HC_NA_FORMATODEMANDAINDUCIDA
AS

select 	
    NOTA.NOMBRE as Nota
    , C.FECHACREACION as [Fecha]
    ,   CASE
            WHEN C.CODCENATE IN(002, 003, 004, 005, 006, 007, 008, 009,017)
            THEN 'BOYACA'
            WHEN C.CODCENATE IN(010, 011, 012, 013, 014)
            THEN 'META'
            WHEN C.CODCENATE IN (015,016)
            THEN 'CASANARE'
        END AS Departamento
    , ce.NOMCENATE  as IPSPrimaria
    , p.IPPRINOMB AS [Primer Nombre]
    , p.IPSEGNOMB AS [Segundo Nombre]
    , p.IPPRIAPEL AS [Primer Apellido]
    , p.IPSEGAPEL AS [Segundo Apellido]
    , CASE 
        WHEN p.IPTIPODOC = '1' THEN 'CC' 
        WHEN p.IPTIPODOC = '2' THEN 'CE' 
	    WHEN p.IPTIPODOC = '3' THEN 'TI' 
        WHEN p.IPTIPODOC = '4' THEN 'RC' 
        WHEN p.IPTIPODOC = '5' THEN 'PA' 
	    WHEN p.IPTIPODOC = '6' THEN 'AS' 
        WHEN p.IPTIPODOC = '7' THEN 'MS' 
        WHEN p.IPTIPODOC ='8' THEN 'NU'  
        when p.IPTIPODOC ='9' then 'NV'  
        when p.IPTIPODOC ='12' then 'PE'  
        END AS TipoIdentificación
    , C.IPCODPACI as NroIdentificacion
    , p.IPFECNACI as FechaNacimiento
    , YEAR(C.FECHACREACION) - YEAR(p.IPFECNACI) AS Edad
    , CASE 
        WHEN p.IPSEXOPAC = '1' THEN 'M'
        WHEN p.IPSEXOPAC = '2' THEN 'F' 
        END AS Sexo
    , p.IPDIRECCI AS Direccion
    , p.IPTELEFON+'-'+p.IPTELMOVI as Telefono
    , C.NUMINGRES as Ingreso
    , TipoSeguimiento.Valor as [Tipo Seguimiento]
    , atepuerperio.Valor as [ATENCIÓN AL PUERPERIO]
    , FECHAatepuerperio.Valor AS [FECHA ATENCIÓN AL PUERPERIO]
    , aterecnaci.Valor as [ATENCIÓN AL RECIÉN NACIDO]
    , fechaaterecnaci.Valor AS [FECHA ATENCIÓN AL RECIÉN NACIDO]
    , planfam.Valor as [PLANIFICACIÓN FAMILIAR Y ANTICONCEPCIÓN]
    , fechaplanfam.Valor as [FECHA PLANIFICACIÓN FAMILIAR Y ANTICONCEPCIÓN]
    , priinf.Valor as [PROGRAMA DE PRIMERA INFANCIA]
    , fechapriinf.Valor as [FECHA PROGRAMA DE PRIMERA INFANCIA]
    , infanc.Valor as [PROGRAMA DE INFANCIA]
    , fechainfanc.Valor as [FECHA PROGRAMA DE INFANCIA]
    , adoles.Valor as [PROGRAMA DE ADOLESCENCIA]
    , fechaadoles.Valor as [FECHA PROGRAMA DE ADOLESCENCIA]
    , juvent.Valor as [PROGRAMA DE JUVENTUD]
    , fechajuvent.Valor as [FECHA PROGRAMA DE JUVENTUD]
    , adulto.Valor as [PROGRAMA DE ADULTEZ]
    , fechaadulto.Valor as [FECHA PROGRAMA DE ADULTEZ]
    , vejez.Valor as [PROGRAMA DE VEJEZ]
    , fechavejez.Valor as [FECHA PROGRAMA DE VEJEZ]
    , prenat.Valor as [ATENCIÓN AL CUIDADO PRENATAL]
    , fechaprenat.Valor as [FECHA ATENCIÓN AL CUIDADO PRENATAL]
    , curso.Valor as [CURSO PREPARACIÓN PARA MATERNIDAD Y PATERNIDAD]
    , fechacurso.Valor as [FECHA CURSO PREPARACIÓN PARA MATERNIDAD Y PATERNIDAD]

    , bucal.Valor as [SALUD BUCAL]
    , fechabucal.Valor as [FECHA SALUD BUCAL]
    , cuelloute.Valor as [DETECCIÓN TEMPRANA CÁNCER CUELLO UTERINO]
    , fechacuelloute.Valor as [FECHA DETECCIÓN TEMPRANA CÁNCER CUELLO UTERINO]
    , mama.Valor as [DETECCIÓN TEMPRANA CÁNCER MAMA]
    , fechamama.Valor as [FECHA DETECCIÓN TEMPRANA CÁNCER MAMA]
    , prostata.Valor as [DETECCIÓN TEMPRANA CÁNCER PRÓSTATA]
    , fechaprostata.Valor as [FECHA DETECCIÓN TEMPRANA CÁNCER PRÓSTATA]
    , colon.Valor as [DETECCIÓN TEMPRANA CÁNCER COLON Y RECTO]
    , fechacolon.Valor as [FECHA DETECCIÓN TEMPRANA CÁNCER COLON Y RECTO]
    , preconcepcional.Valor as [ATENCION AL CUIDADO PRECONCEPCIONAL]
    , fechapreconcepcional.Valor as [FECHA ATENCION AL CUIDADO PRECONCEPCIONAL]
    , vacunacion.Valor as [VACUNACIÓN], fechavacunacion.Valor as [FECHA VACUNACIÓN]
    , lactancia.Valor as [APOYO A LA LACTANCIA MATERNA]
    , fechalactancia.Valor as [FECHA APOYO A LA LACTANCIA MATERNA]
    , educacion.Valor as [CICLOS EDUCACIÓN Y COMUNICACIÓN]
    , fechaeducacion.Valor as [FECHAvalor CICLOS EDUCACIÓN Y COMUNICACIÓN]
    , metab.Valor as [SINDROME METABÓLICO]
    , fechametabgen.Valor as [FECHA SINDROME METABÓLICO MEDICO GENERAL]
    , fechametabint.Valor as [FECHA SINDROME METABÓLICO MEDICO INTERNISTA]
    , fechametabfam.Valor as [FECHA SINDROME METABÓLICO MEDICO FAMILIAR]
    , fechametabpsic.Valor as [FECHA SINDROME METABÓLICO PSICOLOGO]
    , fechametabnutri.Valor as [FECHA SINDROME METABÓLICO NUTRICIONISTA]
    , fechametabenf.Valor as [FECHA SINDROME METABÓLICO ENFERMERIA]
    , fechametabtsoc.Valor as [FECHA SINDROME METABÓLICO TRABAJO SOCIAL]
    , victima.Valor as [ATENCIÓN A VÍCTIMAS DE VIOLENCIA SEXUAL]
    , fechavictima.Valor as [FECHA ATENCIÓN VÍCTIMAS VIOLENCIA SEXUAL]
    , mental.Valor as [SALUD MENTAL]
    , fechamental.Valor  as [FECHA SALUD MENTAL]
    , otro.Valor as [OTRO]
    , fechaotro.Valor  as [FECHA OTRO]
    , domici.Valor as [VISITA DOMICILIARIA]
    , llamada.Valor as [LLAMADA  TELEFÓNICA]
    , resultado.Valor as [RESULTADO DE LA LLAMADA O DE LA VISITA DOCIMILIARIA]
    , asigna.Valor as [FECHA ASIGNACIÓN CITA (AAAA-MM-DD)]
    , motivo.Valor as [MOTIVO DE LA INASISTENCIA O CANCELACIÓN DE LA CITA]
    , asistencia.Valor as [ASISTENCIA DEL USUARIO A LA CONSULTA ASIGNADA]
    , observaciones.Valor as Observaciones
    , u.NOMUSUARI as [Funcionario Realiza Demanda Inducida]

FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
INNER JOIN [INDIGO031].[dbo].[NTADMINISTRATIVAS] AS NOTA ON NOTA.ID=C.IDNOTAADMINISTRATIVA 
inner join [INDIGO031].[dbo].[INPACIENT] as p  on p.IPCODPACI=C.IPCODPACI
inner join [INDIGO031].[dbo].[SEGusuaru] as u  on u.CODUSUARI=C.CODUSUARI
inner join [INDIGO031].[dbo].[ADCENATEN] as ce  on ce.CODCENATE=C.CODCENATE
--inicia los subquerys para las columnas
left outer join (
	select vari.ID as VariID, vari.VARIABLE, CASE WHEN  vard.NOMBRE IS NOT NULL THEN vard.NOMBRE ELSE D.VALOR END AS Valor , D.IDNTNOTASADMINISTRATIVASC
	from [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D
	inner join [INDIGO031].[dbo].[NTVARIABLES] as vari  on vari.ID=D.IDNTVARIABLE
	left outer join [INDIGO031].[dbo].[NTVARIABLESL] as vard  on vard.ID=D.IDITEMLISTA
	where  vari.ID='2') as TipoSeguimiento on TipoSeguimiento.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	select vari.ID as VariID, vari.VARIABLE, CASE WHEN  vard.NOMBRE IS NOT NULL THEN vard.NOMBRE ELSE D.VALOR END AS Valor , D.IDNTNOTASADMINISTRATIVASC
	from [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D 
	inner join [INDIGO031].[dbo].[NTVARIABLES] as vari  on vari.ID=D.IDNTVARIABLE
	left outer join [INDIGO031].[dbo].[NTVARIABLESL] as vard  on vard.ID=D.IDITEMLISTA
	where  vari.ID='1') as observaciones on observaciones.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=4 ) as atepuerperio on atepuerperio.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=73 ) as FECHAatepuerperio on FECHAatepuerperio.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=5) as aterecnaci on aterecnaci.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=74) as fechaaterecnaci on fechaaterecnaci.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=6) as planfam on planfam.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=75) as fechaplanfam on fechaplanfam.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=7) as priinf on priinf.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=76) as fechapriinf on fechapriinf.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=8) as infanc on infanc.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=77) as fechainfanc on fechainfanc.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=9) as adoles on adoles.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=78) as fechaadoles on fechaadoles.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=10) as juvent on juvent.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=79) as fechajuvent on fechajuvent.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=11) as adulto on adulto.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=80) as fechaadulto on fechaadulto.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=12) as vejez on vejez.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=81) as fechavejez on fechavejez.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=13) as prenat on prenat.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=82) as fechaprenat on fechaprenat.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=14) as curso on curso.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=83) as fechacurso on fechacurso.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=15) as bucal on bucal.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=84) as fechabucal on fechabucal.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=16) as cuelloute on cuelloute.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=85) as fechacuelloute on fechacuelloute.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=17) as mama on mama.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=86) as fechamama on fechamama.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=18) as prostata on prostata.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=87) as fechaprostata on fechaprostata.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=18) as colon on colon.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=88) as fechacolon on fechacolon.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=20) as preconcepcional on preconcepcional.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=89) as fechapreconcepcional on fechapreconcepcional.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=21) as vacunacion on vacunacion.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=90) as fechavacunacion on fechavacunacion.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=22) as lactancia on lactancia.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=91) as fechalactancia on fechalactancia.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=23) as educacion on educacion.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=92) as fechaeducacion on fechaeducacion.IDNTNOTASADMINISTRATIVASC=C.ID
	--REVISAR
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE  D.IDNTVARIABLE=24) as metab on metab.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE  D.IDNTVARIABLE=93) as fechametabgen on fechametabgen.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE  D.IDNTVARIABLE=97) as fechametabint on fechametabint.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE  D.IDNTVARIABLE=98) as fechametabfam on fechametabfam.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE  D.IDNTVARIABLE=99) as fechametabpsic on fechametabpsic.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE  D.IDNTVARIABLE=100) as fechametabnutri on fechametabnutri.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari ON vari.ID= D.IDNTVARIABLE
	WHERE  D.IDNTVARIABLE=101) as fechametabenf on fechametabenf.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] as vari ON vari.ID= D.IDNTVARIABLE
	WHERE  D.IDNTVARIABLE=102) as fechametabtsoc on fechametabtsoc.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=25) as victima on victima.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=94) as fechavictima on fechavictima.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=26) as mental on mental.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=95) as fechamental on fechamental.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR  AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=27) as otro on otro.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	SELECT vari.ID as VariID, vari.VARIABLE, D.VALOR AS Valor , D.IDNTNOTASADMINISTRATIVASC
	FROM  [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASC] AS C 
	INNER JOIN [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D  ON C.ID=D.IDNTNOTASADMINISTRATIVASC
	INNER JOIN [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID= D.IDNTVARIABLE
	WHERE D.IDGRUPO=2 AND D.IDNTVARIABLE=96) as fechaotro on fechaotro.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
		select vari.ID as VariID, vari.VARIABLE, CASE WHEN  vard.NOMBRE IS NOT NULL THEN vard.NOMBRE ELSE D.VALOR END AS Valor , D.IDNTNOTASADMINISTRATIVASC
		from [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D 
		inner join [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID=D.IDNTVARIABLE
		left outer join [INDIGO031].[dbo].[NTVARIABLESL] AS vard  ON vard.ID=D.IDITEMLISTA
		where  vari.ID=28) as domici  on domici.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	select vari.ID as VariID, vari.VARIABLE, CASE WHEN  vard.NOMBRE IS NOT NULL THEN vard.NOMBRE ELSE D.VALOR END AS Valor , D.IDNTNOTASADMINISTRATIVASC
	from [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D 
	inner join [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID=D.IDNTVARIABLE
	left outer join [INDIGO031].[dbo].[NTVARIABLESL] AS vard  ON vard.ID=D.IDITEMLISTA
	where  vari.ID=29) as llamada  on llamada.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	select vari.ID as VariID, vari.VARIABLE, CASE WHEN  vard.NOMBRE IS NOT NULL THEN vard.NOMBRE ELSE D.VALOR END AS Valor , D.IDNTNOTASADMINISTRATIVASC
	from [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D 
	inner join [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID=D.IDNTVARIABLE
	left outer join [INDIGO031].[dbo].[NTVARIABLESL] AS vard  ON vard.ID=D.IDITEMLISTA
	where  vari.ID=30) as resultado  on resultado.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	select vari.ID as VariID, vari.VARIABLE, CASE WHEN  vard.NOMBRE IS NOT NULL THEN vard.NOMBRE ELSE D.VALOR END AS Valor , D.IDNTNOTASADMINISTRATIVASC
	from [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D 
	inner join [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID=D.IDNTVARIABLE
	left outer join [INDIGO031].[dbo].[NTVARIABLESL] AS vard  ON vard.ID=D.IDITEMLISTA
	where  vari.ID=31) as asigna  on asigna.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	select vari.ID as VariID, vari.VARIABLE, CASE WHEN  vard.NOMBRE IS NOT NULL THEN vard.NOMBRE ELSE D.VALOR END AS Valor , D.IDNTNOTASADMINISTRATIVASC
	from [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D 
	inner join [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID=D.IDNTVARIABLE
	left outer join [INDIGO031].[dbo].[NTVARIABLESL] AS vard  ON vard.ID=D.IDITEMLISTA
	where  vari.ID=32) as motivo  on motivo.IDNTNOTASADMINISTRATIVASC=C.ID
left outer join (
	select vari.ID as VariID, vari.VARIABLE, CASE WHEN  vard.NOMBRE IS NOT NULL THEN vard.NOMBRE ELSE D.VALOR END AS Valor , D.IDNTNOTASADMINISTRATIVASC
	from [INDIGO031].[dbo].[NTNOTASADMINISTRATIVASD] AS D 
	inner join [INDIGO031].[dbo].[NTVARIABLES] AS vari  ON vari.ID=D.IDNTVARIABLE
	left outer join [INDIGO031].[dbo].[NTVARIABLESL] AS vard  ON vard.ID=D.IDITEMLISTA
	where  vari.ID=33) as asistencia  on asistencia.IDNTNOTASADMINISTRATIVASC=C.ID
--finaliza los subquerys para las columnas
WHERE 
NOTA.CODIGO='00002' 
AND C.FECHACREACION>='2023-01-01' 
and C.IPCODPACI<>'0000'
