-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_IND_INDICACIONESFARMACOLOGICASEXTRAMURALES
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW ViewInternal.VW_IND_INDICACIONESFARMACOLOGICASEXTRAMURALES
AS
SELECT DISTINCT 
    O.FECHAORDE AS FechaOrden, 
    O.IPCODPACI AS Documento, 
    P.IPNOMCOMP AS Paciente, 
    O.NUMINGRES AS Ingreso, 
    O.INDFAREXT AS Medicamentos_Extramurales, 
    PR.CODPROSAL AS CodProf, 
    PR.NOMMEDICO AS Medico, 
    E.DESESPECI AS Especialidad, 
    C.NOMCENATE AS Sede, 
    P.IPDIRECCI, 
    P.IPTELEFON, 
    P.IPTELMOVI, 
    P.IPFECNACI, 
    (CAST(DATEDIFF(dd, P.IPFECNACI, GETDATE()) / 365.25 AS INT)) AS EDAD
FROM [INDIGO031].[dbo].[HCPRESCRC] AS O
    INNER JOIN [INDIGO031].[dbo].[INPACIENT] AS P ON O.IPCODPACI = P.IPCODPACI
    INNER JOIN [INDIGO031].[dbo].[ADCENATEN] AS C ON O.CODCENATE = C.CODCENATE
    INNER JOIN [INDIGO031].[dbo].[INPROFSAL] AS PR ON O.CODPROSAL = PR.CODPROSAL
    INNER JOIN [INDIGO031].[dbo].[INESPECIA] AS E ON PR.CODESPEC1 = E.CODESPECI
WHERE O.INDFAREXT <> '' AND O.FECHAORDE >= DATEADD(MONTH, -3, GETDATE());
