-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_IND_REMISION_REFERENCIA
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [ViewInternal].[VW_IND_REMISION_REFERENCIA] AS

/*
IPCODPACI, NUMINGRES, CODCENATE, UFUCODIGO, CODPROSAL, SERVIDOREM, NIVELREMIT, FECSOLICIT
CODESPECI, QUIENSOLRE, MOTREMISI, OBSERVACIO, CODUSUMOD, FECMODREG, FECREGSIS, CODCONCEC, IDETIPHIS
NUMEFOLIO, OBSEREMI, IDHCREFCONP, EXTRAMURAL

SELECT TOP 10 * FROM dbo.HCREFCONI order by FECREGSIS;
SELECT TOP 10 * FROM dbo.HCREFCONP order by FECREGSIS;
SELECT TOP 10 * FROM dbo.HCREFCONT order by FECREGSIS;
SELECT TOP 10 * FROM dbo.HCHISPACA;
*/

     SELECT DISTINCT 
            REF.FECSOLICIT AS Fecha_Solicitud, 
            REF.FECREGSIS AS Fecha_Registro, 
            REF.SERVIDOREM, 
            P.IPNOMCOMP AS Paciente, 
            P.IPDIRECCI AS Direccion, 
            P.IPTELEFON AS Fijo, 
            P.IPTELMOVI AS Celular, 
            CONVERT(VARCHAR(10), P.IPFECNACI, 101) AS FechaNacimient, 
            CAST(DATEDIFF(dd, P.IPFECNACI, GETDATE()) / 365.25 AS INT) AS EDAD, 
            HC.CODDIAGNO AS Cie10, 
            Dx.NOMDIAGNO AS Diagnostico, 
            REF.CODPROSAL AS CodProfesional, 
            PROF.NOMMEDICO AS Profesional, 
            CA.NOMCENATE AS CentroAtencion, 
            U.UFUDESCRI AS Unidad
     FROM INDIGO031.dbo.HCREFCONT AS REF
          INNER JOIN INDIGO031.dbo.INPACIENT AS P ON P.IPCODPACI = REF.IPCODPACI
          INNER JOIN INDIGO031.dbo.HCHISPACA AS HC ON HC.NUMINGRES = REF.NUMINGRES
          INNER JOIN INDIGO031.dbo.INPROFSAL AS PROF ON PROF.CODPROSAL = REF.CODPROSAL
          INNER JOIN INDIGO031.dbo.ADCENATEN AS CA ON CA.CODCENATE = REF.CODCENATE
          INNER JOIN INDIGO031.dbo.INUNIFUNC AS U ON U.UFUCODIGO = REF.UFUCODIGO
          INNER JOIN INDIGO031.dbo.INDIAGNOS AS Dx ON Dx.CODDIAGNO = HC.CODDIAGNO;
