-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_IND_INDICADORESGRALXPROFESIONAL_INTERCONSULTAS_PB
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW ViewInternal.VW_IND_INDICADORESGRALXPROFESIONAL_INTERCONSULTAS_PB
AS

SELECT 'Interconsultas' AS Tipo, 
    ca.NOMCENATE AS Sede, prof.CODPROSAL, prof.NOMMEDICO as Medico, ESP.DESESPECI as Profesion, ESPT.DESESPECI AS EspecialidadRemitida, 
    CASE WHEN ESPT.CODESPECI IN ('099','101','142','085','184','113','203','002','116','355') THEN 'Red Interna' else 'Red Externa' end as Red,
    CASE
            WHEN ca.CODCENATE IN(002, 003, 004, 005, 006, 007, 008, 009,017,021)
        THEN 'BOYACA'
        WHEN ca.CODCENATE IN(010, 011, 012, 013, 014,018)
        THEN 'META'
        WHEN ca.CODCENATE IN (015,016,019,020)
        THEN 'CASANARE'
    END AS Regional,
    MONTH(I.FECORDMED) AS Mes, 
    YEAR(I.FECORDMED) AS Año, 
    SUM(I.CANSERIPS) AS Cant
FROM [INDIGO031].[dbo].[HCORDINTE] I 
    JOIN [INDIGO031].[dbo].[ADCENATEN] ca  ON I.CODCENATE = ca.CODCENATE
    JOIN [INDIGO031].[dbo].[INPROFSAL] prof  on I.CODPROSAL = prof.CODPROSAL
    JOIN [INDIGO031].[dbo].[INESPECIA] ESP  ON prof.CODESPEC1 = ESP.CODESPECI
    JOIN [INDIGO031].[dbo].[INESPECIA] ESPT  ON ESPT.CODESPECI=I.CODESPECI
WHERE I.FECORDMED >= '01-01-2022' AND I.ESTSERIPS <> '6'   and  I.IPCODPACI not in ('1234567', '12345678', '14141414','9999999') AND I.NUMINGRES+NUMEFOLIO NOT IN (SELECT NUMINGRES+NUMEFOLIO
                                FROM [INDIGO031].[dbo].[HCFOLANUL])
GROUP BY MONTH(I.FECORDMED), 
        ca.NOMCENATE, 
        ca.CODCENATE, 
        YEAR(I.FECORDMED),
        ESP.DESESPECI,
        prof.NOMMEDICO, prof.CODPROSAL, ESPT.DESESPECI, ESPT.CODESPECI
