-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_IND_ESCALAS
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW ViewInternal.VW_IND_ESCALAS
AS

SELECT  ESC.NUMINGRES,
    CASE PA.IPTIPODOC
        WHEN 1
        THEN 'CC'
        WHEN 2
        THEN 'CE'
        WHEN 3
        THEN 'TI'
        WHEN 4
        THEN 'RC'
        WHEN 5
        THEN 'PA'
        WHEN 6
        THEN 'AS'
        WHEN 7
        THEN 'MS'
        WHEN 8
        THEN 'NU'
    END AS TIPODOCUMENTO, 
    ESC.IPCODPACI AS IDENTIFICACION, 
    PA.IPNOMCOMP AS PACIENTE,
    CASE PA.IPSEXOPAC
        WHEN 1
        THEN 'H'
        WHEN 2
        THEN 'M'
    END AS SEXO, 
    CONVERT(VARCHAR, PA.IPFECNACI, 23) AS Fecha_Nacimiento, 
    (DATEDIFF(MONTH, PA.IPFECNACI, GETDATE())) / 12 AS Edad_Paciente, 
    ESC.FECHAREGISTRO, 
    ESC.CODPROSAL, 
    ESC.TIPOESCALA,
    PE.NOMBREESCALA AS Nombre_Escala, 
    ESC.RESULTADO, 
    INDIGO031.dbo.InterpretacionEscala(ESC.ID,ESC.TIPOESCALA,ESC.RESULTADO,ESC.RESULTADODECIMAL,PA.IPSEXOPAC) AS Interpretacion,-- se agrega por solicitud en caso 318104
    CA.NOMCENATE AS Centro_Atencion,
    P.CODPROSAL AS CodMed,
    P.NOMMEDICO AS MEDICO,
    E.DESESPECI AS ESPECIALIDAD
FROM [INDIGO031].[dbo].[HCESCALAS] AS ESC
INNER JOIN [INDIGO031].[dbo].[HCPARAESCALAS] as PE on PE.CODIGO=ESC.TIPOESCALA --falta cargar la tabla
INNER JOIN [INDIGO031].[dbo].[INPACIENT] AS PA ON PA.IPCODPACI = ESC.IPCODPACI
INNER JOIN [INDIGO031].[dbo].[ADCENATEN] AS CA ON CA.CODCENATE = ESC.CODCENATE
INNER JOIN [INDIGO031].[dbo].[INPROFSAL] AS P ON P.CODPROSAL = ESC.CODPROSAL
INNER JOIN [INDIGO031].[dbo].[INESPECIA] AS E ON P.CODESPEC1 = E.CODESPECI
WHERE ESC.FECHAREGISTRO >='01/01/2019'
