-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_IND_INDICADOR_CONSULTASXPROFESIONAL_PB
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW ViewInternal.VW_IND_INDICADOR_CONSULTASXPROFESIONAL_PB
AS
SELECT CA.NOMCENATE AS Sede,
    CASE
        WHEN CA.CODCENATE IN(002, 003, 004, 005, 006, 007, 008, 009,017,021)
        THEN 'BOYACA'
        WHEN CA.CODCENATE IN(010, 011, 012, 013, 014,018)
        THEN 'META'
        WHEN CA.CODCENATE IN (015,016,019,020)
        THEN 'CASANARE'
    END AS Regional,prof.CODPROSAL, prof.NOMMEDICO AS Profesional, E.DESESPECI AS Especialidad,
    'Consultas' AS Tipo, 
    MONTH(H.FECHISPAC) AS Mes, 
    YEAR(H.FECHISPAC) AS Año, 
    COUNT(H.NUMINGRES) AS Cant
FROM [INDIGO031].[dbo].[HCHISPACA] AS H 
    INNER JOIN [INDIGO031].[dbo].[ADCENATEN] AS CA  ON H.CODCENATE = CA.CODCENATE
    JOIN [INDIGO031].[dbo].[INPROFSAL] prof   on H.CODPROSAL = prof.CODPROSAL
    JOIN [INDIGO031].[dbo].[INESPECIA] E   on prof.CODESPEC1 = E. CODESPECI
WHERE(H.TIPHISPAC = 'I')
    AND H.FECHISPAC >= '01-01-2022'  and H.IPCODPACI not in ('1234567', '12345678', '14141414','9999999')
GROUP BY CA.CODCENATE, 
        CA.NOMCENATE, 
        MONTH(H.FECHISPAC), 
        YEAR(H.FECHISPAC), 
        prof.NOMMEDICO,
        E.DESESPECI,
        prof.CODPROSAL;
