-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_IND_AD_AG_CITASMEDICAS_OPTIMIZADA
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW ViewInternal.VW_IND_AD_AG_CITASMEDICAS_OPTIMIZADA 
AS
SELECT TOP (100) PERCENT CE.NUMINGRES AS Ingreso, C.IPCODPACI AS IDENTIFICACION, PA.IPNOMCOMP AS PACIENTE, PA.IPPRIAPEL AS PrimerApellido, PA.IPSEGAPEL AS SegApellido, PA.IPPRINOMB AS PrimerNombre,
PA.IPSEGNOMB AS SegNombre, CASE PA.IPSEXOPAC WHEN 1 THEN 'H' WHEN 2 THEN 'M' END AS SEXO, CA.NOMCENATE AS CentroAtencion, P.CODPROSAL AS CodMed, P.NOMMEDICO AS MEDICO,
E.DESESPECI AS ESPECIALIDAD, C.FECHORAIN AS [FECHA DE CITA], A.DESACTMED AS ACTIVIDAD, R.NOMBRE AS RIAS,
CASE WHEN C.CODTIPSOL = '0' THEN 'Presencial' WHEN C.CODTIPSOL = '1' THEN 'Telefónica' END AS SOLICITUD,
CASE WHEN C.CODTIPCIT = '0' THEN 'Primera Vez' WHEN C.CODTIPCIT = '1' THEN 'Control' WHEN C.CODTIPCIT = '2' THEN 'Pos Operatorio' END AS TIPO,
CASE C.CODESTCIT WHEN '0' THEN 'Asignada' WHEN '1' THEN 'Cumplida' WHEN '2' THEN 'Incumplida' WHEN '3' THEN 'Preasignada' WHEN 4 THEN 'Cancelada'  WHEN '5' THEN
            'Inatención' END AS ESTADO,
CASE WHEN C.CITAEXTRA = '0' THEN 'Normal' WHEN C.CITAEXTRA = '1' THEN 'Cita Extra' END AS [CITA EXTRA], US.NOMUSUARI AS USUARIO, C.FECREGSIS AS [FECHA REGISTRO], DATEDIFF(y, C.FECREGSIS, C.FECHORAIN)
AS [Días Transcurridos], MONTH(C.FECREGSIS) AS MesRegistro, C.FECITADES AS [FECHA DeseaPcte], PA.IPFECNACI AS FECHA_NAC, EA.Code AS CodEPS, EA.Name AS EntidadPaciente, PA.IPTELEFON AS Fijo,
PA.IPTELMOVI AS Celular,  
UC.NOMUSUARI AS Usuario_Cancela,  C.FECHCANCELA AS Fechacancelación, C.OBSCAUCAN AS Mot_Cancelacion, cac.DESCAUCAN as Causa_Cancelacion,
MOT.DESMOTANU as Causa_Inatencion
FROM [INDIGO031].[dbo].[AGASICITA] AS C 
INNER JOIN [INDIGO031].[dbo].[INPACIENT] AS PA ON PA.IPCODPACI = C.IPCODPACI 
INNER JOIN [INDIGO031].[dbo].[INPROFSAL] AS P ON P.CODPROSAL = C.CODPROSAL 
INNER JOIN [INDIGO031].[dbo].[INESPECIA] AS E ON P.CODESPEC1 = E.CODESPECI 
INNER JOIN [INDIGO031].[dbo].[AGACTIMED] AS A ON A.CODACTMED = C.CODACTMED 
INNER JOIN [INDIGO031].[dbo].[SEGusuaru] AS US ON US.CODUSUARI = C.CODUSUASI 
LEFT OUTER JOIN [INDIGO031].[dbo].[ADCONCOEX] AS CE ON C.CODAUTONU = CE.NUMCONCIT
LEFT OUTER JOIN [INDIGO031].[Contract].[HealthAdministrator] AS EA ON PA.GENCONENTITY = EA.Id 
INNER JOIN [INDIGO031].[dbo].[ADCENATEN] AS CA ON C.CODCENATE = CA.CODCENATE 
LEFT OUTER JOIN [INDIGO031].[dbo].[RIASCUPS] AS RIC ON A.IDRIASCUPS = RIC.ID 
LEFT OUTER JOIN [INDIGO031].[dbo].[RIAS] AS R ON RIC.IDRIAS = R.ID
LEFT JOIN [INDIGO031].[dbo].[SEGusuaru] AS UC ON UC.CODUSUARI = C.CANCELUSU
left join [INDIGO031].[dbo].[AGCAUCANC] as cac on cac.CODCAUCAN=C.CODCAUCAN
left outer join [INDIGO031].[dbo].[HCMOANULB] AS MOT  ON MOT.CODMOTANU=C.CODCAUINA
WHERE C.FECREGSIS>= '01/11/2022' --and c.IPCODPACI='1002559232'
