-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_IND_INDICADORESGRALXPROFESIONAL_LABORATORIO_TARIFA_PB
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE view ViewInternal.VW_IND_INDICADORESGRALXPROFESIONAL_LABORATORIO_TARIFA_PB
as

SELECT 
    'Laboratorio' AS Tipo
    , ca.NOMCENATE AS Sede
    , prof.CODPROSAL
    , prof.NOMMEDICO as Medico
    , ESP.DESESPECI as Profesion
    ,CASE
        WHEN ca.CODCENATE IN(002, 003, 004, 005, 006, 007, 008, 009,017,021)
        THEN 'BOYACA'
        WHEN ca.CODCENATE IN(010, 011, 012, 013, 014,018)
        THEN 'META'
        WHEN ca.CODCENATE IN (015,016,019,020)
        THEN 'CASANARE'
    END AS Regional,
    MONTH(I.FECORDMED) AS Mes, 
    YEAR(I.FECORDMED) AS Año, 
    I.CODSERIPS as Codigo,
    CUP.DESSERIPS AS Servicio,
    I.IPCODPACI as Documento,
    I.FECORDMED as Fecha,
    [ISS+ 35%] as Valor
    , NUMINGRES as Ingreso
FROM [INDIGO031].[dbo].[HCORDLABO] I 
inner join [INDIGO031].[dbo].[ADCENATEN] ca  ON I.CODCENATE = ca.CODCENATE
inner join [INDIGO031].[dbo].[INPROFSAL] prof  on I.CODPROSAL = prof.CODPROSAL
inner join [INDIGO031].[dbo].[INESPECIA] ESP  ON prof.CODESPEC1 = ESP.CODESPECI
inner join [INDIGO031].[dbo].[INCUPSIPS] CUP  ON CUP.CODSERIPS = I.CODSERIPS
LEFT JOIN [INDIGO031].[ViewInternal].[Tarifas_Laboratorio] AS T ON T.Code=I.CODSERIPS
WHERE I.FECORDMED >= '01-01-2022' AND I.ESTSERIPS <> 6  and  I.IPCODPACI not in ('1234567', '12345678', '14141414','9999999') AND I.NUMINGRES+NUMEFOLIO NOT IN 
(SELECT NUMINGRES+NUMEFOLIO FROM [INDIGO031].[dbo].[HCFOLANUL])