-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_IND_REMISIONES_RIAS
-- Extracted by Fabric SQL Extractor SPN v3.9.0


/****** Object:  View [dbo].[IND_ProcedimientoNoQX_Ordenados]    Script Date: 7/21/2022 4:05:56 PM ******/


CREATE VIEW [ViewInternal].[VW_IND_REMISIONES_RIAS] AS
SELECT DISTINCT 
    PP.CODCONCEC, 
    PP.NUMINGRES AS INGRESO, 
    PP.IPCODPACI AS IDENTIFICACION, 
    P.IPNOMCOMP AS PACIENTE, 
    P.IPDIRECCI AS DIRECCION, 
    P.IPTELEFON AS TELEFONO, 
    P.IPTELMOVI AS CECLULAR, 
    P.IPFECNACI AS FECHA_NACIMIENTO, 
    (CAST(DATEDIFF(dd, P.IPFECNACI, GETDATE()) / 365.25 AS INT)) AS EDAD, 
    PP.FECREGSIS AS FECHA_REGISTRO, 
    PP.IDRIAS AS COD_RIAS, 
    R.NOMBRE AS RIAS, 
    PP.JUSNOREPP AS JUSTIFICACION_NO_REMISION, 
    PP.CODPROSAL AS IDENTIFICACION_MEDICO, 
    PROF.NOMMEDICO AS MEDICO, 
    E.DESESPECI AS ESPECIALIDAD, 
    U.UFUDESCRI AS UNIDAD_FUNCIONAL
FROM INDIGO031.dbo.HCPPYPPAC AS PP
    INNER JOIN INDIGO031.dbo.RIAS AS R ON R.ID = PP.IDRIAS
    INNER JOIN INDIGO031.dbo.INUNIFUNC AS U ON U.UFUCODIGO = PP.UFUCODIGO
    INNER JOIN INDIGO031.dbo.INPROFSAL AS PROF ON PROF.CODPROSAL = PP.CODPROSAL
    INNER JOIN INDIGO031.dbo.INESPECIA AS E ON PROF.CODESPEC1 = E.CODESPECI
    INNER JOIN INDIGO031.dbo.INPACIENT AS P ON P.IPCODPACI = PP.IPCODPACI
WHERE PP.FECREGSIS >= DATEADD(MONTH, -3, GETDATE())

