-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_IND_REDPROFESIONALES_JER
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [ViewInternal].[VW_IND_REDPROFESIONALES_JER]
AS
SELECT DISTINCT TOP (100) PERCENT E.CODESPECI, E.DESESPECI, 'Red Interna' AS Red
FROM   INDIGO031.dbo.HCHISPACA AS H INNER JOIN
             INDIGO031.dbo.INPROFSAL AS M ON H.CODPROSAL = H.CODPROSAL AND M.ESTADOMED = 1 INNER JOIN
             INDIGO031.dbo.INESPECIA AS E ON M.CODESPEC1 = E.CODESPECI AND E.ESTADO = 1
WHERE (H.FECHISPAC >= '01/01/2023')
