-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_PLANESTRATAMIENTOSODONTOLOGICOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0


--SELECT COUNT(*) FROM [ViewInternal].[VW_PLANESTRATAMIENTOSODONTOLOGICOS]
CREATE VIEW [ViewInternal].[VW_PLANESTRATAMIENTOSODONTOLOGICOS]
--CREATE VIEW PlanesTratamientosOdontologicos_Trimestral
AS
SELECT OC.ID, CA.NOMCENATE AS CentroAtencion, U.UFUDESCRI AS Unidad, OC.IPCODPACI AS Documento, P.IPNOMCOMP AS Paciente, P.IPDIRECCI AS Direccion, 
	   P.IPTELEFON AS Fijo, P.IPTELMOVI AS Celular, CONVERT(varchar(10), P.IPFECNACI, 101) AS FechaNacimiento,
	   CAST(DATEDIFF(dd, P.IPFECNACI, GETDATE()) / 365.25 AS int) AS EDAD, OC.NUMINGRES AS Ingreso, OC.NUMEFOLIO AS Folio, OC.CODPROSAL AS CodProfesional,PROF.NOMMEDICO AS Profesional,
	   OC.FECHAREG AS Fecha_Registro, OC.OBSERVACIONESGENERA AS Observacion, OC.IDRIASCUPS AS RIAS, TRA.DESCRITRA AS Tratamiento_Ordenado, 
	   CASE 
			WHEN PLANTRA.ESTADO = '1' THEN 'Sin realizar'
			WHEN PLANTRA.ESTADO = '2' THEN 'Realizado'
			WHEN PLANTRA.ESTADO = '3' THEN 'No realizado'
			WHEN PLANTRA.ESTADO = '4' THEN 'Cancelado'
	   END AS Estado_Tratamiento,
	   PLANTRA.FECHAORDENO AS Fecha_Ordeno, (SELECT P1.NOMMEDICO FROM INDIGO031.dbo.INPROFSAL as P1 WHERE P1.CODPROSAL=PLANTRA.PROFESIONALORDENO) AS Profesional_Ordeno,
	   PLANTRA.FECHAREALIZO AS Fecha_Realizo,(SELECT P2.NOMMEDICO FROM INDIGO031.dbo.INPROFSAL as P2 WHERE P2.CODPROSAL=PLANTRA.PROFESIONALREALIZO) AS Profesional_Realizo,
	   PLANTRA.FECHACANCELO AS Fecha_Cancelo, (SELECT P3.NOMMEDICO FROM INDIGO031.dbo.INPROFSAL as P3 WHERE P3.CODPROSAL=PLANTRA.PROFESIONALCANCELO) AS Profesional_Cancelo
  FROM INDIGO031.dbo.ODONTOCONTROL AS OC LEFT JOIN
	   INDIGO031.dbo.ODONTOPLANTRATAMIENTOPACD AS PLANTRA ON PLANTRA.IDODONTOCONTROL=OC.ID INNER JOIN
	   INDIGO031.dbo.ODOPARTRA AS TRA ON TRA.CONSECTRA=PLANTRA.IDODOPARTRA INNER JOIN
	   INDIGO031.dbo.INPACIENT AS P ON P.IPCODPACI = OC.IPCODPACI INNER JOIN
	   INDIGO031.dbo.INPROFSAL AS PROF ON OC.CODPROSAL = PROF.CODPROSAL INNER JOIN
	   INDIGO031.dbo.ADCENATEN AS CA ON CA.CODCENATE = OC.CODCENATE INNER JOIN
	   INDIGO031.dbo.INUNIFUNC AS U ON U.UFUCODIGO = OC.UFUCODIGO  
 --WHERE PLANTRA.FECHAORDENO >= DATEADD(MONTH, -3, GETDATE())  order by PLANTRA.FECHAORDENO DESC
 
