-- Workspace: JERSALUD
-- Item: DataWareHouse_Clinical [Warehouse]
-- ItemId: 9c6eaf45-9b46-445f-bd43-868d6c10c562
-- Schema: ViewInternal
-- Object: VW_RUTA_ORDENCANCERPROSTATA
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE view [ViewInternal].[VW_RUTA_ORDENCANCERPROSTATA] as
SELECT DISTINCT  CASE
                WHEN CA.CODCENATE IN(002, 003, 004, 005, 006, 007, 008, 009,017,021)
                THEN 'BOYACA'
                WHEN CA.CODCENATE IN(010, 011, 012, 013, 014,018)
                THEN 'META'
                WHEN CA.CODCENATE IN (015,016,019,020)
                THEN 'CASANARE'
            END AS Regional,  ING.IFECHAING AS FECHA_INGRESO, ING.NUMINGRES AS INGRESO, LTRIM(RTRIM(CA.NOMCENATE)) AS CENTRO_ATENCION, 
				ING.IPCODPACI AS IDENTIFICACION_PACIENTE, C.CODSERIPS AS CUPS, C.DESSERIPS AS CUPS_DESCRIPCION, H.FECORDMED AS Fecha,
				DATEDIFF(year, P.IPFECNACI, ING.IFECHAING) AS EdadEnAtencion, H.*
FROM INDIGO031.dbo.HCORDLABO AS H 
INNER JOIN INDIGO031.dbo.INCUPSIPS AS C  ON C.CODSERIPS=H.CODSERIPS
INNER JOIN INDIGO031.dbo.ADINGRESO AS ING  ON ING.NUMINGRES=H.NUMINGRES
INNER JOIN INDIGO031.dbo.ADCENATEN AS CA  ON CA.CODCENATE = ING.CODCENATE
INNER JOIN INDIGO031.dbo.INPACIENT AS P  ON P.IPCODPACI = ING.IPCODPACI
WHERE H.CODSERIPS IN ('906611','906612','906610') AND H.ESTSERIPS<>'6'
