-- Workspace: SQLServer
-- Item: INDIGO035 [SQL]
-- ItemId: SPN
-- Schema: ViewInternal
-- Object: UltimaEvolucion
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [ViewInternal].[UltimaEvolucion] as

SELECT P.IPCODPACI, P.CODDIAGNO, DX.NOMDIAGNO, P.DATOBJETI, ES.DESESPECI
FROM 
(
SELECT MAX(FECHISPAC) AS FECHA, IPCODPACI AS DOCUMENTO
FROM DBO.HCHISPACA	AS P 
GROUP BY IPCODPACI
) AS R INNER JOIN
DBO.HCHISPACA AS P  ON P.IPCODPACI=R.DOCUMENTO AND P.FECHISPAC=R.FECHA
INNER JOIN DBO.INDIAGNOS AS DX ON DX.CODDIAGNO=P.CODDIAGNO
INNER JOIN DBO.INESPECIA AS ES ON ES.CODESPECI=P.CODESPTRA