-- Workspace: HOMI
-- Item: DataWareHouse_RCM [Warehouse]
-- ItemId: 834d5676-5644-4a78-a5e2-f198281d02d0
-- Schema: Report
-- Object: VW_CENSO_DIARIO_CON_VALORES
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.VW_CENSO_DIARIO_CON_VALORES
AS 

WITH CTE_CAMAS_OCUPADA AS (
    SELECT
        FUN.UFUDESCRI AS 'UNIDAD FUNCIONAL',
        C.IPCODPACI 'IDENTIFICACION',
        C.NUMINGRES 'INGRESO',
        A.NUMCAMHOS 'CAMA',
        G.DESTIPEST 'TIPO ESTANCIA',
        C.ID 'ID_ESTANCIA',
        A.CODICAMAS 'ID_CAMAS',
        CEN.NOMCENATE 'CENTRO DE ATENCION',
        A.CODCLAHAB,
        A.CODCLACAM
    FROM
        [INDIGO036].[dbo].[CHCAMASHO] A
        INNER JOIN [INDIGO036].[dbo].[INUNIFUNC] FUN ON A.UFUCODIGO = FUN.UFUCODIGO
        LEFT JOIN [INDIGO036].[dbo].[CHREGESTA] C ON A.CODICAMAS = C.CODICAMAS
            AND C.REGESTADO = 1
        LEFT JOIN [INDIGO036].[dbo].[CHTIPESTA] G ON G.CODTIPEST = C.CODTIPEST
        LEFT JOIN [INDIGO036].[dbo].[ADCENATEN] CEN ON CEN.CODCENATE = A.CODCENATE
),
CTE_PRIMERA_HOSPITALIZACION AS (
    SELECT
        EST.NUMINGRES,
        EST.IPCODPACI,
        EST.FECINIEST 'FECHA INICIAL HOSPITALIZACION'
    FROM
        [INDIGO036].[dbo].[CHREGESTA] EST
        INNER JOIN (
            SELECT
                EST.NUMINGRES,
                EST.IPCODPACI,
                MIN(EST.ID) ID
            FROM
                [INDIGO036].[dbo].[CHREGESTA] EST
                INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO = EST.NUMINGRES
            GROUP BY
                EST.NUMINGRES,
                EST.IPCODPACI
        ) AS G ON G.ID = EST.ID
),
CTE_ESPECIALIDAD_FINAL AS (
    SELECT
        HIS.NUMINGRES,
        HIS.IPCODPACI,
        HIS.CODESPTRA,
        ESP.DESESPECI 'ESPECIALIDAD',
        SAL.CODPROSAL,
        SAL.NOMMEDICO 'PROFESIONAL'
    FROM
        CTE_CAMAS_OCUPADA CAM
        INNER JOIN [INDIGO036].[dbo].[HCHISPACA] HIS ON CAM.INGRESO = HIS.NUMINGRES
            AND HIS.ID =(
                SELECT
                    MAX(H.ID)
                FROM
                    [INDIGO036].[dbo].[HCHISPACA] H
                WHERE
                    HIS.NUMINGRES = H.NUMINGRES
            )
        INNER JOIN [INDIGO036].[dbo].[INESPECIA] ESP ON ESP.CODESPECI = HIS.CODESPTRA
        INNER JOIN [INDIGO036].[dbo].[INPROFSAL] SAL ON HIS.CODPROSAL = SAL.CODPROSAL
),
CTE_REFERENCIA AS (
    SELECT
        REF.NUMINGRES,
        REF.AUTO,
        REF.FECSOLICIT,
        REF.FECCONFIR
    FROM
        [INDIGO036].[dbo].[HCREFCONP] AS REF
        INNER JOIN (
            SELECT
                NUMINGRES,
                MAX(AUTO) ID
            FROM
                [INDIGO036].[dbo].[HCREFCONP] REF
                INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO = REF.NUMINGRES
            WHERE
                ESTADO != 4
            GROUP BY
                NUMINGRES
        ) AS G ON G.NUMINGRES = REF.NUMINGRES
            AND G.ID = REF.AUTO
),
CTE_PAD AS (
    SELECT
        PAD.NUMINGRES,
        PAD.ID,
        PAD.FECHAREGISTRO
    FROM
        [INDIGO036].[dbo].[PADCONTROL] AS PAD
        INNER JOIN (
            SELECT
                NUMINGRES,
                MAX(ID) ID
            FROM
                [INDIGO036].[dbo].[PADCONTROL] PAD
                INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO = PAD.NUMINGRES
            WHERE
                ESTADO = '1'
            GROUP BY
                NUMINGRES
        ) AS G ON G.NUMINGRES = PAD.NUMINGRES
            AND G.ID = PAD.ID
),
CTE_SERVICIOS_PENDIENTES AS (
    SELECT
        RCD.Id,
        RCD.Status,
        RCD.StatusFolioId,
        RCD.InvoiceCategoryId,
        RC.AdmissionNumber 'INGRESO',
        ISNULL(RC.PatientCode, 0) AS 'IDENTIFICACION'
    FROM
        [INDIGO036].[Billing].[RevenueControlDetail] AS RCD
        INNER JOIN [INDIGO036].[Billing].[RevenueControl] AS RC ON RCD.RevenueControlId = RC.Id
        INNER JOIN [INDIGO036].[dbo].[ADINGRESO] AS ING ON ING.NUMINGRES = RC.AdmissionNumber
        INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO = ING.NUMINGRES
),
CTE_VALOR_ESTANCIA AS (
    SELECT
        RCD.INGRESO,
        RCD.IDENTIFICACION,
        SUM(
            ISNULL(DQ.TotalSalesPrice, SOD.GrandTotalSalesPrice)
        ) 'DET_ORD_VALOR_TOTAL'
    FROM
        CTE_SERVICIOS_PENDIENTES AS RCD
        INNER JOIN [INDIGO036].[Billing].[ServiceOrderDetailDistribution] AS SODD ON RCD.Id = SODD.RevenueControlDetailId
            AND RCD.Status IN ('1', '3')
        INNER JOIN [INDIGO036].[Billing].[ServiceOrderDetail] AS SOD ON SODD.ServiceOrderDetailId = SOD.Id
        LEFT JOIN[INDIGO036].[Billing].[ServiceOrderDetailSurgical] AS DQ ON DQ.ServiceOrderDetailId = SOD.Id
            AND DQ.OnlyMedicalFees = '0'
    WHERE
        SOD.IsDelete = '0'
    GROUP BY
        RCD.INGRESO,
        RCD.IDENTIFICACION
),
CTE_ALTA_MEDICA AS (
    SELECT
        EGR.NUMINGRES,
        EGR.IPCODPACI
    FROM
        [INDIGO036].[dbo].[HCREGEGRE] AS EGR
        INNER JOIN (
            SELECT
                NUMINGRES,
                MAX(EGR.FECALTPAC) FECALTPAC
            FROM
                [INDIGO036].[dbo].[HCREGEGRE] EGR
                INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO = EGR.NUMINGRES
            GROUP BY
                NUMINGRES
        ) AS G ON G.NUMINGRES = EGR.NUMINGRES
            AND G.FECALTPAC = EGR.FECALTPAC
),
CTE_INGRESO AS (
    SELECT
        ING.NUMINGRES,
        ING.IFECHAING,
        ING.IAUTORIZA AS [NUMERO AUTORIZACIÃ“N],
        ING.IOBSERVAC AS [OBSERVACIONES],
        HA.Name AS ENTIDAD,
        CASE
            HA.EntityType
            WHEN 1 THEN 'EPS CONTRIBUTIVO'
            WHEN 2 THEN 'EPS SUBSIDIADO'
            WHEN 3 THEN 'ET VINCULADO MUNICIPIO'
            WHEN 4 THEN 'ET VINCULADOS DAPARTAMENTO'
            WHEN 5 THEN 'ARL RIESGO LABORALES'
            WHEN 6 THEN 'MP MEDICINA PREPAGADA'
            WHEN 7 THEN 'IPS PRIVADA'
            WHEN 8 THEN 'IPS PUBLICA'
            WHEN 9 THEN 'REGIMEN ESPECIAL'
            WHEN 10 THEN 'ACCIDENTE DE TRANSITO'
            WHEN 11 THEN 'FOSYGA'
            WHEN 12 THEN 'OTROS'
        END AS [REGIMEN],
        RTRIM(Q.CODDIAGNO) + ' - ' + RTRIM(Q.NOMDIAGNO) AS [DIAGNOSTICO PRINCIPAL]
    FROM
        CTE_CAMAS_OCUPADA EST
        INNER JOIN [INDIGO036].[dbo].[ADINGRESO] ING ON EST.INGRESO = ING.NUMINGRES
        INNER JOIN [INDIGO036].[Contract].[HealthAdministrator] HA ON ING.GENCONENTITY = HA.Id
        LEFT JOIN [INDIGO036].[dbo].[INDIAGNOP] DIA ON ING.NUMINGRES = DIA.NUMINGRES
            AND DIA.CODDIAPRI = 1
        LEFT JOIN [INDIGO036].[dbo].[INDIAGNOS] Q ON DIA.CODDIAGNO = Q.CODDIAGNO
    GROUP BY
        ING.NUMINGRES,
        ING.IFECHAING,
        ING.IAUTORIZA,
        ING.IOBSERVAC,
        HA.Name,
        HA.EntityType,
        Q.CODDIAGNO,
        Q.NOMDIAGNO
)
SELECT
    CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
    CAM.[CENTRO DE ATENCION],
    CAM.ID_CAMAS AS [CODIGO CAMA],
    CAM.CAMA [CAMA],
    EST.NUMINGRES 'INGRESO',
    CAST(EST.FECINIEST as date) [FECHA INGRESO],
    DATEDIFF(DAY, EST.FECINIEST, GETDATE()) [DIAS TRANSCURRIDOS],
    TE.DESTIPEST AS [TIPO DE ESTANCIA],
    CAM.[UNIDAD FUNCIONAL] 'SERVICIO',
    CASE
        CAM.CODCLAHAB
        WHEN '1' THEN 'SALA OBSERVACION'
        WHEN '2' THEN 'SALA PROCEDIMIENTO'
        WHEN '3' THEN 'SALA RECUPERACION'
        WHEN '4' THEN 'HABITACION 1 CAMA'
        WHEN '5' THEN 'HABITACION 2 CAMAS'
        WHEN '6' THEN 'HABITACION 3 CAMAS'
        WHEN '7' THEN 'HABITACION 4 CAMAS'
        WHEN '8' THEN 'SUITE'
        WHEN '9' THEN 'HAB.ESPECIAL'
        WHEN '10' THEN 'UCI'
        WHEN '11' THEN 'OTRO'
    END AS [CLASE DE HABITACION],
    CASE
        CAM.CODCLACAM
        WHEN '1' THEN UPPER('ObservacionUrgencias')
        WHEN '2' THEN UPPER('Recuperacion Post Qx')
        WHEN '3' THEN 'HOSPITALARIA'
    END AS [CLASE DE CAMA],
    CASE
        PAC.IPTIPODOC
        WHEN '1' THEN 'CC'
        WHEN '2' THEN 'CE'
        WHEN '3' THEN 'TI'
        WHEN '4' THEN 'RC'
        WHEN '5' THEN 'PA'
        WHEN '6' THEN 'AS'
        WHEN '7' THEN 'MS'
        WHEN '8' THEN 'NU'
        WHEN '9' THEN 'NV'
        WHEN '10' THEN 'CD'
        WHEN '11' THEN 'SC'
        WHEN '12' THEN 'PE'
        WHEN '13' THEN 'PT'
        WHEN '14' THEN 'DE'
        WHEN '15' THEN 'SI'
        WHEN '17' THEN 'ME'
    END AS [TIPO DOCUMENTO],
    PAC.IPCODPACI AS [IDENTIFICACION],
    PAC.IPNOMCOMP AS [NOMBRE DEL PACIENTE],
    CASE
        PAC.IPSEXOPAC
        WHEN 1 THEN 'MASCULINO'
        ELSE 'FEMENINO'
    END AS 'SEXO',
    CAST(PAC.IPFECNACI AS DATE) 'FECHA NACIMIENTO',
    FLOOR(
        (
            CAST(CONVERT(VARCHAR(8), EST.FECINIEST, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)
        ) / 10000
    ) AS 'EDAD',
    PAC.IPDIRECCI AS DIRECCION,
    PAC.IPTELEFON AS TELEFONO,
    PAC.IPTELMOVI AS MOVIL,
    ING.ENTIDAD,
    ING.REGIMEN,
    NV.NIVDESCRI AS [CATEGORIA],
    ING.[DIAGNOSTICO PRINCIPAL],
    RTRIM(ISNULL(Prof.CODPROSAL, ESP.CODPROSAL)) + ' - ' + RTRIM(ISNULL(Prof.NOMMEDICO, ESP.PROFESIONAL)) 'MEDICO',
    RTRIM(ISNULL(K.DESESPECI, ESP.ESPECIALIDAD)) AS 'ESPECIALIDAD',
    ING.[NUMERO AUTORIZACIÃ“N],
    ING.[OBSERVACIONES],
    CASE
        WHEN REF.NUMINGRES IS NULL THEN 'NO'
        ELSE 'SI'
    END AS REFERENCIA,
    REF.FECSOLICIT AS [SOLICITUD REFERENCIA],
    CASE
        WHEN PAD.NUMINGRES IS NULL THEN 'NO'
        ELSE 'SI'
    END AS PAD,
    PAD.FECHAREGISTRO AS [FECHA PAD],
    CASE
        WHEN ALT.NUMINGRES IS NULL THEN '1 - Pacientes en la Unidad'
        ELSE '2 - Pacientes Con Salida'
    END AS 'ESTADO',
    ING.IFECHAING as 'FECHA INGRESO ADMISION',
    HOS.[FECHA INICIAL HOSPITALIZACION],
    EST.FECINIEST 'FECHA ASIGNACION UNIDAD',
    CAM.[TIPO ESTANCIA] [ESTANCIA],
    DATEDIFF(
        DAY,
        HOS.[FECHA INICIAL HOSPITALIZACION],
        GETDATE()
    ) 'DIAS DE HOSPITALIZACION',
    DATEDIFF(DAY, EST.FECINIEST, GETDATE()) 'DIAS EN LA UNIDAD',
    ISNULL(VAL.DET_ORD_VALOR_TOTAL, 0) 'VALOR',
    YEAR(EST.FECINIEST) AS 'AÃ‘O FECHA BUSQUEDA',
    MONTH(EST.FECINIEST) AS 'MES AÃ‘O FECHA BUSQUEDA',
    CASE
        MONTH(EST.FECINIEST)
        WHEN 1 THEN 'ENERO'
        WHEN 2 THEN 'FEBRERO'
        WHEN 3 THEN 'MARZO'
        WHEN 4 THEN 'ABRIL'
        WHEN 5 THEN 'MAYO'
        WHEN 6 THEN 'JUNIO'
        WHEN 7 THEN 'JULIO'
        WHEN 8 THEN 'AGOSTO'
        WHEN 9 THEN 'SEPTIEMBRE'
        WHEN 10 THEN 'OCTUBRE'
        WHEN 11 THEN 'NOVIEMBRE'
        WHEN 12 THEN 'DICIEMBRE'
    END AS 'MES NOMBRE FECHA BUSQUEDA',
    FORMAT(DAY(EST.FECINIEST), '00') AS 'DIA FECHA BUSQUEDA',
    CONVERT(
        DATETIME,
        GETDATE() AT TIME ZONE 'Pakistan Standard Time',
        1
    ) AS ULT_ACTUAL 
FROM
    [INDIGO036].[dbo].[CHREGESTA] EST
    INNER JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.ID_ESTANCIA = EST.ID
        AND CAM.INGRESO = EST.NUMINGRES
    LEFT JOIN CTE_INGRESO AS ING ON ING.NUMINGRES = EST.NUMINGRES
    INNER JOIN CTE_PRIMERA_HOSPITALIZACION HOS ON HOS.NUMINGRES = EST.NUMINGRES
    INNER JOIN [INDIGO036].[dbo].[INPACIENT] PAC ON EST.IPCODPACI = PAC.IPCODPACI
    INNER JOIN [INDIGO036].[dbo].[CHTIPESTA] AS TE ON TE.CODTIPEST = EST.CODTIPEST
    INNER JOIN [INDIGO036].[dbo].[ADNIVELES] NV ON PAC.NIVCODIGO = NV.NIVCODIGO
    LEFT JOIN [INDIGO036].[dbo].[INESPECIA] K ON EST.CODESPECI = K.CODESPECI
    LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] Prof ON EST.CODPROSAL = Prof.CODPROSAL
    LEFT JOIN CTE_ESPECIALIDAD_FINAL ESP ON ESP.NUMINGRES = EST.NUMINGRES
    LEFT JOIN CTE_ALTA_MEDICA AS ALT ON ALT.NUMINGRES = EST.NUMINGRES
    LEFT JOIN CTE_REFERENCIA REF ON REF.NUMINGRES = ALT.NUMINGRES
    LEFT JOIN CTE_PAD PAD ON PAD.NUMINGRES = ALT.NUMINGRES
    LEFT JOIN CTE_VALOR_ESTANCIA AS VAL ON VAL.INGRESO = EST.NUMINGRES;