-- Workspace: SQLServer
-- Item: INDIGO036 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_ERP_CUPS_VS_CONCEPTOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE PROCEDURE [Report].[IND_SP_V2_ERP_CUPS_VS_CONCEPTOS] 

AS


WITH CTE_CUPS
AS
(
 SELECT CUPS.CODE CUPS,CUPS.Description DESCRIPCION,CUPS.RIPSCode 'CODIGO RIPS', CG.Code 'CODIGO GRUPO' ,CG.Name 'NOMBRE GRUPO' ,CSG.Code 'CODIGO SUB GRUPO',CSG.Name 'SUB GRUPO',
 CASE CUPS.RIPSConcept WHEN 01 THEN '01 - Consultas'WHEN 02 THEN '02 - Procedimientos de diagnósticos'WHEN 03 THEN '03 - Procedimientos terapéuticos no quirúrgicos'
 WHEN 04 THEN '04 - Procedimientos terapéuticos quirúrgicos'WHEN 05 THEN '05 - Procedimientos de promoción y prevención'WHEN 06 THEN '06 - Estancias'WHEN 07 THEN '07 - Honorarios'
 WHEN 08 THEN '08 - Derechos de sala'WHEN 09 THEN '09 - Materiales e insumos'WHEN 10 THEN '10 - Banco de sangre'WHEN 11 THEN '11 - Prótesis y órtesis'WHEN 12 THEN '12 - Medicamentos POS'
 WHEN 13 THEN '13 - Medicamentos no POS'WHEN 14 THEN '14 - Traslado de pacientes' END 'CONCEPTO RIPS',CASE CUPS.ServiceType WHEN 1 THEN 'Laboratorios'WHEN 2 THEN 'Patologias'
 WHEN 3 THEN 'Imagenes Diagnosticas'WHEN 4 THEN 'Procedimeintos no Qx'WHEN 5 THEN 'Procedimientos Qx'WHEN 6 THEN 'Interconsultas'WHEN 7 THEN 'Ninguno'
 WHEN 8 THEN 'Consulta Externa' END 'TIPO SERVICIO',BG.Code 'CODIGO GRUPO FACTURACION' ,BG.Name 'GRUPO FACTURACION' ,BC.Code 'CODIGO CONCEPTO FACTURACION',
 BC.Name 'CONCEPTO DE FACTURACION',BC.ID ID_CF,cd.code 'CODIGO DESCRI REALACIONADA',CD.Name 'DESCRIPCION RELACIONADA',BGR.NAME 'GRUPO DESCRI RELACIONADA',
BCR.CODE 'COD CONCEPTO FACTURACION RELACIONADA',BCR.NAME 'CONCEPTO DE FACTURACION RELACIONADA',DESCR.BillingConceptId AS ID_CFR
 FROM Contract .CUPSEntity CUPS
 INNER JOIN Contract .CupsSubgroup CSG ON CSG.Id =CUPS.CUPSSubGroupId 
 INNER JOIN Contract .CupsGroup AS CG ON CG.Id =CSG.CupsGroupId 
 INNER JOIN Billing .BillingGroup BG ON BG.Id =CUPS.BillingGroupId 
 INNER JOIN Billing .BillingConcept AS BC ON BC.Id =CUPS.BillingConceptId 
 LEFT JOIN Contract .CUPSEntityContractDescriptions AS DESCR ON DESCR.CUPSEntityId =CUPS.Id 
 LEFT JOIN Contract .ContractDescriptions AS CD ON CD.ID=DESCR.ContractDescriptionId
 LEFT JOIN Billing .BillingGroup BGR ON BGR.Id =DESCR.BillingGroupId 
 LEFT JOIN Billing .BillingConcept AS BCR ON BCR.Id =DESCR.BillingConceptId 
),

CTE_CONCEPTOS
AS
(
SELECT *
FROM
(
  SELECT BC.Id ID_CON ,BC.Code 'CODIGO' ,BC.Name 'NOMBRE CONCEPTO',CASE BC.ConceptType WHEN 1 THEN 'Facturación Básica' when 2 then 'Facturacion Salud' END 'TIPO CONCEPTO',
  CASE BC.ObtainCostCenter WHEN 1 THEN  'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
  ELSE '' END 'OBTENER CENTRO COSTO',IIF(BC.ObtainCostCenter=2,CC.Code,'') 'CODIGO CC' ,IIF(BC.ObtainCostCenter=2,CC.Name,'')  'CENTRO COSTO',
  CASE BC.AccountingType WHEN 1 THEN 'Cuenta Unica de Ingreso' WHEN 2 THEN 'Cuenta por Tipo de Unidad' ELSE '' END 'TIPO CONTABILIZACION',
  IIF(BC.AccountingType=1,MA.Number,IIF(BC.ConceptType=1,MA.Number,''))'CUENTA ENTIDAD',IIF(BC.AccountingType=1,MA.Name,IIF(BC.ConceptType=1,MA.Name,''))'CUENTA INGRESO ENTIDAD',
  IIF(BC.AccountingType=1,MA2.Number,IIF(BC.ConceptType=1,MA2.Number,''))'CUENTA PARTICULAR',IIF(BC.AccountingType=1,MA2.Name,IIF(BC.ConceptType=1,MA2.Name,''))'CUENTA INGRESO PARTICULAR',
  IIF(BC.AccountingType=1,MA3.Number,IIF(BC.ConceptType=1,MA3.Number,''))'CUENTA RECONOCIMIENTO',IIF(BC.AccountingType=1,MA3.Name,IIF(BC.ConceptType=1,MA3.Name,''))'CUENTA INGRESO RECONOCIMIENTO',
  IIF(BC.AccountingType=1,MA4.Number,IIF(BC.ConceptType=1,MA4.Number,''))'CUENTA HONORARIOS',IIF(BC.AccountingType=1,MA4.Name,IIF(BC.ConceptType=1,MA4.Name,''))'CUENTA GASTO HONORARIO',
  IIF(BC.AccountingType=1,MA9.Number,IIF(BC.ConceptType=1,MA9.Number,''))'CUENTA DESCUENTO',IIF(BC.AccountingType=1,MA9.Name,IIF(BC.ConceptType=1,MA9.Name,''))'CUENTA PARA DESCUENTO',
  CASE BCA.UnitType WHEN 1 THEN 'URGENCIAS' WHEN 2 THEN 'HOSPITALIZACION' WHEN 3 THEN 'QUIROFANO' WHEN 4 THEN 'CONSULTA EXTERNA' END 'TIPO UNIDAD' ,
  MA5.NUMBER + '-' + 'IE' + '/' + MA6.NUMBER + '-' + 'IP' +'/' + MA8.NUMBER + '-'  +'GH' + '/' + MA7.NUMBER + '-' + 'RI' 'CUENTA INGRESO UF '--,MA6.NUMBER + '-' + MA6.NAME 'CUENTA PARTICULAR UF'--,MA7.NUMBER + '-' + MA7.NAME 'CUENTA RECONOCIMIENTO UF',
  --MA8.NUMBER + '-' + MA8.NAME 'CUENTA HONORARIO UF'
  FROM Billing.BillingConcept BC
  LEFT JOIN Payroll .CostCenter AS CC ON CC.Id =BC.ObtainCostCenter 
  LEFT JOIN GeneralLedger .MainAccounts MA ON MA.ID=BC.EntityIncomeAccountId 
  LEFT JOIN GeneralLedger .MainAccounts MA2 ON MA2.ID=BC.IndividualIncomeAccountId 
  LEFT JOIN GeneralLedger .MainAccounts MA3 ON MA3.ID=BC.IncomeRecognitionPendingBillingMainAccountId 
  LEFT JOIN GeneralLedger .MainAccounts MA4 ON MA4.ID=BC.FeesExpensesAccountId 
  LEFT JOIN GeneralLedger .MainAccounts MA9 ON MA9.ID=BC.DiscountAccountId 
  LEFT JOIN Billing.BillingConceptAccount AS BCA ON BCA.BillingConceptId =BC.ID
  --
  LEFT JOIN GeneralLedger .MainAccounts MA5 ON MA5.ID=BCA.EntityIncomeAccountId 
  LEFT JOIN GeneralLedger .MainAccounts MA6 ON MA6.ID=BCA.IndividualIncomeAccountId
  LEFT JOIN GeneralLedger .MainAccounts MA7 ON MA7.ID=BCA.IncomeRecognitionMainAccountId
  LEFT JOIN GeneralLedger .MainAccounts MA8 ON MA8.ID=BCA.FeesExpensesAccountId 

 -- WHERE BC.ID=4
 -- ORDER BY BC.ConceptType DESC, BC.CODE
) AS SourceTable

PIVOT  
(MAX([CUENTA INGRESO UF])
    FOR [TIPO UNIDAD] In([URGENCIAS],[HOSPITALIZACION],[QUIROFANO],[CONSULTA EXTERNA])
) AS PVTTABLE
--order by [TIPO CONCEPTO] 
)

--SELECT * FROM CTE_CONCEPTOS 

SELECT CUPS.CUPS ,CUPS.DESCRIPCION ,CUPS.[CODIGO RIPS] ,CUPS.[CODIGO GRUPO] ,CUPS.[NOMBRE GRUPO] ,CUPS.[CODIGO SUB GRUPO] ,CUPS.[SUB GRUPO] ,CUPS.[CONCEPTO RIPS] ,
CUPS.[TIPO SERVICIO],CUPS.[CODIGO GRUPO FACTURACION] ,CUPS.[GRUPO FACTURACION],CUPS.[CODIGO CONCEPTO FACTURACION] ,CUPS.[CONCEPTO DE FACTURACION],
CON.[TIPO CONCEPTO] ,CON.[OBTENER CENTRO COSTO] ,CON.[CENTRO COSTO] ,CON.[TIPO CONTABILIZACION] ,CON.[CUENTA ENTIDAD] ,CON.[CUENTA INGRESO ENTIDAD] ,
CON.[CUENTA PARTICULAR] ,CON.[CUENTA INGRESO PARTICULAR] ,CON.[CUENTA RECONOCIMIENTO] ,CON.[CUENTA INGRESO RECONOCIMIENTO] ,CON.[CUENTA HONORARIOS] ,CON.[CUENTA GASTO HONORARIO] ,
CON.[CUENTA DESCUENTO] ,CON.[CUENTA PARA DESCUENTO] ,CON.URGENCIAS ,CON.HOSPITALIZACION ,CON.QUIROFANO ,CON.[CONSULTA EXTERNA] ,
CUPS.[CODIGO DESCRI REALACIONADA] ,CUPS.[DESCRIPCION RELACIONADA],CUPS.[GRUPO DESCRI RELACIONADA] ,CUPS.[COD CONCEPTO FACTURACION RELACIONADA],CUPS.[CONCEPTO DE FACTURACION RELACIONADA] ,
CONR.[OBTENER CENTRO COSTO] AS [OBTENER CENTRO COSTO R] ,CONR.[CENTRO COSTO] [CENTRO COSTO R] ,
CONR.[TIPO CONTABILIZACION] [TIPO CONTABILIZACION R],
CONR.[CUENTA ENTIDAD] [CUENTA ENTIDAD R],CONR.[CUENTA INGRESO ENTIDAD] [CUENTA INGRESO ENTIDAD R] ,CONR.[CUENTA PARTICULAR] [CUENTA PARTICULAR R] ,
CONR.[CUENTA INGRESO PARTICULAR] [CUENTA INGRESO PARTICULAR R] ,CONR.[CUENTA RECONOCIMIENTO] [CUENTA RECONOCIMIENTO R] ,
CONR.[CUENTA INGRESO RECONOCIMIENTO] [CUENTA INGRESO RECONOCIMIENTO R],CONR.[CUENTA HONORARIOS] [CUENTA HONORARIOS R] ,CONR.[CUENTA GASTO HONORARIO] [CUENTA GASTO HONORARIO R],
CONR.URGENCIAS 'URGENCIAS R' ,CONR.HOSPITALIZACION 'HOSPITALIZACION R' ,CONR.QUIROFANO 'QUIROFANO R' ,CONR.[CONSULTA EXTERNA] 'CONSULTA EXTERNA R'


FROM CTE_CUPS CUPS
LEFT JOIN CTE_CONCEPTOS AS CON ON CUPS.ID_CF =CON.ID_CON 
LEFT JOIN CTE_CONCEPTOS AS CONR ON CUPS.ID_CFR   =CONR.ID_CON
--WHERE CUPS ='10M001'
--WHERE CUPS='902210'
