-- Workspace: SQLServer
-- Item: INDIGO036 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: SP_AUT_ORDENES_AMBULATORIAS_AUTORIZACIONES
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE PROCEDURE [Report].[SP_AUT_ORDENES_AMBULATORIAS_AUTORIZACIONES]
 @FechaInicial as DATETIME,
 @FechaFinal as DATETIME
AS

 --declare @FechaInicial DATETIME='2022-12-01'
 --declare @FechaFinal DATETIME ='2022-12-31';

WITH CTE_ORDENES
AS
(
-- Ordenes de imagenes ambulatorias
SELECT	
'HCORDIMAG' EntityName,
h.AUTO EntityId,		
h.CODCENATE CareCenterCode, 
h.UFUCODIGO FunctionalUnitCode,
h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
h.IPCODPACI PatientCode,h.FECORDMED RequestDate, h.CODPROSAL ProfessionalCode,
h.CANSERIPS Quantity,
1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,h.OBSSERIPS Observations,ESP.DESESPECI 'ESPECIALIDAD',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' 
				   WHEN '2' THEN 'CEDULA DE EXTRANJERIA' 
				   WHEN '3' THEN 'TARJETA DE IDENTIDAD' 
				   WHEN '4' THEN 'REGISTRO CIVIL'
				   WHEN '5' THEN 'PASAPORTE' 
				   WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' 
				   WHEN '7' THEN 'MENOR SIN IDENTIFICACION' 
				   WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION'
				   WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' 
				   WHEN '10' THEN 'CARNET DIPLOMATICO'
				   WHEN '11' THEN 'SALVOCONDUCTO' 
				   WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
				   WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA'
					WHEN '14' THEN 'DOCUMENTO EXTRANJERO'
					WHEN '15' THEN 'SIN IDENTIFICACION'  END AS 'TIPO IDENTIFICACION',
PRO.NOMMEDICO 'PROFESIONAL'
	FROM .HCORDIMAG h
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN INPROFSAL AS PRO ON PRO.CODPROSAL =H.CODPROSAL 
	INNER JOIN INESPECIA AS ESP ON ESP.CODESPECI =PRO.CODESPEC1 
	INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =H.IPCODPACI 
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id
	WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('6')) and cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
	-- Ordenes de laboratorios ambulatorios
SELECT	'HCORDLABO' EntityName, h.AUTO EntityId,		h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
h.IPCODPACI PatientCode,h.FECORDMED RequestDate, h.CODPROSAL ProfessionalCode,h.CANSERIPS Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,h.OBSSERIPS Observations,ESP.DESESPECI 'ESPECIALIDAD' ,
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' WHEN '2' THEN 'CEDULA DE EXTRANJERIA' WHEN '3' THEN 'TARJETA DE IDENTIDAD' WHEN '4' THEN 'REGISTRO CIVIL'
WHEN '5' THEN 'PASAPORTE' WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' WHEN '7' THEN 'MENOR SIN IDENTIFICACION' WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION'
WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO'WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION' END AS 'TIPO IDENTIFICACION',
PRO.NOMMEDICO 'PROFESIONAL'
	FROM .HCORDLABO h
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN INPROFSAL AS PRO ON PRO.CODPROSAL =H.CODPROSAL 
	INNER JOIN INESPECIA AS ESP ON ESP.CODESPECI =PRO.CODESPEC1 
    INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =H.IPCODPACI
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id
	WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('6')) and cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
	-- Ordenes de patologias ambulatorias
SELECT	'HCORDPATO' EntityName, h.AUTO EntityId,		h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
h.IPCODPACI PatientCode,h.FECORDMED RequestDate, h.CODPROSAL ProfessionalCode,h.CANSERIPS Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,h.OBSSERIPS Observations,ESP.DESESPECI 'ESPECIALIDAD',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' WHEN '2' THEN 'CEDULA DE EXTRANJERIA' WHEN '3' THEN 'TARJETA DE IDENTIDAD' WHEN '4' THEN 'REGISTRO CIVIL'
WHEN '5' THEN 'PASAPORTE' WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' WHEN '7' THEN 'MENOR SIN IDENTIFICACION' WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION'
WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO'WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION' END AS 'TIPO IDENTIFICACION',
PRO.NOMMEDICO 'PROFESIONAL'
	FROM .HCORDPATO h
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN INPROFSAL AS PRO ON PRO.CODPROSAL =H.CODPROSAL 
	INNER JOIN INESPECIA AS ESP ON ESP.CODESPECI =PRO.CODESPEC1
	INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =H.IPCODPACI
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id
	WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('6')) and cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
	-- Ordenes de interconsultas ambulatorias
SELECT	'HCORDINTE' EntityName, h.AUTO EntityId,		h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
h.IPCODPACI PatientCode,h.FECORDMED RequestDate, h.CODPROSAL ProfessionalCode,h.CANSERIPS Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,h.OBSSERIPS Observations,ESP.DESESPECI 'ESPECIALIDAD',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' WHEN '2' THEN 'CEDULA DE EXTRANJERIA' WHEN '3' THEN 'TARJETA DE IDENTIDAD' WHEN '4' THEN 'REGISTRO CIVIL'
WHEN '5' THEN 'PASAPORTE' WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' WHEN '7' THEN 'MENOR SIN IDENTIFICACION' WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION'
WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO'WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION' END AS 'TIPO IDENTIFICACION',
PRO.NOMMEDICO 'PROFESIONAL'
	FROM .HCORDINTE h
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN INPROFSAL AS PRO ON PRO.CODPROSAL =H.CODPROSAL 
	INNER JOIN INESPECIA AS ESP ON ESP.CODESPECI =PRO.CODESPEC1
	INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =H.IPCODPACI
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id
	WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('5')) and cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
	-- Ordenes de procedimientos no Qx ambulatorias
SELECT	'HCORDPRON' EntityName, h.AUTO EntityId,		h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
h.IPCODPACI PatientCode,h.FECORDMED RequestDate, h.CODPROSAL ProfessionalCode,h.CANSERIPS Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,h.OBSSERIPS Observations,ESP.DESESPECI 'ESPECIALIDAD',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' WHEN '2' THEN 'CEDULA DE EXTRANJERIA' WHEN '3' THEN 'TARJETA DE IDENTIDAD' WHEN '4' THEN 'REGISTRO CIVIL'
WHEN '5' THEN 'PASAPORTE' WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' WHEN '7' THEN 'MENOR SIN IDENTIFICACION' WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION'
WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO'WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION' END AS 'TIPO IDENTIFICACION',
PRO.NOMMEDICO 'PROFESIONAL'
	FROM .HCORDPRON h
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN INPROFSAL AS PRO ON PRO.CODPROSAL =H.CODPROSAL 
	INNER JOIN INESPECIA AS ESP ON ESP.CODESPECI =PRO.CODESPEC1
	INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =H.IPCODPACI
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id
	WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('5')) and cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
	-- Ordenes de procedimientos Qx ambulatorias
	SELECT	'HCORDPROQ' EntityName, h.AUTO EntityId,    h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
h.IPCODPACI PatientCode,h.FECORDMED RequestDate, h.CODPROSAL ProfessionalCode,h.CANSERIPS Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,h.OBSSERIPS Observations,ESP.DESESPECI 'ESPECIALIDAD',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' WHEN '2' THEN 'CEDULA DE EXTRANJERIA' WHEN '3' THEN 'TARJETA DE IDENTIDAD' WHEN '4' THEN 'REGISTRO CIVIL'
WHEN '5' THEN 'PASAPORTE' WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' WHEN '7' THEN 'MENOR SIN IDENTIFICACION' WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION'
WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO'WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION' END AS 'TIPO IDENTIFICACION',
PRO.NOMMEDICO 'PROFESIONAL'
	FROM .HCORDPROQ h
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN INPROFSAL AS PRO ON PRO.CODPROSAL =H.CODPROSAL 
	INNER JOIN INESPECIA AS ESP ON ESP.CODESPECI =PRO.CODESPEC1
	INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =H.IPCODPACI
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id
	WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('3')) and cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
	-- Hemocomponentes
SELECT 'HCORHEMCO' EntityName, h.ID EntityId,		h.CODCENATE CareCenterCode, ing.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
h.IPCODPACI PatientCode,h.FECORDMED RequestDate, '' ProfessionalCode,hd.Quantity Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,hd.CODSERIPS ItemCodeOriginal,
ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,'' Observations,'ESPECIALIDAD' 'ESPECIALIDAD',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' WHEN '2' THEN 'CEDULA DE EXTRANJERIA' WHEN '3' THEN 'TARJETA DE IDENTIDAD' WHEN '4' THEN 'REGISTRO CIVIL'
WHEN '5' THEN 'PASAPORTE' WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' WHEN '7' THEN 'MENOR SIN IDENTIFICACION' WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION'
WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO'WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION' END AS 'TIPO IDENTIFICACION',
PRO.NOMMEDICO 'PROFESIONAL'
	FROM .ADINGRESO ing
	INNER JOIN .HCORHEMCO h ON ing.NUMINGRES = h.NUMINGRES
	INNER JOIN 
	(
		SELECT	hd.HCORHEMCOID, 
				hd.CODSERIPS, 
				hd.TraceabilityPaperworkId, 
				hd.TraceabilityPaperworkEventsId, 
				hd.IDDESCRIPCIONRELACIONADA,
				COUNT(1) Quantity
		FROM .HCORHEMSER hd
		WHERE hd.ESTADO NOT IN (3)
		GROUP BY hd.HCORHEMCOID, hd.CODSERIPS, hd.TraceabilityPaperworkId, hd.TraceabilityPaperworkEventsId, hd.IDDESCRIPCIONRELACIONADA
	) hd ON h.ID = hd.HCORHEMCOID
	INNER JOIN Contract.CUPSEntity ce ON hd.CODSERIPS = ce.Code
	INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =H.IPCODPACI
	LEFT JOIN DBO.HCHISPACA AS HIS ON HIS.NUMEFOLIO =H.NUMEFOLIO AND HIS.IPCODPACI =H.IPCODPACI AND HIS.NUMINGRES =H.NUMINGRES 
	LEFT JOIN INPROFSAL AS PRO ON PRO.CODPROSAL =HIS.CODPROSAL 
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND hd.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id
	WHERE h.MANEXTPRO = 1 and cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
	-- Ordenes de control por la especialidad que atendió al paciente
SELECT	'HCDESCOEX' EntityName, h.AUTO EntityId,		h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
h.IPCODPACI PatientCode,hc.FECHISPAC RequestDate, hc.CODPROSAL ProfessionalCode,1 Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,hc.INDICAMED Observations,ESP.DESESPECI 'ESPECIALIDAD',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' WHEN '2' THEN 'CEDULA DE EXTRANJERIA' WHEN '3' THEN 'TARJETA DE IDENTIDAD' WHEN '4' THEN 'REGISTRO CIVIL'
WHEN '5' THEN 'PASAPORTE' WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' WHEN '7' THEN 'MENOR SIN IDENTIFICACION' WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION'
WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO'WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION' END AS 'TIPO IDENTIFICACION',
PRO.NOMMEDICO 'PROFESIONAL'
	FROM dbo.HCHISPACA hc
	INNER JOIN .HCDESCOEX h ON hc.NUMINGRES = h.NUMINGRES AND hc.NUMEFOLIO = h.NUMEFOLIO
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN INPROFSAL AS PRO ON PRO.CODPROSAL =HC.CODPROSAL 
	INNER JOIN INESPECIA AS ESP ON ESP.CODESPECI =PRO.CODESPEC1
	INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =H.IPCODPACI
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id
	WHERE cast(hc.FECHISPAC as date) between @FechaInicial and @FechaFinal
),
CTE_GESTION_AUTORIZACIONES
AS
(
  SELECT TP.AdmissionNumber ,TP.ServiceCode,TP.EntityId ,TP.EntityName  ,TP.PatientCode ,TP.RequestDate ,TP.RequestQuantity ,TP.CancellationReasonsId ,TP.CancellationReasonsObservations ,
  TP.PreviousStatus ,TP.STATUS,TP.CareGroupId ,TP.HealthAdministratorId ,TP.FunctionalUnitTargetId ,TP.AcceptanceStatus ,TP.ServiceId ,TP.ContractDescriptionId 
  FROM [Authorization].TraceabilityPaperwork TP
  WHERE TP.Type =1
),
CTE_PORTAFOLIO
AS
(
  SELECT csa.Id,apcc.CareCenterCode,1 Type, apce.CUPSEntityId ItemId,apce.ContractDescriptionId DescriptionId,apce.AuthorizationGroupId
	FROM [Authorization].AuthorizationPortfolioCareCenter apcc
	INNER JOIN [Authorization].AuthorizationPortfolio ap ON apcc.AuthorizationPortfolioId = ap.Id
	INNER JOIN [Authorization].AuthorizationPortfolioCUPSEntity apce ON ap.Id = apce.AuthorizationPortfolioId
	INNER JOIN [Authorization].ConfigurationServicesAmbulatory csa ON apce.Id = csa.AuthorizationPortfolioCUPSEntityId
	WHERE ap.Status = 1
),

--SELECT * FROM CTE_ORDENES 

CTE_RELACION
AS
(
SELECT 
ORD.*,
AUT.PreviousStatus,
AUT.Status 'ESTADO AUTORIZACION',
IIF(POR.Id IS NULL, 0, ISNULL(csae.SusceptibleAuthorization, 1)) Authorized,
fu.UFUDESCRI FunctionalUnitName,
cg.Id CareGroupId, 
cg.Code CareGroupCode, 
cg.Name CareGroupName,
ha.Id HealthAdministratorId, 
ha.Code HealthAdministratorCode, 
ha.Name HealthAdministratorName, 
RTRIM(LTRIM(p.IPNOMCOMP))PatientName,
p.IPDIRECCI PatientAddress,
P.IPTELMOVI,p.IPTELEFON PatientPhone,dbo.Edad(p.IPFECNACI, HC.FECHISPAC) PatientAge,p.IPFECNACI,HC.FECHISPAC ,
CASE CUPS.ServiceType WHEN 1 THEN 'Laboratorios' 
					  WHEN 2 THEN 'Patologias' 
					  WHEN 3 THEN 'Imagenes Diagnosticas'
					  WHEN 4 THEN 'Procedimientos no Qx' 
					  WHEN 5 THEN 'Procedimientos Qx' 
					  WHEN 6 THEN 'Interconsultas' 
					  WHEN 7 THEN 'Ninguno' 
					  WHEN 8 THEN 'Consulta Externa' 
					  WHEN 9 THEN 'HEMOCOMPONENTES' END 'TIPO SERVICIO',

CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO' 
				   WHEN 'F' THEN 'FACTURADO' 
				   WHEN 'A' THEN 'ANULADO' 
				   WHEN 'C' THEN 'CERRADO' 
				   WHEN 'P' THEN 'FACTURADO PARCIAL' END 'ESTADO INGRESO ATENCION',
HC.CODDIAGNO 'CIE10', 
DIA.NOMDIAGNO 'DIAGNOSTICO'
  --, ORD.DescriptionCodeName, ORD.ItemCode,ORD.ItemCodeOriginal,ORD.ItemId,ORD.ItemName,ORD.ProfessionalCode,ORD.Quantity,ORD.RequestDate,ORD.Type,ORD.PatientCode
FROM CTE_ORDENES ORD
INNER JOIN DBO.ADCENATEN cc ON ORD.CareCenterCode = cc.CODCENATE
INNER JOIN DBO.INUNIFUNC fu ON ORD.FunctionalUnitCode = fu.UFUCODIGO
INNER JOIN DBO.ADINGRESO ing ON ORD.AdmissionNumber = ing.NUMINGRES
INNER JOIN Contract.CareGroup cg ON ing.GENCAREGROUP = cg.Id
INNER JOIN Contract.HealthAdministrator ha ON ing.GENCONENTITY = ha.Id
INNER JOIN DBO.INPACIENT p ON ORD.PatientCode = p.IPCODPACI
INNER JOIN Contract .CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Code =ORD.ItemCodeOriginal 
LEFT JOIN Contract.ProcedureCups ptc ON ORD.Type = 1 AND cg.ProcedureTemplateId = ptc.ProceduresTemplateId AND ORD.ItemId = ptc.CupsId AND ISNULL(ORD.ContractDescriptionId, 0) = ISNULL(ptc.CUPSEntityContractDescriptionId, 0)
LEFT JOIN CTE_GESTION_AUTORIZACIONES AS AUT ON ORD.EntityId =AUT.EntityId AND ORD.EntityName =AUT.EntityName  AND ORD.ItemCodeOriginal =AUT.ServiceCode
LEFT JOIN CTE_PORTAFOLIO AS POR ON POR.CareCenterCode =ORD.CareCenterCode AND  ORD.ItemId = POR.ItemId AND ISNULL(ORD.DescriptionId, 0) = ISNULL(POR.DescriptionId, 0)
LEFT JOIN [Authorization].AuthorizationGroup ag on ag.Id = POR.AuthorizationGroupId
LEFT JOIN [Authorization].ConfigurationServicesAmbulatoryExceptions csae ON POR.Id = csae.ConfigurationServicesAmbulatoryId AND cg.Id = csae.CareGroupId
LEFT JOIN [Authorization].ManagementMedicalOrder mmo ON ORD.EntityName = mmo.EntityName AND ORD.EntityId = mmo.EntityId AND ORD.ItemCodeOriginal = mmo.ItemCode
LEFT JOIN DBO.HCHISPACA hc ON ORD.Folio = hc.NUMEFOLIO AND ORD.PatientCode = hc.IPCODPACI
LEFT JOIN DBO.INPROFSAL prof on prof.CODPROSAL = ORD.ProfessionalCode
LEFT JOIN DBO.INDIAGNOS AS DIA ON DIA.CODDIAGNO =HC.CODDIAGNO 
),
--SELECT * FROM CTE_RELACION 

CTE_DATOS_UNICOS_ORDENES
AS
(
  SELECT DISTINCT AUT.PatientCode 'IDENTIFICACION',AUT.AdmissionNumber 'INGRESO',AUT.ItemCodeOriginal 'CUPS' 
  FROM CTE_RELACION AUT
  WHERE [ESTADO AUTORIZACION] IS NULL --AND AdmissionNumber ='69299     '
),
CTE_PROGRAMACION_AGENDAMIENTOS
AS
(
  SELECT DISTINCT 
  CIT.IPCODPACI 'IDENTIFICACION',
  ACT.CODSERIPS 'CUPS', 
  IPS.DESSERIPS 'DESCRIPCION CUPS',
  CAST(CIT.FECHORAIN AS DATE)'FECHA BUSQUEDA',
  CASE cit.CODESTCIT WHEN 0 THEN 'PROGRAMADA' 
					 WHEN 1 THEN 'CUMPLIDA' END 'ESTADO DE CITA'
  FROM  AGASICITA CIT WITH (NOLOCK)
  INNER JOIN CTE_ORDENES AS ORD WITH (NOLOCK) ON ORD.PatientCode =CIT.IPCODPACI 
  INNER JOIN DBO.AGACTIMED AS ACT WITH (NOLOCK) ON ACT.CODACTMED =CIT.CODACTMED 
  INNER JOIN DBO.INCUPSIPS IPS WITH (NOLOCK) ON IPS.CODSERIPS =ACT.CODSERIPS
  WHERE CIT.CODESTCIT in ('0','1') --and cit.IPCODPACI ='1020819742'
),
CTE_PROGRAMACION_AGENDAMIENTOS_CIRUGIAS
AS
(
  SELECT DISTINCT 
  AGE.IPCODPACI 'IDENTIFICACION',
  AGE.CODSERIPS 'CUPS', 
  IPS.DESSERIPS 'DESCRIPCION CUPS',
  CAST(AGE.FECHORAIN AS DATE) 'FECHA BUSQUEDA','PROGRAMADO' 'ESTADO CITA'
  FROM  AGEPROGQX AGE WITH (NOLOCK)
  INNER JOIN DBO.INCUPSIPS IPS WITH (NOLOCK) ON IPS.CODSERIPS =AGE.CODSERIPS
  INNER JOIN CTE_ORDENES AS ORD WITH (NOLOCK) ON ORD.PatientCode =AGE.IPCODPACI 
),
CTE_FACTURA_UNICA
AS
(
  SELECT DISTINCT F.ID,F.InvoiceNumber ,F.AdmissionNumber ,F.PatientCode   FROM 
  Billing.Invoice AS F WITH (NOLOCK)
  INNER JOIN CTE_DATOS_UNICOS_ORDENES AS UNI ON UNI.IDENTIFICACION =F.PatientCode 
  WHERE DOCUMENTTYPE NOT IN (5,6) AND F.Status =1 --AND CAST(F.InvoiceDate AS DATE)  BETWEEN  @FECINI AND @FECFIN
),
CTE_DETALLE_FACTURA
AS
(

  SELECT DISTINCT F.PatientCode ,CUPS.Code 'CUPS',CUPS.Description 'DESCRIPCION CUPS',MIN(CAST(F.InvoiceDate AS DATE)) 'FECHA FACTURA'   
  FROM Billing.Invoice AS F WITH (NOLOCK)
  INNER JOIN CTE_FACTURA_UNICA AS FCAB WITH (NOLOCK) ON FCAB.Id =F.ID
  INNER JOIN Billing .InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =F.Id 
  INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId 
  INNER JOIN Billing .ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId 
  INNER JOIN Contract.CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id = SOD.CUPSEntityId
  WHERE SOD.RecordType =1
  GROUP BY F.PatientCode ,CUPS.Code,CUPS.Description
)
--SELECT * FROM CTE_DETALLE_FACTURA 

SELECT DISTINCT 
AUT.RequestDate 'FECHA ORDEN',
AUT.[TIPO IDENTIFICACION],
AUT.PatientCode 'IDENTIFICACION',
AUT.PatientName 'PACIENTE',AUT.AdmissionNumber 'INGRESO',AUT.[TIPO SERVICIO] ,'ORDENADO' 'ESTADO',
AUT.PatientPhone 'TELEFONO',AUT.IPTELMOVI 'CELULAR',AUT.PatientAddress 'DIRECCION',
AUT.ItemCodeOriginal 'CUPS',ItemName 'DESCRIPCION CUPS',AUT.DescriptionCodeName 'DESCRIPCION RELACIONADA' ,CASE AUT.Authorized WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'SUSCEPTIBLE AUTORIZACION',AUT.FunctionalUnitName 'UNIDAD FUNCIONAL',
AUT.HealthAdministratorName 'ENTIDAD',
AUT.CareGroupCode 'CODIGO GRUPO ANTENCION',
AUT.CareGroupName 'GRUPO ATENCION',
AUT.[ESTADO INGRESO ATENCION],
IIF(ISNULL(AGE.CUPS,CIR.CUPS) IS NULL,'NO','SI') 'PROGRAMADO AGENDAMIENTO',
ISNULL(AGE.CUPS,CIR.CUPS) 'CUPS PROGRMADO',
ISNULL(AGE.[DESCRIPCION CUPS],CIR.[DESCRIPCION CUPS]) 'CUPS PROGRAMADO',
ISNULL(AGE.[FECHA BUSQUEDA],CIR.[FECHA BUSQUEDA]) 'FECHA PROGRAMADA', 
ISNULL(AGE.[ESTADO DE CITA],CIR.[ESTADO CITA]) 'ESTADO CITA',
IIF(FAC.CUPS IS NULL,'NO','SI') 'CUPS FACTURADO',
FAC.[FECHA FACTURA] ,
AUT.ESPECIALIDAD,
AUT.Quantity AS CANTIDAD,
AUT.PROFESIONAL ,AUT.CIE10 ,AUT.DIAGNOSTICO,AUT.Observations AS [OBSERVACION]
FROM CTE_RELACION AUT
LEFT JOIN CTE_PROGRAMACION_AGENDAMIENTOS AS AGE ON AUT.PatientCode =AGE.IDENTIFICACION AND AUT.ItemCodeOriginal =AGE.CUPS AND AGE.[FECHA BUSQUEDA] >= AUT.RequestDate 
LEFT JOIN CTE_PROGRAMACION_AGENDAMIENTOS_CIRUGIAS AS CIR ON AUT.PatientCode =CIR.IDENTIFICACION AND AUT.ItemCodeOriginal =CIR.CUPS AND CIR.[FECHA BUSQUEDA] >= AUT.RequestDate 
LEFT JOIN CTE_DETALLE_FACTURA AS FAC ON FAC.PatientCode =AUT.PatientCode AND FAC.CUPS =AUT.ItemCodeOriginal AND FAC.[FECHA FACTURA] >= AUT.RequestDate
WHERE [ESTADO AUTORIZACION] IS NULL -- AND CIR.CUPS IS NOT NULL  --AdmissionNumber ='69299     '
ORDER BY AUT.RequestDate DESC
