-- Workspace: SQLServer
-- Item: INDIGO036 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: SP_AUT_ORDENES_AMBULATORIAS_AUTORIZACIONES_AUTORIZADOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0





CREATE PROCEDURE [Report].[SP_AUT_ORDENES_AMBULATORIAS_AUTORIZACIONES_AUTORIZADOS]
 @FechaInicial as DATETIME,
 @FechaFinal as DATETIME
AS

 --declare @FechaInicial DATETIME='2022-11-01'
 --declare @FechaFinal DATETIME ='2022-12-30';


WITH 
CTE_ORDENES
AS
(
-- Ordenes de imagenes ambulatorias
SELECT 'HCORDIMAG' EntityName, h.AUTO EntityId,	h.CANSERIPS Quantity,h.OBSSERIPS Observations
FROM DBO.HCORDIMAG h
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
-- Ordenes de laboratorios ambulatorios
SELECT 'HCORDLABO' EntityName, h.AUTO EntityId, h.CANSERIPS Quantity,h.CODSERIPS Observations
FROM DBO.HCORDLABO h
WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('6')) and cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
-- Ordenes de patologias ambulatorias
SELECT 'HCORDPATO' EntityName, h.AUTO EntityId, h.CANSERIPS Quantity,h.OBSSERIPS Observations
FROM DBO.HCORDPATO h
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
-- Ordenes de interconsultas ambulatorias
SELECT 'HCORDINTE' EntityName, h.AUTO EntityId, h.CANSERIPS Quantity,h.OBSSERIPS Observations
FROM DBO.HCORDINTE h
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
-- Ordenes de procedimientos no Qx ambulatorias
SELECT 'HCORDPRON' EntityName, h.AUTO EntityId, h.CANSERIPS Quantity,h.OBSSERIPS Observations
FROM DBO.HCORDPRON h
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
-- Ordenes de procedimientos Qx ambulatorias
SELECT	'HCORDPROQ' EntityName, h.AUTO EntityId, h.CANSERIPS Quantity, h.OBSSERIPS Observations
FROM DBO.HCORDPROQ h
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
--Hemocomponentes
SELECT 'HCORHEMCO' EntityName, h.ID EntityId, hd.Quantity Quantity,'' Observations
FROM .ADINGRESO ing
INNER JOIN .HCORHEMCO h ON ing.NUMINGRES = h.NUMINGRES
INNER JOIN 
(
	SELECT	hd.HCORHEMCOID, 
			hd.CODSERIPS, 
			hd.TraceabilityPaperworkId, 
			hd.TraceabilityPaperworkEventsId, 
			hd.IDDESCRIPCIONRELACIONADA,
			COUNT(1) Quantity
	FROM .HCORHEMSER hd
	WHERE hd.ESTADO NOT IN (3)
	GROUP BY hd.HCORHEMCOID, hd.CODSERIPS, hd.TraceabilityPaperworkId, hd.TraceabilityPaperworkEventsId, hd.IDDESCRIPCIONRELACIONADA
) hd ON h.ID = hd.HCORHEMCOID
WHERE cast(h.FECORDMED as date) between @FechaInicial and @FechaFinal
UNION ALL
-- Ordenes de control por la especialidad que atendió al paciente
SELECT 'HCDESCOEX' EntityName, h.AUTO EntityId, 1 Quantity, hc.INDICAMED Observations
FROM dbo.HCHISPACA hc
INNER JOIN .HCDESCOEX h ON hc.NUMINGRES = h.NUMINGRES AND hc.NUMEFOLIO = h.NUMEFOLIO
WHERE cast(hc.FECHISPAC as date) between @FechaInicial and @FechaFinal
),

CTE_AUTORIZACIONES_AMBULATORIAS_RADICADAS
AS
(
select TP.Id ,RTRIM(ha.Name) 'ENTIDAD',CG.Code 'CODIGO GRUPO', RTRIM(CG.Name) 'GRUPO DE ATENCION',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' 
				   WHEN '2' THEN 'CEDULA DE EXTRANJERIA' 
				   WHEN '3' THEN 'TARJETA DE IDENTIDAD' 
				   WHEN '4' THEN 'REGISTRO CIVIL'WHEN '5' THEN 'PASAPORTE' 
				   WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' 
				   WHEN '7' THEN 'MENOR SIN IDENTIFICACION' 
				   WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION' 
				   WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' 
				   WHEN '10' THEN 'CARNET DIPLOMATICO'
				   WHEN '11' THEN 'SALVOCONDUCTO' 
				   WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
TP.PatientCode 'IDENTIFICACION',
PAC.IPNOMCOMP 'PACIENTE',PAC.IPTELEFON 'TELEFONO',PAC.IPTELMOVI 'CELULAR',PAC.IPDIRECCI 'DIRECCION',
tp.AdmissionNumber 'INGRESO' ,tp.Folio 'FOLIO' ,CASE CUPS.ServiceType WHEN 1 THEN 'Laboratorios' WHEN 2 THEN 'Patologias' WHEN 3 THEN 'Imagenes Diagnosticas'
  WHEN 4 THEN 'Procedimientos no Qx' WHEN 5 THEN 'Procedimientos Qx' WHEN 6 THEN 'Interconsultas' WHEN 7 THEN 'Ninguno' WHEN 8 THEN 'Consulta Externa'
  WHEN 9 THEN 'HEMOCOMPONENTES' END 'TIPO SERVICIO',tp.ServiceCode 'CODIGO CUPS ORDENADO',CUPS.Description 'DESCRIPCION CUPS ORDENADO',cd.Name 'DESCRIPCION RELACIONADA',
  TP.RequestQuantity 'CANTIDAD ORDENADA' ,tp.RequestDate 'FECHA ORDEN',
--'AUTORIZADO' 'ESTADO',
CASE TP.Status WHEN 1 THEN 'Solicitado' 
			   WHEN 2 THEN 'Radicado'
			   WHEN 3 THEN 'Radicado Pendiente de Autorizacion' 
			   WHEN 4 THEN 'Radicado No Autorizado'
			   WHEN 5 THEN 'Autorizado'
			   WHEN 6 THEN 'Autorizado en Entrega'
			   WHEN 7 THEN 'Autorizado Entregado'
			   WHEN 8 THEN 'Autorizado Agendado'
			   WHEN 9 THEN 'Autorizado Ejecutado'
			   WHEN 10 THEN 'Autorizado Facturado'
			   WHEN 11 THEN 'Cancelado'
			   WHEN 12 THEN 'Solicitado en Cotización' 
			   WHEN 13 THEN 'Radicado en Cotización'
			   WHEN 14 THEN 'Autorizado Remitido'
			   WHEN 15 THEN 'Autorizado con Cotización'
			   WHEN 16 THEN 'Postergado' END AS [ESTADO DETALLADO],
CAN.Name AS [MOTIVO DE CANCELACION],
TP.CancellationReasonsObservations AS [OBSERVACION CANCELACION],
CASE TPE.ReportType WHEN 1 THEN 'Llamada Telefónica' 
					WHEN 2 THEN 'Envío Físico' 
					WHEN 3 THEN 'Registro Página Web' 
					WHEN 4 THEN 'Correo Electrónico'
					WHEN 5 THEN 'Tramita Paciente' END 'TIPO REPORTE',
CASE TPE.Status WHEN 1 THEN 'Pendiente por Autorizar' 
				WHEN 2 THEN 'Autorizado'  
				WHEN 3 THEN 'No Autorizado' 
				WHEN 4 THEN 'Autorizado con Aval' END 'ESTADO EVENTO',
TPE.Observations AS [OBSERVACION DE EVENTO],
IIF(tp.AdmissionNumber IS NULL,TP.DocumentDate,
IIF(TPE.ReportType ='5',TPE.CreationDate,ISNULL(TPE.RegistrationDate,ISNULL(TPE.SendDate,ISNULL(TPE.InitialTime,ISNULL(TPE.CreationDate,TP.DocumentDate)))))) 'FECHA RADICADO', 
TPE.RadicateNumber 'NUMERO RADICADO',USU.NOMUSUARI 'USUARIO CREO',TPE.AuthorizationNumber 'NUMERO AUTORIZACION' ,TPE.AuthorizedQuantity 'CANTIDAD AUTRIZADA',
TPE.AuthorizationDate 'FECHA AUTORIZACION' ,TPE.AuthorizationExpiredDate 'FECHA EXPIRACION AUTORIZACION',PRO.NOMMEDICO 'PROFESIONAL',ESP.DESESPECI 'ESPECIALIDAD',
ISNULL(ING.CODDIAING,ING.CODDIAEGR) 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',ORD.Observations AS [OBSERVACION]
from [Authorization].TraceabilityPaperwork tp with(nolock)
INNER JOIN Contract .CUPSEntity AS CUPS with(nolock) ON CUPS.CODE =tp.ServiceCode
INNER JOIN DBO.INPACIENT AS PAC with(nolock) ON PAC.IPCODPACI =TP.PatientCode 
INNER JOIN INPROFSAL AS PRO ON PRO.CODPROSAL =tp.ProfessionalCode  
INNER JOIN INESPECIA AS ESP ON ESP.CODESPECI =PRO.CODESPEC1
LEFT JOIN DBO.ADINGRESO AS ING with(nolock) ON ING.NUMINGRES =tp.AdmissionNumber
LEFT JOIN Contract .HealthAdministrator ha on ha.Id =tp.HealthAdministratorId 
LEFT JOIN Contract .CareGroup AS CG ON CG.Id =TP.CareGroupId 
LEFT JOIN [Authorization].TraceabilityPaperworkEvents AS TPE with(nolock) ON TPE.TraceabilityPaperworkId =TP.Id 
LEFT JOIN SEGusuaru AS USU ON USU.CODUSUARI =TPE.CreationUser 
LEFT JOIN DBO.INDIAGNOS AS DIA with(nolock) ON DIA.CODDIAGNO =ISNULL(ING.CODDIAING,ING.CODDIAEGR)
--LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON CUPS.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
LEFT JOIN Contract.ContractDescriptions cd ON tp.ContractDescriptionId = cd.Id
LEFT JOIN CTE_ORDENES ORD ON TP.EntityName=ORD.EntityName AND TP.EntityId=ORD.EntityId
LEFT JOIN [Authorization].CancellationReasons CAN ON TP.CancellationReasonsId=CAN.Id
WHERE cast(tp.RequestDate as date) between @FechaInicial and @FechaFinal
--where tpe.Status =3 /*and tp.Status in (5,6,7,8,10,14,15) AND TPE.Status NOT IN (1,3)*/
),
CTE_DATOS_UNICOS_ORDENES
AS
(
  SELECT DISTINCT AUT.IDENTIFICACION ,AUT.INGRESO ,AUT.[CODIGO CUPS ORDENADO] 
  FROM CTE_AUTORIZACIONES_AMBULATORIAS_RADICADAS AUT
  where aut.[FECHA ORDEN] >=@FechaInicial
 -- WHERE [ESTADO AUTORIZACION] IS NULL --AND AdmissionNumber ='69299     '
),
CTE_PROGRAMACION_AGENDAMIENTOS
AS
(
  SELECT DISTINCT CIT.IPCODPACI 'IDENTIFICACION',ACT.CODSERIPS 'CUPS', IPS.DESSERIPS 'DESCRIPCION CUPS' ,CAST(CIT.FECHORAIN AS DATE) 'FECHA BUSQUEDA',
  case cit.CODESTCIT when 0 then 'PROGRAMADA' WHEN 1 THEN 'CUMPLIDA' END 'ESTADO DE CITA' 
  FROM  AGASICITA CIT WITH (NOLOCK)
  INNER JOIN CTE_DATOS_UNICOS_ORDENES AS ORD WITH (NOLOCK) ON ORD.IDENTIFICACION =CIT.IPCODPACI 
  INNER JOIN DBO.AGACTIMED AS ACT WITH (NOLOCK) ON ACT.CODACTMED =CIT.CODACTMED 
  INNER JOIN DBO.INCUPSIPS IPS WITH (NOLOCK) ON IPS.CODSERIPS =ACT.CODSERIPS
  WHERE CIT.CODESTCIT in ('0','1') AND CIT.FECHORAIN >=@FechaInicial --and cit.IPCODPACI ='1020819742'
),
CTE_PROGRAMACION_AGENDAMIENTOS_CIRUGIAS
AS
(
  SELECT DISTINCT AGE.IPCODPACI 'IDENTIFICACION',AGE.CODSERIPS 'CUPS', IPS.DESSERIPS 'DESCRIPCION CUPS' ,CAST(AGE.FECHORAIN AS DATE) 'FECHA BUSQUEDA','PROGRAMADO' 'ESTADO CITA'
  FROM  AGEPROGQX AGE WITH (NOLOCK)
  INNER JOIN DBO.INCUPSIPS IPS WITH (NOLOCK) ON IPS.CODSERIPS =AGE.CODSERIPS
  INNER JOIN CTE_DATOS_UNICOS_ORDENES AS ORD WITH (NOLOCK) ON ORD.IDENTIFICACION =AGE.IPCODPACI 
  WHERE AGE.FECHORAIN >=@FechaInicial
),
CTE_FACTURA_UNICA
AS
(
  SELECT DISTINCT F.ID,F.InvoiceNumber ,F.AdmissionNumber ,F.PatientCode   FROM 
  Billing.Invoice AS F WITH (NOLOCK)
  INNER JOIN CTE_DATOS_UNICOS_ORDENES AS UNI ON UNI.IDENTIFICACION =F.PatientCode 
  WHERE DOCUMENTTYPE NOT IN (5,6) AND F.Status =1 AND CAST(F.InvoiceDate AS DATE)>=@FechaInicial
),
CTE_DETALLE_FACTURA
AS
(

  SELECT DISTINCT F.PatientCode ,CUPS.Code 'CUPS',CUPS.Description 'DESCRIPCION CUPS',MIN(CAST(F.InvoiceDate AS DATE)) 'FECHA FACTURA'   ,
  CASE ING.TIPOINGRE   WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'TIPO INGRESO'
  FROM Billing.Invoice AS F WITH (NOLOCK)
  INNER JOIN CTE_FACTURA_UNICA AS FCAB WITH (NOLOCK) ON FCAB.Id =F.ID
  INNER JOIN Billing .InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =F.Id 
  INNER JOIN Billing .ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId 
  INNER JOIN Billing .ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId 
  INNER JOIN Contract.CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id = SOD.CUPSEntityId
  INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES =F.AdmissionNumber 
  WHERE SOD.RecordType =1
  GROUP BY F.PatientCode ,CUPS.Code,CUPS.Description,ING.TIPOINGRE
)

SELECT DISTINCT 
AUT.* ,IIF(ISNULL(AGE.CUPS,CIR.CUPS) IS NULL,'NO','SI') 'PROGRAMADO AGENDAMIENTO',
ISNULL(AGE.CUPS,CIR.CUPS) 'CODIGO CUPS PROGRAMADO',ISNULL(AGE.[DESCRIPCION CUPS],CIR.[DESCRIPCION CUPS]) 'CUPS PROGRAMADO',
--ISNULL(AGE.[FECHA BUSQUEDA],CIR.[FECHA BUSQUEDA]) 'FECHA PROGRAMADA'--, ISNULL(AGE.[ESTADO DE CITA],CIR.[ESTADO CITA]) 'ESTADO CITA'
IIF(FAC.[TIPO INGRESO]='HOSPITALARIO','NO',IIF(FAC.CUPS IS NULL,'NO','SI')) 'CUPS FACTURADO' ,FAC.[FECHA FACTURA], FAC.[TIPO INGRESO]
FROM CTE_AUTORIZACIONES_AMBULATORIAS_RADICADAS AUT
LEFT JOIN CTE_PROGRAMACION_AGENDAMIENTOS AS AGE ON AUT.IDENTIFICACION =AGE.IDENTIFICACION AND AUT.[CODIGO CUPS ORDENADO] =AGE.CUPS AND AGE.[FECHA BUSQUEDA] >= AUT.[FECHA ORDEN] 
LEFT JOIN CTE_PROGRAMACION_AGENDAMIENTOS_CIRUGIAS AS CIR ON AUT.IDENTIFICACION =CIR.IDENTIFICACION AND AUT.[CODIGO CUPS ORDENADO] =CIR.CUPS AND CIR.[FECHA BUSQUEDA] >= AUT.[FECHA ORDEN] 
LEFT JOIN CTE_DETALLE_FACTURA AS FAC ON FAC.PatientCode =AUT.IDENTIFICACION AND FAC.CUPS =AUT.[CODIGO CUPS ORDENADO] AND FAC.[FECHA FACTURA] >= AUT.[FECHA ORDEN]
where  cast(AUT.[FECHA ORDEN] as date) between @FechaInicial and @FechaFinal
--ORDER BY AUT.Id ,AUT.[FECHA RADICADO] 
