-- Workspace: SQLServer
-- Item: INDIGO036 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: SP_FAC_REPORTE_HOSPITALARIO_PENDIENTE_POR_RECONOCER
-- Extracted by Fabric SQL Extractor SPN v3.9.0







CREATE PROCEDURE [Report].[SP_FAC_REPORTE_HOSPITALARIO_PENDIENTE_POR_RECONOCER]
AS
SELECT 'HEMOCOMPONENTES' 'TIPO', HOS.NUMINGRES as 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO]  ,HOS.ENTIDAD ,HOS.[GRUPO ATENCION]  ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA'
FROM REPORT.View_FAC_REPORTE_HEMOCOMPONENTES_POR_RECONOCER_HOS HOS
UNION ALL
SELECT 'IMAGENES' 'TIPO', HOS.NUMINGRES as 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA]  , YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA'
FROM REPORT.View_FAC_REPORTE_IMAGENES_POR_RECONOCER_HOS HOS
UNION ALL
SELECT 'LABORATORIOS' 'TIPO', HOS.NUMINGRES as 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA'
FROM REPORT.View_FAC_REPORTE_LABORATORIOS_POR_RECONOCER_HOS HOS
UNION ALL
SELECT 'PATOLOGIAS' 'TIPO', HOS.NUMINGRES as 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA'
FROM REPORT.View_FAC_REPORTE_PATOLOGIAS_POR_RECONOCER_HOS HOS
UNION ALL
SELECT 'TERAPIAS' 'TIPO', HOS.NUMINGRES as 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA'
FROM REPORT.View_FAC_REPORTE_TERAPIAS_POR_RECONOCER_HOS HOS
UNION ALL
SELECT 'INTERCONSULTAS' 'TIPO',HOS.NUMINGRES as 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA],YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA'
FROM REPORT.View_FAC_REPORTE_INTERCONSULTAS_POR_RECONOCER_HOS HOS
UNION ALL
SELECT 'PROCEDIMIENTOS_NO_QX' 'TIPO', HOS.NUMINGRES as 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA'
FROM REPORT.View_FAC_REPORTE_PROCEDIMIENTOS_NO_QX_POR_RECONOCER_HOS HOS
UNION ALL
SELECT 'GASES' 'TIPO', HOS.NUMINGRES as 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION]  ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA'
FROM REPORT.View_FAC_REPORTE_GASES_POR_RECONOCER_HOS HOS
UNION ALL
SELECT 'VALORACIONES' 'TIPO', HOS.NUMINGRES as 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA],HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA'
FROM REPORT.View_FAC_REPORTE_VALORACIONES_POR_RECONOCER_HOS HOS
UNION ALL
SELECT 'ESTANCIAS' 'TIPO',HOS.NUMINGRES as 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE',HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.CANSERIPS 'CANTIDAD ORDENADA' ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL' ,HOS.NUMCAMHOS 'CAMA',HOS.FECEGRESO 'FECHA EGRESO',   
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA] , YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA'
FROM REPORT.View_FAC_REPORTE_ESTANCIAS_POR_RECONOCER_HOS HOS

