-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: AtencionesConsultaExternaHsj
-- Extracted by Fabric SQL Extractor SPN v3.9.0











CREATE VIEW [Report].[AtencionesConsultaExternaHsj]
AS

WITH CTE_DX_SECUDANARIOS
AS
(
SELECT ROW_NUMBER () OVER (PARTITION BY IPCODPACI ORDER BY NUMINGRES) NUMERO ,CODDIAGNO,NUMEFOLIO, NUMINGRES,  IPCODPACI, CODDIAPRI
FROM INDIAGNOP 
WHERE CODDIAPRI=0

)


SELECT CAST(EX.IPFECHACO AS DATE) 'FECHA DE BUSQUEDA',CASE PAC.IPTIPODOC WHEN 1 THEN 'CC'  
					   WHEN 2 THEN 'CE' 
					   WHEN 3 THEN 'TI'   
					   WHEN 4 THEN 'RC'  
					   WHEN 5 THEN 'PA'  
					   WHEN 6 THEN 'AS'  
					   WHEN 7 THEN 'MS'  
					   WHEN 8 THEN 'NU'  
					   WHEN 9 THEN 'CN' 
					   WHEN 10 THEN 'CD' 
					   WHEN 11 THEN 'SC'
					   WHEN 12 THEN 'PE' 
					   WHEN 13 THEN 'PT' 
					   WHEN 14 THEN 'DE' ELSE 'NO REGISTRA'  END 'TIPO',EX.IPCODPACI 'DOC. PACIENTE', EX. IPNOMCOMP 'NOMBRE', EX.NUMINGRES '# INGRESO',
					   EX.CODESPECI 'COD. ESPECIALIDAD', ESP.DESESPECI 'NOMBRE ESPECIALIDAD', CASE CODTIPCON WHEN 1 THEN 'Primera vez' WHEN 2 THEN 'Control' WHEN 3 THEN  'Pos-operatorio' ELSE 'no aplica' END 'TIPO DE CITA',
					   CIT.CODSERIPS 'COD. CUPS', CUPS.DESSERIPS 'NOMBRE SERVICIO',
					   GRU.NAME 'GRUPO DE ATENCION', HA.NAME 'ENTIDAD', CASE WHEN HIS.ID IS NOT NULL THEN 'Atendido' ELSE 'No Atendido' END 'ESTADO ATENCION', ISNULL(CAST(FECHISPAC AS CHAR),'0') 'FECHA ATENCION',
					   PAC.IPTELEFON 'TEL FIJO',PAC.IPTELMOVI 'TEL. MOVIL', HIS.CODDIAGNO 'COD. DX PRINCIAL', DIA.NOMDIAGNO 'NOMBRE DX', DX1.CODDIAGNO 'COD. DX SEC 1', DIA2.NOMDIAGNO 'NOMBRE DX1',
					   DX2.CODDIAGNO 'COD. DX SEC 2', DIA3.NOMDIAGNO 'NOMBRE DX2', DX3.CODDIAGNO 'COD. DX SEC 3', DIA4.NOMDIAGNO 'NOMBRE D3'



FROM ADCONCOEX EX
INNER JOIN INPACIENT PAC ON PAC.IPCODPACI=EX.IPCODPACI
INNER JOIN INESPECIA ESP ON ESP.CODESPECI=EX.CODESPECI
INNER JOIN CONTRACT.CAREGROUP GRU ON GRU.CODE=EX.GENCAREGROUP
INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.CODE=EX.GENCONENTITY
INNER JOIN AGASICITA CIT ON CIT.NUMINGRES=EX.NUMINGRES AND CIT.CODAUTONU=NUMCONCIT
INNER JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS=CIT.CODSERIPS
LEFT JOIN HCHISPACA HIS ON HIS.NUMINGRES=EX.NUMINGRES
LEFT JOIN INDIAGNOS DIA ON DIA.CODDIAGNO=HIS.CODDIAGNO
LEFT JOIN CTE_DX_SECUDANARIOS DX1 ON DX1.NUMINGRES=HIS.NUMINGRES AND DX1.NUMERO=1
LEFT JOIN INDIAGNOS DIA2 ON DIA2.CODDIAGNO=DX1.CODDIAGNO
LEFT JOIN CTE_DX_SECUDANARIOS DX2 ON DX2.NUMINGRES=HIS.NUMINGRES AND DX2.NUMERO=2
LEFT JOIN INDIAGNOS DIA3 ON DIA3.CODDIAGNO=DX2.CODDIAGNO
LEFT JOIN CTE_DX_SECUDANARIOS DX3 ON DX3.NUMINGRES=HIS.NUMINGRES AND DX3.NUMERO=3
LEFT JOIN INDIAGNOS DIA4 ON DIA4.CODDIAGNO=DX3.CODDIAGNO

--WHERE MONTH(EX.IPFECHACO)=8 
