-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: DIM_Type_FuncionUnit
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[DIM_Type_FuncionUnit] AS

SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  1 ID_TUNID_FUN, 'Urgencias' NOMBRE, 'Urgencias' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL 
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  2 ID_TUNID_FUN, 'Hospitalizacion' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  3 ID_TUNID_FUN, 'Apoyo Dx' NOMBRE, 'Diagnostico y Terapeutico' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  4 ID_TUNID_FUN, 'Apoyo Terapeutico' NOMBRE, 'Diagnostico y Terapeutico' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  5 ID_TUNID_FUN, 'Unidades de Cuidado Intensivo Adulto' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  6 ID_TUNID_FUN, 'Unidades de Cuidado Intermedio Adulto' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  7 ID_TUNID_FUN, 'Unidades de Cuidado Intensivo Pediatrica' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  8 ID_TUNID_FUN, 'Unidades de Cuidado Intermedio Pediatrica' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  9 ID_TUNID_FUN, 'Unidades de Cuidado Intensivo Neonatal' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  10 ID_TUNID_FUN, 'Unidades de Cuidado Intermedio Neonatal' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  11 ID_TUNID_FUN, 'Unidades de Cuidado Basico Neonatal' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  12 ID_TUNID_FUN, 'Unidad Renal' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  13 ID_TUNID_FUN, 'Unidad Oncologica' NOMBRE, 'Diagnostico y Terapeutico' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  14 ID_TUNID_FUN, 'Unidad Medicina Nuclear' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  15 ID_TUNID_FUN, 'Consulta Externa' NOMBRE, 'Consulta Externa' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  16 ID_TUNID_FUN, 'Unidad Mental' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL 
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  17 ID_TUNID_FUN, 'Unidad de Quemados' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  18 ID_TUNID_FUN, 'Unidad de Cuidado Paliativo' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  19 ID_TUNID_FUN, 'Cirugia' NOMBRE, 'Cirugia' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL 
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  20 ID_TUNID_FUN, 'Laboratorio' NOMBRE, 'Diagnostico y Terapeutico' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  21 ID_TUNID_FUN, 'Cardiologia No Invasiva' NOMBRE, 'Diagnostico y Terapeutico' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  22 ID_TUNID_FUN, 'Cardiologia Invasiva' NOMBRE, 'Cirugia' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL 
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  23 ID_TUNID_FUN, 'Gineco-Obstetricia' NOMBRE, 'Hospitalizacion' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL 
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  24 ID_TUNID_FUN, 'Consulta Externa - Gineco-Obstetricia' NOMBRE, 'Consulta Externa' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL 
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  30 ID_TUNID_FUN, 'Otras' NOMBRE, 'Diagnostico y Terapeutico' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  31 ID_TUNID_FUN, 'Consulta Prioritaria' NOMBRE, 'Consulta Externa' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  32 ID_TUNID_FUN, 'Atención Domiciliaria' NOMBRE, 'Consulta Externa' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  33 ID_TUNID_FUN, 'Unidad Radioterapia' NOMBRE, 'Diagnostico y Terapeutico' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  34 ID_TUNID_FUN, 'Unidad Braquiterapia' NOMBRE, 'Diagnostico y Terapeutico' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
UNION ALL  
SELECT CAST(DB_NAME() AS VARCHAR(16)) AS ID_COMPANY,  35 ID_TUNID_FUN, 'Hemodinamia' NOMBRE,  'Diagnostico y Terapeutico' AMBITO, CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL 
