-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: DIM_BedUnit
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE view [Report].[DIM_BedUnit] as

SELECT 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 CONVERT(int, RTRIM(LTRIM(CAM.CODICAMAS))) CODICAMAS,
 CAM.DESCCAMAS,
 CASE CAM.CODCLACAM WHEN 1 THEN 'Urgencias' ELSE 'Hospitalizacion' END [CAMA_AMBITO],
 CONVERT(int,RTRIM(LTRIM(CAM.UFUCODIGO))) [ID_UFUN],
 ISNULL((YEAR(MIN (CTR.[FECHAINICIAL])) * 100) + MONTH(MIN(CTR.[FECHAINICIAL])),
        (YEAR(GETDATE()) * 100) + MONTH(GETDATE())) [ID_TIEMPO_INICIO],
  CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
 [dbo].[CHCAMASHO] CAM
 LEFT JOIN [dbo].[CHCAMATRAZA] CTR ON CTR.CODICAMAS=CAM.CODICAMAS
WHERE
 CAM.CAMVIRTUA = 'FALSE' AND
 CAM.ESTADCAMA <> 3 
GROUP BY
 CASE CAM.CODCLACAM WHEN 1 THEN 'Urgencias' ELSE 'Hospitalizacion' END, 
 CONVERT(int, RTRIM(LTRIM(CAM.CODICAMAS))),
 CAM.DESCCAMAS,
 CONVERT(int,RTRIM(LTRIM(CAM.UFUCODIGO)))

