-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: RecepcionReferencias.
-- Extracted by Fabric SQL Extractor SPN v3.9.1

CREATE VIEW Report.RecepcionReferencias
AS

WITH CTE_SEGUIMIENTOS
AS
(
SELECT ROW_NUMBER () OVER (PARTITION BY EVE.HCREFRECEPID ORDER BY EVE.FECREGIS) 'NUMERO', EVE.HCREFRECEPID,EVE.FECREGIS, EVE.OBSERVACION, EVE.HCMOTREFRECID, 
CASE EVE.ESTADO WHEN 1 THEN 'Aceptado' 
WHEN 2 THEN 'No Aceptado'
WHEN 3 THEN 'Sin Definir Conducta'
WHEN 4 THEN 'Cancelado' END 'ESTADO'

FROM HCREFRECDE EVE --WHERE EVE.HCREFRECEPID IN (4)
)


SELECT CAST(RC.FECREGIS AS DATE) 'FECHA DE BUSQUEDA',RC.ID,CEN.NOMCENATE 'CENTRO DE ATENCION',CAST(PAC.IPTIPODOC AS VARCHAR)+'-'+DOC.Nombre 'TIPO DOCUMENTO' , 
PAC.IPCODPACI 'IDENTIFICACION PACIENTE',CASE RC.CODTIPPAC WHEN 1 THEN 'Maternas'
WHEN 2 THEN 'Menor de 5 años'
WHEN 3 THEN 'Adulto mayor'
WHEN 4 THEN 'Población general' END 'TIPO DE POBLACION' ,
RC.FECREGIS 'FECHA REGISTRO SOLICITUD', RC.INUNIFUNCID 'COD. UF',FUN.UFUDESCRI 'UF DE DESTINO', MED.NOMBRE 'MEDIO DE SOLICITUD',SER.NOMBRE 'SERVICIO QUE REMITE',
MOT.NOMBRE 'MOTIVO DE SOLICITUD',RC.USERCREA 'COD. USUARIO REGISTRA',US.NOMUSUARI 'USUARIO REGISTRA SOLICITUD', ESP1.DESESPECI 'ESPECIALIDAD REMITE', RC.OBSERVACION,
CASE RC.CODCOMPLEJ WHEN 1 THEN 'BAJA' 
WHEN 2 THEN 'MEDIA' 
WHEN 3 THEN 'ALTA' END 'NIVEL DE COMPLEJIDAD SOLICITADO', 
ESP2.DESESPECI 'ESPECIALIDAD SOLICITADA', RC.NUMINGRES '# INGRESO', 
CASE RC.ESTADO WHEN 1 THEN 'Registrado (Solicitado)'
WHEN 2 THEN 'Aceptado Sin Ingreso'
WHEN 3 THEN 'Aceptado Con Ingreso'
WHEN 4 THEN 'Rechazado'
WHEN 5 THEN 'Cancelado'
WHEN 6 THEN 'Egresado' END 'ESTADO',
RC.INENTADMID 'COD. EAPB',ENT.NOMENTIDA 'ENTIDAD DEL PACIENTE',CASE RC.CODURGVITAL WHEN 0 THEN 'NO' ELSE 'SI' END 'URGENCIA VITAL',
CASE RC.CODTIPOENTSOLI WHEN 1 THEN 'IPS'
WHEN 2 THEN 'EAPB'
WHEN 3 THEN 'CRUE'
WHEN 4 THEN 'OTRA' END 'TIPO ENTIDAD SOLICITA', EVE1.FECREGIS 'FECHA SEGUIMIENTO 1', EVE1.OBSERVACION 'OBS. SEGUIMIENTO 1',
EVE2.FECREGIS 'FECHA SEGUIMIENTO 2', EVE2.OBSERVACION 'OBS. SEGUIMIENTO 2',
EVE3.FECREGIS 'FECHA SEGUIMIENTO 3', EVE3.OBSERVACION 'OBS. SEGUIMIENTO 3',
EVE4.FECREGIS 'FECHA SEGUIMIENTO 4', EVE4.OBSERVACION 'OBS. SEGUIMIENTO 4'


FROM HCREFRECEP RC
INNER JOIN ADCENATEN CEN ON CEN.CODCENATE=ADCENATENID
INNER JOIN INPACIENT PAC ON PAC.IPCODPACI=RC.IPCODPACI
INNER JOIN dbo.ADTIPOIDENTIFICA DOC ON PAC.IPTIPODOC=DOC.CODIGO
INNER JOIN INUNIFUNC FUN ON FUN.UFUCODIGO=RC.INUNIFUNCID
INNER JOIN Segusuaru US ON US.CODUSUARI=RC.USERCREA
LEFT JOIN CTE_SEGUIMIENTOS EVE1 ON EVE1.HCREFRECEPID=RC.ID AND EVE1.NUMERO=2
LEFT JOIN CTE_SEGUIMIENTOS EVE2 ON EVE2.HCREFRECEPID=RC.ID AND EVE2.NUMERO=3
LEFT JOIN CTE_SEGUIMIENTOS EVE3 ON EVE3.HCREFRECEPID=RC.ID AND EVE3.NUMERO=3
LEFT JOIN CTE_SEGUIMIENTOS EVE4 ON EVE4.HCREFRECEPID=RC.ID AND EVE4.NUMERO=4
LEFT JOIN RCMODSOLIC MED ON MED.ID=RC.RCMODSOLICID
LEFT JOIN RCMOTREF MOT ON MOT.ID=RC.RCMOTREFID
LEFT JOIN INESPECIA ESP1 ON ESP1.CODESPECI=RC.INESPECIAIDREMITE
LEFT JOIN INESPECIA ESP2 ON ESP2.CODESPECI=RC.INESPECIAIDAREMITIR
LEFT JOIN RCSERVICIOS SER ON SER.ID=RC.RCSERVICIOSID
LEFT JOIN INENTIDAD ENT ON ENT.CODENTIDA=RC.INENTADMID

