-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ReporteCitas
-- Extracted by Fabric SQL Extractor SPN v3.9.0








CREATE VIEW [Report].[ReporteCitas]
AS

SELECT   DISTINCT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
CEN.NOMCENATE 'CENTRO DE ATENCION',
CASE WHEN ING.UFUCODIGO IS NOT NULL THEN FUN.UFUDESCRI ELSE 'SIN ADMISION' END 'UNIDAD FUNCIONAL', 
CIT.IPCODPACI 'ID PACIENTE', 
PAC.IPNOMCOMP 'NOMBRE PACIENTE',
CAST(PAC.IPFECNACI AS DATE) 'FECHA DE NACIMIENTO',
DATEDIFF(YEAR,IPFECNACI,GETDATE()) EDAD,
PAC.IPTELEFON 'TEL FIJO',
PAC.IPTELMOVI 'TEL CELULAR', 
CG.Name 'CONTRATO', 
HA.Name 'EAPB',
ISNULL(CIT.CODPROSAL,'') 'ID PROFESIONAL', ISNULL(PROF.NOMMEDICO,'') 'NOMBRE PROFESIONAL',
ISNULL(ESP.DESESPECI,'') 'ESPECIALIDAD',
CASE WHEN CAST(FECHORAIN AS TIME)  BETWEEN '00:00:00.0000000' AND '12:59:59.0000000' THEN 'Mañana' ELSE 'Tarde' END 'JORNADA',
ISNULL(CIT.NUMINGRES,'')'INGRESO',
ACT.DESACTMED 'ACTIVIDAD',

CUPS.DESSERIPS 'SERVICIO CUPS',
CD.NAME 'DESCRIPCION RELACIONADA',

CASE CIT.TIPSOLICITU WHEN 1 THEN 'Cita médica' 
					 WHEN 2 THEN 'Cita apoyo dx' 
					 WHEN 3 THEN 'Cita tratamientos especiales' END 'TIPO CITA', 
CASE CIT.CODTIPCIT WHEN 0 THEN 'Primera Vez' 
                   WHEN 1 THEN 'Control' 
                   WHEN 2 THEN 'Pos Operatorio' 
                   WHEN 3 THEN 'Cita Web' END  'CLASE CITA' ,

CIT.FECITADES 'FECHA DESEADA',
CIT.FECHORAIN 'FECHA INICIAL', 
FECHORAFI 'FECHA FINAL',
CASE CIT.CITAEXTRA WHEN 0 THEN 'No' ELSE 'Si' END 'CITA EXTRA' , 
CASE CIT.CODESTCIT WHEN 0 THEN 'Asignada'
				   WHEN 1 THEN 'Cumplida'
				   WHEN 2 THEN 'Incumplida'
				   WHEN 3 THEN 'PreAsignada'
				   WHEN 4 THEN 'Cita Cancelada'
				   WHEN 5 THEN 'Inatencion' END 'ESTADO',
ISNULL(CIT.OBSERVACI,'') 'OBSERVACION DE LA CITA',
US1.NOMUSUARI 'USUARIO ASIGNA',
CIT.FECREGSIS 'FECHA ASIGNACION',
ISNULL(US2.NOMUSUARI,'') 'USUARIO REPROGRAMA',
ISNULL(CIT.FECHAREPRO,'') 'FECHA REPROGRAMACION', 
ISNULL(US3.NOMUSUARI,'') 'USUARIO CANCELA',
ISNULL(CIT.FECHCANCELA,'') 'FECHA CANCELACION', 
ISNULL(CAN.DESCAUCAN,'') 'MOTIVO DE CANCELACION', ISNULL(CIT.OBSCAUCAN,'') 'OBS. CANCELACION', 
ISNULL(US5.NOMUSUARI,'') 'USUARIO CONFIRMA',
ISNULL(CONF.FECHACREACION,'') 'FECHA CONFIRMACION', 
ISNULL(US6.NOMUSUARI,'') 'USUARIO EDITA',
CASE CONF.CONTACTOPACIENTE WHEN 1 THEN 'Contacto con paciente' WHEN 0 THEN 'Contacto familiar' ELSE '' END 'CONTACTO PACIENTE',
CASE CONF.ESTADOCONFIRMAR WHEN 1 THEN 'Confirma asistencia' 
						  WHEN 2 THEN 'Cancela asistencia'
						  WHEN 3 THEN 'Sin definir' ELSE '' END 'ESTADO CONFIRMACION',ISNULL(CONF.OBSERVACION,'') 'OBSERVACION' ,

CAST(FECHORAIN AS DATE) 'FECHA DE BUSQUEDA',
YEAR(FECHORAIN  ) AS 'AÑO BUSQUEDA',
MONTH(FECHORAIN  ) AS 'MES BUSQUEDA',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL

FROM AGASICITA CIT
INNER JOIN ADCENATEN CEN ON CEN.CODCENATE=CIT.CODCENATE
INNER JOIN INPACIENT PAC ON PAC.IPCODPACI=CIT.IPCODPACI
INNER JOIN CONTRACT.CareGroup CG ON CG.Id=CIT.GENCAREGROUP
INNER JOIN CONTRACT.HealthAdministrator HA ON HA.Id=CIT.GENCONENTITY
INNER JOIN AGACTIMED ACT ON ACT.CODACTMED=CIT.CODACTMED
INNER JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS=CIT.CODSERIPS
LEFT JOIN INPROFSAL PROF ON PROF.CODPROSAL=CIT.CODPROSAL
LEFT JOIN INESPECIA ESP ON ESP.CODESPECI=CIT.CODESPECI
LEFT JOIN ADCONCOEX ING ON ING.NUMCONCIT=CIT.CODAUTONU
LEFT JOIN INUNIFUNC FUN ON FUN.UFUCODIGO=ING.UFUCODIGO
LEFT JOIN INCUPSIPS CUPS1 ON CUPS1.CODSERIPS=ACT.CODSERIPS
LEFT JOIN SEGusuaru US1 ON US1.CODUSUARI=CIT.CODUSUASI
LEFT JOIN SEGusuaru US2 ON US2.CODUSUARI=CIT.CODUSUARIOREPRO
LEFT JOIN SEGusuaru US3 ON US2.CODUSUARI=CIT.CANCELUSU
LEFT JOIN SEGusuaru US4 ON US4.CODUSUARI=CIT.USUCONFIRM
LEFT JOIN AGCAUCANC CAN ON CAN.CODCAUCAN=CIT.CODCAUCAN
LEFT JOIN AGASICITACONFIR CONF ON CONF.IDAGASICITA=CIT.CODAUTONU
LEFT JOIN SEGusuaru US5 ON US5.CODUSUARI=CONF.USUARIOCREACION
LEFT JOIN SEGusuaru US6 ON US6.CODUSUARI=CONF.USUARIOMODIFICACION
LEFT JOIN contract.CUPSEntityContractDescriptions CDD WITH (NOLOCK) ON CDD.Id = CIT.IDDESCRIPCIONRELACIONADA
LEFT JOIN contract.ContractDescriptions CD WITH (NOLOCK) ON CD.Id = CDD.ContractDescriptionId
