-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: TablaAntecedentes
-- Extracted by Fabric SQL Extractor SPN v3.9.0


/*******************************************************************************************************************
Nombre: [Report].[TablaAntecedentes]
Tipo:Vista
Observacion:vista, que cumple la función de unir tablas de antecedentes por mes y año 
Profesional: Nilsson Miguel Galindo Lopez
Fecha:28-02-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico:
Fecha:
Ovservaciones:
--------------------------------------
Version 2
Persona que modifico:
Fecha:
***********************************************************************************************************************************/
CREATE VIEW [Report].[TablaAntecedentes] AS

WITH CTE_ANTECEDENTES AS 
 (
	SELECT * FROM ANTVALORES202104
	UNION ALL
	SELECT * FROM ANTVALORES202105
	UNION ALL
	SELECT * FROM ANTVALORES202106
	UNION ALL
	SELECT * FROM ANTVALORES202107
	UNION ALL
	SELECT * FROM ANTVALORES202108
	UNION ALL
	SELECT * FROM ANTVALORES202109
	UNION ALL
	SELECT * FROM ANTVALORES202110
	UNION ALL
	SELECT * FROM ANTVALORES202111
	UNION ALL
	SELECT * FROM ANTVALORES202112
	UNION ALL
	SELECT * FROM ANTVALORES202201
	UNION ALL
	SELECT * FROM ANTVALORES202202
	UNION ALL
	SELECT * FROM ANTVALORES202203
	UNION ALL
	SELECT * FROM ANTVALORES202204
	UNION ALL
	SELECT * FROM ANTVALORES202205
	UNION ALL
	SELECT * FROM ANTVALORES202206
	UNION ALL
	SELECT * FROM ANTVALORES202207
	UNION ALL
	SELECT * FROM ANTVALORES202208
	UNION ALL
	SELECT * FROM ANTVALORES202209
	UNION ALL
	SELECT * FROM ANTVALORES202210
	UNION ALL
	SELECT * FROM ANTVALORES202211
	UNION ALL
	SELECT * FROM ANTVALORES202212
	UNION ALL
	SELECT * FROM ANTVALORES202301
	UNION ALL
	SELECT * FROM ANTVALORES202302
	UNION ALL
	SELECT * FROM ANTVALORES202303
	UNION ALL
	SELECT * FROM ANTVALORES202304
	UNION ALL
	SELECT * FROM ANTVALORES202305
	UNION ALL
	SELECT * FROM ANTVALORES202306
	UNION ALL
	SELECT * FROM ANTVALORES202307
	UNION ALL
	SELECT * FROM ANTVALORES202308
	UNION ALL
	SELECT * FROM ANTVALORES202309
	UNION ALL
	SELECT * FROM ANTVALORES202310
	UNION ALL
	SELECT * FROM ANTVALORES202311
	UNION ALL
	SELECT * FROM ANTVALORES202312
	UNION ALL
	SELECT * FROM ANTVALORES202401
 )

SELECT 
 ANT.*, VAL.VARIABLE,HIS.FECHISPAC,HIS.IPCODPACI
FROM 
 CTE_ANTECEDENTES ANT 
 INNER JOIN dbo.ANTVARIABLES VAL ON ANT.IDANTVARIABLE=VAL.ID 
 INNER JOIN dbo.HCHISPACA HIS ON ANT.IDHCHISPACA=HIS.ID
--GO