-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: TablaExamenFisico
-- Extracted by Fabric SQL Extractor SPN v3.9.0



create VIEW [Report].[TablaExamenFisico] WITH SCHEMABINDING AS

WITH CTE_EXAVALORES AS (
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202104
  UNION ALL	
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202105
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202106
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202107
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202108
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202109
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202110
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202111
  UNION ALL										
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202112
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202201
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202202
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202203
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202204
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202205
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202206
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202207
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202208
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202209
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202210
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202211
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202212
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202301
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202302
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202303
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202304
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202305
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202306
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202307
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202308
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202309
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202310
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202311
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202312
  UNION ALL											
  select [ID], [IDHCHISPACA], [IDEXAGRUPO], [IDEXAVARIABLE], [VALOR], [IDITEMLISTA], [VALOROPCION]
  FROM dbo.EXAVALORES202401
 ) 

 SELECT
 VAL.IDHCHISPACA, 
 HIS.IPCODPACI, 
 HIS.NUMINGRES, 
 HIS.NUMEFOLIO, 
 VAL.IDEXAVARIABLE AS ID_VARIABLE,
 GRU.NOMBRE AS NOMBRE_GRUPO, 
 GRUVAL.VALOROPCION AS VALOR_GRUPO, 
 EXA.VARIABLE AS NOMBRE_VARIABLE, 
 VAL.VALOROPCION AS OPCION, 
 VAL.VALOR AS VALOR , LIS.NOMBRE, 
 HIS.FECHISPAC AS FECHA, 
 EXA.IDEXAGRUPO AS IDEXAGRUPO
FROM
 CTE_EXAVALORES as VAL
 INNER JOIN dbo.HCHISPACA AS HIS ON VAL.IDHCHISPACA = HIS.ID
 INNER JOIN dbo.EXAVARIABLES AS EXA ON VAL.IDEXAVARIABLE = EXA.ID
 INNER JOIN dbo.EXAGRUPO AS GRU ON GRU.ID = EXA.IDEXAGRUPO
 INNER JOIN dbo.EXAVALORESGRUPOS AS GRUVAL ON GRUVAL.IDEXAGRUPO = GRU.ID AND GRUVAL.IDHCHISPACA = VAL.IDHCHISPACA
 LEFT JOIN dbo.EXAVARIABLESL AS LIS ON VAL.IDITEMLISTA = LIS.ID	
