-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: TrazabilidadHemocomponentes
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE VIEW [Report].[TrazabilidadHemocomponentes]

as

WITH CTE_FECHAS_SOL
AS
(
SELECT DISTINCT BOL.HCORHEMCOID, BOL.COMSAMID,COM.DESCOMSAM, BOL.ESTADO, BOL.TIPOSOLICI, BOL.FECSOLRES, BOL.FECSOLTRA

FROM HCORHEMBOL BOL 
INNER JOIN HCORHEMCO ORD ON ORD.ID=BOL.HCORHEMCOID
INNER JOIN HCCOMSAN COM ON COM.ID=BOL.COMSAMID

)

SELECT DISTINCT CAST(OH.FECORDMED AS DATE) 'FECHA DE BUSQUEDA',CEN.NOMCENATE 'CENTRO DE ATENCION',
CASE PAC.IPTIPODOC 	WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI' WHEN '4' THEN 'RC'	WHEN '5' THEN 'PA'	WHEN '6' THEN 'AS'
WHEN '7' THEN 'MS'	WHEN '8' THEN 'NU'	WHEN '9' THEN 'CN'	WHEN '10' THEN 'CD'	WHEN '11' THEN 'SC' WHEN '12' THEN 'PE' 
ELSE 'N/A'END 'TIPO DOCUMENTO', OH.IPCODPACI 'IDENTIFICACION',RTRIM(PAC.IPPRINOMB) 'PRIMER NOMBRE', 
 RTRIM(PAC.IPSEGNOMB) 'SEGUNDO NOMBRE', 
 RTRIM(PAC.IPPRIAPEL) 'PRIMER APELLIDO', 
 RTRIM(PAC.IPSEGAPEL) 'SEGUNDO APELLIDO', 
 RTRIM(PAC.IPNOMCOMP) 'NOMBRE COMPLETO PACIENTE', 
 PAC.IPFECNACI 'FECHA NACIMIENTO', 
 FLOOR((CAST(CONVERT(VARCHAR(8), OH.FECORDMED, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS 'EDAD',
 CASE WHEN PAC.IPSEXOPAC = '1' THEN 'M' ELSE 'F' END 'GENERO' ,  OH.NUMEFOLIO 'FOLIO ORDEN', OH.NUMINGRES '# INGRESO', OH.FECORDMED 'FECHA ORDEN',COM.DESCOMSAM 'COMPONENTE SANGUINEO',
 HEM.NUMBOLSA 'NUMERO DE BOLSA', HEM.SELLOCALIDAD 'SELLO DE CALIDAD',
 CASE WHEN OH.idAGASICITA IS NOT NULL THEN 'Ambulatorio' ELSE 'Hospitalario' END 'ORIGEN SOLICITUD', 
 CASE OH.PRIOTRAN WHEN 1 THEN 'Emergencia (hasta 15 min)'
WHEN 2 THEN  'Urgencia (hasta 1 hora)'
WHEN 3 THEN  'Urgencia Diferida (hasta 3 horas)'
WHEN 4 THEN  'Normal (hasta 24 horas)' END 'PRIORIDAD',
CASE OH.RESERCIR WHEN 1 THEN 'Si' ELSE 'No' END 'RESERVA PARA CX',ISNULL(OH.OBSERVACI,'') 'OBSERVACION ORDEN', 
 CASE HEM.ESTADO WHEN 1 THEN 'Solicitud Reserva'
WHEN 2 THEN 'Solicitud de Transfusión'
WHEN 3 THEN 'Reserva sin Solicitud de Transfusión'
WHEN 4 THEN 'Reserva con Solicitud de Transfusión'
WHEN 5 THEN 'Liberado'
WHEN 6 THEN 'Entregado'
WHEN 7 THEN 'Aplicado'
WHEN 8 THEN 'No Aplicado'
WHEN 9 THEN 'Anulado'
WHEN 10 THEN 'Descartado por salida de paciente'
WHEN 11 THEN 'Extramural' END 'ESTADO' ,FUN1.UFUDESCRI 'UF SOLICITA TRANSFUSION',FUN2.UFUDESCRI 'UF SOLICITA RESERVA',FUN3.UFUDESCRI 'UF DESTINO COMPONENTE',FUN4.UFUDESCRI 'UF APLICA TRANSFUSION',
HEM.USURECBOLSA 'COD.USUARIO RECIBE COMPONENTE',PROF1.NOMMEDICO 'USUARIO RECIBE',HEM.ENFRECHAZ 'COD. USUARIO RECHAZA COMPONENTE',PROF2.NOMMEDICO 'USUARIO RECHAZA',
CASE HEM.REGENF WHEN 1 THEN 'Si' ELSE 'No' END 'REGISTRO TRANSFUSION ENFERMERIA' ,HEM.FECAPLICENF 'FECHA TRANSFUSION' ,HEM.FECHINITRA 'INICIO TRANSFUSION',HEM.FECHFINTRA 'FIN TRANSFUSION',HEM.COMPLICACIONES 'COMPLICACIONES',
HEM.ENFAPLICA 'COD. USUARIO APLICA',PROF3.NOMMEDICO 'USUARIO APLICA',HEM.NUMFOLTRANS 'FOLIO REGISTRO TRANSFUSION', CASE HEM.REGMED WHEN 1 THEN 'Si' ELSE 'No' END 'REGISTRO TRANSFUSION MEDICO', HEM.FECAPLICMED 'FECHA REGISTRO MEDICO',
CASE WHEN SOL.FECSOLRES IS NOT NULL THEN CAST(SOL.FECSOLRES AS TIME) ELSE CAST(SOL.FECSOLTRA AS TIME) END 'HORA SOLICITUD' ,CAST(OH.FECORDMED AS TIME) 'HORA RECEPCION SOLICITUD', CAST(HEM.FECENTREGA AS TIME) 'HORA ENTREGA',
CAST(HEM.FECHINITRA AS TIME) 'HORA INICIO TRANSFUSION', CAST(HEM.FECHFINTRA AS TIME) 'HORA FIN TRANSFUSION', CAST(CONVERT(NUMERIC,DATEDIFF(MINUTE,HEM.FECHINITRA,HEM.FECHFINTRA))/60 AS DECIMAL (10,2)) 'DURACION TRANSFUSION'

FROM DBO.HCORHEMCO OH                                                                  
INNER JOIN DBO.ADCENATEN CEN ON CEN.CODCENATE=OH.CODCENATE
INNER JOIN DBO.INPACIENT PAC ON PAC.IPCODPACI=OH.IPCODPACI
INNER JOIN DBO.HCORHEMBOL HEM ON HEM.HCORHEMCOID=OH.ID
INNER JOIN DBO.HCCOMSAN COM ON COM.ID=HEM.COMSAMID 
INNER JOIN CTE_FECHAS_SOL SOL ON SOL.HCORHEMCOID=OH.ID
LEFT JOIN DBO.INUNIFUNC FUN1 ON FUN1.UFUCODIGO=HEM.UFUSOLTRA
LEFT JOIN DBO.INUNIFUNC FUN2 ON FUN2.UFUCODIGO=HEM.UFUSOLRES
LEFT JOIN DBO.INUNIFUNC FUN3 ON FUN3.UFUCODIGO=HEM.UFUENTREGA
LEFT JOIN DBO.INUNIFUNC FUN4 ON FUN4.UFUCODIGO=HEM.UFUAPLICA
LEFT JOIN DBO.INPROFSAL PROF1 ON PROF1.CODPROSAL=HEM.USURECBOLSA
LEFT JOIN DBO.INPROFSAL PROF2 ON PROF2.CODPROSAL=HEM.ENFRECHAZ
LEFT JOIN DBO.INPROFSAL PROF3 ON PROF3.CODPROSAL=HEM.ENFAPLICA


