-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: UploadVieClinicalDailyCensus
-- Extracted by Fabric SQL Extractor SPN v3.9.0





/*******************************************************************************************************************
Nombre: [Report].[UploadVieClinicalDailyCensus]
Tipo:Procedimiento Vista
Observacion:Informe del censo diario que funciona en producción.
Profesional: Andres Cabrera
Fecha:
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha:23-01-2025
Ovservaciones: Se altera la vista original para mejorar el permormance y se crea el tipo de unidad segun las necesidades del cliente.
-----------------------------------------------------------------------------------------------------------------------------------------
Version 2
Persona que modifico:
Fecha: 
Observacion:
***********************************************************************************************************************************/

CREATE VIEW [Report].[UploadVieClinicalDailyCensus] AS

----******************************************************* CENSO DIARIO - INDICADOR DE PORCENTAJE OCUPACIONAL *******************************************************-----

-----***** TABLAS QUE INTERVIENEN EN LA CONSULTA ******----

--  dbo.CHCAMASHO: TABLA DONDE SE ALMACENA LAS CAMAS CREADAS EN EL SISTEMA
--  dbo.ADCENATEN: TABLA DONDE SE ALMACENA LOS CENTROS DE ATENCION DE LA INSTITUCION
--  dbo.INUNIFUNC: TABLA DONDE SE ALMACENA LAS UNIDADES FUNCIONALES CREADAS DE LOS CENTROS DE ATENCION Y DONDE SE ASIGNAN CAMAS
--  dbo.CHREGESTA: TABLA DONDE SE ALMACENA LA TRAZABILIDAD DE LAS ESTANCIAS DE LOS PACIENTES
--  dbo.INPACIENT: TABLA DONDE SE ALMACENA LA INFORMACION DE LOS PACIENTES
--  dbo.ADINGRESO: TABLA DONDE SE ALMACENA LOS INGRESOS O ADMISIONES QUE TIENE LOS PACIENTES
--  Contract.HealthAdministrator: TABLA DONDE SE ALMACENA LAS ENTIDADES ADMINISTRADORAS A LS QUE PERTENEE LOS PACIENTES
--  Common.ThirdParty: TABLA DONDE SE ALMACENA LOS TERCEROS A NIVEL FINANCIERO SE GUARDAN (PACIENTES, PROVEEDORES, CLIENTES, EMPLEADOS)
--  dbo.HCREGEGRE: TABLA DONDE SE ALMACENA LOS EGRESOS DE LOS PACIENTES QUE TIENEN CRITERIO DE SALIDA POR PARTE DE LOS MEDICOS
--  dbo.HCHISPACA: TABLA DONDE SE ALMACENA LOS FOLIO DE LAS HISTORIAS CLINICAS CON CADA VALARACION SE CREA EL REGISTRO

----******************************************************************************************************************************************************************-----


----****************************************************************** CTE CAMAS *************************************************************************************-----

/* CTE QUE CONSULTA LAS CAMAS CREADAS EN EL SISTEMA INDEPENDIENTE DE SU ESTADO, EL OBJETIVO MOSTRAR TODAS LAS CAMAS CREADAS EN EL SISTEMA */
WITH CTE_CAMAS
AS
(
  SELECT 
  YEAR(COMMON.GETDATE()) 'AÑO',
  MONTH(COMMON.GETDATE()) 'MES',
  DAY(COMMON.GETDATE()) 'DIA',
  CEN.NOMCENATE 'CENTRO DE ATENCION',
  CASE UFUTIPUNI WHEN 1 THEN 'Urgencias' 
				 WHEN 2 THEN 'Hospitalización' 
				 WHEN 3 THEN 'Apoyo Dx' 
				 WHEN 4 THEN 'Apoyo Terapeutico'
				 WHEN 5 THEN 'Unidades de Cuidado Intensivo Adulto' 
				 WHEN 6 THEN 'Unidades de Cuidado Intermedio Adulto' 
				 WHEN 7 THEN 'Unidades de Cuidado Intensivo Pediatrica' 
				 WHEN 8 THEN 'Unidades de Cuidado Intermedio Pediatrica'
				 WHEN 9 THEN 'Unidades de Cuidado Intensivo Neonatal' 
				 WHEN 10 THEN 'Unidades de Cuidado Intermedio Neonatal'
				 WHEN 11 THEN 'Unidades de Cuidado Basico Neonatal' 
				 WHEN 12 THEN 'Unidad Renal'
				 WHEN 13 THEN 'Unidad Oncologica' 
				 WHEN 14 THEN 'Unidad Medicina Nuclear'
				 WHEN 15 THEN 'Consulta Externa'
				 WHEN 16 THEN 'Unidad Mental' 
				 WHEN 17 THEN 'Unidad de Quemados' 
				 WHEN 18 THEN 'Unidad de Cuidado Paliativo'
				 WHEN 19 THEN 'Cirugia' 
				 WHEN 20 THEN 'Laboratorio' 
				 WHEN 21 THEN 'Cardiologia No Invasiva' 
				 WHEN 22 THEN 'Cardiologia Invasiva' 
				 WHEN 23 THEN 'Gineco-Obstetricia'
				 WHEN 24 THEN 'Consulta Externa - Gineco-Obstetricia' 
				 WHEN 30 THEN 'Otras'
				 WHEN 31 THEN 'Consulta Prioritaria'
				 WHEN 32 THEN 'Atención domiciliaria' 
				 WHEN 33 THEN 'Unidad Radioterapia' 
				 WHEN 34 THEN 'Unidad Braquiterapia' 
				 WHEN 35 THEN 'Hemodinamia' END AS [TIPO UNIDAD],
 -- IIF(FUN.UFUDESCRI='PABELLON URGENCIAS ADULTOS',FUN.UFUDESCRI,(REPLACE(REPLACE(FUN.UFUDESCRI,'PABELLON ',''),'HOSPITALIZACION',''))) AS 'UNIDAD FUNCIONAL',
 CH.[AREA] [UNIDAD FUNCIONAL],
 CH.[UNIDAD AGRUPADOR] AS [TIPO UNIDAD SAN JOSE],
  A.CODICAMAS 'ID CAMA',
  A.NUMCAMHOS 'CODIGO CAMA',
  A.DESCCAMAS 'DESCRIPCION CAMA',
  CASE CODCLACAM WHEN 1 THEN 'Observacion Urgencias' 
				 WHEN 2 THEN 'Recuperacion Post-Quirurgico' 
				 WHEN 3 THEN 'Hospitalaria' 
				 WHEN 4 THEN 'Cuna de Observación' END 'TIPO CAMA',
  CASE CODCLAHAB WHEN 1 THEN 'Sala de Observacion' 
				 WHEN 2 THEN 'Sala de Procedimientos' 
				 WHEN 3 THEN 'Sala de Recuperación' 
				 WHEN 4 then 'Habitacion 1 Cama' 
				 WHEN 5 THEN 'Habitacion 2 Camas'
				 WHEN 6 THEN 'Habitacion 3 Camas' 
				 WHEN 7 THEN 'Habitacion 4 Camas' 
				 WHEN 8 THEN 'Suite' 
				 WHEN 9 THEN 'Habitacion Especial' 
				 WHEN 10 THEN 'UCI' 
				 WHEN 11 THEN 'Otro' ELSE 'Otro' END 'TIPO HABITACION',
  CASE CAMVIRTUA WHEN 0 THEN 'NO' 
				 WHEN 1 THEN 'SI' END 'VIRTUAL', 
  CASE A.ESTADCAMA WHEN 1 THEN 'Libre' 
				   WHEN 2 THEN 'Asignada' 
				   WHEN 3 THEN 'Inactiva'
				   WHEN 4 THEN  G.BLOQUEO--'En Mantenimiento' 
				   WHEN 5 THEN 'En Aislamiento' 
				   WHEN 6 THEN 'Reservada sin Confirmar' 
				   WHEN 7 THEN 'Reservada Confirmada' END 'ESTADO CAMA',
  FUN.UFUCODIGO,CH.[MOSTRAR]
  FROM dbo.CHCAMASHO A
  INNER JOIN DBO.ADCENATEN CEN ON CEN.CODCENATE =A.CODCENATE
  INNER JOIN DBO.INUNIFUNC FUN ON A.UFUCODIGO =FUN.UFUCODIGO 
  INNER JOIN Report.CAMASHABILITADAS CH ON CH.CODICAMAS=A.CODICAMAS
  LEFT JOIN
  (
   SELECT TRA.CODICAMAS,TRA.CODCENATE,TRA.UFUCODIGO,BLO.FECINIBLO,TIP.DESTIPBLO,UPPER(LEFT(TIP.DESTIPBLO, 1)) + LOWER(SUBSTRING(TIP.DESTIPBLO, 2, LEN(TIP.DESTIPBLO))) BLOQUEO
    FROM DBO.CHCAMATRAZA TRA
    INNER JOIN
    (
      SELECT MAX(T.ID) ID,T.CODICAMAS,T.CODCENATE ,T.UFUCODIGO  FROM DBO.CHCAMATRAZA T
      WHERE T.ESTADOCAMA =4 AND T.FECHAFINAL IS NULL
      GROUP BY T.CODICAMAS,T.CODCENATE ,T.UFUCODIGO
    ) AS G ON G.ID = TRA.ID 
   INNER JOIN dbo.CHREGEBLO  AS BLO ON TRA.IDCHREGEBLO =BLO.ID 
   INNER JOIN dbo.CHTIPBLOQ AS TIP ON BLO.CODTIPBLO =TIP.CODTIPBLO 
  ) AS G ON G.CODICAMAS =A.CODICAMAS AND G.CODCENATE =A.CODCENATE AND G.UFUCODIGO =A.UFUCODIGO 
),

CTE_CENSO_DIARIO
AS
(
 SELECT YEAR(COMMON.GETDATE()) 'AÑO',MONTH(COMMON.GETDATE()) 'MES',DAY(COMMON.GETDATE()) 'DIA',
 A.CODICAMAS AS 'ID CAMA',
 B.NUMCAMHOS 'CODIGO CAMA', 
 RTRIM(B.DESCCAMAS) AS 'DESCRIPCION CAMA',
 A.NUMINGRES AS 'INGRESO',
 CAST(A.FECINIEST AS DATE) [FECHA INICIAL UNIDAD],
 COALESCE (NULLIF (A.IPCODPACI, ''), '') AS 'IDENTIFICACION PACIENTE',
 RTRIM(C.IPNOMCOMP) AS 'NOMBRE PACIENTE',
 CASE C.IPSEXOPAC WHEN 1 THEN 'Masculino' ELSE 'Femenino' END AS GENERO,
 TP.Nit 'NIT',
 RTRIM(ISNULL(HABI.ShortName,HA.Name)) AS 'NOMBRE ENTIDAD',
 CASE HA.EntityType WHEN 1 THEN 'CONTRIBUTIVO' 
					WHEN 2 THEN 'SUBSIDIADO' 
					WHEN 3 THEN 'VINCULADO' 
					WHEN 4 THEN 'VINCULADO'
					WHEN 5 THEN 'ARL' 
					WHEN 6 THEN 'PREPAGADA' 
					WHEN 7 THEN 'IPS PRIVADA' 
					WHEN 8 THEN 'IPS PUBLICA' 
					WHEN 9 THEN 'REGIMEN ESPECIAL' 
					WHEN 10 THEN 'ACCIDENTE DE TRANSITO'
					WHEN 11 THEN 'FOSYGA' 
					WHEN 12 THEN 'OTROS' 
					WHEN 13 THEN 'ASEGURADORAS'
					WHEN 99 THEN 'PARTICULARES' END AS REGIMEN,
 RTRIM(F.DESTIPEST) 'TIPO ESTANCIA',DATEDIFF(YEAR, C.IPFECNACI, Common.GETDATE()) as 'EDAD','OCUPADA' 'ESTADO CENSO',
 CASE WHEN X.INDICAPAC = '22' THEN '2 - Pre-alta hospitalaria' 
	  WHEN I.NUMINGRES IS NULL THEN '1 - Pacientes en la unidad' ELSE '3 - Pacientes con salida' END AS 'DESTINO',
 RTRIM(Q.CODDIAGNO) + ' - ' + RTRIM(Q.NOMDIAGNO) AS [DIAGNOSTICO PRINCIPAL],
 CAST(C.IPFECNACI AS DATE) AS 'FECHA NACIMIENTO'
 FROM  CHREGESTA A WITH(NOLOCK)
 INNER JOIN CHCAMASHO B WITH(NOLOCK) ON A.CODICAMAS=B.CODICAMAS AND A.REGESTADO = 1
 INNER JOIN
 (
   SELECT A.CODICAMAS,MAX(A.ID) ID 
   FROM  CHREGESTA A WITH(NOLOCK)
   INNER JOIN CHCAMASHO B WITH(NOLOCK) ON A.CODICAMAS=B.CODICAMAS AND A.REGESTADO = 1
   GROUP BY A.CODICAMAS
 ) AS G ON G.ID=A.ID
 INNER JOIN INPacient C WITH(NOLOCK) ON A.IPCODPACI=C.IPCODPACI
 INNER JOIN CHTIPESTA F WITH(NOLOCK) ON A.CODTIPEST=F.CODTIPEST
 INNER JOIN ADINGRESO J WITH(NOLOCK) ON A.NUMINGRES=J.NUMINGRES 
 INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON  J.GENCONENTITY=HA.ID
 INNER JOIN Common.ThirdParty AS TP ON TP.Id=HA.ThirdPartyId
 LEFT  JOIN Report.BI_HEALTHADMINISTRATOR HABI WITH(NOLOCK) ON HABI.HealthAdministratorId=HA.Id AND HABI.Code=HA.Code 
 LEFT OUTER JOIN HCREGEGRE I with(nolock) ON A.NUMINGRES = I.NUMINGRES
 Outer apply 
 (select TOP 1 INDICAPAC,IPCODPACI, NUMINGRES from HCHISPACA where IPCODPACI = J.IPCODPACI AND NUMINGRES = J.NUMINGRES order by FECHISPAC desc) as X
 Outer apply
 (SELECT TOP 1 D.CODDIAGNO FROM dbo.INDIAGNOP D WHERE CODDIAPRI=1 AND D.NUMINGRES= J.NUMINGRES order by D.FECDIAGNO desc ) as Y
 LEFT OUTER JOIN dbo.INDIAGNOS Q ON Y.CODDIAGNO=Q.CODDIAGNO
),


----********************************************************* CTE FECHA INICIAL ESTANCIA ******************************************************************************-----

/* CTE QUE CONSULTA LA TABLA QUE GUARDA LAS ESTANCIAS Y TRAE LA FECHA INICIAL DE ESTANCIA DEL INGRESO */

CTE_FECHA_INICIAL_HOSPITALIZACION
AS
(
 SELECT EST.NUMINGRES,MIN(CAST(EST.FECINIEST AS DATE)) 'FECHA HOSPITALIZACION'  
	FROM DBO.CHREGESTA EST
	INNER JOIN CTE_CENSO_DIARIO AS CEN ON CEN.INGRESO=EST.NUMINGRES
	GROUP BY EST.NUMINGRES
),

CTE_OCUPACION_HORAS
AS
(
SELECT G.[ID CAMA],YEAR(COMMON.GETDATE()) 'AÑO',MONTH(COMMON.GETDATE()) 'MES',DAY(COMMON.GETDATE()) 'DIA',SUM([HORAS OCUPACION]) [HORAS OCUPACION]
FROM (
   SELECT A.CODICAMAS [ID CAMA],SUM(DATEDIFF(HOUR,CASE WHEN CAST(FECINIEST AS DATE)=CAST(COMMON.GETDATE() AS DATE) THEN FECINIEST   ---FECINIEST,FECFINEST
    ELSE CAST(CAST(COMMON.GETDATE() AS DATE) AS DATETIME) END,DATEADD(MINUTE, 1440, CAST(CAST(COMMON.GETDATE() AS DATE) AS DATETIME)))) 'HORAS OCUPACION'
    FROM  CHREGESTA A WITH(NOLOCK)
    INNER JOIN CHCAMASHO B WITH(NOLOCK) ON A.CODICAMAS=B.CODICAMAS AND A.REGESTADO = 1 GROUP BY A.CODICAMAS
   ---- 217,299,672,673
   UNION ALL
  SELECT A.CODICAMAS [ID CAMA],SUM(DATEDIFF(HOUR,CASE WHEN CAST(FECINIEST AS DATE)=CAST(COMMON.GETDATE() AS DATE) THEN FECINIEST   ----FECINIEST,FECFINEST
   ELSE CAST(CAST(COMMON.GETDATE() AS DATE) AS DATETIME) END,FECFINEST)) 'HORAS OCUPACION'
   FROM  CHREGESTA A WITH(NOLOCK)
   INNER JOIN CHCAMASHO B WITH(NOLOCK) ON A.CODICAMAS=B.CODICAMAS AND A.REGESTADO <> 1 
   WHERE CAST(FECFINEST AS DATE)= CAST(COMMON.GETDATE() AS DATE) GROUP BY A.CODICAMAS
   ) AS G GROUP BY G.[ID CAMA]  ---WHERE G.CODICAMAS=5 
)

SELECT CAM.[ID CAMA],YEAR(COMMON.GETDATE()) 'AÑO',MONTH(COMMON.GETDATE()) 'MES',DAY(COMMON.GETDATE()) 'DIA',
CAM.[CENTRO DE ATENCION],
CAM.[TIPO UNIDAD],
CAM.[TIPO UNIDAD SAN JOSE],
--CAM.[UNIDAD FUNCIONAL],
 STUFF((SELECT ' ' + UPPER(LEFT(value, 1)) + LOWER(SUBSTRING(value, 2, LEN(value)))
        FROM STRING_SPLIT(CAM.[UNIDAD FUNCIONAL], ' ')FOR XML PATH(''), TYPE).value('.', 'VARCHAR(MAX)'),1, 1, '') AS [UNIDAD FUNCIONAL],
CAM.[CODIGO CAMA],
CAM.[DESCRIPCION CAMA]
,CAM.[TIPO CAMA],
CAM.[TIPO HABITACION],
CAM.[VIRTUAL],
CAM.[ESTADO CAMA],CEN.[INGRESO],
CEN.[IDENTIFICACION PACIENTE],
--CEN.[NOMBRE PACIENTE],
 STUFF((SELECT ' ' + UPPER(LEFT(value, 1)) + LOWER(SUBSTRING(value, 2, LEN(value)))
        FROM STRING_SPLIT(CEN.[NOMBRE PACIENTE], ' ')FOR XML PATH(''), TYPE).value('.', 'VARCHAR(MAX)'),1, 1, '') AS [NOMBRE PACIENTE],
CEN.GENERO,
CEN.[NIT],
CEN.[NOMBRE ENTIDAD],
CEN.REGIMEN,
CEN.[EDAD],
CASE WHEN CEN.EDAD>=0 AND CEN.EDAD<=5 THEN 'Primera Infancia'
	 WHEN CEN.EDAD>=6 AND CEN.EDAD<=11 THEN 'Infancia'
	 WHEN CEN.EDAD>=12 AND CEN.EDAD<=18 THEN 'Adolecencia'
	 WHEN CEN.EDAD>=19 AND CEN.EDAD<=26 THEN 'Juventud'
	 WHEN CEN.EDAD>=27 AND CEN.EDAD<=59 THEN 'Adultos' 
	 WHEN CEN.EDAD>=60 THEN 'Vejez' END AS [GRUPO EDAD],
CEN.[DESTINO],CEN.[TIPO ESTANCIA],ISNULL(CEN.[ESTADO CENSO],'LIBRE') [ESTADO CENSO],1 [CANTIDAD],
ISNULL(OCU.[HORAS OCUPACION],0) [HORAS OCUPACION],24-ISNULL(OCU.[HORAS OCUPACION],0) [HORAS LIBRES],
FEC.[FECHA HOSPITALIZACION],
CEN.[FECHA INICIAL UNIDAD],
CEN.[DIAGNOSTICO PRINCIPAL],
CEN.[FECHA NACIMIENTO],
DATEDIFF(DAY,FEC.[FECHA HOSPITALIZACION],CAST(COMMON.GETDATE() AS DATE)) AS [DIAS HOSPITALIZACION],CAM.[MOSTRAR],
CAST(COMMON.GETDATE() AS DATE) AS [FECHA BUSQUEDA],
COMMON.GETDATE() AS [ULTIMA ACTUALIZACION]
FROM CTE_CAMAS CAM
  LEFT JOIN CTE_CENSO_DIARIO AS CEN ON CAM.[ID CAMA]=CEN.[ID CAMA] AND CAM.[AÑO]=CEN.[AÑO] AND CAM.[MES]=CEN.[MES] AND CAM.[DIA]=CEN.[DIA]
  LEFT JOIN CTE_OCUPACION_HORAS OCU ON CAM.[ID CAMA]=OCU.[ID CAMA] AND CAM.[AÑO]=OCU.[AÑO] AND CAM.[MES]=OCU.[MES] AND CAM.[DIA]=OCU.[DIA]
  LEFT JOIN CTE_FECHA_INICIAL_HOSPITALIZACION AS FEC ON FEC.NUMINGRES=CEN.INGRESO
 where MOSTRAR='SI'
-- WHERE CAM.[ID CAMA]=1
--WHERE [ESTADO CENSO]='OCUPADA'
--order by [TIPO UNIDAD],UFUCODIGO


