-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: UploadCubeVieClinicalQxProcedures
-- Extracted by Fabric SQL Extractor SPN v3.9.0





    /*******************************************************************************************************************
Nombre:[Report].UploadCubeVieClinicalQxProcedures
Tipo:View
Observacion: Cubo de autorizaciones
Profesional: Nilsson Galindo
Fecha:08-10-2024
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico:
Fecha:
Observaciones:
-------------------------------------------------------------------------------------------------------------------------------------
Version 3
Persona que modifico:
Fecha:
Observaciones:
***********************************************************************************************************************************/
CREATE VIEW [Report].[UploadCubeVieClinicalQxProcedures] AS


WITH
----a que entidad se realiza la facturación.
CTE_ORDEN_SERVICIO AS
(
	SELECT
		HA.HealthEntityCode AS [CODIGO EPS/ENTIDAD TERRITORIAL FACTURA],
		HA.Name AS [ENTIDAD ADMINISTRADORA FACTURA],
		CASE HA.EntityType WHEN 1  THEN 'EPS Contributivo'
						   WHEN 2  THEN 'EPS Subsidiado'
						   WHEN 3  THEN 'ET Vinculados Municipios'
						   WHEN 4  THEN 'ET Vinculados Departamentos'
						   WHEN 5  THEN 'ARL Riesgos Laborales'
						   WHEN 6  THEN 'MP Medicina Prepagada'
						   WHEN 7  THEN 'IPS Privada'
						   WHEN 8  THEN 'IPS Publica'
						   WHEN 9  THEN 'Regimen Especial'
						   WHEN 10 THEN 'Accidentes de transito'
						   WHEN 11 THEN 'Fosyga'
						   WHEN 12 THEN 'Otros' END AS [REGIMEN FACTURA],QXR.CONSECUQX
	FROM
		dbo.HCQXREALI QXR
		INNER JOIN Billing.ServiceOrder OD ON QXR.GENSERVICEORDER=OD.Id
		INNER JOIN Billing.ServiceOrderDetail ODD ON OD.Id=ODD.ServiceOrderId
		LEFT JOIN Contract.HealthAdministrator HA ON ODD.HealthAdministratorId=HA.Id
	WHERE QXPRINCIP=1 AND odd.Presentation=2
	GROUP BY HA.HealthEntityCode,HA.Name,HA.EntityType,QXR.CONSECUQX
),
--------profesionales de la saulud con su respectiva especialidad
CTE_PROFESIONALES AS 
(
	SELECT
		PRO.CODPROSAL,
		RTRIM(PRO.CODPROSAL)+' - '+PRO.NOMMEDICO AS PROFESIONAL,
		ESP.DESESPECI AS ESPECIALIDAD
	FROM 
		dbo.INPROFSAL PRO
		INNER JOIN dbo.INESPECIA ESP ON PRO.CODESPEC1=ESP.CODESPECI
),
-----autorizaciones de los procedimientos, ambulatorio, qx y no qx
CTE_AUTORIZACIONES AS 
(
	SELECT 
		ORD.[AUTO] AS ORDID,AUD.NUMVALDER AS [NUMERO AUTORIZACION],AU.NUMINGRES,AU.NUMEFOLIO
	FROM dbo.ADAUTSERD AU
		INNER JOIN dbo.ADAUTEVEN AUD ON CODREGUNI=(SELECT MAX(A.CODREGUNI) FROM dbo.ADAUTEVEN A WHERE AU.CODCONCEC=ADAUTSERID AND A.ESTADO=1)
		INNER JOIN dbo.HCORDPROQ ORD ON AU.NUMINGRES=ORD.NUMINGRES AND AU.NUMEFOLIO=ORD.NUMEFOLIO AND AU.CODSERIPS=ORD.CODSERIPS
	WHERE AU.ESTATUSER=1 AND AU.PROSERIPS=1
	UNION ALL
	SELECT 
		ORD.[AUTO] AS ORDID,AUD.NUMVALDER AS [NUMERO AUTORIZACION],AU.NUMINGRES,AU.NUMEFOLIO
	FROM dbo.ADAUTSERD AU
		INNER JOIN dbo.ADAUTEVEN AUD ON CODREGUNI=(SELECT MAX(A.CODREGUNI) FROM dbo.ADAUTEVEN A WHERE AU.CODCONCEC=ADAUTSERID AND A.ESTADO=1)
		INNER JOIN dbo.HCORDPRON ORD ON AU.NUMINGRES=ORD.NUMINGRES AND AU.NUMEFOLIO=ORD.NUMEFOLIO AND AU.CODSERIPS=ORD.CODSERIPS
	WHERE AU.ESTATUSER=1
	UNION ALL
	SELECT 
		ORD.ID AS ORDID, AUD.NUMVALDER AS [NUMERO AUTORIZACION],AU.NUMINGRES,AU.NUMEFOLIO
	FROM dbo.ADAUTSERD AU
		INNER JOIN dbo.ADAUTEVEN AUD ON CODREGUNI=(SELECT MAX(A.CODREGUNI) FROM dbo.ADAUTEVEN A WHERE AU.CODCONCEC=ADAUTSERID AND A.ESTADO=1)
		INNER JOIN dbo.ADRADICACIONQX ORD ON AU.IPCODPACI=ORD.IPCODPACI AND AU.CODSERIPS=ORD.QXPRINCIPAL 
																		AND YEAR(AUD.FECREGEVE)=YEAR(ORD.FECHARADIC)
																		AND MONTH(AUD.FECREGEVE)=MONTH(ORD.FECHARADIC)
	WHERE AU.ESTATUSER=1
),
---discrimina los procedimientos secundarios y principal
CTE_PROCEDIMIENTOS AS
(
	SELECT 
	0 AS NUMERO,
	1 AS TIPO,
	REA.NUMINGRES,
	REA.NUMEFOLIO,
	CUPS.Code,
	CUPS.Description,
	1 AS CANTIDAD
	FROM
	DBO.HCQXREALI REA INNER JOIN
	[Contract].CUPSEntity CUPS ON REA.CODSERIPS=CUPS.Code AND REA.QXPRINCIP=1
	UNION ALL
	SELECT 
	ROW_NUMBER ( )   
	OVER (PARTITION BY REA.NUMINGRES,REA.NUMEFOLIO order by REA.CONSECUQX DESC) AS NUMERO,
	2 AS TIPO, 
	REA.NUMINGRES,
	REA.NUMEFOLIO,
	CUPS.Code,
	CUPS.Description,
	1 AS CATIDAD
	FROM
	DBO.HCQXREALI REA INNER JOIN
	[Contract].CUPSEntity CUPS ON REA.CODSERIPS=CUPS.Code AND REA.QXPRINCIP=0
),
--calcula la suma total de los procedimientos secundarios.
CTE_CUENTA_PROCEDIMIENTOS AS
(
	SELECT 
	SUM(CANTIDAD) AS CATIDAD,
	NUMINGRES,
	NUMEFOLIO
	FROM CTE_PROCEDIMIENTOS
	WHERE TIPO!=1
	GROUP BY NUMINGRES,NUMEFOLIO
),
---------ordenes de reserva de hemocomponentes cuando el procedimiento es hospitalario
CTE_RESERVA_ORDENES AS
(
	SELECT DISTINCT HMCO.NUMINGRES
	FROM
	dbo.HCORHEMCO HMCO
	INNER JOIN dbo.HCORHEMBOL HBOL ON HMCO.ID=HBOL.HCORHEMCOID
	WHERE HBOL.FECSOLRES IS NOT NULL
),
-----lista de chequeo para la reserva de hemocomponentes cuando el procedimiento es ambulatorio.
CTE_RESERVA_RADICACION AS
(
	SELECT
	RADQXD.IDRADICACIONQX
	FROM
	dbo.ADRADICACIONQXD RADQXD
	INNER JOIN dbo.HCLISTACD TACD ON RADQXD.IDLISTACHEQUEOD=TACD.CODCONSEC AND TACD.DESPREENC='ORDEN DE RESERVA DE SANGRE (SI LO REQUIERE)'
),
CTE_EQUIPO_QX AS
(
SELECT
1 AS NUMERO,
EQ.NUMINGRES,
EQ.NUMEFOLIO,
--EQ.CODPROSAL,
EQ.QXPRINCIP,
EQ.TIPOEQUIP,
CASE EQ.TIPOEQUIP WHEN 1 THEN 'Cirujano'
				  WHEN 2 THEN 'Ayudante'
				  WHEN 3 THEN 'Anestesiologo'
				  WHEN 4 THEN 'Instrumentadora'
				  WHEN 5 THEN 'Circulante'
				  WHEN 6 THEN 'Otro' END AS [PERFIL],
PRO.PROFESIONAL,
ESPECIALIDAD
FROM 
dbo.HCQXEQUIP EQ
INNER JOIN CTE_PROFESIONALES PRO ON EQ.CODPROSAL=PRO.CODPROSAL
WHERE QXPRINCIP=1
UNION ALL
SELECT
ROW_NUMBER ( )   
OVER (PARTITION BY EQ.NUMINGRES,EQ.NUMEFOLIO,EQ.TIPOEQUIP order by EQ.CONSEEQQX DESC) AS NUMERO,
EQ.NUMINGRES,
EQ.NUMEFOLIO,
--EQ.CODPROSAL,
EQ.QXPRINCIP,
EQ.TIPOEQUIP,
CASE EQ.TIPOEQUIP WHEN 1 THEN 'Cirujano'
				  WHEN 2 THEN 'Ayudante'
				  WHEN 3 THEN 'Anestesiologo'
				  WHEN 4 THEN 'Instrumentadora'
				  WHEN 5 THEN 'Circulante'
				  WHEN 6 THEN 'Otro' END AS [PERFIL],
PRO.PROFESIONAL,
ESPECIALIDAD
FROM 
dbo.HCQXEQUIP EQ
INNER JOIN CTE_PROFESIONALES PRO ON EQ.CODPROSAL=PRO.CODPROSAL
WHERE QXPRINCIP!=1
),

 CTE_ANESTESIA AS
 (
 SELECT
 ANE.NUMINGRES,
 REG.CODCIRUGI,
 ANE.HORINIANES,
 ANE.HORFINANES
 FROM
 dbo.HCREGANES ANE
 INNER JOIN (SELECT MAX(A.IDANESTES) AS IDANESTES,A.NUMINGRES,B.CODCIRUGI 
			 FROM dbo.HCREGANES A INNER JOIN dbo.HCREGICIR B ON A.IDANESTES=B.IDREGIANES
			 GROUP BY A.NUMINGRES,CODCIRUGI) AS REG ON ANE.IDANESTES=REG.IDANESTES
 ),
-----Información de las notas administrativas 
CTE_NOTAS_ADMINISTRATIVAS AS
(
SELECT
--NTAC.ID,
NTAC.FECHACREACION AS [FECHA REGISTRO],
NTAC.NUMINGRES AS [INGRESO],
CASE WHEN ESL.VARIABLE='Hora Llegada de Paciente' THEN 1 
	 WHEN ESL.VARIABLE='Hora Inicio Limpieza:' THEN 2 
	 WHEN ESL.VARIABLE='Hora Fin Limpieza:' THEN 3 
	 WHEN ESL.VARIABLE='Causa de Inoportunidad en Inicio CX PROG:' THEN 4
	 WHEN ESL.VARIABLE='Complicaciones Intraoperatoria' THEN 5
	 WHEN ESL.VARIABLE='Reintervencion Quirurgica antes de 72 Horas post-operatoria' THEN 6
	 WHEN ESL.VARIABLE='Mortalidad Intraoperatoria:' THEN 7 END AS [VARIABLE],
NTAD.VALOR,
PRO.CODSERIPS,
VAL.DESCRIPCION
FROM 
dbo.NTADMINISTRATIVAS NAD 
INNER JOIN dbo.NTNOTASADMINISTRATIVASC NTAC ON NAD.ID=NTAC.IDNOTAADMINISTRATIVA
INNER JOIN (SELECT NTAD.IDNTNOTASADMINISTRATIVASC AS ID,NTAD.VALOR AS CODSERIPS FROM  
			dbo.NTNOTASADMINISTRATIVASD NTAD 
			INNER JOIN dbo.NTVARIABLES ESL ON NTAD.IDNTVARIABLE=ESL.ID AND ESL.VARIABLE='Procedimiento:') PRO ON NTAC.ID=PRO.ID
INNER JOIN dbo.NTNOTASADMINISTRATIVASD NTAD ON NTAC.ID=NTAD.IDNTNOTASADMINISTRATIVASC
INNER JOIN dbo.NTVARIABLES ESL ON NTAD.IDNTVARIABLE=ESL.ID
LEFT JOIN dbo.NTVARIABLESL VAL ON ESL.ID=VAL.IDNTVARIABLE AND NTAD.VALOR=VAL.CODIGO
WHERE NAD.ID='2' AND ESL.VARIABLE IN ('Hora Llegada de Paciente','Hora Inicio Limpieza:','Hora Fin Limpieza:','Causa de Inoportunidad en Inicio CX PROG:',
'Complicaciones Intraoperatoria','Reintervencion Quirurgica antes de 72 Horas post-operatoria','Mortalidad Intraoperatoria:')
),

CTE_ORDENAMIENTOS_UNICOS AS
(
SELECT MIN(A.AUTO) AS [AUTO],A.NUMINGRES,A.CODSERIPS 
--FROM dbo.HCORDPROQ A INNER JOIN dbo.AGEPROGQX B ON A.[AUTO]=B.AUTOHCORDPROQ AND A.CODSERIPS=B.CODSERIPS--Se ha quito la logica ya que si el ordenamiento y no cuenta con un agendamiento, no puedo enlazar la autorización
FROM dbo.HCORDPROQ A 
WHERE A.CODANULA IS NULL
GROUP BY A.NUMINGRES,A.CODSERIPS
),

CTE_AGENDAMIENTO AS
(
SELECT INF.AUTO 
FROM dbo.ADRADICACIONQX A
INNER JOIN dbo.AGEPROGQX AGE ON A.ID=AGE.IDRADICACIONQX AND A.QXPRINCIPAL=AGE.CODSERIPS
INNER JOIN dbo.HCQXINFOR INF ON (AGE.NUMINGRES=INF.NUMINGRES AND AGE.CODSERIPS=INF.CODSERIPS) OR 
/*LOGICA PARA SAN JOSE*/(AGE.IPCODPACI=INF.IPCODPACI AND AGE.CODSERIPS=INF.CODSERIPS AND CAST(AGE.FECHORAIN AS DATE)=CAST(INF.FECHORINI AS DATE))
),

/*********************************************************************************************************************************
----Se trae la información de los ordenamientos de procedimientos qx o no qx que cuenten con un informe quirurgico, tambien se trae la información de radicacion.
*********************************************************************************************************************************************/
CTE_PROCEDIMIENTOS_QX AS
(
	SELECT DISTINCT
	A.[AUTO] AS ORDID,
	ISNULL(A.CODCENATE,IQX.CODCENATE) AS CODCENATE,
	ISNULL(A.IPCODPACI,IQX.IPCODPACI) AS IPCODPACI,
	ISNULL(A.NUMINGRES,IQX.NUMINGRES) AS NUMINGRES,
	IQX.[AUTO],
	A.NUMEFOLIO,
	A.CODSERIPS AS ORDCODSERIPS,
	CONVERT(numeric(5,2),FIS.PESOPACIE/1000) AS [PESO PACIENTE],
	ING.CODENTIDA,
	ING.GENCAREGROUP,
	IQX.GENSERVICEORDER,
	QXR.CONSECUQX,
	A.CANSERIPS AS [CANTIDAD ORDEN],
	'HOSPITALARIO' AS AMBITO,
	IIF(A.[AUTO] IS NULL,'INFORME QX','Ordenamiento de Procedimientos QX') AS TIPO,
	CASE A.ESTSERIPS WHEN 1 THEN 'Solicitado'
					 WHEN 2 THEN 'Sala Programada'
					 WHEN 3 THEN 'Cancelado'
					 WHEN 4 THEN 'Procedimiento Realizado'
					 WHEN 5 THEN 'Anulado'
					 WHEN 6 THEN 'Programado no realizado' END AS [ESTADO ORDEN],
	A.CODPROSAL,
	CASE A.PRISERIPS WHEN 1 THEN 'Emergencia'
					 WHEN 2 THEN 'Urgencia'
					 WHEN 3 THEN 'Normal'
					 WHEN 4 THEN 'Definir Conducta' END AS [PRIORIDAD ORDEN],
	A.FECORDMED AS [FECHA ORDEN],
	A.UFUCODIGO,
	A.FECHAANULA AS [FECHA CANCELACION ORDEN],
	A.CODDIAGNO,
	CASE A.LATERALIDAD WHEN 0 THEN 'No Aplica'
					   WHEN 1 THEN 'Izquierda'
					   WHEN 3 THEN 'Derecha'
					   WHEN 4 THEN 'Ambos' END AS [LATERALIDAD ORDEN],
	A.PROFESIONALANULA [CODIGO ANULA],
	NULL AS [NUMERO RADICACION],
	NULL AS QXPRINCIPAL,
	NULL AS [FECHA RADICACION],
	NULL AS [FECHA CONFIRMACION RADICACION],
	NULL AS [CODIGO SERVICIO IPS RADICACION],
	NULL AS [ESTADO RADICACION],
	NULL AS [PRIORIDAD RADICACION],
	NULL AS [DIAGNOSTICO RADICACION],
	AGE.FECREGSIS AS [FECHA REGISTRO PROGRAMACION],
	AGE.FECHORAIN AS [FECHA INICIAL CX PROGRAMACION],
	AGE.FECHORAFI AS [FECHA FINAL CX PROGRAMACION],
	IIF(AGE.CODESTPQX=0 AND IQX.NUMEFOLIO IS NOT NULL,7,AGE.CODESTPQX) AS CODESTPQX,
	AGE.FECHACAN AS [FECHA CANCELACION],
	AGE.CODCAUCAN,
	AGE.AGENSALAC,
	AGE.CODPROSAL AS AGECODPROSAL,
	AGE.TIPOANESTESIA,
	AGE.CODSERIPS AS AGCODSERIPS,
	IIF(ORD.NUMINGRES IS NULL,'NO','SI') AS [REQUIERE RESERVA SANGRE],
	IQX.NUMEFOLIO AS [NUMERO FOLIO INFORME],
	IQX.SALACIRUG,
	IQX.CODDIAPRE,
	IQX.CODDIAPOS,
	IQX.TIPHERCIR,
	ANE.HORINIANES,
	ANE.HORFINANES,
	IQX.FECHORINI,
	IQX.FECHORFIN,
	IQX.CODSERIPS AS [CODSERIPS INFORME QX],
	IQX.PROFIANTI AS [PROFILAXIS],
	IQX.URGECIRUG,
	IQX.CLASIFASA,
	IQX.DateOfAdministration,
	IQX.PROTEIMPL,
	IQX.CXCADERAS,
	IQX.CXRODILLA,
	IQX.LAPAROTOM,
	IQX.FRACTABIE,
	IQX.PerioperativeBleeding,
	IQX.PerioperativeBleedingVolume,
	IQX.MaterialCount,
	IQX.MaterialCountQuantity,
	IQX.Compresses,
	IQX.CompressesQuantity,
	IQX.Gauze,
	IQX.GauzeQuantity,
	ISNULL(IQX.FECHORINI,A.FECORDMED) AS [FECHA BUSQUEDA]
	FROM
	dbo.HCORDPROQ A
	INNER JOIN dbo.ADINGRESO ING ON A.NUMINGRES=ING.NUMINGRES AND A.MANEXTPRO=0
	LEFT JOIN CTE_ORDENAMIENTOS_UNICOS B ON A.AUTO=B.AUTO
	LEFT JOIN dbo.AGEPROGQX AGE ON AGE.CODAUTONU=(SELECT MAX(C.CODAUTONU) FROM dbo.AGEPROGQX C WHERE A.[AUTO]=C.AUTOHCORDPROQ AND A.CODSERIPS=C.CODSERIPS)
	FULL JOIN (SELECT IQX.* FROM dbo.HCQXINFOR IQX 
			   INNER JOIN Contract.CUPSEntity CUP ON IQX.CODSERIPS=CUP.Code AND CUP.ServiceType=5
			   WHERE IQX.AUTO NOT IN(SELECT * FROM CTE_AGENDAMIENTO)
			   ) IQX ON B.NUMINGRES=IQX.NUMINGRES AND B.CODSERIPS=IQX.CODSERIPS AND AGE.CODCAUCAN IS NULL
	LEFT JOIN dbo.HCQXREALI QXR ON IQX.NUMINGRES=QXR.NUMINGRES AND IQX.NUMEFOLIO=QXR.NUMEFOLIO AND IQX.CODSERIPS=QXR.CODSERIPS AND QXR.QXPRINCIP=1
	LEFT JOIN dbo.HCEXFISIC FIS ON FIS.NUMCONSEC=(SELECT MAX(F.NUMCONSEC) FROM dbo.HCEXFISIC F WHERE F.NUMINGRES=A.NUMINGRES AND A.NUMEFOLIO<=F.NUMEFOLIO AND F.PESOPACIE!=0)
	LEFT JOIN CTE_RESERVA_ORDENES ORD ON IQX.NUMINGRES=ORD.NUMINGRES
	LEFT JOIN CTE_ANESTESIA ANE ON IQX.NUMINGRES=ANE.NUMINGRES AND IQX.CODSERIPS=ANE.CODCIRUGI
	--------------------------------------------PROCEDIMIENTOS NO QX CON INFORME QX------------------------------------------------------
	UNION ALL
	SELECT
	A.[AUTO] AS ORDID,
	ISNULL(A.CODCENATE,IQX.CODCENATE) AS CODCENATE,
	ISNULL(A.IPCODPACI,IQX.IPCODPACI) AS IPCODPACI,
	ISNULL(A.NUMINGRES,IQX.NUMINGRES) AS NUMINGRES,
	IQX.[AUTO],
	A.NUMEFOLIO,
	A.CODSERIPS AS ORDCODSERIPS,
	CONVERT(NUMERIC(5,2),FIS.PESOPACIE/1000) AS [PESO PACIENTE],
	ING.CODENTIDA,
	ING.GENCAREGROUP,
	IQX.GENSERVICEORDER,
	QXR.CONSECUQX,
	A.CANSERIPS AS [CANTIDAD ORDEN],
	'HOSPITALARIO' AS AMBITO,
	IIF(A.NUMINGRES IS NULL,'Ordenamiento de Procedimientos no QX','INFORME QX no') AS TIPO,
	CASE A.ESTSERIPS WHEN 1 THEN 'Solicitado'
					 WHEN 2 THEN 'Sala Programada'
					 WHEN 3 THEN 'Cancelado'
					 WHEN 4 THEN 'Procedimiento Realizado'
					 WHEN 5 THEN 'Anulado'
					 WHEN 6 THEN 'Programado no realizado' END AS [ESTADO ORDEN],
	A.CODPROSAL,
	CASE A.PRISERIPS WHEN 1 THEN 'Emergencia'
					 WHEN 2 THEN 'Urgencia'
					 WHEN 3 THEN 'Normal'
					 WHEN 4 THEN 'Definir Conducta' END AS [PRIORIDAD ORDEN],
	A.FECORDMED AS [FECHA ORDEN],
	A.UFUCODIGO,
	NULL AS [FECHA CANCELACION ORDEN],
	A.CODDIAGNO,
	CASE A.LATERALIDAD WHEN 0 THEN 'No Aplica'
					   WHEN 1 THEN 'Izquierda'
					   WHEN 3 THEN 'Derecha'
					   WHEN 4 THEN 'Ambos' END AS [LATERALIDAD ORDEN],
	NULL AS [CODIGO ANULA],
	NULL AS [NUMERO RADICACION],
	NULL AS QXPRINCIPAL,
	NULL AS [FECHA RADICACION],
	NULL AS [FECHA CONFIRMACION RADICACION],
	NULL AS [CODIGO SERVICIO IPS RADICACION],
	NULL AS [ESTADO RADICACION],
	NULL AS [PRIORIDAD RADICACION],
	NULL AS [DIAGNOSTICO RADICACION],
	AGE.FECREGSIS AS [FECHA REGISTRO PROGRAMACION],
	AGE.FECHORAIN AS [FECHA INICIAL CX PROGRAMACION],
	AGE.FECHORAFI AS [FECHA FINAL CX PROGRAMACION],
	AGE.CODESTPQX,
	AGE.FECHACAN AS [FECHA CANCELACION],
	AGE.CODCAUCAN,
	AGE.AGENSALAC,
	AGE.CODPROSAL AS AGECODPROSAL,
	AGE.TIPOANESTESIA,
	AGE.CODSERIPS AS AGCODSERIPS,
	IIF(ORD.NUMINGRES IS NULL,'NO','SI') AS [REQUIERE RESERVA SANGRE],
	IQX.NUMEFOLIO AS [NUMERO FOLIO INFORME],
	IQX.SALACIRUG,
	IQX.CODDIAPRE,
	IQX.CODDIAPOS,
	IQX.TIPHERCIR,
	ANE.HORINIANES,
	ANE.HORFINANES,
	IQX.FECHORINI,
	IQX.FECHORFIN,
	IQX.CODSERIPS AS [CODSERIPS INFORME QX],
	IQX.PROFIANTI AS [PROFILAXIS],
	IQX.URGECIRUG,
	IQX.CLASIFASA,
	IQX.DateOfAdministration,
	IQX.PROTEIMPL,
	IQX.CXCADERAS,
	IQX.CXRODILLA,
	IQX.LAPAROTOM,
	IQX.FRACTABIE,
	IQX.PerioperativeBleeding,
	IQX.PerioperativeBleedingVolume,
	IQX.MaterialCount,
	IQX.MaterialCountQuantity,
	IQX.Compresses,
	IQX.CompressesQuantity,
	IQX.Gauze,
	IQX.GauzeQuantity,
	ISNULL(IQX.FECHORINI,A.FECORDMED) AS [FECHA BUSQUEDA]
	FROM
	dbo.HCORDPRON A
	INNER JOIN dbo.ADINGRESO ING ON A.NUMINGRES=ING.NUMINGRES AND A.NUMEFOLIO=(SELECT MAX(B.NUMEFOLIO) FROM dbo.HCORDPRON B WHERE A.NUMINGRES=B.NUMINGRES AND B.ESTSERIPS NOT IN (3,4,5,6))
	FULL JOIN(SELECT IQX.* FROM dbo.HCQXINFOR IQX 
			   INNER JOIN Contract.CUPSEntity CUP ON IQX.CODSERIPS=CUP.Code AND CUP.ServiceType=4
			   WHERE IQX.AUTO NOT IN(SELECT * FROM CTE_AGENDAMIENTO)
			   ) IQX ON A.NUMINGRES=IQX.NUMINGRES AND A.CODSERIPS=IQX.CODSERIPS
	--full JOIN dbo.HCQXINFOR IQX ON A.NUMINGRES=IQX.NUMINGRES AND A.CODSERIPS=IQX.CODSERIPS AND A.ESTSERIPS NOT IN (3,4,5,6)
	INNER JOIN dbo.HCQXREALI QXR ON IQX.NUMINGRES=QXR.NUMINGRES AND IQX.NUMEFOLIO=QXR.NUMEFOLIO AND IQX.CODSERIPS=QXR.CODSERIPS AND QXR.QXPRINCIP=1
	LEFT JOIN dbo.HCEXFISIC FIS ON FIS.NUMCONSEC=(SELECT MAX(F.NUMCONSEC) FROM dbo.HCEXFISIC F WHERE F.NUMINGRES=A.NUMINGRES AND A.NUMEFOLIO<=F.NUMEFOLIO AND F.PESOPACIE!=0)
	LEFT JOIN dbo.AGEPROGQX AGE ON A.[AUTO]=AGE.AUTOHCORDPRON AND A.CODSERIPS=AGE.CODSERIPS 
	LEFT JOIN CTE_RESERVA_ORDENES ORD ON IQX.NUMINGRES=ORD.NUMINGRES
	LEFT JOIN CTE_ANESTESIA ANE ON IQX.NUMINGRES=ANE.NUMINGRES AND IQX.CODSERIPS=ANE.CODCIRUGI
	UNION ALL
	-----------------------------------------------CIRUGIAS CON AMBITO AMBULATORIO------------------------------------------------------
	SELECT
	a.ID AS ORDID,
	A.CODCENATE,
	A.IPCODPACI,
	ISNULL(IQX.NUMINGRES,ING.NUMINGRES) AS NUMINGRES,
	IQX.[AUTO],
	IQX.NUMEFOLIO AS NUMEFOLIO,
	NULL AS ORDCODSERIPS,
	NULL AS [PESO PACIENTE],
	ING.CODENTIDA,
	ING.GENCAREGROUP,
	IQX.GENSERVICEORDER,
	QXR.CONSECUQX,
	NULL AS [CANTIDAD ORDEN],
	'AMBULATORIO' AS AMBITO,
	'Radicacion' AS TIPO,
	NULL AS [ESTADO ORDEN],
	NULL AS CODPROSAL,
	NULL AS [PRIORIDAD ORDEN],
	NULL AS [FECHA ORDEN],
	NULL AS UFUCODIGO,
	NULL AS [FECHA CANCELACION ORDEN],
	NULL AS CODDIAGNO,
	NULL AS [LATERALIDAD ORDEN],
	NULL AS [CODIGO ANULA],
	A.NUMRADICACION AS [NUMERO RADICACION],
	A.QXPRINCIPAL,
	A.FECHARADIC AS [FECHA RADICACION],
	A.FECHACONFIRMACION AS [FECHA CONFIRMACION RADICACION],
	A.QXPRINCIPAL AS [CODIGO SERVICIO IPS RADICACION],
	CASE A.ESTADO WHEN 1 THEN 'Radicado'
				  WHEN 2 THEN 'Confirmado' 
				  WHEN 3 THEN 'Anulado' END AS [ESTADO RADICACION],
	CASE A.PRIORIDAD WHEN 1 THEN 'Emergencia'
					 WHEN 2 THEN 'Urgencia'
					 WHEN 3 THEN 'Normal' END AS [PRIORIDAD RADICACION],
	A.CODDIAGNO AS [DIAGNOSTICO RADICACION],
	AGE.FECREGSIS AS [FECHA REGISTRO PROGRAMACION],
	AGE.FECHORAIN AS [FECHA INICIAL CX PROGRAMACION],
	AGE.FECHORAFI AS [FECHA FINAL CX PROGRAMACION],
	AGE.CODESTPQX,
	AGE.FECHACAN AS [FECHA CANCELACION],
	AGE.CODCAUCAN,
	AGE.AGENSALAC,
	AGE.CODPROSAL AS AGECODPROSAL,
	AGE.TIPOANESTESIA,
	AGE.CODSERIPS AS AGCODSERIPS,
	IIF(RES.IDRADICACIONQX IS NULL,'NO','SI') AS [REQUIERE RESERVA SANGRE],
	IQX.NUMEFOLIO AS [NUMERO FOLIO INFORME],
	IQX.SALACIRUG,
	IQX.CODDIAPRE,
	IQX.CODDIAPOS,
	IQX.TIPHERCIR,
	ANE.HORINIANES,
	ANE.HORFINANES,
	IQX.FECHORINI,
	IQX.FECHORFIN,
	IQX.CODSERIPS AS [CODSERIPS INFORME QX],
	IQX.PROFIANTI AS [PROFILAXIS],
	IQX.URGECIRUG,
	IQX.CLASIFASA,
	IQX.DateOfAdministration,
	IQX.PROTEIMPL,
	IQX.CXCADERAS,
	IQX.CXRODILLA,
	IQX.LAPAROTOM,
	IQX.FRACTABIE,
	IQX.PerioperativeBleeding,
	IQX.PerioperativeBleedingVolume,
	IQX.MaterialCount,
	IQX.MaterialCountQuantity,
	IQX.Compresses,
	IQX.CompressesQuantity,
	IQX.Gauze,
	IQX.GauzeQuantity,
	ISNULL(IQX.FECHORINI,A.FECHARADIC) AS [FECHA BUSQUEDA]
	FROM 
	dbo.ADRADICACIONQX A
	LEFT JOIN dbo.AGEPROGQX AGE ON A.ID=AGE.IDRADICACIONQX AND A.QXPRINCIPAL=AGE.CODSERIPS
	LEFT JOIN dbo.HCQXINFOR IQX ON (AGE.NUMINGRES=IQX.NUMINGRES AND AGE.CODSERIPS=IQX.CODSERIPS) OR /*LOGICA PARA SAN JOSE*/(AGE.IPCODPACI=IQX.IPCODPACI AND AGE.CODSERIPS=IQX.CODSERIPS AND CAST(AGE.FECHORAIN AS DATE)=CAST(IQX.FECHORINI AS DATE))
	LEFT JOIN dbo.ADINGRESO ING ON ISNULL(AGE.NUMINGRES,IQX.NUMINGRES)=ING.NUMINGRES
	LEFT JOIN dbo.HCQXREALI QXR ON IQX.NUMINGRES=QXR.NUMINGRES AND IQX.NUMEFOLIO=QXR.NUMEFOLIO AND IQX.CODSERIPS=QXR.CODSERIPS AND QXR.QXPRINCIP=1
	LEFT JOIN CTE_RESERVA_RADICACION RES ON A.ID=RES.IDRADICACIONQX
	LEFT JOIN CTE_ANESTESIA ANE ON IQX.NUMINGRES=ANE.NUMINGRES AND IQX.CODSERIPS=ANE.CODCIRUGI
	
	----WHERE A.IPCODPACI='1006774552'
)
/***************************************************************************************************************************
***************************************************************************************************************************/

SELECT DISTINCT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CENA.NOMCENATE AS [CENTRO DE ATENCION],
TID.SIGLA AS [SIGLA TIPO DOCUMENTO],
TID.NOMBRE AS [TIPO DOCUMENTO],
QX.IPCODPACI AS [IDENTIFICACION PACIENTE],
PAC.IPPRIAPEL AS [PRIMER APELLIDO PACIENTE],
PAC.IPSEGAPEL AS [SEGUNDO APELLIDO PACIENTE],
PAC.IPPRINOMB AS [PRIMER NOMBRE PACIENTE],
PAC.IPSEGNOMB AS [SEGUNDO NOMBRE PACIENTE],
PAC.IPNOMCOMP AS [NOMBRE COMPLETO PACIENTE],
CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO PACIENTE],
IIF(QX.[FECHA ORDEN] IS NULL,IIF(QX.[FECHA RADICACION] IS NULL,CONCAT(DATEDIFF(YEAR, PAC.IPFECNACI, QX.FECHORINI) - 
																CASE WHEN MONTH(PAC.IPFECNACI) > MONTH(QX.FECHORINI) OR 
																		(MONTH(PAC.IPFECNACI) = MONTH(QX.FECHORINI) AND DAY(PAC.IPFECNACI) > DAY(QX.FECHORINI)) THEN 1 ELSE 0 END, ' Años, ', DATEDIFF(MONTH, PAC.IPFECNACI, QX.FECHORINI) % 12 - 
																CASE WHEN DAY(PAC.IPFECNACI) > DAY(QX.FECHORINI) THEN 1 ELSE 0 END, ' Meses, ', DAY(QX.FECHORINI) - DAY(PAC.IPFECNACI) + 
																CASE WHEN DAY(QX.FECHORINI) < DAY(PAC.IPFECNACI) THEN DAY(EOMONTH(PAC.IPFECNACI, 0)) ELSE 0 END, ' Dias')
															  ,CONCAT(DATEDIFF(YEAR, PAC.IPFECNACI, QX.[FECHA RADICACION]) - 
																CASE WHEN MONTH(PAC.IPFECNACI) > MONTH(QX.[FECHA RADICACION]) OR 
																		(MONTH(PAC.IPFECNACI) = MONTH(QX.[FECHA RADICACION]) AND DAY(PAC.IPFECNACI) > DAY(QX.[FECHA RADICACION])) THEN 1 ELSE 0 END, ' Años, ', DATEDIFF(MONTH, PAC.IPFECNACI, QX.[FECHA RADICACION]) % 12 - 
																CASE WHEN DAY(PAC.IPFECNACI) > DAY(QX.[FECHA RADICACION]) THEN 1 ELSE 0 END, ' Meses, ', DAY(QX.[FECHA RADICACION]) - DAY(PAC.IPFECNACI) + 
																CASE WHEN DAY(QX.[FECHA RADICACION]) < DAY(PAC.IPFECNACI) THEN DAY(EOMONTH(PAC.IPFECNACI, 0)) ELSE 0 END, ' Dias'))
							,CONCAT(DATEDIFF(YEAR, PAC.IPFECNACI, QX.[FECHA ORDEN]) - 
							 CASE WHEN MONTH(PAC.IPFECNACI) > MONTH(QX.[FECHA ORDEN]) OR 
							 		(MONTH(PAC.IPFECNACI) = MONTH(QX.[FECHA ORDEN]) AND DAY(PAC.IPFECNACI) > DAY(QX.[FECHA ORDEN])) THEN 1 ELSE 0 END, ' Años, ', DATEDIFF(MONTH, PAC.IPFECNACI, QX.[FECHA ORDEN]) % 12 - 
							 CASE WHEN DAY(PAC.IPFECNACI) > DAY(QX.[FECHA ORDEN]) THEN 1 ELSE 0 END, ' Meses, ', DAY(QX.[FECHA ORDEN]) - DAY(PAC.IPFECNACI) + 
							 CASE WHEN DAY(QX.[FECHA ORDEN]) < DAY(PAC.IPFECNACI) THEN DAY(EOMONTH(PAC.IPFECNACI, 0)) ELSE 0 END, ' Dias')) AS [EDAD PACIENTE],
CASE WHEN PAC.IPSEXOPAC = '1' THEN 'Hombre' WHEN PAC.IPSEXOPAC = '2' THEN 'Mujer' END AS [SEXO BIOLOGICO PACIENTE], 
GEN.NAME AS [IDENTIDAD GENERO PACIENTE],
QX.[PESO PACIENTE],
PAC.IPTELEFON AS [TELEFONO PACIENTE], 
PAC.IPTELMOVI AS [MOVIL PACIENTE],
DEP.depcodigo AS [CODIGO DEPARTAMENTO], 
DEP.nomdepart AS [NOMBRE DEPARTAMENTO RESIDENCIA],
MUN.MUNCODIGO [CODIGO MUNICIPIO RESIDENCIA], 
MUN.MUNNOMBRE AS [NOMBRE MUNICIPIO RESIDENCIA],
PAC.IPDIRECCI AS [DIRECCION PACIENTE],
EA.HealthEntityCode AS [CODIGO EPS/ENTIDAD TERRITORIAL],
EA.Name AS [ENTIDAD ADMINISTRADORA],
CASE EA.EntityType WHEN 1  THEN 'EPS Contributivo'
				   WHEN 2  THEN 'EPS Subsidiado'
				   WHEN 3  THEN 'ET Vinculados Municipios'
				   WHEN 4  THEN 'ET Vinculados Departamentos'
				   WHEN 5  THEN 'ARL Riesgos Laborales'
				   WHEN 6  THEN 'MP Medicina Prepagada'
				   WHEN 7  THEN 'IPS Privada'
				   WHEN 8  THEN 'IPS Publica'
				   WHEN 9  THEN 'Regimen Especial'
				   WHEN 10 THEN 'Accidentes de transito'
				   WHEN 11 THEN 'Fosyga'
				   WHEN 12 THEN 'Otros' END AS [REGIMEN],
CASE GA.LIQUIDATIONTYPE WHEN 1 THEN 'PAGO POR SERVICIOS'
						WHEN 2 THEN 'PGP'
						WHEN 3 THEN 'FACTURA GLOBAL'
						WHEN 4 THEN 'CAPITACION GLOBAL'
						WHEN 5 THEN 'CONTROL' END [TIPO CONTRATO],
OS.[CODIGO EPS/ENTIDAD TERRITORIAL FACTURA],
OS.[ENTIDAD ADMINISTRADORA FACTURA],
OS.[REGIMEN FACTURA],
QX.AMBITO,
QX.TIPO,
QX.NUMINGRES AS [NUMERO INGRESO],
QX.NUMEFOLIO AS [NUMERO FOLIO ORDEN],
QX.[FECHA ORDEN],
QX.[CANTIDAD ORDEN],
PRO_ORD.PROFESIONAL AS [PROFESIONAL ORDEN],
PRO_ORD.ESPECIALIDAD AS [ESPECIALIDAD ORDEN],
RTRIM(FUN.UFUCODIGO)+' - '+FUN.UFUDESCRI AS [UNIDAD FUNCIONAL ORDEN],
IPS.CODSERIPS AS [CODIGO SERVICIO IPS ORDEN],
IPS.DESSERIPS AS [SERVICIO IPS ORDEN],
QX.[LATERALIDAD ORDEN],
QX.[PRIORIDAD ORDEN],
DIA.CODDIAGNO+'-'+DIA.NOMDIAGNO AS [DIAGNOSTICO PRINCIPAL ORDEN],
QX.[ESTADO ORDEN],
QX.[FECHA CANCELACION ORDEN],
PRO_AORD.PROFESIONAL AS [PROFESIONAL ANULA ORDEN],
PRO_AORD.ESPECIALIDAD AS [ESPECIALIDAD ANULA ORDEN],
QX.[NUMERO RADICACION],                    
QX.[FECHA RADICACION],
QX.[FECHA CONFIRMACION RADICACION],
QX.[CODIGO SERVICIO IPS RADICACION],
IPSR.DESSERIPS AS [SERVICIO IPS RADICACION],
QX.[ESTADO RADICACION],
QX.[PRIORIDAD RADICACION],
DIAR.CODDIAGNO+'-'+DIAR.NOMDIAGNO AS [DIAGNOSTICO PRINCIPAL RADICACION],
AU.[NUMERO AUTORIZACION],
AU.NUMEFOLIO AS [NUMERO FOLIO AUTORIZACION],
QX.[FECHA REGISTRO PROGRAMACION],
AGIPS.CODSERIPS AS [CODIGO SERVICIO IPS PROGRAMACION],
AGIPS.DESSERIPS AS [SERVICIO IPS PROGRAMACION],
QX.[FECHA INICIAL CX PROGRAMACION],
QX.[FECHA FINAL CX PROGRAMACION],
SAL.DESCRIPSAL AS [SALA PROGRAMACION],
PRO_AGE.PROFESIONAL AS [PROFECIONAL PROGRAMACION],
PRO_AGE.ESPECIALIDAD AS [ESPECIALIDAD PROGRAMACION],
CASE QX.TIPOANESTESIA WHEN 1 THEN 'Local'
					  WHEN 2 THEN 'Regional'
					  WHEN 3 THEN 'General' 
					  WHEN 4 THEN 'Combinada'
					  WHEN 5 THEN 'No aplica' END AS [TIPO ANESTESIA PROGRAMACION],
IIF(PRI.CODE IS NULL, CASE QX.CODESTPQX WHEN 0 THEN 'Cirugía Programada'
										WHEN 1 THEN 'Paciente admitido'
										WHEN 2 THEN 'Paciente en sala de espera' 
										WHEN 3 THEN 'Paciente en sala quirurgica'
										WHEN 4 THEN 'Paciente en recuperación'
										WHEN 5 THEN 'Paciente con alta'
										WHEN 6 THEN 'Anulado - Cancelada' 
										WHEN 7 THEN 'Cirugía realizada' END,
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,'Anulado - Cancelada','Cirugía realizada')) AS [ESTADO PROGRAMACION],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NOT NULL,NULL,QX.[FECHA CANCELACION])AS [FECHA CANCELACION],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NOT NULL,NULL,CAN.DESCAUCAN) AS [CAUSA CANCELACION], 
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,PRI.CODE) AS [CODIGO CUPS],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,PRI.[DESCRIPTION]) AS [CUPS PROCEDIMIENTO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC1.Code +' - '+ SEC1.Description) AS [PROCEDIMIENTO SECUNDARIO UNO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC2.Code +' - '+ SEC2.Description) AS [PROCEDIMIENTO SECUNDARIO DOS],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC3.Code +' - '+ SEC3.Description) AS [PROCEDIMIENTO SECUNDARIO TRES],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC4.Code +' - '+ SEC4.Description) AS [PROCEDIMIENTO SECUNDARIO CUATRO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC5.Code +' - '+ SEC5.Description) AS [PROCEDIMIENTO SECUNDARIO CINCO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC6.Code +' - '+ SEC6.Description) AS [PROCEDIMIENTO SECUNDARIO SEIS],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC7.Code +' - '+ SEC7.Description) AS [PROCEDIMIENTO SECUNDARIO SIETE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC8.Code +' - '+ SEC8.Description) AS [PROCEDIMIENTO SECUNDARIO OCHO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC9.Code +' - '+ SEC9.Description) AS [PROCEDIMIENTO SECUNDARIO NUEVE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC10.Code +' - '+ SEC10.Description) AS [PROCEDIMIENTO SECUNDARIO DIEZ],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC11.Code +' - '+ SEC11.Description) AS [PROCEDIMIENTO SECUNDARIO ONCE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC12.Code +' - '+ SEC12.Description) AS [PROCEDIMIENTO SECUNDARIO DOCE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC13.Code +' - '+ SEC13.Description) AS [PROCEDIMIENTO SECUNDARIO TRECE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC14.Code +' - '+ SEC14.Description) AS [PROCEDIMIENTO SECUNDARIO CATORCE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,SEC15.Code +' - '+ SEC15.Description) AS [PROCEDIMIENTO SECUNDARIO QUINCE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,0,ISNULL(CONTAR.CATIDAD,0)) AS [CANTIDAD PROCEDIMIENTOS SECUNDARIOS],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,QX.[REQUIERE RESERVA SANGRE]) AS [REQUIERE RESERVA SANGRE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,QX.[NUMERO FOLIO INFORME]) AS [NUMERO FOLIO INFORME],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,QX.SALACIRUG) AS [SALA INFORME],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,DIGPRE.CODDIAGNO) AS [CODIGO DIAGNOSTICO PRE OPERATORIO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,DIGPRE.NOMDIAGNO) AS [DIAGNOSTICO PRE OPERATORIO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,DIGPOS.CODDIAGNO) AS [CODIGO DIAGNOSTICO POS OPERATORIO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,DIGPOS.NOMDIAGNO) AS [DIAGNOSTICO POS OPERATORIO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,EQUPRI.PROFESIONAL) AS [PROFESIONAL PRINCIPAL],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,EQUPRI.ESPECIALIDAD) AS [ESPECIALIDAD PROFESIONAL PRINCIPAL],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,EQUPRI.PERFIL) AS [PERFIL PROFESIONAL PRINCIPAL],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,EQUANE.PROFESIONAL) AS [ANESTESIOLOGO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,EQUINS.PROFESIONAL) AS [INSTRUMENTADOR],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,EQUAYU.PROFESIONAL) AS [AYUDANTE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,EQUCIR.PROFESIONAL) AS [CIRCULANTE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.TIPHERCIR WHEN 1 THEN 'LIMPIA'
										   WHEN 2 THEN 'LIMPIA CONTAMINADA'
										   WHEN 3 THEN 'CONTAMINADA'
										   WHEN 4 THEN 'SUCIA E INFECTADA'
										   WHEN 5 THEN 'SUCIA'
										   WHEN 6 THEN 'INFECTADA'
										   WHEN 7 THEN 'NO APLICA' END) AS [TIPO HERIDA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,QX.HORINIANES) AS [FECHA INICIO ANESTESIA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,QX.HORFINANES) AS [FECHA FINAL ANESTESIA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,QX.FECHORINI) AS [FECHA INICIAL CX INFORME],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,QX.FECHORFIN) AS [FECHA FINAL CX INFORME],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.URGECIRUG WHEN 1 THEN 'SI' ELSE 'NO' END) AS [URGENTE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,QX.CLASIFASA) AS [CLASIFICACION ASA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.[PROFILAXIS] WHEN 1 THEN 'SI' ELSE 'NO' END) AS [PROFILAXIS],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,QX.DateOfAdministration) AS [FECHA APLICACION PROFILAXIS],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.PROTEIMPL WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END) AS [PROTESIS/IMPLANTE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.CXCADERAS WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END)AS [CX CADERA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.CXRODILLA WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END) AS [CX RODILLA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.LAPAROTOM WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END) AS [LAPARATOMIA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.FRACTABIE WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END) AS [FRACTURA ABIERTA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.PerioperativeBleeding WHEN 1 THEN 'SI'
													   WHEN 2 THEN 'NO'
													   WHEN 3 THEN 'NO APLICA' END) AS [SANGRADO PERIOPERATORIO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,QX.PerioperativeBleedingVolume) AS [VOLUMEN PERIOPERATORIO],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.MaterialCount WHEN 1 THEN 'SI'
											   WHEN 2 THEN 'NO'
											   WHEN 3 THEN 'NO APLICA' END) AS [CONTEO MATERIAL],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.MaterialCountQuantity WHEN 1 THEN 'COMPLETAS'
													   WHEN 2 THEN 'INCOMPLETAS' END) AS [CANTIDAD MATERIAL],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.Compresses WHEN 1 THEN 'SI'
											WHEN 2 THEN 'NO'
											WHEN 3 THEN 'NO APLICA' END) AS [CONTEO COMPRESAS],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.CompressesQuantity WHEN 1 THEN 'COMPLETAS'
													WHEN 2 THEN 'INCOMPLETAS' END) AS [COMPRESAS],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.Gauze WHEN 1 THEN 'SI'
									   WHEN 2 THEN 'NO'
									   WHEN 3 THEN 'NO APLICA' END) AS [CONTEO GASAS],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,CASE QX.GauzeQuantity WHEN 1 THEN 'COMPLETAS'
											   WHEN 2 THEN 'INCOMPLETAS' END) AS [GASAS],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,NOT1.VALOR) AS [HORA LLEGADA PACIENTE],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,NOT2.VALOR) AS [FECHA INICIO LIMPIEZA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,NOT3.VALOR) AS [FECHA FINAL LIMPIEZA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,NOT4.DESCRIPCION) AS [CAUSA INOPORTUNIDAD INICIO CX],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,NOT5.DESCRIPCION) AS [COMPLICACIONES INTRAOPERATORIA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,NOT6.DESCRIPCION) AS [REINTERVENCION QX ANTES 72 HORAS],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,NULL,NOT7.DESCRIPCION) AS [MORTALIDAD INTRAOPERATORIA],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,0,CASE WHEN QX.[AUTO] IS NULL THEN 0 ELSE 1 END) AS [CANTIDAD INFORMES QX],
 IIF(QX.CODESTPQX=6 AND QX.[NUMERO FOLIO INFORME] IS NULL,0,CASE WHEN QX.[AUTO] IS NULL THEN 0 ELSE ISNULL(CONTAR.CATIDAD,0)+1 END) AS [CANTIDAD PROCEDIMIENTOS QX],
CAST([FECHA BUSQUEDA] AS date) AS [FECHA BUSQUEDA],
YEAR([FECHA BUSQUEDA]) AS [AÑO BUSQUEDA],
MONTH([FECHA BUSQUEDA]) AS [MES BUSQUEDA],
CONCAT(FORMAT(MONTH([FECHA BUSQUEDA]), '00') ,' - ', 
CASE MONTH([FECHA BUSQUEDA]) WHEN 1 THEN 'ENE'
   						WHEN 2 THEN 'FEB'
						WHEN 3 THEN 'MAR'
						WHEN 4 THEN 'ABR'
						WHEN 5 THEN 'MAY'
						WHEN 6 THEN 'JUN'
						WHEN 7 THEN 'JUL'
						WHEN 8 THEN 'AGO'
						WHEN 9 THEN 'SEP'
						WHEN 10 THEN 'OCT'
						WHEN 11 THEN 'NOV'
						WHEN 12 THEN 'DIC' END) AS [MES NOMBRE BUSQUEDA],
CASE DATENAME(dw,[FECHA BUSQUEDA]) WHEN 'Monday' THEN 'LUN' 
							  WHEN 'Tuesday' THEN 'MAR' 
							  WHEN 'Wednesday' THEN 'MIE' 
							  WHEN 'Thursday' THEN 'JUE' 
							  WHEN 'Friday' THEN 'VIE'
							  WHEN 'Saturday' THEN 'SAB' 
							  WHEN 'Sunday' THEN 'DOM' END AS [DIA SEMANA],
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
CTE_PROCEDIMIENTOS_QX QX
INNER JOIN dbo.ADCENATEN CENA ON QX.CODCENATE=CENA.CODCENATE
INNER JOIN dbo.INPACIENT PAC ON QX.IPCODPACI=PAC.IPCODPACI
INNER JOIN dbo.ADTIPOIDENTIFICA TID ON PAC.IPTIPODOC=TID.CODIGO
INNER JOIN dbo.INUBICACI AS UBI ON PAC.AUUBICACI = UBI.AUUBICACI 
INNER JOIN dbo.INMUNICIP AS MUN ON UBI.DEPMUNCOD = MUN.DEPMUNCOD 
INNER JOIN dbo.INDEPARTA AS DEP ON DEP.depcodigo = MUN.DEPCODIGO
LEFT JOIN CTE_ORDEN_SERVICIO OS ON QX.CONSECUQX=OS.CONSECUQX
LEFT JOIN Contract.HealthAdministrator EA ON ISNULL(QX.CODENTIDA,PAC.CODENTIDA)=EA.CODE
LEFT JOIN CONTRACT.CAREGROUP AS GA ON ISNULL(QX.GENCAREGROUP,PAC.GENCAREGROUP)=GA.ID
LEFT JOIN Admissions.GenderTypes GEN ON PAC.IdGenderIdentity=GEN.Id
LEFT JOIN CTE_PROFESIONALES PRO_ORD ON QX.CODPROSAL=PRO_ORD.CODPROSAL
LEFT JOIN CTE_PROFESIONALES PRO_AORD ON QX.[CODIGO ANULA]=PRO_AORD.CODPROSAL
LEFT JOIN CTE_PROFESIONALES PRO_AGE ON QX.AGECODPROSAL=PRO_AGE.CODPROSAL
LEFT JOIN dbo.INUNIFUNC FUN ON QX.UFUCODIGO=FUN.UFUCODIGO
LEFT JOIN dbo.INCUPSIPS IPS ON QX.ORDCODSERIPS=IPS.CODSERIPS
LEFT JOIN dbo.INCUPSIPS IPSR ON QX.[CODIGO SERVICIO IPS RADICACION]=IPSR.CODSERIPS
LEFT JOIN dbo.INCUPSIPS AGIPS ON QX.AGCODSERIPS=AGIPS.CODSERIPS
LEFT JOIN dbo.INDIAGNOS DIA ON QX.CODDIAGNO=DIA.CODDIAGNO
LEFT JOIN dbo.INDIAGNOS DIAR ON QX.[DIAGNOSTICO RADICACION]=DIAR.CODDIAGNO
LEFT JOIN CTE_AUTORIZACIONES AU ON QX.ORDID=AU.ORDID AND QX.NUMINGRES=AU.NUMINGRES
LEFT JOIN dbo.AGCACANQX CAN ON QX.CODCAUCAN=CAN.CODCACANQ
LEFT JOIN dbo.AGENSALAC SAL ON QX.AGENSALAC=SAL.CODCONCEC
LEFT JOIN CTE_PROCEDIMIENTOS PRI ON QX.NUMINGRES=PRI.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=PRI.NUMEFOLIO AND PRI.TIPO=1 
LEFT JOIN CTE_PROCEDIMIENTOS SEC1 ON QX.NUMINGRES=SEC1.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC1.NUMEFOLIO AND SEC1.TIPO=2 AND SEC1.NUMERO=1 
LEFT JOIN CTE_PROCEDIMIENTOS SEC2 ON QX.NUMINGRES=SEC2.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC2.NUMEFOLIO AND SEC2.TIPO=2 AND SEC2.NUMERO=2 
LEFT JOIN CTE_PROCEDIMIENTOS SEC3 ON QX.NUMINGRES=SEC3.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC3.NUMEFOLIO AND SEC3.TIPO=2 AND SEC3.NUMERO=3
LEFT JOIN CTE_PROCEDIMIENTOS SEC4 ON QX.NUMINGRES=SEC4.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC4.NUMEFOLIO AND SEC4.TIPO=2 AND SEC4.NUMERO=4
LEFT JOIN CTE_PROCEDIMIENTOS SEC5 ON QX.NUMINGRES=SEC5.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC5.NUMEFOLIO AND SEC5.TIPO=2 AND SEC5.NUMERO=5
LEFT JOIN CTE_PROCEDIMIENTOS SEC6 ON QX.NUMINGRES=SEC6.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC6.NUMEFOLIO AND SEC6.TIPO=2 AND SEC6.NUMERO=6
LEFT JOIN CTE_PROCEDIMIENTOS SEC7 ON QX.NUMINGRES=SEC7.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC7.NUMEFOLIO AND SEC7.TIPO=2 AND SEC7.NUMERO=7
LEFT JOIN CTE_PROCEDIMIENTOS SEC8 ON QX.NUMINGRES=SEC8.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC8.NUMEFOLIO AND SEC8.TIPO=2 AND SEC8.NUMERO=8
LEFT JOIN CTE_PROCEDIMIENTOS SEC9 ON QX.NUMINGRES=SEC9.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC9.NUMEFOLIO AND SEC9.TIPO=2 AND SEC9.NUMERO=9
LEFT JOIN CTE_PROCEDIMIENTOS SEC10 ON QX.NUMINGRES=SEC10.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC10.NUMEFOLIO AND SEC10.TIPO=2 AND SEC10.NUMERO=10
LEFT JOIN CTE_PROCEDIMIENTOS SEC11 ON QX.NUMINGRES=SEC11.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC11.NUMEFOLIO AND SEC11.TIPO=2 AND SEC11.NUMERO=11
LEFT JOIN CTE_PROCEDIMIENTOS SEC12 ON QX.NUMINGRES=SEC12.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC12.NUMEFOLIO AND SEC12.TIPO=2 AND SEC12.NUMERO=12
LEFT JOIN CTE_PROCEDIMIENTOS SEC13 ON QX.NUMINGRES=SEC13.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC13.NUMEFOLIO AND SEC13.TIPO=2 AND SEC13.NUMERO=13
LEFT JOIN CTE_PROCEDIMIENTOS SEC14 ON QX.NUMINGRES=SEC14.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC14.NUMEFOLIO AND SEC14.TIPO=2 AND SEC14.NUMERO=14
LEFT JOIN CTE_PROCEDIMIENTOS SEC15 ON QX.NUMINGRES=SEC15.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=SEC15.NUMEFOLIO AND SEC15.TIPO=2 AND SEC15.NUMERO=15
LEFT JOIN CTE_CUENTA_PROCEDIMIENTOS CONTAR ON QX.NUMINGRES=CONTAR.NUMINGRES AND QX.[NUMERO FOLIO INFORME]=CONTAR.NUMEFOLIO
LEFT JOIN dbo.INDIAGNOS DIGPRE ON QX.CODDIAPRE=DIGPRE.CODDIAGNO
LEFT JOIN dbo.INDIAGNOS DIGPOS ON QX.CODDIAPOS=DIGPOS.CODDIAGNO
LEFT JOIN CTE_EQUIPO_QX EQUPRI ON QX.NUMINGRES=EQUPRI.NUMINGRES AND EQUPRI.NUMEFOLIO=QX.[NUMERO FOLIO INFORME] AND EQUPRI.QXPRINCIP=1
LEFT JOIN CTE_EQUIPO_QX EQUANE ON QX.NUMINGRES=EQUANE.NUMINGRES AND EQUANE.NUMEFOLIO=QX.[NUMERO FOLIO INFORME] AND EQUANE.TIPOEQUIP=3 AND EQUANE.NUMERO=1
LEFT JOIN CTE_EQUIPO_QX EQUINS ON QX.NUMINGRES=EQUINS.NUMINGRES AND EQUINS.NUMEFOLIO=QX.[NUMERO FOLIO INFORME] AND EQUINS.TIPOEQUIP=4 AND EQUINS.NUMERO=1
LEFT JOIN CTE_EQUIPO_QX EQUAYU ON QX.NUMINGRES=EQUAYU.NUMINGRES AND EQUAYU.NUMEFOLIO=QX.[NUMERO FOLIO INFORME] AND EQUAYU.TIPOEQUIP=2 AND EQUAYU.NUMERO=1
LEFT JOIN CTE_EQUIPO_QX EQUCIR ON QX.NUMINGRES=EQUCIR.NUMINGRES AND EQUCIR.NUMEFOLIO=QX.[NUMERO FOLIO INFORME] AND EQUCIR.TIPOEQUIP=5 AND EQUCIR.NUMERO=1
LEFT JOIN CTE_NOTAS_ADMINISTRATIVAS NOT1 ON QX.NUMINGRES=NOT1.INGRESO AND QX.[CODSERIPS INFORME QX]=NOT1.CODSERIPS AND NOT1.VARIABLE=1
LEFT JOIN CTE_NOTAS_ADMINISTRATIVAS NOT2 ON QX.NUMINGRES=NOT2.INGRESO AND QX.[CODSERIPS INFORME QX]=NOT2.CODSERIPS AND NOT2.VARIABLE=2
LEFT JOIN CTE_NOTAS_ADMINISTRATIVAS NOT3 ON QX.NUMINGRES=NOT3.INGRESO AND QX.[CODSERIPS INFORME QX]=NOT3.CODSERIPS AND NOT3.VARIABLE=3
LEFT JOIN CTE_NOTAS_ADMINISTRATIVAS NOT4 ON QX.NUMINGRES=NOT4.INGRESO AND QX.[CODSERIPS INFORME QX]=NOT4.CODSERIPS AND NOT4.VARIABLE=4
LEFT JOIN CTE_NOTAS_ADMINISTRATIVAS NOT5 ON QX.NUMINGRES=NOT5.INGRESO AND QX.[CODSERIPS INFORME QX]=NOT5.CODSERIPS AND NOT5.VARIABLE=5
LEFT JOIN CTE_NOTAS_ADMINISTRATIVAS NOT6 ON QX.NUMINGRES=NOT6.INGRESO AND QX.[CODSERIPS INFORME QX]=NOT6.CODSERIPS AND NOT6.VARIABLE=6
LEFT JOIN CTE_NOTAS_ADMINISTRATIVAS NOT7 ON QX.NUMINGRES=NOT7.INGRESO AND QX.[CODSERIPS INFORME QX]=NOT7.CODSERIPS AND NOT7.VARIABLE=7
--WHERE CAST(QX.[FECHA BUSQUEDA] AS DATE) BETWEEN '2024-07-01' AND '2024-07-31'
--where qx.NUMINGRES='146927' --and qx.[NUMERO FOLIO INFORME]='61'
--where au.[NUMERO AUTORIZACION] in ('248681127','247487519','248791635')
--order by qx.NUMEFOLIO
--138 VARIABLES
