-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewMipres
-- Extracted by Fabric SQL Extractor SPN v3.9.0




    /*******************************************************************************************************************
Nombre: [Report].[ViewMipres]
Tipo: Vista
Observacion:Detallado de medicamentos no PBS
Profesional: Nilsson Miguel Galindo Lopez
Fecha:30-10-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico:
Fecha:
Observaciones:
-------------------------------------------------------------------------------------------------------------------------------------
Version 3
Persona que modifico:
Fecha:
Observaciones:
***********************************************************************************************************************************/

CREATE VIEW [Report].[ViewMipres] AS

WITH 
CTE_NOPBS AS
(
	SELECT 
	CODPRODUC,
	DESPRODUC,
	NOPOSPROD ,
	ATC.UNIRS  
	FROM 
	IHLISTPRO IHL
	LEFT JOIN Inventory.ATC AS ATC ON ATC.Code =IHL.CODPRODUC 
	WHERE NOPOSPROD='1' OR ATC.UNIRS ='1'
),
---- CTE PARA IDENTIFICAR LOS INGRESOS UNICOS HOSPITALARIOS ACTIVOS
CTE_INGRESOS_UNICOS AS
(
	SELECT 
	ING.NUMINGRES,
	ING.IPCODPACI,
	ING.IESTADOIN
	FROM dbo.ADINGRESO ING
	WHERE ING.TIPOINGRE=2
),
--CTE DE LAS PRESCRIPCIONES REALIZADAS POR PARTE DE LOS PROFESIONALES DE LA SALUD
CTE_SOLICITUDES AS
(
  SELECT 
   D.IPCODPACI,
   D.NUMINGRES,
   PRES.NUMEFOLIO AS [FOLIO ORDEN],
   PRES.CODPRODUC, 
   D.CANPEDPRO AS CANTIDAD,
   NOP.DESPRODUC,
   PRES.FECINIDOS AS FECHAORDE,
   D.FECINIDOS,
   D.ID
   FROM 
   dbo.HCFARMEPD D
   INNER JOIN DBO.HCPRESCRA PRES ON D.IdSourceTable=PRES.ID AND D.SourceTable='HCPRESCRA'
   INNER JOIN CTE_INGRESOS_UNICOS AS ING ON PRES.NUMINGRES=ING.NUMINGRES
   INNER JOIN CTE_NOPBS NOP ON PRES.CODPRODUC=NOP.CODPRODUC 
),

CTE_ENTREGAS AS
(
	SELECT 
	DIS.AdmissionNumber,
	SOL.IPCODPACI,
	ATC.Code,
	PRO.Name, 
	DISD.Quantity AS [CANTIDAD ENTREGADA],
	DIS.Code AS [CODIGO DISPENSACION],
	SOL.ID,
	DDD.Quantity AS DEVOLUCION,
	SOD.RateManualSalePrice AS [VALOR UNITARIO]
	FROM 
	CTE_SOLICITUDES SOL
	INNER JOIN Inventory.PharmaceuticalDispensingDetail DISD ON SOL.ID=DISD.EntityId AND DISD.EntityName='HCFARMEPD'
	INNER JOIN Inventory.PharmaceuticalDispensing DIS ON DISD.PharmaceuticalDispensingId=DIS.Id AND DIS.Status=2
	INNER JOIN Inventory.InventoryProduct PRO ON PRO.Id=DISD.ProductId 
	INNER JOIN Inventory.ATC as atc on ATC.Id =PRO.ATCId AND SOL.CODPRODUC=ATC.Code
	LEFT JOIN Inventory.PharmaceuticalDispensingDetailBatchSerial BAT ON DISD.Id=BAT.PharmaceuticalDispensingDetailId
	LEFT JOIN Inventory.PharmaceuticalDispensingDevolutionDetail DDD ON BAT.Id=DDD.PharmaceuticalDispensingDetailBatchSerialId
	LEFT JOIN Inventory.PharmaceuticalDispensingDevolution DD ON DDD.PharmaceuticalDispensingDevolutionId=DD.Id AND DD.Status=2
	LEFT JOIN Billing.ServiceOrder SO ON DIS.Id=SO.EntityId AND SO.EntityName='PharmaceuticalDispensing'
	LEFT JOIN Billing.ServiceOrderDetail SOD ON SO.Id=SOD.ServiceOrderId AND PRO.Id=SOD.ProductId
	--GROUP BY DIS.AdmissionNumber,SOL.IPCODPACI,ATC.Code,PRO.Name,DIS.Code,SOL.ID
),

CTE_ENTREGAS_TOTAL AS
(
	SELECT 
	AdmissionNumber,
	SUM([CANTIDAD ENTREGADA]) AS [TOTAL DISPENSADO],
	Code
	FROM 
	CTE_ENTREGAS
	GROUP BY AdmissionNumber,Code
),

CTE_NO_POS AS
(
SELECT 
T.NUMINGRES,
T.CODPRODUC, 
SUM(T.CANPEDPRO) AS CANTIDAD,
T.CODMINSALUD
FROM dbo.HCJUNOPOM T
--where NUMINGRES='66068'
GROUP BY T.NUMINGRES,T.CODPRODUC,T.CODMINSALUD
),

CTE_AUTORIZADOS AS
(
SELECT 
A.NUMINGRES 'INGRESO',
D.CODSERIPS AS 'Codigo CUPS', 
CASE ESTATUSER WHEN '1' THEN 'Autorizado'
			   WHEN '2' THEN 'No Autorizado' 
			   WHEN '3' THEN 'Pendiente de Autorizacion' END AS ESTADO,
SUM(D.CANSERAUT) AS 'Cantidad Autorizada'
FROM 
CTE_SOLICITUDES SOL
INNER JOIN dbo.ADAUTSERC A ON SOL.NUMINGRES=A.NUMINGRES
INNER JOIN dbo.SEGusuaru B ON A.CODUSUARI=B.CODUSUARI
INNER JOIN dbo.ADAUTSERD D ON SOL.NUMINGRES=D.NUMINGRES AND A.CODCONCEC=D.CODCONCEC
WHERE ESTATUSER = '1'
GROUP BY A.NUMINGRES,D.CODSERIPS,ESTATUSER
),

--CTE PARA IDENTIFICAR LAS CAMAS ACTIVAS EN HOSPITALIZACION
CTE_CAMAS_OCUPADA AS
(

SELECT DISTINCT 
FUN.UFUDESCRI 'UNIDAD FUNCIONAL' ,
C.IPCODPACI 'IDENTIFICACION' ,
C.NUMINGRES 'INGRESO',
A.NUMCAMHOS 'CAMA',G.DESTIPEST 'TIPO ESTANCIA'  ,C.ID  'ID_ESTANCIA', 
A.CODICAMAS 'ID_CAMAS', CEN.NOMCENATE 'CENTRO DE ATENCION',A.CODCLAHAB ,A.CODCLACAM 
FROM dbo.CHCAMASHO A 
INNER JOIN DBO.INUNIFUNC AS FUN  ON A.UFUCODIGO =FUN.UFUCODIGO 
INNER JOIN dbo.CHREGESTA C  ON A.CODICAMAS=C.CODICAMAS AND C.REGESTADO = 1 
INNER JOIN dbo.CHTIPESTA G  ON G.CODTIPEST=C.CODTIPEST 
INNER JOIN DBO.ADCENATEN AS CEN  ON CEN.CODCENATE =A.CODCENATE 
INNER JOIN CTE_INGRESOS_UNICOS AS ING  ON ING.NUMINGRES =C.NUMINGRES 
)
 
SELECT TOP 100 PERCENT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CEN.NOMCENATE AS [CENTRO DE ATENCION],
DOC.NOMBRE AS [TIPO IDENTIFICACION],
SOL.IPCODPACI AS IDENTIFICACION,
PAC.IPNOMCOMP AS PACIENTE,
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END AS[GENERO DEL PACIENTE],
CAST(PAC.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
CASE ING.CODTIPPAC WHEN '1' THEN 'Maternas' 
				   WHEN '2' THEN 'Pediatrico'
				   WHEN '3' THEN 'Población general' 
				   WHEN '4' THEN 'Adulto mayor' 
				   WHEN '5' THEN 'Población general' END AS [TIPO DE PACIENTE], 
DATEDIFF(YEAR,PAC.IPFECNACI,ING.IFECHAING)-(CASE WHEN DATEADD(YY,DATEDIFF(YEAR,IPFECNACI,ING.IFECHAING),IPFECNACI)>ING.IFECHAING THEN 1 ELSE 0 END) AS EDAD,
HA.Code+' - '+HA.NAME AS ENTIDAD, 
CG.Name AS [GRUPO DE ATENCION],
SOL.NUMINGRES AS INGRESO,
SOL.[FOLIO ORDEN],
CAST(SOL.FECHAORDE AS DATE) AS [FECHA DE LA ORDEN],
SOL.CODPRODUC AS [CODIGO MEDICAMENTO SOLICITADO],
SOL.DESPRODUC AS [MEDICAMENTO SOLICITADO],
SOL.CANTIDAD AS [CANTIDAD SOLICITADA],
NPBS1.CANTIDAD AS [CANTIDAD JUSTIFICADA] ,
NPBS1.CODMINSALUD AS [CODIGO MIPRES],
ISNULL(AUT.[Cantidad Autorizada],0) AS [CANTIDAD AUTORIZADA],
AUT.ESTADO AS [ESTADO AUTORIZACION],
ENT.[CODIGO DISPENSACION],
ISNULL(ENT.[CANTIDAD ENTREGADA],0) AS [CANTIDAD DISPENSADA],
TOL.[TOTAL DISPENSADO],
ING.IESTADOIN AS [ESTADO INGRESO],
ISNULL(AUT.[Cantidad Autorizada],0)-ISNULL(ENT.[CANTIDAD ENTREGADA],0) [AUTORIZADA VS ENTREGADA],
ISNULL(CAM.CAMA,' ') AS [CAMA HOSPITALIZACION],
ISNULL(CAM.[UNIDAD FUNCIONAL],'') AS [UNIDAD FUNCIONAL],
ENT.DEVOLUCION,
ENT.[VALOR UNITARIO],
CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
CAST(ing.FECHEGRESO AS DATE) 'FECHA EGRESO',
CAST(SOL.FECHAORDE AS date) AS 'FECHA BUSQUEDA',
YEAR(SOL.FECHAORDE) AS 'AÑO FECHA BUSQUEDA',
MONTH(SOL.FECHAORDE) AS 'MES FECHA BUSQUEDA',
CASE MONTH(SOL.FECHAORDE) WHEN 1 THEN 'ENERO'
						  WHEN 2 THEN 'FEBRERO'
						  WHEN 3 THEN 'MARZO'
						  WHEN 4 THEN 'ABRIL'
						  WHEN 5 THEN 'MAYO'
						  WHEN 6 THEN 'JUNIO'
						  WHEN 7 THEN 'JULIO'
						  WHEN 8 THEN 'AGOSTO'
						  WHEN 9 THEN 'SEPTIEMBRE'
						  WHEN 10 THEN 'OCTUBRE'
						  WHEN 11 THEN 'NOVIEMBRE'
						  WHEN 12 THEN 'DICIEMBRE'  END AS 'MES NOMBRE FECHA BUSQUEDA', 
  FORMAT(DAY(SOL.FECHAORDE), '00') AS 'DIA FECHA BUSQUEDA',
  CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM CTE_SOLICITUDES SOL
INNER JOIN CTE_ENTREGAS ENT ON SOL.ID=ENT.ID
INNER JOIN CTE_ENTREGAS_TOTAL TOL ON SOL.NUMINGRES=TOL.AdmissionNumber AND SOL.CODPRODUC=TOL.Code
INNER JOIN INPACIENT PAC ON PAC.IPCODPACI=SOL.IPCODPACI
INNER JOIN dbo.ADTIPOIDENTIFICA DOC ON PAC.IPTIPODOC=DOC.CODIGO
INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES =SOL.NUMINGRES 
INNER JOIN dbo.ADCENATEN CEN ON ING.CODCENATE=CEN.CODCENATE 
INNER JOIN Contract .HealthAdministrator AS HA ON ING.GENCONENTITY=HA.Id
INNER JOIN Contract.CareGroup CG ON ING.GENCAREGROUP=CG.Code
INNER JOIN CTE_NO_POS NPBS1 ON NPBS1.NUMINGRES=SOL.NUMINGRES AND NPBS1.CODPRODUC=SOL.CODPRODUC 
LEFT JOIN CTE_AUTORIZADOS AUT ON AUT.INGRESO =SOL.NUMINGRES AND AUT.[Codigo CUPS] =SOL.CODPRODUC 
LEFT JOIN CTE_CAMAS_OCUPADA AS CAM ON CAM.INGRESO=SOL.NUMINGRES
--WHERE PAC.IPCODPACI='46356349'
ORDER BY SOL.NUMINGRES
