-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewProductividadSala
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE VIEW [Report].[ViewProductividadSala] AS

SELECT DISTINCT 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
HC.IPCODPACI AS PACIENTE_DOCUMENTO_IDENTIFICACION,
HC.NUMINGRES AS PACIENTE_NUMERO_INGRESO,
HC.CODDIAPRE AS DIAGNOSTICO_PREVIO,
HC.CODDIAPOS AS DIAGNOSTICO_POSTERIOR,
HC.SALACIRUG AS SALA_CIRUGIA,
UPPER(HC.DESPROCED) AS DESCRIPCION_PROCEDIMIENTO,
CASE HC.TIPOANEST
WHEN '1' THEN 'LOCAL' 
WHEN '2' THEN 'REGIONAL' 
WHEN '3' THEN 'GENERAL' 
WHEN '4' THEN 'COMBINADA' 
WHEN '5' THEN 'NO APLICA'
ELSE 'DESCONOCIDO' END AS TIPO_ANESTESIA,
	CASE HC.TIPHERCIR
	WHEN '1' THEN 'LIMPIA' 
	WHEN '2' THEN 'LIMPIA CONTAMINADA'
	WHEN '3' THEN 'CONTAMINADA'
	WHEN '4' THEN 'SUCIA E INFECTADA'
	WHEN '5' THEN 'SUCIA'
	WHEN '6' THEN 'INFECTADA'
	WHEN '7' THEN 'NO APLICA'
	ELSE 'DESCONOCIDO' END AS TIPO_HERIDA,
	IC.DESSERIPS AS PROCEDIMIENTO_REALIZADO,
	IC.CODSERIPS AS PROCEDIMIENTO_REALIZADO_CODIGO,
	CASE IC.PRESERIPS
	WHEN '1' THEN 'NO QUIRURGICO' 
	WHEN '2' THEN 'QUIRURGICO'
	WHEN '3' THEN 'PAQUETE'
	ELSE 'DESCONOCIDO' END AS PRESENTACION_SERVICIO,
		CASE IC.TIPSERIPS
		 WHEN '1' THEN 'LABORATORIOS' 
		 WHEN '2' THEN 'PATOLOGIAS' 
		 WHEN '3' THEN 'IMAGENES DIAGNOSTICAS' 
		 WHEN '4' THEN 'PROCEDIMIENTOS NO QX' 
		 WHEN '5' THEN 'PROCEDIMIENTOS QX' 
		 WHEN '6' THEN 'INTERCONSULTAS' 
		 WHEN '7' THEN 'NINGUNO' 
		 WHEN '8' THEN 'CONSULTA EXTERNA'
		 ELSE 'DESCONOCIDO' END AS TIPO_SERVICIO,
			CASE IC.CLASERIPS  
			WHEN '1' THEN 'NINGUNO'
			WHEN '2' THEN 'CIRUJANO'
			WHEN '3' THEN 'ANESTESIOLOGO'
			WHEN '4' THEN 'AYUDANTE'
			WHEN '5' THEN 'DERECHO_SALA'
			WHEN '6' THEN 'MATERIALES_SUTURA'
			WHEN '7' THEN 'INSTRUMENTACION_QUIRURGICA'
			ELSE 'DESCONOCIDO' END AS CLASE_SERVICIO,
P.IPNOMCOMP    AS PACIENTE_NOMBRE_COMPLETO,
P.AUUBICACI    AS PACIENTE_UBICACION_GEOGRAFICA,
P.IPFECNACI    AS FECHA_NACIMIENTO,
P.GENCONENTITY AS ENTIDAD_RESPONSABLE_PAGO,
DI.NOMDIAGNO   AS NOMBRE_DIAGNOSTICO_PREVIO,
DF.NOMDIAGNO   AS NOMBRE_DIAGNOSTICO_POSTERIOR,
UF.UFUDESCRI   AS UNIDAD_FUNCIONAL,
PS.NOMMEDICO   AS PROFESIONAL_SALUD,
PS.CODPROSAL   AS PROFESIONAL_SALUD_CODIGO,
CASE WHEN IA1.DESESPECI IS NULL THEN 'NO APLICA' ELSE  IA1.DESESPECI END AS PROFESIONAL_SALUD_ESPECIALIDAD_PRNICIPAL,
CASE WHEN IA2.DESESPECI IS NULL THEN 'NO APLICA' ELSE  IA2.DESESPECI END AS PROFESIONAL_SALUD_ESPECIALIDAD_2,
CASE WHEN IA3.DESESPECI IS NULL THEN 'NO APLICA' ELSE  IA3.DESESPECI END AS PROFESIONAL_SALUD_ESPECIALIDAD_3,
IC.CODSERIPS   AS CODIGO_PROCEDIMIENTO,
HC.FECHORINI AS FECHA_HORA_INICIAL,
HC.FECHORFIN AS FECHA_HORA_FINAL,
1 as 'CANTIDAD',
CAST(HC.FECHORINI AS date) AS 'FECHA BUSQUEDA',
YEAR(HC.FECHORINI) AS 'AÑO FECHA BUSQUEDA',
MONTH(HC.FECHORINI) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(HC.FECHORINI) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
  END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(HC.FECHORINI), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(HC.FECHORINI), '00') ,' - ', 
	   CASE MONTH(HC.FECHORINI) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM DBO.HCQXINFOR HC  WITH (NOLOCK)
LEFT JOIN DBO.INPACIENT P  WITH (NOLOCK) ON HC.IPCODPACI=P.IPCODPACI
LEFT JOIN DBO.INDIAGNOS DI WITH (NOLOCK) ON HC.CODDIAPRE=DI.CODDIAGNO 
LEFT JOIN DBO.INDIAGNOS DF WITH (NOLOCK) ON HC.CODDIAPOS=DF.CODDIAGNO 
LEFT JOIN DBO.INUNIFUNC UF WITH (NOLOCK) ON HC.UFUCODIGO=UF.UFUCODIGO
LEFT JOIN DBO.INPROFSAL PS WITH (NOLOCK) ON HC.CODPROSAL=PS.CODPROSAL
LEFT JOIN DBO.INCUPSIPS IC WITH (NOLOCK) ON HC.CODSERIPS=IC.CODSERIPS
LEFT JOIN DBO.INESPECIA IA1 WITH (NOLOCK) ON PS.CODESPEC1=IA1.CODESPECI 
LEFT JOIN DBO.INESPECIA IA2 WITH (NOLOCK) ON PS.CODESPEC2=IA2.CODESPECI 
LEFT JOIN DBO.INESPECIA IA3 WITH (NOLOCK) ON PS.CODESPEC3=IA3.CODESPECI 
