-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_IND_ORDENES_QUIMIOTERAPIA
-- Extracted by Fabric SQL Extractor SPN v3.9.0






CREATE VIEW [Report].[View_IND_ORDENES_QUIMIOTERAPIA]
AS

WITH CTE_ORDENS_QUIMIO
AS
(
  SELECT CAST(QUI.FECHAREGISTRO AS DATE) 'FECHA ORDEN',CAST(ISNULL(QUI.FECHAFINALIZA,ISNULL(QUI.FECHAANULACION,QUI.FECHAREGISTRO )) AS DATE) 'FECHA ANULACION',
  ESQ.Code 'CODIGO ESQUEMA' ,ESQ.Description 'ESQUEMA', QUI.IPCODPACI IDENTIFICACION,PAC.IPNOMCOMP 'PACIENTE', QUI.NUMINGRES 'INGRESO',
  CASE QUI.ESTADO WHEN 1 THEN 'Orden Solicitada' WHEN 2 THEN 'Esquema iniciado' WHEN 3 THEN 'Esquema finalizado completo'
  WHEN 4 THEN 'Suspendido - Finalización prematura' WHEN 5 THEN 'Anulado' END 'ESTADO',
  IIF(MOTIVOFINALIZAR IS NOT NULL,CASE MOTIVOFINALIZAR WHEN 1 THEN 'TOXICIDAD' WHEN 2 THEN 'MOTIVO MEDICO' WHEN 3 THEN 'MUERTE DEL PACIENTE' WHEN 4 THEN 'CAMBIO EPS'
       WHEN 5 THEN 'USUARIO' WHEN 6 THEN 'NO DISPONIBILIDAD MEDICAMENTO' WHEN 7 THEN 'ADMINISTRATIVOS' WHEN 8 THEN 'OTROS MOTIVOS' ELSE 'OTROS MOTIVOS' END,
	     IIF(QUI.IDHCMOANULB IS NOT NULL,ANU1.DESMOTANU,ANU2.DESMOTANU)) 'MOTIVO DE ANULACION/SUSPENSION',QUI.[46] 'NRO FASES',CASE FASEQUIMIOTERAPIA 
		 WHEN '1' THEN 'Prefase o citorreducción inicial' WHEN '2' THEN 'Inducción' WHEN '3' THEN 'Intensificación' WHEN '4' THEN 'Consolidación'
         WHEN '5' THEN 'Reinducción' WHEN '6' THEN 'Mantenimiento' WHEN '7' THEN 'Mantenimiento largo o final' WHEN '8' THEN 'Otra Fase' END 'FASE ACTUAL',
		 CASE QUI.[48]  WHEN '1' THEN 'Neoadyuvancia (manejo  inicial prequirúrgico)'WHEN '2' THEN 'Tratamiento inicial curativo sin cirugía sugerida'
        WHEN '3' THEN 'Adyuvancia(manejo inicial postquirúrgico)'WHEN '4' THEN 'Manejo paliativo inicial'WHEN '5' THEN 'Manejo curativo de primera recaída'
        WHEN '6' THEN 'Manejo paliativo de primera recaída'WHEN '7' THEN 'Manejo curativo de segunda recaída'WHEN '8' THEN 'Manejo paliativo de segunda recaída'
        WHEN '9' THEN 'Manejo curativo de tercera recaída o posterior'WHEN '10' THEN 'Manejo paliativo de tercera recaída o posterior' END  'UBICACION TEMPORAL',
		QUI.CODDIAGNO 'CIE10', DIA.NOMDIAGNO 'DIAGNOSTICO',FUN.UFUCODIGO 'CODIGO UNIDAD FUNCIONAL',FUN.UFUDESCRI 'UNIDAD FUNCIONAL',HA.Name 'ENTIDAD',
		CG.Code 'CODIGO GRUPO ATENCION', CG.Name 'GRUPO DE ATENCION',CASE HA.EntityType WHEN 1  THEN 'EPS Contributivo'
WHEN '2' THEN 'EPS Subsidiado'WHEN '3' THEN 'ET Vinculados Municipios'WHEN '4' THEN 'ET Vinculados Departamentos'WHEN '5' THEN 'ARL Riesgos Laborales'
WHEN '6' THEN 'MP Medicina Prepagada'WHEN '7' THEN 'IPS Privada'WHEN '8' THEN 'IPS Publica'WHEN '9' THEN 'Regimen Especial'WHEN '10'THEN 'Accidentes de transito'
WHEN '11'THEN 'Fosyga'WHEN '12'THEN 'Otros' END 'REGIMEN'
  FROM EHR.HCORDQUIMIO QUI
  INNER JOIN EHR.Schemes ESQ ON ESQ.Id=QUI.SchemesId
  INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =QUI.IPCODPACI
  INNER JOIN DBO.ADINGRESO AS ING ON QUI.NUMINGRES =ING.NUMINGRES 
  INNER JOIN Contract .HealthAdministrator AS HA ON HA.Id =ING.GENCONENTITY
  INNER JOIN Contract .CareGroup CG ON CG.Id =ING.GENCAREGROUP 
  LEFT JOIN HCMOANULB ANU1 ON ANU1.CODMOTANU=QUI.IDHCMOANULB
  LEFT JOIN HCMOANULB ANU2 ON ANU2.CODMOTANU=QUI.IDHCMOANULB_SUSP 
  LEFT JOIN DBO.INDIAGNOS AS DIA ON DIA.CODDIAGNO =QUI.CODDIAGNO 
  LEFT JOIN DBO.INUNIFUNC AS FUN ON FUN.UFUCODIGO =QUI.UFUCODIGO 
)

SELECT 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, *,
 1 as 'CANTIDAD',
 CAST([FECHA ORDEN] AS date) AS 'FECHA BUSQUEDA',
 YEAR([FECHA ORDEN]) AS 'AÑO BUSQUEDA',
 MONTH([FECHA ORDEN]) AS 'MES BUSQUEDA',
 CONCAT(FORMAT(MONTH([FECHA ORDEN]), '00') ,' - ', 
	   CASE MONTH([FECHA ORDEN]) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
 
FROM CTE_ORDENS_QUIMIO
