-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_IND_V2_CUBO_ATENCION_URGENCIAS_DIA_ACTUAL
-- Extracted by Fabric SQL Extractor SPN v3.9.0












/*******************************************************************************************************************
Nombre: [Report].[View_IND_V2_CUBO_ATENCION_URGENCIAS_DIA_ACTUAL]
Tipo:Procedimiento Vista
Observacion:Informe sobre la oportunidad y clasificación del triage.
Profesional:Andres cabrera
Fecha:
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico:Nilsson Miguel Galindo
Fecha:13-07-2023
Observaciones:Se unifica la logica de la vista View_IND_V2_CUBO_ATENCION_URGENCIAS_DIA_ACTUAL con la vista ViewReporteTriages
--------------------------------------
Version 3
Persona que modifico: Nelly P Morales C
Fecha: 21/07/23
Observaciones: Se renombran los campos
--------------------------------------
Version 4
Persona que modifico:Nilsson Galindo 
Fecha: 11/08/23
Observaciones: Se crean los CTE CTE_TRIAGE_UNICO_POR_ATENCIÓN y CTE_HCURGING1 para quitar los duplicados y mejorar las velocidades.
--------------------------------------
Version 5
Persona que modifico:Nilsson Galindo 
Fecha: 15-01-2023
Observaciones:Se restribuye las columnas en orden segun la atencion para la clasificación de triage
			  Se eliminan columnas OPORTUNIDAD FL vs FT (MIN), OPORTUNIDAD FT vs FA (MIN), OPORTUNIDAD FL vs FA (MIN)
			  Las columnas con respecto a los reingresos con logica de la vista [Report].[ViewReingresos]
			  La columna de fecha de egreso se divide en fecha de alta medica y fecha de egreso
			  Y SE AGREGA CODIGO DE LA EPS
***********************************************************************************************************************************/
CREATE VIEW [Report].[View_IND_V2_CUBO_ATENCION_URGENCIAS_DIA_ACTUAL] AS

WITH CTE_MUERTOS AS
 (
  SELECT
   HIS.NUMINGRES 'INGRESO',
   HIS.ID, 
   EGR.FECMUEPAC 'FECHA MUERTE'
  FROM 
   DBO.HCHISPACA HIS --Se almacena toda la informacion de atencion a nivel clinico
   INNER JOIN DBO.HCREGEGRE AS EGR ON HIS.NUMINGRES=EGR.NUMINGRES AND HIS.NUMEFOLIO=EGR.NUMEFOLIO --Se almacenan los egresos
   INNER JOIN DBO.INUNIFUNC AS FUN ON EGR.UFUCODIGO=FUN.UFUCODIGO -- Se almacena las unidades funcionales
  WHERE 
   HIS.INDICAPAC =11 AND FUN.UFUTIPUNI ='1' AND CAST(HIS.FECHISPAC AS DATE)=CAST(GETDATE()AS DATE)
 ),

---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
CTE_ORDENES_CON_ESTANCIA_RECONOCIDAS AS
 ( 
	SELECT 
	RC.AdmissionNumber
	FROM 
	BILLING.REVENUECONTROL AS RC INNER JOIN
	Billing.RevenueControlDetail AS RCD ON RC.ID=RCD.REVENUECONTROLID INNER JOIN 
	Billing.SERVICEORDERDETAILDISTRIBUTION AS SODD ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2', '3') INNER JOIN 
	BILLING.SERVICEORDERDETAIL AS SOD  ON SODD.SERVICEORDERDETAILID = SOD.ID INNER JOIN 
	Contract .CUPSEntity AS CUPS  ON SOD.CUPSEntityId=CUPS.Id AND CUPS.BillingGroupId IN (2)
	WHERE
	CUPS.Code IN ('890701','890702','890703','890704') AND CAST(SOD.ServiceDate AS DATE)=CAST(GETDATE()AS DATE)
	GROUP BY RC.AdmissionNumber
),

---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
CTE_ORDENES_CON_ESTANCIAS_CARGADAS AS
 ( 
  SELECT 
   RC.AdmissionNumber,
   G.[CONSULTA DE URGENCIAS POR MEDICINA GENERAL],
   G.[CONSULTA DE URGENCIAS POR OTRAS ESPECIALIDADES MEDICAS],
   G.[CONSULTA DE URGENCIAS POR ODONTOLOGIA GENERAL],
   G.[CONSULTA DE URGENCIAS POR ODONTOLOGIA ESPECIALIZADA] 
  FROM 
   BILLING.REVENUECONTROL AS RC 
   INNER JOIN (SELECT 
                *
               FROM
			    (SELECT
				  RC.AdmissionNumber,
				  CUPS.Code CUPS,
				  CUPS.Description 'DESCRIPCION CUPS' 
				 FROM 
				  Billing.RevenueControlDetail AS RCD 
				  INNER JOIN BILLING.REVENUECONTROL AS RC  ON RCD.REVENUECONTROLID = RC.ID
				  INNER JOIN Billing.SERVICEORDERDETAILDISTRIBUTION AS SODD  ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2', '3')
				  INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD  ON SODD.SERVICEORDERDETAILID = SOD.ID
				  INNER JOIN Contract .CUPSEntity AS CUPS  ON CUPS.Id =SOD.CUPSEntityId AND CUPS.BillingGroupId IN  (2)
				  INNER JOIN Contract .IPSService AS IPS  ON IPS.Id =SOD.IPSServiceId

				 WHERE 
				  CUPS.Code IN ('890701','890702','890703','890704') AND CAST(SOD.ServiceDate AS DATE)=CAST(GETDATE()AS DATE)
				 GROUP BY 
				  RC.AdmissionNumber,
				  CUPS.Code,
				  CUPS.Description) AS SourceTable
				 PIVOT (MAX([CUPS])
				 FOR [DESCRIPCION CUPS] In ([CONSULTA DE URGENCIAS POR MEDICINA GENERAL], 
				                            [CONSULTA DE URGENCIAS POR OTRAS ESPECIALIDADES MEDICAS], 
											[CONSULTA DE URGENCIAS POR ODONTOLOGIA GENERAL],
											[CONSULTA DE URGENCIAS POR ODONTOLOGIA ESPECIALIZADA]))AS PVTTABLE) AS G ON G.AdmissionNumber = RC.AdmissionNumber
 ),

----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
CTE_ULTIMA_CAMAS_OCUPADA_OBSERVACION AS
 (
  SELECT 
   EGR.NUMINGRES,
   CAM.NUMCAMHOS 'CAMA OBSERVACION'
  FROM 
   CHREGESTA EGR 
   INNER JOIN (
   SELECT
	EGR.IPCODPACI,
	EGR.NUMINGRES,
	MAX(EGR.ID) ID  
	FROM 
	CHREGESTA EGR 
	INNER JOIN CHCAMASHO AS CAM  ON EGR.CODICAMAS=CAM.CODICAMAS
	INNER JOIN DBO.INUNIFUNC AS FUN  ON CAM.UFUCODIGO =FUN.UFUCODIGO
	WHERE 
	FUN.UFUTIPUNI ='1' AND CAST(EGR.FECREGSIS AS DATE)=CAST(GETDATE() AS DATE)
	GROUP BY EGR.IPCODPACI,	EGR.NUMINGRES) AS G  ON G.ID =EGR.ID
   INNER JOIN CHCAMASHO AS CAM  ON CAM.CODICAMAS =EGR.CODICAMAS 
   INNER JOIN DBO.INUNIFUNC AS FUN  ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),

----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
CTE_ULTIMA_CAMAS_OCUPADA_HOSPITALIZACION AS
 (
  SELECT 
   EGR.NUMINGRES,
   CAM.NUMCAMHOS 'CAMA HOSPITALIZACION'
  FROM 
   CHREGESTA EGR 
   INNER JOIN (SELECT 
                EGR.IPCODPACI,
				EGR.NUMINGRES,MAX(EGR.ID) ID  
			   FROM 
			    CHREGESTA EGR 
			    INNER JOIN CHCAMASHO AS CAM  ON CAM.CODICAMAS =EGR.CODICAMAS
				INNER JOIN DBO.INUNIFUNC AS FUN  ON CAM.UFUCODIGO =FUN.UFUCODIGO
			   WHERE 
			    FUN.UFUTIPUNI <>'1' AND CAST(EGR.FECREGSIS AS DATE)=CAST(GETDATE() AS DATE)
			   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G  ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM  ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN  ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),

---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
CTE_ORDENES_CON_SALAS_CARGADAS AS
 ( 
  SELECT 
   RC.AdmissionNumber,
   G.[INTERNACION COMPLEJIDAD ALTA CUATRO O MAS CAMAS],
   G.[DERECHOS DE SALA DE OBSERVACION EN URGENCIAS COMPLEJIDAD ALTA]
  FROM 
   BILLING.REVENUECONTROL AS RC 
   INNER JOIN (SELECT 
                * 
			   FROM 
			    (SELECT RC.AdmissionNumber ,CUPS.Code CUPS,CUPS.Description 'DESCRIPCION CUPS' 
				 FROM 
				  Billing .RevenueControlDetail AS RCD 
				  INNER JOIN BILLING.REVENUECONTROL AS RC  ON RCD.REVENUECONTROLID = RC.ID
				  INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD  ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2', '3')
				  INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD  ON SODD.SERVICEORDERDETAILID = SOD.ID
				  INNER JOIN Contract .CUPSEntity AS CUPS  ON CUPS.Id =SOD.CUPSEntityId AND CUPS.BillingGroupId IN  (7,8)
				  INNER JOIN Contract .IPSService AS IPS  ON IPS.Id =SOD.IPSServiceId
				 WHERE 
				  CUPS.Code IN ('10A004','5DSA01') AND CAST(SOD.ServiceDate AS DATE)=CAST(GETDATE()AS DATE)
				 GROUP BY 
				  RC.AdmissionNumber ,CUPS.Code ,CUPS.Description) AS SourceTable
				 PIVOT  (MAX([CUPS])
				 FOR [DESCRIPCION CUPS] In ([INTERNACION COMPLEJIDAD ALTA CUATRO O MAS CAMAS],[DERECHOS DE SALA DE OBSERVACION EN URGENCIAS COMPLEJIDAD ALTA]))
				 AS PVTTABLE) AS G ON G.AdmissionNumber =RC.AdmissionNumber
),

---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
CTE_ORDENES_CON_SALA_RECONOCIDAS AS
 ( 
  SELECT 
   RC.AdmissionNumber
  FROM 
   BILLING.REVENUECONTROL AS RC 
   INNER JOIN (SELECT
                RC.AdmissionNumber 
			   FROM 
			    Billing .RevenueControlDetail AS RCD 
			    INNER JOIN BILLING.REVENUECONTROL AS RC  ON RCD.REVENUECONTROLID = RC.ID
				INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD  ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2', '3')
				INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD  ON SODD.SERVICEORDERDETAILID = SOD.ID
				INNER JOIN Contract .CUPSEntity AS CUPS  ON CUPS.Id =SOD.CUPSEntityId AND CUPS.BillingGroupId IN  (7,8)
			   WHERE 
			    CUPS.Code IN ('10A004','5DSA01') AND CAST(SOD.ServiceDate AS DATE)=CAST(GETDATE()AS DATE)
  GROUP BY RC.AdmissionNumber) AS G ON G.AdmissionNumber =RC.AdmissionNumber
 ),
--TODAS LAS ATENCIONES CON UNA CLASIFICACIÓN DE TRIAGE
CTE_TRIAGE_UNICO_POR_ATENCIÓN AS
 (
 SELECT
 A.IPCODPACI,A.CODCENATE,A.CODPROSAL,A.TRIANUMER,A.TRIACATEG,A.NUMINGRES,A.ID,A.TRIAFECHA,
 IIF(A.TRIAGECLA<=5,A.TRIAGECLA,NULL) AS TRIAGECLA,U.UFUCODIGO
 FROM dbo.ADTRIAGEU A
 LEFT JOIN dbo.ADCONTURG U ON A.TRIANUMER=U.CODCONCEC 
 WHERE A.ID=(SELECT MAX(B.ID) FROM dbo.ADTRIAGEU B WHERE A.TRIANUMER=B.TRIANUMER AND CAST(A.TRIAFECHA AS DATE) = CAST(GETDATE() AS DATE)) 
 ),

CTE_HCURGING1 AS
(
SELECT
K.NUMINGRES,K.NUMEFOLIO,K.CODPROSAL,K.UFUCODIGO,K.FECHINIHI,K.FECHFINH,K.INDICAPAC
FROM 
dbo.HCURGING1 k WHERE K.NUMEFOLIO=(SELECT MIN(CAST(FOL.NUMEFOLIO AS INT)) FROM dbo.HCURGING1 FOL WHERE K.NUMINGRES=FOL.NUMINGRES) --AND k.UFUCODIGO = C.UFUCODIGO 
),
-------------------------------------REINGRESOS-----------------------------------------
CTE_REINGRESOS AS
(
SELECT REING.[NUMERO INGRESO A],REING.[NUMERO INGRESO B] FROM 
CTE_TRIAGE_UNICO_POR_ATENCIÓN A
INNER JOIN [Report].[ViewReingresos] REING ON A.NUMINGRES=REING.[NUMERO INGRESO A]

)

SELECT
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 CEN.NOMCENATE AS [CENTRO DE ATENCIÓN],
 CASE U.IPTIPODOC WHEN 1 THEN 'CC'  				  
				 WHEN 2 THEN 'CE'  				  
				 WHEN 3 THEN 'TI'  				  
				 WHEN 4 THEN 'RC'  				  
				 WHEN 5 THEN 'PA'  				  
				 WHEN 6 THEN 'AS'  				  
				 WHEN 7 THEN 'MS'  				  
				 WHEN 8 THEN 'NU' 				  
				 WHEN 9 THEN 'CN'  				  
				 WHEN 10 THEN 'CD'  				  
				 WHEN 11 THEN 'SC'				  
				 WHEN 12 THEN 'PE'  				 
				 WHEN 13 THEN 'PT'				  
				 WHEN 14 THEN 'DE'				  
				 WHEN 20 THEN 'OT' END AS [TIPO DOCUMENTO], 
 A.IPCODPACI AS [IDENTIFICACION],
 U.IPPRIAPEL AS [PRIMER APELLIDO],
 U.IPSEGAPEL AS [SEGUNDO APELLIDO],
 U.IPPRINOMB AS [PRIMER NOMBRE],
 U.IPSEGNOMB AS [SEGUNDO NOMBRE], 
 U.IPNOMCOMP AS [PACIENTE NOMBRE COMPLETO],
 CASE WHEN U.IPSEXOPAC = '1' THEN 'M' WHEN U.IPSEXOPAC = '2' THEN 'F' END AS SEXO, 
 CAST(U.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
 U.IPTELEFON AS TELEFONO, 
 U.IPTELMOVI AS MOVIL,
 CASE WHEN (DATEADD(year,DATEDIFF(year, U.IPFECNACI, ISNULL(C.IPFECLLEGA ,ISNULL(I.IFECHAING ,A.TRIAFECHA))), U.IPFECNACI) > ISNULL(C.IPFECLLEGA ,ISNULL(I.IFECHAING ,A.TRIAFECHA)))
  THEN DATEDIFF(year, U.IPFECNACI  ,ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA))) -1
  ELSE DATEDIFF(year, U.IPFECNACI  ,ISNULL(C.IPFECLLEGA, ISNULL(I.IFECHAING, A.TRIAFECHA))) END AS EDAD,
 HA.HealthEntityCode AS [CODIGO EPS/ENTIDAD TERRITORIAL],
 RTRIM(HA.Name) 'ENTIDAD',
 RTRIM(E.Code) 'CODIGO GRUPO ATENCION',
 RTRIM(E.Name) 'GRUPO ATENCION',
  CASE HA.EntityType  WHEN '1'  THEN 'EPS Contributivo'
					 WHEN '2'  THEN 'EPS Subsidiado'
					 WHEN '3'  THEN 'ET Vinculados Municipios'
					 WHEN '4'  THEN 'ET Vinculados Departamentos'
					 WHEN '5'  THEN 'ARL Riesgos Laborales'
					 WHEN '6'  THEN 'MP Medicina Prepagada'
					 WHEN '7'  THEN 'IPS Privada'
					 WHEN '8'  THEN 'IPS Publica'
					 WHEN '9'  THEN 'Regimen Especial'
					 WHEN '10' THEN 'Accidentes de transito'
					 WHEN '11' THEN 'Fosyga'
					 WHEN '12' THEN 'Otros' 
					 WHEN '13' THEN 'Aseguradoras' END AS REGIMEN,
 GRU.NAME AS [TIPO PACIENTE],
 ISNULL(C.IPFECLLEGA ,ISNULL(I.IFECHAING ,A.TRIAFECHA)) [FECHA LLEGADA],
 IIF(A.TRIAFECHA IS NULL,'NO','SI') 'ATENDIDO TRIAGE',
 A.TRIAFECHA AS 'FECHA TRIAGE',
 rtrim(convert(char(8), A.TRIAFECHA, 108)) [HORA TRIAGE], 
  IIF(C.IPFECLLEGA IS NULL,0,DATEDIFF(MINUTE,C.IPFECLLEGA, A.TRIAFECHA)) AS [MINUTOS ESPERA LLEGADA VS TRIAGE],--OPORTUNIDAD FL vs FT (MIN)
 IIF(convert(char(8), A.TRIAFECHA, 108) BETWEEN '07:00:00' AND '12:59:59','MAÑANA',
     IIF(convert(char(8), A.TRIAFECHA, 108) BETWEEN '13:00:00' AND '18:59:59','TARDE',
	    IIF(((convert(char(8), A.TRIAFECHA, 108) BETWEEN '19:00:00' AND '23:59:99') OR (convert(char(8), A.TRIAFECHA, 108) BETWEEN '00:00:00' AND '06:59:99')) AND 
		DAY(A.TRIAFECHA)%2=0,'NOCHE DÍA PAR',
 IIF(((convert(char(8), A.TRIAFECHA, 108) BETWEEN '19:00:00' AND '23:59:99')OR(convert(char(8), A.TRIAFECHA, 108) BETWEEN '00:00:00' AND '06:59:99')) AND DAY(A.TRIAFECHA)%2=1,'NOCHE DÍA IMPAR','')))) [JORNADA],
 A.TRIAGECLA AS [CLASIFICACION TRIAGE #],
 CASE A.TRIAGECLA  WHEN 1 THEN 'I' 
				   WHEN 2 THEN 'II'
				   WHEN 3 THEN 'III'
				   WHEN 4 THEN 'IV' 
				   WHEN 5 THEN 'V' END AS [CLASIFICACION TRIAGE],
 C.OBVAUSENT AS [OBSERVACION AUSENCIA TRIAGE],
 A.CODPROSAL AS [DOCUMENTO PROFESIONAL TRIAGE],
 P.NOMMEDICO AS [PROFESIONAL TRIAGE],
 ES.DESESPECI AS [ESPECIALIDAD PROFESIONAL TRIAGE],
 IIF(k.FECHINIHI IS NULL OR HC.FECHISPAC IS NULL,'NO','SI') AS [ATENDIDO CONSULTA],
 A.NUMINGRES AS INGRESO,
 CASE I.IESTADOIN WHEN ' ' THEN 'Abierto' 
				  WHEN 'F' THEN 'Facturado' 
				  WHEN 'C' THEN 'Cerrado' 
				  WHEN 'A' THEN 'Anulado' 
				  WHEN 'P' THEN 'Parcial' 
				  WHEN 'B' THEN 'Bloqueado' END AS [ESTADO INGRESO],
 CASE I.IINGREPOR WHEN 1 THEN 'Urgencias'
				  WHEN 2 THEN 'Urgencias' 
				  WHEN 3 THEN 'Urgencias' 
				  WHEN 4 THEN 'Remitido' 
				  WHEN 5 THEN 'Urgencias' END AS [TIPO INGRESO],
 UNF.UFUCODIGO AS [CODIGO UNIDAD FUNCIONAL DE INGRESO],
 UNF.UFUDESCRI AS [UNIDAD FUNCIONAL DE INGRESO],
 PAIU.CODPROSAL AS [DOCUMENTO PROFESIONAL CONSULTA],
 PAIU.NOMMEDICO AS [PROFESIONAL CONSULTA],
 ESP.DESESPECI AS [ESPECIALIDAD PROFESIONAL CONSULTA],
 IIF(REC.AdmissionNumber IS NULL,'NO','SI') AS [RECONOCIDO CONSULTA],
 IIF(k.FECHINIHI IS NULL OR HC.FECHISPAC IS NULL,NULL,cast(ISNULL(k.FECHINIHI,I.IFECHAING) as date)) AS [FECHA ATENCION MEDICA],
 IIF(k.FECHINIHI IS NULL OR HC.FECHISPAC IS NULL,NULL,rtrim(convert(char(5),ISNULL(k.FECHINIHI,I.IFECHAING),108))) AS [HORA ATENCION MEDICA], 
 IIF(k.FECHINIHI IS NULL OR HC.FECHISPAC IS NULL,NULL,DATEDIFF(MINUTE,A.TRIAFECHA,K.FECHINIHI)) AS [MINUTOS ESPERA TRIAGE VS CONSULTA],
 --IIF(C.IPFECLLEGA IS NULL,0,DATEDIFF(MINUTE,C.IPFECLLEGA, A.TRIAFECHA)) AS [OPORTUNIDAD FL vs FT (MIN)],--OPORTUNIDAD FL vs FT (MIN)
 --IIF(k.FECHINIHI IS NULL OR HC.FECHISPAC IS NULL,NULL,DATEDIFF(MINUTE,A.TRIAFECHA,K.FECHINIHI)) AS [OPORTUNIDAD FT vs FA (MIN)],--OPORTUNIDAD FT vs FA (MIN)
 --IIF(C.IPFECLLEGA IS NULL,DATEDIFF(MINUTE,I.IFECHAING,A.TRIAFECHA),DATEDIFF(MINUTE,C.IPFECLLEGA, k.FECHINIHI)) AS [OPORTUNIDAD FL vs FA (MIN)],--OPORTUNIDAD FL vs FA (MIN)
 CASE WHEN C.CONESTADO = '1' THEN 'Sin Atender' 
	  WHEN C.CONESTADO = '2' THEN 'Ausente en Clasificacion TRIAGE' 
	  WHEN C.CONESTADO = '3' THEN 'Clasificado sin Ingreso' 
	  WHEN C.CONESTADO = '4' THEN 'Clasificado con Ingreso'
	  WHEN C.CONESTADO = '5' THEN 'Atendido' 
	  WHEN C.CONESTADO = '6' THEN 'Ausente en Atencion Inicial Urgencias' 
	  WHEN C.CONESTADO = '7' THEN 'Anulado por error de Parametrizacion' 
	  WHEN C.CONESTADO = '8' THEN 'No atendido por Clasificacion sin Autorizacion' ELSE 'Atendido' END AS [ESTADO PACIENTE], 
 DX.CODDIAGNO AS [CODIGO DX INGRESO],
 DX.NOMDIAGNO AS [DX INGRESO],
 ISNULL(k.FECHFINH,HC.FECHISPAC) AS [FECHA HORA FINAL CONSULTA], 
 IIF(k.FECHINIHI IS NULL,0,DATEDIFF(MINUTE,k.FECHINIHI, k.FECHFINH)) AS [MINUTOS DE CONSULTA],
 IIF(C.IPFECLLEGA IS NULL,DATEDIFF(MINUTE,I.IFECHAING,A.TRIAFECHA),DATEDIFF(MINUTE,C.IPFECLLEGA, k.FECHINIHI)) AS [MINUTOS LLEGADA VS ATENCION],--OPORTUNIDAD FL vs FA (MIN)
 ISNULL(CASE K.INDICAPAC WHEN 1 THEN 'Trasladar a Urgencias'
						 WHEN 2 THEN 'Trasladar a Observación Urgencias'
						 WHEN 3 THEN 'Trasladar a Hospitalización'
						 WHEN 7 THEN 'Trasladar a Consulta Externa'
						 WHEN 9 THEN 'Hospitalización en Casa'
						 WHEN 10 THEN 'Referencia'
						 WHEN 11 THEN 'Morgue'
						 WHEN 12 THEN 'Salida'
						 WHEN 13 THEN 'Continúa en la Unidad'
						 WHEN 15 THEN 'Retiro Voluntario'
						 WHEN 16 THEN 'Fuga' END,
						 IIF(FUNEA.UFUDESCRI IS NULL,'Continúa en la Unidad','Salida')) [DESTINO PACIENTE], 
 EGR.FECALTPAC AS [FECHA ALTA MEDICA],
 I.FECHEGRESO AS [FECHA EGRESO],
 DXA.CODDIAGNO AS [CODIGO DX EGRESO],
 DXA.NOMDIAGNO AS [DX EGRESO],
 FUNEA.UFUCODIGO [CODIGO UNIDAD FUNCIONAL DE EGRESO], 
 FUNEA.UFUDESCRI [UNIDAD FUNCIONAL DE EGRESO],
 CASE WHEN TRA.MEDIOTRASPORTE = 1 THEN 'Básica' WHEN TRA.MEDIOTRASPORTE = 2 THEN 'Medicalizada' END AS [TIPO DE AMBULACIA],
 CAM.[CAMA OBSERVACION],
 HOS.[CAMA HOSPITALIZACION],
 IIF(MUE.ID IS NULL,'NO','SI') AS FALLECIDO,
 MUE.[FECHA MUERTE]  ,
 IIF(MUE.ID IS NOT NULL AND DATEDIFF (MINUTE,c.IPFECLLEGA, c.IPFECLLEGA) < 1440,'SI','NO' ) AS [MORTALIDAD URGENCIAS < 24],
 IIF(MUE.ID IS NOT NULL AND DATEDIFF (MINUTE,c.IPFECLLEGA, c.IPFECLLEGA) > 2880,'SI','NO' ) AS [MORTALIDAD URGENCIAS > 48],
 EST.[CONSULTA DE URGENCIAS POR MEDICINA GENERAL],
 EST.[CONSULTA DE URGENCIAS POR OTRAS ESPECIALIDADES MEDICAS],
 EST.[CONSULTA DE URGENCIAS POR ODONTOLOGIA GENERAL],
 EST.[CONSULTA DE URGENCIAS POR ODONTOLOGIA ESPECIALIZADA],
 SAL.[INTERNACION COMPLEJIDAD ALTA CUATRO O MAS CAMAS],
 SAL.[DERECHOS DE SALA DE OBSERVACION EN URGENCIAS COMPLEJIDAD ALTA],
 CASE WHEN REING.[NUMERO INGRESO B] IS NULL THEN 'NO' ELSE 'SI' END AS REINGRESO,
 REING.[NUMERO INGRESO B] AS [NUMERO DE REINGRESO],
 A.ID AS [ID TRIAGE],
 1 as 'CANTIDAD',
 CAST(A.TRIAFECHA AS date) AS 'FECHA BUSQUEDA',
 YEAR(A.TRIAFECHA) AS 'AÑO BUSQUEDA',
 MONTH(A.TRIAFECHA) AS 'MES BUSQUEDA',
 CONCAT(FORMAT(MONTH(A.TRIAFECHA), '00') ,' - ', 
	   CASE MONTH(A.TRIAFECHA) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 CTE_TRIAGE_UNICO_POR_ATENCIÓN A 
 INNER JOIN dbo.INPACIENT U ON A.IPCODPACI = U.IPCODPACI 
 INNER JOIN Contract.CareGroup E  ON E.Id = U.GENCAREGROUP 
 LEFT JOIN dbo.ADCENATEN CEN ON A.CODCENATE=CEN.CODCENATE 
 LEFT JOIN dbo.INPROFSAL P ON P.CODPROSAL = A.CODPROSAL 
 LEFT JOIN dbo.ADCONTURG C ON A.TRIANUMER=C.CODCONCEC 
 LEFT JOIN dbo.INPROFSAL Pa ON Pa.CODPROSAL = C.PROAUSENT 
 LEFT JOIN dbo.INESPECIA ES ON ES.CODESPECI = P.CODESPEC1 
 LEFT JOIN dbo.ADCATTRIU ds ON A.TRIACATEG=ds.TRIACATEG 
 LEFT JOIN CTE_HCURGING1 k ON A.NUMINGRES = k.NUMINGRES 
 LEFT JOIN dbo.ADINGRESO I ON A.NUMINGRES = I.NUMINGRES
 LEFT JOIN Contract.HealthAdministrator HA ON HA.Id =ISNULL(I.GENCONENTITY,U.GENCONENTITY) 
 LEFT JOIN dbo.HCHISPACA HC ON A.NUMINGRES=HC.NUMINGRES AND HC.NUMEFOLIO=(SELECT MIN(CAST(H.NUMEFOLIO AS INT)) FROM dbo.HCHISPACA H WHERE A.NUMINGRES=H.NUMINGRES) 
 LEFT JOIN dbo.INPROFSAL PAIU ON ISNULL(k.CODPROSAL,HC.CODPROSAL)=PAIU.CODPROSAL 
 LEFT JOIN dbo.INESPECIA ESP ON PAIU.CODESPEC1=ESP.CODESPECI
 --LEFT JOIN dbo.INENTIDAD F ON ISNULL(C.CODENTIDA,A.CODENTIDA) = F.CODENTIDA 
 LEFT JOIN dbo.INDIAGNOS AS DX  ON DX.CODDIAGNO = I.CODDIAING  
 LEFT JOIN dbo.INDIAGNOS AS DXA  ON DXA.CODDIAGNO=I.CODDIAEGR 
 LEFT JOIN (SELECT MAX(AUTO) AUTO, NUMINGRES FROM dbo.HCREFCONP GROUP BY NUMINGRES) AS OTRA ON OTRA.NUMINGRES=I.NUMINGRES 
 LEFT JOIN CTE_MUERTOS AS MUE ON A.NUMINGRES=MUE.INGRESO 
 LEFT JOIN dbo.HCTRASLADOS AS TRA ON TRA.IDHCREFCONP=OTRA.AUTO   
 LEFT JOIN DBO.HCREGEGRE EGR ON I.NUMINGRES=EGR.NUMINGRES AND EGR.NUMEFOLIO=(SELECT MAX(E.NUMEFOLIO) FROM DBO.HCREGEGRE E WHERE I.NUMINGRES=E.NUMINGRES)  
 LEFT JOIN dbo.INUNIFUNC AS FUNEA ON EGR.UFUCODIGO = FUNEA.UFUCODIGO 
 LEFT JOIN dbo.INUNIFUNC AS UNF ON ISNULL(A.UFUCODIGO,I.UFUCODIGO)=UNF.UFUCODIGO
 LEFT JOIN Admissions.TypesPopulationGroups GRU ON C.CODTIPPAC=GRU.CODE
 LEFT JOIN CTE_ORDENES_CON_ESTANCIA_RECONOCIDAS REC  ON REC.AdmissionNumber = I.NUMINGRES 
 LEFT JOIN CTE_ORDENES_CON_ESTANCIAS_CARGADAS EST  ON EST.AdmissionNumber = I.NUMINGRES
 LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA_OBSERVACION CAM  ON CAM.NUMINGRES =I.NUMINGRES 
 LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA_HOSPITALIZACION  HOS  ON HOS.NUMINGRES =I.NUMINGRES 
 LEFT JOIN CTE_ORDENES_CON_SALAS_CARGADAS SAL  ON SAL.AdmissionNumber =I.NUMINGRES 
 LEFT JOIN CTE_REINGRESOS REING ON A.NUMINGRES=REING.[NUMERO INGRESO A]
WHERE 
UNF.UFUDESCRI LIKE '%URGENCIAS%'
