-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewResolucion256
-- Extracted by Fabric SQL Extractor SPN v3.9.0










/*******************************************************************************************************************
Nombre: [Report].[ViewResolucion256]
Tipo:Vista
Observacion:Resolución 256
Profesional:Nilsson Miguel Galindo Lopez
Fecha:
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico: Amira Gil Meneses
Fecha: 03-08-2023
Observaciones: Se adiciona condicional para citas cumplidas en el tipo de archivo 2 Oportunidad en Citas.
--------------------------------------------------------------------------------------
Version 2
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:24-11-2023
Ovservaciones:Se agrega la tabla ADTIPOIDENTIFICA y se deja el campo de la sigla segun la resolución.
--------------------------------------------------------------------------------------
Version 3
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:15-01-2024
Ovservaciones:En el tipo 5 se agrega la tabla dbo.HCURGING1 para sacar la fecha de la atención en consulta y se condiciona que solo sean unidades de urgencias
			  En el tipo 4 se agrega condición de CUPS y se valida si es san jose para que tome la fecha de radicacion
			  
_______________________________________________________________________________________________________________________

**********************************************************************************************************************/

CREATE View [Report].[ViewResolucion256] AS

WITH 

CTE_PACIENTE AS
(
SELECT
PAC.IPCODPACI,
/*IN V2 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CEDULA DE CIUDADANIA'
				 WHEN '2'  THEN 'CEDULA DE EXTRANJERIA'
				 WHEN '3'  THEN 'TARJETA DE IDENTIDAD'
				 WHEN '4'  THEN 'REGISTRO CIVIL' 
				 WHEN '5'  THEN 'PASAPORTE'
				 WHEN '6'  THEN 'ADULTO SIN IDENTIFICACION'
				 WHEN '7'  THEN 'MENOR SIN IDENTIFICACION'
				 WHEN '8'  THEN 'NUMERO UNICO DE IDENTIFICACIÒN'
				 WHEN '9'  THEN 'CERTIFICADO NACIDO VIVO'
				 WHEN '10' THEN 'CARNET DIPLOMATICO'
				 WHEN '11' THEN 'SALVOCONDUCTO'
				 WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' END AS [2], FN V2*/
DOC.SIGLA AS [2],
PAC.IPCODPACI AS [3],
CONVERT(DATE,PAC.IPFECNACI,103) AS [4],
CASE PAC.IPSEXOPAC WHEN 1 THEN 'H'
				   WHEN 2 THEN 'F' ELSE 'I' END AS [5],
PAC.IPPRIAPEL AS [6],
PAC.IPSEGAPEL AS [7],
PAC.IPPRINOMB AS [8],
PAC.IPSEGNOMB AS [9],
ENT.HealthEntityCode AS [10],
UBI.DEPMUNCOD AS [11]
FROM
DBO.INPACIENT PAC INNER JOIN
Contract.HealthAdministrator ENT ON PAC.CODENTIDA=ENT.Code INNER JOIN
--DBO.ADTIPOIDENTIFICA TID ON PAC.IPTIPODOC=TID.CODIGO LEFT JOIN
dbo.INUBICACI UBI ON PAC.AUUBICACI=UBI.AUUBICACI
INNER JOIN dbo.ADTIPOIDENTIFICA DOC ON PAC.IPTIPODOC=DOC.CODIGO
),

CTE_INFORME_QX AS
(
SELECT NUMINGRES FROM DBO.HCQXINFOR GROUP BY NUMINGRES
),
CTE_REPROGRAMACION AS
(
SELECT 
QX1.NUMINGRES,QX1.CODSERIPS
FROM dbo.AGEPROGQX QX1 INNER JOIN 
dbo.AGEPROGQX QX2 ON QX1.IPCODPACI=QX2.IPCODPACI AND QX1.CODESTPQX=6 AND QX2.CODESTPQX!=6 AND QX1.CODSERIPS=QX2.CODSERIPS
GROUP BY QX1.NUMINGRES,QX1.CODSERIPS
)


SELECT Distinct
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
'2' AS [0],
ROW_NUMBER ( )   
OVER (order by AGS.FECHORAIN DESC) [1],
PAC.[2],
PAC.[3],
PAC.[4],
PAC.[5],
PAC.[6],
PAC.[7],
PAC.[8],
PAC.[9],
PAC.[10],
CASE ACT.CODSERIPS WHEN '890201' THEN '1'
				   WHEN '890203' THEN '2'
				   WHEN '890266' THEN '3' 
				   WHEN '890283' THEN '4'
				   WHEN '890235' THEN '7' ELSE
	CASE WHEN ACT.DESACTMED='CONSULTA DE PRIMERA VEZ POR ESPECIALISTA EN GINECOLOGA' AND ACT.CODSERIPS='890250' THEN '5'
		 WHEN ACT.DESACTMED='CONSULTA DE PRIMERA VEZ POR ESPECIALISTA EN OBSTETRICIA' AND ACT.CODSERIPS='890250' THEN '6'
		 WHEN ACT.DESACTMED='CONSULTA DE PRIMERA VEZ POR ESPECIALISTA EN GINECOLOGA Y OBSTETRICIA 15MIN' AND ACT.CODSERIPS='890250' THEN '5' ELSE
	CASE WHEN AGS.CODSERIPS BETWEEN '881112' AND '882841' THEN '8' 
	     WHEN AGS.CODSERIPS BETWEEN '883101' AND '883910' THEN '9' END END END AS [11],
CONVERT(VARCHAR(10),CAST(AGS.FECREGSIS as date),23) as [12],
'1'as [13],
CONVERT(VARCHAR(10),CAST(AGS.FECHAOFERTADA as date),23) as [14],
CONVERT(VARCHAR(10),CAST(AGS.FECITADES as date),23) as [15],
'' AS [16],
'' AS [17],
1 CANTIDAD,
CAST(AGS.FECREGSIS as date) [FECHA BUSQUEDA],
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
DBO.AGASICITA AGS INNER JOIN 
dbo.AGACTIMED ACT ON AGS.CODACTMED = ACT.CODACTMED AND ACT.ACTIVICON!='1' 
												   INNER JOIN
CTE_PACIENTE PAC ON AGS.IPCODPACI=PAC.IPCODPACI
WHERE 
((AGS.CODSERIPS BETWEEN '881112' AND '882841') OR (AGS.CODSERIPS BETWEEN '883101' AND '883910') OR
(ACT.CODSERIPS IN ('890201', '890202','890203','890266','890283','890235','890250') AND AGS.CODTIPCIT=0) AND AGS.CODESTCIT=1)


UNION ALL

SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
'4' AS [0],
ROW_NUMBER ( )   
OVER (order by AGX.FECHORAIN DESC) [1],
PAC.[2],
PAC.[3],
PAC.[4],
PAC.[5],
PAC.[6],
PAC.[7],
PAC.[8],
PAC.[9],
PAC.[10],
CONVERT(VARCHAR(5),PAC.[11]) AS [11],
CONVERT(VARCHAR(6),AGX.CODSERIPS) AS [12],
IIF(CAST(DB_NAME() AS VARCHAR(9))='INDIGO040',CONVERT(VARCHAR(10),CAST(RAD.FECHARADIC as date),23)
											 ,CONVERT(VARCHAR(10),CAST(AGX.FECREGSIS as date),23)) AS [13],
CONVERT(VARCHAR(10),CAST(AGX.FECHORAIN as date),23) AS [14],
IIF(AGX.CODESTPQX=6,'2',CASE WHEN INF.NUMINGRES IS NULL THEN '1' ELSE '2' END) AS [15],
IIF(INF.NUMINGRES IS NULL,'',CASE WHEN CAX.DESCAUCAN LIKE '%PACIENTE%' THEN '2'
	 WHEN CAX.DESCAUCAN LIKE '%MANTENIMIENTO%' THEN '1'
	 WHEN CAX.DESCAUCAN LIKE '%ERROR%' THEN '1'
	 WHEN CAX.DESCAUCAN LIKE '%SALA%' THEN '1'
	 WHEN CAX.DESCAUCAN IS NULL THEN '1' END) AS [16],
IIF (INF.NUMINGRES IS NULL,2, CASE WHEN RE.NUMINGRES IS NULL THEN 2 ELSE 1 END) AS [17],
1 CANTIDAD,
CAST(AGX.FECREGSIS as date) [FECHA BUSQUEDA],
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
dbo.AGEPROGQX AGX 
INNER JOIN CTE_PACIENTE PAC ON AGX.IPCODPACI=PAC.IPCODPACI AND AGX.CODESTPQX!='0'
LEFT JOIN dbo.AGCACANQX CAX ON CAX.CODCACANQ=AGX.CODCAUCAN LEFT JOIN
CTE_INFORME_QX INF ON AGX.NUMINGRES=INF.NUMINGRES LEFT JOIN
CTE_REPROGRAMACION RE ON AGX.NUMINGRES=RE.NUMINGRES AND AGX.CODSERIPS=RE.CODSERIPS
LEFT JOIN dbo.ADRADICACIONQX RAD ON AGX.IDRADICACIONQX=RAD.ID
WHERE AGX.CODSERIPS BETWEEN '010101' AND '869700'

UNION ALL

select 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
'6' AS [0],
ROW_NUMBER ( )   
OVER (order by A.CODCONCEC DESC) [1],
PAC.[2],
PAC.[3],
PAC.[4],
PAC.[5],
PAC.[6],
PAC.[7],
PAC.[8],
PAC.[9],
PAC.[10],
CONVERT(VARCHAR(10),CAST(A.TRIAFECHA AS DATE),23) AS [11],
CONVERT(VARCHAR(5),CAST(A.TRIAFECHA AS TIME)) AS [12],
CONVERT(VARCHAR(10),CAST(URG.FECHINIHI AS DATE),23) AS [13],
CONVERT(VARCHAR(5),CAST(URG.FECHINIHI AS TIME)) AS [14],
NULL AS [15],
NULL AS [16],
NULL AS [17],
1 CANTIDAD,
CAST(A.TRIAFECHA as date) [FECHA BUSQUEDA],
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
dbo.ADTRIAGEU A 
INNER JOIN CTE_PACIENTE PAC ON A.IPCODPACI=PAC.IPCODPACI AND A.TRIAGECLA=2 
LEFT JOIN dbo.HCURGING1 URG ON A.NUMINGRES=URG.NUMINGRES AND URG.NUMEFOLIO=(SELECT MIN(CAST(FOL.NUMEFOLIO AS INT)) FROM dbo.HCURGING1 FOL WHERE A.NUMINGRES=FOL.NUMINGRES)
LEFT JOIN dbo.INUNIFUNC FUN ON URG.UFUCODIGO=FUN.UFUCODIGO
WHERE FUN.UFUDESCRI LIKE '%URGENCIAS%' AND A.ID=(SELECT MAX(B.ID) FROM dbo.ADTRIAGEU B WHERE A.TRIANUMER=B.TRIANUMER)

UNION ALL

SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
'3' AS [0],
1 AS [1],
'NI' AS [2],
CA.CODIPSSEC AS [3],
NULL AS [4],
NULL AS [5],
NULL AS [6],
NULL AS [7],
NULL AS [8],
NULL AS [9],
NULL AS [10],
NULL AS [11],
NULL AS [12],
NULL AS [13],
NULL AS [14],
NULL AS [15],
NULL AS [16],
NULL AS [17],
1 CANTIDAD,
CAST(GETDATE() as date)  AS [FECHA BUSQUEDA],
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL

FROM 
dbo.ADCENATEN CA

Union all

Select 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
'5' AS [0],
1 AS [1],
'NI' AS [2],
CA.CODIPSSEC AS [3],
NULL AS [4],
NULL AS [5],
NULL AS [6],
NULL AS [7],
NULL AS [8],
NULL AS [9],
NULL AS [10],
NULL AS [11],
NULL AS [12],
NULL AS [13],
NULL AS [14],
NULL AS [15],
NULL AS [16],
NULL AS [17],
1 CANTIDAD,
CAST(GETDATE() as date)  AS [FECHA BUSQUEDA],
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM  dbo.ADCENATEN CA 
