-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewMedicamentosAplicados
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE VIEW [Report].[ViewMedicamentosAplicados] as

WITH DISPENSACION AS
(
SELECT AdmissionNumber 'INGRESO',
      C.ConfirmationDate 'FECHA ENTREGA',ATC.Code 'CODIGO MEDICAMENTO',P.Code 'CUM',D.Quantity 'CANTIDAD ENTREGADA',D.EntityId 'IDFORMULA'
FROM Inventory.PharmaceuticalDispensing AS C WITH (NOLOCK)
JOIN Inventory.PharmaceuticalDispensingDetail AS D WITH (NOLOCK) ON C.Id =D.PharmaceuticalDispensingId 
JOIN Inventory.InventoryProduct AS P WITH (NOLOCK) ON  D.ProductId =P.ID 
JOIN Inventory.ATC AS ATC  WITH (NOLOCK) ON P.ATCId =ATC.Id  
WHERE C.Status =2
), 

CTE_CONSULTAS_ORDENAMIENTO  AS
(
SELECT
  CEN.NOMCENATE 'CENTRO ATENCION',
  UNI.UFUDESCRI 'UNIDAD FUNCIONAL',
  C.CODCONCEC 'FORMULA',
  MED.NOMMEDICO 'PROFESIONAL',
  HA.Name 'ENTIDAD',
  C.IPCODPACI 'IDENTIFICACION',
  PAC.IPNOMCOMP 'NOMBRE PACIENTE',
  C.NUMINGRES 'INGRESO',
  D.CODPRODUC 'CODIGO MEDICAMENTO',
  PRO.DESPRODUC 'MEDICAMENTO' , 
  PRE.DESFORMED 'PRESENTACION',
  PG.Name 'GRUPO FARMACOLOGICO' ,C.FECHAORDE 'FECHA ORDEN',
  HOM.FECAPLMED AS 'FECHA DE APLICACION',
  CANPEDPRO 'CANTIDAD SOLICITADA',
  DIS.[FECHA ENTREGA],
  ISNULL(DIS.[CANTIDAD ENTREGADA],0) [CANTIDAD ENTREGADA],
  CAST(ISNULL(DIS.[FECHA ENTREGA], C.FECHAORDE) AS DATE) AS 'FECHA BUSQUEDA' 
FROM HCFARMEPC AS C WITH (NOLOCK)
JOIN HCFARMEPD AS D WITH (NOLOCK) ON C.CODCONCEC =D.CODCONCEC AND C.NUMINGRES =D.NUMINGRES 
JOIN IHLISTPRO AS PRO WITH (NOLOCK) ON D.CODPRODUC =PRO.CODPRODUC AND PRO.TIPPRODUC ='1'
JOIN INPROFSAL AS MED WITH (NOLOCK) ON D.CODPROSAL =MED.CODPROSAL 
JOIN ADCENATEN AS CEN WITH (NOLOCK) ON C.CODCENATE =CEN.CODCENATE 
JOIN INUNIFUNC AS UNI WITH (NOLOCK) ON C.UFUCODIGO =UNI.UFUCODIGO 
JOIN INPACIENT AS PAC WITH (NOLOCK) ON C.IPCODPACI =PAC.IPCODPACI
JOIN ADINGRESO AS ING WITH (NOLOCK) ON C.NUMINGRES =ING.NUMINGRES 
JOIN Contract .HealthAdministrator AS HA WITH (NOLOCK) ON ING.GENCONENTITY =HA.Id  
JOIN Inventory .ATC AS ATC  WITH (NOLOCK) ON D.CODPRODUC =ATC.Code 
JOIN Inventory .ATCEntity AS ATCE WITH (NOLOCK) ON ATC.ATCEntityId =ATCE.Id 
JOIN Inventory .PharmacologicalGroup AS PG WITH (NOLOCK) ON PG.Id =ATCE.IdPharmacologicalGroup 
LEFT JOIN IHFORMEDI AS PRE WITH (NOLOCK) ON PRO.CODFORMED =PRE.CODFORMED 
LEFT JOIN DISPENSACION AS DIS WITH (NOLOCK) ON D.ID =DIS.IDFORMULA AND D.NUMINGRES =DIS.INGRESO LEFT JOIN
HCHOJAMED AS HOM ON HOM.IPCODPACI=D.IPCODPACI AND  HOM.NUMINGRES=ING.NUMINGRES AND HOM.CODPRODUC=DIS.[CODIGO MEDICAMENTO]
WHERE ORDESTADO <>'3'  
)

SELECT
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
 *,
 YEAR([FECHA BUSQUEDA]) AS 'AÑO FECHA BUSQUEDA', 
 MONTH([FECHA BUSQUEDA]) AS 'MES AÑO FECHA BUSQUEDA',
 CONCAT(FORMAT(MONTH([FECHA BUSQUEDA]), '00') ,' - ', 
	   CASE MONTH([FECHA BUSQUEDA]) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 DAY([FECHA BUSQUEDA]) AS 'DIA FECHA BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM CTE_CONSULTAS_ORDENAMIENTO
WHERE
  CAST([FECHA BUSQUEDA] AS DATE) BETWEEN CAST(DATEADD(m,-90,GETDATE()) AS DATE) AND CAST(GETDATE() AS DATE)

