-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_FAC_REPORTE_GASES_POR_RECONOCER_URG
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW REPORT.View_FAC_REPORTE_GASES_POR_RECONOCER_URG
AS

WITH CTE_GASES_UNICOS
----CTE PARA IDENTIFICAR LOS INGRESOS UNICOS DE GASES QUE ESTAN PENDIENTES DE RECONOCER - HOSPITALARIOS
AS
(
  SELECT DISTINCT  ING.NUMINGRES ,ING.IPCODPACI,ING.IESTADOIN
   FROM dbo.HCCONOXIG AS A with (nolock)
   INNER JOIN dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = A.NUMINGRES 
   INNER JOIN dbo.HCPARCONO E with (nolock) ON A.CODVIAADM=E.CODVIAADM
   INNER JOIN dbo.INPACIENT P with (nolock) on a.IPCODPACI = P.IPCODPACI
   INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) on FUN.UFUCODIGO =ING.UFUCODIGO 
   WHERE ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER IS NULL AND FUN.UFUTIPUNI ='1'
 UNION ALL
   SELECT DISTINCT ING.NUMINGRES,ING.IPCODPACI,ING.IESTADOIN 
   FROM dbo.HCCONOXIG AS A 
   INNER JOIN dbo.HCPARCONO E ON A.CODVIAADM=E.CODVIAADM
   INNER JOIN dbo.HCINGRESORECNAC INGMH  on a.NUMINGRES = INGMH .NUMINGRESHIJO
   INNER JOIN dbo.HCRECINAC RN  on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
   INNER JOIN dbo.ADINGRESO AS ING  on ING.NUMINGRES = INGMH.NUMINGRESHIJO
   INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) on FUN.UFUCODIGO =ING.UFUCODIGO
   WHERE ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER IS NULL AND FUN.UFUTIPUNI ='1'
),
CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
AS
(
    SELECT EGR.IPCODPACI ,EGR.NUMINGRES,EGR.FECINIEST ,EGR.FECFINEST ,EGR.CODICAMAS,CAM.NUMCAMHOS ,FUN.UFUDESCRI  ,FUN.UFUTIPUNI  
	FROM CHREGESTA EGR with (nolock)
	INNER JOIN 
	(
	   SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR with (nolock)
	   INNER JOIN CTE_GASES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G  ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM with (nolock) ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),
CTE_EGRESO_CAMA
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO  
FROM CHREGEGRE EGR
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECEGRESO) EGRESO 
 FROM CHREGEGRE EGR with (nolock) 
 INNER JOIN CTE_GASES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.EGRESO =EGR.FECEGRESO 
),
CTE_ORDENES_CON_GASES_CARGADAS
---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
AS
( 
SELECT RC.AdmissionNumber,G.CUPS ,G.CANTIDAD  FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN
(
SELECT RC.AdmissionNumber ,CUPS.Code CUPS ,SUM(SOD.InvoicedQuantity) CANTIDAD   
FROM Billing .RevenueControlDetail AS RCD WITH (NOLOCK)
INNER JOIN BILLING.REVENUECONTROL AS RC WITH (NOLOCK) ON RCD.REVENUECONTROLID = RC.ID
INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD WITH (NOLOCK) ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2', '3')
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD WITH (NOLOCK) ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN CTE_GASES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =RC.AdmissionNumber  
INNER JOIN Contract .CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id =SOD.CUPSEntityId AND CUPS.ServiceType IN (4)
INNER JOIN Contract .IPSService AS IPS WITH (NOLOCK) ON IPS.Id =SOD.IPSServiceId
--where rc.AdmissionNumber ='7569' --'431'
GROUP BY RC.AdmissionNumber ,CUPS.Code 
) AS G ON G.AdmissionNumber =RC.AdmissionNumber
),

CTE_DATOS_GASES
---CTE QUE ME TRAE LOS DATOS DE LOS GASES DE FORMA AGRUPADA
AS
(
SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(E.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(a.TOTLITADM ) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA] ,FUN.UFUDESCRI, 
HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',MIN(A.HORAINICIA) 'FECHA REALIZADO MINIMA',MAX(A.HORAINICIA) 'FECHA REALIZADO MAXIMA'
  FROM dbo.HCCONOXIG AS A 
  INNER JOIN dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = A.NUMINGRES 
  INNER JOIN dbo.HCPARCONO E ON A.CODVIAADM=E.CODVIAADM
  INNER JOIN dbo.INPACIENT P on a.IPCODPACI = P.IPCODPACI
  INNER JOIN dbo.INCUPSIPS B ON E.CODSERIPS=B.CODSERIPS
  INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) on FUN.UFUCODIGO =ING.UFUCODIGO
  INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
  INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id
  INNER JOIN
	(
	    SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(E.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.TOTLITADM ) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN
		  FROM dbo.HCCONOXIG AS A 
          INNER JOIN dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = A.NUMINGRES 
          INNER JOIN dbo.HCPARCONO E ON A.CODVIAADM=E.CODVIAADM
          INNER JOIN dbo.INPACIENT P on a.IPCODPACI = P.IPCODPACI
		  INNER JOIN dbo.INCUPSIPS B ON E.CODSERIPS=B.CODSERIPS
		  INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) on FUN.UFUCODIGO =ING.UFUCODIGO
		  INNER JOIN CTE_GASES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =ING.NUMINGRES 
		  WHERE FUN.UFUTIPUNI ='1'
	      GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,E.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =E.CODSERIPS
	WHERE  A.GENSERVICEORDER IS NULL AND FUN.UFUTIPUNI ='1'
	GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,E.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name , CG.Name ,ING.IFECHAING ,FUN.UFUDESCRI
  UNION ALL
   SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(E.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.TOTLITADM ) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA] ,FUN.UFUDESCRI,
   HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',MIN(A.HORAINICIA) 'FECHA REALIZADO MINIMA',MAX(A.HORAINICIA) 'FECHA REALIZADO MAXIMA'
   FROM dbo.HCCONOXIG AS A 
   INNER JOIN dbo.HCPARCONO E ON A.CODVIAADM=E.CODVIAADM
   INNER JOIN dbo.HCINGRESORECNAC INGMH  on a.NUMINGRES = INGMH .NUMINGRESHIJO
   INNER JOIN dbo.HCRECINAC RN  on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
   INNER JOIN  dbo.ADINGRESO AS ING  on ING.NUMINGRES = INGMH.NUMINGRESHIJO
   INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) on FUN.UFUCODIGO =ING.UFUCODIGO
   INNER JOIN dbo.INPACIENT P on a.IPCODPACI = P.IPCODPACI
   INNER JOIN dbo.INCUPSIPS B ON E.CODSERIPS=B.CODSERIPS
   INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
   INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id
   INNER JOIN
	(
	    SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(E.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.TOTLITADM ) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN
        FROM dbo.HCCONOXIG AS A 
        INNER JOIN dbo.HCPARCONO E ON A.CODVIAADM=E.CODVIAADM
        INNER JOIN dbo.HCINGRESORECNAC INGMH  on a.NUMINGRES = INGMH .NUMINGRESHIJO
        INNER JOIN dbo.HCRECINAC RN  on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
        INNER JOIN  dbo.ADINGRESO AS ING  on ING.NUMINGRES = INGMH.NUMINGRESHIJO
        INNER JOIN dbo.INPACIENT P on a.IPCODPACI = P.IPCODPACI
		INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) on FUN.UFUCODIGO =ING.UFUCODIGO
        INNER JOIN dbo.INCUPSIPS B ON E.CODSERIPS=B.CODSERIPS
		INNER JOIN CTE_GASES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =ING.NUMINGRES
		WHERE  FUN.UFUTIPUNI ='1'
		GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,E.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =E.CODSERIPS
	WHERE A.GENSERVICEORDER IS NULL AND FUN.UFUTIPUNI ='1'
	GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,E.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name , CG.Name ,ING.IFECHAING ,FUN.UFUDESCRI
),

CTE_GASES
AS
(
SELECT ING.NUMINGRES,ing.IESTADOIN,ING.[FECHA INGRESO] ,ING.ENTIDAD ,ING.[GRUPO ATENCION]   ,ING.IPCODPACI ,ING.IPNOMCOMP ,ING.CODSERIPS ,ING.DESSERIPS,CAST(ING.[CANTIDAD ORDENADA] AS NUMERIC) 'CANTIDAD ORDENADA'  ,
CAST(ING.CANSERIPS AS NUMERIC) CANSERIPS ,CAM.UFUDESCRI ,
CAM.NUMCAMHOS,EGR.FECEGRESO,CAR.CUPS 'CUPS CARGADO',CAR.CANTIDAD 'CANTIDAD CARGADA',ING.[FECHA REALIZADO MINIMA] ,ING.[FECHA REALIZADO MAXIMA]      
FROM CTE_DATOS_GASES ING with (nolock) 
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM with (nolock) ON ING.NUMINGRES =CAM.NUMINGRES
LEFT JOIN CTE_EGRESO_CAMA EGR with (nolock) ON EGR.NUMINGRES =ING.NUMINGRES
LEFT JOIN CTE_ORDENES_CON_GASES_CARGADAS CAR with (nolock) ON CAR.AdmissionNumber =ING.NUMINGRES AND CAR.CUPS =ING.CODSERIPS 
WHERE ING.[CANTIDAD ORDENADA] <>ISNULL(CAR.CANTIDAD,0)  AND ING.[CANTIDAD ORDENADA] >ISNULL(CAR.CANTIDAD,0)
--and ING.UFUDESCRI in ('PEDIATRIA URGENCIAS','URGENCIAS ADULTOS','PABELLON URGENCIAS ADULTOS','GINECOBSTETRICIA URGENCIAS')
--AND CAM.NUMCAMHOS LIKE 'U%' OR CAM.NUMCAMHOS LIKE 'O%' OR CAM.NUMCAMHOS LIKE 'SRE%'
)


SELECT GAS.* 
FROM 
CTE_GASES  AS GAS
WHERE GAS.UFUDESCRI in ('PEDIATRIA URGENCIAS','URGENCIAS ADULTOS','PABELLON URGENCIAS ADULTOS','GINECOBSTETRICIA URGENCIAS')