-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewPendientesDeOrdenesProcedimientosQx
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[ViewPendientesDeOrdenesProcedimientosQx]
as
-----*****PROCEDIMIENTOS QUIRURGICOS*******-----	   	  
WITH CTE_PROCEDIMIENTO_QX
AS
(
  SELECT	A.CODSERIPS,IIF(A.GENSERVICEORDER IS NULL, 0, 1) AS Seleccione,	A.IPCODPACI, A.NUMINGRES,'Procedimientos con Informe QX' AS Tipo,SUM(CANTIDAQX) AS TOTAL,
			RTRIM(B.DESSERIPS) AS DESSERIPS,A.NUMEFOLIO as NUMEFOLIO,case when (select count(*) from dbo.HCQXREALI where A.IPCODPACI=IPCODPACI AND A.NUMINGRES=NUMINGRES AND A.NUMEFOLIO=NUMEFOLIO) > 1 then 1 else 0 end as IsMultiple,
			A.GENSERVICEORDER,i.IPNOMCOMP  as PersonName, 0 CUPSEntityContractDescriptionId, 0 ContractDescriptionId, '' ContractDescriptionCodeName,
			CAST(A.FECHORINI AS DATE) 'FECHA SERVICIO'
	FROM dbo.HCQXINFOR A 
	JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
	JOIN dbo.INPACIENT i on a.IPCODPACI = i.IPCODPACI 
	JOIN dbo.HCQXREALI C ON A.IPCODPACI=C.IPCODPACI AND A.NUMINGRES=C.NUMINGRES AND A.NUMEFOLIO=C.NUMEFOLIO --AND A.CODSERIPS=C.CODSERIPS 
	WHERE A.GENSERVICEORDER IS NULL
	GROUP BY A.CODSERIPS,B.DESSERIPS,A.IPCODPACI, A.NUMINGRES,A.NUMEFOLIO,A.GENSERVICEORDER,i.IPNOMCOMP,A.FECHORINI
UNION ALL
	SELECT	A.CODSERIPS,IIF(A.GENSERVICEORDER IS NULL, 0, 1) AS Seleccione,A.IPCODPACI, INGMH.NUMINGRES,'Procedimientos con Informe QX' AS Tipo,SUM(CANTIDAQX) AS TOTAL,
			RTRIM(B.DESSERIPS) AS DESSERIPS,A.NUMEFOLIO as NUMEFOLIO,case when (select count(*) from dbo.HCQXREALI where A.IPCODPACI=IPCODPACI AND INGMH.NUMINGRES=NUMINGRES AND A.NUMEFOLIO=NUMEFOLIO) > 1 then 1 else 0 end as IsMultiple,
			A.GENSERVICEORDER,'Hijo '+ cast(rn.NUMHIJREG as varchar(20)) as PersonName, 0 CUPSEntityContractDescriptionId, 0 ContractDescriptionId, '' ContractDescriptionCodeName,
			CAST(A.FECHORINI AS DATE) 'FECHA SERVICIO'
	FROM dbo.HCQXINFOR A 
	JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
	JOIN dbo.HCINGRESORECNAC INGMH  on a.NUMINGRES = INGMH .NUMINGRESHIJO
	JOIN dbo.HCRECINAC RN  on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	JOIN  dbo.ADINGRESO AS ING  on ING.NUMINGRES = INGMH.NUMINGRESHIJO 
	JOIN dbo.HCQXREALI C ON A.IPCODPACI=C.IPCODPACI AND A.NUMINGRES=C.NUMINGRES AND A.NUMEFOLIO=C.NUMEFOLIO --AND A.CODSERIPS=C.CODSERIPS 
	WHERE A.GENSERVICEORDER IS NULL
	GROUP BY A.CODSERIPS,B.DESSERIPS,A.IPCODPACI, INGMH.NUMINGRES,A.NUMEFOLIO,A.GENSERVICEORDER,rn.NUMHIJREG,A.FECHORINI
),

CTE_PROCEDIMIENTOS_QX_REALIZADOS
AS
(
SELECT 'SIN ORDENES' 'ORDENE DE SERVICIO',QX.NUMINGRES 'INGRESO' ,qx.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE' ,
CASE QX.IsMultiple WHEN 1 THEN 'SI' ELSE 'NO' END 'MULTIPLE', CASE vs.QXPRINCIP WHEN 1 THEN 'SI' ELSE 'NO' END 'QX PRINCIPAL',
VS.CODSERIPS 'CUPS REALIZADO',IPS.DESSERIPS 'PROCEDIMIENTO REALIZADO',QX.[FECHA SERVICIO] ,QX.NUMEFOLIO 'FOLIO ORDENAMIENTO',ing.IESTADOIN 'ESTADO' ,f.InvoiceNumber 'NRO FACTURA',
C.RadicatedConsecutive 'NRO RADICADO'
from CTE_PROCEDIMIENTO_QX qx
INNER JOIN dbo.ViewSurgeriesPerformed vs on qx.IPCODPACI=vs.IPCODPACI and qx.NUMINGRES=vs.NUMINGRES and qx.NUMEFOLIO= vs.NUMEFOLIO
INNER JOIN DBO.INCUPSIPS AS IPS ON IPS.CODSERIPS =VS.CODSERIPS 
INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =QX.IPCODPACI 
INNER JOIN DBO.INCUPSIPS AS IPSO ON IPSO.CODSERIPS =QX.CODSERIPS
inner join dbo.ADINGRESO as ing on ing.NUMINGRES =qx.NUMINGRES 
LEFT join Billing .Invoice as f on f.AdmissionNumber =ing.NUMINGRES and f.Status =1
LEFT JOIN Portfolio.RadicateInvoiceD AS RAD ON RAD.InvoiceNumber =F.InvoiceNumber 
LEFT JOIN Portfolio .RadicateInvoiceC AS C ON C.Id =RAD.RadicateInvoiceCId 
where qx.Seleccione =0 and qx.Tipo ='Procedimientos con Informe QX' --and ing.IESTADOIN ='F'
),

CTE_ALTA_MEDICA
AS
(
  SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(FECALTPAC) 'FECHA ALTA' FROM DBO.HCREGEGRE EGR with (nolock) 
  INNER JOIN CTE_PROCEDIMIENTOS_QX_REALIZADOS AS PEN with (nolock) ON PEN.INGRESO =EGR.NUMINGRES 
  GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI
),

CTE_ESTANCIA_MAYOR
AS
(
  SELECT C.NUMINGRES ,C.IPCODPACI,C.CODICAMAS  ,C.FECINIEST 'FECHA ESTANCIA',C.REGESTADO,C.CODTIPEST,C.ID    FROM dbo.CHREGESTA C with (nolock)
    INNER JOIN(SELECT C.NUMINGRES ,C.IPCODPACI ,MAX(C.ID ) IDD FROM dbo.CHREGESTA C with (nolock) GROUP BY C.NUMINGRES ,C.IPCODPACI) AS G ON G.IDD =C.ID 
	--INNER JOIN CTE_PROCEDIMIENTOS_QX_REALIZADOS AS PEN ON PEN.INGRESO =C.NUMINGRES 
),

CTE_CAMAS
AS
(
     SELECT FUN.UFUDESCRI 'UNIDAD FUNCIONAL' ,C.IPCODPACI 'IDENTIFICACION' ,C.NUMINGRES 'INGRESO',A.NUMCAMHOS 'CAMA',G.DESTIPEST 'TIPO ESTANCIA'  ,C.ID  'ID_ESTANCIA', 
	 A.CODICAMAS 'ID_CAMAS', CEN.NOMCENATE 'CENTRO DE ATENCION',A.CODCLAHAB ,A.CODCLACAM 
	 FROM dbo.CHCAMASHO A with (nolock)
	 INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON A.UFUCODIGO =FUN.UFUCODIGO 
	 INNER JOIN CTE_ESTANCIA_MAYOR C with (nolock) ON A.CODICAMAS=C.CODICAMAS AND C.REGESTADO = 1 
     INNER JOIN dbo.CHTIPESTA G with (nolock) ON G.CODTIPEST=C.CODTIPEST 
	 INNER JOIN DBO.ADCENATEN AS CEN with (nolock) ON CEN.CODCENATE =A.CODCENATE 
),

CTE_HISTORIAS_AMBULATORIAS
AS
(
  SELECT HIS.NUMINGRES ,HIS.IPCODPACI ,MAX(FECHISPAC) AS 'FECHA ALTA'    FROM  DBO.HCHISPACA HIS with (nolock)
  INNER JOIN CTE_PROCEDIMIENTOS_QX_REALIZADOS AS PEN with (nolock) ON PEN.INGRESO =HIS.NUMINGRES 
  WHERE HIS.GENCONEXT =1
  GROUP BY HIS.NUMINGRES ,HIS.IPCODPACI
)

SELECT 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 QX.*, 
 ISNULL(ALT.[FECHA ALTA],AMB.[FECHA ALTA]) 'ALTA MEDICA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 CTE_PROCEDIMIENTOS_QX_REALIZADOS QX
 LEFT JOIN CTE_ALTA_MEDICA AS ALT ON ALT.NUMINGRES =QX.INGRESO 
 LEFT JOIN CTE_HISTORIAS_AMBULATORIAS AS AMB ON AMB.NUMINGRES =QX.INGRESO 
