-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewNIIFTotalFacturado
-- Extracted by Fabric SQL Extractor SPN v3.9.0










CREATE VIEW [Report].[ViewNIIFTotalFacturado] AS

WITH CTE_FACTURACION_TOTAL AS
 (
SELECT 
F.Id ID_FACTURA ,
CASE F.DocumentType WHEN '1' THEN 'FACTURA EAPB CON CONTRATO'  
					WHEN '2' THEN 'FACTURA EAPB SIN CONTRATO' 
					WHEN '3' THEN 'FACTURA PARTICULAR'
					WHEN '4' THEN 'FACTURA CAPITA' 
					WHEN '5' THEN 'CONTROL CAPITACION' 
					WHEN '6' THEN 'NO OPERACIONAL' 
					WHEN '7' THEN 'FACTURA VENTA PRODUCTOS' END 'TIPO REGISTRO',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' 
				   WHEN '2' THEN 'CEDULA DE EXTRANJERIA' 
				   WHEN '3' THEN 'TARJETA DE IDENTIDAD' 
				   WHEN '4' THEN 'REGISTRO CIVIL' 
				   WHEN '5' THEN 'PASAPORTE' 
				   WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' 
				   WHEN '7' THEN 'MENOR SIN IDENTIFICACION' 
				   WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION' 
				   WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' 
				   WHEN '10' THEN 'CARNET DIPLOMATICO'
				   WHEN '11' THEN 'SALVOCONDUCTO' 
				   WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
				   WHEN '13' THEN 'PERMISO POR PROTECCION TEMPORAL'
				   WHEN '14' THEN 'DOCUMENTO EXTRANJERO'
				   WHEN '15' THEN 'SIN IDENTIFICACION' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
ISNULL(RTRIM(F.PatientCode), 0) AS 'IDENTIFICACION',
CASE WHEN RTRIM(PAC.IPNOMCOMP) IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'N/A' WHEN PAC.IPNOMCOMP IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'N/A'
ELSE RTRIM(PAC.IPNOMCOMP) END AS  'PACIENTE' ,ISNULL(F.AdmissionNumber,'000') 'INGRESO',CAST(ISNULL(ING.IFECHAING,f.InitialDate) AS DATE)'FECHA INGRESO',CAST(ISNULL(ING.FECHEGRESO,ISNULL(ING.IFECHAING,f.InitialDate)) AS DATE) 'FECHA EGRESO' ,
F.InvoiceNumber 'NRO FACTURA' ,IIF(F.DOCUMENTTYPE=6, cast(f.InitialDate AS date), CAST(F.InvoiceDate AS DATETIME)) AS 'FECHA FACTURA',F.InvoiceExpirationDate AS 'FECHA VENCIMIENTO',
IIF(F.DOCUMENTTYPE=6, f.InvoiceValue, F.TotalInvoice) AS 'TOTAL FACTURA',F.ValueTax AS 'VALOR IMPUESTO',F.ThirdPartySalesValue AS 'VR TOTAL ENTIDAD',F.ThirdPartyDiscountValue AS 'VR TOTAL DESCUENTO',
F.TotalPatientSalesPrice AS 'VR TOTAL CUOTA RECUPERACION',F.PatientDiscount AS 'DESCUENTO CUOTA RECUPERACION',F.PatientPaidValue AS 'VR PAGADO PACIENTE',
F.ThirdPartyAccountReceivableValue AS 'VR CXC',F.PatientAccountReceivableValue AS 'VR CXC GENERADA A PACIENTE',
CASE F.STATUS WHEN '1' THEN 'FACTURADO' WHEN '2' THEN 'ANULADO' END AS 'ESTADO FACTURA',
RTRIM(T.Nit)+'-'+T.DigitVerification AS 'NIT ENTIDAD',
RTRIM(ISNULL(HA.Code,T.NIT)) 'CODIGO ENTIDAD' ,   RTRIM(ISNULL(HA.Name,T.NAME)) 'ENTIDAD' ,RTRIM(ISNULL(CG.Name,'N/A')) 'GRUPO DE ATENCION',
CASE WHEN HA.EntityType LIKE '1' THEN 'EPS CONTRIBUTIVO' WHEN HA.EntityType LIKE '2' THEN 'EPS SUBSIDIADO' WHEN HA.EntityType LIKE '3' THEN 'ET VINCULADO MUNICIPIO'
WHEN HA.EntityType LIKE '4' THEN 'ET VINCULADOS DAPARTAMENTO' WHEN HA.EntityType LIKE '5' THEN 'ARL RIESGO LABORALES' WHEN HA.EntityType LIKE '6' THEN 'MP MEDICINA PREPAGADA'
WHEN HA.EntityType LIKE '7' THEN 'IPS PRIVADA' WHEN HA.EntityType LIKE '8' THEN 'IPS PUBLICA' WHEN HA.EntityType LIKE '9' THEN 'REGIMEN ESPECIAL'WHEN HA.EntityType LIKE '10' THEN 'ACCIDENTE DE TRANSITO'
WHEN HA.EntityType LIKE '11' THEN 'FOSYGA' WHEN HA.EntityType LIKE '12' THEN 'OTROS' WHEN HA.EntityType IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'N/A'
WHEN HA.EntityType IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'N/A' END AS [TIPO REGIMEN],
CASE WHEN ING.TIPOINGRE=1 THEN 'AMBULATORIO'  WHEN ING.TIPOINGRE=2 THEN 'HOSPITALARIO' WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '1' THEN 'FACTURA EAPB CON CONTRATO'
WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '2' THEN 'FACTURA EAPB SIN CONTRATO'WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '3' THEN 'FACTURA PARTICULAR'
WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'FACTURA CAPITA' WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '5' THEN 'CONTROL CAPITACION'
WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'NO OPERACIONAL' WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '7' THEN 'FACTURA VENTA PRODUCTOS' END AS 'TIPO AMBITO',
USU.NOMUSUARI 'USUARIO FACTURO',CAST(F.InvoicedDate AS DATE) 'FECHA REGISTRO',ISNULL(DIA.CODDIAGNO,ISNULL(DIAG.CODDIAGNO,'N/A')) 'CODIGO CIE10',SUBSTRING(ISNULL(RTRIM(DIA.NOMDIAGNO),ISNULL(RTRIM(DIAG.NOMDIAGNO),'N/A')),1,80) 'DIAGNOSTICO',
CASE WHEN ING.IAUTORIZA IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'N/A' WHEN ING.IAUTORIZA IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'N/A' 	WHEN ING.IAUTORIZA LIKE ' ' THEN 'N/A'
ELSE ING.IAUTORIZA END AS 'AUTORIZACION',  ISNULL(IIF (F.DOCUMENTTYPE=6, LTRIM(FU2.CODE) + ' - ' + FU2.NAME, 
ISNULL(FU.CODE + ' - ' +FU.Name, LTRIM(ING.UFUCODIGO) + ' - ' + UF.NAME)), 'N/A') AS [UNIDAD FUNCIONAL EGRESO],IIF (F.DOCUMENTTYPE=6, FU2.NAME, C.Name) AS  'CATEGORIA FACTURA',F.AnnulmentDate 'FECHA ANULACION',
iif(F.DOCUMENTTYPE=6, cast(f.InitialDate AS date), CAST(F.InvoiceDate AS DATE)) AS 'FECHA BUSQUEDA', USU2.NOMUSUARI 'USUARIO ANULO'
FROM 
Billing.Invoice AS F
LEFT JOIN Contract.HealthAdministrator AS HA ON HA.Id =F.HealthAdministratorId 
LEFT JOIN Contract.CareGroup AS CG ON CG.Id =F.CareGroupId 
LEFT JOIN Common.ThirdParty AS T ON T.Id = F.ThirdPartyId
LEFT JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES =F.AdmissionNumber 
LEFT JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =F.PatientCode 
LEFT JOIN DBO.SEGusuaru AS USU ON USU.CODUSUARI =F.InvoicedUser 
LEFT JOIN DBO.INDIAGNOS AS DIA ON DIA.CODDIAGNO =ISNULL(ING.CODDIAEGR ,ING.CODDIAING)
LEFT JOIN Payroll.FunctionalUnit AS UF ON UF.Code  = ING.UFUCODIGO
LEFT JOIN Payroll.FunctionalUnit AS FU ON ING.UFUEGRMED=FU.CODE
LEFT JOIN Billing.BasicBilling AS BB ON BB.InvoiceId =F.Id
LEFT JOIN Payroll.FunctionalUnit AS FU2 ON BB.FunctionalUnitId =FU2.Id
LEFT JOIN Billing.InvoiceCategories AS C ON C.Id = F.InvoiceCategoryId
LEFT JOIN dbo.INDIAGNOS AS DIAG ON DIAG.CODDIAGNO = F.OutputDiagnosis
LEFT JOIN dbo.SEGusuaru AS USU2 ON USU2.CODUSUARI = F.AnnulmentUser
),

CTE_FACTURACION_TOTAL_ANULADA AS
( 
SELECT 
F.Id ID_FACTURA ,
CASE F.DocumentType WHEN '1' THEN 'FACTURA EAPB CON CONTRATO'  
					WHEN '2' THEN 'FACTURA EAPB SIN CONTRATO'  
					WHEN '3' THEN 'FACTURA PARTICULAR'
					WHEN '4' THEN 'FACTURA CAPITA' 
					WHEN '5' THEN 'CONTROL CAPITACION' 
					WHEN '6' THEN 'NO OPERACIONAL' 
					WHEN '7' THEN 'FACTURA VENTA PRODUCTOS' END 'TIPO REGISTRO',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' WHEN '2' THEN 'CEDULA DE EXTRANJERIA' 
				   WHEN '3' THEN 'TARJETA DE IDENTIDAD' 
				   WHEN '4' THEN 'REGISTRO CIVIL' 
				   WHEN '5' THEN 'PASAPORTE' 
				   WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' 
				   WHEN '7' THEN 'MENOR SIN IDENTIFICACION' 
				   WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION' 
				   WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' 
				   WHEN '10' THEN 'CARNET DIPLOMATICO'
				   WHEN '11' THEN 'SALVOCONDUCTO' 
				   WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
				   WHEN '13' THEN 'PERMISO DE PROTECCION ESPECIAL'
				   WHEN '14' THEN 'DOCUMENTO EXTRANJERO'
				   WHEN '15' THEN 'SIN IDENTIFICACION'ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
ISNULL(F.PatientCode, '0') AS 'IDENTIFICACION',
CASE WHEN RTRIM(PAC.IPNOMCOMP) IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'N/A' 
	 WHEN PAC.IPNOMCOMP IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'N/A' ELSE RTRIM(PAC.IPNOMCOMP) END AS  
'PACIENTE' ,ISNULL(F.AdmissionNumber,'000') 'INGRESO',
CAST(ISNULL(ING.IFECHAING,f.InitialDate) AS DATE)'FECHA INGRESO',
CAST(ISNULL(ING.FECHEGRESO,ISNULL(ING.IFECHAING,f.InitialDate)) AS DATE) 'FECHA EGRESO' ,
F.InvoiceNumber 'NRO FACTURA',
CAST(F.AnnulmentDate AS DATETIME) AS 'FECHA FACTURA',
F.InvoiceExpirationDate AS 'FECHA VENCIMIENTO',
IIF(F.DOCUMENTTYPE=6,-f.InvoiceValue,-F.TotalInvoice) AS 'TOTAL FACTURA',
-F.ValueTax AS 'VALOR IMPUESTO',-F.ThirdPartySalesValue AS 'VR TOTAL ENTIDAD',-F.ThirdPartyDiscountValue AS 'VR TOTAL DESCUENTO',
-F.TotalPatientSalesPrice AS 'VR TOTAL CUOTA RECUPERACION',
-F.PatientDiscount AS 'DESCUENTO CUOTA RECUPERACION',
-F.PatientPaidValue AS 'VR PAGADO PACIENTE',
-F.ThirdPartyAccountReceivableValue AS 'VR CXC'
,-F.PatientAccountReceivableValue AS 'VR CXC GENERADA A PACIENTE',
CASE F.STATUS WHEN '1' THEN 'FACTURADO' WHEN '2' THEN 'ANULADO' END AS 'ESTADO FACTURA',
RTRIM(T.Nit)+'-'+T.DigitVerification AS 'NIT ENTIDAD',
RTRIM(ISNULL(HA.Code,T.NIT)) 'CODIGO ENTIDAD' ,   RTRIM(ISNULL(HA.Name,T.NAME)) 'ENTIDAD' ,RTRIM(ISNULL(CG.Name,'N/A')) 'GRUPO DE ATENCION',
CASE WHEN HA.EntityType LIKE '1' THEN 'EPS CONTRIBUTIVO' WHEN HA.EntityType LIKE '2' THEN 'EPS SUBSIDIADO' WHEN HA.EntityType LIKE '3' THEN 'ET VINCULADO MUNICIPIO'
WHEN HA.EntityType LIKE '4' THEN 'ET VINCULADOS DAPARTAMENTO' WHEN HA.EntityType LIKE '5' THEN 'ARL RIESGO LABORALES' WHEN HA.EntityType LIKE '6' THEN 'MP MEDICINA PREPAGADA'
WHEN HA.EntityType LIKE '7' THEN 'IPS PRIVADA' WHEN HA.EntityType LIKE '8' THEN 'IPS PUBLICA' WHEN HA.EntityType LIKE '9' THEN 'REGIMEN ESPECIAL'WHEN HA.EntityType LIKE '10' THEN 'ACCIDENTE DE TRANSITO'
WHEN HA.EntityType LIKE '11' THEN 'FOSYGA' WHEN HA.EntityType LIKE '12' THEN 'OTROS' WHEN HA.EntityType IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'N/A'
WHEN HA.EntityType IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'N/A' END AS [TIPO REGIMEN],
CASE WHEN ING.TIPOINGRE=1 THEN 'AMBULATORIO'  WHEN ING.TIPOINGRE=2 THEN 'HOSPITALARIO' WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '1' THEN 'FACTURA EAPB CON CONTRATO'
WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '2' THEN 'FACTURA EAPB SIN CONTRATO'WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '3' THEN 'FACTURA PARTICULAR'
WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'FACTURA CAPITA' WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '5' THEN 'CONTROL CAPITACION'
WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'NO OPERACIONAL' WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '7' THEN 'FACTURA VENTA PRODUCTOS' END AS 'TIPO AMBITO',
USU.NOMUSUARI 'USUARIO FACTURO',CAST(F.InvoicedDate AS DATE) 'FECHA REGISTRO',ISNULL(DIA.CODDIAGNO,ISNULL(DIAG.CODDIAGNO,'N/A')) 'CODIGO CIE10',SUBSTRING(ISNULL(RTRIM(DIA.NOMDIAGNO),ISNULL(RTRIM(DIAG.NOMDIAGNO),'N/A')),1,80) 'DIAGNOSTICO',
CASE WHEN ING.IAUTORIZA IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'N/A' WHEN ING.IAUTORIZA IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'N/A' 	WHEN ING.IAUTORIZA LIKE ' ' THEN 'N/A'
ELSE ING.IAUTORIZA END AS 'AUTORIZACION',  ISNULL(IIF (F.DOCUMENTTYPE=6, LTRIM(FU2.CODE) + ' - ' + FU2.NAME, 
ISNULL(FU.CODE + ' - ' +FU.Name, LTRIM(ING.UFUCODIGO) + ' - ' + UF.NAME)), 'N/A') AS [UNIDAD FUNCIONAL EGRESO],IIF (F.DOCUMENTTYPE=6, FU2.NAME, C.Name) AS  'CATEGORIA FACTURA',F.AnnulmentDate 'FECHA ANULACION',
CAST(F.AnnulmentDate AS DATE) AS 'FECHA BUSQUEDA', USU2.NOMUSUARI 'USUARIO ANULO'
FROM 
Billing.Invoice AS F
LEFT JOIN Contract .HealthAdministrator AS HA ON HA.Id =F.HealthAdministratorId 
LEFT JOIN Contract .CareGroup AS CG ON CG.Id =F.CareGroupId 
LEFT JOIN Common.ThirdParty AS T ON T.Id = F.ThirdPartyId
LEFT JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES=F.AdmissionNumber 
LEFT JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =F.PatientCode 
LEFT JOIN DBO.SEGusuaru AS USU ON USU.CODUSUARI =F.InvoicedUser 
LEFT JOIN DBO.INDIAGNOS AS DIA ON DIA.CODDIAGNO =ISNULL(ING.CODDIAEGR ,ING.CODDIAING )
LEFT JOIN Payroll.FunctionalUnit AS UF ON UF.Code  = ING.UFUCODIGO
LEFT JOIN Payroll.FunctionalUnit AS FU ON ING.UFUEGRMED=FU.CODE
LEFT JOIN Billing.BasicBilling AS BB ON BB.InvoiceId =F.Id
LEFT JOIN Payroll.FunctionalUnit AS FU2 ON BB.FunctionalUnitId =FU2.Id
LEFT JOIN Billing.InvoiceCategories AS C ON C.Id = F.InvoiceCategoryId
LEFT JOIN dbo.INDIAGNOS AS DIAG ON DIAG.CODDIAGNO = F.OutputDiagnosis
LEFT JOIN dbo.SEGusuaru AS USU2 ON USU2.CODUSUARI = F.AnnulmentUser
WHERE 
F.Status = 2
)

SELECT
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 CABF.*,
 YEAR([FECHA BUSQUEDA]) AS 'AÑO FECHA BUSQUEDA',
 MONTH([FECHA BUSQUEDA]) AS 'MES AÑO FECHA BUSQUEDA',
 CASE MONTH([FECHA BUSQUEDA]) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
 END AS 'MES NOMBRE FECHA BUSQUEDA', 
 FORMAT(DAY([FECHA BUSQUEDA]), '00') AS 'DIA FECHA BUSQUEDA',
 CONCAT(FORMAT(MONTH([FECHA BUSQUEDA]), '00') ,' - ', 
	    CASE MONTH([FECHA BUSQUEDA]) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_BUSQUEDA,
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
 CTE_FACTURACION_TOTAL CABF
UNION ALL
SELECT
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 CABFA.*,
 YEAR([FECHA BUSQUEDA]) AS 'AÑO FECHA BUSQUEDA',
 MONTH([FECHA BUSQUEDA]) AS 'MES AÑO FECHA BUSQUEDA',
 CASE MONTH([FECHA BUSQUEDA])  
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
 END AS 'MES NOMBRE FECHA BUSQUEDA', 
 FORMAT(DAY([FECHA BUSQUEDA]), '00') AS 'DIA FECHA BUSQUEDA',
 CONCAT(FORMAT(MONTH([FECHA BUSQUEDA]), '00') ,' - ', 
	    CASE MONTH([FECHA BUSQUEDA]) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_BUSQUEDA,
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
 CTE_FACTURACION_TOTAL_ANULADA CABFA
