-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewCensoHospitalarioHSJ
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[ViewCensoHospitalarioHSJ]
AS

WITH
CTE_ESTANCIAS
AS
(

SELECT GETDATE() 'FECHA DE BUSQUEDA', ROW_NUMBER () OVER(PARTITION BY EST.NUMINGRES ORDER BY EST.FECINIEST) NUMERO, FUN.UFUDESCRI 'UNIDAD FUNCIONAL',CAM.NUMCAMHOS 'CAMA',ISNULL(EST.IPCODPACI,'CAMA LIBRE') 'IDENTIFICACION', ISNULL(PAC.IPNOMCOMP,'CAMA LIBRE') 'NOMBRE',ISNULL(DATEDIFF(YEAR, PAC.IPFECNACI,GETDATE()),0) 'EDAD',
ISNULL(EST.NUMINGRES,0) 'INGRESO', ISNULL(TIP.DESTIPEST,'CAMA LIBRE') 'ESTANCIA', 
ISNULL(EST.FECINIEST,0) 'FECHA INICIAL', ISNULL(EST.FECFINEST,0)  'FECHA FINAL', CASE EST.REGESTADO WHEN 1 THEN 'CAMA OCUPADA' ELSE 'CAMA LIBRE' END 'ESTADO',
 CASE WHEN FECFINEST='1900-01-01 00:00:00.000' THEN DATEDIFF(DAY, EST.FECINIEST, GETDATE()) ELSE CASE WHEN FECFINEST IS NULL THEN 0 ELSE DATEDIFF(DAY,FECINIEST, FECFINEST) END END'DIAS DE ESTANCIA', 
CASE WHEN PAC.IPCODPACI IS NULL THEN 'CAMA LIBRE' ELSE CASE WHEN HA.Name IS NULL THEN 'SIN DATO' ELSE HA.NAME END END 'ENTIDAD RESPONSABLE',  
ISNULL(TRIM(EST.CODPROSAL)+'-'+PROF.NOMMEDICO,'CAMA LIBRE') 'MEDICO TRATANTE',ISNULL(ESP.DESESPECI,'CAMA LIBRE') 'ESPECIALIDAD'


FROM CHCAMASHO CAM
LEFT JOIN CHREGESTA EST ON CAM.CODICAMAS=EST.CODICAMAS
LEFT JOIN INPACIENT PAC ON PAC.IPCODPACI=EST.IPCODPACI
LEFT JOIN CHTIPESTA TIP ON TIP.CODTIPEST=EST.CODTIPEST
LEFT JOIN INESPECIA ESP ON ESP.CODESPECI=EST.CODESPECI
LEFT JOIN INPROFSAL PROF ON PROF.CODPROSAL=EST.CODPROSAL
LEFT JOIN Contract.HealthAdministrator HA ON HA.ID=PAC.GENCONENTITY
LEFT JOIN INUNIFUNC FUN ON FUN.UFUCODIGO=CAM.UFUCODIGO
)
SELECT *

FROM CTE_ESTANCIAS EST WHERE NUMERO IN (1)