-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewRecienNacidos
-- Extracted by Fabric SQL Extractor SPN v3.9.0




/*******************************************************************************************************************
Nombre: [Report].[ViewRecienNacidos]
Tipo:Vista
Observacion:Pacientes recien nacidos
Profesional: Nilsson Miguel Galindo Lopez
Fecha:25-08-2022
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Vercion 1
Persona que modifico: 
Fecha:
Ovservaciones: 
--------------------------------------
Vercion 2
Persona que modifico:
Fecha:
***********************************************************************************************************************************/

CREATE view [Report].[ViewRecienNacidos]
as

WITH 
CTE_INGRESOS_MADRES AS
(
SELECT ING.NUMINGRES,ING.IPCODPACI,ING.IFECHAING,REC.NUMINGRESHIJO
FROM 
ADINGRESO ING INNER JOIN 
dbo.HCINGRESORECNAC REC ON ING.NUMINGRES=REC.NUMINGRES
),

CTE_OXIGENO AS
(
SELECT 
ROW_NUMBER ( )   
OVER ( PARTITION BY IM.NUMINGRESHIJO  order by IM.NUMINGRESHIJO,FIS.FECREGITE) 'NUMERO', FIS.REGSO2PAC,IM.NUMINGRESHIJO,FIS.FECREGITE,fis.DESOJOPAC
FROM
CTE_INGRESOS_MADRES IM INNER JOIN
dbo.HCEXFISIC FIS ON IM.NUMINGRESHIJO=FIS.NUMINGRES
WHERE FIS.REGSO2PAC!=0
),
CTE_OXIGENO1 AS
(
SELECT * FROM CTE_OXIGENO WHERE NUMERO=1
),
CTE_OXIGENO2 AS
(
SELECT * FROM CTE_OXIGENO WHERE NUMERO=2
)

SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
PAC.IPNOMCOMP AS [NOMBRE MADRE],
PAC.IPCODPACI AS [IDENTIFICACION MADRE],
CASE PAC.IPTIPODOC WHEN 1 THEN 'CC - CEDULA DE CIUDADANIA' 
				   WHEN 2 THEN 'CE - CEDULA DE EXTRANJERIA' 
				   WHEN 3 THEN 'TI - TARJETA DE IDENTIDAD' 
				   WHEN 4 THEN 'RC - REGISTRO CIVIL' 
				   WHEN 5 THEN 'PA - PASAPORTE' 
				   WHEN 6 THEN 'AS - ADULTO SIN IDENTIFICACION' 
				   WHEN 7 THEN 'MS - MENOR SIN IDENTIFICACION' 
				   WHEN 8 THEN 'NU - NUMERO UNICO DE IDENTIFICACIÒN' 
				   WHEN 9 THEN 'NV - CERTIFICADO NACIDO VIVO' 
				   WHEN 10 THEN 'CD - CARNET DIPLOMATICO' 
				   WHEN 11 THEN 'SC - SALVOCONDUCTO' 
				   WHEN 12 THEN 'PE - PERMISO ESPECIAL DE PERMANENCIA' ELSE 'OTRO' END [TIPO IDENTIFICACION],
CAST(PAC.IPFECNACI AS DATE ) AS [FECHA_NACIMIENTO MADRE],
FLOOR((CAST(CONVERT(VARCHAR(8),IM.IFECHAING, 112) AS INT) - CAST(CONVERT(VARCHAR(8),PAC.IPFECNACI, 112) AS INT)) / 10000) AS [EDAD DE LA MADRE],
DEP.NOMDEPART AS DEPARTAMENTO, 
MUN.MUNNOMBRE AS MUNICIPIO,
UB.UBINOMBRE AS UBICACION,
PAC.IPTELEFON AS [TELEFONO],
PAC.IPTELMOVI AS [CELULAR],
EAPB.CODENTIDA AS [CODIGO EAPB],
EAPB.NOMENTIDA AS [NOMBRE EAPB],
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro' 
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado'
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [REGIMEN],
CEN.NOMCENATE AS [CENTRO DE ATENCION],
IM.NUMINGRESHIJO AS [INGRESO DEL HIJO],
FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
RNC.NUMHIJREG AS [NUMERO DE HIJO],
RNC.FECHANACIM AS [FECHA DE NACIMIENTO],
CASE RNC.SEXRECNAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END AS SEXO,
RNC.VITANACIM AS [ESTADO NACIMIENTO],
RNC.RECPERCEF AS [PERIMETRO CEFALICO cm],
RNC.RECPERTOR AS [PERIMETRO TORAXICO cm],
RNC.RECPERABD AS [PERIMETRO ABDOMINAL cm],
RNC.TEMPERREC AS TEMPERATURA,
RNC.FRECARREC AS [FRECUENCIA CARDIACA],
RNC.FRERESREC AS [FRECUENCIA RESPIRATORIA],
OX.REGSO2PAC AS [SATURACION DE OXIGENO 1],
OX.FECREGITE AS [FECHA TOMA DE OXIGENO 1],
OXI.REGSO2PAC AS [SATURACION DE OXIGENO 2],
OXI.FECREGITE AS [FECHA TOMA DE OXIGENO 2],
RNC.APGAR1REC AS [APGAR 1 MINUTO],
RNC.APGAR5REC AS [APGAR 5 MINUTOS],
RNC.APGAR10RN AS [APGAR 10 MINUTOS],
RNC.ADAPRECNA AS [TIPO DE ADAPTACION],
RNC.TALLARECI AS [TALLA cm],
RNC.PESORECNA AS [PESO gr],
RNC.EDADGESNAC AS [EDAD GESTACIONAL],
'SIN DATO' AS [AGUDEZA OJO D],
'SIN DATO' AS [AGUDEZA OJO I],
1 as 'CANTIDAD',
CAST(RNC.FECHISPAC AS date) AS 'FECHA BUSQUEDA',
YEAR(RNC.FECHISPAC) AS 'AÑO FECHA BUSQUEDA',
MONTH(RNC.FECHISPAC) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(RNC.FECHISPAC) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
  END AS 'MES NOMBRE FECHA BUSQUEDA', 
FORMAT(DAY(RNC.FECHISPAC), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(RNC.FECHISPAC), '00') ,' - ', 
	   CASE MONTH(RNC.FECHISPAC) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
--GETDATE() AS ULT_ACTUAL
FROM 
dbo.HCRECINAC RNC /*ON IM.NUMINGRESHIJO=RNC.NUMINGRESHIJO*/ INNER JOIN
DBO.INPACIENT PAC ON RNC.IPCODPACI=PAC.IPCODPACI INNER JOIN
CTE_INGRESOS_MADRES IM ON RNC.IPCODPACI=IM.IPCODPACI INNER JOIN
INUBICACI UB ON PAC.AUUBICACI=UB.AUUBICACI INNER JOIN
INMUNICIP MUN ON UB.DEPMUNCOD = MUN.DEPMUNCOD INNER JOIN
INDEPARTA DEP ON MUN.DEPCODIGO = DEP.DEPCODIGO AND PAC.AUUBICACI = UB.AUUBICACI INNER JOIN
INENTIDAD AS EAPB ON PAC.CODENTIDA=EAPB.CODENTIDA INNER JOIN
dbo.ADCENATEN CEN ON RNC.CODCENATE=CEN.CODCENATE INNER JOIN
dbo.INUNIFUNC FUN ON RNC.UFUCODIGO=FUN.UFUCODIGO LEFT JOIN
CTE_OXIGENO1 OX ON IM.NUMINGRESHIJO=OX.NUMINGRESHIJO LEFT JOIN
CTE_OXIGENO2 OXI ON IM.NUMINGRESHIJO=OXI.NUMINGRESHIJO
--WHERE RNC.FECHANACIM BETWEEN GETDATE() - 400 AND GETDATE ()
--where PAC.IPCODPACI='1123638279'

