-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_V2_FAC_REPORTE_IMAGENES_POR_RECONOCER_HOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[View_V2_FAC_REPORTE_IMAGENES_POR_RECONOCER_HOS]
AS

WITH CTE_IMAGENES_UNICOS
----CTE PARA IDENTIFICAR LOS INGRESOS UNICOS DE IMAGENES QUE ESTAN PENDIENTES DE RECONOCER - HOSPITALARIOS
AS
(
SELECT DISTINCT  ING.NUMINGRES ,ING.IPCODPACI,ING.IESTADOIN
FROM dbo.ADINGRESO ing with (nolock)
	INNER JOIN dbo.HCORDIMAG A with (nolock) ON ing.NUMINGRES = A.NUMINGRES
	INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS
	WHERE ING.TIPOINGRE=2 AND  ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER IS NULL and (A.ESTSERIPS IN ('2','3','4') OR B.SERREASIT='1') AND A.MANEXTPRO ='0'
   UNION ALL
	SELECT DISTINCT ING.NUMINGRES,ING.IPCODPACI,ING.IESTADOIN 
	FROM dbo.HCORDIMAG A with (nolock) 
	INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS 
	INNER JOIN dbo.HCINGRESORECNAC INGMH  with (nolock) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	INNER JOIN dbo.HCRECINAC RN  with (nolock) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	INNER JOIN dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	WHERE ING.TIPOINGRE=2 AND  ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER IS NULL and (A.ESTSERIPS IN ('2','3','4') OR B.SERREASIT='1') AND A.MANEXTPRO ='0'
),

CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
AS
(
    SELECT EGR.IPCODPACI ,EGR.NUMINGRES,EGR.FECINIEST ,EGR.FECFINEST ,EGR.CODICAMAS,CAM.NUMCAMHOS ,FUN.UFUDESCRI  ,FUN.UFUTIPUNI  
	FROM CHREGESTA EGR with (nolock)
	INNER JOIN 
	(
	   SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR with (nolock)
	   INNER JOIN CTE_IMAGENES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G  ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM with (nolock) ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),
CTE_EGRESO_CAMA
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO  
FROM CHREGEGRE EGR
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECEGRESO) EGRESO 
 FROM CHREGEGRE EGR with (nolock) 
 INNER JOIN CTE_IMAGENES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.EGRESO =EGR.FECEGRESO 
),
CTE_ORDENES_CON_IMAGENES_CARGADAS
---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
AS
( 
SELECT RC.AdmissionNumber,G.CUPS ,G.CANTIDAD  FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN
(
SELECT RC.AdmissionNumber ,CUPS.Code CUPS ,SUM(SOD.InvoicedQuantity) CANTIDAD   
FROM Billing .RevenueControlDetail AS RCD WITH (NOLOCK)
INNER JOIN BILLING.REVENUECONTROL AS RC WITH (NOLOCK) ON RCD.REVENUECONTROLID = RC.ID
INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD WITH (NOLOCK) ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2', '3')
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD WITH (NOLOCK) ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN CTE_IMAGENES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =RC.AdmissionNumber  
INNER JOIN Contract .CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id =SOD.CUPSEntityId AND CUPS.ServiceType IN (3)--CUPS.BillingGroupId IN  (11,16)
INNER JOIN Contract .IPSService AS IPS WITH (NOLOCK) ON IPS.Id =SOD.IPSServiceId
GROUP BY RC.AdmissionNumber ,CUPS.Code 
) AS G ON G.AdmissionNumber =RC.AdmissionNumber
),

CTE_DATOS_IMAGENES
---CTE QUE ME TRAE LOS DATOS DE LAS IMAGENES DE FORMA AGRUPADA
AS
(
SELECT ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS ) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA] ,
HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',MIN(COALESCE(A.FECHLECT, A.FECORDMED)) as 'FECHA REALIZADO MINIMA',
MAX(COALESCE(A.FECHLECT, A.FECORDMED)) as 'FECHA REALIZADO MAXIMA'
FROM dbo.ADINGRESO ing with (nolock) 
	INNER JOIN dbo.HCORDIMAG A with (nolock) ON ing.NUMINGRES = A.NUMINGRES
	INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS 
	INNER JOIN dbo.INPROFSAL C with (nolock) ON A.CODPROSAL=C.CODPROSAL 	
	INNER JOIN dbo.INUNIFUNC D with (nolock) ON A.UFUCODIGO=D.UFUCODIGO
	INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI 
	INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id
	INNER JOIN
	(
	    SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS ) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN
	    FROM dbo.ADINGRESO ing with (nolock) 
	    INNER JOIN dbo.HCORDIMAG A ON ing.NUMINGRES = A.NUMINGRES
	    INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
	    INNER JOIN dbo.INPROFSAL C ON A.CODPROSAL=C.CODPROSAL 	
	    INNER JOIN dbo.INUNIFUNC D ON A.UFUCODIGO=D.UFUCODIGO
		INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI 
	    INNER JOIN CTE_IMAGENES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =ING.NUMINGRES 
	    WHERE (A.ESTSERIPS IN ('2','3','4') OR B.SERREASIT='1') AND A.MANEXTPRO ='0'
	    GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =A.CODSERIPS
	WHERE (A.ESTSERIPS IN ('2','3','4') OR B.SERREASIT='1') AND A.GENSERVICEORDER IS NULL AND A.MANEXTPRO ='0'
	GROUP BY ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name, CG.Name ,ING.IFECHAING 
  UNION ALL
   SELECT ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS ) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA] ,
   HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',MIN(COALESCE(A.FECHLECT, A.FECORDMED)) as 'FECHA REALIZADO MINIMA',
   MAX(COALESCE(A.FECHLECT, A.FECORDMED)) as 'FECHA REALIZADO MAXIMA'
   FROM dbo.HCORDIMAG A with (nolock) 
	INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS 
	INNER JOIN dbo.INPROFSAL C with (nolock) ON A.CODPROSAL=C.CODPROSAL 	
	INNER JOIN dbo.INUNIFUNC D with (nolock) ON A.UFUCODIGO=D.UFUCODIGO
	INNER JOIN dbo.HCINGRESORECNAC INGMH  with (nolock) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	INNER JOIN dbo.HCRECINAC RN  with (nolock) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	INNER JOIN dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI
	INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id
	INNER JOIN
	(
	    SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS ) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN
		   FROM dbo.HCORDIMAG A with (nolock) 
	       INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS 
	       INNER JOIN dbo.INPROFSAL C with (nolock) ON A.CODPROSAL=C.CODPROSAL 	
	       INNER JOIN dbo.INUNIFUNC D with (nolock) ON A.UFUCODIGO=D.UFUCODIGO
	       INNER JOIN dbo.HCINGRESORECNAC INGMH  with (nolock) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	       INNER JOIN dbo.HCRECINAC RN  with (nolock) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	       INNER JOIN dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO  
		   INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI
		   INNER JOIN CTE_IMAGENES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =ING.NUMINGRES
		WHERE (A.ESTSERIPS IN ('2','3','4') OR B.SERREASIT='1' ) AND A.MANEXTPRO ='0'
	    GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =A.CODSERIPS
	WHERE (A.ESTSERIPS IN ('2','3','4') OR B.SERREASIT='1') AND A.GENSERVICEORDER IS NULL AND A.MANEXTPRO ='0'
	GROUP BY ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name , CG.Name ,ING.IFECHAING 
),

--SE CREA EL CTE DE JUSTIFICACIONES, PARA QUE ME RETORNE TODOS LOS ORDENAMIENTOS CON ALGUNA JUSTIFIACION.
CTE_RECONOCIMIENTOS_IMAGENES AS
(
SELECT ING.NUMINGRES,ING.NUMEFOLIO,ing.IESTADOIN,ing.[FECHA INGRESO] ,ING.ENTIDAD ,ING.[GRUPO ATENCION]   ,ING.IPCODPACI ,ING.IPNOMCOMP ,ING.CODSERIPS ,ING.DESSERIPS,ING.[CANTIDAD ORDENADA]  ,ING.CANSERIPS,CAM.UFUDESCRI  ,
CAM.NUMCAMHOS,EGR.FECEGRESO,CAR.CUPS 'CUPS CARGADO',CAR.CANTIDAD 'CANTIDAD CARGADA'   ,ING.[FECHA REALIZADO MINIMA] ,ING.[FECHA REALIZADO MAXIMA] 
FROM CTE_DATOS_IMAGENES ING with (nolock) 
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM with (nolock) ON ING.NUMINGRES =CAM.NUMINGRES
LEFT JOIN CTE_EGRESO_CAMA EGR with (nolock) ON EGR.NUMINGRES =ING.NUMINGRES
LEFT JOIN CTE_ORDENES_CON_IMAGENES_CARGADAS CAR with (nolock) ON CAR.AdmissionNumber =ING.NUMINGRES AND CAR.CUPS =ING.CODSERIPS 
WHERE ING.[CANTIDAD ORDENADA] <>ISNULL(CAR.CANTIDAD,0)  AND ING.[CANTIDAD ORDENADA] >ISNULL(CAR.CANTIDAD,0)
AND CAM.UFUTIPUNI NOT IN ('1','19') --AND CAM.NUMCAMHOS NOT LIKE 'U%' AND CAM.NUMCAMHOS NOT LIKE 'O%' AND CAM.NUMCAMHOS NOT LIKE 'SRE%'
--AND CAM.NUMCAMHOS NOT LIKE 'SAL%' AND CAM.NUMCAMHOS NOT LIKE 'PRE%' AND CAM.NUMCAMHOS NOT LIKE 'REC%'
),

CTE_JUSTIFICACIONES AS
(
SELECT DISTINCT IM.NUMINGRES,IM.NUMEFOLIO,IM.CODSERIPS,JUS.Code
FROM 
[Billing].[BillingJustificationControl] JUS INNER JOIN
[Billing].[AccountControlJustification] CON ON JUS.ID=JustificationId INNER JOIN
dbo.HCORDIMAG IM ON CON.EntityId=IM.AUTO AND CON.EntityName='HCORDIMAG'
)
-- SE CREA LA NUEVA CONSULTA UNIENDO EL CTE CON EL CTE_JUSTIFICACIONES PARA QUE NO ME MUESTRE LAS ORDENES QUE SE ENCUENTRAN JUSTIFICADAS
SELECT IM.* 
FROM 
CTE_RECONOCIMIENTOS_IMAGENES IM LEFT JOIN
CTE_JUSTIFICACIONES JUS ON IM.NUMINGRES=JUS.NUMINGRES AND IM.NUMEFOLIO=JUS.NUMEFOLIO AND IM.CODSERIPS=JUS.CODSERIPS
WHERE JUS.Code IS NULL
--FN V2
