-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewNIIFOrdenamientosAmbulatorios
-- Extracted by Fabric SQL Extractor SPN v3.9.0






CREATE VIEW [Report].[ViewNIIFOrdenamientosAmbulatorios] AS

WITH CTE_ORDENAMIENTO AS
 (
  SELECT	
h.UFUDESCRI 'UNIDAD FUNCIONAL',
h.RequestDate 'FECHA ATENCION',
H.ProfessionalCode 'ID PROFESIONAL',
H.NOMMEDICO 'PROFESIONAL',
H.DESESPECI 'ESPECIALIDAD',
ES.CodEspeciaHomologo 'COD ESPECIALIDAD HOMOLOGO',
ES.EspecialidadHomologo 'ESPECIALIDAD HOMOLOGO',
h.[TIPO IDENTIFICACION] ,
h.PatientCode 'IDENTIFICACION',H.IPNOMCOMP ,h.[FECHA DE NACIMIENTO] ,dbo.Edad(p.IPFECNACI, [Common].[GETDATE]()) 'EDAD',H.SEXO ,H.[TELEFONO FIJO] ,H.[TELEFONO MOVIL] ,H.DIRECCION ,
H.AdmissionNumber 'INGRESO',h.CIE10 ,h.DIAGNOSTICO ,h.EntityName 'TIPO DE ORDEN',
h.ItemCodeOriginal 'CODIGO CUPS', 
ISNULL(C.CupsHomologo,h.ItemCodeOriginal)as [CUPS HOMOLOGO],
h.ItemName 'DESCRIPCION SERVICIO',h.Quantity 'CANTIDAD',
h.DescriptionCodeName 'DESCRIPCION RELACIONADA',
h.[INDICACIONES MEDICAS],
ha.Code 'CODIGO ENTIDAD', ha.Name 'ENTIDAD ADMINISTRADORA',
cg.Code 'CODIGO GRUPO ATENCION', 
cg.Name 'GRUPO ATENCION',
IIF(ISNULL(ptc.Id, 0) > 0 OR ISNULL(prd.Id, 0) > 0, 1, 0) 'CUBIERTO',
IIF(ISNULL(ptc.Contracted, 0) = 1 OR ISNULL(prd.Contracted, 0) = 1, 1, 0) 'CONTRATADO',
IIF(ISNULL(ptc.Quoted, 0) = 1 OR ISNULL(prd.Quoted, 0) = 1, 1, 0) 'COTIZADO',
IIF(csa.Id IS NULL, 0, ISNULL(csae.SusceptibleAuthorization, 1)) 'AUTORIZADO'
FROM
(
-- Ordenes de imagenes ambulatorias
SELECT	
'IMAGENES' EntityName, 
h.AUTO EntityId,		
h.CODCENATE CareCenterCode, 
h.UFUCODIGO FunctionalUnitCode,
h.NUMINGRES AdmissionNumber,
h.NUMEFOLIO Folio,
h.IPCODPACI PatientCode,
h.FECORDMED RequestDate, 
h.CODPROSAL ProfessionalCode,
h.CANSERIPS Quantity,
1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,ce.Description ItemName,
cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,
UNI.UFUDESCRI,
SAL.NOMMEDICO ,
ESP.DESESPECI,
ESP.CODESPECI,
CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' 
				   WHEN '2' THEN 'CE' 
				   WHEN '3' THEN 'TI' 
				   WHEN '4' THEN 'RC'
				   WHEN '5' THEN 'PA' WHEN '6' THEN 'AS' WHEN '7' THEN 'MS' WHEN '8' THEN 'NU'
				   WHEN '9' THEN 'CN' WHEN '10' THEN 'CD'WHEN '11' THEN 'SC' WHEN '12' THEN 'PE'
				   WHEN '13' THEN 'PT' WHEN '14' THEN 'DE' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
PAC.IPNOMCOMP ,
CAST(PAC.IPFECNACI AS DATE) 'FECHA DE NACIMIENTO',
CASE PAC.IPSEXOPAC  WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END 'SEXO',PAC.IPTELEFON 'TELEFONO FIJO',
PAC.IPTELMOVI 'TELEFONO MOVIL',RTRIM(PAC.IPDIRECCI)  'DIRECCION',HIS.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',HIS.INDICAMED 'INDICACIONES MEDICAS',
h.OBSSERIPS Observations
FROM .HCORDIMAG h
INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
INNER JOIN HCHISPACA AS HIS WITH (NOLOCK) ON HIS.NUMINGRES =H.NUMINGRES AND HIS.NUMEFOLIO =H.NUMEFOLIO 
INNER JOIN INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =HIS.IPCODPACI
INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =H.UFUCODIGO 
INNER JOIN DBO.INPROFSAL AS SAL WITH (NOLOCK) ON SAL.CODPROSAL =HIS.CODPROSAL 
INNER JOIN INDIAGNOS AS DIA  WITH (NOLOCK) ON DIA.CODDIAGNO =HIS.CODDIAGNO --  AND DIA.CODDIAPRI = 1 
INNER JOIN INESPECIA AS ESP  WITH (NOLOCK) ON ESP.CODESPECI =SAL.CODESPEC1 
LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id 
WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('6'))
UNION ALL
	-- Ordenes de laboratorios ambulatorios
	        SELECT	'LABORATORIOS' EntityName, h.AUTO EntityId,		h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
            h.IPCODPACI PatientCode,h.FECORDMED RequestDate, h.CODPROSAL ProfessionalCode,h.CANSERIPS Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
            ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,
            UNI.UFUDESCRI,
            SAL.NOMMEDICO ,
            ESP.DESESPECI,
			ESP.CODESPECI,
			CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI' WHEN '4' THEN 'RC'WHEN '5' THEN 'PA' WHEN '6' THEN 'AS' WHEN '7' THEN 'MS' WHEN '8' THEN 'NU'
            WHEN '9' THEN 'CN' WHEN '10' THEN 'CD'WHEN '11' THEN 'SC' WHEN '12' THEN 'PE'WHEN '13' THEN 'PT' WHEN '14' THEN 'DE' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
			PAC.IPNOMCOMP ,
			CAST(PAC.IPFECNACI AS DATE) 'FECHA DE NACIMIENTO',CASE PAC.IPSEXOPAC  WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END 'SEXO',PAC.IPTELEFON 'TELEFONO FIJO',
			PAC.IPTELMOVI 'TELEFONO MOVIL',RTRIM(PAC.IPDIRECCI)  'DIRECCION',HIS.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',HIS.INDICAMED 'INDICACIONES MEDICAS',
			h.OBSSERIPS Observations
	FROM .HCORDLABO h
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN HCHISPACA AS HIS WITH (NOLOCK) ON HIS.NUMINGRES =H.NUMINGRES AND HIS.NUMEFOLIO =H.NUMEFOLIO 
	INNER JOIN INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =HIS.IPCODPACI
	INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =H.UFUCODIGO 
	INNER JOIN DBO.INPROFSAL AS SAL WITH (NOLOCK) ON SAL.CODPROSAL =HIS.CODPROSAL 
	INNER JOIN INDIAGNOS AS DIA  WITH (NOLOCK) ON DIA.CODDIAGNO =HIS.CODDIAGNO --  AND DIA.CODDIAPRI = 1 
	INNER JOIN INESPECIA AS ESP  WITH (NOLOCK) ON ESP.CODESPECI =SAL.CODESPEC1
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id 
	WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('6'))
UNION ALL
	-- Ordenes de patologias ambulatorias
	        SELECT	'PATOLOGIAS' EntityName, h.AUTO EntityId,		
			h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,
			h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
            h.IPCODPACI PatientCode,h.FECORDMED RequestDate, h.CODPROSAL ProfessionalCode,h.CANSERIPS Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
            ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,
            UNI.UFUDESCRI,
            SAL.NOMMEDICO ,
            ESP.DESESPECI,
			ESP.CODESPECI,
			CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI' WHEN '4' THEN 'RC'WHEN '5' THEN 'PA' WHEN '6' THEN 'AS' WHEN '7' THEN 'MS' WHEN '8' THEN 'NU'
            WHEN '9' THEN 'CN' WHEN '10' THEN 'CD'WHEN '11' THEN 'SC' WHEN '12' THEN 'PE'WHEN '13' THEN 'PT' WHEN '14' THEN 'DE' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
			PAC.IPNOMCOMP ,
			CAST(PAC.IPFECNACI AS DATE) 'FECHA DE NACIMIENTO',CASE PAC.IPSEXOPAC  WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END 'SEXO',PAC.IPTELEFON 'TELEFONO FIJO',
			PAC.IPTELMOVI 'TELEFONO MOVIL',RTRIM(PAC.IPDIRECCI)  'DIRECCION',HIS.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',HIS.INDICAMED 'INDICACIONES MEDICAS',
			h.OBSSERIPS Observations
	FROM .HCORDPATO h
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN HCHISPACA AS HIS WITH (NOLOCK) ON HIS.NUMINGRES =H.NUMINGRES AND HIS.NUMEFOLIO =H.NUMEFOLIO 
	INNER JOIN INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =HIS.IPCODPACI
	INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =H.UFUCODIGO 
	INNER JOIN DBO.INPROFSAL AS SAL WITH (NOLOCK) ON SAL.CODPROSAL =HIS.CODPROSAL 
	INNER JOIN INDIAGNOS AS DIA  WITH (NOLOCK) ON DIA.CODDIAGNO =HIS.CODDIAGNO --  AND DIA.CODDIAPRI = 1 
	INNER JOIN INESPECIA AS ESP  WITH (NOLOCK) ON ESP.CODESPECI =SAL.CODESPEC1
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id 
	WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('6'))
UNION ALL
	-- Ordenes de interconsultas ambulatorias
	        SELECT	'INTERCONSULTAS' EntityName, h.AUTO EntityId,		h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
            h.IPCODPACI PatientCode,h.FECORDMED RequestDate, h.CODPROSAL ProfessionalCode,h.CANSERIPS Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
            ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,
            UNI.UFUDESCRI,
            SAL.NOMMEDICO ,
            ESP.DESESPECI,
			ESP.CODESPECI,
			CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI' WHEN '4' THEN 'RC'WHEN '5' THEN 'PA' WHEN '6' THEN 'AS' WHEN '7' THEN 'MS' WHEN '8' THEN 'NU'
            WHEN '9' THEN 'CN' WHEN '10' THEN 'CD'WHEN '11' THEN 'SC' WHEN '12' THEN 'PE'WHEN '13' THEN 'PT' WHEN '14' THEN 'DE' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
			PAC.IPNOMCOMP ,
			CAST(PAC.IPFECNACI AS DATE) 'FECHA DE NACIMIENTO',CASE PAC.IPSEXOPAC  WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END 'SEXO',PAC.IPTELEFON 'TELEFONO FIJO',
			PAC.IPTELMOVI 'TELEFONO MOVIL',RTRIM(PAC.IPDIRECCI)  'DIRECCION',HIS.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',HIS.INDICAMED 'INDICACIONES MEDICAS',
			h.OBSSERIPS Observations
	FROM .HCORDINTE h
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN HCHISPACA AS HIS WITH (NOLOCK) ON HIS.NUMINGRES =H.NUMINGRES AND HIS.NUMEFOLIO =H.NUMEFOLIO 
	INNER JOIN INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =HIS.IPCODPACI
	INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =H.UFUCODIGO 
	INNER JOIN DBO.INPROFSAL AS SAL WITH (NOLOCK) ON SAL.CODPROSAL =HIS.CODPROSAL 
	INNER JOIN INDIAGNOS AS DIA  WITH (NOLOCK) ON DIA.CODDIAGNO =HIS.CODDIAGNO --  AND DIA.CODDIAPRI = 1 
	INNER JOIN INESPECIA AS ESP  WITH (NOLOCK) ON ESP.CODESPECI =SAL.CODESPEC1
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id  
	WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('5'))
UNION ALL
	-- Ordenes de procedimientos no Qx ambulatorias
	        SELECT	'PROCEDIMIENTOS NO QX' EntityName, h.AUTO EntityId,		h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
	        h.IPCODPACI PatientCode,h.FECORDMED RequestDate, h.CODPROSAL ProfessionalCode,h.CANSERIPS Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
            ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,
            UNI.UFUDESCRI,
            SAL.NOMMEDICO ,
            ESP.DESESPECI,
			ESP.CODESPECI,
			CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI' WHEN '4' THEN 'RC'WHEN '5' THEN 'PA' WHEN '6' THEN 'AS' WHEN '7' THEN 'MS' WHEN '8' THEN 'NU'
            WHEN '9' THEN 'CN' WHEN '10' THEN 'CD'WHEN '11' THEN 'SC' WHEN '12' THEN 'PE'WHEN '13' THEN 'PT' WHEN '14' THEN 'DE' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
			PAC.IPNOMCOMP ,
			CAST(PAC.IPFECNACI AS DATE) 'FECHA DE NACIMIENTO',CASE PAC.IPSEXOPAC  WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END 'SEXO',PAC.IPTELEFON 'TELEFONO FIJO',
			PAC.IPTELMOVI 'TELEFONO MOVIL',RTRIM(PAC.IPDIRECCI)  'DIRECCION',HIS.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',HIS.INDICAMED 'INDICACIONES MEDICAS',
			h.OBSSERIPS Observations
	FROM .HCORDPRON h
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN HCHISPACA AS HIS WITH (NOLOCK) ON HIS.NUMINGRES =H.NUMINGRES AND HIS.NUMEFOLIO =H.NUMEFOLIO 
	INNER JOIN INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =HIS.IPCODPACI
	INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =H.UFUCODIGO 
	INNER JOIN DBO.INPROFSAL AS SAL WITH (NOLOCK) ON SAL.CODPROSAL =HIS.CODPROSAL 
	INNER JOIN INDIAGNOS AS DIA  WITH (NOLOCK) ON DIA.CODDIAGNO =HIS.CODDIAGNO --  AND DIA.CODDIAPRI = 1 
	INNER JOIN INESPECIA AS ESP  WITH (NOLOCK) ON ESP.CODESPECI =SAL.CODESPEC1
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id  
	WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('5'))
UNION ALL
	-- Ordenes de procedimientos Qx ambulatorias
	SELECT	'PROCEDIMIENTOS QX' EntityName, h.AUTO EntityId,		h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
            h.IPCODPACI PatientCode,h.FECORDMED RequestDate, h.CODPROSAL ProfessionalCode,h.CANSERIPS Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,h.CODSERIPS ItemCodeOriginal,
            ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,
            UNI.UFUDESCRI,
            SAL.NOMMEDICO ,
            ESP.DESESPECI,
			ESP.CODESPECI,
			CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI' WHEN '4' THEN 'RC'WHEN '5' THEN 'PA' WHEN '6' THEN 'AS' WHEN '7' THEN 'MS' WHEN '8' THEN 'NU'
            WHEN '9' THEN 'CN' WHEN '10' THEN 'CD'WHEN '11' THEN 'SC' WHEN '12' THEN 'PE'WHEN '13' THEN 'PT' WHEN '14' THEN 'DE' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
			PAC.IPNOMCOMP ,
			CAST(PAC.IPFECNACI AS DATE) 'FECHA DE NACIMIENTO',CASE PAC.IPSEXOPAC  WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END 'SEXO',PAC.IPTELEFON 'TELEFONO FIJO',
			PAC.IPTELMOVI 'TELEFONO MOVIL',RTRIM(PAC.IPDIRECCI)  'DIRECCION',HIS.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',HIS.INDICAMED 'INDICACIONES MEDICAS',
			h.OBSSERIPS Observations
	FROM .HCORDPROQ h
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN HCHISPACA AS HIS WITH (NOLOCK) ON HIS.NUMINGRES =H.NUMINGRES AND HIS.NUMEFOLIO =H.NUMEFOLIO 
	INNER JOIN INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =HIS.IPCODPACI
	INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =H.UFUCODIGO 
	INNER JOIN DBO.INPROFSAL AS SAL WITH (NOLOCK) ON SAL.CODPROSAL =HIS.CODPROSAL 
	INNER JOIN INDIAGNOS AS DIA  WITH (NOLOCK) ON DIA.CODDIAGNO =HIS.CODDIAGNO --  AND DIA.CODDIAPRI = 1 
	INNER JOIN INESPECIA AS ESP  WITH (NOLOCK) ON ESP.CODESPECI =SAL.CODESPEC1
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id  
	WHERE h.MANEXTPRO = 1 AND NOT (h.ESTSERIPS IN ('3'))
UNION ALL
	-- Hemocomponentes
	SELECT 'HEMOCOMPONENTES' EntityName, h.ID EntityId,		h.CODCENATE CareCenterCode, ing.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
            h.IPCODPACI PatientCode,h.FECORDMED RequestDate, '' ProfessionalCode,hd.Quantity Quantity,1 Type,ce.Id ItemId,ce.Code ItemCode,hd.CODSERIPS ItemCodeOriginal,
            ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,
            UNI.UFUDESCRI,
            SAL.NOMMEDICO ,
            ESP.DESESPECI,
			ESP.CODESPECI,
			CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI' WHEN '4' THEN 'RC'WHEN '5' THEN 'PA' WHEN '6' THEN 'AS' WHEN '7' THEN 'MS' WHEN '8' THEN 'NU'
            WHEN '9' THEN 'CN' WHEN '10' THEN 'CD'WHEN '11' THEN 'SC' WHEN '12' THEN 'PE'WHEN '13' THEN 'PT' WHEN '14' THEN 'DE' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
			PAC.IPNOMCOMP ,
			CAST(PAC.IPFECNACI AS DATE) 'FECHA DE NACIMIENTO',CASE PAC.IPSEXOPAC  WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END 'SEXO',PAC.IPTELEFON 'TELEFONO FIJO',
			PAC.IPTELMOVI 'TELEFONO MOVIL',RTRIM(PAC.IPDIRECCI)  'DIRECCION',HIS.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',HIS.INDICAMED 'INDICACIONES MEDICAS',
			'' Observations
	FROM .ADINGRESO ing
	JOIN .HCORHEMCO h ON ing.NUMINGRES = h.NUMINGRES
	JOIN 
	(
		SELECT	hd.HCORHEMCOID, 
				hd.CODSERIPS, 
				hd.TraceabilityPaperworkId, 
				hd.TraceabilityPaperworkEventsId, 
				hd.IDDESCRIPCIONRELACIONADA,
				COUNT(1) Quantity
		FROM .HCORHEMSER hd
		WHERE hd.ESTADO NOT IN (3)
		GROUP BY hd.HCORHEMCOID, hd.CODSERIPS, hd.TraceabilityPaperworkId, hd.TraceabilityPaperworkEventsId, hd.IDDESCRIPCIONRELACIONADA
	) hd ON h.ID = hd.HCORHEMCOID
	JOIN Contract.CUPSEntity ce ON hd.CODSERIPS = ce.Code
	INNER JOIN HCHISPACA AS HIS WITH (NOLOCK) ON HIS.NUMINGRES =H.NUMINGRES AND HIS.NUMEFOLIO =H.NUMEFOLIO 
	INNER JOIN INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =HIS.IPCODPACI
	INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =HIS.UFUCODIGO 
	INNER JOIN DBO.INPROFSAL AS SAL WITH (NOLOCK) ON SAL.CODPROSAL =HIS.CODPROSAL 
	INNER JOIN INDIAGNOS AS DIA  WITH (NOLOCK) ON DIA.CODDIAGNO =HIS.CODDIAGNO --  AND DIA.CODDIAPRI = 1 
	INNER JOIN INESPECIA AS ESP  WITH (NOLOCK) ON ESP.CODESPECI =SAL.CODESPEC1
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND hd.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id  
	WHERE h.MANEXTPRO = 1
UNION ALL
	-- Ordenes de control por la especialidad que atendió al paciente
	SELECT	'CONTROLES' EntityName, h.AUTO EntityId,		
	h.CODCENATE CareCenterCode, 
	h.UFUCODIGO FunctionalUnitCode,
	h.NUMINGRES AdmissionNumber,
	h.NUMEFOLIO Folio,
     h.IPCODPACI PatientCode,
	 hc.FECHISPAC RequestDate, 
	 hc.CODPROSAL ProfessionalCode,1 Quantity,1 Type,			
	 ce.Id ItemId,
	 ce.Code ItemCode,
	 h.CODSERIPS ItemCodeOriginal,
            ce.Description ItemName,cecd.Id ContractDescriptionId,cd.Id DescriptionId,CONCAT(cd.Code, ' - ', cd.Name) DescriptionCodeName,
            UNI.UFUDESCRI,
            SAL.NOMMEDICO ,
            ESP.DESESPECI,
			ESP.CODESPECI,
			CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI' WHEN '4' THEN 'RC'WHEN '5' THEN 'PA' WHEN '6' THEN 'AS' WHEN '7' THEN 'MS' WHEN '8' THEN 'NU'
            WHEN '9' THEN 'CN' WHEN '10' THEN 'CD'WHEN '11' THEN 'SC' WHEN '12' THEN 'PE'WHEN '13' THEN 'PT' WHEN '14' THEN 'DE' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
			PAC.IPNOMCOMP ,
			CAST(PAC.IPFECNACI AS DATE) 'FECHA DE NACIMIENTO',CASE PAC.IPSEXOPAC  WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END 'SEXO',PAC.IPTELEFON 'TELEFONO FIJO',
			PAC.IPTELMOVI 'TELEFONO MOVIL',RTRIM(PAC.IPDIRECCI)  'DIRECCION',HIS.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',HIS.INDICAMED 'INDICACIONES MEDICAS',
			hc.INDICAMED Observations
	FROM dbo.HCHISPACA hc
	INNER JOIN .HCDESCOEX h ON hc.NUMINGRES = h.NUMINGRES AND hc.NUMEFOLIO = h.NUMEFOLIO
	INNER JOIN Contract.CUPSEntity ce ON h.CODSERIPS = ce.Code
	INNER JOIN HCHISPACA AS HIS WITH (NOLOCK) ON HIS.NUMINGRES =H.NUMINGRES AND HIS.NUMEFOLIO =H.NUMEFOLIO 
	INNER JOIN INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =HIS.IPCODPACI
	INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =H.UFUCODIGO 
	INNER JOIN DBO.INPROFSAL AS SAL WITH (NOLOCK) ON SAL.CODPROSAL =HIS.CODPROSAL 
	INNER JOIN INDIAGNOS AS DIA  WITH (NOLOCK) ON DIA.CODDIAGNO =HIS.CODDIAGNO --  AND DIA.CODDIAPRI = 1 
	INNER JOIN INESPECIA AS ESP  WITH (NOLOCK) ON ESP.CODESPECI =SAL.CODESPEC1
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd ON ce.Id = cecd.CUPSEntityId AND h.IDDESCRIPCIONRELACIONADA = cecd.Id
	LEFT JOIN Contract.ContractDescriptions cd ON cecd.ContractDescriptionId = cd.Id
UNION ALL
	-- Medicamentos extramurales
	SELECT	'MEDICAMENTOS' EntityName, h.ID EntityId,		h.CODCENATE CareCenterCode, h.UFUCODIGO FunctionalUnitCode,h.NUMINGRES AdmissionNumber,h.NUMEFOLIO Folio,
            h.IPCODPACI PatientCode,h.FECINIDOS RequestDate, h.CODPROSAL ProfessionalCode,h.CANPEDPRO Quantity,2 Type,ip.Id ItemId,ip.Code ItemCode,h.CODPRODUC ItemCodeOriginal,
            ip.Name ItemName,NULL ContractDescriptionId,NULL DescriptionId,NULL DescriptionCodeName,
            UNI.UFUDESCRI,
            SAL.NOMMEDICO ,
            ESP.DESESPECI,
			ESP.CODESPECI,
			CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI' WHEN '4' THEN 'RC'WHEN '5' THEN 'PA' WHEN '6' THEN 'AS' WHEN '7' THEN 'MS' WHEN '8' THEN 'NU'
            WHEN '9' THEN 'CN' WHEN '10' THEN 'CD'WHEN '11' THEN 'SC' WHEN '12' THEN 'PE'WHEN '13' THEN 'PT' WHEN '14' THEN 'DE' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
			PAC.IPNOMCOMP ,
			CAST(PAC.IPFECNACI AS DATE) 'FECHA DE NACIMIENTO',CASE PAC.IPSEXOPAC  WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END 'SEXO',PAC.IPTELEFON 'TELEFONO FIJO',
			PAC.IPTELMOVI 'TELEFONO MOVIL',RTRIM(PAC.IPDIRECCI)  'DIRECCION',HIS.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',HIS.INDICAMED 'INDICACIONES MEDICAS',
			'' Observations
	FROM .HCPRESCRA h
	INNER JOIN Inventory.ATC atc ON h.CODPRODUC = atc.Code
	INNER JOIN Inventory.InventoryProduct ip ON atc.Id = ip.ATCId
	INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =H.UFUCODIGO 
	INNER JOIN HCHISPACA AS HIS WITH (NOLOCK) ON HIS.NUMINGRES =H.NUMINGRES AND HIS.NUMEFOLIO =H.NUMEFOLIO 
	INNER JOIN INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =HIS.IPCODPACI
	INNER JOIN DBO.INPROFSAL AS SAL WITH (NOLOCK) ON SAL.CODPROSAL =HIS.CODPROSAL 
	INNER JOIN INDIAGNOS AS DIA  WITH (NOLOCK) ON DIA.CODDIAGNO =HIS.CODDIAGNO --  AND DIA.CODDIAPRI = 1 
	INNER JOIN INESPECIA AS ESP  WITH (NOLOCK) ON ESP.CODESPECI =SAL.CODESPEC1

	WHERE h.MANEXTPRO = 1
) h
JOIN .ADCENATEN cc ON h.CareCenterCode = cc.CODCENATE
JOIN .INUNIFUNC fu ON h.FunctionalUnitCode = fu.UFUCODIGO
JOIN .ADINGRESO ing ON h.AdmissionNumber = ing.NUMINGRES
JOIN Contract.CareGroup cg ON ing.GENCAREGROUP = cg.Id
JOIN Contract.HealthAdministrator ha ON ing.GENCONENTITY = ha.Id
JOIN .INPACIENT p ON h.PatientCode = p.IPCODPACI
LEFT JOIN Contract.ProcedureCups ptc ON h.Type = 1 AND cg.ProcedureTemplateId = ptc.ProceduresTemplateId AND h.ItemId = ptc.CupsId AND ISNULL(h.ContractDescriptionId, 0) = ISNULL(ptc.CUPSEntityContractDescriptionId, 0)
LEFT JOIN 
	(
	SELECT	prd.ProductRateId, prd.ProductId, 
	MAX(prd.Id) Id, MAX(IIF(prd.Contracted = 1, 1, 0)) Contracted, MAX(IIF(prd.Quoted = 1, 1, 0)) Quoted,
	MIN(prd.InitialDate) InitialDate, MAX(prd.EndDate) EndDate
	FROM Inventory.ProductRateDetail prd
	GROUP BY prd.ProductRateId, prd.ProductId
	) prd ON h.Type = 2 AND cg.ProductRateId = prd.ProductRateId AND h.ItemId = prd.ProductId AND CAST(h.RequestDate AS DATE) BETWEEN prd.InitialDate AND prd.EndDate
LEFT JOIN
(
	SELECT	csa.Id,
			apcc.CareCenterCode, 		
			1 Type, 
			apce.CUPSEntityId ItemId,
			apce.ContractDescriptionId DescriptionId,
			apce.AuthorizationGroupId
	FROM [Authorization].AuthorizationPortfolioCareCenter apcc
	JOIN [Authorization].AuthorizationPortfolio ap ON apcc.AuthorizationPortfolioId = ap.Id
	JOIN [Authorization].AuthorizationPortfolioCUPSEntity apce ON ap.Id = apce.AuthorizationPortfolioId
	JOIN [Authorization].ConfigurationServicesAmbulatory csa ON apce.Id = csa.AuthorizationPortfolioCUPSEntityId
	WHERE ap.Status = 1
UNION ALL
	SELECT	csa.Id,
			apcc.CareCenterCode, 		
			2 Type, 
			apip.InventoryProductId ItemId,
			NULL DescriptionId,
			apip.AuthorizationGroupId
	FROM [Authorization].AuthorizationPortfolioCareCenter apcc
	JOIN [Authorization].AuthorizationPortfolio ap ON apcc.AuthorizationPortfolioId = ap.Id
	JOIN [Authorization].AuthorizationPortfolioInventoryProduct apip ON ap.Id = apip.AuthorizationPortfolioId
	JOIN [Authorization].ConfigurationServicesAmbulatory csa ON apip.Id = csa.AuthorizationPortfolioCUPSEntityId
	WHERE ap.Status = 1
) csa ON h.CareCenterCode = csa.CareCenterCode AND h.Type = csa.Type AND h.ItemId = csa.ItemId AND ISNULL(h.DescriptionId, 0) = ISNULL(csa.DescriptionId, 0)
left join [Authorization].AuthorizationGroup ag on ag.Id = csa.AuthorizationGroupId
LEFT JOIN [Authorization].ConfigurationServicesAmbulatoryExceptions csae ON csa.Id = csae.ConfigurationServicesAmbulatoryId AND cg.Id = csae.CareGroupId
LEFT JOIN [Authorization].ManagementMedicalOrder mmo ON h.EntityName = mmo.EntityName AND h.EntityId = mmo.EntityId AND h.ItemCodeOriginal = mmo.ItemCode
LEFT JOIN .HCHISPACA hc ON h.Folio = hc.NUMEFOLIO AND h.PatientCode = hc.IPCODPACI
left join .INPROFSAL prof on prof.CODPROSAL = h.ProfessionalCode LEFT JOIN
Report.HomologoCUPS c ON h.ItemCodeOriginal=C.CUPS left join
[Report].HomologoEspecialidades es on H.CODESPECI=ES.CodEspecia
WHERE  mmo.Id IS NULL OR (mmo.Status = 1) 
)

SELECT 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 *,
CAST([FECHA ATENCION] AS date) AS 'FECHA BUSQUEDA',
YEAR([FECHA ATENCION]) AS 'AÑO FECHA BUSQUEDA',
MONTH([FECHA ATENCION]) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH([FECHA ATENCION]) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
  END AS 'MES NOMBRE FECHA BUSQUEDA', 
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
CTE_ORDENAMIENTO 


--SELECT * FROM Contract.CUPSEntity
