-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewQxAgenda
-- Extracted by Fabric SQL Extractor SPN v3.9.0












/*******************************************************************************************************************
Nombre: [Report].[ViewQxAgenda]
Tipo:Vista
Observacion:Informe de la agenda de procedimientos QX
Profesional: 
Fecha:
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha:12-04-2023
Ovservaciones: Se cambia la logica de la union de la tala dbo.HCORDPRON no con el campo ipcodpaci sino con numingres y se adiciona el campo id de agenda a petición de HOMI descrito en el ticket 8991
--------------------------------------
Version 3
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:26-06-2023
Observaciones:Se agrega el campo de Observaciones de la agenda, y prioridad, esto solicitado en el ticket 10677 para HOMI
--------------------------------------
Version 4
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:28-06-2023
Observaciones:Se agrega el Ttipo de procedimiento, solicitado por San Jose
--------------------------------------
Version 5
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:26-10-2023
Observaciones:Se agregan los camps de duración total de los procedimientos y datos de la radicación.
***********************************************************************************************************************************/

CREATE VIEW [Report].[ViewQxAgenda] AS

WITH
CTE_DURACION_QX AS
(
SELECT
IDAGENDA,
IPCODPACI,
SUM(DURPROCQX) AS TIEMPO
FROM DBO.AGEPROGQX WHERE CODESTPQX!=6
GROUP BY IDAGENDA,IPCODPACI
)
SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
   CASE INP.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' 
					WHEN '2' THEN 'CEDULA DE EXTRANJERIA' 
					WHEN '3' THEN 'TARJETA DE IDENTIDAD' 
					WHEN '4' THEN 'REGISTRO CIVIL' 
					WHEN '5' THEN 'PASAPORTE'
					WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' 
					WHEN '7' THEN 'MENOR SIN IDENTIFICACION' 
					WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACIÒN' 
		
		WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' 
					WHEN '10' THEN 'CARNET DIPLOMATICO'
					WHEN '11' THEN 'SALVOCONDUCTO' 
					WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
					WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA'
					WHEN '14' THEN 'DOCUMENTO EXTRANJERO'
					WHEN '15' THEN 'SIN IDENTIFICACION' END AS [TIPO DOCUMENTO],
  INP.IPCODPACI 'ID. PACIENTE',
  INP.IPNOMCOMP 'NOMBRE PACIENTE', 
  CAST(INP.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
  FLOOR((CAST(CONVERT(VARCHAR(8), AGEN.FECHORAIN, 112) AS INT) - CAST(CONVERT(VARCHAR(8), INP.IPFECNACI, 112) AS INT)) / 10000) 'EDAD AÑOS',
  DATEDIFF(MONTH,CAST(INP.IPFECNACI AS varchar),CAST (AGEN.FECHORAIN AS DATE)) 'EDAD MESES',
  CASE INP.IPSEXOPAC WHEN 1 THEN 'Masculino' WHEN 2 THEN 'Femenino' END AS SEXO,
  INP.IPDIRECCI AS DIRECCION,
  INP.IPTELEFON AS [TELEFONO FIJO],
  INP.IPTELMOVI AS [MOVIL],
    CASE INP.IPTIPOPAC WHEN 1 THEN 'Contributivo'
					 WHEN 2 THEN 'Subsidiado' 
					 WHEN 3 THEN 'Vinculado'
					 WHEN 4 THEN 'Particular'
					 WHEN 5 THEN 'Otro'
					 WHEN 6 THEN 'Desplazado Reg. Contributivo'
					 WHEN 7 THEN 'Desplazado Reg. Subsidiado'
	
	WHEN 8 THEN 'Desplazado No Asegurado' END AS REGIMEN,
  RTRIM(IDE.CODENTIDA)+'-'+IDE.NOMENTIDA AS ESTIDAD,
  AGEN.CODSERIPS 'CUPS AGENDADO',
  AGEN.CODAUTONU AS [ID AGENDA],
  GRU.Grupoqx AS [GRUPO QX],
  PRO.NOMMEDICO AS [CIRUJANO],
  INE.DESESPECI AS [ESPECIALIDAD MEDICO],
/*IN V4*/AGEN.FECREGSIS [FECHA AGENDAMIENTO],/*FN V4*/
  CASE AGEN.PRINCIPAL WHEN 1 THEN 'PRINCIPAL' ELSE 'SECUNDARIO' END AS [TIPO DE PROCEDIMIENTO],
  AGEN.CODSERIPS 'PROC. QX. ORDENADO',
  CUPS.DESCODCUPS 'NOMBRE PROCEDIMIENTO', 
  CUPS2.Code 'CUPS PROCEDIMIENTO RELACIONADO',
  CUPS2.Description 'NOMBRE PROCEDIMIENTO RELACIONADO', 
  CASE WHEN AGEN.ORIGENQX=1 THEN 'Ambulatorio' ELSE 'Hospitalario' END 'AMBITO',
  CASE AGEN.TIPOANESTESIA WHEN 1 THEN 'Local'
						  WHEN 2 THEN 'Regional'
						  WHEN 3 THEN 'General'
						  WHEN 4 THEN 'Combinada'
						  WHEN 5 THEN 'No Aplica' END [TIPO ANESTESIA],
/*IN V3*/CASE ORD.PRISERIPS WHEN 1 THEN 'EMERGENCIA'
							WHEN 2 THEN 'URGENCIA'
							WHEN 3 THEN 'NORMAL'
							WHEN 4 THEN 'DEFINIR CONDUCTA' END AS PRIORIDAD,/*FN V3*/
  ISNULL(Rtrim(FUN.UFUCODIGO)+' - '+FUN.UFUDESCRI,RTRIM(FUN2.UFUCODIGO)+'-'+FUN2.UFUDESCRI) AS [UNIDAD SOLICITUD],
  CASE WHEN AGEN.ESTADOFARM=1 THEN 'Pendiente Confirmacion' 
       ELSE 'Solicitado a Farmacia' END 'ESTADO PAQUETE QX', 
  CAST(AGEN.FECHORAIN AS DATE) 'FECHA CITA',AGEN.FECHORAIN 'INICIA CX', AGEN.FECHORAFI 'FIN CX',
  AGEN.DURPROCQX 'DURACION',
  TI.TIEMPO AS [DURACION TOTAL],
  CASE AGEN.CODESTPQX WHEN 0 THEN 'Cirugia Programada'
					  WHEN 1 THEN 'Paciente admitido (Cirugia Origen Ambulatoria)' 
					  WHEN 2 THEN 'Paciente en sala de espera' 
					  WHEN 3 THEN 'Paciente en sala quirurgica'
					  WHEN 4 THEN 'Paciente en recuperación' 
					  WHEN 5 THEN 'Paciente con alta' 
					  WHEN 6 THEN 'Anulado - Cancelada' END 'ESTADO PROGRAMACION', 
  AGEN.NUMAUTORI 'AUTORIZACION', 
  ISNULL(AGEN.NUMINGRES,ORD.NUMINGRES) 'INGRESO',
  CAM.NUMCAMHOS AS [CAMA ACTUAL],
  CASE WHEN DATEPART(HOUR,AGEN.FECHORAIN) BETWEEN '07' AND '11' THEN 'Mañana'
   WHEN DATEPART(HOUR,AGEN.FECHORAIN) BETWEEN '12' AND '18' THEN 'Tarde'
   WHEN DATEPART(HOUR,AGEN.FECHORAIN) BETWEEN '19' AND '06' THEN 'Noche' 
  END 'JORNADA',SALA.DESCRIPSAL 'SALA', 
  /*IN V3*/AGEN.OBSERVACION,/*FN V3*/
  /*IN V4*/IIF(AGEN.CODESTPQX!=6,RAD.NUMRADICACION,NULL) AS [# RADICACIÓN],
  IIF(AGEN.CODESTPQX!=6,RAD.FECHACONFIRMACION,NULL) AS [FECHA RADICACION],
  IIF(AGEN.CODESTPQX!=6,CASE RAD.ESTADO WHEN 1 THEN 'RADICADO'
										WHEN 2 THEN 'CONFIRMADO' END,NULL) AS [ESTADO RADICACIÓN],
  IIF(AGEN.CODESTPQX!=6,USU.NOMUSUARI,NULL) AS [USUARIO RADICACION],/*FN V4*/
  AGEN.FECHACAN 'FECHA CANCELACION', 
  AGEN.CODCAUCAN  'COD. CAUSA CANCELACION',
  CAN.DESCAUCAN 'DESCRIPCION CAUSA',
  1 as 'CANTIDAD',
CAST(AGEN.FECHORAIN AS DATE) AS 'FECHA BUSQUEDA', 
YEAR(AGEN.FECHORAIN) AS 'AÑO FECHA BUSQUEDA', 
MONTH(AGEN.FECHORAIN) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(AGEN.FECHORAIN)
     WHEN 1 THEN 'ENERO'
	 WHEN 2 THEN 'FEBRERO'
	 WHEN 3 THEN 'MARZO'
	 WHEN 4 THEN 'ABRIL'
	 WHEN 5 THEN 'MAYO'
	 WHEN 6 THEN 'JUNIO'
	 WHEN 7 THEN 'JULIO'
	 WHEN 8 THEN 'AGOSTO'
	 WHEN 9 THEN 'SEPTIEMBRE'
	 WHEN 10 THEN 'OCTUBRE'
	 WHEN 11 THEN 'NOVIEMBRE'
	 WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA', 
FORMAT(DAY(AGEN.FECHORAIN), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(AGEN.FECHORAIN), '00') ,' - ', 
	   CASE MONTH(AGEN.FECHORAIN) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_INGRESO,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
 FROM 
  DBO.AGEPROGQX AGEN 
  INNER JOIN DBO.INPACIENT INP ON INP.IPCODPACI = AGEN.IPCODPACI 
  INNER JOIN DBO.INENTIDAD IDE ON INP.CODENTIDA=IDE.CODENTIDA
  INNER JOIN dbo.INPROFSAL PRO ON AGEN.CODPROSAL = PRO.CODPROSAL
  INNER JOIN dbo.INESPECIA INE ON PRO.CODESPEC1 = INE.CODESPECI
  INNER JOIN dbo.INCUPSIPS CUPS ON CUPS.CODGOCUPS = AGEN.CODSERIPS
  LEFT JOIN CTE_DURACION_QX TI ON AGEN.IDAGENDA=TI.IDAGENDA AND AGEN.IPCODPACI=TI.IPCODPACI
  LEFT JOIN/*IN V3*/dbo.HCORDPROQ ORD ON AGEN.AUTOHCORDPROQ=ORD.AUTO
  LEFT JOIN DBO.ADINGRESO ING ON ING.NUMINGRES = ISNULL(AGEN.NUMINGRES,ORD.NUMINGRES)
  LEFT JOIN dbo.CHCAMASHO CAM ON ING.CODCAMACT=CAM.CODICAMAS
  LEFT JOIN Contract.CUPSEntityContractDescriptions CUPSREL ON CUPSREL.Id = AGEN.IDDESCRIPCIONRELACIONADA
  LEFT JOIN Contract.CUPSEntity CUPS2 ON CUPSREL.Id = CUPS2.Id
  LEFT JOIN DBO.AGCACANQX CAN ON CAN.CODCACANQ=AGEN.CODCAUCAN 
  LEFT JOIN dbo.HCORDPROQ QX ON AGEN.AUTOHCORDPROQ=QX.AUTO
  LEFT JOIN dbo.HCORDPRON NOQ ON AGEN.NUMINGRES=NOQ.NUMINGRES AND NOQ.CODSERIPS=AGEN.CODSERIPS AND NOQ.FECORDMED<AGEN.FECHORAIN
  LEFT JOIN dbo.INUNIFUNC FUN ON QX.UFUCODIGO=FUN.UFUCODIGO
  LEFT JOIN DBO.INUNIFUNC FUN2 ON FUN2.UFUCODIGO=NOQ.UFUCODIGO
  LEFT JOIN AGENSALAC SALA ON SALA.CODCONCEC=AGEN.AGENSALAC 
  LEFT JOIN Report.GruposQX GRU ON AGEN.CODSERIPS=GRU.Code
  LEFT JOIN dbo.ADRADICACIONQX RAD ON AGEN.IDRADICACIONQX=RAD.ID AND RAD.ESTADO!=3
  LEFT JOIN dbo.SEGusuaru USU ON RAD.USUARIOCONFIRMACION=USU.CODUSUARI
  --WHERE INP.IPCODPACI='1017062184'
