-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewConsultationMorbidityEDA
-- Extracted by Fabric SQL Extractor SPN v3.9.0



/*******************************************************************************************************************
Nombre: [Report].[ViewConsultationMorbidityEDA]
Tipo:Vista
Observacion: Vista con diagnosticos de infeccion de trato digestivo ocacionado por virus o infeccion, que proboca diarreas EDA)
Profesional:
Fecha:
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico:Nilsson Miguel Galiundo Lopez
Fecha:09-06-2023
Observaciones: Se modifican los Dx para eda pasando de tener en cuenta 3 a 61 Dx
--------------------------------------
_________________________________________________________________________
Version 3
Persona que modifico:Amira Gil Meneses
Observación: Se realiza CTE para los Diagnosticos Relacionados
Fecha: 31-07-2023
***********************************************************************************************************************************/

CREATE VIEW [Report].[ViewConsultationMorbidityEDA] as 

WITH TIPO_INFECCION  AS 
 (
  SELECT 
   CODDIAGNO 'DIAGNOSTICO',
   NOMDIAGNO 'DIAG. NOMBRE',
   'EDA' TIPO_INFECCION
  FROM INDIAGNOS
  WHERE CODDIAGNO BETWEEN 'A000' AND 'A09X' --EDA
 ),

CTE_DIAGNOSTICO_RELACIONADOS AS
(
Select 
ROW_NUMBER ( )   
OVER (PARTITION BY IND.IPCODPACI  order by IND.NUMEFOLIO DESC) AS NUMERO,
TP.DIAGNOSTICO,
IND.CODDIAGNO AS [COD DX RELACIONADO],
DG.NOMDIAGNO AS [NOM DX RELACIONADO]
From 
INDIAGNOP IND 
INNER JOIN DBO.INDIAGNOS DG ON IND.CODDIAGNO=DG.CODDIAGNO
INNER JOIN TIPO_INFECCION TP ON TP.DIAGNOSTICO=DG.CODDIAGNO
WHERE IND.CODDIAPRI!=1
),

CTE_CONSULTAS_MORBILIDAD_EDA AS (
 SELECT 
  HA.Name AS 'ENTIDAD',
  HC.FECHISPAC 'FECHA DE ATENCION', 
  INU.UFUDESCRI AS 'NOMBRE UNIDAD FUNCIONAL',
  CASE INP.IPSEXO WHEN 'M' THEN 'FEMENINO' WHEN 'H' THEN 'MASCULINO' END 'SEXO', 
  CASE HC.INDICAPAC WHEN '11' THEN 1 ELSE 0 END AS 'ESTADO_PCTE',
  CAST(HC.FECHISPAC AS DATE) AS 'FECHA HISTORIA CLINICA', 
  YEAR(HC.FECHISPAC) AS 'AÑO HISTORIA CLINICA', 
  MONTH(HC.FECHISPAC) AS 'MES HISTORIA CLINICA', 
  DAY(HC.FECHISPAC) AS 'DIA HISTORIA CLINICA', 
  DATEDIFF(WW, DATEADD(DD, DAY(HC.FECHISPAC) * -1, HC.FECHISPAC) + 1, HC.FECHISPAC) + 1 AS 'SEMANA DEL MES',
  TI.DIAGNOSTICO 'DIAGNOSTICO', 
  TI.[DIAG. NOMBRE],
  DXR.[COD DX RELACIONADO],
  DXR.[NOM DX RELACIONADO],
  CASE HNF.CLASIFICACIONCASO WHEN 1 THEN 1 ELSE 0 END AS 'SOSPECHOSO',
  CASE HNF.CLASIFICACIONCASO WHEN 2 THEN 1 ELSE 0 END AS 'PROBABLE',
  CASE HNF.CLASIFICACIONCASO WHEN 3 THEN 1 ELSE 0 END AS 'CONF.LABORATORIO',
  CASE HNF.CLASIFICACIONCASO WHEN 4 THEN 1 ELSE 0 END AS 'CONF.CLINICO',
  CASE HNF.CLASIFICACIONCASO WHEN 5 THEN 1 ELSE 0 END AS 'CONF.EPIDEIMIOLOGICO',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) < 1 THEN 1 ELSE 0 END AS 'MENORES DE 1',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 1 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 4 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 1 A 4',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 5 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 9 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 5 A 9',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 10 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 14 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 10 A 14',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 15 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 19 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 15 A 19',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 20 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 24 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 20 A 24',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 25 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 29 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 25 A 29',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 30 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 34 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 30 A 34',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 35 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 39 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 35 A 39',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 40 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 44 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 40 A 44',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 45 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 49 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 45 A 49',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 50 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 54 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 50 A 54',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 55 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 59 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 55 A 59',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 60 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 64 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 60 A 64',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 65 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 69 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 65 A 69',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 70 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 74 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 70 A 74',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 75 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 79 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 75 A 79',
  CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 80 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'MAYORES DE 80'
 FROM 
  INDIAGNOP IND
  INNER JOIN TIPO_INFECCION TI ON IND.CODDIAGNO = TI.DIAGNOSTICO --AND IND.CODDIAPRI = 1
  INNER JOIN HCHISPACA HC ON IND.NUMINGRES = HC.NUMINGRES AND IND.IPCODPACI = HC.IPCODPACI AND IND.NUMEFOLIO = HC.NUMEFOLIO
  INNER JOIN CTE_DIAGNOSTICO_RELACIONADOS  AS DXR ON DXR.[COD DX RELACIONADO] = IND.CODDIAGNO ---ESTE
  INNER JOIN INPACIENT INP ON HC.IPCODPACI = INP.IPCODPACI 
  INNER JOIN ADINGRESO AD ON HC.NUMINGRES = AD.NUMINGRES
  INNER JOIN INDIAGNOS INS ON IND.CODDIAGNO = INS.CODDIAGNO 
  INNER JOIN ADCENATEN ADC ON HC.CODCENATE = ADC.CODCENATE
  INNER JOIN INUNIFUNC INU ON HC.UFUCODIGO = INU.UFUCODIGO 
  INNER JOIN INPROFSAL IPR ON HC.CODPROSAL = IPR.CODPROSAL
  INNER JOIN INESPECIA INE ON HC.CODESPTRA = INE.CODESPECI 
  LEFT JOIN dbo.HCFICHANOTIFICACION HNF ON HC.NUMINGRES=HNF.NUMINGRES
  INNER JOIN Contract.HealthAdministrator HA ON HA.Id = AD.GENCONENTITY
 GROUP BY 
  HA.Name, INU.UFUDESCRI, HC.FECHISPAC, INP.IPSEXO, HC.INDICAPAC,
  HNF.TIPOFICHA, HNF.CODEVENTO, IND.NUMINGRES, HNF.CLASIFICACIONCASO, TI.DIAGNOSTICO, 
  TI.[DIAG. NOMBRE], CAST(HC.FECHISPAC AS DATE), DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC), 
  DATEDIFF(WW, DATEADD(DD, DAY(HC.FECHISPAC) * -1, HC.FECHISPAC) + 1, HC.FECHISPAC) + 1,
  DXR.[COD DX RELACIONADO], DXR.[NOM DX RELACIONADO]

)

SELECT 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 [FECHA DE ATENCION],
 ENTIDAD, 
 [NOMBRE UNIDAD FUNCIONAL], 
 [SEXO], 
 CASE WHEN [ESTADO_PCTE]=0 THEN 'NO' WHEN [ESTADO_PCTE]=1 THEN 'SI' ELSE 'NO REPORTA' END [MORATALIDAD],
 [AÑO HISTORIA CLINICA], 
 [MES HISTORIA CLINICA], 
 [SEMANA DEL MES], 
 [DIA HISTORIA CLINICA],
 [DIAGNOSTICO],
 [DIAG. NOMBRE],
 [COD DX RELACIONADO],
 [NOM DX RELACIONADO],
 [SOSPECHOSO],
 [PROBABLE],
 [CONF.LABORATORIO],
 [CONF.CLINICO],
 [CONF.EPIDEIMIOLOGICO],
 SUM([SOSPECHOSO])+ SUM([PROBABLE])+SUM ([CONF.LABORATORIO])+SUM([CONF.CLINICO])+SUM([CONF.EPIDEIMIOLOGICO]) AS 'TOTAL_CLASIFICACION',
 SUM([MENORES DE 1]) AS [MENORES DE 1], 
 SUM([DE 1 A 4]) AS [DE 1 A 4], 
 SUM([DE 5 A 9]) AS [DE 5 A 9],                
 SUM([DE 10 A 14]) AS [DE 10 A 14], 
 SUM([DE 15 A 19]) AS [DE 15 A 19], 
 SUM([DE 20 A 24]) AS [DE 20 A 24], 
 SUM([DE 25 A 29]) AS [DE 25 A 29], 
 SUM([DE 30 A 34]) AS [DE 30 A 34], 
 SUM([DE 35 A 39]) AS [DE 35 A 39], 
 SUM([DE 40 A 44]) AS [DE 40 A 44], 
 SUM([DE 45 A 49]) AS [DE 45 A 49], 
 SUM([DE 50 A 54]) AS [DE 50 A 54], 
 SUM([DE 55 A 59]) AS [DE 55 A 59], 
 SUM([DE 60 A 64]) AS [DE 60 A 64], 
 SUM([DE 65 A 69]) AS [DE 65 A 69], 
 SUM([DE 70 A 74]) AS [DE 70 A 74], 
 SUM([DE 75 A 79]) AS [DE 75 A 79], 
 SUM([MAYORES DE 80]) AS [MAYORES DE 80], 
 SUM([MENORES DE 1]) + SUM([DE 1 A 4]) + SUM([DE 5 A 9]) + SUM([DE 10 A 14]) + SUM([DE 15 A 19]) + SUM([DE 20 A 24]) + 
 SUM([DE 25 A 29]) + SUM([DE 30 A 34]) + SUM([DE 35 A 39]) + SUM([DE 40 A 44]) + SUM([DE 45 A 49]) + SUM([DE 50 A 54]) + 
 SUM([DE 55 A 59]) + SUM([DE 60 A 64]) + SUM([DE 65 A 69]) + SUM([DE 70 A 74]) + SUM([DE 75 A 79]) + SUM([MAYORES DE 80]) AS [TOTAL],
 CAST([FECHA HISTORIA CLINICA] AS date) AS 'FECHA BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM CTE_CONSULTAS_MORBILIDAD_EDA
GROUP BY
 ENTIDAD, [FECHA DE ATENCION], [NOMBRE UNIDAD FUNCIONAL], [SEXO], 
 [ESTADO_PCTE], [AÑO HISTORIA CLINICA], [MES HISTORIA CLINICA], 
 [SEMANA DEL MES], [DIA HISTORIA CLINICA], [SOSPECHOSO],
 [PROBABLE], [CONF.LABORATORIO], [CONF.CLINICO], [CONF.EPIDEIMIOLOGICO],
 [DIAGNOSTICO], [DIAG. NOMBRE], [FECHA HISTORIA CLINICA], [COD DX RELACIONADO],
 [NOM DX RELACIONADO]
