-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: VIEW_RADIOTERAPIA_APLICACIONES
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE view [Report].[VIEW_RADIOTERAPIA_APLICACIONES] as

select * FROM
(
 select 
  CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
  CEN.NOMCENATE 'CENTRO DE ATENCION',HEA.Code 'CODIGO ENTIDAD' ,RTRIM(HEA.Name) 'ENTIDAD',RTRIM(CGR.Name) 'GRUPO DE ATENCION',ORD.IPCODPACI 'IDENTIFICACION',RTRIM(PAC.IPNOMCOMP) 'PACIENTE', 
  ESQ.NUMINGRES 'INGRESO',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO' ,ORD.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',ORD.CODSERIPS 'CUPS',B.DESSERIPS 'DESCRIPCION SERVICIO' ,
  CAST(ORD.FECHAORDEN AS DATE) 'FECHA DE ORDEN' ,
  CASE ORD.ESTADO WHEN 1 THEN 'SOLICITADO' WHEN 2 THEN 'SIMULACION PROGRAMADA' WHEN 3 THEN 'PLANEACION PROGRAMADA' WHEN 4 THEN 'PLANEACION CONFIRMADA' WHEN 5 THEN 'FINALIZADO'
  WHEN 6 THEN 'ANULADO' WHEN 7 THEN 'COMPLETADO' WHEN 8 THEN 'BRAQUITERAPIA INICIADA' END AS 'ESTADO',
  CAST(FECHASIMULA AS DATE) 'FECHA SIMULACION' ,CAST(ORD.FECHAPLANEA AS DATE) 'FECHA PLANEACION', 
  ESQ.DOSTOTAL 'DOSIS TOTAL' ,ESQ.DOSISPORSESION 'DOSIS POR SESION',ESQ.NUMSESION 'NRO DE SESIONES' ,CAST(ESQ.FECHACREA AS DATE) 'FECHA ESQUEMA',
  ROW_NUMBER() OVER(PARTITION BY ORD.IPCODPACI+ESQ.NUMINGRES  ORDER BY DOS.FECHAREGISTRO ASC) AS 'NUMERO DE SESION',CAST(DOS.FECHAREGISTRO AS DATE) 'FECHA APLICACION',
  prof.nommedico AS [PROFESIONAL ORDENO],
  espe.codespeci + ' - ' + espe.desespeci AS ESPECIALIDAD,
  USU.NOMUSUARI  'USUARIO APLICO', DOS.DOSISTUMOR1 ,DOS.DOSISTUMOR2,DOS.DOSISTUMOR3,DOS.DOSISTUMOR4,DOS.DOSISTUMOR5,DOS.DOSISTUMOR6,DOS.TOTALDOSIS ,DOS.OBSERVACION,
  1 as 'CANTIDAD',
  CAST(DOS.FECHAREGISTRO AS date) AS 'FECHA BUSQUEDA',
  YEAR(DOS.FECHAREGISTRO) AS 'AÑO BUSQUEDA',
  MONTH(DOS.FECHAREGISTRO) AS 'MES BUSQUEDA',
  CONCAT(FORMAT(MONTH(DOS.FECHAREGISTRO), '00') ,' - ', 
	   CASE MONTH(DOS.FECHAREGISTRO) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
 FROM DBO.HCRADORDEN ORD 
  INNER JOIN dbo.inprofsal AS prof  ON ORD.codprosal = prof.codprosal
  INNER JOIN dbo.inespecia AS espe  ON prof.codespec1 = espe.codespeci
  INNER JOIN dbo.HCORDPRON AS PRON  ON PRON.AUTO =ORD.IDHCORDPRON
  INNER JOIN dbo.INPACIENT AS PAC  ON PAC.IPCODPACI =ORD.IPCODPACI 
  INNER JOIN dbo.ADCENATEN AS CEN  ON ORD.CODCENATE =CEN.CODCENATE
  INNER JOIN dbo.INCUPSIPS B  ON ORD.CODSERIPS=B.CODSERIPS
  INNER JOIN DBO.INDIAGNOS AS DIA WITH(NOLOCK) ON DIA.CODDIAGNO =ORD.CODDIAGNO 
  LEFT JOIN DBO.HCRADESQUEMAS ESQ  ON ESQ.IDHCRADORDEN = ORD.ID
  LEFT JOIN dbo.ADINGRESO AS ING  ON ESQ.NUMINGRES =ING.NUMINGRES 
  LEFT JOIN DBO.HCRADDOSIS DOS  ON DOS.IDHCRADESQUEMAS = ESQ.ID
  LEFT JOIN Contract .HealthAdministrator HEA  ON ING.GENCONENTITY =HEA.ID
  LEFT JOIN Contract .CareGroup AS CGR  ON ING.GENCAREGROUP =CGR.Id
  LEFT JOIN SEGusuaru AS USU  ON USU.CODUSUARI =DOS.USUARIOREGISTRO 
  WHERE (B.DESSERIPS LIKE '%TELETER%' OR B.DESSERIPS LIKE  '%RADIOCIRUGIA%' )
) RADIO
