-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_V2_FAC_REPORTE_PROCEDIMIENTOS_NO_QX_POR_RECONOCER_HOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [Report].[View_V2_FAC_REPORTE_PROCEDIMIENTOS_NO_QX_POR_RECONOCER_HOS]
AS


WITH CTE_PROCEDIMIENTOS_NO_QX_UNICOS
----CTE PARA IDENTIFICAR LOS INGRESOS UNICOS DE IMAGENES QUE ESTAN PENDIENTES DE RECONOCER - HOSPITALARIOS
AS
(
  SELECT DISTINCT  ING.NUMINGRES ,ING.IPCODPACI,ING.IESTADOIN
	FROM dbo.ADINGRESO ing WITH (NOLOCK)
	INNER JOIN dbo.HCORDPRON A WITH (NOLOCK) ON ing.NUMINGRES = a.NUMINGRES
	INNER JOIN dbo.INCUPSIPS B WITH (NOLOCK) ON A.CODSERIPS=B.CODSERIPS 
	WHERE ING.TIPOINGRE=2 AND  ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER IS NULL AND A.ESTSERIPS NOT IN ('1','5') 
	AND A.CODSERIPS not in ('S55201','S55202','S55203','S55204','S55205','S55206','S55207','S55208','S55209','939403','931001','S55000','933601','931501',
    '937000','937101','937201','937202','937203','937300','937400','938303','938302','933501','893801','903883') AND A.MANEXTPRO ='0'
UNION ALL
	SELECT DISTINCT ING.NUMINGRES,ING.IPCODPACI,ING.IESTADOIN 
	FROM dbo.HCORDPRON A  WITH (NOLOCK) 
	INNER JOIN dbo.INCUPSIPS B WITH (NOLOCK) ON A.CODSERIPS=B.CODSERIPS 
	INNER JOIN dbo.HCINGRESORECNAC INGMH  WITH (NOLOCK) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	INNER JOIN dbo.HCRECINAC RN  WITH (NOLOCK) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	INNER JOIN dbo.ADINGRESO AS ING  WITH (NOLOCK) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	WHERE ING.TIPOINGRE=2 AND  ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER IS NULL AND A.ESTSERIPS NOT IN ('1','5') 
	AND A.CODSERIPS not in ('S55201','S55202','S55203','S55204','S55205','S55206','S55207','S55208','S55209','939403','931001','S55000','933601','931501',
    '937000','937101','937201','937202','937203','937300','937400','938303','938302','933501','893801','903883') AND A.MANEXTPRO ='0'
),
CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
AS
(
    SELECT EGR.IPCODPACI ,EGR.NUMINGRES,EGR.FECINIEST ,EGR.FECFINEST ,EGR.CODICAMAS,CAM.NUMCAMHOS ,FUN.UFUDESCRI  ,FUN.UFUTIPUNI  
	FROM CHREGESTA EGR with (nolock)
	INNER JOIN 
	(
	   SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  
	   FROM CHREGESTA EGR with (nolock)
	   INNER JOIN CTE_PROCEDIMIENTOS_NO_QX_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G  ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM with (nolock) ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),
CTE_EGRESO_CAMA
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO  
FROM CHREGEGRE EGR
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECEGRESO) EGRESO 
 FROM CHREGEGRE EGR with (nolock) 
 INNER JOIN CTE_PROCEDIMIENTOS_NO_QX_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.EGRESO =EGR.FECEGRESO 
),
CTE_ORDENES_CON_PROCEDIMIENTOS_NO_QX_CARGADAS
---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
AS
( 
SELECT RC.AdmissionNumber,G.CUPS ,G.CANTIDAD  FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN
(
SELECT RC.AdmissionNumber ,CUPS.Code CUPS ,SUM(SOD.InvoicedQuantity) CANTIDAD   
FROM Billing.RevenueControlDetail AS RCD WITH (NOLOCK)
INNER JOIN BILLING.REVENUECONTROL AS RC WITH (NOLOCK) ON RCD.REVENUECONTROLID = RC.ID
INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD WITH (NOLOCK) ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2','3')
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD WITH (NOLOCK) ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN CTE_PROCEDIMIENTOS_NO_QX_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =RC.AdmissionNumber  
INNER JOIN Contract.CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id =SOD.CUPSEntityId AND CUPS.ServiceType IN (4,7)--CUPS.BillingGroupId IN (3,4,6,18,19,20,22,23,26)
INNER JOIN Contract .IPSService AS IPS WITH (NOLOCK) ON IPS.Id =SOD.IPSServiceId
GROUP BY RC.AdmissionNumber ,CUPS.Code 
) AS G ON G.AdmissionNumber =RC.AdmissionNumber
),

CTE_DATOS_PROCEDIMIENTOS_NO_QX
---CTE QUE ME TRAE LOS DATOS DE LOS PROCEDIMIENTO NO QX DE FORMA AGRUPADA
AS
(
SELECT 
ING.NUMINGRES,
A.NUMEFOLIO,
A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS) CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA] ,
     HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',MIN(ISNULL(PRO.FECREAPRO,A.FECORDMED)) 'FECHA REALIZADO MINIMA',
	 MAX(ISNULL(PRO.FECREAPRO,A.FECORDMED)) 'FECHA REALIZADO MAXIMA'
 	FROM dbo.ADINGRESO ing WITH (NOLOCK) 
	INNER JOIN dbo.HCORDPRON A WITH (NOLOCK) ON ing.NUMINGRES = a.NUMINGRES
	INNER JOIN dbo.INCUPSIPS B WITH (NOLOCK) ON A.CODSERIPS=B.CODSERIPS 
    INNER JOIN DBO.INPACIENT AS P WITH (NOLOCK) ON P.IPCODPACI =A.IPCODPACI 
	INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id
    INNER JOIN
	(
	    SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS)  'CANTIDAD ORDENADA',UNI.IESTADOIN
		 FROM dbo.ADINGRESO ing WITH (NOLOCK) 
	     INNER JOIN dbo.HCORDPRON A WITH (NOLOCK) ON ing.NUMINGRES = a.NUMINGRES
	     INNER JOIN dbo.INCUPSIPS B WITH (NOLOCK) ON A.CODSERIPS=B.CODSERIPS 
         INNER JOIN DBO.INPACIENT AS P WITH (NOLOCK) ON P.IPCODPACI =A.IPCODPACI 
		 INNER JOIN CTE_PROCEDIMIENTOS_NO_QX_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =ING.NUMINGRES 
	     WHERE A.ESTSERIPS NOT IN ('1','5') AND A.CODSERIPS not in ('S55201','S55202','S55203','S55204','S55205','S55206','S55207','S55208','S55209','939403','931001','S55000','933601','931501',
        '937000','937101','937201','937202','937203','937300','937400','938303','938302','933501','893801','903883') AND A.MANEXTPRO ='0'
	    GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =A.CODSERIPS
	LEFT JOIN HCINFPROM PRO ON PRO.CODSERIPS = A.CODSERIPS AND PRO.NUMINGRES = A.NUMINGRES  AND PRO.NUMEFOLIO =A.NUMEFOLIO 
	WHERE A.ESTSERIPS NOT IN ('1','5') AND A.GENSERVICEORDER IS NULL AND A.CODSERIPS not in ('S55201','S55202','S55203','S55204','S55205','S55206','S55207','S55208','S55209','939403','931001','S55000','933601','931501',
    '937000','937101','937201','937202','937203','937300','937400','938303','938302','933501','893801','903883') AND A.MANEXTPRO ='0'
	GROUP BY ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name , CG.Name ,ING.IFECHAING 
	UNION ALL
   SELECT 
   ING.NUMINGRES,
   A.NUMEFOLIO,
   A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS) CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA] ,
    HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',MIN(ISNULL(PRO.FECREAPRO,A.FECORDMED)) 'FECHA REALIZADO MINIMA',
	 MAX(ISNULL(PRO.FECREAPRO,A.FECORDMED)) 'FECHA REALIZADO MAXIMA'
   	FROM dbo.HCORDPRON A WITH (NOLOCK) 
	INNER JOIN dbo.INCUPSIPS B WITH (NOLOCK) ON A.CODSERIPS=B.CODSERIPS 
	INNER JOIN dbo.HCINGRESORECNAC INGMH  WITH (NOLOCK) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	INNER JOIN dbo.HCRECINAC RN  WITH (NOLOCK) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	INNER JOIN dbo.ADINGRESO AS ING  WITH (NOLOCK) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	INNER JOIN DBO.INPACIENT AS P WITH (NOLOCK) ON P.IPCODPACI =A.IPCODPACI
	INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id
	INNER JOIN
	(
	    SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN
		FROM dbo.HCORDPRON A  WITH (NOLOCK) 
	    INNER JOIN dbo.INCUPSIPS B WITH (NOLOCK) ON A.CODSERIPS=B.CODSERIPS 
	    INNER JOIN dbo.HCINGRESORECNAC INGMH  WITH (NOLOCK) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	    INNER JOIN dbo.HCRECINAC RN  WITH (NOLOCK) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	    INNER JOIN dbo.ADINGRESO AS ING  WITH (NOLOCK) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	    INNER JOIN DBO.INPACIENT AS P WITH (NOLOCK) ON P.IPCODPACI =A.IPCODPACI
		INNER JOIN CTE_PROCEDIMIENTOS_NO_QX_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =ING.NUMINGRES
		WHERE A.ESTSERIPS NOT IN ('1','5') AND A.CODSERIPS not in ('S55201','S55202','S55203','S55204','S55205','S55206','S55207','S55208','S55209','939403','931001','S55000','933601','931501',
        '937000','937101','937201','937202','937203','937300','937400','938303','938302','933501','893801','903883') AND A.MANEXTPRO ='0'
	  GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =A.CODSERIPS
	LEFT JOIN HCINFPROM PRO ON PRO.IPCODPACI = A.IPCODPACI AND PRO.CODSERIPS = A.CODSERIPS AND PRO.NUMINGRES = A.NUMINGRES AND PRO.NUMEFOLIO =A.NUMEFOLIO 
	WHERE A.ESTSERIPS NOT IN ('1','5') AND A.GENSERVICEORDER IS NULL AND A.CODSERIPS not in ('S55201','S55202','S55203','S55204','S55205','S55206','S55207','S55208','S55209','939403','931001','S55000','933601','931501',
    '937000','937101','937201','937202','937203','937300','937400','938303','938302','933501','893801','903883') AND A.MANEXTPRO ='0'
	GROUP BY ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name , CG.Name ,ING.IFECHAING 
),

CTE_RECONOCIMIENTOS_NOQX AS
(
SELECT 
ING.NUMINGRES,
ING.NUMEFOLIO,
ing.IESTADOIN,ING.[FECHA INGRESO],ING.ENTIDAD ,ING.[GRUPO ATENCION]   ,ING.IPCODPACI ,ING.IPNOMCOMP ,ING.CODSERIPS ,ING.DESSERIPS,ING.[CANTIDAD ORDENADA]  ,ING.CANSERIPS ,CAM.UFUDESCRI,
CAM.NUMCAMHOS,EGR.FECEGRESO,CAR.CUPS 'CUPS CARGADO',CAR.CANTIDAD 'CANTIDAD CARGADA',ING.[FECHA REALIZADO MINIMA] ,ING.[FECHA REALIZADO MAXIMA] 
FROM CTE_DATOS_PROCEDIMIENTOS_NO_QX ING
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM with (nolock) ON ING.NUMINGRES =CAM.NUMINGRES
LEFT JOIN CTE_EGRESO_CAMA EGR with (nolock) ON EGR.NUMINGRES =ING.NUMINGRES
LEFT JOIN CTE_ORDENES_CON_PROCEDIMIENTOS_NO_QX_CARGADAS CAR with (nolock) ON CAR.AdmissionNumber =ING.NUMINGRES AND CAR.CUPS =ING.CODSERIPS

WHERE CAM.UFUTIPUNI NOT IN ('1','19') --AND CAM.NUMCAMHOS NOT LIKE 'U%' AND CAM.NUMCAMHOS NOT LIKE 'O%' 
--AND CAM.NUMCAMHOS NOT LIKE 'SAL%' AND CAM.NUMCAMHOS NOT LIKE 'PRE%' AND CAM.NUMCAMHOS NOT LIKE 'REC%' AND CAM.NUMCAMHOS NOT LIKE 'SRE%' 
AND ING.[CANTIDAD ORDENADA] <>ISNULL(CAR.CANTIDAD,0)  AND ING.[CANTIDAD ORDENADA] >ISNULL(CAR.CANTIDAD,0) and ing.DESSERIPS not like 'interna%'
--AND ING.NUMINGRES='173331'
),
--IN V2
--SE CREA EL CTE DE JUSTIFICACIONES, PARA QUE ME RETORNE TODOS LOS ORDENAMIENTOS CON ALGUNA JUSTIFIACION.
CTE_JUSTIFICACIONES AS
(
SELECT H.NUMINGRES,H.NUMEFOLIO,H.CODSERIPS,JUS.CODE
FROM 
[Billing].[BillingJustificationControl] JUS INNER JOIN
[Billing].[AccountControlJustification] CON ON JUS.ID=JustificationId INNER JOIN
dbo.HCORDPRON H ON CON.EntityId=H.AUTO AND CON.EntityName='HCORDPRON'
)
-- SE CREA LA NUEVA CONSULTA UNIENDO EL CTE CTE_RECONOCIMIENTOS_NOQX CON EL CTE_JUSTIFICACIONES PARA QUE NO ME MUESTRE LAS ORDENES QUE SE ENCUENTRAN JUSTIFICADAS
SELECT NOQX.* 
FROM 
CTE_RECONOCIMIENTOS_NOQX NOQX LEFT JOIN
CTE_JUSTIFICACIONES JUS ON NOQX.NUMINGRES=JUS.NUMINGRES AND NOQX.NUMEFOLIO=JUS.NUMEFOLIO AND NOQX.CODSERIPS=JUS.CODSERIPS
WHERE JUS.Code IS NULL
--FN V2
