-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewResolution2031
-- Extracted by Fabric SQL Extractor SPN v3.9.0

/*******************************************************************************************************************
Nombre: [Report].[ViewResolution2031]
Tipo:Procedimiento Vista
Observacion:2031 reporte de aceleración para la reducción de la mortalidad materna
Profesional: Nilsson Miguel Galindo Lopez
Fecha:13-04-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico:
Fecha:
Ovservaciones:
--------------------------------------
Version 2
Persona que modifico:
Fecha:
***********************************************************************************************************************************/
CREATE VIEW [Report].[ViewResolution2031] AS

WITH 
--CTE TO COLLECT ALL PATIENTS TO WHOM THEY WILL BE SUBJECTS TO PRESENT IN THE REPORT
--CTE DE DE LA POBLACIÓN SUJETA AL REPORTE
CTE_POPULATION AS
(
	--USERS WHO ENTER THROUGH ATTENTION
	SELECT  
		HC.IPCODPACI,
		DATEPART(ISO_WEEK,HC.FECHISPAC) AS [WEEK],
		YEAR(HC.FECHISPAC) AS [YEAR],
		CAST(HC.FECHISPAC AS DATE) AS FECHA
	FROM HCHISPACA HC INNER JOIN
		dbo.ADINGRESO ING ON HC.NUMINGRES=ING.NUMINGRES
	WHERE (HC.IDMODELOHC IN (11)) AND (HC.FECHISPAC BETWEEN GETDATE()-365 AND GETDATE())
	--SELECT * FROM PRMODELOHC
	UNION ALL
	----PATIENTS WITH DELIVERIES
	----PACIENTES CON PARTOS
	SELECT
		ING.IPCODPACI,
		DATEPART(ISO_WEEK,RN.FECHISPAC) AS [WEEK],
		YEAR(RN.FECHISPAC) AS [YEAR],
		CAST(ING.IFECHAING AS DATE) FECHA
	FROM 
		dbo.HCRECINAC RN INNER JOIN
		DBO.ADINGRESO ING ON RN.NUMINGRES=ING.NUMINGRES
		WHERE ING.IFECHAING BETWEEN GETDATE()-365 AND GETDATE()
),

--CTE TO DEBUG USERS THAT ARE REPEATED
CTE_DEPURATED_POPULATION AS 
(
	SELECT * FROM CTE_POPULATION A GROUP BY IPCODPACI,[WEEK],[YEAR],FECHA
),


CTE_PRENATAL_MOMENT AS
(
	SELECT
		HC.IPCODPACI,
		ISNULL(CAST(AGO.FECHISPAC AS DATE),CAST(HC.FECHISPAC AS DATE)) AS FECHISPAC,
		ISNULL(CONVERT(INT,NOMSEMGES),0) AS NOMSEMGES,
		ISNULL(CASE WHEN AGO.RIESOBTET LIKE '%ALTO%' THEN '4'
					WHEN AGO.RIESOBTET LIKE '%BAJO%' THEN '5'ELSE '0' END,'0') AS RIESOBTET,
		ISNULL(YEAR(AGO.FECHISPAC),YEAR(HC.FECHISPAC)) AS [YEAR],
		ISNULL(DATEPART(ISO_WEEK,AGO.FECHISPAC),DATEPART(ISO_WEEK,HC.FECHISPAC)) AS [WEEK],
		CAST(AGO.FECPROPAR AS DATE) AS FECPROPAR

	FROM 
		dbo.HCHISPACA HC LEFT JOIN
		dbo.HCANTGINE AGO ON HC.NUMINGRES=AGO.NUMINGRES AND HC.NUMEFOLIO=AGO.NUMEFOLIO
	WHERE HC.IDMODELOHC=11
	GROUP BY HC.IPCODPACI,AGO.NOMSEMGES,CAST(AGO.FECHISPAC AS DATE) ,YEAR(AGO.FECHISPAC),
			 DATEPART(ISO_WEEK,AGO.FECHISPAC),AGO.RIESOBTET,CAST(HC.FECHISPAC AS DATE),YEAR(HC.FECHISPAC),DATEPART(ISO_WEEK,HC.FECHISPAC),AGO.FECPROPAR
),

CTE_ATENTION_CENTER AS
(
SELECT 
ING.IPCODPACI,
ING.NUMINGRES,
CEN.CODIPSSEC
FROM
dbo.ADINGRESO ING INNER JOIN
dbo.ADCENATEN CEN ON ING.CODCENATE=CEN.CODCENATE AND ING.TIPOINGRE=1 
												 AND ING.NUMINGRES=(SELECT MAX(AD.NUMINGRES) FROM ADINGRESO AD WHERE ING.IPCODPACI=AD.IPCODPACI AND AD.TIPOINGRE=1)
),

CTE_CUPS AS
(
SELECT
AG.IPCODPACI,
YEAR(AG.FECHORAIN) AS [YEAR],
DATEPART(ISO_WEEK,AG.FECHORAIN) AS [WEEK],
CASE WHEN AGA.DESACTMED LIKE '%PLANIFICACIÓN FAMILIAR%' THEN '03' 
	 WHEN AGA.DESACTMED LIKE '%OPTOMETRIA%' THEN '08' ELSE '10' END AS [5],
CASE WHEN AGA.DESACTMED LIKE '%PLANIFICACIÓN FAMILIAR%' THEN 'Atención en Planificación Familiar' 
	 WHEN AGA.DESACTMED LIKE '%OPTOMETRIA%' THEN 'Detección de Alteraciones de Agudeza Visual' ELSE 'No Aplica' END AS [6]
FROM
dbo.AGASICITA AG INNER JOIN
dbo.AGACTIMED AGA ON AG.CODACTMED=AGA.CODACTMED AND AGA.ACTIVICON=0  INNER JOIN
CTE_POPULATION DP ON AG.IPCODPACI=DP.IPCODPACI
),

CTE_DIAGNOSTICS AS
(
	SELECT 
	CASE WHEN DIA.NOMDIAGNO like '%PREECLAMPSIA%' THEN 1
		 WHEN DIA.NOMDIAGNO like '%NUTRICIONALES%' THEN 2 END AS TIPO,
	NOG.IPCODPACI,
	DATEPART(ISO_WEEK,NOG.FECDIAGNO) AS [WEEK],
	YEAR(NOG.FECDIAGNO) AS [YEAR]
	FROM
	dbo.INDIAGNOS DIA INNER JOIN
	dbo.INDIAGNOP NOG ON DIA.CODDIAGNO=NOG.CODDIAGNO AND (DIA.NOMDIAGNO like '%PREECLAMPSIA%' OR DIA.NOMDIAGNO like '%NUTRICIONALES%')
	GROUP BY IPCODPACI,NOG.FECDIAGNO,DIA.NOMDIAGNO
),

CTE_PRODUCT AS
(
	SELECT
	CASE WHEN PRO.[NAME] LIKE '%ACIDO ACETILSALICILICO%' THEN 1 
		 WHEN PRO.[NAME] LIKE '%ACIDO FOLICO%' THEN 2 
		 WHEN PRO.[NAME] LIKE '%SULFATO FERROSO%' THEN 3 
		 WHEN PRO.[NAME] LIKE '%CALCIO%' THEN 4
		 WHEN PRO.[NAME] LIKE '%INTRAUTERINO%' OR PRO.[NAME] LIKE '%DIU%' THEN 5
		 WHEN PRO.[NAME] LIKE '%PRESERVATIVOS%' OR PRO.[NAME] LIKE '%CONDONES%' THEN 6
		 WHEN PRO.[NAME] LIKE '%LEVONORGESTREL%' OR PRO.[NAME] LIKE '%MEDROXIPROGESTERONA%' THEN 7 
		 WHEN PRO.Name='ACIDO ACETILSALICILICO' THEN 8 END AS TIPO,
	ING.IPCODPACI,
	CAST(DISD.ServiceDate AS DATE) FECHA,
	YEAR(DISD.ServiceDate) AS [YEAR]
	from 
	Inventory.PharmaceuticalDispensing DIS INNER JOIN
	Inventory.PharmaceuticalDispensingDetail DISD ON DIS.Id=DISD.PharmaceuticalDispensingId INNER JOIN
	Inventory.InventoryProduct PRO ON DISD.ProductId=PRO.Id INNER JOIN
	dbo.ADINGRESO ING ON DIS.AdmissionNumber=ING.NUMINGRES
	WHERE (DISD.ServiceDate BETWEEN GETDATE()-271 AND GETDATE()) AND (PRO.[NAME] LIKE '%ACIDO ACETILSALICILICO%' OR PRO.[NAME] LIKE '%ACIDO FOLICO%'
	OR PRO.[NAME] LIKE '%SULFATO FERROSO%' OR PRO.[NAME] LIKE '%CALCIO%') OR PRO.[NAME] LIKE '%INTRAUTERINO%' 
OR PRO.[NAME] LIKE '%PRESERVATIVOS%'OR PRO.[NAME] LIKE '%LEVONORGESTREL%' OR PRO.[NAME] LIKE '%DIU%' OR PRO.[NAME] LIKE '%CONDONES%' 
OR PRO.[NAME] LIKE '%MEDROXIPROGESTERONA%' OR PRO.[Name]='ACIDO ACETILSALICILICO'
),

--CTE PARA RECIEN NACIDOS 
CTE_NEMWORD AS
(
SELECT
RN.IPCODPACI,
YEAR(ING.IFECHAING) AS [YEAR],
DATEPART(ISO_WEEK,ING.IFECHAING) AS [WEEK],
CAST(ING.FECHEGRESO AS DATE) AS FECHEGRESO
FROM 
dbo.HCRECINAC RN INNER JOIN
DBO.ADINGRESO ING ON RN.NUMINGRES=ING.NUMINGRES 
),

CTE_PACIENT_TYPE_4 AS
(
SELECT
		'1' AS TIPO,
		PAC.IPCODPACI,
		PAC.IPTIPODOC,
		DP.[WEEK],
		DP.[YEAR],
		DP.FECHA
	FROM 
		CTE_DEPURATED_POPULATION DP INNER JOIN
		DBO.INPACIENT PAC ON DP.IPCODPACI=PAC.IPCODPACI AND DATEDIFF(YEAR,PAC.IPFECNACI,GETDATE())>35
	UNION ALL
	SELECT
		'2' AS TIPO,
		PAC.IPCODPACI,
		PAC.IPTIPODOC,
		DP.WEEK,
		DP.YEAR,
		DP.FECHA
	FROM
		CTE_DEPURATED_POPULATION DP INNER JOIN
		CTE_DIAGNOSTICS DIA ON DP.IPCODPACI=DIA.IPCODPACI AND DIA.TIPO=2
													  AND DP.[YEAR]=DIA.[YEAR]
													  AND DP.[WEEK]=DIA.[WEEK] INNER JOIN
	DBO.INPACIENT PAC ON DP.IPCODPACI=PAC.IPCODPACI 
UNION ALL
SELECT
		'3' AS TIPO,
		PAC.IPCODPACI,
		PAC.IPTIPODOC,
		DP.[WEEK],
		DP.[YEAR],
		CAST(TRI.TRIAFECHA AS DATE) AS FECHA
	FROM
		dbo.ADTRIAGEU TRI INNER JOIN
		CTE_DEPURATED_POPULATION DP ON DP.IPCODPACI=TRI.IPCODPACI AND TRI.TRIAGECLA<=3 
																  AND YEAR(TRI.TRIAFECHA)=DP.[YEAR] 
																  AND DATEPART(ISO_WEEK,TRI.TRIAFECHA)=DP.[WEEK] INNER JOIN
		DBO.INPACIENT PAC ON DP.IPCODPACI=PAC.IPCODPACI 
	UNION ALL
	SELECT
		'7' AS TIPO,
		PAC.IPCODPACI,
		PAC.IPTIPODOC,
		DP.WEEK,
		DP.YEAR,
		DP.FECHA
	FROM
		CTE_DEPURATED_POPULATION DP INNER JOIN
		CTE_DIAGNOSTICS DIA ON DP.IPCODPACI=DIA.IPCODPACI AND DIA.TIPO=1
														  AND DP.[YEAR]=DIA.[YEAR]
														  AND DP.[WEEK]=DIA.[WEEK] INNER JOIN
		DBO.INPACIENT PAC ON DP.IPCODPACI=PAC.IPCODPACI 
),

CTE_TECNOLOGIA AS
(
SELECT
DP.IPCODPACI,
DP.[WEEK],
DP.[YEAR],
CASE HC.IDMODELOHC WHEN 5 THEN '02' 
				   WHEN 29 THEN '01'
				   WHEN 30 THEN '03' 
				   WHEN 8 THEN '04'
				   WHEN 9 THEN '05' ELSE '10' END AS [6]
FROM 
CTE_DEPURATED_POPULATION DP INNER JOIN
dbo.HCHISPACA HC ON DP.IPCODPACI=HC.IPCODPACI AND HC.NUMEFOLIO=(SELECT MAX(H.NUMEFOLIO) FROM dbo.HCHISPACA H WHERE DP.IPCODPACI=H.IPCODPACI AND DP.[YEAR]=YEAR(H.FECHISPAC)
																																			AND DP.[WEEK]=DATEPART(ISO_WEEK,H.FECHISPAC))
)
-------------------------------------------------------------------------------------------------------------------------------------

SELECT --TOP 100 PERCENT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CEN.CODIPSSEC AS [CODIGO HABILITACION],
ACT.DESACTIVI AS [OCUPACIÓN],
DP.[YEAR] AS [AÑO DE ATENCIÓN],
DP.[WEEK] AS [SEMANA DE ATENCIÓN],
2 AS [0],
ROW_NUMBER ( ) OVER (PARTITION BY DP.[YEAR],DP.[WEEK]  ORDER BY DP.[YEAR],DP.[WEEK] DESC) [1],
CASE PAI.Name WHEN 'Argentina' THEN 'ARG' WHEN 'Namibia' THEN 'NAM' WHEN 'Jamaica' THEN 'JAM' WHEN 'Australia' THEN 'AUT'
			  WHEN 'Bolivia' THEN 'BOL' WHEN 'Croacia' THEN 'HRV' WHEN 'Nicaragua' THEN 'NIC' WHEN 'Uruguay' THEN 'URY'
			  WHEN 'Brasil' THEN 'BRA' WHEN 'Panamá' THEN 'PAN' WHEN 'Suiza' THEN 'CHE' WHEN 'Francia' THEN 'FRA'
			  WHEN 'Chile' THEN 'CHL' WHEN 'Rusia' THEN 'RUS' WHEN 'Reino Unido' THEN 'GBR' WHEN 'Cuba' THEN 'CUB'
			  WHEN 'Colombia' THEN 'COL' WHEN 'Suecia' THEN 'SWE' WHEN 'Italia' THEN 'ITA' WHEN 'República Dominicana' THEN 'DOM'
			  WHEN 'Ecuador' THEN 'ECU' WHEN 'Armenia' THEN 'ARM' WHEN 'Austria' THEN 'AUT' WHEN 'Canadá' THEN 'CAN' WHEN 'Tailandia' THEN 'THA'
			  WHEN 'Estados Unidos' THEN 'USA' WHEN 'Noruega' THEN 'SJM' WHEN 'Países Bajos' THEN 'NLD' WHEN 'Costa Rica' THEN 'CRI'
			  WHEN 'México' THEN 'MEX' WHEN 'Paraguay' THEN 'PRY' WHEN 'Puerto Rico' THEN 'PRI' WHEN 'Bélgica' THEN 'BEL'
			  WHEN 'Perú' THEN 'PER' WHEN 'España' THEN 'ESP' WHEN 'Nigeria' THEN 'NGA' WHEN 'Alemania' THEN 'DEU' WHEN 'Honduras' THEN 'HND'
			  WHEN 'Venezuela' THEN 'VEN' WHEN 'Israel' THEN 'ISR' WHEN 'Bulgaria' THEN 'BGR' WHEN 'Irlanda' THEN 'IRL' WHEN 'Haití' THEN 'HTI'
			  WHEN 'Portugal' THEN 'PRT' WHEN 'Belgica' THEN 'BEL' WHEN 'Australia' THEN 'AUS' WHEN 'China' THEN 'CHN' WHEN 'Dinamarca' THEN 'DNK'
			  WHEN 'Canada' THEN 'CAN' END AS [2],
UBI.DEPMUNCOD AS [3],
CASE UBI.TIPOUBICA WHEN 0 THEN '01' ELSE '02' END AS [4],
CEN.CODIPSSEC AS [5],
CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' 
				   WHEN '2' THEN 'CE'
				   WHEN '3' THEN 'TI'
				   WHEN '4' THEN 'RC'	
				   WHEN '5' THEN 'PA'	
				   WHEN '6' THEN 'AS'
				   WHEN '7' THEN 'MS'
				   WHEN '8' THEN 'MS'
				   WHEN '9' THEN 'CN'
				   WHEN '10' THEN 'CD'	
				   WHEN '11' THEN 'SC' 
				   WHEN '12' THEN 'PE'
				   WHEN '13' THEN 'PT'
				   WHEN '14' THEN 'DE' ELSE 'N/A'END AS [6],
PAC.IPCODPACI AS [7],
PAC.IPPRIAPEL AS [8],
PAC.IPSEGAPEL AS [9],
PAC.IPPRINOMB AS [10],
PAC.IPSEGNOMB AS [11],
CONVERT(VARCHAR(10),PAC.IPFECNACI,23) AS [12],
CASE GE.DESGRUPET WHEN 'INDIGENAS' THEN '1' 
				  WHEN 'PUEBLO ROM GITANOS' THEN '2' 
				  WHEN 'RAIZALES SAN ANDRES Y PROVIDENCIA' THEN '3' 
				  WHEN 'PALENQUEROS DE SAN BASILIO' THEN '4' 
				  WHEN 'AFROCOLOMBIANOS NEGROS MULATOS O AFRODESCENDIENTES' THEN '5'
				  ELSE '6' END AS [13],
ACT.CODACTIVI AS [14],
CASE NIV.NIVEDESCRI WHEN 'PRE ESCOLAR' THEN '1'
					WHEN 'BASICA PRIMARIA' THEN '2'
					WHEN 'BASICA SECUNDARIA BACHILLERATO BASICO' THEN '3'
					WHEN 'MEDIA ACADEMICA O CLASICA BACHILLERATO BASICO' THEN '4'
					WHEN 'MEDIA TECNICA BACHILLERATO TECNICO' THEN '5'
					WHEN 'NORMALISTA' THEN '6'
					WHEN 'TECNICA PROFESIONAL' THEN '7'
					WHEN 'TECNOLOGICA' THEN '8'
					WHEN 'PROFESIONAL' THEN '9'
					WHEN 'ESPECIALIZACION' THEN '10'
					WHEN 'MAESTRIA' THEN '11'
					WHEN 'DOCTORADO' THEN '12' ELSE '13' END AS [15],
PREM.FECPROPAR AS [16]
FROM 
CTE_DEPURATED_POPULATION DP INNER JOIN
DBO.INPACIENT PAC ON DP.IPCODPACI=PAC.IPCODPACI INNER JOIN
Common.Country PAI ON PAC.IDPAIS=PAI.Id INNER JOIN
CTE_ATENTION_CENTER CEN ON DP.IPCODPACI=CEN.IPCODPACI LEFT JOIN
dbo.INUBICACI UBI ON PAC.AUUBICACI=UBI.AUUBICACI LEFT JOIN
DBO.ADGRUETNI GE ON PAC.CODGRUPOE=GE.CODGRUPOE LEFT JOIN
dbo.ADACTIVID ACT ON PAC.CODACTIVI=ACT.codactivi LEFT JOIN
dbo.ADNIVELED NIV ON PAC.NIVECODIGO=NIV.NIVECODIGO LEFT JOIN
CTE_PRENATAL_MOMENT PREM ON DP.IPCODPACI=PREM.IPCODPACI AND DP.[YEAR]=PREM.[YEAR]
														AND DP.[WEEK]=PREM.[WEEK]
UNION ALL
SELECT 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CEN.CODIPSSEC AS [CODIGO HABILITACION],
'' AS [OCUPACIÓN],
DP.[YEAR] AS [AÑO DE ATENCIÓN],
DP.[WEEK] AS [SEMANA DE ATENCIÓN],
3 AS [0],
ROW_NUMBER ( ) OVER (PARTITION BY DP.[YEAR],DP.[WEEK]  ORDER BY DP.[YEAR],DP.[WEEK] DESC) [1],
CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' 
				   WHEN '2' THEN 'CE'
				   WHEN '3' THEN 'TI'
				   WHEN '4' THEN 'RC'	
				   WHEN '5' THEN 'PA'	
				   WHEN '6' THEN 'AS'
				   WHEN '7' THEN 'MS'
				   WHEN '8' THEN 'MS'
				   WHEN '9' THEN 'CN'
				   WHEN '10' THEN 'CD'	
				   WHEN '11' THEN 'SC' 
				   WHEN '12' THEN 'PE'
				   WHEN '13' THEN 'PT'
				   WHEN '14' THEN 'DE' ELSE 'N/A'END AS [2],
PAC.IPCODPACI AS [3],
CONVERT(VARCHAR(10),DP.FECHA,23) AS [4],
CUPS.[5],
TEC.[6],
ISNULL(PREM.RIESOBTET,0) AS [7],
IIF(DIA.IPCODPACI IS NULL,'5','4') AS [8],
IIF(ACIS.IPCODPACI IS NULL,'21','1') AS [9],
IIF(FOL.IPCODPACI IS NULL,'21','1') AS [10],
IIF(FE.IPCODPACI IS NULL,'21','1') AS [11],
IIF(CAL.IPCODPACI IS NULL,'21','1') AS [12],
CONVERT(VARCHAR(10),ANTC.FECHA,23) AS [13],
CASE ANTC.TIPO WHEN 5 THEN '1'
			   WHEN 6 THEN '15'
			   WHEN 7 THEN '5' END AS [14],
ISNULL(CONVERT(VARCHAR(10),REC.FECHEGRESO,23),'1845-01-01') AS [15],
'' AS [16]
FROM
CTE_DEPURATED_POPULATION DP INNER JOIN
DBO.INPACIENT PAC ON DP.IPCODPACI=PAC.IPCODPACI INNER JOIN
CTE_ATENTION_CENTER CEN ON DP.IPCODPACI=CEN.IPCODPACI LEFT JOIN
CTE_CUPS CUPS ON DP.IPCODPACI=CUPS.IPCODPACI AND DP.[YEAR]=CUPS.[YEAR] 
											 AND DP.[WEEK]=CUPS.[WEEK] LEFT JOIN
CTE_PRENATAL_MOMENT PREM ON DP.IPCODPACI=PREM.IPCODPACI AND DP.[YEAR]=PREM.[YEAR]
														AND DP.[WEEK]=PREM.[WEEK] LEFT JOIN
CTE_DIAGNOSTICS DIA ON DP.IPCODPACI=DIA.IPCODPACI AND DIA.TIPO=1 
													AND DP.[YEAR]=DIA.[YEAR]
													AND DP.[WEEK]=DIA.[WEEK] LEFT JOIN
CTE_PRODUCT ACIS ON DP.IPCODPACI=ACIS.IPCODPACI AND ACIS.TIPO=8
												AND DP.[YEAR]=YEAR(ACIS.FECHA)
											    AND DP.[WEEK]=DATEPART(ISO_WEEK,ACIS.FECHA) LEFT JOIN
CTE_PRODUCT FOL ON DP.IPCODPACI=FOL.IPCODPACI AND FOL.TIPO=2
											  AND DP.[YEAR]=YEAR(FOL.FECHA)
											  AND DP.[WEEK]=DATEPART(ISO_WEEK,FOL.FECHA) LEFT JOIN
CTE_PRODUCT FE ON DP.IPCODPACI=FE.IPCODPACI AND FE.TIPO=3
											AND DP.[YEAR]=YEAR(FE.FECHA)
											AND DP.[WEEK]=DATEPART(ISO_WEEK,FE.FECHA) LEFT JOIN
CTE_PRODUCT CAL ON DP.IPCODPACI=CAL.IPCODPACI AND CAL.TIPO=4
											  AND DP.[YEAR]=YEAR(CAL.FECHA)
											  AND DP.[WEEK]=DATEPART(ISO_WEEK,CAL.FECHA) LEFT JOIN
CTE_PRODUCT ANTC ON DP.IPCODPACI=ANTC.IPCODPACI AND ANTC.TIPO IN (5,6,7)
												AND DP.[YEAR]=ANTC.[YEAR]
												AND DP.[WEEK]=DATEPART(ISO_WEEK,ANTC.FECHA) LEFT JOIN
CTE_NEMWORD REC ON DP.IPCODPACI=REC.IPCODPACI AND DP.[YEAR]=REC.[YEAR]
											  AND DP.[WEEK]=REC.[WEEK] LEFT JOIN
CTE_TECNOLOGIA TEC ON DP.IPCODPACI=TEC.IPCODPACI AND DP.[YEAR]=TEC.[YEAR]
											     AND DP.[WEEK]=TEC.[WEEK]
--WHERE DP.IPCODPACI='1020103859'
UNION ALL

SELECT 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CEN.CODIPSSEC AS [CODIGO HABILITACION],
'' AS [OCUPACIÓN],
DP.[YEAR] AS [AÑO DE ATENCIÓN],
DP.[WEEK] AS [SEMANA DE ATENCIÓN],
4 AS [0],
ROW_NUMBER ( ) OVER (PARTITION BY DP.[YEAR],DP.[WEEK]  ORDER BY DP.[YEAR],DP.[WEEK] DESC) [1],
CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' 
				   WHEN '2' THEN 'CE'
				   WHEN '3' THEN 'TI'
				   WHEN '4' THEN 'RC'	
				   WHEN '5' THEN 'PA'	
				   WHEN '6' THEN 'AS'
				   WHEN '7' THEN 'MS'
				   WHEN '8' THEN 'MS'
				   WHEN '9' THEN 'CN'
				   WHEN '10' THEN 'CD'	
				   WHEN '11' THEN 'SC' 
				   WHEN '12' THEN 'PE'
				   WHEN '13' THEN 'PT'
				   WHEN '14' THEN 'DE' ELSE 'N/A'END AS [2],
PAC.IPCODPACI AS [3],
DP.TIPO AS [4],
CONVERT(VARCHAR(10),DP.FECHA,23) AS [5],
'4' AS [6],
'2' AS [7],
'2' AS [8],
'2' AS [9],
'2' AS [10],
'2' AS [11],
'2' AS [12],
'2' AS [13],
'' AS [14],
'' AS [15],
'' AS [16]
FROM 
CTE_PACIENT_TYPE_4 DP INNER JOIN
CTE_ATENTION_CENTER CEN ON DP.IPCODPACI=CEN.IPCODPACI INNER JOIN
dbo.INPACIENT PAC ON DP.IPCODPACI=PAC.IPCODPACI AND DP.FECHA=(SELECT MAX(D.FECHA) FROM CTE_PACIENT_TYPE_4 D WHERE DP.IPCODPACI=D.IPCODPACI AND DP.[YEAR]=D.[YEAR] 
																																		   AND DP.[WEEK]=D.[WEEK])

--select * from CTE_DEPURATED_POPULATION DP inner join 
--CTE_DIAGNOSTICS DIA ON DP.IPCODPACI=DIA.IPCODPACI

--SELECT * FROM CTE_DEPURATED_POPULATION DP INNER JOIN
--dbo.ADTRIAGEU DIA ON DP.IPCODPACI=DIA.IPCODPACI