-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewPacientesDiscapacidad
-- Extracted by Fabric SQL Extractor SPN v3.9.0








    /*******************************************************************************************************************
Nombre: [Report].[ViewPacientesDiscapacidad]
Tipo:Vista
Observacion:Se elistan todos los pacientes con algun tipo de discapacidad
Profesional: Nilsson Miguel Galindo Lopez
Fecha:25-08-2022
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Vercion 1
Persona que modifico: 
Fecha:
Ovservaciones: 
--------------------------------------
Vercion 2
Persona que modifico:
Fecha:
--***********************************************************************************************************************************/

CREATE view [Report].[ViewPacientesDiscapacidad]
as

SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
PAC.IPCODPACI AS IDENTIFICACION,
CASE PAC.IPTIPODOC WHEN 1 THEN 'CC - CEDULA DE CIUDADANIA' 
				   WHEN 2 THEN 'CE - CEDULA DE EXTRANJERIA' 
				   WHEN 3 THEN 'TI - TARJETA DE IDENTIDAD' 
				   WHEN 4 THEN 'RC - REGISTRO CIVIL' 
				   WHEN 5 THEN 'PA - PASAPORTE' 
				   WHEN 6 THEN 'AS - ADULTO SIN IDENTIFICACION' 
				   WHEN 7 THEN 'MS - MENOR SIN IDENTIFICACION' 
				   WHEN 8 THEN 'NU - NUMERO UNICO DE IDENTIFICACIÒN' 
				   WHEN 9 THEN 'NV - CERTIFICADO NACIDO VIVO' 
				   WHEN 10 THEN 'CD - CARNET DIPLOMATICO' 
				   WHEN 11 THEN 'SC - SALVOCONDUCTO' 
				   WHEN 12 THEN 'PE - PERMISO ESPECIAL DE PERMANENCIA' ELSE 'OTRO' END [TIPO IDENTIFICACION],
PAC.IPNOMCOMP AS [NOMBRE COMPLETO],
PAC.IPPRINOMB AS [PRIMER NOMBRE],
PAC.IPSEGNOMB AS [SEGUNDO NOMBRE], 
PAC.IPPRIAPEL AS [PRIMER APELLIDO],
PAC.IPSEGAPEL AS [SEGUNDO APELLIDO],
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END [SEXO],
CAST(PAC.IPFECNACI AS DATE ) AS [FECHA_NACIMIENTO],
PAC.IPDIRECCI AS DIRECCION,
DEP.NOMDEPART AS DEPARTAMENTO, 
MUN.MUNNOMBRE AS MUNICIPIO,
UB.UBINOMBRE AS UBICACION,
PAC.IPTELEFON AS [TELEFONO],
PAC.IPTELMOVI AS [CELULAR],
EAPB.CODENTIDA AS [CODIGO EAPB],
EAPB.NOMENTIDA AS [NOMBRE EAPB],
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro' 
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado'
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [REGIMEN],
DIS.DISCDESCRI AS DISCAPACIDAD,
ING.NUMINGRES AS INGRESO,
ING.IFECHAING AS [FECHA DE ATENCIÓN],
CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO'
				   WHEN 2 THEN 'HOSPITALARIO'END AS [TIPO INGRESO],
CASE ING.IINGREPOR WHEN 1 THEN 'URGENCIAS'
				   WHEN 2 THEN 'CONSULTA EXTERNA'
				   WHEN 3 THEN 'NACIDO HOSPITAL'
				   WHEN 4 THEN 'REMITIDO'
				   WHEN 5 THEN 'HOSPITALIZACIÓN DE URGENCIAS' END AS [INGRESO POR],
DI.CODDIAGNO+' - '+DI.NOMDIAGNO AS [DIAGNOSTICO DE INGRESO],
DIA.CODDIAGNO+' - '+DIA.NOMDIAGNO AS [DIAGNOSTICO DE EGRESO],
 1 'CANTIDAD',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
DBO.INPACIENT PAC INNER JOIN
INUBICACI UB ON PAC.AUUBICACI=UB.AUUBICACI INNER JOIN
INMUNICIP MUN ON UB.DEPMUNCOD = MUN.DEPMUNCOD INNER JOIN
INDEPARTA DEP ON MUN.DEPCODIGO = DEP.DEPCODIGO AND PAC.AUUBICACI = UB.AUUBICACI INNER JOIN
INENTIDAD AS EAPB ON PAC.CODENTIDA=EAPB.CODENTIDA INNER JOIN
dbo.ADDISCAPACI DIS ON PAC.DISCCODIGO=DIS.DISCCODIGO INNER JOIN 
ADINGRESO ING ON PAC.IPCODPACI=ING.IPCODPACI LEFT JOIN
DBO.INDIAGNOS DI ON ING.CODDIAING=DI.CODDIAGNO LEFT JOIN
DBO.INDIAGNOS DIA ON ING.CODDIAEGR=DIA.CODDIAGNO
WHERE DIS.DISCDESCRI not like'%ningun%' and DIS.DISCDESCRI not like'%sin dis%'



