-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewMorbilidad
-- Extracted by Fabric SQL Extractor SPN v3.9.0






CREATE VIEW [Report].[ViewMorbilidad] as 

WITH CTE_DATOSHIS_UNICOS as
 (
  SELECT
   HIS.IPCODPACI,
   MAX(HIS.FECHISPAC) [FECHA_ATENCION],
   (SELECT TOP 1 NUMINGRES FROM HCHISPACA H WHERE H.IPCODPACI = HIS.IPCODPACI AND H.FECHISPAC = MAX(HIS.FECHISPAC)) NUMINGRES
  FROM 
   HCHISPACA HIS
  WHERE
   HIS.GENCONEXT IN (1, 0) AND
   HIS.IPCODPACI <> '000000000000000'
  GROUP BY
   HIS.IPCODPACI
)

SELECT --COUNT(*)
   CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
   CASE PAC.IPTIPODOC 
      WHEN 1  THEN	'CC - CEDULA DE CIUDADANIA' 
	  WHEN 2  THEN	'CE - CEDULA DE EXTRANJERIA' 
	  WHEN 3  THEN	'TI - TARJETA DE IDENTIDAD' 
	  WHEN 4  THEN	'RC - REGISTRO CIVIL' 
	  WHEN 5  THEN	'PA - PASAPORTE' 
	  WHEN 6  THEN	'AS - ADULTO SIN IDENTIFICACION' 
	  WHEN 7  THEN	'MS - MENOR SIN IDENTIFICACION' 
	  WHEN 8  THEN	'NU - NUMERO UNICO DE IDENTIFICACIÒN' 
	  WHEN 9  THEN	'NV - CERTIFICADO NACIDO VIVO' 
	  WHEN 10 THEN	'CD - CARNET DIPLOMATICO' 
	  WHEN 11 THEN	'SC - SALVOCONDUCTO' 
	  WHEN 12 THEN	'PE - PERMISO ESPECIAL DE PERMANENCIA' ELSE 'NO REGISTRA'
	  END 'TIPO IDENTIFICACION',
   HIS.IPCODPACI 'ID. PACIENTE',
   PAC.IPNOMCOMP 'NOMBRE PACIENTE',
   DATEDIFF(YEAR,PAC.IPFECNACI,  CAST(CTE.[FECHA_ATENCION] AS DATE)) 'EDAD AÑOS', 
   DATEDIFF(MONTH,PAC.IPFECNACI, CAST(CTE.[FECHA_ATENCION] AS DATE)) 'EDAD MESES',
   CASE WHEN PAC.IPSEXOPAC =1 THEN 'M' ELSE 'F' END 'SEXO',
   DEP.nomdepart 'DEPARTAMENTO', 
   MUN.MUNNOMBRE 'MUNICIPIO',
   HA.Code 'COD. EAPB', 
   HA.Name 'NOMBRE EAPB',
   CASE WHEN HIS.GENCONEXT = 1 THEN 'Ambulatorio' ELSE 'Hospitalario' END 'AMBITO', 
   HIS.NUMINGRES AS 'INGRESO', 
   CAST(CTE.[FECHA_ATENCION] AS DATE) 'FECHA ATENCION',
   HIS.UFUCODIGO 'COD. UF', 
   FUN.UFUDESCRI 'UNIDAD FUNCIONAL',
   PRO.NOMMEDICO AS 'NOMBRE PROFESIONAL',
   ESP.DESESPECI AS 'ESPECIALIDAD TRATANTE', 
   TI1.CODDIAGNO 'COD. DX CIE-10', 
   TI1.NOMDIAGNO 'DX CIE-10', 
   TI2.CODDIAGNO 'COD CIE-10 RELACIONADO', 
   TI2.NOMDIAGNO 'DX CIE-10 RELACIONADO',
   CASE HIS.INDICAPAC WHEN '11' THEN 'SI' ELSE 'NO' END 'MORTALIDAD',
   CASE WHEN DATEDIFF(MONTH,PAC.IPFECNACI,CTE.[FECHA_ATENCION]) <12 THEN 1 ELSE 0 END '< 1 AÑO',
   CASE WHEN DATEDIFF(MONTH,PAC.IPFECNACI,CTE.[FECHA_ATENCION]) BETWEEN 12 AND 23 THEN 1 ELSE 0 END '1 AÑO',
   CASE WHEN DATEDIFF(MONTH,PAC.IPFECNACI,CTE.[FECHA_ATENCION]) BETWEEN 24 AND 59 THEN 1 ELSE 0 END '2 a 4 AÑOS',
   CASE WHEN DATEDIFF(MONTH,PAC.IPFECNACI,CTE.[FECHA_ATENCION]) BETWEEN 60 AND 239 THEN 1 ELSE 0 END '5 A 19 AÑOS',
   CASE WHEN DATEDIFF(MONTH,PAC.IPFECNACI,CTE.[FECHA_ATENCION]) BETWEEN 240 AND 479 THEN 1 ELSE 0 END '20 A 39 AÑOS',
   CASE WHEN DATEDIFF(MONTH,PAC.IPFECNACI,CTE.[FECHA_ATENCION]) BETWEEN 480 AND 719 THEN 1 ELSE 0 END '40 A 59 AÑOS',
   CASE WHEN DATEDIFF(MONTH,PAC.IPFECNACI,CTE.[FECHA_ATENCION]) > 719 THEN 1 ELSE 0 END '>60 AÑOS',
   /*FAC.CUPS AS 'COD. CUPS', 
   FAC.DESCRIPCION AS 'DESCRIPCION CUPS', */
   1 as 'CANTIDAD',
   CAST(CTE.[FECHA_ATENCION] AS DATE) AS 'FECHA BUSQUEDA',
   YEAR(CTE.[FECHA_ATENCION]) AS 'AÑO FECHA BUSQUEDA',
   MONTH(CTE.[FECHA_ATENCION]) AS 'MES AÑO FECHA BUSQUEDA',
   CASE MONTH(CTE.[FECHA_ATENCION]) 
	    WHEN 1 THEN 'ENERO'
		WHEN 2 THEN 'FEBRERO'
		WHEN 3 THEN 'MARZO'
		WHEN 4 THEN 'ABRIL'
		WHEN 5 THEN 'MAYO'
		WHEN 6 THEN 'JUNIO'
		WHEN 7 THEN 'JULIO'
		WHEN 8 THEN 'AGOSTO'
		WHEN 9 THEN 'SEPTIEMBRE'
		WHEN 10 THEN 'OCTUBRE'
		WHEN 11 THEN 'NOVIEMBRE'
		WHEN 12 THEN 'DICIEMBRE'
   END AS 'MES NOMBRE FECHA BUSQUEDA', 
   FORMAT(DAY(CTE.[FECHA_ATENCION]), '00') AS 'DIA FECHA BUSQUEDA',
   CONCAT(FORMAT(MONTH(CTE.[FECHA_ATENCION]), '00') ,' - ', 
         CASE MONTH(CTE.[FECHA_ATENCION]) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_BUSQUEDA,
   CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
  FROM 
   CTE_DATOSHIS_UNICOS CTE --14.638
   INNER JOIN HCHISPACA HIS ON CTE.IPCODPACI = HIS.IPCODPACI AND CTE.[FECHA_ATENCION] = HIS.FECHISPAC --14.638
   INNER JOIN INPACIENT PAC ON PAC.IPCODPACI=HIS.IPCODPACI --14.638
   INNER JOIN INPROFSAL AS PRO  ON PRO.CODPROSAL=HIS.CODPROSAL
   INNER JOIN INESPECIA AS ESP  ON ESP.CODESPECI=HIS.CODESPTRA
   INNER JOIN INUBICACI AS UB ON UB.AUUBICACI = PAC.AUUBICACI
   INNER JOIN INMUNICIP AS MUN ON MUN.DEPMUNCOD = UB.DEPMUNCOD
   INNER JOIN INDEPARTA AS DEP ON DEP.depcodigo=MUN.DEPCODIGO
   INNER JOIN Contract.HealthAdministrator HA ON HA.Code=PAC.CODENTIDA  --14.639
   INNER JOIN DBO.INUNIFUNC FUN ON FUN.UFUCODIGO = HIS.UFUCODIGO --14.640
   INNER JOIN INDIAGNOP DIAGT1 ON DIAGT1.NUMINGRES = HIS.NUMINGRES AND DIAGT1.IPCODPACI = HIS.IPCODPACI AND DIAGT1.NUMEFOLIO = HIS.NUMEFOLIO  AND DIAGT1.CODDIAPRI = 1 --14-547
   INNER JOIN INDIAGNOS TI1 ON TI1.CODDIAGNO = DIAGT1.CODDIAGNO --14.547
   LEFT JOIN INDIAGNOP DIAGT2 ON DIAGT2.NUMINGRES = HIS.NUMINGRES AND DIAGT2.IPCODPACI = HIS.IPCODPACI AND DIAGT2.NUMEFOLIO = HIS.NUMEFOLIO  AND DIAGT2.CODDIAPRI = 0
   LEFT JOIN INDIAGNOS TI2 ON DIAGT2.CODDIAGNO = TI2.CODDIAGNO
   
