-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewNIIFServiciosFacturados
-- Extracted by Fabric SQL Extractor SPN v3.9.0



/*******************************************************************************************************************
Nombre: [Report].[ViewNIIFServiciosFacturados]
Tipo:Vista
Observacion:Todos los servicios prestados con su correspondiente facturación y estado en el que encuentra el servicio
Profesional: Andres Cabrera
Fecha:10-05-2022
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Vercion 2
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha: 13-09-2022
Ovservaciones: se agrega los campos de la fecha y hora del servicio por solicitud de HOMI 
--------------------------------------
Vercion 3
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha:04-10-2022
Observacion Se agrega el campo de codigo rips, solicitado por HOMI
***********************************************************************************************************************************/


CREATE VIEW [Report].[ViewNIIFServiciosFacturados] AS
-------NIIF SERVICIOS FACTURADOS -----
WITH CTE_FACTURACION_CABECERA AS
(
SELECT 
F.Id ID_FACTURA,
CASE F.DocumentType WHEN '1' THEN 'FACTURA EAPB CON CONTRATO'
					WHEN '2' THEN 'FACTURA EAPB SIN CONTRATO'
					WHEN '3' THEN 'FACTURA PARTICULAR'
					WHEN '4' THEN 'FACTURA CAPITA'
					WHEN '5' THEN 'CONTROL CAPITACION'
					WHEN '6' THEN 'FACTURA BASICA'
					WHEN '7' THEN 'FACTURA VENTA PRODUCTOS'END 'TIPO REGISTRO',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' 
				   WHEN '2' THEN 'CEDULA DE EXTRANJERIA' 
				   WHEN '3' THEN 'TARJETA DE IDENTIDAD' 
				   WHEN '4' THEN 'REGISTRO CIVIL' 
				   WHEN '5' THEN 'PASAPORTE' 
				   WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' 
				   WHEN '7' THEN 'MENOR SIN IDENTIFICACION' 
				   WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION' 
				   WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' 
				   WHEN '10' THEN 'CARNET DIPLOMATICO'
				   WHEN '11' THEN 'SALVOCONDUCTO' 
				   WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
				   WHEN '13' THEN 'PERMISO POR PROTECCION TEMPORAL'
				   WHEN '14' THEN 'DOCUMENTO EXTRANJERO'
				   WHEN '15' THEN 'SIN IDENTIFICACION' ELSE 'N/A' END AS 'TIPO IDENTIFICACION',
ISNULL(F.PatientCode, 0) AS 'IDENTIFICACION',
CASE WHEN RTRIM(PAC.IPNOMCOMP) IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'N/A' 
	 WHEN PAC.IPNOMCOMP IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'N/A' ELSE RTRIM(PAC.IPNOMCOMP) END AS 'PACIENTE',
F.AdmissionNumber 'INGRESO',
CAST(ING.IFECHAING AS DATE)'FECHA INGRESO',
CAST(ISNULL(ING.FECHEGRESO,ING.IFECHAING) AS DATE) 'FECHA EGRESO',
F.InvoiceNumber 'NRO FACTURA',
CAST(F.InvoiceDate AS DATE)'FECHA FACTURA',
F.TotalInvoice 'TOTAL FACTURA',
F.ThirdPartySalesValue AS 'VR TOTAL ENTIDAD',
F.ThirdPartyDiscountValue AS 'VR TOTAL DESCUENTO',
F.TotalPatientSalesPrice AS 'VR TOTAL CUOTA RECUPERACION',
CASE F.STATUS WHEN '1' THEN 'FACTURADO' 
			  WHEN '2' THEN 'ANULADO' END AS 'ESTADO FACTURA',
F.HealthAdministratorId 'ID ENTIDAD',
RTRIM(T.Nit) 'NIT ENTIDAD',
RTRIM(HA.Code) 'CODIGO ENTIDAD',
RTRIM(HA.Name) 'ENTIDAD' ,
RTRIM(CG.code) 'CODIGO GRUPO',
RTRIM(CG.Name) 'GRUPO DE ATENCION',
CASE WHEN HA.EntityType LIKE '1' THEN 'EPS CONTRIBUTIVO' 
	 WHEN HA.EntityType LIKE '2' THEN 'EPS SUBSIDIADO' 
	 WHEN HA.EntityType LIKE '3' THEN 'ET VINCULADO MUNICIPIO'
	 WHEN HA.EntityType LIKE '4' THEN 'ET VINCULADOS DAPARTAMENTO'
	 WHEN HA.EntityType LIKE '5' THEN 'ARL RIESGO LABORALES'
	 WHEN HA.EntityType LIKE '6' THEN 'MP MEDICINA PREPAGADA'
	 WHEN HA.EntityType LIKE '7' THEN 'IPS PRIVADA'
	 WHEN HA.EntityType LIKE '8' THEN 'IPS PUBLICA' 
	 WHEN HA.EntityType LIKE '9' THEN 'REGIMEN ESPECIAL'
	 WHEN HA.EntityType LIKE '10' THEN 'ACCIDENTE DE TRANSITO'
	 WHEN HA.EntityType LIKE '11' THEN 'FOSYGA' 
	 WHEN HA.EntityType LIKE '12' THEN 'OTROS' 
	 WHEN HA.EntityType IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'N/A'
	 WHEN HA.EntityType IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'N/A' END AS [TIPO REGIMEN],
CASE WHEN ING.TIPOINGRE=1 THEN 'AMBULATORIO' 
	 WHEN ING.TIPOINGRE=2 THEN 'HOSPITALARIO' 
	 WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '1' THEN 'FACTURA EAPB CON CONTRATO'
	 WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '2' THEN 'FACTURA EAPB SIN CONTRATO'
	 WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '3' THEN 'FACTURA PARTICULAR'
	 WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'FACTURA CAPITA' 
	 WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '5' THEN 'CONTROL CAPITACION'
	 WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'FACTURA BASICA' 
	 WHEN ING.TIPOINGRE IS NULL AND F.DOCUMENTTYPE LIKE '7' THEN 'FACTURA VENTA PRODUCTOS' END AS 'TIPO AMBITO INGRESO',
USU.NOMUSUARI 'USUARIO FACTURO',
CAST(F.InvoicedDate AS DATE) 'FECHA REGISTRO',
ISNULL(DIA.CODDIAGNO,DIAG.CODDIAGNO ) 'CODIGO CIE10',
ISNULL(RTRIM(DIA.NOMDIAGNO),RTRIM(DIAG.NOMDIAGNO)) 'DIAGNOSTICO',
CASE WHEN ING.IAUTORIZA IS NULL AND F.DOCUMENTTYPE LIKE '4' THEN 'N/A' 
	 WHEN ING.IAUTORIZA IS NULL AND F.DOCUMENTTYPE LIKE '6' THEN 'N/A' 
	 WHEN ING.IAUTORIZA LIKE ' ' THEN 'N/A' ELSE ING.IAUTORIZA END AS 'AUTORIZACION', 
ISNULL(IIF (F.DOCUMENTTYPE=6, LTRIM(FU2.CODE) + ' - ' + FU2.NAME,
ISNULL(FU.CODE + ' - ' +FU.Name, 
LTRIM(ING.UFUCODIGO) + ' - ' + UF.NAME)), 'N/A') AS [UNIDAD FUNCIONAL EGRESO],
C.Name 'CATEGORIA FACTURA',
F.AnnulmentDate 'FECHA ANULACION',
CASE F.STATUS WHEN '1' THEN CAST(F.InvoiceDate AS DATE) 
			  WHEN '2' THEN CAST(F.AnnulmentDate AS DATE) END AS 'FECHA BUSQUEDA'
FROM Billing.Invoice AS F 
INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES = F.AdmissionNumber
INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =F.PatientCode
INNER JOIN Contract .HealthAdministrator AS HA ON HA.Id =F.HealthAdministratorId
INNER JOIN Contract .CareGroup AS CG ON CG.Id =F.CareGroupId
INNER JOIN Common.ThirdParty AS T ON T.Id = F.ThirdPartyId
INNER JOIN Billing.InvoiceCategories AS C ON C.Id = F.InvoiceCategoryId
LEFT JOIN DBO.SEGusuaru AS USU ON USU.CODUSUARI =F.InvoicedUser
LEFT JOIN DBO.INDIAGNOS AS DIA ON DIA.CODDIAGNO =ISNULL(ING.CODDIAEGR ,ING.CODDIAING )
LEFT JOIN Payroll.FunctionalUnit AS UF ON UF.Code = ING.UFUCODIGO
LEFT JOIN Payroll.FunctionalUnit AS FU ON ING.UFUEGRMED=FU.CODE
LEFT JOIN Billing.BasicBilling AS BB ON BB.InvoiceId =F.Id
LEFT JOIN Payroll.FunctionalUnit AS FU2 ON BB.FunctionalUnitId =FU2.Id
LEFT JOIN dbo.INDIAGNOS AS DIAG ON DIAG.CODDIAGNO = F.OutputDiagnosis
--WHERE 
-- CAST(F.InvoiceDate AS DATE) BETWEEN CAST(GETDATE()-1 AS DATE) AND CAST(GETDATE() AS DATE) OR
-- CAST(F.AnnulmentDate AS DATE) BETWEEN CAST(GETDATE()-1 AS DATE) AND CAST(GETDATE() AS DATE)
),

CTE_ALTA_MEDICA
AS
(
  SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(FECALTPAC) 'FECHA ALTA' FROM DBO.HCREGEGRE EGR
  INNER JOIN CTE_FACTURACION_CABECERA AS PEN ON PEN.INGRESO =EGR.NUMINGRES 
  GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI
),

CTE_HISTORIAS_AMBULATORIAS
AS
(
  SELECT HIS.NUMINGRES ,HIS.IPCODPACI ,MAX(FECHISPAC) AS 'FECHA ALTA'    FROM  DBO.HCHISPACA HIS
  INNER JOIN CTE_FACTURACION_CABECERA AS PEN ON PEN.INGRESO =HIS.NUMINGRES 
  WHERE HIS.GENCONEXT =1
  GROUP BY HIS.NUMINGRES ,HIS.IPCODPACI
),

CTE_AMBITO
AS
(
select 
ING.NUMINGRES, 
CASE UNF.UnitType   WHEN 1 THEN 'URGENCIAS' 
					WHEN 2 THEN 'HOSPITALIZACION'
					WHEN 3 THEN 'APOYO DIAGNOSTICO'
					WHEN 4 THEN 'APOYO TERAPEUTICO'
					WHEN 5 THEN 'UCI'
					WHEN 6 THEN 'UCI'
					WHEN 7 THEN 'UCI'
					WHEN 8 THEN 'UCI'
					WHEN 9 THEN 'UCI'
					WHEN 10 THEN 'UCI'
					WHEN 11 THEN 'UCI'
					WHEN 12 THEN 'UNIDAD RENAL'
					WHEN 13 THEN 'UNIDAD ONCOLOGICA' 
					WHEN 14 THEN 'UNIDAD MEDICINA NUCLEAR'
					WHEN 15 THEN 'AMBULATORIO'
					WHEN 16 THEN 'UNIDAD MENTAL'
					WHEN 17 THEN 'UNIDAD DE QUEMADOS'
					WHEN 18 THEN 'UNIDAD DE CUIDADOS PALATIVOS'
					WHEN 19 THEN 'CIRUGIA'
					WHEN 20 THEN 'LABORATORIOS'
					WHEN 21 THEN 'CARDIOLOGIA NO INVASIVA'
					WHEN 22 THEN 'CARDIOLOGIA INVASIVA'
					WHEN 23 THEN 'GINECO OBSTETRICIA'
					WHEN 24 THEN 'CONSULTA EXTERNA GINOCO OBSTETRICIA'
					WHEN 30 THEN 'OTRAS'
					WHEN 31 THEN 'CONSULTA PRIORITARIA' END AS [AMBITO DE INGRESO],
UNF.Code+'-'+UNF.Name [UNIDAD FUNCIONAL DE INGRESO],
CASE WHEN UNI.UFUCODIGO IS NULL AND UNF.Code='1112010' THEN '1112010 -CONSULTA EXTERNA C.E' ELSE UNI.UFUCODIGO+'-'+UNI.UFUDESCRI END AS [UNIDAD FUNCIONAL DE EGRESO],
 CASE WHEN UNI.UFUTIPUNI=1 THEN 'URGENCIAS' 
	  WHEN UNI.UFUTIPUNI=2 THEN 'HOSPITALIZACION'
	  WHEN UNI.UFUTIPUNI=3 THEN 'APOYO DIAGNOSTICO'
	  WHEN UNI.UFUTIPUNI=4 THEN 'APOYO TERAPEUTICO'
	  WHEN UNI.UFUTIPUNI=5 THEN 'UCI'
	  WHEN UNI.UFUTIPUNI=6 THEN 'UCI'
	  WHEN UNI.UFUTIPUNI=7 THEN 'UCI'
	  WHEN UNI.UFUTIPUNI=8 THEN 'UCI'
	  WHEN UNI.UFUTIPUNI=9 THEN 'UCI'
	  WHEN UNI.UFUTIPUNI=10 THEN 'UCI'
	  WHEN UNI.UFUTIPUNI=11 THEN 'UCI'
	  WHEN UNI.UFUTIPUNI=12 THEN 'UNIDAD RENAL'
	  WHEN UNI.UFUTIPUNI=13 THEN 'UNIDAD ONCOLOGICA' 
	  WHEN UNI.UFUTIPUNI=14 THEN 'UNIDAD MEDICINA NUCLEAR'
	  WHEN UNI.UFUTIPUNI=15 THEN 'AMBULATORIO'
	  WHEN UNI.UFUTIPUNI=16 THEN 'UNIDAD MENTAL'
	  WHEN UNI.UFUTIPUNI=17 THEN 'UNIDAD DE QUEMADOS'
	  WHEN UNI.UFUTIPUNI=18 THEN 'UNIDAD DE CUIDADOS PALATIVOS'
	  WHEN UNI.UFUTIPUNI=19 THEN 'CIRUGIA'
	  WHEN UNI.UFUTIPUNI=20 THEN 'LABORATORIOS'
	  WHEN UNI.UFUTIPUNI=21 THEN 'CARDIOLOGIA NO INVASIVA'
	  WHEN UNI.UFUTIPUNI=22 THEN 'CARDIOLOGIA INVASIVA'
	  WHEN UNI.UFUTIPUNI=23 THEN 'GINECO OBSTETRICIA'
	  WHEN UNI.UFUTIPUNI=24 THEN 'CONSULTA EXTERNA GINOCO OBSTETRICIA'
	  WHEN UNI.UFUTIPUNI=30 THEN 'OTRAS'
	  WHEN UNI.UFUTIPUNI=31 THEN 'CONSULTA PRIORITARIA' 
	  WHEN UNI.UFUCODIGO IS NULL AND UNF.Code='1112010' THEN 'AMBULATORIO' END  as [AMBITO DE EGRESO]
from 
DBO.ADINGRESO ING INNER JOIN
Payroll.FunctionalUnit UNF ON ING.UFUCODIGO=UNF.Code LEFT JOIN
dbo.HCREGEGRE EGR ON ING.NUMINGRES=EGR.NUMINGRES LEFT JOIN
dbo.INUNIFUNC UNI ON EGR.UFUCODIGO = UNI.UFUCODIGO
),

CTE_FACTURA_DETALLE
AS
(
SELECT  CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
FCAB.[NIT ENTIDAD],
SUBSTRING(FCAB.ENTIDAD,1,50) 'ENTIDAD',
FCAB.[CODIGO GRUPO],
FCAB.[GRUPO DE ATENCION],
FCAB.INGRESO,
FCAB.[FECHA INGRESO],
FCAB.[FECHA EGRESO],
FCAB.[TIPO IDENTIFICACION],
FCAB.IDENTIFICACION,
FCAB.PACIENTE,
FCAB.[ESTADO FACTURA],
FCAB.[NRO FACTURA],
FCAB.[FECHA FACTURA],
FCAB.[TOTAL FACTURA],
FCAB.[VR TOTAL DESCUENTO],
FCAB.[VR TOTAL ENTIDAD],
FCAB.[VR TOTAL CUOTA RECUPERACION],
SO.Code 'CAB_ORD_NRO',
SO.OrderDate 'CAB_ORD_FECHA_ORDEN',
CASE SOD.RecordType WHEN 1 THEN 'Servicios' 
					WHEN 2 THEN 'Medicamentos' ELSE 'N/A' END 'DET_ORD_TIPO',
--in v2
CAST(SOD.ServiceDate AS DATE) AS 'FECHA DE SERVICIO',
CAST(SOD.ServiceDate AS TIME) AS 'HORA DE SERVICIO',
--fn v2
ISNULL(GF.Name, GF2.Name) AS 'DET_ORD_GRUPO FACTURACION',
ISNULL(CGR.Code + '-' + CGR.Name, PG.Code + '-' + PG.NAME) 'DET_ORD_GRUPO', 
ISNULL(CSG.CODE + '-' + CSG.Name, PSG.Code + '-' + PSG.NAME) 'DET_ORD_SUBGRUPO',
CASE SOD.Presentation WHEN 1 THEN 'No quirurgico' 
					  WHEN 2 THEN 'Quirurgico'
					  WHEN 3 THEN 'Paquete' ELSE 'PRODUCTO' END 'DET_ORD_PRESENTACION',
ISNULL(CUPS.Code,'N/A') 'DET_ORD_CUPS',SUBSTRING(ISNULL(RTRIM(CUPS.Description),'N/A'),1,60) 'DET_ORD_DESCRIPCION_CUPS',
/*IN V3*/CUPS.RIPSCode AS 'CODIGO RIPS',/*FN V3*/
ISNULL(RTRIM(IPS.Code),RTRIM(IPR.CODE)) 'DET_ORD_CODIGO_SERVICIO/PRODUCTO',SUBSTRING(ISNULL(RTRIM(IPS.Name),RTRIM(IPR.NAME)),1,60) 'DET_ORD_DESCRIPCION_SERVICIO/PRODUCTO',
ISNULL(SERVICIOSIPSQ.Code, 'N/A') AS 'DET_ORDQX_SUBCODIGO', SUBSTRING(ISNULL(RTRIM(SERVICIOSIPSQ.Name), 'N/A'),1,60) AS 'DET_ORDQX_SUBNOMBRE',
'' 'DET VISUALIZA FACTURA',
CASE SOD.IsPackage WHEN 1 THEN 'PAQUETE (INCLUYE OTROS SERVICIOS)' 
				   WHEN 0 THEN 'NO ES PAQUETE' ELSE 'N/A' END 'DET_ORD_PAQUETE',
CASE SOD.Packaging WHEN 1 THEN 'INCLUIDO EN PAQUETE' 
				   WHEN 0 THEN 'NO INCLUIDO EN PAQUETE' ELSE 'N/A' END 'DET_ORD_INCLUIDO_EN_PAQUETE',
ISNULL(CUPS_PAQ.Code,'N/A') 'DET_ORD_CUPS_PAQUETE',
SUBSTRING(ISNULL(RTRIM(CUPS_PAQ.Description),'N/A'),1,60) 'DET_ORD_DESCRIPCION_CUPS_PAQUETE',

CASE sod.SettlementType WHEN 1 THEN 'Por manual de tarifas' 
						WHEN 2 THEN '% de otro servicio cargado' 
						WHEN 3 THEN '100% incluido dentro de otro servicio (No se cobra nada)'
						WHEN 4 THEN '% del mismo servicio' ELSE 'N/A' END 'DET_ORD_TIPO_LIQUIDACION',
ISNULL(CUPS_INC.Code,'N/A') 'DET_ORD_CUPS_INCLUIDO',
SUBSTRING(ISNULL(RTRIM(CUPS_INC.Description),'N/A'),1,60) 'DET_ORD_DESCRIPCION_CUPS_INCLUIDO',
FU.Code 'DET_ORD_CODIGO_UNIDAD_FUNCIONAL',
RTRIM(FU.Name)'DET_ORD_UNIDAD_FUNCIONAL_PRESTO_SERVICIO',
COST.Code 'DET_ORD_COD_CENTRO_COSTO',RTRIM(COST.Name) 'DET_ORD_CENTRO_COSTO',
RTRIM(ISNULL(DQ.PERFORMSHEALTHPROFESSIONALCODE,ISNULL(MED.CODPROSAL,'000'))) 'DET_ORD_IDENTIFICACION_PROFESIONAL' ,RTRIM(ISNULL(MEDQX.NOMMEDICO,ISNULL(MED.NOMMEDICO,'N/A'))) 'DET_ORD_PROFESIONAL' ,
RTRIM(ISNULL(ESPQX.DESESPECI,ISNULL(ESPMED.DESESPECI,'N/A'))) 'DET_ORD_ESPECIALIDAD',ISNULL(DQ.InvoicedQuantity,SOD.InvoicedQuantity) 'DET_ORD_CANTIDAD' ,
ISNULL(DQ.RateManualSalePrice,SOD.RateManualSalePrice) 'DET_ORD_VALOR_SERVICIO',ISNULL(DQ.TOTALSALESPRICE,sod.TotalSalesPrice) 'DET_ORD_VALOR_UNITARIO' ,
ISNULL(DQ.TOTALSALESPRICE,SOD.GrandTotalSalesPrice) 'DET_ORD_VALOR_TOTAL',
CASE ISNULL(IPS.POS,IPR.POSProduct ) WHEN 1 THEN 'PBS' ELSE 'NO PBS' END 'DET_ORD_TECNOLOGIA_PBS',
--FCAB.[TIPO AMBITO INGRESO],
IIF(FCAB.[TIPO AMBITO INGRESO]='HOSPITALARIO',
ALT.[FECHA ALTA],
ISNULL(AMB.[FECHA ALTA],
FCAB.[FECHA INGRESO])) 'FECHA ALTA MEDICA',
FCAB.[FECHA ANULACION],'' 'CAMA ACTIVA' ,
SOD.ID 'ID_ORDE_DETALLE',
0 'ID_ORDE_DETALLE_QX',
FCAB.ID_FACTURA,
FCAB.[ID ENTIDAD],
fcab.[TIPO REGISTRO], 
FCAB.[FECHA BUSQUEDA],
CAST(SOD.ServiceDate AS DATE) 'FECHA SERVICIO BUSQUEDA',
'SI' 'FACTURADO',
 SOD.AuthorizationNumber 'AUTORIZACION SERVICIO', FCAB.AUTORIZACION 
FROM Billing .InvoiceDetail AS ID 
INNER JOIN CTE_FACTURACION_CABECERA AS FCAB ON FCAB.ID_FACTURA =ID.InvoiceId
INNER JOIN Billing .ServiceOrderDetail AS SOD ON SOD.Id =ID.ServiceOrderDetailId 
INNER JOIN Billing .ServiceOrder AS SO ON SO.Id =SOD.ServiceOrderId 
INNER JOIN Payroll.FunctionalUnit AS FU ON FU.Id = SOD.PerformsFunctionalUnitId
INNER JOIN Contract .CareGroup AS CG ON CG.Id =SOD.CareGroupId
INNER JOIN Contract .HealthAdministrator AS HA ON HA.Id =ISNULL(SOD.HealthAdministratorId,FCAB.[ID ENTIDAD] )
LEFT JOIN Inventory.InventoryProduct AS PR ON PR.Id = SOD.ProductId
LEFT JOIN Contract.CUPSEntity AS CUPS ON CUPS.Id = SOD.CUPSEntityId
LEFT JOIN Contract.IPSService AS IPS ON IPS.Id = SOD.IPSServiceId
LEFT JOIN Billing .ServiceOrderDetail AS SOD_PAQ ON SOD_PAQ.Id =SOD.PackageServiceOrderDetailId
LEFT JOIN Contract.CUPSEntity AS CUPS_PAQ ON CUPS_PAQ.Id = SOD_PAQ.CUPSEntityId
LEFT JOIN Inventory.InventoryProduct AS IPR ON IPR.Id = SOD.ProductId
LEFT JOIN dbo.INPROFSAL AS MED ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
LEFT JOIN dbo.INESPECIA AS ESPMED ON ESPMED.CODESPECI = MED.CODESPEC1
LEFT JOIN Payroll.CostCenter AS COST ON COST.Id =SOD.CostCenterId
LEFT JOIN Billing .ServiceOrderDetail AS SOD_INC ON SOD_INC.Id =SOD.IncludeServiceOrderDetailId
LEFT JOIN Contract.CUPSEntity AS CUPS_INC ON CUPS_INC.Id = SOD_INC.CUPSEntityId
LEFT JOIN Inventory.ProductGroup AS PG ON PG.ID =IPR.ProductGroupId
LEFT JOIN Inventory.ProductSubGroup AS PSG ON PSG.ID =IPR.ProductSubGroupId
LEFT JOIN Contract.CupsSubgroup AS CSG ON CSG.Id =CUPS .CUPSSubGroupId
LEFT JOIN Contract.CupsGroup AS CGR ON CGR.Id =CSG.CupsGroupId
LEFT JOIN Billing.BillingGroup AS GF ON GF.Id = CUPS.BillingGroupId
LEFT JOIN Billing.BillingGroup AS GF2 ON GF2.Id = IPR.BillingGroupId
LEFT JOIN Billing.ServiceOrderDetailSurgical AS DQ ON DQ.ServiceOrderDetailId = SOD.Id AND DQ.OnlyMedicalFees = '0'
LEFT JOIN dbo.INPROFSAL AS MEDQX ON MEDQX.CODPROSAL = DQ.PerformsHealthProfessionalCode
LEFT JOIN dbo.INESPECIA AS ESPQX ON ESPQX.CODESPECI = MEDQX.CODESPEC1
LEFT JOIN Contract.IPSService AS SERVICIOSIPSQ ON SERVICIOSIPSQ.Id = DQ.IPSServiceId
LEFT JOIN CTE_ALTA_MEDICA AS ALT ON ALT.NUMINGRES =FCAB.INGRESO 
LEFT JOIN CTE_HISTORIAS_AMBULATORIAS AS AMB ON AMB.NUMINGRES =FCAB.INGRESO
WHERE SOD.InvoicedQuantity <>'0'
),

CTE_ORDENES_FACTURADA_PAQUETE
AS
(
SELECT   
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
ORDF.[NIT ENTIDAD],
SUBSTRING(ORDF.ENTIDAD,1,50) 'ENTIDAD',
ORDF.[CODIGO GRUPO],
ORDF.[GRUPO DE ATENCION],
ORDF.INGRESO ,
ORDF.[FECHA INGRESO],ORDF.[FECHA EGRESO] ,
ORDF.[TIPO IDENTIFICACION],ORDF.IDENTIFICACION ,ORDF.PACIENTE,ORDF.[ESTADO FACTURA] ,
ORDF.[NRO FACTURA],ORDF.[FECHA FACTURA] ,ORDF.[TOTAL FACTURA],ORDF.[VR TOTAL DESCUENTO], 
ORDF.[VR TOTAL ENTIDAD] ,ORDF.[VR TOTAL CUOTA RECUPERACION],
SO.Code 'CAB_ORD_NRO',SO.OrderDate 'CAB_ORD_FECHA_ORDEN',
CASE SOD.RecordType WHEN 1 THEN 'Servicios' WHEN 2 THEN 'Medicamentos' ELSE 'N/A' END 'DET_ORD_TIPO',
--in v2
CAST(SOD.ServiceDate AS DATE) AS 'FECHA DE SERVICO',
CAST(SOD.ServiceDate AS TIME) AS 'HORA DE SERVICO',
--fn v2
ISNULL(GF.Name, GF2.Name) AS 'DET_ORD_GRUPO FACTURACION',ISNULL(CGR.Code + '-' + CGR.Name, PG.Code + '-' + PG.NAME) 'DET_ORD_GRUPO', 
ISNULL(CSG.CODE + '-' + CSG.Name, PSG.Code + '-' + PSG.NAME) 'DET_ORD_SUBGRUPO',
CASE SOD.Presentation WHEN 1 THEN 'No quirurgico' WHEN 2 THEN 'Quirurgico'WHEN 3 THEN 'Paquete' ELSE 'PRODUCTO' END 'DET_ORD_PRESENTACION',
ISNULL(CUPS.Code,'N/A') 'DET_ORD_CUPS',SUBSTRING(ISNULL(RTRIM(CUPS.Description),'N/A'),1,60) 'DET_ORD_DESCRIPCION_CUPS',
/*IN V3*/CUPS.RIPSCode AS 'CODIGO RIPS',/*FN V3*/
ISNULL(RTRIM(IPS.Code),RTRIM(IPR.CODE)) 'DET_ORD_CODIGO_SERVICIO/PRODUCTO',SUBSTRING(ISNULL(RTRIM(IPS.Name),RTRIM(IPR.NAME)),1,60) 'DET_ORD_DESCRIPCION_SERVICIO/PRODUCTO',
ISNULL(SERVICIOSIPSQ.Code, 'N/A') AS 'DET_ORDQX_SUBCODIGO', ISNULL(RTRIM(SERVICIOSIPSQ.Name), 'N/A') AS 'DET_ORDQX_SUBNOMBRE',
'' 'DET VISUALIZA FACTURA',
CASE SOD.IsPackage WHEN 1 THEN 'PAQUETE (INCLUYE OTROS SERVICIOS)' WHEN 0 THEN 'NO ES PAQUETE' ELSE 'N/A' END 'DET_ORD_PAQUETE',
CASE SOD.Packaging WHEN 1 THEN 'INCLUIDO EN PAQUETE' WHEN 0 THEN 'NO INCLUIDO EN PAQUETE' ELSE 'N/A' END 'DET_ORD_INCLUIDO_EN_PAQUETE',ISNULL(CUPS_PAQ.Code,'N/A') 'DET_ORD_CUPS_PAQUETE',
SUBSTRING(ISNULL(RTRIM(CUPS_PAQ.Description),'N/A'),1,60) 'DET_ORD_DESCRIPCION_CUPS_PAQUETE',
CASE sod.SettlementType WHEN 1 THEN 'Por manual de tarifas' WHEN 2 THEN '% de otro servicio cargado' WHEN 3 THEN '100% incluido dentro de otro servicio (No se cobra nada)'
WHEN 4 THEN '% del mismo servicio' ELSE 'N/A' END 'DET_ORD_TIPO_LIQUIDACION', ISNULL(CUPS_INC.Code,'N/A') 'DET_ORD_CUPS_INCLUIDO',
SUBSTRING(ISNULL(RTRIM(CUPS_INC.Description),'N/A'),1,60) 'DET_ORD_DESCRIPCION_CUPS_INCLUIDO',
FU.Code 'DET_ORD_CODIGO_UNIDAD_FUNCIONAL',
RTRIM(FU.Name) 'DET_ORD_UNIDAD_FUNCIONAL_PRESTO_SERVICIO',
COST.Code 'DET_ORD_COD_CENTRO_COSTO',RTRIM(COST.Name) 'DET_ORD_CENTRO_COSTO',
RTRIM(ISNULL(DQ.PERFORMSHEALTHPROFESSIONALCODE,ISNULL(MED.CODPROSAL,'000'))) 'DET_ORD_IDENTIFICACION_PROFESIONAL' ,RTRIM(ISNULL(MEDQX.NOMMEDICO,ISNULL(MED.NOMMEDICO,'N/A'))) 'DET_ORD_PROFESIONAL' ,
RTRIM(ISNULL(ESPQX.DESESPECI,ISNULL(ESPMED.DESESPECI,'N/A'))) 'DET_ORD_ESPECIALIDAD',ISNULL(DQ.InvoicedQuantity,SOD.InvoicedQuantity) 'DET_ORD_CANTIDAD' ,
ISNULL(DQ.RateManualSalePrice,SOD.RateManualSalePrice) 'DET_ORD_VALOR_SERVICIO',ISNULL(DQ.TOTALSALESPRICE,sod.TotalSalesPrice) 'DET_ORD_VALOR_UNITARIO' ,
ISNULL(DQ.TOTALSALESPRICE,SOD.GrandTotalSalesPrice) 'DET_ORD_VALOR_TOTAL',
CASE ISNULL(IPS.POS,IPR.POSProduct ) WHEN 1 THEN 'PBS' ELSE 'NO PBS' END 'DET_ORD_TECNOLOGIA_PBS',
ORDF.[FECHA ALTA MEDICA],
ORDF.[FECHA ANULACION],'' 'CAMA ACTIVA' ,
SOD.ID 'ID_ORDE_DETALLE',
DQ.ID 'ID_ORDE_DETALLE_QX',
ORDF.ID_FACTURA,
ORDF.[ID ENTIDAD],
ORDF.[TIPO REGISTRO], 
ORDF.[FECHA BUSQUEDA],
CAST(SOD.ServiceDate AS DATE) 'FECHA SERVICIO BUSQUEDA',
'SI' 'FACTURADO',
 SOD.AuthorizationNumber 'AUTORIZACION SERVICIO', '' AUTORIZACION 
FROM Billing.ServiceOrder AS SO 
  INNER JOIN Billing.ServiceOrderDetail AS SOD ON SO.Id =SOD.ServiceOrderId 
  INNER JOIN CTE_FACTURA_DETALLE AS ORDF ON SOD.PackageServiceOrderDetailId =ORDF.ID_ORDE_DETALLE 
  INNER JOIN Payroll.FunctionalUnit AS FU ON FU.Id = SOD.PerformsFunctionalUnitId
  INNER JOIN Contract.CareGroup AS CG ON CG.Id =SOD.CareGroupId
  INNER JOIN Contract.HealthAdministrator AS HA ON HA.Id =ISNULL(SOD.HealthAdministratorId,ORDF.[ID ENTIDAD])
  LEFT JOIN Inventory.InventoryProduct AS PR ON PR.Id = SOD.ProductId
  LEFT JOIN Contract.CUPSEntity AS CUPS ON CUPS.Id = SOD.CUPSEntityId
  LEFT JOIN Contract.IPSService AS IPS ON IPS.Id = SOD.IPSServiceId
  LEFT JOIN Billing .ServiceOrderDetail AS SOD_PAQ ON SOD_PAQ.Id =SOD.PackageServiceOrderDetailId
  LEFT JOIN Contract.CUPSEntity AS CUPS_PAQ ON CUPS_PAQ.Id = SOD_PAQ.CUPSEntityId
  LEFT JOIN Inventory.InventoryProduct AS IPR ON IPR.Id = SOD.ProductId
  LEFT JOIN dbo.INPROFSAL AS MED ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
  LEFT JOIN dbo.INESPECIA AS ESPMED ON ESPMED.CODESPECI = MED.CODESPEC1
  LEFT JOIN Payroll.CostCenter AS COST ON COST.Id =SOD.CostCenterId
  LEFT JOIN Billing .ServiceOrderDetail AS SOD_INC ON SOD_INC.Id =SOD.IncludeServiceOrderDetailId
  LEFT JOIN Contract.CUPSEntity AS CUPS_INC ON CUPS_INC.Id = SOD_INC.CUPSEntityId
  LEFT JOIN Inventory.ProductGroup AS PG ON PG.ID =IPR.ProductGroupId
  LEFT JOIN Inventory.ProductSubGroup AS PSG ON PSG.ID =IPR.ProductSubGroupId
  LEFT JOIN Contract.CupsSubgroup AS CSG ON CSG.Id =CUPS .CUPSSubGroupId
  LEFT JOIN Contract.CupsGroup AS CGR ON CGR.Id =CSG.CupsGroupId
  LEFT JOIN Billing.BillingGroup AS GF ON GF.Id = CUPS.BillingGroupId
  LEFT JOIN Billing.BillingGroup AS GF2 ON GF2.Id = IPR.BillingGroupId
  LEFT JOIN Billing.ServiceOrderDetailSurgical AS DQ ON DQ.ServiceOrderDetailId = SOD.Id AND DQ.OnlyMedicalFees = '0'
  LEFT JOIN dbo.INPROFSAL AS MEDQX ON MEDQX.CODPROSAL = DQ.PerformsHealthProfessionalCode
  LEFT JOIN dbo.INESPECIA AS ESPQX ON ESPQX.CODESPECI = MEDQX.CODESPEC1
  LEFT JOIN Contract.IPSService AS SERVICIOSIPSQ ON SERVICIOSIPSQ.Id = DQ.IPSServiceId
  WHERE SOD.PackageServiceOrderDetailId IS NOT NULL 
)

SELECT 
  *,
  1 as 'CANTIDAD',
  YEAR([FECHA BUSQUEDA]) AS 'AÑO BUSQUEDA',
  MONTH([FECHA BUSQUEDA]) AS 'MES BUSQUEDA',
  CONCAT(FORMAT(MONTH([FECHA BUSQUEDA]), '00') ,' - ', 
	   CASE MONTH([FECHA BUSQUEDA]) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 CTE_FACTURA_DETALLE FAC 
 LEFT JOIN CTE_AMBITO AMBI ON FAC.INGRESO=AMBI.NUMINGRES
UNION ALL
 SELECT
  *,
  1 as 'CANTIDAD',
  YEAR([FECHA BUSQUEDA]) AS 'AÑO BUSQUEDA',
  MONTH([FECHA BUSQUEDA]) AS 'MES BUSQUEDA',
  CONCAT(FORMAT(MONTH([FECHA BUSQUEDA]), '00') ,' - ', 
	   CASE MONTH([FECHA BUSQUEDA]) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM CTE_ORDENES_FACTURADA_PAQUETE PAQ LEFT JOIN
CTE_AMBITO AMBI ON PAQ.INGRESO=AMBI.NUMINGRES
