-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewPendientesDeOrdenesGases
-- Extracted by Fabric SQL Extractor SPN v3.9.0





CREATE VIEW [Report].[ViewPendientesDeOrdenesGases]
as


WITH CTE_GASES
AS
(
SELECT 'GASES MEDICINALES' EntityName,iif(A.GENSERVICEORDER IS NULL,'SIN ORDEN','CON ORDEN')  'ORDENE DE SERVICIO' ,'HOSPITALARIO'  'AMBITO',E.DESVIAADM 'VIA',
E.CODSERIPS 'CODIGO CUPS',B.DESSERIPS 'PROCEDIMIENTO CUPS',A.NUMINGRES 'INGRESO',A.IPCODPACI 'IDENTIFICACION',RTRIM(i.IPNOMCOMP) 'PACIENTE' ,
A.FECHREGIS AS DIAS,A.LITRXMINUT,A.HORAINICIA,A.HORAFINAL,A.TOTHORAS,A.TOTLITADM,C.NOMMEDICO 'PROFESIONAL',D.UFUDESCRI 'UNIDAD FUNCIONAL',ING.IESTADOIN 'ESTADO INGRESO'

FROM dbo.HCCONOXIG AS A 
INNER JOIN dbo.INPROFSAL AS C ON A.CODPROSAL=C.CODPROSAL 
INNER JOIN dbo.INUNIFUNC AS D ON A.UFUCODIGO=D.UFUCODIGO 
INNER JOIN dbo.HCPARCONO E ON A.CODVIAADM=E.CODVIAADM
inner join dbo.INPACIENT i on a.IPCODPACI = i.IPCODPACI 
inner join  dbo.ADINGRESO AS ING  on ING.NUMINGRES = A.NUMINGRES  
INNER JOIN dbo.INCUPSIPS B with (nolock) ON E.CODSERIPS=B.CODSERIPS 
WHERE A.GENSERVICEORDER IS NULL
union all

SELECT 'GASES MEDICINALES' EntityName,iif(A.GENSERVICEORDER IS NULL,'SIN ORDEN','CON ORDEN')  'ORDENE DE SERVICIO' , 'HOSPITALARIO'  'AMBITO',E.DESVIAADM 'VIA',
E.CODSERIPS 'CODIGO CUPS',B.DESSERIPS 'PROCEDIMIENTO CUPS',
A.NUMINGRES 'INGRESO',A.IPCODPACI 'IDENTIFICACION',RTRIM(PAC.IPNOMCOMP) 'PACIENTE' ,
		
A.FECHREGIS AS DIAS,A.LITRXMINUT,A.HORAINICIA,A.HORAFINAL,A.TOTHORAS,A.TOTLITADM,C.NOMMEDICO 'PROFESIONAL',D.UFUDESCRI 'UNIDAD FUNCIONAL',ING.IESTADOIN 'ESTADO INGRESO'
FROM dbo.HCCONOXIG AS A 
INNER JOIN dbo.INPROFSAL AS C ON A.CODPROSAL=C.CODPROSAL 
INNER JOIN dbo.INUNIFUNC AS D ON A.UFUCODIGO=D.UFUCODIGO 
INNER JOIN dbo.HCPARCONO E ON A.CODVIAADM=E.CODVIAADM
inner join dbo.HCINGRESORECNAC INGMH  on a.NUMINGRES = INGMH .NUMINGRESHIJO
inner join dbo.HCRECINAC RN  on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
inner join  dbo.ADINGRESO AS ING  on ING.NUMINGRES = INGMH.NUMINGRESHIJO 
INNER JOIN DBO.INPACIENT AS PAC with (nolock) ON PAC.IPCODPACI =A.IPCODPACI
INNER JOIN dbo.INCUPSIPS B with (nolock) ON E.CODSERIPS=B.CODSERIPS 
WHERE A.GENSERVICEORDER IS NULL
),


CTE_ALTA_MEDICA
AS
(
  SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(FECALTPAC) 'FECHA ALTA' FROM DBO.HCREGEGRE EGR with (nolock) 
  INNER JOIN CTE_GASES AS PEN with (nolock) ON PEN.INGRESO =EGR.NUMINGRES 
  GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI
),

CTE_ESTANCIA_MAYOR
AS
(
  SELECT C.NUMINGRES ,C.IPCODPACI,C.CODICAMAS  ,C.FECINIEST 'FECHA ESTANCIA',C.REGESTADO,C.CODTIPEST,C.ID    FROM dbo.CHREGESTA C with (nolock)
  INNER JOIN CTE_GASES AS PEN ON PEN.INGRESO =C.NUMINGRES 
  INNER JOIN(SELECT C.NUMINGRES ,C.IPCODPACI ,MAX(C.ID ) IDD FROM dbo.CHREGESTA C with (nolock) GROUP BY C.NUMINGRES ,C.IPCODPACI) AS G ON G.IDD =C.ID 
),

CTE_CAMAS
AS
(
     SELECT FUN.UFUDESCRI 'UNIDAD FUNCIONAL' ,C.IPCODPACI 'IDENTIFICACION' ,C.NUMINGRES 'INGRESO',A.NUMCAMHOS 'CAMA',G.DESTIPEST 'TIPO ESTANCIA'  ,C.ID  'ID_ESTANCIA', 
	 A.CODICAMAS 'ID_CAMAS', CEN.NOMCENATE 'CENTRO DE ATENCION',A.CODCLAHAB ,A.CODCLACAM 
	 FROM dbo.CHCAMASHO A with (nolock)
	 INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON A.UFUCODIGO =FUN.UFUCODIGO 
	 INNER JOIN CTE_ESTANCIA_MAYOR C with (nolock) ON A.CODICAMAS=C.CODICAMAS AND C.REGESTADO = 1 
     INNER JOIN dbo.CHTIPESTA G with (nolock) ON G.CODTIPEST=C.CODTIPEST 
	 INNER JOIN DBO.ADCENATEN AS CEN with (nolock) ON CEN.CODCENATE =A.CODCENATE 
),

CTE_HISTORIAS_AMBULATORIAS
AS
(
  SELECT HIS.NUMINGRES ,HIS.IPCODPACI ,MAX(FECHISPAC) AS 'FECHA ALTA'    FROM  DBO.HCHISPACA HIS with (nolock)
  INNER JOIN CTE_GASES AS PEN with (nolock) ON PEN.INGRESO =HIS.NUMINGRES 
  WHERE HIS.GENCONEXT =1
  GROUP BY HIS.NUMINGRES ,HIS.IPCODPACI
)


SELECT
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 IMG.*,F.InvoiceNumber 'NRO FACTURA',
 ALT.[FECHA ALTA],
 1 as 'CANTIDAD',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 CTE_GASES IMG
 inner join dbo.ADINGRESO as ing with (nolock) ON img.INGRESO =ing.NUMINGRES 
 LEFT JOIN CTE_ALTA_MEDICA AS ALT with (nolock) ON ALT.NUMINGRES =IMG.INGRESO 
 LEFT JOIN Billing .Invoice AS F ON F.AdmissionNumber =IMG.INGRESO 
