-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewReferenciaRecepcion
-- Extracted by Fabric SQL Extractor SPN v3.9.0


    /*******************************************************************************************************************
Nombre: [Report].[ViewReferanciaRecepcion]
Tipo: Vista
Observacion:Oportunidad de la recepción de la referencia
Profesional: Nilsson Galindo
Fecha:13-10-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico:
Fecha:
Observaciones:
-------------------------------------------------------------------------------------------------------------------------------------
Version 3
Persona que modifico:
Fecha:
Observaciones:
***********************************************************************************************************************************/

CREATE VIEW [Report].[ViewReferenciaRecepcion] AS

SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CA.NOMCENATE AS CENTRO_ATENCION,
DOC.Nombre as [TIPO DOCUMENTO],
RR.IPCODPACI AS IDENTIFICACION,
PAC.IPNOMCOMP AS [PACIENTE],
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END AS[GENERO DEL PACIENTE],
CAST(PAC.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
CASE RR.CODTIPPAC WHEN '1' THEN 'Maternas' 
				  WHEN '2' THEN 'Pediatrico'
				  WHEN '3' THEN 'Población general' 
				  WHEN '4' THEN 'Adulto mayor' 
				  WHEN '5' THEN 'Población general' END AS [TIPO DE PACIENTE], 
DATEDIFF(YEAR,IPFECNACI ,GETDATE()) -(CASE WHEN DATEADD(YY,DATEDIFF(YEAR,IPFECNACI,GETDATE()),IPFECNACI)>GETDATE() THEN 1 ELSE 0 END) AS EDAD,
RR.FECREGIS AS [FECHA REGISTRO REFERENCIA], 
CASE RR.CODTIPOENTSOLI WHEN '1' THEN 'IPS' 
					   WHEN '2' THEN 'EAPB' 
					   WHEN '3' THEN 'CRUE' 
					   WHEN '4' THEN 'OTRA' END AS [TIPO ENTIDAD SOLICITUD],
EN.NOMENTIDA AS [EAPB PAGADORA], 
ME.Nombre AS [MEDIO DE ENVIO REFERENCIA],
RR.FECMEDENV AS [FECHA DE ENVIO],
IPS.DSCRIPIPS AS [IPS QUE REMITE],
RS.Nombre AS [SERVICIO QUE REMITE],
RR.MEDREMITE AS [MEDICO QUE REMITE],
E.DESESPECI AS [ESPECIALIDAD QUE REMITE],
UF.UFUDESCRI AS [SERVICIO AL QUE SE REMITE], 
E1.DESESPECI AS [ESPECIALIDAD A LA QUE REMITE],
MODS.Nombre AS [MODALIDAD DE LA SOLICITUD],
MR.Nombre AS [MOTIVO DE LA REFERENCIA], 
CASE RR.CODCOMPLEJ WHEN '1' THEN 'Baja' 
				   WHEN '2' THEN 'Media' 
				   WHEN '3' THEN 'Alta' END AS COMPLEJIDAD,
CASE RR.CODURGVITAL WHEN 0 THEN 'No' ELSE 'Si' END AS [URGENCIA VITAL],

DIAG.CODDIAGNO AS [CODIGO DIAGNOSTICO],
DIAG.NOMDIAGNO AS DIAGNOSTICO, 
CASE RR.ESTADO WHEN '1' THEN 'Registrado' 
			   WHEN '2' THEN 'Aceptado sin ingreso' 
			   WHEN '3' THEN 'Aceptado coon ingreso' 
			   WHEN '4' THEN 'Rechazado' 
			   WHEN '5' THEN 'Cancelado' 
			   WHEN '6' THEN 'Egresado' END AS ESTADO,
U.NOMUSUARI AS [USUARIO RECEPCION],
RR.CONSEC AS CONSECUTIVO, RR.OBSERVACION,
RR.NUMINGRES AS [NUMERO INGRESO], 
I.IFECHAING AS [FECHA INGRESO], 
DATEDIFF(DAY, RR.FECREGIS,I.IFECHAING)/24 AS [DIAS REGISTRO VS INGRESO],
DATEDIFF(HOUR, RR.FECREGIS,I.IFECHAING) AS [HORAS REGISTRO VS INGRESO],
IIF(RR.ESTADO IN (4,5),DE.OBSERVACION,NULL) AS [OBSERVACION RECHAZO],
IIF(RR.ESTADO IN (4,5),REC.CODIGO+'-'+REC.DESCRIPCION,NULL) AS [MOTIVO RECHAZO],
IIF(RR.ESTADO IN (4,5),DE.FECREGIS,NULL) AS [FECHA RECHAZO],
IIF(RR.ESTADO IN (4,5),DATEDIFF(DAY, RR.FECREGIS,DE.FECREGIS),NULL) AS [DIAS REGISTRO VS RECHAZO],
IIF(RR.ESTADO IN (4,5),DATEDIFF(HOUR, RR.FECREGIS,DE.FECREGIS),NULL) AS [HORAS REGISTRO VS RECHAZO],
IIF(RR.ESTADO IN (4,5),USU.NOMUSUARI,NULL) AS [USUARIO RECHAZO],
1 as 'CANTIDAD',
CAST(RR.FECREGIS AS date) AS 'FECHA BUSQUEDA',
YEAR(RR.FECREGIS) AS 'AÑO FECHA BUSQUEDA',
MONTH(RR.FECREGIS) AS 'MES FECHA BUSQUEDA',
CASE MONTH(RR.FECREGIS)
WHEN 1 THEN 'ENERO'
WHEN 2 THEN 'FEBRERO'
WHEN 3 THEN 'MARZO'
WHEN 4 THEN 'ABRIL'
WHEN 5 THEN 'MAYO'
WHEN 6 THEN 'JUNIO'
WHEN 7 THEN 'JULIO'
WHEN 8 THEN 'AGOSTO'
WHEN 9 THEN 'SEPTIEMBRE'
WHEN 10 THEN 'OCTUBRE'
WHEN 11 THEN 'NOVIEMBRE'
WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM            
dbo.HCREFRECEP RR INNER JOIN
dbo.ADCENATEN CA ON RR.ADCENATENID = CA.CODCENATE LEFT JOIN
dbo.INPACIENT PAC ON RR.IPCODPACI=PAC.IPCODPACI  LEFT JOIN
dbo.ADTIPOIDENTIFICA DOC ON PAC.IPTIPODOC=DOC.CODIGO LEFT JOIN
dbo.INENTIDAD AS EN ON RR.INENTADMID=EN.CODENTIDA LEFT JOIN
dbo.ADCONTIPS IPS ON RR.ADCONTIPSID=IPS.CODIGOIPS LEFT JOIN
dbo.RCMEDIOSENVIO AS ME ON RR.RCMEDIOSENVIOID = ME.ID LEFT JOIN
dbo.RCSERVICIOS AS RS ON RR.RCSERVICIOSID = RS.Id LEFT JOIN
dbo.INUNIFUNC AS UF ON RR.INUNIFUNCID = UF.UFUCODIGO LEFT JOIN
dbo.INESPECIA AS E ON RR.INESPECIAIDREMITE = E.CODESPECI LEFT JOIN
dbo.INESPECIA AS E1 ON RR.INESPECIAIDAREMITIR = E1.CODESPECI LEFT JOIN
dbo.SEGusuaru AS U ON RR.USERCREA = U.CODUSUARI LEFT JOIN
dbo.RCMOTREF AS MR ON MR.Id = RR.RCMOTREFID LEFT JOIN
dbo.HCREFREDIAG AS REFD ON REFD.HCREFRECEPID = RR.ID AND REFD.PRINCIPAL = 1 LEFT JOIN
dbo.INDIAGNOS AS DIAG ON REFD.INDIAGNOSCOD = DIAG.CODDIAGNO LEFT JOIN
dbo.ADINGRESO AS I ON I.NUMINGRES = RR.NUMINGRES LEFT JOIN
dbo.RCMODSOLIC MODS ON RR.RCMODSOLICID=MODS.Id LEFT JOIN
dbo.HCREFRECDE DE ON RR.ID=DE.HCREFRECEPID AND DE.ID=(SELECT MAX(A.ID) FROM dbo.HCREFRECDE A WHERE RR.ID=A.HCREFRECEPID) LEFT JOIN
dbo.HCMOTREFREC REC ON DE.HCMOTREFRECID=REC.ID LEFT JOIN
dbo.SEGusuaru AS USU ON DE.FUNCREG=USU.CODUSUARI
--WHERE RR.IPCODPACI='80129656'



