-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: VIEW_SEG_MEDICAMENTOSUSPENDIDO
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[VIEW_SEG_MEDICAMENTOSUSPENDIDO] AS
SELECT --TOP 10
 HM.IPCODPACI 'IDENTIFICACION',
 PAC.IPNOMCOMP 'NOMBRE PACIENTE',
 HM.NUMINGRES 'INGRESO',
 PRO.DESPRODUC 'MEDICAMENTO' , 
 PRE.DESFORMED 'PRESENTACION',
 HM.FECAPLMED 'FECHA PROGRAMADA APLICACION',
 HM.FECAPLMED 'FECHA REAL APLICACION',
 HM.CANDESCON 'CANTIDAD SOLICITADA',
 UNI.DESUNIMED 'UNIDAD MEDICAMENTO',
 HM.MOTSUSMED 'MOTIVO SUSPENSION', 
 CASE HM.MEDESTADO
  WHEN 1 THEN 'Pendiente'
  WHEN 2 THEN 'Aplicado'
  WHEN 3 THEN 'Suspendido'
 END 'ESTADO APLICAICON',
 RTRIM(FE.CODPROSAL)+' - '+FE.NOMMEDICO AS [PROFESIONAL DE LA SALUD]
FROM 
 DBO.HCHOJAMED HM --6299
 JOIN ADINGRESO AS ING ON HM.NUMINGRES = ING.NUMINGRES --6299
 JOIN INPACIENT AS PAC ON HM.IPCODPACI = PAC.IPCODPACI --6299
 JOIN IHLISTPRO AS PRO ON HM.CODPRODUC = PRO.CODPRODUC AND PRO.TIPPRODUC ='1' --6300
 LEFT JOIN DBO.INUNIMEDI AS UNI ON HM.CODUNIMED =UNI.CODUNIMED
 LEFT JOIN IHFORMEDI AS PRE ON PRO.CODFORMED = PRE.CODFORMED 
 LEFT JOIN dbo.INPROFSAL AS FE ON HM.CODUSUSUS=FE.CODPROSAL
WHERE
 HM.MEDESTADO = 3 
