-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewControlOdontologia
-- Extracted by Fabric SQL Extractor SPN v3.9.0



/*******************************************************************************************************************
Nombre: [Report].[ViewControlOdontologia]
Tipo:Vista
Observacion:Informe sobre las consultas por odontología 
Profesional: 
Fecha:
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha: 14-02-2023
Ovservaciones: Se cambia la logia de la consulta, asemejandose a la 202 v2
--------------------------------------
Version 2
Persona que modifico:
Fecha:
***********************************************************************************************************************************/

CREATE VIEW [Report].[ViewControlOdontologia] as

with
CTE_PACIENTES_ODONTOLOGIA as
(
	SELECT 
		HIS.ID,
		HIS.IPCODPACI,
		HIS.NUMINGRES,
		HIS.NUMEFOLIO,
		HIS.CODPROSAL,
		HIS.CODESPTRA,
		HIS.FECHISPAC,
		HIS.CODDIAGNO,
		MHC.NOMBRE
	FROM 
		dbo.HCHISPACA HIS INNER JOIN
		dbo.PRMODELOHC MHC ON HIS.IDMODELOHC=MHC.ID AND MHC.NOMBRE LIKE '%ODONTO%' 
													AND HIS.NUMEFOLIO=(SELECT MAX(HC.NUMEFOLIO) FROM dbo.HCHISPACA HC WHERE HIS.NUMINGRES=HC.NUMINGRES)
		--WHERE HIS.IPCODPACI='43165232'
),
CTE_ODONTOLOGIA_COP AS
 (
SELECT
	CON.IPCODPACI,
	CON.NUMINGRES,
	DET.CEO_C,DET.CEO_O,DET.CEO_E,
	DET.CPO_C ,DET.CPO_O ,DET.CPO_P,
	CON.FECHAREG,
	CON.NUMEFOLIO,
	CASE HTO.ESTADO when 2 THEN 'Terminado' else 'Sin Terminar'end as [ESTADO TRATAMIENTO],
	DIENTES.NUMERO
	FROM 
	ODONTOCONTROL CON 
INNER JOIN ODONTOCONTROLVALO DET ON CON.ID=DET.IDODONTOCONTROL AND CON.NUMEFOLIO=(SELECT MAX(CO.NUMEFOLIO) FROM ODONTOCONTROL CO  INNER JOIN ODONTOCONTROLVALO DE ON CON.IPCODPACI=CO.IPCODPACI AND CO.ID=DE.IDODONTOCONTROL) --INNER JOIN PARA SOLO TENER EN CUENTA LAS VALORACIONES, LEFT JOIN PARA TENER ENCUENTA TODAS LAS CONSULTAS YA SEA POR ODONTOLOGIA O POR SALUD BUCAL.
INNER JOIN (SELECT 
			DIE.IDODONTOCONTROL,
			COUNT(TRATA.IDODONTODIENTE) AS NUMERO
			FROM 
			dbo.ODONTODIENTE DIE
			LEFT JOIN (SELECT IDODONTODIENTE FROM(SELECT IDODONTODIENTE FROM dbo.ODONTODIENTETRATA WHERE CONSECTRA!=51
					   UNION ALL
					   SELECT IDODONTODIENTE FROM dbo.ODONTODIENTEDIAG
					   ) TRATA GROUP BY IDODONTODIENTE) TRATA ON DIE.ID=TRATA.IDODONTODIENTE GROUP BY DIE.IDODONTOCONTROL
			) DIENTES ON CON.ID=DIENTES.IDODONTOCONTROL
LEFT JOIN ODONTOPLANTRATAMIENTOPACD HTO ON CON.ID=HTO.IDODONTOCONTROL
 )

SELECT DISTINCT
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 CASE PAC.IPTIPODOC WHEN 1  THEN 'CC - CEDULA DE CIUDADANIA' 
					WHEN 2  THEN 'CE - CEDULA DE EXTRANJERIA' 
					WHEN 3  THEN 'TI - TARJETA DE IDENTIDAD' 
					WHEN 4  THEN 'RC - REGISTRO CIVIL' 
					WHEN 5  THEN 'PA - PASAPORTE' 
					WHEN 6  THEN 'AS - ADULTO SIN IDENTIFICACION' 
					WHEN 7  THEN 'MS - MENOR SIN IDENTIFICACION' 
					WHEN 8  THEN 'NU - NUMERO UNICO DE IDENTIFICACIÒN' 
					WHEN 9  THEN 'NV - CERTIFICADO NACIDO VIVO' 
					WHEN 10 THEN 'CD - CARNET DIPLOMATICO' 
					WHEN 11 THEN 'SC - SALVOCONDUCTO' 
					WHEN 12 THEN 'PE - PERMISO ESPECIAL DE PERMANENCIA' ELSE 'NO REGISTRA' END 'TIPO IDENTIFICACION', 
 HIS.IPCODPACI AS 'IDENTIDAD PACIENTE', PAC.IPNOMCOMP AS 'NOMBRE COMPLETO',
 PAC.IPPRINOMB AS 'PRIMER NOMBRE', PAC.IPSEGNOMB AS 'SEGUNDO NOMBRE', 
 PAC.IPPRIAPEL AS 'PRIMER APELLIDO', PAC.IPSEGAPEL AS 'SEGUNDO APELLIDO', 
 CASE PAC.IPSEXOPAC 
      WHEN 1 THEN 'MASCULINO' 
	  WHEN 2 THEN 'FEMENINO' END 'SEXO',
 CASE WHEN PAC.DISCCODIGO IS NULL THEN 'NO' ELSE 'SI' END 'DISCAPACIDAD',
   CASE PAC.NIVCODIGO WHEN '01' THEN 'NO DEFINIDO'
					  WHEN '02' THEN 'PREESCOLAR'
					  WHEN '03' THEN 'BASICA PRIMARIA'
					  WHEN '04' THEN 'BASICA SECUNDARIA'
					  WHEN '05' THEN 'MEDIA ACADEMICA'
					  WHEN '06' THEN 'MEDIA TECNICA'
					  WHEN '07' THEN 'NORMALISTA'
					  WHEN '08' THEN 'TECNICA PROFESIONAL'
					  WHEN '09' THEN 'TECNOLOGICA'
					  WHEN '10' THEN 'PROFESIONAL'
					  WHEN '11' THEN 'ESPECIALIZACION'
					  WHEN '12' THEN 'MAESTRIA'
					  WHEN '13' THEN 'DOCTORADO' END AS 'NIVEL EDUCATIVO',
CASE WHEN TR.TRIVICONF IS NULL THEN 'NO' ELSE 'SI' END AS 'VICTIMA DE CONFLICTO',
CASE PAC.IPORIENTSEXUAL WHEN '1' THEN 'HOMOSEXUAL' 
						WHEN '3' THEN 'BISEXUAL'
						WHEN '8' THEN 'OTRO' ELSE 'NO' END AS 'LGTB',
CAST(PAC.IPFECNACI AS DATE) AS 'FECHA_NACIMIENTO',
FLOOR((CAST(CONVERT(VARCHAR(8), HIS.FECHISPAC , 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS 'EDAD',
DEP.nomdepart AS 'DEPARTAMENTO', 
MUN.MUNNOMBRE AS 'MUNICIPIO', 
UB.UBINOMBRE AS 'UBICACION', 
RTRIM (PAC.CODENTIDA) AS 'CODIGO EAPB', 
ENT.NOMENTIDA AS 'NOMBRE EAPB',
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro'
				   WHEN 6 THEN 'Desplazado Reg Contributivo'
				   WHEN 7 THEN 'Desplazado Reg Subsidiado'
				   WHEN 8 THEN 'Desplazado No asegurado' end as [TIPO DE REGIMEN],
HIS.FECHISPAC AS 'FECHA DE ATENCION', 
HIS.CODPROSAL AS 'COD. PROFESIONAL', 
PROF.NOMMEDICO AS 'NOMBRE PROFESIONAL',
ESP.DESESPECI AS 'ESPECIALIDAD TRATANTE', 
HIS.NOMBRE AS 'TIPO HISTORIA',
CASE RIE.GESTACION  WHEN '0' THEN 'NO APLICA'
					WHEN '1' THEN 'SI'
					WHEN '2' THEN 'NO'
					WHEN '3' THEN 'RIESGO NO EVALUADO' ELSE 'NO APLICA' END 'GESTANTE',
CASE RS.VALOR WHEN '1' THEN 'Si'
			  WHEN '2' THEN 'No' END [TRATAMIENTO CONTROLADO],
CASE RA.VALOR WHEN '1' THEN 'Primera Vez'
			  WHEN '2' THEN 'Control'
			  WHEN '3' THEN 'Urgencias' END [TIPO DE ATENCION],
ISNULL(COP.[Estado Tratamiento],'Sin Terminar')as [Estado Tratamiento],
HIS.FECHISPAC AS [FECHA DE REALIZACION],
IIF(DATEDIFF(MONTH,PAC.IPFECNACI, HIS.FECHISPAC)<6,IIF(COP.FECHAREG IS NULL,'1800-01-01',CONVERT(VARCHAR(10),COP.FECHAREG,23))
												  ,IIF(COP.CPO_C IS NULL,'21'
																		,RIGHT('00' + Ltrim(Rtrim(rtrim(cast((COP.NUMERO-COP.CPO_P-COP.CEO_C-((COP.CPO_C+COP.CEO_C+COP.CPO_O+COP.CEO_O))) as char)))),2) + '00' +  RIGHT('00' + Ltrim(Rtrim(COP.CPO_C+COP.CEO_C)),2)
																				+ RIGHT('00' + Ltrim(Rtrim(COP.CPO_O+COP.CEO_O)),2) + RIGHT('00' + Ltrim(Rtrim(COP.CPO_P+COP.CEO_E)),2) + RIGHT('00' + Ltrim(Rtrim(rtrim(cast(COP.NUMERO-COP.CPO_P-COP.CEO_E as char)))),2)			 
					) 
	) AS COP,
--CASE WHEN (DATEDIFF(MONTH,PAC.IPFECNACI, HIS.FECHISPAC)) <7 THEN '0' ELSE
--	CASE WHEN COP.CPO_C IS NULL AND COP.CPO_O IS NULL AND COP.CPO_P IS NULL THEN '21' ELSE
--		CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HIS.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<10 THEN
--RIGHT('00' + Ltrim(Rtrim(rtrim(cast((24-COP.CPO_P -((COP.CPO_C +COP.CPO_O))) as char)))),2) + '00' +  RIGHT('00' + Ltrim(Rtrim(COP.CPO_C)),2)
--+ RIGHT('00' + Ltrim(Rtrim(COP.CPO_O)),2) + RIGHT('00' + Ltrim(Rtrim(COP.CPO_P)),2) + RIGHT('00' + Ltrim(Rtrim(rtrim(cast(24-COP.CPO_P as char)))),2) ELSE
--CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HIS.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=10 THEN 
-- RIGHT('00' + Ltrim(Rtrim(rtrim(cast((32-COP.CPO_P -((COP.CPO_C +COP.CPO_O))) as char)))),2) + '00' +  RIGHT('00' + Ltrim(Rtrim(COP.CPO_C)),2)
--+RIGHT('00' + Ltrim(Rtrim(COP.CPO_O)),2) + RIGHT('00' + Ltrim(Rtrim(COP.CPO_P)),2) + RIGHT('00' + Ltrim(Rtrim(rtrim(cast(32-COP.CPO_P as char)))),2) ELSE '21'  END END END END 'COPITO',
--HIS.NUMINGRES AS FOLIO,
1 as 'CANTIDAD',
CAST(HIS.FECHISPAC AS date) AS 'FECHA BUSQUEDA',
YEAR(HIS.FECHISPAC) AS 'AÑO FECHA BUSQUEDA', 
MONTH(HIS.FECHISPAC) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(HIS.FECHISPAC) WHEN 1 THEN 'ENERO'
						  WHEN 2 THEN 'FEBRERO'
						  WHEN 3 THEN 'MARZO'
						  WHEN 4 THEN 'ABRIL'
						  WHEN 5 THEN 'MAYO'
						  WHEN 6 THEN 'JUNIO'
						  WHEN 7 THEN 'JULIO'
						  WHEN 8 THEN 'AGOSTO'
						  WHEN 9 THEN 'SEPTIEMBRE'
						  WHEN 10 THEN 'OCTUBRE'
						  WHEN 11 THEN 'NOVIEMBRE'
						  WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(HIS.FECHISPAC), '00') AS 'DIA FECHA BUSQUEDA',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
--GETDATE () AS ULT_ACTUAL
FROM
	CTE_PACIENTES_ODONTOLOGIA HIS INNER JOIN
	dbo.INPACIENT PAC ON HIS.IPCODPACI=PAC.IPCODPACI LEFT JOIN
	report.TablaRevisionXSistema AS RS ON RS.IDHCHISPACA=HIS.ID AND RS.IDRSVARIABLE='218' LEFT JOIN 
	report.TablaRevisionXSistema AS RA ON RA.IDHCHISPACA=HIS.ID AND RA.IDRSVARIABLE='217'
	LEFT JOIN INPROFSAL AS PROF ON PROF.CODPROSAL=HIS.CODPROSAL
	LEFT JOIN INESPECIA AS ESP ON ESP.CODESPECI=HIS.CODESPTRA
	LEFT JOIN HCRIESGOSP AS RIE ON RIE.IPCODPACI=HIS.IPCODPACI AND RIE.NUMINGRCES=HIS.NUMINGRES
	LEFT JOIN INUBICACI AS UB ON UB.AUUBICACI=PAC.AUUBICACI
	LEFT JOIN INMUNICIP MUN ON UB.DEPMUNCOD = MUN.DEPMUNCOD
	LEFT JOIN INDEPARTA DEP ON MUN.DEPCODIGO = DEP.DEPCODIGO AND PAC.AUUBICACI = UB.AUUBICACI
	LEFT JOIN INENTIDAD ENT ON PAC.CODENTIDA = ENT.CODENTIDA
	LEFT JOIN INDIAGNOS AS DIA ON DIA.CODDIAGNO=HIS.CODDIAGNO
	LEFT JOIN ADTRIAGEU AS TR ON TR.IPCODPACI = HIS.IPCODPACI
	LEFT JOIN CTE_ODONTOLOGIA_COP AS COP ON HIS.NUMINGRES=COP.NUMINGRES
