-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_V2_FAC_REPORTE_INTERCONSULTAS_POR_RECONOCER_URG
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[View_V2_FAC_REPORTE_INTERCONSULTAS_POR_RECONOCER_URG]
AS

WITH CTE_INTERCONSULTAS_UNICOS
----CTE PARA IDENTIFICAR LOS INGRESOS UNICOS DE IMAGENES QUE ESTAN PENDIENTES DE RECONOCER - HOSPITALARIOS
AS
(
SELECT DISTINCT  ING.NUMINGRES ,ING.IPCODPACI,ING.IESTADOIN
  FROM dbo.ADINGRESO ing with (nolock)
	INNER JOIN dbo.HCORDINTE A with (nolock) ON ing.NUMINGRES = A.NUMINGRES
	INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS
	INNER JOIN DBO.INUNIFUNC FUN ON FUN.UFUCODIGO =ING.UFUCODIGO 
	WHERE ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER IS NULL AND A.ESTSERIPS ='3' and A.MANEXTPRO ='0' AND FUN.UFUTIPUNI ='1' --ING.UFUCODIGO in ('1111001','1113008','1113009')
  UNION ALL
	SELECT DISTINCT ING.NUMINGRES,ING.IPCODPACI,ING.IESTADOIN 
	FROM dbo.HCORDINTE A with (nolock) 
	INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS 
	INNER JOIN dbo.HCINGRESORECNAC INGMH  with (nolock) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	INNER JOIN dbo.HCRECINAC RN  with (nolock) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	INNER JOIN dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	INNER JOIN DBO.INUNIFUNC FUN ON FUN.UFUCODIGO =ING.UFUCODIGO 
	WHERE ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER IS NULL AND A.ESTSERIPS ='3' and A.MANEXTPRO ='0' AND FUN.UFUTIPUNI ='1'--ING.UFUCODIGO in ('1111001','1113008','1113009')
),
CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
AS
(
    SELECT EGR.IPCODPACI ,EGR.NUMINGRES,EGR.FECINIEST ,EGR.FECFINEST ,EGR.CODICAMAS,CAM.NUMCAMHOS ,FUN.UFUDESCRI  ,FUN.UFUTIPUNI  
	FROM CHREGESTA EGR with (nolock)
	INNER JOIN 
	(
	   SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR with (nolock)
	   INNER JOIN CTE_INTERCONSULTAS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G  ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM with (nolock) ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),
CTE_EGRESO_CAMA
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO  
FROM CHREGEGRE EGR
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECEGRESO) EGRESO 
 FROM CHREGEGRE EGR with (nolock) 
 INNER JOIN CTE_INTERCONSULTAS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.EGRESO =EGR.FECEGRESO 
),
CTE_ORDENES_CON_INTER_CARGADAS
---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
AS
( 
SELECT RC.AdmissionNumber,G.CUPS ,G.CANTIDAD  FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN
(
SELECT RC.AdmissionNumber ,CUPS.Code AS CUPS ,SUM(SOD.InvoicedQuantity) CANTIDAD   
FROM Billing .RevenueControlDetail AS RCD WITH (NOLOCK)
INNER JOIN BILLING.REVENUECONTROL AS RC WITH (NOLOCK) ON RCD.REVENUECONTROLID = RC.ID
INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD WITH (NOLOCK) ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2', '3')
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD WITH (NOLOCK) ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN CTE_INTERCONSULTAS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =RC.AdmissionNumber  
INNER JOIN Contract .CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id =SOD.CUPSEntityId AND CUPS.ServiceType ='6'
INNER JOIN Contract .IPSService AS IPS WITH (NOLOCK) ON IPS.Id =SOD.IPSServiceId
--where rc.AdmissionNumber ='7569' --'431'
GROUP BY RC.AdmissionNumber ,CUPS.Code 
) AS G ON G.AdmissionNumber =RC.AdmissionNumber
),
CTE_DATOS_INTERCONSULTAS
---CTE QUE ME TRAE LOS DATOS DE LOS HEMOCOMPONENTES DE FORMA AGRUPADA
AS
(
SELECT ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS ) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],
HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',FUN.UFUDESCRI ,FUN.UFUTIPUNI,
	  MIN(ISNULL(HIS.FECHISPAC,A.FECORDMED)) 'FECHA REALIZADO MINIMA',
	  MAX(ISNULL(HIS.FECHISPAC,A.FECORDMED)) 'FECHA REALIZADO MAXIMA'
       FROM dbo.ADINGRESO ing with (nolock)
	    INNER JOIN dbo.HCORDINTE A with (nolock) ON ing.NUMINGRES = A.NUMINGRES
	    INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS
		INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI
		INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	    INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id
		INNER JOIN DBO.INUNIFUNC FUN ON FUN.UFUCODIGO =ING.UFUCODIGO
		INNER JOIN
	    (
	      SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS ) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN
          FROM dbo.ADINGRESO ing with (nolock)
	      INNER JOIN dbo.HCORDINTE A with (nolock) ON ing.NUMINGRES = A.NUMINGRES
		  INNER JOIN DBO.INUNIFUNC FUN ON FUN.UFUCODIGO =ING.UFUCODIGO
	      INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS
		  INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI
		  INNER JOIN CTE_INTERCONSULTAS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =ING.NUMINGRES
		  WHERE A.ESTSERIPS ='3' and A.MANEXTPRO ='0' AND FUN.UFUTIPUNI ='1'--ING.UFUCODIGO in ('1111001','1113008','1113009')
		  GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	    ) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =A.CODSERIPS
		LEFT JOIN DBO.HCHISPACA AS HIS ON HIS.NUMINGRES =A.NUMINGRES AND HIS.NUMEFOLIO =A.NUMEFOLIO
	    WHERE A.ESTSERIPS ='3' and A.MANEXTPRO ='0' AND A.GENSERVICEORDER IS NULL AND FUN.UFUTIPUNI =1--ING.UFUCODIGO in ('1111001','1113008','1113009')
	    GROUP BY ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name , CG.Name ,ING.IFECHAING,FUN.UFUDESCRI ,FUN.UFUTIPUNI 
	 UNION ALL
      SELECT ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS ) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],
	  HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',FUN.UFUDESCRI ,FUN.UFUTIPUNI,
	  MIN(ISNULL(HIS.FECHISPAC,A.FECORDMED)) 'FECHA REALIZADO MINIMA' ,
	  MAX(ISNULL(HIS.FECHISPAC,A.FECORDMED)) 'FECHA REALIZADO MAXIMA'
	    	FROM dbo.HCORDINTE A with (nolock) 
	         INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS 
	         INNER JOIN dbo.HCINGRESORECNAC INGMH  with (nolock) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	         INNER JOIN dbo.HCRECINAC RN  with (nolock) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	         INNER JOIN dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO 
			 INNER JOIN DBO.INUNIFUNC FUN ON FUN.UFUCODIGO =ING.UFUCODIGO
			 INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI
			 INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	         INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id
		     INNER JOIN
	        (
	          SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS ) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN
	    	  FROM dbo.HCORDINTE A with (nolock) 
	          INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS 
	          INNER JOIN dbo.HCINGRESORECNAC INGMH  with (nolock) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	          INNER JOIN dbo.HCRECINAC RN  with (nolock) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	          INNER JOIN dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO 
			  INNER JOIN DBO.INUNIFUNC FUN ON FUN.UFUCODIGO =ING.UFUCODIGO
			  INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI
	          INNER JOIN CTE_INTERCONSULTAS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =ING.NUMINGRES
		      WHERE A.ESTSERIPS ='3' and A.MANEXTPRO ='0' AND FUN.UFUTIPUNI ='1'
		      GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	         ) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =A.CODSERIPS
			 LEFT JOIN DBO.HCHISPACA AS HIS ON HIS.NUMINGRES =A.NUMINGRES AND HIS.NUMEFOLIO =A.NUMEFOLIO
	        WHERE A.ESTSERIPS ='3' and A.MANEXTPRO ='0' AND A.GENSERVICEORDER IS NULL AND FUN.UFUTIPUNI ='1'
	        GROUP BY ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name , CG.Name ,ING.IFECHAING,FUN.UFUDESCRI ,FUN.UFUTIPUNI
),
--IN V2
--SE CREA EL CTE DE JUSTIFICACIONES, PARA QUE ME RETORNE TODOS LOS ORDENAMIENTOS CON ALGUNA JUSTIFIACION.
CTE_RECONOCIMIENTOS_INTERCONSULTA AS
(
SELECT ING.NUMINGRES,ING.NUMEFOLIO,ing.IESTADOIN,ing.[FECHA INGRESO] ,ING.ENTIDAD ,ING.[GRUPO ATENCION] ,ING.IPCODPACI ,ING.IPNOMCOMP ,ING.CODSERIPS ,ING.DESSERIPS,ING.[CANTIDAD ORDENADA]  ,ING.CANSERIPS,CAM.UFUDESCRI ,
CAM.NUMCAMHOS,EGR.FECEGRESO,CAR.CUPS 'CUPS CARGADO' ,CAR .CANTIDAD 'CANTIDAD CARGADA' ,ING.[FECHA REALIZADO MINIMA] ,ING.[FECHA REALIZADO MAXIMA] 
FROM CTE_DATOS_INTERCONSULTAS  ING
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM ON ING.NUMINGRES =CAM.NUMINGRES
LEFT JOIN CTE_EGRESO_CAMA EGR ON EGR.NUMINGRES =ING.NUMINGRES
LEFT JOIN CTE_ORDENES_CON_INTER_CARGADAS CAR ON CAR.AdmissionNumber =ING.NUMINGRES AND CAR.CUPS =ING.CODSERIPS
WHERE ING.[CANTIDAD ORDENADA] <>ISNULL(CAR.CANTIDAD,0)  AND ING.[CANTIDAD ORDENADA] >ISNULL(CAR.CANTIDAD,0)
--AND CAM.NUMCAMHOS LIKE 'U%' OR CAM.NUMCAMHOS LIKE 'O%' OR CAM.NUMCAMHOS LIKE 'SRE%'
),

CTE_JUSTIFICACIONES AS
(
SELECT DISTINCT IM.NUMINGRES,IM.NUMEFOLIO,IM.CODSERIPS,JUS.Code
FROM 
[Billing].[BillingJustificationControl] JUS INNER JOIN
[Billing].[AccountControlJustification] CON ON JUS.ID=JustificationId INNER JOIN
dbo.HCORDINTE IM ON CON.EntityId=IM.AUTO AND CON.EntityName='HCORDINTE'
)
-- SE CREA LA NUEVA CONSULTA UNIENDO EL CTE CON EL CTE_JUSTIFICACIONES PARA QUE NO ME MUESTRE LAS ORDENES QUE SE ENCUENTRAN JUSTIFICADAS
SELECT INTE.* 
FROM 
CTE_RECONOCIMIENTOS_INTERCONSULTA INTE LEFT JOIN
CTE_JUSTIFICACIONES JUS ON INTE.NUMINGRES=JUS.NUMINGRES AND INTE.NUMEFOLIO=JUS.NUMEFOLIO AND INTE.CODSERIPS=JUS.CODSERIPS
WHERE JUS.Code IS NULL AND INTE.UFUDESCRI in ('PEDIATRIA URGENCIAS','URGENCIAS ADULTOS','PABELLON URGENCIAS ADULTOS','GINECOBSTETRICIA URGENCIAS')
--FN V2

