-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewValoracionesDiarias
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [Report].[ViewValoracionesDiarias] AS

SELECT  top 100 percent
HIS.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE' ,HIS.NUMINGRES 'INGRESO',his.NUMEFOLIO 'FOLIO',PRO.NOMMEDICO 'PROFESIONAL',HIS.FECHISPAC 'FECHA HISTORIA',
UNI.UFUDESCRI 'UNIDAD FUNCIONAL' ,ESP.DESESPECI 'ESPECIALIDAD TRATANTE',G2.[FECHA ALTA MEDICA] ,CG.Name 'GRUPO ATENCION'
FROM DBO.HCHISPACA HIS
INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =HIS.IPCODPACI
INNER JOIN DBO.INPROFSAL AS PRO ON PRO.CODPROSAL =HIS.CODPROSAL 
INNER JOIN DBO.INESPECIA AS ESP ON ESP.CODESPECI =HIS.CODESPTRA 
INNER JOIN DBO.INUNIFUNC AS UNI ON UNI.UFUCODIGO =HIS.UFUCODIGO
INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES =HIS.NUMINGRES 
INNER JOIN Contract .CareGroup AS CG ON CG.Id =ING.GENCAREGROUP 
LEFT JOIN
(
	 SELECT EGR.NUMINGRES 'INGRESO' ,EGR.IPCODPACI 'IDENTIFICACION',EGR.FECALTPAC 'FECHA ALTA MEDICA'  
     FROM HCREGEGRE EGR with (nolock)
     INNER JOIN
     ( SELECT EGR.NUMINGRES 'INGRESO' ,EGR.IPCODPACI 'IDENTIFICACION' ,MAX(EGR.FECALTPAC) 'FECHA ALTA MEDICA'  
     FROM DBO.HCREGEGRE EGR with (nolock)
     GROUP BY EGR.NUMINGRES,EGR.IPCODPACI
     )  AS G ON G.INGRESO =EGR.NUMINGRES AND G.IDENTIFICACION  =EGR.IPCODPACI AND G.[FECHA ALTA MEDICA] =EGR.FECALTPAC
	) AS G2 ON G2.INGRESO =HIS.NUMINGRES 
WHERE GENCONEXT =0 AND ESP.DESESPECI LIKE '%RESIDENTE%'
--GROUP BY HIS.IPCODPACI,PAC.IPNOMCOMP,HIS.NUMINGRES,ESP.DESESPECI,G2.[FECHA ALTA MEDICA],UNI.UFUDESCRI ,HIS.NUMEFOLIO ,HIS.FECHISPAC ,CG.Name,PRO.NOMMEDICO 
ORDER BY HIS.IPCODPACI, HIS.FECHISPAC ASC
