-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewNonSurgicalProceduresRequests
-- Extracted by Fabric SQL Extractor SPN v3.9.0






/*******************************************************************************************************************
Nombre: ViewNonSurgicalProceduresRequests
Tipo: Vista
Observacion:Ordenamiento de procedimientos no QX
Profesional: Nilsson Miguel Galindo Lopez
Fecha: 10-05-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico: Amira Gil Meneses
Fecha:28-06-2023
Ovservaciones:se ingresa al mismo campo el codigo de la entidad y codigo de la especialidad- Solicitud HSJ
-------------------------------------------------
Version 3
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:24-01-2024
Ovservaciones:Se modifica la logica para la especialidad que realiza el procedimiento, ya que en la tabla dbo.AMBORDOTROSPRO en el campo CODESPREALI
			  muestra la especialidad de agendamiento mas no la especialidad que realizo el procedimiento.
--------------------------------------------------
Version 
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:11-04-2024
Ovservaciones:Se agregan campos de interpretación.
***********************************************************************************************************************************/
CREATE VIEW [Report].[ViewNonSurgicalProceduresRequests]
AS

WITH
CTE_PROCEDIMIENTOS_NOQX AS
(
SELECT
A.NUMINGRES,A.UFUCODIGO,A.CODPROSAL,CODSERIPS,IDDESCRIPCIONRELACIONADA,IDAREAPRO,MEDREALI,ESPEREALI,A.UFUCODIGOPRO,
A.CODPROINT,A.NUMFOLINT,A.ESTSERIPS,A.MANEXTPRO,A.NUMEFOLIO,A.FECORDMED,A.CANSERIPS,A.OBSSERIPS,FECHREALI,
A.FECHAPRO,A.GENSERVICEORDER
FROM
dbo.HCORDPRON A
INNER JOIN CONTRACT.CUPSENTITY AS CUPS ON A.CODSERIPS=CUPS.CODE
WHERE CUPS.Description NOT LIKE '%TERAPIAS%'
UNION ALL
SELECT
A.NUMINGRES,
'' AS UFUCODIGO,'' AS CODPROSAL,
A.CODSERIPS,
A.IDDESCRIPCIONRELACIONADA,
A.IDAREAPRO,
A.MEDICOREALI AS MEDREALI,
--IN V2 A.CODESPREALI AS ESPEREALI,
HC.CODESPTRA AS ESPEREALI,--FN V2
A.UFUCODIGOPRO,
A.CODPROSALINT AS CODPROINT,A.NUMEFOLIOINT AS NUMFOLINT,
A.ESTADO AS ESTSERIPS,'' AS MANEXTPRO,'' AS NUMEFOLIO, 
A.FECHAREG AS FECORDMED,
A.CANTIDAD AS CANSERIPS,
'' AS OBSSERIPS,
A.FECHAREALI,
A.FECHAPRO,A.GENSERVICEORDER
FROM
dbo.AMBORDOTROSPRO A
INNER JOIN CONTRACT.CUPSENTITY AS CUPS ON A.CODSERIPS=CUPS.CODE
/*IN V2*/INNER JOIN dbo.HCHISPACA HC ON A.NUMINGRES=HC.NUMINGRES AND HC.NUMEFOLIO=(SELECT MAX(H.NUMEFOLIO) FROM dbo.HCHISPACA H WHERE A.NUMINGRES=H.NUMINGRES)/*FN V2*/
WHERE CUPS.Description NOT LIKE '%TERAPIAS%'

--ISNULL(NOQX.FECHREALI,ISNULL(NOQX.FECHAPRO,HCIN.FECHISPAC)) AS [FECHA REALIZACIÓN],
--ISNULL(NOQX.MEDREALI,PROIN.CODPROINT) AS [ID PROFESIONAL REALIZACIÓN],
--ISNULL(PRORE.NOMMEDICO,PROIN.NOMMEDICO) AS [PROFESIONAL REALIZACIÓN],
--ISNULL(INERE.DESESPECI,INEIN.DESESPECI) AS [ESPECIALIDAD REALIZACIÓN],
--ISNULL(FUNRE.UFUCODIGO+'-'+FUNRE.UFUDESCRI,FUNIN.UFUCODIGO+' - '+FUNIN.UFUDESCRI) AS [UNIDAD FUNCIONAL REALIZACIÓN],
),
--Se crea CTE para sacar el ultipo diagnostico realizado a cada ingreso.
CTE_DIAGNOSTICOS AS
(
SELECT 
NOH.NUMINGRES,
NOS.CODDIAGNO,
NOS.NOMDIAGNO,
CASE NOP.ESTADIO WHEN 0 THEN 'ESTADIO CLÍNICO (EC) 0 (TUMOR IN SITU)'
				 WHEN 1 THEN 'EC I O 1'
				 WHEN 2 THEN 'EC IA O 1A'
				 WHEN 3 THEN 'EC IA1'
				 WHEN 4 THEN 'EC IA2'
				 WHEN 5 THEN 'EC IB O 1B'
				 WHEN 6 THEN 'EC IB1'
				 WHEN 7 THEN 'EC IB2'
				 WHEN 8 THEN 'EC IC O 1C'
				 WHEN 9 THEN 'EC IS O 1S'
				 WHEN 10 THEN 'EC II O 2'
				 WHEN 11 THEN 'EC IIA O 2A'
				 WHEN 12 THEN 'EC IIA1'
				 WHEN 13 THEN 'EC IIA2'
				 WHEN 14 THEN 'EC IIB O 2B'
				 WHEN 15 THEN 'EC IIC O 2C'
				 WHEN 16 THEN 'EC III O 3'
				 WHEN 17 THEN 'EC IIIA O 3A'
				 WHEN 18 THEN 'EC IIIB O 3B'
				 WHEN 19 THEN 'EC IIIC O 3C'
				 WHEN 20 THEN 'EC IV O 4'
				 WHEN 21 THEN 'EC IVA O 4A'
				 WHEN 22 THEN 'EC IVB O 4B'
				 WHEN 23 THEN 'EC IVC O 4C'
				 WHEN 24 THEN 'EC 4S (PARA NEUROBLASTOMA)'
				 WHEN 25 THEN 'EC  V O 5'
				 WHEN 26 THEN 'EC ESTADIO IAB'
				 WHEN 55 THEN 'PERSONA CON ASEGURAMIENTO (RÉGIMEN SUBSIDIADO O CONTRIBUTIVO Y QUE NO SON PPNA) QUE RECIBIÓ SERVICIOS DE SALUD POR PARTE DEL ENTE TERRITORIALDURANTE EL PERIODO DE REPORTE'
				 WHEN 93 THEN 'SIN INFORMACIÓN DE ESTADIFICACIÓN EN HISTORIA CLÍNICA'
				 WHEN 98 THEN 'NO APLICA (ES CÁNCER DE PIEL BASOCELULAR, ES CÁNCER HEMATOLÓGICO O ES CÁNCER EN SNC, EXCEPTO NEUROBLASTOMA)'
				 WHEN 99 THEN 'DESCONOCIDO, EL DATO DE ESTA VARIABLE NO SE ENCUENTRA DESCRITO EN LOS SOPORTES CLÍNICOS' ELSE ''END  AS ESTADIO
FROM 
dbo.INDIAGNOH NOH INNER JOIN
DBO.INDIAGNOS NOS ON NOH.CODDIAGNO=NOS.CODDIAGNO AND NOH.CODDIAPRI=1 
												 AND NOH.NUMEFOLIO=(SELECT MAX(DIA.NUMEFOLIO) FROM dbo.INDIAGNOH DIA WHERE NOH.NUMINGRES=DIA.NUMINGRES AND DIA.CODDIAPRI=1) LEFT JOIN
dbo.INDIAGNOP NOP ON NOH.NUMINGRES=NOP.NUMINGRES AND NOH.NUMEFOLIO=NOP.NUMEFOLIO AND NOP.CODDIAPRI=1
),
--CTE para contratos
CTE_CONTRATOS AS
(
SELECT 
	CG.CODE, 
    CE.CODE AS CUPS, 
    CASE PC.CONTRACTED WHEN 1 THEN 'SI' ELSE 'NO' END AS CONTRATADO,
    CASE PC.QUOTED WHEN 1 THEN 'SI' ELSE 'NO'END AS COTIZADO, 
    CECD.ID AS IDRELACION
FROM 
	CONTRACT.CAREGROUP AS CG INNER JOIN 
	CONTRACT.PROCEDURETEMPLATE AS PT ON CG.PROCEDURETEMPLATEID = PT.ID INNER JOIN 
	CONTRACT.PROCEDURECUPS AS PC ON PT.ID = PC.PROCEDURESTEMPLATEID INNER JOIN 
	CONTRACT.CUPSENTITY AS CE ON PC.CUPSID = CE.ID LEFT JOIN 
	CONTRACT.CUPSENTITYCONTRACTDESCRIPTIONS AS CECD ON PC.CUPSENTITYCONTRACTDESCRIPTIONID = CECD.ID
)


SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CEN.NOMCENATE AS [CENTRO DE ATENCION],
IDE.SIGLA AS [TIPO DE IDENTIFICACION],
PAC.IPCODPACI AS IDENTIFICACION,
PAC.IPNOMCOMP AS PACIENTE,
CAST(PAC.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
CAST((DATEDIFF(M,PAC.IPFECNACI, GETDATE())/12) as varchar) + ' Años ' + cast((DATEDIFF(M,PAC.IPFECNACI, GETDATE())%12) as varchar) + ' Meses' as EDAD,
CASE PAC.IPSEXOPAC WHEN '1' THEN 'MASCULINO' ELSE 'FEMENINO' END AS [SEXO],
PAC.IPTELEFON AS [TELEFONO FIJO], 
PAC.IPTELMOVI AS [TELEFONO MOVIL], 
PAC.IPDIRECCI AS DIRECCION,
EA.HealthEntityCode [CODIGO EPS/ENTIDAD TERRITORIAL],
EA.NAME AS [ENTIDAD ADMINISTRADORA],
GA.CODE [CODIGO GRUPO ATENCION], 
GA.CODE + ' - ' + GA.NAME [GRUPO ATENCION],
CASE GA.LIQUIDATIONTYPE WHEN 1 THEN 'PAGO POR SERVICIOS'
						WHEN 2 THEN 'PGP'
						WHEN 3 THEN 'FACTURA GLOBAL'
						WHEN 4 THEN 'CAPITACION GLOBAL'
						WHEN 5 THEN 'CONTROL'END [TIPO CONTRATO],
IIF(CON.CODE IS NULL, 'NO', 'SI') CUBIERTO, 
ISNULL(CON.CONTRATADO, 'NO') CONTRATADO, 
ISNULL(CON.COTIZADO, 'NO') COTIZADO,
CASE ING.TIPOINGRE WHEN 1 THEN 'Ambulatorio'
				   WHEN 2 THEN 'Hospitalario' END AS [AMBITO DE INGRESO],
ISNULL(ARE.DESAREA,'PROCEDIMIENTO NO QX') AS [TIPO ORDEN],
RTRIM(NOQX.UFUCODIGO) + ' - ' + RTRIM(FUN.UFUDESCRI) AS [UNIDAD FUNCIONAL],
ING.CODCAMACT AS CAMA,
NOQX.NUMINGRES AS INGRESO,
NOQX.NUMEFOLIO AS FOLIO,
NOQX.CODSERIPS AS [CODIGO CUPS],
RTRIM(CUPS.Description) AS [DESCRIPCION SERVICIO],
CG.CODE + '-' + CG.NAME [GRUPO],
CSG.CODE + '-' + CSG.NAME [SUBGRUPO],
ISNULL(CD.CODE + ' - ' + CD.NAME,'') [DESCRIPCION RELACIONADA],
IIF(NOQX.MANEXTPRO=1,'Extramural'
					,IIF(PRONOQX.NUMINGRES IS NULL,CASE WHEN NOQX.ESTSERIPS='1' AND NOQX.GENSERVICEORDER IS NULL THEN 'Ordenado'
														WHEN NOQX.ESTSERIPS='1' AND NOQX.GENSERVICEORDER IS NOT NULL THEN 'Completado' ELSE
														CASE NOQX.ESTSERIPS WHEN '2' THEN 'Completado' 
																			WHEN '3' THEN 'Interpretado'
																			WHEN '4' THEN 'Realizados'
																			WHEN '5' THEN 'Anulado' END END
												  ,'Realizados')) AS ESTADO,
NOQX.CANSERIPS AS [CANTIDAD ORDEN],
PRO.CODPROSAL AS [ID PROFESIONAL SOLICITUD], 
PRO.NOMMEDICO AS [PROFESIONAL SOLICITUD],
ESP.CODESPECI +' - '+ ESP.DESESPECI AS [ESPECIALIDAD SOLICITUD],
NOQX.OBSSERIPS AS [OBSERVACION SOLICITUD],
DIA.CODDIAGNO AS [CODIGO DX PRINCIPAL SOLICITUD],
DIA.NOMDIAGNO AS [DX PRINCIPAL SOLICITUD],
DIA.ESTADIO,
CAST(NOQX.FECORDMED AS DATE) AS [FECHA ORDEN],
CAST(NOQX.FECORDMED AS TIME) AS [HORA ORDEN],
ISNULL(CAST(HCOTR.FECHISPAC AS DATE),ISNULL(CAST(NOQX.FECHREALI AS DATE),CAST(NOQX.FECHAPRO AS DATE))) AS [FECHA REALIZACIÓN],
ISNULL(CAST(HCOTR.FECHISPAC AS TIME),ISNULL(CAST(NOQX.FECHREALI AS TIME),CAST(NOQX.FECHAPRO AS TIME))) AS [HORA REALIZACIÓN],
ISNULL(HCOTR.CODPROSAL,NOQX.MEDREALI) AS [ID PROFESIONAL REALIZACIÓN],
ISNULL(PROTR.NOMMEDICO,PRORE.NOMMEDICO) AS [PROFESIONAL REALIZACIÓN],
ISNULL(INEOTR.DESESPECI,INERE.DESESPECI) AS [ESPECIALIDAD REALIZACIÓN],
ISNULL(RTRIM(FUNOTR.UFUCODIGO)+' - '+FUNOTR.UFUDESCRI,RTRIM(FUNRE.UFUCODIGO)+' - '+FUNRE.UFUDESCRI) AS [UNIDAD FUNCIONAL REALIZACIÓN],
HCOTR.NUMEFOLIO AS [FOLIO REALIZACIÓN],
CAST(HCIN.FECHISPAC AS DATE) AS [FECHA INTERPRETACIÓN],
CAST(HCIN.FECHISPAC AS TIME) AS [HORA INTERPRETACIÓN],
PROIN.CODPROSAL AS [ID PROFESIONAL INTERPRETACIÓN],
PROIN.NOMMEDICO AS [PROFESIONAL INTERPRETACIÓN],
INEIN.DESESPECI AS [ESPECIALIDAD INTERPRETACIÓN],
RTRIM(FUNIN.UFUCODIGO)+' - '+FUNIN.UFUDESCRI AS [UNIDAD FUNCIONAL INTERPRETACIÓN],
NOQX.NUMFOLINT AS [FOLIO INTERPRETACIÓN],
CAST(NOQX.FECORDMED AS date) AS 'FECHA BUSQUEDA',
YEAR(NOQX.FECORDMED) AS 'AÑO BUSQUEDA',
MONTH(NOQX.FECORDMED) AS 'MES BUSQUEDA',
CONCAT(FORMAT(MONTH(NOQX.FECORDMED), '00') ,' - ', 
	   CASE MONTH(NOQX.FECORDMED) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
CTE_PROCEDIMIENTOS_NOQX NOQX 
INNER JOIN dbo.ADINGRESO ING ON NOQX.NUMINGRES=ING.NUMINGRES 
INNER JOIN dbo.ADCENATEN CEN ON ING.CODCENATE=CEN.CODCENATE 
INNER JOIN dbo.INPACIENT PAC ON ING.IPCODPACI=PAC.IPCODPACI 
INNER JOIN dbo.ADTIPOIDENTIFICA IDE ON PAC.IPTIPODOC=IDE.CODIGO 
INNER JOIN CONTRACT.HEALTHADMINISTRATOR EA ON ING.GENCONENTITY=EA.Id 
INNER JOIN CONTRACT.CAREGROUP AS GA ON ING.GENCAREGROUP=GA.ID 
INNER JOIN CONTRACT.CUPSENTITY AS CUPS ON NOQX.CODSERIPS=CUPS.CODE 
INNER JOIN CONTRACT.CUPSSUBGROUP AS CSG ON CUPS.CUPSSUBGROUPID=CSG.ID 
INNER JOIN CONTRACT.CUPSGROUP AS CG ON CG.ID=CSG.CUPSGROUPID 
LEFT JOIN (SELECT A.NUMINGRES,B.CODSERIPS,A.IDHCHISPACA
		   FROM dbo.HCPLAOTRPROC A INNER JOIN dbo.HCPLAOTRPROCUPS B on A.ID=B.IDHCPLAOTRPROC) PRONOQX ON NOQX.NUMINGRES=PRONOQX.NUMINGRES AND NOQX.CODSERIPS=PRONOQX.CODSERIPS AND NOQX.MANEXTPRO!=1 AND NOQX.ESTSERIPS=4
LEFT JOIN CONTRACT.CUPSENTITYCONTRACTDESCRIPTIONS CECD ON NOQX.IDDESCRIPCIONRELACIONADA=CECD.ID 
LEFT JOIN CONTRACT.CONTRACTDESCRIPTIONS CD ON CECD.CONTRACTDESCRIPTIONID=CD.ID 
LEFT JOIN dbo.INUNIFUNC FUN ON NOQX.UFUCODIGO=FUN.UFUCODIGO 
LEFT JOIN DBO.INPROFSAL PRO ON NOQX.CODPROSAL=PRO.CODPROSAL 
LEFT JOIN DBO.INESPECIA ESP ON PRO.CODESPEC1=ESP.CODESPECI 
LEFT JOIN dbo.HCAREASC ARE ON NOQX.IDAREAPRO=ARE.ID
LEFT JOIN CTE_DIAGNOSTICOS DIA ON NOQX.NUMINGRES=DIA.NUMINGRES 
LEFT JOIN CTE_CONTRATOS CON ON GA.Code=CON.Code AND NOQX.CODSERIPS=CON.CUPS
									  AND NOQX.IDDESCRIPCIONRELACIONADA=CON.IDRELACION
-----------------------------REALIZACIÓN----------------------------------------------------------
LEFT JOIN dbo.INPROFSAL PRORE ON NOQX.MEDREALI=PRORE.CODPROSAL
LEFT JOIN dbo.INESPECIA INERE ON NOQX.ESPEREALI=INERE.CODESPECI
LEFT JOIN dbo.INUNIFUNC FUNRE ON NOQX.UFUCODIGOPRO=FUNRE.UFUCODIGO
---------------------------INTERPRETACION------------------------------------------------------
LEFT JOIN dbo.INPROFSAL PROIN ON NOQX.CODPROINT=PROIN.CODPROSAL
LEFT JOIN dbo.INESPECIA INEIN ON PROIN.CODESPEC1=INEIN.CODESPECI
LEFT JOIN dbo.HCHISPACA HCIN ON NOQX.NUMINGRES=HCIN.NUMINGRES AND NOQX.NUMFOLINT=HCIN.NUMEFOLIO
LEFT JOIN dbo.INUNIFUNC FUNIN ON HCIN.UFUCODIGO=FUNIN.UFUCODIGO
---------------------------EVOLUCIONES O NOTAS DE OTROS PORCEDIMIENTOS (PRONOQX)--------------
LEFT JOIN dbo.HCHISPACA HCOTR ON PRONOQX.IDHCHISPACA=HCOTR.ID
LEFT JOIN dbo.INPROFSAL PROTR ON HCOTR.CODPROSAL=PROTR.CODPROSAL
LEFT JOIN dbo.INUNIFUNC FUNOTR ON HCOTR.UFUCODIGO=FUNOTR.UFUCODIGO
LEFT JOIN dbo.INESPECIA INEOTR ON HCOTR.CODESPTRA=INEOTR.CODESPECI
--where ING.NUMINGRES='311571'

--WHERE ING.IPCODPACI='41736191' and CUPS.Code='876241'



