-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewUploadCubeVieClinicalDailyEmergencies
-- Extracted by Fabric SQL Extractor SPN v3.9.0








CREATE VIEW [Report].[ViewUploadCubeVieClinicalDailyEmergencies] AS

SELECT 
      [CENTRO DE ATENCION]
     ,[TIPO DOCUMENTO]
     ,CAST([IDENTIFICACION] AS varchar(25)) AS [IDENTIFICACION]
     ,[PACIENTE NOMBRE COMPLETO]
     ,[SEXO BIOLOGICO]
     ,[IDENTIDAD DE GENERO]
     ,[GRUPO ETARIO]
     ,ISNULL([ENTIDAD],'Sin Dato') AS [ENTIDAD]
     ,[REGIMEN]
     ,[TIPO PACIENTE]
     ,[MINUTOS ESPERA LLEGADA VS TRIAGE] AS [RESULTADO LLEGADA VS TRIAGE]
     ,[JORNADA]
     ,[CLASIFICACION TRIAGE #]
     ,[ATENDIDO CONSULTA]
	 ,CONCAT(UPPER(SUBSTRING([UNIDAD FUNCIONAL DE INGRESO], 1, 1)), LOWER(SUBSTRING([UNIDAD FUNCIONAL DE INGRESO], 2))) AS [UNIDAD FUNCIONAL DE INGRESO]
     ,[MINUTOS ESPERA TRIAGE VS CONSULTA] AS [RESULTADO TRIAGE VS CONSULTA]
     ,[ESTADO PACIENTE]
     ,CONCAT(UPPER(SUBSTRING([DX INGRESO], 1, 1)), LOWER(SUBSTRING([DX INGRESO], 2))) AS [DX INGRESO]
	 ,CONCAT(UPPER(SUBSTRING([DX EGRESO], 1, 1)), LOWER(SUBSTRING([DX EGRESO], 2))) AS [DX EGRESO]
     ,[MINUTOS LLEGADA VS ATENCION]
	 ,[MINUTOS LLEGADA VS ATENCION] AS [RESULTADO LLEGADA VS ATENCION]
     ,[DESTINO URGENCIAS]
	 ,[FECHA LLEGADA]
	 ,FORMAT([FECHA LLEGADA], 'HH') AS [HORA]
	 ,[ULT_ACTUAL]

FROM [Report].[UploadCubeVieClinicalDailyEmergencies]
