-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewProcedimientosOdontologia
-- Extracted by Fabric SQL Extractor SPN v3.9.0



    /*******************************************************************************************************************
Nombre: Report.ProcedimientosOdontologia
Tipo:Vista
Observacion:Vista de los procedimientos odontologicos
Profesional: Nilsson Miguel Galindo Lopez
Fecha:28-07-2022
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Vercion 1
Persona que modifico: 
Fecha:
Ovservaciones: 
--------------------------------------
Vercion 2
Persona que modifico:
Fecha:
***********************************************************************************************************************************/



--select * from dbo.ODONTOCONTROL
--select * from dbo.ODONTOCONTROLVALO
--select * from dbo.ODONTODIENTE --Tabla de control de odontograma por diente, y por tipo control (odontograma valoracion - Odontograma Tratamiento )
--select * from dbo.ODONTODIENTEDIAG --Tabla de Diagnosticos por diente
--select * from dbo.ODONTODIENTETRATA --Tabla de Tratamientos por Diente
--select * from dbo.ODONTOOTROSTRA --Tabla en la que se guarda los Otros tratamientos del odontograma.
--select * from dbo.ODONTOPLANTRATAMIENTOPAC --Tabla donde vamos a guardar el Plan de tratamiento del paciente
--select * from dbo.ODONTOPLANTRATAMIENTOPACD --Tabla en la cual me almacena los tratamientos que le envió el medico al paciente
--select * from dbo.ODONTOPLANTRATAMIENTOPACH --Tabla en la cual vamos a manejar los historicos de los tratamientos de los planes que ha tenido el paciente en el Odontograma
--select * from dbo.ODOPARDIA --Tabla que contiene los parametros de diagnosticos de odontologia
--select * from dbo.ODOPARTRA --Tabla que contiene los parametros de los tratamientos de odontologia
--select * from dbo.ODOPARTRACUPSD --Tabla en la cual vamos a almacenar los CUPS que tiene relacionados el tratamiento odontologico
--3.315
CREATE VIEW [Report].[ViewProcedimientosOdontologia]
as

WITH
CTE_CONSULTA AS 
(
SELECT TIPCITMED,NUMINGRES,NUMEFOLIO,FECINIATE,FECHFINH FROM dbo.HCURGING1 
),
CTE_DATOSPERSONALES AS
(
SELECT
CEN.NOMCENATE,PAC.IPTIPODOC,PAC.IPCODPACI,PAC.IPNOMCOMP,PAC.IPPRINOMB,PAC.IPSEGNOMB,PAC.IPPRIAPEL,PAC.IPSEGAPEL,PAC.IPSEXOPAC,
PAC.IPFECNACI,ING.IFECHAING,DEP.NOMDEPART,MUN.MUNNOMBRE,UB.UBINOMBRE,PAC.IPTELEFON,PAC.IPTELMOVI,EAPB.CODENTIDA,EAPB.NOMENTIDA,
PAC.IPTIPOPAC,FUN.UFUDESCRI,ODC.NUMINGRES,ODC.NUMEFOLIO,ODC.CODPROSAL,PRO.NOMMEDICO,CON.TIPCITMED,CON.FECINIATE,
CON.FECHFINH
FROM 
dbo.ODONTOCONTROL ODC INNER JOIN
DBO.ADINGRESO ING ON ODC.NUMINGRES=ING.NUMINGRES INNER JOIN
DBO.INPACIENT PAC ON ODC.IPCODPACI=PAC.IPCODPACI INNER JOIN
DBO.ADCENATEN CEN ON ODC.CODCENATE=CEN.CODCENATE INNER JOIN
DBO.INUBICACI UB ON PAC.AUUBICACI=UB.AUUBICACI INNER JOIN
DBO.INMUNICIP MUN ON UB.DEPMUNCOD = MUN.DEPMUNCOD INNER JOIN
DBO.INDEPARTA DEP ON MUN.DEPCODIGO = DEP.DEPCODIGO AND PAC.AUUBICACI = UB.AUUBICACI INNER JOIN
DBO.INENTIDAD AS EAPB ON PAC.CODENTIDA=EAPB.CODENTIDA INNER JOIN
DBO.INUNIFUNC AS FUN ON ODC.UFUCODIGO=FUN.UFUCODIGO INNER JOIN
DBO.INPROFSAL AS PRO ON ODC.CODPROSAL=PRO.CODPROSAL INNER JOIN
CTE_CONSULTA CON ON ODC.NUMINGRES=CON.NUMINGRES AND ODC.NUMEFOLIO=CON.NUMEFOLIO 
),

CTE_HISTORICO AS
(
SELECT
IDODONTOCONTROL,IDODOPARTRA,PROFESIONALORDENO,ESTADO,PROFESIONALREALIZO,FECHAREALIZO
FROM
dbo.ODONTOPLANTRATAMIENTOPACH 
)

select 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
DAT.NOMCENATE AS [CENTRO DE ATENCION],
CASE DAT.IPTIPODOC WHEN 1 THEN 'CC - CEDULA DE CIUDADANIA' 
				   WHEN 2 THEN 'CE - CEDULA DE EXTRANJERIA' 
				   WHEN 3 THEN 'TI - TARJETA DE IDENTIDAD' 
				   WHEN 4 THEN 'RC - REGISTRO CIVIL' 
				   WHEN 5 THEN 'PA - PASAPORTE' 
				   WHEN 6 THEN 'AS - ADULTO SIN IDENTIFICACION' 
				   WHEN 7 THEN 'MS - MENOR SIN IDENTIFICACION' 
				   WHEN 8 THEN 'NU - NUMERO UNICO DE IDENTIFICACIÒN' 
				   WHEN 9 THEN 'NV - CERTIFICADO NACIDO VIVO' 
				   WHEN 10 THEN 'CD - CARNET DIPLOMATICO' 
				   WHEN 11 THEN 'SC - SALVOCONDUCTO' 
				   WHEN 12 THEN 'PE - PERMISO ESPECIAL DE PERMANENCIA' ELSE 'OTRO' END [TIPO IDENTIFICACION],
DAT.IPCODPACI AS IDENTIFICACION,
DAT.IPNOMCOMP AS [NOMBRE COMPLETO],
DAT.IPPRINOMB AS [PRIMER NOMBRE],
DAT.IPSEGNOMB AS [SEGUNDO NOMBRE], 
DAT.IPPRIAPEL AS [PRIMER APELLIDO],
DAT.IPSEGAPEL AS [SEGUNDO APELLIDO],
CASE DAT.IPSEXOPAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END [SEXO],
CAST(DAT.IPFECNACI AS DATE ) AS [FECHA_NACIMIENTO],
FLOOR((CAST(CONVERT(VARCHAR(8), DAT.IFECHAING , 112) AS INT) - CAST(CONVERT(VARCHAR(8), DAT.IPFECNACI, 112) AS INT)) / 10000) AS [EDAD],
DAT.NOMDEPART AS DEPARTAMENTO, 
DAT.MUNNOMBRE AS MUNICIPIO,
DAT.UBINOMBRE AS UBICACION,
DAT.IPTELEFON AS [TELEFONO],
DAT.IPTELMOVI AS [CELULAR],
DAT.CODENTIDA AS [CODIGO EAPB],
DAT.NOMENTIDA AS [NOMBRE EAPB],
CASE DAT.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro' 
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado'
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [REGIMEN],
DAT.UFUDESCRI AS [UNIDAD FUNCIONAL],
ODC.NUMINGRES AS INGRESO,
ODC.NUMEFOLIO AS FOLIO,
ODC.CODPROSAL AS [IDENTIFICACION PROFESIONAL],
DAT.NOMMEDICO AS [NOMBRE PROFESIONAL],
ODC.FECHAREG AS [FECHA REGISTRO],
DAT.FECINIATE AS [FECHA INICIAL ATENCION],
DAT.FECHFINH AS [FECHA FINAL ATENCION],
DIE.DIENTE AS [# DIENTE],
CASE OD.TIPO WHEN 1 THEN 'Nivel Diente' 
			 WHEN 2 THEN 'Vestibular' 
			 WHEN 3 THEN 'Oclusal' 
			 WHEN 4 THEN 'Palatina' 
			 WHEN 5 THEN 'Distal Izquierda' 
			 WHEN 6 THEN 'Distal Derecha' 
			 WHEN 7 THEN 'Mesial Derecha' 
			 WHEN 8 THEN 'Mesial Izquierda' 
			 WHEN 9 THEN 'Vestibular' 
			 WHEN 10 THEN 'Lingual' END UBICACIONES,	
rtrim(TRATA.CODIGOTRA) + ' - '+  RTRIM(TRATA.DESCRITRA) AS [DESCRIPCION],
RTRIM(TRATA.CODSERIPS)+' - '+CUP.DESSERIPS AS CUPS,
CASE TRATA.INDICECPO WHEN 'N' THEN 'No Aplica' 
					 WHEN 'C' THEN 'Cariado' 
					 WHEN 'P' THEN 'Perdido'
					 WHEN 'O' THEN 'Obturado' END AS [INDICE CPO],
CASE TRATA.INDICECEO WHEN 'N' THEN 'No Aplica' 
					 WHEN 'C' THEN 'Cariado' 
					 WHEN 'E' THEN 'Extraido'
					 WHEN 'O' THEN 'Obturado' END AS [INDICE CEO],
TRATA.OBSERVTRA AS OBSERVACION,
CASE DAT.TIPCITMED WHEN 1 THEN 'PRIMERA VEZ'
				   WHEN 0 THEN 'CONTROL' END AS [TIPO DE CITA],
CASE HIS.estado WHEN 1 THEN 'NO REALIZADO'
				WHEN 2 THEN 'REALIZADO' END as ESTADO,
CASE DIE.TIPOODONTOGRAMA WHEN 'V' THEN 'VALORACION'
						 WHEN 'T' THEN 'TRATAMIENTO' END AS TIPO,
 1 'CANTIDAD',
 CAST(ODC.FECHAREG AS date) AS 'FECHA BUSQUEDA',
 YEAR(ODC.FECHAREG) AS 'AÑO FECHA BUSQUEDA',
 MONTH(ODC.FECHAREG) AS 'MES AÑO FECHA BUSQUEDA',
 CASE MONTH(ODC.FECHAREG) WHEN 1 THEN 'ENERO'
							   WHEN 2 THEN 'FEBRERO'
							   WHEN 3 THEN 'MARZO'
							   WHEN 4 THEN 'ABRIL'
							   WHEN 5 THEN 'MAYO'
							   WHEN 6 THEN 'JUNIO'
							   WHEN 7 THEN 'JULIO'
							   WHEN 8 THEN 'AGOSTO'
							   WHEN 9 THEN 'SEPTIEMBRE'
							   WHEN 10 THEN 'OCTUBRE'
							   WHEN 11 THEN 'NOVIEMBRE'
							   WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(ODC.FECHAREG), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(ODC.FECHAREG), '00') ,' - ', 
CASE MONTH(ODC.FECHAREG) WHEN 1 THEN 'ENERO'
							  WHEN 2 THEN 'FEBRERO'
							  WHEN 3 THEN 'MARZO'
							  WHEN 4 THEN 'ABRIL'
							  WHEN 5 THEN 'MAYO'
							  WHEN 6 THEN 'JUNIO'
							  WHEN 7 THEN 'JULIO'
							  WHEN 8 THEN 'AGOSTO'
							  WHEN 9 THEN 'SEPTIEMBRE'
							  WHEN 10 THEN 'OCTUBRE'
							  WHEN 11 THEN 'NOVIEMBRE'
							  WHEN 12 THEN 'DICIEMBRE' END) MES_LABEL_INGRESO,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
from 
dbo.ODONTOCONTROL ODC INNER JOIN
CTE_DATOSPERSONALES DAT ON ODC.NUMINGRES=DAT.NUMINGRES INNER JOIN
dbo.ODONTODIENTE DIE ON ODC.ID=DIE.IDODONTOCONTROL INNER JOIN
dbo.ODONTODIENTETRATA OD on DIE.ID = OD.IDODONTODIENTE INNER JOIN
dbo.ODOPARTRA TRATA ON OD.CONSECTRA = TRATA.CONSECTRA LEFT JOIN
DBO.INCUPSIPS CUP ON TRATA.CODSERIPS=CUP.CODSERIPS LEFT JOIN
CTE_HISTORICO HIS ON ODC.ID=HIS.IDODONTOCONTROL AND TRATA.CONSECTRA=HIS.IDODOPARTRA


UNION ALL

select 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
DAT.NOMCENATE AS [CENTRO DE ATENCION],
CASE DAT.IPTIPODOC WHEN 1 THEN 'CC - CEDULA DE CIUDADANIA' 
				   WHEN 2 THEN 'CE - CEDULA DE EXTRANJERIA' 
				   WHEN 3 THEN 'TI - TARJETA DE IDENTIDAD' 
				   WHEN 4 THEN 'RC - REGISTRO CIVIL' 
				   WHEN 5 THEN 'PA - PASAPORTE' 
				   WHEN 6 THEN 'AS - ADULTO SIN IDENTIFICACION' 
				   WHEN 7 THEN 'MS - MENOR SIN IDENTIFICACION' 
				   WHEN 8 THEN 'NU - NUMERO UNICO DE IDENTIFICACIÒN' 
				   WHEN 9 THEN 'NV - CERTIFICADO NACIDO VIVO' 
				   WHEN 10 THEN 'CD - CARNET DIPLOMATICO' 
				   WHEN 11 THEN 'SC - SALVOCONDUCTO' 
				   WHEN 12 THEN 'PE - PERMISO ESPECIAL DE PERMANENCIA' ELSE 'OTRO' END [TIPO IDENTIFICACION],
DAT.IPCODPACI AS IDENTIFICACION,
DAT.IPNOMCOMP AS [NOMBRE COMPLETO],
DAT.IPPRINOMB AS [PRIMER NOMBRE],
DAT.IPSEGNOMB AS [SEGUNDO NOMBRE], 
DAT.IPPRIAPEL AS [PRIMER APELLIDO],
DAT.IPSEGAPEL AS [SEGUNDO APELLIDO],
CASE DAT.IPSEXOPAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END [SEXO],
CAST(DAT.IPFECNACI AS DATE ) AS [FECHA_NACIMIENTO],
FLOOR((CAST(CONVERT(VARCHAR(8), DAT.IFECHAING , 112) AS INT) - CAST(CONVERT(VARCHAR(8), DAT.IPFECNACI, 112) AS INT)) / 10000) AS [EDAD],
DAT.NOMDEPART AS DEPARTAMENTO, 
DAT.MUNNOMBRE AS MUNICIPIO,
DAT.UBINOMBRE AS UBICACION,
DAT.IPTELEFON AS [TELEFONO],
DAT.IPTELMOVI AS [CELULAR],
DAT.CODENTIDA AS [CODIGO EAPB],
DAT.NOMENTIDA AS [NOMBRE EAPB],
CASE DAT.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro' 
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado'
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [REGIMEN],
DAT.UFUDESCRI AS [UNIDAD FUNCIONAL],
ODC.NUMINGRES AS INGRESO,
ODC.NUMEFOLIO AS FOLIO,
ODC.CODPROSAL AS [IDENTIFICACION PROFESIONAL],
DAT.NOMMEDICO AS [NOMBRE PROFESIONAL],
ODC.FECHAREG AS [FECHA REGISTRO],
DAT.FECINIATE AS [FECHA INICIAL ATENCION],
DAT.FECHFINH AS [FECHA FINAL ATENCION],
'' AS [# DIENTE],
'' AS UBICACIONES,	
rtrim(TRA.CODIGOTRA) + ' - '+  RTRIM(TRA.DESCRITRA) AS [DESCRIPCION],
RTRIM(TRA.CODSERIPS)+' - '+CUP.DESSERIPS AS CUPS,
CASE TRA.INDICECPO WHEN 'N' THEN 'No Aplica' 
					 WHEN 'C' THEN 'Cariado' 
					 WHEN 'P' THEN 'Perdido'
					 WHEN 'O' THEN 'Obturado' END AS [INDICE CPO],
CASE TRA.INDICECEO WHEN 'N' THEN 'No Aplica' 
					 WHEN 'C' THEN 'Cariado' 
					 WHEN 'E' THEN 'Extraido'
					 WHEN 'O' THEN 'Obturado' END AS [INDICE CEO],
TRA.OBSERVTRA AS OBSERVACION,
CASE DAT.TIPCITMED WHEN 1 THEN 'PRIMERA VEZ'
					 WHEN 0 THEN 'CONTROL' END AS [TIPO DE CITA],
CASE HIS.estado WHEN 1 THEN 'NO REALIZADO'
				WHEN 2 THEN 'REALIZADO' END as ESTADO,
'' AS TIPO, 1 'CANTIDAD',
 CAST(ODC.FECHAREG AS date) AS 'FECHA BUSQUEDA',
 YEAR(ODC.FECHAREG) AS 'AÑO FECHA BUSQUEDA',
 MONTH(ODC.FECHAREG) AS 'MES AÑO FECHA BUSQUEDA',
 CASE MONTH(ODC.FECHAREG) WHEN 1 THEN 'ENERO'
							   WHEN 2 THEN 'FEBRERO'
							   WHEN 3 THEN 'MARZO'
							   WHEN 4 THEN 'ABRIL'
							   WHEN 5 THEN 'MAYO'
							   WHEN 6 THEN 'JUNIO'
							   WHEN 7 THEN 'JULIO'
							   WHEN 8 THEN 'AGOSTO'
							   WHEN 9 THEN 'SEPTIEMBRE'
							   WHEN 10 THEN 'OCTUBRE'
							   WHEN 11 THEN 'NOVIEMBRE'
							   WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(ODC.FECHAREG), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(ODC.FECHAREG), '00') ,' - ', 
CASE MONTH(ODC.FECHAREG) WHEN 1 THEN 'ENERO'
							  WHEN 2 THEN 'FEBRERO'
							  WHEN 3 THEN 'MARZO'
							  WHEN 4 THEN 'ABRIL'
							  WHEN 5 THEN 'MAYO'
							  WHEN 6 THEN 'JUNIO'
							  WHEN 7 THEN 'JULIO'
							  WHEN 8 THEN 'AGOSTO'
							  WHEN 9 THEN 'SEPTIEMBRE'
							  WHEN 10 THEN 'OCTUBRE'
							  WHEN 11 THEN 'NOVIEMBRE'
							  WHEN 12 THEN 'DICIEMBRE' END) MES_LABEL_INGRESO,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
from 
dbo.ODONTOCONTROL ODC INNER JOIN
CTE_DATOSPERSONALES DAT ON ODC.NUMINGRES=DAT.NUMINGRES INNER JOIN
dbo.ODONTOOTROSTRA OTR ON ODC.ID=OTR.IDODONTOCONTROL INNER JOIN
dbo.ODOPARTRA TRA ON OTR.CONSECTRA=TRA.CONSECTRA LEFT JOIN
DBO.INCUPSIPS CUP ON TRA.CODSERIPS=CUP.CODSERIPS LEFT JOIN
CTE_HISTORICO HIS ON ODC.ID=HIS.IDODONTOCONTROL AND TRA.CONSECTRA=HIS.IDODOPARTRA
