-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewEstructuraSanitas
-- Extracted by Fabric SQL Extractor SPN v3.9.0





CREATE VIEW [Report].[ViewEstructuraSanitas]
AS

WITH
CTE_ATENCIONES AS
(
--select NUMINGRES,CODPROSAL,CODSERIPS,CANSERIPS,''AS OBSSERIPS,FECORDMED from dbo.AMBORDIMA WHERE ESTSERIPS='7'--imagenes DX ambulatorias
--UNION ALL
SELECT NUMINGRES,'' AS NUMEFOLIO,CODPROSAL,CODSERIPS,CANSERIPS,''AS OBSSERIPS,FECORDMED FROM dbo.AMBORDIMA WHERE ESTSERIPS='7'--IMAGENES DX
UNION ALL
SELECT NUMINGRES,'' AS NUMEFOLIO,CODPROSAL,CODSERIPS,CANSERIPS,''AS OBSSERIPS,FECORDMED FROM dbo.AMBORDPAT WHERE ESTSERIPS='7'--PATOLOGIAS AMBULATORIAS
UNION ALL
SELECT NUMINGRES,NUMEFOLIO,CODPROSAL,CODSERIPS,CANSERIPS,OBSSERIPS,FECORDMED FROM dbo.HCORDIMAG WHERE MANEXTPRO='1'--IMAGENES dx
UNION ALL
SELECT NUMINGRES,NUMEFOLIO,CODPROSAL,CODSERIPS,CANSERIPS,OBSSERIPS,FECORDMED FROM dbo.HCORDINTE WHERE MANEXTPRO='1'--INTERCONSULTAS
UNION ALL
SELECT NUMINGRES,NUMEFOLIO,CODPROSAL,CODSERIPS,CANSERIPS,OBSSERIPS,FECORDMED FROM dbo.HCORDLABO WHERE MANEXTPRO='1' --LABORATORIOS
UNION ALL
SELECT NUMINGRES,NUMEFOLIO,CODPROSAL,CODSERIPS,CANSERIPS,OBSSERIPS,FECORDMED FROM dbo.HCORDPATO WHERE MANEXTPRO='1'--PATOLOGIAS
UNION ALL
SELECT NUMINGRES,NUMEFOLIO,CODPROSAL,CODSERIPS,CANSERIPS,OBSSERIPS,FECORDMED FROM dbo.HCORDPRON WHERE MANEXTPRO='1'--PROCEDIMIENTOS NO QX
UNION ALL
SELECT NUMINGRES,NUMEFOLIO,CODPROSAL,CODSERIPS,CANSERIPS,OBSSERIPS,FECORDMED FROM dbo.HCORDPROQ WHERE MANEXTPRO='1'--PROCEDIMIENTOS QX
UNION ALL
SELECT CON.NUMINGRES,CON.NUMEFOLIO,HC.CODPROSAL,CON.CODSERIPS,1 AS CANSERIPS,''AS OBSSERIPS,HC.FECHISPAC AS FECORDMED 
FROM dbo.HCDESCOEX CON INNER JOIN dbo.HCHISPACA HC ON CON.NUMINGRES=HC.NUMINGRES AND CON.NUMEFOLIO=HC.NUMEFOLIO
)


select 
convert(varchar,getdate(),103) as [Fecha de Actual],
CAST(ATE.FECORDMED AS DATE) AS [Fecha de Solicitud],
CA.CODIPSSEC as [Codigo de Habilitacion],
CA.NOMCENATE as [Nombre Prestador Remitente],
ID.NOMBRE as [Tipo Identificacion],
PAC.IPCODPACI as [Numero de Identificacion del Afiliado],
PAC.IPNOMCOMP as [Nombre Paciente],
PAC.IPTELEFON as [Telefono Celular 1],
PAC.IPTELMOVI as [Telefono Celular 2],
cast(ING.IFECHAING as date) as [FECHA INGRESO],
--cast(ATE.FECORDMED as date) as [Fecha Solicitud Extramural],
ISNULL(IND.CODICIE10,DIA.CODICIE10) AS CIE10,
PRO.NOMMEDICO AS [Nombre Medico],
ISNULL(ESP.CodEspeciaHomologo,EP.CODESPECI) AS [Codigo Especialidad Remitente],
ISNULL(ESP.EspecialidadHomologo,EP.DESESPECI) AS [Especialidad Remitente],
cups.Code AS [Código CUPS Prestacion],
cups.Description AS [Descripcion Prestacion],
ATE.CANSERIPS AS Cantidad,
ATE.OBSSERIPS AS [Justificacion Clinica],
GES.EDADGESTA AS [Edad Gestacional (Semanas)],
ate.NUMINGRES,
'' AS ANESTESIA,
'' AS SEDACION,
'' AS COMPARATIVO,
'' AS BILATERAL,
'' AS CONTRASTE,
ATE.NUMEFOLIO
from 
DBO.ADINGRESO ING INNER JOIN
DBO.INPACIENT PAC ON ING.IPCODPACI=PAC.IPCODPACI INNER JOIN
DBO.ADTIPOIDENTIFICA ID ON PAC.IPTIPODOC=ID.CODIGO INNER JOIN
DBO.INENTIDAD EAPB ON ING.CODENTIDA=EAPB.CODENTIDA AND EAPB.NOMENTIDA LIKE '%SANITAS%'INNER JOIN
CTE_ATENCIONES ATE ON ING.NUMINGRES=ATE.NUMINGRES INNER JOIN
dbo.INPROFSAL PRO ON ATE.CODPROSAL=PRO.CODPROSAL LEFT JOIN
DBO.INDIAGNOS IND ON ING.CODDIAING=IND.CODDIAGNO LEFT JOIN
DBO.INDIAGNOS DIA ON ING.CODDIAEGR=DIA.CODDIAGNO LEFT JOIN
[Report].[HomologoEspecialidades] ESP ON PRO.CODESPEC1=ESP.CodEspecia OR PRO.CODESPEC1='0'+ESP.CodEspecia 
																	  OR PRO.CODESPEC1='00'+ESP.CodEspecia 
LEFT JOIN dbo.INESPECIA EP ON PRO.CODESPEC1=EP.CODESPECI 
--[Report].[HomologoCUPS] CUP ON ATE.CODSERIPS=CUP.Cups left join 
LEFT JOIN Contract.CUPSEntity cups on ATE.CODSERIPS=cups.Code LEFT JOIN
dbo.HCANTPERI GES ON ING.NUMINGRES=GES.NUMINGRES,dbo.ADCENATEN CA
WHERE(Cups.Code IS NOT NULL) --and ing.IPCODPACI='16367125' 

--select * from [Report].[HomologoEspecialidades]
--SELECT * FROM DBO.INESPECIA



--SELECT * FROM dbo.HCORDIMAG WHERE MANEXTPRO='1' AND IPCODPACI='16367125' --IMAGENES dx

     --SELECT * FROM DBO.ADTIPOIDENTIFICA
--dbo.INESPECIA
--select * from DBO.ADINGRESO ING where ING.NUMINGRES='12272'
--select * from dbo.HCHISPACA where IPCODPACI='1000859347'
--select * from DBO.INDIAGNOP  where NUMINGRES='12272'
--SELECT * FROM INENTIDAD WHERE NOMENTIDA LIKE '%FAMIS%' OR CODENTIDA='034'
--select * from dbo.HCCUPSDIA

