-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_V2_FAC_REPORTE_HEMOCOMPONENTES_POR_RECONOCER_HOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[View_V2_FAC_REPORTE_HEMOCOMPONENTES_POR_RECONOCER_HOS]
AS

WITH CTE_HEMOCOMPONENTES_UNICOS
----CTE PARA IDENTIFICAR LOS INGRESOS UNICOS DE HEMOCOMPONENTES QUE ESTAN PENDIENTES DE RECONOCER - HOSPITALARIOS
AS
(
	SELECT  DISTINCT ING.NUMINGRES,ING.IPCODPACI,ING.IESTADOIN 
	FROM 
	HCORHEMSER SER with (nolock) 
      INNER JOIN HCORHEMCO SOL with (nolock) ON SOL.ID = SER.HCORHEMCOID
	  INNER JOIN ADINGRESO ING with (nolock) ON SOL.NUMINGRES = ING.NUMINGRES
	 WHERE ING.TIPOINGRE=2 AND SER.ESTADO=2 AND ing.IESTADOIN in (' ','P') AND SER.ORDSERVICIOID IS NOT NULL AND SOL.MANEXTPRO ='0' --AND ING.NUMINGRES  ='26401'  --,428,12680,7569,26401,24522,25932 '
	UNION ALL
	SELECT DISTINCT ING.NUMINGRES,ING.IPCODPACI,ING.IESTADOIN 
	FROM  HCORHEMSER SER
	  INNER JOIN HCORHEMCO SOL ON SOL.ID = SER.HCORHEMCOID
	  INNER JOIN HCINGRESORECNAC INGMH on SOL.NUMINGRES = INGMH.NUMINGRESHIJO
	  INNER JOIN HCRECINAC RN on INGMH.NUMINGRESHIJO  = RN.NUMINGRESHIJO  
	  INNER JOIN ADINGRESO AS ING on ING.NUMINGRES = INGMH.NUMINGRESHIJO 
	  WHERE ING.TIPOINGRE=2 AND SER.ESTADO=2 AND ing.IESTADOIN in (' ','P') AND SER.ORDSERVICIOID IS NOT NULL AND SOL.MANEXTPRO ='0' --AND ING.NUMINGRES  = '26401'
),

CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO EN PENDIENTE DE RECONOCER
AS
(
    SELECT EGR.IPCODPACI ,EGR.NUMINGRES,EGR.FECINIEST ,EGR.FECFINEST ,EGR.CODICAMAS,CAM.NUMCAMHOS ,FUN.UFUDESCRI  ,FUN.UFUTIPUNI  
	FROM CHREGESTA EGR with (nolock)
	INNER JOIN 
	(
	   SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR with (nolock)
	   INNER JOIN CTE_HEMOCOMPONENTES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM with (nolock) ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),

CTE_EGRESO_CAMA
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA EN PENDIENTE DE RECONOCER
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO  
FROM CHREGEGRE EGR
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECEGRESO) EGRESO 
 FROM CHREGEGRE EGR 
 INNER JOIN CTE_HEMOCOMPONENTES_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.EGRESO =EGR.FECEGRESO 
),

CTE_ORDENES_CON_HEMOCOMPONENTES_CARGADAS
---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA EN PENDIENTE DE RECONOCER
AS
( 
SELECT RC.AdmissionNumber,G.CUPS ,G.CANTIDAD  FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN
(
SELECT RC.AdmissionNumber ,CUPS.Code CUPS ,SUM(SOD.InvoicedQuantity) CANTIDAD FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN CTE_HEMOCOMPONENTES_UNICOS PRO ON RC.AdmissionNumber =PRO.NUMINGRES
INNER JOIN Billing .RevenueControlDetail AS RCD WITH (NOLOCK) ON RC.Id =RCD.RevenueControlId 
INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD WITH (NOLOCK) ON RCD.ID = SODD.REVENUECONTROLDETAILID --AND RCD.STATUS IN ('1','2', '3')
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD WITH (NOLOCK) ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN Contract .CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id =SOD.CUPSEntityId --AND CUPS.BillingGroupId IN (9,14)
WHERE RCD.STATUS IN ('1','2', '3') AND CUPS.ServiceType IN (9)--CUPS.BillingGroupId IN (9,14)
GROUP BY RC.AdmissionNumber ,CUPS.Code 
) AS G ON G.AdmissionNumber =RC.AdmissionNumber
),

CTE_DATOS_HEMOCOMPONENTES
---CTE QUE ME TRAE LOS DATOS DE LOS HEMOCOMPONENTES DE FORMA AGRUPADA
AS
(
SELECT ING.NUMINGRES,SOL.NUMEFOLIO,SOL.IPCODPACI,P.IPNOMCOMP ,RTRIM(SER.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA] ,
    HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
	MIN(ISNULL( CAST(REPLACE(CONVERT(VARCHAR, COALESCE(BOL.FECAPLICENF, BOL.FECAPLICMED), 126), 'T00:00:00', 'T23:59:59.998') AS DATETIME),SOL.FECORDMED)) AS 'FECHA REALIZADO MINIMA',
	MAX(ISNULL( CAST(REPLACE(CONVERT(VARCHAR, COALESCE(BOL.FECAPLICENF, BOL.FECAPLICMED), 126), 'T00:00:00', 'T23:59:59.998') AS DATETIME),SOL.FECORDMED)) AS 'FECHA REALIZADO MAXIMA'
 	FROM HCORHEMSER SER
	INNER JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS = SER.CODSERIPS
	INNER JOIN HCORHEMCO SOL ON SOL.ID = SER.HCORHEMCOID
	INNER JOIN ADINGRESO ING ON SOL.NUMINGRES = ING.NUMINGRES
	INNER JOIN INPACIENT P ON P.IPCODPACI = ING.IPCODPACI
	INNER JOIN INCUPSIPS B ON SER.CODSERIPS=B.CODSERIPS 
	INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id 
	INNER JOIN
	(
	    SELECT ING.NUMINGRES,SOL.IPCODPACI,P.IPNOMCOMP ,RTRIM(SER.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN
 	    FROM HCORHEMSER SER
	    INNER JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS = SER.CODSERIPS
	    INNER JOIN HCORHEMCO SOL ON SOL.ID = SER.HCORHEMCOID
	    INNER JOIN ADINGRESO ING ON SOL.NUMINGRES = ING.NUMINGRES
	    INNER JOIN INPACIENT P ON P.IPCODPACI = ING.IPCODPACI
	    INNER JOIN INCUPSIPS B ON SER.CODSERIPS=B.CODSERIPS 
	    INNER JOIN CTE_HEMOCOMPONENTES_UNICOS UNI ON UNI.NUMINGRES=ING.NUMINGRES 
	    WHERE ser.ESTADO='2' AND SER.TIPOSERVICIO IN ( 2, 3) AND SOL.MANEXTPRO ='0'
	    GROUP BY ING.NUMINGRES,SOL.IPCODPACI,P.IPNOMCOMP ,SER.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =SER.CODSERIPS 
	LEFT JOIN 
	(
		SELECT ROW_NUMBER() OVER (PARTITION BY SER1.HCORHEMCOID ORDER BY SER1.HCORHEMBOLID ASC) ID_PARTICION, SER1.HCORHEMCOID, SER1.HCORHEMBOLID 
		FROM HCORHEMSER SER1 
		WHERE SER1.HCORHEMBOLID IS NOT NULL
	) SER2 ON SER2.HCORHEMCOID = SOL.ID AND SER2.ID_PARTICION = 1
	LEFT JOIN HCORHEMBOL BOL ON BOL.ID = SER.HCORHEMBOLID
	LEFT JOIN dbo.HCCOMSAN COM ON COM.ID = BOL.COMSAMID
	LEFT JOIN HCORHEMBOL BOL1 ON BOL1.ID = SER2.HCORHEMBOLID
	LEFT JOIN dbo.INUNIFUNC D ON D.UFUCODIGO = COALESCE(BOL.UFUAPLICA, BOL.UFUENTREGA, BOL.UFUSOLTRA, BOL.UFUSOLRES, BOL1.UFUAPLICA, BOL1.UFUENTREGA, BOL1.UFUSOLTRA, BOL1.UFUSOLRES)
	LEFT JOIN dbo.INPROFSAL C ON C.CODPROSAL = COALESCE(BOL.PROFAPLICA, BOL.PROFSOLTRA, BOL.PROFSOLRES, BOL1.PROFAPLICA, BOL1.PROFSOLTRA, BOL1.PROFSOLRES)
	WHERE ser.ESTADO='2' AND SER.TIPOSERVICIO IN ( 2, 3) AND SER.ORDSERVICIOID IS NULL AND SOL.MANEXTPRO ='0'
	GROUP BY ING.NUMINGRES,SOL.NUMEFOLIO,SOL.IPCODPACI,P.IPNOMCOMP ,SER.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name,CG.Name,ING.IFECHAING 
UNION ALL
	SELECT ING.NUMINGRES,SOL.NUMEFOLIO,SOL.IPCODPACI,P.IPNOMCOMP ,RTRIM(SER.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],
	HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
    MIN(ISNULL( CAST(REPLACE(CONVERT(VARCHAR, COALESCE(BOL.FECAPLICENF, BOL.FECAPLICMED), 126), 'T00:00:00', 'T23:59:59.998') AS DATETIME),SOL.FECORDMED)) AS 'FECHA REALIZADO MINIMA',
	MAX(ISNULL( CAST(REPLACE(CONVERT(VARCHAR, COALESCE(BOL.FECAPLICENF, BOL.FECAPLICMED), 126), 'T00:00:00', 'T23:59:59.998') AS DATETIME),SOL.FECORDMED)) AS 'FECHA REALIZADO MAXIMA'
	FROM HCORHEMSER SER
	INNER JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS = SER.CODSERIPS
	INNER JOIN HCORHEMCO SOL ON SOL.ID = SER.HCORHEMCOID
	INNER JOIN HCINGRESORECNAC INGMH on SOL.NUMINGRES = INGMH.NUMINGRESHIJO
	INNER JOIN HCRECINAC RN on INGMH.NUMINGRESHIJO  = RN.NUMINGRESHIJO  
	INNER JOIN ADINGRESO AS ING on ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	INNER JOIN INPACIENT P ON P.IPCODPACI = ING.IPCODPACI
	INNER JOIN dbo.INCUPSIPS B ON SER.CODSERIPS=B.CODSERIPS 
	INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id 
	INNER JOIN
	(
	 SELECT  ING.NUMINGRES,SOL.IPCODPACI,P.IPNOMCOMP ,RTRIM(SER.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS 'CANTIDAD ORDENADA' ,UNI.IESTADOIN 
	 FROM HCORHEMSER SER
	INNER JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS = SER.CODSERIPS
	INNER JOIN HCORHEMCO SOL ON SOL.ID = SER.HCORHEMCOID
	INNER JOIN HCINGRESORECNAC INGMH on SOL.NUMINGRES = INGMH.NUMINGRESHIJO
	INNER JOIN HCRECINAC RN on INGMH.NUMINGRESHIJO  = RN.NUMINGRESHIJO  
	INNER JOIN ADINGRESO AS ING on ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	INNER JOIN INPACIENT P ON P.IPCODPACI = ING.IPCODPACI
	INNER JOIN dbo.INCUPSIPS B ON SER.CODSERIPS=B.CODSERIPS 
	INNER JOIN CTE_HEMOCOMPONENTES_UNICOS UNI ON UNI.NUMINGRES=ING.NUMINGRES
	WHERE ser.ESTADO='2' AND SER.TIPOSERVICIO IN ( 2, 3)  AND SOL.MANEXTPRO ='0'
	GROUP BY ING.NUMINGRES,SOL.NUMEFOLIO,SOL.IPCODPACI,P.IPNOMCOMP ,SER.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =SER.CODSERIPS
	LEFT JOIN 
	(
		SELECT ROW_NUMBER() OVER (PARTITION BY SER1.HCORHEMCOID ORDER BY SER1.HCORHEMBOLID ASC) ID_PARTICION, SER1.HCORHEMCOID, SER1.HCORHEMBOLID 
		FROM HCORHEMSER SER1 
		WHERE SER1.HCORHEMBOLID IS NOT NULL
	) SER2 ON SER2.HCORHEMCOID = SOL.ID AND SER2.ID_PARTICION = 1
	LEFT JOIN HCORHEMBOL BOL ON BOL.ID = SER.HCORHEMBOLID
	LEFT JOIN dbo.HCCOMSAN COM ON COM.ID = BOL.COMSAMID
	LEFT JOIN HCORHEMBOL BOL1 ON BOL1.ID = SER2.HCORHEMBOLID
	LEFT JOIN dbo.INUNIFUNC D ON D.UFUCODIGO = COALESCE(BOL.UFUAPLICA, BOL.UFUENTREGA, BOL.UFUSOLTRA, BOL.UFUSOLRES, BOL1.UFUAPLICA, BOL1.UFUENTREGA, BOL1.UFUSOLTRA, BOL1.UFUSOLRES)
	LEFT JOIN dbo.INPROFSAL C ON C.CODPROSAL = COALESCE(BOL.PROFAPLICA, BOL.PROFSOLTRA, BOL.PROFSOLRES, BOL1.PROFAPLICA, BOL1.PROFSOLTRA, BOL1.PROFSOLRES)
	WHERE ser.ESTADO='2' AND SER.TIPOSERVICIO IN ( 2, 3) AND SER.ORDSERVICIOID IS NULL AND SOL.MANEXTPRO ='0'
	GROUP BY ING.NUMINGRES,SOL.NUMEFOLIO,SOL.IPCODPACI,P.IPNOMCOMP ,SER.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name,CG.Name,ING.IFECHAING 
),

CTE_RECONOCIMIENTOS_HEMOCOMPONENTES AS
(
SELECT 
ING.NUMINGRES,ING.NUMEFOLIO,ing.IESTADOIN,ING.[FECHA INGRESO],ING.ENTIDAD ,ING.[GRUPO ATENCION] ,
ING.IPCODPACI ,ING.IPNOMCOMP ,ING.CODSERIPS ,ING.DESSERIPS,ING.[CANTIDAD ORDENADA]  ,ING.CANSERIPS,CAM.UFUDESCRI ,
CAM.NUMCAMHOS,EGR.FECEGRESO,CAR.CUPS [CUPS CARGADO] ,CAR .CANTIDAD [CANTIDAD CARGADA],ING.[FECHA REALIZADO MINIMA] ,ING.[FECHA REALIZADO MAXIMA] 
FROM CTE_DATOS_HEMOCOMPONENTES ING
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM ON ING.NUMINGRES =CAM.NUMINGRES-- AND CAM.NUMCAMHOS IS NOT NULL
LEFT JOIN CTE_EGRESO_CAMA EGR ON EGR.NUMINGRES =ING.NUMINGRES
LEFT JOIN CTE_ORDENES_CON_HEMOCOMPONENTES_CARGADAS CAR ON CAR.AdmissionNumber =ING.NUMINGRES AND CAR.CUPS =ING.CODSERIPS
WHERE ING.[CANTIDAD ORDENADA] <>ISNULL(CAR.CANTIDAD,0)  AND ING.[CANTIDAD ORDENADA] >ISNULL(CAR.CANTIDAD,0)
AND CAM.UFUTIPUNI NOT IN ('1','19') --AND CAM.NUMCAMHOS NOT LIKE 'U%' AND CAM.NUMCAMHOS NOT LIKE 'O%' AND CAM.NUMCAMHOS NOT LIKE 'SRE%'
--AND CAM.NUMCAMHOS NOT LIKE 'SAL%' AND CAM.NUMCAMHOS NOT LIKE 'PRE%' AND CAM.NUMCAMHOS NOT LIKE 'REC%'
),

CTE_JUSTIFICACIONES AS
--SE CREA EL CTE DE JUSTIFICACIONES, PARA QUE ME RETORNE TODOS LOS ORDENAMIENTOS CON ALGUNA JUSTIFIACION.
(
SELECT DISTINCT HE.NUMINGRES,HE.NUMEFOLIO,HEM.CODSERIPS,JUS.Code
FROM 
[Billing].[BillingJustificationControl] JUS INNER JOIN
[Billing].[AccountControlJustification] CON ON JUS.ID=JustificationId INNER JOIN
dbo.HCORHEMSER HEM ON CON.EntityId=HEM.ID AND CON.EntityName='HCORHEMSER'INNER JOIN
dbo.HCORHEMCO HE ON HEM.HCORHEMCOID=HE.ID
)

-- SE CREA LA NUEVA CONSULTA UNIENDO EL CTE CON EL CTE_JUSTIFICACIONES PARA QUE NO ME MUESTRE LAS ORDENES QUE SE ENCUENTRAN JUSTIFICADAS
SELECT HEM.* 
FROM 
CTE_RECONOCIMIENTOS_HEMOCOMPONENTES HEM LEFT JOIN
CTE_JUSTIFICACIONES JUS ON HEM.NUMINGRES=JUS.NUMINGRES AND HEM.NUMEFOLIO=JUS.NUMEFOLIO AND HEM.CODSERIPS=JUS.CODSERIPS
WHERE JUS.Code IS NULL

