-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewUploadCubeVieClinicalChemotherapyOrders
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[ViewUploadCubeVieClinicalChemotherapyOrders] 
AS

--ALTER PROCEDURE [EHR].[SP_QUIMIOTERAPIA]
--DECLARE	@FECINI Datetime ='2024-01-01';
--DECLARE	@FECFIN Datetime ='2024-04-30';

--WITH
--CTE_APLICACION AS (
--	SELECT 
--	--INGR.IPCODPACI,
--	ORD.Id,
--	INGR.NUMINGRES AS 'INGRESO APLICACION',
--	HO.Name AS 'ENTIDAD APLICACION',
--	CGO.Name AS 'GRUPO ATENCION APLICACION'
--	FROM
--	--dbo.HCHOJAMED AS MEDI-- ON ORD.IPCODPACI=MEDI.IPCODPACI
--	EHR.HCORDCICLOS ORD 
--	INNER JOIN dbo.ADINGRESO AS INGR ON ORD.NUMINGRES  =INGR.NUMINGRES
--	--INNER join Contract.HealthAdministrator  HO on HO.Id=INGR.GENCONENTITY-- INGRESO 	
--	INNER join Contract.HealthAdministrator HO ON INGR.CODENTIDA=HO.Code
--	INNER JOIN Contract.CareGroup AS CGO ON CGO.Id=INGR.GENCAREGROUP 
--	GROUP BY INGR.NUMINGRES,HO.Name,CGO.Name
--	--WHERE INGR.NUMINGRES='757216'
--	)

	SELECT  DISTINCT
	CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
		CASE P.IPTIPODOC 	
			WHEN 1 THEN 'CC'
			WHEN 2 THEN 'CE'
			WHEN 3 THEN 'TI'
			WHEN 4 THEN 'RC'
			WHEN 5 THEN 'PA'
			WHEN 6 THEN 'AS'
			WHEN 7 THEN 'MS'
			WHEN 8 THEN 'NU'
			WHEN 9 THEN 'CN'
			WHEN 10 THEN 'CD'
			WHEN 11 THEN 'SC' 
			WHEN 12 THEN 'PE' 
			WHEN 13 THEN 'PT'
			WHEN 14 THEN 'DE'
			WHEN 15 THEN 'SI' END AS 'TIPO IDENTIFICACION',--[TipoIdentificacion], 
		
		ORD.IPCODPACI AS 'NRO IDENTIFICACION',-- [NroIdentificacion],
		RTRIM(P.IPNOMCOMP) AS 'NOMBRE PACIENTE',--[NombrePaciente], 
		CAST(P.IPFECNACI AS DATE) AS 'FECHA NACIMIENTO',--[FechaNacimiento], 
		DATEDIFF(YEAR, P.IPFECNACI, ING.IFECHAING) AS 'EDAD',--[Edad],  
		P.IPTELEFON AS 'TELEFONO PRINCIPAL',--[TelPrincipal],
		P.IPTELMOVI AS 'TELEFONO ALTERNATIVO',--[TelAlternativo],
		--DP.depcodigo AS 'Cod. Departamento',
		DP.nomdepart AS 'DEPARTAMENTO',--[Departamento],
		--MU.MUNCODIGO AS 'Cod. Municipio',
		MU.MUNNOMBRE AS 'MINICIPIO',--[Municipio],
		UPPER(P.IPDIRECCI) AS 'DIRECCION',--[Direccion],
		H.Name AS 'ENTIDAD',--[Entidad],
		CG.Name AS 'GRUPO ATENCION',-- [GrupoAtencion], 
		ORD.NUMINGRES AS 'NRO DE INGRESO',--[NroIngreso],
	   CIC.NUMINGRES AS 'INGRESO APLICACION',
		--APLI.[INGRESO APLICACION] AS 'INGRESO APLICACION',
		HO.Name AS 'APLICACION ENTIDAD',		
		CGO.Name AS 'APLICACION GRUPO DE ATENCION',		
		CEN.NOMCENATE AS 'CENTRO DE ATENCION',--[CentroAtencion],
		FUN.UFUDESCRI AS 'UNIDAD FUNCIONAL',--[UnidadFuncional],
		CASE 
			WHEN ORD.CODCENATE = '13031'THEN 'ARMENIA' 
			when ORD.CODCENATE = '13034' THEN 'ARMENIA'
			when ORD.CODCENATE = '13032' THEN 'ARMENIA'
			when ORD.CODCENATE = '11011' THEN 'PEREIRA'
			when ORD.CODCENATE = '11012' THEN 'PEREIRA'
			when ORD.CODCENATE = '12021' THEN 'MANIZALES'
			when ORD.CODCENATE = '14041' THEN 'CARTAGO'
			WHEN ORD.CODCENATE = '12022' THEN 'MANIZALES'
			WHEN ORD.CODCENATE = '12024' THEN 'MANIZALES'
			WHEN ORD.CODCENATE = '13033' THEN 'ARMENIA'
			WHEN ORD.CODCENATE = '12025' THEN 'LA DORADA' END AS 'CIUDAD PROCEDIMIENTO',-- [CiudadProcedimiento],
		S.Code AS 'CODIGO ESQUEMA',--[CodEsquema],
		S.Description AS 'ESQUEMA',--[Esquema],
		CASE S.TypeScheme 
			WHEN 1 THEN 'Quimioterapia' 
			WHEN 2 THEN 'Enfermedades Huérfanas'
			WHEN 3 THEN 'Otros' END AS 'TIPO ESQUEMA',--[TipoEsquema],
		RTRIM(CUP.Description) AS 'SERVICIO ADMINISTRACION',--[ServicioAdministracion],
		CASE ORD.ESTADO 
			WHEN 1 THEN  'Orden Solicitada' 
			WHEN 2 THEN 'Esquema iniciado' 
			WHEN 3 THEN 'Esquema finalizado completo'
			WHEN 4 THEN 'Suspendido - Finalización prematura' 
			WHEN 5 THEN 'Anulado - Cuando no se ha iniciado tratamiento' END 'ESTADO',-- [Estado],
		ORD.CODDIAGNO 'CODIGO DIAGNOSTICO',--[CodDiagnostico],
		DIA.NOMDIAGNO AS 'DIAGNOSTICO',--[Diagnostico],
		CASE DXP.TIPDIAGNO 
			WHEN 'I' THEN 'Impresion Diagnostica' 
			WHEN 'C' THEN 'Confirmado Nuevo' 
			WHEN 'R' THEN 'Confirmado Repetido' END AS 'TIPO DIAGNOSTICO',--[TipoDiagnostico],
		CONVERT(VARCHAR(10), CAC.[23], 103) AS 'FECHA PATOLOGIA',--[FechaPatologia], 
		CAST(ORD.CICLOS AS CHAR) 'NRO CICLOS ESQUEMA',--[NroCiclosEsquema],
		CAST(DET.CICLO AS CHAR) 'CICLO ACTUAL',--[CicloActual],
		CAST(DET.DIA AS CHAR) 'DIA',--[Dia],
		M.NOMMEDICO AS 'PROFESIONAL ORDENO',--[ProfesionalOrdeno], 
		MED.NOMMEDICO AS 'PROFEIONAL ORDENO CICLO',--[ProfesionalOrdenoCiclo], 
		CAST(ORD.FECHAREGISTRO AS DATE) 'FECHA ORDEN',--[FechaOrden],
		CAST(CIC.FECHAREGISTRO AS DATE) 'FECHA ORDEN CICLO',--[FechaOrdenCiclo], 
		CASE DET.ESTADODIA 
			WHEN 1 THEN 'Dia Sin Cumplir' 
			WHEN 2 THEN 'Dia cumplido' 
			WHEN 3 THEN 'Antes de Indigo' END 'ESTADO DIA',--[EstadoDia],
		ISNULL(CAST(CIT.FECHORAIN AS DATE),'1900-01-01') AS 'FECHA APLICACION',--[FechaAplicacion],
		ING.IAUTORIZA AS 'NRO AUTORIZACION',--,
		PRO.CODSERIPS  'CUPS',--[CUPS], 
		CE.Description as 'DESCRIPCION',--[Descripcion],
		[CICLO ESQUEMA] = concat('Ciclo ', ORD.CICLOACTUAL, ' de ' , ORD.CICLOS),
		SAL.DESCRIPSAL AS 'SALA',--[Sala]
		CAST(ISNULL(CIT.FECHORAIN,'1900-01-01')  AS DATE) 'FECHA BUSQUEDA',
		YEAR(ORD.FECHAREGISTRO) AS 'AÑO CARGUE',
		CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL

	FROM EHR.HCORDQUIMIO ORD
	JOIN EHR.HCORDCICLOSD DET ON DET.IDHCORDQUIMIO =ORD.ID 
	LEFT JOIN EHR.HCORDCICLOS CIC ON DET.IDHCORDCICLOS=CIC.Id
	JOIN EHR.Schemes S ON S.Id = ORD.SchemesId
	LEFT JOIN Contract.CUPSEntity AS CUP ON S.ServiceIPS = CUP.Code
	JOIN dbo.INPACIENT AS P ON P.IPCODPACI = ORD.IPCODPACI
	JOIN dbo.ADINGRESO AS ING ON ORD.NUMINGRES  =ING.NUMINGRES
	JOIN dbo.ADCENATEN CEN ON CEN.CODCENATE = ORD.CODCENATE
	JOIN dbo.INUNIFUNC AS FUN ON FUN.UFUCODIGO =ORD.UFUCODIGO
	JOIN Contract.HealthAdministrator  H  on H.Id = ING.GENCONENTITY 
	JOIN Contract.CareGroup AS CG ON CG.Id =ING.GENCAREGROUP 
	JOIN dbo.INPROFSAL M ON M.CODPROSAL = ORD.CODPROSAL
	JOIN dbo.INPROFSAL AS MED ON CIC.CODPROSAL = MED.CODPROSAL 
	JOIN dbo.INUBICACI AS UB ON UB.AUUBICACI = P.AUUBICACI
	JOIN dbo.INMUNICIP AS MU ON MU.DEPMUNCOD = UB.DEPMUNCOD
	JOIN dbo.INDEPARTA AS DP ON DP.depcodigo = MU.DEPCODIGO
	--left JOIN CTE_APLICACION AS APLI ON CIC.NUMINGRES=APLI.[ingreso aplicacion]
	LEFT JOIN dbo.ADINGRESO AS INGR ON CIC.NUMINGRES=INGR.NUMINGRES
	LEFT join Contract.HealthAdministrator HO ON INGR.CODENTIDA=HO.Code
	LEFT JOIN Contract.CareGroup AS CGO ON CGO.Id=INGR.GENCAREGROUP 
	LEFT JOIN dbo.INDIAGNOS AS DIA ON DIA.CODDIAGNO =ORD.CODDIAGNO
	LEFT JOIN dbo.AGASICITA CIT ON CIT.IDHCORDCICLOSD = DET.ID
	LEFT JOIN dbo.HCORDPRON AS PRO ON PRO.AUTO =CIC.IDHCORDPRON 
	LEFT JOIN Contract.CUPSEntity  AS CE ON CE.Code  =PRO.CODSERIPS 
	LEFT JOIN dbo.AGENSALAC AS SAL ON CIT.IDSALA= SAL.CODCONCEC
	LEFT JOIN dbo.INDIAGNOP AS DXP  ON ORD.NUMINGRES=DXP.NUMINGRES  AND ORD.CODDIAGNO=DXP.CODDIAGNO
	LEFT JOIN dbo.HCONCOPREG AS CAC ON ORD.IPCODPACI=CAC.[6] AND ORD.CODDIAGNO=CAC.[17] 
	
	WHERE ORD.ESTADO in (1, 2, 3, 4) and CODESTCIT = 1 --AND CAST(ISNULL(CIT.FECHORAIN,'1900-01-01')  AS DATE) BETWEEN @FECINI AND @FECFIN 
	--ORDER BY P.IPCODPACI,S.Code