-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewInventarioHistoricoPrescripcion
-- Extracted by Fabric SQL Extractor SPN v3.9.0





    /*******************************************************************************************************************
Nombre: [Report].[ViewInventarioHistoricoPrescripcion]
Tipo:Vista
Observacion:Historico de ordenes y despensaciones de medicamentos e insumos.
Profesional: Nilsson Miguel Galindo Lopez
Fecha:03-08-2022
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha: 07-09-2022
Ovservaciones: se agrega las solicitudes de liquidos, se aclara que esta veción solo funciona para las bases de datos con vercion superior 31
--------------------------------------
Version 3
Persona que modifico: Nilsson Miguel Galindo Lopez 
Observacion:Se agregan los campos de registro de la devolucion de dispensacion farmaceutica
Fecha: 15-09-2022
--------------------------------------------------------------------------------------------
--------------------------------------
Version 4
Persona que modifico: Nilsson Miguel Galindo Lopez 
Observacion:Por solicitud de Paola Cuellar por medio del por gupo de whatsapp de homi se agregan los insumos a esta vista
Fecha: 21-09-2022
--------------------------------------
Version 5
Persona que modifico: Nilsson Miguel Galindo Lopez 
Observacion:Se cambia de logica, camabiando de tabla principal Inventory.InventoryProduct a las tablas Inventory.ATC para medicamentos y Inventory.InventorySupplie para insumos.
Fecha: 27-01-2023
--------------------------------------
Version 6
Persona que modifico: Nilsson Miguel Galindo Lopez 
Observacion:Se cambia la logica de los liquidos y mezclas, ya que antes no estaba trallendo la orden completa.
Fecha: 03-05-2023
--***********************************************************************************************************************************/
CREATE VIEW [Report].[ViewInventarioHistoricoPrescripcion]
AS

WITH

CTE_INGRESO AS
(
SELECT ING.NUMINGRES,ING.FECHEGRESO,CAM.DESCCAMAS
FROM 
dbo.ADINGRESO ING INNER JOIN
dbo.CHCAMASHO CAM ON ING.CODCAMACT=CAM.CODICAMAS
),

CTE_DEVOLUCION_DISPENSACION AS
(
SELECT
DISD.Id AS DispensacionDetalleId,
DD.Code AS CodigoDevolucionDispensacion,
DD.ConfirmationDate as FechaDevolucion,
USU.NOMUSUARI AS Regente,
DDD.Quantity AS Cantidad,
--in v3
PRO.NOMMEDICO,
CASE PRO.TIPPROFES WHEN 1 THEN 'Medico General' 
				   WHEN 2 THEN 'Medico Especialista' 
				   WHEN 3 THEN 'Enfermera'
				   WHEN 4 THEN 'Auxiliar Enfermeria' 
				   WHEN 16 THEN 'Terapeuta'
				   WHEN 21 THEN 'Instrumentador' END PROFESION,
FECREGISTR
--fn v3
FROM
Inventory.PharmaceuticalDispensingDevolutionDetail DDD INNER JOIN
Inventory.PharmaceuticalDispensingDetailBatchSerial BAT ON DDD.PharmaceuticalDispensingDetailBatchSerialId=BAT.Id INNER JOIN
Inventory.PharmaceuticalDispensingDetail DISD ON BAT.PharmaceuticalDispensingDetailId=DISD.Id INNER JOIN
Inventory.PharmaceuticalDispensingDevolution DD ON DDD.PharmaceuticalDispensingDevolutionId=DD.Id AND DD.Status=2 INNER JOIN
dbo.SEGusuaru USU ON DD.ConfirmationUser=USU.CODUSUARI LEFT JOIN
--in v3
dbo.HCDEVMEDC DEV ON DD.EntityId=DEV.CODCONCEC LEFT JOIN
dbo.INPROFSAL PRO ON DEV.CODPROSAL=PRO.CODPROSAL
--fn v3
),

CTE_DETALLE_FARMACIA AS
(
select 
D.CODCONCEC,a.NUMINGRES,a.CODPRODUC,D.CODUNIMED,D.ID,
ISNULL(A.DOSISPROD,D.DOSISPROD)AS DOSISPROD,A.FRECUENCI,A.UNIFRECUE,A.DURACIDOS,D.CANPEDPRO
from 
dbo.HCFARMEPC c inner join
dbo.HCFARMEPD d on c.CODCONCEC=d.CODCONCEC inner join
dbo.HCPRESCRA  a on a.NUMINGRES= d.NUMINGRES and a.CODPRODUC=d.CODPRODUC and (c.FECHAORDE>=a.FECINIDOS and c.FECHAORDE<=a.FECFINDOS)
union all
select
D.CODCONCEC,a.NUMINGRES,a.CODPRODUC,D.CODUNIMED,D.ID,
ISNULL(A.DOSISPROD,D.DOSISPROD)AS DOSISPROD,A.FRECUENCI,A.UNIFRECUE,A.DURACIDOS,D.CANPEDPRO
from 
dbo.HCFARMEPC c inner join
dbo.HCFARMEPD d on c.CODCONCEC=d.CODCONCEC inner join
dbo.HCPRESCRA a on a.NUMINGRES= d.NUMINGRES and a.CODPRODUC=d.CODPRODUC and c.FECHAORDE>=a.FECINIDOS and a.PREESTADO NOT IN (2,4,5,6,7)
),

----------------------CTE PARA LOS LIQUIDOS----------------------------------------------------------------------------------
--IN V2, IN V6
CTE_LIQUIDOS AS
(
SELECT 
FAR.ID,
ISNULL(FAR.FECINIDOS,A.FECHAINIC) AS FECHA,
CASE A.PREESTADO WHEN 1 THEN 'TRATAMIENTO NUEVO'ELSE 'TRATAMIENTO ANTIGUO'END AS ESTADO,
A.NUMINGRES,
A.UFUCODIGO,
A.NUMEFOLIO,A.IPCODPACI,
FAR.CODPRODUC,
FAR.DOSISPROD AS DOSIS,
CASE WHEN D.UNIMEDBOL IS NOT NULL THEN D.UNIMEDBOL
	 WHEN D.UNIMEDINF IS NOT NULL THEN D.UNIMEDINF 
	 WHEN D.UNIMEDDIL IS NOT NULL THEN D.UNIMEDDIL END AS MEDIDA,
FAR.FRECUENCI AS FRECUENCIA,
CASE FAR.UNIFRECUE WHEN 1 THEN 'MINUTOS'
				   WHEN 2 THEN 'HORAS'
				   WHEN 3 THEN 'DIAS' END AS TIEMPO,
'INTRAVENOSA' as ADMINISTRACION,
ISNULL(D.DURACIINF,'Dosis Unica')as DURACION,
CASE D.DURACIINF WHEN 'Tratamiento Continuo' THEN DATEDIFF(DAY,A.FECHAINIC,GETDATE()) END AS TRATAMIENTO,
D.CANPROCAL AS CANTIDAD,
A.CODPROSAL AS PROFESIONAL
FROM 
dbo.HCFARMEPD FAR INNER JOIN
DBO.HCINFLIQA A ON FAR.IdSourceTable=A.CONSECUTI AND FAR.SourceTable='HCINFLIQA' INNER JOIN
DBO.HCINFLIQD D ON A.CODCONCEC=D.CODCONCEC
)
--FN V2 FN V6
-------------------------------SELECT DE LOS MEDICAMENTOS------------------------------------------------------------------------------------------

SELECT DISTINCT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
FAR.FECHAORDE AS [FECHA DE LA ORDEN],
CASE FAR.ORDTRANUE WHEN 1 THEN 'TRATAMIENTO NUEVO' 
				   WHEN 2 THEN 'TRATAMIENTO ANTIGUO'
				   WHEN 3 THEN 'CODIGO AZUL' END AS [TIPO DE ORDEN],
FAR.NUMINGRES AS [NUMERO DE INGRESO],
FAR.NUMEFOLIO AS [NUMERO DE FOLIO],
PAC.IPCODPACI AS [ID PACIENTE],
PAC.IPNOMCOMP AS PACIENTE,
FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
ING.DESCCAMAS AS CAMA,
FARD.CODPRODUC AS [CODIGO DE PRODUCTO],
INV.Name AS PRODUCTO,
TIP.Name AS [TIPO DE PRODUCTO],
GFA.Name AS [GRUPO FARMACOLOGICO],
ISNULL(FARD.DOSISPROD,'0.00') AS DOSIS,
UM.Name AS MEDIDA,
FARD.FRECUENCI AS FRECUENCIA,
CASE UNIFRECUE WHEN 1 THEN 'MINUTOS'
			   WHEN 2 THEN 'HORAS'
			   WHEN 3 THEN 'DIAS' END AS TIEMPO,
ADM.NAME AS [VIA DE ADMINISTRACION],
DURACIDOS AS DURACION,
FARD.CANPEDPRO AS [CANTIDAD FORMULADA],
CASE HC.CONCILIACIONMED WHEN 'TRUE' THEN 'SI' 
						WHEN 'FALSE' THEN 'NO' END AS [CONCILIACION MEDICAMENTOSA],
DISD.Quantity AS [CANTIDAD DISPENSADA],
'' AS [CANTIDAD APLICADA],
DD.Cantidad AS [CANTIDAD DEVUELTA],
DIS.Code AS [CODIGO DE DISPENSACION],
DIS.ConfirmationDate AS [FECHA Y HORA DISPENSACION],
USU.NOMUSUARI AS [USUARIO CONFIRMACION],
--in v3
DD.NOMMEDICO AS [USUARIO DE DEVOLUCION],
DD.PROFESION AS [CARGO DE DEVOLUCION],
DD.FECREGISTR AS [REGISTRO DE DEVOLUCIÓN],
--fn v3
DD.CodigoDevolucionDispensacion AS [CODIGO DEVOLUCION DISPENSACION],
DD.FechaDevolucion AS [FECHA Y HORA DEVOLUCION DISPENSACION],
DD.Regente AS [USUARIO CONFIRMA DEVOLUCION],
ENT.NOMENTIDA AS ENTIDAD,
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro'
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado' 
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [GRUPO DE ATENCION],
CASE WHEN ING.FECHEGRESO IS NULL THEN 'HOSPITALIZADO' ELSE 'EGRESADO' END AS ESTADO,
PRO.NOMMEDICO AS [PROFESIONAL QUE ORDENO],
INV.ProductCost AS [COSTO PROMEDIO],
CAST(FAR.FECHAORDE AS date) AS 'FECHA BUSQUEDA',
YEAR(FAR.FECHAORDE) AS 'AÑO FECHA BUSQUEDA',
MONTH(FAR.FECHAORDE) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(FAR.FECHAORDE), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(FAR.FECHAORDE), '00') ,' - ', 
CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE'END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
dbo.HCFARMEPC FAR INNER JOIN
CTE_DETALLE_FARMACIA FARD ON FAR.CODCONCEC=FARD.CODCONCEC INNER JOIN
DBO.INPACIENT PAC ON FAR.IPCODPACI=PAC.IPCODPACI INNER JOIN
DBO.INUNIFUNC FUN ON FAR.UFUCODIGO=FUN.UFUCODIGO INNER JOIN
Inventory.ATC ATC ON FARD.CODPRODUC=ATC.Code INNER JOIN --in v5 Se pone como unon entre los medicamentos la tabla medicamentos y se une luego con la de productos fn v5
Inventory.InventoryProduct INV ON ATC.ID= INV.ATCId AND INV.STATUS=1 INNER JOIN
Inventory.ProductType TIP ON INV.ProductTypeId=TIP.Id LEFT JOIN
--Inventory.ATC ATC ON INV.ATCId=ATC.Id LEFT JOIN --in v5 se sube la tabla de medicamentos
Inventory.PharmacologicalGroup GFA ON ATC.PharmacologicalGroupId=GFA.Id LEFT JOIN
Inventory.InventoryMeasurementUnit UM ON FARD.CODUNIMED=UM.Code LEFT JOIN
Inventory.AdministrationRoute ADM ON ATC.AdministrationRouteId=ADM.Id LEFT JOIN
Inventory.PharmaceuticalDispensingDetail DISD ON FARD.ID=DISD.EntityId LEFT JOIN
Inventory.PharmaceuticalDispensing DIS ON DISD.PharmaceuticalDispensingId=DIS.Id AND DIS.Status=2 LEFT JOIN
dbo.SEGusuaru USU ON DIS.ConfirmationUser=USU.CODUSUARI LEFT JOIN
dbo.INENTIDAD ENT ON PAC.CODENTIDA=ENT.CODENTIDA LEFT JOIN
CTE_INGRESO ING ON FAR.NUMINGRES=ING.NUMINGRES LEFT JOIN
dbo.INPROFSAL PRO ON FAR.CODPROSAL=PRO.CODPROSAL LEFT JOIN
CTE_DEVOLUCION_DISPENSACION DD ON DISD.Id=DD.DispensacionDetalleId LEFT JOIN
dbo.HCHISPACA HC ON FAR.NUMINGRES=HC.NUMINGRES AND FAR.NUMEFOLIO=HC.NUMEFOLIO

UNION ALL

-----------mezclas y liquidos---------------------------------------------------
SELECT DISTINCT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
FAR.FECHA AS [FECHA DE LA ORDEN],
FAR.ESTADO AS [TIPO DE ORDEN],
FAR.NUMINGRES AS [NUMERO DE INGRESO],
FAR.NUMEFOLIO AS [NUMERO DE FOLIO],
PAC.IPCODPACI AS [ID PACIENTE],
PAC.IPNOMCOMP AS PACIENTE,
FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
ING.DESCCAMAS AS CAMA,
FAR.CODPRODUC AS [CODIGO DE PRODUCTO],
INV.Name AS PRODUCTO,
'MEZCLAS/LIQUIDOS' AS [TIPO DE PRODUCTO],
GFA.Name AS [GRUPO FARMACOLOGICO],
FAR.DOSIS,
UM.Name AS MEDIDA,
FAR.FRECUENCIA,
FAR.TIEMPO,
ADM.NAME AS [VIA DE ADMINISTRACION],
FAR.DURACION,
FAR.CANTIDAD AS [CANTIDAD FORMULADA],
NULL AS [CONCILIACION MEDICAMENTOSA],
DISD.Quantity AS [CANTIDAD DISPENSADA],
'' AS [CANTIDAD APLICADA],
DD.Cantidad AS [CANTIDAD DEVUELTA],
DIS.Code AS [CODIGO DE DISPENSACION],
DIS.ConfirmationDate AS [FECHA Y HORA DISPENSACION],
USU.NOMUSUARI AS [USUARIO CONFIRMACION],
--in v3
DD.NOMMEDICO AS [USUARIO DE DEVOLUCION],
DD.PROFESION AS [CARGO DE DEVOLUCION],
DD.FECREGISTR AS [REGISTRO DE DEVOLUCIÓN],
--fn v3
DD.CodigoDevolucionDispensacion AS [CODIGO DEVOLUCION DISPENSACION],
DD.FechaDevolucion AS [FECHA Y HORA DEVOLUCION DISPENSACION],
DD.Regente AS [USUARIO CONFIRMA DEVOLUCION],
ENT.NOMENTIDA AS ENTIDAD,
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro'
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado' 
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [GRUPO DE ATENCION],
CASE WHEN ING.FECHEGRESO IS NULL THEN 'HOSPITALIZADO' ELSE 'EGRESADO' END AS ESTADO,
PRO.NOMMEDICO AS [PROFESIONAL QUE ORDENO],
INV.ProductCost AS [COSTO PROMEDIO],
CAST(FAR.FECHA AS date) AS 'FECHA BUSQUEDA',
YEAR(FAR.FECHA) AS 'AÑO FECHA BUSQUEDA',
MONTH(FAR.FECHA) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(FAR.FECHA) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(FAR.FECHA), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(FAR.FECHA), '00') ,' - ', 
CASE MONTH(FAR.FECHA) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE'END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
CTE_LIQUIDOS FAR INNER JOIN
DBO.INPACIENT PAC ON FAR.IPCODPACI=PAC.IPCODPACI INNER JOIN
DBO.INUNIFUNC FUN ON FAR.UFUCODIGO=FUN.UFUCODIGO INNER JOIN
Inventory.ATC ATC ON FAR.CODPRODUC=ATC.CODE INNER JOIN --in v5 Se pone como unon entre los medicamentos la tabla medicamentos y se une luego con la de productos fn v5
Inventory.InventoryProduct INV ON ATC.ID=INV.ATCID INNER JOIN
Inventory.ProductType TIP ON INV.ProductTypeId=TIP.Id AND TIP.Name='MEDICAMENTOS' LEFT JOIN
--Inventory.ATC ATC ON INV.ATCId=ATC.Id LEFT JOIN --in v5 se sube la tabla de medicamentos
Inventory.PharmacologicalGroup GFA ON ATC.PharmacologicalGroupId=GFA.Id LEFT JOIN
Inventory.InventoryMeasurementUnit UM ON FAR.MEDIDA=UM.Code LEFT JOIN
Inventory.AdministrationRoute ADM ON ATC.AdministrationRouteId=ADM.Id LEFT JOIN
Inventory.PharmaceuticalDispensingDetail DISD ON FAR.ID=DISD.EntityId AND EntityName='HCFARMEPD' LEFT JOIN
Inventory.PharmaceuticalDispensing DIS ON DISD.PharmaceuticalDispensingId=DIS.Id AND DIS.Status=2 LEFT JOIN
dbo.SEGusuaru USU ON DIS.ConfirmationUser=USU.CODUSUARI LEFT JOIN
dbo.INENTIDAD ENT ON PAC.CODENTIDA=ENT.CODENTIDA LEFT JOIN
CTE_INGRESO ING ON FAR.NUMINGRES=ING.NUMINGRES LEFT JOIN
dbo.INPROFSAL PRO ON FAR.PROFESIONAL=PRO.CODPROSAL LEFT JOIN
CTE_DEVOLUCION_DISPENSACION DD ON DISD.Id=DD.DispensacionDetalleId  
--FN V2
UNION ALL 

-----------------------------------SELECT CUANDO LAS SOLICITUDES SON SUMINISTROS MEDICOS----------------------------------
--IN V4
SELECT DISTINCT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
FAR.FECHAORDE AS [FECHA DE LA ORDEN],
'' AS [TIPO DE ORDEN],
FAR.NUMINGRES AS [NUMERO DE INGRESO],
FAR.NUMEFOLIO AS [NUMERO DE FOLIO],
PAC.IPCODPACI AS [ID PACIENTE],
PAC.IPNOMCOMP AS PACIENTE,
FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
ING.DESCCAMAS AS CAMA,
FARD.CODPRODUC AS [CODIGO DE PRODUCTO],
INV.Name AS PRODUCTO,
'SUMINISTROS' AS [TIPO DE PRODUCTO],
'' AS [GRUPO FARMACOLOGICO],
ISNULL(FARD.DOSISPROD,'0.00') AS DOSIS,
'' AS MEDIDA,
FARD.FRECUENCI AS FRECUENCIA,
CASE UNIFRECUE WHEN 1 THEN 'MINUTOS'
			   WHEN 2 THEN 'HORAS'
			   WHEN 3 THEN 'DIAS' END AS TIEMPO,
'' AS [VIA DE ADMINISTRACION],
DURACIDOS AS DURACION,
FARD.CANPEDPRO AS [CANTIDAD FORMULADA],
NULL AS [CONCILIACION MEDICAMENTOSA],
DISD.Quantity AS [CANTIDAD DISPENSADA],
'' AS [CANTIDAD APLICADA],
DD.Cantidad AS [CANTIDAD DEVUELTA],
DIS.Code AS [CODIGO DE DISPENSACION],
DIS.ConfirmationDate AS [FECHA Y HORA DISPENSACION],
USU.NOMUSUARI AS [USUARIO CONFIRMACION],
--in v3
DD.NOMMEDICO AS [USUARIO DE DEVOLUCION],
DD.PROFESION AS [CARGO DE DEVOLUCION],
DD.FECREGISTR AS [REGISTRO DE DEVOLUCIÓN],
--fn v3
DD.CodigoDevolucionDispensacion AS [CODIGO DEVOLUCION DISPENSACION],
DD.FechaDevolucion AS [FECHA Y HORA DEVOLUCION DISPENSACION],
DD.Regente AS [USUARIO CONFIRMA DEVOLUCION],
ENT.NOMENTIDA AS ENTIDAD,
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro'
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado' 
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [GRUPO DE ATENCION],
CASE WHEN ING.FECHEGRESO IS NULL THEN 'HOSPITALIZADO' ELSE 'EGRESADO' END AS ESTADO,
PRO.NOMMEDICO AS [PROFESIONAL QUE ORDENO],
INV.ProductCost AS [COSTO PROMEDIO],
CAST(FAR.FECHAORDE AS date) AS 'FECHA BUSQUEDA',
YEAR(FAR.FECHAORDE) AS 'AÑO FECHA BUSQUEDA',
MONTH(FAR.FECHAORDE) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(FAR.FECHAORDE), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(FAR.FECHAORDE), '00') ,' - ', 
CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE'END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
dbo.HCFARMEPC FAR INNER JOIN
dbo.HCFARMEPD FARD ON FAR.CODCONCEC=FARD.CODCONCEC INNER JOIN
DBO.INPACIENT PAC ON FAR.IPCODPACI=PAC.IPCODPACI INNER JOIN
DBO.INUNIFUNC FUN ON FAR.UFUCODIGO=FUN.UFUCODIGO INNER JOIN
Inventory.InventorySupplie INS ON FARD.CODPRODUC=INS.CODE INNER JOIN --in v5 Se pone como unon entre los suministros la tabla insumos fn v5
Inventory.InventoryProduct INV ON INS.ID=INV.SupplieId LEFT JOIN 
--Inventory.ProductType TIP ON INV.ProductTypeId=TIP.Id  AND TIP.Name LIKE '%SUMINISTROS%' LEFT JOIN -- se quita la tabla de tipo de productos
Inventory.PharmaceuticalDispensingDetail DISD ON FARD.ID=DISD.EntityId LEFT JOIN
Inventory.PharmaceuticalDispensing DIS ON DISD.PharmaceuticalDispensingId=DIS.Id AND DIS.Status=2 LEFT JOIN
dbo.SEGusuaru USU ON DIS.ConfirmationUser=USU.CODUSUARI LEFT JOIN
dbo.INENTIDAD ENT ON PAC.CODENTIDA=ENT.CODENTIDA LEFT JOIN
CTE_INGRESO ING ON FAR.NUMINGRES=ING.NUMINGRES LEFT JOIN
dbo.INPROFSAL PRO ON FAR.CODPROSAL=PRO.CODPROSAL LEFT JOIN
CTE_DEVOLUCION_DISPENSACION DD ON DISD.Id=DD.DispensacionDetalleId  
--IN V4
