-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewAdicionalGestionRiesgo
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[ViewAdicionalGestionRiesgo] AS

WITH CTE_POBLACION AS
 (
  SELECT --ROW_NUMBER () OVER (PARTITION BY IPCODPACI ORDER BY IDMODELOHC, FECHISPAC DESC) 'NUMERO',
	IPCODPACI,IDMODELOHC, 
	NUMEFOLIO,
	FECHISPAC,
	ID,
	CODCENATE,
	NUMINGRES
	FROM HCHISPACA 
--WHERE (FECHISPAC BETWEEN @FechaInicial AND @FechaFinal) -- AND IDMODELOHC IS NOT NULL --AND IPCODPACI='1002276183'
 ),

CTE_EDUCACIONGRUPAL
AS
(
  	  SELECT DISTINCT F.AdmissionNumber ,F.PatientCode ,CUPS.Code ,CUPS.Description, DOS.ServiceDate   FROM   BILLING.INVOICE AS F WITH (NOLOCK) 
		   INNER JOIN BILLING.INVOICEDETAIL AS DF WITH (NOLOCK) ON DF.INVOICEID = F.ID 
		   --INNER JOIN BILLING.REVENUECONTROLDETAIL RCD WITH (NOLOCK) ON RCD.ID = F.REVENUECONTROLDETAILID 
		   --INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON CAST(ING.NUMINGRES AS INT) = F.ADMISSIONNUMBER 
		   --INNER JOIN DBO.ADCENATEN AS CEN WITH (NOLOCK) ON CEN.CODCENATE = ING.CODCENATE 
		   INNER JOIN BILLING.SERVICEORDERDETAIL AS DOS WITH (NOLOCK) ON DOS.ID = DF.SERVICEORDERDETAILID
		  INNER JOIN CONTRACT.CUPSENTITY AS CUPS WITH (NOLOCK) ON CUPS.ID = DOS.CUPSENTITYID
		   WHERE CUPS.Code IN ('990101','990102','990103','990104','990105','990106','990107','990108','990109','990110','990111','990112','990113') 
		   AND F.Status =1 group by F.AdmissionNumber ,F.PatientCode ,CUPS.Code ,CUPS.Description,DOS.ServiceDate
),

CTE_EDUCACIONINDIVIDUAL
AS
(
  	  SELECT DISTINCT F.AdmissionNumber ,F.PatientCode ,CUPS.Code ,CUPS.Description, DOS.ServiceDate   FROM   BILLING.INVOICE AS F WITH (NOLOCK) 
		   INNER JOIN BILLING.INVOICEDETAIL AS DF WITH (NOLOCK) ON DF.INVOICEID = F.ID 
		   --INNER JOIN BILLING.REVENUECONTROLDETAIL RCD WITH (NOLOCK) ON RCD.ID = F.REVENUECONTROLDETAILID 
		   --INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON CAST(ING.NUMINGRES AS INT) = F.ADMISSIONNUMBER 
		   --INNER JOIN DBO.ADCENATEN AS CEN WITH (NOLOCK) ON CEN.CODCENATE = ING.CODCENATE 
		   INNER JOIN BILLING.SERVICEORDERDETAIL AS DOS WITH (NOLOCK) ON DOS.ID = DF.SERVICEORDERDETAILID
		  INNER JOIN CONTRACT.CUPSENTITY AS CUPS WITH (NOLOCK) ON CUPS.ID = DOS.CUPSENTITYID
		   WHERE CUPS.Code IN ('990201','990202','990203','990204','990205','990206','990207','990208','990209','990210','990211','990212','990213','990221','990222','990223','990224') 
		   AND F.Status =1 group by F.AdmissionNumber ,F.PatientCode ,CUPS.Code ,CUPS.Description,DOS.ServiceDate
),

CTE_EDUCACIONFAMILIAR
AS
(
  	  SELECT DISTINCT F.AdmissionNumber ,F.PatientCode ,CUPS.Code ,CUPS.Description, DOS.ServiceDate   FROM   BILLING.INVOICE AS F WITH (NOLOCK) 
		   INNER JOIN BILLING.INVOICEDETAIL AS DF WITH (NOLOCK) ON DF.INVOICEID = F.ID 
		   --INNER JOIN BILLING.REVENUECONTROLDETAIL RCD WITH (NOLOCK) ON RCD.ID = F.REVENUECONTROLDETAILID 
		   --INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON CAST(ING.NUMINGRES AS INT) = F.ADMISSIONNUMBER 
		   --INNER JOIN DBO.ADCENATEN AS CEN WITH (NOLOCK) ON CEN.CODCENATE = ING.CODCENATE 
		   INNER JOIN BILLING.SERVICEORDERDETAIL AS DOS WITH (NOLOCK) ON DOS.ID = DF.SERVICEORDERDETAILID
		  INNER JOIN CONTRACT.CUPSENTITY AS CUPS WITH (NOLOCK) ON CUPS.ID = DOS.CUPSENTITYID
		   WHERE CUPS.Code IN ('990201','990202','990203','990204','990205','990206','990207','990208','990209','990210','990211','990212','990213','990221','990222','990223','990224') 
		   AND F.Status =1 group by F.AdmissionNumber ,F.PatientCode ,CUPS.Code ,CUPS.Description,DOS.ServiceDate
),

CTE_EDAD_LACTANCIA
AS
(
SELECT*FROM ANTVALORES WHERE IDANTVARIABLE IN (373)

),

CTE_ANTECEDENTES_ALCOCHOL
AS
(
SELECT*FROM ANTVALORES WHERE IDANTVARIABLE IN (290,315,316,317)

),

CTE_RIESGO_CAPROSTATA
AS
(
SELECT*FROM [TablaExamenFisico] WHERE [ID_VARIABLE] IN (106,209,210)

),

CTE_DISPENSACIONES_ANTIPARASITARIOS
AS
(
SELECT  PDD.SERVICEDATE 'FECHA DISPENSACION', HA.NAME 'ENTIDAD', PER.IDENTIFICATIONNUMBER 'ID TERCERO/PACIENTE', TER.NAME 'NOMBRE TERCERO/PACIENTE',PRO.CODE 'COD. PRODUCTO' ,
PRO.NAME 'NOMBRE PRODUCTO',GRU.NAME 'GRUPO FARMACOLOGICO', PDD.QUANTITY 'CANTIDAD'

FROM INVENTORY.PHARMACEUTICALDISPENSING PD
INNER JOIN INVENTORY.PHARMACEUTICALDISPENSINGDETAIL PDD ON PDD.PHARMACEUTICALDISPENSINGID=PD.ID
INNER JOIN COMMON.THIRDPARTY TER ON TER.ID=PDD.THIRDPARTYID
INNER JOIN COMMON.PERSON PER ON PER.ID=TER.PERSONID
INNER JOIN INVENTORY.INVENTORYPRODUCT PRO ON PRO.ID=PDD.PRODUCTID
INNER JOIN INVENTORY.ATC ATC ON ATC.CODE=PRO.CODE
INNER JOIN INVENTORY.PHARMACOLOGICALGROUP GRU ON GRU.ID=ATC.PHARMACOLOGICALGROUPID
INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.ID=PDD.HEALTHADMINISTRATORID

WHERE GRU.ID IN (22,31)

),

CTE_DISPENSACIONES_MICRONUTRIENTES
AS
(
SELECT  PDD.SERVICEDATE 'FECHA DISPENSACION', HA.NAME 'ENTIDAD', PER.IDENTIFICATIONNUMBER 'ID TERCERO/PACIENTE', TER.NAME 'NOMBRE TERCERO/PACIENTE',PRO.CODE 'COD. PRODUCTO' ,
PRO.NAME 'NOMBRE PRODUCTO',GRU.NAME 'GRUPO FARMACOLOGICO', PDD.QUANTITY 'CANTIDAD'

FROM INVENTORY.PHARMACEUTICALDISPENSING PD
INNER JOIN INVENTORY.PHARMACEUTICALDISPENSINGDETAIL PDD ON PDD.PHARMACEUTICALDISPENSINGID=PD.ID
INNER JOIN COMMON.THIRDPARTY TER ON TER.ID=PDD.THIRDPARTYID
INNER JOIN COMMON.PERSON PER ON PER.ID=TER.PERSONID
INNER JOIN INVENTORY.INVENTORYPRODUCT PRO ON PRO.ID=PDD.PRODUCTID
INNER JOIN INVENTORY.ATC ATC ON ATC.CODE=PRO.CODE
INNER JOIN INVENTORY.PHARMACOLOGICALGROUP GRU ON GRU.ID=ATC.PHARMACOLOGICALGROUPID
INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.ID=PDD.HEALTHADMINISTRATORID

WHERE GRU.ID IN (88)

),

CTE_DISPENSACIONES_VITAMINA_A
AS
(
SELECT  PDD.SERVICEDATE 'FECHA DISPENSACION', HA.NAME 'ENTIDAD', PER.IDENTIFICATIONNUMBER 'ID TERCERO/PACIENTE', TER.NAME 'NOMBRE TERCERO/PACIENTE',PRO.CODE 'COD. PRODUCTO' ,
PRO.NAME 'NOMBRE PRODUCTO',GRU.NAME 'GRUPO FARMACOLOGICO', PDD.QUANTITY 'CANTIDAD'

FROM INVENTORY.PHARMACEUTICALDISPENSING PD
INNER JOIN INVENTORY.PHARMACEUTICALDISPENSINGDETAIL PDD ON PDD.PHARMACEUTICALDISPENSINGID=PD.ID
INNER JOIN COMMON.THIRDPARTY TER ON TER.ID=PDD.THIRDPARTYID
INNER JOIN COMMON.PERSON PER ON PER.ID=TER.PERSONID
INNER JOIN INVENTORY.INVENTORYPRODUCT PRO ON PRO.ID=PDD.PRODUCTID
INNER JOIN INVENTORY.ATC ATC ON ATC.CODE=PRO.CODE
INNER JOIN INVENTORY.PHARMACOLOGICALGROUP GRU ON GRU.ID=ATC.PHARMACOLOGICALGROUPID
INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.ID=PDD.HEALTHADMINISTRATORID

WHERE ATC.CODE IN ('A11CA0101')

),

CTE_DISPENSACIONES_HIERRO
AS
(
SELECT  PDD.SERVICEDATE 'FECHA DISPENSACION', HA.NAME 'ENTIDAD', PER.IDENTIFICATIONNUMBER 'ID TERCERO/PACIENTE', TER.NAME 'NOMBRE TERCERO/PACIENTE',PRO.CODE 'COD. PRODUCTO' ,
PRO.NAME 'NOMBRE PRODUCTO',GRU.NAME 'GRUPO FARMACOLOGICO', PDD.QUANTITY 'CANTIDAD'

FROM INVENTORY.PHARMACEUTICALDISPENSING PD
INNER JOIN INVENTORY.PHARMACEUTICALDISPENSINGDETAIL PDD ON PDD.PHARMACEUTICALDISPENSINGID=PD.ID
INNER JOIN COMMON.THIRDPARTY TER ON TER.ID=PDD.THIRDPARTYID
INNER JOIN COMMON.PERSON PER ON PER.ID=TER.PERSONID
INNER JOIN INVENTORY.INVENTORYPRODUCT PRO ON PRO.ID=PDD.PRODUCTID
INNER JOIN INVENTORY.ATC ATC ON ATC.CODE=PRO.CODE
INNER JOIN INVENTORY.PHARMACOLOGICALGROUP GRU ON GRU.ID=ATC.PHARMACOLOGICALGROUPID
INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.ID=PDD.HEALTHADMINISTRATORID

WHERE ATC.CODE IN ('B03AA0701','B03AA0702','B03AA0703','B03AC0201')
),

CTE_DISPENSACIONES_FERROSO
AS
(
SELECT  PDD.SERVICEDATE 'FECHA DISPENSACION', HA.NAME 'ENTIDAD', PER.IDENTIFICATIONNUMBER 'ID TERCERO/PACIENTE', TER.NAME 'NOMBRE TERCERO/PACIENTE',PRO.CODE 'COD. PRODUCTO' ,
PRO.NAME 'NOMBRE PRODUCTO',GRU.NAME 'GRUPO FARMACOLOGICO', PDD.QUANTITY 'CANTIDAD'

FROM INVENTORY.PHARMACEUTICALDISPENSING PD
INNER JOIN INVENTORY.PHARMACEUTICALDISPENSINGDETAIL PDD ON PDD.PHARMACEUTICALDISPENSINGID=PD.ID
INNER JOIN COMMON.THIRDPARTY TER ON TER.ID=PDD.THIRDPARTYID
INNER JOIN COMMON.PERSON PER ON PER.ID=TER.PERSONID
INNER JOIN INVENTORY.INVENTORYPRODUCT PRO ON PRO.ID=PDD.PRODUCTID
INNER JOIN INVENTORY.ATC ATC ON ATC.CODE=PRO.CODE
INNER JOIN INVENTORY.PHARMACOLOGICALGROUP GRU ON GRU.ID=ATC.PHARMACOLOGICALGROUPID
INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.ID=PDD.HEALTHADMINISTRATORID

WHERE ATC.CODE IN ('B03AE0201','B03BB0101','B03BB0102','D05AX0101')
),

CTE_DISPENSACIONES_CALCIO
AS
(
SELECT  PDD.SERVICEDATE 'FECHA DISPENSACION', HA.NAME 'ENTIDAD', PER.IDENTIFICATIONNUMBER 'ID TERCERO/PACIENTE', TER.NAME 'NOMBRE TERCERO/PACIENTE',PRO.CODE 'COD. PRODUCTO' ,
PRO.NAME 'NOMBRE PRODUCTO',GRU.NAME 'GRUPO FARMACOLOGICO', PDD.QUANTITY 'CANTIDAD'

FROM INVENTORY.PHARMACEUTICALDISPENSING PD
INNER JOIN INVENTORY.PHARMACEUTICALDISPENSINGDETAIL PDD ON PDD.PHARMACEUTICALDISPENSINGID=PD.ID
INNER JOIN COMMON.THIRDPARTY TER ON TER.ID=PDD.THIRDPARTYID
INNER JOIN COMMON.PERSON PER ON PER.ID=TER.PERSONID
INNER JOIN INVENTORY.INVENTORYPRODUCT PRO ON PRO.ID=PDD.PRODUCTID
INNER JOIN INVENTORY.ATC ATC ON ATC.CODE=PRO.CODE
INNER JOIN INVENTORY.PHARMACOLOGICALGROUP GRU ON GRU.ID=ATC.PHARMACOLOGICALGROUPID
INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.ID=PDD.HEALTHADMINISTRATORID

WHERE ATC.CODE IN ('A12AA0401','A11AA0201','A02AC0101')
),

CTE_DISPENSACION_PRESERVATIVOS
AS
(
SELECT  PDD.SERVICEDATE 'FECHA DISPENSACION', HA.NAME 'ENTIDAD', PER.IDENTIFICATIONNUMBER 'ID TERCERO/PACIENTE', TER.NAME 'NOMBRE TERCERO/PACIENTE',PRO.CODE 'COD. PRODUCTO' ,
PRO.NAME 'NOMBRE PRODUCTO', PDD.QUANTITY 'CANTIDAD'

FROM INVENTORY.PHARMACEUTICALDISPENSING PD
INNER JOIN INVENTORY.PHARMACEUTICALDISPENSINGDETAIL PDD ON PDD.PHARMACEUTICALDISPENSINGID=PD.ID
INNER JOIN INVENTORY.INVENTORYPRODUCT PRO ON PRO.ID=PDD.PRODUCTID
INNER JOIN COMMON.THIRDPARTY TER ON TER.ID=PDD.THIRDPARTYID
INNER JOIN COMMON.PERSON PER ON PER.ID=TER.PERSONID
INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.ID=PDD.HEALTHADMINISTRATORID

WHERE PRO.CODE IN ('DM00801')
),

CTE_RIESGO_UROANALISIS
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (182)
),

CTE_FECHA_COLESTEROLTOTAL
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (153)
),

CTE_RESULTADO_COLESTEROLTOTAL
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (154)
),

CTE_FECHA_HDL
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (156)

),

CTE_RESULTADO_HDL
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (157)
),

CTE_FECHA_LDL
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (159)
),

CTE_RESULTADO_LDL
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (161)

),


CTE_FECHA_CREATININA
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (173,176)
),

CTE_RESULTADO_CREATININA
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (174,177,185)
),

CTE_FECHA_TRIGLICERIDOS
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (179,186,187)

),

CTE_RESULTADO_TRIGLICERIDOS
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (180)
),

CTE_FECHA_GLICEMIA
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (150)

),

CTE_RESULTADO_GLICEMIA
AS
(
SELECT*FROM [Report].[TablaExamenFisico]  WHERE [ID_VARIABLE] IN (151)

),

CTE_FECHA_HEMATOCRITO
AS
(
SELECT*FROM [Report].[TablaExamenFisico]  WHERE [ID_VARIABLE] IN (163,165)
),

CTE_RESULTADO_HEMATOCRITO
AS
(
SELECT*FROM [Report].[TablaExamenFisico]  WHERE [ID_VARIABLE] IN (164,166,168)
),

CTE_RESULTADO_ECOMAMA
AS
(
SELECT DISTINCT NTC.IPCODPACI, NT.NOMBRE, NTC.NUMINGRES, NTC.FECHACREACION, NTC.CODUSUARI, NTD.IDGRUPO, NTD.IDNTVARIABLE, VARI.VARIABLE,NTD.VALOR

FROM NTADMINISTRATIVAS NT
INNER JOIN NTNOTASADMINISTRATIVASC NTC ON NTC.IDNOTAADMINISTRATIVA=NT.ID
INNER JOIN NTNOTASADMINISTRATIVASD NTD ON NTD.IDNTNOTASADMINISTRATIVASC=NTC.ID
INNER JOIN NTVARIABLES VARI ON VARI.ID=NTD.IDNTVARIABLE



WHERE NTC.IDNOTAADMINISTRATIVA='20' AND IDNTVARIABLE=74
),

CTE_RESULTADO_EXAMEN_MAMA
AS
(
SELECT DISTINCT NTC.IPCODPACI, NT.NOMBRE, NTC.NUMINGRES, NTC.FECHACREACION, NTC.CODUSUARI, NTD.IDGRUPO, NTD.IDNTVARIABLE, VARI.VARIABLE,NTD.VALOR

FROM NTADMINISTRATIVAS NT
INNER JOIN NTNOTASADMINISTRATIVASC NTC ON NTC.IDNOTAADMINISTRATIVA=NT.ID
INNER JOIN NTNOTASADMINISTRATIVASD NTD ON NTD.IDNTNOTASADMINISTRATIVASC=NTC.ID
INNER JOIN NTVARIABLES VARI ON VARI.ID=NTD.IDNTVARIABLE



WHERE NTC.IDNOTAADMINISTRATIVA='21' AND IDNTVARIABLE=79
),

CTE_COLPOSCOPIA
AS
(
SELECT DISTINCT ROW_NUMBER () OVER (PARTITION BY IPCODPACI ORDER BY FECHACREACION DESC) NUMERO,  NTC.IPCODPACI, NT.NOMBRE, NTC.NUMINGRES, NTC.FECHACREACION, NTC.CODUSUARI, NTD.IDGRUPO, NTD.IDNTVARIABLE, VARI.VARIABLE,NTD.VALOR

FROM NTADMINISTRATIVAS NT
INNER JOIN NTNOTASADMINISTRATIVASC NTC ON NTC.IDNOTAADMINISTRATIVA=NT.ID
INNER JOIN NTNOTASADMINISTRATIVASD NTD ON NTD.IDNTNOTASADMINISTRATIVASC=NTC.ID
INNER JOIN NTVARIABLES VARI ON VARI.ID=NTD.IDNTVARIABLE



WHERE NTC.IDNOTAADMINISTRATIVA IN(18) AND IDNTVARIABLE=55
),

CTE_RIESGO_CARDIOVASCULAR
AS
(
SELECT*FROM [Report].[TablaExamenFisico]  WHERE [ID_VARIABLE] IN (141)

),

CTE_ALIMENTACION_SALUDABLE
AS
(
Select ESC.NUMEFOLIO, ESC.NUMINGRES, ESC.IPCODPACI, ITEM.IDHCESCALAS, ITEM.TAGPREGUNTA, ITEM.VALORITEMSELECCIONADO


from HCESCALAS ESC
INNER JOIN HCESCALASRESULTITEMS ITEM ON ITEM.IDHCESCALAS=ESC.ID


WHERE TIPOESCALA=8 AND ITEM.TAGPREGUNTA='005'
),

CTE_ASESORIA_VIH2
AS
(
SELECT*FROM [Report].[TablaRevisionXSistema] WHERE [idrsvariable] IN (234)

),

CTE_SEDENTARISMO
AS
(
SELECT*FROM ANTVALORES WHERE IDANTVARIABLE IN (449)
),

CTE_FECHA_BX_PROSTATA
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (291)

),

CTE_RESULTADO_BX_PROSTATA
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (292)

),

CTE_RESULTADO_EXAMEN_CLINICO_MAMA
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (286)
),

CTE_RESULTADO_EMBARAZO
AS
(
SELECT*FROM [Report].[TablaExamenFisico] WHERE [ID_VARIABLE] IN (289)
),

CTE_TEST_AUTONOMIA
AS
(
SELECT*FROM [Report].[TablaRevisionXSistema] WHERE [idrsvariable] IN (236)

),

CTE_TEST_SSR
AS
(
SELECT*FROM [Report].[TablaRevisionXSistema] WHERE [idrsvariable] IN (239)
),

CTE_TEST_IDENTIDAD
AS
(
SELECT*FROM [Report].[TablaRevisionXSistema] WHERE [idrsvariable] IN (241)
)

SELECT 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 CARE.NAME 'GRUPO DE ATENCION',HA.NAME 'EAPB',
 CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' 
				    WHEN '2' THEN 'CE'
				    WHEN '3' THEN 'TI'
				    WHEN '4' THEN 'RC'	
				    WHEN '5' THEN 'PA'	
				    WHEN '6' THEN 'AS'
				    WHEN '7' THEN 'MS'
				    WHEN '8' THEN 'NU'
				    WHEN '9' THEN 'CN'
				    WHEN '10' THEN 'CD'	
				    WHEN '11' THEN 'SC' 
				    WHEN '12' THEN 'PE'
				    WHEN '13' THEN 'PT'
				    WHEN '14' THEN 'DE' ELSE 'N/A'END AS 'TIPO DOCUMENTO',
POB.IPCODPACI 'ID PACIENTE',PAC.IPNOMCOMP 'NOMBRE PACIENTE',CAST (PAC.IPFECNACI AS DATE) 'FECHA DE NACIMIENTO',
FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS 'EDAD (AÑOS)',
CASE WHEN PAC.IPSEXOPAC=1 THEN 'MASCULINO' ELSE 'FEMENINO' END 'SEXO PACIENTE',POB.FECHISPAC 'FECHA ATENCION', CASE WHEN MODE.DESCRIPCION IS NOT NULL THEN MODE.DESCRIPCION ELSE 'Consulta Externa' END  'TIPO DE ATENCION', 
CASE WHEN PAC.IPSEXOPAC=1 THEN '1845-01-01' ELSE 
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) <10 OR FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>59 THEN '1845-01-01' ELSE 
CASE WHEN MODE.DESCRIPCION='Atencion Preconcepcional' THEN CAST(POB.FECHISPAC AS DATE) ELSE '1800-01-01' END END END 'ATENCION PRECONCEPCIONAL',
'Parametrizar educacion familiar en HCL' 'EDUCACION_FAMILIAR',
CASE WHEN GRU.ServiceDate IS NOT NULL THEN CAST(GRU.ServiceDate AS DATE) ELSE '1800-01-01' END 'EDUCACION_GRUPAL',
CASE WHEN IND.ServiceDate IS NOT NULL THEN CAST(IND.ServiceDate AS DATE) ELSE '1800-01-01' END 'EDUCACION_INDIVIDUAL' ,
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)< 10 THEN '1845-01-01' ELSE  CASE WHEN VIH2.VALOR IS NULL THEN '1800-01-01' ELSE CASE WHEN VIH2.VALOR=1 THEN CAST(POB.FECHISPAC AS DATE) END END END 'PRE_TEST_ELISA', 
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)< 10 THEN '1845-01-01' ELSE  CASE WHEN VIH2.VALOR IS NULL THEN '1800-01-01' ELSE CASE WHEN VIH2.VALOR=2 THEN CAST(POB.FECHISPAC AS DATE) END END END 'POS_TEST_ELISA',
CASE WHEN SAL.VALORITEMSELECCIONADO IS NULL THEN 'NO EVALUADO' ELSE CASE WHEN SAL.VALORITEMSELECCIONADO='0' THEN '1' ELSE '2' END END 'ALIMENTACION SALUDABLE',  CASE WHEN ALC.VALOR IS NOT NULL THEN '1' ELSE '2' END 'CONSUMO ALCOCHOL', 
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>= 6 THEN 'NO APLICA' ELSE 
CASE WHEN LAC.VALOR IS NOT NULL THEN LAC.VALOR  ELSE 'NO EVALUADO' END END  'EDAD LACTANCIA EXLUSIVA', 
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)< 5 THEN 'No aplica' ELSE  CASE WHEN SED.VALOR IS NULL THEN 'No evaluado' ELSE CASE WHEN SED.VALOR=1 THEN '1' ELSE '2' END END END 'SEDENTARISMO',
CASE WHEN PAC.IPSEXOPAC=1 THEN 'NO APICA' ELSE CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)< 45 THEN 'NO APLICA' ELSE
CASE WHEN PROS.VALOR IS NOT NULL THEN '1' ELSE '2' END END END 'FACTOR_TIESGO_CAPPRÓSTATA', CASE WHEN PAR.[CANTIDAD] IS NULL THEN 0 ELSE PAR.[CANTIDAD] END 'ANTIPARASITARIO',
CASE WHEN MIC.[CANTIDAD] IS NULL THEN 0 ELSE MIC.[CANTIDAD] END 'MICRONUTRIENTES_POLVO', CASE WHEN VIT.[CANTIDAD] IS NULL THEN 0 ELSE VIT.[CANTIDAD] END 'VITAMINA A',
CASE WHEN VIT.[CANTIDAD] IS NULL THEN 0 ELSE VIT.[CANTIDAD] END 'SULFATO FERROSO', CASE WHEN FER.[CANTIDAD] IS NULL THEN 0 ELSE FER.[CANTIDAD] END 'ACIDO FOLICO',
CASE WHEN CAL.[CANTIDAD] IS NULL THEN 0 ELSE CAL.[CANTIDAD] END 'CALCIO', CASE WHEN CON.[CANTIDAD] IS NULL THEN 0 ELSE CON.[CANTIDAD] END 'PRESERVATIVOS',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN '1845-01-01' ELSE
CASE WHEN URO.VALOR IS NOT NULL THEN URO.VALOR  ELSE '1800-01-01' END END 'UROANALISIS', 
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN '1845-01-01' ELSE
CASE WHEN COL.VALOR IS NOT NULL THEN COL.VALOR  ELSE '1800-01-01' END END 'FECHA COLESTEROL TOTAL',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN RESCOL.VALOR IS NOT NULL THEN RESCOL.VALOR  ELSE 'NO EVALUADO' END END 'RESULTADO COLESTEROL TOTAL',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN '1845-01-01' ELSE
CASE WHEN FECHDL.VALOR IS NOT NULL THEN FECHDL.VALOR  ELSE '1800-01-01' END END 'FECHA HDL',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN RESHDL.VALOR IS NOT NULL THEN RESHDL.VALOR  ELSE 'NO EVALUADO' END END 'RESULTADO HDL',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN '1845-01-01' ELSE
CASE WHEN FECLDL.VALOR IS NOT NULL THEN FECLDL.VALOR  ELSE '1800-01-01' END END 'FECHA LDL',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN RESLDL.VALOR IS NOT NULL THEN RESLDL.VALOR  ELSE 'NO EVALUADO' END END 'RESULTADO LDL',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN '1845-01-01' ELSE
CASE WHEN FECCREA.VALOR IS NOT NULL THEN FECCREA.VALOR  ELSE '1800-01-01' END END 'FECHA CREATININA',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN RESCREA.VALOR IS NOT NULL THEN RESCREA.VALOR  ELSE 'NO EVALUADO' END END 'RESULTADO CREATININA',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN '1845-01-01' ELSE
CASE WHEN FECTRIGLI.VALOR IS NOT NULL THEN FECTRIGLI.VALOR  ELSE '1800-01-01' END END 'FECHA TRIGLICERIDOS',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN RESTRIGLI.VALOR IS NOT NULL THEN RESTRIGLI.VALOR  ELSE 'NO EVALUADO' END END 'RESULTADO TRIGLICERIDOS',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN '1845-01-01' ELSE
CASE WHEN FECGLI.VALOR IS NOT NULL THEN FECGLI.VALOR  ELSE '1800-01-01' END END 'FECHA GLICEMIA',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN RESGLI.VALOR IS NOT NULL THEN RESGLI.VALOR  ELSE 'NO EVALUADO' END END 'RESULTADO GLICEMIA',
CASE WHEN PAC.IPSEXOPAC=1 THEN '1845-01-01' ELSE
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<10 THEN '1845-01-01' ELSE
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>17 THEN '1845-01-01' ELSE
CASE WHEN FECHEMA.VALOR IS NOT NULL THEN FECHEMA.VALOR  ELSE '1800-01-01' END END END END 'FECHA HEMATOCRITO',
CASE WHEN PAC.IPSEXOPAC=1 THEN '1845-01-01' ELSE
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<10 THEN 'NO APLICA' ELSE
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>17 THEN 'NO APLICA' ELSE
CASE WHEN RESHEMA.VALOR IS NOT NULL THEN RESHEMA.VALOR  ELSE 'NO EVALUADO' END END END END 'RESULTADO HEMATOCRITO',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<29 THEN '1845-01-01' ELSE
CASE WHEN PROST.VALOR IS NULL THEN '1800-01-01' ELSE CAST (PROST.VALOR AS DATE) END END 'FECHA_BIOPSIA_PROSTATA', 
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<29 THEN 'NO APLICA' ELSE
CASE WHEN BXPROS.[valor] IS NULL THEN 'No Evaluado' ELSE CAST(BXPROS.[valor] AS CHAR) END END 'RESULTADO_BIOPSIA_PROSTATA',
CASE WHEN PAC.IPSEXOPAC=1 THEN  'No aplica' ELSE CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=10 AND ECOMAMA.VALOR IS NULL THEN
'No Evaluado' ELSE ECOMAMA.VALOR END END 'ECO_MAMA',
CASE WHEN PAC.IPSEXOPAC=1 THEN  'No aplica' ELSE CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=40 AND EXAMAMA.VALOR IS NULL THEN
'No Evaluado' ELSE CASE WHEN EXAMAMA.VALOR IS NOT NULL THEN EXAMAMA.[valor] ELSE CAST(EXMAMA.[valor] AS VARCHAR)  END END END 'EXAMEN_CLINICO_MAMA',CASE WHEN FIS.NEOPERABD IS NULL THEN '0' ELSE FIS.NEOPERABD END 'PERIMETRO ABDOMINAL',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=6 THEN '0' ELSE CASE WHEN FIS.PB IS NULL THEN '0' ELSE FIS.PB END END 'PERIMETRO BRAQUIAL',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=6 THEN '0' ELSE CASE WHEN FIS.NEOPERCEF IS NULL
THEN '0' ELSE FIS.NEOPERCEF END END 'PERIMETRO CEFALICO', CASE WHEN DATEDIFF (DAY,PAC.IPFECNACI,POB.FECHISPAC)>=29 THEN '0' ELSE CASE WHEN FIS.REGSO2PAC IS NULL THEN '0' ELSE FIS.REGSO2PAC END END 'TAMIZAJE_OXIMETRIA',
CASE WHEN FIS.TENARTDIA IS NOT NULL THEN FIS.TENARTDIA ELSE '0' END 'TA_DIASTOLICA', CASE WHEN FIS.TENARTSIS IS NOT NULL THEN FIS.TENARTSIS ELSE '0' END 'TA_SISTOLICA', CASE WHEN DIAGRA.TIPODIAGRAMA=1 AND DIAGRA.FECHACREACION IS NOT NULL THEN  CAST(DIAGRA.FECHACREACION AS DATE) ELSE '1800-01-01' END 'ECOMAPA',
CASE WHEN DIAGRA.TIPODIAGRAMA=2 AND DIAGRA.FECHACREACION IS NOT NULL THEN  CAST(DIAGRA.FECHACREACION AS DATE) ELSE '1800-01-01' END 'FAMILIOGRAMA',
CASE WHEN PAC.IPSEXOPAC=1 THEN 'No aplica' ELSE CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<10 THEN 'No aplica' ELSE CAST(GES.[valor] AS VARCHAR) END END 'PRUEBA_EMBARAZO',
CASE WHEN ESC2.RESULTADO BETWEEN '13' AND '16' THEN '1'
	 WHEN ESC2.RESULTADO BETWEEN '10' AND '12' THEN '2'
	 WHEN ESC2.RESULTADO <= '9' THEN '3'
	 WHEN ESC2.RESULTADO BETWEEN '17' AND '20' THEN '4'
	 ELSE 'NO EVALUADO' END 'TEST_APGAR_FAMILIAR',
CASE WHEN ESC60.RESULTADO <=3 THEN '5'
	 WHEN ESC60.RESULTADO BETWEEN '4' AND '26' THEN '6'
	 WHEN ESC60.RESULTADO >= '27' THEN '4'
	 ELSE 'NO EVALUADO' END 'TEST_ASSIST',
CASE WHEN ESC54.RESULTADO <=7 THEN '5'
	 WHEN ESC54.RESULTADO BETWEEN '8' AND '15' THEN '6'
	 WHEN ESC54.RESULTADO BETWEEN '16' AND '19' THEN '3'
	 WHEN ESC54.RESULTADO >= '20' THEN '4'
	 ELSE 'NO EVALUADO' END 'TEST_AUDIT',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN AUT.VALOR IS NULL THEN '1800-01-01' ELSE AUT.VALOR END END 'TEST AUTONOMIA',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<60 THEN 'NO APLICA'
	 WHEN ESC35.RESULTADO BETWEEN '96' AND '100' THEN '5'
	 WHEN ESC35.RESULTADO BETWEEN '91' AND '95' THEN '4'
	 WHEN ESC35.RESULTADO BETWEEN '60' AND '90' THEN '3'
	 WHEN ESC35.RESULTADO BETWEEN '16' AND '59' THEN '3'
	 WHEN ESC35.RESULTADO <= '15' THEN '1'
	 ELSE 'NO EVALUADO' END 'TEST_BARTHEL',

CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN SSR.VALOR IS NULL THEN '1800-01-01' ELSE SSR.VALOR END END 'TEST_DERECHOS_SSR',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<60 THEN 'NO APLICA'
	 WHEN ESC19.RESULTADO <'10' THEN '2' 
	 WHEN ESC19.RESULTADO >='10' THEN '1'
	 WHEN ESC19.RESULTADO IS NULL THEN 'NO EVALUADO' END 'TEST_EPOC',

CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'No Aplica' ELSE
CASE WHEN RCV.VALOR IS NULL THEN 'No Evaluado' ELSE
CASE WHEN RCV.VALOR ='001' THEN '5'  
	 WHEN RCV.VALOR ='002' THEN '6' 
	 WHEN RCV.VALOR ='003' THEN '4' 
	 WHEN RCV.VALOR ='004' THEN '3' 
	 ELSE 'Extremadamente Alto' END END END 'TEST_ESTRATIFICACION_OMS_(CARDIOVASCULAR)',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA'
	 WHEN ESC8.RESULTADO BETWEEN '0' AND '7' THEN '5' 
	 WHEN ESC8.RESULTADO BETWEEN '8' AND '11' THEN '6' 
	 WHEN ESC8.RESULTADO >'11' THEN ''
	 WHEN ESC8.RESULTADO IS NULL THEN 'NO EVALUADO' END 'TEST_FINDRISK_(METABOLICO)',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA'
	 WHEN ESC6.RESULTADO <'10' THEN '5' 
	 WHEN ESC6.RESULTADO BETWEEN '10' AND '20' THEN '6'
	 WHEN ESC6.RESULTADO >'20' THEN '4'
	 WHEN ESC6.RESULTADO IS NULL THEN 'NO EVALUADO' END 'TEST_FRAMINGHAM_(CARDIOVASCULAR)',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN IDE.VALOR IS NULL THEN '1800-01-01' ELSE IDE.VALOR END END 'TEST_IDENTIDAD',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<60 THEN 'NO APLICA'
	 WHEN ESC56.RESULTADO IS NULL THEN 'NO EVALUADO'
	 WHEN ESC56.RESULTADO ='1' THEN '1' 
	 WHEN ESC56.RESULTADO BETWEEN '6' AND '7' THEN '4'
	 WHEN ESC56.RESULTADO BETWEEN '4' AND '5' THEN '3'
	 WHEN ESC56.RESULTADO BETWEEN '2' AND '3' THEN '2'
	 WHEN ESC56.RESULTADO >'8' THEN '5' ELSE 'NO EVALUADO'
	 END 'TEST_LAWTON_BRODY_(DEPENDENCIA)',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<60 THEN 'NO APLICA'
	 WHEN ESC55.RESULTADO ='0' THEN '3' 
	 WHEN ESC55.RESULTADO BETWEEN '1' AND '2' THEN '1'
	 WHEN ESC55.RESULTADO BETWEEN '3' AND '5' THEN '2'
	 WHEN ESC55.RESULTADO IS NULL THEN 'NO EVALUADO' END 'TEST_LINDA_FRIED_(FRAGILIDAD)',
CASE WHEN DATEDIFF(MONTH, PAC.IPFECNACI,POB.FECHISPAC) <16 THEN 'NO APLICA'
	 WHEN DATEDIFF(MONTH, PAC.IPFECNACI,POB.FECHISPAC) >30 THEN 'NO APLICA'	
	 WHEN ESC52.RESULTADO BETWEEN '3' AND '7' THEN '6'
	 WHEN ESC52.RESULTADO BETWEEN '0' AND '2' THEN '5'
	 WHEN ESC52.RESULTADO >='8' THEN '4'
	 WHEN ESC52.RESULTADO IS NULL THEN 'NO EVALUADO' END 'TEST_M_CHAT_(AUTISMO)',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<5 THEN 'NO APLICA'
	 WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>15 THEN 'NO APLICA'
	 WHEN ESC43.RESULTADO ='0' THEN 'Negativo'
	 WHEN ESC43.RESULTADO = '1'THEN 'Positivo'
	 WHEN ESC43.RESULTADO IS NULL THEN 'NO EVALUADO' END 'TEST_RQC_S_MENTAL(5-15)',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>16 THEN 'NO APLICA'
	 WHEN ESC51.RESULTADO ='0' THEN 'Negativo'
	 WHEN ESC51.RESULTADO = '1'THEN 'Positivo'
	 WHEN ESC51.RESULTADO IS NULL THEN 'NO EVALUADO' END 'TEST_SQR_S_MENTAL(16+)',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<13 THEN 'NO APLICA'
	 WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>17 THEN 'NO APLICA'	
	 WHEN TANNER.RESULTADO ='1' THEN '1-Estadio 1'
	 WHEN TANNER.RESULTADO ='2' THEN '2-Estadio 2'
	 WHEN TANNER.RESULTADO ='3' THEN '3-Estadio 3'
	 WHEN TANNER.RESULTADO ='4' THEN '4-Estadio 4'
	 WHEN TANNER.RESULTADO ='5' THEN '5-Estadio 5'
	 WHEN TANNER.RESULTADO IS NULL THEN 'NO EVALUADO' END 'TEST_TANNER',
CASE WHEN PAC.IPSEXOPAC=1 THEN  'No aplica' ELSE CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<10 THEN 'No aplica' ELSE
CASE WHEN COLP.VALOR IS NULL THEN 'NO EVALUADO' ELSE CASE WHEN COLP.VALOR='001' THEN '1' ELSE CASE WHEN COLP.VALOR='002' THEN '2' END END END END END  'COLPOSCOPIA',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<6 THEN 'NO APLICA' ELSE
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>12 THEN 'NO APLICA'ELSE
CASE WHEN ESC20.RESULTADO BETWEEN '0' AND '19' THEN 'Discapacidad Intelectual Profunda'
	 WHEN ESC20.RESULTADO BETWEEN '20' AND '49' THEN 'Discapacidad Intelectual Severa'
	 WHEN ESC20.RESULTADO BETWEEN '50' AND '69' THEN 'Discapacidad Intelectual Moderada'
	 WHEN ESC20.RESULTADO BETWEEN '70' AND '79' THEN 'Discapacidad Intelectual Leve'
	 WHEN ESC20.RESULTADO BETWEEN '80' AND '89' THEN 'Limitrofe'
	 WHEN ESC20.RESULTADO BETWEEN '90' AND '109' THEN 'Normal o Media'
	 WHEN ESC20.RESULTADO BETWEEN '110' AND '119' THEN 'Superior'
	 WHEN ESC20.RESULTADO BETWEEN '120' AND '139' THEN 'Muy Superior'
	 WHEN ESC20.RESULTADO = '140' THEN 'Casi Genialidad'
	 WHEN ESC20.RESULTADO = '150' THEN 'Genialidad'
	 WHEN ESC20.RESULTADO IS NULL THEN 'NO EVALUADO' END END END 'TEST_GOODENOUGH',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN ESC53.RESULTADO = '0' THEN 'Sin Riesgo'
	 WHEN ESC53.RESULTADO = '1' OR ESC53.RESULTADO = '2' THEN 'Riesgo de Depresion'
	 WHEN ESC53.RESULTADO IS NULL THEN 'NO EVALUADO' END END 'TEST_WHOOLEY' ,
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN ESC57.RESULTADO BETWEEN '0' AND '10' THEN 'Sin Riesgo de Ansiedad'
	 WHEN ESC57.RESULTADO > '10' THEN 'Riesgo de Ansiedad'
	 WHEN ESC57.RESULTADO IS NULL THEN 'NO EVALUADO' END END 'TEST_GAD',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<18 THEN 'NO APLICA' ELSE
CASE WHEN ESC42.RESULTADO BETWEEN '0' AND '46' THEN 'Ausencia de Sobrecarga'
	 WHEN ESC42.RESULTADO BETWEEN '47' AND '55' THEN 'Sobrecarga Ligera'
	 WHEN ESC42.RESULTADO >= '56' THEN 'Sobrecarga Intensa'
	 WHEN ESC42.RESULTADO IS NULL THEN 'NO EVALUADO' END END 'TEST_ZARIT',
CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), POB.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<60 THEN 'NO APLICA' ELSE
CASE WHEN ESC9.RESULTADO BETWEEN '0' AND '13' THEN 'Deterioro Grave'
	 WHEN ESC9.RESULTADO BETWEEN '14' AND '18' THEN 'Deterioro Moderado'
	 WHEN ESC9.RESULTADO BETWEEN '19' AND '23' THEN 'Deterioro Leve'
	 WHEN ESC9.RESULTADO > '23' THEN 'Normal'
	 WHEN ESC9.RESULTADO IS NULL THEN 'NO EVALUADO' END END 'TEST_MINIMENTAL',
1 as 'CANTIDAD',
MONTH(POB.FECHISPAC) AS 'MES BUSQUEDA',
CONCAT(FORMAT(MONTH(POB.FECHISPAC), '00') ,' - ', 
	   CASE MONTH(POB.FECHISPAC) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) 'MES NOMBRE BUSQUEDA',
YEAR(POB.FECHISPAC) AS 'AÑO BUSQUEDA',
CAST(POB.FECHISPAC AS date) AS 'FECHA BUSQUEDA',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 CTE_POBLACION POB
 INNER JOIN INPACIENT PAC ON PAC.IPCODPACI=POB.IPCODPACI
 INNER JOIN ADINGRESO ING ON ING.NUMINGRES=POB.NUMINGRES
 INNER JOIN CONTRACT.CAREGROUP CARE ON CARE.ID=ING.GENCAREGROUP
 INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.ID=ING.GENCONENTITY
 LEFT JOIN PRMODELOHC MODE ON MODE.ID=POB.IDMODELOHC
 LEFT JOIN CTE_EDUCACIONGRUPAL GRU ON GRU.PatientCode=POB.IPCODPACI AND MONTH(GRU.ServiceDate)=MONTH(POB.FECHISPAC)
 LEFT JOIN CTE_EDUCACIONINDIVIDUAL IND ON IND.PatientCode=POB.IPCODPACI AND MONTH(IND.ServiceDate)=MONTH(POB.FECHISPAC)
 LEFT JOIN CTE_ANTECEDENTES_ALCOCHOL ALC ON ALC.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_EDAD_LACTANCIA LAC ON LAC.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RIESGO_CAPROSTATA PROS ON PROS.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_DISPENSACIONES_ANTIPARASITARIOS PAR ON PAR.[ID TERCERO/PACIENTE]=POB.IPCODPACI AND MONTH(PAR.[FECHA DISPENSACION])=MONTH(POB.FECHISPAC)
 LEFT JOIN CTE_DISPENSACIONES_MICRONUTRIENTES MIC ON MIC.[ID TERCERO/PACIENTE]=POB.IPCODPACI AND MONTH(MIC.[FECHA DISPENSACION])=MONTH(POB.FECHISPAC)
 LEFT JOIN CTE_DISPENSACIONES_VITAMINA_A VIT ON VIT.[ID TERCERO/PACIENTE]=POB.IPCODPACI AND MONTH(VIT.[FECHA DISPENSACION])=MONTH(POB.FECHISPAC)
 LEFT JOIN CTE_DISPENSACIONES_HIERRO HIE ON HIE.[ID TERCERO/PACIENTE]=POB.IPCODPACI AND MONTH(HIE.[FECHA DISPENSACION])=MONTH(POB.FECHISPAC)
 LEFT JOIN CTE_DISPENSACIONES_FERROSO FER ON FER.[ID TERCERO/PACIENTE]=POB.IPCODPACI AND MONTH(FER.[FECHA DISPENSACION])=MONTH(POB.FECHISPAC)
 LEFT JOIN CTE_DISPENSACIONES_CALCIO CAL ON CAL.[ID TERCERO/PACIENTE]=POB.IPCODPACI AND MONTH(CAL.[FECHA DISPENSACION])=MONTH(POB.FECHISPAC)
 LEFT JOIN CTE_DISPENSACION_PRESERVATIVOS CON ON CON.[ID TERCERO/PACIENTE]=POB.IPCODPACI AND MONTH(CON.[FECHA DISPENSACION])=MONTH(POB.FECHISPAC)
 LEFT JOIN CTE_RIESGO_UROANALISIS URO ON URO.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_FECHA_COLESTEROLTOTAL COL ON COL.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RESULTADO_COLESTEROLTOTAL RESCOL ON RESCOL.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_FECHA_HDL FECHDL ON FECHDL.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RESULTADO_HDL RESHDL ON RESHDL.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_FECHA_LDL FECLDL ON FECLDL.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RESULTADO_LDL RESLDL ON RESLDL.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_FECHA_CREATININA FECCREA ON FECCREA.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RESULTADO_CREATININA RESCREA ON RESCREA.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_FECHA_TRIGLICERIDOS FECTRIGLI ON FECTRIGLI.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RESULTADO_TRIGLICERIDOS RESTRIGLI ON RESTRIGLI.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_FECHA_GLICEMIA FECGLI ON FECGLI.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RESULTADO_GLICEMIA RESGLI ON RESGLI.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_FECHA_HEMATOCRITO FECHEMA ON FECHEMA.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RESULTADO_HEMATOCRITO RESHEMA ON RESHEMA.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RESULTADO_ECOMAMA ECOMAMA ON ECOMAMA.IPCODPACI=POB.IPCODPACI
 LEFT JOIN CTE_RESULTADO_EXAMEN_MAMA EXAMAMA ON EXAMAMA.IPCODPACI=POB.IPCODPACI
 LEFT JOIN HCEXFISIC FIS ON FIS.IPCODPACI=POB.IPCODPACI AND FIS.NUMEFOLIO=POB.NUMEFOLIO
 LEFT JOIN HCDIAGRAMAS DIAGRA ON DIAGRA.NUMEFOLIO=POB.NUMEFOLIO AND DIAGRA.IPCODPACI=POB.IPCODPACI
 LEFT JOIN HCESCALAS ESC2 ON ESC2.TIPOESCALA=2 AND POB.NUMEFOLIO=ESC2.NUMEFOLIO AND POB.IPCODPACI=ESC2.IPCODPACI
 LEFT JOIN HCESCALAS ESC60 ON ESC60.TIPOESCALA=60 AND POB.NUMEFOLIO=ESC60.NUMEFOLIO AND POB.IPCODPACI=ESC60.IPCODPACI
 LEFT JOIN HCESCALAS ESC54 ON ESC54.TIPOESCALA=54 AND POB.NUMEFOLIO=ESC54.NUMEFOLIO AND POB.IPCODPACI=ESC54.IPCODPACI
 LEFT JOIN HCESCALAS ESC35 ON ESC35.TIPOESCALA=35 AND POB.NUMEFOLIO=ESC35.NUMEFOLIO AND POB.IPCODPACI=ESC35.IPCODPACI
 LEFT JOIN HCESCALAS ESC19 ON ESC19.TIPOESCALA=19 AND POB.NUMEFOLIO=ESC19.NUMEFOLIO AND POB.IPCODPACI=ESC19.IPCODPACI
 LEFT JOIN CTE_RIESGO_CARDIOVASCULAR RCV ON RCV.IDHCHISPACA=POB.ID
 LEFT JOIN HCESCALAS ESC6 ON ESC6.TIPOESCALA=6 AND POB.NUMEFOLIO=ESC6.NUMEFOLIO AND POB.IPCODPACI=ESC6.IPCODPACI
 LEFT JOIN HCESCALAS ESC8 ON ESC8.TIPOESCALA=8 AND POB.NUMEFOLIO=ESC8.NUMEFOLIO AND POB.IPCODPACI=ESC8.IPCODPACI
 LEFT JOIN HCESCALAS ESC56 ON ESC56.TIPOESCALA=56 AND POB.NUMEFOLIO=ESC56.NUMEFOLIO AND POB.IPCODPACI=ESC56.IPCODPACI
 LEFT JOIN HCESCALAS ESC55 ON ESC55.TIPOESCALA=55 AND POB.NUMEFOLIO=ESC55.NUMEFOLIO AND POB.IPCODPACI=ESC55.IPCODPACI
 LEFT JOIN HCESCALAS ESC52 ON ESC52.TIPOESCALA=52 AND POB.NUMEFOLIO=ESC52.NUMEFOLIO AND POB.IPCODPACI=ESC52.IPCODPACI
 LEFT JOIN HCESCALAS ESC43 ON ESC43.TIPOESCALA=43 AND POB.NUMEFOLIO=ESC43.NUMEFOLIO AND POB.IPCODPACI=ESC43.IPCODPACI
 LEFT JOIN HCESCALAS ESC51 ON ESC51.TIPOESCALA=51 AND POB.NUMEFOLIO=ESC51.NUMEFOLIO AND POB.IPCODPACI=ESC51.IPCODPACI
 LEFT JOIN HCESCALAS TANNER ON TANNER.TIPOESCALA IN (11,12,13,14) AND POB.NUMEFOLIO=TANNER.NUMEFOLIO AND POB.IPCODPACI=TANNER.IPCODPACI
 LEFT JOIN CTE_COLPOSCOPIA COLP ON COLP.IPCODPACI=POB.IPCODPACI AND COLP.NUMERO=1
 LEFT JOIN CTE_ALIMENTACION_SALUDABLE SAL ON SAL.NUMINGRES=POB.NUMINGRES 
 LEFT JOIN HCESCALAS ESC20 ON ESC20.TIPOESCALA=20 AND POB.NUMEFOLIO=ESC20.NUMEFOLIO AND POB.IPCODPACI=ESC20.IPCODPACI
 LEFT JOIN HCESCALAS ESC53 ON ESC53.TIPOESCALA=53 AND POB.NUMEFOLIO=ESC53.NUMEFOLIO AND POB.IPCODPACI=ESC53.IPCODPACI
 LEFT JOIN HCESCALAS ESC57 ON ESC57.TIPOESCALA=57 AND POB.NUMEFOLIO=ESC57.NUMEFOLIO AND POB.IPCODPACI=ESC57.IPCODPACI
 LEFT JOIN HCESCALAS ESC42 ON ESC42.TIPOESCALA=42 AND POB.NUMEFOLIO=ESC42.NUMEFOLIO AND POB.IPCODPACI=ESC42.IPCODPACI
 LEFT JOIN HCESCALAS ESC9 ON ESC9.TIPOESCALA=9 AND POB.NUMEFOLIO=ESC9.NUMEFOLIO AND POB.IPCODPACI=ESC9.IPCODPACI
 LEFT JOIN CTE_ASESORIA_VIH2 VIH2 ON VIH2.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_SEDENTARISMO SED ON SED.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_FECHA_BX_PROSTATA PROST ON PROST.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RESULTADO_BX_PROSTATA BXPROS ON BXPROS.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RESULTADO_EXAMEN_CLINICO_MAMA EXMAMA ON EXMAMA.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_RESULTADO_EMBARAZO GES ON GES.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_TEST_AUTONOMIA AUT ON AUT.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_TEST_SSR SSR ON SSR.IDHCHISPACA=POB.ID
 LEFT JOIN CTE_TEST_IDENTIDAD IDE ON IDE.IDHCHISPACA=POB.ID
--WHERE  POB.FECHISPAC BETWEEN @FechaInicial AND @FechaFinal AND POB.IPCODPACI= '1067917732' --'1234567' --'39150646' -- --    --'15242392'
GROUP BY 
 POB.FECHISPAC,IND.ServiceDate ,GRU.ServiceDate, PAC.IPTIPODOC, POB.IPCODPACI, PAC.IPNOMCOMP, PAC.IPFECNACI,MODE.DESCRIPCION, PAC.IPSEXOPAC, ALC.VALOR, LAC.VALOR, PROS.VALOR,
 PAR.[CANTIDAD], MIC.[CANTIDAD], VIT.[CANTIDAD], HIE.[CANTIDAD], FER.[CANTIDAD], CAL.[CANTIDAD], CON.[CANTIDAD], URO.VALOR, COL.VALOR, RESCOL.VALOR, FECHDL.VALOR,RESHDL.VALOR,
 FECLDL.VALOR,RESLDL.VALOR, FECCREA.VALOR, RESCREA.VALOR, FECTRIGLI.VALOR, RESTRIGLI.VALOR, FECGLI.VALOR, RESGLI.VALOR, FECHEMA.VALOR, RESHEMA.VALOR, ECOMAMA.VALOR, EXAMAMA.VALOR,FIS.NEOPERABD,
 FIS.PB, FIS.NEOPERCEF,FIS.REGSO2PAC, FIS.TENARTDIA, FIS.TENARTSIS, DIAGRA.FECHACREACION, DIAGRA.TIPODIAGRAMA, ESC2.RESULTADO, ESC60.RESULTADO, ESC54.RESULTADO, ESC35.RESULTADO,
 ESC19.RESULTADO, RCV.VALOR,ESC6.RESULTADO, ESC8.RESULTADO, ESC56.RESULTADO, ESC55.RESULTADO, ESC52.RESULTADO, ESC43.RESULTADO, ESC51.RESULTADO, TANNER.RESULTADO, COLP.VALOR, CARE.NAME, HA.NAME,
 SAL.VALORITEMSELECCIONADO, ESC20.RESULTADO,ESC53.RESULTADO, ESC57.RESULTADO, ESC42.RESULTADO, ESC9.RESULTADO, VIH2.VALOR, SED.VALOR, PROST.VALOR, BXPROS.[valor], EXMAMA.[valor],
 GES.[valor], AUT.VALOR, SSR.VALOR, IDE.VALOR
