-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_V2_FAC_REPORTE_VALORACIONES_POR_RECONOCER_HOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE VIEW [Report].[View_V2_FAC_REPORTE_VALORACIONES_POR_RECONOCER_HOS]
AS

WITH CTE_VALORACIONES_UNICAS
----CTE PARA IDENTIFICAR LOS INGRESOS UNICOS CON ESTANCIAS PENDIENTES DE LIQUIDAR HOSPITALARIAS
AS
(
 SELECT DISTINCT A.IPCODPACI ,A.NUMINGRES,ING.IESTADOIN ,P.IPNOMCOMP ,HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
     MIN(A.FECHISPAC ) 'FECHA REALIZADO MINIMA', MAX(A.FECHISPAC) 'FECHA REALIZADO MAXIMA',ESP.DESESPECI 'ESPECIALIDAD' 
 	FROM dbo.HCHISPACA A  
	INNER JOIN dbo.INPROFSAL B ON A.CODPROSAL=B.CODPROSAL 
	INNER JOIN dbo.INPACIENT P on a.IPCODPACI = P.IPCODPACI 
	INNER JOIN dbo.ADINGRESO ing on A.NUMINGRES = ing.NUMINGRES
	INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id 
	INNER JOIN DBO.INESPECIA AS ESP ON ESP.CODESPECI =A.CODESPTRA 
	LEFT JOIN Billing.AccountControlJustification acj WITH(NOLOCK) on A.ID=acj.EntityId and acj.EntityName='HCHISPACA' and acj.EntityTap='INDlcgValoraciones'
	LEFT JOIN Billing.BillingJustificationControl bjc WITH(NOLOCK) on acj.JustificationId= bjc.Id
	WHERE  ING.TIPOINGRE=2 and  ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER IS NULL AND A.GENCONEXT ='0'  and bjc.Code is null
	GROUP BY A.IPCODPACI ,A.NUMINGRES,ING.IESTADOIN ,P.IPNOMCOMP ,HA.Name, CG.Name,ING.IFECHAING,ESP.DESESPECI 
),
CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
AS
(
    SELECT EGR.IPCODPACI ,EGR.NUMINGRES,EGR.FECINIEST ,EGR.FECFINEST ,EGR.CODICAMAS,CAM.NUMCAMHOS ,FUN.UFUDESCRI  ,FUN.UFUTIPUNI  
	FROM CHREGESTA EGR with (nolock)
	INNER JOIN 
	(
	   SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR with (nolock)
	   INNER JOIN CTE_VALORACIONES_UNICAS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G  ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM with (nolock) ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),
CTE_EGRESO_CAMA
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO  
FROM CHREGEGRE EGR
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECEGRESO) EGRESO 
 FROM CHREGEGRE EGR with (nolock) 
 INNER JOIN CTE_VALORACIONES_UNICAS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.EGRESO =EGR.FECEGRESO 
),
CTE_ORDENES_CON_VALORACIONES_CARGADAS
---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
AS
( 
SELECT RC.AdmissionNumber,G.CANTIDAD  FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN
(
SELECT RC.AdmissionNumber ,SUM(SOD.InvoicedQuantity) CANTIDAD   
FROM Billing .RevenueControlDetail AS RCD WITH (NOLOCK)
INNER JOIN BILLING.REVENUECONTROL AS RC WITH (NOLOCK) ON RCD.REVENUECONTROLID = RC.ID
INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD WITH (NOLOCK) ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2','3')
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD WITH (NOLOCK) ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN CTE_VALORACIONES_UNICAS AS UNI with (nolock) ON UNI.NUMINGRES =RC.AdmissionNumber  
INNER JOIN Contract .CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id =SOD.CUPSEntityId AND CUPS.ServiceType IN (6)--CUPS.BillingGroupId =2
INNER JOIN Contract .IPSService AS IPS WITH (NOLOCK) ON IPS.Id =SOD.IPSServiceId
GROUP BY RC.AdmissionNumber 
) AS G ON G.AdmissionNumber =RC.AdmissionNumber
)

SELECT ING.NUMINGRES,ing.IESTADOIN,ING.[FECHA INGRESO] ,ING.ENTIDAD ,ING.[GRUPO ATENCION]   ,ING.IPCODPACI ,ING.IPNOMCOMP ,'' CODSERIPS ,ING.ESPECIALIDAD  DESSERIPS,'0' [CANTIDAD ORDENADA]  ,'0' CANSERIPS,CAM.UFUDESCRI  ,
CAM.NUMCAMHOS,EGR.FECEGRESO,'' 'CUPS CARGADO','' 'CANTIDAD CARGADA' ,ING.[FECHA REALIZADO MINIMA] ,ING.[FECHA REALIZADO MAXIMA]   
FROM CTE_VALORACIONES_UNICAS ING 
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM with (nolock) ON ING.NUMINGRES =CAM.NUMINGRES
LEFT JOIN CTE_EGRESO_CAMA EGR with (nolock) ON EGR.NUMINGRES =ING.NUMINGRES
LEFT JOIN CTE_ORDENES_CON_VALORACIONES_CARGADAS CAR with (nolock) ON CAR.AdmissionNumber =ING.NUMINGRES 
WHERE CAR.CANTIDAD IS NULL AND CAM.UFUTIPUNI NOT IN ('1','19') --AND CAM.NUMCAMHOS NOT LIKE 'U%' AND CAM.NUMCAMHOS NOT LIKE 'O%'
--AND CAM.NUMCAMHOS NOT LIKE 'SAL%' AND CAM.NUMCAMHOS NOT LIKE 'PRE%' AND CAM.NUMCAMHOS NOT LIKE 'REC%' AND CAM.NUMCAMHOS NOT LIKE 'SRE%'
