-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewSeguimientoIngresos
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[ViewSeguimientoIngresos] AS
SELECT  
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 CASE PAC.IPTIPODOC 	
  WHEN '1' THEN 'CC' WHEN '2' THEN 'CE' WHEN '3' THEN 'TI' WHEN '4' THEN 'RC'	WHEN '5' THEN 'PA'	WHEN '6' THEN 'AS'
 WHEN '7' THEN 'MS'	WHEN '8' THEN 'NU'	WHEN '9' THEN 'CN'	WHEN '10' THEN 'CD'	WHEN '11' THEN 'SC' WHEN '12' THEN 'PE' 
 ELSE 'N/A'END 'TIPO DOCUMENTO',ING.IPCODPACI 'ID PACIENTE' ,PAC.IPNOMCOMP 'NOMBRE PACIENTE',PAC.IPTELEFON 'TEL. FIJO', PAC.IPTELMOVI 'TEL. CELULAR',
 PAC.CORELEPAC 'CORREO ELECTRONICO',
 PAC.CODIGONIT 'NIT',GRU.NAME 'GRUPO DE ATENCION',HA.NAME 'ENTIDAD EAPB',
 ING.NUMINGRES,CASE WHEN ING.TIPOINGRE='1' THEN 'Ambulatorio' ELSE 'Hospitalario' END 'TIPO DE INGRESO', ING.UFUCODIGO 'COD. UF INGRESO',
 FUN1.UFUDESCRI 'UNIDAD FUNCIONAL DE INGRESO',ING.IFECHAING 'FECHA DE INGRESO', 
 ING.UFUACTPAC 'COD UF EGRESO',FUN2.UFUDESCRI 'UNIDAD FUNCIONAL DE EGRESO',ING.FECREGCRE 'FECHA DE EGRESO',
 ING.IFECHAING 'FECHA DE BUSQUEDA',
 1 as 'CANTIDAD',
 CAST(ING.IFECHAING AS date) AS 'FECHA BUSQUEDA',
 YEAR(ING.IFECHAING) AS 'AÑO BUSQUEDA',
 MONTH(ING.IFECHAING) AS 'MES BUSQUEDA',
 CONCAT(FORMAT(MONTH(ING.IFECHAING), '00') ,' - ', 
        CASE MONTH(ING.IFECHAING) 
	     WHEN 1 THEN 'ENERO'
   	     WHEN 2 THEN 'FEBRERO'
	     WHEN 3 THEN 'MARZO'
	     WHEN 4 THEN 'ABRIL'
	     WHEN 5 THEN 'MAYO'
	     WHEN 6 THEN 'JUNIO'
	     WHEN 7 THEN 'JULIO'
	     WHEN 8 THEN 'AGOSTO'
	     WHEN 9 THEN 'SEPTIEMBRE'
	     WHEN 10 THEN 'OCTUBRE'
	     WHEN 11 THEN 'NOVIEMBRE'
	     WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 ADINGRESO ING
 INNER JOIN INPACIENT PAC ON PAC.IPCODPACI= ING.IPCODPACI
 INNER JOIN INUNIFUNC FUN1 ON FUN1.UFUCODIGO=ING.UFUCODIGO
 INNER JOIN CONTRACT.CareGroup GRU ON GRU.ID=PAC.GENCAREGROUP
 INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.ID=PAC.GENCONENTITY
 LEFT JOIN INUNIFUNC FUN2 ON FUN2.UFUCODIGO=ING.UFUACTPAC
