-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewExamenFisico
-- Extracted by Fabric SQL Extractor SPN v3.9.0



/*******************************************************************************************************************
Nombre: [Report].[ViewExamenFisico]
Tipo:Vista
Observacion:Reporte de examen fisico normal sin histrorias clinicas parametrizables. 
Profesional: Nilsson Miguel Galindo Lopez
Fecha:
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico: Amira Gil Meneses
Fecha: 01-06-2023
Ovservaciones:Se ingresan el campo 'DOLOR' de la tabla dbo.HCEXFISIC al reporte.
-------------------------------------------------------------------------------------
Version 3
Persona que modifico: Nilsson Miguel Galindo Lopez 
Observacion:Se mejora la velocidad del la consulta en un 95%
Fecha:
-------------------------------------------------------------------------------------
Version 3
Persona que modifico: Nilsson Miguel Galindo Lopez
Observacion:
Fecha:
****************************************************************************************************************************/

CREATE view [Report].[ViewExamenFisico] as

WITH 
CTE_DIAP AS
(
SELECT 
DIA.NUMINGRES,DIA.CODDIAGNO,DG.NOMDIAGNO
FROM
DBO.INDIAGNOP DIA INNER JOIN
DBO.ADINGRESO ING ON DIA.NUMINGRES=ING.NUMINGRES AND ING.IFECHAING BETWEEN GETDATE() - 400 AND GETDATE() INNER JOIN
DBO.INDIAGNOS DG ON DIA.CODDIAGNO=DG.CODDIAGNO
WHERE CODDIAPRI=1
),
CTE_DIAGNOSTICOS AS
(
select 
ROW_NUMBER ( )   
OVER ( PARTITION BY DIA.NUMINGRES  order by DIA.CODDIAGNO,DIA.NUMINGRES) 'NUMERO',
DIA.NUMINGRES,
DIA.CODDIAGNO,
DG.NOMDIAGNO
from 
DBO.INDIAGNOP DIA INNER JOIN
DBO.ADINGRESO ING ON DIA.NUMINGRES=ING.NUMINGRES AND ING.IFECHAING BETWEEN GETDATE() - 400 AND GETDATE() INNER JOIN
DBO.INDIAGNOS DG ON DIA.CODDIAGNO=DG.CODDIAGNO
WHERE DIAESTADO=1 AND CODDIAPRI!=1
)

SELECT --TOP 100
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CEN.NOMCENATE AS [CENTRO DE ATENCION],
CASE pac.IPTIPODOC WHEN 1 THEN 'CC - CEDULA DE CIUDADANIA' 
				   WHEN 2 THEN 'CE - CEDULA DE EXTRANJERIA' 
				   WHEN 3 THEN 'TI - TARJETA DE IDENTIDAD' 
				   WHEN 4 THEN 'RC - REGISTRO CIVIL' 
				   WHEN 5 THEN 'PA - PASAPORTE' 
				   WHEN 6 THEN 'AS - ADULTO SIN IDENTIFICACION' 
				   WHEN 7 THEN 'MS - MENOR SIN IDENTIFICACION' 
				   WHEN 8 THEN 'NU - NUMERO UNICO DE IDENTIFICACIÒN' 
				   WHEN 9 THEN 'NV - CERTIFICADO NACIDO VIVO' 
				   WHEN 10 THEN 'CD - CARNET DIPLOMATICO' 
				   WHEN 11 THEN 'SC - SALVOCONDUCTO' 
				   WHEN 12 THEN 'PE - PERMISO ESPECIAL DE PERMANENCIA' 
				   WHEN 13 THEN 'PT - PERMISO TEMPORAL DE PERMANENCIA'
				   WHEN 14 THEN 'DE - DOCUMENTO EXTRANJERO'
				   WHEN 15 THEN 'SI - SIN IDENTIFICACION'
				   END [TIPO IDENTIFICACION],
pac.IPCODPACI AS IDENTIFICACION,
pac.IPNOMCOMP AS [NOMBRE PACIENTE],
pac.IPFECNACI AS [FECHA DE NACIMIENTO],
FLOOR((CAST(CONVERT(VARCHAR(8), ING.IFECHAING , 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS [EDAD],
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END AS SEXO,
PAC.IPTELEFON AS [TELEFONO],
PAC.IPTELMOVI AS [CELULAR],
EAPB.CODENTIDA AS [CODIGO EAPB],
EAPB.NOMENTIDA AS [NOMBRE EAPB],
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro' 
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado'
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [REGIMEN],
ing.NUMINGRES as INGRESO,
/*IN V3*/
FIS.NUMEFOLIO AS FOLIO,
CASE ING.TIPOINGRE WHEN 1 THEN 'Ambulatorio'
				   WHEN 2 THEN 'Hospitalario' END [TIPO DE INGRESO],/*FN V3*/
ING.IFECHAING AS [FECHA DE INGRESO],
FIS.NUMCONSEC AS [NUMERO DE REGISTRO],
fis.FECREGITE as [FECHA DE REGISTRO],
fis.TENARTSIS as [TENSION SISTOLICA],
fis.TENARTDIA as [TENSION ARTERIAL DIASTOLICA],
fis.TEMPERPAC as TEMPERATURA,
fis.FRECARPAC as [FRECUENCIA CARDIACA],
fis.FRERESPAC as [FRECUENCIA RESPIRATORIA],
fis.REGSO2PAC as [SATURACION OXIGENO],
fis.TALLAPACI as TALLA,
convert(bigint,fis.PESOPACIE) as [PESO Gr],
(convert(bigint,fis.PESOPACIE)/1000) as [PESO Kg],
/*IN V2*/FIS.DOLOR as [DOLOR],/*FN V2*/
DXP.CODDIAGNO+' - '+DXP.NOMDIAGNO AS [DX PRINCIPAL],
DX2.CODDIAGNO+' - '+DX2.NOMDIAGNO AS [DX 2],
DX3.CODDIAGNO+' - '+DX3.NOMDIAGNO AS [DX 3],
ESP.DESESPECI AS ESPECIALIDAD,
1 as 'CANTIDAD',
CAST(ING.IFECHAING AS date) AS 'FECHA BUSQUEDA',
YEAR(ING.IFECHAING) AS 'AÑO FECHA BUSQUEDA',
MONTH(ING.IFECHAING) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(ING.IFECHAING) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
  END AS 'MES NOMBRE FECHA BUSQUEDA', 
FORMAT(DAY(ING.IFECHAING), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(ING.IFECHAING), '00') ,' - ', 
	   CASE MONTH(ING.IFECHAING) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
--GETDATE() AS ULT_ACTUAL
from 
dbo.ADINGRESO ING inner join
DBO.INPACIENT PAC on ING.IPCODPACI=pac.IPCODPACI INNER JOIN
dbo.HCEXFISIC FIS ON ING.NUMINGRES=FIS.NUMINGRES AND FIS.NUMCONSEC=(SELECT MAX(F.NUMCONSEC) FROM dbo.HCEXFISIC F WHERE ING.NUMINGRES=F.NUMINGRES) INNER JOIN
dbo.INPROFSAL PRO ON FIS.CODPROSAL=PRO.CODPROSAL INNER JOIN
DBO.ADCENATEN CEN ON ING.CODCENATE=CEN.CODCENATE INNER JOIN
DBO.INENTIDAD AS EAPB ON PAC.CODENTIDA=EAPB.CODENTIDA INNER JOIN
dbo.INESPECIA ESP ON PRO.CODESPEC1=ESP.CODESPECI 
LEFT JOIN CTE_DIAP DXP ON ING.NUMINGRES=DXP.NUMINGRES
LEFT JOIN CTE_DIAGNOSTICOS DX2 ON ING.NUMINGRES=DX2.NUMINGRES AND DX2.NUMERO=1
LEFT JOIN CTE_DIAGNOSTICOS DX3 ON ING.NUMINGRES=DX3.NUMINGRES AND DX3.NUMERO=2






