-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewEgresosHospitalarios
-- Extracted by Fabric SQL Extractor SPN v3.9.0






/*********************************************************************************
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico: Amira Esperanza Gil Meneses
Fecha: 12-07-2023
Observaciones:Se Ingresa campo para el código de la Unidad Funcional - Solicitud HSJ. 
--------------------------------------
Version 2
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:23-11-2023
Observacion:Se cambia las fechas de busqueda, de la de ingreso a la fecha de alta medica, esto solicitado por San Jose
--------------------------------------
Version 3
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:20-05-2024
Observacion:Se Adiciona el campo de boleta de salida del paciente.
--------------------------------------
Version 4
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:26-07-2024
Observacion:Se Adiciona el cte de egreso y los campos correspondientes al egreso.
--------------------------------------
Version 5
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:04-02-2025
Observacion:Se ajustan las comparativas en segundos para que sea mas exacto el dato en horas

--------------------------------------
Version 6
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:05-05-2025
Observacion:Se adicionan los campos de Horas y Dias de Diferencia
--**************
*********************************************************************************************************************/


CREATE VIEW [Report].[ViewEgresosHospitalarios] as

WITH CTE_PRIMER_INGRESO AS
 (
  SELECT 
   EST.NUMINGRES,
   EST.IPCODPACI,
   MIN(EST.IFECHAING) AS [FECHA INGRESO],
   EST.CODESPTRA,
   ESPMED.DESESPECI
  FROM 
   DBO.ADINGRESO EST
   LEFT JOIN dbo.INESPECIA AS ESPMED ON EST.CODESPTRA = ESPMED.CODESPECI
  GROUP BY 
   EST.NUMINGRES,
   EST.IPCODPACI,
   EST.CODESPTRA,
   ESPMED.DESESPECI
),

CTE_ULTIMO_INGRESO AS
(
     SELECT 
	  EST.NUMINGRES,
	  --EST.IPCODPACI,
	  MAX(EST.FECHEGRESO) 'FECHA EGRESO'
	 FROM 
	  DBO.ADINGRESO EST
	 GROUP BY 
	  EST.NUMINGRES,
	  EST.IPCODPACI
),

INGRESO_INICIAL AS
 (
  SELECT 
   ES.IPCODPACI, 
   ES.NUMINGRES,  
   ES.FECINIEST 'FECHA HOSPITALIZACION', 
   ES.CODTIPEST,
   UNF.Name 'UnidadIngreso'
  FROM 
   CHREGESTA AS ES
   INNER JOIN (
				SELECT EST.IPCODPACI
					,EST.NUMINGRES
					,MIN(ID) ID 
				FROM CHREGESTA AS EST 
				GROUP BY EST.IPCODPACI, EST.NUMINGRES
			  ) AS G ON G.ID = ES.ID
   INNER JOIN CHCAMASHO CAMD ON CAMD.CODICAMAS = ES.CODICAMAS
   LEFT JOIN Payroll.FunctionalUnit UNF ON CAMD.UFUCODIGO=UNF.Code
   --WHERE ES.IPCODPACI='1024520447'
 ),

----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
 CTE_ULTIMA_CAMAS_OCUPADA AS
 (
   SELECT 
	EGR.NUMINGRES,
	EGR.FECINIEST,
	EGR.FECFINEST,
	EGR.CODICAMAS,
	CAM.NUMCAMHOS,
	FUN.UFUDESCRI,
	FUN.UFUTIPUNI,
	FUN.UFUCODIGO,
	'EGRESO' AS TIPINGEST, 
	EGR.CODTIPEST, 
	TIP.DESTIPEST, EGR.GENESTLIQ,EGR.ID
   FROM 
    CHREGESTA EGR 
    INNER JOIN
     (
       SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR 
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES
	 ) AS G ON G.ID =EGR.ID
    INNER JOIN CHCAMASHO AS CAM  ON CAM.CODICAMAS =EGR.CODICAMAS
    INNER JOIN DBO.INUNIFUNC AS FUN  ON CAM.UFUCODIGO =FUN.UFUCODIGO
	INNER JOIN CHTIPESTA TIP ON TIP.CODTIPEST=EGR.CODTIPEST 
   WHERE 
    EGR.FECFINEST>'1900-01-01 00:00:00.000'
),
---egreso de enferneria 
CTE_EGRESO AS
(
SELECT 
HGR.NUMINGRES,
PER.Identification,
PER.Fullname,
INE.DESESPECI,
HGR.FECMUEPAC
FROM 
dbo.CHREGEGRE HGR
INNER JOIN [Security].[User] US ON HGR.CODUSUARI=US.UserCode
INNER JOIN [Security].Person PER ON US.IdPerson=PER.Id
LEFT JOIN DBO.INPROFSAL PRO ON PER.Identification=PRO.CODPROSAL
LEFT JOIN DBO.INESPECIA INE ON PRO.CODESPEC1=INE.CODESPECI
--where HGR.numingres='66578'
)

SELECT  --COUNT(*) 
 --CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 --CEN.NOMCENATE AS [CENTRO DE ATENCION],
 HEA.HealthEntityCode AS [CODIGO EPS/ENTIDAD TERRITORIAL],
 HEA.CODE AS [CODIGO ENTIDAD], 
 RTRIM(HEA.NAME) AS ENTIDAD, 
 RTRIM(CGR.NAME) AS [GRUPO DE ATENCION],
 CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
					WHEN 2 THEN 'Subsidiado'
					WHEN 3 THEN 'No afiliado' 
					WHEN 4 THEN 'Particular'
					WHEN 5 THEN 'Otro'
					WHEN 6 THEN 'Desplazado Reg. Contributivo'
					WHEN 7 THEN 'Desplazado Reg. Subsidiado'
					WHEN 8 THEN 'Desplazado No Asegurado'
					WHEN 9 THEN 'Especial o excepción'
					WHEN 10 THEN 'Personas privadas de la libertad a cargo del Fondo Nacional de Salud'
					WHEN 11 THEN 'Tomador / amparado ARL'
					WHEN 12 THEN 'Tomador / amparado SOAT'
					WHEN 13 THEN 'Tomador / amparado planes voluntarios de salud' END AS [TIPO PACIENTE],
 NIV.NIVDESCRI AS [NIVEL O ESTRATO],
 CASE PAC.IPTIPOAFI WHEN 0 THEN 'No Aplica'
					WHEN 1 THEN 'Cotizante' 
					WHEN 2 THEN 'Beneficiario'
					WHEN 3 THEN 'Adicional'
					WHEN 4 THEN 'Jub/Retirado'
					WHEN 5 THEN 'Pensionado' END AS [TIPO AFILIADO],
TIP.SIGLA AS [TIPO IDENTIFICACION],
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' 
					WHEN '2' THEN 'CEDULA DE EXTRANJERIA' 
					WHEN '3' THEN 'TARJETA DE IDENTIDAD' 
					WHEN '4' THEN 'REGISTRO CIVIL' 
					WHEN '5' THEN 'PASAPORTE'
					WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' 
					WHEN '7' THEN 'MENOR SIN IDENTIFICACION' 
					WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACIÒN' 
					WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' 
					WHEN '10' THEN 'CARNET DIPLOMATICO'
					WHEN '11' THEN 'SALVOCONDUCTO' 
					WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA'
					WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA'
					WHEN '14' THEN 'DOCUMENTO EXTRANJERO'
					WHEN '15' THEN 'SIN IDENTIFICACION'
					END AS [DESCRIPCION IDENTIFICACION],
--TIP.NOMBRE AS [DESCRIPCION IDENTIFICACION], 
 HC.IPCODPACI AS IDENTIFICACION, 
 RTRIM(PAC.IPPRINOMB) AS [PRIMER NOMBRE], 
 RTRIM(PAC.IPSEGNOMB) AS [SEGUNDO NOMBRE], 
 RTRIM(PAC.IPPRIAPEL) AS [PRIMER APELLIDO], 
 RTRIM(PAC.IPSEGAPEL) AS [SEGUNDO APELLIDO], 
 RTRIM(PAC.IPNOMCOMP) AS [NOMBRE COMPLETO PACIENTE], 
 CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO], 
 FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS EDAD,
 CONCAT
(
    -- Cálculo de años
    CAST(
        DATEDIFF(YEAR, PAC.IPFECNACI, GETDATE()) - 
        CASE 
            WHEN (MONTH(PAC.IPFECNACI) > MONTH(GETDATE())) 
              OR (MONTH(PAC.IPFECNACI) = MONTH(GETDATE()) AND DAY(PAC.IPFECNACI) > DAY(GETDATE())) 
            THEN 1 
            ELSE 0 
        END AS VARCHAR),
    ' años, ',
    
    -- Cálculo de meses
    CAST(
        (MONTH(GETDATE()) - MONTH(PAC.IPFECNACI) + 
         CASE 
            WHEN DAY(GETDATE()) < DAY(PAC.IPFECNACI) THEN -1 ELSE 0 
         END + 12) % 12 AS VARCHAR),
    ' meses, ',
    
    -- Cálculo de días
    CAST(
        DAY(GETDATE()) - DAY(PAC.IPFECNACI) + 
        CASE 
            WHEN DAY(GETDATE()) < DAY(PAC.IPFECNACI) 
            THEN DAY(EOMONTH(DATEADD(MONTH, -1, GETDATE()))) 
            ELSE 0 
        END AS VARCHAR),
    ' días'
) AS EDAD1,
 CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=5 THEN '0-5 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=6 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=12 THEN '6-12 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=13 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=17 THEN '13-17 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=18 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=28 THEN '18-28 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=29 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=59 THEN '29-59 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=60 THEN 'Mayor 60 Años' END AS [RANGO DE EDAD],
 CASE WHEN PAC.IPSEXOPAC = '1' THEN 'M' ELSE 'F' END AS SEXO,
 PAC.IPDIRECCI AS DIRECCION,
 PAC.IPTELEFON AS [TELEFONO FIJO],
 PAC.IPTELMOVI AS [TELEFONO MOVIL],
 CASE PAC.CODGRUPOE WHEN '000' THEN 'OTRO'
					WHEN '001' THEN 'INDIGENAS'
					WHEN '002' THEN 'AFROCOLOMBIANOS NEGROS MULATOS O AFRODESCENDIENTES'
					WHEN '003' THEN 'RAIZALES SAN ANDRES Y PROVIDENCIA'
					WHEN '004' THEN 'PUEBLO ROM GITANOS'
					WHEN '999' THEN 'NO SABE  NO INFORMA  NO APLICA' ELSE 'NO REGISTRA' END AS [ETNIA PACIENTE], 
 CASE ING.CODTIPPAC 
 WHEN '1' THEN 'Maternas' 
 WHEN '2' THEN 'Menores de 5 Años' 
 WHEN '3' THEN 'Adultos Mayores' 
 WHEN '4' THEN 'Discapacitados' 
 WHEN '5' THEN 'Poblacion General'
 END AS 'TIPO DE POBLACION',
 DEP.depcodigo AS [CODIGO DEPARTAMENTO],
 DEP.nomdepart AS DEPARTAMENTO,
 MUN.DEPMUNCOD AS [CODIGO MUNICIPIO],
 MUN.MUNNOMBRE AS MUNICIPIO,
 HC.NUMINGRES AS INGRESO,
 CASE UNI.UFUTIPUNI WHEN 1 THEN 'URGENCIAS' 
					WHEN 2 THEN 'HOSPITALIZACION'
					WHEN 3 THEN 'APOYO DIAGNOSTICO'
					WHEN 4 THEN 'APOYO TERAPEUTICO'
					WHEN 5 THEN 'UCI'
					WHEN 6 THEN 'UCI'
					WHEN 7 THEN 'UCI'
					WHEN 8 THEN 'UCI'
					WHEN 9 THEN 'UCI'
					WHEN 10 THEN 'UCI'
					WHEN 11 THEN 'UCI'
					WHEN 12 THEN 'UNIDAD RENAL'
					WHEN 13 THEN 'UNIDAD ONCOLOGICA' 
					WHEN 14 THEN 'UNIDAD MEDICINA NUCLEAR'
					WHEN 15 THEN 'CONSULTA EXTERNA'
					WHEN 16 THEN 'UNIDAD MENTAL'
					WHEN 17 THEN 'UNIDAD DE QUEMADOS'
					WHEN 18 THEN 'UNIDAD DE CUIDADOS PALATIVOS'
					WHEN 19 THEN 'CIRUGIA'
					WHEN 20 THEN 'LABORATORIOS'
					WHEN 21 THEN 'CARDIOLOGIA NO INVASIVA'
					WHEN 22 THEN 'CARDIOLOGIA INVASIVA'
					WHEN 23 THEN 'GINECO OBSTETRICIA'
					WHEN 24 THEN 'CONSULTA EXTERNA GINOCO OBSTETRICIA'
					WHEN 30 THEN 'OTRAS'
					WHEN 31 THEN 'CONSULTA PRIORITARIA' END AS [TIPO UNIDAD DE INGRESO], 
 UNI.UFUCODIGO AS [CODIGO UNIDAD FUNCIONAL DE INGRESO],
 RTRIM(UNI.UFUDESCRI) AS [UNIDAD FUNCIONAL DE INGRESO],
 RTRIM(CAM.NUMCAMHOS) AS [CAMA ACTUAL],
 CING.[CODESPTRA] AS [COD. ESPECIALIDAD TRATANTE INGRESO], 
 CING.[DESESPECI] AS [ESPECIALIDAD TRATANTE INGRESO], 
 CING.[DESESPECI] AS [ESPECIALIDAD PRE ALTA],  
  
 ING.CODDIAING AS [CÓDIGO DIAGNÓSTICO DE INGRESO], 
 RTRIM(DIA.NOMDIAGNO) AS [DESCRIPCIÓN DIAGNÓSTICO DE INGRESO],
  CASE EI.CODTIPEST WHEN '001' THEN 'GENERAL ADULTO'                          
				  WHEN '002' THEN 'INTENSIVO PEDIATRICO'                    
				  WHEN '003' THEN 'INTERMEDIO PEDIATRICO'                   
				  WHEN '004' THEN 'INTENSIVO NEONATAL'                      
				  WHEN '005' THEN 'INTERMEDIO NEONATAL'                     
				  WHEN '006' THEN 'BASICO NEONATAL'                         
				  WHEN '007' THEN 'OBSERVACION URGENCIAS'                   
				  WHEN '008' THEN 'REANIMACION'                             
				  WHEN '009' THEN 'INTENSIVO ADULTO'                        
				  WHEN '010' THEN 'INTERMEDIO ADULTO'                       
				  WHEN '011' THEN 'AISLAMIENTO'                             
				  WHEN '012' THEN 'GENERAL PEDIATRICO'                      
				  END AS [TIPO ESTANCIA],
 --CASE EI.CODTIPEST WHEN '001' THEN 'GENERAL' 
	--			   WHEN '002' THEN 'CUIDADO BASICO' 
	--			   WHEN '003' THEN 'CUIDADO INTERMEDIO' 
	--			   ELSE 'CUIDADO INTENSIVO' 
	--			   END AS [TIPO ESTANCIA],
 CAST (CING.[FECHA INGRESO] as date) AS [FECHA INGRESO],
 CONVERT(NVARCHAR, CAST (CING.[FECHA INGRESO] as time),8) AS [HORA INGRESO],
 EI.[UnidadIngreso] AS [UNIDAD FUNCIONAL HOSPITALIZACION], 
 CAST (EI.[FECHA HOSPITALIZACION] as date) AS [FECHA HOSPITALIZACION], 
 CONVERT(NVARCHAR, CAST (EI.[FECHA HOSPITALIZACION] as time), 8) AS [HORA HOSPITALIZACION],
 ING.CODDIAING AS [CÓDIGO DIAGNÓSTICO HOSPITALIZACION], 
 RTRIM(DIA.NOMDIAGNO) AS [DESCRIPCIÓN DIAGNÓSTICO HOSPITALIZACION],
 PRO.CODPROSAL AS [CODIGO PROFESIONAL ALTA MEDICA],
 PRO.NOMMEDICO AS [PROFESIONAL ALTA MEDICA], 
 ESP.DESESPECI AS [ESPECIALIDAD ALTA MEDICA],
 EGR.Identification AS [CODIGO PROFESIONAL EGRESO],
 EGR.Fullname AS [PROFESIONAL EGRESO],
 EGR.DESESPECI AS [ESPECIALIDAD EGRESO],
 ING.CODDIAEGR AS [CODIGO DIAGNOSTICO EGRESO], 
 RTRIM(DIAE.NOMDIAGNO) AS [DESCRIPCION DIAGNOSTICO EGRESO], 
 CO.UFUDESCRI AS [UNIDAD DE EGRESO],
 CO.NUMCAMHOS AS [CAMA DE EGRESO],
 CASE HC.ESTPACEGR WHEN 1 THEN 'MEJOR'
				   WHEN 2 THEN 'IGUAL Y PEOR'
				   WHEN 3 THEN 'FALLECIDO'
				   WHEN 4 THEN 'REMITIDO'
				   WHEN 5 THEN 'HOSPITALIZACION EN CASA' END AS [ESTADO AL EGRESO], 
 CASE HIS.INDICAPAC WHEN 1 THEN 'Trasladar a Urgencias: Solo consulta externa'
                    WHEN 2 THEN  'Trasladar a Observacion Urgencias: solo Urgencias' 
                    WHEN 3 THEN 'Trasladar a Hospitalizacion: Dif Misma Unidad' 
                    WHEN 4 THEN 'Trasladar a UCI Adulto: Dif Misma Unidad' 
				    WHEN 5 THEN 'Trasladar a UCI Pediatrica: Dif Misma Unidad' 
					WHEN 6 THEN 'Trasladar a UCI Neonatal: Dif Misma Unidad' 
					WHEN 7 THEN 'Trasladar a Consulta Externa: Dif Misma Unidad'
					WHEN 8 THEN 'Trasladar a Cirugia: Dif Misma Unidad' 
					WHEN 9 THEN 'Hospitalizacion en Casa' 
					WHEN 10 THEN 'Referencia' 
					WHEN 11 THEN 'Morgue' 
					WHEN 12 THEN 'Salida' 
					WHEN 13 THEN 'Continua en la Unidad' 
					WHEN 14 THEN 'Paciente en Tratamiento' 
					WHEN 15 THEN 'Retiro Voluntario' 
					WHEN 16 THEN 'Fuga' 
					WHEN 17 THEN 'Salida Parcial' 
					WHEN 18 THEN 'Estancia Con la Madre' 
					WHEN 19 THEN 'U.Cuidado Intermedio' 
					WHEN 20 THEN 'U.Basica' END AS [DESTINO PACIENTE],
 CAST(HC.FECALTPAC as date) AS [FECHA ALTA MEDICA], 
 CONVERT(NVARCHAR, CAST(HC.FECALTPAC as time), 8) AS [HORA ALTA MEDICA],
  RIGHT('0' + CAST(DATEDIFF(SECOND, CING.[FECHA INGRESO], HC.FECALTPAC) / 3600 AS VARCHAR), 2) + ':' +
  RIGHT('0' + CAST((DATEDIFF(SECOND, CING.[FECHA INGRESO], HC.FECALTPAC) % 3600) / 60 AS VARCHAR), 2) + ':' +
  RIGHT('0' + CAST(DATEDIFF(SECOND, CING.[FECHA INGRESO], HC.FECALTPAC) % 60 AS VARCHAR), 2) 
  AS [HORAS DE ESTANCIA],
 CAST(ISNULL(CTUE.[FECHA EGRESO],CO.FECFINEST) as date) AS [FECHA EGRESO], 
 DATEDIFF(DAY, HC.FECALTPAC, ISNULL(CTUE.[FECHA EGRESO], CO.FECFINEST)) AS [DIAS DIFERENCIA FECHA ALTA MEDICA VS FECHA DE EGRESO],
 DATEDIFF(HOUR, HC.FECALTPAC, ISNULL(CTUE.[FECHA EGRESO], CO.FECFINEST)) AS [HORAS DIFERENCIA FECHA ALTA MEDICA VS FECHA DE EGRESO],

 CONVERT(NVARCHAR, CAST(ISNULL(CTUE.[FECHA EGRESO],CO.FECFINEST) as time), 8) [HORA EGRESO], 
 FORMAT(CAST(CAST(DATEDIFF(SECOND,CING.[FECHA INGRESO],HC.FECALTPAC) AS FLOAT) / 60 AS FLOAT)/60,'N2') AS [FECHA INGRESO VS FECHA DE ALTA EN HORAS],
 FORMAT(CAST(DATEDIFF(SECOND, CING.[FECHA INGRESO], HC.FECALTPAC) AS FLOAT) / 86400, 'N2') AS [DIAS DE ESTANCIA],
 FORMAT(CAST(CAST(DATEDIFF(SECOND,HC.FECALTPAC,ISNULL(CTUE.[FECHA EGRESO],CO.FECFINEST)) AS FLOAT) / 60 AS FLOAT)/60,'N2') AS [FECHA ALTA MEDICA VS FECHA DE EGRESO EN HORAS],
 SAL.Code AS [CODIGO BOLETA DE SALIDA],
 HC.FECMUEPAC AS [FECHA DE MUERTE],
 CASE HC.CODCAUMUE  WHEN 001 THEN 'MUERTE NATURAL'
                    WHEN 002 THEN 'MUERTE VIOLENTA'
                    WHEN 003 THEN 'MUERTE EN ESTUDIO' END AS [CAUSA DE MUERTE 1],
 '' AS [CAUSA DE MUERTE 2],
 '' AS [CAUSA DE MUERTE 3],
 HC.NUMCERDEF AS [NO_CERT_DEFUNCION],
 IIF(DATEDIFF(MINUTE,CING.[FECHA INGRESO],HC.FECMUEPAC)/60<=48,'SI','NO') AS [MUERTE < 48 HORAS],
 IIF(DATEDIFF(MINUTE,CING.[FECHA INGRESO],HC.FECMUEPAC)/60>=48,'SI','NO') AS [MUERTE > 48 HORAS],
  IIF(DATEDIFF(MINUTE,CING.[FECHA INGRESO],HC.FECMUEPAC)/60<=24,'SI','NO') AS [MUERTE < 24 HORAS],
 IIF(DATEDIFF(MINUTE,CING.[FECHA INGRESO],HC.FECMUEPAC)/60>=24,'SI','NO') AS [MUERTE > 24 HORAS],
 1 as 'CANTIDAD',
 CAST(HC.FECALTPAC AS date) AS 'FECHA BUSQUEDA',
 YEAR(HC.FECALTPAC) AS 'AÑO BUSQUEDA',
 MONTH(HC.FECALTPAC) AS 'MES BUSQUEDA',
 CONCAT(FORMAT(MONTH(HC.FECALTPAC), '00') ,' - ', 
	   CASE MONTH(HC.FECALTPAC) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 HCREGEGRE HC
 INNER JOIN ADINGRESO AS ING ON HC.NUMINGRES=ING.NUMINGRES
 LEFT JOIN dbo.CHCAMASHO CAM ON ING.CODCAMACT=CAM.CODICAMAS
 INNER JOIN INGRESO_INICIAL EI ON HC.NUMINGRES = EI.NUMINGRES
 INNER JOIN CTE_ULTIMO_INGRESO CTUE ON HC.NUMINGRES = CTUE.NUMINGRES
 LEFT JOIN CTE_PRIMER_INGRESO CING ON CING.NUMINGRES =HC.NUMINGRES 
 INNER JOIN HCHISPACA HIS ON HC.NUMINGRES = HIS.NUMINGRES AND HC.NUMEFOLIO = HIS.NUMEFOLIO
 INNER JOIN INPACIENT AS PAC ON PAC.IPCODPACI = HC.IPCODPACI
 INNER JOIN dbo.ADTIPOIDENTIFICA TIP ON PAC.IPTIPODOC=TIP.CODIGO
 INNER JOIN ADCENATEN AS CEN ON HC.CODCENATE = CEN.CODCENATE
 INNER JOIN INUNIFUNC UNI ON HC.UFUCODIGO = UNI.UFUCODIGO
 INNER JOIN.CONTRACT.HEALTHADMINISTRATOR HEA ON ING.GENCONENTITY = HEA.ID
 INNER JOIN.CONTRACT.CAREGROUP AS CGR ON ING.GENCAREGROUP = CGR.ID
 LEFT JOIN INPROFSAL PRO ON HIS.CODPROSAL = PRO.CODPROSAL
 LEFT JOIN INESPECIA AS ESP ON ESP.CODESPECI = HIS.CODESPTRA
 LEFT JOIN INDIAGNOS AS DIA ON ING.CODDIAING = DIA.CODDIAGNO
 LEFT JOIN INDIAGNOS AS DIAE ON ING.CODDIAEGR = DIAE.CODDIAGNO
 LEFT JOIN dbo.INUBICACI UBI on pac.AUUBICACI=UBI.AUUBICACI
LEFT JOIN dbo.INMUNICIP MUN ON UBI.DEPMUNCOD=MUN.DEPMUNCOD 
LEFT JOIN dbo.INDEPARTA DEP ON MUN.DEPCODIGO=DEP.depcodigo
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA CO ON HC.NUMINGRES=CO.NUMINGRES
LEFT JOIN Billing.SlipOut SAL ON SAL.Id=(SELECT MAX(SA.ID) FROM Billing.SlipOut SA WHERE HC.NUMINGRES=SA.AdmissionNumber)
LEFT JOIN dbo.ADNIVELES NIV ON PAC.NIVCODIGO=NIV.NIVCODIGO
LEFT JOIN CTE_EGRESO EGR ON HC.NUMINGRES=EGR.NUMINGRES
--where HC.FECALTPAC is null
--WHERE CAST(ING.IFECHAING as date) BETWEEN '2023-09-01' AND '2023-09-30'
--WHERE HC.IPCODPACI='1024520447'
--where hc.IPCODPACI='1000000566' and hc.NUMINGRES='136442'
--where CTUE.[FECHA EGRESO] is null
UNION ALL--------------------------------------------------------------------------------------
SELECT  --COUNT(*) 
 --CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 --CEN.NOMCENATE AS [CENTRO DE ATENCION],
 HEA.HealthEntityCode AS [CODIGO EPS/ENTIDAD TERRITORIAL],
 HEA.CODE AS [CODIGO ENTIDAD], 
 RTRIM(HEA.NAME) AS ENTIDAD, 
 RTRIM(CGR.NAME) AS [GRUPO DE ATENCION],
 CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
					WHEN 2 THEN 'Subsidiado'
					WHEN 3 THEN 'No afiliado' 
					WHEN 4 THEN 'Particular'
					WHEN 5 THEN 'Otro'
					WHEN 6 THEN 'Desplazado Reg. Contributivo'
					WHEN 7 THEN 'Desplazado Reg. Subsidiado'
					WHEN 8 THEN 'Desplazado No Asegurado'
					WHEN 9 THEN 'Especial o excepción'
					WHEN 10 THEN 'Personas privadas de la libertad a cargo del Fondo Nacional de Salud'
					WHEN 11 THEN 'Tomador / amparado ARL'
					WHEN 12 THEN 'Tomador / amparado SOAT'
					WHEN 13 THEN 'Tomador / amparado planes voluntarios de salud' END AS [TIPO PACIENTE],
 NIV.NIVDESCRI AS [NIVEL O ESTRATO],
 CASE PAC.IPTIPOAFI WHEN 0 THEN 'No Aplica'
					WHEN 1 THEN 'Cotizante' 
					WHEN 2 THEN 'Beneficiario'
					WHEN 3 THEN 'Adicional'
					WHEN 4 THEN 'Jub/Retirado'
					WHEN 5 THEN 'Pensionado' END AS [TIPO AFILIADO],
TIP.SIGLA AS [TIPO IDENTIFICACION],
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' 
					WHEN '2' THEN 'CEDULA DE EXTRANJERIA' 
					WHEN '3' THEN 'TARJETA DE IDENTIDAD' 
					WHEN '4' THEN 'REGISTRO CIVIL' 
					WHEN '5' THEN 'PASAPORTE'
					WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' 
					WHEN '7' THEN 'MENOR SIN IDENTIFICACION' 
					WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACIÒN' 
					WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' 
					WHEN '10' THEN 'CARNET DIPLOMATICO'
					WHEN '11' THEN 'SALVOCONDUCTO' 
					WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA'
					WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA'
					WHEN '14' THEN 'DOCUMENTO EXTRANJERO'
					WHEN '15' THEN 'SIN IDENTIFICACION'
					END AS [DESCRIPCION IDENTIFICACION],
--TIP.NOMBRE AS [DESCRIPCION IDENTIFICACION], 
 HC.IPCODPACI AS IDENTIFICACION, 
 RTRIM(PAC.IPPRINOMB) AS [PRIMER NOMBRE], 
 RTRIM(PAC.IPSEGNOMB) AS [SEGUNDO NOMBRE], 
 RTRIM(PAC.IPPRIAPEL) AS [PRIMER APELLIDO], 
 RTRIM(PAC.IPSEGAPEL) AS [SEGUNDO APELLIDO], 
 RTRIM(PAC.IPNOMCOMP) AS [NOMBRE COMPLETO PACIENTE], 
 CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO], 
 FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS EDAD,
 CONCAT
(
    -- Cálculo de años
    CAST(
        DATEDIFF(YEAR, PAC.IPFECNACI, GETDATE()) - 
        CASE 
            WHEN (MONTH(PAC.IPFECNACI) > MONTH(GETDATE())) 
              OR (MONTH(PAC.IPFECNACI) = MONTH(GETDATE()) AND DAY(PAC.IPFECNACI) > DAY(GETDATE())) 
            THEN 1 
            ELSE 0 
        END AS VARCHAR),
    ' años, ',
    
    -- Cálculo de meses
    CAST(
        (MONTH(GETDATE()) - MONTH(PAC.IPFECNACI) + 
         CASE 
            WHEN DAY(GETDATE()) < DAY(PAC.IPFECNACI) THEN -1 ELSE 0 
         END + 12) % 12 AS VARCHAR),
    ' meses, ',
    
    -- Cálculo de días
    CAST(
        DAY(GETDATE()) - DAY(PAC.IPFECNACI) + 
        CASE 
            WHEN DAY(GETDATE()) < DAY(PAC.IPFECNACI) 
            THEN DAY(EOMONTH(DATEADD(MONTH, -1, GETDATE()))) 
            ELSE 0 
        END AS VARCHAR),
    ' días'
) AS EDAD1,
 CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=5 THEN '0-5 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=6 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=11 THEN '6-12 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=13 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=17 THEN '13-17 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=18 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=28 THEN '18-28 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=29 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=59 THEN '29-59 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=60 THEN 'Mayor 60 Años' END AS [RANGO DE EDAD],
 CASE WHEN PAC.IPSEXOPAC = '1' THEN 'M' ELSE 'F' END AS SEXO,
 PAC.IPDIRECCI AS DIRECCION,
 PAC.IPTELEFON AS [TELEFONO FIJO],
 PAC.IPTELMOVI AS [TELEFONO MOVIL],
 CASE PAC.CODGRUPOE WHEN '000' THEN 'OTRO'
					WHEN '001' THEN 'INDIGENAS'
					WHEN '002' THEN 'AFROCOLOMBIANOS NEGROS MULATOS O AFRODESCENDIENTES'
					WHEN '003' THEN 'RAIZALES SAN ANDRES Y PROVIDENCIA'
					WHEN '004' THEN 'PUEBLO ROM GITANOS'
					WHEN '999' THEN 'NO SABE  NO INFORMA  NO APLICA' ELSE 'NO REGISTRA' END AS [ETNIA PACIENTE], 
 CASE ING.CODTIPPAC 
 WHEN '1' THEN 'Maternas' 
 WHEN '2' THEN 'Menores de 5 Años' 
 WHEN '3' THEN 'Adultos Mayores' 
 WHEN '4' THEN 'Discapacitados' 
 WHEN '5' THEN 'Poblacion General'
 END AS 'TIPO DE POBLACION',
 DEP.depcodigo AS [CODIGO DEPARTAMENTO],
 DEP.nomdepart AS DEPARTAMENTO,
 MUN.DEPMUNCOD AS [CODIGO MUNICIPIO],
 MUN.MUNNOMBRE AS MUNICIPIO,
 HC.NUMINGRES AS INGRESO, 
 CASE UNI.UFUTIPUNI WHEN 1 THEN 'URGENCIAS' 
					WHEN 2 THEN 'HOSPITALIZACION'
					WHEN 3 THEN 'APOYO DIAGNOSTICO'
					WHEN 4 THEN 'APOYO TERAPEUTICO'
					WHEN 5 THEN 'UCI'
					WHEN 6 THEN 'UCI'
					WHEN 7 THEN 'UCI'
					WHEN 8 THEN 'UCI'
					WHEN 9 THEN 'UCI'
					WHEN 10 THEN 'UCI'
					WHEN 11 THEN 'UCI'
					WHEN 12 THEN 'UNIDAD RENAL'
					WHEN 13 THEN 'UNIDAD ONCOLOGICA' 
					WHEN 14 THEN 'UNIDAD MEDICINA NUCLEAR'
					WHEN 15 THEN 'CONSULTA EXTERNA'
					WHEN 16 THEN 'UNIDAD MENTAL'
					WHEN 17 THEN 'UNIDAD DE QUEMADOS'
					WHEN 18 THEN 'UNIDAD DE CUIDADOS PALATIVOS'
					WHEN 19 THEN 'CIRUGIA'
					WHEN 20 THEN 'LABORATORIOS'
					WHEN 21 THEN 'CARDIOLOGIA NO INVASIVA'
					WHEN 22 THEN 'CARDIOLOGIA INVASIVA'
					WHEN 23 THEN 'GINECO OBSTETRICIA'
					WHEN 24 THEN 'CONSULTA EXTERNA GINOCO OBSTETRICIA'
					WHEN 30 THEN 'OTRAS'
					WHEN 31 THEN 'CONSULTA PRIORITARIA' END AS [TIPO UNIDAD DE INGRESO], 
 UNI.UFUCODIGO AS [CODIGO UNIDAD FUNCIONAL DE INGRESO],
 RTRIM(UNI.UFUDESCRI) AS [UNIDAD FUNCIONAL DE INGRESO],
 RTRIM(CAM.NUMCAMHOS) AS [CAMA ACTUAL],
 CING.[CODESPTRA] AS [COD. ESPECIALIDAD TRATANTE INGRESO], 
 CING.[DESESPECI] AS [ESPECIALIDAD TRATANTE INGRESO], 
 CING.[DESESPECI] AS [ESPECIALIDAD PREALTA],  
 ING.CODDIAING AS [CÓDIGO DIAGNÓSTICO DE INGRESO], 
 RTRIM(DIA.NOMDIAGNO) AS [DESCRIPCIÓN DIAGNÓSTICO DE INGRESO], 
 CASE EI.CODTIPEST WHEN '001' THEN 'GENERAL ADULTO'                          
				  WHEN '002' THEN 'INTENSIVO PEDIATRICO'                    
				  WHEN '003' THEN 'INTERMEDIO PEDIATRICO'                   
				  WHEN '004' THEN 'INTENSIVO NEONATAL'                      
				  WHEN '005' THEN 'INTERMEDIO NEONATAL'                     
				  WHEN '006' THEN 'BASICO NEONATAL'                         
				  WHEN '007' THEN 'OBSERVACION URGENCIAS'                   
				  WHEN '008' THEN 'REANIMACION'                             
				  WHEN '009' THEN 'INTENSIVO ADULTO'                        
				  WHEN '010' THEN 'INTERMEDIO ADULTO'                       
				  WHEN '011' THEN 'AISLAMIENTO'                             
				  WHEN '012' THEN 'GENERAL PEDIATRICO'                      
				  END AS [TIPO ESTANCIA],
 --CASE EI.CODTIPEST WHEN '001' THEN 'GENERAL' 
	--			   WHEN '002' THEN 'CUIDADO BASICO' 
	--			   WHEN '003' THEN 'CUIDADO INTERMEDIO' 
	--			   ELSE 'CUIDADO INTENSIVO' 
	--			   END AS [TIPO ESTANCIA],
 CAST (CING.[FECHA INGRESO] as date) AS [FECHA INGRESO],
 CONVERT(NVARCHAR, CAST (CING.[FECHA INGRESO] as time),8) AS [HORA INGRESO],
 EI.[UnidadIngreso] AS [UNIDAD FUNCIONAL HOSPITALIZACION], 
 CAST (EI.[FECHA HOSPITALIZACION] as date) AS [FECHA HOSPITALIZACION], 
 CONVERT(NVARCHAR, CAST (EI.[FECHA HOSPITALIZACION] as time), 8) AS [HORA HOSPITALIZACION], 
 ING.CODDIAING AS [CÓDIGO DIAGNÓSTICO HOSPITALIZACION], 
 RTRIM(DIA.NOMDIAGNO) AS [DESCRIPCIÓN DIAGNÓSTICO HOSPITALIZACION],
 PRO.CODPROSAL AS [CODIGO PROFESIONAL ALTA MEDICA],
 PRO.NOMMEDICO AS [PROFESIONAL ALTA MEDICA], 
 ESP.DESESPECI AS [ESPECIALIDAD ALTA MEDICA],
 EGR.Identification AS [CODIGO PROFESIONAL EGRESO],
 EGR.Fullname AS [PROFESIONAL EGRESO],
 EGR.DESESPECI AS [ESPECIALIDAD EGRESO],
 ING.CODDIAEGR AS [CODIGO DIAGNOSTICO EGRESO], 
 RTRIM(DIAE.NOMDIAGNO) AS [DESCRIPCION DIAGNOSTICO EGRESO], 
 CO.UFUDESCRI AS [UNIDAD DE EGRESO],
 CO.NUMCAMHOS AS [CAMA DE EGRESO],
 CASE HC.FECHISPAC WHEN 1 THEN 'MEJOR'
				   WHEN 2 THEN 'IGUAL Y PEOR'
				   WHEN 3 THEN 'FALLECIDO'
				   WHEN 4 THEN 'REMITIDO'
				   WHEN 5 THEN 'HOSPITALIZACION EN CASA' END AS [ESTADO AL EGRESO], 
 CASE HIS.INDICAPAC WHEN 1 THEN 'Trasladar a Urgencias: Solo consulta externa'
                    WHEN 2 THEN  'Trasladar a Observacion Urgencias: solo Urgencias' 
                    WHEN 3 THEN 'Trasladar a Hospitalizacion: Dif Misma Unidad' 
                    WHEN 4 THEN 'Trasladar a UCI Adulto: Dif Misma Unidad' 
				    WHEN 5 THEN 'Trasladar a UCI Pediatrica: Dif Misma Unidad' 
					WHEN 6 THEN 'Trasladar a UCI Neonatal: Dif Misma Unidad' 
					WHEN 7 THEN 'Trasladar a Consulta Externa: Dif Misma Unidad'
					WHEN 8 THEN 'Trasladar a Cirugia: Dif Misma Unidad' 
					WHEN 9 THEN 'Hospitalizacion en Casa' 
					WHEN 10 THEN 'Referencia' 
					WHEN 11 THEN 'Morgue' 
					WHEN 12 THEN 'Salida' 
					WHEN 13 THEN 'Continua en la Unidad' 
					WHEN 14 THEN 'Paciente en Tratamiento' 
					WHEN 15 THEN 'Retiro Voluntario' 
					WHEN 16 THEN 'Fuga' 
					WHEN 17 THEN 'Salida Parcial' 
					WHEN 18 THEN 'Estancia Con la Madre' 
					WHEN 19 THEN 'U.Cuidado Intermedio' 
					WHEN 20 THEN 'U.Basica' END AS [DESTINO PACIENTE],
 CAST(HC.FECHISPAC as date) AS [FECHA ALTA MEDICA], 
 CONVERT(NVARCHAR, CAST(HC.FECHISPAC as time), 8) AS [HORA ALTA MEDICA], 
  RIGHT('0' + CAST(DATEDIFF(SECOND, CING.[FECHA INGRESO], HC.FECHISPAC) / 3600 AS VARCHAR), 2) + ':' +
  RIGHT('0' + CAST((DATEDIFF(SECOND, CING.[FECHA INGRESO], HC.FECHISPAC) % 3600) / 60 AS VARCHAR), 2) + ':' +
  RIGHT('0' + CAST(DATEDIFF(SECOND, CING.[FECHA INGRESO], HC.FECHISPAC) % 60 AS VARCHAR), 2) 
  AS [HORAS DE ESTANCIA],
 CAST(ISNULL(CTUE.[FECHA EGRESO],CO.FECFINEST) as date) AS [FECHA EGRESO],
DATEDIFF(DAY, HC.FECHISPAC, ISNULL(CTUE.[FECHA EGRESO], CO.FECFINEST)) AS [DIAS DIFERENCIA FECHA ALTA MEDICA VS FECHA DE EGRESO],
DATEDIFF(HOUR, HC.FECHISPAC, ISNULL(CTUE.[FECHA EGRESO], CO.FECFINEST)) AS [HORAS DIFERENCIA FECHA ALTA MEDICA VS FECHA DE EGRESO],

 CONVERT(NVARCHAR, CAST(ISNULL(CTUE.[FECHA EGRESO],CO.FECFINEST) as time), 8) [HORA EGRESO], 
 FORMAT(CAST(CAST(DATEDIFF(SECOND,CING.[FECHA INGRESO],HC.FECHISPAC) AS FLOAT) / 60 AS FLOAT)/60,'N2') AS [FECHA INGRESO VS FECHA DE ALTA EN HORAS],
 FORMAT(CAST(CAST(CAST(DATEDIFF(SECOND,CING.[FECHA INGRESO],HC.FECHISPAC) AS FLOAT) / 60 AS FLOAT)/60 AS FLOAT )/24,'N2') AS [FECHA INGRESO VS FECHA DE ALTA EN DIAS],
 FORMAT(CAST(CAST(DATEDIFF(SECOND,HC.FECHISPAC,ISNULL(CTUE.[FECHA EGRESO],CO.FECFINEST)) AS FLOAT) / 60 AS FLOAT)/60,'N2') AS [FECHA ALTA MEDICA VS FECHA DE EGRESO EN HORAS],
 SAL.Code AS [CODIGO BOLETA DE SALIDA],
 HC.FECHISPAC AS [FECHA DE MUERTE],
 CASE HC.FECHISPAC  WHEN 001 THEN 'MUERTE NATURAL'
                    WHEN 002 THEN 'MUERTE VIOLENTA'
                    WHEN 003 THEN 'MUERTE EN ESTUDIO' END AS [CAUSA DE MUERTE 1],
 '' AS [CAUSA DE MUERTE 2],
 '' AS [CAUSA DE MUERTE 3],
null AS [NO_CERT_DEFUNCION],
 IIF(DATEDIFF(MINUTE,CING.[FECHA INGRESO],EGR.FECMUEPAC)/60<=48,'SI','NO') AS [MUERTE < 48 HORAS],
 IIF(DATEDIFF(MINUTE,CING.[FECHA INGRESO],EGR.FECMUEPAC)/60>=48,'SI','NO') AS [MUERTE > 48 HORAS],
  IIF(DATEDIFF(MINUTE,CING.[FECHA INGRESO],EGR.FECMUEPAC)/60<=24,'SI','NO') AS [MUERTE < 24 HORAS],
 IIF(DATEDIFF(MINUTE,CING.[FECHA INGRESO],EGR.FECMUEPAC)/60>=24,'SI','NO') AS [MUERTE > 24 HORAS],
 1 as 'CANTIDAD',
 CAST(HC.FECHISPAC AS date) AS 'FECHA BUSQUEDA',
 YEAR(HC.FECHISPAC) AS 'AÑO BUSQUEDA',
 MONTH(HC.FECHISPAC) AS 'MES BUSQUEDA',
 CONCAT(FORMAT(MONTH(HC.FECHISPAC), '00') ,' - ', 
	   CASE MONTH(HC.FECHISPAC) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
(SELECT * FROM DBO.HCHISPACA HC WHERE NUMINGRES NOT IN (SELECT NUMINGRES FROM DBO.HCREGEGRE) AND INDICAPAC=12 AND GENCONEXT=0) HC
 INNER JOIN ADINGRESO AS ING ON HC.NUMINGRES=ING.NUMINGRES
 LEFT JOIN dbo.CHCAMASHO CAM ON ING.CODCAMACT=CAM.CODICAMAS
 INNER JOIN INGRESO_INICIAL EI ON HC.NUMINGRES = EI.NUMINGRES
 INNER JOIN CTE_ULTIMO_INGRESO CTUE ON HC.NUMINGRES = CTUE.NUMINGRES
 LEFT JOIN CTE_PRIMER_INGRESO CING ON CING.NUMINGRES =HC.NUMINGRES 
 INNER JOIN HCHISPACA HIS ON HC.NUMINGRES = HIS.NUMINGRES AND HC.NUMEFOLIO = HIS.NUMEFOLIO
 INNER JOIN INPACIENT AS PAC ON PAC.IPCODPACI = HC.IPCODPACI
 INNER JOIN dbo.ADTIPOIDENTIFICA TIP ON PAC.IPTIPODOC=TIP.CODIGO
 INNER JOIN ADCENATEN AS CEN ON HC.CODCENATE = CEN.CODCENATE
 INNER JOIN INUNIFUNC UNI ON HC.UFUCODIGO = UNI.UFUCODIGO
 INNER JOIN.CONTRACT.HEALTHADMINISTRATOR HEA ON ING.GENCONENTITY = HEA.ID
 INNER JOIN.CONTRACT.CAREGROUP AS CGR ON ING.GENCAREGROUP = CGR.ID
 LEFT JOIN INPROFSAL PRO ON HIS.CODPROSAL = PRO.CODPROSAL
 LEFT JOIN INESPECIA AS ESP ON ESP.CODESPECI = HIS.CODESPTRA
 LEFT JOIN INDIAGNOS AS DIA ON ING.CODDIAING = DIA.CODDIAGNO
 LEFT JOIN INDIAGNOS AS DIAE ON ING.CODDIAEGR = DIAE.CODDIAGNO
 LEFT JOIN dbo.INUBICACI UBI on pac.AUUBICACI=UBI.AUUBICACI
LEFT JOIN dbo.INMUNICIP MUN ON UBI.DEPMUNCOD=MUN.DEPMUNCOD 
LEFT JOIN dbo.INDEPARTA DEP ON MUN.DEPCODIGO=DEP.depcodigo
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA CO ON HC.NUMINGRES=CO.NUMINGRES
LEFT JOIN Billing.SlipOut SAL ON SAL.Id=(SELECT MAX(SA.ID) FROM Billing.SlipOut SA WHERE HC.NUMINGRES=SA.AdmissionNumber)
LEFT JOIN dbo.ADNIVELES NIV ON PAC.NIVCODIGO=NIV.NIVCODIGO
LEFT JOIN CTE_EGRESO EGR ON HC.NUMINGRES=EGR.NUMINGRES
--where HC.FECALTPAC is null
--WHERE CAST(ING.IFECHAING as date) BETWEEN '2023-09-01' AND '2023-09-30'
--WHERE HC.NUMINGRES='66578'
--where  HC.IPCODPACI='1024520447'


--select * from dbo.HCREGEGRE where NUMINGRES='66578'
--select * from dbo.HCHISPACA where NUMINGRES IN ('66578')
--select * from dbo.CHREGESTA where NUMINGRES='175288'
--select * from dbo.CHTIPESTA
----SELECT * FROM dbo.CHREGEGRE WHERE NUMINGRES='66578'
--SELECT * FROM dbo.CHREGEGRE where NUMINGRES='66578'
