-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewOrdenesImagenologia
-- Extracted by Fabric SQL Extractor SPN v3.9.0





/*******************************************************************************************************************
Nombre: [Report].[ViewOrdenesImagenologia]
Tipo:Vista
Observacion:Reporte ordenes de imagenología
Profesional: Juan Pablo Robayo Bohórquez
Fecha:
---------------------------------------------------------------------------

****************************************************************************************************************************/

CREATE view [Report].[ViewOrdenesImagenologia] as

SELECT DISTINCT CAST(ORD.FECORDMED AS DATE) 'FECHA DE BUSQUEDA',ORD.NUMEFOLIO 'FOLIO ORDEN', ORD.IPCODPACI 'ID PACIENTE', PAC.IPNOMCOMP 'NOMBRE PACIENTE',ORD.NUMINGRES '# INGRESO', ORD.CODSERIPS 'COD. CUPS',
CUPS.DESSERIPS 'SERVICIO', CAST(ORD.FECORDMED AS DATE) 'FECHA DE ORDEN',FECRECEXA 'FECHA TOMA', ORD.USURECEXA 'COD. USUARIO TOMA',ISNULL(US1.NOMUSUARI,US3.NOMMEDICO) 'USUARIO TOMA',
ORD.FECHLECT 'FECHA LECTURA',ORD.MEDREALEC 'COD. USUARIO LEE', ISNULL(US2.NOMUSUARI,US4.NOMMEDICO) 'USUARIO LEE', 
CASE ORD.ESTSERIPS WHEN 1 THEN 'Solicitado'
WHEN 2 THEN 'Estudio Realizado'
WHEN 3 THEN 'Imagen Procesada'
WHEN 4 THEN 'Estudio Interpretado'
WHEN 5 THEN 'Remitido'
WHEN 6 THEN 'Anulado'
WHEN 7 THEN 'Extramural' END 'ESTADO',
AN.FECANUIMG 'FECHA ANULACION', AN.USUANUIMG 'COD. USUARIO ANULA', ISNULL(US5.NOMUSUARI,US6.NOMMEDICO) 'USUARIO ANULA'

FROM  HCORDIMAG ORD
INNER JOIN INPACIENT PAC ON PAC.IPCODPACI=ORD.IPCODPACI
INNER JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS=ORD.CODSERIPS
LEFT JOIN SEGusuaru US1 ON US1.CODUSUARI=ORD.USURECEXA
LEFT JOIN SEGusuaru US2 ON US2.CODUSUARI=ORD.MEDREALEC
LEFT JOIN INPROFSAL US3 ON US3.CODPROSAL=ORD.USURECEXA
LEFT JOIN INPROFSAL US4 ON US4.CODPROSAL=ORD.MEDREALEC
LEFT JOIN HCIMGANUL AN ON ORD.NUMINGRES=AN.NUMINGRES AND ORD.CODSERIPS=AN.CODSERIPS AND AN.NUMEFOLIO=ORD.NUMEFOLIO
LEFT JOIN SEGusuaru US5 ON US5.CODUSUARI=AN.USUANUIMG
LEFT JOIN INPROFSAL US6 ON US6.CODPROSAL=AN.USUANUIMG





