-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewResolution2175
-- Extracted by Fabric SQL Extractor SPN v3.9.0










    /*******************************************************************************************************************
Nombre: [Report].[ViewResolution2175]
Tipo:Vista
Observacion:Resolución 2175 del 2015
Profesional: Nilsson Miguel Galindo Lopez
Fecha:09-02-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:07-11-2023
Ovservaciones: Se ajusta las variables desde la 11 a la 21 ya que estaban intercambid ticket 13193
--------------------------------------
Version 2
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:15-12-2023
Ovservaciones: Se ajusta la condicion de las consultas, ya no por numero de ingreso sino por fecha
--------------------------------------
Version 3
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:15-12-2023
Ovservaciones: Se ajusta la condicion de las consultas, ya no por numero de ingreso sino por fecha
***********************************************************************************************************************************/

CREATE VIEW [Report].[ViewResolution2175] AS

WITH 
--ESTE CTE APLICA PARA LOS LABORATORIOS DE:
--LOS RECIEN NACIDOS
--NIÑOS DE 0 A 5 AÑOS
--MOÑOS DE 6 A 11 AÑOS 

CTE_LABORATORIO AS
(
		SELECT 
		LAB.AUTO,
		LAB.IPCODPACI,
		LAB.NUMINGRES,
		CASE WHEN IPS.DESSERIPS like '%hemoglobina%' THEN 2 
			 END VARIABLE,
		CONVERT(VARCHAR,CAST(FECRECMUE AS DATE),23) AS FECHA,
		VAL.VALOR,
		VAL.ANALITO
	FROM
		dbo.AMBORDLAB LAB INNER JOIN
		dbo.INCUPSIPS IPS ON LAB.CODSERIPS=IPS.CODSERIPS AND LAB.FECRECMUE IS NOT NULL  INNER JOIN
		dbo.INTERLABD VAL ON LAB.AUTO=VAL.AUTOLABOR AND ANALITO='HEMOGLOBINA'
	WHERE (LAB.FECRECMUE > CAST(GETDATE() - 400 AS DATE)) AND IPS.DESSERIPS like '%hemoglobina%'

	UNION ALL

	SELECT 
		LAB.AUTO,
		LAB.IPCODPACI,
		LAB.NUMINGRES,
		CASE WHEN IPS.CODSERIPS='904902' THEN 1 WHEN IPS.CODSERIPS='904904' THEN 1 --TSH
			 WHEN IPS.CODSERIPS='906249' THEN 3 -- VIH
			 WHEN IPS.DESSERIPS like '%HEPATITIS B ANTICUERPOS%' THEN 4 --HEPATITIS B
			 WHEN IPS.CODSERIPS='906915' THEN 5 WHEN IPS.CODSERIPS='906039' THEN 5
			 END VARIABLE,
		CONVERT(VARCHAR,CAST(FECRECMUE AS DATE),23) AS FECHA,
		VAL.VALOR,
		VAL.ANALITO
	FROM
		dbo.AMBORDLAB LAB INNER JOIN
		dbo.INCUPSIPS IPS ON LAB.CODSERIPS=IPS.CODSERIPS AND LAB.FECRECMUE IS NOT NULL  INNER JOIN
		dbo.INTERLABD VAL ON LAB.AUTO=VAL.AUTOLABOR 
	WHERE (LAB.FECRECMUE > CAST(GETDATE() - 400 AS DATE)) AND (IPS.CODSERIPS IN('904902','904904','906249','906915','906039') OR IPS.DESSERIPS like '%HEPATITIS B ANTICUERPOS%') --AND LAB.IPCODPACI='1035923076'

	UNION ALL

	SELECT
		AUTO,
		IPCODPACI,
		NUMINGRES,
		CASE CODSERIPS WHEN '904902' THEN 1 WHEN '904904' THEN 1 --TSH
					   END VARIABLE,
		CONVERT(VARCHAR,CAST(FECRECMUE AS DATE),23) AS FECHA,
		'' AS VALOR,
		'' AS ANALITO
	FROM 
		dbo.HCORDLABO 
	WHERE (FECRECMUE > CAST(GETDATE() - 400 AS DATE)) AND CODSERIPS IN('904902','904904') AND FECRECMUE IS NOT NULL

--	SELECT * FROM dbo.INCUPSIPS WHERE DESSERIPS LIKE '%VIH%'
),

--EN EL CASO QUE NO SE CUENTE CON INTERFAZ, SE CONSULTA LAS TBLAS DE EXAMEN FISICO, PARA PODER SACAR ALGUNA FECHA.
--RECIEN NACIDOS
--NIÑOS DE 0 A 5 AÑOS
--NIÑOS DE 6 A 11 AÑOS
CTE_EXAMEN_FISICO AS
(
	SELECT
		NUMINGRES,
		IDHCHISPACA,
		CASE NOMBRE_VARIABLE WHEN 'Fecha tamizaje TSH neonatal' THEN 1
							 WHEN 'Fecha de toma hemoglobina' THEN 2
							 WHEN 'Resultado de hemoglobina' THEN 3 WHEN 'Resultado de hemoglobina 2' THEN 3
							 END [VARIABLE],
		VALOR
	FROM
		[Report].[TablaExamenFisico]
	WHERE (FECHA > CAST(GETDATE() - 380 AS DATE)) AND (NOMBRE_VARIABLE IN ('Fecha tamizaje TSH neonatal','Fecha de toma hemoglobina','Resultado de hemoglobina','Resultado de hemoglobina 2'))

--	SELECT * FROM [Report].[TablaExamenFisico] WHERE NOMBRE_VARIABLE LIKE '%resultado de HEMOGLOBINA%'
),
----CTE SUMINISTRO DE MEDICAMENTOS
----DE 0 A 5 AÑOS
----DE 6 A 11 AÑOS
CTE_MEDICAMENTOS AS
(
	SELECT
		DIS.ID,
		DIS.AdmissionNumber,
		ING.IPCODPACI,
		CASE WHEN PRO.Name LIKE '%SULFATO%FERROSO%' THEN 1 
			 WHEN PRO.Name LIKE '%VITAMINA A%' THEN 2
			 WHEN PRO.Name LIKE '%ACIDO%FOLICO%' THEN 3
			 WHEN PRO.Name LIKE '%CALCIO%CARBONATO%' THEN 4 
			 WHEN PRO.[Name] LIKE '%PRESERVATIVOS%' THEN 5 
			 WHEN PRO.[Name] LIKE '%LEVONORGESTREL%' THEN 5
			 WHEN PRO.[Name] LIKE '%MEDROXIPROGESTERONA%' THEN 5 END VARIABLE,
		CONVERT(VARCHAR,CAST(DIS.ConfirmationDate AS DATE),23) AS FECHA
	FROM 
		Inventory.PharmaceuticalDispensing DIS INNER JOIN
		Inventory.PharmaceuticalDispensingDetail DISD ON DIS.Id=DISD.PharmaceuticalDispensingId INNER JOIN
		Inventory.InventoryProduct PRO ON DISD.ProductId=PRO.Id INNER JOIN
		DBO.ADINGRESO ING ON DIS.AdmissionNumber=ING.NUMINGRES
	WHERE (ING.IFECHAING > CAST(GETDATE() - 400 AS DATE)) AND (
	PRO.Name LIKE '%SULFATO%FERROSO%' OR PRO.Name LIKE '%VITAMINA A%' OR PRO.Name LIKE '%ACIDO%FOLICO%' OR PRO.Name LIKE '%CALCIO%CARBONATO%' OR
	PRO.[NAME] LIKE '%INTRAUTERINO%' OR PRO.[NAME] LIKE '%PRESERVATIVOS%'OR PRO.[NAME] LIKE '%LEVONORGESTREL%' OR PRO.[NAME] LIKE '%DIU%' OR 
	PRO.[NAME] LIKE '%CONDONES%' OR PRO.[NAME] LIKE '%MEDROXIPROGESTERONA%')
	--SELECT * FROM Inventory.InventoryProduct WHERE NAME LIKE '%hepatitis%'
),
----SELECT DE LOS RECIEN NACIDOS
CTE_TIPOS AS
(
SELECT
	CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
	ENT.NOMENTIDA AS ENTIDAD,
	RN.NUMINGRESHIJO AS INGRESO,
	RN.NUMEFOLIO AS FOLIO,
	'RECIEN NACIDO' AS TIPO,
	2 AS [0],
	--ROW_NUMBER() OVER(ORDER BY RN.IPCODPACIHIJO) AS [1],
	CASE PAC.IPTIPODOC WHEN 1 THEN 'CC'  
					   WHEN 2 THEN 'CE' 
					   WHEN 3 THEN 'TI'   
					   WHEN 4 THEN 'RC'  
					   WHEN 5 THEN 'PA'  
					   WHEN 6 THEN 'AS'  
					   WHEN 7 THEN 'MS'  
					   WHEN 8 THEN 'NU'  
					   WHEN 9 THEN 'CN' 
					   WHEN 10 THEN 'CD' 
					   WHEN 11 THEN 'SC'
					   WHEN 12 THEN 'PE' 
					   WHEN 13 THEN 'PT' 
					   WHEN 14 THEN 'DE' ELSE 'NO REGISTRA'  END AS [2],
	RN.IPCODPACIHIJO AS [3],
	CONVERT(VARCHAR,CAST(PAC.IPFECNACI AS DATE),23) AS [4],
	CASE PAC.IPSEXOPAC WHEN 1 THEN 'H' ELSE 'M' END AS [5],
	CASE GE.DESGRUPET WHEN 'INDIGENAS' THEN '1' 
					  WHEN 'PUEBLO ROM GITANOS' THEN '2' 
					  WHEN 'RAIZALES SAN ANDRES Y PROVIDENCIA' THEN '3' 
					  WHEN 'PALENQUEROS DE SAN BASILIO' THEN '4' 
					  WHEN 'AFROCOLOMBIANOS NEGROS MULATOS O AFRODESCENDIENTES' THEN '5' ELSE '6' END AS [6],
	PAC.IPPRIAPEL AS [7],
	PAC.IPSEGAPEL AS [8],
	PAC.IPPRINOMB AS [9],
	PAC.IPSEGNOMB AS [10],
	IIF(LAB.FECHA IS NULL,IIF(FIS.VALOR IS NULL,'NO'
											   ,CONVERT(VARCHAR,CONVERT(DATE,CONVERT(NCHAR(10),FIS.VALOR),103),23))
						 ,'SI') AS [11],
	IIF(LAB.FECHA IS NULL,IIF(FIS.VALOR IS NULL,''
											   ,CONVERT(VARCHAR,CONVERT(DATE,CONVERT(NCHAR(10),FIS.VALOR),103),23))
						 ,LAB.FECHA) AS [12],
	'NA' AS [13],
	'NA' AS [14],
	'NA' AS [15],
	'NA' AS [16],
	'NA' AS [17],
	'NA' AS [18],
	'NA' AS [19],
	'NA' AS [20],
	'NA' AS [21],
	'NA' AS [22],
	'NA' AS [23],
	'NA' AS [24],
	'NA' AS [25],
	'NA' AS [26],
	 1 as 'CANTIDAD',
 CAST(RN.FECHISPAC AS date)  'FECHA BUSQUEDA',
 YEAR(RN.FECHISPAC) AS 'AÑO FECHA BUSQUEDA',
 MONTH(RN.FECHISPAC) AS 'MES AÑO FECHA BUSQUEDA',
 CONCAT(FORMAT(MONTH(RN.FECHISPAC), '00') ,' - ', 
	    CASE MONTH(RN.FECHISPAC) 
	     WHEN 1 THEN 'ENERO'
		 WHEN 2 THEN 'FEBRERO'
		 WHEN 3 THEN 'MARZO'
		 WHEN 4 THEN 'ABRIL'
		 WHEN 5 THEN 'MAYO'
		 WHEN 6 THEN 'JUNIO'
		 WHEN 7 THEN 'JULIO'
		 WHEN 8 THEN 'AGOSTO'
		 WHEN 9 THEN 'SEPTIEMBRE'
		 WHEN 10 THEN 'OCTUBRE'
		 WHEN 11 THEN 'NOVIEMBRE'
		 WHEN 12 THEN 'DICIEMBRE'
		END) AS 'MES NOMBRE FECHA BUSQUEDA',
 FORMAT(DAY(RN.FECHISPAC), '00') AS 'DIA FECHA BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
	dbo.HCRECINAC RN INNER JOIN
	dbo.ADINGRESO ING ON RN.NUMINGRESHIJO=ING.NUMINGRES INNER JOIN
	dbo.INENTIDAD ENT ON ING.CODENTIDA=ENT.CODENTIDA INNER JOIN
	dbo.INPACIENT PAC ON RN.IPCODPACIHIJO=PAC.IPCODPACI LEFT JOIN
	DBO.ADGRUETNI GE ON PAC.CODGRUPOE=GE.CODGRUPOE LEFT JOIN
	CTE_LABORATORIO LAB ON RN.NUMINGRESHIJO=LAB.NUMINGRES AND LAB.VARIABLE=1
														  AND LAB.AUTO=(SELECT MIN(LA.AUTO) FROM CTE_LABORATORIO LA WHERE LAB.NUMINGRES=LA.NUMINGRES AND  LAB.VARIABLE=1) LEFT JOIN
	CTE_EXAMEN_FISICO FIS ON RN.NUMINGRESHIJO=FIS.NUMINGRES AND FIS.VARIABLE=1
															AND FIS.IDHCHISPACA=(SELECT MIN(FI.IDHCHISPACA) FROM CTE_EXAMEN_FISICO FI WHERE FIS.NUMINGRES=FI.NUMINGRES AND FI.VARIABLE=1)
	WHERE (RN.FECHISPAC > CAST(GETDATE() - 380 AS DATE))

UNION ALL

 --TIPO 3 SELECT DE 0 A 5 AÑOS
SELECT
	CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
	ENT.NOMENTIDA AS ENTIDAD,
	ING.NUMINGRES AS INGRESO,
	'' AS FOLIO,
	'DE 0 A 5 AÑOS' AS TIPO,
	3 AS [0],
	--ROW_NUMBER() OVER(ORDER BY PAC.IPCODPACI) AS [1],
	CASE PAC.IPTIPODOC WHEN 1 THEN 'CC'  
						WHEN 2 THEN 'CE' 
						WHEN 3 THEN 'TI'   
						WHEN 4 THEN 'RC'  
						WHEN 5 THEN 'PA'  
						WHEN 6 THEN 'AS'  
						WHEN 7 THEN 'MS'  
						WHEN 8 THEN 'NU'  
						WHEN 9 THEN 'CN' 
						WHEN 10 THEN 'CD' 
						WHEN 11 THEN 'SC'
						WHEN 12 THEN 'PE' 
						WHEN 13 THEN 'PT' 
						WHEN 14 THEN 'DE' ELSE 'NO REGISTRA'  END AS [2],
	PAC.IPCODPACI AS [3],
	CONVERT(VARCHAR,CAST(PAC.IPFECNACI AS DATE),23) AS [4],
	CASE PAC.IPSEXOPAC WHEN 1 THEN 'H' ELSE 'M' END AS [5],
	CASE GE.DESGRUPET WHEN 'INDIGENAS' THEN '1' 
						WHEN 'PUEBLO ROM GITANOS' THEN '2' 
						WHEN 'RAIZALES SAN ANDRES Y PROVIDENCIA' THEN '3' 
						WHEN 'PALENQUEROS DE SAN BASILIO' THEN '4' 
						WHEN 'AFROCOLOMBIANOS NEGROS MULATOS O AFRODESCENDIENTES' THEN '5' ELSE '6' END AS [6],
	PAC.IPPRIAPEL AS [7],
	PAC.IPSEGAPEL AS [8],
	PAC.IPPRINOMB AS [9],
	PAC.IPSEGNOMB AS [10],--SEGUNDO NOMBRE
	CONVERT(VARCHAR,CAST(ING.IFECHAING AS DATE),23) AS [11],--FECHA DE ATENCION
	'04' AS [12],--FINALIDAD CONSULTA
	AGM.CODSERIPS AS [13],--CUPS DEL PROCEDIMIENTO
	IIF(FIS.PESOPACIE<=999,CONVERT(VARCHAR(6),FORMAT(FIS.PESOPACIE,'00.000')),CONVERT(VARCHAR(6),FORMAT(FIS.PESOPACIE/1000,'00.000'))) AS [14],--PESO
	CONVERT(VARCHAR(3),FORMAT(FIS.TALLAPACI,'0##')) AS [15],--TALLA
	ISNULL(FER.FECHA,'') AS [16],--FECHA SULFATO FERROSO
	ISNULL(A.FECHA,'') AS [17],--FECHA SUMINISTRO VITAMINA A
	'' AS [18],--FECHA SUMINISTRO MICRONUTRIENTES
	IIF(HEMO.FECHA IS NULL,IIF(EXAF.VALOR IS NULL,''
												,CONVERT(VARCHAR,CONVERT(DATE,CONVERT(NCHAR(10),EXAF.VALOR),103),23))
						  ,HEMO.FECHA) AS [19],--FECHA HEMOGLOBINA
	IIF(HEMO.VALOR IS NULL,IIF(FHEM.VALOR IS NULL,''
												 ,CONVERT(VARCHAR(4),FHEM.VALOR))
						  ,HEMO.VALOR) AS [20],--RESULTADO HEMOGLOBINA
	'NA' AS [21],
	'NA' AS [22],
	'NA' AS [23],
	'NA' AS [24],
	'NA' AS [25],
	'NA' AS [26],
	 1 as 'CANTIDAD',
 CAST(ING.IFECHAING AS date)  'FECHA BUSQUEDA',
 YEAR(ING.IFECHAING) AS 'AÑO FECHA BUSQUEDA',
 MONTH(ING.IFECHAING) AS 'MES AÑO FECHA BUSQUEDA',
 CONCAT(FORMAT(MONTH(ING.IFECHAING), '00') ,' - ', 
	    CASE MONTH(ING.IFECHAING) 
	     WHEN 1 THEN 'ENERO'
		 WHEN 2 THEN 'FEBRERO'
		 WHEN 3 THEN 'MARZO'
		 WHEN 4 THEN 'ABRIL'
		 WHEN 5 THEN 'MAYO'
		 WHEN 6 THEN 'JUNIO'
		 WHEN 7 THEN 'JULIO'
		 WHEN 8 THEN 'AGOSTO'
		 WHEN 9 THEN 'SEPTIEMBRE'
		 WHEN 10 THEN 'OCTUBRE'
		 WHEN 11 THEN 'NOVIEMBRE'
		 WHEN 12 THEN 'DICIEMBRE'
		END) AS 'MES NOMBRE FECHA BUSQUEDA',
 FORMAT(DAY(ING.IFECHAING), '00') AS 'DIA FECHA BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
	dbo.INPACIENT PAC INNER JOIN
	dbo.ADINGRESO ING ON PAC.IPCODPACI=ING.IPCODPACI AND DATEDIFF(YEAR,PAC.IPFECNACI,GETDATE())<=5 AND ING.TIPOINGRE=1 INNER JOIN
	dbo.HCEXFISIC FIS ON ING.NUMINGRES=FIS.NUMINGRES AND FIS.NUMEFOLIO=(SELECT MAX(FI.NUMEFOLIO) FROM dbo.HCEXFISIC FI WHERE FIS.NUMINGRES=FI.NUMINGRES AND TALLAPACI!='0.0') INNER JOIN
	dbo.INENTIDAD ENT ON ING.CODENTIDA=ENT.CODENTIDA INNER JOIN
	dbo.ADCONCOEX ADC ON ING.NUMINGRES=ADC.NUMINGRES INNER JOIN
	dbo.AGASICITA AGA ON ADC.NUMCONCIT=AGA.CODAUTONU INNER JOIN
	dbo.AGACTIMED AGM ON AGA.CODACTMED=AGM.CODACTMED  AND AGM.CODSERIPS IN ('890201','890205','890301','890305') LEFT JOIN
	dbo.ADGRUETNI GE ON PAC.CODGRUPOE=GE.CODGRUPOE LEFT JOIN
	CTE_MEDICAMENTOS FER ON ING.NUMINGRES=FER.AdmissionNumber AND FER.VARIABLE=1 LEFT JOIN
	CTE_MEDICAMENTOS A ON ING.NUMINGRES=A.AdmissionNumber AND A.VARIABLE=2 LEFT JOIN
	CTE_LABORATORIO HEMO ON ING.IPCODPACI=HEMO.IPCODPACI AND HEMO.AUTO=(SELECT MAX(LA.AUTO) FROM CTE_LABORATORIO LA WHERE HEMO.IPCODPACI=LA.IPCODPACI AND LA.VARIABLE=2
																																					  AND LA.FECHA<ING.IFECHAING) LEFT JOIN
	CTE_EXAMEN_FISICO EXAF ON ING.NUMINGRES=EXAF.NUMINGRES AND EXAF.VARIABLE=2 LEFT JOIN
	CTE_EXAMEN_FISICO FHEM ON ING.NUMINGRES=FHEM.NUMINGRES AND FHEM.VARIABLE=3
	WHERE (ING.IFECHAING > CAST(GETDATE() - 380 AS DATE))

UNION ALL

 ----SELECT DE 6 A 11 AÑOS
SELECT
	CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
	ENT.NOMENTIDA AS ENTIDAD,
	ING.NUMINGRES AS INGRESO,
	'' AS FOLIO,
	'DE 6 A 11 AÑOS' AS TIPO,
	4 AS [0],--tipo de registro
	--ROW_NUMBER() OVER(ORDER BY PAC.IPCODPACI) AS [1],--Consecutivo de registro
	CASE PAC.IPTIPODOC WHEN 1 THEN 'CC'  
						WHEN 2 THEN 'CE' 
						WHEN 3 THEN 'TI'   
						WHEN 4 THEN 'RC'  
						WHEN 5 THEN 'PA'  
						WHEN 6 THEN 'AS'  
						WHEN 7 THEN 'MS'  
						WHEN 8 THEN 'NU'  
						WHEN 9 THEN 'CN' 
						WHEN 10 THEN 'CD' 
						WHEN 11 THEN 'SC'
						WHEN 12 THEN 'PE' 
						WHEN 13 THEN 'PT' 
						WHEN 14 THEN 'DE' ELSE 'NO REGISTRA'  END AS [2],--Tipo de identificacion
	PAC.IPCODPACI AS [3],--Numero de identificacion
	CONVERT(VARCHAR,CAST(PAC.IPFECNACI AS DATE),23) AS [4],--Fecha de nacimiento
	CASE PAC.IPSEXOPAC WHEN 1 THEN 'H' ELSE 'M' END AS [5],--Sexo
	CASE GE.DESGRUPET WHEN 'INDIGENAS' THEN '1' 
						WHEN 'PUEBLO ROM GITANOS' THEN '2' 
						WHEN 'RAIZALES SAN ANDRES Y PROVIDENCIA' THEN '3' 
						WHEN 'PALENQUEROS DE SAN BASILIO' THEN '4' 
						WHEN 'AFROCOLOMBIANOS NEGROS MULATOS O AFRODESCENDIENTES' THEN '5' ELSE '6' END AS [6],--codigo grupo etnico
	PAC.IPPRIAPEL AS [7],--Primer apellido
	PAC.IPSEGAPEL AS [8],--Sgundo apellido
	PAC.IPPRINOMB AS [9],--Primer nombre
	PAC.IPSEGNOMB AS [10],--Segundo nombre
	CONVERT(VARCHAR,CAST(ING.IFECHAING AS DATE),23) AS [11],--Fecha de atencion
	'04' AS [12],--Finalidad de la consulta
	AGM.CODSERIPS AS [13],--Codigo CUPS
	IIF(FIS.PESOPACIE<=999,CONVERT(VARCHAR(6),FORMAT(FIS.PESOPACIE,'00.000')),CONVERT(VARCHAR(6),FORMAT(FIS.PESOPACIE/1000,'00.000'))) AS [14],--Peso
	CONVERT(VARCHAR(3),FORMAT(FIS.TALLAPACI,'0##')) AS [15],--talla 
	IIF(HEMO.FECHA IS NULL,IIF(EXAF.VALOR IS NULL,''
												,CONVERT(VARCHAR,CONVERT(DATE,CONVERT(NCHAR(10),EXAF.VALOR),103),23))
						  ,HEMO.FECHA) AS [16],--Fecha de hemoglobina
	IIF(HEMO.VALOR IS NULL,IIF(FHEM.VALOR IS NULL,''
												 ,CONVERT(VARCHAR(4),FHEM.VALOR))
						  ,HEMO.VALOR) AS [17],--resultado hemoglobina
	'NA' AS [18],
	'NA' AS [19],
	'NA' AS [20],
	'NA' AS [21],
	'NA' AS [22],
	'NA' AS [23],
	'NA' AS [24],
	'NA' AS [25],
	'NA' AS [26],
	 1 as 'CANTIDAD',
 CAST(ING.IFECHAING AS date)  'FECHA BUSQUEDA',
 YEAR(ING.IFECHAING) AS 'AÑO FECHA BUSQUEDA',
 MONTH(ING.IFECHAING) AS 'MES AÑO FECHA BUSQUEDA',
 CONCAT(FORMAT(MONTH(ING.IFECHAING), '00') ,' - ', 
	    CASE MONTH(ING.IFECHAING) 
	     WHEN 1 THEN 'ENERO'
		 WHEN 2 THEN 'FEBRERO'
		 WHEN 3 THEN 'MARZO'
		 WHEN 4 THEN 'ABRIL'
		 WHEN 5 THEN 'MAYO'
		 WHEN 6 THEN 'JUNIO'
		 WHEN 7 THEN 'JULIO'
		 WHEN 8 THEN 'AGOSTO'
		 WHEN 9 THEN 'SEPTIEMBRE'
		 WHEN 10 THEN 'OCTUBRE'
		 WHEN 11 THEN 'NOVIEMBRE'
		 WHEN 12 THEN 'DICIEMBRE'
		END) AS 'MES NOMBRE FECHA BUSQUEDA',
 FORMAT(DAY(ING.IFECHAING), '00') AS 'DIA FECHA BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
	dbo.INPACIENT PAC INNER JOIN
	dbo.ADINGRESO ING ON PAC.IPCODPACI=ING.IPCODPACI AND DATEDIFF(YEAR,PAC.IPFECNACI,GETDATE())>=6 AND DATEDIFF(YEAR,PAC.IPFECNACI,GETDATE())<=11 AND ING.TIPOINGRE=1 INNER JOIN
	dbo.HCEXFISIC FIS ON ING.NUMINGRES=FIS.NUMINGRES AND FIS.NUMEFOLIO=(SELECT MAX(FI.NUMEFOLIO) FROM dbo.HCEXFISIC FI WHERE FIS.NUMINGRES=FI.NUMINGRES AND TALLAPACI!='0.0') INNER JOIN
	dbo.INENTIDAD ENT ON ING.CODENTIDA=ENT.CODENTIDA INNER JOIN
	dbo.ADCONCOEX ADC ON ING.NUMINGRES=ADC.NUMINGRES INNER JOIN
	dbo.AGASICITA AGA ON ADC.NUMCONCIT=AGA.CODAUTONU INNER JOIN
	dbo.AGACTIMED AGM ON AGA.CODACTMED=AGM.CODACTMED  AND AGM.CODSERIPS IN ('890201','890205','890301','890305') LEFT JOIN
	dbo.ADGRUETNI GE ON PAC.CODGRUPOE=GE.CODGRUPOE LEFT JOIN
		CTE_LABORATORIO HEMO ON ING.IPCODPACI=HEMO.IPCODPACI AND HEMO.AUTO=(SELECT MAX(LA.AUTO) FROM CTE_LABORATORIO LA WHERE HEMO.IPCODPACI=LA.IPCODPACI AND LA.VARIABLE=2
																																						  AND LA.FECHA<ING.IFECHAING) LEFT JOIN
	CTE_EXAMEN_FISICO EXAF ON ING.NUMINGRES=EXAF.NUMINGRES AND EXAF.VARIABLE=2 LEFT JOIN
	CTE_EXAMEN_FISICO FHEM ON ING.NUMINGRES=FHEM.NUMINGRES AND FHEM.VARIABLE=3
	WHERE (ING.IFECHAING > CAST(GETDATE() - 380 AS DATE))

UNION ALL
 ----SELECT DE 12 A 17 AÑOS
SELECT
	CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
	ENT.NOMENTIDA AS ENTIDAD,
	ING.NUMINGRES AS INGRESO,
	'' AS FOLIO,
	'DE 12 A 17 AÑOS' AS TIPO,
	5 AS [0],
	--ROW_NUMBER() OVER(ORDER BY PAC.IPCODPACI) AS [1],
	CASE PAC.IPTIPODOC WHEN 1 THEN 'CC'  
						WHEN 2 THEN 'CE' 
						WHEN 3 THEN 'TI'   
						WHEN 4 THEN 'RC'  
						WHEN 5 THEN 'PA'  
						WHEN 6 THEN 'AS'  
						WHEN 7 THEN 'MS'  
						WHEN 8 THEN 'NU'  
						WHEN 9 THEN 'CN' 
						WHEN 10 THEN 'CD' 
						WHEN 11 THEN 'SC'
						WHEN 12 THEN 'PE' 
						WHEN 13 THEN 'PT' 
						WHEN 14 THEN 'DE' ELSE 'NO REGISTRA'  END AS [2],
	PAC.IPCODPACI AS [3],
	CONVERT(VARCHAR,CAST(PAC.IPFECNACI AS DATE),23) AS [4],
	CASE PAC.IPSEXOPAC WHEN 1 THEN 'H' ELSE 'M' END AS [5],
	CASE GE.DESGRUPET WHEN 'INDIGENAS' THEN '1' 
						WHEN 'PUEBLO ROM GITANOS' THEN '2' 
						WHEN 'RAIZALES SAN ANDRES Y PROVIDENCIA' THEN '3' 
						WHEN 'PALENQUEROS DE SAN BASILIO' THEN '4' 
						WHEN 'AFROCOLOMBIANOS NEGROS MULATOS O AFRODESCENDIENTES' THEN '5' ELSE '6' END AS [6],
	PAC.IPPRIAPEL AS [7],
	PAC.IPSEGAPEL AS [8],
	PAC.IPPRINOMB AS [9],
	PAC.IPSEGNOMB AS [10],--Segundo nombre
	CONVERT(VARCHAR,CAST(ING.IFECHAING AS DATE),23) AS [11],--Fecha de atencion
	'05' AS [12],--Finalidad de consulta
	AGM.CODSERIPS AS [13],--Codigo del procedimiento
	IIF(FIS.PESOPACIE<=999,CONVERT(VARCHAR(6),FORMAT(FIS.PESOPACIE,'00.000')),CONVERT(VARCHAR(6),FORMAT(FIS.PESOPACIE/1000,'00.000'))) AS [14],--Peso
	CONVERT(VARCHAR(3),FORMAT(FIS.TALLAPACI,'0##')) AS [15],--Talla
	IIF(HEMO.FECHA IS NULL,IIF(EXAF.VALOR IS NULL,''
												,CONVERT(VARCHAR,CONVERT(DATE,CONVERT(NCHAR(10),EXAF.VALOR),103),23))
						  ,HEMO.FECHA) AS [16],--Fecha Hemoglobina
	IIF(HEMO.VALOR IS NULL,IIF(FHEM.VALOR IS NULL,''
												 ,CONVERT(VARCHAR(4),FHEM.VALOR))
						  ,HEMO.VALOR) AS [17],--Resultado Hemoglobina
	'NA' AS [18],
	'NA' AS [19],
	'NA' AS [20],
	'NA' AS [21],
	'NA' AS [22],
	'NA' AS [23],
	'NA' AS [24],
	'NA' AS [25],
	'NA' AS [26],
	 1 as 'CANTIDAD',
 CAST(ING.IFECHAING AS date)  'FECHA BUSQUEDA',
 YEAR(ING.IFECHAING) AS 'AÑO FECHA BUSQUEDA',
 MONTH(ING.IFECHAING) AS 'MES AÑO FECHA BUSQUEDA',
 CONCAT(FORMAT(MONTH(ING.IFECHAING), '00') ,' - ', 
	    CASE MONTH(ING.IFECHAING) 
	     WHEN 1 THEN 'ENERO'
		 WHEN 2 THEN 'FEBRERO'
		 WHEN 3 THEN 'MARZO'
		 WHEN 4 THEN 'ABRIL'
		 WHEN 5 THEN 'MAYO'
		 WHEN 6 THEN 'JUNIO'
		 WHEN 7 THEN 'JULIO'
		 WHEN 8 THEN 'AGOSTO'
		 WHEN 9 THEN 'SEPTIEMBRE'
		 WHEN 10 THEN 'OCTUBRE'
		 WHEN 11 THEN 'NOVIEMBRE'
		 WHEN 12 THEN 'DICIEMBRE'
		END) AS 'MES NOMBRE FECHA BUSQUEDA',
 FORMAT(DAY(ING.IFECHAING), '00') AS 'DIA FECHA BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
	dbo.INPACIENT PAC INNER JOIN
	dbo.ADINGRESO ING ON PAC.IPCODPACI=ING.IPCODPACI AND DATEDIFF(YEAR,PAC.IPFECNACI,GETDATE())>=12 AND DATEDIFF(YEAR,PAC.IPFECNACI,GETDATE())<=17 AND ING.TIPOINGRE=1 INNER JOIN
	dbo.HCEXFISIC FIS ON ING.NUMINGRES=FIS.NUMINGRES AND FIS.NUMEFOLIO=(SELECT MAX(FI.NUMEFOLIO) FROM dbo.HCEXFISIC FI WHERE FIS.NUMINGRES=FI.NUMINGRES AND TALLAPACI!='0.0') INNER JOIN
	dbo.INENTIDAD ENT ON ING.CODENTIDA=ENT.CODENTIDA INNER JOIN
	dbo.ADCONCOEX ADC ON ING.NUMINGRES=ADC.NUMINGRES INNER JOIN
	dbo.AGASICITA AGA ON ADC.NUMCONCIT=AGA.CODAUTONU INNER JOIN
	dbo.AGACTIMED AGM ON AGA.CODACTMED=AGM.CODACTMED  AND AGM.CODSERIPS IN ('890201','890205','890301','890305') LEFT JOIN
	dbo.ADGRUETNI GE ON PAC.CODGRUPOE=GE.CODGRUPOE LEFT JOIN
		CTE_LABORATORIO HEMO ON ING.IPCODPACI=HEMO.IPCODPACI AND HEMO.AUTO=(SELECT MAX(LA.AUTO) FROM CTE_LABORATORIO LA WHERE HEMO.IPCODPACI=LA.IPCODPACI AND LA.VARIABLE=2
																																						  AND LA.FECHA<ING.IFECHAING) LEFT JOIN
	CTE_EXAMEN_FISICO EXAF ON ING.NUMINGRES=EXAF.NUMINGRES AND EXAF.VARIABLE=2 LEFT JOIN
	CTE_EXAMEN_FISICO FHEM ON ING.NUMINGRES=FHEM.NUMINGRES AND FHEM.VARIABLE=3
	WHERE (ING.IFECHAING > CAST(GETDATE() - 380 AS DATE))

UNION ALL

---SELECT DE GESTANTES
SELECT
	CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
	ENT.NOMENTIDA AS ENTIDAD,
	AG.NUMINGRES AS INGRESO,
	AG.NUMEFOLIO AS FOLIO,
	'MUJERES GESTANTES' AS TIPO,
	6 AS [0],
	--ROW_NUMBER() OVER(ORDER BY PAC.IPCODPACI) AS [1],
	CASE PAC.IPTIPODOC WHEN 1 THEN 'CC'  
						WHEN 2 THEN 'CE' 
						WHEN 3 THEN 'TI'   
						WHEN 4 THEN 'RC'  
						WHEN 5 THEN 'PA'  
						WHEN 6 THEN 'AS'  
						WHEN 7 THEN 'MS'  
						WHEN 8 THEN 'NU'  
						WHEN 9 THEN 'CN' 
						WHEN 10 THEN 'CD' 
						WHEN 11 THEN 'SC'
						WHEN 12 THEN 'PE' 
						WHEN 13 THEN 'PT' 
						WHEN 14 THEN 'DE' ELSE 'NO REGISTRA'  END AS [2],
	PAC.IPCODPACI AS [3],
	PAC.IPPRIAPEL AS [4],
	PAC.IPSEGAPEL AS [5],
	PAC.IPPRINOMB AS [6],
	PAC.IPSEGNOMB AS [7],
	CONVERT(VARCHAR,CAST(PAC.IPFECNACI AS DATE),23) AS [8],
	CONVERT(VARCHAR(2),FORMAT(AG.NOMSEMGES,'0#')) AS [9],
	CASE GE.DESGRUPET WHEN 'INDIGENAS' THEN '1' 
					WHEN 'PUEBLO ROM GITANOS' THEN '2' 
					WHEN 'RAIZALES SAN ANDRES Y PROVIDENCIA' THEN '3' 
					WHEN 'PALENQUEROS DE SAN BASILIO' THEN '4' 
					WHEN 'AFROCOLOMBIANOS NEGROS MULATOS O AFRODESCENDIENTES' THEN '5' ELSE '6' END AS [10],
	CONVERT(VARCHAR,CAST(AG.FECHISPAC AS DATE),23) AS [11],
	'06' AS [12],
	AGM.CODSERIPS AS [13],
	ISNULL(CONVERT(VARCHAR,CAST(AF.FECHA AS DATE),23),'') AS [14],
	ISNULL(CONVERT(VARCHAR,CAST(FE.FECHA AS DATE),23),'') AS [15],
	ISNULL(CONVERT(VARCHAR,CAST(CAL.FECHA AS DATE),23),'') AS [16],
	ISNULL(CONVERT(VARCHAR,CAST(HPB.FECHA AS DATE),23),'') AS [17],
	CASE HPB.VALOR WHEN 'NEGATIVO' THEN '2'
				   WHEN 'POSITIVO' THEN '1' ELSE '' END AS [18],
	ISNULL(CONVERT(VARCHAR,CAST(SIF.FECHA AS DATE),23),'') AS [19],
	CASE WHEN SIF.VALOR LIKE '%REACTIVA%' THEN '1'
		 WHEN SIF.VALOR LIKE '%NO REACTIVA%' THEN '2' ELSE '' END [20],
	ISNULL(CONVERT(VARCHAR,CAST(HC.FECHISPAC AS DATE),23),'') AS [21],
	ISNULL(CONVERT(VARCHAR,CAST(VIH.FECHA AS DATE),23),'') AS [22],
	CASE VIH.VALOR WHEN 'NEGATIVO' THEN '1'
				   WHEN 'POSITIVO' THEN '2' ELSE '' END AS [23],
	IIF(HEMO.FECHA IS NULL,IIF(EXAF.VALOR IS NULL,''
												,CONVERT(VARCHAR,CONVERT(DATE,CONVERT(NCHAR(10),EXAF.VALOR),103),23))
						  ,HEMO.FECHA) AS [24],
	IIF(HEMO.VALOR IS NULL,IIF(FHEM.VALOR IS NULL,''
												 ,CONVERT(VARCHAR(4),FHEM.VALOR))
						  ,HEMO.VALOR) AS [25],
	ISNULL(CONVERT(VARCHAR,CAST(LAC.FECHISPAC AS DATE),23),'') AS [26],
	 1 as 'CANTIDAD',
	CAST(AG.FECHISPAC AS date)  'FECHA BUSQUEDA',
	YEAR(AG.FECHISPAC) AS 'AÑO FECHA BUSQUEDA',
	MONTH(AG.FECHISPAC) AS 'MES AÑO FECHA BUSQUEDA',
	CONCAT(FORMAT(MONTH(AG.FECHISPAC), '00') ,' - ', 
	    CASE MONTH(AG.FECHISPAC) 
	     WHEN 1 THEN 'ENERO'
		 WHEN 2 THEN 'FEBRERO'
		 WHEN 3 THEN 'MARZO'
		 WHEN 4 THEN 'ABRIL'
		 WHEN 5 THEN 'MAYO'
		 WHEN 6 THEN 'JUNIO'
		 WHEN 7 THEN 'JULIO'
		 WHEN 8 THEN 'AGOSTO'
		 WHEN 9 THEN 'SEPTIEMBRE'
		 WHEN 10 THEN 'OCTUBRE'
		 WHEN 11 THEN 'NOVIEMBRE'
		 WHEN 12 THEN 'DICIEMBRE'
		END) AS 'MES NOMBRE FECHA BUSQUEDA',
 FORMAT(DAY(AG.FECHISPAC), '00') AS 'DIA FECHA BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
	dbo.INPACIENT PAC INNER JOIN
	dbo.HCANTGINE AG ON PAC.IPCODPACI=AG.IPCODPACI AND AG.NOMSEMGES!='0.0' INNER JOIN
	dbo.ADINGRESO ING ON AG.NUMINGRES=ING.NUMINGRES AND ING.TIPOINGRE=1 INNER JOIN
	dbo.ADCONCOEX ADC ON ING.NUMINGRES=ADC.NUMINGRES INNER JOIN
	dbo.AGASICITA AGA ON ADC.NUMCONCIT=AGA.CODAUTONU INNER JOIN
	dbo.AGACTIMED AGM ON AGA.CODACTMED=AGM.CODACTMED AND AGM.CODSERIPS IN ('890201','890301','890305','890203','890303','890206','890306') AND AGM.DESACTMED NOT LIKE '%ODONTOLOGIA%' LEFT JOIN
	dbo.INENTIDAD ENT ON PAC.CODENTIDA=ENT.CODENTIDA LEFT JOIN
	dbo.ADGRUETNI GE ON PAC.CODGRUPOE=GE.CODGRUPOE LEFT JOIN
	CTE_MEDICAMENTOS AF ON AG.NUMINGRES=AF.AdmissionNumber AND AF.VARIABLE=3 LEFT JOIN
	CTE_MEDICAMENTOS FE ON AG.NUMINGRES=FE.AdmissionNumber AND FE.VARIABLE=1 LEFT JOIN
	CTE_MEDICAMENTOS CAL ON AG.NUMINGRES=CAL.AdmissionNumber AND CAL.VARIABLE=4 LEFT JOIN
	CTE_LABORATORIO VIH ON ING.IPCODPACI=VIH.IPCODPACI AND VIH.ANALITO LIKE '%VIH%' AND VIH.AUTO=(SELECT MAX(LA.AUTO) FROM CTE_LABORATORIO LA WHERE VIH.IPCODPACI=LA.IPCODPACI AND LA.VARIABLE=3
																																							AND CAST(LA.FECHA AS DATE)<=CAST(AG.FECHISPAC AS date))LEFT JOIN
	CTE_LABORATORIO HPB ON ING.IPCODPACI=HPB.IPCODPACI AND HPB.AUTO=(SELECT MAX(LA.AUTO) FROM CTE_LABORATORIO LA WHERE HPB.IPCODPACI=LA.IPCODPACI AND LA.VARIABLE=4
																																							AND CAST(LA.FECHA AS DATE)<=CAST(AG.FECHISPAC AS date))LEFT JOIN
	CTE_LABORATORIO SIF ON ING.IPCODPACI=SIF.IPCODPACI AND SIF.AUTO=(SELECT MAX(LA.AUTO) FROM CTE_LABORATORIO LA WHERE SIF.IPCODPACI=LA.IPCODPACI AND LA.VARIABLE=5
																																							AND CAST(LA.FECHA AS DATE)<=CAST(AG.FECHISPAC AS date))LEFT JOIN
	dbo.HCHISPACA HC ON AG.NUMINGRES=HC.NUMINGRES AND HC.IDMODELOHC='26' LEFT JOIN
	CTE_LABORATORIO HEMO ON ING.IPCODPACI=HEMO.IPCODPACI AND HEMO.AUTO=(SELECT MAX(LA.AUTO) FROM CTE_LABORATORIO LA WHERE HEMO.IPCODPACI=LA.IPCODPACI AND LA.VARIABLE=2
																																					  AND CAST(LA.FECHA AS DATE)<CAST(AG.FECHISPAC AS date)) LEFT JOIN
	CTE_EXAMEN_FISICO EXAF ON ING.NUMINGRES=EXAF.NUMINGRES AND EXAF.VARIABLE=2 LEFT JOIN
	CTE_EXAMEN_FISICO FHEM ON ING.NUMINGRES=FHEM.NUMINGRES AND FHEM.VARIABLE=3 LEFT JOIN
	dbo.HCHISPACA LAC ON AG.NUMINGRES=LAC.NUMINGRES AND LAC.IDMODELOHC='36'
	WHERE (AG.FECHISPAC > CAST(GETDATE() - 380 AS DATE))

UNION ALL

---SELECT ATENCION AL PARTO
SELECT
	CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
	ENT.NOMENTIDA AS ENTIDAD,
	AP.NUMINGRES AS INGRESO,
	'' AS FOLIO,
	'DETALLE PARTO' AS TIPO,
	7 AS [0],
	--ROW_NUMBER() OVER(ORDER BY PAC.IPCODPACI) AS [1],
	CASE PAC.IPTIPODOC WHEN 1 THEN 'CC'  
						WHEN 2 THEN 'CE' 
						WHEN 3 THEN 'TI'   
						WHEN 4 THEN 'RC'  
						WHEN 5 THEN 'PA'  
						WHEN 6 THEN 'AS'  
						WHEN 7 THEN 'MS'  
						WHEN 8 THEN 'NU'  
						WHEN 9 THEN 'CN' 
						WHEN 10 THEN 'CD' 
						WHEN 11 THEN 'SC'
						WHEN 12 THEN 'PE' 
						WHEN 13 THEN 'PT' 
						WHEN 14 THEN 'DE' ELSE 'NO REGISTRA'  END AS [2],
	PAC.IPCODPACI AS [3],
	PAC.IPPRIAPEL AS [4],
	PAC.IPSEGAPEL AS [5],
	PAC.IPPRINOMB AS [6],
	PAC.IPSEGNOMB AS [7],
	CASE GE.DESGRUPET WHEN 'INDIGENAS' THEN '1' 
					  WHEN 'PUEBLO ROM GITANOS' THEN '2' 
					  WHEN 'RAIZALES SAN ANDRES Y PROVIDENCIA' THEN '3' 
					  WHEN 'PALENQUEROS DE SAN BASILIO' THEN '4' 
					  WHEN 'AFROCOLOMBIANOS NEGROS MULATOS O AFRODESCENDIENTES' THEN '5' ELSE '6' END AS [8],
	CONVERT(VARCHAR,CAST(AP.FECHANACIM AS DATE),23) AS [9],
	'01' AS [10],
	IIF(QX.NUMINGRES IS NULL,'735910','740100') AS [11],
	IIF(SIF.FECHA IS NULL,'2','1') AS [12],
	ISNULL(CONVERT(VARCHAR,CAST(SIF.FECHA AS DATE),23),'') AS [13],
	CASE WHEN SIF.VALOR LIKE '%REACTIVA%' THEN '1'
		 WHEN SIF.VALOR LIKE '%NO REACTIVA%' THEN '2' ELSE '' END [14],
	IIF(HC.FECHISPAC IS NULL,'2','1') AS [15],
	ISNULL(CONVERT(VARCHAR,CAST(HC.FECHISPAC AS DATE),23),'') AS [16],
	IIF(VIH.FECHA IS NULL,'2','1') AS [17],
	ISNULL(CONVERT(VARCHAR,CAST(VIH.FECHA AS DATE),23),'') AS [18],
	CASE VIH.VALOR WHEN 'NEGATIVO' THEN '1'
				   WHEN 'POSITIVO' THEN '2' ELSE '' END AS [19],
	IIF(PRE.FECHA IS NULL,'2','1') AS [20],
	ISNULL(CONVERT(VARCHAR,CAST(PRE.FECHA AS DATE),23),'') AS [21],
	'NA' AS [22],
	'NA' AS [23],
	'NA' AS [24],
	'NA' AS [25],
	'NA' AS [26],
	 1 as 'CANTIDAD',
 CAST(AP.FECHISPAC AS date)  'FECHA BUSQUEDA',
 YEAR(AP.FECHISPAC) AS 'AÑO FECHA BUSQUEDA',
 MONTH(AP.FECHISPAC) AS 'MES AÑO FECHA BUSQUEDA',
 CONCAT(FORMAT(MONTH(AP.FECHISPAC), '00') ,' - ', 
	    CASE MONTH(AP.FECHISPAC) 
	     WHEN 1 THEN 'ENERO'
		 WHEN 2 THEN 'FEBRERO'
		 WHEN 3 THEN 'MARZO'
		 WHEN 4 THEN 'ABRIL'
		 WHEN 5 THEN 'MAYO'
		 WHEN 6 THEN 'JUNIO'
		 WHEN 7 THEN 'JULIO'
		 WHEN 8 THEN 'AGOSTO'
		 WHEN 9 THEN 'SEPTIEMBRE'
		 WHEN 10 THEN 'OCTUBRE'
		 WHEN 11 THEN 'NOVIEMBRE'
		 WHEN 12 THEN 'DICIEMBRE'
		END) AS 'MES NOMBRE FECHA BUSQUEDA',
 FORMAT(DAY(AP.FECHISPAC), '00') AS 'DIA FECHA BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
	dbo.HCRECINAC AP INNER JOIN
	dbo.INPACIENT PAC ON AP.IPCODPACI=PAC.IPCODPACI AND AP.NUMEFOLIO=(SELECT MIN(A.NUMEFOLIO) FROM dbo.HCRECINAC A WHERE AP.IPCODPACI=A.IPCODPACI) INNER JOIN
	dbo.INENTIDAD ENT ON PAC.CODENTIDA=ENT.CODENTIDA LEFT JOIN
	dbo.ADGRUETNI GE ON PAC.CODGRUPOE=GE.CODGRUPOE LEFT JOIN
	dbo.HCQXINFOR QX ON AP.NUMINGRES=QX.NUMINGRES AND CODSERIPS IN ('740003','740002') LEFT JOIN
	CTE_LABORATORIO VIH ON AP.IPCODPACI=VIH.IPCODPACI AND VIH.ANALITO LIKE '%VIH%' AND VIH.AUTO=(SELECT MAX(LA.AUTO) FROM CTE_LABORATORIO LA WHERE VIH.IPCODPACI=LA.IPCODPACI AND LA.VARIABLE=3
																																				 AND CAST(LA.FECHA AS DATE)<=CAST(AP.FECHISPAC AS DATE))LEFT JOIN
	CTE_LABORATORIO SIF ON AP.IPCODPACI=SIF.IPCODPACI AND SIF.AUTO=(SELECT MAX(LA.AUTO) FROM CTE_LABORATORIO LA WHERE SIF.IPCODPACI=LA.IPCODPACI AND LA.VARIABLE=5
																																				 AND CAST(LA.FECHA AS DATE)<=CAST(AP.FECHISPAC AS DATE))LEFT JOIN
	dbo.HCHISPACA HC ON AP.NUMINGRES=HC.NUMINGRES AND HC.IDMODELOHC='26' LEFT JOIN
	CTE_MEDICAMENTOS PRE ON AP.IPCODPACI=PRE.IPCODPACI AND PRE.VARIABLE=5 AND PRE.Id=(SELECT TOP 1 MAX(MED.Id) FROM CTE_MEDICAMENTOS MED WHERE PRE.IPCODPACI=MED.IPCODPACI AND CAST(MED.FECHA AS DATE)<=CAST(AP.FECHISPAC AS DATE)																																						AND MED.VARIABLE=5)
	WHERE (AP.FECHISPAC > CAST(GETDATE() - 380 AS DATE))
)

SELECT 
	ID_COMPANY,
	ENTIDAD,
	INGRESO,
	FOLIO,
	TIPO,
	[0],ROW_NUMBER ( ) OVER(PARTITION BY [AÑO FECHA BUSQUEDA],[MES AÑO FECHA BUSQUEDA] ORDER BY [0]) AS [1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18],[19],[20],
	[21],[22],[23],[24],[25],[26],
	CANTIDAD,[FECHA BUSQUEDA],[AÑO FECHA BUSQUEDA],[MES AÑO FECHA BUSQUEDA],[MES NOMBRE FECHA BUSQUEDA],
	[DIA FECHA BUSQUEDA],ULT_ACTUAL
FROM CTE_TIPOS 
