-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewConsultDetailIRAandEDA
-- Extracted by Fabric SQL Extractor SPN v3.9.0


/*******************************************************************************************************************
Nombre: [Report].[ViewConsultDetailIRAandEDA]
Tipo:Vista
Observacion:Detalle de las vistas de [Report].[ViewConsultationMorbidityIRA] y [Report].[ViewConsultationMorbidityEDA]
Profesional:Nilsson Miguel Galindo
Fecha:20-02-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico:Nilsson Galindo
Fecha:08-03-2023
Ovservaciones: SE modifica la relacion de la tabla HCHISPACA no con el numero de folio sino con el tipo de ingreso de la misma tabla
				esto se realizo para que la fecha de la historia clinica concuerde con la fecha de atención de la vista [Report].[ViewMorbilidad]
--------------------------------------
Version 2
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:09-06-2023
Observaciones: Se modifican los Dx para eda pasando de tener en cuenta 3 a 61 Dx
___________________________________________________________________________________
Version 3
Persona que modifico:Amira Gil Meneses
Observación: Se realiza CTE para los Diagnosticos Relacionados
Fecha: 31-07-2023

***********************************************************************************************************************************/

CREATE VIEW [Report].[ViewConsultDetailIRAandEDA] AS

WITH TIPO_INFECCION AS 
 (
  SELECT 
   CODDIAGNO 'DIAGNOSTICO',
   NOMDIAGNO 'DIAG. NOMBRE',
   'IRA' AS TIPO_INFECCION
  FROM 
   INDIAGNOS
  WHERE 
   CODDIAGNO  
	IN ('J00X','J010','J011','J012','J013','J014','J018','J019','J020','J028','J029','J030','J038','J039','J040','J041','J042','J050',
	    'J051','J060','J068','J069','J09X','J100','J101','J108','J110','J111','J118','J120','J121','J122','J123','J128','J129','J13X',
		'J14X','J150','J151','J152','J153','J154','J155','J156','J157','J158','J159','J160','J168','J170','J171','J172','J173','J178',
		'J180','J181','J182','J188','J189','J200','J201','J202','J203','J204','J205','J206','J207','J208','J209','J210','J211','J218',
		'J219','J22X','U071','U072','B342')
  UNION ALL
  SELECT 
   CODDIAGNO 'DIAGNOSTICO',
   NOMDIAGNO 'DIAG. NOMBRE',
   'EDA' AS TIPO_INFECCION
  FROM 
   INDIAGNOS
  WHERE 
   CODDIAGNO BETWEEN 'A000' AND 'A09X'
),

CTE_DIAGNOSTICO_RELACIONADOS AS
 (
  SELECT 
   ROW_NUMBER ( )   
   OVER (PARTITION BY IND.IPCODPACI  order by IND.NUMEFOLIO DESC) AS NUMEFOLIO,
   IND.NUMINGRES,
   TP.DIAGNOSTICO,
   IND.CODDIAGNO AS [COD DX RELACIONADO],
   DG.NOMDIAGNO AS [NOM DX RELACIONADO]
  FROM 
   INDIAGNOP IND 
   INNER JOIN DBO.INDIAGNOS DG ON IND.CODDIAGNO=DG.CODDIAGNO
   INNER JOIN TIPO_INFECCION TP ON TP.DIAGNOSTICO=DG.CODDIAGNO
  WHERE 
   IND.CODDIAPRI <> 1
 ),

CTE_CONSULTAS_MORBILIDAD_IRA_Y_EDA  AS 
 (
  SELECT 
   TI.TIPO_INFECCION,
   ADC.NOMCENATE AS 'NOMBRE CENTRO ATENCION', 
   INU.UFUDESCRI AS 'NOMBRE UNIDAD FUNCIONAL',
   HA.Code AS 'CODIGO ENTIDAD',
   HA.NAME AS 'ENTIDAD',
   HC.NUMINGRES AS INGRESO,
   HC.IPCODPACI AS IDENTIFICACION, 
   INP.IPNOMCOMP AS PACIENTE, 
   DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) 'EDAD',
   CASE INP.IPSEXO WHEN 'M' THEN 'FEMENINO' WHEN 'H' THEN 'MASCULINO' END 'SEXO', 
   CASE HC.INDICAPAC WHEN '11' THEN 'SI' ELSE 'NO' END AS 'MORTALIDAD',
   IPR.NOMMEDICO AS 'PROFESIONAL', 
   INE.DESESPECI AS 'ESPECIALIDAD', 
   CAST(HC.FECHISPAC AS DATE) AS 'FECHA HISTORIA CLINICA', 
   YEAR(HC.FECHISPAC) AS 'AÑO HISTORIA CLINICA', 
   MONTH(HC.FECHISPAC) AS 'MES HISTORIA CLINICA', 
   DAY(HC.FECHISPAC) AS 'DIA HISTORIA CLINICA', 
   DATEDIFF(WW, DATEADD(DD, DAY(HC.FECHISPAC) * -1, HC.FECHISPAC) + 1, HC.FECHISPAC) + 1 AS 'SEMANA DEL MES',
   TI.DIAGNOSTICO AS 'CODIGO DIAGNOSTICO', 
   TI.[DIAG. NOMBRE] AS 'NOMBRE DIAGNOSTICO',
   DXR.[COD DX RELACIONADO] 'DIAGNOSTICO RELACIONADO',
   DXR.[NOM DX RELACIONADO] 'DIAG RELACIONADO NOMBRE',
   CASE IND.CODDIAPRI WHEN 1 THEN 'SI' ELSE 'NO' END AS 'DIAGNOSTICO PRINCIPAL',

   CASE HNF.CLASIFICACIONCASO WHEN 1 THEN 1 ELSE 0 END AS 'SOSPECHOSO',
   CASE HNF.CLASIFICACIONCASO WHEN 2 THEN 1 ELSE 0 END AS 'PROBABLE',
   CASE HNF.CLASIFICACIONCASO WHEN 3 THEN 1 ELSE 0 END AS 'CONF.LABORATORIO',
   CASE HNF.CLASIFICACIONCASO WHEN 4 THEN 1 ELSE 0 END AS 'CONF.CLINICO',
   CASE HNF.CLASIFICACIONCASO WHEN 5 THEN 1 ELSE 0 END AS 'CONF.EPIDEIMIOLOGICO',

   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) < 1 THEN 1 ELSE 0 END AS 'MENORES DE 1',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 1 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 4 THEN 1 ELSE 0 END AS 'DE 1 A 4',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 5 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 9 THEN 1 ELSE 0 END AS 'DE 5 A 9',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 10 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 14 THEN 1 ELSE 0 END AS 'DE 10 A 14',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 15 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 19 THEN 1 ELSE 0 END AS 'DE 15 A 19',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 20 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 24 THEN 1 ELSE 0 END AS 'DE 20 A 24',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 25 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 29 THEN 1 ELSE 0 END AS 'DE 25 A 29',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 30 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 34 THEN 1 ELSE 0 END AS 'DE 30 A 34',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 35 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 39 THEN 1 ELSE 0 END AS 'DE 35 A 39',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 40 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 44 THEN 1 ELSE 0 END AS 'DE 40 A 44',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 45 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 49 THEN 1 ELSE 0 END AS 'DE 45 A 49',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 50 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 54 THEN 1 ELSE 0 END AS 'DE 50 A 54',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 55 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 59 THEN 1 ELSE 0 END AS 'DE 55 A 59',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 60 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 64 THEN 1 ELSE 0 END AS 'DE 60 A 64',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 65 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 69 THEN 1 ELSE 0 END AS 'DE 65 A 69',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 70 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 74 THEN 1 ELSE 0 END AS 'DE 70 A 74',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 75 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 79 THEN 1 ELSE 0 END AS 'DE 75 A 79',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 80 THEN 1 ELSE 0 END AS 'MAYORES DE 80',

   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) = 1 THEN 1 ELSE 0 END AS 'DE 1 AÑO',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 2 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 4 THEN 1 ELSE 0 END AS 'DE 2 A 4',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 5 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 19 THEN 1 ELSE 0 END AS 'DE 5 A 19',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 20 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 39 THEN 1 ELSE 0 END AS 'DE 20 A 39',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 40 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 59 THEN 1 ELSE 0 END AS 'DE 40 A 59',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 60 THEN 1 ELSE 0 END AS 'MAYORES DE 60'

   FROM 
    INDIAGNOP IND
    INNER JOIN HCHISPACA HC ON IND.NUMINGRES = HC.NUMINGRES AND IND.IPCODPACI = HC.IPCODPACI AND IND.NUMEFOLIO = HC.NUMEFOLIO AND IND.CODDIAPRI = 1
    INNER JOIN TIPO_INFECCION TI ON IND.CODDIAGNO = TI.DIAGNOSTICO
    LEFT JOIN CTE_DIAGNOSTICO_RELACIONADOS AS DXR ON DXR.[COD DX RELACIONADO] = IND.CODDIAGNO AND HC.NUMINGRES = DXR.NUMINGRES AND HC.NUMEFOLIO = DXR.NUMEFOLIO 
    INNER JOIN INPACIENT INP ON HC.IPCODPACI = INP.IPCODPACI 
    INNER JOIN ADINGRESO AD ON HC.NUMINGRES = AD.NUMINGRES
    INNER JOIN INDIAGNOS INS ON IND.CODDIAGNO = INS.CODDIAGNO 
    INNER JOIN ADCENATEN ADC ON HC.CODCENATE = ADC.CODCENATE
    INNER JOIN INUNIFUNC INU ON HC.UFUCODIGO = INU.UFUCODIGO 
    INNER JOIN INPROFSAL IPR ON HC.CODPROSAL = IPR.CODPROSAL
    INNER JOIN INESPECIA INE ON HC.CODESPTRA = INE.CODESPECI 
    LEFT JOIN dbo.HCFICHANOTIFICACION HNF ON HC.NUMINGRES=HNF.NUMINGRES
    INNER JOIN Contract.HealthAdministrator HA ON HA.Id = AD.GENCONENTITY
 )

SELECT --TOP 10
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 *,
 1 as 'CANTIDAD',
 CAST([FECHA HISTORIA CLINICA] AS date) AS 'FECHA BUSQUEDA',
 YEAR([FECHA HISTORIA CLINICA]) AS 'AÑO BUSQUEDA',
 MONTH([FECHA HISTORIA CLINICA]) AS 'MES BUSQUEDA',
 CONCAT(FORMAT(MONTH([FECHA HISTORIA CLINICA]), '00') ,' - ', 
  CASE MONTH([FECHA HISTORIA CLINICA]) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM CTE_CONSULTAS_MORBILIDAD_IRA_Y_EDA 