-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_V2_FAC_REPORTE_LABORATORIOS_POR_RECONOCER_HOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[View_V2_FAC_REPORTE_LABORATORIOS_POR_RECONOCER_HOS]
AS


WITH CTE_LABORATORIOS_UNICOS
----CTE PARA IDENTIFICAR LOS INGRESOS UNICOS DE LABORATORIOS QUE ESTAN PENDIENTES DE RECONOCER - HOSPITALARIOS
AS
(
    SELECT DISTINCT ING.NUMINGRES ,ING.IPCODPACI,ING.IESTADOIN
    FROM dbo.HCORDLABO A INNER JOIN
	dbo.ADINGRESO ING ON A.NUMINGRES=ING.NUMINGRES INNER JOIN 
	dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
	WHERE ING.TIPOINGRE=2 AND  ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER  IS NULL AND A.ESTSERIPS IN ('3','4') AND A.MANEXTPRO ='0'
  UNION ALL
   SELECT DISTINCT ING.NUMINGRES ,ING.IPCODPACI,ING.IESTADOIN
   FROM dbo.HCORDLABO A 
	INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS = B.CODSERIPS 
	INNER JOIN dbo.INPROFSAL C ON A.CODPROSAL = C.CODPROSAL 
	INNER JOIN 
	(
		SELECT INGMH.NUMINGRESHIJO, MIN(INGMH.ID) ID
		FROM dbo.HCINGRESORECNAC INGMH
		GROUP BY INGMH.NUMINGRESHIJO
	) INGMHD ON A.NUMINGRES = INGMHD.NUMINGRESHIJO
	INNER JOIN dbo.HCINGRESORECNAC INGMH on INGMHD.ID = INGMH.ID
	INNER JOIN dbo.HCRECINAC RN on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	INNER JOIN  dbo.ADINGRESO AS ING on ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	WHERE ING.TIPOINGRE=2 AND  ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER  IS NULL AND A.ESTSERIPS IN ('3','4') AND A.MANEXTPRO ='0'
),
CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
AS
(
    SELECT EGR.NUMINGRES,CAM.NUMCAMHOS ,FUN.UFUDESCRI,FUN.UFUTIPUNI 
	FROM CHREGESTA EGR
	INNER JOIN 
	(
	   SELECT EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR 
	   INNER JOIN CTE_LABORATORIOS_UNICOS AS UNI ON UNI.NUMINGRES =EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN  ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),
--SELECT * FROM CHREGESTA
CTE_EGRESO_CAMA
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO  
FROM CHREGEGRE EGR
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,MAX(EGR.FECEGRESO) EGRESO 
 FROM CHREGEGRE EGR 
 INNER JOIN CTE_LABORATORIOS_UNICOS AS UNI ON UNI.NUMINGRES =EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.EGRESO =EGR.FECEGRESO 
),
CTE_ORDENES_CON_LABORATORIOS_CARGADAS
---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
AS
( 
SELECT RC.AdmissionNumber,G.CUPS ,G.CANTIDAD  FROM BILLING.REVENUECONTROL AS RC
INNER JOIN
(
SELECT RC.AdmissionNumber ,CUPS.Code CUPS ,SUM(SOD.InvoicedQuantity) CANTIDAD   
FROM Billing .RevenueControlDetail AS RCD
INNER JOIN BILLING.REVENUECONTROL AS RC ON RCD.REVENUECONTROLID = RC.ID
INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2', '3')
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN CTE_LABORATORIOS_UNICOS AS UNI ON UNI.NUMINGRES =RC.AdmissionNumber  
INNER JOIN Contract .CUPSEntity AS CUPS ON CUPS.Id =SOD.CUPSEntityId AND CUPS.ServiceType IN (1)--CUPS.BillingGroupId IN (14,15)
INNER JOIN Contract .IPSService AS IPS ON IPS.Id =SOD.IPSServiceId
GROUP BY RC.AdmissionNumber ,CUPS.Code 
) AS G ON G.AdmissionNumber =RC.AdmissionNumber

),
CTE_DATOS_LABORATORIOS
---CTE QUE ME TRAE LOS DATOS DE LOS HEMOCOMPONENTES DE FORMA AGRUPADA
AS
(
SELECT ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS ) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],CAM.NUMCAMHOS,
HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
MIN(CAST(REPLACE(CONVERT(VARCHAR,CASE WHEN ISNULL(I.FECGENERA, '') <> '' THEN TRY_PARSE(I.FECGENERA AS DATETIME USING 'es-co')
WHEN ISNULL(I.FECSERIPS, '') <> '' THEN TRY_PARSE(I.FECSERIPS  AS DATETIME USING 'es-co') WHEN ISNULL(A.FECHARESULT, '') <> '' THEN A.FECHARESULT 
WHEN ISNULL(E.FECHISPAC, '') <> '' THEN E.FECHISPAC ELSE A.FECHARESULT END, 126), 'T00:00:00', 'T23:59:59.998') AS DATETIME)) AS 'FECHA REALIZADO MINIMA',
MAX(CAST(REPLACE(CONVERT(VARCHAR,CASE WHEN ISNULL(I.FECGENERA, '') <> '' THEN TRY_PARSE(I.FECGENERA AS DATETIME USING 'es-co')
WHEN ISNULL(I.FECSERIPS, '') <> '' THEN TRY_PARSE(I.FECSERIPS  AS DATETIME USING 'es-co') WHEN ISNULL(A.FECHARESULT, '') <> '' THEN A.FECHARESULT 
WHEN ISNULL(E.FECHISPAC, '') <> '' THEN E.FECHISPAC ELSE A.FECHARESULT END, 126), 'T00:00:00', 'T23:59:59.998') AS DATETIME)) AS 'FECHA REALIZADO MAXIMA'
    FROM dbo.ADINGRESO ING
	INNER JOIN dbo.HCORDLABO A  ON ing.NUMINGRES = a.NUMINGRES
	INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
	INNER JOIN DBO.INPACIENT AS P ON P.IPCODPACI =A.IPCODPACI
	INNER JOIN Contract .HealthAdministrator AS HA ON ING.GENCONENTITY =HA.Id 
	INNER JOIN Contract .CareGroup AS CG ON ING.GENCAREGROUP =CG.Id 
	INNER JOIN
	(
	    SELECT 
		ING.NUMINGRES,RTRIM(A.CODSERIPS) AS CODSERIPS,
		SUM(A.CANSERIPS ) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN 
		    FROM dbo.ADINGRESO ing
			 INNER JOIN dbo.HCORDLABO A  ON ing.NUMINGRES = a.NUMINGRES
			 INNER JOIN CTE_LABORATORIOS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =A.NUMINGRES 
	         INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
	         INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI
			 WHERE A.ESTSERIPS IN ('3','4') AND A.MANEXTPRO ='0'
			 GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	)AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =A.CODSERIPS
	INNER JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM ON CAM.NUMINGRES =ING.NUMINGRES 
	INNER JOIN dbo.INPROFSAL C ON A.CODPROSAL=C.CODPROSAL 	
	LEFT JOIN
	(
		SELECT I.AUTOLABOR, MIN(I.AUTO) AUTO
		FROM dbo.INTERCTRL I
		WHERE I.NUMUESTRA = 1
		GROUP BY I.AUTOLABOR
	) ID ON A.AUTO = ID.AUTOLABOR
	LEFT JOIN dbo.INTERCTRL I ON ID.AUTO = I.AUTO
	LEFT JOIN dbo.INPROFSAL C2 ON I.CODPROSAL=C2.CODPROSAL
	LEFT JOIN dbo.HCHISPACA E ON A.NUMINGRES = E.NUMINGRES AND A.NUMEFOLIO = E.NUMEFOLIO
	WHERE A.GENSERVICEORDER  IS NULL AND A.ESTSERIPS IN ('3','4') AND A.MANEXTPRO ='0'
	GROUP BY ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],CAM.NUMCAMHOS,HA.Name , CG.Name ,ING.IFECHAING 
  UNION ALL
   SELECT ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(A.CANSERIPS ) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],CAM.NUMCAMHOS,
   HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
MIN(CAST(REPLACE(CONVERT(VARCHAR,CASE WHEN ISNULL(I.FECGENERA, '') <> '' THEN TRY_PARSE(I.FECGENERA AS DATETIME USING 'es-co')
WHEN ISNULL(I.FECSERIPS, '') <> '' THEN TRY_PARSE(I.FECSERIPS  AS DATETIME USING 'es-co') WHEN ISNULL(A.FECHARESULT, '') <> '' THEN A.FECHARESULT 
WHEN ISNULL(E.FECHISPAC, '') <> '' THEN E.FECHISPAC	ELSE A.FECHARESULT END, 126), 'T00:00:00', 'T23:59:59.998') AS DATETIME)) AS 'FECHA REALIZADO MINIMA',
MAX(CAST(REPLACE(CONVERT(VARCHAR,CASE WHEN ISNULL(I.FECGENERA, '') <> '' THEN TRY_PARSE(I.FECGENERA AS DATETIME USING 'es-co')
WHEN ISNULL(I.FECSERIPS, '') <> '' THEN TRY_PARSE(I.FECSERIPS  AS DATETIME USING 'es-co') WHEN ISNULL(A.FECHARESULT, '') <> '' THEN A.FECHARESULT 
WHEN ISNULL(E.FECHISPAC, '') <> '' THEN E.FECHISPAC	ELSE A.FECHARESULT END, 126), 'T00:00:00', 'T23:59:59.998') AS DATETIME)) AS 'FECHA REALIZADO MAXIMA'

    FROM dbo.HCORDLABO A 
	INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS = B.CODSERIPS 
	INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI
	INNER JOIN
	(
		SELECT INGMH.NUMINGRESHIJO, MIN(INGMH.ID) ID
		FROM dbo.HCINGRESORECNAC INGMH
		GROUP BY INGMH.NUMINGRESHIJO
	) INGMHD ON A.NUMINGRES = INGMHD.NUMINGRESHIJO
	INNER JOIN dbo.HCINGRESORECNAC INGMH on INGMHD.ID = INGMH.ID
	INNER JOIN dbo.HCRECINAC RN on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	INNER JOIN  dbo.ADINGRESO AS ING on ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	INNER JOIN Contract .HealthAdministrator AS HA ON ING.GENCONENTITY =HA.Id 
	INNER JOIN Contract .CareGroup AS CG ON ING.GENCAREGROUP =CG.Id 
	INNER JOIN
	(
	   SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,
	   SUM(A.CANSERIPS) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN 
	   FROM dbo.HCORDLABO A 
	   INNER JOIN CTE_LABORATORIOS_UNICOS AS UNI ON UNI.NUMINGRES =A.NUMINGRES
	   INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS = B.CODSERIPS 
	   INNER JOIN DBO.INPACIENT AS P ON P.IPCODPACI =A.IPCODPACI
	   INNER JOIN
	   (
	   	SELECT INGMH.NUMINGRESHIJO, MIN(INGMH.ID) ID
	   	FROM dbo.HCINGRESORECNAC INGMH
	   	GROUP BY INGMH.NUMINGRESHIJO
	   ) INGMHD ON A.NUMINGRES = INGMHD.NUMINGRESHIJO
	   INNER JOIN dbo.HCINGRESORECNAC INGMH on INGMHD.ID = INGMH.ID
	   INNER JOIN dbo.HCRECINAC RN on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	   INNER JOIN  dbo.ADINGRESO AS ING on ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	   WHERE A.ESTSERIPS IN ('3','4') AND A.MANEXTPRO ='0'
			 GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN 
	)AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =A.CODSERIPS
	INNER JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM ON CAM.NUMINGRES =ING.NUMINGRES
	INNER JOIN dbo.INPROFSAL C ON A.CODPROSAL = C.CODPROSAL
	LEFT JOIN
	(
		SELECT I.AUTOLABOR, MIN(I.AUTO) AUTO
		FROM dbo.INTERCTRL I
		WHERE I.NUMUESTRA = 1
		GROUP BY I.AUTOLABOR
	) ID ON A.AUTO = ID.AUTOLABOR
	LEFT JOIN dbo.INTERCTRL I ON ID.AUTO = I.AUTO
	LEFT JOIN dbo.INPROFSAL C2 ON I.CODPROSAL = C2.CODPROSAL 
	LEFT JOIN dbo.HCHISPACA E ON INGMH.NUMINGRES = E.NUMINGRES AND A.NUMEFOLIO = E.NUMEFOLIO
	WHERE A.GENSERVICEORDER  IS NULL AND A.ESTSERIPS IN ('3','4') AND A.MANEXTPRO ='0'
	GROUP BY ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],CAM.NUMCAMHOS,HA.Name, CG.Name,ING.IFECHAING 
),

CTE_RECONOCIMIENTOS_LABORATORIOS AS
(
SELECT ING.NUMINGRES ,ING.NUMEFOLIO,ing.IESTADOIN,ing.[FECHA INGRESO],ING.ENTIDAD,ING.[GRUPO ATENCION],ING.IPCODPACI,ING.IPNOMCOMP ,ING.CODSERIPS ,ING.DESSERIPS,
ING.[CANTIDAD ORDENADA]  ,ING.CANSERIPS,CAM.UFUDESCRI ,ING.NUMCAMHOS,EGR.FECEGRESO,CAR.CUPS 'CUPS CARGADO',CAR.CANTIDAD 'CANTIDAD CARGADA'  ,ING.[FECHA REALIZADO MINIMA] ,
ING.[FECHA REALIZADO MAXIMA]  
FROM 
CTE_DATOS_LABORATORIOS ING
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM ON ING.NUMINGRES =CAM.NUMINGRES 
LEFT JOIN CTE_EGRESO_CAMA EGR ON EGR.NUMINGRES =ING.NUMINGRES
LEFT JOIN CTE_ORDENES_CON_LABORATORIOS_CARGADAS CAR ON CAR.AdmissionNumber =ING.NUMINGRES AND CAR.CUPS =ING.CODSERIPS
WHERE ING.[CANTIDAD ORDENADA] <>ISNULL(CAR.CANTIDAD,0)  AND ING.[CANTIDAD ORDENADA] >ISNULL(CAR.CANTIDAD,0)-- AND UFUDESCRI IS NOT NULL
AND CAM.UFUTIPUNI NOT IN ('1','19')
),

CTE_JUSTIFICACIONES AS
(
SELECT DISTINCT IM.NUMINGRES,IM.NUMEFOLIO,IM.CODSERIPS,JUS.Code FROM 
[Billing].[BillingJustificationControl] JUS INNER JOIN
[Billing].[AccountControlJustification] CON ON JUS.ID=JustificationId INNER JOIN
dbo.HCORDLABO IM ON CON.EntityId=IM.AUTO AND CON.EntityName='HCORDLABO'
)
-- SE CREA LA NUEVA CONSULTA UNIENDO EL CTE CON EL CTE_JUSTIFICACIONES PARA QUE NO ME MUESTRE LAS ORDENES QUE SE ENCUENTRAN JUSTIFICADAS
SELECT LAB.* 
FROM 
CTE_RECONOCIMIENTOS_LABORATORIOS LAB LEFT JOIN
CTE_JUSTIFICACIONES JUS ON LAB.NUMINGRES=JUS.NUMINGRES AND LAB.NUMEFOLIO=JUS.NUMEFOLIO AND LAB.CODSERIPS=JUS.CODSERIPS
WHERE JUS.Code IS NULL
--FN V2

