-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewGestionSalidas
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [Report].[ViewGestionSalidas]
as
WITH
CTE_HISTORIAS
AS
(
SELECT ROW_NUMBER () OVER (PARTITION BY NUMINGRES ORDER BY FECHISPAC DESC) NUMERO , IPCODPACI, NUMINGRES, INDICAPAC, FECHISPAC FROM HCHISPACA
)



SELECT CAST(ING.IFECHAING AS DATE) 'FECHA BUSQUEDA',FUN.UFUDESCRI 'UNIDAD FUNCIONAL',ING.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'NOMBRE', HA.Name 'ENTIDAD DEL PACIENTE',ING.NUMINGRES 'INGRESO',CAM.DESCCAMAS 'CAMA' ,FECHISPAC 'FECHA DE ULTIMA ATENCION', 
CASE  HC.INDICAPAC WHEN 1 THEN 'Trasladar a Urgencias'
WHEN 2 THEN 'Trasladar a Observacion Urgencias'
WHEN 3 THEN 'Trasladar a Hospitalizacion'
WHEN 4 THEN 'Trasladar a  UCI Adulto'
WHEN 5 THEN 'Trasladar a UCI Pediatrica'
WHEN 6 THEN 'Trasladar a UCI Neonatal: Dif Misma Unidad'
WHEN 7 THEN 'Trasladar a Consulta Externa: Dif Misma Unidad'
WHEN 8 THEN 'Trasladar a  Cirugia: Dif Misma Unidad'
WHEN 9 THEN 'Hospitalizacion en Casa'
WHEN 10 THEN 'Referencia'
WHEN 11 THEN 'Morgue'
WHEN 12 THEN'Salida'
WHEN 13 THEN'Continua en la Unidad'
WHEN 14 THEN 'Paciente en Tratamiento'
WHEN 15 THEN 'Retiro Voluntario'
WHEN 16 THEN 'Fuga'
WHEN 17 THEN 'Salida Parcial'
WHEN 18 THEN 'Estancia Con la Madre'
WHEN 19 THEN 'U.Cuidado Intermedio'
WHEN 20 THEN 'U.Basica' END 'DESTINO DEL PACIENTE'

FROM ADINGRESO ING
LEFT JOIN CTE_HISTORIAS HC ON HC.NUMINGRES=ING.NUMINGRES AND NUMERO=1
LEFT JOIN INPACIENT PAC ON PAC.IPCODPACI=ING.IPCODPACI
LEFT JOIN INUNIFUNC FUN ON FUN.UFUCODIGO=ING.UFUCODIGO
LEFT JOIN Contract.HealthAdministrator HA ON HA.Id=ING.GENCONENTITY
LEFT JOIN CHREGESTA EST ON EST.NUMINGRES=ING.NUMINGRES
LEFT JOIN CHCAMASHO CAM ON CAM.CODICAMAS=EST.CODICAMAS


WHERE ING.UFUCODIGO NOT IN (2000)

