-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_PBI_IND_URGENCIAS_EGRESOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE view [Report].[View_PBI_IND_URGENCIAS_EGRESOS] as

WITH CTE_TRIAGE_UNICO_POR_ATENCIÓN AS
 (
   SELECT A.NUMINGRES, A.TRIAFECHA, A.TRIANUMER
   FROM dbo.ADTRIAGEU A 
   WHERE A.ID=(SELECT MAX(B.ID) FROM dbo.ADTRIAGEU B WHERE A.IPCODPACI=B.IPCODPACI AND CAST(A.TRIAFECHA AS DATE)=CAST(B.TRIAFECHA AS DATE))
 ),

CTE_HCURGING1 AS
 (
  SELECT K.NUMINGRES,K.NUMEFOLIO,K.CODPROSAL,K.UFUCODIGO,K.FECHINIHI,K.FECHFINH,K.INDICAPAC
  FROM dbo.HCURGING1 k 
  WHERE K.NUMEFOLIO=(SELECT MIN(CAST(FOL.NUMEFOLIO AS INT)) FROM dbo.HCURGING1 FOL WHERE K.NUMINGRES=FOL.NUMINGRES)
 )

SELECT
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,  
 YEAR(ISNULL(C.IPFECLLEGA ,ISNULL(I.IFECHAING ,A.TRIAFECHA))) * 100 + MONTH(ISNULL(C.IPFECLLEGA ,ISNULL(I.IFECHAING ,A.TRIAFECHA))) [ID_TIEMPO],
 A.NUMINGRES,
 CONVERT(int,RTRIM(LTRIM(UNF.UFUCODIGO))) [ID_UFUN],
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 CTE_TRIAGE_UNICO_POR_ATENCIÓN A 
 LEFT JOIN CTE_HCURGING1 k ON A.NUMINGRES = k.NUMINGRES 
 LEFT JOIN dbo.ADINGRESO I ON A.NUMINGRES = I.NUMINGRES
 LEFT JOIN dbo.INUNIFUNC AS UNF ON ISNULL(K.UFUCODIGO,I.UFUCODIGO)=UNF.UFUCODIGO
 LEFT JOIN dbo.ADCONTURG C ON A.TRIANUMER=C.CODCONCEC 
WHERE 
 UNF.UFUTIPUNI=1 

--IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Report].[View_PBI_IND_URGENCIAS_EGRESOS]') AND type in (N'U'))
--DROP EXTERNAL TABLE [Report].[View_PBI_IND_URGENCIAS_EGRESOS]
--GO

--CREATE EXTERNAL TABLE [Report].[View_PBI_IND_URGENCIAS_EGRESOS]
--(
--    [ID_COMPANY] [varchar](9) NULL,
--	[ID_TIEMPO] [int] NULL,
--	[NUMINGRES] [char](10) NULL,
--	[ID_UFUN] [int] NULL,
--	[ULT_ACTUAL] [datetime] NULL
--)
--WITH (DATA_SOURCE = [INDIGO036],SCHEMA_NAME = N'Report',OBJECT_NAME = N'View_PBI_IND_URGENCIAS_EGRESOS')
--GO
