-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewReporteSIAU
-- Extracted by Fabric SQL Extractor SPN v3.9.0






/*******************************************************************************************************************
Nombre: [Report].[ViewReporteSIAU]
Tipo:Vista
Observacion:Informe de todas las solicitudes realizadas extramuralmente.
Profesional: Nelly Morales Capera
Fecha:
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha: 15-02-2023
Ovservaciones: Se suprime CTE_DatosPaciente, para mejorar la velocidad de la consulta, ademas .
--------------------------------------
Version 2
Persona que modifico:
Fecha:
***********************************************************************************************************************************/

CREATE VIEW [Report].[ViewReporteSIAU] as

WITH CTE_SERVICIOS AS
 (
  SELECT NUMINGRES,NUMEFOLIO, CODPROSAL, CODSERIPS, CANSERIPS, OBSSERIPS, FECORDMED FROM dbo.HCORDIMAG WHERE MANEXTPRO='1'--IMAGENES dx
  UNION ALL
  SELECT NUMINGRES,NUMEFOLIO, CODPROSAL, CODSERIPS, CANSERIPS, OBSSERIPS,FECORDMED FROM dbo.HCORDINTE WHERE MANEXTPRO='1'--INTERCONSULTAS
  UNION ALL
  SELECT NUMINGRES,NUMEFOLIO, CODPROSAL, CODSERIPS, CANSERIPS, OBSSERIPS,FECORDMED FROM dbo.HCORDLABO WHERE MANEXTPRO='1' --LABORATORIOS
  UNION ALL
  SELECT NUMINGRES,NUMEFOLIO, CODPROSAL, CODSERIPS, CANSERIPS, OBSSERIPS,FECORDMED FROM dbo.HCORDPATO WHERE MANEXTPRO='1'--PATOLOGIAS
  UNION ALL
  SELECT NUMINGRES,NUMEFOLIO, CODPROSAL, CODSERIPS, CANSERIPS, OBSSERIPS,FECORDMED FROM dbo.HCORDPRON WHERE MANEXTPRO='1'--PROCEDIMIENTOS NO QX
  UNION ALL
  SELECT NUMINGRES,NUMEFOLIO, CODPROSAL, CODSERIPS, CANSERIPS, OBSSERIPS,FECORDMED FROM dbo.HCORDPROQ WHERE MANEXTPRO='1'--PROCEDIMIENTOS QX
  UNION ALL
  SELECT CON.NUMINGRES,CON.NUMEFOLIO,HC.CODPROSAL,CON.CODSERIPS,'1' AS CANSERIPS,'' AS OBSSERIPS,HC.FECHISPAC AS FECORDMED 
  FROM dbo.HCDESCOEX CON INNER JOIN dbo.HCHISPACA HC ON CON.NUMINGRES=HC.NUMINGRES AND CON.NUMEFOLIO=HC.NUMEFOLIO
)


  SELECT
   CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
   HIS.NUMINGRES,
   ROW_NUMBER() OVER (ORDER BY HIS.IPCODPACI ) AS [CONSECUTIVO],
   EA.Name AS [ENTIDAD ADMINISTRADORA],
   CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' 
					  WHEN '2' THEN 'CE' 
					  WHEN '3' THEN 'TI' 
					  WHEN '4' THEN 'RC' 
					  WHEN '5' THEN 'PA'
					  WHEN '6' THEN 'AS' 
					  WHEN '7' THEN 'MS' 
					  WHEN '8' THEN 'NU' 
					  WHEN '9' THEN 'NV' 
					  WHEN '10' THEN 'CD' 
					  WHEN '11' THEN 'SC' 
					  WHEN '12' THEN 'PE' 
					  WHEN '13' THEN 'PT'
					  WHEN '14' THEN 'DE'
					  WHEN '15' THEN 'SI' END AS [TIPO DOCUMENTO],
   HIS.IPCODPACI AS [NUMERO DE DOCUMENTO],
   PAC.IPTELEFON AS [TELEFONO],
   PAC.IPTELMOVI AS [CELULAR],
   CASE HIS.GENCONEXT WHEN 1 THEN 'A' ELSE 'H' END [AMBITO],
   UNI.UFUDESCRI AS [SERVICIO], 
   HIS.FECHISPAC AS [FECHA ORDEN MEDICA],
   CEN.CODIPSSEC AS [CODIGO DE HABILITACION], 
    CASE PER.IdentificationType WHEN 1 THEN 'CC'
								WHEN 2 THEN 'CE' ELSE 'PA' END AS [TIPO DOCUMENTO PROFESIONAL],
   HIS.CODPROSAL AS [NUMERO DOCUMENTO PROFESIONAL],
   HIS.CODESPTRA [ESPECIALIDAD PROFESIONAL],
   CASE ING.ICAUSAING WHEN '3'  THEN '1' 
					  WHEN '10' THEN '2' 
					  WHEN '6'  THEN '3'
					  WHEN '7'  THEN '4' 
					  WHEN '1'  THEN '4'
					  WHEN '2'  THEN '5' ELSE '1' END AS [ORIGEN DE LA ATENCION],
   '1' AS [PRIORIDAD DE LA ATENCION],
   IIF(HIS.GENCONEXT=1,'1',IIF(ING.IINGREPOR=4,'5','2')) AS [TIPO SERVICIO SOLICITADO],
    CASE UNI.UFUTIPUNI WHEN 1  THEN '2' 
					   WHEN 15 THEN '1' 
					   WHEN 24 THEN '1' 
					   WHEN 3  THEN '1' 
					   WHEN 4  THEN '1'
					   WHEN 20 THEN '1' 
					   WHEN 30 THEN '1' ELSE '3' END AS [UBICACION DEL PACIENTE],
    HIS.CODDIAGNO AS [CODIGO DIAGNOSTICO],
	CASE DIA.TIPDIAGNO WHEN 'I' THEN '102'
					   WHEN 'C' THEN '100'
					   WHEN 'R' THEN '101' ELSE '100' END AS [TIPO DIAGNOSTICO],
   CASE WHEN DIA.CODDIAPRI='1' THEN '1' ELSE '0' END [DIAGNOTICO PRINCIPAL],
   '1' AS [TIPO TECNOLOGIA],
   SER.CODSERIPS AS [CODIGO TECNOLOGIA],
   B.DESSERIPS AS [NOMBRE SERVICIO],
   SER.CANSERIPS AS [CANTIDAD],
   '1' AS [DURACION],
   '' AS [CODIGO SERVICIO],
   '0' AS [DOSIS],
   '0' AS [FRECUENCIA],
   '0' AS [TIPO FRECUENCIA],
   '' AS [VIA ADMINISTRACION],
   CAST(HIS.FECHISPAC AS DATE) AS [FECHA ATENCION],
   SUBSTRING(ISNULL(URG.ANALISISP, ISNULL(EVOR.ANALISISP, EVO.ANALISISP)), 0, 3000) AS [JUSTIFICACION CLINICA], 
   CAST(HIS.FECHISPAC AS date) AS [FECHA BUSQUEDA], 
   YEAR(HIS.FECHISPAC) AS 'AÑO FECHA BUSQUEDA',
   MONTH(HIS.FECHISPAC) AS 'MES AÑO FECHA BUSQUEDA',
   CONCAT(FORMAT(MONTH(HIS.FECHISPAC), '00') ,' - ', 
     	  CASE MONTH(HIS.FECHISPAC) 
		   WHEN 1 THEN 'ENERO'
		   WHEN 2 THEN 'FEBRERO'
		   WHEN 3 THEN 'MARZO'
		   WHEN 4 THEN 'ABRIL'
		   WHEN 5 THEN 'MAYO'
		   WHEN 6 THEN 'JUNIO'
		   WHEN 7 THEN 'JULIO'
		   WHEN 8 THEN 'AGOSTO'
		   WHEN 9 THEN 'SEPTIEMBRE'
		   WHEN 10 THEN 'OCTUBRE'
		   WHEN 11 THEN 'NOVIEMBRE'
		   WHEN 12 THEN 'DICIEMBRE' END) AS 'MES NOMBRE FECHA BUSQUEDA',
   FORMAT(DAY(HIS.FECHISPAC), '00') AS 'DIA FECHA BUSQUEDA',
   CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
 FROM
	CTE_SERVICIOS SER INNER JOIN
	dbo.ADINGRESO ING ON SER.NUMINGRES=ING.NUMINGRES INNER JOIN
	dbo.HCHISPACA HIS ON ING.NUMINGRES=HIS.NUMINGRES AND SER.NUMEFOLIO=HIS.NUMEFOLIO INNER JOIN
	dbo.INPACIENT PAC ON ING.IPCODPACI=PAC.IPCODPACI INNER JOIN
	dbo.INUNIFUNC UNI ON HIS.UFUCODIGO=UNI.UFUCODIGO INNER JOIN
	Security.Person PER ON HIS.CODPROSAL=PER.Identification INNER JOIN
	Contract.HealthAdministrator EA ON ING.CODENTIDA=EA.Code INNER JOIN
	dbo.ADCENATEN AS CEN ON ING.CODCENATE = CEN.CODCENATE INNER JOIN
	dbo.INCUPSIPS B ON SER.CODSERIPS=B.CODSERIPS LEFT JOIN
	dbo.INDIAGNOH AS DIA ON DIA.CODDIAGNO=HIS.CODDIAGNO AND DIA.NUMINGRES=HIS.NUMINGRES AND HIS.NUMEFOLIO=DIA.NUMEFOLIO AND DIA.CODDIAPRI=1 LEFT JOIN
	dbo.HCURGING1 AS URG ON URG.IDETIPHIS=HIS.IDETIPHIS AND URG.NUMINGRES=HIS.NUMINGRES AND HIS.NUMEFOLIO=URG.NUMEFOLIO LEFT JOIN
	dbo.HCURGEVO1 AS EVO ON EVO.IDETIPHIS=HIS.IDETIPHIS AND EVO.NUMINGRES=HIS.NUMINGRES AND HIS.NUMEFOLIO=EVO.NUMEFOLIO LEFT JOIN
	dbo.HCNOTEVO1 AS EVOR ON EVOR.IDETIPHIS=HIS.IDETIPHIS AND EVOR.NUMINGRES=HIS.NUMINGRES AND HIS.NUMEFOLIO=EVOR.NUMEFOLIO
