-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewProcedimientosQxHSJ.
-- Extracted by Fabric SQL Extractor SPN v3.9.1










CREATE view [Report].[ViewProcedimientosQxHSJ]
AS


WITH CTE_PROCEDIMIENTOS_PRINCIPALES
AS
(
SELECT QX.CODAUTONU,QX.CODSERIPS,CUPS.DESSERIPS, QX.IPCODPACI, QX.FECHORAIN 
FROM AGEPROGQX QX
INNER JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS=QX.CODSERIPS



WHERE PRINCIPAL=1
),

CTE_PROCEDIMIENTOS_SECUNDARIOS
AS
(
SELECT QX.CODAUTONU,QX.CODSERIPS,CUPS.DESSERIPS, QX.IPCODPACI, QX.FECHORAIN 
FROM AGEPROGQX QX
INNER JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS=QX.CODSERIPS



WHERE PRINCIPAL=0
)


SELECT CAST(CX.FECHORAIN AS DATE) 'FECHA BUSQUEDA','SOCIEDAD DE CIRUGIA DE BOGOTÁ HOSPITAL DE DAN JOSÉ' 'CENTRO DE ATENCION',
CASE PAC.IPTIPODOC WHEN '1'THEN 'CC'
					WHEN '2'THEN 'CE'
				    WHEN '3'THEN 'TI'
				    WHEN '4'THEN 'RC'
				    WHEN '5'THEN 'PA'
				    WHEN '6'THEN 'AS'
				    WHEN '7'THEN 'MS'
				    WHEN '8'THEN 'NU'
				    WHEN '9'THEN 'NV'
				    WHEN '10'THEN 'CD'
				    WHEN '11'THEN 'SC'
				    WHEN '12'THEN 'PE' END AS [TIPO IDENTIFICACION],CX.IPCODPACI '# DOCUMENTO',PAC.IPNOMCOMP 'NOMBRE PACIENTE',PR.CODSERIPS 'COD. PROC. PRINCIPAL',PR.DESSERIPS 'PROCEDIMIENTO PRINCIPAL',
SE.CODSERIPS,CX.CODPROSAL 'DOC. PROFESIONAL', CX.DURPROCQX 'DURACION', CX.FECHORAIN 'HORA INICIAL', CX.FECHORAFI 'HORA FINAL', 
CASE CX.CODESTPQX WHEN  0 THEN 'Cirugia Programada'
WHEN 1 THEN 'Paciente admitido (Cirugia Origen Ambulatoria)'
WHEN 2 THEN 'Paciente en sala de espera'
WHEN 3 THEN 'Paciente en sala quirurgica'
WHEN 4 THEN 'Paciente en recuperación'
WHEN 5 THEN 'Paciente con alta'
WHEN 6 THEN 'Anulado - Cancelada' END 'ESTADO', CX.CODUSUASI 'COD. USUARIO ASIGNA', CX.FECREGSIS 'FECHA PROGRAMACION', CASE CX.ORIGENQX WHEN 1 THEN 'AMBULATORIO' ELSE 'HOSPITALARIO' END  'ORIGEN' , 
CX.IDRADICACIONQX 'NUMERO RADICADO', CASE WHEN CX.ESTADOFARM IN (1) THEN 'PAQUETE SOLICITADO' ELSE 'SIN SOLUCITUD DE PAQUETE' END 'ESTADO SOLICITUD FARMACIA', CX.NUMINGRES '# INGRESO',
CX.AGENSALAC 'COD. SALA', SAL.DESCRIPSAL 'SALA'


FROM AGEPROGQX CX
INNER JOIN INPACIENT PAC ON PAC.IPCODPACI=CX.IPCODPACI
INNER JOIN CTE_PROCEDIMIENTOS_PRINCIPALES PR ON PR.CODAUTONU=CX.CODAUTONU 
INNER JOIN AGENSALAC SAL ON SAL.CODCONCEC=CX.AGENSALAC
LEFT JOIN CTE_PROCEDIMIENTOS_SECUNDARIOS SE ON SE.CODAUTONU=CX.CODAUTONU 
