-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewInterconsultas.
-- Extracted by Fabric SQL Extractor SPN v3.9.1

CREATE VIEW [Report].[ViewInterconsultas] AS

SELECT 
INT.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE' ,INT.NUMINGRES 'INGRESO',UNI.UFUDESCRI 'UNIDAD FUNCIONAL',FECORDMED 'FECHA SOLICITUD',INT.CODDIAGNO 'CIE-10',
DIA.NOMDIAGNO 'DIAGNOSTICO',
ESP.DESESPECI 'ESPECIALIDAD' ,INT.CODSERIPS 'CUPS',CUPS.DESSERIPS 'NOMBRE SERVICIO', CASE INT.ESTSERIPS WHEN 1 THEN 'SOLICITADO' WHEN 2 THEN 'SOLICITUD ENVIADA' 
WHEN 3 THEN 'REALIZADA' WHEN 4 THEN 'EXTRAMURAL' WHEN 5 THEN 'ANULADO' END 'ESTADO INTERCONSULTA',datediff(day, FECORDMED,COMMON.GETDATE ()) 'TIEMPO DE ESPERA EN DIAS',
G2.[FECHA ALTA MEDICA]

 

FROM DBO.HCORDINTE INT
INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =INT.IPCODPACI 
INNER JOIN DBO.INUNIFUNC AS UNI ON UNI.UFUCODIGO =INT.UFUCODIGO 
INNER JOIN DBO.INDIAGNOS AS DIA ON DIA.CODDIAGNO =INT.CODDIAGNO 
INNER JOIN DBO.INESPECIA AS ESP ON ESP.CODESPECI =INT.CODESPECI 
INNER JOIN DBO.INCUPSIPS AS CUPS ON CUPS.CODSERIPS =INT.CODSERIPS 
LEFT JOIN
(
	 SELECT EGR.NUMINGRES 'INGRESO' ,EGR.IPCODPACI 'IDENTIFICACION',EGR.FECALTPAC 'FECHA ALTA MEDICA'  
     FROM HCREGEGRE EGR with (nolock)
     INNER JOIN
     ( SELECT EGR.NUMINGRES 'INGRESO' ,EGR.IPCODPACI 'IDENTIFICACION' ,MAX(EGR.FECALTPAC) 'FECHA ALTA MEDICA'  
     FROM DBO.HCREGEGRE EGR with (nolock)
     GROUP BY EGR.NUMINGRES,EGR.IPCODPACI
     )  AS G ON G.INGRESO =EGR.NUMINGRES AND G.IDENTIFICACION  =EGR.IPCODPACI AND G.[FECHA ALTA MEDICA] =EGR.FECALTPAC
	) AS G2 ON G2.INGRESO =INT.NUMINGRES 
where int.ESTSERIPS in (1,2) AND INT.MANEXTPRO =0