-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewReporteVacunacion
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [Report].[ViewReporteVacunacion] as

WITH  CTE_DATOS_UNICOS
AS
 (
 SELECT HIS.IPCODPACI ,HIS.NUMINGRES,HIS.FECHISPAC,HIS.CODESPTRA,HIS.NUMEFOLIO, HIS.CODCENATE   FROM HCHISPACA AS HIS
 WHERE HIS.IDMODELOHC = '6' /*AND CAST(HIS.FECHISPAC  AS DATE) BETWEEN CAST(CONCAT(CASE WHEN  (MONTH(GETDATE()) - 1) <> 0  THEN  (MONTH(GETDATE()) - 1) ELSE  12 END,'/','01/',                                                 
                                                 CASE WHEN  (MONTH(GETDATE()) - 1) <> 0  THEN  YEAR(GETDATE()) ELSE  (YEAR(GETDATE()) - 1) END) as date) AND GETDATE()*/

 ),

CTE_CYD
AS
 (
 SELECT HIS.IPCODPACI DOCUMENTO ,HIS.NUMINGRES INGRESO,HIS.FECHISPAC FECHA,HIS.CODESPTRA ESPECIALIDAD,HIS.NUMEFOLIO FOLIO, HIS.CODCENATE CENTRO   FROM HCHISPACA AS HIS
 WHERE HIS.IDMODELOHC IN ('7','8') /*AND CAST(HIS.FECHISPAC  AS DATE) BETWEEN CAST(CONCAT(CASE WHEN  (MONTH(GETDATE()) - 1) <> 0  THEN  (MONTH(GETDATE()) - 1) ELSE  12 END,'/','01/',                                                 
                                                 CASE WHEN  (MONTH(GETDATE()) - 1) <> 0  THEN  YEAR(GETDATE()) ELSE  (YEAR(GETDATE()) - 1) END) as date) AND GETDATE()*/

 GROUP BY HIS.IPCODPACI ,HIS.NUMINGRES,HIS.FECHISPAC,HIS.CODESPTRA,HIS.NUMEFOLIO, HIS.CODCENATE

 ),


 CTE_LABORATORIO
AS
(
--AMBULATORIO
 SELECT NUMINGRES,IPCODPACI,NOMBRE_GRUPO,VALOR_GRUPO,NOMBRE_VARIABLE,OPCION ,VALOR FROM Report.TablaExamenFisico
),
CTE_ANTECEDENTES
AS
(
--
 SELECT NUMINGRES,IPCODPACI,IDHCHISPACA,CODANTECEDENTE,ID_VARIABLE,NOMBRE_VARIABLE,VALOR,ID FROM Report.TablaResultadosAntecedentes-- WHERE ID_VARIABLE IN (436,437)
),

CTE_VACUNACION
  AS
  (
  SELECT       PLA.IPCODPACI, PLA.IDPLAVACU, PLA.FECAPLVAC, PLA.APLICADA, PLA.NUMINGRES,VAC.EDAREGVAC, VAC.TIPVACUNA, VAC.NUMDOSISV
FROM            ..HCPLANVAC PLA INNER JOIN 
   ..INPLANVAC VAC ON PLA.IDPLAVACU =VAC.IDPLAVACU inner join
    CTE_DATOS_UNICOS  AS DAT ON DAT.IPCODPACI =PLA.IPCODPACI     /*AND CAST(PLA.FECAPLVAC AS DATE) BETWEEN CAST(CONCAT(CASE WHEN  (MONTH(GETDATE()) - 1) <> 0  THEN  (MONTH(GETDATE()) - 1) ELSE  12 END,'/','01/',                                                 
                                                 CASE WHEN  (MONTH(GETDATE()) - 1) <> 0  THEN  YEAR(GETDATE()) ELSE  (YEAR(GETDATE()) - 1) END) as date) AND GETDATE()*/
  ),

CTE_RECIEN_NACIDO 
AS
(
SELECT  ROW_NUMBER() OVER(ORDER BY PAC.IPCODPACI) AS 'CONSECUTIVO',
CASE MONTH(HIS.FECHISPAC) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
  END AS 'MES', EAPB.HealthEntityCode AS 'COD.EAPB', EAPB.Name AS 'ENTIDAD', TRIM(CEN.NOMCENATE) AS 'LUGAR DE NACIMIENTO' ,
CASE PAC.IPSEXOPAC WHEN 1 THEN 'M' 
				   WHEN 2 THEN 'F' ELSE 'I' END AS 'SEXO', PAC.IPTELEFON + '-' + PAC.IPTELMOVI AS 'TELEFONO', ISNULL(GRU.TIPOET ,'6') AS 'CODIGO ETNIA',
ISNULL(MAD.VALOR,'SIN DATO') AS 'NOMBRE MADRE', 'SIN DATO' AS 'ID MADRE',EMAD.VALOR AS 'EDAD MADRE' ,CASE WHEN PER.EDADGESTA IS NOT NULL THEN PER.EDADGESTA ELSE '0' END AS 'EDAD GESTACIONAL'
, CASE PAC.IPTIPODOC WHEN 1 THEN 'CC' 
				   WHEN 2 THEN 'CE' 
				   WHEN 3 THEN 'TI' 
				   WHEN 4 THEN 'RC' 
				   WHEN 5 THEN 'PA' 
				   WHEN 6 THEN 'AS' 
				   WHEN 7 THEN 'MS' 
				   WHEN 8 THEN 'NU' 
				   WHEN 9 THEN 'CN' 
				   WHEN 10 THEN 'CD' 
				   WHEN 11 THEN 'SC'
				   WHEN 12 THEN 'PE' END AS 'TIPO DOCUMENTO',
PAC.IPCODPACI AS 'IDENTIFICACION',  ISNULL(PER.CANTPRENA,'0') AS 'NUMERO CONS. PRENATALES',
CAST(EX.PESOPACIE/1000 AS FLOAT) AS 'PESO',EX.TALLAPACI AS 'TALLA EN CM', CAST(PAC.IPFECNACI AS DATE) AS 'FECHA DE PARTO',
PAC.IPPRIAPEL AS 'PRIMER APELLIDO', PAC.IPSEGAPEL AS 'SEGUNDO APELLIDO', PAC.IPPRINOMB AS 'PRIMER NOMBRE', PAC.IPSEGNOMB AS 'SEGUNDO NOMBRE',
IIF(VAC.FECAPLVAC IS NULL,NULL,CAST(VAC.FECAPLVAC AS DATE)) AS 'FECHA VACUNA HEP B',
IIF(VAC2.FECAPLVAC IS NULL,NULL,CAST(VAC2.FECAPLVAC AS DATE)) AS 'FECHA VACUNA BCG',
IIF([Report].[FN_Laboratorios_Rias_TSH_Fecha](HIS.FECHISPAC,HIS.IPCODPACI) IS NULL,
    IIF(ANT.VALOR IS NULL,'SIN DATO','SI'),'SI') 'REALIZACION TSH',
IIF([Report].[FN_Laboratorios_Rias_TSH_Fecha](HIS.FECHISPAC,HIS.IPCODPACI) IS NULL,
     IIF(ANT.VALOR IS NULL,'',ANT.VALOR),CONVERT(VARCHAR(10),[Report].[FN_Laboratorios_Rias_TSH_Fecha](HIS.FECHISPAC,HIS.IPCODPACI),103))  'FECHA REALIZACION TSH',
'SIN DATO' AS 'TRATAMIENTO HIPOTIROIDISMO', CAST(HIS.FECHISPAC AS DATE) AS 'FECHA REVISION RN', IIF(CYD.FECHA IS NOT NULL, CAST(CYD.FECHA AS DATE), NULL) AS 'FECHA INGRESO CYD',
1 as 'CANTIDAD',
CAST(HIS.FECHISPAC AS date) AS 'FECHA BUSQUEDA',
YEAR(HIS.FECHISPAC) AS 'AÑO FECHA BUSQUEDA',
MONTH(HIS.FECHISPAC ) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(HIS.FECHISPAC) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
  END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(HIS.FECHISPAC), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(HIS.FECHISPAC), '00') ,' - ', 
	   CASE MONTH(HIS.FECHISPAC) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM CTE_DATOS_UNICOS  AS HIS
INNER JOIN ..INPACIENT PAC WITH(NOLOCK) ON PAC.IPCODPACI=HIS.IPCODPACI
INNER JOIN ..ADINGRESO ING WITH(NOLOCK) ON ING.NUMINGRES=HIS.NUMINGRES
LEFT JOIN ..ADCENATEN AS CEN WITH(NOLOCK) ON CEN.CODCENATE=HIS.CODCENATE
INNER JOIN ..INESPECIA ESP WITH(NOLOCK) ON ESP.CODESPECI=HIS.CODESPTRA
INNER JOIN ..HCEXFISIC EX WITH(NOLOCK) ON EX.IPCODPACI=HIS.IPCODPACI AND EX.NUMINGRES=HIS.NUMINGRES
LEFT JOIN ..HCURGING1 HUR WITH(NOLOCK) ON HIS.NUMINGRES=HUR.NUMINGRES AND HIS.NUMEFOLIO=HUR.NUMEFOLIO
LEFT JOIN ..HCANTPERI PER WITH(NOLOCK) ON PER.IPCODPACI=HIS.IPCODPACI
LEFT JOIN ADGRUETNI GRU WITH(NOLOCK) ON PAC.CODGRUPOE =GRU.CODGRUPOE
LEFT JOIN CTE_LABORATORIO LABFECHATSH WITH(NOLOCK) ON LABFECHATSH.NUMINGRES  =HIS.NUMINGRES AND LABFECHATSH.NOMBRE_VARIABLE='Fecha de TSH'
LEFT JOIN CTE_LABORATORIO LABVALORTSH WITH(NOLOCK) ON LABVALORTSH.NUMINGRES  =HIS.NUMINGRES AND LABVALORTSH.NOMBRE_VARIABLE='TSH'
LEFT JOIN CTE_ANTECEDENTES ANT WITH(NOLOCK) ON ANT.IPCODPACI=HIS.IPCODPACI AND ANT.NUMINGRES=HIS.NUMINGRES AND ANT.CODANTECEDENTE='1' AND ANT.NOMBRE_VARIABLE='Fecha THS neonatal'
LEFT JOIN CTE_VACUNACION VAC WITH (NOLOCK) ON VAC.IPCODPACI =HIS.IPCODPACI AND VAC.NUMINGRES =HIS.NUMINGRES AND VAC.IDPLAVACU ='0002' ---Vacunacion Hepatitis B
LEFT JOIN CTE_VACUNACION VAC2 WITH (NOLOCK) ON VAC2.IPCODPACI =HIS.IPCODPACI AND VAC2.NUMINGRES =HIS.NUMINGRES AND VAC2.IDPLAVACU ='0001' ---Vacunacion BCG
LEFT JOIN CTE_CYD CYD WITH(NOLOCK) ON CYD.DOCUMENTO=HIS.IPCODPACI
LEFT JOIN CTE_ANTECEDENTES MAD WITH(NOLOCK) ON MAD.IPCODPACI=HIS.IPCODPACI AND MAD.NUMINGRES=HIS.NUMINGRES AND MAD.CODANTECEDENTE='10' AND MAD.NOMBRE_VARIABLE='Nombre y apellido de la madre'
LEFT JOIN CTE_ANTECEDENTES EMAD WITH(NOLOCK) ON EMAD.IPCODPACI=HIS.IPCODPACI AND EMAD.NUMINGRES=HIS.NUMINGRES AND EMAD.CODANTECEDENTE='10' AND EMAD.NOMBRE_VARIABLE='Edad de la madre (años)'
LEFT JOIN HCATINPAR PAR WITH(NOLOCK) ON PAR.NUMINGRES=EMAD.NUMINGRES
INNER JOIN ..Contract.HealthAdministrator AS EAPB WITH(NOLOCK) ON EAPB.Id=ING.GENCONENTITY
INNER JOIN ..INUBICACI AS UB WITH(NOLOCK) ON UB.AUUBICACI = PAC.AUUBICACI
INNER JOIN ..INMUNICIP AS MUN WITH(NOLOCK) ON MUN.DEPMUNCOD = UB.DEPMUNCOD
INNER JOIN ..INDEPARTA AS DEP WITH(NOLOCK) ON DEP.depcodigo=MUN.DEPCODIGO
)

SELECT CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, * FROM CTE_RECIEN_NACIDO
