-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_PBI_IND_CONSULTA_EXTERNA
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE view [Report].[View_PBI_IND_CONSULTA_EXTERNA] as
SELECT 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 YEAR(A.FECHORAIN) * 100 + MONTH(A.FECHORAIN) [ID_TIEMPO],
 CASE A.CODESTCIT WHEN '0' THEN 'ASIGNADA' 
				  WHEN '1' THEN 'CUMPLIDA'
				  WHEN '2' THEN 'INCUMPLIDA'
				  WHEN '3' THEN 'PREASIGNADA'
				  WHEN '4' THEN 'CANCELADA'
				  WHEN '5' THEN 'INATENCION' 
				  WHEN '7' THEN 'N/A' END AS [ESTADO ACTUAL],
 CONVERT(int, LTRIM(RTRIM(A.CODESPECI))) AS [ID_ESPEC], 
 A.IPCODPACI PACIENTE,
 COUNT(1) NO_CITAS,
 CONVERT(int, LTRIM(RTRIM(AGC.UFUCODIGO))) AS [ID_UFUN], 
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 AGASICITA A 
 INNER JOIN ADCENATEN AS C  ON A.CODCENATE = C.CODCENATE --35.227
 LEFT JOIN AGCONSULT AS AGC  ON AGC.CODIGOCON = A.CODIGOCON AND AGC.CODCENATE = C.CODCENATE --35.227
 LEFT JOIN INUNIFUNC AS UNICE  ON UNICE.UFUCODIGO = AGC.UFUCODIGO --35.227
WHERE
 --CAST(A.FECHORAIN as date) BETWEEN '2023-07-01' AND '2023-07-31' AND
 CONVERT(int, LTRIM(RTRIM(A.CODESPECI))) <> 0 AND
 a.TIPSOLICITU = 1
GROUP BY
 YEAR(A.FECHORAIN) * 100 + MONTH(A.FECHORAIN),
 RTRIM(AGC.UFUCODIGO),
 RTRIM(A.CODESPECI),
 A.IPCODPACI,
 CASE A.CODESTCIT WHEN '0' THEN 'ASIGNADA' 
				  WHEN '1' THEN 'CUMPLIDA'
				  WHEN '2' THEN 'INCUMPLIDA'
				  WHEN '3' THEN 'PREASIGNADA'
				  WHEN '4' THEN 'CANCELADA'
				  WHEN '5' THEN 'INATENCION' 
				  WHEN '7' THEN 'N/A' END 

--IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Report].[View_PBI_IND_CONSULTA_EXTERNA]') AND type in (N'U'))
-- DROP EXTERNAL TABLE [Report].[View_PBI_IND_CONSULTA_EXTERNA]
--GO

--CREATE EXTERNAL TABLE [Report].[View_PBI_IND_CONSULTA_EXTERNA]
-- (
--	[ID_COMPANY] [varchar](9) NULL,
--	[ID_TIEMPO] [int] NULL,
--	[ESTADO ACTUAL] [varchar](11) NULL,
--	[ID_ESPEC] [int] NULL,
--	[PACIENTE] [varchar](25) NOT NULL,
--	[NO_CITAS] [int] NULL,
--	[ID_UFUN] [int] NULL,
--	[ULT_ACTUAL] [datetime] NULL
-- )
--WITH (DATA_SOURCE = [INDIGO040],SCHEMA_NAME = N'Report',OBJECT_NAME = N'View_PBI_IND_CONSULTA_EXTERNA')
--GO
