-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewConsultationMorbidityIRA
-- Extracted by Fabric SQL Extractor SPN v3.9.0


/*************************************************************************
_________________________________________________________________________
Version 1
Persona que modifico:Amira Gil Meneses
Observación: Se realiza CTE para los Diagnosticos Relacionados
Fecha: 31-07-2023
_________________________________________________________________________
*************************************************************************/

CREATE VIEW [Report].[ViewConsultationMorbidityIRA] as 
WITH TIPO_INFECCION AS 
 (
  SELECT 
   CODDIAGNO 'COD. DIAGNOSTICO', 
   NOMDIAGNO 'NOMBRE DIAGNOSTICO',
   'IRA' TIPO_INFECCION
  FROM 
   INDIAGNOS
  WHERE 
   CODDIAGNO   IN ('J00X','J010','J011','J012','J013','J014','J018','J019','J020','J028','J029','J030','J038','J039','J040','J041','J042','J050',
                   'J051','J060','J068','J069','J09X','J100','J101','J108','J110','J111','J118','J120','J121','J122','J123','J128','J129','J13X',
				   'J14X','J150','J151','J152','J153','J154','J155','J156','J157','J158','J159','J160','J168','J170','J171','J172','J173','J178',
				   'J180','J181','J182','J188','J189','J200','J201','J202','J203','J204','J205','J206','J207','J208','J209','J210','J211','J218',
				   'J219','J22X','U071','U072','B342')
),
CTE_DIAGNOSTICO_RELACIONADOS AS
(
select 
ROW_NUMBER ( )   
OVER (PARTITION BY IND.IPCODPACI  order by IND.NUMEFOLIO DESC) AS NUMERO,

TP.[COD. DIAGNOSTICO],
IND.CODDIAGNO AS [COD DX RELACIONADO],
DG.NOMDIAGNO AS [NOM DX RELACIONADO]
from 
INDIAGNOP IND 
INNER JOIN DBO.INDIAGNOS DG ON IND.CODDIAGNO=DG.CODDIAGNO
INNER JOIN TIPO_INFECCION TP ON TP.[COD. DIAGNOSTICO]=DG.CODDIAGNO
--WHERE IND.CODDIAPRI!=1
),

CTE_CONSULTAS_MORBILIDAD_IRA AS 
 (
  SELECT 
   HA.Name AS 'ENTIDAD', 
   HC.FECHISPAC 'FECHA ATENCION',
   INU.UFUDESCRI AS 'NOMBRE UNIDAD FUNCIONAL',
   CASE INP.IPSEXO WHEN 'M' THEN 'FEMENINO' WHEN 'H' THEN 'MASCULINO' END 'SEXO', 
   CASE HC.INDICAPAC WHEN '11' THEN 1 ELSE 0 END AS 'ESTADO_PCTE',
   CAST(HC.FECHISPAC AS DATE) AS 'FECHA HISTORIA CLINICA', 
   YEAR(HC.FECHISPAC) AS 'AÑO HISTORIA CLINICA',  
   MONTH(HC.FECHISPAC) AS 'MES HISTORIA CLINICA', 
   DAY(HC.FECHISPAC) AS 'DIA HISTORIA CLINICA', 
   DATEDIFF(WW, DATEADD(DD, DAY(HC.FECHISPAC) * -1, HC.FECHISPAC) + 1, HC.FECHISPAC) + 1 AS 'SEMANA DEL MES',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) < 1 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'MENORES DE 1',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) = 1 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 1 AÑO',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 2 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 4 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 2 A 4',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 5 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 19 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 5 A 19',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 20 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 39 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 20 A 39',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 40 AND DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) <= 59 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'DE 40 A 59',
   CASE WHEN DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC) >= 60 THEN COUNT(DISTINCT HC.IPCODPACI) ELSE 0 END AS 'MAYORES DE 60',
   TI.[COD. DIAGNOSTICO], 
   TI.[NOMBRE DIAGNOSTICO],
   DXR.[COD DX RELACIONADO],
   DXR.[NOM DX RELACIONADO]
    
  FROM 
   INDIAGNOP IND 
   INNER JOIN TIPO_INFECCION TI ON IND.CODDIAGNO = TI.[COD. DIAGNOSTICO]
   INNER JOIN HCHISPACA HC ON IND.NUMINGRES = HC.NUMINGRES AND IND.IPCODPACI = HC.IPCODPACI AND IND.NUMEFOLIO = HC.NUMEFOLIO
   INNER JOIN CTE_DIAGNOSTICO_RELACIONADOS  AS DXR ON DXR.[COD DX RELACIONADO] = IND.CODDIAGNO ---ESTE
   INNER JOIN INPACIENT INP ON HC.IPCODPACI = INP.IPCODPACI 
   INNER JOIN ADINGRESO AD ON HC.NUMINGRES = AD.NUMINGRES
   INNER JOIN INDIAGNOS INS ON IND.CODDIAGNO = INS.CODDIAGNO
   INNER JOIN ADCENATEN ADC ON HC.CODCENATE = ADC.CODCENATE
   INNER JOIN INUNIFUNC INU ON HC.UFUCODIGO = INU.UFUCODIGO
   INNER JOIN INPROFSAL IPR ON HC.CODPROSAL = IPR.CODPROSAL
   INNER JOIN INESPECIA INE ON HC.CODESPTRA = INE.CODESPECI
   INNER JOIN Contract.HealthAdministrator HA ON HA.Id = AD.GENCONENTITY
  GROUP BY 
   HA.Name, INU.UFUDESCRI, HC.FECHISPAC, INP.IPSEXO, HC.INDICAPAC, TI.[COD. DIAGNOSTICO], TI.[NOMBRE DIAGNOSTICO], CAST(HC.FECHISPAC AS DATE), 
   DATEDIFF(YEAR, INP.IPFECNACI, HC.FECHISPAC),  DATEDIFF(WW, DATEADD(DD, DAY(HC.FECHISPAC) * -1, HC.FECHISPAC) + 1, HC.FECHISPAC) + 1,
  DXR.[COD DX RELACIONADO], DXR.[NOM DX RELACIONADO],IND.NUMINGRES
 )
 
  SELECT 
   CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
   [FECHA ATENCION], 
   ENTIDAD, 
   [NOMBRE UNIDAD FUNCIONAL], 
   [SEXO],
   CASE 
    WHEN [ESTADO_PCTE]=0 THEN 'NO'
    WHEN [ESTADO_PCTE]=1 THEN 'SI'
    ELSE 'NO REPORTA'
   END [MORATALIDAD],
   [AÑO HISTORIA CLINICA], 
   [MES HISTORIA CLINICA], 
   [SEMANA DEL MES], 
   [DIA HISTORIA CLINICA], 
   [COD. DIAGNOSTICO],
   [NOMBRE DIAGNOSTICO],
   [COD DX RELACIONADO],
   [NOM DX RELACIONADO],
   SUM([MENORES DE 1]) AS [MENORES DE 1], 
   SUM([DE 1 AÑO]) AS [DE 1 AÑO], 
   SUM([DE 2 A 4]) AS [DE 2 A 4], 
   SUM([DE 5 A 19]) AS [DE 5 A 19], 
   SUM([DE 20 A 39]) AS [DE 20 A 39], 
   SUM([DE 40 A 59]) AS [DE 40 A 59], 
   SUM([MAYORES DE 60]) AS [MAYORES DE 60], 
   SUM([MENORES DE 1]) + SUM([DE 1 AÑO]) + SUM([DE 2 A 4]) + SUM([DE 5 A 19]) + SUM([DE 20 A 39]) + SUM([DE 40 A 59]) + SUM([MAYORES DE 60]) AS TOTAL,
   CAST([FECHA HISTORIA CLINICA] AS date) AS 'FECHA BUSQUEDA',
   YEAR([FECHA HISTORIA CLINICA]) AS 'AÑO FECHA BUSQUEDA',
   MONTH([FECHA HISTORIA CLINICA]) AS 'MES AÑO FECHA BUSQUEDA',
   CASE MONTH([FECHA HISTORIA CLINICA]) 
    WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'					  
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
   END AS 'MES NOMBRE FECHA BUSQUEDA',
   FORMAT(DAY([FECHA HISTORIA CLINICA]), '00') AS 'DIA FECHA BUSQUEDA',
   CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
  FROM 
   CTE_CONSULTAS_MORBILIDAD_IRA
 GROUP BY 
   ENTIDAD, [FECHA ATENCION],  [NOMBRE UNIDAD FUNCIONAL], [SEXO], [ESTADO_PCTE], [AÑO HISTORIA CLINICA], 
   [MES HISTORIA CLINICA], [SEMANA DEL MES],  [DIA HISTORIA CLINICA], [COD. DIAGNOSTICO], [NOMBRE DIAGNOSTICO],
   [FECHA HISTORIA CLINICA],[COD DX RELACIONADO],[NOM DX RELACIONADO]
