-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewPAD
-- Extracted by Fabric SQL Extractor SPN v3.9.0



/*******************************************************************************************************************
Nombre: [Report].[ViewPAD]
Tipo:Vistas
Observacion:Vista sobre la oportunidad atencion domiciliaria
Profesional: Nilsson Miguel Galindo Lopez
Fecha:27-09-2022
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Vercion 2
Persona que modifico: Amira Esperanza Gil 
Fecha: 19-05-2023
Ovservaciones: 
--------------------------------------
Vercion 3
Persona que modifico:
Fecha:
***********************************************************************************************************************************/


CREATE VIEW [Report].[ViewPAD] as

WITH 
CTE_SOLICITUD AS
(
	SELECT 
	ROW_NUMBER ( )   
		OVER ( PARTITION BY PAD.IPCODPACI  order by PAD.IPCODPACI,PAD.NUMINGRES) 'NUMERO',
	PAD.ID,
	PAD.NUMINGRES,
	PAD.NUMEFOLIO,
	PAD.IPCODPACI,
	PAD.FECHAREGISTRO,
	PAD.ESTADO,
	PAD.TIPOATENCION,
	PAD.FECHASUSP,
	EGR.FECALTPAC AS [FECHA ALTA MEDICA],
  	EGR.ESTPACEGR, 
	EGR.FECMUEPAC, 
	EGR.NUMCERDEF,
	EGR.CODCAUMUE,
	ING.FECHEGRESO AS [FECHA EGRESO]
	FROM 
	dbo.PADCONTROL PAD INNER JOIN
	dbo.ADINGRESO ING ON PAD.NUMINGRES=ING.NUMINGRES AND PAD.NUMEFOLIO=(SELECT MAX(CON.NUMEFOLIO) FROM dbo.PADCONTROL CON WHERE PAD.NUMINGRES=CON.NUMINGRES) LEFT JOIN
	dbo.HCREGEGRE EGR ON PAD.NUMINGRES=EGR.NUMINGRES 
	--WHERE PAD.IPCODPACI='6491466'
),
CTE_INGRESO_PAD AS
(
	SELECT 
	ROW_NUMBER ( )   
		OVER ( PARTITION BY ING.IPCODPACI  order by ING.IPCODPACI,ING.IFECHAING) 'NUMERO',
	ING.NUMINGRES,
	ING.IPCODPACI,
	ING.IFECHAING,
	EGR.FECALTPAC AS [FECHA EGRESO PAD],
	ING.UFUCODIGO,
	APAD.FECHAEGRESO AS [FECHA ALTA MEDICA PAD]
	FROM 
	dbo.ADINGRESO ING INNER JOIN
	dbo.INUNIFUNC FUN ON ING.UFUCODIGO=FUN.UFUCODIGO AND FUN.UFUDESCRI LIKE '%DOMICILIARIA%' LEFT JOIN
	dbo.HCREGEGRE EGR ON ING.NUMINGREI=EGR.NUMINGRES
	INNER JOIN dbo.PADASIGNACION  APAD ON ING.NUMINGRES=APAD.NUMEROINGRESO
	--WHERE ING.IPCODPACI='6491466'

),

CTE_CONTROL AS
(
	SELECT 
	SOL.ID,
	SOL.IPCODPACI,
	SOL.NUMINGRES AS NUMINGRES_SOL,
	SOL.NUMEFOLIO,
	SOL.FECHAREGISTRO,
	CASE WHEN PAD.NUMINGRES IS NOT NULL THEN 'ATENDIDO' 
	     WHEN SOL.ESTADO=1 THEN 'REGISTRADO' ELSE 'SUSPENDIDO' END AS ESTADO,
	CASE SOL.TIPOATENCION  WHEN 1 THEN 'ATENCIÓN DOMICILIARIA' 
						   WHEN 2 THEN 'HOSPITALIZACIÓN EN CASA' END AS [TIPO DE SOLICITUD],						   							 
	CASE WHEN PAD.NUMINGRES IS NOT NULL THEN NULL ELSE SOL.FECHASUSP END AS FECHASUSP,
	SOL.[FECHA ALTA MEDICA],
	PAD.NUMINGRES AS NUMINGRES_PAD,
	PAD.IFECHAING AS [FECHA INGRESO PAD],
	PAD.[FECHA EGRESO PAD],
	PAD.[FECHA ALTA MEDICA PAD],
	CASE SOL.ESTPACEGR   WHEN 1 THEN 'MEJOR'
                         WHEN 2 THEN 'IGUAL Y PEOR'
                         WHEN 3 THEN 'FALLECIDO'
                         WHEN 4 THEN 'REMITIDO'
                         WHEN 5 THEN 'HOSPITALIZACION EN CASA' END AS [ESTADO PACIENTE AL EGRESO], 
	CASE SOL.ESTPACEGR  WHEN 3 THEN 'SI' ELSE 'NO' END AS [FALLECIDO],
	SOL.FECMUEPAC AS [FECHA DE MUERTE],
	SOL.NUMCERDEF AS [NO_CERT_DEFUNCION],
	CASE SOL.CODCAUMUE  WHEN 001 THEN 'MUERTE NATURAL'
                    WHEN 002 THEN 'MUERTE VIOLENTA'
                    WHEN 003 THEN 'MUERTE EN ESTUDIO' END AS [CAUSA DE MUERTE]
	FROM 
	CTE_SOLICITUD SOL LEFT JOIN
	CTE_INGRESO_PAD PAD ON SOL.IPCODPACI=PAD.IPCODPACI AND SOL.NUMERO=PAD.NUMERO
)


SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CEN.NOMCENATE AS [CENTRO DE ATENCION],
CON.IPCODPACI AS [IDENTIFICACION PACIENTE],
CASE PAC.IPTIPODOC WHEN 1 THEN 'CC - CEDULA DE CIUDADANIA' 
				   WHEN 2 THEN 'CE - CEDULA DE EXTRANJERIA' 
				   WHEN 3 THEN 'TI - TARJETA DE IDENTIDAD' 
				   WHEN 4 THEN 'RC - REGISTRO CIVIL' 
				   WHEN 5 THEN 'PA - PASAPORTE' 
				   WHEN 6 THEN 'AS - ADULTO SIN IDENTIFICACION' 
				   WHEN 7 THEN 'MS - MENOR SIN IDENTIFICACION' 
				   WHEN 8 THEN 'NU - NUMERO UNICO DE IDENTIFICACIÒN' 
				   WHEN 9 THEN 'NV - CERTIFICADO NACIDO VIVO' 
				   WHEN 10 THEN 'CD - CARNET DIPLOMATICO' 
				   WHEN 11 THEN 'SC - SALVOCONDUCTO' 
				   WHEN 12 THEN 'PE - PERMISO ESPECIAL DE PERMANENCIA' ELSE 'OTRO' END [TIPO IDENTIFICACION],
PAC.IPNOMCOMP AS [NOMBRES Y APELLIDOS PACIENTE],
CAST(PAC.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
FLOOR((CAST(CONVERT(VARCHAR(8), ING.IFECHAING , 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS [EDAD],
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END AS SEXO,
PAC.IPTELEFON AS [TELEFONO],
PAC.IPTELMOVI AS [CELULAR],
EAPB.CODENTIDA AS [CODIGO EAPB],
EAPB.NOMENTIDA AS [NOMBRE EAPB],
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro' 
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado'
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [REGIMEN],
CON.NUMINGRES_SOL AS INGRESO,
CON.NUMEFOLIO AS FOLIO,
CON.FECHAREGISTRO AS [FECHA SOLICITUD],
CON.ESTADO,
CON.[TIPO DE SOLICITUD],
PADO.PERTINENCIA,
CON.[FECHA ALTA MEDICA],
ING.FECHEGRESO AS [FECHA EGRESO],
CON.[ESTADO PACIENTE AL EGRESO],
CON.FALLECIDO,
CON.[FECHA DE MUERTE],
CON.[CAUSA DE MUERTE],
CON.NO_CERT_DEFUNCION,
CON.[FECHA INGRESO PAD],
CON.NUMINGRES_PAD AS [INGRESO PAD],
CON.[FECHA ALTA MEDICA PAD],
CON.[FECHA EGRESO PAD],
CON.FECHASUSP AS [FECHA SUSPENCIÓN DE SOLICITUD],
'1' AS CATIDAD,
CAST (CON.FECHAREGISTRO as date) 'FECHA BUSQUEDA',
YEAR(CON.FECHAREGISTRO) AS 'AÑO FECHA BUSQUEDA',
MONTH(CON.FECHAREGISTRO) AS 'MES AÑO FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(CON.FECHAREGISTRO), '00') ,' - ', 
	   CASE MONTH(CON.FECHAREGISTRO) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) AS 'MES NOMBRE FECHA BUSQUEDA',
DAY(CON.FECHAREGISTRO) AS 'DIA FECHA BUSQUEDA',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
CTE_CONTROL CON INNER JOIN
dbo.PADORDEN PADO ON CON.ID=PADO.IDPADCONTROL INNER JOIN
dbo.ADINGRESO ING ON CON.NUMINGRES_SOL=ING.NUMINGRES INNER JOIN 
DBO.INPACIENT PAC on CON.IPCODPACI=PAC.IPCODPACI INNER JOIN
DBO.ADCENATEN CEN ON ING.CODCENATE=CEN.CODCENATE INNER JOIN
DBO.INENTIDAD EAPB ON PAC.CODENTIDA=EAPB.CODENTIDA
