-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewReferencia
-- Extracted by Fabric SQL Extractor SPN v3.9.0




    /*******************************************************************************************************************
Nombre: [Report].[ViewReferancia]
Tipo: Vista
Observacion:Oportunidad de la referencia
Profesional: Nilsson Galindo
Fecha:23-10-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico:
Fecha:
Observaciones:
-------------------------------------------------------------------------------------------------------------------------------------
Version 3
Persona que modifico:
Fecha:
Observaciones:
***********************************************************************************************************************************/

CREATE VIEW [Report].[ViewReferencia] AS

WITH

CTE_SOLICITUDES AS
(
SELECT 
RR.AUTO,RR.NUMINGRES,RR.CODCENATE,RR.UFUCODIGO,RR.CODPROSAL,RR.CODESPECI,RR.IDHCREFCONP,RR.MOTREMISI,RR.SERVIDOREM,
RR.NIVELREMIT,RR.FECSOLICIT
FROM dbo.HCREFCONT RR
WHERE CAST(RR.[AUTO] AS INT)=(SELECT MIN(CAST(A.AUTO AS INT)) FROM dbo.HCREFCONT A WHERE RR.NUMINGRES=A.NUMINGRES)
AND RR.MOTREMISI NOT LIKE '%A%'
)

SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CA.NOMCENATE AS [CENTRO DE ATENCION],
DOC.Nombre as [TIPO DOCUMENTO],
PAC.IPCODPACI AS IDENTIFICACION,
PAC.IPNOMCOMP AS [PACIENTE],
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END AS[GENERO DEL PACIENTE],
CAST(PAC.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
CASE ING.CODTIPPAC WHEN '1' THEN 'Maternas' 
				   WHEN '2' THEN 'Pediatrico'
				   WHEN '3' THEN 'Población general' 
				   WHEN '4' THEN 'Adulto mayor' 
				   WHEN '5' THEN 'Población general' END AS [TIPO DE PACIENTE], 
DATEDIFF(YEAR,IPFECNACI ,GETDATE()) -(CASE WHEN DATEADD(YY,DATEDIFF(YEAR,IPFECNACI,GETDATE()),IPFECNACI)>GETDATE() THEN 1 ELSE 0 END) AS EDAD,
HEA.Code AS [CODIGO ENTIDAD],
HEA.Name AS [ENTIDAD],
CG.Name AS [GRUPO DE ATENCION],
RR.NUMINGRES AS [INGRESO],
FUN.UFUDESCRI AS [UNIDAD FUNCIONAL SOLICITUD],
PRO.CODPROSAL AS [IDENTIFICACION PROFESIONAL],
PRO.NOMMEDICO AS [PROFESIONAL DE SOLICITUD],
ESP.DESESPECI AS [ESPECIALIDAD PROFESIONAL],
RRP.CODCONCECG AS CONSECUTIVO,
MOTR.Nombre AS [MOTIVO DE REMISION],
DIA.CODDIAGNO+' - '+DIA.NOMDIAGNO AS [DIAGNOSTICO REFERENCIA],
RR.NIVELREMIT AS [NIVEL A QUE SE REMITE],
ESPR.DESESPECI AS [ESPECIALIDAD A REMITIR],
SER.Nombre AS [SERVICIO REMISION],
CASE RRP.ESTADO WHEN 1 THEN 'Solicitado'
				WHEN 2 THEN 'Pendinte o Gestionando'
				WHEN 3 THEN 'Aceptado con pediente de salida'
				WHEN 4 THEN 'Suspendido'
				WHEN 5 THEN 'Ya salio'
				WHEN 6 THEN 'Solicitud con Pertinencia' END AS ESTADO,
CASE RRD.TIPENTIDAD WHEN 1 THEN 'IPS' 
					WHEN 2 THEN 'EAPB'
					WHEN 3 THEN 'CRUE'
					WHEN 4 THEN 'OTRAS' END AS [TIPO ENTIDAD],
ENT.NOMENTIDA AS [ENTIDAD REFERENCIA],
MODR.Nombre AS [MODALIDAD GESTION],
USU.NOMUSUARI AS [USUARIO SEGUIMIENTO],
IPS.DSCRIPIPS AS [INSTITUCION],
RR.FECSOLICIT AS [FECHA SOLICITUD],
RRD.FECSEGUIMIENTO AS [FECHA GUARDADO],
RRD.FECHCREREG AS [FECHA REGISTRO],
RRD.FECHCONFIR AS [FECHA CONFIRMACION],
ING.FECHEGRESO AS [FECHA EGRESO],
RRP.FECHAVISADO AS [FECHA VISADO],
DATEDIFF(HOUR,RR.FECSOLICIT,ING.FECHEGRESO) AS [SOLICITUD VS EGRESO (H)],
MOTS.Nombre AS [MOTIVO SUSPENCION],
RRP.FECHASUSPEN AS [FECHA SUSPENCION],
USUS.NOMUSUARI AS [USUARIO SUSPENCION],
DATEDIFF(HOUR,RR.FECSOLICIT,RRP.FECHASUSPEN) AS [SOLICITUD VS SUPSPENCION (H)],
1 as 'CANTIDAD',
CAST(RR.FECSOLICIT AS date) AS [FECHA BUSQUEDA],
YEAR(RR.FECSOLICIT) AS [AÑO FECHA BUSQUEDA],
MONTH(RR.FECSOLICIT) AS [MES FECHA BUSQUEDA],
CASE MONTH(RR.FECSOLICIT) WHEN 1 THEN 'ENERO'
						  WHEN 2 THEN 'FEBRERO'
						  WHEN 3 THEN 'MARZO'
						  WHEN 4 THEN 'ABRIL'
						  WHEN 5 THEN 'MAYO'
						  WHEN 6 THEN 'JUNIO'
						  WHEN 7 THEN 'JULIO'
						  WHEN 8 THEN 'AGOSTO'
						  WHEN 9 THEN 'SEPTIEMBRE'
						  WHEN 10 THEN 'OCTUBRE'
						  WHEN 11 THEN 'NOVIEMBRE'
						  WHEN 12 THEN 'DICIEMBRE' END AS [MES NOMBRE FECHA BUSQUEDA],
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
CTE_SOLICITUDES RR INNER JOIN
dbo.ADCENATEN CA ON RR.CODCENATE = CA.CODCENATE INNER JOIN
dbo.INUNIFUNC FUN ON RR.UFUCODIGO=FUN.UFUCODIGO INNER JOIN
dbo.ADINGRESO ING ON RR.NUMINGRES=ING.NUMINGRES INNER JOIN
dbo.INPACIENT PAC ON ING.IPCODPACI=PAC.IPCODPACI INNER JOIN
dbo.ADTIPOIDENTIFICA DOC ON PAC.IPTIPODOC=DOC.CODIGO LEFT JOIN
CONTRACT.HEALTHADMINISTRATOR HEA ON CAST(ING.GENCONENTITY as varchar)=HEA.Code LEFT JOIN
Contract.CareGroup CG ON CAST(ING.GENCAREGROUP as varchar)=CG.Code INNER JOIN
dbo.INPROFSAL PRO ON RR.CODPROSAL=PRO.CODPROSAL INNER JOIN
dbo.INESPECIA ESP ON PRO.CODESPEC1=ESP.CODESPECI INNER JOIN
dbo.HCREFCONTDET DX ON RR.AUTO=DX.HCREFCONTAUTO INNER JOIN
dbo.INDIAGNOS DIA ON DX.CODDIAGNO=DIA.CODDIAGNO INNER JOIN
dbo.INESPECIA ESPR ON RR.CODESPECI=ESPR.CODESPECI INNER JOIN
dbo.HCREFCONP RRP ON RR.IDHCREFCONP=RRP.AUTO INNER JOIN
dbo.RCMOTREF MOTR ON RR.MOTREMISI=MOTR.Id INNER JOIN
dbo.RCSERVICIOS SER ON RR.SERVIDOREM=SER.Codigo LEFT JOIN
dbo.HCREFCONTD RRD ON RRP.AUTO=RRD.HCREFCONPID AND RRD.ID=(SELECT MAX(A.ID) FROM dbo.HCREFCONTD A WHERE RRD.HCREFCONPID=A.HCREFCONPID) LEFT JOIN
dbo.INENTIDAD ENT ON RRD.CODENTIDA=ENT.CODENTIDA LEFT JOIN
dbo.RCMODSOLIC MODR ON RRD.RCMODSOLICID=MODR.Id LEFT JOIN
dbo.SEGusuaru USU ON RRD.CODUSUAREG=USU.CODUSUARI LEFT JOIN
dbo.ADCONTIPS IPS ON RRD.IPSACEPTADO=IPS.CODIGOIPS LEFT JOIN
DBO.RCMOTNOREF MOTS ON RRP.RCMOTNOREFID=MOTS.Id LEFT JOIN
dbo.SEGusuaru USUS ON RRP.USUARSUSPEN=USUS.CODUSUARI
--WHERE ING.IPCODPACI='33448680'
