-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewPacientesSinEgreso
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW Report.ViewPacientesSinEgreso AS
SELECT 
HC.IPCODPACI AS [IDENTIFICACION PACIENTE],
PAC.IPNOMCOMP AS [NOMBRE],
HC.NUMEFOLIO AS FOLIO,
HC.NUMINGRES AS [NUMERO INGRESO],
FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
HC.FECHISPAC AS [FECHA HISTORIA CLINICA],
DATOBJETI AS [EVALUACION OBJETIVA],
YEAR(HC.FECHISPAC) AS AÑO,
MONTH(HC.FECHISPAC) AS MES
FROM 
DBO.HCHISPACA HC
INNER JOIN dbo.INPACIENT PAC ON HC.IPCODPACI=PAC.IPCODPACI
LEFT JOIN dbo.INUNIFUNC FUN ON HC.UFUCODIGO=FUN.UFUCODIGO
where INDICAPAC=12 AND GENCONEXT=0 AND
NUMINGRES NOT IN (SELECT NUMINGRES FROM DBO.HCREGEGRE)
