-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_V2_FAC_REPORTE_ESTANCIAS_POR_RECONOCER_HOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[View_V2_FAC_REPORTE_ESTANCIAS_POR_RECONOCER_HOS]
AS

WITH CTE_ESTANCIAS_UNICAS
----CTE PARA IDENTIFICAR LOS INGRESOS UNICOS CON ESTANCIAS PENDIENTES DE LIQUIDAR HOSPITALARIAS
AS
(
 SELECT DISTINCT EST.IPCODPACI ,EST.NUMINGRES,ING.IESTADOIN ,EST.ID,ACS.StayId  FROM   dbo.CHREGESTA EST
 INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES = EST.NUMINGRES 
 LEFT JOIN Billing.AccountControlStays ACS with (nolock) ON ACS.AdmissionCode=EST.NUMINGRES AND ACS.StayId=EST.ID
 WHERE (GENESTLIQ IN (1, 2)) AND ING.TIPOINGRE=2 and  ing.IESTADOIN in (' ','P') AND EST.REGDIAEST>0 and ACS.StayId IS NULL
),
CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
AS
(
    SELECT EGR.IPCODPACI ,EGR.NUMINGRES,EGR.FECINIEST ,EGR.FECFINEST ,EGR.CODICAMAS,CAM.NUMCAMHOS ,FUN.UFUDESCRI  ,FUN.UFUTIPUNI  
	FROM CHREGESTA EGR with (nolock)
	INNER JOIN 
	(
	   SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR with (nolock)
	   INNER JOIN CTE_ESTANCIAS_UNICAS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G  ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM with (nolock) ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),
CTE_EGRESO_CAMA
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO  
FROM CHREGEGRE EGR
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECEGRESO) EGRESO 
 FROM CHREGEGRE EGR with (nolock) 
 INNER JOIN CTE_ESTANCIAS_UNICAS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.EGRESO =EGR.FECEGRESO 
),
CTE_ORDENES_CON_ESTANCIAS_CARGADAS
---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
AS
( 
SELECT RC.AdmissionNumber,G.CANTIDAD  FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN
(
SELECT RC.AdmissionNumber ,/*CUPS.Code CUPS ,CUPS.Description,*/SUM(SOD.InvoicedQuantity) CANTIDAD   
FROM Billing .RevenueControlDetail AS RCD WITH (NOLOCK)
INNER JOIN BILLING.REVENUECONTROL AS RC WITH (NOLOCK) ON RCD.REVENUECONTROLID = RC.ID
INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD WITH (NOLOCK) ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2','3')
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD WITH (NOLOCK) ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN CTE_ESTANCIAS_UNICAS AS UNI with (nolock) ON UNI.NUMINGRES =RC.AdmissionNumber  
INNER JOIN Contract .CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id =SOD.CUPSEntityId AND CUPS.BillingGroupId IN (3,31)
INNER JOIN Contract .IPSService AS IPS WITH (NOLOCK) ON IPS.Id =SOD.IPSServiceId
GROUP BY RC.AdmissionNumber 
) AS G ON G.AdmissionNumber =RC.AdmissionNumber
),
CTE_TARIFA_ESTANCIAS
----CTE PARA IDENTIFICAR LAS TARIFAS DE LAS CAMAS
AS
(
SELECT TAR.CODCONCEC,tar.UFUCODIGO 'CODIGO UNIDAD', UNI.UFUDESCRI 'UNIDAD FUNCIONAL' ,TAR.CODICAMAS,CAM.NUMCAMHOS 'CAMA' ,TAR.CODTIPEST ,TAR.TIPLIQEST ,TAR.NUMHOREST ,TAR.GENCUPS ,
ISNULL(IPS.Code,IPS2.Code ) 'CUPS ESTANCIA' ,ISNULL(IPS.Description,IPS2.Description )'ESTANCIA',TAR.IDDESCRIPCIONRELACIONADA_CUPS ,TAR.IDDESCRIPCIONRELACIONADA_CUPS2 
FROM DBO.CHGENTARI TAR WITH (NOLOCK) 
INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON TAR.UFUCODIGO =UNI.UFUCODIGO 
INNER JOIN DBO.CHCAMASHO AS CAM WITH (NOLOCK) ON CAM.CODICAMAS  =TAR.CODICAMAS 
LEFT JOIN Contract.CUPSEntity  AS IPS WITH (NOLOCK) ON IPS.Id =TAR.GENCUPS ---URGENCIAS
LEFT JOIN Contract.CUPSEntity  AS IPS2 WITH (NOLOCK) ON IPS2.Id =TAR.GENCUPS2 ---HOSPITALIZACION
),

CTE_DATOS_ESTANCIAS
---CTE QUE ME TRAE LOS DATOS DE LOS HEMOCOMPONENTES DE FORMA AGRUPADA
AS
(
SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(TAR.[CUPS ESTANCIA]) AS CODSERIPS,TAR.ESTANCIA DESSERIPS,
SUM(IIF((A.REGDIAEST=0 AND A.FECFINEST='1900-01-01 00:00:00.000'),DATEDIFF(DAY,A.FECINIEST,GETDATE ()),DATEDIFF(DAY,A.FECINIEST,A.FECFINEST))) AS CANSERIPS,UNI.IESTADOIN ,
HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',MIN(A.FECINIEST) 'FECHA REALIZADO MINIMA' ,MAX(A.FECFINEST) 'FECHA REALIZADO MAXIMA'
 FROM dbo.CHREGESTA A WITH (NOLOCK)
   INNER JOIN DBO.INPACIENT AS P WITH (NOLOCK) ON P.IPCODPACI =A.IPCODPACI 
   INNER JOIN DBO.CHCAMASHO AS CAM WITH (NOLOCK) ON CAM.CODICAMAS =A.CODICAMAS 
   INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES=A.NUMINGRES
   INNER JOIN CTE_ESTANCIAS_UNICAS AS UNI with (nolock) ON UNI.NUMINGRES =A.NUMINGRES AND A.ID =UNI.ID
   INNER JOIN CTE_TARIFA_ESTANCIAS AS TAR WITH (NOLOCK) ON TAR.CODICAMAS =A.CODICAMAS AND TAR.CODTIPEST =A.CODTIPEST 
   INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
   INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id 
   LEFT JOIN Billing.AccountControlStays ACS with (nolock) ON ACS.AdmissionCode=A.NUMINGRES AND ACS.StayId=A.ID
   WHERE (GENESTLIQ IN (1, 2)) AND ACS.StayId IS NULL AND A.REGDIAEST>0
   AND IIF((A.REGDIAEST=0 AND A.FECFINEST='1900-01-01 00:00:00.000'),DATEDIFF(DAY,A.FECINIEST,GETDATE ()),A.REGDIAEST)>0
   AND IIF((A.REGDIAEST=0 AND A.FECFINEST='1900-01-01 00:00:00.000'),DATEDIFF(MINUTE,A.FECINIEST,GETDATE ()),DATEDIFF(MINUTE,A.FECINIEST,FECFINEST))>30
   GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,TAR.[CUPS ESTANCIA],TAR.ESTANCIA,UNI.IESTADOIN,HA.Name , CG.Name ,ING.IFECHAING
)

SELECT ING.NUMINGRES,ing.IESTADOIN,ING.[FECHA INGRESO] ,ING.ENTIDAD ,ING.[GRUPO ATENCION]   ,ING.IPCODPACI ,ING.IPNOMCOMP ,ING.CODSERIPS ,ING.DESSERIPS,ING.CANSERIPS,CAM.UFUDESCRI  ,
CAM.NUMCAMHOS,EGR.FECEGRESO,'' 'CUPS CARGADO',CAR.CANTIDAD 'CANTIDAD CARGADA',ING.[FECHA REALIZADO MINIMA] ,ING.[FECHA REALIZADO MAXIMA] 
FROM CTE_DATOS_ESTANCIAS ING with (nolock) 
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM with (nolock) ON ING.NUMINGRES =CAM.NUMINGRES
LEFT JOIN CTE_EGRESO_CAMA EGR with (nolock) ON EGR.NUMINGRES =ING.NUMINGRES
LEFT JOIN CTE_ORDENES_CON_ESTANCIAS_CARGADAS CAR with (nolock) ON CAR.AdmissionNumber =ING.NUMINGRES --AND CAR.CUPS =ING.CODSERIPS 
WHERE ING.CANSERIPS <>ISNULL(CAR.CANTIDAD,0)  AND ING.CANSERIPS >ISNULL(CAR.CANTIDAD,0)
AND CAM.UFUTIPUNI NOT IN ('1','19') --AND CAM.NUMCAMHOS NOT LIKE 'U%' AND CAM.NUMCAMHOS NOT LIKE 'O%' AND CAM.NUMCAMHOS NOT LIKE 'SRE%'
--AND CAM.NUMCAMHOS NOT LIKE 'SAL%' AND CAM.NUMCAMHOS NOT LIKE 'PRE%' AND CAM.NUMCAMHOS NOT LIKE 'REC%'

