-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: VIEW_SEG_ESTANCIAS
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [report].VIEW_SEG_ESTANCIAS AS



SELECT 
A.IPCODPACI AS [IDENTIFICACION PACIENTE],
PAC.IPNOMCOMP AS PACIENTE,
A.NUMINGRES AS INGRESO,
A.TRIAGECLA AS [CLASIFICACION DE TRIAGE],
A.TRIAFECHA AS [FECHA DE TRIAGE],
HC.FECHISPAC AS [FECHA ULTIMO FOLIO],
DATEDIFF(HOUR,A.TRIAFECHA,HC.FECHISPAC) AS [HORAS SIN DESTINO],
CASE HC.INDICAPAC WHEN 11 THEN 'Morgue' 
				  WHEN 12 THEN 'Salida' 
				  WHEN 13 THEN 'Continua en la Unidad' ELSE '' END AS [ULTIMO DESTINO]
FROM 
dbo.ADTRIAGEU A INNER JOIN
dbo.HCURGING1 B ON A.NUMINGRES=B.NUMINGRES AND A.ID=(SELECT MIN(EU.ID) FROM dbo.ADTRIAGEU EU WHERE A.NUMINGRES=EU.NUMINGRES) INNER JOIN
dbo.INPACIENT PAC ON A.IPCODPACI=PAC.IPCODPACI AND B.ID=(SELECT MAX(G1.ID) FROM dbo.HCURGING1 G1 WHERE B.NUMINGRES=G1.NUMINGRES) INNER JOIN
dbo.ADINGRESO ING ON B.NUMINGRES=ING.NUMINGRES AND ING.UFUAACTHOS IS NULL AND B.INDICAPAC=13 LEFT JOIN
dbo.HCHISPACA HC ON B.NUMINGRES=HC.NUMINGRES AND HC.NUMEFOLIO=(SELECT MAX(H.NUMEFOLIO) FROM dbo.HCHISPACA H WHERE A.NUMINGRES=H.NUMINGRES AND H.INDICAPAC IN (10,11,12,13,15,16))
WHERE DATEDIFF(HOUR,A.TRIAFECHA,HC.FECHISPAC)>6-- AND B.NUMINGRES='68541'



--select * from dbo.ADTRIAGEU where NUMINGRES in ('67905     ')
--select * from ADINGRESO where NUMINGRES in ('63202')
--select * from dbo.HCURGING1 where NUMINGRES in ('63202')
--select * from HCHISPACA where NUMINGRES in ('66608 ')



     
