-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewCitologia
-- Extracted by Fabric SQL Extractor SPN v3.9.0






CREATE VIEW [Report].[ViewCitologia] as

/*
INDIGO001
INDIGO006
INDIGO007
INDIGO008
INDIGO009
INDIGO010
INDIGO012
INDIGO013
INDIGO014
INDIGO015
INDIGO029
INDIGO030
*/

WITH

CTE_GESTACION	AS
 (
	SELECT HCR1.IPCODPACI IPCODPACI, HCR1.NUMINGRCES NUMINGRES, GESTACION, FECGESTA, INP.IPTIPODOC,
	CAST([Report].[FN_Medicamento_Rias_Benzatinica_Fecha](HCR1.FECGESTA,HCR1.IPCODPACI) AS date) AS 'FECHA_BENZATINICA'                      
	FROM dbo.HCRIESGOSP HCR1 WITH (NOLOCK)
		INNER JOIN dbo.INPACIENT INP WITH (NOLOCK) ON HCR1.IPCODPACI=INP.IPCODPACI
		INNER JOIN (SELECT MAX(NUMINGRCES) NUMINGRCES, IPCODPACI 
		FROM dbo.HCRIESGOSP WITH (NOLOCK) 
		WHERE NUMINGRCES IS NOT NULL 
        GROUP BY IPCODPACI) HCR2 
		ON  HCR1.NUMINGRCES=HCR2.NUMINGRCES AND HCR1.IPCODPACI=HCR2.IPCODPACI 
 ),

CTE_ANTECEDENTES_GINECOBTETRICOS AS
 (
	SELECT GIN.IPCODPACI PACIENTE, 
		   GIN.NUMEFOLIO FOLIO, 
		   GIN.NUMINGRES INGRESO, 
		   MAX(GIN.FECHISPAC) FECHAHC,
		   GIN.FECULTCIT CITO ,
		   GIN.EDADVIDSE EDDSEX, 
		   GIN.FECHAPLA FECHAPLA, 
		   GIN.CODPLANIF METODO 
		   FROM HCANTGINE GIN
		GROUP BY GIN.IPCODPACI, GIN.NUMEFOLIO , GIN.NUMINGRES , GIN.FECHISPAC ,GIN.FECULTCIT ,GIN.EDADVIDSE , GIN.FECHAPLA , GIN.CODPLANIF 
 ),


CTE_FACTURACION_TIPO_CITOLOGIA AS
 (
  SELECT F.AdmissionNumber ,F.PatientCode ,CUPS.Code ,CUPS.Description  FROM   BILLING.INVOICE AS F WITH (NOLOCK) 
		   INNER JOIN BILLING.INVOICEDETAIL AS DF WITH (NOLOCK) ON DF.INVOICEID = F.ID 
		   INNER JOIN BILLING.REVENUECONTROLDETAIL RCD WITH (NOLOCK) ON RCD.ID = F.REVENUECONTROLDETAILID 
		   INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES = F.ADMISSIONNUMBER 
		   INNER JOIN DBO.ADCENATEN AS CEN WITH (NOLOCK) ON CEN.CODCENATE = ING.CODCENATE 
		   INNER JOIN BILLING.SERVICEORDERDETAIL AS DOS WITH (NOLOCK) ON DOS.ID = DF.SERVICEORDERDETAILID
		   LEFT OUTER JOIN CONTRACT.CUPSENTITY AS CUPS WITH (NOLOCK) ON CUPS.ID = DOS.CUPSENTITYID
		   WHERE CUPS.Code IN ('892904','892901','898001','908436') AND F.Status =1 
		   group by F.AdmissionNumber ,F.PatientCode ,CUPS.Code ,CUPS.Description
 ),

CTE_FECHA_REMISION_CITOL AS 
 (
  SELECT AMB.CODSERIPS SERVICIO, MAX(FECORDMED) FECHAORD, AMB.ESTSERIPS ESTADO, AMB.IPCODPACI PACIENTE, AMB.FECHARESULT RESULT  FROM   AMBORDLAB AS AMB WITH (NOLOCK) 
  INNER JOIN HCHISPACA AS HIS WITH (NOLOCK) ON HIS.IPCODPACI = AMB.IPCODPACI 
  WHERE AMB.CODSERIPS IN ('892904','892901','898001','908436') AND AMB.ESTSERIPS=5 
  group by AMB.IPCODPACI , AMB.CODSERIPS, AMB.FECORDMED, AMB.ESTSERIPS, AMB.FECHARESULT
  ),

CTE_NOTAS_ADMINISTRATIVAS_CITOLOGIA AS
 (
   Select
   NA.IPCODPACI,NA.NUMINGRES, V1.VALOR AS FECHA_SEGUIMIENTO,V2.VALOR AS FECHA_RESULTADO_ANTERIOR,V3.VALOR AS FECHA_RESULTADO_ACTUAL,
   V4.VALOR AS RESULTADO_ANTERIOR,V5.VALOR AS TRATAMIENTO_RECIBIDOS,V7.NOMBRE AS CELULAS_ESCAMOSAS, V9.NOMBRE AS CELULARES_GLANDULARES,
   V11.NOMBRE AS CALIDAD_MUESTRA,V13.NOMBRE AS CLASIFICACION_GENERAL,V15.NOMBRE AS RESULTADO_MICROBIOLOGIA,V17.NOMBRE AS PROXIMA_CITOLOGIA
   From  
   NTADMINISTRATIVAS GNA INNER JOIN
   NTNOTASADMINISTRATIVASC NA ON GNA.ID=NA.IDNOTAADMINISTRATIVA INNER JOIN
   NTNOTASADMINISTRATIVASD V1 ON V1.IDNTNOTASADMINISTRATIVASC=NA.ID AND V1.IDNTVARIABLE=20 LEFT JOIN--fecha de seguimiento
   NTNOTASADMINISTRATIVASD V2 ON V2.IDNTNOTASADMINISTRATIVASC=NA.ID AND V2.IDNTVARIABLE=39 LEFT JOIN --Fecha de resultado de citologia anterior a la actual
   NTNOTASADMINISTRATIVASD V3 ON V3.IDNTNOTASADMINISTRATIVASC=NA.ID AND V3.IDNTVARIABLE=40 LEFT JOIN--Fecha de resultado de citologia actual
   NTNOTASADMINISTRATIVASD V4 ON V4.IDNTNOTASADMINISTRATIVASC=NA.ID AND V4.IDNTVARIABLE=41 LEFT JOIN--Resultado de citologia anterior a la actual
   NTNOTASADMINISTRATIVASD V5 ON V5.IDNTNOTASADMINISTRATIVASC=NA.ID AND V5.IDNTVARIABLE=42 LEFT JOIN--Tratamientos recibidos
   NTNOTASADMINISTRATIVASD V6 ON V6.IDNTNOTASADMINISTRATIVASC=NA.ID AND V6.IDNTVARIABLE=43 LEFT JOIN
   NTVARIABLESL V7 ON V7.CODIGO=V6.VALOR AND V7.IDNTVARIABLE=43 LEFT JOIN--Hallazgos en celulas escamosas
   NTNOTASADMINISTRATIVASD V8 ON V8.IDNTNOTASADMINISTRATIVASC=NA.ID AND V8.IDNTVARIABLE=44 LEFT JOIN
   NTVARIABLESL V9 ON V9.CODIGO=V8.VALOR AND V9.IDNTVARIABLE=44 LEFT JOIN--Hallazgos en celulas glandulares
   NTNOTASADMINISTRATIVASD V10 ON V10.IDNTNOTASADMINISTRATIVASC=NA.ID AND V10.IDNTVARIABLE=45 LEFT JOIN
   NTVARIABLESL V11 ON V11.CODIGO=V10.VALOR AND V11.IDNTVARIABLE=45 LEFT JOIN--Calidad de la muestra
   NTNOTASADMINISTRATIVASD V12 ON V12.IDNTNOTASADMINISTRATIVASC=NA.ID AND V12.IDNTVARIABLE=46 LEFT JOIN
   NTVARIABLESL V13 ON V13.CODIGO=V12.VALOR AND V13.IDNTVARIABLE=46 LEFT JOIN--Clasificación general
   NTNOTASADMINISTRATIVASD V14 ON V14.IDNTNOTASADMINISTRATIVASC=NA.ID AND V14.IDNTVARIABLE=47 LEFT JOIN
   NTVARIABLESL V15 ON V15.CODIGO=V14.VALOR AND V15.IDNTVARIABLE=47 LEFT JOIN--Resultado microbiologico
   NTNOTASADMINISTRATIVASD V16 ON V16.IDNTNOTASADMINISTRATIVASC=NA.ID AND V16.IDNTVARIABLE=48 LEFT JOIN
   NTVARIABLESL V17 ON V17.CODIGO=V16.VALOR AND V17.IDNTVARIABLE=48 --Proxima citologia
   WHERE GNA.NOMBRE LIKE '%RESULTADO DE CITOLOGIA%' --AND NA.IPCODPACI='1234567'
 )

SELECT 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 HA.Code AS 'CODIGO EAPB',HA.Name AS 'NOMBRE EAPB',
 CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' 
					WHEN '2' THEN 'CEDULA DE EXTRANJERIA' 
					WHEN '3' THEN 'TARJETA DE IDENTIDAD' 
					WHEN '4' THEN 'REGISTRO CIVIL' 
					WHEN '5' THEN 'PASAPORTE'
					WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' 
					WHEN '7' THEN 'MENOR SIN IDENTIFICACION' 
					WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACIÒN' 
					WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' 
					WHEN '10' THEN 'CARNET DIPLOMATICO'
					WHEN '11' THEN 'SALVOCONDUCTO' 
					WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' END AS [TIPO DOCUMENTO],
 HC.IPCODPACI 'IDENTIFICACION', 
 HC.NUMINGRES AS 'NUMERO DE INGRESO',
 PAC.IPNOMCOMP 'NOMBRE PACIENTE',
 PAC.IPPRINOMB AS 'PRIMER NOMBRE', 
 PAC.IPSEGNOMB AS 'SEGUNDO NOMBRE', 
 PAC. IPPRIAPEL AS 'PRIMER APELLIDO', 
 PAC.IPSEGAPEL AS 'SEGUNDO APELLIDO', 
 CAST(PAC.IPFECNACI AS DATE) AS 'FECHA NAC.',
 CASE PAC.IPSEXO WHEN 'M' THEN 'FEMENINO'
 WHEN 'H' THEN 'MASCULINO' END 'SEXO',
 FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS 'EDAD', 
 PAC.IPTELEFON AS 'TEL. FIJO',
 PAC.IPTELMOVI AS 'TEL. MOVIL',
 MUN.MUNNOMBRE AS 'MUNICIPIO PACIENTE',
 UB.UBINOMBRE AS 'BARRIO', 
 HC.FECHISPAC 'FECHA ATENCION',
 GIN.EDDSEX 'INICIO SEXUAL', 
 ANT.ANTQUIPAC AS 'HISTERECTOMIA', 
 CASE WHEN RIE.GESTACION = 1 THEN 'SI' ELSE 'NULL' END 'GESTANTE', 
 GIN.CITO AS 'FECHA ULTIMA CITO.', 
 CIT.Code  'CODIGO SERVICIO',
 IIF(CIT.code IS NULL, 'NO HAY DATO', 
     CASE WHEN CIT.Code='892901' OR CIT.Code='898001' THEN 'CITOLOGIA CERVICOUTERINA'
	      WHEN CIT.Code='908436' THEN 'TAMIZACION ADN-VPH' 
		  ELSE 'INPECCION VISUAL' END) 'TIPO CITOLOGIA', 
 ORD.FECHAORD AS 'FECHA DE REMISION MUESTRA',
 NAC.FECHA_SEGUIMIENTO 'FECHA DE SEGUIMIENTO',
 NAC.FECHA_RESULTADO_ANTERIOR 'FECHA RESULTADO ANTERIOR CI',
 NAC.FECHA_RESULTADO_ACTUAL,
 NAC.RESULTADO_ANTERIOR,
 NAC.TRATAMIENTO_RECIBIDOS,
 NAC.CELULAS_ESCAMOSAS,
 NAC.CELULARES_GLANDULARES,
 NAC.CALIDAD_MUESTRA,
 NAC.CLASIFICACION_GENERAL,
 NAC.RESULTADO_MICROBIOLOGIA,
 NAC.PROXIMA_CITOLOGIA, 
 ORD.RESULT 'FECHA RECEPCION RESULTADO',
 CASE GIN.METODO WHEN 1 THEN 'NO PLANIFICA' 
				 WHEN 2 THEN 'ORAL'
				 WHEN 3 THEN 'PRESERVATIVO'
				 WHEN 4 THEN 'INYECTABLE'
				 WHEN 5 THEN 'DIU'
				 WHEN 6 THEN 'POMEROY'
				 WHEN 7 THEN 'VASECTOMIA'
				 WHEN 8 THEN 'OTROS'
				 WHEN 9 THEN 'IMPLANTE SUBDÉRMICO' END 'METODO PLANIFICACION' ,
				 PROF.NOMMEDICO 'PROFESIONAL QUE ATIENDE', 
 1 as 'CANTIDAD',
 CAST(HC.FECHISPAC AS date) AS 'FECHA BUSQUEDA', 
 YEAR(HC.FECHISPAC) AS 'AÑO FECHA BUSQUEDA', 
 MONTH(HC.FECHISPAC) AS 'MES AÑO FECHA BUSQUEDA', 
 CASE MONTH(HC.FECHISPAC) 
      WHEN 1 THEN 'ENERO'
	  WHEN 2 THEN 'FEBRERO'
	  WHEN 3 THEN 'MARZO'
	  WHEN 4 THEN 'ABRIL'
	  WHEN 5 THEN 'MAYO'
	  WHEN 6 THEN 'JUNIO'
	  WHEN 7 THEN 'JULIO'
	  WHEN 8 THEN 'AGOSTO'
	  WHEN 9 THEN 'SEPTIEMBRE'
	  WHEN 10 THEN 'OCTUBRE'
	  WHEN 11 THEN 'NOVIEMBRE'
	  WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA', 
  FORMAT(DAY(HC.FECHISPAC), '00') AS 'DIA FECHA BUSQUEDA',
  CONCAT(MONTH (HC.FECHISPAC),
       ' - ', 
	   CASE MONTH(HC.FECHISPAC) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_INGRESO,
  CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
  FROM DBO.HCHISPACA AS HC WITH(NOLOCK) 
  INNER JOIN DBO.INPACIENT AS PAC WITH(NOLOCK) ON PAC.IPCODPACI = HC.IPCODPACI
  INNER JOIN DBO.INPROFSAL AS PROF WITH(NOLOCK) ON PROF.CODPROSAL = HC.CODPROSAL 
  INNER JOIN DBO.INUBICACI AS UB WITH(NOLOCK) ON UB.AUUBICACI = PAC.AUUBICACI 
  INNER JOIN  DBO.INMUNICIP AS MUN WITH(NOLOCK) ON MUN.DEPMUNCOD = UB.DEPMUNCOD 
  LEFT OUTER JOIN CTE_NOTAS_ADMINISTRATIVAS_CITOLOGIA NAC ON HC.IPCODPACI=NAC.IPCODPACI AND HC.NUMINGRES=NAC.NUMINGRES
  LEFT OUTER JOIN CTE_ANTECEDENTES_GINECOBTETRICOS AS GIN WITH(NOLOCK) ON GIN.PACIENTE = PAC.IPCODPACI AND HC.NUMEFOLIO=GIN.FOLIO AND HC.NUMINGRES=GIN.INGRESO
  LEFT OUTER JOIN DBO.HCANTPACH AS ANT WITH(NOLOCK) ON ANT.IPCODPACI = HC.IPCODPACI AND ANTQUIPAC LIKE '%HISTER%'
  LEFT OUTER JOIN CTE_GESTACION AS RIE WITH(NOLOCK) ON RIE.IPCODPACI=HC.IPCODPACI
  LEFT OUTER JOIN CTE_FACTURACION_TIPO_CITOLOGIA AS CIT WITH(NOLOCK) ON CIT.PatientCode=HC.IPCODPACI
  LEFT OUTER JOIN CTE_FECHA_REMISION_CITOL AS ORD WITH(NOLOCK) ON ORD.PACIENTE=HC.IPCODPACI 
  LEFT JOIN .Contract.HealthAdministrator AS HA WITH(NOLOCK) ON HA.Code=PAC.CODENTIDA --inner join
WHERE
 HC.IDMODELOHC='35'
