-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewDiagnoses
-- Extracted by Fabric SQL Extractor SPN v3.9.0



/*******************************************************************************************************************
Nombre: [Report].[ViewDiagnoses]
Tipo:Vista
Observacion:Diagnosticos por ingreso
Profesional:Nilsson Miguel Galindo Lopez
Fecha:31-01-2024
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha: 17-05-2024
Observaciones: se agrega el nombre del paciente por separado. 
--------------------------------------------------------------------------------------
Version 2
Persona que modifico:
Fecha:
Ovservaciones:
_______________________________________________________________________________________________________________________

**********************************************************************************************************************/
CREATE VIEW [Report].[ViewDiagnoses]
AS

WITH
CTE_DX_PRINCIPAL AS
(
SELECT
0 AS NUMERO,
CODCENATE,
NUMEFOLIO,
UFUCODIGO,
NUMINGRES,
IPCODPACI,
CODDIAGNO,
DIAINGEGR,
TIPDIAGNO,
CLADIAGNO,
OBSDIAGNO,
FECDIAGNO,
1 AS [DX PRINCIPAL]
FROM
dbo.INDIAGNOP WHERE CODDIAPRI=1
),
CTE_DX_RELACIONADOS AS
(
SELECT
ROW_NUMBER ( )   
OVER (PARTITION BY NUMINGRES ORDER BY FECDIAGNO DESC) AS NUMERO,
CODCENATE,
NUMEFOLIO,
UFUCODIGO,
NUMINGRES,
IPCODPACI,
CODDIAGNO,
DIAINGEGR,
TIPDIAGNO,
CLADIAGNO,
OBSDIAGNO,
FECDIAGNO,
0 AS [DX PRINCIPAL]
FROM
dbo.INDIAGNOP WHERE CODDIAPRI!=1
),
CTE_DX AS
(
SELECT * FROM CTE_DX_PRINCIPAL
UNION ALL
SELECT * FROM CTE_DX_RELACIONADOS
)

SELECT 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CEN.NOMCENATE AS [CENTRO DE ATENCION],
HEA.HealthEntityCode AS [CODIGO EPS/ENTIDAD TERRITORIAL],
HEA.CODE AS [CODIGO ENTIDAD], 
RTRIM(HEA.NAME) AS ENTIDAD, 
RTRIM(CGR.NAME) AS [GRUPO DE ATENCION],
CASE PAC.IPTIPOPAC WHEN 1 THEN 'CONTRIBUTIVO' 
				   WHEN 2 THEN 'SUBSIDIADO' 
				   WHEN 3 THEN 'VINCULADO' 
				   WHEN 4 THEN 'PARTICULAR' 
				   WHEN 5 THEN 'OTRO' 
				   WHEN 6 THEN 'DESPLAZADO REG. CONTRIBUTIVO' 	 
				   WHEN 7 THEN 'DESPLAZADO REG. SUBSIDIADO' ELSE 'DESPLAZADO NO ASEGURADO' END AS RÉGIMEN,
TIPD.SIGLA AS [TIPO IDENTIFICACIÓN],
PAC.IPCODPACI AS [IDENDTIFICACIÓN],
PAC.IPPRIAPEL AS [PRIMER APELLIDO PACIENTE],
PAC.IPSEGAPEL AS [SEGUNDO APELLIDO PACIENTE],
PAC.IPPRINOMB AS [PRIMER NOMBRE PACIENTE],
PAC.IPSEGNOMB AS [SEGUNDO NOMBRE PACIENTE],
RTRIM(PAC.IPNOMCOMP) AS [NOMBRE COMPLETO PACIENTE], 
CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO], 
FLOOR((CAST(CONVERT(VARCHAR(8),ING.IFECHAING,112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS EDAD,
CASE WHEN PAC.IPSEXOPAC = '1' THEN 'M' ELSE 'F' END AS SEXO,
PAC.IPDIRECCI AS DIRECCION,
PAC.IPTELEFON AS [TELEFONO FIJO],
PAC.IPTELMOVI AS [TELEFONO MOVIL],
CASE PAC.CODGRUPOE WHEN '000' THEN 'OTRO'
				   WHEN '001' THEN 'INDIGENAS'
				   WHEN '002' THEN 'AFROCOLOMBIANOS NEGROS MULATOS O AFRODESCENDIENTES'
				   WHEN '003' THEN 'RAIZALES SAN ANDRES Y PROVIDENCIA'
				   WHEN '004' THEN 'PUEBLO ROM GITANOS'
				   WHEN '999' THEN 'NO SABE  NO INFORMA  NO APLICA' ELSE 'NO REGISTRA' END AS [ETNIA PACIENTE],
FUN.UFUDESCRI AS [UNIDAD ASIGNACIÓN DX],
DX.NUMINGRES AS INGRESO,
DX.NUMEFOLIO AS FOLIO,
DX.CODDIAGNO AS [CODIGO DIAGNOSTICO],
DIA.NOMDIAGNO AS DIAGNOSTICO,
CASE DX.[DX PRINCIPAL] WHEN 1 THEN 'SI'
					   WHEN 0 THEN 'NO' END AS [DX PRINCIPAL],
CASE DX.DIAINGEGR WHEN 'I' THEN 'Ingreso'
				  WHEN 'E' THEN 'Egreso'
				  WHEN 'A' THEN 'Ambos' END AS [DX EGRESO O INGRESO],
CASE DX.TIPDIAGNO WHEN 'I' THEN 'Impresion Diagnostica'
				  WHEN 'C' THEN 'Confirmado Nuevo'
				  WHEN 'R' THEN 'Confirmado Repetido' END AS [TIPO DE DX],
CASE DX.CLADIAGNO WHEN 'PR' THEN 'Pre-operatorio'
				  WHEN 'PO' THEN 'Pos-operatorio'
				  WHEN 'PP' THEN 'Pre y Pos-Operatorio'
				  WHEN 'HI' THEN 'Hispatologico'
				  WHEN 'NA' THEN 'No Aplica' END AS [CLASE DE DX],
DX.OBSDIAGNO AS OBSERVACIÓN,
DX.FECDIAGNO AS [FECHA DX],
 1 as 'CANTIDAD',
 CAST(DX.FECDIAGNO AS date) AS 'FECHA BUSQUEDA',
 YEAR(DX.FECDIAGNO) AS 'AÑO BUSQUEDA',
 MONTH(DX.FECDIAGNO) AS 'MES BUSQUEDA',
 CONCAT(FORMAT(MONTH(DX.FECDIAGNO), '00') ,' - ', 
	   CASE MONTH(DX.FECDIAGNO) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
CTE_DX AS DX
INNER JOIN dbo.ADINGRESO AS ING ON DX.NUMINGRES=ING.NUMINGRES
INNER JOIN dbo.INPACIENT PAC ON ING.IPCODPACI=PAC.IPCODPACI
INNER JOIN dbo.ADTIPOIDENTIFICA TIPD ON PAC.IPTIPODOC=TIPD.CODIGO
INNER JOIN CONTRACT.HEALTHADMINISTRATOR HEA ON ING.GENCONENTITY = HEA.ID
INNER JOIN CONTRACT.CAREGROUP AS CGR ON ING.GENCAREGROUP = CGR.ID
INNER JOIN ADCENATEN AS CEN ON DX.CODCENATE=CEN.CODCENATE
INNER JOIN dbo.INUNIFUNC FUN ON DX.UFUCODIGO=FUN.UFUCODIGO
LEFT JOIN dbo.INDIAGNOS DIA ON DX.CODDIAGNO=DIA.CODDIAGNO
--WHERE ING.NUMINGRES='3E0C520EF5'
