-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: VIEW_SEG_GASES
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE view [Report].VIEW_SEG_GASES as

WITH
CTE_INSUMOS AS
(
SELECT 
FARD.NUMINGRES,
SUP.Code,
INV.Name,
SUM(FARD.CANPEDPRO) AS [# SOLICITUDES]
FROM
dbo.HCFARMEPD FARD INNER JOIN
Inventory.InventorySupplie SUP ON CODPRODUC=SUP.Code INNER JOIN
Inventory.InventoryProduct INV ON SUP.ID=INV.SupplieId 
WHERE (INV.NAME LIKE '%CANULA%' OR INV.NAME LIKE '%MASCARA%') AND INV.Code NOT IN ('71007K','00143M')
GROUP BY FARD.NUMINGRES,SUP.Code,INV.Name
),
CTE_OXIGENO AS
(
SELECT 
COUNT(*) AS [# DE REGISTROS GAS],
NUMINGRES
FROM dbo.HCCONOXIG GROUP BY NUMINGRES
)
SELECT
ING.IPCODPACI,
OXI.NUMINGRES,
OXI.[# DE REGISTROS GAS],
FAR.Code AS [CODIGO INSUMO],
FAR.Name AS INSUMO,
FAR.[# SOLICITUDES]
FROM 
CTE_OXIGENO OXI INNER JOIN 
dbo.ADINGRESO ING ON OXI.NUMINGRES=ING.NUMINGRES LEFT JOIN
CTE_INSUMOS FAR ON OXI.NUMINGRES=FAR.NUMINGRES

