-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewOrdenamientoInsumosQx
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE view [Report].[ViewOrdenamientoInsumosQx] as

SELECT 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 INF.FECHAORDE FECHA_ORDEN,  
 INF.IPCODPACI AS DOCUMENTO,   
 LTRIM(RTRIM(PAC.IPNOMCOMP)) AS NOMBREPACIENTE,   
 INF.NUMINGRES AS INGRESO,   
 INF.NUMEFOLIO AS FOLIO_SOLICITUD,  
 UF.UFUDESCRI AS UNIDAD_FUNCIONAL,   
 INF.INDFARINT AS MATERIAL,  
 PRO.NOMMEDICO AS MEDICO_SOLICITA, 
 ESP.DESESPECI AS ESPECIALIDAD, 
 ENT.NOMENTIDA AS ENTIDAD,  
 CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END AS TIPOINGRESO,
 T2.CODDIAGNO AS DIAGNOSTICO_PRINCIPAL, 
 ND.NOMDIAGNO AS NOMBRE_DIAGNOSTICO, 
 1 as 'CANTIDAD',
  CAST(INF.FECHAORDE AS date) AS 'FECHA BUSQUEDA',
  YEAR(INF.FECHAORDE) AS 'AÑO BUSQUEDA',
  MONTH(INF.FECHAORDE) AS 'MES BUSQUEDA',
  CONCAT(FORMAT(MONTH(INF.FECHAORDE), '00') ,' - ', 
	   CASE MONTH(INF.FECHAORDE) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 DBO.HCPRESCRC AS INF  
 RIGHT JOIN  
(  
    SELECT MIN(CODCONCEC) ID, NUMINGRES,MIN(FECHAORDE) FECHA  
    FROM DBO.HCPRESCRC AS INF  
    WHERE INDFARINT <> '' AND INDFARINT IS NOT NULL   
    GROUP BY NUMINGRES  
) AS T ON INF.CODCONCEC = T.ID  
     INNER JOIN DBO.INPACIENT AS PAC ON INF.IPCODPACI = PAC.IPCODPACI  
     INNER JOIN DBO.INUNIFUNC AS UF ON INF.UFUCODIGO = UF.UFUCODIGO  
  INNER JOIN DBO.INENTIDAD AS ENT ON PAC.CODENTIDA =ENT.CODENTIDA  
  INNER JOIN DBO.INPROFSAL AS PRO ON INF.CODPROSAL=PRO.CODPROSAL  
  INNER JOIN DBO.INESPECIA AS ESP ON PRO.CODESPEC1=ESP.CODESPECI  
  INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES=T.NUMINGRES  
  INNER JOIN (SELECT NUMINGRES, CODDIAGNO FROM DBO.INDIAGNOP WHERE CODDIAPRI=1) AS T2 ON T2.NUMINGRES=T.NUMINGRES  
  INNER JOIN DBO.INDIAGNOS AS ND ON T2.CODDIAGNO=ND.CODDIAGNO 