-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewDailyBedCensus
-- Extracted by Fabric SQL Extractor SPN v3.9.0







/*******************************************************************************************************************
Nombre: [Report].[ViewDailyBedCensus]
Tipo:Procedimiento Vista
Observacion:Informe del censo diario de camas
Profesional: Nilsson Miguel Galindo Lopez
Fecha:29-09-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha: 17-07-2024
Ovservaciones: Se agrga la condicion en el CTE_ESPECIALIDAD_FINAL para evitar que se duplice los registros, cuando al paciente
			   se le realiza traslado y no es aceptado de inmediato en la nueva ubicación.
-----------------------------------------------------------------------------------------------------------------------------------------
Version 3
Persona que modifico:
Fecha:
Observacion:
***********************************************************************************************************************************/
CREATE VIEW [Report].[ViewDailyBedCensus] AS

WITH
CTE_ESPECIALIDAD_FINAL AS
(
SELECT
EST.NUMINGRES,
RTRIM(PRO.CODPROSAL)+' - '+PRO.NOMMEDICO AS MEDICO,
ESP.CODESPECI+' - '+ESP.DESESPECI AS ESPECIALIDAD
FROM 
dbo.CHREGESTA EST 
INNER JOIN dbo.HCHISPACA HC ON EST.NUMINGRES=HC.NUMINGRES AND EST.REGESTADO = 1 AND HC.NUMEFOLIO=(SELECT MAX(H.NUMEFOLIO) FROM dbo.HCHISPACA H WHERE EST.NUMINGRES=H.NUMINGRES) 
INNER JOIN dbo.INPROFSAL PRO ON HC.CODPROSAL = PRO.CODPROSAL 
INNER JOIN dbo.INESPECIA ESP ON PRO.CODESPEC1 = ESP.CODESPECI 
/*IN V2*/WHERE EST.ID=(SELECT MAX(A.ID) FROM dbo.CHREGESTA A WHERE EST.NUMINGRES=A.NUMINGRES)/*FN V2*/
),

CTE_REFERENCIA AS
(
SELECT
REF.NUMINGRES,
REF.FECSOLICIT
FROM
dbo.CHREGESTA EST INNER JOIN
DBO.HCREFCONP REF ON EST.NUMINGRES=REF.NUMINGRES AND EST.REGESTADO = 1 AND REF.AUTO=(SELECT MAX(RE.AUTO) FROM DBO.HCREFCONP RE WHERE EST.NUMINGRES=RE.NUMINGRES)
),

CTE_PAD AS
(
SELECT
CON.NUMINGRES,
CON.FECHAREGISTRO
FROM
dbo.CHREGESTA EST INNER JOIN
dbo.PADCONTROL CON ON EST.NUMINGRES=CON.NUMINGRES AND EST.REGESTADO = 1 AND CON.ID=(SELECT MAX(C.ID) FROM dbo.PADCONTROL C WHERE EST.NUMINGRES=C.NUMINGRES)
),

CTE_ALTA_MEDICA AS
(
SELECT 
EGR.NUMINGRES
FROM 
dbo.CHREGESTA EST INNER JOIN
dbo.HCREGEGRE EGR ON EST.NUMINGRES=EGR.NUMINGRES AND EST.REGESTADO = 1 AND EGR.NUMEFOLIO=(SELECT MAX(EG.NUMEFOLIO) FROM dbo.HCREGEGRE EG WHERE EST.NUMINGRES=EG.NUMINGRES)
),
CTE_SERVICIOS_PENDIENTES AS
(
SELECT
RCD.id, 
RCD.Status,
RC.AdmissionNumber AS INGRESO
FROM BILLING.REVENUECONTROLDETAIL AS RCD
INNER JOIN BILLING.REVENUECONTROL AS RC ON RCD.REVENUECONTROLID = RC.ID
INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES = RC.ADMISSIONNUMBER
INNER JOIN dbo.CHREGESTA AS CAM ON CAM.NUMINGRES =ING.NUMINGRES AND CAM.REGESTADO = 1
),

CTE_VALOR_ESTANCIA
AS
(
 SELECT 
 RCD.INGRESO,
 SUM(ISNULL(DQ.TOTALSALESPRICE,SOD.GrandTotalSalesPrice)) 'DET_ORD_VALOR_TOTAL'
 FROM CTE_SERVICIOS_PENDIENTES  AS RCD
 INNER JOIN BILLING.SERVICEORDERDETAILDISTRIBUTION AS SODD ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1', '3')
 INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD ON SODD.SERVICEORDERDETAILID = SOD.ID
 LEFT JOIN Billing.ServiceOrderDetailSurgical AS DQ ON DQ.ServiceOrderDetailId = SOD.Id AND DQ.OnlyMedicalFees = '0'
 WHERE SOD.IsDelete ='0'
 GROUP BY RCD.INGRESO
 )


SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
CEN.NOMCENATE AS [CENTRO DE ATENCIÓN],
RTRIM(UF.UFUCODIGO)+' - '+UF.UFUDESCRI AS [UNIDAD FUNCIONAL],
CAM.CODICAMAS AS [CODIGO CAMA],
CAM.NUMCAMHOS AS [#CAMA],
CAM.DESCCAMAS AS [DESCRIPCIÓN CAMA],
CASE CAM.CODCLAHAB WHEN '1' THEN 'SALA OBSERVACION' 
				   WHEN '2' THEN 'SALA PROCEDIMIENTO' 
				   WHEN '3' THEN 'SALA RECUPERACION' 
				   WHEN '4' THEN 'HABITACION 1 CAMA' 
				   WHEN '5' THEN 'HABITACION 2 CAMAS'  
				   WHEN '6' THEN 'HABITACION 3 CAMAS'  
				   WHEN '7' THEN 'HABITACION 4 CAMAS'  
				   WHEN '8' THEN 'SUITE' 
				   WHEN '9' THEN 'HAB.ESPECIAL' 
				   WHEN '10' THEN 'UCI'  
				   WHEN '11' THEN 'OTRO' END AS [CLASE DE HABITACION], 
CASE CAM.CODCLACAM WHEN '1' THEN UPPER('ObservacionUrgencias') 
				   WHEN '2' THEN UPPER('Recuperacion Post Qx')  
				   WHEN '3' THEN 'HOSPITALARIA' END AS [CLASE DE CAMA],
--IIF(EST.NUMINGRES IS NULL,'DISPONIBLE','OCUPADA') AS [ESTADOS CAMA],
CASE CAM.ESTADCAMA WHEN 1 THEN 'Libre'
				   WHEN 2 THEN 'Asignada'
				   WHEN 3 THEN 'Inactiva'
				   WHEN 4 THEN 'En Mantenimiento'
				   WHEN 5 THEN 'En Aislamiento'
				   WHEN 6 THEN 'Reservada sin Confirmar'
				   WHEN 7 THEN 'Reservada Confirmada' END AS [ESTADO CAMA],
DOC.NOMBRE AS [TIPO DE IDENTIFICACIÓN],
EST.IPCODPACI AS IDENTIFICACION,
PAC.IPNOMCOMP AS [NONBRE PACIENTE],PAC.IPPRINOMB 'PRIMER NOMBRE', PAC.IPSEGNOMB 'SEGUNDO NOMBRE',PAC.IPPRIAPEL 'PRIMER APELLIDO', PAC.IPSEGAPEL 'SEGUNDO APELLIDO',
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' 
				   WHEN 2 THEN 'FEMENINO' ELSE NULL END AS SEXO,
CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
FLOOR((CAST(CONVERT(VARCHAR(8), EST.FECINIEST  , 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS EDAD,
PAC.IPDIRECCI AS DIRECCION, 
PAC.IPTELEFON AS TELEFONO, 
PAC.IPTELMOVI AS MOVIL,
EST.NUMINGRES AS INGRESO,
EST.FECINIEST AS [FECHA INICIO ESTANCIA],
DATEDIFF(DAY,EST.FECINIEST,GETDATE()) [DIAS TRANSCURRIDOS],
TIP.DESTIPEST AS [TIPO DE ESTANCIA],
HA.Name AS ENTIDAD,
CASE HA.ENTITYTYPE WHEN 1 THEN 'EPS CONTRIBUTIVO' 
				   WHEN 2 THEN 'EPS SUBSIDIADO' 
				   WHEN 3 THEN 'ET VINCULADO MUNICIPIO' 
				   WHEN 4 THEN 'ET VINCULADOS DAPARTAMENTO'
				   WHEN 5 THEN 'ARL RIESGO LABORALES' 
				   WHEN 6 THEN 'MP MEDICINA PREPAGADA' 
				   WHEN 7 THEN 'IPS PRIVADA' 
				   WHEN 8 THEN 'IPS PUBLICA' 
				   WHEN 9 THEN 'REGIMEN ESPECIAL' 
				   WHEN 10 THEN 'ACCIDENTE DE TRANSITO'
				   WHEN 11 THEN 'FOSYGA' 
				   WHEN 12 THEN 'OTROS' END AS [REGIMEN],
CASE PAC.IPTIPOAFI WHEN 0 THEN 'No Aplica' 
				   WHEN 1 THEN 'Cotizante'
				   WHEN 2 THEN 'Beneficiario'
				   WHEN 3 THEN 'Adicional'
				   WHEN 4 THEN 'Jub/Retirado'
				   WHEN 5 THEN 'Pensionado' END AS [TIPO AFILIADO],
NV.NIVDESCRI AS [CATEGORIA],
RTRIM(NOS.CODDIAGNO) + ' - ' + RTRIM(NOS.NOMDIAGNO) AS [DIAGNOSTICO PRINCIPAL],
ESP.MEDICO AS [ULTIMO PROFESIONAL],
ESP.ESPECIALIDAD AS [ULTIMA ESPECIALIDAD],
ING.IAUTORIZA AS [NUMERO AUTORIZACIÓN], 
ING.IOBSERVAC AS [OBSERVACIONES],
IIF(REF.NUMINGRES IS NULL,IIF(EST.NUMINGRES IS NULL,NULL,'NO'),'SI') AS REFERENCIA,
REF.FECSOLICIT AS [SOLICITUD REFERENCIA],
IIF(PAD.NUMINGRES IS NULL,IIF(EST.NUMINGRES IS NULL,NULL,'NO'),'SI') AS PAD,
PAD.FECHAREGISTRO AS [FECHA PAD],
IIF(AL.NUMINGRES IS NULL,IIF(EST.NUMINGRES IS NULL,NULL,'1 - Pacientes en la Unidad'),'2 - Pacientes Con Salida') AS [ESTADO INGRESO],
ING.IFECHAING AS [FECHA INGRESO ADMISION],
IIF(EST.NUMINGRES IS NULL,0,ISNULL(VAL.DET_ORD_VALOR_TOTAL,0)) AS [VALOR ESTANCIA],
1 AS CANTIDAD,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
dbo.CHCAMASHO CAM 
INNER JOIN dbo.INUNIFUNC UF ON CAM.UFUCODIGO = UF.UFUCODIGO 
INNER JOIN dbo.ADCENATEN CEN ON CAM.CODCENATE = CEN.CODCENATE 
LEFT JOIN dbo.CHREGESTA EST ON CAM.CODICAMAS = EST.CODICAMAS AND EST.REGESTADO = 1 
LEFT JOIN dbo.CHTIPESTA TIP ON EST.CODTIPEST = TIP.CODTIPEST 
LEFT JOIN dbo.INPACIENT PAC ON EST.IPCODPACI = PAC.IPCODPACI 
LEFT JOIN dbo.ADTIPOIDENTIFICA DOC ON PAC.IPTIPODOC=DOC.CODIGO 
LEFT JOIN dbo.ADINGRESO ING ON EST.NUMINGRES=ING.NUMINGRES 
LEFT JOIN CONTRACT.HEALTHADMINISTRATOR HA ON ING.GENCONENTITY=HA.ID 
LEFT JOIN INDIAGNOP DIA ON ING.NUMINGRES=DIA.NUMINGRES AND DIA.CODDIAPRI=1 
LEFT JOIN dbo.INDIAGNOS NOS ON DIA.CODDIAGNO=NOS.CODDIAGNO 
LEFT JOIN dbo.ADNIVELES NV ON PAC.NIVCODIGO=NV.NIVCODIGO 
LEFT JOIN CTE_ESPECIALIDAD_FINAL ESP ON EST.NUMINGRES=ESP.NUMINGRES 
LEFT JOIN CTE_REFERENCIA REF ON EST.NUMINGRES=REF.NUMINGRES 
LEFT JOIN CTE_PAD PAD ON EST.NUMINGRES=PAD.NUMINGRES 
LEFT JOIN CTE_ALTA_MEDICA AL ON EST.NUMINGRES=AL.NUMINGRES 
LEFT JOIN CTE_VALOR_ESTANCIA VAL ON EST.NUMINGRES=VAL.INGRESO
--where pac.IPCODPACI='40417620'
