-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewProductividadMedica
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [Report].[ViewProductividadMedica] AS
SELECT --COUNT(1)
  CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
  CASE
      UNI.UFUTIPUNI 
		WHEN	1		THEN	'URGENCIAS'
		WHEN	2		THEN	'HOSPITALIZACION'
		WHEN	3		THEN	'APOYO DX'
		WHEN	4		THEN	'APOYO TERAPEUTICO'
		WHEN	5		THEN	'UNIDADES DE CUIDADO INTENSIVO ADULTO'
		WHEN	6		THEN	'UNIDADES DE CUIDADO INTERMEDIO ADULTO'
		WHEN	7		THEN	'UNIDADES DE CUIDADO INTENSIVO PEDIATRICA'
		WHEN	8		THEN	'UNIDADES DE CUIDADO INTERMEDIO PEDIATRICA'
		WHEN	9		THEN	'UNIDADES DE CUIDADO INTENSIVO NEONATAL'
		WHEN	10		THEN	 'UNIDADES DE CUIDADO INTERMEDIO NEONATAL'
		WHEN	11		THEN	 'UNIDADES DE CUIDADO BASICO NEONATAL'
		WHEN	12		THEN	 'UNIDAD RENAL'
		WHEN	13		THEN	 'UNIDAD ONCOLOGICA'
		WHEN	14		THEN	 'UNIDAD MEDICINA NUCLEAR'
		WHEN	15		THEN	 'CONSULTA EXTERNA'
		WHEN	16		THEN	 'UNIDAD MENTAL'
		WHEN	17		THEN	 'UNIDAD DE QUEMADOS'
		WHEN	18		THEN	 'UNIDAD DE CUIDADO PALIATIVO'
		WHEN	19		THEN	 'CIRUGIA'
		WHEN	20		THEN	 'LABORATORIO'
		WHEN	21		THEN	 'CARDIOLOGIA NO INVASIVA'
		WHEN	22		THEN	 'CARDIOLOGIA INVASIVA'
		WHEN	23		THEN	 'GINECO-OBSTETRICIA'
		WHEN	24		THEN	 'CONSULTA EXTERNA - GINECO-OBSTETRICIA'
		WHEN	30		THEN	 'OTRAS'
		WHEN	31		THEN	 'CONSULTA PRIORITARIA'
	  ELSE 'DESCONOCIDO'
   END
   AS TIPOUNIDAD, 
   CASE
		WHEN	MO.NOMBRE IS NULL THEN	UNI.UFUDESCRI 
		ELSE	MO.NOMBRE 
   END
   AS NOMBREHISTORIA, ING.CODCENATE AS CODCENTRO, RTRIM(CEN.NOMCENATE) AS CENTROATENCION, UNI.UFUDESCRI AS UNIDADFUNCIONAL, 
   CASE
      PAC.IPTIPODOC 
      WHEN		1		THEN	'CC - CEDULA DE CIUDADANIA' 
      WHEN		2		THEN	'CE - CEDULA DE EXTRANJERIA' 
      WHEN		3		THEN	'TI - TARJETA DE IDENTIDAD' 
      WHEN		4		THEN	'RC - REGISTRO CIVIL' 
      WHEN		5		THEN	'PA - PASAPORTE' 
      WHEN		6		THEN	'AS - ADULTO SIN IDENTIFICACION' 
      WHEN		7		THEN	'MS - MENOR SIN IDENTIFICACION' 
      WHEN		8		THEN	'NU - NUMERO UNICO DE IDENTIFICACIÒN' 
	  WHEN		9		THEN	'NV - CERTIFICADO NACIDO VIVO' 
	  WHEN		10		THEN	'CD - CARNET DIPLOMATICO' 
	  WHEN		11		THEN	'SC - SALVOCONDUCTO' 
      WHEN		12		THEN	'PE - PERMISO ESPECIAL DE PERMANENCIA' 
   END
   AS TIPOIDENTIFICACION, RTRIM(ING.IPCODPACI) AS IDENTIFICACION, RTRIM(PAC.IPPRINOMB) AS PRIMERNOMBRE, RTRIM(PAC.IPSEGNOMB) AS SEGUNDONOMBRE, RTRIM(PAC.IPPRIAPEL) AS PRIMERAPELLIDO, 
   RTRIM(PAC.IPSEGAPEL) AS SEGUNDOAPELLIDO, CAST(PAC.IPFECNACI AS DATE) AS FECHA_NACIMIENTO, DATEDIFF(YEAR, PAC.IPFECNACI,GETDATE()) AS EDAD_ACTUAL, 
   DATEDIFF(YEAR, PAC.IPFECNACI,HC.FECHISPAC) AS EDAD_EN_CONSULTA, UBI.UBINOMBRE AS BARRIO , PAC.IPDIRECCI AS DIRECCION, PAC.IPTELMOVI AS CELULAR, PAC.IPTELEFON AS TELEFONOFIJO, 
   DGE.[GRUPO_ETAREO_RES_5268], DGE.[GRUPO_ETAREO_UPC], DGE.[GRUPO_ETAREO_CICLO_VITAL],
   CASE
      PAC.IPSEXOPAC 
      WHEN		1		THEN	'MASCULINO' 
      WHEN		2		THEN	'FEMENINO' 
   END
   AS SEXO, HC.NUMEFOLIO AS FOLIO, HC.FECHISPAC AS FECHA_FOLIO, 
   HC.CODDIAGNO AS CODDIAGNOSTICO, RTRIM(DIAG.NOMDIAGNO) AS DIAGNOSTICO, S.CODUSUARI AS CODPROFESIONAL, S.NOMMEDICO AS NOMBREPROFESIONAL, 
   CASE
      ING.ICAUSAING 
      WHEN		1		THEN	'HERIDOS EN COMBATE' 
      WHEN		2		THEN	'ENFERMEDAD PROFESIONAL' 
      WHEN		3		THEN	'ENFERMEDAD GENERAL ADULTO' 
      WHEN		4		THEN	'ENFERMEDAD GENERAL PEDIATRIA' 
      WHEN		5		THEN	'ODONTOLOGÍA' 
      WHEN		6		THEN	'ACCIDENTE DE TRANSITO' 
      WHEN		7		THEN	'CATASTROFE/FISALUD' 
      WHEN		8		THEN	'QUEMADOS' 
      WHEN		9		THEN	'MATERNIDAD' 
      WHEN		10		THEN	'ACCIDENTE LABORAL' 
      WHEN		11		THEN	'CIRUGIA PROGRAMADA' 
   END
   AS CAUSAINGRESO, ING.CODENTIDA AS CODIGOENTIDAD, ENT.NOMENTIDA AS ENTIDAD, 
   CASE
      PAC.IPSEXOPAC 
      WHEN         1       THEN         'NO APLICA' 
      ELSE         CASE            WHEN               RIE.GESTACION = 1 
            THEN               'SI'            ELSE               'NO' 
         END
   END
   AS EMBARAZADA, 
   CASE
      HC.INDICAPAC 
      WHEN		1		THEN	'TRASLADAR A URGENCIAS' 
      WHEN		2		THEN	'TRASLADAR A OBSERVACION URGENCIAS' 
      WHEN		3		THEN	'TRASLADAR A HOSPITALIZACION' 
      WHEN		4		THEN	'TRASLADAR A  UCI ADULTO' 
      WHEN		5		THEN	'TRASLADAR A UCI PEDIATRICA' 
      WHEN		6		THEN	'TRASLADAR A UCI NEONATAL' 
      WHEN		7		THEN	'TRASLADAR A CONSULTA EXTERNA' 
      WHEN		8		THEN	'TRASLADAR A  CIRUGIA' 
      WHEN		9		THEN	'HOSPITALIZACION EN CASA' 
      WHEN		10		THEN	'REFERENCIA' 
      WHEN		11		THEN	'MORGUE' 
      WHEN		12		THEN	'SALIDA' 
      WHEN		13		THEN	'CONTINUA EN LA UNIDAD' 
      WHEN		14		THEN	'PACIENTE EN TRATAMIENTO' 
      WHEN		15		THEN	'RETIRO VOLUNTARIO' 
      WHEN		16		THEN	'FUGA' 
      WHEN		17		THEN	'SALIDA PARCIAL' 
      WHEN		18		THEN	'ESTANCIA CON LA MADRE' 
      WHEN		19		THEN	'U.CUIDADO INTERMEDIO' 
      WHEN		20		THEN	'U.BASICA' 
   END
   SALIDA , 
   ING.NUMINGRES NUMERO_INGRESO,
   ISNULL(G2.CODIGO_CUP, 'SIN DATO') AS [CODIGO CUPS],
   ISNULL(G2.CUPS , 'SIN DATO') AS CUPS,
   1 as 'CANTIDAD',
   CAST(HC.FECHISPAC AS date) AS 'FECHA BUSQUEDA',
   YEAR(HC.FECHISPAC) AS 'AÑO FECHA BUSQUEDA',
   MONTH(HC.FECHISPAC) AS 'MES AÑO FECHA BUSQUEDA',
   CASE MONTH(HC.FECHISPAC) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
  END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(HC.FECHISPAC), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(HC.FECHISPAC), '00') ,' - ', 
	   CASE MONTH(HC.FECHISPAC) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
   DBO.ADINGRESO AS ING WITH (NOLOCK) 
   INNER JOIN DBO.HCHISPACA AS HC WITH (NOLOCK)   ON ING.NUMINGRES = HC.NUMINGRES AND ING.IPCODPACI = HC.IPCODPACI 
   INNER JOIN DBO.ADCENATEN AS CEN WITH (NOLOCK)  ON CEN.CODCENATE = ING.CODCENATE 
   INNER JOIN DBO.INPACIENT AS PAC WITH (NOLOCK)  ON ING.IPCODPACI = PAC.IPCODPACI 
   INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK)  ON UNI.UFUCODIGO = HC.UFUCODIGO 
   INNER JOIN DBO.INUBICACI AS UBI WITH (NOLOCK)  ON PAC.AUUBICACI = UBI.AUUBICACI 
   INNER JOIN DBO.INDIAGNOS AS DIAG WITH (NOLOCK) ON HC.CODDIAGNO = DIAG.CODDIAGNO 
   INNER JOIN DBO.INPROFSAL AS S WITH (NOLOCK)    ON S.CODPROSAL = HC.CODPROSAL 
   INNER JOIN DBO.INENTIDAD AS ENT WITH (NOLOCK)  ON ING.CODENTIDA = ENT.CODENTIDA 
   LEFT OUTER JOIN DBO.PRMODELOHC AS MO WITH (NOLOCK)  ON MO.ID = HC.IDMODELOHC 
   LEFT OUTER JOIN DBO.HCRIESGOSP AS RIE WITH (NOLOCK) ON RIE.NUMINGRCES = ING.NUMINGRES --75.784
   LEFT JOIN  [Report].[ETAREO_GROUP_HOMO] HGE WITH(NOLOCK) ON DATEDIFF(YEAR, PAC.IPFECNACI,HC.FECHISPAC) = HGE.GRUPO_ETAREO_EDAD
   LEFT JOIN  [Report].[ETAREO_GROUP] DGE WITH(NOLOCK) ON HGE.ID_GRUPO_ETAREO = DGE.ID_GRUPO_ETAREO

   LEFT JOIN (SELECT 
               AdmissionNumber AS INGRESO ,InvoiceNumber AS FACTURA ,CUPS.Code AS CODIGO_CUP,
			   CUPS.Description CUPS ,CDD.Code AS CODIGO_RELACIONADO ,CDD.Name AS DESCRIPCION_RELACIONADA,
			   F.InvoiceDate AS 'FECHA FACTURA', DF.TotalSalesPrice AS 'VALOR SERVICIO', F.InvoiceValue AS 'VALOR FACTURA'
			  FROM Billing.Invoice AS F
			       LEFT JOIN Billing.InvoiceDetail AS DF WITH (NOLOCK) ON DF.InvoiceId = F.Id
				   LEFT JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id = DF.ServiceOrderDetailId
				   LEFT JOIN Contract.CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id = SOD.CUPSEntityId
				   LEFT JOIN Contract.CUPSEntityContractDescriptions AS CECD WITH (NOLOCK) ON CECD.ID=SOD.CUPSEntityContractDescriptionId
				   LEFT JOIN Contract.ContractDescriptions AS CDD WITH (NOLOCK) ON CECD.ContractDescriptionId =CDD.Id
				   WHERE F.Status =1 AND CUPS.ServiceType IN (6,8)
			 ) AS G2 ON G2.INGRESO =ING.NUMINGRES

WHERE
   ING.IESTADOIN <> 'A' 
