-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewRadicacionHSJ
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[ViewRadicacionHSJ]
AS
WITH

CTE_ORDENES
AS
(

SELECT ROW_NUMBER() OVER(PARTITION BY CODSERIPS ORDER BY  IPCODPACI,FECORDMED DESC) 'NUMERO', IPCODPACI, FECORDMED, CODSERIPS

FROM HCORDPROQ

--WHERE IPCODPACI ='1222209318'


),

CTE_INFORME
AS
(
SELECT INF.IPCODPACI, INF.NUMINGRES, INF.CODSERIPS, FECHORINI

FROM HCQXINFOR INF

--WHERE INF.IPCODPACI='1071169816'
),


CTE_RADICACIONES
AS
(
SELECT RAD.ID,
 INP.IPCODPACI 'ID. PACIENTE',
 INP.IPNOMCOMP 'NOMBRE PACIENTE',INP.IPTELMOVI 'TEL.MOVIL',INP.IPTELEFON 'TEL.FIJO', INP.CORELEPAC 'CORREO ELECTRONICO',
 FLOOR((CAST(CONVERT(VARCHAR(8), RAD.FECHAREGISTRO, 112) AS INT) - CAST(CONVERT(VARCHAR(8), INP.IPFECNACI, 112) AS INT)) / 10000) 'EDAD AÑOS',
 DATEDIFF(MONTH,CAST(INP.IPFECNACI AS varchar),CAST (RAD.FECHAREGISTRO AS DATE)) 'EDAD MESES',RAD.FECHACONFIRMACION,
CASE  RAD.ESTADO
  WHEN 1 THEN 'Radicado'
  WHEN 2 THEN 'Confirmado'
  WHEN 3 THEN 'Anulado'
 END 'ESTADO RADICACION', 
 CAST(RAD.FECHARADIC AS DATE) 'FECHA RADICADO', 
 RAD.NUMRADICACION '# RADICADO', 
 RAD.QXPRINCIPAL 'CUPS PRINCIPAL',
 CUPS1.DESCODCUPS 'CX PRINCIPAL',
 RADD.CODSERIPS 'CUPS OTROS',
 CUPS2.DESCODCUPS 'OTROS PROC',
 RAD.CODPROSAL 'COD. PROFESIONAL', PROF.NOMMEDICO 'NOMBRE PROFESIONAL', ESP.DESESPECI 'ESPECIALIDAD'

FROM 
  DBO.ADRADICACIONQX RAD  --581
  INNER JOIN DBO.INPACIENT INP ON INP.IPCODPACI = RAD.IPCODPACI
  LEFT JOIN DBO.ADRADICACIONQXS RADD ON RAD.ID = RADD.IDRADICACIONQX --689
  LEFT JOIN DBO.INCUPSIPS CUPS2 ON CUPS2.CODSERIPS=RADD.CODSERIPS
  LEFT JOIN DBO.INCUPSIPS CUPS1 ON CUPS1.CODSERIPS = RAD.QXPRINCIPAL --581
  LEFT JOIN INPROFSAL PROF ON PROF.CODPROSAL=RAD.CODPROSAL
  LEFT JOIN INESPECIA ESP ON ESP.CODESPECI=RAD.CODESPECI
  
  --WHERE INP.IPCODPACI='1028955800'
  
 GROUP BY RAD.ID,INP.IPCODPACI , INP.IPNOMCOMP ,  RAD.FECHACONFIRMACION,INP.IPFECNACI, RAD.ESTADO, RAD.NUMRADICACION, RAD.QXPRINCIPAL, CUPS1.DESCODCUPS,
 RADD.CODSERIPS, CUPS2.DESCODCUPS,RAD.CODPROSAL, PROF.NOMMEDICO, ESP.DESESPECI, RAD.FECHAREGISTRO,RAD.FECHARADIC, INP.IPTELMOVI ,INP.IPTELEFON , INP.CORELEPAC
 ),

 CTE_LISTA_CHEQUEO
 AS
 
  (
 SELECT DISTINCT FEC.FECHAREGISTRO,DET.IDRADICACIONQX,DET.IDLISTACHEQUEOD,DET.CAMPOFECHA,
  CASE WHEN LIS1.DESPREENC IS NOT NULL AND LIS1.DESPREENC='ORDEN MEDICA' THEN 'SI' ELSE 'NO' END  'ORDEN MEDICA',
 CASE WHEN LIS2.DESPREENC IS NOT NULL AND LIS2.DESPREENC='ORDEN DE INSUMOS' THEN 'SI' ELSE 'NO' END  'ORDEN DE INSUMOS',
 CASE WHEN LIS3.DESPREENC IS NOT NULL AND LIS3.DESPREENC='CONSENTIMIENTO INFORMADO'  THEN 'SI' ELSE 'NO' END  'CONSENTIMIENTO INFORMADO',
 CASE WHEN LIS4.DESPREENC IS NOT NULL AND LIS4.DESPREENC='AUTORIZACION' THEN 'SI' ELSE 'NO' END  'AUTORIZACION',
 CASE WHEN LIS5.DESPREENC IS NOT NULL AND LIS5.DESPREENC='COPAGO' THEN 'SI' ELSE 'NO' END  'COPAGO',
 CASE WHEN LIS6.DESPREENC IS NOT NULL AND LIS6.DESPREENC='FECHA VIGENCIA AUTORIZACION' THEN 'SI' ELSE 'NO' END  'VIGENCIA AUTORIZACION'


 FROM ADRADICACIONQX FEC 
  INNER JOIN ADRADICACIONQXD DET  ON FEC.ID=DET.IDRADICACIONQX 
  LEFT JOIN HCLISTACD LIS1 ON LIS1.CODCONSEC=DET.IDLISTACHEQUEOD  AND LIS1.DESPREENC IS NOT NULL
  LEFT JOIN HCLISTACD LIS2 ON LIS2.CODCONSEC=DET.IDLISTACHEQUEOD AND LIS2.DESPREENC IS NOT NULL
  LEFT JOIN HCLISTACD LIS3 ON LIS3.CODCONSEC=DET.IDLISTACHEQUEOD AND LIS3.DESPREENC IS NOT NULL
  LEFT JOIN HCLISTACD LIS4 ON LIS4.CODCONSEC=DET.IDLISTACHEQUEOD AND LIS4.DESPREENC IS NOT NULL
  LEFT JOIN HCLISTACD LIS5 ON LIS5.CODCONSEC=DET.IDLISTACHEQUEOD AND LIS5.DESPREENC IS NOT NULL
  LEFT JOIN HCLISTACD LIS6 ON LIS6.CODCONSEC=DET.IDLISTACHEQUEOD AND LIS6.DESPREENC IS NOT NULL
  

  GROUP BY  DET.CAMPOFECHA,FEC.FECHAREGISTRO,DET.IDRADICACIONQX,LIS1.DESPREENC , LIS2.DESPREENC , LIS3.DESPREENC , LIS4.DESPREENC , LIS5.DESPREENC , LIS6.DESPREENC, DET.IDLISTACHEQUEOD
  
 )

 SELECT DISTINCT ISNULL(RAD.[FECHA RADICADO],GETDATE()) 'FECHA DE BUSQUEDA',RAD.[ID. PACIENTE], RAD.[NOMBRE PACIENTE], RAD.[EDAD AÑOS], RAD.[EDAD MESES],RAD.[TEL.MOVIL], RAD.[TEL.FIJO], RAD.[CORREO ELECTRONICO],
 CAST(ISNULL(ORD.FECORDMED,'') AS DATE) 'FECHA ORDEN',RAD.[ESTADO RADICACION],
 RAD.[# RADICADO],RAD.[FECHA RADICADO],CAST(RAD.FECHACONFIRMACION AS DATE) 'FECHA CONFIRMACION', RAD.[CX PRINCIPAL],RAD.[CUPS PRINCIPAL], RAD.[OTROS PROC],RAD.[CUPS OTROS],RAD.[NOMBRE PROFESIONAL],RAD.ESPECIALIDAD, 
 CASE WHEN LIS1.[ORDEN MEDICA] ='SI' THEN 'SI' ELSE 'NO' END 'ORDEN MEDICA',  
 CASE WHEN LIS2.[ORDEN DE INSUMOS] ='SI' THEN 'SI' ELSE 'NO' END 'ORDEN DE INSUMOS', 
 CASE WHEN LIS3.[CONSENTIMIENTO INFORMADO] ='SI' THEN 'SI' ELSE 'NO' END 'CONSENTIMIENTO INFORMADO',
 CASE WHEN LIS4.AUTORIZACION ='SI' THEN 'SI' ELSE 'NO' END 'AUTORIZACION',
 CASE WHEN LIS5.COPAGO ='SI' THEN 'SI' ELSE 'NO' END 'COPAGO',
 CASE WHEN LIS6.[VIGENCIA AUTORIZACION] ='SI' THEN 'SI' ELSE 'NO' END 'FECHA VIGENCIA AUTORIZACION',
 LIS6.CAMPOFECHA 'FECHA VIGENCIA'
 
 
 FROM CTE_RADICACIONES RAD
 LEFT JOIN CTE_LISTA_CHEQUEO LIS1 ON LIS1.IDRADICACIONQX=RAD.ID AND LIS1.[ORDEN MEDICA]='SI'
 LEFT JOIN CTE_LISTA_CHEQUEO LIS2 ON LIS2.IDRADICACIONQX=RAD.ID AND LIS2.[ORDEN DE INSUMOS]='SI'
 LEFT JOIN CTE_LISTA_CHEQUEO LIS3 ON LIS3.IDRADICACIONQX=RAD.ID AND LIS3.[CONSENTIMIENTO INFORMADO]='SI'
 LEFT JOIN CTE_LISTA_CHEQUEO LIS4 ON LIS4.IDRADICACIONQX=RAD.ID AND LIS4.AUTORIZACION='SI'
 LEFT JOIN CTE_LISTA_CHEQUEO LIS5 ON LIS5.IDRADICACIONQX=RAD.ID AND LIS5.COPAGO='SI'
 LEFT JOIN CTE_LISTA_CHEQUEO LIS6 ON LIS6.IDRADICACIONQX=RAD.ID AND LIS6.[VIGENCIA AUTORIZACION]='SI'
 LEFT JOIN CTE_ORDENES ORD ON ORD.IPCODPACI=RAD.[ID. PACIENTE] AND ORD.FECORDMED<RAD.[FECHA RADICADO]
 LEFT JOIN CTE_INFORME INF ON INF.IPCODPACI=RAD.[ID. PACIENTE] AND INF.CODSERIPS=RAD.[CUPS PRINCIPAL] AND INF.FECHORINI>RAD.FECHACONFIRMACION 

 WHERE INF.CODSERIPS IS NULL 

