-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewOrderedSupplies
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [Report].[ViewOrderedSupplies]
AS
     SELECT CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
            CEN.NOMCENATE [CENTRO ATENCION], 
            UNI.UFUDESCRI [UNIDAD FUNCIONAL], 
            HEA.Code 'CODIGO ENTIDAD', 
            HEA.Name 'ENTIDAD', 
            CGR.Name 'GRUPO DE ATENCION', 
            CAST(FECHAORDE AS DATE) [FECHA SOLICITUD], 
            SAL.NOMMEDICO [PROFESIONAL], 
            CAB.IPCODPACI [IDENTIFICACION], 
            PAC.IPNOMCOMP [PACINETE], 
            CAB.NUMINGRES [INGRESO], 
            DET.CODPRODUC [CODIGO PRODUCTO], 
            PRO.DESPRODUC [DESCRIPCION PRODUCTO],
            CASE PRO.TIPPRODUC
                WHEN 3
                THEN 'MEDICAMENTO COMO INSUMO'
                WHEN 2
                THEN 'INSUMO'
            END [TIPO PRODUCTO], 
            CANPEDPRO [CANTIDAD PRODUCTO],
			CAST(FECHAORDE AS DATE) [FECHA BUSQUEDA], 
			YEAR(FECHAORDE) AS 'AÑO FECHA BUSQUEDA', 
			MONTH(FECHAORDE) AS 'MES AÑO FECHA BUSQUEDA', 
			CASE MONTH(FECHAORDE) 
			     WHEN 1 THEN 'ENERO'	  
				 WHEN 2 THEN 'FEBRERO'
				 WHEN 3 THEN 'MARZO'
				 WHEN 4 THEN 'ABRIL'
				 WHEN 5 THEN 'MAYO'
				 WHEN 6 THEN 'JUNIO'
				 WHEN 7 THEN 'JULIO'
				 WHEN 8 THEN 'AGOSTO'
				 WHEN 9 THEN 'SEPTIEMBRE'
				 WHEN 10 THEN 'OCTUBRE'
				 WHEN 11 THEN 'NOVIEMBRE'
				 WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA', 
		    DAY(FECHAORDE) AS 'DIA FECHA BUSQUEDA',
			CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
     FROM dbo.HCSOLINSC AS CAB WITH(NOLOCK)
          INNER JOIN dbo.HCSOLINSD AS DET WITH(NOLOCK) ON CAB.CODCONCEC = DET.CODCONCEC
          INNER JOIN dbo.ADINGRESO AS ING WITH(NOLOCK) ON ING.IPCODPACI = CAB.IPCODPACI AND ING.NUMINGRES = CAB.NUMINGRES
          INNER JOIN dbo.INPACIENT AS PAC WITH(NOLOCK) ON CAB.IPCODPACI = PAC.IPCODPACI
          INNER JOIN dbo.IHLISTPRO AS PRO WITH(NOLOCK) ON DET.CODPRODUC = PRO.CODPRODUC
          INNER JOIN dbo.ADCENATEN AS CEN WITH(NOLOCK) ON CAB.CODCENATE = CEN.CODCENATE
          INNER JOIN dbo.INUNIFUNC AS UNI WITH(NOLOCK) ON CAB.UFUCODIGO = UNI.UFUCODIGO
          INNER JOIN dbo.INPROFSAL AS SAL WITH(NOLOCK) ON DET.CODPROSAL = SAL.CODPROSAL
          INNER JOIN [Contract].HealthAdministrator HEA WITH(NOLOCK) ON ING.GENCONENTITY = HEA.ID
          INNER JOIN [Contract].CareGroup AS CGR WITH(NOLOCK) ON ING.GENCAREGROUP = CGR.Id
     WHERE PRO.TIPPRODUC <> '1';
