-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: VIEW_SEG_MEDICAMENTOELIMINADOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE VIEW [Report].[VIEW_SEG_MEDICAMENTOELIMINADOS] AS
SELECT --TOP 10
 HM.IPCODPACI 'IDENTIFICACION',
 PAC.IPNOMCOMP 'NOMBRE PACIENTE',
 HM.NUMINGRES 'INGRESO',
 PRO.DESPRODUC 'MEDICAMENTO' , 
 PRE.DESFORMED 'PRESENTACION',
 HM.FECINIDOS 'FECHA ORDEN',
 UNI.DESUNIMED 'UNIDAD MEDICAMENTO'
FROM 
dbo.HCPRESCRA HM --6299
 JOIN ADINGRESO AS ING ON HM.NUMINGRES = ING.NUMINGRES --6299
 JOIN INPACIENT AS PAC ON HM.IPCODPACI = PAC.IPCODPACI --6299
 JOIN IHLISTPRO AS PRO ON HM.CODPRODUC = PRO.CODPRODUC AND PRO.TIPPRODUC ='1' --6300
 LEFT JOIN DBO.INUNIMEDI AS UNI ON HM.CODUNIMED =UNI.CODUNIMED
 LEFT JOIN IHFORMEDI AS PRE ON PRO.CODFORMED = PRE.CODFORMED
WHERE HM.MEDPENAGE=0
