-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewMedicamentosOrdenadosAFarmacia
-- Extracted by Fabric SQL Extractor SPN v3.9.0





CREATE VIEW [Report].[ViewMedicamentosOrdenadosAFarmacia] AS

WITH CTE_CAMAS
AS
(
  SELECT C.IPCODPACI ,C.NUMINGRES ,A.CODICAMAS,A.NUMCAMHOS   FROM dbo.CHCAMASHO A with (nolock)
     INNER JOIN dbo.CHREGESTA C with (nolock) ON A.CODICAMAS=C.CODICAMAS AND C.REGESTADO = 1 
     INNER JOIN dbo.CHTIPESTA G with (nolock) ON G.CODTIPEST=C.CODTIPEST 
	 WHERE A.ESTADCAMA ='2' --AND C.NUMINGRES in ('5251')--,'4442') -- AND EXTRAMURAL ='0'
),

CTE_ORDENAMIENTOS_MEDICOS_HCPRESCRC_HCPRESCRD
AS
(
   SELECT CAB.CODCONCEC 'CAB_CONSECUTIVO', CAB.IDETIPHIS 'CAB_TIPO_HISTORIA' ,CAB.NUMEFOLIO 'CAB_FOLIO',
   CAB.FECHAORDE 'CAB_FECHA_ORDENAMIENTO',
   CAB.IPCODPACI 'CAB_IDENTIFICACION' ,CAB.NUMINGRES 'CAB_INGRESO' ,FUN.UFUDESCRI 'CAB_UNIDAD',
   RTRIM(DET.CODPRODUC) 'DET_COD_MEDICAMENTO',RTRIM(PRO.DESPRODUC) 'DET_MEDICAMENTO',FORM.DESFORMED 'DET_FORMA_FARMACEUTICA',CASE DET.TIPFORMED WHEN 1 THEN 'Peso' WHEN 2 THEN 'Volumen'
   WHEN 3 THEN 'Peso-Volumen' WHEN 4 THEN 'Unidad de Administración' end 'DET_TIPO_FORMULACION',DET.DOSISPROD 'DET_DOSIS_SOLICITADA',UNI.DESUNIMED  'DET_UNIDAD_MEDICAMENTO',DET.DURACIDOS 'DET_DURACION' ,DET.CANPEDPRO 'DET_CANTIDAD_PEDIDA' ,
   DET.FOLIOINIC 'DET_FOLIO_INICIAL', RTRIM(DET.DESADMINI) 'DET_DESCRIPCION_ADMIN',DET.ID 'DET_ID',CAM.NUMCAMHOS 'CAMA',VIA.DESVIAADM 'VIA DE ADMINISTRACION'
   FROM DBO.HCPRESCRC CAB with (nolock)
   INNER JOIN CTE_CAMAS AS CAM  with (nolock) ON CAM.IPCODPACI =CAB.IPCODPACI AND CAM.NUMINGRES =CAB.NUMINGRES 
   INNER JOIN DBO.HCPRESCRD AS DET with (nolock) ON CAB.CODCONCEC =DET.CODCONCEC 
   INNER JOIN DBO.IHLISTPRO AS PRO with (nolock) ON DET.CODPRODUC =PRO.CODPRODUC 
   INNER JOIN Inventory .ATC AS ATC with (nolock) ON ATC.Code =PRO.CODPRODUC 
   INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAB.UFUCODIGO =FUN.UFUCODIGO 
   INNER JOIN DBO.IHFORMEDI AS FORM with (nolock) ON FORM.CODFORMED =DET.CODFORMED 
   INNER JOIN DBO.INPROFSAL AS SAL with (nolock) ON DET.CODPROSAL =SAL.CODPROSAL 
   LEFT JOIN DBO.HCVIAADMI AS VIA with (nolock) ON VIA.CODVIAADM =DET.CODVIAADM 
   LEFT JOIN DBO.INUNIMEDI AS UNI with (nolock) ON DET.CODUNIMED =UNI.CODUNIMED
   WHERE CAB.FECHAORDE BETWEEN (GETDATE()-2) AND (GETDATE())
),

CTE_MEDICAMENTOS_HCPRESCRA
AS
(
   SELECT PRE.IDETIPHIS 'PRE_TIPO_HISTORIA' ,PRE.NUMEFOLIO 'PRE_FOLIO',PRE.IPCODPACI 'PRE_IDENTIFICACION' ,PRE.NUMINGRES 'PRE_INGRESO' ,FUN.UFUDESCRI 'PRE_UNIDAD_FUNCIONAL' ,
   SAL.NOMMEDICO 'PRE_PROFESIONAL' ,PRE.CODPRODUC 'PRE_COD_MEDICAMENTO',PRO.DESPRODUC 'PRE_MEDICAMENTO' ,PRE.DOSISPROD 'PRE_DOSIS_ORDENADA' ,UNI.DESUNIMED 'PRE_UNIDAD_MEDIDA' ,
   PRE.FRECUENCI 'PRE_FRECUENCIA' ,CASE PRE.UNIFRECUE WHEN 1 THEN 'Minutos' WHEN 2 THEN 'Horas' WHEN 3 THEN 'Dias' END 'PRE_UNIDAD_FRECUENCIA',PRE.FECINIDOS 'PRE_FECHA_INICIAL',
   CASE PRE.TIPFORMED WHEN 1 THEN 'Peso' WHEN 2 THEN 'Volumen' WHEN 3 THEN 'Peso-Volumen' WHEN 4 THEN 'Unidad de Administración' end 'PRE_TIPO_FORMULACION' ,CAM.NUMCAMHOS 'CAMA',
   PRE.DURACIDOS 'PRE_DURACION' ,PRE.VALDURFIJ 'PRE_DURACION_FIJA' ,CASE PRE.UNIDURFIJ WHEN 1 THEN 'Minutos' WHEN 2 THEN 'Horas' WHEN 3 THEN 'Dias' END 'PRE_UNIDAD_FIJA',
   PREESTADO 'PRE_ESTADO' ,PRE.CODCONCEC 'PRE_CONSECUTIVO' ,PRE.CODDIAGNO 'PRE_DIAGNOSTICO' ,PRE.CANPEDPRO 'PRE_CANTIDAD_ORDENADA' ,PRE.DESADMINI 'PRE_DESCRIPCION_ADMIN' ,PRE.ID 'PRE_ID',
   VIA.DESVIAADM 'VIA DE ADMINISTRACION'
   FROM DBO.HCPRESCRA PRE with (nolock)
   INNER JOIN CTE_CAMAS AS CAM with (nolock) ON CAM.IPCODPACI =PRE.IPCODPACI AND CAM.NUMINGRES =PRE.NUMINGRES
   INNER JOIN DBO.IHLISTPRO AS PRO with (nolock) ON PRE.CODPRODUC =PRO.CODPRODUC 
   INNER JOIN Inventory .ATC AS ATC with (nolock) ON ATC.Code =PRO.CODPRODUC 
   INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON PRE.UFUCODIGO =FUN.UFUCODIGO 
   INNER JOIN DBO.IHFORMEDI AS FORM with (nolock) ON FORM.CODFORMED =PRE.CODFORMED 
   INNER JOIN DBO.INPROFSAL AS SAL with (nolock) ON PRE.CODPROSAL =SAL.CODPROSAL
   LEFT JOIN DBO.HCVIAADMI AS VIA with (nolock) ON VIA.CODVIAADM =PRE.CODVIAADM
   LEFT JOIN DBO.INUNIMEDI AS UNI with (nolock) ON PRE.CODUNIMED =UNI.CODUNIMED 
),

CTE_MEDICAMENTOS_HCPRESCRA_HCPRESCRD
AS
(
  SELECT PRE.IPCODPACI ,PRE.NUMINGRES ,PRE.CODPRODUC ,PRE.FECINIDOS ,PRE.CODCONCEC,PRE.CODDIAGNO ,PRE.DESADMINI ,PRE.DOSISPROD PRE_DOSIS , PRE.ID,
  DET.CODCONCEC DET_CONSECUTIVO,DET.DURACIDOS DET_DURACION,DET.DOSISPROD DET_DOSIS ,UNI.DESUNIMED DET_UNIDAD ,DET.CANPEDPRO DET_CANTIDAD,DET.PREESTADO ESTADO,
  DET.DESADMINI DET_DESCRIPCION_INICIAL, DET.FRECUENCI DET_FRECUENCIA,CASE DET.UNIFRECUE WHEN 1 THEN 'Minutos' WHEN 2 THEN 'Horas' WHEN 3 THEN 'Dias' END  DET_UNIDAD_FRECUENCIA, DET.VALDURFIJ DET_DURACION_FIJA,DET.UNIDURFIJ DET_UNIDAD_FRECUENCIA_FIJA ,
  DET.FECINIDOS DET_FECHA_INICIAL,PRE.DESADMINI DET_DESCRIPCION_MODIFICADA,VIA.DESVIAADM 'VIA DE ADMINISTRACION'
 FROM DBO.HCPRESCRA AS PRE with (nolock)
  INNER JOIN DBO.HCPRESCRD AS DET with (nolock) ON PRE.CODCONCEC =DET.CODCONCEC AND PRE.CODPRODUC =DET.CODPRODUC 
  INNER JOIN DBO.INUNIMEDI AS UNI with (nolock) ON UNI.CODUNIMED =DET.CODUNIMED 
  INNER JOIN CTE_CAMAS AS CAM with (nolock) ON CAM.IPCODPACI =PRE.IPCODPACI AND CAM.NUMINGRES =PRE.NUMINGRES
  LEFT JOIN DBO.HCVIAADMI AS VIA with (nolock) ON VIA.CODVIAADM =PRE.CODVIAADM
),

CTE_MEZCLAS
AS
(
   SELECT A.CONSECUTI ,A.CODCONCEC ,A.IDETIPHIS ,A.NUMEFOLIO ,A.FECHAFINC ,A.CODPROSAL ,A.IPCODPACI, A.NUMINGRES ,A.UFUCODIGO,A.MEZLIQPAC 'PRESCRIPCION'  ,A.ADMMEZLIQ,A.CODDIAGNO ,
   MED.CODPRODUC 'CODIGO MEDICAMENTO' ,MED.CONMEDMEZ 'DOSIS MEZCLA' ,MED.UNIMEDMED 'UNIDAD MEZCLA' ,MED.CANPROCAL 'CANTIDAD SOLICITADA' ,MED.UNIMEDVOL ,MED.UNIMEDPES ,LIQ.CODPRODUC ,
   LIQ.CANPROCAL ,LIQ.CANPASDIL 'DOSIS LIQUIDO' ,LIQ.UNIMEDDIL 
   FROM DBO.HCINFLIQA A with (nolock)
   INNER JOIN CTE_CAMAS AS CAM with (nolock) ON CAM.IPCODPACI =A.IPCODPACI AND CAM.NUMINGRES =A.NUMINGRES
   LEFT JOIN DBO.HCINFCONC AS MED with (nolock) ON A.CODCONCEC =MED.CODCONCEC AND A.NUMINGRES =MED.NUMINGRES 
   LEFT JOIN DBO.HCINFLIQD AS LIQ with (nolock) ON A.CODCONCEC =LIQ.CODCONCEC AND A.NUMINGRES =LIQ.NUMINGRES 
),

CTE_ORDENAMIENTO_FARMACIA_HCFARMEPC_HCFARMEPD
AS
(
   SELECT DETF.ID ,CABF.CODCONCEC 'CABF_CONSECUTIVO' ,CABF.IDETIPHIS 'CABF_TIPO_HC' ,CABF.NUMEFOLIO 'CABF_FOLIO' ,
   CABF.FECHAORDE 'CABF_FECHA_ORDEN' ,
   CABF.CODPROSAL 'CABF_PREFESIONAL' ,
   CABF.IPCODPACI 'CABF_IDENTIFICACION' ,CABF.NUMINGRES 'CABF_INGRESO' ,CABF.UFUCODIGO 'CABF_UNIDAD_FUNCIONAL' ,CABF.CODCONCEP 'CABF_CONSECUTIVO_PADRE'  ,
   CASE CABF.ORDTRANUE WHEN 1 THEN 'Tratamiento Nuevo' WHEN 2 THEN 'Tratamiento Antiguo' WHEN 3 THEN 'Codigo Azul' END 'CABF_TIPO_ORDEN', 
   CASE CABF.ORDESTADO WHEN 1 THEN 'Pendiente' WHEN 2 THEN 'Entregada' WHEN 3 THEN 'Anulada' END 'CABF_ESTADO_ORDEN',   
   DETF.CODPRODUC 'DETF_COD_MEDICAMENTO',PRO.DESPRODUC 'DETF_MEDICAMENTO' ,DETF.DOSISPROD 'DETF_DOSIS_ORDENADA' ,UNI.DESUNIMED 'DETF_UNIDAD_MEDIDA' ,DETF.FRECUENCI 'DETF_FRECUENCIA',
   CASE DETF.UNIFRECUE WHEN 1 THEN 'Minutos' WHEN 2 THEN 'Horas' WHEN 3 THEN 'Dias' END 'DETF_UNIDAD_FRECUENCIA'  ,DETF.FECINIDOS 'DETF_FECHA_INICIAL' ,
   CASE DETF.TIPFORMED WHEN 1 THEN 'Peso' WHEN 2 THEN 'Volumen' WHEN 3 THEN 'Peso-Volumen' WHEN 4 THEN 'Unidad de Administración' end 'DETF_TIPO_FORMULACION',DETF.DURACIDOS 'DETF_DURACION',
   DETF.VALDURFIJ 'DETF_DURACION_FIJA' ,CASE DETF.UNIDURFIJ WHEN 1 THEN 'Minutos' WHEN 2 THEN 'Horas' WHEN 3 THEN 'Dias' END 'DETF_UNIDAD_DURACION_FIJA',DETF.CANPEDPRO 'DETF_CANTIDAD_ORDENADA',
   CASE DETF.PROESTADO WHEN 1 THEN 'Pendiente' WHEN 2 THEN 'Entregado' WHEN 3 THEN 'Anulado por Suspencion' WHEN 4 THEN 'Confirmacion de Entregado' END 'DETF_ESTADO_MEDICAMENTO',
   CASE DETF.NOPOSPROD WHEN 1 THEN 'PBS' ELSE 'NO PBS' END 'DETF_TECNOLOGIA' ,DETF.ID 'DETF_ID' ,DETF.IdSourceTable 'DETF_ID_HCPRESCRA' ,DETF.SourceTable 'DETF_TABLA_ORIGEN',
   VIA.DESVIAADM 'VIA DE ADMINISTRACION',GP.Name 'GRUPO TERAPEUTICO'
   FROM DBO.HCFARMEPC CABF with (nolock)
   INNER JOIN CTE_CAMAS AS CAM with (nolock) ON CAM.IPCODPACI =CABF.IPCODPACI AND CAM.NUMINGRES =CABF.NUMINGRES
   INNER JOIN DBO.HCFARMEPD AS DETF with (nolock) ON CABF.CODCONCEC =DETF.CODCONCEC 
   INNER JOIN DBO.IHLISTPRO AS PRO with (nolock) ON DETF.CODPRODUC =PRO.CODPRODUC 
   INNER JOIN Inventory .ATC AS ATC with (nolock) ON ATC.Code =PRO.CODPRODUC 
   INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON DETF.UFUCODIGO =FUN.UFUCODIGO 
   INNER JOIN DBO.INPROFSAL AS SAL with (nolock) ON DETF.CODPROSAL =SAL.CODPROSAL
   INNER JOIN Inventory .PharmacologicalGroup GP with (nolock) ON GP.Id =ATC.PharmacologicalGroupId 
   LEFT JOIN DBO.INUNIMEDI AS UNI with (nolock) ON DETF.CODUNIMED =UNI.CODUNIMED
   LEFT JOIN DBO.HCVIAADMI AS VIA with (nolock) ON VIA.CODVIAADM =PRO.CODVIAADM
   --WHERE CAST(CABF.FECHAORDE AS DATE) BETWEEN DATEADD(Day,-2,GETDATE()) AND GETDATE()
 WHERE CABF.FECHAORDE BETWEEN (GETDATE()-2) AND (GETDATE())
 )

SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
CASE FAR.DETF_TABLA_ORIGEN WHEN 'HCPRESCRA' THEN 'MEDICAMENTOS' WHEN 'HCINFLIQA' THEN 'MEZCLAS' ELSE 
IIF((FAR.CABF_TIPO_HC<>'ENFERMER1' AND FAR.DETF_ID_HCPRESCRA IS NULL),'MEZCLA','REPOSICION ENFERMERIA')  END 'TIPO FORMULACION', 
CASE FAR.CABF_TIPO_HC WHEN 'ENFERMER1' THEN 'REPOSICION ENFERMERIA' ELSE 'MEDICOS' END 'TIPO ROL' ,FAR.CABF_FOLIO 'FOLIO ORDENAMIENTO', 
FAR.CABF_FECHA_ORDEN 'FECHA ORDEN' ,
FAR.CABF_IDENTIFICACION 'IDENTIFICACION',PAC.IPNOMCOMP  'PACIENTE',CAST(PAC.IPFECNACI AS date ) 'FECHA NACIMIENTO' ,FAR.CABF_INGRESO 'INGRESO' ,UFU.UFUDESCRI 'UNIDAD FUNCIONAL',CAM.NUMCAMHOS 'CAMA', 
CASE  FAR.CABF_TIPO_ORDEN WHEN 'Tratamiento Nuevo' THEN 
IIF(REL.DET_CONSECUTIVO IS NOT NULL,IIF(REL.DET_DESCRIPCION_INICIAL <>REL.DET_DESCRIPCION_MODIFICADA,'Tratamiento Modificado','Tratamiento Nuevo'),'Tratamiento Nuevo')
WHEN 'Tratamiento Antiguo' THEN 'Tratamiento Antiguo' WHEN 'Codigo Azul' THEN 'Codigo Azul' ELSE 'N/A' END 'TIPO TRATAMIENTO',
FAR.CABF_ESTADO_ORDEN 'ESTADO DE LA ORDEN',FAR.DETF_COD_MEDICAMENTO 'CODIGO MEDICAMENTO' ,FAR.DETF_MEDICAMENTO 'MEDICAMENTO' ,
IIF(FAR.DETF_TABLA_ORIGEN='HCINFLIQA','',REL.DET_DESCRIPCION_INICIAL) 'DESCRIPCION INICIAL MEDICAMENTOS' ,RTRIM(MEZ.PRESCRIPCION) +' ' + RTRIM(MEZ.ADMMEZLIQ) 'DESCRIPCION INICIAL MEZCLAS',
ISNULL(PRE.PRE_DOSIS_ORDENADA ,REL.PRE_DOSIS) 'DOSIS ORDENDA MEDICAMENTOS',
ISNULL(MEZ.[DOSIS MEZCLA],MEZL.[DOSIS LIQUIDO] ) 'DOSIS ORDENADA MEZCLA', FAR.DETF_DOSIS_ORDENADA 'DOSIS FARMACIA' ,
ISNULL(FAR.DETF_UNIDAD_MEDIDA,REL.DET_UNIDAD) 'UNIDAD MEDIDA',
ISNULL(FAR.DETF_FRECUENCIA,ISNULL(PRE.PRE_FRECUENCIA,REL.DET_FRECUENCIA)) 'FRECUENCIA' ,ISNULL(FAR.DETF_UNIDAD_FRECUENCIA,ISNULL(PRE.PRE_UNIDAD_FRECUENCIA,REL.DET_UNIDAD_FRECUENCIA))'UNIDAD FRECUENCIA', 
ISNULL(FAR.DETF_DURACION,ISNULL(PRE.PRE_DURACION,REL.DET_DURACION)) 'DURACION',ISNULL(FAR.DETF_DURACION_FIJA,ISNULL(PRE.PRE_DURACION_FIJA,REL.DET_DURACION_FIJA )) 'DURACION FIJA',
ISNULL(FAR.DETF_UNIDAD_DURACION_FIJA,ISNULL(PRE.PRE_UNIDAD_FIJA,REL.DET_UNIDAD_FRECUENCIA_FIJA)) 'UNIDAD DURACION FIJA',ISNULL(PRE.PRE_DESCRIPCION_ADMIN,ISNULL(REL.DET_DESCRIPCION_MODIFICADA,MEZ.PRESCRIPCION )  ) 'ADMINISTRACION',
FAR.DETF_CANTIDAD_ORDENADA 'CANTIDAD ORDENADA' ,FAR.DETF_TECNOLOGIA 'TECNOLOGIA',ISNULL(PRE.[VIA DE ADMINISTRACION],ISNULL(REL.[VIA DE ADMINISTRACION],FAR.[VIA DE ADMINISTRACION])) 'VIA DE ADMINISTRACION',
FAR.[GRUPO TERAPEUTICO] ,FAR.DETF_ID ,FAR.CABF_CONSECUTIVO ,FAR.DETF_ID_HCPRESCRA ,FAR.DETF_TABLA_ORIGEN,
1 as 'CANTIDAD',
CAST([CABF_FECHA_ORDEN] AS date) AS 'FECHA BUSQUEDA',
YEAR([CABF_FECHA_ORDEN]) AS 'AÑO FECHA BUSQUEDA',
MONTH([CABF_FECHA_ORDEN]) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH([CABF_FECHA_ORDEN]) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
  END AS 'MES NOMBRE FECHA BUSQUEDA', 
FORMAT(DAY([CABF_FECHA_ORDEN]), '00') AS 'DIA FECHA BUSQUEDA',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM CTE_ORDENAMIENTO_FARMACIA_HCFARMEPC_HCFARMEPD FAR with (nolock)
INNER JOIN DBO.INUNIFUNC UFU with (nolock) ON FAR.CABF_UNIDAD_FUNCIONAL  = UFU.UFUCODIGO 
INNER JOIN DBO.INPROFSAL AS PROF with (nolock) ON FAR.CABF_PREFESIONAL  =PROF.CODPROSAL 
INNER JOIN DBO.INPACIENT AS PAC with (nolock) ON FAR.CABF_IDENTIFICACION  =PAC.IPCODPACI 
INNER JOIN CTE_CAMAS AS CAM with (nolock) ON CAM.IPCODPACI =FAR.CABF_IDENTIFICACION AND CAM.NUMINGRES =FAR.CABF_INGRESO 
LEFT JOIN CTE_MEDICAMENTOS_HCPRESCRA AS PRE with (nolock) ON FAR.CABF_IDENTIFICACION =PRE.PRE_IDENTIFICACION AND FAR.DETF_ID_HCPRESCRA =PRE.PRE_ID 
LEFT JOIN CTE_MEDICAMENTOS_HCPRESCRA_HCPRESCRD AS REL with (nolock) ON REL.IPCODPACI =FAR.CABF_IDENTIFICACION AND REL.NUMINGRES =FAR.CABF_INGRESO AND REL.CODPRODUC =FAR.DETF_COD_MEDICAMENTO 
LEFT JOIN CTE_MEZCLAS AS MEZ with (nolock) ON MEZ.CONSECUTI =FAR.DETF_ID_HCPRESCRA AND MEZ.[CODIGO MEDICAMENTO] =FAR.DETF_COD_MEDICAMENTO 
LEFT JOIN CTE_MEZCLAS AS MEZL with (nolock) ON MEZL.CONSECUTI =FAR.DETF_ID_HCPRESCRA AND MEZL.CODPRODUC  =FAR.DETF_COD_MEDICAMENTO 
--order by CABF_CONSECUTIVO
