-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewReingresos
-- Extracted by Fabric SQL Extractor SPN v3.9.0








    /*******************************************************************************************************************
Nombre: [Report].[ViewReingresos]
Tipo:Vista
Observacion:Vista de reingresos hasta las 72 horas por mismo diagnostico en urgencias y 15 dias por hospitalización,
Profesional: Nilsson Miguel Galindo Lopez
Fecha:18-07-2022
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Vercion 1
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha: 21-07-2023
Ovservaciones:Se cambia la logica, cambiando el tipo de ingreso no teniendo encuenta solo el tipo 2, ya que si el paciente ingresa por urgencias
			  el ingreso que se apertura es uno como si fuera consulta externa, por eso ahora se pone que el paciente halla ingresado por cualquier unidad
			  menos la de consulta externa.
--------------------------------------
Vercion 2
Persona que modifico:
Fecha:
***********************************************************************************************************************************/
CREATE VIEW [Report].[ViewReingresos] AS

WITH

CTE_INGRESO as
(
SELECT
ROW_NUMBER ( )   
    OVER ( PARTITION BY ING.IPCODPACI  order by ING.IPCODPACI,ING.IFECHAING) 'NUMERO',
ING.IPCODPACI,ING.NUMINGRES,ING.IFECHAING,EGR.FECALTPAC AS FECHEGRESO,ING.CODDIAING,ING.CODDIAEGR,ING.UFUCODIGO,
ING.UFUEGRMED,ING.CODCENATE,
CASE ING.IREINGRES WHEN 1 THEN 'SI' ELSE 'NO' END AS IREINGRES
FROM 
DBO.ADINGRESO ING INNER JOIN
dbo.HCREGEGRE EGR ON ING.NUMINGRES=EGR.NUMINGRES AND EGR.FECALTPAC IS NOT NULL
WHERE ING.IINGREPOR!=2  --IN V2 ING.TIPOINGRE=2 FN V2
),

CTE_REINGRESOS AS
(
select 
A.CODCENATE,
A.IPCODPACI AS [IDENTIFICACION],
A.NUMINGRES AS [NUMERO INGRESO A],
A.IFECHAING AS [FECHA INGRESO A],
A.FECHEGRESO AS [FECHA EGRESO A],
A.CODDIAING AS [DIAGNOSTICO INGRESO A],
A.CODDIAEGR AS [DIAGNOSTICO EGRESO A],
A.UFUCODIGO AS [UNIDAD INGRESO A],
A.UFUEGRMED AS [UNIDAD EGRESO A],
A.IREINGRES AS [REINGRESO VIE A],
B.NUMINGRES [NUMERO INGRESO B],
B.IFECHAING [FECHA INGRESO B],
B.FECHEGRESO [FECHA EGRESO B],
B.CODDIAING AS [DIAGNOSTICO INGRESO B],
B.CODDIAEGR AS [DIAGNOSTICO EGRESO B],
B.UFUCODIGO AS [UNIDAD INGRESO B],
B.UFUEGRMED AS [UNIDAD EGRESO B],
B.IREINGRES AS [REINGRESO VIE B],
DATEDIFF(HOUR,A.FECHEGRESO,B.IFECHAING) AS [HORAS EA vs IB]
from 
CTE_INGRESO A inner join CTE_INGRESO B ON A.IPCODPACI=B.IPCODPACI AND A.NUMERO='1' AND B.NUMERO='2' AND (A.CODDIAEGR=B.CODDIAING OR A.CODDIAING=B.CODDIAING)
UNION 
select 
A.CODCENATE,
A.IPCODPACI AS [IDENTIFICACION],
A.NUMINGRES AS [NUMERO INGRESO A],
A.IFECHAING AS [FECHA INGRESO A],
A.FECHEGRESO AS [FECHA EGRESO A],
A.CODDIAING AS [DIAGNOSTICO INGRESO A],
A.CODDIAEGR AS [DIAGNOSTICO EGRESO A],
A.UFUCODIGO AS [UNIDAD INGRESO A],
A.UFUEGRMED AS [UNIDAD EGRESO A],
A.IREINGRES AS [REINGRESO VIE A],
B.NUMINGRES [NUMERO INGRESO B],
B.IFECHAING [FECHA INGRESO B],
B.FECHEGRESO [FECHA EGRESO B],
B.CODDIAING AS [DIAGNOSTICO INGRESO B],
B.CODDIAEGR AS [DIAGNOSTICO EGRESO B],
B.UFUCODIGO AS [UNIDAD INGRESO B],
B.UFUEGRMED AS [UNIDAD EGRESO B],
B.IREINGRES AS [REINGRESO VIE B],
DATEDIFF(HOUR,A.FECHEGRESO,B.IFECHAING) AS [HORAS EA vs IB]
from 
CTE_INGRESO A inner join CTE_INGRESO B ON A.IPCODPACI=B.IPCODPACI AND A.NUMERO='2' AND B.NUMERO='3' AND (A.CODDIAEGR=B.CODDIAING OR A.CODDIAING=B.CODDIAING)
UNION 
select 
A.CODCENATE,
A.IPCODPACI AS [IDENTIFICACION],
A.NUMINGRES AS [NUMERO INGRESO A],
A.IFECHAING AS [FECHA INGRESO A],
A.FECHEGRESO AS [FECHA EGRESO A],
A.CODDIAING AS [DIAGNOSTICO INGRESO A],
A.CODDIAEGR AS [DIAGNOSTICO EGRESO A],
A.UFUCODIGO AS [UNIDAD INGRESO A],
A.UFUEGRMED AS [UNIDAD EGRESO A],
A.IREINGRES AS [REINGRESO VIE A],
B.NUMINGRES [NUMERO INGRESO B],
B.IFECHAING [FECHA INGRESO B],
B.FECHEGRESO [FECHA EGRESO B],
B.CODDIAING AS [DIAGNOSTICO INGRESO B],
B.CODDIAEGR AS [DIAGNOSTICO EGRESO B],
B.UFUCODIGO AS [UNIDAD INGRESO B],
B.UFUEGRMED AS [UNIDAD EGRESO B],
B.IREINGRES AS [REINGRESO VIE B],
DATEDIFF(HOUR,A.FECHEGRESO,B.IFECHAING) AS [HORAS EA vs IB]
from 
CTE_INGRESO A inner join CTE_INGRESO B ON A.IPCODPACI=B.IPCODPACI AND A.NUMERO='3' AND B.NUMERO='4' AND (A.CODDIAEGR=B.CODDIAING OR A.CODDIAING=B.CODDIAING)
)

------------------------------CONSULTA CON LOS 3 REINGRESOS POSIBLES-----------------------------------------------------

SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
RTRIM(R.CODCENATE)+' - '+ CEN.NOMCENATE AS [CENTRO DE ATENCION],
ROW_NUMBER ( )   
    OVER ( PARTITION BY IDENTIFICACION  order by IDENTIFICACION,[FECHA INGRESO A]) AS [NUMERO DE REINGRESOS],
IDENTIFICACION,
CASE PAC.IPTIPODOC WHEN 1 THEN 'CC - CEDULA DE CIUDADANIA' 
				   WHEN 2 THEN 'CE - CEDULA DE EXTRANJERIA' 
				   WHEN 3 THEN 'TI - TARJETA DE IDENTIDAD' 
				   WHEN 4 THEN 'RC - REGISTRO CIVIL' 
				   WHEN 5 THEN 'PA - PASAPORTE' 
				   WHEN 6 THEN 'AS - ADULTO SIN IDENTIFICACION' 
				   WHEN 7 THEN 'MS - MENOR SIN IDENTIFICACION' 
				   WHEN 8 THEN 'NU - NUMERO UNICO DE IDENTIFICACIÒN' 
				   WHEN 9 THEN 'NV - CERTIFICADO NACIDO VIVO' 
				   WHEN 10 THEN 'CD - CARNET DIPLOMATICO' 
				   WHEN 11 THEN 'SC - SALVOCONDUCTO' 
				   WHEN 12 THEN 'PE - PERMISO ESPECIAL DE PERMANENCIA' ELSE 'OTRO' END [TIPO IDENTIFICACION],
PAC.IPNOMCOMP AS [NOMBRE COMPLETO],
PAC.IPPRINOMB AS [PRIMER NOMBRE],
PAC.IPSEGNOMB AS [SEGUNDO NOMBRE], 
PAC.IPPRIAPEL AS [PRIMER APELLIDO],
PAC.IPSEGAPEL AS [SEGUNDO APELLIDO],
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END [SEXO],
CAST(PAC.IPFECNACI AS DATE ) AS [FECHA_NACIMIENTO],
FLOOR((CAST(CONVERT(VARCHAR(8), [FECHA INGRESO A] , 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS [EDAD],
DEP.NOMDEPART AS DEPARTAMENTO, 
MUN.MUNNOMBRE AS MUNICIPIO,
UB.UBINOMBRE AS UBICACION,
PAC.IPTELEFON AS [TELEFONO],
PAC.IPTELMOVI AS [CELULAR],
EAPB.CODENTIDA AS [CODIGO EAPB],
EAPB.NOMENTIDA AS [NOMBRE EAPB],
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro' 
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado'
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [REGIMEN],
[NUMERO INGRESO A],
[FECHA INGRESO A],
[FECHA EGRESO A],
[DIAGNOSTICO INGRESO A]+' - '+INGA.NOMDIAGNO AS [DIAGNOSTICO INGRESO A],
[DIAGNOSTICO EGRESO A]+' - '+EGRA.NOMDIAGNO AS [DIAGNOSTICO EGRESO A],
RTRIM([UNIDAD INGRESO A])+' - '+FUNIA.UFUDESCRI AS [UNIDAD INGRESO A],
RTRIM([UNIDAD EGRESO A])+' - '+FUNEA.UFUDESCRI AS [UNIDAD EGRESO A],
[NUMERO INGRESO B],
[FECHA INGRESO B],
[FECHA EGRESO B],
[DIAGNOSTICO INGRESO B]+' - '+INGA.NOMDIAGNO AS [DIAGNOSTICO INGRESO B],
[DIAGNOSTICO EGRESO B]+' - '+EGRA.NOMDIAGNO AS [DIAGNOSTICO EGRESO B],
RTRIM([UNIDAD INGRESO B])+' - '+FUNIB.UFUDESCRI AS [UNIDAD INGRESO B],
RTRIM([UNIDAD EGRESO B])+' - '+FUNEB.UFUDESCRI AS [UNIDAD EGRESO B],
[REINGRESO VIE B],
[HORAS EA vs IB],
 1 'CANTIDAD',
 CAST([FECHA INGRESO A] AS date) AS 'FECHA BUSQUEDA',
 YEAR([FECHA INGRESO A]) AS 'AÑO BUSQUEDA',
 MONTH([FECHA INGRESO A]) AS 'MES BUSQUEDA',
 CONCAT(FORMAT(MONTH([FECHA INGRESO A]), '00') ,' - ', 
	   CASE MONTH([FECHA INGRESO A]) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
CTE_REINGRESOS R INNER JOIN
DBO.INPACIENT PAC ON R.IDENTIFICACION=PAC.IPCODPACI INNER JOIN
INUBICACI UB ON PAC.AUUBICACI=UB.AUUBICACI INNER JOIN
INMUNICIP MUN ON UB.DEPMUNCOD = MUN.DEPMUNCOD INNER JOIN
INDEPARTA DEP ON MUN.DEPCODIGO = DEP.DEPCODIGO AND PAC.AUUBICACI = UB.AUUBICACI INNER JOIN
INENTIDAD AS EAPB ON PAC.CODENTIDA=EAPB.CODENTIDA INNER JOIN
INDIAGNOS AS INGA ON R.[DIAGNOSTICO INGRESO A]=INGA.CODDIAGNO INNER JOIN
INDIAGNOS AS EGRA ON R.[DIAGNOSTICO EGRESO A]=EGRA.CODDIAGNO INNER JOIN
INDIAGNOS AS INGB ON R.[DIAGNOSTICO INGRESO B]=INGB.CODDIAGNO INNER JOIN
INDIAGNOS AS EGRB ON R.[DIAGNOSTICO EGRESO B]=EGRB.CODDIAGNO INNER JOIN
INUNIFUNC AS FUNIA ON R.[UNIDAD INGRESO A]=FUNIA.UFUCODIGO INNER JOIN
INUNIFUNC AS FUNEA ON R.[UNIDAD EGRESO A]=FUNEA.UFUCODIGO INNER JOIN
INUNIFUNC AS FUNIB ON R.[UNIDAD INGRESO B]=FUNIB.UFUCODIGO INNER JOIN
INUNIFUNC AS FUNEB ON R.[UNIDAD EGRESO B]=FUNEB.UFUCODIGO INNER JOIN
dbo.ADCENATEN CEN ON R.CODCENATE=CEN.CODCENATE
WHERE 
(DATEDIFF(HOUR,[FECHA EGRESO A],[FECHA INGRESO B])<='360' AND FUNEA.UFUDESCRI NOT LIKE '%URGENCIAS%') OR
(DATEDIFF(HOUR,[FECHA EGRESO A],[FECHA INGRESO B])<='72' AND FUNEA.UFUDESCRI LIKE '%URGENCIAS%')
