-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_FAC_PENDIENTE_POR_FACTURAR_PRODUCTIVIDAD
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[View_FAC_PENDIENTE_POR_FACTURAR_PRODUCTIVIDAD]
AS

WITH CTE_INGRESOS_PENDIENTES_UNICOS
----CTE PARA IDENTIFICAR LOS INGRESOS UNICOS PENDIENTES DE LIQUIDAR
AS
(
SELECT DISTINCT RCD.RevenueControlId  ,RC.AdmissionNumber 
--SUM(sodd.ThirdPartySalesPrice + sodd.SubTotalPatientSalesPrice + sodd.GrandTotalDiscount)
FROM Contract.CareGroup cg WITH (NOLOCK)
	INNER JOIN Billing.RevenueControlDetail rcd WITH (NOLOCK) ON cg.Id = rcd.CareGroupId
	INNER JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) ON rcd.Id = sodd.RevenueControlDetailId
	INNER JOIN Billing.ServiceOrderDetail sod WITH (NOLOCK) ON sodd.ServiceOrderDetailId = sod.Id
	INNER JOIN Billing .RevenueControl AS RC WITH (NOLOCK) ON RC.Id =RCD.RevenueControlId 
WHERE rcd.[Status] IN (1,3) And cg.LiquidationType In (1, 3) AND sod.IsDelete = 0 AND sod.SettlementType != 3 AND sod.GrandTotalSalesPrice > 0
),
CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
AS
(
    SELECT EGR.IPCODPACI ,EGR.NUMINGRES,EGR.FECINIEST ,EGR.FECFINEST ,EGR.CODICAMAS,CAM.NUMCAMHOS ,FUN.UFUDESCRI  ,FUN.UFUTIPUNI  
	FROM CHREGESTA EGR with (nolock)
	INNER JOIN 
	(
	   SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR with (nolock)
	   INNER JOIN CTE_INGRESOS_PENDIENTES_UNICOS AS UNI with (nolock) ON UNI.AdmissionNumber=EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G  ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM with (nolock) ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),
CTE_EGRESO_CAMA
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO  
FROM CHREGEGRE EGR
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECEGRESO) EGRESO 
 FROM CHREGEGRE EGR with (nolock) 
 INNER JOIN CTE_INGRESOS_PENDIENTES_UNICOS AS UNI with (nolock) ON UNI.AdmissionNumber=EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.EGRESO =EGR.FECEGRESO 
),
CTE_ALTA_MEDICA
----CTE PARA IDENTIFICAR LA FECHA DE ALTA MEDICA
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECALTPAC 
FROM HCREGEGRE EGR with (nolock)
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECALTPAC) 'ALTA MEDICA' 
 FROM HCREGEGRE EGR with (nolock) 
 INNER JOIN CTE_INGRESOS_PENDIENTES_UNICOS AS UNI with (nolock) ON UNI.AdmissionNumber=EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.[ALTA MEDICA] =EGR.FECALTPAC 
),
CTE_HISTORIAS_AMBULATORIAS
--CTE PARA IDENTIFICAR LAS HISTORIAS CLINICAS AMBULATORIAS SU FECHA DE HISTORIA
AS
(
  SELECT HIS.NUMINGRES ,HIS.IPCODPACI ,FECHISPAC AS 'FECHA ALTA' FROM  DBO.HCHISPACA HIS with (nolock)
  INNER JOIN
  (
  SELECT HIS.NUMINGRES ,HIS.IPCODPACI ,MAX(HIS.ID) AS 'ID' FROM  DBO.HCHISPACA HIS with (nolock)
  INNER JOIN CTE_INGRESOS_PENDIENTES_UNICOS AS PEN with (nolock) ON PEN.AdmissionNumber  =HIS.NUMINGRES
  WHERE HIS.GENCONEXT =1
  GROUP BY HIS.NUMINGRES ,HIS.IPCODPACI
  ) AS G ON G.NUMINGRES =HIS.NUMINGRES AND G.ID =HIS.ID 
),
CTE_PENDIENTES_FACTURAR
AS
(
SELECT 
SUBSTRING(HA.Name ,1,50) 'ENTIDAD',CG.Code 'CODIGO GRUPO ATENCION',CG.Name  'GRUPO DE ATENCION',UNI.AdmissionNumber 'INGRESO',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
CAST(ISNULL(ING.FECHEGRESO,ISNULL(EGR.FECEGRESO,ING.IFECHAING)) AS DATE) 'FECHA EGRESO',
CASE PAC.IPTIPODOC WHEN '1' THEN 'CEDULA DE CIUDADANIA' WHEN '2' THEN 'CEDULA DE EXTRANJERIA' WHEN '3' THEN 'TARJETA DE IDENTIDAD' WHEN '4' THEN 'REGISTRO CIVIL' 
WHEN '5' THEN 'PASAPORTE' WHEN '6' THEN 'ADULTO SIN IDENTIFICACION' WHEN '7' THEN 'MENOR SIN IDENTIFICACION' WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION' 
WHEN '9' THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO'WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION' END AS 'TIPO IDENTIFICACION',
RC.PatientCode 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE','SIN FACTURAR' AS 'ESTADO FACTURA',
'-' 'NRO FACTURA','1900-01-01' AS 'FECHA FACTURA','0' AS 'TOTAL FACTURA','0' AS 'VR TOTAL ENTIDAD','0' AS 'VR TOTAL CUOTA RECUPERACION',
CASE SOD.RecordType WHEN 1 THEN 'Servicios' WHEN 2 THEN 'Medicamentos' ELSE 'N/A' END 'TIPO REGISTRO',
ISNULL(CGR.Code + '-' + CGR.Name, PG.Code + '-' + PG.NAME) 'GRUPO', ISNULL(CSG.CODE + '-' + CSG.Name, PSG.Code + '-' + PSG.NAME) 'SUBGRUPO',
ISNULL(GF.Name, GF2.Name) AS 'GRUPO FACTURACION',CASE SOD.Presentation WHEN 1 THEN 'No quirurgico' WHEN 2 THEN 'Quirurgico' WHEN 3 THEN 'Paquete' ELSE 'PRODUCTO' END 'PRESENTACION',
SO.OrderDate 'FECHA ORDEN', SOD.ServiceDate 'FECHA SERVICIO',ISNULL(CUPS.Code,'N/A') 'CUPS',SUBSTRING(ISNULL(RTRIM(CUPS.Description),'N/A'),1,60) 'DESCRIPCION CUPS',
ISNULL(RTRIM(IPS.Code),RTRIM(IPR.CODE)) 'CODIGO SERVICIO/PRODUCTO',SUBSTRING(ISNULL(RTRIM(IPS.Name),RTRIM(IPR.NAME)),1,60) 'DESCRIPCION SERVICIO/PRODUCTO',
ISNULL(SERVICIOSIPSQ.Code, 'N/A') AS 'SUBCODIGO', SUBSTRING(ISNULL(RTRIM(SERVICIOSIPSQ.Name), 'N/A'),1,60) AS 'SUBNOMBRE',
CASE SOD.IsPackage WHEN 1 THEN 'PAQUETE (INCLUYE OTROS SERVICIOS)'  WHEN 0 THEN 'NO ES PAQUETE' ELSE 'N/A' END 'PAQUETE',
CASE SOD.Packaging WHEN 1 THEN 'INCLUIDO EN PAQUETE'  WHEN 0 THEN 'NO INCLUIDO EN PAQUETE' ELSE 'N/A' END 'INCLUIDO EN PAQUETE',
ISNULL(CUPS_PAQ.Code,'N/A') 'CUPS PAQUETE',SUBSTRING(ISNULL(RTRIM(CUPS_PAQ.Description),'N/A'),1,60) 'DESCRIPCION CUPS PAQUETE',
CASE sod.SettlementType WHEN 1 THEN 'Por manual de tarifas' WHEN 2 THEN '% de otro servicio cargado' WHEN 3 THEN '100% incluido dentro de otro servicio (No se cobra nada)'
WHEN 4 THEN '% del mismo servicio' ELSE 'N/A' END 'TIPO LIQUIDACION',
ISNULL(CUPS_INC.Code,'N/A') 'CUPS INCLUIDO',SUBSTRING(ISNULL(RTRIM(CUPS_INC.Description),'N/A'),1,60) 'DESCRIPCION CUPS INCLUIDO',
FU.Code 'COD UNIDAD FUNCIONAL',RTRIM(FU.Name)'UNIDAD FUNCIONAL PRESTO SERVICIO',COST.Code 'COD CENTRO COSTO',RTRIM(COST.Name) 'CENTRO COSTO PRESTO SERVICIO',
RTRIM(ISNULL(DQ.PERFORMSHEALTHPROFESSIONALCODE,ISNULL(MED.CODPROSAL,'000'))) 'IDENTIFICACION PROFESIONAL' ,RTRIM(ISNULL(MEDQX.NOMMEDICO,ISNULL(MED.NOMMEDICO,'N/A'))) 'PROFESIONAL' ,
RTRIM(ISNULL(ESPQX.DESESPECI,ISNULL(ESPMED.DESESPECI,'N/A'))) 'ESPECIALIDAD',ISNULL(DQ.InvoicedQuantity,SOD.InvoicedQuantity) 'CANTIDAD',
ISNULL(DQ.RateManualSalePrice,SOD.RateManualSalePrice) 'VALOR SERVICIO',ISNULL(DQ.TOTALSALESPRICE,sod.TotalSalesPrice) 'VALOR UNITARIO',
ISNULL(DQ.TOTALSALESPRICE,SOD.GrandTotalSalesPrice) 'VALOR TOTAL',ISNULL(SOD.AuthorizationNumber,ING.IAUTORIZA) 'NUMERO AUTORIZACION',
CASE ISNULL(IPS.POS,IPR.POSProduct ) WHEN 1 THEN 'PBS' ELSE 'NO PBS' END 'TECNOLOGIA PBS',
CAM.NUMCAMHOS 'CAMA HOSPITALARIA' ,
CASE WHEN ING.TIPOINGRE=1 THEN 'AMBULATORIO'  WHEN ING.TIPOINGRE=2 AND (CAM.NUMCAMHOS LIKE 'O%' OR CAM.NUMCAMHOS LIKE 'U%' OR CAM.NUMCAMHOS LIKE 'SRE%' )THEN 'URGENCIAS' 
WHEN ING.TIPOINGRE=2 AND (CAM.NUMCAMHOS LIKE 'SAL%' OR CAM.NUMCAMHOS LIKE 'PRE%' OR CAM.NUMCAMHOS LIKE 'REC%')THEN 'CIRUGIA'
WHEN ING.TIPOINGRE=2 AND (CAM.NUMCAMHOS NOT LIKE 'SAL%' AND CAM.NUMCAMHOS NOT LIKE 'PRE%' AND  CAM.NUMCAMHOS NOT LIKE 'REC%' AND
CAM.NUMCAMHOS NOT LIKE 'O%' OR CAM.NUMCAMHOS NOT LIKE 'U%' OR CAM.NUMCAMHOS NOT LIKE 'SRE%') THEN 'HOSPITALIZACION'
END  'TIPO AMBITO'
--DISTINCT UNI.AdmissionNumber ,ING.NUMINGRES --RCD.* 
--SUM (sodd.ThirdPartySalesPrice + sodd.SubTotalPatientSalesPrice + sodd.GrandTotalDiscount)
--SUM(ISNULL(DQ.TOTALSALESPRICE,SOD.GrandTotalSalesPrice))
--SUM(SOD.GrandTotalSalesPrice)
FROM 
Billing .RevenueControlDetail AS RCD WITH (NOLOCK) 
INNER JOIN CTE_INGRESOS_PENDIENTES_UNICOS AS UNI WITH (NOLOCK) ON UNI.RevenueControlId =RCD.RevenueControlId 
INNER JOIN BILLING.SERVICEORDERDETAILDISTRIBUTION AS SODD WITH (NOLOCK) ON RCD.ID = SODD.REVENUECONTROLDETAILID
INNER JOIN Billing .RevenueControl AS RC ON RC.Id =RCD.RevenueControlId AND UNI.AdmissionNumber =RC.AdmissionNumber 
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD WITH (NOLOCK) ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN Billing .ServiceOrder AS SO WITH (NOLOCK) ON SOD.ServiceOrderId =SO.Id 
INNER JOIN CONTRACT.CAREGROUP AS CG WITH (NOLOCK) ON CG.ID = RCD.CAREGROUPID
INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
INNER JOIN Payroll.CostCenter AS COST WITH (NOLOCK) ON COST.Id =SOD.CostCenterId
LEFT JOIN DBO.INPACIENT AS PAC WITH (NOLOCK) ON RC.PatientCode =PAC.IPCODPACI
LEFT JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES =UNI.AdmissionNumber
LEFT JOIN CONTRACT.HEALTHADMINISTRATOR AS HA WITH (NOLOCK) ON HA.ID = RCD.HEALTHADMINISTRATORID
LEFT JOIN CTE_EGRESO_CAMA AS EGR ON EGR.NUMINGRES =UNI.AdmissionNumber 
LEFT JOIN CONTRACT.CUPSENTITY AS CUPS WITH (NOLOCK) ON CUPS.ID = SOD.CUPSENTITYID
LEFT JOIN INVENTORY.INVENTORYPRODUCT AS IPR WITH (NOLOCK) ON IPR.ID = SOD.PRODUCTID --AND IPR.Status = 1
LEFT JOIN Contract.CupsSubgroup AS CSG WITH (NOLOCK) ON CUPS.CUPSSubGroupId=CSG.ID
LEFT JOIN Contract.CupsGroup AS CGR WITH (NOLOCK) ON CGR.ID=CSG.CupsGroupId
LEFT JOIN Contract.IPSService AS IPS WITH (NOLOCK) ON IPS.Id = SOD.IPSServiceId
LEFT JOIN Inventory.ProductGroup AS PG WITH (NOLOCK) ON PG.ID =IPR.ProductGroupId
LEFT JOIN Inventory.ProductSubGroup AS PSG WITH (NOLOCK) ON PSG.ID =IPR.ProductSubGroupId
LEFT JOIN Billing.BillingGroup AS GF WITH (NOLOCK) ON GF.Id = CUPS.BillingGroupId
LEFT JOIN Billing.BillingGroup AS GF2 WITH (NOLOCK) ON GF2.Id = IPR.BillingGroupId
LEFT JOIN Billing.ServiceOrderDetailSurgical AS DQ WITH (NOLOCK) ON DQ.ServiceOrderDetailId = SOD.Id AND DQ.OnlyMedicalFees = '0'
LEFT JOIN Contract.IPSService AS SERVICIOSIPSQ WITH (NOLOCK) ON SERVICIOSIPSQ.Id = DQ.IPSServiceId
LEFT JOIN Billing .ServiceOrderDetail AS SOD_PAQ WITH (NOLOCK) ON SOD_PAQ.Id =SOD.PackageServiceOrderDetailId 
LEFT JOIN Contract.CUPSEntity AS CUPS_PAQ WITH (NOLOCK) ON CUPS_PAQ.Id = SOD_PAQ.CUPSEntityId
LEFT JOIN Billing .ServiceOrderDetail AS SOD_INC WITH (NOLOCK) ON SOD_INC.Id =SOD.IncludeServiceOrderDetailId
LEFT JOIN Contract.CUPSEntity AS CUPS_INC WITH (NOLOCK) ON CUPS_INC.Id = SOD_INC.CUPSEntityId
LEFT JOIN dbo.INPROFSAL AS MED WITH (NOLOCK) ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
LEFT JOIN dbo.INESPECIA AS ESPMED WITH (NOLOCK) ON ESPMED.CODESPECI = MED.CODESPEC1
LEFT JOIN dbo.INPROFSAL AS MEDQX WITH (NOLOCK) ON MEDQX.CODPROSAL = DQ.PerformsHealthProfessionalCode
LEFT JOIN dbo.INESPECIA AS ESPQX WITH (NOLOCK) ON ESPQX.CODESPECI = MEDQX.CODESPEC1
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA CAM (NOLOCK) ON CAM.NUMINGRES =UNI.AdmissionNumber 
where rcd.[Status] IN (1,3) And cg.LiquidationType In (1, 3) AND sod.IsDelete = 0 AND sod.SettlementType != 3 AND sod.GrandTotalSalesPrice > 0
--AND UNI.AdmissionNumber ='595       '
--ORDER BY RC.AdmissionNumber 
--SELECT * FROM CTE_INGRESOS_PENDIENTES_UNICOS
)

SELECT PEN.* FROM CTE_PENDIENTES_FACTURAR PEN
