-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewImagingRequests
-- Extracted by Fabric SQL Extractor SPN v3.9.0



/*******************************************************************************************************************
Nombre: [Report].[ViewImagingRequests]
Tipo:Vista
Observacion:Informe de todas las solicitudes realizadas correspondientes a imagenes DX
Profesional: 
Fecha:
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico: Nilsson Miguel Galindo Lopez
Fecha: 14-02-2023
Ovservaciones: Se crea CTE para las imagenes DX, tanto hospitalarias y ambulatorias, para mejorar el perfomance de la consulta.
--------------------------------------
Version 3
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:16-06-2023
Ovservaciones:Se cambia el tipo del dato datetime a date y se crean los campos HORA DE SOLICITUD ORDEN, HORA DE TOMA IMAGEN, HORA DE RESULTADO, TOMA VS RESULTADO
			  y SOLICITUD VS RESULTADO.
--------------------------------------
Version 4
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:13-10-2023
Ovservaciones:Se agrega el profesional y fecha de la validación de la trascripcion tambien el profesional y fecha del profesional que realiza la lectura.
***********************************************************************************************************************************/

CREATE VIEW [Report].[ViewImagingRequests] AS

--IN V2
--CTE para unir los ordenamientos de imagenes DX ya sean hospitalarios o extramulares
WITH
CTE_IMAGENES AS
(
	SELECT 
		[AUTO] AS [Id],
		IPCODPACI,
		CASE WHEN MANEXTPRO = 0 THEN 'HOSPITALARIO' ELSE 'AMBULATORIO' END AS [TIPO SOLICITUD],
		UFUCODIGO,
		NUMINGRES,
		NUMEFOLIO,
		CODSERIPS,
		FECORDMED,
		CASE ESTSERIPS WHEN '1' THEN 'SOLICITADO'
					   WHEN '2' THEN 'ESTUDIO REALIZADO' 
					   WHEN '3' THEN 'ESTUDIO REALIZADO'
					   WHEN '4' THEN 'ESTUDIOS REALIZADOS'
					   WHEN '5' THEN 'REMITIDO'
					   WHEN '6' THEN 'EXTRAMURAL'
					   WHEN '7'THEN 'ANULADO' ELSE 'ESTUDIOS NO REALIZADOS'END AS ESTADO,
		OBSSERIPS AS OBSERVACION,
		FECRECEXA,
		NOMARCIMG AS [NOMBRE ARCHIVO],
		CODCENATE,
		IDDESCRIPCIONRELACIONADA,
		CODPROSAL,
		ESTSERIPS,
		ISNULL(FECTRASER,FECHLECT) AS FECTRASER,
		NOMARCIMG,
		MEDREALEC,
		FECHLECT,
		CODPROVAL,
		FECVALSER
	FROM DBO.HCORDIMAG
	UNION ALL
	SELECT
		[AUTO] AS [Id],
		IPCODPACI,
		'AMBULATORIO' AS MANEXTPRO,
		UFUCODIGO,
		NUMINGRES,
		'' AS NUMEFOLIO,
		CODSERIPS,
		FECORDMED,
		CASE ESTSERIPS WHEN '1' THEN 'SOLICITADO'
					   WHEN '2' THEN 'ESTUDIO REALIZADO' 
					   WHEN '3' THEN 'ESTUDIO REALIZADO'
					   WHEN '4' THEN 'ESTUDIOS REALIZADOS'
					   WHEN '5' THEN 'REMITIDO'
					   WHEN '6' THEN 'EXTRAMURAL'
					   WHEN '7'THEN 'ANULADO' ELSE 'ESTUDIOS NO REALIZADOS'END AS ESTADO,
		OBSERVACI AS OBSERVACION,
		FECRECEXA,
		NOMARCIMG AS [NOMBRE ARCHIVO],
		CODCENATE,
		IDDESCRIPCIONRELACIONADA,
		CODPROSAL,
		ESTSERIPS,
		ISNULL(FECTRASER,FECHLECT) AS FECTRASER,
		NOMARCIMG,
		MEDREALEC,
		FECHLECT,
		CODPROVAL,
		FECVALSER
	FROM dbo.AMBORDIMA 
),
--FN V2
--CTE primer dx con estadio 
CTE_ESTADIO AS 
(
	SELECT
	EST.NUMEFOLIO, 
	EST.IPCODPACI PACIENTE, 
	ESTADIO
	FROM DBO.INDIAGNOH AS EST WHERE EST.NUMEFOLIO=(SELECT MIN(CAST(A.NUMEFOLIO AS INT)) FROM DBO.INDIAGNOH A WHERE EST.IPCODPACI=A.IPCODPACI AND A.ESTADIO IS NOT NULL 																																	 AND A.ESTADIO NOT IN (93, 98, 99))
),

--SERVICIOS CONTRARADOS POR GRUPO DE ATENCION
CTE_CONTRATOS_GRUPO AS
(
SELECT 
	CG.CODE AS CODGRUPO, 
    CE.CODE AS CUPS,
    CASE PC.CONTRACTED WHEN 1 THEN 'SI' ELSE 'NO' END AS CONTRATADO,
    CASE PC.QUOTED WHEN 1 THEN 'SI' ELSE 'NO'END AS COTIZADO, 
    CECD.ID AS IDRELACION
    FROM 
	CONTRACT.CAREGROUP AS CG INNER JOIN 
	CONTRACT.CONTRACT AS CON  ON CG.CONTRACTID = CON.ID INNER JOIN 
	CONTRACT.PROCEDURETEMPLATE AS PT  ON CG.PROCEDURETEMPLATEID = PT.ID INNER JOIN 
	CONTRACT.PROCEDURECUPS AS PC  ON PT.ID = PC.PROCEDURESTEMPLATEID INNER JOIN 
	CONTRACT.CUPSENTITY AS CE  ON PC.CUPSID = CE.ID LEFT JOIN 
	CONTRACT.CUPSENTITYCONTRACTDESCRIPTIONS AS CECD  ON PC.CUPSENTITYCONTRACTDESCRIPTIONID = CECD.ID 
)

SELECT 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
RTRIM(E.NOMCENATE) AS [CENTRO ATENCION],
CASE I.IPTIPODOC WHEN '1' THEN 'CC'
				 WHEN '2' THEN 'CE'
				 WHEN '3' THEN 'TI'
				 WHEN '4' THEN 'RC'
				 WHEN '5' THEN 'PA'
				 WHEN '6' THEN 'AS'
				 WHEN '7' THEN 'MS'
				 WHEN '8' THEN 'NU'
				 WHEN '9' THEN 'NV'
				 WHEN '10' THEN 'CD'
				 WHEN '11' THEN 'SC'
				 WHEN '12' THEN 'PE' 
				 WHEN '13' THEN 'PT'
				 WHEN '14' THEN 'DE'
				 WHEN '15' THEN 'SI' END AS [TIPO IDENTIFICACION],
A.IPCODPACI AS [IDENTIFICACION], 
I.IPNOMCOMP AS [PACIENTE],
CAST (I.IPFECNACI AS DATE) [FECHA DE NACIMIENTO],
cast((datediff(m, I.IPFECNACI, GETDATE())/12) as varchar) + ' Años ' + cast((DATEDIFF(m, I.IPFECNACI, GETDATE())%12) as varchar) + ' Meses' as EDAD,
CASE I.IPSEXOPAC WHEN '1' THEN 'MASCULINO' ELSE 'FEMENINO' END AS [SEXO],
I.IPTELEFON AS [TELEFONO FIJO], 
I.IPTELMOVI AS [TELEFONO MOVIL], 
I.IPDIRECCI AS DIRECCION,
EA.CODE + ' - ' + EA.NAME AS [ENTIDAD ADMINISTRADORA],
GA.CODE [CODIGO GRUPO ATENCION], 
GA.CODE + ' - ' + GA.NAME [GRUPO ATENCION],
CASE GA.LIQUIDATIONTYPE WHEN 1 THEN 'PAGO POR SERVICIOS'
						WHEN 2 THEN 'PGP'
						WHEN 3 THEN 'FACTURA GLOBAL'
						WHEN 4 THEN 'CAPITACION GLOBAL'
						WHEN 5 THEN 'CONTROL'END [TIPO CONTRATO],
A.[TIPO SOLICITUD],
'IMAGENES' [TIPO ORDEN],
A.UFUCODIGO + ' - ' + RTRIM(C.UFUDESCRI) AS [UNIDAD FUNCIONAL],
ING.CODCAMACT AS CAMA,
A.NUMINGRES AS INGRESO,
A.NUMEFOLIO AS FOLIO,
A.CODSERIPS [CODIGO CUPS],
CG.CODE + '-' + CG.NAME [GRUPO],
CSG.CODE + '-' + CSG.NAME [SUBGRUPO],
RTRIM(B.DESSERIPS) AS [DESCRIPCION SERVICIO],
ISNULL(CD.CODE + ' - ' + CD.NAME, '') [DESCRIPCION RELACIONADA],
/*IN V3*/CAST(A.FECORDMED AS DATE) AS [FECHA DE SOLICITUD ORDEN],
CAST(CAST(A.FECORDMED AS TIME) AS varchar(8)) [HORA DE SOLICITUD ORDEN],/*FN V3*/
A.ESTADO,
1 AS CANTIDAD,
PRO.CODPROSAL AS [ID PROFESIONAL], 
PRO.NOMMEDICO AS PROFESIONAL,
ESPMED.DESESPECI AS ESPECIALIDAD,
A.OBSERVACION,
CASE A.ESTSERIPS WHEN 7 THEN NULL ELSE DIAG.CODDIAGNO END AS CIE10, 
CASE A.ESTSERIPS WHEN 7 THEN NULL ELSE DIAG.NOMDIAGNO END AS DIAGNOSTICO,
CASE ESTA.ESTADIO WHEN 0 THEN 'ESTADIO CLÍNICO (EC) 0 (TUMOR IN SITU)'
				  WHEN 1 THEN 'EC I O 1'
				  WHEN 2 THEN 'EC IA O 1A'
				  WHEN 3 THEN 'EC IA1'
				  WHEN 4 THEN 'EC IA2'
				  WHEN 5 THEN 'EC IB O 1B'
				  WHEN 6 THEN 'EC IB1'
				  WHEN 7 THEN 'EC IB2'
				  WHEN 8 THEN 'EC IC O 1C'
				  WHEN 9 THEN 'EC IS O 1S'
				  WHEN 10 THEN 'EC II O 2'
				  WHEN 11 THEN 'EC IIA O 2A'
				  WHEN 12 THEN 'EC IIA1'
				  WHEN 13 THEN 'EC IIA2'
				  WHEN 14 THEN 'EC IIB O 2B'
				  WHEN 15 THEN 'EC IIC O 2C'
				  WHEN 16 THEN 'EC III O 3'
				  WHEN 17 THEN 'EC IIIA O 3A'
				  WHEN 18 THEN 'EC IIIB O 3B'
				  WHEN 19 THEN 'EC IIIC O 3C'
				  WHEN 20 THEN 'EC IV O 4'
				  WHEN 21 THEN 'EC IVA O 4A'
				  WHEN 22 THEN 'EC IVB O 4B'
				  WHEN 23 THEN 'EC IVC O 4C'
				  WHEN 24 THEN 'EC 4S (PARA NEUROBLASTOMA)'
				  WHEN 25 THEN 'EC  V O 5'
				  WHEN 26 THEN 'EC ESTADIO IAB'
				  WHEN 55 THEN 'PERSONA CON ASEGURAMIENTO (RÉGIMEN SUBSIDIADO O CONTRIBUTIVO Y QUE NO SON PPNA) QUE RECIBIÓ SERVICIOS DE SALUD POR PARTE DEL ENTE TERRITORIALDURANTE EL PERIODO DE REPORTE'
				  WHEN 93 THEN 'SIN INFORMACIÓN DE ESTADIFICACIÓN EN HISTORIA CLÍNICA'
				  WHEN 98 THEN 'NO APLICA (ES CÁNCER DE PIEL BASOCELULAR, ES CÁNCER HEMATOLÓGICO O ES CÁNCER EN SNC, EXCEPTO NEUROBLASTOMA)'
				  WHEN 99 THEN 'DESCONOCIDO, EL DATO DE ESTA VARIABLE NO SE ENCUENTRA DESCRITO EN LOS SOPORTES CLÍNICOS' ELSE ''END  AS ESTADIO,
IIF(G.CODGRUPO IS NULL, 'NO', 'SI') CUBIERTO, 
ISNULL(G.CONTRATADO, 'NO') CONTRATADO, 
ISNULL(G.COTIZADO, 'NO') COTIZADO, 
CAST(A.FECRECEXA AS DATE) AS [FECHA DE TOMA IMAGEN],
/*IN V3*/CAST(CAST(A.FECRECEXA AS time) as varchar(8)) AS [HORA DE TOMA IMAGEN],/*FN V3*/
CAST(A.FECTRASER AS DATE)[FECHA DE RESULTADO],
/*INV3*/CAST(CAST (A.FECTRASER AS TIME) AS varchar(8)) [HORA DE RESULTADO],
DATEDIFF(HOUR,A.FECRECEXA,A.FECTRASER) AS [TOMA VS RESULTADO H],
DATEDIFF(HOUR,A.FECORDMED,A.FECTRASER) AS [SOLICITUD VS RESULTADO H],/*FN V3*/
--IN V4
RTRIM(PROVAL.CODPROSAL)+' - '+PROVAL.NOMMEDICO AS [VALIDADOR TRANCRIPCION],
A.FECVALSER AS [FECHA VALIDACION],
RTRIM(PROLEC.CODPROSAL)+' - '+PROLEC.NOMMEDICO AS [PROFESIONAL LECTURA],
A.FECHLECT AS [FECHA LECTURA],
--FN V4
A.NOMARCIMG AS [NOMBRE ARCHIVO],
CAST(A.FECORDMED AS date) AS 'FECHA BUSQUEDA',
YEAR(A.FECORDMED) AS 'AÑO BUSQUEDA',
MONTH(A.FECORDMED) AS 'MES BUSQUEDA',
CONCAT(FORMAT(MONTH(A.FECORDMED), '00') ,' - ', 
CASE MONTH(A.FECORDMED) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
CTE_IMAGENES A LEFT OUTER JOIN
dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS INNER JOIN
dbo.INUNIFUNC C ON A.UFUCODIGO=C.UFUCODIGO INNER JOIN
DBO.ADCENATEN E ON A.CODCENATE = E.CODCENATE INNER JOIN
CONTRACT.CUPSENTITY AS CUPS ON CUPS.CODE = B.CODSERIPS INNER JOIN
CONTRACT.CUPSSUBGROUP AS CSG ON CSG.ID = CUPS.CUPSSUBGROUPID INNER JOIN
CONTRACT.CUPSGROUP AS CG ON CG.ID = CSG.CUPSGROUPID LEFT JOIN
CONTRACT.CUPSENTITYCONTRACTDESCRIPTIONS CECD ON CECD.ID = A.IDDESCRIPCIONRELACIONADA LEFT JOIN
CONTRACT.CONTRACTDESCRIPTIONS CD ON CD.ID = CECD.CONTRACTDESCRIPTIONID INNER JOIN
DBO.INPACIENT I ON A.IPCODPACI = I.IPCODPACI INNER JOIN
DBO.INPROFSAL PRO ON A.CODPROSAL = PRO.CODPROSAL INNER JOIN
DBO.HCHISPACA HIS ON A.NUMINGRES = HIS.NUMINGRES AND A.NUMEFOLIO = HIS.NUMEFOLIO INNER JOIN
DBO.INESPECIA AS ESPMED ON ESPMED.CODESPECI = HIS.CODESPTRA INNER JOIN
DBO.INDIAGNOS AS DIAG ON DIAG.CODDIAGNO = HIS.CODDIAGNO LEFT JOIN
DBO.ADINGRESO AS ING ON ING.NUMINGRES = A.NUMINGRES LEFT JOIN
CONTRACT.CAREGROUP AS GA ON GA.ID = ING.GENCAREGROUP LEFT JOIN


CONTRACT.HEALTHADMINISTRATOR AS EA ON EA.ID = ING.GENCONENTITY LEFT JOIN
-- IN V2 DBO.HCORDIMAG D ON A.Id=D.AUTO AND A.ESTSERIPS in (2,3,4) and A.FECRECEXA is null LEFT JOIN --FN V2
DBO.INDIAGNOP AS EST ON A.IPCODPACI = EST.IPCODPACI AND A.NUMINGRES = EST.NUMINGRES
													AND EST.NUMEFOLIO = A.NUMEFOLIO
													AND EST.ESTADIO IS NOT NULL LEFT JOIN     
CTE_CONTRATOS_GRUPO AS G ON G.CODGRUPO = GA.CODE AND G.CUPS = A.CODSERIPS
												 AND A.IDDESCRIPCIONRELACIONADA = G.IDRELACION LEFT JOIN
CTE_ESTADIO ESTA ON ING.IPCODPACI = ESTA.PACIENTE LEFT JOIN
DBO.INPROFSAL PROVAL ON A.CODPROVAL=PROVAL.CODPROSAL LEFT JOIN
DBO.INPROFSAL PROLEC ON A.MEDREALEC=PROLEC.CODPROSAL
--WHERE
--PROVAL.CODPROSAL IS NOT NULL
