-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_V2_FAC_REPORTE_TERAPIAS_POR_RECONOCER_URG
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE  VIEW REPORT.View_V2_FAC_REPORTE_TERAPIAS_POR_RECONOCER_URG
AS

WITH CTE_TERAPIAS_UNICOS
----CTE PARA IDENTIFICAR LOS INGRESOS UNICOS DE TERAPIAS QUE ESTAN PENDIENTES DE RECONOCER - URGENCIAS
AS
(
    SELECT DISTINCT  ING.NUMINGRES ,ING.IPCODPACI,ING.IESTADOIN
   	FROM dbo.HCPROCTER A 
	INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
	INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES =A.NUMINGRES 
	INNER JOIN DBO.INUNIFUNC AS FUN ON FUN.UFUCODIGO =A.UFUCODIGO 
	WHERE ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER IS NULL AND FUN.UFUTIPUNI ='1'--ING.UFUCODIGO in ('1111001','1113008','1113009')
  UNION ALL
	SELECT DISTINCT ING.NUMINGRES,ING.IPCODPACI,ING.IESTADOIN 
	 FROM dbo.HCPROCTER A 
	 INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
	 INNER JOIN DBO.INUNIFUNC AS FUN ON FUN.UFUCODIGO =A.UFUCODIGO
	 INNER JOIN dbo.HCINGRESORECNAC INGMH  on a.NUMINGRES = INGMH .NUMINGRESHIJO
	 INNER JOIN dbo.HCRECINAC RN  on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	 INNER JOIN dbo.ADINGRESO AS ING  on ING.NUMINGRES = INGMH.NUMINGRESHIJO 
    WHERE ing.IESTADOIN in (' ','P') AND A.GENSERVICEORDER IS NULL AND  FUN.UFUTIPUNI ='1'--ING.UFUCODIGO in ('1111001','1113008','1113009')
),
CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
AS
(
    SELECT EGR.IPCODPACI ,EGR.NUMINGRES,EGR.FECINIEST ,EGR.FECFINEST ,EGR.CODICAMAS,CAM.NUMCAMHOS ,FUN.UFUDESCRI  ,FUN.UFUTIPUNI  
	FROM CHREGESTA EGR with (nolock)
	INNER JOIN 
	(
	   SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR with (nolock)
	   INNER JOIN CTE_TERAPIAS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G  ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM with (nolock) ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),
CTE_EGRESO_CAMA
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO  
FROM CHREGEGRE EGR
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECEGRESO) EGRESO 
 FROM CHREGEGRE EGR with (nolock) 
 INNER JOIN CTE_TERAPIAS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.EGRESO =EGR.FECEGRESO 
),
CTE_ORDENES_CON_TERAPIAS_CARGADAS
---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA
AS
( 
SELECT RC.AdmissionNumber,G.CUPS ,G.CANTIDAD  FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN
(
SELECT RC.AdmissionNumber ,CUPS.Code CUPS ,CUPS.Description,SUM(SOD.InvoicedQuantity) CANTIDAD   
FROM Billing .RevenueControlDetail AS RCD WITH (NOLOCK)
INNER JOIN BILLING.REVENUECONTROL AS RC WITH (NOLOCK) ON RCD.REVENUECONTROLID = RC.ID
INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD WITH (NOLOCK) ON RCD.ID = SODD.REVENUECONTROLDETAILID AND RCD.STATUS IN ('1','2', '3')
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD WITH (NOLOCK) ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN CTE_TERAPIAS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =RC.AdmissionNumber  
INNER JOIN Contract .CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id =SOD.CUPSEntityId AND CUPS.ServiceType =''
INNER JOIN Contract .IPSService AS IPS WITH (NOLOCK) ON IPS.Id =SOD.IPSServiceId
GROUP BY RC.AdmissionNumber ,CUPS.Code ,CUPS.Description
) AS G ON G.AdmissionNumber =RC.AdmissionNumber
),
CTE_DATOS_TERAPIAS
---CTE QUE ME TRAE LOS DATOS DE LAS TERAPIAS DE FORMA AGRUPADA
AS
(
SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],
        HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',MIN(A.FECHISPAC) 'FECHA REALIZADO MINIMA',
		MAX(A.FECHISPAC) 'FECHA REALIZADO MAXIMA'
    	FROM dbo.HCPROCTER A 
	    INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
		INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES =A.NUMINGRES
		INNER JOIN DBO.INUNIFUNC AS FUN ON FUN.UFUCODIGO =A.UFUCODIGO 
		INNER JOIN DBO.INPACIENT AS P ON P.IPCODPACI =A.IPCODPACI 
		INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	    INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id 
		INNER JOIN
	    (
	    SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN
    	FROM dbo.HCPROCTER A 
	    INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
		INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES =A.NUMINGRES
		INNER JOIN DBO.INUNIFUNC AS FUN ON FUN.UFUCODIGO =A.UFUCODIGO 
		INNER JOIN DBO.INPACIENT AS P ON P.IPCODPACI =A.IPCODPACI
		INNER JOIN CTE_TERAPIAS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =ING.NUMINGRES
		WHERE FUN.UFUTIPUNI ='1'--ING.UFUCODIGO in ('1111001','1113008','1113009')
	    GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
		) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =A.CODSERIPS
	WHERE  A.GENSERVICEORDER IS NULL AND FUN.UFUTIPUNI ='1'--ING.UFUCODIGO in ('1111001','1113008','1113009')
	GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name , CG.Name ,ING.IFECHAING 
   UNION ALL
    SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS CANSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],
	HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',MIN(A.FECHISPAC) 'FECHA REALIZADO MINIMA',
		MAX(A.FECHISPAC) 'FECHA REALIZADO MAXIMA'
	 FROM dbo.HCPROCTER A 
	 INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
	 INNER JOIN DBO.INUNIFUNC AS FUN ON FUN.UFUCODIGO =A.UFUCODIGO
	 INNER JOIN dbo.HCINGRESORECNAC INGMH  on a.NUMINGRES = INGMH .NUMINGRESHIJO
	 INNER JOIN dbo.HCRECINAC RN  on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	 INNER JOIN dbo.ADINGRESO AS ING  on ING.NUMINGRES = INGMH.NUMINGRESHIJO
	 INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI
	 INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	 INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id 
	 INNER JOIN
	(
	    SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(A.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN
		 FROM dbo.HCPROCTER A 
	     INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
		 INNER JOIN DBO.INUNIFUNC AS FUN ON FUN.UFUCODIGO =A.UFUCODIGO
	     INNER JOIN dbo.HCINGRESORECNAC INGMH  on a.NUMINGRES = INGMH .NUMINGRESHIJO
	     INNER JOIN dbo.HCRECINAC RN  on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	     INNER JOIN dbo.ADINGRESO AS ING  on ING.NUMINGRES = INGMH.NUMINGRESHIJO
	     INNER JOIN DBO.INPACIENT AS P with (nolock) ON P.IPCODPACI =A.IPCODPACI
		 INNER JOIN CTE_TERAPIAS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =ING.NUMINGRES
		 WHERE FUN.UFUTIPUNI ='1'--ING.UFUCODIGO in ('1111001','1113008','1113009')
	    GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN
	) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =A.CODSERIPS
	WHERE  A.GENSERVICEORDER IS NULL AND FUN.UFUTIPUNI ='1'--ING.UFUCODIGO in ('1111001','1113008','1113009')
	GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,A.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name , CG.Name ,ING.IFECHAING 
),

--IN V2
--SE CREA EL CTE DE JUSTIFICACIONES, PARA QUE ME RETORNE TODOS LOS ORDENAMIENTOS CON ALGUNA JUSTIFIACION.
CTE_RECONOCIMIENTOS_TERAPIAS AS
(
SELECT ING.NUMINGRES,ing.IESTADOIN,ING.[FECHA INGRESO] ,ING.ENTIDAD ,ING.[GRUPO ATENCION]  ,ING.IPCODPACI ,ING.IPNOMCOMP ,ING.CODSERIPS ,ING.DESSERIPS,ING.[CANTIDAD ORDENADA]  ,ING.CANSERIPS,CAM.UFUDESCRI  ,
CAM.NUMCAMHOS,EGR.FECEGRESO,CAR.CUPS 'CUPS CARGADO',CAR.CANTIDAD 'CANTIDAD CARGADA',ING.[FECHA REALIZADO MINIMA] ,ING.[FECHA REALIZADO MAXIMA]      
FROM CTE_DATOS_TERAPIAS ING with (nolock) 
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM with (nolock) ON ING.NUMINGRES =CAM.NUMINGRES
LEFT JOIN CTE_EGRESO_CAMA EGR with (nolock) ON EGR.NUMINGRES =ING.NUMINGRES
LEFT JOIN CTE_ORDENES_CON_TERAPIAS_CARGADAS CAR with (nolock) ON CAR.AdmissionNumber =ING.NUMINGRES AND CAR.CUPS =ING.CODSERIPS 
WHERE ING.[CANTIDAD ORDENADA] <>ISNULL(CAR.CANTIDAD,0)  AND ING.[CANTIDAD ORDENADA] >ISNULL(CAR.CANTIDAD,0)
--AND CAM.NUMCAMHOS LIKE 'U%' OR CAM.NUMCAMHOS LIKE 'O%' OR CAM.NUMCAMHOS LIKE 'SRE%'
),

CTE_JUSTIFICACIONES AS
(
SELECT DISTINCT IM.NUMINGRES,--IM.NUMEFOLIO,
IM.CODSERIPS,JUS.Code
FROM 
[Billing].[BillingJustificationControl] JUS INNER JOIN
[Billing].[AccountControlJustification] CON ON JUS.ID=JustificationId INNER JOIN
dbo.HCPROCTER IM ON CON.EntityId=IM.CODCONSEC AND CON.EntityName='HCPROCTER'
)
-- SE CREA LA NUEVA CONSULTA UNIENDO EL CTE CON EL CTE_JUSTIFICACIONES PARA QUE NO ME MUESTRE LAS ORDENES QUE SE ENCUENTRAN JUSTIFICADAS
SELECT TE.* 
FROM 
CTE_RECONOCIMIENTOS_TERAPIAS TE LEFT JOIN
CTE_JUSTIFICACIONES JUS ON TE.NUMINGRES=JUS.NUMINGRES AND TE.CODSERIPS=JUS.CODSERIPS
WHERE JUS.Code IS NULL AND TE.UFUDESCRI in ('PEDIATRIA URGENCIAS','URGENCIAS ADULTOS','PABELLON URGENCIAS ADULTOS','GINECOBSTETRICIA URGENCIAS')
--FN V2


