-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewPendientesDeOrdenesTotal
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [Report].[ViewPendientesDeOrdenesTotal] as

WITH CTE_PND_ORDE AS
 (
  select PAR.EntityName,PAR.[ORDENE DE SERVICIO] ,par.IDENTIFICACION ,par.PACIENTE  ,PAR.INGRESO,PAR.[FECHA ORDENAMIENTO] 'FECHA SERVICIO'  ,PAR.[CODIGO CUPS] ,PAR.[PROCEDIMIENTO CUPS] ,PAR.ESTADO ,PAR.[FECHA LECTURA] 'FECHA REALIZACION',
  PAR.[ESTADO INGRESO] ,PAR.ADJUNTO ,PAR.[NRO FACTURA] ,PAR.[FECHA ALTA] 'FECHA ALTA'
  from [Report].ViewPendientesDeOrdenesParaclinicos as PAR 
  WHERE CAST(PAR.[FECHA ORDENAMIENTO] as date) BETWEEN CAST(DATEADD(m,-365,GETDATE()) AS DATE) AND CAST(GETDATE() AS DATE)

UNION ALL

SELECT 'PROCEDIMIENTOS QX' EntityName,PAR.[ORDENE DE SERVICIO],par.IDENTIFICACION ,par.PACIENTE  ,PAR.INGRESO,PAR.[FECHA SERVICIO] ,PAR.[CUPS REALIZADO] ,PAR.[PROCEDIMIENTO REALIZADO] ,'Procedimiento realizado' ESTADO ,PAR.[FECHA SERVICIO] 'FECHA REALIZACION',
PAR.ESTADO 'ESTADO INGRESO','' ADJUNTO, PAR.[NRO FACTURA] ,PAR.[ALTA MEDICA] 'FECHA ALTA'
from [Report].ViewPendientesDeOrdenesProcedimientosQx as PAR
  WHERE CAST(PAR.[FECHA SERVICIO] as date) BETWEEN CAST(DATEADD(m,-365,GETDATE()) AS DATE) AND CAST(GETDATE() AS DATE)

UNION ALL

SELECT 'PROCEDIMIENTOS NO QX' EntityName,PAR.[ORDENE DE SERVICIO],par.IDENTIFICACION ,par.PACIENTE  ,PAR.INGRESO,PAR.[FECHA REALIZACION] 'FECHA SERVICIO' ,PAR.[CUPS PROCEDIMIENTO]  [CUPS REALIZADO] ,PAR.PROCEDIMIENTO  [PROCEDIMIENTO REALIZADO] ,'Procedimiento realizado' ESTADO ,PAR.[FECHA REALIZACION]  'FECHA REALIZACION',
par.ESTADO 'ESTADO INGRESO','' ADJUNTO, PAR.[NRO FACTURA] ,PAR.[FECHA ALTA]  'FECHA ALTA'
from [Report].ViewPendientesDeOrdenesProcedimientosNoQx as PAR
  WHERE CAST (PAR.[FECHA REALIZACION] as date) BETWEEN CAST(DATEADD(m,-365,GETDATE()) AS DATE) AND CAST(GETDATE() AS DATE)

UNION ALL

SELECT 'TERAPIAS' EntityName,PAR.[ORDENE DE SERVICIO],par.IDENTIFICACION ,par.PACIENTE  ,PAR.INGRESO,PAR.[FECHA REALIZACION] 'FECHA SERVICIO' ,PAR.[CODIGO CUPS]  [CUPS REALIZADO] ,PAR.[PROCEDIMIENTO CUPS]   [PROCEDIMIENTO REALIZADO] ,'Procedimiento realizado' ESTADO ,PAR.[FECHA REALIZACION]  'FECHA REALIZACION',
par.ESTADO 'ESTADO INGRESO','' ADJUNTO, PAR.[NRO FACTURA] ,PAR.[FECHA ALTA]  'FECHA ALTA'
from [Report].ViewPendientesDeOrdenesTerapias as PAR
  WHERE CAST(PAR.[FECHA REALIZACION] as date) BETWEEN CAST(DATEADD(m,-365,GETDATE()) AS DATE) AND CAST(GETDATE() AS DATE)

UNION ALL

SELECT 'GASES' EntityName,PAR.[ORDENE DE SERVICIO],par.IDENTIFICACION ,par.PACIENTE  ,PAR.INGRESO,PAR.HORAINICIA  'FECHA SERVICIO' ,PAR.[CODIGO CUPS]  [CUPS REALIZADO] ,PAR.[PROCEDIMIENTO CUPS]   [PROCEDIMIENTO REALIZADO] ,'Procedimiento realizado' ESTADO ,PAR.HORAINICIA 'FECHA REALIZACION',
par.[ESTADO INGRESO],'' ADJUNTO, PAR.[NRO FACTURA] ,PAR.[FECHA ALTA]  'FECHA ALTA'
from [Report].ViewPendientesDeOrdenesGases as PAR
  WHERE CAST(PAR.HORAINICIA as date) BETWEEN CAST(DATEADD(m,-365,GETDATE()) AS DATE) AND CAST(GETDATE() AS DATE)

)

SELECT
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 *,
 IIF([FECHA ALTA] IS NULL,'NO','SI') 'CON ALTA',
 1 as 'CANTIDAD',
 CAST([FECHA SERVICIO] AS date) AS 'FECHA BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
 CTE_PND_ORDE

