-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewExternalConsultationTimes
-- Extracted by Fabric SQL Extractor SPN v3.9.0








    /*******************************************************************************************************************
Nombre: [Report].[ViewExternalConsultationTimes]
Tipo: Vista
Observacion:Mide la oportunidad de la consulta externa desde que el paciente llega a la institución hasta el final de la consulta, realizada por
			parte del profesional de la salud esta vista fue solicitada por San Jose
Profesional: Nilsson Galindo
Fecha:19-10-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico: Amira Gil Meneses
Fecha:22-01-2025
Observaciones: Se modifican los nombres de los campos adicionando Tiempo 1, Tiempo 2, Tiempo 3 y Oportunidad
-------------------------------------------------------------------------------------------------------------------------------------
Version 3
Persona que modifico:
Fecha:
Observaciones:
***********************************************************************************************************************************/
CREATE VIEW  [Report].[ViewExternalConsultationTimes] AS


WITH
CTE_AGENDAMIENTO AS
(
SELECT
ISNULL(AC.NUMINGRES,AGE.NUMINGRES) AS NUMINGRES,
AC.CODESPECI,
AC.CODACTMED,
AC.TIPSOLICITU,
AC.CODTIPCIT,
AC.CITAEXTRA,
AC.FECHORAIN,
AGE.IDHCHISPACA
FROM
dbo.AGASICITA AC
LEFT JOIN dbo.ADCONCOEX AGE ON AC.CODAUTONU=AGE.NUMCONCIT
--WHERE AC.CODESTCIT=1 AND (AC.NUMINGRES='186C211C19' OR AGE.NUMINGRES='186C211C19')
),

CTE_AGENDAMIENTO_GRUP AS
(
SELECT * FROM CTE_AGENDAMIENTO
WHERE NUMINGRES IS NOT NULL --AND NUMINGRES='9468E4EE07'
GROUP BY NUMINGRES,CODESPECI,CODACTMED,TIPSOLICITU,CODTIPCIT,CITAEXTRA,FECHORAIN,IDHCHISPACA
)

SELECT 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
CA.NOMCENATE AS [CENTRO DE ATENCION],
DOC.NOMBRE AS [TIPO IDENTIFICACION],
PAC.IPCODPACI AS IDENTIFICACION,
PAC.IPNOMCOMP AS [PACIENTE],
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END AS[GENERO DEL PACIENTE],
CAST(PAC.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
CASE ING.CODTIPPAC WHEN '1' THEN 'Maternas' 
				   WHEN '2' THEN 'Pediatrico'
				   WHEN '3' THEN 'Población general' 
				   WHEN '4' THEN 'Adulto mayor' 
				   WHEN '5' THEN 'Población general' END AS [TIPO DE PACIENTE], 
DATEDIFF(MONTH,PAC.IPFECNACI,ING.IFECHAING)/12 AS EDAD,
HEA.Code AS [CODIGO ENTIDAD],
HEA.Name AS [ENTIDAD],
CG.Name AS [GRUPO DE ATENCION],
ING.NUMINGRES AS INGRESO,
CASE AG.TIPSOLICITU WHEN 3 THEN 'Tratamientos Especiales'
					WHEN 2 THEN 'Apoyo Diagnostico'
					WHEN 1 THEN 'Cita Medica' END AS [TIPO AGENDAMIENTO],
INE.CODESPECI AS [CODIGO ESPECIALIDAD],
INE.DESESPECI AS ESPECIALIDAD,
ATV.DESACTMED AS [ACTIVIDAD AGENDAMIENTO],
CASE AG.CODTIPCIT WHEN '0' THEN 'PRIMERA VEZ' 
				  WHEN '1' THEN 'CONTROL' 
				  WHEN '2' THEN 'POS OPERATORIO' 
				  WHEN '3' THEN 'CITA WEB' END [TIPO DE CITA],
CASE AG.CITAEXTRA WHEN 1 THEN 'Si' ELSE 'No' END AS [CITA EXTRA],
AG.FECHORAIN AS [FECHA CITA],
ING.IFECHAING AS [TIEMPO 1_FECHA INGRESO],
FAC.CreationDate AS [TIEMPO 2_FECHA FACTURACION],
ISNULL(ATE1.FECHINIHI,ATE2.FECHINIHI) AS [TIEMPO 3_FECHA INICIAL ATENCION],
ISNULL(ATE1.FECHFINH,ATE2.FECINIATE) AS [FECHA FINAL ATENCION],
DATEDIFF(MINUTE,AG.FECHORAIN,ING.IFECHAING) AS [FECHA CITA VS FECHA INGRESO (MIN)],
DATEDIFF(MINUTE,ING.IFECHAING,FAC.CreationDate) AS [FECHA INGRESO VS FECHA FACTURA (MIN)],
DATEDIFF(MINUTE,ISNULL(ATE1.FECHINIHI,ATE2.FECHINIHI),ISNULL(ATE1.FECHFINH,ATE2.FECINIATE)) AS [INICIO ATENCIÓN VS FINAL ATENCIÓN (MIN)],
DATEDIFF(MINUTE,ING.IFECHAING,ISNULL(ATE1.FECHFINH,ATE2.FECINIATE)) AS [OPORTUNIDAD_FECHA INGRESO VS FINAL ATENCIÓN (MIN)]
FROM 
dbo.ADINGRESO ING
INNER JOIN dbo.ADCENATEN CA ON ING.CODCENATE = CA.CODCENATE
INNER JOIN dbo.INPACIENT PAC ON ING.IPCODPACI=PAC.IPCODPACI
INNER JOIN dbo.ADTIPOIDENTIFICA DOC ON PAC.IPTIPODOC=DOC.CODIGO
INNER JOIN CONTRACT.HEALTHADMINISTRATOR HEA ON ING.GENCONENTITY=HEA.Code 
INNER JOIN Contract.CareGroup CG ON ING.GENCAREGROUP=CG.Code
INNER JOIN CTE_AGENDAMIENTO_GRUP AG ON ING.NUMINGRES=AG.NUMINGRES
LEFT JOIN dbo.INESPECIA INE ON AG.CODESPECI=INE.CODESPECI
LEFT JOIN dbo.AGACTIMED AS ATV ON AG.CODACTMED=ATV.CODACTMED
LEFT JOIN Billing.ServiceOrder FAC ON ING.NUMINGRES=FAC.AdmissionNumber AND FAC.ID=(SELECT MIN(OD.ID) FROM Billing.ServiceOrder OD WHERE FAC.AdmissionNumber=OD.AdmissionNumber)
LEFT JOIN dbo.HCHISPACA HC ON AG.IDHCHISPACA=HC.ID
LEFT JOIN dbo.HCURGING1 ATE1 ON HC.NUMINGRES=ATE1.NUMINGRES AND HC.NUMEFOLIO=ATE1.NUMEFOLIO AND HC.IDETIPHIS='HCURGING1'
LEFT JOIN dbo.HCNOTEVO1 ATE2 ON HC.NUMINGRES=ATE2.NUMINGRES AND HC.NUMEFOLIO=ATE2.NUMEFOLIO AND HC.IDETIPHIS='HCNOTEVO1'
WHERE ING.TIPOINGRE=1 AND ING.IINGREPOR=2 --and ing.IPCODPACI in ('1073685306','52953364')
--and ing.NUMINGRES='9285404908'
--AND CAST(AG.FECHORAIN AS DATE) BETWEEN '2024-06-10' AND '2024-06-11'


