-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewTrazabilidadPacientesIngresados
-- Extracted by Fabric SQL Extractor SPN v3.9.0



----juan pablo robayo, ticket 16638  no dar soporte.
CREATE VIEW [Report].[ViewTrazabilidadPacientesIngresados]
as

WITH CTE_DX_SECUDANARIOS
AS
(
SELECT ROW_NUMBER () OVER (PARTITION BY IPCODPACI ORDER BY NUMINGRES) NUMERO ,CODDIAGNO,NUMEFOLIO, NUMINGRES,  IPCODPACI, CODDIAPRI
FROM INDIAGNOP 
WHERE CODDIAPRI=0

),

CTE_AMBULATORIO
AS
(
SELECT NUMINGRES, 
CASE CONESTADO WHEN 1 THEN 'No atendido'
WHEN 2 THEN 'Ausente/Anulada'
WHEN 3 THEN 'Atendido'
WHEN 4 THEN 'En Sala'
WHEN 5 THEN 'En Consultorio'
WHEN 6 THEN 'Atendido (Continúa en la unidad)' ELSE 'No atendido' END 'ESTADO ATENCION', IPCODPACI

FROM ADCONCOEX

),

CTE_HOSPITALIZADOS
AS
(
SELECT*FROM CHREGESTA

WHERE REGESTADO IN (1)
),

CTE_HISTORIAS
AS
(
SELECT ROW_NUMBER () OVER (PARTITION BY NUMINGRES ORDER BY FECHISPAC DESC) NUMERO ,NUMINGRES, IPCODPACI, FECHISPAC, CODDIAGNO, ID, CODESPTRA

FROM HCHISPACA
)


SELECT DISTINCT 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
TID.SIGLA AS TIPO,
ING.IPCODPACI 'DOC. PACIENTE', PAC.IPNOMCOMP 'NOMBRE PACIENTE', ING.NUMINGRES '# INGRESO', ISNULL(GRU.NAME,'NO REGISTRA') 'GRUPO DE ATENCION', HA.NAME 'ENTIDAD',
ISNULL(ACOM.IDACOMPAN,0) 'ID ACOMPAÑANTE',ISNULL(ACOM.PRINOMBRE+' '+ACOM.SEGNOMBRE+' '+ACOM.PRIAPELLI+' '+ACOM.SEGAPELLI,'SIN ACOMPAÑANTE') 'NOMBRE ACOMPAÑANTE',
CASE WHEN ING.TIPOINGRE = 2 THEN 'Hospitalario' ELSE 'Ambulatorio' END 'ÁMBITO DE ATENCIÓN',
ISNULL(HOS.FECINIEST,'1900-01-01') 'INICIO ESTANCIA', ISNULL(ESP.DESESPECI,'NO ATENDIDO') 'NOMBRE ESPECIALIDAD',FUN.UFUDESCRI 'UNIDAD ACTUAL', 
ISNULL(CAM.DESCCAMAS,AMA.DESCCAMAS) 'CAMA', CASE WHEN HIS.ID IS NOT NULL THEN 'Atendido'  WHEN HIS.ID IS NULL THEN AMB.[ESTADO ATENCION] ELSE 'No Atendido' END 'ESTADO ATENCION', 
ISNULL(CAST(FECHISPAC AS DATETIME),'1900-01-01') 'FECHA ATENCION', PAC.IPTELEFON 'TEL FIJO',PAC.IPTELMOVI 'TEL. MOVIL', HIS.CODDIAGNO 'COD. DX PRINCIAL', 
DIA.NOMDIAGNO 'NOMBRE DX1',
DX1.CODDIAGNO 'COD. DX SEC 1', 
DIA2.NOMDIAGNO 'NOMBRE DX2', 
DX2.CODDIAGNO 'COD. DX SEC 2', 
DIA3.NOMDIAGNO 'NOMBRE DX3', 
DX3.CODDIAGNO 'COD. DX SEC 3', 
DIA4.NOMDIAGNO 'NOMBRE DX4',
URG.TRIAGECLA AS TRIAGE,
CAST(ING.IFECHAING AS DATE) AS [FECHA BUSQUEDA]
FROM ADINGRESO ING 
LEFT JOIN CTE_HOSPITALIZADOS HOS ON HOS.NUMINGRES=ING.NUMINGRES
LEFT JOIN CTE_AMBULATORIO AMB ON AMB.NUMINGRES=ING.NUMINGRES
LEFT JOIN INPACIENT PAC ON PAC.IPCODPACI=ING.IPCODPACI
LEFT JOIN dbo.ADTIPOIDENTIFICA TID ON PAC.IPTIPODOC=TID.CODIGO
LEFT JOIN CTE_HISTORIAS HIS ON HIS.NUMINGRES=ING.NUMINGRES AND NUMERO IN (1)
LEFT JOIN INESPECIA ESP ON ESP.CODESPECI=HIS.CODESPTRA
LEFT JOIN CONTRACT.CAREGROUP GRU ON GRU.CODE=ING.GENCAREGROUP
LEFT JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.CODE=ING.GENCONENTITY
LEFT JOIN INUNIFUNC FUN ON FUN.UFUCODIGO=ING.UFUACTPAC
LEFT JOIN INDIAGNOS DIA ON DIA.CODDIAGNO=HIS.CODDIAGNO
LEFT JOIN CTE_DX_SECUDANARIOS DX1 ON DX1.NUMINGRES=HIS.NUMINGRES AND DX1.NUMERO=1
LEFT JOIN INDIAGNOS DIA2 ON DIA2.CODDIAGNO=DX1.CODDIAGNO
LEFT JOIN CTE_DX_SECUDANARIOS DX2 ON DX2.NUMINGRES=HIS.NUMINGRES AND DX2.NUMERO=2
LEFT JOIN INDIAGNOS DIA3 ON DIA3.CODDIAGNO=DX2.CODDIAGNO
LEFT JOIN CTE_DX_SECUDANARIOS DX3 ON DX3.NUMINGRES=HIS.NUMINGRES AND DX3.NUMERO=3
LEFT JOIN INDIAGNOS DIA4 ON DIA4.CODDIAGNO=DX3.CODDIAGNO
LEFT JOIN CHCAMASHO CAM ON CAM.CODICAMAS=HOS.CODICAMAS AND HOS.REGESTADO=1
LEFT JOIN CHCAMASHO AMA ON ING.CODCAMACT=AMA.CODICAMAS
LEFT JOIN ADACOMPAN ACOM ON ACOM.NUMINGRES=ING.NUMINGRES
LEFT JOIN dbo.ADTRIAGEU URG ON ING.NUMINGRES=URG.NUMINGRES
WHERE CAST(ING.IFECHAING AS DATE) BETWEEN CAST(GETDATE()-150 AS DATE) AND CAST(GETDATE() AS DATE)
--WHERE MONTH(ING.IFECHAING)=MONTH --AND ING.IESTADOIN IN ('','P')  AND HOS.CODESPECI IS NOT NULL

