-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewTrazabilidadImagenes
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [Report].[ViewTrazabilidadImagenes]
AS

WITH CTE_ANULACIONES
AS
(
SELECT IM.IPCODPACI,IM.NUMINGRES,IM.NUMEFOLIO, IM.UFUCODIGO, IM.CODSERIPS, IM.CODMOTANU,AN.DESMOTANU,IM.OBSERVACI, IM.FECANUIMG, IM.USUANUIMG,US.NOMUSUARI

FROM HCIMGANUL IM
LEFT JOIN HCMOANULB AN ON AN.CODMOTANU=IM.CODMOTANU
LEFT JOIN Segusuaru US ON US.CODUSUARI=IM.USUANUIMG
)


SELECT CAST(ORD.FECORDMED AS DATE) 'FECHA DE BUSQUEDA',ORD.UFUCODIGO 'COD. UF',FUN.UFUDESCRI 'UNIDAD FUNCIONAL ORDENA',ORD.IPCODPACI 'ID PACIENTE',PAC.IPNOMCOMP 'NOMBRE PACIENTE', ORD.NUMINGRES '# INGRESO', ORD.CODSERIPS 'CUPS',
CUPS.DESSERIPS 'SERVICIO',RELA.NAME 'DESCRIPCION RELACIONADA',ORD.CANSERIPS 'CANTIDAD', ORD.OBSSERIPS 'OBSERVACION DE LA ORDEN', 
CASE ORD.ESTSERIPS WHEN 1 THEN 'Solicitado'
WHEN 2 THEN 'Estudio Realizado'
WHEN 3 THEN 'Imagen Procesada'
WHEN 4 THEN 'Estudio Interpretado'
WHEN 5 THEN 'Remitido'
WHEN 6 THEN 'Anulado'
WHEN 7 THEN 'Extramural' END 'ESTADO', ORD.CODDIAGNO 'CIE-10',DIA.NOMDIAGNO 'DIAGNOSTICO',ORD.FECRECEXA 'FECHA DE TOMA', ORD.USURECEXA 'CODIGO',
CASE WHEN ORD.USURECEXA = PROF.CODPROSAL THEN PROF.NOMMEDICO ELSE CASE WHEN ORD.USURECEXA=PROF2.CODUSUARI THEN PROF2.NOMMEDICO END END 'NOMBRE USUARIO TOMA',
FECHLECT 'FECHA LECTURA',ORD.MEDREALEC 'COD. PROF. LECTURA',PROF3.NOMMEDICO 'NOMBRE PROFESIONAL LECTURA',ORD.LECTURA 'DESCRIPCION LECTURA', ORD.INTERPRET 'INTERPRETACION', 
ORD.CODPROINT 'COD. PROF. INTERPRETA',PROF4.NOMMEDICO 'PROFESIONAL INTERPRETA', ORD.NUMFOLINT 'FOLIO INTERPRETA', ANUL.FECANUIMG 'FECHA ANULACION',ANUL.USUANUIMG 'COD. USUARIO ANULA',
ANUL.NOMUSUARI 'NOMBRE USUARIO ANULA', ANUL.DESMOTANU 'MOTIVO DE ANULACION',ANUL.OBSERVACI 'OBSERVACION', ANUL.NUMEFOLIO 'FOLIO ANULACION' 

FROM HCORDIMAG ORD
INNER JOIN INPACIENT PAC ON PAC.IPCODPACI=ORD.IPCODPACI
INNER JOIN INUNIFUNC FUN ON FUN.UFUCODIGO=ORD.UFUCODIGO
INNER JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS=ORD.CODSERIPS
INNER JOIN INDIAGNOS DIA ON DIA.CODDIAGNO=ORD.CODDIAGNO
LEFT JOIN INPROFSAL PROF ON PROF.CODPROSAL=ORD.USURECEXA
LEFT JOIN INPROFSAL PROF2 ON PROF2.CODUSUARI=ORD.USURECEXA
LEFT JOIN INPROFSAL PROF3 ON PROF3.CODPROSAL=ORD.MEDREALEC
LEFT JOIN INPROFSAL PROF4 ON PROF4.CODPROSAL=ORD.CODPROINT
LEFT JOIN CTE_ANULACIONES ANUL ON ANUL.NUMINGRES=ORD.NUMINGRES AND ORD.CODSERIPS=ANUL.CODSERIPS AND ORD.FECORDMED<ANUL.FECANUIMG
LEFT JOIN CONTRACT.ContractDescriptions RELA ON RELA.ID=ORD.IDDESCRIPCIONRELACIONADA



