-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewNIIFServiciosTotal
-- Extracted by Fabric SQL Extractor SPN v3.9.0






CREATE VIEW [Report].[ViewNIIFServiciosTotal] AS
WiTH cte_total_niif as
 (
 SELECT 
	[ID_COMPANY],
	[NIT ENTIDAD],
	[ENTIDAD],
	[CODIGO GRUPO],
	[GRUPO DE ATENCION],
	[INGRESO],
	[FECHA INGRESO],
	[FECHA EGRESO],
	[TIPO IDENTIFICACION],
	[IDENTIFICACION],
	[PACIENTE],
	[ESTADO FACTURA],
	[NRO FACTURA],
	[FECHA FACTURA],
	[TOTAL FACTURA],
	[VR TOTAL DESCUENTO],
	[VR TOTAL ENTIDAD],
	[VR TOTAL CUOTA RECUPERACION],
	[CAB_ORD_NRO],
	[CAB_ORD_FECHA_ORDEN],
	[DET_ORD_TIPO],
	[FECHA DE SERVICIO],
	[HORA DE SERVICIO],
	[DET_ORD_GRUPO FACTURACION],
	[DET_ORD_GRUPO],
	[DET_ORD_SUBGRUPO],
	[DET_ORD_PRESENTACION],
	[DET_ORD_CUPS],
	[DET_ORD_DESCRIPCION_CUPS],
	[DET_ORD_CODIGO_SERVICIO/PRODUCTO],
	[DET_ORD_DESCRIPCION_SERVICIO/PRODUCTO],
	[DET_ORDQX_SUBCODIGO],
	[DET_ORDQX_SUBNOMBRE],
	[DET VISUALIZA FACTURA],
	[DET_ORD_PAQUETE],
	[DET_ORD_INCLUIDO_EN_PAQUETE],
	[DET_ORD_CUPS_PAQUETE],
	[DET_ORD_DESCRIPCION_CUPS_PAQUETE],
	[DET_ORD_TIPO_LIQUIDACION],
	[DET_ORD_CUPS_INCLUIDO],
	[DET_ORD_DESCRIPCION_CUPS_INCLUIDO],
	[DET_ORD_CODIGO_UNIDAD_FUNCIONAL],
	[DET_ORD_UNIDAD_FUNCIONAL_PRESTO_SERVICIO],
	[DET_ORD_COD_CENTRO_COSTO],
	[DET_ORD_CENTRO_COSTO],
	[DET_ORD_IDENTIFICACION_PROFESIONAL],
	[DET_ORD_PROFESIONAL],
	[DET_ORD_ESPECIALIDAD],
	[DET_ORD_CANTIDAD],
	[DET_ORD_VALOR_SERVICIO],
	[DET_ORD_VALOR_UNITARIO],
	[DET_ORD_VALOR_TOTAL],
	[DET_ORD_TECNOLOGIA_PBS],
	[FECHA ALTA MEDICA],
	[FECHA ANULACION],
	[CAMA ACTIVA],
	[ID_ORDE_DETALLE],
	[ID_FACTURA],
	[ID ENTIDAD],
	[TIPO REGISTRO],
	[FECHA SERVICIO BUSQUEDA],
	[FACTURADO],
	[AUTORIZACION SERVICIO],
	[AUTORIZACION],
	[NUMINGRES],
	[AMBITO DE INGRESO],
	[UNIDAD FUNCIONAL DE INGRESO],
	[UNIDAD FUNCIONAL DE EGRESO],
	[AMBITO DE EGRESO]
 FROM Report.ViewNIIFServiciosFacturados 
 UNION ALL
 SELECT 
 [ID_COMPANY],
	[NIT ENTIDAD],
	[ENTIDAD],
	[CODIGO GRUPO],
	[GRUPO DE ATENCION],
	[INGRESO],
	[FECHA INGRESO],
	[FECHA EGRESO],
	[TIPO IDENTIFICACION],
	[IDENTIFICACION],
	[PACIENTE],
	[ESTADO FACTURA],
	[NRO FACTURA],
	[FECHA FACTURA],
	[TOTAL FACTURA],
	[VR TOTAL DESCUENTO],
	[VR TOTAL ENTIDAD],
	[VR TOTAL CUOTA RECUPERACION],
	[CAB_ORD_NRO],
	[FECHA DE SERVICIO] AS [CAB_ORD_FECHA_ORDEN],
	[DET_ORD_TIPO],
	[FECHA DE SERVICIO],
	[HORA DE SERVICIO],
	[DET_ORD_GRUPO FACTURACION],
	[DET_ORD_GRUPO],
	[DET_ORD_SUBGRUPO],
	[DET_ORD_PRESENTACION],
	[DET_ORD_CUPS],
	[DET_ORD_DESCRIPCION_CUPS],
	[DET_ORD_CODIGO_SERVICIO/PRODUCTO],
	[DET_ORD_DESCRIPCION_SERVICIO/PRODUCTO],
	[DET_ORDQX_SUBCODIGO],
	[DET_ORDQX_SUBNOMBRE],
	[DET VISUALIZA FACTURA],
	[DET_ORD_PAQUETE],
	[DET_ORD_INCLUIDO_EN_PAQUETE],
	[DET_ORD_CUPS_PAQUETE],
	[DET_ORD_DESCRIPCION_CUPS_PAQUETE],
	[DET_ORD_TIPO_LIQUIDACION],
	[DET_ORD_CUPS_INCLUIDO],
	[DET_ORD_DESCRIPCION_CUPS_INCLUIDO],
	[DET_ORD_CODIGO_UNIDAD_FUNCIONAL],
	[DET_ORD_UNIDAD_FUNCIONAL_PRESTO_SERVICIO],
	[DET_ORD_COD_CENTRO_COSTO],
	[DET_ORD_CENTRO_COSTO],
	[DET_ORD_IDENTIFICACION_PROFESIONAL],
	[DET_ORD_PROFESIONAL],
	[DET_ORD_ESPECIALIDAD],
	[DET_ORD_CANTIDAD],
	[DET_ORD_VALOR_SERVICIO],
	[DET_ORD_VALOR_UNITARIO],
	[DET_ORD_VALOR_TOTAL],
	[DET_ORD_TECNOLOGIA_PBS],
	[FECHA ALTA MEDICA],
	[FECHA ANULACION],
	[CAMA ACTIVA],
	[ID_ORDE_DETALLE],
	[ID_FACTURA],
	[ID ENTIDAD],
	[TIPO REGISTRO],
	[FECHA SERVICIO BUSQUEDA],
	[FACTURADO],
	[AUTORIZACION SERVICIO],
	[AUTORIZACION],
	[NUMINGRES],
	[AMBITO DE INGRESO],
	[UNIDAD FUNCIONAL DE INGRESO],
	[UNIDAD FUNCIONAL DE EGRESO],
	[AMBITO DE EGRESO]
 FROM Report.ViewNIIFServiciosPendientes 
 )
SELECT
 *,
  CAST(nf.[FECHA SERVICIO BUSQUEDA] AS date) AS 'FECHA BUSQUEDA',
  YEAR(nf.[FECHA SERVICIO BUSQUEDA] ) AS 'AÑO BUSQUEDA',
  MONTH(nf.[FECHA SERVICIO BUSQUEDA]) AS 'MES BUSQUEDA',
  CONCAT(FORMAT(MONTH(nf.[FECHA SERVICIO BUSQUEDA]), '00') ,' - ', 
	   CASE MONTH(nf.[FECHA SERVICIO BUSQUEDA]) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
 cte_total_niif nf
