-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_V2_FAC_REPORTE_PROCEDIMIENTOS_QX_POR_RECONOCER
-- Extracted by Fabric SQL Extractor SPN v3.9.0





CREATE VIEW [Report].[View_V2_FAC_REPORTE_PROCEDIMIENTOS_QX_POR_RECONOCER]
AS

WITH CTE_PROCEDIMIENTO_QX_UNICOS
----CTE PARA IDENTIFICAR LOS PROCEDIMIENTOS QX POR RECONOCER EN LOS DOS AMBITOS
AS
(
SELECT DISTINCT A.NUMINGRES,A.IPCODPACI,ING.IESTADOIN,CASE ING.TIPOINGRE WHEN 1 THEN 'Ambulatorio' WHEN 2 THEN 'Hospitalario' END AMBITO--,C.CONSECUQX--,JUS.CODE,CON.ID
	FROM dbo.HCQXINFOR A with (nolock)
	INNER JOIN DBO.ADINGRESO AS ING with (nolock) ON ING.NUMINGRES =A.NUMINGRES 
	INNER JOIN dbo.INPACIENT P with (nolock) ON a.IPCODPACI = P.IPCODPACI 
	INNER JOIN dbo.HCQXREALI C with (nolock) ON A.IPCODPACI=C.IPCODPACI AND A.NUMINGRES=C.NUMINGRES AND A.NUMEFOLIO=C.NUMEFOLIO 
	--LEFT JOIN [Billing].[AccountControlJustification] CON with (nolock) ON CON.EntityId=C.CONSECUQX  AND CON.EntityName='HCQXREALI'
	--LEFT JOIN [Billing].[BillingJustificationControl] JUS ON JUS.ID=CON.JustificationId	AND JUS.SkipClearance=1
	WHERE C.GENSERVICEORDER IS NULL AND  ing.IESTADOIN in (' ','P') --AND con.id IS NULL--and A.NUMINGRES ='65839'
  UNION ALL
SELECT DISTINCT A.NUMINGRES ,A.IPCODPACI,ING.IESTADOIN,CASE ING.TIPOINGRE WHEN 1 THEN 'Ambulatorio' WHEN 2 THEN 'Hospitalario' END AMBITO--,C.CONSECUQX--,JUS.CODE,CON.ID
   	FROM dbo.HCQXINFOR A with (nolock)
	INNER JOIN dbo.HCINGRESORECNAC INGMH  with (nolock) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	INNER JOIN dbo.HCRECINAC RN  with (nolock) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	INNER JOIN  dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO 
	INNER JOIN dbo.HCQXREALI C with (nolock) ON A.IPCODPACI=C.IPCODPACI AND A.NUMINGRES=C.NUMINGRES AND A.NUMEFOLIO=C.NUMEFOLIO 
	--LEFT JOIN [Billing].[AccountControlJustification] CON with (nolock) ON CON.EntityId=C.CONSECUQX  AND CON.EntityName='HCQXREALI'
	--LEFT JOIN [Billing].[BillingJustificationControl] JUS ON JUS.ID=CON.JustificationId	AND JUS.SkipClearance=1
	WHERE C.GENSERVICEORDER IS NULL AND ing.IESTADOIN in (' ','P')  --AND con.id IS NULL--and A.NUMINGRES ='65839'
),

CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO EN PENDIENTE DE RECONOCER
AS
(
    SELECT EGR.IPCODPACI ,EGR.NUMINGRES,EGR.FECINIEST ,EGR.FECFINEST ,EGR.CODICAMAS,CAM.NUMCAMHOS ,FUN.UFUDESCRI  ,FUN.UFUTIPUNI  
	FROM CHREGESTA EGR with (nolock)
	INNER JOIN 
	(
	   SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR with (nolock)
	   INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G ON G.ID =EGR.ID
	INNER JOIN CHCAMASHO AS CAM with (nolock) ON CAM.CODICAMAS =EGR.CODICAMAS 
	INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAM.UFUCODIGO =FUN.UFUCODIGO 
),
CTE_EGRESO_CAMA
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA EN PENDIENTE DE RECONOCER
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO  
FROM CHREGEGRE EGR
INNER JOIN 
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECEGRESO) EGRESO 
 FROM CHREGEGRE EGR 
 INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.EGRESO =EGR.FECEGRESO 
),

CTE_ORDENES_CON_QX_CARGADAS
---CTE PARA IDENTIFICAR SI EL CUPS YA ESTA COBRADO DE FORMA AGRUPADA EN PENDIENTE DE RECONOCER
AS
( 
SELECT RC.AdmissionNumber,G.CUPS ,G.CANTIDAD  FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN
(
SELECT RC.AdmissionNumber ,CUPS.Code CUPS ,SUM(SOD.InvoicedQuantity) CANTIDAD FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS PRO ON RC.AdmissionNumber =PRO.NUMINGRES
INNER JOIN Billing .RevenueControlDetail AS RCD WITH (NOLOCK) ON RC.Id =RCD.RevenueControlId 
INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD WITH (NOLOCK) ON RCD.ID = SODD.REVENUECONTROLDETAILID 
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD WITH (NOLOCK) ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN Contract .CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id =SOD.CUPSEntityId 
WHERE RCD.STATUS IN ('1','2', '3') AND CUPS.ServiceType IN (4,5)
GROUP BY RC.AdmissionNumber ,CUPS.Code 
) AS G ON G.AdmissionNumber =RC.AdmissionNumber
),
CTE_INGRESO_CON_QX_CARGADAS
---CTE PARA IDENTIFICAR SI EL INGRESO TIENE ALGUN CARGUE DE CUPS DE CIRUGIA
AS
( 
SELECT RC.AdmissionNumber,G.CANTIDAD  FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN
(
SELECT RC.AdmissionNumber ,SUM(SOD.InvoicedQuantity) CANTIDAD FROM BILLING.REVENUECONTROL AS RC WITH (NOLOCK)
INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS PRO ON RC.AdmissionNumber =PRO.NUMINGRES
INNER JOIN Billing .RevenueControlDetail AS RCD WITH (NOLOCK) ON RC.Id =RCD.RevenueControlId 
INNER JOIN Billing .SERVICEORDERDETAILDISTRIBUTION AS SODD WITH (NOLOCK) ON RCD.ID = SODD.REVENUECONTROLDETAILID 
INNER JOIN BILLING.SERVICEORDERDETAIL AS SOD WITH (NOLOCK) ON SODD.SERVICEORDERDETAILID = SOD.ID
INNER JOIN Contract .CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id =SOD.CUPSEntityId 
WHERE RCD.STATUS IN ('1','2', '3') AND CUPS.ServiceType IN (4,5)
GROUP BY RC.AdmissionNumber  
) AS G ON G.AdmissionNumber =RC.AdmissionNumber
),

CTE_DATOS_PROCEDIMIENTOS_QX
AS
(
SELECT ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(C.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS CANSERIPS ,G.IESTADOIN,G.[CANTIDAD ORDENADA] ,
    HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',G.AMBITO,V.DESVIAABO,PRO.NOMMEDICO 'CIRUJANO',CAST(A.FECHORINI AS DATE) 'FECHA CIRUGIA'
	FROM dbo.HCQXINFOR A 
	INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES =A.NUMINGRES 
	INNER JOIN dbo.INPACIENT P on a.IPCODPACI = P.IPCODPACI 
	INNER JOIN dbo.HCQXREALI C ON A.IPCODPACI=C.IPCODPACI AND A.NUMINGRES=C.NUMINGRES AND A.NUMEFOLIO=C.NUMEFOLIO
	INNER JOIN dbo.INCUPSIPS B ON C.CODSERIPS=B.CODSERIPS
	INNER JOIN dbo.HCQXVIABO as V ON V.CODVIAABO =C.CODVIAABO
	INNER JOIN dbo.INPROFSAL as pro on pro.CODPROSAL =A.CODPROSAL 
	INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id
	INNER JOIN
	(
	    SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(C.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN,UNI.AMBITO ,V.DESVIAABO,
		PRO.NOMMEDICO 'CIRUJANO'
			FROM dbo.HCQXINFOR A 
	        INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES =A.NUMINGRES 
	        INNER JOIN dbo.INPACIENT P on a.IPCODPACI = P.IPCODPACI 
	        INNER JOIN dbo.HCQXREALI C ON A.IPCODPACI=C.IPCODPACI AND A.NUMINGRES=C.NUMINGRES AND A.NUMEFOLIO=C.NUMEFOLIO
			INNER JOIN dbo.INCUPSIPS B ON C.CODSERIPS=B.CODSERIPS
			INNER JOIN dbo.HCQXVIABO as V ON V.CODVIAABO =C.CODVIAABO 
			INNER JOIN dbo.INPROFSAL as pro on pro.CODPROSAL =A.CODPROSAL 
			INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS UNI ON UNI.NUMINGRES=ING.NUMINGRES
			GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,C.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN,UNI.AMBITO ,V.DESVIAABO,PRO.NOMMEDICO
	) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =C.CODSERIPS
	WHERE C.GENSERVICEORDER  IS NULL AND ing.IESTADOIN in (' ','P')
	GROUP BY ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,C.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name,CG.Name,ING.IFECHAING ,G.AMBITO ,V.DESVIAABO,
	PRO.NOMMEDICO,CAST(A.FECHORINI AS DATE)
UNION ALL
SELECT ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(C.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS CANSERIPS ,G.IESTADOIN,G.[CANTIDAD ORDENADA] ,
    HA.Name ENTIDAD, CG.Name 'GRUPO ATENCION',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',G.AMBITO ,V.DESVIAABO,PRO.NOMMEDICO 'CIRUJANO',CAST(A.FECHORINI AS DATE) 'FECHA CIRUGIA'
   	        FROM dbo.HCQXINFOR A with (nolock)
	        INNER JOIN dbo.HCINGRESORECNAC INGMH  with (nolock) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	        INNER JOIN dbo.HCRECINAC RN  with (nolock) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	        INNER JOIN  dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO 
	        INNER JOIN dbo.HCQXREALI C with (nolock) ON A.IPCODPACI=C.IPCODPACI AND A.NUMINGRES=C.NUMINGRES AND A.NUMEFOLIO=C.NUMEFOLIO 
			INNER JOIN dbo.HCQXVIABO as V ON V.CODVIAABO =C.CODVIAABO
			INNER JOIN dbo.INPROFSAL as pro on pro.CODPROSAL =A.CODPROSAL
		    INNER JOIN INPACIENT P ON P.IPCODPACI = ING.IPCODPACI
			INNER JOIN INCUPSIPS B ON C.CODSERIPS=B.CODSERIPS
	        INNER JOIN Contract .HealthAdministrator AS HA with (nolock) ON ING.GENCONENTITY =HA.Id 
	        INNER JOIN Contract .CareGroup AS CG with (nolock) ON ING.GENCAREGROUP =CG.Id
	        INNER JOIN
	(
	    SELECT ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,RTRIM(C.CODSERIPS) AS CODSERIPS,B.DESSERIPS,SUM(1) AS 'CANTIDAD ORDENADA',UNI.IESTADOIN,UNI.AMBITO ,V.DESVIAABO,
		PRO.NOMMEDICO 'CIRUJANO'
   	        FROM dbo.HCQXINFOR A with (nolock)
	        INNER JOIN dbo.HCINGRESORECNAC INGMH  with (nolock) ON a.NUMINGRES = INGMH .NUMINGRESHIJO
	        INNER JOIN dbo.HCRECINAC RN  with (nolock) ON INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	        INNER JOIN  dbo.ADINGRESO AS ING  with (nolock) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO 
	        INNER JOIN dbo.HCQXREALI C with (nolock) ON A.IPCODPACI=C.IPCODPACI AND A.NUMINGRES=C.NUMINGRES AND A.NUMEFOLIO=C.NUMEFOLIO 
			INNER JOIN dbo.HCQXVIABO as V ON V.CODVIAABO =C.CODVIAABO
			INNER JOIN dbo.INPROFSAL as pro on pro.CODPROSAL =A.CODPROSAL
		    INNER JOIN INPACIENT P ON P.IPCODPACI = ING.IPCODPACI
			INNER JOIN INCUPSIPS B ON C.CODSERIPS=B.CODSERIPS
			INNER JOIN CTE_PROCEDIMIENTO_QX_UNICOS UNI ON UNI.NUMINGRES=ING.NUMINGRES
			GROUP BY ING.NUMINGRES,A.IPCODPACI,P.IPNOMCOMP ,C.CODSERIPS,B.DESSERIPS,UNI.IESTADOIN,UNI.AMBITO ,V.DESVIAABO,PRO.NOMMEDICO
	) AS G ON G.NUMINGRES =ING.NUMINGRES AND G.CODSERIPS =C.CODSERIPS
	WHERE C.GENSERVICEORDER  IS NULL AND ing.IESTADOIN in (' ','P')
	GROUP BY ING.NUMINGRES,A.NUMEFOLIO,A.IPCODPACI,P.IPNOMCOMP ,C.CODSERIPS,B.DESSERIPS,G.IESTADOIN,G.[CANTIDAD ORDENADA],HA.Name,CG.Name,ING.IFECHAING,G.AMBITO ,V.DESVIAABO,
	PRO.NOMMEDICO,CAST(A.FECHORINI AS DATE)
),
CTE_QX_AMBITO
AS
(
SELECT DISTINCT ING.NUMINGRES ,ING.IDRADICACIONQX, case ing.ORIGENQX  when 1 THEN 'AMBULATORIA' WHEN 2 THEN 'HOSPITALARIA' ELSE 'HOSPITALARIA'  END AMBITO
FROM 
CTE_PROCEDIMIENTO_QX_UNICOS UNI
LEFT JOIN AGEPROGQX ING ON UNI.NUMINGRES=ING.NUMINGRES
),

CTE_PROCEDIMIENTOS_QX AS
(
SELECT ING.NUMINGRES,ING.NUMEFOLIO,ing.IESTADOIN,ING.[FECHA INGRESO],ISNULL(AMB.AMBITO,'HOSPITALARIA') 'AMBITO CIRUGIA' ,ING.ENTIDAD,ING.[GRUPO ATENCION],ING.IPCODPACI,ING.IPNOMCOMP,ING.CODSERIPS,ING.DESSERIPS,ING.[CANTIDAD ORDENADA],ING.CANSERIPS,
CAM.UFUDESCRI,CAM.NUMCAMHOS,EGR.FECEGRESO,'' [CUPS CARGADO] ,'' [CANTIDAD CARGADA], ING.DESVIAABO 'VIA DE ABORADAJE',ING.CIRUJANO ,ING.[FECHA CIRUGIA]
FROM CTE_DATOS_PROCEDIMIENTOS_QX ING
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA AS CAM ON ING.NUMINGRES =CAM.NUMINGRES
LEFT JOIN CTE_EGRESO_CAMA EGR ON EGR.NUMINGRES =ING.NUMINGRES
--LEFT JOIN CTE_ORDENES_CON_QX_CARGADAS CAR ON CAR.AdmissionNumber =ING.NUMINGRES AND CAR.CUPS =ING.CODSERIPS
--LEFT JOIN CTE_INGRESO_CON_QX_CARGADAS CAR2 ON CAR2.AdmissionNumber =ING.NUMINGRES 
LEFT JOIN CTE_QX_AMBITO AS AMB ON AMB.NUMINGRES =ING.NUMINGRES 
--WHERE CAR.CUPS  IS NULL   --AND CAR2.CANTIDAD IS NULL-- AND ING.NUMINGRES ='475'
),
--IN V2
--SE CREA EL CTE DE JUSTIFICACIONES, PARA QUE ME RETORNE TODOS LOS ORDENAMIENTOS CON ALGUNA JUSTIFIACION.
CTE_JUSTIFICACIONES AS
(
SELECT DISTINCT QX.NUMINGRES,QX.NUMEFOLIO,QX.CODSERIPS,JUS.Code
FROM 
[Billing].[BillingJustificationControl] JUS INNER JOIN
[Billing].[AccountControlJustification] CON ON JUS.ID=JustificationId INNER JOIN
dbo.HCQXREALI QX ON CON.EntityId=QX.CONSECUQX AND CON.EntityName='HCQXREALI'
where JUS.SkipClearance=1
)
-- SE CREA LA NUEVA CONSULTA UNIENDO EL CTE CON EL CTE_JUSTIFICACIONES PARA QUE NO ME MUESTRE LAS ORDENES QUE SE ENCUENTRAN JUSTIFICADAS
SELECT QX.* 
FROM 
CTE_PROCEDIMIENTOS_QX QX LEFT JOIN
CTE_JUSTIFICACIONES JUS ON QX.NUMINGRES=JUS.NUMINGRES AND QX.NUMEFOLIO=JUS.NUMEFOLIO AND QX.CODSERIPS=JUS.CODSERIPS
WHERE JUS.Code IS NULL
--FN V2
--ORDER BY QX.NUMINGRES ,QX.[FECHA INGRESO]
