-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewGestantes
-- Extracted by Fabric SQL Extractor SPN v3.9.0







    /*******************************************************************************************************************
Nombre: [Report].[ViewGestantes]
Tipo:Vista
Observacion:Informe sobre antecedentes gineco opstetricos y examen fisico
Profesional: Nilsson Miguel Galindo Lopez
Fecha:01-09-2022
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Vercion 1
Persona que modifico: Nilsson Galindo Lopez
Fecha:24-02-2023
Ovservaciones: Que no traiga información si las semanas de gestacion es igual a 0.0
--------------------------------------
Vercion 2
Persona que modifico:
Fecha:
***********************************************************************************************************************************/

CREATE view [Report].[ViewGestantes] as
WITH 
CTE_INGRESO_PROGRAMA AS
(
select
B.IPFECHACO,
B.NUMINGRES
from
dbo.AGASICITA A INNER JOIN
dbo.ADCONCOEX B ON A.CODAUTONU=B.NUMCONCIT AND A.CODACTMED='010' AND CODESTCIT NOT in (2,4,5) AND CONESTADO NOT IN ('1','2')
),
CTE_ELISA AS
(
--CONSULTA DE PRIMERA VEZ POR ENFERMERIA ASESORIA PRE Y POS VIH PRENATAL
SELECT
ROW_NUMBER ( )   
OVER (PARTITION BY IPCODPACI  order by FECHORAIN) 'NUMERO',
1 AS TIPO,
IPCODPACI,
FECHORAIN
FROM AGASICITA WHERE CODACTMED ='012'
UNION ALL
--CONSULTA DE PRIMERA VEZ POR MEDICINA GENERAL ASESORIA PRE Y POS VIH PRENATAL
SELECT
ROW_NUMBER ( )   
OVER (PARTITION BY IPCODPACI  order by FECHORAIN) 'NUMERO',
2 AS TIPO,
IPCODPACI,
FECHORAIN
FROM AGASICITA WHERE CODACTMED ='013'
UNION ALL
--CONSULTA DE PRIMERA VEZ POR PSICOLOGIA ASESORIA PRE Y POS VIH PRENATAL
SELECT
ROW_NUMBER ( )   
OVER (PARTITION BY IPCODPACI  order by FECHORAIN) 'NUMERO',
3 AS TIPO,
IPCODPACI,
FECHORAIN
FROM AGASICITA WHERE CODACTMED ='033'
),
CTE_LACTANTE AS
(
SELECT
ROW_NUMBER ( )   
OVER (PARTITION BY IPCODPACI  order by FECHORAIN) 'NUMERO',
IPCODPACI,
FECHORAIN
FROM AGASICITA WHERE CODACTMED ='121'
)


SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
PAC.IPCODPACI AS IDENTIFICACION,
CASE PAC.IPTIPODOC WHEN 1 THEN 'CC - CEDULA DE CIUDADANIA' 
				   WHEN 2 THEN 'CE - CEDULA DE EXTRANJERIA' 
				   WHEN 3 THEN 'TI - TARJETA DE IDENTIDAD' 
				   WHEN 4 THEN 'RC - REGISTRO CIVIL' 
				   WHEN 5 THEN 'PA - PASAPORTE' 
				   WHEN 6 THEN 'AS - ADULTO SIN IDENTIFICACION' 
				   WHEN 7 THEN 'MS - MENOR SIN IDENTIFICACION' 
				   WHEN 8 THEN 'NU - NUMERO UNICO DE IDENTIFICACIÒN' 
				   WHEN 9 THEN 'NV - CERTIFICADO NACIDO VIVO' 
				   WHEN 10 THEN 'CD - CARNET DIPLOMATICO' 
				   WHEN 11 THEN 'SC - SALVOCONDUCTO' 
				   WHEN 12 THEN 'PE - PERMISO ESPECIAL DE PERMANENCIA' ELSE 'OTRO' END [TIPO IDENTIFICACION],
PAC.IPNOMCOMP AS [NOMBRE COMPLETO],
PAC.IPPRINOMB AS [PRIMER NOMBRE],
PAC.IPSEGNOMB AS [SEGUNDO NOMBRE], 
PAC.IPPRIAPEL AS [PRIMER APELLIDO],
PAC.IPSEGAPEL AS [SEGUNDO APELLIDO],
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' ELSE 'FEMENINO' END [SEXO],
CAST(PAC.IPFECNACI AS DATE ) AS [FECHA_NACIMIENTO],
DEP.NOMDEPART AS DEPARTAMENTO, 
MUN.MUNNOMBRE AS MUNICIPIO,
UB.UBINOMBRE AS UBICACION,
PAC.IPTELEFON AS [TELEFONO],
PAC.IPTELMOVI AS [CELULAR],
EST.NIVEDESCRI AS [NIVEL EDUCATIVO],
ACT.desactivi AS [ACTIVIDAD/OCUPACION],
EAPB.CODENTIDA AS [CODIGO EAPB],
EAPB.NOMENTIDA AS [NOMBRE EAPB],
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro' 
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado'
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [REGIMEN],
GIO.NUMINGRES AS INGRESO,
GIO.NUMEFOLIO AS FOLIO,
CASE ING.IINGREPOR WHEN 1 THEN 'Urgencias'
				   WHEN 2 THEN 'Consulta Externa' 
				   WHEN 3 THEN 'Nacido Hospital' 
				   WHEN 4 THEN 'Remitido'
				   WHEN 5 THEN 'Hospitalización de Urgencias' END AS [UNIDAD INGRESO],
CAST(PRO.IPFECHACO AS DATE) AS [FECHA PRIMERA VEZ PRENATAL],
GIO.FECHISPAC AS [FECHA ATENCION],
GIO.MENARQUIA AS [MENARQUIA AÑOS],
GIO.CICLOSPAC AS [CICLOS DIAS],
GIO.MENSTRDUR AS [DURACION MENSTRUACION DIAS],
CASE GIO.CICLOREGU WHEN 1 THEN 'SI' ELSE 'NO' END AS [CICLO REGULAR],
GIO.EDADVIDSE AS [EDAD INICIO SEXUAL],
GIO.GESTACION AS [NUMERO DE GESTACIONES],
GIO.NUMPARTO AS [NUMERO DE PARTOS],
GIO.NUMCESARE AS [NUMERO DE CESAREAS],
GIO.NUMABORTO AS [NUMERO DE ABORTOS],
GIO.NUMHIJVIV AS [NUMERP NACIDOS VIVOS],
GIO.NUMMORTIN AS [NUMERO DE MORTINATOS],
GIO.NUMETOPIC AS [EMBARAZOS ETOPICOS],
GIO.NUMEOVITO AS [EMBARAZOS OVITOS],
GIO.FECULTMEN AS MOLA,
GIO.FECULTPAR AS [FECHA ULTIMO PARTO],
GIO.FECULTCIT AS [FECHA ULTIMA CITOLOGIA],
PLA.DESPLANIF AS [METODO PLANIFICACION],
GIO.OTROSANTE AS [OTROS ANTECEDENTES],
GIO.CANTPRENA AS [CONTROLES PRENATALES],
GIO.NOMSEMGES AS [SEMANAS DE GESTACION],
GIO.RIESOBTET AS [RIESGO],
GIO.RESCUAHEM AS [CUADRO HEMATICO],
GIO.FECHACUA AS [FECHA CUADRO HEMATICO],
GIO.RESPARORI AS [PARCIAL DE ORINA],
GIO.FECHAORI AS [FECHA PARCIAL ORINA],
GIO.TESTSULLI AS [TEST SULLIVAN O PTOG],
GIO.GLUCBASAL AS [GLUSEMIA BASAL],
GIO.DILUCVDRL AS [VDRL DILUCIONES],
GIO.IGGTOXOPL AS [IgG TOXOPLASMA],
CAST(GIO.FECULTIGG AS DATE) AS [FECHA EXAMEN LgG],
CASE GIO.RESULTHIV WHEN 0 THEN 'NEGATIVO' 
				   WHEN 1 THEN 'POSITIVO' ELSE 'RIESGO NO EVALUADO' END AS [HIV/VIH],
CAST(GIO.FECHAHIV AS DATE) AS [FECHA HIV/VIH],
CASE GIO.HEPATITIB WHEN 1 THEN '+POSITIVO'
				   WHEN 2 THEN '-NEGATIVO'
				   WHEN 3 THEN 'NO TIENE' END AS [ANT.SUP.HEPATITIS B],
CAST(GIO.FECHAHEPB AS DATE) AS [FECHA HEPATITIS B],
CAST(GIO.FECPROPAR AS DATE) AS [FECHA PROBALE PARTO],
FIS.TENARTSIS as [TENSION SISTOLICA],
fis.TENARTDIA as [TENSION ARTERIAL DIASTOLICA],
fis.TEMPERPAC as TEMPERATURA,
fis.FRECARPAC as [FRECUENCIA CARDIACA],
fis.FRERESPAC as [FRECUENCIA RESPIRATORIA],
fis.REGSO2PAC as [SATURACION OXIGENO],
fis.TALLAPACI as TALLA,
convert(bigint,fis.PESOPACIE) as [PESO Gr],
ISNULL((convert(bigint,fis.PESOPACIE)/1000),'00') as [PESO Kg],
CASE WHEN fis.PESOPACIE='0.000' OR fis.TALLAPACI='0.0' THEN NULL
	 ELSE convert(INT,fis.PESOPACIE/CONVERT(decimal(3,2),fis.TALLAPACI/100)*2) END as IMC,
fis.INTERALTURAUTERINA as [ALTURA UTERINA],
DIS.DISCDESCRI AS DISCAPACIDAD,
IIF(ELI1.IPCODPACI IS NULL,'NO','SI') AS [PRE ELISA ENFERMERIA],
IIF(ELI2.IPCODPACI IS NULL,'NO','SI') AS [POS ELISA ENFERMERIA],
IIF(LAC.IPCODPACI IS NULL,'NO','SI') AS [LACTANCIA MATERNA],
1 as 'CANTIDAD',
CAST(GIO.FECHISPAC  AS date) AS 'FECHA BUSQUEDA',
YEAR(GIO.FECHISPAC ) AS 'AÑO FECHA BUSQUEDA',
MONTH(GIO.FECHISPAC ) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(GIO.FECHISPAC ) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
  END AS 'MES NOMBRE FECHA BUSQUEDA', 
FORMAT(DAY(GIO.FECHISPAC ), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(GIO.FECHISPAC ), '00') ,' - ', 
	   CASE MONTH(GIO.FECHISPAC ) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
dbo.HCANTGINE GIO INNER JOIN
DBO.INPACIENT PAC ON GIO.IPCODPACI=PAC.IPCODPACI AND /* IN V2*/ GIO.NOMSEMGES!='0.0' /* FN V2*/ INNER JOIN
INUBICACI UB ON PAC.AUUBICACI=UB.AUUBICACI INNER JOIN
INMUNICIP MUN ON UB.DEPMUNCOD = MUN.DEPMUNCOD INNER JOIN
HCHISPACA HIS ON GIO.NUMINGRES = HIS.NUMINGRES AND HIS.IDMODELOHC NOT IN (9) INNER JOIN
dbo.ADINGRESO ING ON GIO.NUMINGRES=ING.NUMINGRES INNER JOIN
INDEPARTA DEP ON MUN.DEPCODIGO = DEP.DEPCODIGO AND PAC.AUUBICACI = UB.AUUBICACI INNER JOIN
INENTIDAD AS EAPB ON PAC.CODENTIDA=EAPB.CODENTIDA LEFT JOIN
dbo.HCEXFISIC FIS ON GIO.NUMINGRES=FIS.NUMINGRES AND GIO.NUMEFOLIO=FIS.NUMEFOLIO LEFT JOIN
dbo.HCTIPPLAN PLA ON GIO.CODPLANIF=PLA.CODPLANIF LEFT JOIN
CTE_INGRESO_PROGRAMA PRO ON GIO.NUMINGRES=PRO.NUMINGRES LEFT JOIN
dbo.ADDISCAPACI DIS ON PAC.DISCCODIGO=DIS.DISCCODIGO LEFT JOIN
dbo.ADNIVELED EST ON PAC.NIVECODIGO=EST.NIVECODIGO LEFT JOIN
dbo.ADACTIVID ACT ON PAC.CODACTIVI=ACT.codactivi LEFT JOIN
CTE_ELISA ELI1 ON GIO.IPCODPACI=ELI1.IPCODPACI AND ELI1.TIPO=1 AND ELI1.NUMERO=1 AND GIO.FECHISPAC>=ELI1.FECHORAIN LEFT JOIN
CTE_ELISA ELI2 ON GIO.IPCODPACI=ELI2.IPCODPACI AND ELI2.TIPO=1 AND ELI2.NUMERO=2 AND GIO.FECHISPAC>=ELI2.FECHORAIN LEFT JOIN
CTE_LACTANTE LAC ON GIO.IPCODPACI=LAC.IPCODPACI AND LAC.NUMERO=1 AND GIO.FECHISPAC>=LAC.FECHORAIN

--1873



--select * from dbo.HCANTGINE
--SELECT * FROM dbo.HCRIESGOSP

--SELECT * FROM dbo.HCANTGINE WHERE ipcodpaci='1030220403'
--select * from hchispaca where numingres='145362'
--select * from dbo.PRMODELOHC
