-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewResolucion768
-- Extracted by Fabric SQL Extractor SPN v3.9.0





    /*******************************************************************************************************************
Nombre: [Report].[ViewResolucion768]
Tipo:Vista
Observacion:Vista que trae resolución 768(estancias mayores a 6 horas de hospitalización.)
Profesional: Nilsson Miguel Galindo Lopez
Fecha:21-09-2022
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Vercion 2
Persona que modifico:
Fecha:
Ovservaciones:
--------------------------------------
Vercion 3
Persona que modifico:
Fecha:
***********************************************************************************************************************************/
CREATE VIEW [Report].[ViewResolucion768] AS

WITH

CTE_ESTANCIAS AS
(
--- select de estancias que no sean de observacion ni de uci ni de cx
SELECT
CEN.CODIPSSEC AS [CODIGO REPS],
CASE P.IPTIPODOC WHEN 1 THEN 'CC'
				 WHEN 2 THEN 'CE'
				 WHEN 3 THEN 'TI'
				 WHEN 4 THEN 'RC' 
				 WHEN 5 THEN 'PA'
				 WHEN 6 THEN 'AS' 
				 WHEN 7 THEN 'MS'
				 WHEN 8 THEN 'NU'
				 when 9 then 'CN'
				 when 10 then 'CD'
				 when 11 then 'SC'
				 when 12 then 'PE' 
				 WHEN 13 THEN 'PT' 
				 WHEN 14 THEN 'DE' END AS [TIPO DE IDENTIFICACION],
A.IPCODPACI AS [IDENTIFICACION],
P.IPPRIAPEL AS [PRIMER APELLIDO],
P.IPSEGAPEL AS [SEGUNDO APELLIDO],
P.IPPRINOMB AS [PRIMER NOMBRE],
P.IPSEGNOMB AS [SEGUNDO NOMBRE],
A.NUMINGRES AS [INGRESO],
CASE A.FECFINEST WHEN '1989-01-01 00:00:00.000' THEN DATEDIFF(HOUR,A.FECINIEST,A.FECFINEST) 
	 ELSE DATEDIFF(HOUR,A.FECINIEST,getdate())  END AS [HORAS DE ESTANCIA],
D.UFUDESCRI AS [UNIDAD FUNCIONAL],
ING.IFECHAING
FROM 
DBO.CHREGESTA A INNER JOIN 
dbo.CHCAMASHO B ON A.CODICAMAS=B.CODICAMAS INNER JOIN .
dbo.INUNIFUNC D ON B.UFUCODIGO=D.UFUCODIGO INNER JOIN 
dbo.INPACIENT P ON A.IPCODPACI=P.IPCODPACI INNER JOIN
dbo.ADINGRESO ING ON A.NUMINGRES=ING.NUMINGRES AND ING.FECHEGRESO IS NULL INNER JOIN
dbo.ADCENATEN CEN ON ING.CODCENATE=CEN.CODCENATE
WHERE 
(D.UFUDESCRI NOT LIKE '%UNIDAD DE CUIDADO INTENSIVO%' AND D.UFUDESCRI NOT LIKE '%CIRUGIA%' AND D.UFUDESCRI NOT LIKE '%GINECOLOGIA%' AND
D.UFUDESCRI NOT LIKE '%OBSERVACION%' AND D.UFUDESCRI NOT LIKE '%EXTERNA%')

UNION ALL
----select con unidad funcional de observacion igual o mayor a 6 horas-----------------------------------------------------------------
SELECT
CEN.CODIPSSEC AS [CODIGO REPS],
CASE P.IPTIPODOC WHEN 1 THEN 'CC'
				 WHEN 2 THEN 'CE'
				 WHEN 3 THEN 'TI'
				 WHEN 4 THEN 'RC' 
				 WHEN 5 THEN 'PA'
				 WHEN 6 THEN 'AS' 
				 WHEN 7 THEN 'MS'
				 WHEN 8 THEN 'NU'
				 when 9 then 'CN'
				 when 10 then 'CD'
				 when 11 then 'SC'
				 when 12 then 'PE' 
				 WHEN 13 THEN 'PT'
				 WHEN 14 THEN 'DE' END AS [TIPO DE IDENTIFICACION],
A.IPCODPACI AS [IDENTIFICACION],
P.IPPRIAPEL AS [PRIMER APELLIDO],
P.IPSEGAPEL AS [SEGUNDO APELLIDO],
P.IPPRINOMB AS [PRIMER NOMBRE],
P.IPSEGNOMB AS [SEGUNDO NOMBRE],
A.NUMINGRES AS [INGRESO],
CASE A.FECFINEST WHEN '1989-01-01 00:00:00.000' THEN DATEDIFF(HOUR,A.FECINIEST,A.FECFINEST) 
	 ELSE DATEDIFF(HOUR,A.FECINIEST,getdate())  END AS [HORAS DE ESTANCIA],
D.UFUDESCRI AS [UNIDAD FUNCIONAL],
ING.IFECHAING
FROM 
DBO.CHREGESTA A INNER JOIN 
dbo.CHCAMASHO B ON A.CODICAMAS=B.CODICAMAS INNER JOIN .
dbo.INUNIFUNC D ON B.UFUCODIGO=D.UFUCODIGO INNER JOIN 
dbo.INPACIENT P ON A.IPCODPACI=P.IPCODPACI INNER JOIN
dbo.ADINGRESO ING ON A.NUMINGRES=ING.NUMINGRES AND ING.FECHEGRESO IS NULL INNER JOIN
dbo.ADCENATEN CEN ON ING.CODCENATE=CEN.CODCENATE
WHERE D.UFUDESCRI LIKE '%OBSERVACION%'
)

SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
[CODIGO REPS],
[TIPO DE IDENTIFICACION],
IDENTIFICACION,
[PRIMER APELLIDO],
[SEGUNDO APELLIDO],
[PRIMER NOMBRE],
[SEGUNDO NOMBRE],
INGRESO,
SUM([HORAS DE ESTANCIA]) AS [HORAS DE ESTANCIA],
1 AS [CANTIDAD],
CAST(IFECHAING AS DATE) AS 'FECHA BUSQUEDA', 
YEAR(IFECHAING) AS 'AÑO FECHA BUSQUEDA', 
MONTH(IFECHAING) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(IFECHAING) WHEN 1  THEN 'ENERO'
					  WHEN 2  THEN 'FEBRERO'
					  WHEN 3  THEN 'MARZO'
					  WHEN 4  THEN 'ABRIL'
					  WHEN 5  THEN 'MAYO'
					  WHEN 6  THEN 'JUNIO'
					  WHEN 7  THEN 'JULIO'
					  WHEN 8  THEN 'AGOSTO' 
					  WHEN 9  THEN 'SEPTIEMBRE'
					  WHEN 10 THEN 'OCTUBRE'
					  WHEN 11 THEN 'NOVIEMBRE'   
					  WHEN 12 THEN 'DICIEMBRE'END AS 'MES NOMBRE FECHA BUSQUEDA', 
DAY(IFECHAING) AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(IFECHAING), '00') ,' - ', 
CASE MONTH(IFECHAING) WHEN 1 THEN 'ENERO'
					  WHEN 2 THEN 'FEBRERO'
					  WHEN 3 THEN 'MARZO'
					  WHEN 4 THEN 'ABRIL'
					  WHEN 5 THEN 'MAYO'
					  WHEN 6 THEN 'JUNIO'
					  WHEN 7 THEN 'JULIO'
					  WHEN 8 THEN 'AGOSTO'
					  WHEN 9 THEN 'SEPTIEMBRE'
					  WHEN 10 THEN 'OCTUBRE'
					  WHEN 11 THEN 'NOVIEMBRE'
					  WHEN 12 THEN 'DICIEMBRE'END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM CTE_ESTANCIAS
WHERE [HORAS DE ESTANCIA]>=6 --and IDENTIFICACION='1112627561'
GROUP BY [CODIGO REPS],[TIPO DE IDENTIFICACION],IDENTIFICACION,[PRIMER APELLIDO],[SEGUNDO APELLIDO],[PRIMER NOMBRE],
[SEGUNDO NOMBRE],INGRESO,IFECHAING
