-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewReporteSUIT
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[ViewReporteSUIT] as
SELECT DISTINCT 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
AUD.CODUSUCONS 'ID USUARIO QUE CONSULTA',US.NOMUSUARI 'USUARIO CONSULTA',AUD.CODPACQCON 'ID PACIENTE CONSULTADO',
PAC.IPNOMCOMP 'NOMBRE PACIENTE', AUD.FECHCONSU 'FECHA DE CONSULTA',AUD.NOMMAQCONS 'EQUIPO GENERA CONSULTA',
ISNULL(AUD.FOLIOIN,'N/A') 'FOLIO CONSULTADO', AUD.IPMAQCONS 'DIR. IP EQUIPO',ISNULL(AUD.INGRESO,'N/A') 'INGRESO', 
ISNULL(CHC.Nombre,'SIN MOTIVO DE CONSULTA') 'MOTIVO DE CONSULTA',
1 as 'CANTIDAD',
CAST(AUD.FECHCONSU AS date) AS 'FECHA BUSQUEDA',
YEAR(AUD.FECHCONSU) AS 'AÑO FECHA BUSQUEDA', 
MONTH(AUD.FECHCONSU) AS 'MES AÑO FECHA BUSQUEDA', 
CASE MONTH(AUD.FECHCONSU) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE'
  END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(AUD.FECHCONSU), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(AUD.FECHCONSU), '00') ,' - ', 
	   CASE MONTH(AUD.FECHCONSU) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM HCAUDITORIA AUD
LEFT JOIN MOVCONSULHC CHC WITH(NOLOCK) ON CHC.Id=AUD.MOVCONSULHCID
LEFT JOIN INPACIENT PAC WITH(NOLOCK) ON PAC.IPCODPACI=AUD.CODPACQCON
LEFT JOIN SEGusuaru US WITH(NOLOCK) ON US.CODUSUARI=AUD.CODUSUCONS
WHERE AUD.CODPACQCON NOT IN ('000000000000000')
