-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewPendientesDeOrdenesProcedimientosNoQx
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE VIEW [Report].[ViewPendientesDeOrdenesProcedimientosNoQx]
as
WITH CTE_PROCEDIMIENTOS_NO_QX
AS
(
SELECT	CONCAT('HCORDPRON', '-', A.AUTO) Id,'HCORDPRON' EntityName,	A.[AUTO] as Row,A.CODSERIPS,IIF(A.GENSERVICEORDER IS NULL, 0, 1) AS Seleccione,	CONCAT(RTRIM(D.UFUCODIGO), ' - ', RTRIM(D.UFUDESCRI)) AS UnidadFuncional,
			CONCAT(RTRIM(C.CODIGONIT), ' - ', RTRIM(C.NOMMEDICO)) AS Medico,A.OBSSERIPS AS Observacion,	A.FECORDMED AS Fecha,A.NUMEFOLIO AS Folio,A.CODPROSAL,CODESPEC1,CANSERIPS,A.NUMINGRES,
			A.IPCODPACI,D.UFUCODIGO,C.CODIGONIT as NitMedico,A.GENSERVICEORDER,
			case when A.ESTSERIPS = '1' then 'No Realizados' when A.ESTSERIPS = '5' then 'Anulados' else 'Realizados' end as Tipo,
			COALESCE((SELECT TOP 1 CODPROSAL FROM dbo.HCINFPROM where IPCODPACI = A.IPCODPACI AND CODSERIPS = A.CODSERIPS AND NUMINGRES = A.NUMINGRES ORDER BY FECREAPRO ASC), A.CODPROSAL) as MedicoRealizo,
			COALESCE((SELECT TOP 1 FECREAPRO FROM dbo.HCINFPROM where IPCODPACI = A.IPCODPACI AND CODSERIPS = A.CODSERIPS AND NUMINGRES = A.NUMINGRES ORDER BY FECREAPRO ASC), A.FECORDMED) as FechaRealizacion,
			CASE WHEN (SELECT TOP 1 CODPROSAL FROM dbo.HCINFPROM where IPCODPACI = A.IPCODPACI AND CODSERIPS = A.CODSERIPS AND NUMINGRES = A.NUMINGRES ORDER BY FECREAPRO ASC) IS NULL THEN 0 ELSE 1 END as Realizo,
			RTRIM(B.DESSERIPS) AS DESSERIPS,ISNULL(cecd.Id, 0) CUPSEntityContractDescriptionId,ISNULL(cd.Id, 0) ContractDescriptionId,ISNULL(cd.Code + ' - ' + cd.Name, '') ContractDescriptionCodeName
	FROM dbo.ADINGRESO ing
	JOIN dbo.HCORDPRON A ON ing.NUMINGRES = a.NUMINGRES
	JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
	JOIN dbo.INPROFSAL C ON A.CODPROSAL=C.CODPROSAL 
	JOIN dbo.INUNIFUNC D ON A.UFUCODIGO=D.UFUCODIGO
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd on cecd.Id = a.IDDESCRIPCIONRELACIONADA
	LEFT JOIN Contract.ContractDescriptions cd on cd.Id = cecd.ContractDescriptionId
	WHERE A.MANEXTPRO = 0 OR ISNULL(ing.TRATAESPECIA, 0) = 3 AND A.GENSERVICEORDER IS NULL
UNION ALL
	SELECT CONCAT('HCORDPRON', '-', A.AUTO) Id,	'HCORDPRON' EntityName,	A.[AUTO] as Row,A.CODSERIPS, IIF(A.GENSERVICEORDER IS NULL, 0, 1) AS Seleccione,
			CONCAT(RTRIM(D.UFUCODIGO), ' - ', RTRIM(D.UFUDESCRI)) AS UnidadFuncional,CONCAT(RTRIM(C.CODIGONIT), ' - ', RTRIM(C.NOMMEDICO)) AS Medico,
			A.OBSSERIPS AS Observacion,	A.FECORDMED AS Fecha,A.NUMEFOLIO AS Folio,A.CODPROSAL,CODESPEC1,CANSERIPS,INGMH.NUMINGRES,a.IPCODPACI,D.UFUCODIGO,
			C.CODIGONIT as NitMedico,A.GENSERVICEORDER, 
			case when A.ESTSERIPS = '1' then 'No Realizados' when A.ESTSERIPS = '5' then 'Anulados' else 'Realizados' end as Tipo,
			COALESCE((SELECT TOP 1 CODPROSAL FROM dbo.HCINFPROM where IPCODPACI = A.IPCODPACI AND CODSERIPS = A.CODSERIPS AND NUMINGRES = A.NUMINGRES ORDER BY FECREAPRO ASC), A.CODPROSAL) as MedicoRealizo,
			COALESCE((SELECT TOP 1 FECREAPRO FROM dbo.HCINFPROM where IPCODPACI = A.IPCODPACI AND CODSERIPS = A.CODSERIPS AND NUMINGRES = A.NUMINGRES ORDER BY FECREAPRO ASC), A.FECORDMED) as FechaRealizacion,
			CASE WHEN (SELECT TOP 1 CODPROSAL FROM dbo.HCINFPROM where IPCODPACI = A.IPCODPACI AND CODSERIPS = A.CODSERIPS AND NUMINGRES = A.NUMINGRES ORDER BY FECREAPRO ASC) IS NULL THEN 0 ELSE 1 END as Realizo,
			RTRIM(B.DESSERIPS) AS DESSERIPS,ISNULL(cecd.Id, 0) CUPSEntityContractDescriptionId,	ISNULL(cd.Id, 0) ContractDescriptionId,ISNULL(cd.Code + ' - ' + cd.Name, '') ContractDescriptionCodeName
	FROM dbo.HCORDPRON A 
	JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS 
	JOIN dbo.INPROFSAL C ON A.CODPROSAL=C.CODPROSAL 
	JOIN dbo.INUNIFUNC D ON A.UFUCODIGO=D.UFUCODIGO 
	JOIN dbo.HCINGRESORECNAC INGMH  on a.NUMINGRES = INGMH .NUMINGRESHIJO
	JOIN dbo.HCRECINAC RN  on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	JOIN dbo.ADINGRESO AS ING  on ING.NUMINGRES = INGMH.NUMINGRESHIJO  
	LEFT JOIN Contract.CUPSEntityContractDescriptions cecd on cecd.Id = a.IDDESCRIPCIONRELACIONADA
	LEFT JOIN Contract.ContractDescriptions cd on cd.Id = cecd.ContractDescriptionId
	WHERE A.MANEXTPRO = 0 OR ISNULL(ing.TRATAESPECIA, 0) = 3 AND A.GENSERVICEORDER IS NULL
),


CTE_ALTA_MEDICA
AS
(
  SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(FECALTPAC) 'FECHA ALTA' FROM DBO.HCREGEGRE EGR with (nolock) 
  INNER JOIN CTE_PROCEDIMIENTOS_NO_QX AS PEN with (nolock) ON PEN.NUMINGRES =EGR.NUMINGRES 
  GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI
),

CTE_ESTANCIA_MAYOR
AS
(
  SELECT C.NUMINGRES ,C.IPCODPACI,C.CODICAMAS  ,C.FECINIEST 'FECHA ESTANCIA',C.REGESTADO,C.CODTIPEST,C.ID    FROM dbo.CHREGESTA C with (nolock)
  INNER JOIN CTE_PROCEDIMIENTOS_NO_QX AS PEN ON PEN.NUMINGRES =C.NUMINGRES 
  INNER JOIN(SELECT C.NUMINGRES ,C.IPCODPACI ,MAX(C.ID ) IDD FROM dbo.CHREGESTA C with (nolock) GROUP BY C.NUMINGRES ,C.IPCODPACI) AS G ON G.IDD =C.ID 
),

CTE_CAMAS
AS
(
     SELECT FUN.UFUDESCRI 'UNIDAD FUNCIONAL' ,C.IPCODPACI 'IDENTIFICACION' ,C.NUMINGRES 'INGRESO',A.NUMCAMHOS 'CAMA',G.DESTIPEST 'TIPO ESTANCIA'  ,C.ID  'ID_ESTANCIA', 
	 A.CODICAMAS 'ID_CAMAS', CEN.NOMCENATE 'CENTRO DE ATENCION',A.CODCLAHAB ,A.CODCLACAM 
	 FROM dbo.CHCAMASHO A with (nolock)
	 INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON A.UFUCODIGO =FUN.UFUCODIGO 
	 INNER JOIN CTE_ESTANCIA_MAYOR C with (nolock) ON A.CODICAMAS=C.CODICAMAS AND C.REGESTADO = 1 
     INNER JOIN dbo.CHTIPESTA G with (nolock) ON G.CODTIPEST=C.CODTIPEST 
	 INNER JOIN DBO.ADCENATEN AS CEN with (nolock) ON CEN.CODCENATE =A.CODCENATE 
),

CTE_HISTORIAS_AMBULATORIAS
AS
(
  SELECT HIS.NUMINGRES ,HIS.IPCODPACI ,MAX(FECHISPAC) AS 'FECHA ALTA'    FROM  DBO.HCHISPACA HIS with (nolock)
  INNER JOIN CTE_PROCEDIMIENTOS_NO_QX AS PEN with (nolock) ON PEN.NUMINGRES =HIS.NUMINGRES 
  WHERE HIS.GENCONEXT =1
  GROUP BY HIS.NUMINGRES ,HIS.IPCODPACI
)


/*Vista procedimiento no qx;  seleccione(1- con orden de servicio; 0- sin orden de servicio) tipo Realizados */
SELECT 'PROCEDIMIENTOS NO QX' EntityName ,'SIN ORDENES' 'ORDENE DE SERVICIO',noqx.NUMINGRES 'INGRESO',noqx.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE',
noqx.UnidadFuncional 'UNIDAD FUNCIONAL',noqx.Medico 'PROFESIONAL',noqx.FechaRealizacion 'FECHA REALIZACION', noqx.CODSERIPS 'CUPS PROCEDIMIENTO',
noqx.DESSERIPS 'PROCEDIMIENTO',noqx.CANSERIPS 'CANTIDAD' ,ing.IESTADOIN 'ESTADO' ,f.InvoiceNumber 'NRO FACTURA' ,C.RadicatedConsecutive 'NRO RADICADO',alt.[FECHA ALTA]
from CTE_PROCEDIMIENTOS_NO_QX noqx 
INNER JOIN DBO.INPACIENT AS PAC ON PAC.IPCODPACI =noqx.IPCODPACI
inner join dbo.ADINGRESO as ing on noqx.NUMINGRES  =ing.NUMINGRES 
left join Billing .Invoice as f on f.AdmissionNumber =ing.NUMINGRES and f.Status =1
LEFT JOIN Portfolio.RadicateInvoiceD AS RAD ON RAD.InvoiceNumber =F.InvoiceNumber 
LEFT JOIN Portfolio .RadicateInvoiceC AS C ON C.Id =RAD.RadicateInvoiceCId 
LEFT JOIN CTE_ALTA_MEDICA AS ALT with (nolock) ON ALT.NUMINGRES =noqx.NUMINGRES
where noqx.Seleccione =0 and noqx.Tipo ='Realizados' and  noqx.CODSERIPS not in ('S55201','S55202','S55203','S55204','S55205','S55206','S55207','S55208','S55209','939403','931001',
'937000','937101','937201','937202','937203','937300','937400','938303','938302','933501','893801')-- AND NOQX.NUMINGRES ='322 '
--AND noqx.FechaRealizacion BETWEEN '2022-05-01' AND '2022-05-31' and ing.IESTADOIN ='F'
