-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewOrdenesTraslado
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE VIEW [Report].[ViewOrdenesTraslado] AS

WITH CTE_DESTINOS AS 
 (
  SELECT 
   ROW_NUMBER () OVER(PARTITION BY HCP.IPCODPACI ORDER BY HCP.NUMEFOLIO DESC) 'NUMERO',
   HCP.NUMEFOLIO, HCP.NUMINGRES, HCP.CODDIAGNO, HCP.IPCODPACI, HCP.UFUCODIGO,  HCP.FECHISPAC, HCP.INDICAPAC,
   PRON.CODSERIPS
  FROM 
   HCHISPACA HCP --48745
   LEFT JOIN HCORDPRON PRON ON HCP.IPCODPACI = PRON.IPCODPACI AND HCP.NUMINGRES = PRON.NUMINGRES AND HCP.NUMEFOLIO = PRON.NUMEFOLIO 
  WHERE 
   INDICAPAC IN (2,3,4,5,6,8,18,19)
 )

SELECT 
 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 CASE 
  PAC.IPTIPODOC
  WHEN 1 THEN 'CC'
  WHEN 2 THEN 'CE'
  WHEN 3 THEN 'TI'
  WHEN 4 THEN 'RC'
  WHEN 5 THEN 'PA'
  WHEN 6 THEN 'AS'
  WHEN 7 THEN 'MS'
  WHEN 8 THEN 'NU'
  WHEN 9 THEN 'CN'
  WHEN 10 THEN 'CD'
  WHEN 11 THEN 'SC'
  WHEN 12 THEN 'PE' 
  WHEN 13 THEN 'PT' 
  WHEN 14 THEN 'DE' 
  WHEN 15 THEN 'SI'
 END 'TIPO DOC',
 PRON.IPCODPACI 'ID. PACIENTE', 
 PAC.IPNOMCOMP 'NOMBRE PACIENTE', 
 CAST(PRON.FECHISPAC AS date) AS 'FECHA SOLICITUD ORDEN',
 ENT.CODENTIDA 'COD. EAPB', 
 ENT.NOMENTIDA 'NOMBRE EAPB', 
 CASE PRON.INDICAPAC 
  WHEN 2 THEN 'Trasladar a Observacion Urgencias'
  WHEN 3 THEN 'Trasladar a Hospitalizacion' 
  WHEN 4 THEN  'Trasladar a UCI Adulto'
  WHEN 5 THEN 'Trasladar a UCI Pediatrica' 
  WHEN 6 THEN 'Trasladar a UCI Neonatal'
  WHEN 8 THEN 'Trasladar a Cirugia'
  WHEN 18 THEN 'Estancia Con la Madre'
  WHEN 19 THEN 'U.Cuidado Intermedio'
  WHEN 20 THEN 'U.Basica' END 'TIPO DE TRASLADO',
  PRON.CODSERIPS 'COD. CUPS',
  CUPS.DESCODCUPS 'NOMBRE CUPS', 
  PRON.CODDIAGNO 'COD.CIE-10', 
  DIAG.NOMDIAGNO 'DIAGNOSTICO',
  PRON.UFUCODIGO 'COD. UF',
  FUN.UFUDESCRI 'UNIDAD FUNCIONAL',
  CAM.DESCCAMAS 'CAMA ESTANCIA ACTUAL',
  TIP.Nombre 'AISLAMIENTO',
  CAST(AIS.FECINIAIS as date) 'FECHA AISLAMIENTO',
  1 as 'CANTIDAD',
  CAST(PRON.FECHISPAC AS date) AS 'FECHA BUSQUEDA',
  YEAR(PRON.FECHISPAC) AS 'AÑO BUSQUEDA',
  MONTH(PRON.FECHISPAC) AS 'MES BUSQUEDA',
  CONCAT(FORMAT(MONTH(PRON.FECHISPAC), '00') ,' - ', 
	   CASE MONTH(PRON.FECHISPAC) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
  CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 CTE_DESTINOS PRON
 INNER JOIN INCUPSIPS CUPS ON CUPS.CODSERIPS=PRON.CODSERIPS
 INNER JOIN INPACIENT PAC ON PAC.IPCODPACI=PRON.IPCODPACI
 INNER JOIN INENTIDAD ENT ON ENT.CODENTIDA=PAC.CODENTIDA
 INNER JOIN INDIAGNOS DIAG ON DIAG.CODDIAGNO=PRON.CODDIAGNO
 LEFT JOIN CHREGESTA EST ON PRON.IPCODPACI = EST.IPCODPACI AND EST.REGESTADO=1
 LEFT JOIN CHCAMASHO CAM ON CAM.CODICAMAS=EST.CODICAMAS
 LEFT JOIN CHREGAISL AIS ON AIS.IPCODPACI=PRON.IPCODPACI AND AIS.CODICAMAS=EST.CODICAMAS AND AIS.NUMINGRES = PRON.NUMINGRES
 LEFT JOIN CHTIPOSAISLAMIENTOS TIP ON TIP.Codigo=AIS.CODAISLAM
 LEFT JOIN INUNIFUNC FUN ON FUN.UFUCODIGO=PRON.UFUCODIGO
WHERE 
 --PRON.IPCODPACI IN ('1146147140') AND
 PRON.NUMERO=1  AND 
 PRON.CODSERIPS IN ('105M01','106M01','106M02','107M01','107M02','108A01','109A01','10A001','10A002','10A003','10A004','10A005','10B001','10B002','10B003',
                    '10B004','10M001','10M002','10M003','10M004','110A01','111A01','120N01','121B01','121M01','121M02','124P01','125A01','126A01','126A02',
					'126A03','126A04','126M01','126M02','126M03','126M04','820P01')

 
 
