-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: View_V2_FAC_REPORTE_ORDENES_CON_VALORACIONES_POR_RECONOCER_HOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE VIEW [Report].[View_V2_FAC_REPORTE_ORDENES_CON_VALORACIONES_POR_RECONOCER_HOS]
AS
SELECT 'HOSPITALARIO' 'TYPE', 'VALORACIONES' 'TIPO', HOS.NUMINGRES 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA],HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA',0 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_VALORACIONES_POR_RECONOCER_HOS HOS