-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: ViewEstufepacientes
-- Extracted by Fabric SQL Extractor SPN v3.9.0




CREATE view [Report].[ViewEstufepacientes]
as
WITH 
CTE_DIAGNOSTICO AS
(
SELECT DIA.CODDIAGNO,DIA.NOMDIAGNO,DIG.NUMINGRES,DIG.NUMEFOLIO
FROM
dbo.HCPRODUCTOSCONTROL CON INNER JOIN
DBO.INDIAGNOH DIG ON CON.NUMINGRES=DIG.NUMINGRES AND DIG.CODDIAPRI=1 AND CON.NUMEFOLIO=DIG.NUMEFOLIO INNER JOIN
DBO.INDIAGNOS DIA ON DIG.CODDIAGNO=DIA.CODDIAGNO
GROUP BY DIA.CODDIAGNO,DIA.NOMDIAGNO,DIG.NUMINGRES,DIG.NUMEFOLIO
)
select 
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
Row_Number() Over (Order By CON.id) as [No],
FU.[Name] as [Servicio],
CON.INCONSECUCONTROL AS [Serie Consecutivo],
PAC.ipcodpaci as [Id Paciente],
DIA.CODDIAGNO+'-'+DIA.NOMDIAGNO AS [Dx],
PRF.NOMMEDICO AS Prescriptor,
ATC.[NAME] AS [Medicamento],
CON.CANTIDAD AS [Cantidad Prescrita],
PRF.TARJETAPR AS [Tarjeta Profesional MED.],
(SELECT TOP(1)USU.NOMUSUARI FROM Inventory.PharmaceuticalDispensing DP INNER JOIN dbo.SEGusuaru USU ON  DP.ConfirmationUser=USU.CODUSUARI WHERE DP.AdmissionNumber=CON.NUMINGRES) AS [Nombre Aux. Farmacia],
CON.FECHAREGISTRO AS [Fecha]
from 
dbo.HCPRODUCTOSCONTROL CON INNER JOIN
Payroll.FunctionalUnit FU ON CON.UFUCODIGO=FU.Code INNER JOIN
DBO.ADINGRESO ING ON CON.NUMINGRES=ING.NUMINGRES INNER JOIN
DBO.INPACIENT PAC ON ING.IPCODPACI=PAC.IPCODPACI INNER JOIN
CTE_DIAGNOSTICO DIA ON ING.NUMINGRES=DIA.NUMINGRES AND CON.NUMEFOLIO=DIA.NUMEFOLIO INNER JOIN
DBO.INPROFSAL PRF ON CON.CODPROSAL=PRF.CODPROSAL INNER JOIN
Inventory.ATC ATC ON CON.CODPRODUC=ATC.Code 

