-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_ERP_PRODUCTIVIDAD_DETALLADA_FACTURACION_V2
-- Extracted by Fabric SQL Extractor SPN v3.9.0





CREATE PROCEDURE [Report].[IND_SP_V2_ERP_PRODUCTIVIDAD_DETALLADA_FACTURACION_V2]

@FECHAINI AS DATE,
@FECHAFIN AS DATE

--DECLARE @FECHAINI AS DATE='2024-11-01';
--DECLARE @FECHAFIN AS DATE='2024-11-20';
--DECLARE @FACTURA AS VARCHAR(20)='HSJS144658'

AS

DECLARE @ID_COMPANY VARCHAR(9)=(CAST(DB_NAME() AS VARCHAR(9)));
DECLARE @TIPOFACTURA INT,@TIPOANULACION INT,@RECONOCIMIENTO INT

------- ************************************************ SE VALIDA QUE CLIENTE ES PARA ASI SACAR EL ID DE LA CUENTA **********************************************************--
IF @ID_COMPANY='INDIGO040' BEGIN SET @TIPOFACTURA=29 SET @TIPOANULACION=30 SET @RECONOCIMIENTO=92 END--HOSPITAL SAN JOSE
IF @ID_COMPANY='INDIGO045' BEGIN SET @TIPOFACTURA=11 SET @TIPOANULACION=30 SET @RECONOCIMIENTO=92 END;--ODO
IF @ID_COMPANY='INDIGO046' BEGIN SET @TIPOFACTURA=11 SET @TIPOANULACION=30 SET @RECONOCIMIENTO=92 END;--UDC
IF @ID_COMPANY='INDIGO047' BEGIN SET @TIPOFACTURA=11 SET @TIPOANULACION=30 SET @RECONOCIMIENTO=92 END;--CCD

--*****************************************************************************************************************************************************************************--
--*************************************************************** SEGMENTO FACTURAS GENERADAS *********************************************************************************--
--*****************************************************************************************************************************************************************************--

--****************CTE PARA SACAR LAS FACTURAS DEL MES DESEADO, DEBEN SER REGISTROS UNICOS DESDE CONTABILIDAD POR EL TIPO DE DOCUMENTO IPO FACTURA******************************--
SET STATISTICS TIME ON;

WITH CTE_FACTURADOS_TOTAL_UNICOS
AS
(
	SELECT DISTINCT JV.EntityId,CAST(JV.VoucherDate AS DATE) VoucherDate,sum(JVD.CreditValue) Valor_Credito,AdmissionNumber, F.InvoiceNumber,JV.Consecutive,
	JVT.Code + ' - ' + JVT.NAME 'TIPO COMPROBANTE',C.Name 'CIUDAD',F.OutputDiagnosis 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',
	CASE F.Status WHEN 1 THEN 'FACTURADO' WHEN 2 THEN 'ANULADO' END 'ESTADO FACTURACION',CAST(F.AnnulmentDate AS DATE) 'FECHA ANULACION',
	F.InvoicedUser,F.AnnulmentUser
	FROM GeneralLedger.JournalVouchers JV WITH (NOLOCK)
	INNER JOIN GeneralLedger.JournalVoucherDetails AS JVD WITH (NOLOCK) ON JVD.IdAccounting =JV.Id
	INNER JOIN Billing.Invoice AS F WITH (NOLOCK) ON F.Id =JV.EntityId
	INNER JOIN GeneralLedger.JournalVoucherTypes AS JVT WITH (NOLOCK) ON JVT.Id =JV.IdJournalVoucher
	INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =F.ThirdPartyId 
	INNER JOIN Common.OperatingUnit AS OU WITH (NOLOCK) ON OU.Id=F.OperatingUnitId
	INNER JOIN Common.City AS C WITH (NOLOCK) ON C.ID=OU.IdCity
	INNER JOIN DBO.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO= F.OutputDiagnosis
	INNER JOIN DBO.SEGusuaru SUF WITH (NOLOCK) ON SUF.CODUSUARI = F.InvoicedUser
	INNER JOIN Billing.InvoiceCategories AS IC WITH (NOLOCK) ON IC.Id=F.InvoiceCategoryId
	LEFT  JOIN DBO.SEGusuaru SUA WITH (NOLOCK) ON SUA.CODUSUARI = F.AnnulmentUser
	WHERE CAST(JV.VoucherDate AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
	--cast(JV.VoucherDate as date)  between '2024-01-01' and '2024-02-28'
	--cast(JV.VoucherDate as date)  between '2024-03-01' and '2024-04-30'
	--cast(JV.VoucherDate as date)  between '2024-05-01' and '2024-06-30'
	--cast(JV.VoucherDate as date)  between '2024-07-01' and '2024-08-31'
	--cast(JV.VoucherDate as date)  between '2024-09-01' and '2024-10-31' 
	--cast(JV.VoucherDate as date)  between '2024-11-01' and '2024-12-31'
	--YEAR(JV.VoucherDate) =@ANO AND MONTH(JV.VoucherDate)=@MES -- AND TP.NIT='900156264'
	AND JV.LegalBookId =1 AND jv.EntityName ='Invoice'  AND IdJournalVoucher=@TIPOFACTURA --AND F.Status=1
	--AND JV.EntityCode LIKE @FACTURA --  'HSJS129077'
	GROUP BY JV.EntityId,CAST(JV.VoucherDate AS DATE),AdmissionNumber, F.InvoiceNumber,JV.Consecutive,JVT.Code + ' - ' + JVT.NAME,C.Name,F.OutputDiagnosis,
	DIA.NOMDIAGNO,F.Status,CAST(F.AnnulmentDate AS DATE),F.InvoicedUser,F.AnnulmentUser
),

----************************* CTE PARA TRAER LAS ORDENES DE IMAGENES CON EL RADIOLOGO QUE REALIZO LA LECTURA DE FACTURAS GENERADAS **********************************************---

CTE_USUARIO_LECTURA_IMAGENES
AS
(
 SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.MEDREALEC,A.ESPEREALIZA,A.GENSERVICEORDER,A.AUTO, 
 PRO.NOMMEDICO 'PROFESIONAL REALIZO',ESP.DESESPECI 'ESPECIALIDA REALIZO',MFC.ContractName 'AGREMIACION'
 FROM dbo.HCORDIMAG A
  INNER JOIN CTE_FACTURADOS_TOTAL_UNICOS AS UNI ON CAST(UNI.AdmissionNumber AS CHAR)=CAST(A.NUMINGRES AS CHAR)
   INNER JOIN
   (
    SELECT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER,MAX(A.AUTO) AUTO
     FROM dbo.ADINGRESO ing with (nolock)
	  INNER JOIN dbo.HCORDIMAG A with (nolock) ON ing.NUMINGRES = A.NUMINGRES
	  INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS
	  INNER JOIN CTE_FACTURADOS_TOTAL_UNICOS AS UNI ON CAST(UNI.AdmissionNumber AS CHAR)=CAST(ING.NUMINGRES AS CHAR)
	  GROUP BY A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER
   ) AS G ON G.AUTO=A.AUTO AND G.NUMINGRES=A.NUMINGRES AND G.CODSERIPS=A.CODSERIPS
 LEFT JOIN dbo.INPROFSAL AS PRO with (nolock) ON PRO.CODPROSAL=A.MEDREALEC
 LEFT JOIN dbo.INESPECIA AS ESP ON ESP.CODESPECI =PRO.CODESPEC1
 LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =PRO.CODPROSAL AND HPC.LiquidateDefault = 1
 LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
 
 UNION ALL

 SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.MEDREALEC,A.ESPEREALIZA,A.GENSERVICEORDER,A.AUTO, 
 ISNULL(PRO.NOMMEDICO,PROE.NOMMEDICO) 'PROFESIONAL REALIZO',ISNULL(ESP.DESESPECI,ESPE.DESESPECI) 'ESPECIALIDA REALIZO',MFC.ContractName 'AGREMIACION'
  FROM dbo.AMBORDIMA A
  INNER JOIN CTE_FACTURADOS_TOTAL_UNICOS AS UNI ON CAST(UNI.AdmissionNumber AS CHAR)=CAST(A.NUMINGRES AS CHAR)
   INNER JOIN
   (
    SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER,MAX(A.AUTO) AUTO
     FROM dbo.ADINGRESO ing with (nolock)
	  INNER JOIN dbo.AMBORDIMA A with (nolock) ON ing.NUMINGRES = A.NUMINGRES
	  INNER JOIN dbo.INCUPSIPS B with (nolock) ON A.CODSERIPS=B.CODSERIPS
	  INNER JOIN CTE_FACTURADOS_TOTAL_UNICOS AS UNI ON CAST(UNI.AdmissionNumber AS CHAR)=CAST(ING.NUMINGRES AS CHAR)
	  --WHERE A.NUMINGRES='DF139D804D'
	  GROUP BY A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER
   ) AS G ON G.AUTO=A.AUTO AND G.NUMINGRES=A.NUMINGRES AND G.CODSERIPS=A.CODSERIPS
 LEFT JOIN dbo.INPROFSAL AS PRO with (nolock) ON PRO.CODPROSAL=A.MEDREALEC
 LEFT JOIN dbo.INESPECIA AS ESP ON ESP.CODESPECI =PRO.CODESPEC1
 LEFT JOIN dbo.INPROFSAL AS PROE with (nolock) ON PROE.CODPROSAL=A.USURECEXA
 LEFT JOIN dbo.INESPECIA AS ESPE ON ESPE.CODESPECI =PROE.CODESPEC1
 LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =ISNULL(PRO.CODPROSAL,PROE.CODPROSAL) AND HPC.LiquidateDefault = 1
 LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
),

CTE_PAQUETE_UNICO
AS
(  --CA.CODIPSSEC 'CODIGO HABILITACION'
 SELECT DISTINCT CASE pac.iptipodoc	WHEN 1 THEN 'CC'WHEN 2 THEN 'CE'WHEN 3 THEN 'TI'WHEN 4 THEN 'RC'WHEN 5 THEN 'PA'WHEN 6 THEN 'AS'
				WHEN 7 THEN 'MS'WHEN 8 THEN 'NU'WHEN 9 THEN 'CN'WHEN 10 THEN 'CD'WHEN 11 THEN 'SC' WHEN 12 THEN 'PE' WHEN 13 THEN 'PT'
				WHEN 14 THEN 'DE'WHEN 15 THEN 'SI' WHEN 16 THEN 'NI' END AS [TIPO IDENTIFICACION], I.CUFE,CA.NOMCENATE 'CENTRO ATENCION',
 SOD.ID,SO.AdmissionNumber,I.PatientCode AS IDENTIFICACION,RTRIM(PAC.IPNOMCOMP) AS PACIENTE,I.AdmissionNumber AS INGRESO,
 CAST(ING.IFECHAING AS DATE) AS [FECHA INGRESO/ADMISION],CAST(ISNULL(ING.FECHEGRESO,I.OutputDate)AS DATE) AS [FECHA EGRESO/ALTA] ,UNI.[CIE10],UNI.[DIAGNOSTICO],
 ING.IAUTORIZA,CA.CODIPSSEC 'CODIGO HABILITACION',CASE I.Status WHEN 1 THEN 'FACTURADO' WHEN 2 THEN 'ANULADO' END 'ESTADO FACTURACION',
 I.InvoiceNumber AS [NRO FACTURA],CAST(I.InvoiceDate AS DATE) AS [FECHA FACTURA],UNI.[CIUDAD], UNI.[FECHA ANULACION],
 CAST(I.InvoiceDate AS DATE) AS 'FECHA BUSQUEDA',--CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',
 CAST(I.InitialDate AS DATE) 'FECHA INGRESO/CORTE FACTURA',CAST(I.OutputDate AS DATE) 'FECHA EGRESO/CORTE FACTURA',
 I.TotalInvoice AS [TOTAL FACTURA], TP.Nit AS NIT,TP.Name AS ENTIDAD,CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION]
  FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN CTE_FACTURADOS_TOTAL_UNICOS AS UNI WITH (NOLOCK) ON UNI.EntityId =I.Id
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES =I.AdmissionNumber
   INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK)  ON PAC.IPCODPACI =I.PatientCode
   INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =I.ThirdPartyId 
   INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =I.CareGroupId
   LEFT JOIN DBO.ADCENATEN AS ca WITH (NOLOCK) ON ing.codcenate = ca.codcenate 
   WHERE SOD.IsPackage=1
),

CTE_CUPS
AS
(
   SELECT CUPS.Id,CUPS.Code, CUPS.Description, 
   CASE CUPS.ServiceType WHEN 1 then 'LABORATORIOS' WHEN 2 then 'PATOLOGIAS' WHEN 3 then 'IMAGENES DIAGNOSTICAS' WHEN 4 then 'PROCEDIMIENTOS NO QX'
      		WHEN 5 then 'PROCEDIMIENTOS QX' WHEN 6 then 'INTERCONSULTAS'WHEN 7 then 'NINGUNO'WHEN 8 then 'CONSULTA EXTERNA' ELSE 'OTROS' END AS 'TIPO SERVICIO',
   BG.CODE 'CODIGO FACTURACION', BG.NAME 'GRUPO FACTURACION',BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION',   CGC.Code 'CODIGO GRUPO',CGC.Name 'GRUPO CUPS',
   CSG.CODE 'CODIGO SUBGRUPO',CSG.Name  'SUBGRUPO CUPS',
   CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
   ELSE 'N/A' END 'OBTENER CC'
   FROM Contract.CUPSEntity AS CUPS
   INNER JOIN Billing.BillingGroup as BG WITH (NOLOCK) ON BG.Id=CUPS.BillingGroupId
   INNER JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=CUPS.BillingConceptId
   INNER JOIN Contract.CupsSubgroup AS CSG WITH (NOLOCK) ON CSG.Id =CUPS.CUPSSubGroupId
   INNER JOIN Contract.CupsGroup AS CGC WITH (NOLOCK) ON CGC.Id =CSG.CupsGroupId
),

CTE_PRODUCTOS
AS
(
  SELECT IPR.ID,IPR.Code,IPR.Name,PG.CODE 'CODIGO PRODUCTO',PG.NAME 'GRUPO PRODUCTO',PSG.Code 'CODIGO SUBGRUPO',PSG.NAME 'SUBGRUPO PRODUCTO',
  BG.CODE 'CODIGO FACTURACION',BG.NAME 'GRUPO FACTURACION',CASE PT.Class WHEN '2' THEN 'MEDICAMENTOS'	WHEN '3' THEN 'INSUMOS' 
			ELSE 'SERVICIOS' END AS [TIPO REGISTRO]
  FROM Inventory.InventoryProduct AS IPR WITH (NOLOCK)
   INNER JOIN Inventory.ProductGroup AS PG WITH (NOLOCK) ON PG.Id=IPR.ProductGroupId
   INNER JOIN Inventory.ProductSubGroup AS PSG WITH (NOLOCK) ON PSG.ID =IPR.ProductSubGroupId
   INNER JOIN Inventory.ProductType AS PT ON IPR.ProductTypeId = PT.Id
   LEFT JOIN Billing.BillingGroup as BG WITH (NOLOCK) ON BG.ID=IPR.BillingGroupId
),

CTE_IPS
AS
(
 SELECT IPS.ID,IPS.Code,IPS.Name, CASE IPS.ServiceClass WHEN 1 THEN 'Ninguno' WHEN 2 THEN 'Cirujano' WHEN 3 THEN 'Anestesiologo' WHEN 4 THEN 'Ayudante' 
 WHEN 5 THEN 'Derecho Sala' WHEN 6 THEN 'Materiales Sutura'    WHEN 7 THEN 'Instrumentacion Quirurgica' ELSE 'Ninguno' end 'TIPO SERVICIO IPS',
 BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION IPS QX',
 CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
 ELSE 'N/A' END 'OBTENER CC'
 FROM Contract.IPSService IPS WITH (NOLOCK)
 LEFT JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=IPS.BillingConceptId
)
--,

--CTE_FACTURA_DETALLADA
--AS
--(  ---CA.CODIPSSEC 'CODIGO HABILITACION',I.CUFE,
SELECT DISTINCT CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, SOD.ID ,
UNI.[CIUDAD],CA.NOMCENATE 'CENTRO ATENCION' ,CASE pac.iptipodoc WHEN 1 THEN 'CC'WHEN 2 THEN 'CE'WHEN 3 THEN 'TI'WHEN 4 THEN 'RC'WHEN 5 THEN 'PA'WHEN 6 THEN 'AS'
WHEN 7 THEN 'MS'WHEN 8 THEN 'NU'WHEN 9 THEN 'CN'WHEN 10 THEN 'CD'WHEN 11 THEN 'SC' WHEN 12 THEN 'PE' WHEN 13 THEN 'PT'
WHEN 14 THEN 'DE'WHEN 15 THEN 'SI' WHEN 16 THEN 'NI' END AS [TIPO IDENTIFICACION],
I.PatientCode AS IDENTIFICACION,RTRIM(PAC.IPNOMCOMP) AS PACIENTE,I.AdmissionNumber AS INGRESO,CAST(ING.IFECHAING AS DATE) AS [FECHA INGRESO/ADMISION],
CAST(ISNULL(ING.FECHEGRESO,I.OutputDate)AS DATE) AS [FECHA EGRESO/ALTA],
CAST(I.InitialDate AS DATE) 'FECHA INGRESO/CORTE FACTURA',CAST(I.OutputDate AS DATE) 'FECHA EGRESO/CORTE FACTURA',
  I.InvoiceNumber AS [NRO FACTURA],CAST(I.InvoiceDate AS DATE) AS [FECHA FACTURA],I.TotalInvoice AS [TOTAL FACTURA],
  TP.Nit AS NIT,TP.Name AS ENTIDAD,CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],
  		ISNULL(IPR.[TIPO REGISTRO],'SERVICIO') AS 'TIPO REGISTRO',
		ISNULL(CUPS.[TIPO SERVICIO],IPR.[TIPO REGISTRO]) 'TIPO SERVICIO',
  CASE SOD.Presentation WHEN 1 THEN 'NO QUIRURGICO' WHEN 2 THEN 'QUIRURGICO' WHEN 3 THEN 'PAQUETE' ELSE 'NO QUIRURGICO' END AS 'PRESENTACION',
  ISNULL(CUPS.[GRUPO FACTURACION],IPR.[GRUPO FACTURACION]) 'GRUPO FACTURACION',
  CAST(SOD.ServiceDate AS DATE) AS 'FECHA SERVICIO', ISNULL(CUPS.Code,IPR.Code) AS 'CUPS/PRODUCTO',  
  REPLACE(ISNULL(CUPS.Description,IPR.Name), ',', '')  AS 'DESCRIPCION', 
  ISNULL(IPSS.Code, 'N/A') AS ' CODIGO SERVICIO IPS', REPLACE(SUBSTRING(ISNULL(RTRIM(IPSS.Name), 'N/A'),1,60), ',', '')  AS 'DESCRIPCION SERVICIO IPS',
  ISNULL(IPSQX.Code, 'N/A') AS 'CODIGO DETALLE QX',REPLACE(SUBSTRING(ISNULL(RTRIM(IPSQX.Name), 'N/A'),1,60), ',', '')  AS 'DESCRIPCION DETALLE QX',
  ISNULL(IPSQX.[TIPO SERVICIO IPS],'Ninguno') 'TIPO SERVICIO IPS',CD.Name 'DESCRIPCION RELACIONADA',
  ISNULL(IDS.InvoicedQuantity,ID.InvoicedQuantity) 'CANTIDAD',  
  ISNULL(CAST(IDS.TotalSalesPrice as NUMERIC(18,2)),CAST(ID.TotalSalesPrice AS NUMERIC(18,2))) 'VALOR UNITARIO',
  ISNULL(CAST(IDS.TotalSalesPrice as NUMERIC(18,2)),CAST(SOD.RateManualSalePrice AS NUMERIC(18,2))) 'VALOR SERVICIO',
  ISNULL(CAST(SOD.CostValue AS NUMERIC(18,2)) * ISNULL(IDS.InvoicedQuantity,ID.InvoicedQuantity),0) 'COSTO SERVICIO', 
    0 'VALOR DETALLE PAQUETE',  
  ISNULL(CAST(IDS.TotalSalesPrice AS NUMERIC(18,2)),CAST(ID.GrandTotalSalesPrice AS NUMERIC(18,2))) 'VALOR TOTAL FACTURA',
  IIF((ID.Presentation=2 AND ID.SubTotalPatientSalesPrice<>0),CAST(IDS.TotalSalesPrice-((IDS.TotalSalesPrice*(ID.SubTotalPatientSalesPrice/ID.GrandTotalSalesPrice))) AS NUMERIC(18,2)),ISNULL(CAST(IDS.TotalSalesPrice AS NUMERIC(18,2)),CAST(ID.ThirdPartySalesPrice AS NUMERIC(18,2)))) 'VALOR ENTIDAD',
  IIF((ID.Presentation=2 AND ID.SubTotalPatientSalesPrice<>0),CAST((IDS.TotalSalesPrice*(ID.SubTotalPatientSalesPrice/ID.GrandTotalSalesPrice)) AS NUMERIC(18,2)),CAST(ID.SubTotalPatientSalesPrice AS NUMERIC(18,2))) 'VALOR PACIENTE',
  CASE SOD.IsPackage WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'ES PAQUETE',CASE SOD.Packaging WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'INCLUIDO EN PAQUETE',
  '' 'CODIGO PAQUETE','' 'NOMBRE PAQUETE',0 'VALOR PAQUETE',CASE SOD.SettlementType WHEN 3 THEN 'SI (No se cobra nada)'ELSE 'NO (Se cobra)' END 'SERVICIO INCLUIDO',
  CUPSI.Code 'CUPS QUE INCLUYE',CUPSI.Description 'NOMBRE CUPS QUE INCLUYE',FU.Code 'CODIGO UFS',FU.Name AS 'UNIDAD FUNCIONAL SERVICIO',
  CC.CODE 'CODIGO CC CONTABILIZO',CC.Name 'CENTRO COSTO CONTABILIZO',MA.Number 'NRO CUENTA CONTABILIZO',  MA.Name 'CUENTA CONTABILIZO',  
  UNI.[CIE10],UNI.[DIAGNOSTICO],ISNULL(SOD.AuthorizationNumber,ING.IAUTORIZA) 'AUTORIZACION',  CAST(SO.CreationDate AS DATE) 'FECHA ORDEN',
  ISNULL(SUSO.NOMUSUARI,'INDIGOBOT') 'USUARIO CREO ORDEN',SO.CODE 'CODIGO ORDEN',
  ISNULL(RTRIM(IMA.[PROFESIONAL REALIZO]),  RTRIM(ISNULL(MEDQX.NOMMEDICO,ISNULL(MED.NOMMEDICO,TPT.Name)))) 'PROFESIONAL REALIZO',ISNULL(IMA.[ESPECIALIDA REALIZO],
  ISNULL(ESPQX.DESESPECI,ESPMED.DESESPECI)) 'ESPECIALIDAD REALIZO',ISNULL(CUPS.[GRUPO CUPS],IPR.[GRUPO PRODUCTO]) 'GRUPO CUPS/PRODUCTO',
  ISNULL(CUPS.[SUBGRUPO CUPS],IPR.[SUBGRUPO PRODUCTO]) 'SUBGRUPO CUPS/PRODUCTO',ISNULL(CUPS.[CODIGO CONCEPTO],IPR.[CODIGO PRODUCTO]) 'CODIGO CONCEPTO FAC CUPS',
  ISNULL(CUPS.[CONCEPTO FACTURACION],IPR.[GRUPO PRODUCTO]) 'CONCEPTO FACTURACION CUPS',ISNULL(CUPS.[OBTENER CC],'N/A') 'OBTENER CC CUPS',
  ISNULL(IPSQX.[CODIGO CONCEPTO],'N/A') 'CODIGO CONCEPTO FAC IPS QX', ISNULL(IPSQX.[CONCEPTO FACTURACION IPS QX],'N/A') 'CONCEPTO FACTURACION IPS QX',
  ISNULL(IPSQX.[OBTENER CC],'N/A') 'OBTENER CC IPS QX',
  CASE DRD.RuleType WHEN 1 THEN 'Servicio IPS' WHEN 2 THEN 'CUPS' WHEN 3 THEN 'SubGrupos CUPS' WHEN 4 THEN 'Grupo CUPS' WHEN 5 THEN 'General' ELSE 'N/A' END 'TIPO REGLA',
  UNI.[ESTADO FACTURACION],UNI.[FECHA ANULACION],IIF(SO.EntityName='PharmaceuticalDispensing',SO.EntityCode,'N/A') 'CODIGO DISPENSACION',
  ISNULL(IMA.[AGREMIACION],MFC.ContractName) 'AGREMIACION',CAST(I.InvoiceDate AS DATE) AS 'FECHA BUSQUEDA',
  CASE ING.TIPOINGRE WHEN 1 THEN IIF((SOD.Presentation =2 OR SOD.Presentation =3),'AMBULATORIO - QUIRURGICO','AMBULATORIO') 
                     WHEN 2 THEN IIF((SOD.Presentation =2 OR SOD.Presentation =3),'HOSPITALARIO - QUIRURGICO','HOSPITALARIO') END 'AMBITO',
  CONVERT(DATETIME,COMMON.GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
  /**/

 FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN CTE_FACTURADOS_TOTAL_UNICOS AS UNI WITH (NOLOCK) ON UNI.EntityId =I.Id
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
   INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON CAST(ING.NUMINGRES  AS CHAR)=CAST(I.AdmissionNumber AS CHAR)
   INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =I.PatientCode
   INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =I.ThirdPartyId 
   INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =I.CareGroupId
   LEFT JOIN DBO.ADCENATEN AS ca WITH (NOLOCK) ON ing.codcenate = ca.codcenate
   LEFT JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.ID=SOD.CUPSEntityId
   LEFT JOIN CTE_PRODUCTOS AS IPR WITH (NOLOCK) ON IPR.ID= SOD.ProductId
   LEFT JOIN Billing.InvoiceDetailSurgical AS IDS WITH (NOLOCK) ON IDS.InvoiceDetailId =ID.Id AND IDS.OnlyMedicalFees = '0'
   LEFT JOIN CTE_IPS AS IPSS WITH (NOLOCK) ON IPSS.Id =SOD.IPSServiceId
   LEFT JOIN CTE_IPS AS IPSQX WITH (NOLOCK) ON IPSQX.Id =IDS.IPSServiceId
   LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =SOD.CUPSEntityContractDescriptionId  AND SOD.CUPSEntityId=DESCR.CUPSEntityId 
   LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
   LEFT JOIN Billing.ServiceOrderDetail AS SODI  ON SODI.Id =SOD.IncludeServiceOrderDetailId 
   LEFT JOIN CTE_CUPS AS CUPSI WITH (NOLOCK) ON CUPSI.ID=SODI.CUPSEntityId
   LEFT JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =ISNULL(IDS.CostCenterId,SOD.CostCenterId)
   LEFT JOIN GeneralLedger.MainAccounts AS MA  ON MA.Id =ISNULL(IDS.IncomeMainAccountId,SOD.IncomeMainAccountId)
   LEFT JOIN DBO.SEGusuaru SUSO WITH (NOLOCK) ON SUSO.CODUSUARI = SO.CreationUser
   LEFT JOIN dbo.INPROFSAL AS MED  ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode  
   LEFT JOIN dbo.INESPECIA AS ESPMED  ON ESPMED.CODESPECI = SOD.PerformsProfessionalSpecialty 
   LEFT JOIN Common.ThirdParty AS TPT  ON TPT.Id =SOD.PerformsHealthProfessionalThirdPartyId 
   LEFT JOIN dbo.INPROFSAL AS MEDQX  ON MEDQX.CODPROSAL = IDS.PerformsHealthProfessionalCode
   LEFT JOIN dbo.INESPECIA AS ESPQX  ON ESPQX.CODESPECI = MEDQX.CODESPEC1
   LEFT JOIN Contract.DefinitionRateDetail DRD ON DRD.ID=SOD.DefinitionRateDetailId
   LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =  ISNULL(IDS.PerformsHealthProfessionalCode,ISNULL(MED.CODPROSAL,TPT.Nit)) AND HPC.LiquidateDefault = 1
   LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
   LEFT JOIN CTE_USUARIO_LECTURA_IMAGENES IMA ON cast(IMA.NUMINGRES as char)=cast(I.AdmissionNumber as char) and IMA.GENSERVICEORDER=SO.ID AND IMA.CODSERIPS=CUPS.CODE

--),
UNION ALL
--CTE_SERVICIOS_PAQUETE_DETALLADO
--AS
--(  ---UNI.[CODIGO HABILITACION],UNI.CUFE,
SELECT DISTINCT CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,SOD.ID, 
UNI.[CIUDAD],UNI.[CENTRO ATENCION],UNI.[TIPO IDENTIFICACION],UNI.[IDENTIFICACION],UNI.[PACIENTE],UNI.[INGRESO],UNI.[FECHA INGRESO/ADMISION],
UNI.[FECHA EGRESO/ALTA],UNI.[FECHA INGRESO/CORTE FACTURA],UNI.[FECHA EGRESO/CORTE FACTURA],--UNI.[FECHA EGRESO],
UNI.[NRO FACTURA],UNI.[FECHA FACTURA],UNI.[TOTAL FACTURA],UNI.[NIT],UNI.[ENTIDAD],UNI.[CODIGO GRUPO ATENCION],UNI.[GRUPO ATENCION],
    ISNULL(IPR.[TIPO REGISTRO],'SERVICIO') AS 'TIPO REGISTRO',ISNULL(CUPS.[TIPO SERVICIO],IPR.[TIPO REGISTRO]) 'TIPO SERVICIO',
    CASE SOD.Presentation WHEN 1 THEN 'NO QUIRURGICO' WHEN 2 THEN 'QUIRURGICO' WHEN 3 THEN 'PAQUETE' ELSE 'NO QUIRURGICO' END AS 'PRESENTACION', 
	ISNULL(CUPS.[GRUPO FACTURACION],IPR.[GRUPO FACTURACION]) 'GRUPO FACTURACION',
    CAST(SOD.ServiceDate AS DATE) AS 'FECHA SERVICIO', ISNULL(CUPS.Code,IPR.Code) AS 'CUPS/PRODUCTO',
	REPLACE(ISNULL(CUPS.Description,IPR.Name), ',', '')	 AS 'DESCRIPCION',
    ISNULL(IPSS.Code, 'N/A') AS ' CODIGO SERVICIO IPS',REPLACE(SUBSTRING(ISNULL(RTRIM(IPSS.Name), 'N/A'),1,60), ',', '') AS 'DESCRIPCION SERVICIO IPS',
    ISNULL(IPSQX.Code, 'N/A') AS 'CODIGO DETALLE QX',REPLACE(SUBSTRING(ISNULL(RTRIM(IPSQX.Name), 'N/A'),1,60), ',', '') AS 'DESCRIPCION DETALLE QX',
	ISNULL(IPSQX.[TIPO SERVICIO IPS],'Ninguno') 'TIPO SERVICIO IPS',CD.Name 'DESCRIPCION RELACIONADA',
    ISNULL(SODS.InvoicedQuantity,SOD.InvoicedQuantity) 'CANTIDAD',
	ISNULL(CAST(SODS.TotalSalesPrice AS NUMERIC(18,2)),CAST(SOD.TotalSalesPrice AS NUMERIC(20,2))) 'VALOR UNITARIO',
	ISNULL(CAST(SODS.RateManualSalePrice AS NUMERIC(18,2)),CAST(SOD.RateManualSalePrice AS NUMERIC(20,2))) 'VALOR SERVICIO',
    ISNULL(CAST(SOD.CostValue AS NUMERIC(18,2)) * ISNULL(SODS.InvoicedQuantity,SOD.InvoicedQuantity),0) 'COSTO SERVICIO', 
	IIF(SOD.Packaging=0,0,ISNULL(CAST(SODS.TotalSalesPrice AS NUMERIC(18,2)),CAST(SOD.GrandTotalSalesPrice AS NUMERIC(18,2)))) 'VALOR DETALLE PAQUETE',
    0 'VALOR TOTAL FACTURA',0 'VALOR ENTIDAD', 0 'VALOR PACIENTE',	CASE SOD.IsPackage WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'ES PAQUETE',
    CASE SOD.Packaging WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'INCLUIDO EN PAQUETE',CUPSP.Code 'CODIGO PAQUETE',CUPSP.Description 'NOMBRE PAQUETE',
	CAST(SODP.GrandTotalSalesPrice AS NUMERIC(18,2)) 'VALOR PAQUETE',CASE SOD.SettlementType WHEN 3 THEN 'SI (No se cobra nada)'ELSE 'NO (Se cobra)' END 'SERVICIO INCLUIDO',
	CUPSI.Code 'CUPS QUE INCLUYE',CUPSI.Description 'NOMBRE CUPS QUE INCLUYE',FU.Code 'CODIGO UFS',FU.Name AS 'UNIDAD FUNCIONAL SERVICIO',
	CC.CODE 'CODIGO CC CONTABILIZO',CC.Name 'CENTRO COSTO CONTABILIZO',MA.Number 'NRO CUENTA CONTABILIZO',  MA.Name 'CUENTA CONTABILIZO',
	UNI.[CIE10],UNI.[DIAGNOSTICO],ISNULL(SOD.AuthorizationNumber,UNI.IAUTORIZA) 'AUTORIZACION',	CAST(SO.CreationDate AS DATE) 'FECHA ORDEN',
	ISNULL(SUSO.NOMUSUARI,'INDIGOBOT') 'USUARIO CREO ORDEN',SO.CODE 'CODIGO ORDEN',
	ISNULL(RTRIM(IMA.[PROFESIONAL REALIZO]),
	--RTRIM(ISNULL(MEDQX.NOMMEDICO,ISNULL(MED.NOMMEDICO,TPT.Name)))) 'PROFESIONAL REALIZA',
	--ISNULL(IMA.[ESPECIALIDA REALIZO],ISNULL(ESPQX.DESESPECI,ESPMED.DESESPECI)) 'ESPECIALIDAD REALIZO',
	RTRIM(ISNULL(MED.NOMMEDICO,TPT.Name))) 'PROFESIONAL REALIZA',
	ISNULL(IMA.[ESPECIALIDA REALIZO],ESPMED.DESESPECI) 'ESPECIALIDAD REALIZO',
	ISNULL(CUPS.[GRUPO CUPS],IPR.[GRUPO PRODUCTO]) 'GRUPO CUPS/PRODUCTO',
	ISNULL(CUPS.[SUBGRUPO CUPS],IPR.[SUBGRUPO PRODUCTO]) 'SUBGRUPO CUPS/PRODUCTO',ISNULL(CUPS.[CODIGO CONCEPTO],IPR.[CODIGO PRODUCTO]) 'CODIGO CONCEPTO FAC CUPS',
	ISNULL(CUPS.[CONCEPTO FACTURACION],IPR.[GRUPO PRODUCTO]) 'CONCEPTO FACTURACION',ISNULL(CUPS.[OBTENER CC],'N/A') 'OBTENER CC CUPS',
	ISNULL(IPSQX.[CODIGO CONCEPTO],'N/A') 'CODIGO CONCEPTO FAC IPS QX',ISNULL(IPSQX.[CONCEPTO FACTURACION IPS QX],'N/A') 'CONCEPTO FACTURACION IPS QX',
	ISNULL(IPSQX.[OBTENER CC],'N/A') 'OBTENER CC IPS QX',
	CASE DRD.RuleType WHEN 1 THEN 'Servicio IPS' WHEN 2 THEN 'CUPS' WHEN 3 THEN 'SubGrupos CUPS' WHEN 4 THEN 'Grupo CUPS' WHEN 5 THEN 'General' ELSE 'N/A' END 'TIPO REGLA',
	UNI.[ESTADO FACTURACION],UNI.[FECHA ANULACION],IIF(SO.EntityName='PharmaceuticalDispensing',SO.EntityCode,'N/A') 'CODIGO DISPENSACION',
	ISNULL(IMA.[AGREMIACION],MFC.ContractName) 'AGREMIACION',UNI.[FECHA BUSQUEDA],
	CASE ING.TIPOINGRE WHEN 1 THEN IIF((SOD.Presentation =2 OR SOD.Presentation =3),'AMBULATORIO - QUIRURGICO','AMBULATORIO') 
                       WHEN 2 THEN IIF((SOD.Presentation =2 OR SOD.Presentation =3),'HOSPITALARIO - QUIRURGICO','HOSPITALARIO') END 'AMBITO',
	CONVERT(DATETIME,COMMON.GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL

   FROM Billing.ServiceOrderDetail AS SOD WITH (NOLOCK)
   INNER JOIN CTE_PAQUETE_UNICO AS UNI WITH (NOLOCK) ON UNI.ID=SOD.PackageServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Payroll.FunctionalUnit AS FU  ON FU.Id = SOD.PerformsFunctionalUnitId
   INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON CAST(ING.NUMINGRES  AS CHAR)=CAST(SO.AdmissionNumber AS CHAR)
   LEFT JOIN Billing.ServiceOrderDetailSurgical SODS WITH (NOLOCK) ON SODS.ServiceOrderDetailId=SOD.ID
   LEFT JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.ID=SOD.CUPSEntityId
   LEFT JOIN CTE_PRODUCTOS AS IPR WITH (NOLOCK) ON IPR.ID= SOD.ProductId
   LEFT JOIN CTE_IPS AS IPSS WITH (NOLOCK) ON IPSS.Id =SOD.IPSServiceId
   LEFT JOIN CTE_IPS AS IPSQX WITH (NOLOCK) ON IPSQX.Id =SODS.IPSServiceId
   LEFT JOIN Billing.ServiceOrderDetail AS SODP WITH (NOLOCK) ON SODP.ID=SOD.PackageServiceOrderDetailId
   LEFT JOIN CTE_CUPS AS CUPSP WITH (NOLOCK) ON CUPSP.ID=SODP.CUPSEntityId
   LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR  ON DESCR.Id  =SOD.CUPSEntityContractDescriptionId  AND SOD.CUPSEntityId=DESCR.CUPSEntityId 
   LEFT JOIN Contract.ContractDescriptions AS CD  ON CD.ID=DESCR.ContractDescriptionId
   LEFT JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =ISNULL(SODS.CostCenterId,SOD.CostCenterId)
   LEFT JOIN GeneralLedger.MainAccounts AS MA  ON MA.Id =ISNULL(SODS.IncomeMainAccountId,SOD.IncomeMainAccountId)
   LEFT JOIN Billing.ServiceOrderDetail AS SODI  ON SODI.Id =SOD.IncludeServiceOrderDetailId 
   LEFT JOIN CTE_CUPS AS CUPSI WITH (NOLOCK) ON CUPSI.ID=SODI.CUPSEntityId
   LEFT JOIN DBO.SEGusuaru SUSO WITH (NOLOCK) ON SUSO.CODUSUARI = SO.CreationUser
   LEFT JOIN dbo.INPROFSAL AS MED  ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode  
   LEFT JOIN dbo.INESPECIA AS ESPMED  ON ESPMED.CODESPECI = SOD.PerformsProfessionalSpecialty 
   LEFT JOIN Common.ThirdParty AS TPT  ON TPT.Id =SOD.PerformsHealthProfessionalThirdPartyId 
   --LEFT JOIN dbo.INPROFSAL AS MEDQX  ON MEDQX.CODPROSAL = SODS.PerformsHealthProfessionalCode
   --LEFT JOIN dbo.INESPECIA AS ESPQX  ON ESPQX.CODESPECI = MEDQX.CODESPEC1
   LEFT JOIN Contract.DefinitionRateDetail DRD ON DRD.ID=SOD.DefinitionRateDetailId
   LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =  ISNULL(SODP.PerformsHealthProfessionalCode,ISNULL(MED.CODPROSAL,TPT.Nit)) AND HPC.LiquidateDefault = 1
   LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
   LEFT JOIN CTE_USUARIO_LECTURA_IMAGENES IMA ON cast(IMA.NUMINGRES as char)=cast(UNI.INGRESO as char) and IMA.GENSERVICEORDER=SO.ID AND IMA.CODSERIPS=CUPS.CODE
--)

----SELECT * FROM CTE_PAQUETE_UNICO

--SELECT * 
--FROM CTE_FACTURA_DETALLADA --where NIT='900156264'
----where ingreso='94515     '
--UNION ALL
--SELECT *
--FROM CTE_SERVICIOS_PAQUETE_DETALLADO --where NIT='900156264'
----where ingreso='94515     '


----SET STATISTICS TIME OFF;
--GO


