-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_TERAPIAS_TABLERO_ORDENADAS_POR_REALIZAR_DIA_ACTUAL_V2
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE PROCEDURE [Report].[IND_SP_V2_EHR_TERAPIAS_TABLERO_ORDENADAS_POR_REALIZAR_DIA_ACTUAL_V2]
AS

WITH CTE_CENSO
AS
(
  SELECT DISTINCT C.IPCODPACI,C.NUMINGRES,C.CODICAMAS ,FUN.UFUDESCRI AS 'UNIDAD FUNCIONAL',A.NUMCAMHOS 'CAMA',G.DESTIPEST 'TIPO ESTANCIA'
  FROM dbo.CHCAMASHO A
  INNER JOIN DBO.INUNIFUNC FUN ON A.UFUCODIGO =FUN.UFUCODIGO 
  INNER JOIN dbo.CHREGESTA C ON A.CODICAMAS=C.CODICAMAS AND C.REGESTADO = 1 
  LEFT JOIN dbo.CHTIPESTA G ON G.CODTIPEST=C.CODTIPEST
),
------------------------**********************************************************************************************************************------------------
CTE_CUPS
AS
(
  SELECT CUPS.Id,CUPS.Code [CUPS], CUPS.Description [DESCRIPCION CUPS], 
  CASE CUPS.ServiceType WHEN 1 then 'LABORATORIOS' WHEN 2 then 'PATOLOGIAS' WHEN 3 then 'IMAGENES DIAGNOSTICAS' WHEN 4 then 'PROCEDIMIENTOS NO QX'
  WHEN 5 then 'PROCEDIMIENTOS QX' WHEN 6 then 'INTERCONSULTAS'WHEN 7 then 'NINGUNO'WHEN 8 then 'CONSULTA EXTERNA' WHEN 9 THEN 'HEMOCOMPONENTES' ELSE 'OTROS' END AS 'TIPO SERVICIO',
  BG.CODE 'CODIGO FACTURACION',BG.NAME 'GRUPO FACTURACION',BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION',CGC.Code 'CODIGO GRUPO',CGC.Name 'GRUPO CUPS',
  CSG.CODE 'CODIGO SUBGRUPO',CSG.Name  'SUBGRUPO CUPS',
  CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
  ELSE 'N/A' END 'OBTENER CC',CUPS.ServiceType
  FROM Contract.CUPSEntity AS CUPS WITH (NOLOCK)
  INNER JOIN Billing.BillingGroup as BG WITH (NOLOCK) ON BG.Id=CUPS.BillingGroupId
  INNER JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=CUPS.BillingConceptId
  INNER JOIN Contract.CupsSubgroup AS CSG WITH (NOLOCK) ON CSG.Id =CUPS.CUPSSubGroupId
  INNER JOIN Contract.CupsGroup AS CGC WITH (NOLOCK) ON CGC.Id =CSG.CupsGroupId
 ),
------------------------*************************************************************************************************************************------------------
CTE_ORDENES_TERAPIAS
AS
(
 SELECT '1. ORDEN MEDICA' 'FUNCIONAL',CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO', CEN.[UNIDAD FUNCIONAL],CEN.[CAMA],
 TER.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE',TER.NUMINGRES 'INGRESO',TER.NUMEFOLIO 'FOLIO',CAST(TER.FECORDMED AS DATE) 'FECHA ORDEN', TER.CODSERIPS 'CUPS',
 CUPS.[DESCRIPCION CUPS], CD.Name 'DESCRIPCION RELACIONADA',TER.CANSERIPS 'CANTIDAD ORDENADA',ISNULL(G.[CANTIDAD REALIZADA],0) [CANTIDAD REALIZADA],
 MED.NOMMEDICO 'PROFESIONAL',ESP.DESESPECI 'ESPECIALIDAD',
 DIA.CODDIAGNO 'CIE10', DIA.NOMDIAGNO 'DIAGNOSTICO',TP.Nit AS NIT,TP.Name AS ENTIDAD, CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION]
 FROM DBO.HCORDPRON TER WITH (NOLOCK)
 INNER JOIN CTE_CENSO AS CEN WITH (NOLOCK) ON CEN.NUMINGRES=TER.NUMINGRES
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = TER.CODPROSAL
 INNER JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
 INNER JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=TER.CODDIAGNO
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 LEFT JOIN
 (
  SELECT TER.IPCODPACI,TER.NUMINGRES,TER.CODSERIPS,IDDESCRIPCIONRELACIONADA,COUNT(TER.CODSERIPS) 'CANTIDAD REALIZADA' --CAST(TER.FECREGSIS AS DATE)
  FROM dbo.HCPROCTER TER
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
  INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
  WHERE IM.Agrupador='Terapias' AND CAST(TER.FECHISPAC AS DATE) = CAST(GETDATE() AS DATE)
  GROUP BY TER.IPCODPACI,TER.NUMINGRES,CAST(TER.FECREGSIS AS DATE),TER.CODSERIPS,IDDESCRIPCIONRELACIONADA
 ) AS G ON G.IPCODPACI=TER.IPCODPACI AND G.NUMINGRES=TER.NUMINGRES AND G.CODSERIPS=TER.CODSERIPS AND G.IDDESCRIPCIONRELACIONADA=TER.IDDESCRIPCIONRELACIONADA
 WHERE IM.Agrupador='Terapias' AND TER.MANEXTPRO=0 AND TER.ESTSERIPS NOT IN (2,5) AND CAST(TER.FECORDMED AS DATE) = CAST(GETDATE() AS DATE)
)

SELECT * FROM CTE_ORDENES_TERAPIAS
--WHERE INGRESO='124013' AND CUPS='931001              '
ORDER BY [UNIDAD FUNCIONAL],[INGRESO],[FECHA ORDEN] DESC


--SELECT * FROM DBO.HCORDPRON
