-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_CAUSACION_PRODUCTIVIDAD_NEUMOLOGIA_V2
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE PROCEDURE [Report].[IND_SP_V2_EHR_CAUSACION_PRODUCTIVIDAD_NEUMOLOGIA_V2]

@FECHAINI AS DATE,
@FECHAFIN AS DATE

--DECLARE @FECHAINI AS DATE='2024-10-01';
--DECLARE @FECHAFIN AS DATE='2024-10-31';

AS
WITH CTE_CUPS
AS
(
   SELECT CUPS.Id,CUPS.Code [CUPS], CUPS.Description [DESCRIPCION CUPS], 
   CASE CUPS.ServiceType WHEN 1 then 'LABORATORIOS' WHEN 2 then 'PATOLOGIAS' WHEN 3 then 'IMAGENES DIAGNOSTICAS' WHEN 4 then 'PROCEDIMIENTOS NO QX'
   WHEN 5 then 'PROCEDIMIENTOS QX' WHEN 6 then 'INTERCONSULTAS'WHEN 7 then 'NINGUNO'WHEN 8 then 'CONSULTA EXTERNA' WHEN 9 THEN 'HEMOCOMPONENTES' ELSE 'OTROS' END AS 'TIPO SERVICIO',
   BG.CODE 'CODIGO FACTURACION',BG.NAME 'GRUPO FACTURACION',BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION',CGC.Code 'CODIGO GRUPO',CGC.Name 'GRUPO CUPS',
   CSG.CODE 'CODIGO SUBGRUPO',CSG.Name  'SUBGRUPO CUPS',
   CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
   ELSE 'N/A' END 'OBTENER CC',CUPS.ServiceType
   FROM Contract.CUPSEntity AS CUPS WITH (NOLOCK)
   INNER JOIN Billing.BillingGroup as BG WITH (NOLOCK) ON BG.Id=CUPS.BillingGroupId
   INNER JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=CUPS.BillingConceptId
   INNER JOIN Contract.CupsSubgroup AS CSG WITH (NOLOCK) ON CSG.Id =CUPS.CUPSSubGroupId
   INNER JOIN Contract.CupsGroup AS CGC WITH (NOLOCK) ON CGC.Id =CSG.CupsGroupId
   --where --CUPS.Description like '%ECOGRAFI%' and 
   --CUPS.Code='332902'
 ),

CTE_IPS
AS
(
 SELECT IPS.ID,IPS.Code 'CODIGO SERVICIO IPS',IPS.Name 'NOMBRE SERVICIO IPS', CASE IPS.ServiceClass WHEN 1 THEN 'Ninguno' WHEN 2 THEN 'Cirujano' WHEN 3 THEN 'Anestesiologo' WHEN 4 THEN 'Ayudante' 
 WHEN 5 THEN 'Derecho Sala' WHEN 6 THEN 'Materiales Sutura'    WHEN 7 THEN 'Instrumentacion Quirurgica' ELSE 'Ninguno' end 'TIPO SERVICIO IPS',
 BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION IPS QX',
 CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
 ELSE 'N/A' END 'OBTENER CC'
 FROM Contract.IPSService IPS WITH (NOLOCK)
 LEFT JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=IPS.BillingConceptId
),

CTE_DATOS_INGRESO_UNICO
AS
(
 SELECT DISTINCT G.NUMINGRES
 FROM
  (
   SELECT DISTINCT NUMINGRES
   FROM dbo.ADCONCOEX A 
   WHERE CODESPECI IN ('430','939') AND CAST(A.IPFECHCIT AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
   UNION ALL 
   SELECT DISTINCT NUMINGRES
   FROM dbo.AMBORDOTROSPRO A 
   WHERE CODESPECI IN ('430','939') AND CAST(A.FECHAREG AS DATE) BETWEEN @FECHAINI AND @FECHAFIN
  ) AS G
),

CTE_CONSULTAS
AS
(
 SELECT DISTINCT '1. HISTORIA CLINICA' 'FUENTE','AMBULATORIO' 'AMBITO',IM.GrupoCausacion 'TIPO SERVICIO',
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CC'WHEN '2'  THEN 'CE'WHEN '3'  THEN 'TI'WHEN '4'  THEN 'RC'WHEN '5'  THEN 'PA'WHEN '6'  THEN 'AS'WHEN '7'  THEN 'MS'
 WHEN '8'  THEN 'NU'WHEN '9'  THEN 'NV'WHEN '10' THEN 'CD'WHEN '11' THEN 'SC'WHEN '12' THEN 'PE' WHEN '13' THEN 'PT'WHEN '14' THEN 'DE'WHEN '15' THEN 'SI'END AS [TIPO IDENTIFICACION],
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CEDULA DE CIUDADANIA' WHEN '2'  THEN 'CEDULA DE EXTRANJERIA' WHEN '3'  THEN 'TARJETA DE IDENTIDAD' WHEN '4'  THEN 'REGISTRO CIVIL' 
 WHEN '5'  THEN 'PASAPORTE' WHEN '6'  THEN 'ADULTO SIN IDENTIFICACION' WHEN '7'  THEN 'MENOR SIN IDENTIFICACION' WHEN '8'  THEN 'NUMERO UNICO DE IDENTIFICACION'
 WHEN '9'  THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO' WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
 WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION'END AS [DESCRIPCION IDENTIFICACION],
 A.IPCODPACI 'IDENTIFICACION',CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
 CONCAT(FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.IPFECHCIT) AS FLOAT) / 365), ' años, ',FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.IPFECHCIT) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.IPFECHCIT) AS FLOAT) / 365)) * 12),' meses,',FLOOR(((((CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.IPFECHCIT) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.IPFECHCIT) AS FLOAT) / 365)) * 12) - FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.IPFECHCIT) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.IPFECHCIT) AS FLOAT) / 365)) * 12)) * (365 / 12))), ' días') AS [EDAD],
 CASE PAC.IPSEXOPAC WHEN '1' THEN 'H' WHEN '2' THEN 'M' END AS [CODIGO SEXO],CASE PAC.IPSEXOPAC WHEN '1' THEN 'HOMBRE' WHEN '2' THEN 'MUJER' END AS [SEXO],
 UPPER(PAC.IPPRIAPEL) 'PRIMER APELLIDO',UPPER(PAC.IPSEGAPEL) 'SEGUNDO APELLIDO',UPPER(PAC.IPPRINOMB) 'PRIMER NOMBRE',UPPER(PAC.IPSEGNOMB) 'SEGUNDO NOMBRE',
 PAC.IPNOMCOMP 'NOMBRE COMPLETO PACIENTE',TP.Nit AS NIT,TP.Name AS ENTIDAD,HA.HealthEntityCode 'CODIGO EAPB',CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],
 CASE HA.EntityType WHEN 1 THEN 'EPS Contributivo' WHEN 2 THEN 'EPS Subsidiado' WHEN 3 THEN 'ET Vinculados Municipios' WHEN 4 THEN 'ET Vinculados Departamentos'
 WHEN 5 THEN 'ARL Riesgos Laborales' WHEN 6 THEN 'MP Medicina Prepagada' WHEN 7 THEN 'IPS Privada' WHEN 8 THEN 'IPS Publica' WHEN 9 THEN 'Regimen Especial'
 WHEN 10 THEN 'Accidentes de transito' WHEN 11 THEN 'Fosyga' WHEN 12 THEN 'Otros' ELSE 'Otros' end [REGIMEN],
 A.NUMINGRES 'INGRESO', HIS.NUMEFOLIO 'FOLIO',CAST(A.IPFECHCIT AS DATE) 'FECHA ATENCION',CUPS.[CUPS],CUPS.[DESCRIPCION CUPS],
 ISNULL(G2.[DESCRIPCION RELACIONADA],CUPS.[DESCRIPCION CUPS]) 'DESCRIPCION RELACIONADA',G2.InvoicedQuantity 'CANTIDAD',
 CASE A.CONESTADO WHEN 1 THEN 'SIN ATENDER' WHEN 2 THEN 'AUSENTE/ANULADO' WHEN 3 THEN 'ATENDIDO' WHEN 4 THEN 'EN SALA' WHEN 5 THEN 'EN CONSULTORIO' END 'ESTADO',
 UNI.UFUDESCRI 'UNIDAD FUNCIONAL',HIS.CODPROSAL 'ID PROFESIONAL ATENDIO',MED.NOMMEDICO 'PROFESIONAL ATENDIO',
 DIA.CODDIAGNO 'CIE10 ORDEN',DIA.NOMDIAGNO 'DIAGNOSTICO ORDEN',--ISNULL(G2.[NRO ORDEN],ISNULL(G4.[NRO ORDEN],G5.[NRO ORDEN])) 'NRO ORDEN FACTURACION',
 CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO' WHEN 'F' THEN 'FACTURADO' WHEN 'A' THEN 'ANULADO' WHEN 'C' THEN 'CERRADO' WHEN 'P' THEN 'PARCIAL' ELSE 'OTRO' END 'ESTADO INGRESO',
 ISNULL(G2.[NRO FACTURA],ISNULL(G4.[NRO FACTURA],G5.[NRO FACTURA])) [NRO FACTURA],ISNULL(G2.[FECHA FACTURA],ISNULL(G4.[FECHA FACTURA],G5.[FECHA FACTURA])) [FECHA FACTURA]
 FROM dbo.ADCONCOEX A WITH (NOLOCK)
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON A.IPCODPACI = PAC.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON A.NUMINGRES=ING.NUMINGRES
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = A.UFUCODIGO
 INNER JOIN
 (
  SELECT A.CODCONCEC,A.IPCODPACI,A.NUMINGRES,A.NUMCONCIT,A.IDHCHISPACA,ROW_NUMBER() OVER (PARTITION BY A.IPCODPACI,A.NUMCONCIT  
  ORDER BY CASE WHEN A.IDHCHISPACA IS NOT NULL THEN A.IDHCHISPACA ELSE A.CODCONCEC END DESC) AS RowNum
  FROM dbo.ADCONCOEX A WITH (NOLOCK)
 ) AS G ON G.RowNum=1 AND G.CODCONCEC=A.CODCONCEC
  LEFT JOIN dbo.AGASICITA AS CTE WITH (NOLOCK) ON CTE.CODAUTONU=A.NUMCONCIT
  LEFT JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=CTE.CODSERIPS
  LEFT JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
  LEFT JOIN DBO.HCHISPACA HIS WITH (NOLOCK) ON HIS.ID=A.IDHCHISPACA
  LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = HIS.CODPROSAL
  LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
  LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=HIS.CODDIAGNO
  LEFT JOIN 
  (
   SELECT SOD.ID,SOD.ServiceOrderId,SOD.ControlExternalConsultationCode, SO.AdmissionNumber,CUPS.[CUPS],I.InvoiceNumber 'NRO FACTURA',SO.CODE 'NRO ORDEN',
   CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',SOD.Packaging,SOD.SettlementType,SOD.InvoicedQuantity,CD.Name 'DESCRIPCION RELACIONADA'
   FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
   INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
   INNER JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =SOD.CostCenterId
   INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
   INNER JOIN CTE_DATOS_INGRESO_UNICO AS ING WITH (NOLOCK) ON cast(ING.NUMINGRES as char)=cast(SO.AdmissionNumber as char)
   LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.Id
   LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
   LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
   LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
   LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.Id =ID.ServiceOrderDetailId
   LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =SOD.CUPSEntityContractDescriptionId  AND SOD.CUPSEntityId=DESCR.CUPSEntityId 
   LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
   where SO.Status<>3 and SOD.RecordType=1 AND IM.Agrupador IN('Neumologia') and IM.ReportType in ('Causacion') AND 
   IM.GrupoCausacion in ('CONSULTA','INTERCONSULTA','JUNTA MEDICA') --,'CONSULTA MEDICIONES','ESPIROMETRIA','PRUEBA MEDICIONES'
   ) AS G2 ON G2.ControlExternalConsultationCode= A.CODCONCEC AND G2.AdmissionNumber=A.NUMINGRES 
   LEFT JOIN
  (
   SELECT DISTINCT I.AdmissionNumber,I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA' ,CUPS.[CUPS] ,SOD.InvoicedQuantity,SO.Code [NRO ORDEN]
   FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN CTE_DATOS_INGRESO_UNICO AS ING WITH (NOLOCK) ON cast(ING.NUMINGRES as char)=cast(I.AdmissionNumber as char)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.ID=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
   where SO.Status<>3  AND I.STATUS=1 AND SOD.RecordType=1 AND IM.Agrupador IN('Neumologia') and IM.ReportType in ('Causacion') AND 
   IM.GrupoCausacion in ('CONSULTA','INTERCONSULTA','JUNTA MEDICA')
  ) AS G4 ON CAST(G4.AdmissionNumber AS CHAR)=CAST(A.NUMINGRES AS CHAR) AND G4.[CUPS]=CTE.CODSERIPS
  LEFT JOIN
  (
   SELECT DISTINCT I.AdmissionNumber,I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA' ,CUPS.[CUPS] ,SOD.InvoicedQuantity,SO.Code [NRO ORDEN]
   FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN CTE_DATOS_INGRESO_UNICO AS ING WITH (NOLOCK) ON cast(ING.NUMINGRES as char)=cast(I.AdmissionNumber as char)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.ID=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
   where SO.Status<>3  AND I.STATUS=1 AND SOD.RecordType=1 AND IM.Agrupador IN('Neumologia') and IM.ReportType in ('Causacion') AND 
   IM.GrupoCausacion in ('CONSULTA','INTERCONSULTA','JUNTA MEDICA')
  ) AS G5 ON CAST(G5.AdmissionNumber AS CHAR)=CAST(A.NUMINGRES AS CHAR)

 WHERE A.CODESPECI IN ('430','939') AND CAST(A.IPFECHCIT AS DATE) BETWEEN @FECHAINI AND @FECHAFIN AND IM.Agrupador='Neumologia' and IM.ReportType in ('Causacion') and
 IM.GrupoCausacion in ('CONSULTA','INTERCONSULTA','JUNTA MEDICA') --'CONSULTA MEDICIONES','ESPIROMETRIA','PRUEBA MEDICIONES'
),

CTE_PROCEDIMIENTOS_NEUMO
AS
(
SELECT DISTINCT '1. HISTORIA CLINICA' 'FUENTE','AMBULATORIO' 'AMBITO',IM.GrupoCausacion 'TIPO SERVICIO',
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CC'WHEN '2'  THEN 'CE'WHEN '3'  THEN 'TI'WHEN '4'  THEN 'RC'WHEN '5'  THEN 'PA'WHEN '6'  THEN 'AS'WHEN '7'  THEN 'MS'
 WHEN '8'  THEN 'NU'WHEN '9'  THEN 'NV'WHEN '10' THEN 'CD'WHEN '11' THEN 'SC'WHEN '12' THEN 'PE' WHEN '13' THEN 'PT'WHEN '14' THEN 'DE'WHEN '15' THEN 'SI'END AS [TIPO IDENTIFICACION],
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CEDULA DE CIUDADANIA' WHEN '2'  THEN 'CEDULA DE EXTRANJERIA' WHEN '3'  THEN 'TARJETA DE IDENTIDAD' WHEN '4'  THEN 'REGISTRO CIVIL' 
 WHEN '5'  THEN 'PASAPORTE' WHEN '6'  THEN 'ADULTO SIN IDENTIFICACION' WHEN '7'  THEN 'MENOR SIN IDENTIFICACION' WHEN '8'  THEN 'NUMERO UNICO DE IDENTIFICACION'
 WHEN '9'  THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO' WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
 WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION'END AS [DESCRIPCION IDENTIFICACION],
 A.IPCODPACI 'IDENTIFICACION',CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
 CONCAT(FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.FECHAREG) AS FLOAT) / 365), ' años, ',FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.FECHAREG) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.FECHAREG) AS FLOAT) / 365)) * 12),' meses,',FLOOR(((((CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.FECHAREG) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.FECHAREG) AS FLOAT) / 365)) * 12) - FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.FECHAREG) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,A.FECHAREG) AS FLOAT) / 365)) * 12)) * (365 / 12))), ' días') AS [EDAD],
 CASE PAC.IPSEXOPAC WHEN '1' THEN 'H' WHEN '2' THEN 'M' END AS [CODIGO SEXO],CASE PAC.IPSEXOPAC WHEN '1' THEN 'HOMBRE' WHEN '2' THEN 'MUJER' END AS [SEXO],
 UPPER(PAC.IPPRIAPEL) 'PRIMER APELLIDO',UPPER(PAC.IPSEGAPEL) 'SEGUNDO APELLIDO',UPPER(PAC.IPPRINOMB) 'PRIMER NOMBRE',UPPER(PAC.IPSEGNOMB) 'SEGUNDO NOMBRE',
 PAC.IPNOMCOMP 'NOMBRE COMPLETO PACIENTE',TP.Nit AS NIT,TP.Name AS ENTIDAD,HA.HealthEntityCode 'CODIGO EAPB',CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],
 CASE HA.EntityType WHEN 1 THEN 'EPS Contributivo' WHEN 2 THEN 'EPS Subsidiado' WHEN 3 THEN 'ET Vinculados Municipios' WHEN 4 THEN 'ET Vinculados Departamentos'
 WHEN 5 THEN 'ARL Riesgos Laborales' WHEN 6 THEN 'MP Medicina Prepagada' WHEN 7 THEN 'IPS Privada' WHEN 8 THEN 'IPS Publica' WHEN 9 THEN 'Regimen Especial'
 WHEN 10 THEN 'Accidentes de transito' WHEN 11 THEN 'Fosyga' WHEN 12 THEN 'Otros' ELSE 'Otros' end [REGIMEN],
 A.NUMINGRES 'INGRESO', HIS.NUMEFOLIO 'FOLIO',CAST(A.FECHAREG AS DATE) 'FECHA ATENCION',CUPS.[CUPS],CUPS.[DESCRIPCION CUPS],
 ISNULL(G3.[DESCRIPCION RELACIONADA],CUPS.[DESCRIPCION CUPS]) 'DESCRIPCION RELACIONADA',ISNULL(G3.InvoicedQuantity,ISNULL(G4.InvoicedQuantity,1)) 'CANTIDAD',
 IIF(HIS.CODPROSAL IS NOT NULL,'ATENDIDO',IIF(G3.[NRO FACTURA] IS NOT NULL OR G4.[NRO FACTURA] IS NOT NULL,'ATENDIDO',
 CASE A.ESTADO WHEN 1 THEN 'SIN ATENDER' WHEN 2 THEN 'ATENDIDO' WHEN 3 THEN 'ATENDIDO' WHEN 5 THEN 'AUSENTE/ANULADO' WHEN 4 THEN 'OTRO' ELSE 'OTRO' END)) 'ESTADO',

 UNI.UFUDESCRI 'UNIDAD FUNCIONAL',HIS.CODPROSAL 'ID PROFESIONAL ATENDIO',MED.NOMMEDICO 'PROFESIONAL ATENDIO',
 DIA.CODDIAGNO 'CIE10 ORDEN',DIA.NOMDIAGNO 'DIAGNOSTICO ORDEN',--ISNULL(G3.[NRO ORDEN],ISNULL(G4.[NRO ORDEN],G5.[NRO ORDEN])) 'NRO ORDEN FACTURACION',
 CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO' WHEN 'F' THEN 'FACTURADO' WHEN 'A' THEN 'ANULADO' WHEN 'C' THEN 'CERRADO' WHEN 'P' THEN 'PARCIAL' ELSE 'OTRO' END 'ESTADO INGRESO',
 ISNULL(G3.[NRO FACTURA],ISNULL(G4.[NRO FACTURA],G5.[NRO FACTURA])) [NRO FACTURA],ISNULL(G3.[FECHA FACTURA],ISNULL(G4.[FECHA FACTURA],G5.[FECHA FACTURA])) [FECHA FACTURA]
FROM dbo.AMBORDOTROSPRO A WITH (NOLOCK)
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON A.IPCODPACI = PAC.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON A.NUMINGRES=ING.NUMINGRES
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = A.UFUCODIGO
 LEFT JOIN
 (
   SELECT PRO.NUMINGRES,PRO.IPCODPACI,PRO.IDHCHISPACA,PRO.NUMEFOLIO,PRO.CODPROSAL,PRO.FECHAREGISTRO, CU.CODSERIPS
   FROM DBO.HCPLAOTRPROC PRO
   INNER JOIN
   (
     SELECT MAX(PRO.ID) ID,PRO.NUMINGRES
     FROM DBO.HCPLAOTRPROC PRO
     INNER JOIN CTE_DATOS_INGRESO_UNICO AS UNI ON UNI.NUMINGRES=PRO.NUMINGRES
     GROUP BY PRO.NUMINGRES
   ) AS G ON G.ID=PRO.ID AND G.NUMINGRES=PRO.NUMINGRES
   INNER JOIN DBO.HCPLAOTRPROCUPS AS CU ON CU.IDHCPLAOTRPROC=PRO.ID
  ) AS G2 ON G2.NUMINGRES=A.NUMINGRES AND G2.CODSERIPS=A.CODSERIPS
  LEFT JOIN dbo.ADCONCOEX CON ON CON.NUMCONCIT=A.IDCITA
  LEFT JOIN dbo.AGASICITA AS CTE WITH (NOLOCK) ON CTE.CODAUTONU=A.IDCITA
  LEFT JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=A.CODSERIPS
  LEFT JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
  LEFT JOIN DBO.HCHISPACA HIS WITH (NOLOCK) ON HIS.ID=G2.IDHCHISPACA
  LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = HIS.CODPROSAL
  LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
  LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=HIS.CODDIAGNO
  LEFT JOIN 
  (
   SELECT SOD.ID,SOD.ServiceOrderId,SOD.ControlExternalConsultationCode, SO.AdmissionNumber,CUPS.[CUPS],I.InvoiceNumber 'NRO FACTURA',SO.CODE 'NRO ORDEN',
   CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',SOD.Packaging,SOD.SettlementType,SOD.InvoicedQuantity,CD.Name 'DESCRIPCION RELACIONADA'
   FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
   INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
   INNER JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =SOD.CostCenterId
   INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
   INNER JOIN CTE_DATOS_INGRESO_UNICO AS ING WITH (NOLOCK) ON cast(ING.NUMINGRES as char)=cast(SO.AdmissionNumber as char)
   LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.Id
   LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
   LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
   LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
   LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.Id =ID.ServiceOrderDetailId
   LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =SOD.CUPSEntityContractDescriptionId  AND SOD.CUPSEntityId=DESCR.CUPSEntityId 
   LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
   where SO.Status<>3  AND SOD.RecordType=1 AND IM.Agrupador IN('Neumologia') and IM.ReportType in ('Causacion') AND 
   IM.GrupoCausacion in ('CONSULTA MEDICIONES','ESPIROMETRIA','PRUEBA MEDICIONES','BIOPSIAS','TORACENTESIS','PLEURODESIS QUIMICA','BRONCOSCOPIA','EXTRACCION DE CUERPO')
   ) AS G3 ON G3.ControlExternalConsultationCode= CON.CODCONCEC AND G3.AdmissionNumber=A.NUMINGRES 
  LEFT JOIN
  (
   SELECT DISTINCT I.AdmissionNumber,I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA' ,CUPS.[CUPS] ,SOD.InvoicedQuantity,SO.CODE 'NRO ORDEN'
   FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN CTE_DATOS_INGRESO_UNICO AS ING WITH (NOLOCK) ON cast(ING.NUMINGRES as char)=cast(I.AdmissionNumber as char)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.ID=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
   where SO.Status<>3  AND I.STATUS=1 AND SOD.RecordType=1 AND IM.Agrupador IN('Neumologia') and IM.ReportType in ('Causacion') AND 
   IM.GrupoCausacion in ('CONSULTA MEDICIONES','ESPIROMETRIA','PRUEBA MEDICIONES','BIOPSIAS','TORACENTESIS','PLEURODESIS QUIMICA','BRONCOSCOPIA','EXTRACCION DE CUERPO')
  ) AS G4 ON G4.AdmissionNumber=A.NUMINGRES AND G4.[CUPS]=A.CODSERIPS
  LEFT JOIN
  (
   SELECT DISTINCT I.AdmissionNumber,I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA' ,CUPS.[CUPS] ,SOD.InvoicedQuantity,SO.CODE 'NRO ORDEN'
   FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN CTE_DATOS_INGRESO_UNICO AS ING WITH (NOLOCK) ON cast(ING.NUMINGRES as char)=cast(I.AdmissionNumber as char)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.ID=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
   where SO.Status<>3  AND I.STATUS=1 AND SOD.RecordType=1 AND IM.Agrupador IN('Neumologia') and IM.ReportType in ('Causacion') AND 
   IM.GrupoCausacion in ('CONSULTA MEDICIONES','ESPIROMETRIA','PRUEBA MEDICIONES','BIOPSIAS','TORACENTESIS','PLEURODESIS QUIMICA','BRONCOSCOPIA','EXTRACCION DE CUERPO')
  ) AS G5 ON CAST(G5.AdmissionNumber AS CHAR)=CAST(A.NUMINGRES AS CHAR)
 
 
 WHERE A.CODESPECI IN ('430','939') AND CAST(A.FECHAREG AS DATE) BETWEEN @FECHAINI AND @FECHAFIN AND IM.Agrupador='Neumologia' and IM.ReportType in ('Causacion') and
 IM.GrupoCausacion in ('CONSULTA MEDICIONES','ESPIROMETRIA','PRUEBA MEDICIONES','BIOPSIAS','TORACENTESIS','PLEURODESIS QUIMICA','BRONCOSCOPIA', 'EXTRACCION DE CUERPO')

)
SELECT * FROM CTE_PROCEDIMIENTOS_NEUMO
--WHERE INGRESO IN ('5DA6373F42')
UNION ALL 
SELECT * FROM CTE_CONSULTAS
--WHERE INGRESO IN ('5DA6373F42')

--SELECT * FROM dbo.ADCONCOEX A WHERE CODESPECI IN ('430','939')

--SELECT 'AMBORDOTROSPRO',* FROM dbo.AMBORDOTROSPRO WHERE CODESPECI IN ('430','939')

--SELECT * FROM REPORT.TableSocieties WHERE Agrupador='Neumologia'