-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_FAC_REPORTE_HOSPITALARIO_PENDIENTE_POR_RECONOCER_VALORADO
-- Extracted by Fabric SQL Extractor SPN v3.9.0





CREATE PROCEDURE [Report].[IND_SP_V2_FAC_REPORTE_HOSPITALARIO_PENDIENTE_POR_RECONOCER_VALORADO]
AS

SELECT 'HOSPITALARIO' 'TYPE', 'HEMOCOMPONENTES' 'TIPO', HOS.NUMINGRES 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO]  ,HOS.ENTIDAD ,HOS.[GRUPO ATENCION]  ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA',ISNULL(HOS.CANSERIPS*HEM.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_HEMOCOMPONENTES_POR_RECONOCER_HOS HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_HEMOCOMPONENTES_POR_RECONOCER_VALORIZADO AS HEM ON HEM.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'HOSPITALARIO' 'TYPE', 'IMAGENES' 'TIPO', HOS.NUMINGRES 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA]  , YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA',ISNULL(HOS.CANSERIPS*IMG.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_IMAGENES_POR_RECONOCER_HOS HOS
LEFT JOIN  [Report].[View_V2_FAC_REPORTE_IMAGENES_POR_RECONOCER_VALORIZADO] AS IMG ON IMG.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'HOSPITALARIO' 'TYPE', 'LABORATORIOS' 'TIPO', HOS.NUMINGRES 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA',ISNULL(HOS.CANSERIPS*LAB.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_LABORATORIOS_POR_RECONOCER_HOS HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_LABORATORIOS_POR_RECONOCER_VALORIZADO AS LAB ON LAB.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'HOSPITALARIO' 'TYPE', 'PATOLOGIAS' 'TIPO', HOS.NUMINGRES 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA',ISNULL(HOS.CANSERIPS*PAT.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_PATOLOGIAS_POR_RECONOCER_HOS HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_PATOLOGIAS_POR_RECONOCER_VALORIZADO AS PAT ON PAT.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'HOSPITALARIO' 'TYPE', 'TERAPIAS' 'TIPO', HOS.NUMINGRES 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA',ISNULL(HOS.CANSERIPS*TER.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_TERAPIAS_POR_RECONOCER_HOS HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_TERAPIAS_POR_RECONOCER_VALORIZADO AS TER ON TER.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'HOSPITALARIO' 'TYPE', 'INTERCONSULTAS' 'TIPO', HOS.NUMINGRES 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA],YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA',ISNULL(HOS.CANSERIPS*INTE.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_INTERCONSULTAS_POR_RECONOCER_HOS HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_INTERCONSULTAS_POR_RECONOCER_VALORIZADO AS INTE ON INTE.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'HOSPITALARIO' 'TYPE', 'PROCEDIMIENTOS_NO_QX' 'TIPO', HOS.NUMINGRES 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA',ISNULL(HOS.CANSERIPS*NOQX.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_PROCEDIMIENTOS_NO_QX_POR_RECONOCER_HOS HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_PROCEDIMIENTOS_NO_QX_POR_RECONOCER_VALORIZADO AS NOQX ON NOQX.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'HOSPITALARIO' 'TYPE', 'GASES' 'TIPO', HOS.NUMINGRES 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION]  ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA], YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA',ISNULL(HOS.CANSERIPS*GAS.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_GASES_POR_RECONOCER_HOS HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_GASES_POR_RECONOCER_VALORIZADO AS GAS ON GAS.[CUPS]=HOS.CODSERIPS
UNION ALL

SELECT 'HOSPITALARIO' 'TYPE', 'ESTANCIAS' 'TIPO', HOS.NUMINGRES 'INGRESO', HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE',HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.CANSERIPS 'CANTIDAD ORDENADA' ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL' ,HOS.NUMCAMHOS 'CAMA',HOS.FECEGRESO 'FECHA EGRESO',   
'HOSPITALARIO' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA] , YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',
CAST(HOS.[FECHA REALIZADO MINIMA] AS DATE) 'FECHA REALIZADO MINIMA' ,CAST(HOS.[FECHA REALIZADO MAXIMA] AS DATE) 'FECHA REALIZADO MAXIMA',ISNULL(HOS.CANSERIPS*EST.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_ESTANCIAS_POR_RECONOCER_HOS HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_ESTANCIAS_POR_RECONOCER_VALORIZADO AS EST ON EST.[CUPS]=HOS.CODSERIPS
