-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_CAUSACION_PRODUCTIVIDAD_IMAGENOLOGIA_V2
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE PROCEDURE [Report].[IND_SP_V2_EHR_CAUSACION_PRODUCTIVIDAD_IMAGENOLOGIA_V2]

@FECHAINI AS DATE,
@FECHAFIN AS DATE

--DECLARE @FECHAINI AS DATE='2024-10-01';
--DECLARE @FECHAFIN AS DATE='2024-10-31';

AS

WITH CTE_CUPS
AS
(
   SELECT CUPS.Id,CUPS.Code [CUPS], CUPS.Description [DESCRIPCION CUPS], 
   CASE CUPS.ServiceType WHEN 1 then 'LABORATORIOS' WHEN 2 then 'PATOLOGIAS' WHEN 3 then 'IMAGENES DIAGNOSTICAS' WHEN 4 then 'PROCEDIMIENTOS NO QX'
   WHEN 5 then 'PROCEDIMIENTOS QX' WHEN 6 then 'INTERCONSULTAS'WHEN 7 then 'NINGUNO'WHEN 8 then 'CONSULTA EXTERNA' WHEN 9 THEN 'HEMOCOMPONENTES' ELSE 'OTROS' END AS 'TIPO SERVICIO',
   BG.CODE 'CODIGO FACTURACION',BG.NAME 'GRUPO FACTURACION',BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION',CGC.Code 'CODIGO GRUPO',CGC.Name 'GRUPO CUPS',
   CSG.CODE 'CODIGO SUBGRUPO',CSG.Name  'SUBGRUPO CUPS',
   CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
   ELSE 'N/A' END 'OBTENER CC',CUPS.ServiceType
   FROM Contract.CUPSEntity AS CUPS WITH (NOLOCK)
   INNER JOIN Billing.BillingGroup as BG WITH (NOLOCK) ON BG.Id=CUPS.BillingGroupId
   INNER JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=CUPS.BillingConceptId
   INNER JOIN Contract.CupsSubgroup AS CSG WITH (NOLOCK) ON CSG.Id =CUPS.CUPSSubGroupId
   INNER JOIN Contract.CupsGroup AS CGC WITH (NOLOCK) ON CGC.Id =CSG.CupsGroupId
   --where --CUPS.Description like '%ECOGRAFI%' and 
   --CUPS.Code='881701'
 ),
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CTE_IPS
AS
(
 SELECT IPS.ID,IPS.Code 'CODIGO SERVICIO IPS',IPS.Name 'NOMBRE SERVICIO IPS', CASE IPS.ServiceClass WHEN 1 THEN 'Ninguno' WHEN 2 THEN 'Cirujano' WHEN 3 THEN 'Anestesiologo' WHEN 4 THEN 'Ayudante' 
 WHEN 5 THEN 'Derecho Sala' WHEN 6 THEN 'Materiales Sutura'    WHEN 7 THEN 'Instrumentacion Quirurgica' ELSE 'Ninguno' end 'TIPO SERVICIO IPS',
 BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION IPS QX',IPS.Code,IPS.Name,
 CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
 ELSE 'N/A' END 'OBTENER CC'
 FROM Contract.IPSService IPS WITH (NOLOCK)
 LEFT JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=IPS.BillingConceptId
),
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CTE_DATOS_INGRESO_UNICO
AS
(
  SELECT DISTINCT G.NUMINGRES FROM
  ( 
    SELECT DISTINCT TER.NUMINGRES 
    FROM dbo.HCORDIMAG TER WITH (NOLOCK)
    INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
    INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
    WHERE IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion') AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN  AND TER.MANEXTPRO=0
    UNION ALL
    SELECT DISTINCT TER.NUMINGRES 
    FROM dbo.AMBORDIMA TER WITH (NOLOCK)
    INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
    INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
    WHERE IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion') AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN 
	UNION ALL
    SELECT DISTINCT TER.NUMINGRES 
    FROM dbo.AMBORDOTROSPRO TER WITH (NOLOCK)
    INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
    INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
    WHERE IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion') AND CAST(TER.FECHAREG AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
 ) AS G
),
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CTE_DATOS_PACIENTES_UNICOS
 AS
 (
  SELECT DISTINCT G.IPCODPACI FROM
  (  
   SELECT DISTINCT IPCODPACI
   FROM dbo.HCORDIMAG TER
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
   WHERE IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion') AND TER.ESTSERIPS<>5 AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN --AND TER.MANEXTPRO=0
   UNION ALL
   SELECT DISTINCT IPCODPACI
   FROM dbo.AMBORDIMA TER
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
   WHERE IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion') AND TER.ESTSERIPS<>5 AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN --AND TER.MANEXTPRO=0
   UNION ALL
   SELECT DISTINCT IPCODPACI
   FROM dbo.AMBORDOTROSPRO TER
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
   WHERE IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion') AND  CAST(TER.FECHAREG AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN --AND TER.MANEXTPRO=0
  ) AS G
),
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CTE_DATOS_INDIRA
AS
(
 SELECT IND.NumeroAccesoINDIRA,IND.TipoOrden,IND.NumeroOrdenVIE,IND.IdentificacionPaciente,IND.NombreCompletoPaciente,IND.IngresoVIE,
 IND.[Fecha de toma estudio],IND.FechaLecturaConfirmada,IND.IdentificacionUsuarioValida,IND.UsuarioValidaLectura,IND.FechaOrdenMedica,IND.FechaInicialCita,
 IND.CodigoServico,IND.DescripcionServicio,IND.Modalidad,IND.NombreModalidad,IND.Cantidad,IND.EstadoLectura 'ESTADO LECTURA INDIRA',IND.EstadoOrden 'ESTADO ORDEN INDIRA'
 FROM Report.TableIndira IND
 INNER JOIN CTE_DATOS_INGRESO_UNICO AS ING ON ING.NUMINGRES=IND.IngresoVIE
 LEFT JOIN
 (
    SELECT NumeroOrdenVIE,IngresoVIE,CodigoServico,MAX(FechaLecturaConfirmada) FechaLectura
    FROM Report.TableIndira  --WHERE NumeroOrdenVIE=176070
    GROUP BY NumeroOrdenVIE,IngresoVIE,CodigoServico
 ) AS G ON G.NumeroOrdenVIE=IND.NumeroOrdenVIE AND G.IngresoVIE=IND.IngresoVIE AND G.CodigoServico=IND.CodigoServico AND G.FechaLectura=IND.FechaLecturaConfirmada
),
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CTE_DATOS_CARGOS_IMAGENES
AS
(
  SELECT DISTINCT ISNULL(RC.AdmissionNumber,SO.AdmissionNumber) 'INGRESO', NULL 'FOLIO',CAST(SOD.ServiceDate AS DATE) 'FECHA ORDEN/EJECUCION',CUPS.[CUPS],
  CUPS.[DESCRIPCION CUPS],CD.Name 'DESCRIPCION RELACIONADA',isnull(ID.InvoicedQuantity,SOD.InvoicedQuantity)'CANTIDAD',SO.AdmissionNumber,FU.Name 'UNIDAD FUNCIONAL',
  SOD.ID IDSERVICEORDERDETAIL,SO.ID GENSERVICEORDER,I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',SOD.Packaging,SOD.SettlementType,
  FU.Name 'UNIDAD CARGO',CC.NAME 'CENTRO DE COSTO CARGO',SO.STATUS 'ESTADO ORDEN',SOD.ControlExternalConsultationCode,SO.CODE,I.ID GENINVOICEID,
  DIA.CODDIAGNO 'CIE10 ORDEN',DIA.NOMDIAGNO 'DIAGNOSTICO ORDEN',ID.id 'ID_HIJOS',CC.ID ID_CC
  FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =SOD.CostCenterId
  INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  INNER JOIN CTE_DATOS_INGRESO_UNICO AS ING ON ING.NUMINGRES=cast(SO.AdmissionNumber as char)
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.Id
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.Id =ID.ServiceOrderDetailId
  LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =SOD.CUPSEntityContractDescriptionId  AND SOD.CUPSEntityId=DESCR.CUPSEntityId 
  LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
  LEFT JOIN DBO.ADINGRESO AS INGR ON INGR.NUMINGRES= ISNULL(RC.AdmissionNumber, SO.AdmissionNumber)
  LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=ISNULL(I.OutputDiagnosis,ISNULL(INGR.CODDIAEGR,INGR.CODDIAING))
  where SO.STATUS<>3 AND SOD.IsDelete=0 and SOD.RecordType=1 AND IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion')
),
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CTE_FACTURAS_INTERVENCIONISMO
AS
(

SELECT DISTINCT CAST(I.AdmissionNumber AS CHAR) INGRESO,I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA' ,CUPS.[CUPS] ,SOD.InvoicedQuantity,
   SOD.Packaging,SOD.SettlementType,FU.Name 'UNIDAD CARGO',CC.NAME 'CENTRO DE COSTO CARGO',SO.STATUS 'ESTADO ORDEN',SO.CODE,SOD.ID 'IDSERVICEORDERDETAIL',
   SOD.ControlExternalConsultationCode,DIA.CODDIAGNO 'CIE10 ORDEN',DIA.NOMDIAGNO 'DIAGNOSTICO ORDEN',ID.id 'ID_HIJOS',CC.ID ID_CC
   FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN dbo.ADINGRESO AS INGR WITH (NOLOCK) ON CAST(I.AdmissionNumber AS CHAR)=CAST(INGR.NUMINGRES AS CHAR)
   INNER JOIN CTE_DATOS_INGRESO_UNICO AS ING WITH (NOLOCK) ON ING.NUMINGRES=cast(I.AdmissionNumber as char)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.ID=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
   INNER JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =SOD.CostCenterId
   INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
   LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=I.OutputDiagnosis
   where SO.Status<>3 AND SOD.IsDelete=0 AND I.STATUS=1 AND SOD.RecordType=1 AND IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion') AND IM.GrupoCausacion in ('INTERVENCIONISMO')
  -- and i.AdmissionNumber='87D0D7EEC7'
),
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CTE_FACTURAS_INGRESO_INTERVENCIONISMO
AS
(
   SELECT DISTINCT I.AdmissionNumber,I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA' ,CUPS.[CUPS] ,SOD.InvoicedQuantity,SO.Code [NRO ORDEN]
   FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN CTE_DATOS_INGRESO_UNICO AS ING WITH (NOLOCK) ON ING.NUMINGRES =cast(I.AdmissionNumber as char)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.ID=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
   where SO.Status<>3  AND I.STATUS=1 AND SOD.RecordType=1 AND IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion') AND 
   IM.GrupoCausacion in ('INTERVENCIONISMO')
   --AND I.AdmissionNumber='2D2AD2D414'
),

 ---*********************************************************************************************************************************************************************---
 ---*********************************************************RADIOLOGIA CONVENCIONAL*************************************************************************************---
 ---*********************************************************************************************************************************************************************---

CTE_DATOS_ORDENES_IMAGENES_AMBULATORIO
AS
(
 SELECT DISTINCT '1. HISTORIA CLINICA' 'FUENTE','AMBULATORIO' 'AMBITO',IM.AgrupadorImagen 'AGRUPADOR IMAGENES',IM.GrupoCausacion 'TIPO IMAGEN',
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CC'WHEN '2'  THEN 'CE'WHEN '3'  THEN 'TI'WHEN '4'  THEN 'RC'WHEN '5'  THEN 'PA'WHEN '6'  THEN 'AS'WHEN '7'  THEN 'MS'
 WHEN '8'  THEN 'NU'WHEN '9'  THEN 'NV'WHEN '10' THEN 'CD'WHEN '11' THEN 'SC'WHEN '12' THEN 'PE' WHEN '13' THEN 'PT'WHEN '14' THEN 'DE'WHEN '15' THEN 'SI'END AS [TIPO IDENTIFICACION],
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CEDULA DE CIUDADANIA' WHEN '2'  THEN 'CEDULA DE EXTRANJERIA' WHEN '3'  THEN 'TARJETA DE IDENTIDAD' WHEN '4'  THEN 'REGISTRO CIVIL' 
 WHEN '5'  THEN 'PASAPORTE' WHEN '6'  THEN 'ADULTO SIN IDENTIFICACION' WHEN '7'  THEN 'MENOR SIN IDENTIFICACION' WHEN '8'  THEN 'NUMERO UNICO DE IDENTIFICACION'
 WHEN '9'  THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO' WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
 WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION'END AS [DESCRIPCION IDENTIFICACION],
 TER.IPCODPACI 'IDENTIFICACION',CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
 CONCAT(FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365), ' años, ',FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12),' meses,',FLOOR(((((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12) - FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12)) * (365 / 12))), ' días') AS [EDAD],
 CASE PAC.IPSEXOPAC WHEN '1' THEN 'H' WHEN '2' THEN 'M' END AS [CODIGO SEXO],CASE PAC.IPSEXOPAC WHEN '1' THEN 'HOMBRE' WHEN '2' THEN 'MUJER' END AS [SEXO],
 UPPER(PAC.IPPRIAPEL) 'PRIMER APELLIDO',UPPER(PAC.IPSEGAPEL) 'SEGUNDO APELLIDO',UPPER(PAC.IPPRINOMB) 'PRIMER NOMBRE',UPPER(PAC.IPSEGNOMB) 'SEGUNDO NOMBRE',
 PAC.IPNOMCOMP 'NOMBRE COMPLETO PACIENTE',TP.Nit AS NIT,TP.Name AS ENTIDAD,HA.HealthEntityCode 'CODIGO EAPB',CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],
 CASE HA.EntityType WHEN 1 THEN 'EPS Contributivo' WHEN 2 THEN 'EPS Subsidiado' WHEN 3 THEN 'ET Vinculados Municipios' WHEN 4 THEN 'ET Vinculados Departamentos'
 WHEN 5 THEN 'ARL Riesgos Laborales' WHEN 6 THEN 'MP Medicina Prepagada' WHEN 7 THEN 'IPS Privada' WHEN 8 THEN 'IPS Publica' WHEN 9 THEN 'Regimen Especial'
 WHEN 10 THEN 'Accidentes de transito' WHEN 11 THEN 'Fosyga' WHEN 12 THEN 'Otros' ELSE 'Otros' end [REGIMEN],
 TER.NUMINGRES 'INGRESO', 'N/A' 'FOLIO',CAST(TER.FECORDMED AS DATE) 'FECHA ORDEN',TER.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS],
 ISNULL(CD.Name,CUPS.[DESCRIPCION CUPS]) 'DESCRIPCION RELACIONADA','N/A' 'CODIGO DETALLE QX','N/A' 'DESCRIPCION DETALLE QX',TER.CANSERIPS 'CANTIDAD',
 IIF((CAR.[ESTADO ORDEN]=3),'ANULADO',CASE ESTSERIPS WHEN 1 THEN 'SOLICITADO' WHEN 2 THEN 'ESTUDIO REALIZADO' WHEN 3 THEN 'ESTUDIO REALIZADO' WHEN 4 THEN 'ESTUDIO REALIZADO' WHEN 5 THEN 'REMITIDO'
 WHEN 6 THEN 'ANULADO' WHEN 7 THEN 'EXTRAMURAL' ELSE 'OTROS' END) 'ESTADO',
 UNI.UFUDESCRI 'UNIDAD FUNCIONAL',TER.CODPROSAL 'ID PROFESIONAL ORDEN',MED.NOMMEDICO 'PROFESIONAL ORDEN',ESP.DESESPECI 'ESPECIALIDAD ORDEN' ,
 MLEC.CODPROSAL 'ID PROFESIONAL LECTURA',MLEC.NOMMEDICO 'PROFESIONAL LECTURA',ESPL.DESESPECI 'ESPECIALIDAD LECTURA',
 CAST(ISNULL(G3.FECHA_HORA_ASIGNACION,ISNULL(CIT.FECREGSIS,ISNULL(IND.FechaInicialCita,TER.FECORDMED))) AS DATE) 'FECHA CITA',CAST(ISNULL(IND.[Fecha de toma estudio],TER.FECRECEXA) AS DATE) 'FECHA DE TOMA',
 CAST(ISNULL(IND.FechaLecturaConfirmada,TER.FECHLECT) AS DATE) 'FECHA LECTURA',DATEDIFF(DAY,CAST(ISNULL(CIT.FECREGSIS,ISNULL(IND.FechaInicialCita,TER.FECORDMED)) AS DATE), 
 CAST(ISNULL(IND.[Fecha de toma estudio], TER.FECRECEXA) AS DATE)) AS  'TEMPO DE ESPERA FEC CITA VS FEC TOMA',
 DIA.CODDIAGNO 'CIE10 ORDEN',DIA.NOMDIAGNO 'DIAGNOSTICO ORDEN',TER.AUTO,CAR.CODE 'NRO ORDEN FACTURACION',
 CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO' WHEN 'F' THEN 'FACURACION' WHEN 'A' THEN 'ANULADO' WHEN 'C' THEN 'CERRADO' WHEN 'P' THEN 'PARCIAL' ELSE 'OTRO' END 'ESTADO INGRESO',
 IIF(TER.GENINVOICEID IS NOT NULL,TER.GENINVOICE,CAR.[NRO FACTURA] ) 'NRO FACTURA',
 IIF(TER.GENINVOICEID IS NOT NULL,CAST(I.InvoiceDate AS DATE),CAST(CAR.[FECHA FACTURA] AS DATE)) 'FECHA FACTURA',
 CASE CAR.Packaging WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'ES PAQUETE', CASE CAR.SettlementType WHEN 1 THEN 'NO' WHEN 2 THEN 'NO' WHEN 3 THEN 'SI' 
 WHEN 4 THEN 'NO' END 'INCLUIDO OTRO SERVICIO',CAR.[UNIDAD CARGO], CAR.[CENTRO DE COSTO CARGO],
 TER.NUMCONCIT 'IDCITA',IM.Agrupador 'AGRUPADOR', 0 'VALOR UNITARIO',0 'VALOR TOTAL',IND.NumeroAccesoINDIRA 'NRO INDIRA',IND.[ESTADO LECTURA INDIRA], IND.[ESTADO ORDEN INDIRA],
 CAST(TER.FECORDMED AS DATE) 'FECHA BUSQUEDA'
 FROM dbo.AMBORDIMA TER WITH (NOLOCK)
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = TER.UFUCODIGO
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = TER.CODPROSAL
 LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=TER.NUMINGRES AND IND.NumeroOrdenVIE=TER.AUTO
 LEFT JOIN dbo.INPROFSAL AS MLEC WITH (NOLOCK) ON MLEC.CODPROSAL=ISNULL(TER.MEDREALEC,IND.IdentificacionUsuarioValida)
 LEFT JOIN dbo.INESPECIA AS ESPL WITH (NOLOCK) ON ESPL.CODESPECI =MLEC.CODESPEC1
 LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =MLEC.CODPROSAL AND HPC.LiquidateDefault = 1
 LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
 LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.Id=TER.GENINVOICEID and I.STATUS<>2
 LEFT JOIN dbo.AGASICITA CIT WITH (NOLOCK) ON CIT.CODAUTONU=TER.NUMCONCIT
 LEFT JOIN CTE_DATOS_CARGOS_IMAGENES as CAR ON CAR.GENSERVICEORDER=TER.GENSERVICEORDER AND CAR.[CUPS]=TER.CODSERIPS AND TER.NUMINGRES=CAR.INGRESO
 LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=ISNULL(ING.CODDIAEGR,ISNULL(I.OutputDiagnosis,ISNULL(CAR.[CIE10 ORDEN],ING.CODDIAING)))
 LEFT JOIN 
 (
  SELECT DISTINCT SER.NUMERO_DOCUMENTO,SER.FECHA_HORA_ASIGNACION,SER.FECHA_HORA_USR_SOLICTA,SER.FECHA_HORA_CITA,ID_CITA_SERVINTE
  FROM [dbo].[CitasServinte] SER
  INNER JOIN CTE_DATOS_PACIENTES_UNICOS PAC ON PAC.IPCODPACI=SER.NUMERO_DOCUMENTO
  INNER JOIN
   (SELECT NUMERO_DOCUMENTO,CONVERT(VARCHAR(16), CAST(FECHA_HORA_CITA AS DATETIME), 20) 'FECHA_HORA_CITA',
    CONVERT(VARCHAR(16), CAST(MAX(FECHA_HORA_ASIGNACION) AS DATETIME),20) 'FECHA_REGISTRO' 
	 FROM [dbo].[CitasServinte]
	 WHERE  COD_MOTIVO_CANCELACION IS NULL --AND NUMERO_DOCUMENTO='52197408'
	 GROUP BY NUMERO_DOCUMENTO,CONVERT(VARCHAR(16),CAST(FECHA_HORA_CITA AS DATETIME),20)
	) AS G ON G.NUMERO_DOCUMENTO=SER.NUMERO_DOCUMENTO AND G.[FECHA_HORA_CITA]=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_CITA AS DATETIME),20) AND
	  G.FECHA_REGISTRO=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_ASIGNACION AS DATETIME),20)
  ) AS G3 ON G3.NUMERO_DOCUMENTO=CIT.IPCODPACI AND CONVERT(VARCHAR(16),CIT.FECHORAIN,20)=CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_CITA AS DATETIME),20)
 WHERE IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion') AND GrupoCausacion in ('RADIOGRAFIAS','FLUOROSCOPIA','TOMOGRAFIAS','ECOGRAFIAS') AND
 TER.ESTSERIPS<>5 AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
),

---*******************************************************************************************************************************************************************---
---*****************************************************INTERVENCIONISMOS PROCEDIMIENTOS******************************************************************************---
---*******************************************************************************************************************************************************************---

CTE_DATOS_ORDENES_IMAGENES_INTERVENCIONISMO_AMBULATORIO
AS
(
 SELECT DISTINCT '1. HISTORIA CLINICA' 'FUENTE','AMBULATORIO' 'AMBITO',IM.AgrupadorImagen 'AGRUPADOR IMAGENES',IM.GrupoCausacion 'TIPO IMAGEN',
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CC'WHEN '2'  THEN 'CE'WHEN '3'  THEN 'TI'WHEN '4'  THEN 'RC'WHEN '5'  THEN 'PA'WHEN '6'  THEN 'AS'WHEN '7'  THEN 'MS'
 WHEN '8'  THEN 'NU'WHEN '9'  THEN 'NV'WHEN '10' THEN 'CD'WHEN '11' THEN 'SC'WHEN '12' THEN 'PE' WHEN '13' THEN 'PT'WHEN '14' THEN 'DE'WHEN '15' THEN 'SI'END AS [TIPO IDENTIFICACION],
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CEDULA DE CIUDADANIA' WHEN '2'  THEN 'CEDULA DE EXTRANJERIA' WHEN '3'  THEN 'TARJETA DE IDENTIDAD' WHEN '4'  THEN 'REGISTRO CIVIL' 
 WHEN '5'  THEN 'PASAPORTE' WHEN '6'  THEN 'ADULTO SIN IDENTIFICACION' WHEN '7'  THEN 'MENOR SIN IDENTIFICACION' WHEN '8'  THEN 'NUMERO UNICO DE IDENTIFICACION'
 WHEN '9'  THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO' WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
 WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION'END AS [DESCRIPCION IDENTIFICACION],
 TER.IPCODPACI 'IDENTIFICACION',CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
 CONCAT(FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECHAREG) AS FLOAT) / 365), ' años, ',FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECHAREG) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECHAREG) AS FLOAT) / 365)) * 12),' meses,',FLOOR(((((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECHAREG) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECHAREG) AS FLOAT) / 365)) * 12) - FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECHAREG) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECHAREG) AS FLOAT) / 365)) * 12)) * (365 / 12))), ' días') AS [EDAD],
 CASE PAC.IPSEXOPAC WHEN '1' THEN 'H' WHEN '2' THEN 'M' END AS [CODIGO SEXO],CASE PAC.IPSEXOPAC WHEN '1' THEN 'HOMBRE' WHEN '2' THEN 'MUJER' END AS [SEXO],
 UPPER(PAC.IPPRIAPEL) 'PRIMER APELLIDO',UPPER(PAC.IPSEGAPEL) 'SEGUNDO APELLIDO',UPPER(PAC.IPPRINOMB) 'PRIMER NOMBRE',UPPER(PAC.IPSEGNOMB) 'SEGUNDO NOMBRE',
 PAC.IPNOMCOMP 'NOMBRE COMPLETO PACIENTE',TP.Nit AS NIT,TP.Name AS ENTIDAD,HA.HealthEntityCode 'CODIGO EAPB',CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],
 CASE HA.EntityType WHEN 1 THEN 'EPS Contributivo' WHEN 2 THEN 'EPS Subsidiado' WHEN 3 THEN 'ET Vinculados Municipios' WHEN 4 THEN 'ET Vinculados Departamentos'
 WHEN 5 THEN 'ARL Riesgos Laborales' WHEN 6 THEN 'MP Medicina Prepagada' WHEN 7 THEN 'IPS Privada' WHEN 8 THEN 'IPS Publica' WHEN 9 THEN 'Regimen Especial'
 WHEN 10 THEN 'Accidentes de transito' WHEN 11 THEN 'Fosyga' WHEN 12 THEN 'Otros' ELSE 'Otros' end [REGIMEN],
 TER.NUMINGRES 'INGRESO', 'N/A' 'FOLIO',CAST(TER.FECHAREG AS DATE) 'FECHA ORDEN',TER.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS],
 ISNULL(CD.Name,CUPS.[DESCRIPCION CUPS]) 'DESCRIPCION RELACIONADA',
 ISNULL(IPSQXf.Code,isnull(IPSQXc.Code,'N/A')) AS 'CODIGO DETALLE QX' ,
 REPLACE(SUBSTRING(ISNULL(RTRIM(IPSQXf.Name),isnull(RTRIM(IPSQXc.Name),'N/A')),1,60), ',', '')  AS 'DESCRIPCION DETALLE QX',TER.CANTIDAD 'CANTIDAD', 
 IIF((FAC.[ESTADO ORDEN]=3 OR CAR.[ESTADO ORDEN]=3),'ANULADO',CASE TER.ESTADO WHEN 1 THEN 'SOLICITADO' WHEN 2 THEN 'ESTUDIO REALIZADO' WHEN 3 THEN 'ESTUDIO REALIZADO' WHEN 4 THEN 'ESTUDIO REALIZADO' WHEN 5 THEN 'ANULADO'
 ELSE 'OTROS' END) 'ESTADO',
 UNI.UFUDESCRI 'UNIDAD FUNCIONAL',TER.CODPROSAL 'ID PROFESIONAL ORDEN',MED.NOMMEDICO 'PROFESIONAL ORDEN',ESP.DESESPECI 'ESPECIALIDAD ORDEN' ,
 MLEC.CODPROSAL 'ID PROFESIONAL LECTURA',MLEC.NOMMEDICO 'PROFESIONAL LECTURA',ESPL.DESESPECI 'ESPECIALIDAD LECTURA',
 CAST(ISNULL(G3.FECHA_HORA_ASIGNACION,ISNULL(CIT.FECREGSIS,TER.FECHAREG)) AS DATE) 'FECHA CITA',CAST(TER.FECHAPRO AS DATE) 'FECHA DE TOMA',
 CAST(TER.FECHAPRO AS DATE) 'FECHA LECTURA',
 DATEDIFF(DAY,CAST(ISNULL(CIT.FECREGSIS,TER.FECHAREG) AS DATE),CAST(TER.FECHAPRO AS DATE)) AS  'TEMPO DE ESPERA FEC CITA VS FEC TOMA',
 DIA.CODDIAGNO 'CIE10 ORDEN',DIA.NOMDIAGNO 'DIAGNOSTICO ORDEN',TER.ID, ISNULL(FAC.CODE,CAR.CODE) 'NRO ORDEN FACTURACION',
 CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO' WHEN 'F' THEN 'FACURACION' WHEN 'A' THEN 'ANULADO' WHEN 'C' THEN 'CERRADO' WHEN 'P' THEN 'PARCIAL' ELSE 'OTRO' END 'ESTADO INGRESO',
 ISNULL(FAC.[NRO FACTURA],CAR.[NRO FACTURA]) [NRO FACTURA],CAST(ISNULL(FAC.[FECHA FACTURA],CAR.[FECHA FACTURA]) AS DATE) 'FECHA FACTURA',
 CASE ISNULL(FAC.Packaging,CAR.Packaging) WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'ES PAQUETE', 
 CASE ISNULL(FAC.SettlementType,CAR.SettlementType) WHEN 1 THEN 'NO' WHEN 2 THEN 'NO' WHEN 3 THEN 'SI' WHEN 4 THEN 'NO' END 'INCLUIDO OTRO SERVICIO',
 ISNULL(FAC.[UNIDAD CARGO],CAR.[UNIDAD CARGO]) [UNIDAD CARGO], 
 ISNULL(CC.NAME,ISNULL(FAC.[CENTRO DE COSTO CARGO],CAR.[CENTRO DE COSTO CARGO])) [CENTRO DE COSTO CARGO],
 TER.IDCITA 'IDCITA',IM.Agrupador 'AGRUPADOR', 0 'VALOR UNITARIO',0 'VALOR TOTAL',NULL 'NRO INDIRA',NULL [ESTADO LECTURA INDIRA], NULL [ESTADO ORDEN INDIRA],
 CAST(TER.FECHAREG AS DATE) 'FECHA BUSQUEDA'--,TER.GENSERVICEORDER,ISNULL(FAC.IDSERVICEORDERDETAIL,CAR.IDSERVICEORDERDETAIL) IDDETALLE
 FROM dbo.AMBORDOTROSPRO TER
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]  --,'GUIA - FLUROSCOPIA','GUIA - TOMOGRAFIA','GUIA - ECOGRAFIAS'
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = TER.UFUCODIGO
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = TER.CODPROSAL
 LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 --LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=TER.NUMINGRES AND IND.NumeroOrdenVIE=TER.AUTO
 LEFT JOIN dbo.INPROFSAL AS MLEC WITH (NOLOCK) ON MLEC.CODPROSAL=TER.MEDICOREALI
 LEFT JOIN dbo.INESPECIA AS ESPL WITH (NOLOCK) ON ESPL.CODESPECI =MLEC.CODESPEC1
 LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK) ON HPC.HealthProfessionalCode =MLEC.CODPROSAL AND HPC.LiquidateDefault = 1
 LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
 LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.Id=TER.GENINVOICEID AND I.STATUS <>2
  LEFT JOIN dbo.AGASICITA CIT WITH (NOLOCK) ON CIT.CODAUTONU=TER.IDCITA
 LEFT JOIN CTE_DATOS_CARGOS_IMAGENES as CAR ON TER.NUMINGRES=CAR.INGRESO AND CAR.ControlExternalConsultationCode=TER.GENSERVICEORDER AND CAR.[CUPS]=TER.CODSERIPS 
 LEFT JOIN CTE_FACTURAS_INTERVENCIONISMO as FAC ON TER.NUMINGRES=FAC.INGRESO AND TER.CODSERIPS=FAC.CUPS
 LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=ISNULL(ING.CODDIAEGR,ISNULL(I.OutputDiagnosis,ISNULL(CAR.[CIE10 ORDEN],ISNULL(FAC.[CIE10 ORDEN],ING.CODDIAING))))
 LEFT JOIN Billing.InvoiceDetailSurgical AS IDSc WITH (NOLOCK) ON IDSc.InvoiceDetailId =CAR.Id_Hijos AND IDSc.OnlyMedicalFees = '0'
 LEFT JOIN Billing.InvoiceDetailSurgical AS IDSf WITH (NOLOCK) ON IDSf.InvoiceDetailId =FAC.Id_Hijos AND IDSf.OnlyMedicalFees = '0'
 LEFT JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =ISNULL(IDSf.CostCenterId,ISNULL(IDSc.CostCenterId,ISNULL(FAC.[ID_CC],CAR.[ID_CC])))
 LEFT JOIN CTE_IPS AS IPSQXc WITH (NOLOCK) ON IPSQXc.Id =IDSc.IPSServiceId
 LEFT JOIN CTE_IPS AS IPSQXf WITH (NOLOCK) ON IPSQXf.Id =IDSf.IPSServiceId
 --LEFT JOIN CTE_FACTURAS_INGRESO_INTERVENCIONISMO AS FACIND ON CAST(FACIND.AdmissionNumber AS CHAR)=TER.NUMINGRES
 LEFT JOIN 
 (
  SELECT DISTINCT SER.NUMERO_DOCUMENTO,SER.FECHA_HORA_ASIGNACION,SER.FECHA_HORA_USR_SOLICTA,SER.FECHA_HORA_CITA,ID_CITA_SERVINTE
  FROM [dbo].[CitasServinte] SER
  INNER JOIN CTE_DATOS_PACIENTES_UNICOS PAC ON PAC.IPCODPACI=SER.NUMERO_DOCUMENTO
  INNER JOIN
   (SELECT NUMERO_DOCUMENTO,CONVERT(VARCHAR(16), CAST(FECHA_HORA_CITA AS DATETIME), 20) 'FECHA_HORA_CITA',
    CONVERT(VARCHAR(16), CAST(MAX(FECHA_HORA_ASIGNACION) AS DATETIME),20) 'FECHA_REGISTRO' 
	 FROM [dbo].[CitasServinte]
	 WHERE  COD_MOTIVO_CANCELACION IS NULL --AND NUMERO_DOCUMENTO='52197408'
	 GROUP BY NUMERO_DOCUMENTO,CONVERT(VARCHAR(16),CAST(FECHA_HORA_CITA AS DATETIME),20)
	) AS G ON G.NUMERO_DOCUMENTO=SER.NUMERO_DOCUMENTO AND G.[FECHA_HORA_CITA]=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_CITA AS DATETIME),20) AND
	  G.FECHA_REGISTRO=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_ASIGNACION AS DATETIME),20)
  ) AS G3 ON G3.NUMERO_DOCUMENTO=CIT.IPCODPACI AND CONVERT(VARCHAR(16),CIT.FECHORAIN,20)=CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_CITA AS DATETIME),20)

 WHERE IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion') AND GrupoCausacion in ('INTERVENCIONISMO')
 AND CAST(TER.FECHAREG AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
 ---------------------------------------------------GUIAS PARA INTERVENCIONISMO---------------------------------------------------------------------------------------
 UNION ALL
 ---------------------------------------------------GUIAS PARA INTERVENCIONISMO---------------------------------------------------------------------------------------
 SELECT DISTINCT '1. HISTORIA CLINICA' 'FUENTE','AMBULATORIO' 'AMBITO',IM.AgrupadorImagen 'AGRUPADOR IMAGENES',IM.GrupoCausacion 'TIPO IMAGEN',
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CC'WHEN '2'  THEN 'CE'WHEN '3'  THEN 'TI'WHEN '4'  THEN 'RC'WHEN '5'  THEN 'PA'WHEN '6'  THEN 'AS'WHEN '7'  THEN 'MS'
 WHEN '8'  THEN 'NU'WHEN '9'  THEN 'NV'WHEN '10' THEN 'CD'WHEN '11' THEN 'SC'WHEN '12' THEN 'PE' WHEN '13' THEN 'PT'WHEN '14' THEN 'DE'WHEN '15' THEN 'SI'END AS [TIPO IDENTIFICACION],
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CEDULA DE CIUDADANIA' WHEN '2'  THEN 'CEDULA DE EXTRANJERIA' WHEN '3'  THEN 'TARJETA DE IDENTIDAD' WHEN '4'  THEN 'REGISTRO CIVIL' 
 WHEN '5'  THEN 'PASAPORTE' WHEN '6'  THEN 'ADULTO SIN IDENTIFICACION' WHEN '7'  THEN 'MENOR SIN IDENTIFICACION' WHEN '8'  THEN 'NUMERO UNICO DE IDENTIFICACION'
 WHEN '9'  THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO' WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
 WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION'END AS [DESCRIPCION IDENTIFICACION],
 TER.IPCODPACI 'IDENTIFICACION',CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
 CONCAT(FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365), ' años, ',FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12),' meses,',FLOOR(((((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12) - FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12)) * (365 / 12))), ' días') AS [EDAD],
 CASE PAC.IPSEXOPAC WHEN '1' THEN 'H' WHEN '2' THEN 'M' END AS [CODIGO SEXO],CASE PAC.IPSEXOPAC WHEN '1' THEN 'HOMBRE' WHEN '2' THEN 'MUJER' END AS [SEXO],
 UPPER(PAC.IPPRIAPEL) 'PRIMER APELLIDO',UPPER(PAC.IPSEGAPEL) 'SEGUNDO APELLIDO',UPPER(PAC.IPPRINOMB) 'PRIMER NOMBRE',UPPER(PAC.IPSEGNOMB) 'SEGUNDO NOMBRE',
 PAC.IPNOMCOMP 'NOMBRE COMPLETO PACIENTE',TP.Nit AS NIT,TP.Name AS ENTIDAD,HA.HealthEntityCode 'CODIGO EAPB',CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],
 CASE HA.EntityType WHEN 1 THEN 'EPS Contributivo' WHEN 2 THEN 'EPS Subsidiado' WHEN 3 THEN 'ET Vinculados Municipios' WHEN 4 THEN 'ET Vinculados Departamentos'
 WHEN 5 THEN 'ARL Riesgos Laborales' WHEN 6 THEN 'MP Medicina Prepagada' WHEN 7 THEN 'IPS Privada' WHEN 8 THEN 'IPS Publica' WHEN 9 THEN 'Regimen Especial'
 WHEN 10 THEN 'Accidentes de transito' WHEN 11 THEN 'Fosyga' WHEN 12 THEN 'Otros' ELSE 'Otros' end [REGIMEN],TER.NUMINGRES 'INGRESO', 'N/A' 'FOLIO',
 CAST(TER.FECORDMED AS DATE) 'FECHA ORDEN',TER.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS], ISNULL(CD.Name,CUPS.[DESCRIPCION CUPS]) 'DESCRIPCION RELACIONADA',
 'N/A' 'CODIGO DETALLE QX','N/A' 'DESCRIPCION DETALLE QX',TER.CANSERIPS 'CANTIDAD', 
 IIF((CAR.[ESTADO ORDEN]=3),'ANULADO',CASE ESTSERIPS WHEN 1 THEN 'SOLICITADO' WHEN 2 THEN 'ESTUDIO REALIZADO' WHEN 3 THEN 'ESTUDIO REALIZADO' WHEN 4 THEN 'ESTUDIO REALIZADO' WHEN 5 THEN 'REMITIDO'
 WHEN 6 THEN 'ANULADO' WHEN 7 THEN 'EXTRAMURAL' ELSE 'OTROS' END) 'ESTADO',
 UNI.UFUDESCRI 'UNIDAD FUNCIONAL',TER.CODPROSAL 'ID PROFESIONAL ORDEN',MED.NOMMEDICO 'PROFESIONAL ORDEN',ESP.DESESPECI 'ESPECIALIDAD ORDEN',
 MLEC.CODPROSAL 'ID PROFESIONAL LECTURA',MLEC.NOMMEDICO 'PROFESIONAL LECTURA',ESPL.DESESPECI 'ESPECIALIDAD LECTURA',
 CAST(ISNULL(G3.FECHA_HORA_ASIGNACION,ISNULL(CIT.FECREGSIS,ISNULL(IND.FechaInicialCita,TER.FECORDMED))) AS DATE) 'FECHA CITA',CAST(ISNULL(IND.[Fecha de toma estudio],TER.FECRECEXA) AS DATE) 'FECHA DE TOMA',
 CAST(ISNULL(IND.FechaLecturaConfirmada,TER.FECHLECT) AS DATE) 'FECHA LECTURA', DATEDIFF(DAY,CAST(ISNULL(CIT.FECREGSIS,ISNULL(IND.FechaInicialCita,TER.FECORDMED)) AS DATE), 
 CAST(ISNULL(IND.[Fecha de toma estudio], TER.FECRECEXA) AS DATE)) AS  'TEMPO DE ESPERA FEC CITA VS FEC TOMA',
 DIA.CODDIAGNO 'CIE10 ORDEN',DIA.NOMDIAGNO 'DIAGNOSTICO ORDEN',TER.AUTO,CAR.CODE 'NRO ORDEN FACTURACION',
 CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO' WHEN 'F' THEN 'FACURACION' WHEN 'A' THEN 'ANULADO' WHEN 'C' THEN 'CERRADO' WHEN 'P' THEN 'PARCIAL' ELSE 'OTRO' END 'ESTADO INGRESO',
 IIF(TER.GENINVOICEID IS NOT NULL,TER.GENINVOICE,CAR.[NRO FACTURA] ) 'NRO FACTURA',
 IIF(TER.GENINVOICEID IS NOT NULL,CAST(I.InvoiceDate AS DATE),CAST(CAR.[FECHA FACTURA] AS DATE)) 'FECHA FACTURA',
 CASE CAR.Packaging WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'ES PAQUETE', CASE CAR.SettlementType WHEN 1 THEN 'NO' WHEN 2 THEN 'NO' WHEN 3 THEN 'SI' 
 WHEN 4 THEN 'NO' END 'INCLUIDO OTRO SERVICIO',CAR.[UNIDAD CARGO], CAR.[CENTRO DE COSTO CARGO],
 TER.NUMCONCIT 'IDCITA',IM.Agrupador 'AGRUPADOR', 0 'VALOR UNITARIO',0 'VALOR TOTAL',IND.NumeroAccesoINDIRA 'NRO INDIRA',IND.[ESTADO LECTURA INDIRA], IND.[ESTADO ORDEN INDIRA],
 CAST(TER.FECORDMED AS DATE) 'FECHA BUSQUEDA'

 FROM dbo.AMBORDIMA TER WITH (NOLOCK)
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = TER.UFUCODIGO
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = TER.CODPROSAL
 LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=TER.NUMINGRES AND IND.NumeroOrdenVIE=TER.AUTO
 LEFT JOIN dbo.INPROFSAL AS MLEC WITH (NOLOCK) ON MLEC.CODPROSAL=ISNULL(TER.MEDREALEC,IND.IdentificacionUsuarioValida)
 LEFT JOIN dbo.INESPECIA AS ESPL WITH (NOLOCK) ON ESPL.CODESPECI =MLEC.CODESPEC1
 LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =MLEC.CODPROSAL AND HPC.LiquidateDefault = 1
 LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
 LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.Id=TER.GENINVOICEID AND I.STATUS<>2
 LEFT JOIN dbo.AGASICITA CIT WITH (NOLOCK) ON CIT.CODAUTONU=TER.NUMCONCIT
 LEFT JOIN CTE_DATOS_CARGOS_IMAGENES as CAR ON TER.NUMINGRES=CAR.INGRESO AND CAR.GENSERVICEORDER=TER.GENSERVICEORDER AND CAR.[CUPS]=TER.CODSERIPS 
 LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=ISNULL(ING.CODDIAEGR,ISNULL(I.OutputDiagnosis,ISNULL(CAR.[CIE10 ORDEN],ING.CODDIAING)))
 LEFT JOIN 
 (
  SELECT DISTINCT SER.NUMERO_DOCUMENTO,SER.FECHA_HORA_ASIGNACION,SER.FECHA_HORA_USR_SOLICTA,SER.FECHA_HORA_CITA,ID_CITA_SERVINTE
  FROM [dbo].[CitasServinte] SER
  INNER JOIN CTE_DATOS_PACIENTES_UNICOS PAC ON PAC.IPCODPACI=SER.NUMERO_DOCUMENTO
  INNER JOIN
   (SELECT NUMERO_DOCUMENTO,CONVERT(VARCHAR(16), CAST(FECHA_HORA_CITA AS DATETIME), 20) 'FECHA_HORA_CITA',
    CONVERT(VARCHAR(16), CAST(MAX(FECHA_HORA_ASIGNACION) AS DATETIME),20) 'FECHA_REGISTRO' 
	 FROM [dbo].[CitasServinte]
	 WHERE  COD_MOTIVO_CANCELACION IS NULL --AND NUMERO_DOCUMENTO='52197408'
	 GROUP BY NUMERO_DOCUMENTO,CONVERT(VARCHAR(16),CAST(FECHA_HORA_CITA AS DATETIME),20)
	) AS G ON G.NUMERO_DOCUMENTO=SER.NUMERO_DOCUMENTO AND G.[FECHA_HORA_CITA]=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_CITA AS DATETIME),20) AND
	  G.FECHA_REGISTRO=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_ASIGNACION AS DATETIME),20)
  ) AS G3 ON G3.NUMERO_DOCUMENTO=CIT.IPCODPACI AND CONVERT(VARCHAR(16),CIT.FECHORAIN,20)=CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_CITA AS DATETIME),20)

 WHERE IM.Agrupador IN('Imagenes') and IM.ReportType in ('Causacion') AND GrupoCausacion in ('GUIA - FLUROSCOPIA','GUIA - TOMOGRAFIA','GUIA - ECOGRAFIAS') AND
 TER.ESTSERIPS<>5 AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
)--,

SELECT * FROM CTE_DATOS_ORDENES_IMAGENES_AMBULATORIO --WHERE INGRESO='2D2AD2D414'
UNION ALL
SELECT * FROM CTE_DATOS_ORDENES_IMAGENES_INTERVENCIONISMO_AMBULATORIO --WHERE INGRESO='2D2AD2D414'

