-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_AGENDAMIENTO_CITAS_TOTAL_V3
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE PROCEDURE [Report].[IND_SP_V2_EHR_AGENDAMIENTO_CITAS_TOTAL_V3]
@FECHAINI DATE,
@FECHAFIN DATE
AS

--DECLARE @FECHAINI AS DATE='2024-10-01';
--DECLARE @FECHAFIN AS DATE='2024-10-31';

--SET STATISTICS TIME ON;

WITH CTE_CUPS
AS
(
   SELECT CUPS.Id,CUPS.Code [CUPS], CUPS.Description [DESCRIPCION CUPS], 
   CASE CUPS.ServiceType WHEN 1 then 'LABORATORIOS' WHEN 2 then 'PATOLOGIAS' WHEN 3 then 'IMAGENES DIAGNOSTICAS' WHEN 4 then 'PROCEDIMIENTOS NO QX'
   WHEN 5 then 'PROCEDIMIENTOS QX' WHEN 6 then 'INTERCONSULTAS'WHEN 7 then 'NINGUNO'WHEN 8 then 'CONSULTA EXTERNA' WHEN 9 THEN 'HEMOCOMPONENTES' ELSE 'OTROS' END AS 'TIPO SERVICIO',
   BG.CODE 'CODIGO FACTURACION',BG.NAME 'GRUPO FACTURACION',BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION',CGC.Code 'CODIGO GRUPO',CGC.Name 'GRUPO CUPS',
   CSG.CODE 'CODIGO SUBGRUPO',CSG.Name  'SUBGRUPO CUPS',
   CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
   ELSE 'N/A' END 'OBTENER CC',CUPS.ServiceType
   FROM Contract.CUPSEntity AS CUPS WITH (NOLOCK)
   INNER JOIN Billing.BillingGroup as BG WITH (NOLOCK) ON BG.Id=CUPS.BillingGroupId
   INNER JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=CUPS.BillingConceptId
   INNER JOIN Contract.CupsSubgroup AS CSG WITH (NOLOCK) ON CSG.Id =CUPS.CUPSSubGroupId
   INNER JOIN Contract.CupsGroup AS CGC WITH (NOLOCK) ON CGC.Id =CSG.CupsGroupId
 ),

 CTE_CITAS
AS
( --29684
 SELECT DISTINCT A.CODAUTONU,A.IPCODPACI,A.CODPROSAL,A.CODESPECI,A.FECHORAIN,A.TIPSOLICITU,A.CODSERIPS,A.NUMINGRES,A.IdCitaSync,RTRIM(C.NOMCENATE) AS [CENTRO ATENCION],
 RTRIM(C.CODIPSSEC) AS [CODIGO IPS],C.CODCENATE,
 IIF(D.IPSEXOPAC=1,'N/A',CASE RIE.GESTACION WHEN 0 THEN 'N/A' when 1 then 'SI' when 2 then 'NO' when 21 then 'Riesgo no evaluado' ELSE 'Riesgo no evaluado' end) 'GESTACION'
 FROM dbo.AGASICITA A WITH (NOLOCK)
 INNER JOIN dbo.INPACIENT AS D WITH (NOLOCK) ON A.IPCODPACI = D.IPCODPACI
 INNER JOIN dbo.ADCENATEN AS C WITH (NOLOCK) ON A.CODCENATE = C.CODCENATE
 LEFT JOIN DBO.HCRIESGOSP AS RIE WITH (NOLOCK) ON A.NUMINGRES=RIE.NUMINGRCES AND A.IPCODPACI=RIE.IPCODPACI
 WHERE CAST(A.FECHORAIN AS DATE) BETWEEN @FECHAINI AND @FECHAFIN --and A.IPCODPACI='1000353665' --AND NUMINGRES IN ('E47A9F0ECB','72217A5C2C')
),

--SELECT * FROM CTE_CITAS

CTE_CONTROL_SI
AS
( ---21006
 SELECT DISTINCT A.CODCONCEC,A.IPCODPACI,A.IPFECHCIT,A.CODPROSAL,A.NUMINGRES,A.NUMCONCIT,A.GENCAREGROUP,A.GENCONENTITY,A.FECREGSIS,A.IDHCHISPACA,A.FECCITACUMPLIDA,A.IdCitaSync,
 RTRIM(HEA.HealthEntityCode) 'CODIGO ENTIDAD ADMISION',RTRIM(HEA.Name) 'ENTIDAD ADMISION',CG.Name AS [GRUPO ATENCION ADMISION],A.CODSERIPS,
 IIF(D.IPSEXOPAC=1,'N/A',CASE RIE.GESTACION WHEN 0 THEN 'N/A' when 1 then 'SI' when 2 then 'NO' when 21 then 'Riesgo no evaluado' ELSE 'Riesgo no evaluado' end) 'GESTACION'
 FROM dbo.ADCONCOEX A WITH (NOLOCK)
 INNER JOIN dbo.INPACIENT AS D WITH (NOLOCK) ON A.IPCODPACI = D.IPCODPACI
 INNER JOIN
 (
  SELECT A.CODCONCEC,A.IPCODPACI,A.NUMINGRES,A.NUMCONCIT,A.IDHCHISPACA,ROW_NUMBER() OVER (PARTITION BY A.IPCODPACI,A.NUMCONCIT  
  ORDER BY CASE WHEN A.IDHCHISPACA IS NOT NULL THEN A.IDHCHISPACA ELSE A.CODCONCEC END DESC) AS RowNum
  FROM dbo.ADCONCOEX A WITH (NOLOCK)
  INNER JOIN CTE_CITAS AS CTE WITH (NOLOCK) ON CTE.CODAUTONU=A.NUMCONCIT
  ) AS G ON G.RowNum=1 AND G.CODCONCEC=A.CODCONCEC
  LEFT JOIN Contract.HealthAdministrator AS HEA WITH (NOLOCK) ON A.GENCONENTITY = HEA.Id
  LEFT JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON A.GENCAREGROUP=CG.Id
  LEFT JOIN DBO.HCRIESGOSP AS RIE WITH (NOLOCK) ON A.NUMINGRES=RIE.NUMINGRCES AND A.IPCODPACI=RIE.IPCODPACI
),

CTE_CONTROL_NO
AS
( ---368
 SELECT DISTINCT A.CODCONCEC,A.IPCODPACI,A.IPFECHCIT,A.CODPROSAL,A.NUMINGRES,A.NUMCONCIT,A.GENCAREGROUP,A.GENCONENTITY,A.FECREGSIS,A.IDHCHISPACA,A.FECCITACUMPLIDA,A.IdCitaSync,
 RTRIM(HEA.HealthEntityCode) 'CODIGO ENTIDAD ADMISION',RTRIM(HEA.Name) 'ENTIDAD ADMISION',CG.Name AS [GRUPO ATENCION ADMISION],A.CODSERIPS,
 IIF(D.IPSEXOPAC=1,'N/A',CASE RIE.GESTACION WHEN 0 THEN 'N/A' when 1 then 'SI' when 2 then 'NO' when 21 then 'Riesgo no evaluado' ELSE 'Riesgo no evaluado' end) 'GESTACION'
 FROM dbo.ADCONCOEX A WITH (NOLOCK)
 INNER JOIN dbo.INPACIENT AS D WITH (NOLOCK) ON A.IPCODPACI = D.IPCODPACI
 INNER JOIN
 (
    SELECT A.CODCONCEC,A.IPCODPACI,A.NUMINGRES,A.NUMCONCIT,A.IDHCHISPACA,ROW_NUMBER() OVER (PARTITION BY A.IPCODPACI,A.NUMCONCIT  
    ORDER BY CASE WHEN A.IDHCHISPACA IS NOT NULL THEN A.IDHCHISPACA ELSE A.CODCONCEC END DESC) AS RowNum
    FROM dbo.ADCONCOEX A WITH (NOLOCK)
    LEFT JOIN CTE_CITAS AS CTE WITH (NOLOCK) ON CTE.CODAUTONU=A.NUMCONCIT
	WHERE CAST(A.IPFECHCIT AS DATE) BETWEEN @FECHAINI AND @FECHAFIN AND CTE.CODAUTONU IS NULL
 ) AS G ON G.RowNum=1 AND G.CODCONCEC=A.CODCONCEC
 LEFT JOIN Contract.HealthAdministrator AS HEA WITH (NOLOCK) ON A.GENCONENTITY = HEA.Id
 LEFT JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON A.GENCAREGROUP=CG.Id
 LEFT JOIN DBO.HCRIESGOSP AS RIE WITH (NOLOCK) ON A.NUMINGRES=RIE.NUMINGRCES AND A.IPCODPACI=RIE.IPCODPACI
),

CTE_OTROS_PROCEDIMENTOS_SI
AS
(
 SELECT DISTINCT A.ID CODCONCEC,A.IPCODPACI,A.FECHAPRO,A.CODPROSAL,A.NUMINGRES,A.IDCITA,A.GENCAREGROUP,A.GENCONENTITY,A.FECHAREG,A.CODSERIPS,
 RTRIM(HEA.HealthEntityCode) 'CODIGO ENTIDAD ADMISION',RTRIM(HEA.Name) 'ENTIDAD ADMISION',CG.Name AS [GRUPO ATENCION ADMISION],G2.IDHCHISPACA,A.CODESPECI,
 IIF(D.IPSEXOPAC=1,'N/A',CASE RIE.GESTACION WHEN 0 THEN 'N/A' when 1 then 'SI' when 2 then 'NO' when 21 then 'Riesgo no evaluado' ELSE 'Riesgo no evaluado' end) 'GESTACION'
 FROM dbo.AMBORDOTROSPRO A WITH (NOLOCK)
 INNER JOIN dbo.INPACIENT AS D WITH (NOLOCK) ON A.IPCODPACI = D.IPCODPACI
 INNER JOIN 
 (
   SELECT MAX(A.ID) ID,A.IPCODPACI,A.NUMINGRES,A.IDCITA  
   FROM dbo.AMBORDOTROSPRO A WITH (NOLOCK)
   INNER JOIN CTE_CITAS AS CTE WITH (NOLOCK) ON CTE.CODAUTONU=A.IDCITA
   GROUP BY A.IPCODPACI,A.NUMINGRES,A.IDCITA
 ) AS G ON G.ID=A.ID
  LEFT JOIN 
  (
   SELECT PRO.ID,PRO.IDHCHISPACA,PRO.IPCODPACI,PRO.NUMINGRES,PRO.CODPROSAL ,PRO.FECHAREGISTRO
    FROM  DBO.HCPLAOTRPROC PRO WITH (NOLOCK)
    INNER JOIN (
	            SELECT MIN(ID) ID,IPCODPACI,NUMINGRES,CODPROSAL
	            FROM DBO.HCPLAOTRPROC WITH (NOLOCK)
	            GROUP BY IPCODPACI,NUMINGRES,CODPROSAL
	           ) AS G ON G.ID=PRO.ID
  ) AS G2 ON G2.NUMINGRES=A.NUMINGRES AND G2.IPCODPACI=A.IPCODPACI AND CAST(G2.FECHAREGISTRO AS DATE)=CAST(A.FECHAREG AS DATE)
  LEFT JOIN Contract.HealthAdministrator AS HEA WITH (NOLOCK) ON A.GENCONENTITY = HEA.Id
  LEFT JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON A.GENCAREGROUP=CG.Id
  LEFT JOIN DBO.HCRIESGOSP AS RIE WITH (NOLOCK) ON A.NUMINGRES=RIE.NUMINGRCES AND A.IPCODPACI=RIE.IPCODPACI
),

--SELECT * FROM CTE_OTROS_PROCEDIMENTOS_SI

CTE_OTROS_PROCEDIMENTOS_NO
AS
(
SELECT DISTINCT  A.ID CODCONCEC,A.IPCODPACI,A.FECHAPRO,A.CODPROSAL,A.NUMINGRES,A.IDCITA,A.GENCAREGROUP,A.GENCONENTITY,A.FECHAREG,A.CODSERIPS,
 RTRIM(HEA.HealthEntityCode) 'CODIGO ENTIDAD ADMISION',RTRIM(HEA.Name) 'ENTIDAD ADMISION',CG.Name AS [GRUPO ATENCION ADMISION],G2.IDHCHISPACA,A.CODESPECI,
 IIF(D.IPSEXOPAC=1,'N/A',CASE RIE.GESTACION WHEN 0 THEN 'N/A' when 1 then 'SI' when 2 then 'NO' when 21 then 'Riesgo no evaluado' ELSE 'Riesgo no evaluado' end) 'GESTACION'
 FROM dbo.AMBORDOTROSPRO A WITH (NOLOCK)
 INNER JOIN dbo.INPACIENT AS D WITH (NOLOCK) ON A.IPCODPACI = D.IPCODPACI
 INNER JOIN
 (
  SELECT MAX(A.ID) ID,A.IPCODPACI,A.NUMINGRES,A.IDCITA  
   FROM dbo.AMBORDOTROSPRO A WITH (NOLOCK)
   LEFT JOIN CTE_CITAS AS CTE WITH (NOLOCK) ON CTE.CODAUTONU=A.IDCITA
   WHERE CAST(A.FECHAREG AS DATE) BETWEEN @FECHAINI AND @FECHAFIN AND A.IDCITA IS NULL
   GROUP BY A.IPCODPACI,A.NUMINGRES,A.IDCITA
 ) AS G ON G.ID=A.ID
 LEFT JOIN 
  (
   SELECT PRO.ID,PRO.IDHCHISPACA,PRO.IPCODPACI,PRO.NUMINGRES,PRO.CODPROSAL ,PRO.FECHAREGISTRO
    FROM  DBO.HCPLAOTRPROC PRO WITH (NOLOCK)
    INNER JOIN (
	            SELECT MIN(ID) ID,IPCODPACI,NUMINGRES,CODPROSAL
	            FROM DBO.HCPLAOTRPROC WITH (NOLOCK)
	            GROUP BY IPCODPACI,NUMINGRES,CODPROSAL
	           ) AS G ON G.ID=PRO.ID
  ) AS G2 ON G2.NUMINGRES=A.NUMINGRES AND G2.IPCODPACI=A.IPCODPACI AND CAST(G2.FECHAREGISTRO AS DATE)=CAST(A.FECHAREG AS DATE)
  LEFT JOIN Contract.HealthAdministrator AS HEA WITH (NOLOCK) ON A.GENCONENTITY = HEA.Id
  LEFT JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON A.GENCAREGROUP=CG.Id
  LEFT JOIN DBO.HCRIESGOSP AS RIE WITH (NOLOCK) ON A.NUMINGRES=RIE.NUMINGRCES AND A.IPCODPACI=RIE.IPCODPACI
),

CTE_HCHISPACA
AS
(
 SELECT HIS.IPCODPACI,HIS.NUMINGRES,HIS.FECHISPAC,HIS.ID,HIS.CODESPTRA FROM 
  DBO.HCHISPACA HIS
  INNER JOIN
  (
   SELECT A.IPCODPACI,A.NUMINGRES,MAX(A.ID) ID 
   FROM DBO.HCHISPACA A
   WHERE CAST(A.FECHISPAC AS DATE) BETWEEN @FECHAINI AND @FECHAFIN AND A.GENCONEXT=1
   GROUP BY A.IPCODPACI,A.NUMINGRES
  ) AS G ON G.ID=HIS.ID
),

CTE_DATOS_CITA
AS
(
SELECT CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,CTE.[CENTRO ATENCION],CTE.[CODIGO IPS],
CASE A.TIPSOLICITU WHEN 3 THEN 'Tratamientos Especiales' WHEN 2 THEN 'Apoyo Diagnostico' WHEN 1 THEN  'Cita Medica'END [TIPO AGENDAMIENTO],
RTRIM(ISNULL(UNICE.UFUDESCRI,UNIID.UFUDESCRI)) AS [UNIDAD FUNCIONAL], 
CASE RTRIM(ISNULL(UNICE.UFUTIPUNI, UNIID.UFUTIPUNI))
      WHEN 1 THEN 'URGENCIAS'  WHEN 2 THEN 'HOSPITALIZACION' WHEN 3 THEN 'APOYO DIAGNOSTICO' WHEN 4 THEN 'APOYO TERAPEUTICO' WHEN 5 THEN 'UCI' WHEN 6 THEN 'UCI'
	  WHEN 7 THEN 'UCI' WHEN 8 THEN 'UCI' WHEN 9 THEN 'UCI' WHEN 10 THEN 'UCI' WHEN 11 THEN 'UCI' WHEN 12 THEN 'UNIDAD RENAL' WHEN 13 THEN 'UNIDAD ONCOLOGICA' 
	  WHEN 14 THEN 'UNIDAD MEDICINA NUCLEAR' WHEN 15 THEN 'AMBULATORIO' WHEN 16 THEN 'UNIDAD MENTAL' WHEN 17 THEN 'UNIDAD DE QUEMADOS' WHEN 18 THEN 'UNIDAD DE CUIDADOS PALATIVOS'
	  WHEN 19 THEN 'CIRUGIA' WHEN 20 THEN 'LABORATORIOS' WHEN 21 THEN 'CARDIOLOGIA NO INVASIVA' WHEN 22 THEN 'CARDIOLOGIA INVASIVA' WHEN 23 THEN 'GINECO OBSTETRICIA'
	  WHEN 24 THEN 'CONSULTA EXTERNA GINOCO OBSTETRICIA' WHEN 30 THEN 'OTRAS' WHEN 31 THEN 'CONSULTA PRIORITARIA' ELSE 'CONSULTA EXTERNA' END  [AMBITO],
B.CODESPECI AS [CODIGO ESPECIALIDAD], RTRIM(B.DESESPECI) AS ESPECIALIDAD, RTRIM(E.CODPROSAL) AS [CODIGO MEDICO], RTRIM(E.NOMMEDICO) AS [MEDICO], 
RTRIM(F.DESACTMED) AS 'ACTIVIDAD AGENDAMIENTO',
/*in v6*/AGC.DESCRICON AS CONSULTORIO,/*fn v6*/
IIF(F.DURAACTIV <> 0, F.DURAACTIV, (select top(1)FD.DURACSERVI from AGACTMEDD AS FD where a.CODACTMED = FD.CODACTMED AND FD.CODSERIPS = A.CODSERIPS )) + ' ' + 'MINUTOS' 'DURACION ACTIVIDAD',
CASE D.IPTIPODOC WHEN '1'  THEN 'CC'WHEN '2'  THEN 'CE'WHEN '3'  THEN 'TI'WHEN '4'  THEN 'RC'WHEN '5'  THEN 'PA'WHEN '6'  THEN 'AS'WHEN '7'  THEN 'MS'
WHEN '8'  THEN 'NU'WHEN '9'  THEN 'NV'WHEN '10' THEN 'CD'WHEN '11' THEN 'SC'WHEN '12' THEN 'PE' WHEN '13' THEN 'PT'WHEN '14' THEN 'DE'WHEN '15' THEN 'SI'END AS [TIPO IDENTIFICACION],
CASE D.IPTIPODOC WHEN '1'  THEN 'CEDULA DE CIUDADANIA' WHEN '2'  THEN 'CEDULA DE EXTRANJERIA' WHEN '3'  THEN 'TARJETA DE IDENTIDAD' WHEN '4'  THEN 'REGISTRO CIVIL' 
 WHEN '5'  THEN 'PASAPORTE' WHEN '6'  THEN 'ADULTO SIN IDENTIFICACION' WHEN '7'  THEN 'MENOR SIN IDENTIFICACION' WHEN '8'  THEN 'NUMERO UNICO DE IDENTIFICACIÒN'
 WHEN '9'  THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO' WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
 WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION'END AS [DESCRIPCION IDENTIFICACION], 
D.IPCODPACI AS [NRO IDENTIFICACION],D.ID AS [ID PACIENTE],CAST(D.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
CONCAT(FLOOR(CAST(DATEDIFF(DAY,D.IPFECNACI,A.FECHORAIN) AS FLOAT) / 365), ' años, ',FLOOR((CAST(DATEDIFF(DAY,D.IPFECNACI,A.FECHORAIN) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,D.IPFECNACI,A.FECHORAIN) AS FLOAT) / 365)) * 12),' meses,',FLOOR(((((CAST(DATEDIFF(DAY,D.IPFECNACI,A.FECHORAIN) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,D.IPFECNACI,A.FECHORAIN) AS FLOAT) / 365)) * 12) - FLOOR((CAST(DATEDIFF(DAY,D.IPFECNACI,A.FECHORAIN) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,D.IPFECNACI,A.FECHORAIN) AS FLOAT) / 365)) * 12)) * (365 / 12))), ' días') AS [EDAD],
CASE D.IPSEXOPAC WHEN '1' THEN 'H' WHEN '2' THEN 'M' END AS [CODIGO SEXO],CASE D.IPSEXOPAC WHEN '1' THEN 'HOMBRE' WHEN '2' THEN 'MUJER' END AS [SEXO], 
RTRIM(D.IPPRIAPEL) AS [PRIMER APELLIDO], RTRIM(D.IPSEGAPEL) AS [SEGUNDO APELLIDO], RTRIM(D.IPPRINOMB) AS [PRIMER NOMBRE], RTRIM(D.IPSEGNOMB) AS [SEGUNDO NOMBRE], 
UPPER(D.CORELEPAC) AS CORREO,DEP.depcodigo AS [CODIGO DEPARTAMENTO], DEP.nomdepart AS [NOMBRE DEPARTAMENTO RESIDENCIA], MUN.MUNCODIGO [CODIGO MUNICIPIO RESIDENCIA], 
MUN.MUNNOMBRE AS [NOMBRE MUNICIPIO RESIDENCIA], UPPER(D.IPDIRECCI) AS [DIRECCION], D.IPTELMOVI AS CELULAR, D.IPTELEFON AS [TELEFONO FIJO],
/*CASE WHEN A.CODTIPSOL = '0' THEN 'PRESENCIAL' WHEN A.CODTIPSOL = '1' THEN 'TELEFONICA' END*/ NULL AS [FORMA DE SOLICITUD],
ISNULL(IM.Agrupador,IIF(A.TIPSOLICITU=1,CASE A.CODTIPCIT WHEN 0 THEN 'PRIMERA VEZ' WHEN 1 THEN 'CONTROL' WHEN 2 THEN 'POS OPERATORIO' ELSE 'N/A' END,'N/A')) [TIPO DE CITA],
--FN V2 
CASE A.MODALIDAD WHEN 0 THEN 'PRESENCIAL' WHEN 1 THEN 'TELECONSULTA' ELSE 'N/A' END AS [MODALIDAD],
CASE WHEN HEA.Id IS NOT NULL THEN RTRIM(HEA.HealthEntityCode) ELSE RTRIM(ENT.CODENTIDA) END AS [CODIGO ENTIDAD CITA],
CASE WHEN HEA.Id IS NOT NULL THEN RTRIM(HEA.Name) ELSE RTRIM(ENT.NOMENTIDA) END AS [ENTIDAD CITA],
CASE HEA.EntityType WHEN 1 THEN 'EPS Contributivo' WHEN 2 THEN 'EPS Subsidiado' WHEN 3 THEN 'ET Vinculados Municipios' WHEN 4 THEN 'ET Vinculados Departamentos'
WHEN 5 THEN 'ARL Riesgos Laborales' WHEN 6 THEN 'MP Medicina Prepagada' WHEN 7 THEN 'IPS Privada' WHEN 8 THEN 'IPS Publica' WHEN 9 THEN 'Regimen Especial'
WHEN 10 THEN 'Accidentes de transito' WHEN 11 THEN 'Fosyga' WHEN 12 THEN 'Otros' ELSE 'Otros' end [REGIMEN CITA], 
CG.Name AS [GRUPO ATENCION CITA],
ISNULL(IM.Type,CUPS.[TIPO SERVICIO]) 'TIPO SERVICIO',
ISNULL(CTESI.CODSERIPS,A.CODSERIPS) AS [CODIGO CUPS],CUPS.[DESCRIPCION CUPS],
CONVERT(VARCHAR(16), CAST(A.FECREGSIS AS DATETIME), 20) AS [FECHA DE SOLICITUD],
CONVERT(VARCHAR(16), CAST(A.FECITADES AS DATETIME), 20) AS [FECHA SOLICITA PACIENTE],
CONVERT(VARCHAR(16), CAST(A.FECHORAIN AS DATETIME), 20) AS [FECHA DE CITA],
DATEDIFF(DAY, A.FECREGSIS, A.FECHORAIN) AS [OPORTUNIDAD DE CITA FS VS FAC],
CASE WHEN A.CITAEXTRA = 1 THEN 'Si' ELSE 'No' END AS [CITA EXTRA],
'ASIGNADA' AS [ESTADO INICIAL],
CASE A.CODESTCIT WHEN 1 THEN IIF((A.CODESTCIT=1 AND ING.NUMINGRES IS NULL),'INCUMPLIDA','CUMPLIDA') WHEN 2 THEN 
IIF(HIS.ID IS NOT NULL OR CTEOTROSI.IDHCHISPACA IS NOT NULL OR CTEOTRONO.IDHCHISPACA IS NOT NULL OR HIS2.ID IS NOT NULL,'CUMPLIDA','INCUMPLIDA')
WHEN 3 THEN 'PREASIGNADA'WHEN 4 THEN 'CANCELADA' WHEN 5 THEN 'INATENCION' END AS [ESTADO ACTUAL],
A.CODCAUCAN AS [CODIGO CANCELACION],CAN.DESCAUCAN AS [DESCRIPCION CANCELACION],ING.NUMINGRES AS [INGRESO DE ATENCION],
ing.IAUTORIZA 'NUMERO AUTORIZACION',IIF(HIS.ID IS NOT NULL OR CTEOTROSI.IDHCHISPACA IS NOT NULL OR CTEOTRONO.IDHCHISPACA IS NOT NULL OR 
HIS2.ID IS NOT NULL,'SI','NO') 'REGISTRO HISTORIA',
ISNULL(CTESI.[GESTACION],ISNULL(CTENO.[GESTACION],ISNULL(CTEOTROSI.[GESTACION],ISNULL(CTEOTRONO.[GESTACION],CTE.[GESTACION])))) [GESTACION],
A.codautonu 'IDCITA',ING.GENCONENTITY,ING.GENCAREGROUP,CTE.IdCitaSync 'idcitaIntegracion',CTESI.IdCitaSync 'idcitaSI',CTENO.IdCitaSync 'idCitaNO',
CASE ING.IESTADOIN WHEN 'F' THEN 'FACTURADO' WHEN 'C' THEN 'CERRADO' WHEN 'A' THEN 'ANULADO' WHEN '' THEN 'ABIERTO' END 'ESTADO INGRESO',
DIA.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO'
FROM dbo.AGASICITA A WITH (NOLOCK)
INNER JOIN dbo.INPACIENT AS D WITH (NOLOCK) ON A.IPCODPACI = D.IPCODPACI
INNER JOIN CTE_CITAS AS CTE ON CTE.CODAUTONU=A.CODAUTONU AND CTE.IPCODPACI=A.IPCODPACI
LEFT JOIN CTE_CONTROL_SI CTESI ON CTESI.NUMCONCIT=A.CODAUTONU AND CTESI.IPCODPACI=A.IPCODPACI
LEFT JOIN CTE_CONTROL_NO CTENO ON CTENO.IPCODPACI=A.IPCODPACI AND CTENO.NUMINGRES=A.NUMINGRES AND CTENO.CODPROSAL=A.CODPROSAL 
LEFT JOIN CTE_OTROS_PROCEDIMENTOS_SI CTEOTROSI ON CTEOTROSI.IDCITA=A.CODAUTONU AND CTEOTROSI.IPCODPACI=A.IPCODPACI AND CTEOTROSI.CODSERIPS=A.CODSERIPS
LEFT JOIN CTE_OTROS_PROCEDIMENTOS_NO CTEOTRONO ON CTEOTRONO.IPCODPACI=A.IPCODPACI AND CTEOTRONO.NUMINGRES=A.NUMINGRES AND CTEOTRONO.CODESPECI=A.CODESPECI
/*AGENDA DE CONSULTORIOS Y UNIDAD FUNCIONAL DE CONSULTA EXTERNA*/
LEFT JOIN dbo.AGCONSULT AS AGC WITH (NOLOCK) ON A.CODIGOCON=AGC.CODIGOCON AND CTE.CODCENATE=AGC.CODCENATE
LEFT JOIN dbo.INUNIFUNC AS UNICE WITH (NOLOCK) ON AGC.UFUCODIGO=UNICE.UFUCODIGO
/*SALAS Y UNIDADES FUNCIONALES DE APOYO DX Y PROCEDIMIENTOS*/
LEFT JOIN dbo.AGENSALAACT AS AGAC WITH (NOLOCK) ON A.IDSALA = AGAC.CODCONCEC AND A.CODACTMED=AGAC.CODACTMED
LEFT JOIN dbo.AGENSALAC AS AGS WITH (NOLOCK) ON AGAC.CODCONCEC = AGS.CODCONCEC
LEFT JOIN dbo.INUNIFUNC AS UNIID WITH (NOLOCK) ON AGS.UFUCODIGO=UNIID.UFUCODIGO
LEFT JOIN INESPECIA AS B WITH (NOLOCK) ON A.CODESPECI = B.CODESPECI
LEFT JOIN AGACTIMED AS F WITH (NOLOCK) ON A.CODACTMED = F.CODACTMED
LEFT JOIN INPROFSAL AS E WITH (NOLOCK) ON A.CODPROSAL = E.CODPROSAL
LEFT JOIN INUBICACI AS UBI WITH (NOLOCK) ON D.AUUBICACI = UBI.AUUBICACI
LEFT JOIN INMUNICIP AS MUN WITH (NOLOCK) ON UBI.DEPMUNCOD = MUN.DEPMUNCOD
LEFT JOIN INDEPARTA AS DEP WITH (NOLOCK) ON DEP.depcodigo = MUN.DEPCODIGO
LEFT JOIN INENTIDAD AS ENT WITH (NOLOCK) ON D.CODENTIDA = ENT.CODENTIDA
LEFT JOIN Contract.HealthAdministrator AS HEA WITH (NOLOCK) ON A.GENCONENTITY = HEA.Id
LEFT JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON A.GENCAREGROUP=CG.Id
LEFT JOIN REPORT.TableSocieties as IM WITH (NOLOCK) ON IM.Code=A.CODSERIPS AND IM.ReportType='Agendamiento'
LEFT JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=ISNULL(CTESI.CODSERIPS,A.CODSERIPS)
LEFT JOIN AGCAUCANC AS CAN WITH (NOLOCK)ON A.CODCAUCAN = CAN.CODCAUCAN
LEFT JOIN ADINGRESO AS ING WITH (NOLOCK)ON ING.NUMINGRES=ISNULL(CTESI.NUMINGRES,ISNULL(CTENO.NUMINGRES,ISNULL(CTEOTROSI.NUMINGRES,ISNULL(CTEOTRONO.NUMINGRES,A.NUMINGRES))))
LEFT JOIN HCHISPACA AS HIS WITH (NOLOCK) ON HIS.ID=ISNULL(CTESI.IDHCHISPACA,ISNULL(CTENO.IDHCHISPACA,ISNULL(CTEOTROSI.IDHCHISPACA,CTEOTRONO.IDHCHISPACA)))
LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=HIS.CODDIAGNO
LEFT JOIN CTE_HCHISPACA AS HIS2 WITH (NOLOCK) ON HIS2.NUMINGRES=A.NUMINGRES AND HIS2.IPCODPACI=A.IPCODPACI AND CAST(HIS2.FECHISPAC AS DATE)=CAST(A.FECHORAIN AS DATE) AND
HIS2.CODESPTRA=A.CODESPECI
)

SELECT 
ID_COMPANY,[CENTRO ATENCION],[CODIGO IPS],[TIPO AGENDAMIENTO],[UNIDAD FUNCIONAL],[AMBITO],[CODIGO ESPECIALIDAD],[ESPECIALIDAD],[CODIGO MEDICO],[MEDICO],[ACTIVIDAD AGENDAMIENTO],
[CONSULTORIO],[DURACION ACTIVIDAD],[TIPO IDENTIFICACION],[DESCRIPCION IDENTIFICACION],[NRO IDENTIFICACION],[ID PACIENTE],[FECHA NACIMIENTO],[EDAD],[CODIGO SEXO],CIT.[SEXO],
[PRIMER APELLIDO],[SEGUNDO APELLIDO],[PRIMER NOMBRE],[SEGUNDO NOMBRE],[CORREO],[CODIGO DEPARTAMENTO],[NOMBRE DEPARTAMENTO RESIDENCIA],[CODIGO MUNICIPIO RESIDENCIA],
[NOMBRE MUNICIPIO RESIDENCIA],[DIRECCION],[CELULAR],[TELEFONO FIJO],[FORMA DE SOLICITUD],[TIPO DE CITA],[MODALIDAD],[CODIGO ENTIDAD CITA],[ENTIDAD CITA],[REGIMEN CITA],
[GRUPO ATENCION CITA],[TIPO SERVICIO],[CODIGO CUPS],[DESCRIPCION CUPS],NULL [FECHA DE SOLICITUD],NULL [FECHA SOLICITA PACIENTE],NULL [FECHA DE CITA], NULL [OPORTUNIDAD DE CITA FS VS FAC],
[CITA EXTRA],[ESTADO INICIAL],[ESTADO ACTUAL],[CODIGO CANCELACION],[DESCRIPCION CANCELACION],[INGRESO DE ATENCION],[NUMERO AUTORIZACION],[REGISTRO HISTORIA],[GESTACION],
[IDCITA],HEA2.HealthEntityCode [CODIGO ENTIDAD ADMISION],HEA2.NAME [NOMBRE ENTIDAD ADMISION],CG2.NAME [GRUPO ATENCION ADMISION],G2.[CODIGO ENTIDAD FACTURACION],
G2.[ENTIDAD FACTURACION],G2.[GRUPO ATENCION FACTURACION],CIT.[ESTADO INGRESO],
IIF([CITA EXTRA]='SI',[FECHA DE SOLICITUD],CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_ASIGNACION AS DATETIME),20)) [FECHA DE SOLICITUD SERVINTE],
--CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_ASIGNACION AS DATETIME),20) [FECHA DE SOLICITUD SERVINTE2],
IIF([CITA EXTRA]='SI',[FECHA SOLICITA PACIENTE],CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_USR_SOLICTA AS DATETIME),20)) [FECHA SOLICITA PACIENTE SERVINTE],
--CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_USR_SOLICTA AS DATETIME),20) [FECHA SOLICITA PACIENTE SERVINTE2],
IIF([CITA EXTRA]='SI',[FECHA DE CITA],CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_CITA AS DATETIME),20)) [FECHA DE CITA SERVINTE],
--CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_CITA AS DATETIME),20) [FECHA DE CITA SERVINTE],
DATEDIFF(DAY,IIF([CITA EXTRA]='SI',[FECHA DE SOLICITUD],CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_ASIGNACION AS DATETIME),20)),
IIF([CITA EXTRA]='SI',[FECHA DE CITA],CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_CITA AS DATETIME),20))) AS [OPORTUNIDAD DE CITA F_ASIGNACION VS F_CITA],
--DATEDIFF(DAY,G3.FECHA_HORA_ASIGNACION,G3.FECHA_HORA_CITA) AS [OPORTUNIDAD DE CITA F_ASIGNACION VS F_CITA2],
CIT.[CIE10],CIT.[DIAGNOSTICO],G3.ID_CITA_SERVINTE
FROM CTE_DATOS_CITA CIT
LEFT JOIN Contract.HealthAdministrator AS HEA2 WITH (NOLOCK) ON CIT.GENCONENTITY = HEA2.Id
LEFT JOIN Contract.CareGroup AS CG2 WITH (NOLOCK) ON CIT.GENCAREGROUP=CG2.Id
LEFT JOIN 
  (
  SELECT I.AdmissionNumber,HEA3.HealthEntityCode [CODIGO ENTIDAD FACTURACION],HEA3.Name [ENTIDAD FACTURACION],CG3.Name [GRUPO ATENCION FACTURACION]
  FROM Billing.Invoice AS I
  INNER JOIN 
    (
      SELECT max(I.Id) id FROM Billing.Invoice AS I 
      where I.Status=1
      group by i.AdmissionNumber
    ) AS G ON G.Id=I.Id
   INNER JOIN Contract.HealthAdministrator AS HEA3 WITH (NOLOCK) ON I.HealthAdministratorId = HEA3.Id
   INNER JOIN Contract.CareGroup AS CG3 WITH (NOLOCK) ON I.CareGroupId=CG3.Id
  ) AS G2 ON G2.AdmissionNumber = CIT.[INGRESO DE ATENCION]
 LEFT JOIN 
 (
  SELECT SER.NUMERO_DOCUMENTO,SER.FECHA_HORA_ASIGNACION,SER.FECHA_HORA_USR_SOLICTA,SER.FECHA_HORA_CITA,ID_CITA_SERVINTE
  FROM [dbo].[CitasServinte] SER
  INNER JOIN
   (SELECT NUMERO_DOCUMENTO,CONVERT(VARCHAR(16), CAST(FECHA_HORA_CITA AS DATETIME), 20) 'FECHA_HORA_CITA',
    CONVERT(VARCHAR(16), CAST(MAX(FECHA_HORA_ASIGNACION) AS DATETIME),20) 'FECHA_REGISTRO' 
	 FROM [dbo].[CitasServinte]
	 WHERE  COD_MOTIVO_CANCELACION IS NULL or COD_MOTIVO_CANCELACION='' --AND NUMERO_DOCUMENTO='52197408'
	 GROUP BY NUMERO_DOCUMENTO,CONVERT(VARCHAR(16),CAST(FECHA_HORA_CITA AS DATETIME),20)
	) AS G ON G.NUMERO_DOCUMENTO=SER.NUMERO_DOCUMENTO AND G.[FECHA_HORA_CITA]=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_CITA AS DATETIME),20) AND
	  G.FECHA_REGISTRO=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_ASIGNACION AS DATETIME),20)
  ) AS G3 ON G3.NUMERO_DOCUMENTO=CIT.[NRO IDENTIFICACION] AND CONVERT(VARCHAR(16),CIT.[FECHA DE CITA],20)=CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_CITA AS DATETIME),20) 
 -- WHERE [NRO IDENTIFICACION]='1014673297'

 --WHERE [NRO IDENTIFICACION]='1000353665'

--SET STATISTICS TIME OFF;




--select * from [dbo].[CitasServinte]
--where NUMERO_DOCUMENTO='52197408' AND FECHA_HORA_CITA BETWEEN '2024-07-01' AND '2024-07-31'
-----------
--select COUNT(NUMERO_DOCUMENTO +CONVERT(VARCHAR(16), CAST(FECHA_HORA_CITA AS DATETIME), 20)) CANTIDAD, NUMERO_DOCUMENTO,FECHA_HORA_CITA from [dbo].[CitasServinte]
----where NUMERO_DOCUMENTO='1000035860'
--GROUP BY NUMERO_DOCUMENTO +CONVERT(VARCHAR(16), CAST(FECHA_HORA_CITA AS DATETIME), 20),NUMERO_DOCUMENTO ,FECHA_HORA_CITA 
--HAVING COUNT(NUMERO_DOCUMENTO +CONVERT(VARCHAR(16), CAST(FECHA_HORA_CITA AS DATETIME), 20))>1