-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_ERP_PARAMETROS_MEDICAMENTOS_PRODUCTOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE PROCEDURE [Report].[IND_SP_V2_ERP_PARAMETROS_MEDICAMENTOS_PRODUCTOS] 
AS

SELECT DCI.Code 'CODIGO DCI',RTRIM(DCI.Name) 'DESCRIPCION DCI',ATC.Code 'CODIGO MEDICAMENTO',
RTRIM(ATC.Name) 'DESCRIPCION MEDICAMENTO',RTRIM(ATC.Concentration) 'CONCENTRACION',RTRIM(PF.Name) 'FORMA FARMACEUTICA',RTRIM(AR.Name) 'VIA ADMINISTRACION',
ATC.StabilityMinimumHours 'ESTABILIDAD MINIMA',ATC.StabilityMaximumHours 'ESTABILIDAD MAXIMA',
CASE ATC.FormulationType WHEN 1 THEN 'PESO' WHEN 2 THEN 'VOLUMEN' WHEN 3 THEN 'PESO-VOLUMEN' WHEN 4 THEN 'UNIDAD ADMINISTRACION' END 'TIPO FORMULACION' ,
ISNULL(ATC.Weight,'0') 'PESO' ,ISNULL(RTRIM(IM1.Name),'') 'UNIDAD DE PESO',ISNULL(ATC.Volume,'0') 'VOLUMEN',ISNULL(RTRIM(IM2.Name),'') 'UNIDAD DE VOLUMEN',
ISNULL(RTRIM(IM3.Name),'') 'UNIDAD DE ADMINISTRACION',CASE ATC.AutomaticCalculation  WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END 'CALCULO AUTOMATICO',
CASE ATC.DiluentProduct WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'DILUYENTE' ,CASE ATC.Status WHEN 0 THEN 'INACTIVO' WHEN 1 THEN 'ACTIVO' END 'ESTADO',
CASE ATC.POSProduct WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'MEDICAMENTO PBS',CASE ATC.Conditioned WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'MEDICAMENTO CONDICIONADO',
CASE ATC.UNIRS WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'MEDICAMENTOS UNIRS',CASE ATC.Antibiotic WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'MEDICAMENTO ANTIBIOTICO',
CASE ATC.HighCost WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'MEDICAMENTO ALTO COSTO',IPP.Code 'CODIGO PRODUCTO',IPP.CodeCUM 'CODIGO CUM',RTRIM(IPP.Name) 'DESCRIPCION PRODUCTO',
IPP.CodeAlternative 'CODIGO ALTERNO 1' ,IPP.CodeAlternativeTwo 'CODIGO ALTERNO 2',PG.Code 'CODIGO GRUPO INVENTARIO' ,RTRIM(PG.Name) 'GRUPO INVENTARIO',
PSG.Code 'CODIGO SUB GRUPO INVENTARIO',RTRIM(PSG.Name) 'SUB GRUPO INVENTARIO',BG.Code 'CODIGO GRUPO FACTURACION', RTRIM(BG.Name) 'GRUPO FACTURACION',
CASE IPP.HandlesHealthRegistration WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END 'REGISTRO INVIMA' ,IPP.HealthRegistration 'NRO REGISTRO INVIMA' ,
CAST(IPP.ExpirationDate AS DATE) 'VENCIMIENTO INVIMA',IPP.FinalProductCost 'ULTIMO COSTO COMPRA' ,IPP.ProductCost 'COSTO',IPP.SellingPrice 'PRECIO VENTA' ,
CASE IPP.Status  WHEN 0 THEN 'INACTIVO' WHEN 1 THEN 'ACTIVO' END 'ESTADO PRODUCTO' 
FROM Inventory . ATC ATC WITH (NOLOCK)
INNER JOIN Inventory .DCI AS DCI WITH (NOLOCK) ON DCI.Id =ATC.DCIId 
INNER JOIN Inventory .ATCEntity ATCE WITH (NOLOCK) ON ATCE.Id =ATC.ATCEntityId 
INNER JOIN Inventory .AdministrationRoute AS AR WITH (NOLOCK) ON AR.Id =ATC.AdministrationRouteId 
INNER JOIN Inventory .PharmaceuticalForm AS PF WITH (NOLOCK) ON PF.Id =ATC.PharmaceuticalFormId 
INNER JOIN Inventory .InventoryProduct AS IPP WITH (NOLOCK) ON IPP.ATCId =ATC.Id 
LEFT JOIN Inventory .InventoryMeasurementUnit AS IM1 WITH (NOLOCK) ON IM1.Id =ATC.WeightMeasureUnit 
LEFT JOIN Inventory .InventoryMeasurementUnit AS IM2 WITH (NOLOCK) ON IM2.Id =ATC.VolumeMeasureUnit  
LEFT JOIN Inventory .InventoryMeasurementUnit AS IM3 WITH (NOLOCK) ON IM3.Id =ATC.AdministrationUnitId 
LEFT JOIN Inventory .ProductGroup AS PG WITH (NOLOCK) ON PG.Id =IPP.ProductGroupId 
LEFT JOIN Inventory .ProductSubGroup  AS PSG WITH (NOLOCK) ON IPP.ProductSubGroupId =PSG.Id 
LEFT JOIN Billing .BillingGroup AS BG WITH (NOLOCK) ON BG.Id  =IPP.BillingGroupId 

--where atc.name like '%acetamin%'
ORDER BY ATC.Name 
