-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_IMAGENES_PRODUCTIVIDAD_FECHA_SERVICIO_V2
-- Extracted by Fabric SQL Extractor SPN v3.9.0



--SET STATISTICS TIME ON;
CREATE PROCEDURE [Report].[IND_SP_V2_EHR_IMAGENES_PRODUCTIVIDAD_FECHA_SERVICIO_V2]

@FECHAINI AS DATE,
@FECHAFIN AS DATE

--DECLARE @FECHAINI AS DATE='2024-09-01';
--DECLARE @FECHAFIN AS DATE='2024-09-30';

AS

WITH CTE_CUPS
AS
(
   SELECT CUPS.Id,CUPS.Code [CUPS], CUPS.Description [DESCRIPCION CUPS], 
   CASE CUPS.ServiceType WHEN 1 then 'LABORATORIOS' WHEN 2 then 'PATOLOGIAS' WHEN 3 then 'IMAGENES DIAGNOSTICAS' WHEN 4 then 'PROCEDIMIENTOS NO QX'
   WHEN 5 then 'PROCEDIMIENTOS QX' WHEN 6 then 'INTERCONSULTAS'WHEN 7 then 'NINGUNO'WHEN 8 then 'CONSULTA EXTERNA' WHEN 9 THEN 'HEMOCOMPONENTES' ELSE 'OTROS' END AS 'TIPO SERVICIO',
   BG.CODE 'CODIGO FACTURACION',BG.NAME 'GRUPO FACTURACION',BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION',CGC.Code 'CODIGO GRUPO',CGC.Name 'GRUPO CUPS',
   CSG.CODE 'CODIGO SUBGRUPO',CSG.Name  'SUBGRUPO CUPS',
   CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
   ELSE 'N/A' END 'OBTENER CC',CUPS.ServiceType
   FROM Contract.CUPSEntity AS CUPS WITH (NOLOCK)
   INNER JOIN Billing.BillingGroup as BG WITH (NOLOCK) ON BG.Id=CUPS.BillingGroupId
   INNER JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=CUPS.BillingConceptId
   INNER JOIN Contract.CupsSubgroup AS CSG WITH (NOLOCK) ON CSG.Id =CUPS.CUPSSubGroupId
   INNER JOIN Contract.CupsGroup AS CGC WITH (NOLOCK) ON CGC.Id =CSG.CupsGroupId
 ),

 CTE_DATOS_PACIENTES_UNICOS
 AS
 (
  SELECT DISTINCT G.IPCODPACI FROM
  (  
   SELECT DISTINCT IPCODPACI
   FROM dbo.HCORDIMAG TER
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
   WHERE IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad') AND TER.ESTSERIPS<>5 AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN --AND TER.MANEXTPRO=0
   UNION ALL
   SELECT DISTINCT IPCODPACI
   FROM dbo.AMBORDIMA TER
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
   WHERE IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad') AND TER.ESTSERIPS<>5 AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN --AND TER.MANEXTPRO=0
  ) AS G
),

 CTE_DATOS_INGRESOS_UNICOS
 AS
 (
  SELECT DISTINCT G.NUMINGRES FROM 
  (
   SELECT DISTINCT NUMINGRES
   FROM dbo.HCORDIMAG TER
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
   WHERE IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad') AND TER.ESTSERIPS<>5 AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN --AND TER.MANEXTPRO=0
   UNION ALL
   SELECT DISTINCT NUMINGRES
   FROM dbo.AMBORDIMA TER
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
   WHERE IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad') AND TER.ESTSERIPS<>5 AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN --AND TER.MANEXTPRO=0
  ) AS G
),

CTE_DATOS_INDIRA
AS
(
 SELECT IND.NumeroAccesoINDIRA,IND.TipoOrden,IND.NumeroOrdenVIE,IND.IdentificacionPaciente,IND.NombreCompletoPaciente,IND.IngresoVIE,
 IND.[Fecha de toma estudio],IND.FechaLecturaConfirmada,IND.IdentificacionUsuarioValida,IND.UsuarioValidaLectura,IND.FechaOrdenMedica,IND.FechaInicialCita,
 IND.CodigoServico,IND.DescripcionServicio,IND.Modalidad,IND.NombreModalidad,IND.Cantidad,IND.EstadoLectura
 FROM Report.TableIndira IND
 INNER JOIN CTE_DATOS_INGRESOS_UNICOS ING ON ING.NUMINGRES=IND.IngresoVIE
 LEFT JOIN
 (
    SELECT NumeroOrdenVIE,IngresoVIE,CodigoServico,MAX(FechaLecturaConfirmada) FechaLectura
    FROM Report.TableIndira  --WHERE NumeroOrdenVIE=176070
    GROUP BY NumeroOrdenVIE,IngresoVIE,CodigoServico
 ) AS G ON G.NumeroOrdenVIE=IND.NumeroOrdenVIE AND G.IngresoVIE=IND.IngresoVIE AND G.CodigoServico=IND.CodigoServico AND G.FechaLectura=IND.FechaLecturaConfirmada
),

 ---*************************************************************************************************************************************************************************-----

CTE_DATOS_ORDENES_IMAGENES
AS
(
 SELECT DISTINCT 'VIE' 'FUENTE','1. ORDEN MEDICA' 'FUNCIONAL',CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',TER.IPCODPACI 'IDENTIFICACION',
 PAC.IPNOMCOMP 'PACIENTE',TER.NUMINGRES 'INGRESO', TER.NUMEFOLIO 'FOLIO',CAST(TER.FECORDMED AS DATE) 'FECHA ORDEN/EJECUCION',TER.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS],
 CD.Name 'DESCRIPCION RELACIONADA',TER.CANSERIPS 'CANTIDAD', CASE MANEXTPRO WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'EXTRAMURAL', UNI.UFUDESCRI 'UNIDAD FUNCIONAL',
 TER.CODPROSAL 'ID PROFESIONAL',MED.NOMMEDICO 'PROFESIONAL',ESP.DESESPECI 'ESPECIALIDAD' ,TER.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',TP.Nit AS NIT,TP.Name AS ENTIDAD,
 CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],'N/A' 'FACTURADO','N/A' 'NRO FACTURA',TER.AUTO,TER.GENSERVICEORDER, IM.Agrupador 'AGRUPADOR',
 CAST(ISNULL(IND.FechaInicialCita,TER.FECORDMED) AS DATE) 'FECHA CITA',CAST(IND.[Fecha de toma estudio] AS DATE) 'FECHA DE TOMA'
 FROM dbo.HCORDIMAG TER WITH (NOLOCK)
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = TER.UFUCODIGO
 INNER JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = TER.CODPROSAL
 INNER JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
 INNER JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=TER.CODDIAGNO
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=TER.NUMINGRES AND IND.NumeroOrdenVIE=TER.AUTO
 WHERE IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad') AND TER.ESTSERIPS<>5 AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN --AND TER.MANEXTPRO=0
 --AND TER.NUMINGRES='118242    '
 UNION ALL
  SELECT DISTINCT 'VIE' 'FUENTE','1. ORDEN MEDICA' 'FUNCIONAL','AMBULATORIO' 'AMBITO',--CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',
  TER.IPCODPACI 'IDENTIFICACION',
 PAC.IPNOMCOMP 'PACIENTE',TER.NUMINGRES 'INGRESO', NULL 'FOLIO',CAST(TER.FECORDMED AS DATE) 'FECHA ORDEN/EJECUCION',TER.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS],
 CD.Name 'DESCRIPCION RELACIONADA',TER.CANSERIPS 'CANTIDAD', 'NO' 'EXTRAMURAL', UNI.UFUDESCRI 'UNIDAD FUNCIONAL',
 TER.CODPROSAL 'ID PROFESIONAL',MED.NOMMEDICO 'PROFESIONAL',ESP.DESESPECI 'ESPECIALIDAD' ,DIA.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',TP.Nit AS NIT,TP.Name AS ENTIDAD,
 CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],'N/A' 'FACTURADO','N/A' 'NRO FACTURA',TER.AUTO,TER.GENSERVICEORDER,IM.Agrupador 'AGRUPADOR',
 CAST(ISNULL(G3.FECHA_HORA_ASIGNACION,IND.FechaInicialCita) AS DATE) 'FECHA CITA',CAST(IND.[Fecha de toma estudio] AS DATE) 'FECHA DE TOMA'
 FROM dbo.AMBORDIMA TER WITH (NOLOCK)
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = TER.UFUCODIGO
 LEFT  JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 LEFT  JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 LEFT  JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = TER.CODPROSAL
 LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
 LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=ING.CODDIAING
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=TER.NUMINGRES AND IND.NumeroOrdenVIE=TER.AUTO
 LEFT JOIN dbo.AGASICITA CIT WITH (NOLOCK) ON CIT.CODAUTONU=TER.NUMCONCIT
 LEFT JOIN 
 (
  SELECT DISTINCT SER.NUMERO_DOCUMENTO,SER.FECHA_HORA_ASIGNACION,SER.FECHA_HORA_USR_SOLICTA,SER.FECHA_HORA_CITA,ID_CITA_SERVINTE
  FROM [dbo].[CitasServinte] SER
  INNER JOIN CTE_DATOS_PACIENTES_UNICOS PAC ON PAC.IPCODPACI=SER.NUMERO_DOCUMENTO
  INNER JOIN
   (SELECT NUMERO_DOCUMENTO,CONVERT(VARCHAR(16), CAST(FECHA_HORA_CITA AS DATETIME), 20) 'FECHA_HORA_CITA',
    CONVERT(VARCHAR(16), CAST(MAX(FECHA_HORA_ASIGNACION) AS DATETIME),20) 'FECHA_REGISTRO' 
	 FROM [dbo].[CitasServinte]
	 WHERE  COD_MOTIVO_CANCELACION IS NULL --AND NUMERO_DOCUMENTO='52197408'
	 GROUP BY NUMERO_DOCUMENTO,CONVERT(VARCHAR(16),CAST(FECHA_HORA_CITA AS DATETIME),20)
	) AS G ON G.NUMERO_DOCUMENTO=SER.NUMERO_DOCUMENTO AND G.[FECHA_HORA_CITA]=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_CITA AS DATETIME),20) AND
	  G.FECHA_REGISTRO=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_ASIGNACION AS DATETIME),20)
  ) AS G3 ON G3.NUMERO_DOCUMENTO=CIT.IPCODPACI AND CONVERT(VARCHAR(16),CIT.FECHORAIN,20)=CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_CITA AS DATETIME),20)
 WHERE IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad') AND TER.ESTSERIPS<>5 AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
 --AND TER.NUMINGRES='118242    '
),

--SELECT * FROM CTE_DATOS_ORDENES_IMAGENES
---*************************************************************************************************************************************************************************-----

CTE_DATOS_EJECUCION_IMAGENES
AS
(
 SELECT DISTINCT 'VIE' 'FUENTE','2. INDIRA-VIE' 'FUNCIONAL',CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',TER.IPCODPACI 'IDENTIFICACION',
 PAC.IPNOMCOMP 'PACIENTE',TER.NUMINGRES 'INGRESO', TER.NUMFOLINT 'FOLIO',CAST(ISNULL(TER.FECHLECT,ISNULL(TER.FECRECEXA,TER.FECORDMED)) AS DATE) 'FECHA ORDEN/EJECUCION',TER.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS],
 CD.Name 'DESCRIPCION RELACIONADA',1 'CANTIDAD', 'NO' 'EXTRAMURAL', UNI.UFUDESCRI 'UNIDAD FUNCIONAL',
 TER.CODPROSAL 'ID PROFESIONAL',MED.NOMMEDICO 'PROFESIONAL',ESP.DESESPECI 'ESPECIALIDAD',DIA.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',TP.Nit AS NIT,TP.Name AS ENTIDAD,
 CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],'N/A' 'FACTURADO','N/A' 'NRO FACTURA',TER.AUTO,TER.GENSERVICEORDER,IM.Agrupador 'AGRUPADOR',
 CAST(TER.FECORDMED AS DATE) 'FECHA CITA',CAST(IND.[Fecha de toma estudio] AS DATE) 'FECHA DE TOMA'
 FROM dbo.HCORDIMAG TER
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = TER.UFUCODIGO
 INNER JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = ISNULL(TER.MEDREALEC,ISNULL(CODPROVAL,ISNULL(USURECEXA,TER.CODPROINT)))
 INNER JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
 INNER JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=ISNULL(CODDIAEGR,CODDIAING)
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=TER.NUMINGRES AND IND.NumeroOrdenVIE=TER.AUTO
 WHERE IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad') AND 
 CAST(ISNULL(TER.FECHLECT,ISNULL(TER.FECRECEXA,TER.FECORDMED)) AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN and TER.ESTSERIPS IN ('2','3','4')
 --AND TER.NUMINGRES='118242    '
 UNION ALL
 SELECT DISTINCT 'VIE' 'FUENTE','2. INDIRA-VIE' 'FUNCIONAL',CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',TER.IPCODPACI 'IDENTIFICACION',
 PAC.IPNOMCOMP 'PACIENTE',TER.NUMINGRES 'INGRESO', TER.NUMFOLINT 'FOLIO',CAST(ISNULL(TER.FECHLECT,ISNULL(TER.FECRECEXA,TER.FECORDMED)) AS DATE) 'FECHA ORDEN/EJECUCION',TER.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS],
 CD.Name 'DESCRIPCION RELACIONADA',1 'CANTIDAD', 'NO' 'EXTRAMURAL', UNI.UFUDESCRI 'UNIDAD FUNCIONAL',
 TER.CODPROSAL 'ID PROFESIONAL',MED.NOMMEDICO 'PROFESIONAL',ESP.DESESPECI 'ESPECIALIDAD',DIA.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',TP.Nit AS NIT,TP.Name AS ENTIDAD,
 CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],'N/A' 'FACTURADO','N/A' 'NRO FACTURA',TER.AUTO,TER.GENSERVICEORDER,IM.Agrupador 'AGRUPADOR',
 CAST(ISNULL(G3.FECHA_HORA_ASIGNACION,ISNULL(IND.FechaInicialCita,TER.FECORDMED)) AS DATE) 'FECHA CITA',CAST(IND.[Fecha de toma estudio]  AS DATE) 'FECHA DE TOMA'
 FROM dbo.AMBORDIMA TER
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = TER.UFUCODIGO
 INNER JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = ISNULL(TER.MEDREALEC,ISNULL(CODPROVAL,ISNULL(USURECEXA,TER.CODPROINT)))
 INNER JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
 INNER JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=ISNULL(CODDIAEGR,CODDIAING)
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=TER.NUMINGRES AND IND.NumeroOrdenVIE=TER.AUTO
 LEFT JOIN dbo.AGASICITA CIT WITH (NOLOCK) ON CIT.CODAUTONU=TER.NUMCONCIT
 LEFT JOIN 
 (
  SELECT SER.NUMERO_DOCUMENTO,SER.FECHA_HORA_ASIGNACION,SER.FECHA_HORA_USR_SOLICTA,SER.FECHA_HORA_CITA,ID_CITA_SERVINTE
  FROM [dbo].[CitasServinte] SER
  INNER JOIN CTE_DATOS_PACIENTES_UNICOS PAC ON PAC.IPCODPACI=SER.NUMERO_DOCUMENTO
  INNER JOIN
   (SELECT NUMERO_DOCUMENTO,CONVERT(VARCHAR(16), CAST(FECHA_HORA_CITA AS DATETIME), 20) 'FECHA_HORA_CITA',
    CONVERT(VARCHAR(16), CAST(MAX(FECHA_HORA_ASIGNACION) AS DATETIME),20) 'FECHA_REGISTRO' 
	 FROM [dbo].[CitasServinte]
	 WHERE  COD_MOTIVO_CANCELACION IS NULL --AND NUMERO_DOCUMENTO='52197408'
	 GROUP BY NUMERO_DOCUMENTO,CONVERT(VARCHAR(16),CAST(FECHA_HORA_CITA AS DATETIME),20)
	) AS G ON G.NUMERO_DOCUMENTO=SER.NUMERO_DOCUMENTO AND G.[FECHA_HORA_CITA]=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_CITA AS DATETIME),20) AND
	  G.FECHA_REGISTRO=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_ASIGNACION AS DATETIME),20)
  ) AS G3 ON G3.NUMERO_DOCUMENTO=CIT.IPCODPACI AND CONVERT(VARCHAR(16),CIT.FECHORAIN,20)=CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_CITA AS DATETIME),20)
 WHERE IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad') 
 AND CAST(ISNULL(TER.FECHLECT,ISNULL(TER.FECRECEXA,TER.FECORDMED)) AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN and TER.ESTSERIPS IN ('2','3','4')
 --AND TER.NUMINGRES='118242    '
),

--SELECT * FROM CTE_DATOS_EJECUCION_IMAGENES
---*************************************************************************************************************************************************************************-----

CTE_DATOS_CARGOS_IMAGENES
AS
(
 SELECT DISTINCT 'VIE' 'FUENTE','3. ORDEN DE SERVICIO' 'FUNCIONAL',CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',PAC.IPCODPACI 'IDENTIFICACION',
 PAC.IPNOMCOMP 'PACIENTE',ISNULL(RC.AdmissionNumber,SO.AdmissionNumber) 'INGRESO', NULL 'FOLIO',CAST(SOD.ServiceDate AS DATE) 'FECHA ORDEN/EJECUCION',CUPS.[CUPS],CUPS.[DESCRIPCION CUPS],
 CD.Name 'DESCRIPCION RELACIONADA',isnull(ID.InvoicedQuantity,SOD.InvoicedQuantity)'CANTIDAD', 'NO' 'EXTRAMURAL', FU.Name 'UNIDAD FUNCIONAL',
 ISNULL(G.[IDENTIFICACION PROFESIONAL],MED.CODPROSAL) 'ID PROFESIONAL',ISNULL(G.[PROFESIONAL REALIZO],MED.NOMMEDICO) 'PROFESIONAL',
 ISNULL(G.[ESPECIALIDA REALIZO],ESPMED.DESESPECI) 'ESPECIALIDAD',DIA.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO', TP.Nit AS NIT,TP.Name AS ENTIDAD,
 CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],SOD.ID AUTO,SO.ID GENSERVICEORDER,I.InvoiceNumber 'NRO FACTURA',IM.Agrupador 'AGRUPADOR',
 G.[FECHA CITA],G.[FECHA DE TOMA]
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =SOD.CostCenterId
  INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =SOD.ThirdPartyId
  INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =SOD.CareGroupId
  LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
  LEFT JOIN dbo.INESPECIA AS ESPMED WITH (NOLOCK) ON ESPMED.CODESPECI = SOD.PerformsProfessionalSpecialty
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.Id
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.Id =ID.ServiceOrderDetailId
  LEFT JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =ISNULL(RC.PatientCode,SO.PatientCode)
  LEFT JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON CAST(ING.NUMINGRES  AS CHAR)=CAST(ISNULL(RC.AdmissionNumber,SO.AdmissionNumber) AS CHAR)
  LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=ISNULL(ING.CODDIAEGR,ING.CODDIAING)
  LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =SOD.CUPSEntityContractDescriptionId  AND SOD.CUPSEntityId=DESCR.CUPSEntityId 
  LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
  LEFT JOIN
  (
      SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.MEDREALEC,A.ESPEREALIZA,A.GENSERVICEORDER,A.AUTO, A.MEDREALEC 'IDENTIFICACION PROFESIONAL',
       PRO.NOMMEDICO 'PROFESIONAL REALIZO',ESP.DESESPECI 'ESPECIALIDA REALIZO',MFC.ContractName 'AGREMIACION',CAST(A.FECHLECT AS DATE) 'FECHA LECTURA',
	   CAST(A.FECORDMED AS DATE) 'FECHA CITA',CAST(IND.[Fecha de toma estudio] AS DATE) 'FECHA DE TOMA'
       FROM dbo.HCORDIMAG A WITH (NOLOCK)
	   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=A.CODSERIPS
       INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
	   INNER JOIN
       (
        SELECT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER,MAX(A.AUTO) AUTO
         FROM dbo.ADINGRESO ing WITH (NOLOCK)
	        INNER JOIN dbo.HCORDIMAG A with (nolock) ON ing.NUMINGRES = A.NUMINGRES
			INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=A.CODSERIPS
            INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
			where A.MEDREALEC IS NOT NULL AND A.GENSERVICEORDER IS NOT NULL AND IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad')
	        GROUP BY A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER
       ) AS G ON G.AUTO=A.AUTO AND G.NUMINGRES=A.NUMINGRES AND G.CODSERIPS=A.CODSERIPS
       LEFT JOIN dbo.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL=A.MEDREALEC
       LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI =PRO.CODESPEC1
       LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =PRO.CODPROSAL AND HPC.LiquidateDefault = 1
       LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
	   LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=A.NUMINGRES AND IND.NumeroOrdenVIE=A.AUTO
	   where IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad')
    UNION ALL
        SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.MEDREALEC,A.ESPEREALIZA,A.GENSERVICEORDER,A.AUTO, A.MEDREALEC 'IDENTIFICACION PROFESIONAL',
         ISNULL(PRO.NOMMEDICO,PROE.NOMMEDICO) 'PROFESIONAL REALIZO',ISNULL(ESP.DESESPECI,ESPE.DESESPECI) 'ESPECIALIDA REALIZO',MFC.ContractName 'AGREMIACION',
		 CAST(A.FECHLECT AS DATE) 'FECHA LECTURA',CAST(ISNULL(G3.FECHA_HORA_ASIGNACION,ISNULL(IND.FechaInicialCita,A.FECORDMED)) AS DATE) 'FECHA CITA',
		 CAST(IND.[Fecha de toma estudio] AS DATE) 'FECHA DE TOMA'
        FROM dbo.AMBORDIMA A WITH (NOLOCK)
		INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=A.CODSERIPS
        INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
        INNER JOIN
        (
         SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER,MAX(A.AUTO) AUTO
         FROM dbo.ADINGRESO ing WITH (NOLOCK)
	      INNER JOIN dbo.AMBORDIMA A WITH (NOLOCK) ON ing.NUMINGRES = A.NUMINGRES
		  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=A.CODSERIPS
          INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
		  where A.MEDREALEC IS NOT NULL AND A.GENSERVICEORDER IS NOT NULL AND IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad')
	      GROUP BY A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER
        ) AS G ON G.AUTO=A.AUTO AND G.NUMINGRES=A.NUMINGRES AND G.CODSERIPS=A.CODSERIPS
        LEFT JOIN dbo.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL=A.MEDREALEC
        LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI =PRO.CODESPEC1
        LEFT JOIN dbo.INPROFSAL AS PROE WITH (NOLOCK) ON PROE.CODPROSAL=A.USURECEXA
        LEFT JOIN dbo.INESPECIA AS ESPE WITH (NOLOCK) ON ESPE.CODESPECI =PROE.CODESPEC1
        LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =ISNULL(PRO.CODPROSAL,PROE.CODPROSAL) AND HPC.LiquidateDefault = 1
        LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
		LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=A.NUMINGRES AND IND.NumeroOrdenVIE=A.AUTO
		LEFT JOIN dbo.AGASICITA CIT WITH (NOLOCK) ON CIT.CODAUTONU=A.NUMCONCIT
		LEFT JOIN 
        (
         SELECT SER.NUMERO_DOCUMENTO,SER.FECHA_HORA_ASIGNACION,SER.FECHA_HORA_USR_SOLICTA,SER.FECHA_HORA_CITA,ID_CITA_SERVINTE
         FROM [dbo].[CitasServinte] SER
         INNER JOIN CTE_DATOS_PACIENTES_UNICOS PAC ON PAC.IPCODPACI=SER.NUMERO_DOCUMENTO
         INNER JOIN
          (SELECT NUMERO_DOCUMENTO,CONVERT(VARCHAR(16), CAST(FECHA_HORA_CITA AS DATETIME), 20) 'FECHA_HORA_CITA',
           CONVERT(VARCHAR(16), CAST(MAX(FECHA_HORA_ASIGNACION) AS DATETIME),20) 'FECHA_REGISTRO' 
        	 FROM [dbo].[CitasServinte]
        	 WHERE  COD_MOTIVO_CANCELACION IS NULL --AND NUMERO_DOCUMENTO='52197408'
        	 GROUP BY NUMERO_DOCUMENTO,CONVERT(VARCHAR(16),CAST(FECHA_HORA_CITA AS DATETIME),20)
          ) AS G ON G.NUMERO_DOCUMENTO=SER.NUMERO_DOCUMENTO AND G.[FECHA_HORA_CITA]=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_CITA AS DATETIME),20) AND
        	  G.FECHA_REGISTRO=CONVERT(VARCHAR(16),CAST(SER.FECHA_HORA_ASIGNACION AS DATETIME),20)
       ) AS G3 ON G3.NUMERO_DOCUMENTO=CIT.IPCODPACI AND CONVERT(VARCHAR(16),CIT.FECHORAIN,20)=CONVERT(VARCHAR(16),CAST(G3.FECHA_HORA_CITA AS DATETIME),20)
		where IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad')
  ) AS G ON G.NUMINGRES=CAST(ISNULL(RC.AdmissionNumber,SO.AdmissionNumber) AS CHAR) AND G.GENSERVICEORDER=SO.ID AND G.CODSERIPS=CUPS.[CUPS] 
  WHERE IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad') AND CAST(SOD.ServiceDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
),

--SELECT * FROM CTE_DATOS_CARGOS_IMAGENES

CTE_DATOS_CARGOS_EMPAQUETADO
AS
(
 SELECT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,so.status,SOD.CUPSEntityId,SOD.IPSServiceId,sod.PackageServiceOrderDetailId,IM.Agrupador 'AGRUPADOR',
 ID.ID,I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CUPS2.[CUPS] 'CUPS PAQUETE',CUPS2.[DESCRIPCION CUPS] 'DESCRIPCION PAQUETE'
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.PackageServiceOrderDetailId
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.PackageServiceOrderDetailId =ID.ServiceOrderDetailId
  LEFT JOIN Billing.ServiceOrderDetail SODP WITH (NOLOCK) ON SODP.Id = sod.PackageServiceOrderDetailId
  LEFT JOIN CTE_CUPS AS CUPS2 WITH (NOLOCK) ON CUPS2.Id=SODP.CUPSEntityId
 WHERE SOD.RecordType=1 AND SOD.Packaging=1  and IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad')
 AND CAST(SOD.ServiceDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
 ),

CTE_DATOS_CARGOS_INCLUIDO
AS
(
 SELECT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,so.status,SOD.CUPSEntityId,SOD.IPSServiceId,SOD.SettlementType,SOD.IncludeServiceOrderDetailId,ID.ID 'Id_DetFacInc',
 I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CUPS2.[CUPS] 'CUPS INCLUIDO',CUPS2.[DESCRIPCION CUPS] 'DESCRIPCION INCLUIDO',IM.Agrupador 'AGRUPADOR'
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.IncludeServiceOrderDetailId
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.IncludeServiceOrderDetailId =ID.ServiceOrderDetailId
  LEFT JOIN Billing.ServiceOrderDetail SODI WITH (NOLOCK) ON SODI.Id = sod.IncludeServiceOrderDetailId
  LEFT JOIN CTE_CUPS AS CUPS2 WITH (NOLOCK) ON CUPS2.Id=SODI.CUPSEntityId
  WHERE SOD.RecordType=1 AND SOD.SettlementType IN (2,3) and IM.Agrupador IN('Resonancia','Imagenes') and IM.ReportType in ('Causacion', 'Calidad')
  AND CAST(SOD.ServiceDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
)

---*************************************************************************************************************************************************************************-----

SELECT FUENTE,FUNCIONAL,AMBITO,IDENTIFICACION,PACIENTE,INGRESO,FOLIO,[FECHA ORDEN/EJECUCION],CUPS,[DESCRIPCION CUPS],[DESCRIPCION RELACIONADA],CANTIDAD,EXTRAMURAL,[ID PROFESIONAL],
PROFESIONAL,ESPECIALIDAD,CIE10,DIAGNOSTICO,NIT,ENTIDAD,[CODIGO GRUPO ATENCION],[GRUPO ATENCION],[FACTURADO],[NRO FACTURA],[AGRUPADOR],AUTO,GENSERVICEORDER,
CASE WHEN [FECHA DE TOMA] < [FECHA CITA] THEN [FECHA DE TOMA] ELSE [FECHA CITA] end [FECHA CITA],[FECHA DE TOMA],
DATEDIFF(DAY,(CASE WHEN [FECHA DE TOMA] < [FECHA CITA] THEN [FECHA DE TOMA] ELSE [FECHA CITA] END),[FECHA DE TOMA]) AS  'TEMPO DE ESPERA FEC CITA VS FEC TOMA'
FROM CTE_DATOS_ORDENES_IMAGENES
UNION ALL
SELECT FUENTE,FUNCIONAL,AMBITO,IDENTIFICACION,PACIENTE,INGRESO,FOLIO,[FECHA ORDEN/EJECUCION],CUPS,[DESCRIPCION CUPS],[DESCRIPCION RELACIONADA],CANTIDAD,EXTRAMURAL,[ID PROFESIONAL],
PROFESIONAL,ESPECIALIDAD,CIE10,DIAGNOSTICO,NIT,ENTIDAD,[CODIGO GRUPO ATENCION],[GRUPO ATENCION],[FACTURADO],[NRO FACTURA],[AGRUPADOR],AUTO,GENSERVICEORDER,
CASE WHEN [FECHA DE TOMA] < [FECHA CITA] THEN [FECHA DE TOMA] ELSE [FECHA CITA] end [FECHA CITA],[FECHA DE TOMA],
DATEDIFF(DAY,(CASE WHEN [FECHA DE TOMA] < [FECHA CITA] THEN [FECHA DE TOMA] ELSE [FECHA CITA] END),[FECHA DE TOMA]) AS  'TEMPO DE ESPERA FEC CITA VS FEC TOMA'
FROM CTE_DATOS_EJECUCION_IMAGENES
UNION ALL
SELECT IMG.FUENTE,IMG.FUNCIONAL,IMG.AMBITO,IMG.IDENTIFICACION,IMG.PACIENTE,IMG.INGRESO,IMG.FOLIO,IMG.[FECHA ORDEN/EJECUCION],IMG.CUPS,[DESCRIPCION CUPS],IMG.[DESCRIPCION RELACIONADA],
IMG.CANTIDAD,IMG.EXTRAMURAL,IMG.[ID PROFESIONAL],IMG.PROFESIONAL,IMG.ESPECIALIDAD,IMG.CIE10,IMG.DIAGNOSTICO,IMG.NIT,IMG.ENTIDAD,IMG.[CODIGO GRUPO ATENCION],
IMG.[GRUPO ATENCION],IIF(ISNULL(IMG.[NRO FACTURA],ISNULL(PAQ.[NRO FACTURA],INC.[NRO FACTURA])) IS NULL,'NO','SI') 'FACTURADO',
ISNULL(IMG.[NRO FACTURA],ISNULL(PAQ.[NRO FACTURA],INC.[NRO FACTURA])) [NRO FACTURA],ISNULL(IMG.[AGRUPADOR],ISNULL(PAQ.[AGRUPADOR],INC.[AGRUPADOR])) [AGRUPADOR],
IMG.AUTO,IMG.GENSERVICEORDER,
CASE WHEN [FECHA DE TOMA] < [FECHA CITA] THEN [FECHA DE TOMA] ELSE [FECHA CITA] end [FECHA CITA],[FECHA DE TOMA],
DATEDIFF(DAY,(CASE WHEN [FECHA DE TOMA] < [FECHA CITA] THEN [FECHA DE TOMA] ELSE [FECHA CITA] END),[FECHA DE TOMA]) AS  'TEMPO DE ESPERA FEC CITA VS FEC TOMA'
FROM CTE_DATOS_CARGOS_IMAGENES IMG
LEFT JOIN CTE_DATOS_CARGOS_EMPAQUETADO PAQ ON IMG.AUTO=PAQ.ServiceOrderDetailId
LEFT JOIN CTE_DATOS_CARGOS_INCLUIDO INC ON IMG.AUTO=INC.ServiceOrderDetailId

--ORDER BY FUNCIONAL



--SET STATISTICS TIME OFF;
