-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_IMAGENES_SEGUIMIENTO
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE PROCEDURE [Report].[IND_SP_V2_EHR_IMAGENES_SEGUIMIENTO] 
 @IDENTIFICACION AS CHAR(25),
 @INGRESO AS CHAR(25)
AS

SELECT 'AMBULATORIO' 'AMBITO' ,O.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE',O.NUMINGRES 'INGRESO',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',FUN.UFUDESCRI 'UNIDAD FUNCIONAL','PROCEDIMIENTO' 'TIPO',
O.CODSERIPS 'CODIGO CUPS',IPS.DESSERIPS 'DESCRIPCION SERVICIO',O.CANTIDAD 'CANTIDAD',O.FECHAREG 'FECHA ORDEN','' FOLIO,
CASE O.ESTADO WHEN 1 THEN 'Ordenado' WHEN 2 THEN 'Realizado (Completado)' WHEN 3 THEN 'Interpretado' WHEN 4 THEN 'Sin Interfaz' WHEN 5 THEN 'Anulado' END 'ESTADO',
HA.Name 'ENTIDAD', CG.Name 'GRIPO DE ATENCION',PRO.NOMMEDICO 'PROFESIONAL', ESP.DESESPECI 'ESPECIALIDAD',O.GENSERVICEORDER 'ORDEN LIQUIDACION','CONTROL DE SERVICIOS AMBULATORIOS' 'FLUJO',
CAST(O.FECHAREG AS DATE) 'FECHA REALIZACION','' 'ADJUNTO'

FROM DBO.AMBORDOTROSPRO O WITH (NOLOCK)
INNER JOIN DBO.INPACIENT  AS PAC  WITH (NOLOCK) ON PAC.IPCODPACI =O.IPCODPACI 
INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES =O.NUMINGRES 
INNER JOIN DBO.INUNIFUNC AS FUN WITH (NOLOCK) ON FUN.UFUCODIGO =O.UFUCODIGO 
INNER JOIN DBO.INCUPSIPS AS IPS WITH (NOLOCK) ON IPS.CODSERIPS =O.CODSERIPS 
INNER JOIN CONTRACT.HealthAdministrator AS HA WITH (NOLOCK) ON HA.Id =O.GENCONENTITY 
INNER JOIN Contract .CareGroup AS CG WITH (NOLOCK) ON CG.Id =O.GENCAREGROUP 
LEFT JOIN DBO.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL =O.CODPROSAL 
LEFT JOIN DBO.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI =O.CODESPECI 
WHERE O.IPCODPACI =@IDENTIFICACION AND O.NUMINGRES =@INGRESO
UNION ALL
SELECT 'AMBULATORIO' 'AMBITO' ,O.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE',O.NUMINGRES 'INGRESO',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',FUN.UFUDESCRI 'UNIDAD FUNCIONAL','IMAGENES' 'TIPO',
O.CODSERIPS 'CODIGO CUPS',IPS.DESSERIPS 'DESCRIPCION SERVICIO',O.CANSERIPS 'CANTIDAD',O.FECORDMED  'FECHA ORDEN','' FOLIO,
CASE O.ESTSERIPS WHEN 1 THEN 'Ordenado' WHEN 2 THEN 'Estudio Realizado' WHEN 3 THEN 'Imagen Procesada' WHEN 4 THEN 'Estudio Interpretado' WHEN 5 THEN 'Remitido' WHEN 6 THEN 'Anulado'
WHEN 7 THEN 'Extramural' END 'ESTADO',HA.Name 'ENTIDAD', CG.Name 'GRIPO DE ATENCION',PRO.NOMMEDICO 'PROFESIONAL', ESP.DESESPECI 'ESPECIALIDAD',O.GENSERVICEORDER 'ORDEN LIQUIDACION',
'CONTROL DE SERVICIOS AMBULATORIOS' 'FLUJO',CAST(O.FECRECEXA AS DATE) 'FECHA REALIZACION',O.NOMARCIMG 'ADJUNTO'
FROM DBO.AMBORDIMA O
INNER JOIN DBO.INPACIENT  AS PAC  WITH (NOLOCK) ON PAC.IPCODPACI =O.IPCODPACI 
INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES =O.NUMINGRES 
INNER JOIN DBO.INUNIFUNC AS FUN WITH (NOLOCK) ON FUN.UFUCODIGO =O.UFUCODIGO 
INNER JOIN DBO.INCUPSIPS AS IPS WITH (NOLOCK) ON IPS.CODSERIPS =O.CODSERIPS
INNER JOIN CONTRACT.HealthAdministrator AS HA WITH (NOLOCK) ON HA.Id =O.GENCONENTITY 
INNER JOIN Contract .CareGroup AS CG WITH (NOLOCK) ON CG.Id =O.GENCAREGROUP 
LEFT JOIN DBO.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL =O.CODPROSAL 
LEFT JOIN DBO.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI =O.ESPEREALIZA 
WHERE O.IPCODPACI =@IDENTIFICACION AND O.NUMINGRES =@INGRESO
------
UNION ALL
SELECT 'HOSPITALARIO' 'AMBITO' ,O.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE',O.NUMINGRES 'INGRESO',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',FUN.UFUDESCRI 'UNIDAD FUNCIONAL','IMAGENES' 'TIPO',
O.CODSERIPS 'CODIGO CUPS',IPS.DESSERIPS 'DESCRIPCION SERVICIO',O.CANSERIPS 'CANTIDAD',O.FECORDMED  'FECHA ORDEN',O.NUMEFOLIO 'FOLIO',
CASE O.ESTSERIPS WHEN 1 THEN 'Ordenado' WHEN 2 THEN 'Estudio Realizado' WHEN 3 THEN 'Imagen Procesada' WHEN 4 THEN 'Estudio Interpretado' WHEN 5 THEN 'Remitido' WHEN 6 THEN 'Anulado'
WHEN 7 THEN 'Extramural' END 'ESTADO',HA.Name 'ENTIDAD', CG.Name 'GRIPO DE ATENCION',PRO.NOMMEDICO 'PROFESIONAL', ESP.DESESPECI 'ESPECIALIDAD',O.GENSERVICEORDER 'ORDEN LIQUIDACION',
'HISTORIA CLINICA INTRAHOSPITALARIA' 'FLUJO',O.FECRECEXA 'FECHA REALIZACION',O.NOMARCIMG 'ADJUNTO'

FROM DBO.HCORDIMAG O
INNER JOIN DBO.INPACIENT  AS PAC  WITH (NOLOCK) ON PAC.IPCODPACI =O.IPCODPACI 
INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES =O.NUMINGRES 
INNER JOIN DBO.INUNIFUNC AS FUN WITH (NOLOCK) ON FUN.UFUCODIGO =O.UFUCODIGO 
INNER JOIN DBO.INCUPSIPS AS IPS WITH (NOLOCK) ON IPS.CODSERIPS =O.CODSERIPS
INNER JOIN CONTRACT.HealthAdministrator AS HA WITH (NOLOCK) ON HA.Id =ING.GENCONENTITY 
INNER JOIN Contract .CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP 
LEFT JOIN DBO.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL =O.CODPROSAL 
LEFT JOIN DBO.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI =O.ESPEREALIZA 
WHERE O.IPCODPACI =@IDENTIFICACION AND O.NUMINGRES =@INGRESO