-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_ERP_PRODUCTIVIDAD_COMPARACION_CONSOLIDADAvsDETALLADA
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE PROCEDURE [Report].[IND_SP_V2_ERP_PRODUCTIVIDAD_COMPARACION_CONSOLIDADAvsDETALLADA] 
@ANO AS INT,
@MES AS INT
AS

WITH CTE_FACTURADOS_UNICOS
AS
(
  SELECT DISTINCT  JV.Id ,JV.EntityCode ,JV.EntityId,CAST(JV.VoucherDate AS DATE) VoucherDate,sum(JVD.CreditValue) Valor_Credito,JV.CreationUser ,F.AdmissionNumber
  FROM GeneralLedger.JournalVouchers JV WITH (NOLOCK)
  INNER JOIN GeneralLedger .JournalVoucherDetails AS JVD WITH (NOLOCK) ON JVD.IdAccounting =JV.Id
  LEFT  JOIN Billing .Invoice AS F WITH (NOLOCK) ON F.Id =JV.EntityId 
  WHERE YEAR(JV.VoucherDate)=@ANO AND MONTH(JV.VoucherDate)=@MES  AND JV.LegalBookId =1 AND jv.EntityName ='Invoice' AND IdJournalVoucher =29
  --and JV.EntityCode in ('IND161039')
  GROUP BY JV.Id ,JV.EntityCode ,JV.EntityId,CAST(JV.VoucherDate AS DATE),JV.CreationUser ,F.AdmissionNumber 
),
CTE_BILLING_FACTURADO_CONSOLIDADO
AS
(
    SELECT I.PatientCode 'IDENTIFICACION',RTRIM(PAC.IPNOMCOMP) 'PACIENTE',I.AdmissionNumber 'INGRESO',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',I.InvoiceNumber 'NRO FACTURA',
	CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',I.TotalInvoice 'VALOR TOTAL'
    FROM Billing.Invoice AS I WITH (NOLOCK)
     INNER JOIN CTE_FACTURADOS_UNICOS AS UNI WITH (NOLOCK) ON UNI.EntityId =I.Id 
     INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES =I.AdmissionNumber 
     INNER JOIN Common .ThirdParty AS TP WITH (NOLOCK) ON TP.Id =I.ThirdPartyId 
     INNER JOIN Contract .CareGroup AS CG WITH (NOLOCK) ON CG.Id =I.CareGroupId 
     INNER JOIN DBO.INPACIENT AS PAC  WITH (NOLOCK) ON PAC.IPCODPACI =I.PatientCode
     LEFT JOIN DBO.SEGusuaru AS USU WITH (NOLOCK) ON USU.CODUSUARI =UNI.CreationUser 
     LEFT JOIN DBO.INUNIFUNC AS FUN WITH (NOLOCK) ON FUN.UFUCODIGO =ISNULL(ING.UFUACTPAC,ING.UFUCODIGO)
 ),
 CTE_BILLING_FACTURADOS_DETALLADO
AS
(
   SELECT I.PatientCode 'IDENTIFICACION',RTRIM(PAC.IPNOMCOMP) 'PACIENTE',I.AdmissionNumber 'INGRESO',CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
   I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',SUM(ISNULL(IDS.TotalSalesPrice,ID.GrandTotalSalesPrice)) 'VALOR TOTAL'
   
   FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN CTE_FACTURADOS_UNICOS AS UNI WITH (NOLOCK) ON UNI.EntityId =I.Id 
   INNER JOIN Billing .InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id 
   INNER JOIN Billing .ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing .ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
   INNER JOIN Payroll.CostCenter AS COST WITH (NOLOCK) ON COST.Id =SOD.CostCenterId
   INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES =I.AdmissionNumber 
   INNER JOIN Common .ThirdParty AS TP WITH (NOLOCK) ON TP.Id =I.ThirdPartyId 
   INNER JOIN Contract .CareGroup AS CG WITH (NOLOCK) ON CG.Id =I.CareGroupId 
   INNER JOIN DBO.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =I.PatientCode
   LEFT JOIN Contract.CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id = SOD.CUPSEntityId
   LEFT JOIN Inventory.InventoryProduct AS IPR WITH (NOLOCK) ON IPR.Id = SOD.ProductId
   LEFT JOIN Contract .CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =SOD.CUPSEntityContractDescriptionId  AND SOD.CUPSEntityId=DESCR.CUPSEntityId 
   LEFT JOIN Contract .ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
   LEFT JOIN Billing .ServiceOrderDetail AS SODP WITH (NOLOCK) ON SODP.Id =SOD.PackageServiceOrderDetailId 
   LEFT JOIN Contract.CUPSEntity AS CUPSP WITH (NOLOCK) ON CUPSP.Id = SODP.CUPSEntityId
   LEFT JOIN Billing .ServiceOrderDetail AS SODI WITH (NOLOCK) ON SODI.Id =SOD.IncludeServiceOrderDetailId 
   LEFT JOIN Contract.CUPSEntity AS CUPSI WITH (NOLOCK) ON CUPSI.Id = SODI.CUPSEntityId
   LEFT JOIN dbo.INPROFSAL AS MED WITH (NOLOCK) ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
   LEFT JOIN dbo.INESPECIA AS ESPMED WITH (NOLOCK) ON ESPMED.CODESPECI = SOD.PerformsProfessionalSpecialty 
   LEFT JOIN Common.ThirdParty AS TPT WITH (NOLOCK) ON TPT.Id =SOD.PerformsHealthProfessionalThirdPartyId 
   LEFT JOIN Billing .InvoiceDetailSurgical AS IDS WITH (NOLOCK) ON IDS.InvoiceDetailId =ID.Id AND IDS.OnlyMedicalFees = '0' --AND IDS.SurchargeApply <>1
   LEFT JOIN Contract .IPSService AS IPS WITH (NOLOCK) ON IPS.Id =IDS.IPSServiceId 
   LEFT JOIN dbo.INPROFSAL AS MEDQX WITH (NOLOCK) ON MEDQX.CODPROSAL = IDS.PerformsHealthProfessionalCode
   LEFT JOIN dbo.INESPECIA AS ESPQX WITH (NOLOCK) ON ESPQX.CODESPECI = MEDQX.CODESPEC1
   LEFT JOIN GeneralLedger .MainAccounts AS MA WITH (NOLOCK) ON MA.Id =ISNULL(IDS.IncomeMainAccountId,SOD.IncomeMainAccountId)
   GROUP BY I.PatientCode,PAC.IPNOMCOMP,I.AdmissionNumber,CAST(ING.IFECHAING AS DATE),I.InvoiceNumber,CAST(I.InvoiceDate AS DATE)
)

SELECT CON.IDENTIFICACION ,CON.PACIENTE ,CON.INGRESO,CON.[NRO FACTURA] ,CON.[FECHA INGRESO] ,CON.[FECHA FACTURA] ,CAST(CON.[VALOR TOTAL] AS numeric ) [VALOR TOTAL CONSOLIDADO] ,
CAST(DET.[VALOR TOTAL] AS numeric ) [VALOR TOTAL DETALLADO], (CAST(CON.[VALOR TOTAL] AS numeric )-CAST(DET.[VALOR TOTAL] AS numeric )) 'VALOR DIFERENCIA'
FROM CTE_BILLING_FACTURADOS_DETALLADO DET
INNER JOIN CTE_BILLING_FACTURADO_CONSOLIDADO CON  ON CON.INGRESO =DET.INGRESO AND CON.[NRO FACTURA] =DET.[NRO FACTURA] 