-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_ERP_PACIENTES_ATENDIDOS_V1
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE PROCEDURE [Report].[IND_SP_V2_ERP_PACIENTES_ATENDIDOS_V1]

@FECHAINI AS DATE,
@FECHAFIN AS DATE

--DECLARE @FECHAINI AS DATE='2024-10-01';
--DECLARE @FECHAFIN AS DATE='2024-10-31';


--SET STATISTICS TIME ON;
AS
SELECT CAST(I.IFECHAING AS DATE) 'FECHA ATENCION',CASE PAC.IPTIPODOC WHEN '1'  THEN 'CC'WHEN '2'  THEN 'CE'WHEN '3'  THEN 'TI'WHEN '4'  THEN 'RC'WHEN '5'  
THEN 'PA'WHEN '6'  THEN 'AS'WHEN '7'  THEN 'MS' WHEN '8'  THEN 'NU'WHEN '9'  THEN 'NV'WHEN '10' THEN 'CD'WHEN '11' THEN 'SC'WHEN '12' THEN 'PE' WHEN '13'
THEN 'PT'WHEN '14' THEN 'DE'WHEN '15' THEN 'SI'END AS [TIPO IDENTIFICACION],
I.IPCODPACI 'IDENTIFICACION',UPPER(PAC.IPPRIAPEL) 'PRIMER APELLIDO',UPPER(PAC.IPSEGAPEL) 'SEGUNDO APELLIDO',
UPPER(PAC.IPPRINOMB) 'PRIMER NOMBRE',UPPER(PAC.IPSEGNOMB) 'SEGUNDO NOMBRE', PAC.IPNOMCOMP 'NOMBRE COMPLETO PACIENTE',
CASE PAC.IPSEXOPAC WHEN '1' THEN 'HOMBRE' WHEN '2' THEN 'MUJER' END AS [SEXO],CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
CONCAT(FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.IFECHAING) AS FLOAT) / 365), ' años, ',FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.IFECHAING) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.IFECHAING) AS FLOAT) / 365)) * 12),' meses,',FLOOR(((((CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.IFECHAING) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.IFECHAING) AS FLOAT) / 365)) * 12) - FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.IFECHAING) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.IFECHAING) AS FLOAT) / 365)) * 12)) * (365 / 12))), ' días') AS [EDAD],
I.NUMINGRES 'INGRESO', ISNULL(G.NIT,TP.NIT) [NIT],ISNULL(G.[ENTIDAD],HA.Name) [ENTIDAD],
ISNULL(G.[REGIMEN],
CASE HA.EntityType WHEN 1 THEN 'Contributivo' WHEN 2 THEN 'Subsidiado' WHEN 3 THEN 'Vinculados' WHEN 4 THEN 'Vinculados'
 WHEN 5 THEN 'ARL Riesgos Laborales' WHEN 6 THEN 'MP Medicina Prepagada' WHEN 7 THEN 'IPS Privada' WHEN 8 THEN 'IPS Publica' WHEN 9 THEN 'Regimen Especial'
 WHEN 10 THEN 'Accidentes de transito' WHEN 11 THEN 'Fosyga' WHEN 12 THEN 'Otros' WHEN 99 THEN 'Particulares' ELSE 'Otros' end) [REGIMEN],
 CASE I.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END [AMBITO],
 UNII.UFUDESCRI [UNIDAD ADMISION],
 UNIH.UFUDESCRI [UNIDAD PRIMERA HC],
 UNIE.UFUDESCRI [UNIDAD EGRESO],
 DEP.nomdepart [DEPARTAMENTO RESIDENCIA],MUN.MUNNOMBRE AS [MUNICIPIO RESIDENCIA],PAC.IPTELEFON [TELEFONO 1],PAC.IPTELMOVI [TELEFONO 2],
 MUN.DEPMUNCOD  [CODIGO MUNICIPIO],
 ISNULL(DIA.CODDIAGNO,'Z000') [CIE10],ISNULL(DIA.NOMDIAGNO,'EXAMEN MEDICO GENERAL') [DIAGNOSTICO]

FROM DBO.ADINGRESO I
INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =I.IPCODPACI
LEFT JOIN
(
 SELECT distinct RC.AdmissionNumber,RCD.HealthAdministratorId,TP.NIT,HA.Name 'ENTIDAD',
 CASE HA.EntityType WHEN 1 THEN 'Contributivo' WHEN 2 THEN 'Subsidiado' WHEN 3 THEN 'Vinculados' WHEN 4 THEN 'Vinculados'
 WHEN 5 THEN 'ARL Riesgos Laborales' WHEN 6 THEN 'MP Medicina Prepagada' WHEN 7 THEN 'IPS Privada' WHEN 8 THEN 'IPS Publica' WHEN 9 THEN 'Regimen Especial'
 WHEN 10 THEN 'Accidentes de transito' WHEN 11 THEN 'Fosyga' WHEN 12 THEN 'Otros' WHEN 99 THEN 'Particulares' ELSE 'Otros' end [REGIMEN]
 FROM Billing.RevenueControl RC
 INNER JOIN Billing.RevenueControlDetail RCD WITH (NOLOCK) ON RC.Id=RCD.RevenueControlId
 INNER JOIN Contract.HealthAdministrator HA WITH (NOLOCK) ON HA.ID=RCD.HealthAdministratorId
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 WHERE RCD.Status<>3 --AND AdmissionNumber IN ('73497','98802','6EE7DF0089')
) AS G ON G.AdmissionNumber=I.NUMINGRES
INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= I.GENCONENTITY
INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
LEFT JOIN INUBICACI AS UBI WITH (NOLOCK) ON PAC.AUUBICACI = UBI.AUUBICACI
LEFT JOIN INMUNICIP AS MUN WITH (NOLOCK) ON UBI.DEPMUNCOD = MUN.DEPMUNCOD
LEFT JOIN INDEPARTA AS DEP WITH (NOLOCK) ON DEP.depcodigo = MUN.DEPCODIGO
LEFT JOIN DBO.INUNIFUNC AS UNII WITH (NOLOCK) ON UNII.UFUCODIGO=I.UFUCODIGO
LEFT JOIN DBO.INUNIFUNC AS UNIH WITH (NOLOCK) ON UNIH.UFUCODIGO=I.UFUINGMED
LEFT JOIN DBO.INUNIFUNC AS UNIE WITH (NOLOCK) ON UNIE.UFUCODIGO=ISNULL(I.UFUEGRMED,I.UFUCODIGO)
LEFT JOIN DBO.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO =ISNULL(I.CODDIAEGR,I.CODDIAING ) 
WHERE CAST(I.IFECHAING AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN AND IESTADOIN <>'A'
--AND I.NUMINGRES='6EE7DF0089'   25507

--SET STATISTICS TIME OFF;
