-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_LABORATORIOS_SEGUIMIENTO_CARGUE
-- Extracted by Fabric SQL Extractor SPN v3.9.0


--CONSULTA POR RANGO DE FECHA

CREATE PROCEDURE [Report].[IND_SP_V2_EHR_LABORATORIOS_SEGUIMIENTO_CARGUE] 
@FechaInicial date,
@FechaFinal date

AS

--DECLARE @FechaInicial as date = '2023-11-01';
--DECLARE @FechaFinal as date = '2023-11-01';

WITH CTE_LABORATORIOS AS
(
SELECT 'HOSPITALARIO' 'AMBITO',L.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE' ,L.NUMINGRES 'INGRESO',
CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO'WHEN 'F' THEN 'FACTURADO' WHEN 'A' THEN 'ANULADO' WHEN 'C' THEN 'CERRADO SIN CARGOS' WHEN 'P' THEN 'FACTURADO PARCIAL' END 'ESTADO INGRESO',
UNI.UFUDESCRI 'UNIDAD FUNCIONAL',PRO.NOMMEDICO 'PROFESIONAL',
L.NUMEFOLIO 'FOLIO ORDENAMIENTO' ,cast(L.FECORDMED as smalldatetime) 'FECHA ORDENAMIENTO' ,L.CODSERIPS 'CUPS',IPS.DESSERIPS 'DESCRIPCION LABORATORIO',L.CANSERIPS 'CANTIDAD',
CASE L.ESTSERIPS WHEN 1 THEN 'Solicitado' WHEN 2 THEN 'Muestra Recolectada' WHEN 3 THEN 'Resultado Entregado' WHEN 4 THEN 'Examen Interpretado' WHEN 5 THEN 'Remitido'
WHEN 6 THEN 'Anulado' WHEN 7 THEN 'Extramural' WHEN 8 THEN 'Muestra Recolectada Parcialmente' END 'ESTADO LABORATORIO',L.INTERPRET 'INTERPRETACION',
PRI.NOMMEDICO 'PROFESIONAL INTERPRETO',L.NUMFOLINT 'FOLIO INTERPRETO',CAST(L.FECRECMUE AS smalldatetime) 'FECHA RECOLECCION MUESTRA' ,L.NOMARCLAB 'ADJUNTO',
SEG.NOMUSUARI 'USUARIO',IIF(L.GENSERVICEORDER IS NULL,'NO','SI') 'LIQUIDADO'

FROM DBO.HCORDLABO AS L WITH (NOLOCK)
INNER JOIN DBO.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =L.IPCODPACI 
INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES =L.NUMINGRES 
INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =L.UFUCODIGO 
INNER JOIN DBO.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL =L.CODPROSAL 
INNER JOIN DBO.INCUPSIPS AS IPS WITH (NOLOCK) ON IPS.CODSERIPS =L.CODSERIPS 
LEFT  JOIN DBO.INPROFSAL AS PRI WITH (NOLOCK) ON PRI.CODPROSAL =L.CODPROINT 
LEFT  JOIN DBO.SEGusuaru AS SEG WITH (NOLOCK) ON SEG.CODUSUARI =L.USURECMUE 
WHERE L.MANEXTPRO =0

UNION ALL

SELECT 'HOSPITALARIO' 'AMBITO',L.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE' ,L.NUMINGRES 'INGRESO',
CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO'WHEN 'F' THEN 'FACTURADO' WHEN 'A' THEN 'ANULADO' WHEN 'C' THEN 'CERRADO SIN CARGOS' WHEN 'P' THEN 'FACTURADO PARCIAL' END 'ESTADO INGRESO',
UNI.UFUDESCRI 'UNIDAD FUNCIONAL',PRO.NOMMEDICO 'PROFESIONAL',
L.NUMEFOLIO 'FOLIO ORDENAMIENTO' ,cast(L.FECORDMED as smalldatetime) 'FECHA ORDENAMIENTO' ,L.CODSERIPS 'CUPS',IPS.DESSERIPS 'DESCRIPCION LABORATORIO',L.CANSERIPS 'CANTIDAD',
CASE L.ESTSERIPS WHEN 1 THEN 'Solicitado' WHEN 2 THEN 'Muestra Recolectada' WHEN 3 THEN 'Resultado Entregado' WHEN 4 THEN 'Examen Interpretado' WHEN 5 THEN 'Remitido'
WHEN 6 THEN 'Anulado' WHEN 7 THEN 'Extramural' WHEN 8 THEN 'Muestra Recolectada Parcialmente' END 'ESTADO LABORATORIO',L.INTERPRET 'INTERPRETACION',
PRI.NOMMEDICO 'PROFESIONAL INTERPRETO',L.NUMFOLINT 'FOLIO INTERPRETO',CAST(L.FECRECMUE AS smalldatetime) 'FECHA RECOLECCION MUESTRA',L.NOMARCLAB 'ADJUNTO',
SEG.NOMUSUARI 'USUARIO',IIF(L.GENSERVICEORDER IS NULL,'NO','SI') 'LIQUIDADO'

FROM DBO.HCORDLABO AS L WITH (NOLOCK)
INNER JOIN DBO.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =L.IPCODPACI 
INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES =L.NUMINGRES 
INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =L.UFUCODIGO 
INNER JOIN DBO.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL =L.CODPROSAL 
INNER JOIN DBO.INCUPSIPS AS IPS WITH (NOLOCK) ON IPS.CODSERIPS =L.CODSERIPS 
INNER JOIN
	(
		SELECT INGMH.NUMINGRESHIJO, MIN(INGMH.ID) ID
		FROM dbo.HCINGRESORECNAC INGMH
		GROUP BY INGMH.NUMINGRESHIJO
	) INGMHD ON L.NUMINGRES = INGMHD.NUMINGRESHIJO
	INNER JOIN dbo.HCINGRESORECNAC INGMH on INGMHD.ID = INGMH.ID
	INNER JOIN dbo.HCRECINAC RN on INGMH.NUMINGRESHIJO  = rn.NUMINGRESHIJO  
	LEFT  JOIN DBO.INPROFSAL AS PRI WITH (NOLOCK) ON PRI.CODPROSAL =L.CODPROINT 
	LEFT  JOIN DBO.SEGusuaru AS SEG WITH (NOLOCK) ON SEG.CODUSUARI =L.USURECMUE
WHERE L.MANEXTPRO =0

UNION ALL

SELECT 'AMBULATORIO' 'AMBITO',L.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE' ,L.NUMINGRES 'INGRESO',
CASE ING.IESTADOIN WHEN '' THEN 'ABIERTO'WHEN 'F' THEN 'FACTURADO' WHEN 'A' THEN 'ANULADO' WHEN 'C' THEN 'CERRADO SIN CARGOS' WHEN 'P' THEN 'FACTURADO PARCIAL' END 'ESTADO INGRESO',
UNI.UFUDESCRI 'UNIDAD FUNCIONAL',PRO.NOMMEDICO 'PROFESIONAL',
'' 'FOLIO ORDENAMIENTO' ,cast(L.FECORDMED as smalldatetime) 'FECHA ORDENAMIENTO' ,L.CODSERIPS 'CUPS',IPS.DESSERIPS 'DESCRIPCION LABORATORIO',L.CANSERIPS 'CANTIDAD',
CASE L.ESTSERIPS WHEN 1 THEN 'Solicitado' WHEN 2 THEN 'Muestra Recolectada' WHEN 3 THEN 'Resultado Entregado' WHEN 4 THEN 'Examen Interpretado' WHEN 5 THEN 'Remitido'
WHEN 6 THEN 'Anulado' WHEN 7 THEN 'Extramural' WHEN 8 THEN 'Muestra Recolectada Parcialmente' END 'ESTADO LABORATORIO',L.INTERPRET 'INTERPRETACION',
PRI.NOMMEDICO 'PROFESIONAL INTERPRETO',L.NUMFOLINT 'FOLIO INTERPRETO',CAST(L.FECRECMUE AS smalldatetime) 'FECHA RECOLECCION MUESTRA' ,L.NOMARCLAB 'ADJUNTO',
SEG.NOMUSUARI 'USUARIO',IIF(G.CODE IS NULL,'NO','SI') 'LIQUIDADO'

FROM DBO.AMBORDLAB AS L WITH (NOLOCK)
INNER JOIN DBO.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =L.IPCODPACI 
INNER JOIN DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES =L.NUMINGRES 
INNER JOIN DBO.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO =L.UFUCODIGO 
INNER JOIN DBO.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL =L.CODPROSAL 
INNER JOIN DBO.INCUPSIPS AS IPS WITH (NOLOCK) ON IPS.CODSERIPS =L.CODSERIPS 
LEFT  JOIN DBO.INPROFSAL AS PRI WITH (NOLOCK) ON PRI.CODPROSAL =L.CODPROINT 
LEFT  JOIN DBO.SEGusuaru AS SEG WITH (NOLOCK) ON SEG.CODUSUARI =L.USURECMUE 
LEFT  JOIN 
 (
  SELECT so.AdmissionNumber ,sod.CUPSEntityId ,CUPS.Code  FROM Billing.ServiceOrder SO WITH (NOLOCK)
   INNER JOIN Billing .ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId 
   INNER JOIN Contract .CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id =SOD.CUPSEntityId 
) as G ON G.AdmissionNumber =L.NUMINGRES AND L.CODSERIPS =G.Code 
--WHERE L.NUMINGRES ='389C2FEE13'

--SELECT * FROM DBO.AMBORDLAB WHERE NUMINGRES ='389C2FEE13'
)

SELECT * FROM CTE_LABORATORIOS 
WHERE CAST([FECHA ORDENAMIENTO] AS DATE) BETWEEN  @FechaInicial AND @FechaFinal
