-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_CIRUGIAS_REALIZADAS_V1
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE PROCEDURE [Report].[IND_SP_V2_EHR_CIRUGIAS_REALIZADAS_V1]
@FECHAINI DATE,
@FECHAFIN DATE
AS

--DECLARE @FECHAINI DATE='2024-12-01';
--DECLARE @FECHAFIN DATE='2024-12-31';

SELECT DISTINCT INF.IPCODPACI [NRO IDENTIFICACION],RTRIM(D.IPPRIAPEL) AS [PRIMER APELLIDO], RTRIM(D.IPSEGAPEL) AS [SEGUNDO APELLIDO], RTRIM(D.IPPRINOMB) AS [PRIMER NOMBRE], 
RTRIM(D.IPSEGNOMB) AS [SEGUNDO NOMBRE],INF.NUMINGRES [INGRESO], CASE TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END [AMBITO],
UNI.UFUDESCRI [UNIDAD FUNCIONAL],
INF.CODDIAPRE [CIE10_PRE],DIAI.NOMDIAGNO [DIAGNOSTICO PRE OPERATORIO],INF.CODDIAPOS [CIE10_POS],DIAE.NOMDIAGNO [DIAGNOSTICO POS OPERATORIO],
INF.FECHORINI [FECHA INICIAL QX],INF.FECHORFIN [FECHA FINAL QX],INF.AUTO,REA.CODSERIPS [CUPS],CUPS.DESSERIPS [DESCRIPCION PROCEDIMIENTO],
CASE REA.QXPRINCIP WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END 'PROCEDIMIENTO PRINCIPAL',
IIF(G.[UNIDAD FUNCIONAL SALA] IS NOT NULL,G.[UNIDAD FUNCIONAL SALA],IIF(UFUTIPUNI=19,UNI.UFUDESCRI,NULL)) [UNIDAD FUNCIONAL SALA]
 FROM dbo.HCQXINFOR INF WITH (NOLOCK)
 INNER JOIN dbo.HCQXREALI AS REA WITH (NOLOCK) ON INF.IPCODPACI=REA.IPCODPACI AND REA.NUMINGRES=INF.NUMINGRES AND REA.NUMEFOLIO=INF.NUMEFOLIO
 INNER JOIN dbo.INPACIENT AS D WITH (NOLOCK) ON INF.IPCODPACI = D.IPCODPACI
 INNER JOIN dbo.ADINGRESO ING WITH (NOLOCK) ON INF.NUMINGRES=ING.NUMINGRES
 LEFT JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON REA.UFUCODIGO=UNI.UFUCODIGO
 LEFT JOIN dbo.INDIAGNOS AS DIAI WITH (NOLOCK) ON DIAI.CODDIAGNO=INF.CODDIAPRE
 LEFT JOIN dbo.INDIAGNOS AS DIAE WITH (NOLOCK) ON DIAE.CODDIAGNO=INF.CODDIAPOS
 LEFT JOIN dbo.INCUPSIPS AS CUPS WITH (NOLOCK) ON CUPS.CODSERIPS=REA.CODSERIPS
 LEFT JOIN 
 (
   SELECT IPCODPACI,CAST(FECHORAIN AS DATE) FECHORAIN ,AGENSALAC, UNI.UFUDESCRI [UNIDAD FUNCIONAL SALA],QX.NUMINGRES
   FROM dbo.AGEPROGQX QX
   LEFT JOIN dbo.AGENSALAC SAL ON QX.AGENSALAC=SAL.CODCONCEC
   LEFT JOIN DBO.INUNIFUNC AS UNI ON SAL.UFUCODIGO=UNI.UFUCODIGO
   --WHERE IPCODPACI='79667958' 
   GROUP BY IPCODPACI,CAST(FECHORAIN AS DATE),AGENSALAC,UNI.UFUDESCRI,QX.NUMINGRES
 ) AS G ON (G.IPCODPACI=INF.IPCODPACI AND CAST(G.FECHORAIN AS DATE)=CAST(INF.FECHORINI AS DATE)) OR (G.NUMINGRES=INF.NUMINGRES)
WHERE cast(INF.FECHORINI as date) BETWEEN @FECHAINI AND @FECHAFIN
--AND INF.IPCODPACI='1064987145'--INF.NUMINGRES='146975    '   ---2492
order by INF.NUMINGRES, INF.FECHORINI

/*
SELECT IPCODPACI,CAST(FECHORAIN AS DATE) FECHORAIN ,AGENSALAC, UNI.UFUDESCRI
FROM dbo.AGEPROGQX QX
LEFT JOIN dbo.AGENSALAC SAL ON QX.AGENSALAC=SAL.CODCONCEC
LEFT JOIN DBO.INUNIFUNC AS UNI ON SAL.UFUCODIGO=UNI.UFUCODIGO
WHERE IPCODPACI='1064987145' 
GROUP BY IPCODPACI,CAST(FECHORAIN AS DATE),AGENSALAC,UNI.UFUDESCRI
*/