-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_AGENDAMIENTO_AGENDAS_CONSOLIDADAS
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE PROCEDURE [Report].[IND_SP_V2_EHR_AGENDAMIENTO_AGENDAS_CONSOLIDADAS] 
@FechaInicial date,
@FechaFinal date
AS

WITH CTE_ACTIVIDADES

AS
(
  SELECT ROW_NUMBER () OVER (PARTITION BY AG.CODAUTONU ORDER BY AG.CODACTMED ) NUMERO, AG.CODAUTONU, AG.CODACTMED, ACT.DESACTMED
  FROM AGAGEMEDD AG
  INNER JOIN AGACTIMED ACT ON ACT.CODACTMED=AG.CODACTMED
),

CTE_LOGICA
AS
(
SELECT DISTINCT PROF.CODPROSAL 'IDENTIFICACION',PROF.NOMMEDICO 'NOMBRE MEDICO', CON.DESCRICON 'CONSULTORIO',CASE WHEN CON.DESCRICON IS NULL THEN SAL.DESCRIPSAL ELSE 'N/A' END 'SALA', ESP.DESESPECI 'ESPECIALIDAD', 
CASE DATENAME(dw,AGE.FECHORAIN)
     when 'Monday' then '1.LUNES'
     when 'Tuesday' then '2.MARTES'
     when 'Wednesday' then '3.MIERCOLES'
     when 'Thursday' then '4.JUEVES'
     when 'Friday' then '5.VIERNES'
     when 'Saturday' then '6.SABADO'
     when 'Sunday' then '7.DOMINGO' END 'DIA DE LA SEMANA',
 CONCAT(SUBSTRING(CONVERT(VARCHAR,CAST( AGE.FECHORAIN AS TIME )),1,5 ),' ','-',' ',SUBSTRING(CONVERT(VARCHAR,CAST(AGE.FECHORAFI AS TIME)),1,5)) 'HORARIO', 
 CONCAT(ACT1.DESACTMED,'-',ACT2.DESACTMED,'-',ACT3.DESACTMED,'-',ACT4.DESACTMED,'-',ACT5.DESACTMED,'-',ACT6.DESACTMED,'-',ACT7.DESACTMED,'-',ACT8.DESACTMED,'-',ACT9.DESACTMED,'-',ACT10.DESACTMED) 'ACTIVIDAD MEDICA'
 ,FECHORAIN
FROM AGAGEMEDC AGE
INNER JOIN INPROFSAL PROF ON PROF.CODPROSAL=AGE.CODPROSAL
INNER JOIN CTE_ACTIVIDADES ACT1 ON ACT1.CODAUTONU=AGE.CODAUTONU AND ACT1.NUMERO=1
LEFT JOIN CTE_ACTIVIDADES ACT2 ON ACT2.CODAUTONU=AGE.CODAUTONU AND ACT2.NUMERO=2
LEFT JOIN CTE_ACTIVIDADES ACT3 ON ACT3.CODAUTONU=AGE.CODAUTONU AND ACT3.NUMERO=3
LEFT JOIN CTE_ACTIVIDADES ACT4 ON ACT4.CODAUTONU=AGE.CODAUTONU AND ACT4.NUMERO=4
LEFT JOIN CTE_ACTIVIDADES ACT5 ON ACT5.CODAUTONU=AGE.CODAUTONU AND ACT2.NUMERO=5
LEFT JOIN CTE_ACTIVIDADES ACT6 ON ACT6.CODAUTONU=AGE.CODAUTONU AND ACT3.NUMERO=6
LEFT JOIN CTE_ACTIVIDADES ACT7 ON ACT7.CODAUTONU=AGE.CODAUTONU AND ACT4.NUMERO=7
LEFT JOIN CTE_ACTIVIDADES ACT8 ON ACT8.CODAUTONU=AGE.CODAUTONU AND ACT2.NUMERO=8
LEFT JOIN CTE_ACTIVIDADES ACT9 ON ACT9.CODAUTONU=AGE.CODAUTONU AND ACT3.NUMERO=9
LEFT JOIN CTE_ACTIVIDADES ACT10 ON ACT10.CODAUTONU=AGE.CODAUTONU AND ACT4.NUMERO=10
LEFT JOIN AGCONSULT CON ON CON.CODIGOCON=AGE.CODIGOCON
LEFT JOIN INESPECIA ESP ON ESP.CODESPECI=AGE.CODESPECI
LEFT JOIN AGENSALAC SAL ON SAL.CODCONCEC=AGE.AGENSALAC

--WHERE AGE.CODPROSAL='80845089'
)

SELECT DISTINCT IDENTIFICACION,[NOMBRE MEDICO],CONSULTORIO,SALA,ESPECIALIDAD,ISNULL([1.LUNES],'NO ASIGNADO') [1.LUNES],ISNULL([2.MARTES],'NO ASIGNADO') [2.MARTES],ISNULL([3.MIERCOLES],'NO ASIGNADO') [3.MIERCOLES],
ISNULL([4.JUEVES],'NO ASIGNADO')[4.JUEVES] ,ISNULL([5.VIERNES],'NO ASIGNADO') [5.VIERNES],ISNULL([6.SABADO],'NO ASIGNADO') [6.SABADO],ISNULL([7.DOMINGO],'NO ASIGNADO')[7.DOMINGO], [ACTIVIDAD MEDICA]

FROM
(
  SELECT * FROM CTE_LOGICA 
  WHERE CAST(FECHORAIN AS DATE) BETWEEN  @FechaInicial AND  @FechaFinal
  --ORDER BY CONSULTORIO ,[DIA DE LA SEMANA] ASC
) AS SourceTable

PIVOT  
(MAX([HORARIO])
    FOR [DIA DE LA SEMANA] In([1.LUNES],[2.MARTES],[3.MIERCOLES],[4.JUEVES],[5.VIERNES],[6.SABADO],[7.DOMINGO])
) AS PVTTABLE
--order by [TIPO CONCEPTO] 



