-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_ERP_CAUSACION_PRODUCTIVIDAD_HEMO-CARDIO-NEUMO_FECHA_FACTURA_V2
-- Extracted by Fabric SQL Extractor SPN v3.9.0


--SET STATISTICS TIME ON;

CREATE PROCEDURE [Report].[IND_SP_V2_ERP_CAUSACION_PRODUCTIVIDAD_HEMO-CARDIO-NEUMO_FECHA_FACTURA_V2]

@FECHAINI AS DATE,
@FECHAFIN AS DATE

--DECLARE @FECHAINI AS DATE='2024-07-01';
--DECLARE @FECHAFIN AS DATE='2024-07-31';

AS

WITH CTE_CUPS
AS
(
   SELECT CUPS.Id,CUPS.Code [CUPS], CUPS.Description [DESCRIPCION CUPS], 
   CASE CUPS.ServiceType WHEN 1 then 'LABORATORIOS' WHEN 2 then 'PATOLOGIAS' WHEN 3 then 'IMAGENES DIAGNOSTICAS' WHEN 4 then 'PROCEDIMIENTOS NO QX'
   WHEN 5 then 'PROCEDIMIENTOS QX' WHEN 6 then 'INTERCONSULTAS'WHEN 7 then 'NINGUNO'WHEN 8 then 'CONSULTA EXTERNA' WHEN 9 THEN 'HEMOCOMPONENTES' ELSE 'OTROS' END AS 'TIPO SERVICIO',
   BG.CODE 'CODIGO FACTURACION',BG.NAME 'GRUPO FACTURACION',BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION',CGC.Code 'CODIGO GRUPO',CGC.Name 'GRUPO CUPS',
   CSG.CODE 'CODIGO SUBGRUPO',CSG.Name  'SUBGRUPO CUPS',
   CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
   ELSE 'N/A' END 'OBTENER CC',CUPS.ServiceType
   FROM Contract.CUPSEntity AS CUPS WITH (NOLOCK)
   INNER JOIN Billing.BillingGroup as BG WITH (NOLOCK) ON BG.Id=CUPS.BillingGroupId
   INNER JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=CUPS.BillingConceptId
   INNER JOIN Contract.CupsSubgroup AS CSG WITH (NOLOCK) ON CSG.Id =CUPS.CUPSSubGroupId
   INNER JOIN Contract.CupsGroup AS CGC WITH (NOLOCK) ON CGC.Id =CSG.CupsGroupId
 ),

CTE_IPS
AS
(
 SELECT IPS.ID,IPS.Code 'CODIGO SERVICIO IPS',IPS.Name 'NOMBRE SERVICIO IPS', CASE IPS.ServiceClass WHEN 1 THEN 'Ninguno' WHEN 2 THEN 'Cirujano' WHEN 3 THEN 'Anestesiologo' WHEN 4 THEN 'Ayudante' 
 WHEN 5 THEN 'Derecho Sala' WHEN 6 THEN 'Materiales Sutura'    WHEN 7 THEN 'Instrumentacion Quirurgica' ELSE 'Ninguno' end 'TIPO SERVICIO IPS',
 BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION IPS QX',
 CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
 ELSE 'N/A' END 'OBTENER CC'
 FROM Contract.IPSService IPS WITH (NOLOCK)
 LEFT JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=IPS.BillingConceptId
),

CTE_PAQUETE_UNICO
AS
(  --CA.CODIPSSEC 'CODIGO HABILITACION'
 SELECT DISTINCT I.CUFE,SOD.ID,SO.AdmissionNumber,I.PatientCode AS IDENTIFICACION,I.AdmissionNumber AS INGRESO,
 CASE I.Status WHEN 1 THEN 'FACTURADO' WHEN 2 THEN 'ANULADO' END 'ESTADO FACTURACION',I.InvoiceNumber AS [NRO FACTURA],CAST(I.AnnulmentDate AS DATE) [FECHA ANULACION],
 CAST(I.InvoiceDate AS DATE) AS 'FECHA BUSQUEDA', CAST(I.InitialDate AS DATE) 'FECHA INGRESO/CORTE FACTURA',CAST(I.OutputDate AS DATE) 'FECHA EGRESO/CORTE FACTURA',
 I.TotalInvoice AS [TOTAL FACTURA]
  FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Contract.CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.code
   WHERE I.STATUS=1 AND CAST(I.InvoiceDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN AND SOD.RecordType=1 AND SOD.Packaging=1 
   and IM.Agrupador in('Neumologia','Hemodinamia-Cardiologia') AND IM.ReportType ='Causacion' AND CUPS.ServiceType IN (3,4,5,6,7,8)
),

CTE_INCLUIDO_UNICO
AS
(  --CA.CODIPSSEC 'CODIGO HABILITACION'
 SELECT DISTINCT I.CUFE,SOD.ID,SO.AdmissionNumber,I.PatientCode AS IDENTIFICACION,I.AdmissionNumber AS INGRESO,
 CASE I.Status WHEN 1 THEN 'FACTURADO' WHEN 2 THEN 'ANULADO' END 'ESTADO FACTURACION',I.InvoiceNumber AS [NRO FACTURA],CAST(I.InvoiceDate AS DATE) AS [FECHA FACTURA],
 CAST(I.AnnulmentDate AS DATE) [FECHA ANULACION],CAST(I.InvoiceDate AS DATE) AS 'FECHA BUSQUEDA', CAST(I.InitialDate AS DATE) 'FECHA INGRESO/CORTE FACTURA',
 CAST(I.OutputDate AS DATE) 'FECHA EGRESO/CORTE FACTURA',I.TotalInvoice AS [TOTAL FACTURA]
  FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Contract.CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.code
   WHERE I.STATUS=1 AND CAST(I.InvoiceDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN AND SOD.RecordType=1 AND SOD.SettlementType IN (2,3) 
   and IM.Agrupador in('Neumologia','Hemodinamia-Cardiologia') AND IM.ReportType ='Causacion' and CUPS.ServiceType IN (3,4,5,6,7,8)
),

CTE_DATOS_PROCEDIMIENTOS
AS
(
 SELECT DISTINCT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,SO.code 'NRO ORDEN',I.PatientCode AS 'IDENTIFICACION',
  I.AdmissionNumber AS 'INGRESO',CAST(SOD.ServiceDate AS DATE) 'FECHA SERVICIO',IPSS.[CODIGO SERVICIO IPS],IPSS.[NOMBRE SERVICIO IPS],
  SOD.CUPSEntityId,CUPS.[CUPS],CUPS.[DESCRIPCION CUPS],CUPS.[CODIGO CONCEPTO],CUPS.[CONCEPTO FACTURACION],CUPS.[TIPO SERVICIO],
  FU.Code 'CODIGO UFS',FU.Name AS 'UNIDAD FUNCIONAL SERVICIO',CC.Code 'CODIGO CC',CC.NAME 'CENTRO DE COSTO',CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],
  isnull(ID.InvoicedQuantity,SOD.InvoicedQuantity) 'CANTIDAD',SOD.RateManualSalePrice,CUPS.[OBTENER CC],TP.Nit AS NIT,TP.Name AS ENTIDAD,
  isnull(CAST(ID.TotalSalesPrice AS NUMERIC(18,2)),cast(SOD.TotalSalesPrice as numeric(18,2))) 'VALOR UNITARIO',USUF.NOMUSUARI 'USUARIO FACTURO',
  isnull(CAST(ID.GrandTotalSalesPrice AS NUMERIC(18,2)),cast(SOD.GrandTotalSalesPrice as numeric(18,2))) 'VALOR TOTAL',
  ISNULL(G.[IDENTIFICACION PROFESIONAL],SOD.PerformsHealthProfessionalCode) 'IDENTIFICACION PROFESIONAL',CD.Name 'DESCRIPCION RELACIONADA',
  ISNULL(G.[PROFESIONAL REALIZO],MED.NOMMEDICO) 'PROFESIONAL',ISNULL(G.[ESPECIALIDA REALIZO],ESPMED.DESESPECI) 'ESPECIALIDAD',
  CASE SOD.Packaging WHEN 1 THEN 'SI' ELSE 'NO' END 'EMPAQUETADO',SOD.PackageServiceOrderDetailId,ISNULL(G.[AGREMIACION],MFC.ContractName) 'AGREMIACION',
  CASE SettlementType WHEN 3 THEN 'SI' ELSE 'NO' END 'INCLUIDO EN SERVICIO',IncludeServiceOrderDetailId,USUA.NOMUSUARI 'USUARIO ANULO',CAST(I.AnnulmentDate AS DATE) [FECHA ANULACION],
  CASE TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',sod.RateManualSalePrice [VALOR SERVICIO],IM.[GrupoCausacion] 'AGRUPADOR CAUSACION',
  IM.Type 'TIPO',CUPS.[GRUPO FACTURACION],G.[AUTO],IM.Percentage 'PORCENTAJE CAUSACION',so.status,RTRIM(PAC.IPNOMCOMP) AS PACIENTE,
  CASE IESTADOIN WHEN ' ' THEN 'ABIERTO' WHEN 'F' THEN 'FACTURADO' WHEN 'A' THEN 'ANULADO' WHEN 'C' THEN 'CERRADO' WHEN 'P' THEN 'PARCIAL' END 'ESTADO INGRESO',
  CASE I.Status WHEN 1 THEN 'FACTURADO' WHEN 2 THEN 'ANULADO' END 'ESTADO FACTURACION',SOD.IsDelete,ID.ID Id_DetFac,I.InvoiceNumber 'NRO FACTURA',
  CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CAST(G.[FECHA LECTURA] AS DATE) 'FECHA LECTURA' ,IM.Agrupador

 FROM 
   Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =SOD.CostCenterId
   INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
   INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON CAST(ING.NUMINGRES  AS CHAR)=CAST(I.AdmissionNumber AS CHAR)
   INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =I.PatientCode
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS]
   INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =I.ThirdPartyId
   INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =I.CareGroupId
   INNER JOIN CTE_IPS AS IPSS WITH (NOLOCK) ON IPSS.Id =SOD.IPSServiceId
   LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
   LEFT JOIN dbo.INESPECIA AS ESPMED WITH (NOLOCK) ON ESPMED.CODESPECI = SOD.PerformsProfessionalSpecialty
   LEFT JOIN DBO.SEGusuaru USUF WITH (NOLOCK) ON USUF.CODUSUARI = I.InvoicedUser
   LEFT JOIN DBO.SEGusuaru USUA WITH (NOLOCK) ON USUA.CODUSUARI = I.AnnulmentUser
   LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =SOD.CUPSEntityContractDescriptionId  AND SOD.CUPSEntityId=DESCR.CUPSEntityId 
   LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
    LEFT JOIN
  (
      SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.MEDREALEC,A.ESPEREALIZA,A.GENSERVICEORDER,A.AUTO, A.MEDREALEC 'IDENTIFICACION PROFESIONAL',
       PRO.NOMMEDICO 'PROFESIONAL REALIZO',ESP.DESESPECI 'ESPECIALIDA REALIZO',MFC.ContractName 'AGREMIACION',CAST(A.FECHLECT AS DATE) 'FECHA LECTURA'
       FROM dbo.HCORDIMAG A WITH (NOLOCK)
       INNER JOIN
       (
        SELECT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER,MAX(A.AUTO) AUTO
         FROM dbo.ADINGRESO ing WITH (NOLOCK)
	        INNER JOIN dbo.HCORDIMAG A with (nolock) ON ing.NUMINGRES = A.NUMINGRES
			where A.MEDREALEC IS NOT NULL AND A.GENSERVICEORDER IS NOT NULL 
	        GROUP BY A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER
       ) AS G ON G.AUTO=A.AUTO AND G.NUMINGRES=A.NUMINGRES AND G.CODSERIPS=A.CODSERIPS
       LEFT JOIN dbo.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL=A.MEDREALEC
       LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI =PRO.CODESPEC1
       LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =PRO.CODPROSAL AND HPC.LiquidateDefault = 1
       LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
    UNION ALL
        SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.MEDREALEC,A.ESPEREALIZA,A.GENSERVICEORDER,A.AUTO, A.MEDREALEC 'IDENTIFICACION PROFESIONAL',
         ISNULL(PRO.NOMMEDICO,PROE.NOMMEDICO) 'PROFESIONAL REALIZO',ISNULL(ESP.DESESPECI,ESPE.DESESPECI) 'ESPECIALIDA REALIZO',MFC.ContractName 'AGREMIACION',
		 CAST(A.FECHLECT AS DATE) 'FECHA LECTURA'
        FROM dbo.AMBORDIMA A WITH (NOLOCK)
        INNER JOIN
        (
         SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER,MAX(A.AUTO) AUTO
         FROM dbo.ADINGRESO ing WITH (NOLOCK)
	      INNER JOIN dbo.AMBORDIMA A WITH (NOLOCK) ON ing.NUMINGRES = A.NUMINGRES
		  where A.MEDREALEC IS NOT NULL AND A.GENSERVICEORDER IS NOT NULL
	      GROUP BY A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER
        ) AS G ON G.AUTO=A.AUTO AND G.NUMINGRES=A.NUMINGRES AND G.CODSERIPS=A.CODSERIPS
        LEFT JOIN dbo.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL=A.MEDREALEC
        LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI =PRO.CODESPEC1
        LEFT JOIN dbo.INPROFSAL AS PROE WITH (NOLOCK) ON PROE.CODPROSAL=A.USURECEXA
        LEFT JOIN dbo.INESPECIA AS ESPE WITH (NOLOCK) ON ESPE.CODESPECI =PROE.CODESPEC1
        LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =ISNULL(PRO.CODPROSAL,PROE.CODPROSAL) AND HPC.LiquidateDefault = 1
        LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
  ) AS G ON G.NUMINGRES=CAST(I.AdmissionNumber AS CHAR) AND G.GENSERVICEORDER=SO.ID AND G.CODSERIPS=CUPS.[CUPS]
  LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =ISNULL(G.[IDENTIFICACION PROFESIONAL],SOD.PerformsHealthProfessionalCode)
  AND HPC.LiquidateDefault = 1
  LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
   WHERE I.STATUS=1 AND SOD.RecordType=1 AND IM.Agrupador in('Neumologia','Hemodinamia-Cardiologia') AND IM.ReportType ='Causacion' AND CUPS.ServiceType  in (3,4,5,6,7,8) 
   AND CAST(I.InvoiceDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
),

CTE_DATOS_PROCEDIMIENTOS_EMPAQUETADO
AS
(
 SELECT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,so.status,SOD.CUPSEntityId,SOD.IPSServiceId,sod.PackageServiceOrderDetailId,ID.ID,I.InvoiceNumber 'NRO FACTURA',
 CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CUPS2.[CUPS] 'CUPS PAQUETE',CUPS2.[DESCRIPCION CUPS] 'DESCRIPCION PAQUETE',UNI.[ESTADO FACTURACION],
 UNI.[FECHA ANULACION]
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  INNER JOIN CTE_PAQUETE_UNICO UNI ON UNI.ID=SOD.ID
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.PackageServiceOrderDetailId
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.PackageServiceOrderDetailId =ID.ServiceOrderDetailId
  LEFT JOIN Billing.ServiceOrderDetail SODP WITH (NOLOCK) ON SODP.Id = sod.PackageServiceOrderDetailId
  LEFT JOIN CTE_CUPS AS CUPS2 WITH (NOLOCK) ON CUPS2.Id=SODP.CUPSEntityId
 WHERE SOD.RecordType=1 AND SOD.Packaging=1  and IM.Agrupador in('Neumologia','Hemodinamia-Cardiologia') AND IM.ReportType ='Causacion' 
 AND CUPS.ServiceType IN (3,4,5,6,7,8) 
),

CTE_DATOS_PROCEDIMIENTOS_INCLUIDO
AS
(
 SELECT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,so.status,SOD.CUPSEntityId,SOD.IPSServiceId,SOD.SettlementType,SOD.IncludeServiceOrderDetailId,ID.ID 'Id_DetFacInc',
 I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CUPS2.[CUPS] 'CUPS INCLUIDO',CUPS2.[DESCRIPCION CUPS] 'DESCRIPCION INCLUIDO',
 UNI.[ESTADO FACTURACION],UNI.[FECHA ANULACION]
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN CTE_INCLUIDO_UNICO AS UNI WITH (NOLOCK) ON UNI.ID=SOD.ID
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.IncludeServiceOrderDetailId
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.IncludeServiceOrderDetailId =ID.ServiceOrderDetailId
  LEFT JOIN Billing.ServiceOrderDetail SODI WITH (NOLOCK) ON SODI.Id = sod.IncludeServiceOrderDetailId
  LEFT JOIN CTE_CUPS AS CUPS2 WITH (NOLOCK) ON CUPS2.Id=SODI.CUPSEntityId
   WHERE SOD.RecordType=1 AND SOD.SettlementType IN (2,3) and IM.Agrupador in('Neumologia','Hemodinamia-Cardiologia') AND IM.ReportType ='Causacion'
   and CUPS.ServiceType IN (3,4,5,6,7,8) 
),
-----*******************************************************************************************************************************************************************-----
-----************************************************************* SEGMENTO ANULADOS ***********************************************************************************-----
-----*******************************************************************************************************************************************************************-----

CTE_PAQUETE_UNICO_ANULADOS
AS
( 
 SELECT DISTINCT I.CUFE,SOD.ID,SO.AdmissionNumber,I.PatientCode AS IDENTIFICACION,I.AdmissionNumber AS INGRESO,
 CASE I.Status WHEN 1 THEN 'FACTURADO' WHEN 2 THEN 'ANULADO' END 'ESTADO FACTURACION',I.InvoiceNumber AS [NRO FACTURA],CAST(I.InvoiceDate AS DATE) AS [FECHA FACTURA],
 CAST(I.AnnulmentDate AS DATE) [FECHA ANULACION],CAST(I.AnnulmentDate AS DATE) AS 'FECHA BUSQUEDA', CAST(I.InitialDate AS DATE) 'FECHA INGRESO/CORTE FACTURA',
 CAST(I.OutputDate AS DATE) 'FECHA EGRESO/CORTE FACTURA', I.TotalInvoice AS [TOTAL FACTURA]
  FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Contract.CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.code
   WHERE I.STATUS=2 AND CAST(I.AnnulmentDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN AND SOD.RecordType=1 AND SOD.Packaging=1 
   and IM.Agrupador in('Neumologia','Hemodinamia-Cardiologia') AND IM.ReportType ='Causacion'  AND CUPS.ServiceType IN (3,4,5,6,7,8)
),

CTE_INCLUIDO_UNICO_ANULADOS
AS
( 
 SELECT DISTINCT I.CUFE,SOD.ID,SO.AdmissionNumber,I.PatientCode AS IDENTIFICACION,I.AdmissionNumber AS INGRESO,
 CASE I.Status WHEN 1 THEN 'FACTURADO' WHEN 2 THEN 'ANULADO' END 'ESTADO FACTURACION',I.InvoiceNumber AS [NRO FACTURA],CAST(I.InvoiceDate AS DATE) AS [FECHA FACTURA],
 CAST(I.AnnulmentDate AS DATE) [FECHA ANULACION],CAST(I.AnnulmentDate AS DATE) AS 'FECHA BUSQUEDA', CAST(I.InitialDate AS DATE) 'FECHA INGRESO/CORTE FACTURA',
 CAST(I.OutputDate AS DATE) 'FECHA EGRESO/CORTE FACTURA', I.TotalInvoice AS [TOTAL FACTURA]
  FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Contract.CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.code
   WHERE I.STATUS=2 AND CAST(I.AnnulmentDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN AND SOD.RecordType=1 AND SOD.SettlementType IN (2,3) 
   and IM.Agrupador in('Neumologia','Hemodinamia-Cardiologia') AND IM.ReportType ='Causacion' and CUPS.ServiceType IN (3,4,5,6,7,8)
),

CTE_DATOS_PROCEDIMIENTOS_ANULADOS
AS
(
 SELECT DISTINCT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,SO.code 'NRO ORDEN',I.PatientCode AS 'IDENTIFICACION',
  I.AdmissionNumber AS 'INGRESO',CAST(SOD.ServiceDate AS DATE) 'FECHA SERVICIO',IPSS.[CODIGO SERVICIO IPS],IPSS.[NOMBRE SERVICIO IPS],
  SOD.CUPSEntityId,CUPS.[CUPS],CUPS.[DESCRIPCION CUPS],CUPS.[CODIGO CONCEPTO],CUPS.[CONCEPTO FACTURACION],CUPS.[TIPO SERVICIO],
  FU.Code 'CODIGO UFS',FU.Name AS 'UNIDAD FUNCIONAL SERVICIO',CC.Code 'CODIGO CC',CC.NAME 'CENTRO DE COSTO',CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],
  isnull(ID.InvoicedQuantity,SOD.InvoicedQuantity) 'CANTIDAD',SOD.RateManualSalePrice,CUPS.[OBTENER CC],TP.Nit AS NIT,TP.Name AS ENTIDAD,
  isnull(CAST(ID.TotalSalesPrice AS NUMERIC(18,2)),cast(SOD.TotalSalesPrice as numeric(18,2))) 'VALOR UNITARIO',USUF.NOMUSUARI 'USUARIO FACTURO',
  isnull(CAST(ID.GrandTotalSalesPrice AS NUMERIC(18,2)),cast(SOD.GrandTotalSalesPrice as numeric(18,2))) 'VALOR TOTAL',
  ISNULL(G.[IDENTIFICACION PROFESIONAL],SOD.PerformsHealthProfessionalCode) 'IDENTIFICACION PROFESIONAL',CD.Name 'DESCRIPCION RELACIONADA',
  ISNULL(G.[PROFESIONAL REALIZO],MED.NOMMEDICO) 'PROFESIONAL',ISNULL(G.[ESPECIALIDA REALIZO],ESPMED.DESESPECI) 'ESPECIALIDAD',
  CASE SOD.Packaging WHEN 1 THEN 'SI' ELSE 'NO' END 'EMPAQUETADO',SOD.PackageServiceOrderDetailId,ISNULL(G.[AGREMIACION],MFC.ContractName) 'AGREMIACION',
  CASE SettlementType WHEN 3 THEN 'SI' ELSE 'NO' END 'INCLUIDO EN SERVICIO',IncludeServiceOrderDetailId,USUA.NOMUSUARI 'USUARIO ANULO',
  CASE TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',sod.RateManualSalePrice [VALOR SERVICIO],IM.[GrupoCausacion] 'AGRUPADOR CAUSACION',
  IM.Type 'TIPO',CUPS.[GRUPO FACTURACION],G.[AUTO],IM.Percentage 'PORCENTAJE CAUSACION',so.status,RTRIM(PAC.IPNOMCOMP) AS PACIENTE,CAST(I.AnnulmentDate AS DATE) [FECHA ANULACION],
  CASE IESTADOIN WHEN ' ' THEN 'ABIERTO' WHEN 'F' THEN 'FACTURADO' WHEN 'A' THEN 'ANULADO' WHEN 'C' THEN 'CERRADO' WHEN 'P' THEN 'PARCIAL' END 'ESTADO INGRESO',
  CASE I.Status WHEN 1 THEN 'FACTURADO' WHEN 2 THEN 'ANULADO' END 'ESTADO FACTURACION',SOD.IsDelete,ID.ID Id_DetFac,I.InvoiceNumber 'NRO FACTURA',
  CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CAST(G.[FECHA LECTURA] AS DATE) 'FECHA LECTURA' ,IM.Agrupador

 FROM 
   Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =SOD.CostCenterId
   INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
   INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON CAST(ING.NUMINGRES  AS CHAR)=CAST(I.AdmissionNumber AS CHAR)
   INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =I.PatientCode
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS]
   INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =I.ThirdPartyId
   INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =I.CareGroupId
   INNER JOIN CTE_IPS AS IPSS WITH (NOLOCK) ON IPSS.Id =SOD.IPSServiceId
   LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
   LEFT JOIN dbo.INESPECIA AS ESPMED WITH (NOLOCK) ON ESPMED.CODESPECI = SOD.PerformsProfessionalSpecialty
   LEFT JOIN DBO.SEGusuaru USUF WITH (NOLOCK) ON USUF.CODUSUARI = I.InvoicedUser
   LEFT JOIN DBO.SEGusuaru USUA WITH (NOLOCK) ON USUA.CODUSUARI = I.AnnulmentUser
   LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =SOD.CUPSEntityContractDescriptionId  AND SOD.CUPSEntityId=DESCR.CUPSEntityId 
   LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
    LEFT JOIN
  (
      SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.MEDREALEC,A.ESPEREALIZA,A.GENSERVICEORDER,A.AUTO, A.MEDREALEC 'IDENTIFICACION PROFESIONAL',
       PRO.NOMMEDICO 'PROFESIONAL REALIZO',ESP.DESESPECI 'ESPECIALIDA REALIZO',MFC.ContractName 'AGREMIACION',CAST(A.FECHLECT AS DATE) 'FECHA LECTURA'
       FROM dbo.HCORDIMAG A WITH (NOLOCK)
       INNER JOIN
       (
        SELECT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER,MAX(A.AUTO) AUTO
         FROM dbo.ADINGRESO ing WITH (NOLOCK)
	        INNER JOIN dbo.HCORDIMAG A with (nolock) ON ing.NUMINGRES = A.NUMINGRES
			where A.MEDREALEC IS NOT NULL AND A.GENSERVICEORDER IS NOT NULL 
	        GROUP BY A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER
       ) AS G ON G.AUTO=A.AUTO AND G.NUMINGRES=A.NUMINGRES AND G.CODSERIPS=A.CODSERIPS
       LEFT JOIN dbo.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL=A.MEDREALEC
       LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI =PRO.CODESPEC1
       LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =PRO.CODPROSAL AND HPC.LiquidateDefault = 1
       LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
    UNION ALL
        SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.MEDREALEC,A.ESPEREALIZA,A.GENSERVICEORDER,A.AUTO, A.MEDREALEC 'IDENTIFICACION PROFESIONAL',
         ISNULL(PRO.NOMMEDICO,PROE.NOMMEDICO) 'PROFESIONAL REALIZO',ISNULL(ESP.DESESPECI,ESPE.DESESPECI) 'ESPECIALIDA REALIZO',MFC.ContractName 'AGREMIACION',
		 CAST(A.FECHLECT AS DATE) 'FECHA LECTURA'
        FROM dbo.AMBORDIMA A WITH (NOLOCK)
        INNER JOIN
        (
         SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER,MAX(A.AUTO) AUTO
         FROM dbo.ADINGRESO ing WITH (NOLOCK)
	      INNER JOIN dbo.AMBORDIMA A WITH (NOLOCK) ON ing.NUMINGRES = A.NUMINGRES
		  where A.MEDREALEC IS NOT NULL AND A.GENSERVICEORDER IS NOT NULL
	      GROUP BY A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER
        ) AS G ON G.AUTO=A.AUTO AND G.NUMINGRES=A.NUMINGRES AND G.CODSERIPS=A.CODSERIPS
        LEFT JOIN dbo.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL=A.MEDREALEC
        LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI =PRO.CODESPEC1
        LEFT JOIN dbo.INPROFSAL AS PROE WITH (NOLOCK) ON PROE.CODPROSAL=A.USURECEXA
        LEFT JOIN dbo.INESPECIA AS ESPE WITH (NOLOCK) ON ESPE.CODESPECI =PROE.CODESPEC1
        LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =ISNULL(PRO.CODPROSAL,PROE.CODPROSAL) AND HPC.LiquidateDefault = 1
        LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
  ) AS G ON G.NUMINGRES=CAST(I.AdmissionNumber AS CHAR) AND G.GENSERVICEORDER=SO.ID AND G.CODSERIPS=CUPS.[CUPS]
  LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =ISNULL(G.[IDENTIFICACION PROFESIONAL],SOD.PerformsHealthProfessionalCode)
  AND HPC.LiquidateDefault = 1
  LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
   WHERE I.STATUS=2 AND SOD.RecordType=1 AND IM.Agrupador in('Neumologia','Hemodinamia-Cardiologia') AND IM.ReportType ='Causacion' AND CUPS.ServiceType  in (3,4,5,6,7,8) 
   AND CAST(I.AnnulmentDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
),

CTE_DATOS_PROCEDIMIENTOS_EMPAQUETADO_ANULADOS
AS
(
 SELECT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,so.status,SOD.CUPSEntityId,SOD.IPSServiceId,sod.PackageServiceOrderDetailId,ID.ID,I.InvoiceNumber 'NRO FACTURA',
 CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CUPS2.[CUPS] 'CUPS PAQUETE',CUPS2.[DESCRIPCION CUPS] 'DESCRIPCION PAQUETE',UNI.[ESTADO FACTURACION],UNI.[FECHA ANULACION]
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  INNER JOIN CTE_PAQUETE_UNICO_ANULADOS UNI ON UNI.ID=SOD.ID
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.PackageServiceOrderDetailId
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.PackageServiceOrderDetailId =ID.ServiceOrderDetailId
  LEFT JOIN Billing.ServiceOrderDetail SODP WITH (NOLOCK) ON SODP.Id = sod.PackageServiceOrderDetailId
  LEFT JOIN CTE_CUPS AS CUPS2 WITH (NOLOCK) ON CUPS2.Id=SODP.CUPSEntityId
 WHERE SOD.RecordType=1 AND SOD.Packaging=1  and IM.Agrupador in('Neumologia','Hemodinamia-Cardiologia') AND IM.ReportType ='Causacion' AND CUPS.ServiceType IN (3,4,5,6,7,8) 
),

CTE_DATOS_PROCEDIMIENTOS_INCLUIDO_ANULADOS
AS
(
 SELECT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,so.status,SOD.CUPSEntityId,SOD.IPSServiceId,SOD.SettlementType,SOD.IncludeServiceOrderDetailId,ID.ID 'Id_DetFacInc',
 I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CUPS2.[CUPS] 'CUPS INCLUIDO',CUPS2.[DESCRIPCION CUPS] 'DESCRIPCION INCLUIDO',
 UNI.[ESTADO FACTURACION],UNI.[FECHA ANULACION]
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN CTE_INCLUIDO_UNICO_ANULADOS AS UNI WITH (NOLOCK) ON UNI.ID=SOD.ID
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.IncludeServiceOrderDetailId
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.IncludeServiceOrderDetailId =ID.ServiceOrderDetailId
  LEFT JOIN Billing.ServiceOrderDetail SODI WITH (NOLOCK) ON SODI.Id = sod.IncludeServiceOrderDetailId
  LEFT JOIN CTE_CUPS AS CUPS2 WITH (NOLOCK) ON CUPS2.Id=SODI.CUPSEntityId
   WHERE SOD.RecordType=1 AND SOD.SettlementType IN (2,3) and IM.Agrupador in('Neumologia','Hemodinamia-Cardiologia')AND IM.ReportType ='Causacion' and CUPS.ServiceType IN (3,4,5,6,7,8) 
)

SELECT 'VIE' 'FUENTE',IMG.[TIPO SERVICIO],IMG.IDENTIFICACION,IMG.[PACIENTE],IMG.[FECHA SERVICIO],
CONVERT(VARCHAR(7),IMG.[FECHA SERVICIO],120) AS 'AÑO_MES_SERVICIO',IMG.[CUPS],IMG.[DESCRIPCION CUPS],IMG.[CODIGO SERVICIO IPS],IMG.[NOMBRE SERVICIO IPS],
IMG.[DESCRIPCION RELACIONADA],IMG.[CANTIDAD],IMG.[VALOR SERVICIO],IMG.[VALOR UNITARIO],IMG.[VALOR TOTAL] 'VALOR FACTURADO',IMG.[GRUPO FACTURACION],IMG.[CODIGO UFS],
IMG.[UNIDAD FUNCIONAL SERVICIO],IMG.[CODIGO CC],IMG.[CENTRO DE COSTO],ISNULL(IMG.[NRO FACTURA],ISNULL(PAQ.[NRO FACTURA],INC.[NRO FACTURA])) [NRO FACTURA],
ISNULL(IMG.[FECHA FACTURA],ISNULL(PAQ.[FECHA FACTURA],INC.[FECHA FACTURA])) 'FECHA FACTURA',IMG.[PORCENTAJE CAUSACION], IMG.[TIPO] 'AGRUPADOR CAUSACION',
CAST(IIF(IMG.[VALOR TOTAL]=0,IMG.[VALOR SERVICIO],IMG.[VALOR TOTAL])*(IMG.[PORCENTAJE CAUSACION]/100) AS NUMERIC(18,2)) 'VALOR CAUSADO',
IIF(IMG.[Id_DetFac] IS NOT NULL,IMG.[ESTADO FACTURACION],IIF(PAQ.ID IS NOT NULL,PAQ.[ESTADO FACTURACION],IIF(INC.[Id_DetFacInc] IS NOT NULL,INC.[ESTADO FACTURACION],'SIN FACTURAR'))) [ESTADO REGISTRO],
CONVERT(VARCHAR(7),ISNULL(IMG.[FECHA FACTURA],ISNULL(PAQ.[FECHA FACTURA],INC.[FECHA FACTURA])), 120) AS 'AÑO_MES_FACTURA',IMG.INGRESO,IMG.[IDENTIFICACION PROFESIONAL],
IMG.[PROFESIONAL],IMG.[ESPECIALIDAD],IMG.[AGREMIACION],IMG.[EMPAQUETADO],PAQ.[CUPS PAQUETE],PAQ.[DESCRIPCION PAQUETE],IMG.[INCLUIDO EN SERVICIO],INC.[CUPS INCLUIDO],
INC.[DESCRIPCION INCLUIDO],IMG.[CODIGO CONCEPTO],IMG.[CONCEPTO FACTURACION],IMG.[OBTENER CC],IMG.[NRO ORDEN],IMG.[AUTO],IMG.[AMBITO], IMG.[NIT],IMG.[ENTIDAD],
IMG.[GRUPO ATENCION],IMG.[USUARIO FACTURO],IMG.[USUARIO ANULO],ISNULL(IMG.[FECHA ANULACION],ISNULL(PAQ.[FECHA ANULACION],INC.[FECHA ANULACION])) 'FECHA ANULACION',
IMG.[FECHA LECTURA],IMG.[AGRUPADOR CAUSACION],IMG.[AGRUPADOR] 
FROM CTE_DATOS_PROCEDIMIENTOS IMG
LEFT JOIN CTE_DATOS_PROCEDIMIENTOS_EMPAQUETADO PAQ ON IMG.ServiceOrderDetailId=PAQ.ServiceOrderDetailId
LEFT JOIN CTE_DATOS_PROCEDIMIENTOS_INCLUIDO INC ON IMG.ServiceOrderDetailId=INC.ServiceOrderDetailId
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
UNION ALL
----------------------------------***************************** SEGMENTO ANULADOS *********************************----------------------------------------------------------
SELECT 'VIE' 'FUENTE',IMG.[TIPO SERVICIO],IMG.IDENTIFICACION,IMG.[PACIENTE],IMG.[FECHA SERVICIO],
CONVERT(VARCHAR(7),IMG.[FECHA SERVICIO],120) AS 'AÑO_MES_SERVICIO',IMG.[CUPS],IMG.[DESCRIPCION CUPS],IMG.[CODIGO SERVICIO IPS],IMG.[NOMBRE SERVICIO IPS],
IMG.[DESCRIPCION RELACIONADA],-1*IMG.[CANTIDAD] [CANTIDAD],-1*IMG.[VALOR SERVICIO] [VALOR SERVICIO],-1*IMG.[VALOR UNITARIO] [VALOR UNITARIO],
-1*IMG.[VALOR TOTAL] 'VALOR FACTURADO',IMG.[GRUPO FACTURACION],IMG.[CODIGO UFS],IMG.[UNIDAD FUNCIONAL SERVICIO],IMG.[CODIGO CC],IMG.[CENTRO DE COSTO],
ISNULL(IMG.[NRO FACTURA],ISNULL(PAQ.[NRO FACTURA],INC.[NRO FACTURA])) [NRO FACTURA],ISNULL(IMG.[FECHA FACTURA],ISNULL(PAQ.[FECHA FACTURA],INC.[FECHA FACTURA])) 'FECHA FACTURA',
IMG.[PORCENTAJE CAUSACION], IMG.[TIPO] 'AGRUPADOR CAUSACION',-1*CAST(IIF(IMG.[VALOR TOTAL]=0,IMG.[VALOR SERVICIO],IMG.[VALOR TOTAL])*(IMG.[PORCENTAJE CAUSACION]/100) AS NUMERIC(18,2)) 'VALOR CAUSADO',
IIF(IMG.[Id_DetFac] IS NOT NULL,IMG.[ESTADO FACTURACION],IIF(PAQ.ID IS NOT NULL,PAQ.[ESTADO FACTURACION],IIF(INC.[Id_DetFacInc] IS NOT NULL,INC.[ESTADO FACTURACION],'SIN FACTURAR'))) [ESTADO REGISTRO],
CONVERT(VARCHAR(7),ISNULL(IMG.[FECHA ANULACION],ISNULL(PAQ.[FECHA ANULACION],INC.[FECHA ANULACION])), 120) AS 'AÑO_MES_FACTURA',IMG.INGRESO,IMG.[IDENTIFICACION PROFESIONAL],
IMG.[PROFESIONAL],IMG.[ESPECIALIDAD],IMG.[AGREMIACION],IMG.[EMPAQUETADO],PAQ.[CUPS PAQUETE],PAQ.[DESCRIPCION PAQUETE],IMG.[INCLUIDO EN SERVICIO],INC.[CUPS INCLUIDO],
INC.[DESCRIPCION INCLUIDO],IMG.[CODIGO CONCEPTO],IMG.[CONCEPTO FACTURACION],IMG.[OBTENER CC],IMG.[NRO ORDEN],IMG.[AUTO],IMG.[AMBITO], IMG.[NIT],IMG.[ENTIDAD],
IMG.[GRUPO ATENCION],IMG.[USUARIO FACTURO],IMG.[USUARIO ANULO],ISNULL(IMG.[FECHA ANULACION],ISNULL(PAQ.[FECHA ANULACION],INC.[FECHA ANULACION])) 'FECHA ANULACION',
IMG.[FECHA LECTURA],IMG.[AGRUPADOR CAUSACION],IMG.[AGRUPADOR] 
FROM CTE_DATOS_PROCEDIMIENTOS_ANULADOS IMG
LEFT JOIN CTE_DATOS_PROCEDIMIENTOS_EMPAQUETADO_ANULADOS PAQ ON IMG.ServiceOrderDetailId=PAQ.ServiceOrderDetailId
LEFT JOIN CTE_DATOS_PROCEDIMIENTOS_INCLUIDO_ANULADOS INC ON IMG.ServiceOrderDetailId=INC.ServiceOrderDetailId
