-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_ERP_CAUSACION_PRODUCTIVIDAD_RESONANCIA_V2
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE PROCEDURE [Report].[IND_SP_V2_ERP_CAUSACION_PRODUCTIVIDAD_RESONANCIA_V2]

@FECHAINI AS DATE,
@FECHAFIN AS DATE

--DECLARE @FECHAINI AS DATE='2024-07-01';
--DECLARE @FECHAFIN AS DATE='2024-07-31';

AS

WITH CTE_CUPS
AS
(
   SELECT CUPS.Id,CUPS.Code [CUPS], CUPS.Description [DESCRIPCION CUPS], 
   CASE CUPS.ServiceType WHEN 1 then 'LABORATORIOS' WHEN 2 then 'PATOLOGIAS' WHEN 3 then 'IMAGENES DIAGNOSTICAS' WHEN 4 then 'PROCEDIMIENTOS NO QX'
   WHEN 5 then 'PROCEDIMIENTOS QX' WHEN 6 then 'INTERCONSULTAS'WHEN 7 then 'NINGUNO'WHEN 8 then 'CONSULTA EXTERNA' WHEN 9 THEN 'HEMOCOMPONENTES' ELSE 'OTROS' END AS 'TIPO SERVICIO',
   BG.CODE 'CODIGO FACTURACION',BG.NAME 'GRUPO FACTURACION',BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION',CGC.Code 'CODIGO GRUPO',CGC.Name 'GRUPO CUPS',
   CSG.CODE 'CODIGO SUBGRUPO',CSG.Name  'SUBGRUPO CUPS',
   CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
   ELSE 'N/A' END 'OBTENER CC',CUPS.ServiceType
   FROM Contract.CUPSEntity AS CUPS WITH (NOLOCK)
   INNER JOIN Billing.BillingGroup as BG WITH (NOLOCK) ON BG.Id=CUPS.BillingGroupId
   INNER JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=CUPS.BillingConceptId
   INNER JOIN Contract.CupsSubgroup AS CSG WITH (NOLOCK) ON CSG.Id =CUPS.CUPSSubGroupId
   INNER JOIN Contract.CupsGroup AS CGC WITH (NOLOCK) ON CGC.Id =CSG.CupsGroupId
  -- where CUPS.ServiceType=3 and BG.NAME='RESONANCIA NUCLEAR MAGNETICA'
 ),

CTE_DATOS_IMAGENES_INGRESO
AS
(
 SELECT DISTINCT TER.NUMINGRES 
  FROM dbo.HCORDIMAG TER WITH (NOLOCK)
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
  INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
  WHERE IM.Agrupador IN('Resonancia') and IM.ReportType in ('Causacion') AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
  AND TER.MANEXTPRO=0
),

CTE_DATOS_FACTURACION
AS
(
 SELECT distinct I.InvoiceNumber,I.AdmissionNumber,CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',SOD.ServiceOrderId, CUPS.[CUPS], CUPS.[DESCRIPCION CUPS]
   FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN CTE_DATOS_IMAGENES_INGRESO AS ING ON CAST(ING.NUMINGRES  AS CHAR)=CAST(I.AdmissionNumber AS CHAR)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[ID]=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
  WHERE I.Status=1 AND SOD.IsDelete=0 AND IM.Agrupador IN('Resonancia') and IM.ReportType in ('Causacion')
),

CTE_IPS
AS
(
 SELECT IPS.ID,IPS.Code 'CODIGO SERVICIO IPS',IPS.Name 'NOMBRE SERVICIO IPS', CASE IPS.ServiceClass WHEN 1 THEN 'Ninguno' WHEN 2 THEN 'Cirujano' WHEN 3 THEN 'Anestesiologo' WHEN 4 THEN 'Ayudante' 
 WHEN 5 THEN 'Derecho Sala' WHEN 6 THEN 'Materiales Sutura'    WHEN 7 THEN 'Instrumentacion Quirurgica' ELSE 'Ninguno' end 'TIPO SERVICIO IPS',
 BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION IPS QX',
 CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
 ELSE 'N/A' END 'OBTENER CC'
 FROM Contract.IPSService IPS WITH (NOLOCK)
 LEFT JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=IPS.BillingConceptId
),

CTE_DATOS_INDIRA
AS
(
 SELECT IND.NumeroAccesoINDIRA,IND.TipoOrden,IND.NumeroOrdenVIE,IND.IdentificacionPaciente,IND.NombreCompletoPaciente,IND.IngresoVIE,
 IND.[Fecha de toma estudio],IND.FechaLecturaConfirmada,IND.IdentificacionUsuarioValida,IND.UsuarioValidaLectura,IND.FechaOrdenMedica,IND.FechaInicialCita,
 IND.CodigoServico,IND.DescripcionServicio,IND.Modalidad,IND.NombreModalidad,IND.Cantidad,IND.EstadoLectura 'ESTADO LECTURA INDIRA',IND.EstadoOrden 'ESTADO ORDEN INDIRA'
 FROM Report.TableIndira IND
 LEFT JOIN
 (
    SELECT NumeroOrdenVIE,IngresoVIE,CodigoServico,MAX(FechaLecturaConfirmada) FechaLectura
    FROM Report.TableIndira  --WHERE NumeroOrdenVIE=176070
    GROUP BY NumeroOrdenVIE,IngresoVIE,CodigoServico
 ) AS G ON G.NumeroOrdenVIE=IND.NumeroOrdenVIE AND G.IngresoVIE=IND.IngresoVIE AND G.CodigoServico=IND.CodigoServico AND G.FechaLectura=IND.FechaLecturaConfirmada
),

--SELECT * FROM CTE_DATOS_INDIRA

CTE_DATOS_ORDENES_IMAGENES_HOSPITALARIA
AS
(
 SELECT DISTINCT '1. HISTORIA CLINICA' 'FUENTE','HOSPITALARIO' 'AMBITO',--CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CC'WHEN '2'  THEN 'CE'WHEN '3'  THEN 'TI'WHEN '4'  THEN 'RC'WHEN '5'  THEN 'PA'WHEN '6'  THEN 'AS'WHEN '7'  THEN 'MS'
 WHEN '8'  THEN 'NU'WHEN '9'  THEN 'NV'WHEN '10' THEN 'CD'WHEN '11' THEN 'SC'WHEN '12' THEN 'PE' WHEN '13' THEN 'PT'WHEN '14' THEN 'DE'WHEN '15' THEN 'SI'END AS [TIPO IDENTIFICACION],
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CEDULA DE CIUDADANIA' WHEN '2'  THEN 'CEDULA DE EXTRANJERIA' WHEN '3'  THEN 'TARJETA DE IDENTIDAD' WHEN '4'  THEN 'REGISTRO CIVIL' 
 WHEN '5'  THEN 'PASAPORTE' WHEN '6'  THEN 'ADULTO SIN IDENTIFICACION' WHEN '7'  THEN 'MENOR SIN IDENTIFICACION' WHEN '8'  THEN 'NUMERO UNICO DE IDENTIFICACION'
 WHEN '9'  THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO' WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
 WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION'END AS [DESCRIPCION IDENTIFICACION],
 TER.IPCODPACI 'IDENTIFICACION',CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
 CONCAT(FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365), ' años, ',FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12),' meses,',FLOOR(((((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12) - FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12)) * (365 / 12))), ' días') AS [EDAD],
 CASE PAC.IPSEXOPAC WHEN '1' THEN 'H' WHEN '2' THEN 'M' END AS [CODIGO SEXO],CASE PAC.IPSEXOPAC WHEN '1' THEN 'HOMBRE' WHEN '2' THEN 'MUJER' END AS [SEXO],
 UPPER(PAC.IPPRIAPEL) 'PRIMER APELLIDO',UPPER(PAC.IPSEGAPEL) 'SEGUNDO APELLIDO',UPPER(PAC.IPPRINOMB) 'PRIMER NOMBRE',UPPER(PAC.IPSEGNOMB) 'SEGUNDO NOMBRE',
 PAC.IPNOMCOMP 'NOMBRE COMPLETO PACIENTE',TP.Nit AS NIT,TP.Name AS ENTIDAD,HA.HealthEntityCode 'CODIGO EAPB',CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],
 CASE HA.EntityType WHEN 1 THEN 'EPS Contributivo' WHEN 2 THEN 'EPS Subsidiado' WHEN 3 THEN 'ET Vinculados Municipios' WHEN 4 THEN 'ET Vinculados Departamentos'
 WHEN 5 THEN 'ARL Riesgos Laborales' WHEN 6 THEN 'MP Medicina Prepagada' WHEN 7 THEN 'IPS Privada' WHEN 8 THEN 'IPS Publica' WHEN 9 THEN 'Regimen Especial'
 WHEN 10 THEN 'Accidentes de transito' WHEN 11 THEN 'Fosyga' WHEN 12 THEN 'Otros' ELSE 'Otros' end [REGIMEN],
 TER.NUMINGRES 'INGRESO', TER.NUMEFOLIO 'FOLIO',CAST(TER.FECORDMED AS DATE) 'FECHA ORDEN',TER.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS],
 ISNULL(CD.Name,CUPS.[DESCRIPCION CUPS]) 'DESCRIPCION RELACIONADA',TER.CANSERIPS 'CANTIDAD', CASE MANEXTPRO WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'EXTRAMURAL', 
 CASE ESTSERIPS WHEN 1 THEN 'SOLICITADO' WHEN 2 THEN 'ESTUDIO REALIZADO' WHEN 3 THEN 'ESTUDIO REALIZADO' WHEN 4 THEN 'ESTUDIO REALIZADO' WHEN 5 THEN 'REMITIDO'
 WHEN 6 THEN 'ANULADO' WHEN 7 THEN 'EXTRAMURAL' ELSE 'OTROS' END 'ESTADO',
 UNI.UFUDESCRI 'UNIDAD FUNCIONAL',TER.CODPROSAL 'ID PROFESIONAL ORDEN',MED.NOMMEDICO 'PROFESIONAL ORDEN',ESP.DESESPECI 'ESPECIALIDAD ORDEN' ,
 MLEC.CODPROSAL 'ID PROFESIONAL LECTURA',MLEC.NOMMEDICO 'PROFESIONAL LECTURA',ESPL.DESESPECI 'ESPECIALIDAD LECTURA',
 CAST(ISNULL(TER.FECORDMED,IND.FechaInicialCita) AS DATE) 'FECHA CITA',CAST(ISNULL(IND.[Fecha de toma estudio],TER.FECRECEXA) AS DATE) 'FECHA DE TOMA',
 CAST(ISNULL(IND.FechaLecturaConfirmada,TER.FECHLECT) AS DATE) 'FECHA LECTURA',
 DATEDIFF(DAY, CAST(ISNULL(TER.FECORDMED, IND.FechaInicialCita) AS DATE), 
        CAST(ISNULL(IND.[Fecha de toma estudio], TER.FECRECEXA) AS DATE)) AS  'TEMPO DE ESPERA FEC CITA VS FEC TOMA',
 TER.CODDIAGNO 'CIE10 ORDEN',DIA.NOMDIAGNO 'DIAGNOSTICO ORDEN',TER.AUTO,SO.Code 'NRO ORDEN FACTURACION',
 IIF(TER.GENSERVICEORDER IS NOT NULL AND FAC.InvoiceNumber IS NOT NULL,'FACTURADO',IIF(TER.GENSERVICEORDER IS NOT NULL AND FAC.InvoiceNumber IS NULL,'PENDIENTE FACTURAR',
 IIF(TER.GENSERVICEORDER IS NULL AND FAC.InvoiceNumber IS NULL,'SIN CARGUE','N/A'))) 'ESTADO FACTURACION', ISNULL(FAC.InvoiceNumber,'N/A') 'NRO FACTURA',FAC.[FECHA FACTURA],
 '' 'IDCITA',IM.Agrupador 'AGRUPADOR', 0 'VALOR UNITARIO',0 'VALOR TOTAL',IND.NumeroAccesoINDIRA 'NRO INDIRA',IND.[ESTADO LECTURA INDIRA], IND.[ESTADO ORDEN INDIRA] ,
 CAST(TER.FECORDMED AS DATE) 'FECHA BUSQUEDA'
 FROM dbo.HCORDIMAG TER WITH (NOLOCK)
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = TER.UFUCODIGO
 INNER JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = TER.CODPROSAL
 INNER JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
 INNER JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=TER.CODDIAGNO
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=TER.NUMINGRES AND IND.NumeroOrdenVIE=TER.AUTO
 LEFT JOIN dbo.INPROFSAL AS MLEC WITH (NOLOCK) ON MLEC.CODPROSAL=ISNULL(TER.MEDREALEC,IND.IdentificacionUsuarioValida)
 LEFT JOIN dbo.INESPECIA AS ESPL WITH (NOLOCK) ON ESPL.CODESPECI =MLEC.CODESPEC1
 LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =MLEC.CODPROSAL AND HPC.LiquidateDefault = 1
 LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
 LEFT JOIN CTE_DATOS_FACTURACION FAC WITH (NOLOCK) ON cast(FAC.AdmissionNumber AS CHAR)=CAST(TER.NUMINGRES AS CHAR) AND FAC.ServiceOrderId=TER.GENSERVICEORDER AND FAC.[CUPS]=TER.CODSERIPS
 LEFT JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =TER.GENSERVICEORDER
 WHERE IM.Agrupador IN('Resonancia') and IM.ReportType in ('Causacion') AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
 AND TER.MANEXTPRO=0 --AND TER.ESTSERIPS<>5
),

CTE_DATOS_ORDENES_IMAGENES_AMBULATORIA
AS
(
 SELECT DISTINCT '1. HISTORIA CLINICA' 'FUENTE','AMBULATORIO' 'AMBITO',--CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CC'WHEN '2'  THEN 'CE'WHEN '3'  THEN 'TI'WHEN '4'  THEN 'RC'WHEN '5'  THEN 'PA'WHEN '6'  THEN 'AS'WHEN '7'  THEN 'MS'
 WHEN '8'  THEN 'NU'WHEN '9'  THEN 'NV'WHEN '10' THEN 'CD'WHEN '11' THEN 'SC'WHEN '12' THEN 'PE' WHEN '13' THEN 'PT'WHEN '14' THEN 'DE'WHEN '15' THEN 'SI'END AS [TIPO IDENTIFICACION],
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CEDULA DE CIUDADANIA' WHEN '2'  THEN 'CEDULA DE EXTRANJERIA' WHEN '3'  THEN 'TARJETA DE IDENTIDAD' WHEN '4'  THEN 'REGISTRO CIVIL' 
 WHEN '5'  THEN 'PASAPORTE' WHEN '6'  THEN 'ADULTO SIN IDENTIFICACION' WHEN '7'  THEN 'MENOR SIN IDENTIFICACION' WHEN '8'  THEN 'NUMERO UNICO DE IDENTIFICACION'
 WHEN '9'  THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO' WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
 WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION'END AS [DESCRIPCION IDENTIFICACION],
 TER.IPCODPACI 'IDENTIFICACION',CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
 CONCAT(FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365), ' años, ',FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12),' meses,',FLOOR(((((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12) - FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,TER.FECORDMED) AS FLOAT) / 365)) * 12)) * (365 / 12))), ' días') AS [EDAD],
 CASE PAC.IPSEXOPAC WHEN '1' THEN 'H' WHEN '2' THEN 'M' END AS [CODIGO SEXO],CASE PAC.IPSEXOPAC WHEN '1' THEN 'HOMBRE' WHEN '2' THEN 'MUJER' END AS [SEXO],
 UPPER(PAC.IPPRIAPEL) 'PRIMER APELLIDO',UPPER(PAC.IPSEGAPEL) 'SEGUNDO APELLIDO',UPPER(PAC.IPPRINOMB) 'PRIMER NOMBRE',UPPER(PAC.IPSEGNOMB) 'SEGUNDO NOMBRE',
 PAC.IPNOMCOMP 'NOMBRE COMPLETO PACIENTE',TP.Nit AS NIT,TP.Name AS ENTIDAD,HA.HealthEntityCode 'CODIGO EAPB',CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],
 CASE HA.EntityType WHEN 1 THEN 'EPS Contributivo' WHEN 2 THEN 'EPS Subsidiado' WHEN 3 THEN 'ET Vinculados Municipios' WHEN 4 THEN 'ET Vinculados Departamentos'
 WHEN 5 THEN 'ARL Riesgos Laborales' WHEN 6 THEN 'MP Medicina Prepagada' WHEN 7 THEN 'IPS Privada' WHEN 8 THEN 'IPS Publica' WHEN 9 THEN 'Regimen Especial'
 WHEN 10 THEN 'Accidentes de transito' WHEN 11 THEN 'Fosyga' WHEN 12 THEN 'Otros' ELSE 'Otros' end [REGIMEN],
 TER.NUMINGRES 'INGRESO', 'N/A' 'FOLIO',CAST(TER.FECORDMED AS DATE) 'FECHA ORDEN',TER.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS],
 ISNULL(CD.Name,CUPS.[DESCRIPCION CUPS]) 'DESCRIPCION RELACIONADA',TER.CANSERIPS 'CANTIDAD', 'SI' 'EXTRAMURAL', 
 CASE ESTSERIPS WHEN 1 THEN 'SOLICITADO' WHEN 2 THEN 'ESTUDIO REALIZADO' WHEN 3 THEN 'ESTUDIO REALIZADO' WHEN 4 THEN 'ESTUDIO REALIZADO' WHEN 5 THEN 'REMITIDO'
 WHEN 6 THEN 'ANULADO' WHEN 7 THEN 'EXTRAMURAL' ELSE 'OTROS' END 'ESTADO',
 UNI.UFUDESCRI 'UNIDAD FUNCIONAL',TER.CODPROSAL 'ID PROFESIONAL ORDEN',MED.NOMMEDICO 'PROFESIONAL ORDEN',ESP.DESESPECI 'ESPECIALIDAD ORDEN' ,
 MLEC.CODPROSAL 'ID PROFESIONAL LECTURA',MLEC.NOMMEDICO 'PROFESIONAL LECTURA',ESPL.DESESPECI 'ESPECIALIDAD LECTURA',
 CAST(ISNULL(CIT.FECREGSIS,ISNULL(IND.FechaInicialCita,TER.FECORDMED)) AS DATE) 'FECHA CITA',CAST(ISNULL(IND.[Fecha de toma estudio],TER.FECRECEXA) AS DATE) 'FECHA DE TOMA',
 CAST(ISNULL(IND.FechaLecturaConfirmada,TER.FECHLECT) AS DATE) 'FECHA LECTURA',
 DATEDIFF(DAY,CAST(ISNULL(CIT.FECREGSIS,ISNULL(IND.FechaInicialCita,TER.FECORDMED)) AS DATE), 
        CAST(ISNULL(IND.[Fecha de toma estudio], TER.FECRECEXA) AS DATE)) AS  'TEMPO DE ESPERA FEC CITA VS FEC TOMA',
  DIA.CODDIAGNO 'CIE10 ORDEN',DIA.NOMDIAGNO 'DIAGNOSTICO ORDEN',TER.AUTO,SO.Code 'NRO ORDEN FACTURACION',
 IIF(TER.GENSERVICEORDER IS NOT NULL AND TER.GENINVOICEID IS NOT NULL,'FACTURADO',IIF(TER.GENSERVICEORDER IS NOT NULL AND TER.GENINVOICEID IS NULL,'PENDIENTE FACTURAR',
 IIF(TER.GENSERVICEORDER IS NULL AND TER.GENINVOICEID IS NULL,'SIN CARGUE','N/A'))) 'ESTADO FACTURACION', ISNULL(TER.GENINVOICE,'N/A') 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) [FECHA FACTURA],
 TER.NUMCONCIT 'IDCITA',IM.Agrupador 'AGRUPADOR', 0 'VALOR UNITARIO',0 'VALOR TOTAL',IND.NumeroAccesoINDIRA 'NRO INDIRA',IND.[ESTADO LECTURA INDIRA], IND.[ESTADO ORDEN INDIRA],
 CAST(TER.FECORDMED AS DATE) 'FECHA BUSQUEDA'
 
 FROM dbo.AMBORDIMA TER WITH (NOLOCK)
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = TER.UFUCODIGO
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = TER.CODPROSAL
 LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=TER.NUMINGRES AND IND.NumeroOrdenVIE=TER.AUTO
 LEFT JOIN dbo.INPROFSAL AS MLEC WITH (NOLOCK) ON MLEC.CODPROSAL=ISNULL(TER.MEDREALEC,IND.IdentificacionUsuarioValida)
 LEFT JOIN dbo.INESPECIA AS ESPL WITH (NOLOCK) ON ESPL.CODESPECI =MLEC.CODESPEC1
 LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =MLEC.CODPROSAL AND HPC.LiquidateDefault = 1
 LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
 LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.Id=TER.GENINVOICEID
 LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=I.OutputDiagnosis
 LEFT JOIN dbo.AGASICITA CIT WITH (NOLOCK) ON CIT.CODAUTONU=TER.NUMCONCIT
 LEFT JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =TER.GENSERVICEORDER
 WHERE IM.Agrupador IN('Resonancia') and IM.ReportType in ('Causacion') AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
 --AND TER.MANEXTPRO=0 --AND TER.ESTSERIPS<>5
),

CTE_PAQUETE_UNICO
AS
(  --CA.CODIPSSEC 'CODIGO HABILITACION'
 SELECT DISTINCT I.CUFE,SOD.ID,SO.AdmissionNumber,I.PatientCode AS IDENTIFICACION,I.AdmissionNumber AS INGRESO,
 CASE I.Status WHEN 1 THEN 'FACTURADO' WHEN 2 THEN 'ANULADO' END 'ESTADO FACTURACION',I.InvoiceNumber AS [NRO FACTURA],CAST(I.AnnulmentDate AS DATE) [FECHA ANULACION],
 CAST(I.InvoiceDate AS DATE) AS 'FECHA BUSQUEDA', CAST(I.InitialDate AS DATE) 'FECHA INGRESO/CORTE FACTURA',CAST(I.OutputDate AS DATE) 'FECHA EGRESO/CORTE FACTURA',
 I.TotalInvoice AS [TOTAL FACTURA]
  FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Contract.CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.code
   WHERE IM.Agrupador IN('Resonancia') and IM.ReportType in ('Causacion') AND I.STATUS=1 AND CAST(I.InvoiceDate AS DATE) BETWEEN @FECHAINI AND @FECHAFIN 
   AND SOD.RecordType=1 AND SOD.Packaging=1 --AND CUPS.ServiceType IN (3,4,5,6,7,8) 
),

CTE_INCLUIDO_UNICO
AS
(  --CA.CODIPSSEC 'CODIGO HABILITACION'
 SELECT DISTINCT I.CUFE,SOD.ID,SO.AdmissionNumber,I.PatientCode AS IDENTIFICACION,I.AdmissionNumber AS INGRESO,
 CASE I.Status WHEN 1 THEN 'FACTURADO' WHEN 2 THEN 'ANULADO' END 'ESTADO FACTURACION',I.InvoiceNumber AS [NRO FACTURA],CAST(I.InvoiceDate AS DATE) AS [FECHA FACTURA],
 CAST(I.AnnulmentDate AS DATE) [FECHA ANULACION],CAST(I.InvoiceDate AS DATE) AS 'FECHA BUSQUEDA', CAST(I.InitialDate AS DATE) 'FECHA INGRESO/CORTE FACTURA',
 CAST(I.OutputDate AS DATE) 'FECHA EGRESO/CORTE FACTURA',I.TotalInvoice AS [TOTAL FACTURA]
  FROM Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Contract.CUPSEntity AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.code
   WHERE I.STATUS=1 AND CAST(I.InvoiceDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN AND SOD.RecordType=1 AND SOD.SettlementType IN (2,3) 
   and IM.Agrupador='Resonancia'AND IM.ReportType='Causacion' --and CUPS.ServiceType IN (3,4,5,6,7,8)
),

CTE_DATOS_IMAGENES_EMPAQUETADO
AS
(
 SELECT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,so.status,SOD.CUPSEntityId,SOD.IPSServiceId,sod.PackageServiceOrderDetailId,ID.ID,I.InvoiceNumber 'NRO FACTURA',
 CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CUPS2.[CUPS] 'CUPS PAQUETE',CUPS2.[DESCRIPCION CUPS] 'DESCRIPCION PAQUETE',UNI.[ESTADO FACTURACION],
 UNI.[FECHA ANULACION]
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  INNER JOIN CTE_PAQUETE_UNICO UNI ON UNI.ID=SOD.ID
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.PackageServiceOrderDetailId
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.PackageServiceOrderDetailId =ID.ServiceOrderDetailId
  LEFT JOIN Billing.ServiceOrderDetail SODP WITH (NOLOCK) ON SODP.Id = sod.PackageServiceOrderDetailId
  LEFT JOIN CTE_CUPS AS CUPS2 WITH (NOLOCK) ON CUPS2.Id=SODP.CUPSEntityId
 WHERE SOD.RecordType=1 AND SOD.Packaging=1  and IM.Agrupador='Resonancia' AND IM.ReportType='Causacion' --AND CUPS.ServiceType IN (3,4,5,6,7,8) 
),

CTE_DATOS_IMAGENES_INCLUIDO
AS
(
 SELECT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,so.status,SOD.CUPSEntityId,SOD.IPSServiceId,SOD.SettlementType,SOD.IncludeServiceOrderDetailId,ID.ID 'Id_DetFacInc',
 I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CUPS2.[CUPS] 'CUPS INCLUIDO',CUPS2.[DESCRIPCION CUPS] 'DESCRIPCION INCLUIDO',
 UNI.[ESTADO FACTURACION],UNI.[FECHA ANULACION]
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN CTE_INCLUIDO_UNICO AS UNI WITH (NOLOCK) ON UNI.ID=SOD.ID
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.IncludeServiceOrderDetailId
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.IncludeServiceOrderDetailId =ID.ServiceOrderDetailId
  LEFT JOIN Billing.ServiceOrderDetail SODI WITH (NOLOCK) ON SODI.Id = sod.IncludeServiceOrderDetailId
  LEFT JOIN CTE_CUPS AS CUPS2 WITH (NOLOCK) ON CUPS2.Id=SODI.CUPSEntityId
   WHERE SOD.RecordType=1 AND SOD.SettlementType IN (2,3) and IM.Agrupador='Resonancia' AND IM.ReportType='Causacion' --and CUPS.ServiceType IN (3,4,5,6,7,8) 
),

CTE_DATOS_FACTURACION_RESONANCIA
AS
(
SELECT  DISTINCT '2. FACTURACION' 'FUENTE',CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CC'WHEN '2'  THEN 'CE'WHEN '3'  THEN 'TI'WHEN '4'  THEN 'RC'WHEN '5'  THEN 'PA'WHEN '6'  THEN 'AS'WHEN '7'  THEN 'MS'
 WHEN '8'  THEN 'NU'WHEN '9'  THEN 'NV'WHEN '10' THEN 'CD'WHEN '11' THEN 'SC'WHEN '12' THEN 'PE' WHEN '13' THEN 'PT'WHEN '14' THEN 'DE'WHEN '15' THEN 'SI'END AS [TIPO IDENTIFICACION],
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CEDULA DE CIUDADANIA' WHEN '2'  THEN 'CEDULA DE EXTRANJERIA' WHEN '3'  THEN 'TARJETA DE IDENTIDAD' WHEN '4'  THEN 'REGISTRO CIVIL' 
 WHEN '5'  THEN 'PASAPORTE' WHEN '6'  THEN 'ADULTO SIN IDENTIFICACION' WHEN '7'  THEN 'MENOR SIN IDENTIFICACION' WHEN '8'  THEN 'NUMERO UNICO DE IDENTIFICACION'
 WHEN '9'  THEN 'CERTIFICADO NACIDO VIVO' WHEN '10' THEN 'CARNET DIPLOMATICO' WHEN '11' THEN 'SALVOCONDUCTO' WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' 
 WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA' WHEN '14' THEN 'DOCUMENTO EXTRANJERO' WHEN '15' THEN 'SIN IDENTIFICACION'END AS [DESCRIPCION IDENTIFICACION],
 PAC.IPCODPACI 'IDENTIFICACION',CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
 CONCAT(FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.InvoiceDate) AS FLOAT) / 365), ' años, ',FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.InvoiceDate) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.InvoiceDate) AS FLOAT) / 365)) * 12),' meses,',FLOOR(((((CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.InvoiceDate) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.InvoiceDate) AS FLOAT) / 365)) * 12) - FLOOR((CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.InvoiceDate) AS FLOAT) / 365 - 
       FLOOR(CAST(DATEDIFF(DAY,PAC.IPFECNACI,I.InvoiceDate) AS FLOAT) / 365)) * 12)) * (365 / 12))), ' días') AS [EDAD],
 CASE PAC.IPSEXOPAC WHEN '1' THEN 'H' WHEN '2' THEN 'M' END AS [CODIGO SEXO],CASE PAC.IPSEXOPAC WHEN '1' THEN 'HOMBRE' WHEN '2' THEN 'MUJER' END AS [SEXO],
 UPPER(PAC.IPPRIAPEL) 'PRIMER APELLIDO',UPPER(PAC.IPSEGAPEL) 'SEGUNDO APELLIDO',UPPER(PAC.IPPRINOMB) 'PRIMER NOMBRE',UPPER(PAC.IPSEGNOMB) 'SEGUNDO NOMBRE',
 PAC.IPNOMCOMP 'NOMBRE COMPLETO PACIENTE',TP.Nit AS NIT,TP.Name AS ENTIDAD,HA.HealthEntityCode 'CODIGO EAPB',CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],
 CASE HA.EntityType WHEN 1 THEN 'EPS Contributivo' WHEN 2 THEN 'EPS Subsidiado' WHEN 3 THEN 'ET Vinculados Municipios' WHEN 4 THEN 'ET Vinculados Departamentos'
 WHEN 5 THEN 'ARL Riesgos Laborales' WHEN 6 THEN 'MP Medicina Prepagada' WHEN 7 THEN 'IPS Privada' WHEN 8 THEN 'IPS Publica' WHEN 9 THEN 'Regimen Especial'
 WHEN 10 THEN 'Accidentes de transito' WHEN 11 THEN 'Fosyga' WHEN 12 THEN 'Otros' ELSE 'Otros' end [REGIMEN],
 ING.NUMINGRES 'INGRESO', 'N/A' 'FOLIO',CAST(SOD.ServiceDate AS DATE) 'FECHA ORDEN',CUPS.[CUPS],CUPS.[DESCRIPCION CUPS],
 ISNULL(CD.Name,CUPS.[DESCRIPCION CUPS])'DESCRIPCION RELACIONADA',isnull(ID.InvoicedQuantity,SOD.InvoicedQuantity) 'CANTIDAD','N/A' 'EXTRAMURAL','ESTUDIO REALIZADO' 'ESTADO',
 FU.Name 'UNIDAD FUNCIONAL',SOD.PerformsHealthProfessionalCode 'ID PROFESIONAL ORDEN',MED.NOMMEDICO 'PROFESIONAL ORDEN',ESPMED.DESESPECI 'ESPECIALIDAD ORDEN',
 G.[IDENTIFICACION PROFESIONAL] 'ID PROFESIONAL LECTURA',G.[PROFESIONAL REALIZO] 'PROFESIONAL LECTURA',G.[ESPECIALIDA REALIZO] 'ESPECIALIDAD LECTURA',
 CAST(ISNULL(G.[FECHA CITA],SOD.ServiceDate) AS DATE) 'FECHA CITA',CAST(G.[FECHA TOMA] AS DATE) 'FECHA DE TOMA',
 CAST(G.[FECHA LECTURA] AS DATE) 'FECHA LECTURA',
 DATEDIFF(DAY, CAST(ISNULL(G.[FECHA CITA],SOD.ServiceDate) AS DATE),CAST(G.[FECHA TOMA] AS DATE)) AS  'TEMPO DE ESPERA FEC CITA VS FEC TOMA',
 DIA.CODDIAGNO 'CIE10 ORDEN',DIA.NOMDIAGNO 'DIAGNOSTICO ORDEN',
 SOD.ID,SO.Code 'NRO ORDEN FACTURACION','FACTURADO' 'ESTADO FACTURACION',I.InvoiceNumber'NRO FACTURA',
 CAST(I.InvoiceDate AS DATE) [FECHA FACTURA],
 G.NUMCONCIT 'IDCITA',IM.Agrupador 'AGRUPADOR',
 isnull(CAST(ID.TotalSalesPrice AS NUMERIC(18,2)),cast(SOD.TotalSalesPrice as numeric(18,2))) 'VALOR UNITARIO',
 isnull(CAST(ID.GrandTotalSalesPrice AS NUMERIC(18,2)),cast(SOD.GrandTotalSalesPrice as numeric(18,2))) 'VALOR TOTAL',G.[NRO INDIRA],
 G.[ESTADO LECTURA INDIRA], G.[ESTADO ORDEN INDIRA],
 --CASE SOD.Packaging WHEN 1 THEN 'SI' ELSE 'NO' END 'EMPAQUETADO',SOD.PackageServiceOrderDetailId,
 --CASE SettlementType WHEN 3 THEN 'SI' ELSE 'NO' END 'INCLUIDO EN SERVICIO',SOD.IncludeServiceOrderDetailId,
  CAST(I.InvoiceDate AS DATE) 'FECHA BUSQUEDA'
 
  FROM  Billing.Invoice AS I WITH (NOLOCK)
   INNER JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId =I.Id
   INNER JOIN Billing.ServiceOrderDetail AS SOD WITH (NOLOCK) ON SOD.Id =ID.ServiceOrderDetailId
   INNER JOIN Billing.ServiceOrder AS SO WITH (NOLOCK) ON SO.Id =SOD.ServiceOrderId
   INNER JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =SOD.CostCenterId
   INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
   INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON CAST(ING.NUMINGRES  AS CHAR)=CAST(I.AdmissionNumber AS CHAR)
   INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =I.PatientCode
   INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
   INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS]
   INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= I.HealthAdministratorId
   INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =I.ThirdPartyId
   INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =I.CareGroupId
   LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
   LEFT JOIN dbo.INESPECIA AS ESPMED WITH (NOLOCK) ON ESPMED.CODESPECI = SOD.PerformsProfessionalSpecialty
   LEFT JOIN DBO.SEGusuaru USUF WITH (NOLOCK) ON USUF.CODUSUARI = I.InvoicedUser
   LEFT JOIN DBO.SEGusuaru USUA WITH (NOLOCK) ON USUA.CODUSUARI = I.AnnulmentUser
   LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =SOD.CUPSEntityContractDescriptionId  AND SOD.CUPSEntityId=DESCR.CUPSEntityId 
   LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
   LEFT JOIN
  (
      SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.MEDREALEC,A.ESPEREALIZA,A.GENSERVICEORDER,A.AUTO,IND.NumeroAccesoINDIRA 'NRO INDIRA',
	  ISNULL(IND.IdentificacionUsuarioValida,A.MEDREALEC) 'IDENTIFICACION PROFESIONAL',ISNULL(PROIN.NOMMEDICO,PRO.NOMMEDICO) 'PROFESIONAL REALIZO',
	  ISNULL(ESPIN.DESESPECI,ESP.DESESPECI) 'ESPECIALIDA REALIZO',ISNULL(MFCIN.ContractName,MFC.ContractName) 'AGREMIACION',
	  CAST(ISNULL(IND.FechaLecturaConfirmada,A.FECHLECT) AS DATE) 'FECHA LECTURA','' NUMCONCIT,IND.[ESTADO LECTURA INDIRA], IND.[ESTADO ORDEN INDIRA],
	  ISNULL(A.FECORDMED,IND.FechaInicialCita) 'FECHA CITA',CAST(ISNULL(IND.[Fecha de toma estudio],FECRECEXA) AS DATE) [FECHA TOMA]
       FROM dbo.HCORDIMAG A WITH (NOLOCK)
       INNER JOIN
       (
        SELECT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER,MAX(A.AUTO) AUTO
         FROM dbo.ADINGRESO ing WITH (NOLOCK)
	        INNER JOIN dbo.HCORDIMAG A with (nolock) ON ing.NUMINGRES = A.NUMINGRES
			where A.MEDREALEC IS NOT NULL AND A.GENSERVICEORDER IS NOT NULL 
	        GROUP BY A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER
       ) AS G ON G.AUTO=A.AUTO AND G.NUMINGRES=A.NUMINGRES AND G.CODSERIPS=A.CODSERIPS
       LEFT JOIN dbo.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL=A.MEDREALEC
       LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI =PRO.CODESPEC1
       LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =PRO.CODPROSAL AND HPC.LiquidateDefault = 1
       LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
       LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=A.NUMINGRES AND IND.NumeroOrdenVIE=A.AUTO
	   LEFT JOIN dbo.INPROFSAL AS PROIN WITH (NOLOCK) ON PROIN.CODPROSAL=IND.IdentificacionUsuarioValida
       LEFT JOIN dbo.INESPECIA AS ESPIN WITH (NOLOCK) ON ESPIN.CODESPECI =PRO.CODESPEC1
       LEFT JOIN MedicalFees.HealthProfessionalContract HPCIN WITH (NOLOCK)  ON HPCIN.HealthProfessionalCode =PROIN.CODPROSAL AND HPCIN.LiquidateDefault = 1
       LEFT JOIN MedicalFees.MedicalFeesContract MFCIN WITH (NOLOCK) ON MFCIN.Id = HPCIN.MedicalFeesContractId
	  UNION ALL
        SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.MEDREALEC,A.ESPEREALIZA,A.GENSERVICEORDER,A.AUTO,IND.NumeroAccesoINDIRA 'NRO INDIRA',
		ISNULL(IND.IdentificacionUsuarioValida,A.MEDREALEC) 'IDENTIFICACION PROFESIONAL',ISNULL(PROIN.NOMMEDICO,PRO.NOMMEDICO) 'PROFESIONAL REALIZO',
	    ISNULL(ESPIN.DESESPECI,ESP.DESESPECI) 'ESPECIALIDA REALIZO',ISNULL(MFCIN.ContractName,MFC.ContractName) 'AGREMIACION',
		CAST(ISNULL(IND.FechaLecturaConfirmada,A.FECHLECT) AS DATE) 'FECHA LECTURA','' NUMCONCIT,IND.[ESTADO LECTURA INDIRA], IND.[ESTADO ORDEN INDIRA],
	    ISNULL(CIT.FECREGSIS,ISNULL(A.FECORDMED,IND.FechaInicialCita)) 'FECHA CITA',CAST(ISNULL(IND.[Fecha de toma estudio],FECRECEXA) AS DATE) [FECHA TOMA]
        FROM dbo.AMBORDIMA A WITH (NOLOCK)
        INNER JOIN
        (
         SELECT DISTINCT A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER,MAX(A.AUTO) AUTO
         FROM dbo.ADINGRESO ing WITH (NOLOCK)
	      INNER JOIN dbo.AMBORDIMA A WITH (NOLOCK) ON ing.NUMINGRES = A.NUMINGRES
		  where A.MEDREALEC IS NOT NULL AND A.GENSERVICEORDER IS NOT NULL
	      GROUP BY A.IPCODPACI,A.NUMINGRES,A.CODSERIPS,A.GENSERVICEORDER
        ) AS G ON G.AUTO=A.AUTO AND G.NUMINGRES=A.NUMINGRES AND G.CODSERIPS=A.CODSERIPS
        LEFT JOIN dbo.INPROFSAL AS PRO WITH (NOLOCK) ON PRO.CODPROSAL=A.MEDREALEC
        LEFT JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI =PRO.CODESPEC1
        LEFT JOIN dbo.INPROFSAL AS PROE WITH (NOLOCK) ON PROE.CODPROSAL=A.USURECEXA
        LEFT JOIN dbo.INESPECIA AS ESPE WITH (NOLOCK) ON ESPE.CODESPECI =PROE.CODESPEC1
        LEFT JOIN MedicalFees.HealthProfessionalContract HPC WITH (NOLOCK)  ON HPC.HealthProfessionalCode =ISNULL(PRO.CODPROSAL,PROE.CODPROSAL) AND HPC.LiquidateDefault = 1
        LEFT JOIN MedicalFees.MedicalFeesContract MFC WITH (NOLOCK) ON MFC.Id = HPC.MedicalFeesContractId
		LEFT JOIN dbo.AGASICITA CIT WITH (NOLOCK) ON CIT.CODAUTONU=A.NUMCONCIT
		LEFT JOIN CTE_DATOS_INDIRA AS IND ON IND.IngresoVIE=A.NUMINGRES AND IND.NumeroOrdenVIE=A.AUTO
		LEFT JOIN dbo.INPROFSAL AS PROIN WITH (NOLOCK) ON PROIN.CODPROSAL=IND.IdentificacionUsuarioValida
        LEFT JOIN dbo.INESPECIA AS ESPIN WITH (NOLOCK) ON ESPIN.CODESPECI =PRO.CODESPEC1
        LEFT JOIN MedicalFees.HealthProfessionalContract HPCIN WITH (NOLOCK)  ON HPCIN.HealthProfessionalCode =PROIN.CODPROSAL AND HPCIN.LiquidateDefault = 1
        LEFT JOIN MedicalFees.MedicalFeesContract MFCIN WITH (NOLOCK) ON MFCIN.Id = HPCIN.MedicalFeesContractId
  ) AS G ON G.NUMINGRES=CAST(I.AdmissionNumber AS CHAR) AND G.GENSERVICEORDER=SO.ID AND G.CODSERIPS=CUPS.[CUPS]
  LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=I.OutputDiagnosis
  --LEFT JOIN dbo.AMBORDIMA A WITH (NOLOCK) ON 
   WHERE I.STATUS=1 AND SOD.RecordType=1 AND IM.Agrupador='Resonancia' AND IM.ReportType='Causacion' --AND CUPS.ServiceType  in (3,4,5,6,7,8) 
   AND CAST(I.InvoiceDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN

)


 SELECT * FROM CTE_DATOS_ORDENES_IMAGENES_HOSPITALARIA--where ingreso='134711'
UNION ALL
 SELECT * FROM CTE_DATOS_ORDENES_IMAGENES_AMBULATORIA
UNION ALL
SELECT IMG.* FROM CTE_DATOS_FACTURACION_RESONANCIA IMG
LEFT JOIN CTE_DATOS_IMAGENES_EMPAQUETADO PAQ ON IMG.Id=PAQ.ServiceOrderDetailId
LEFT JOIN CTE_DATOS_IMAGENES_INCLUIDO INC ON IMG.Id=INC.ServiceOrderDetailId
