-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_TERAPIAS_PRODUCTIVIDAD_FECHA_SERVICIO_V2
-- Extracted by Fabric SQL Extractor SPN v3.9.0

--SET STATISTICS TIME ON;
CREATE PROCEDURE [Report].[IND_SP_V2_EHR_TERAPIAS_PRODUCTIVIDAD_FECHA_SERVICIO_V2]

@FECHAINI AS DATE,
@FECHAFIN AS DATE

--DECLARE @FECHAINI AS DATE='2024-07-01';
--DECLARE @FECHAFIN AS DATE='2024-07-31';

AS

WITH CTE_CUPS
AS
(
   SELECT CUPS.Id,CUPS.Code [CUPS], CUPS.Description [DESCRIPCION CUPS], 
   CASE CUPS.ServiceType WHEN 1 then 'LABORATORIOS' WHEN 2 then 'PATOLOGIAS' WHEN 3 then 'IMAGENES DIAGNOSTICAS' WHEN 4 then 'PROCEDIMIENTOS NO QX'
   WHEN 5 then 'PROCEDIMIENTOS QX' WHEN 6 then 'INTERCONSULTAS'WHEN 7 then 'NINGUNO'WHEN 8 then 'CONSULTA EXTERNA' WHEN 9 THEN 'HEMOCOMPONENTES' ELSE 'OTROS' END AS 'TIPO SERVICIO',
   BG.CODE 'CODIGO FACTURACION',BG.NAME 'GRUPO FACTURACION',BC.CODE 'CODIGO CONCEPTO',BC.NAME 'CONCEPTO FACTURACION',CGC.Code 'CODIGO GRUPO',CGC.Name 'GRUPO CUPS',
   CSG.CODE 'CODIGO SUBGRUPO',CSG.Name  'SUBGRUPO CUPS',
   CASE ObtainCostCenter WHEN 1 THEN 'Unidad Funcional del Paciente' WHEN 2 THEN 'Centro de Costo Específico' WHEN 3 THEN 'Centro de Costo por Sucursal y Unidad Funcional'
   ELSE 'N/A' END 'OBTENER CC',CUPS.ServiceType
   FROM Contract.CUPSEntity AS CUPS WITH (NOLOCK)
   INNER JOIN Billing.BillingGroup as BG WITH (NOLOCK) ON BG.Id=CUPS.BillingGroupId
   INNER JOIN Billing.BillingConcept as BC WITH (NOLOCK) ON BC.Id=CUPS.BillingConceptId
   INNER JOIN Contract.CupsSubgroup AS CSG WITH (NOLOCK) ON CSG.Id =CUPS.CUPSSubGroupId
   INNER JOIN Contract.CupsGroup AS CGC WITH (NOLOCK) ON CGC.Id =CSG.CupsGroupId
 ),

 ---*************************************************************************************************************************************************************************-----

CTE_DATOS_ORDENES_TERAPIAS
AS
(
 SELECT 'VIE' 'FUENTE','1. ORDEN MEDICA' 'FUNCIONAL',CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',TER.IPCODPACI 'IDENTIFICACION',
 PAC.IPNOMCOMP 'PACIENTE',TER.NUMINGRES 'INGRESO', TER.NUMEFOLIO 'FOLIO',CAST(TER.FECORDMED AS DATE) 'FECHA ORDEN',TER.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS],
 CD.Name 'DESCRIPCION RELACIONADA',TER.CANSERIPS 'CANTIDAD', CASE MANEXTPRO WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'EXTRAMURAL', UNI.UFUDESCRI 'UNIDAD FUNCIONAL',
 TER.CODPROSAL 'ID PROFESIONAL',MED.NOMMEDICO 'PROFESIONAL',ESP.DESESPECI 'ESPECIALIDAD' ,TER.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',TP.Nit AS NIT,TP.Name AS ENTIDAD,
 CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],'N/A' 'FACTURADO','N/A' 'NRO FACTURA',TER.AUTO,TER.GENSERVICEORDER
 FROM DBO.HCORDPRON TER WITH (NOLOCK)
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS] 
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = TER.UFUCODIGO
 INNER JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = TER.CODPROSAL
 INNER JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = MED.CODESPEC1
 INNER JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=TER.CODDIAGNO
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 WHERE IM.Agrupador='Terapias' AND TER.ESTSERIPS<>5 AND CAST(TER.FECORDMED AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
 --AND TER.NUMINGRES='118242    '
),

---*************************************************************************************************************************************************************************-----

CTE_DATOS_EJECUCION_TERAPIAS
AS
(
 SELECT 'VIE' 'FUENTE','2. NOTAS TERAPIAS' 'FUNCIONAL',CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',TER.IPCODPACI 'IDENTIFICACION',
 PAC.IPNOMCOMP 'PACIENTE',TER.NUMINGRES 'INGRESO', NULL 'FOLIO',CAST(TER.FECHISPAC AS DATE) 'FECHA ORDEN',TER.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS],
 CD.Name 'DESCRIPCION RELACIONADA',1 'CANTIDAD', 'NO' 'EXTRAMURAL', UNI.UFUDESCRI 'UNIDAD FUNCIONAL',
 TER.CODPROSAL 'ID PROFESIONAL',MED.NOMMEDICO 'PROFESIONAL',ESP.DESESPECI 'ESPECIALIDAD',DIA.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',TP.Nit AS NIT,TP.Name AS ENTIDAD,
 CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],'N/A' 'FACTURADO','N/A' 'NRO FACTURA',TER.CODCONSEC,TER.GENSERVICEORDER 
 FROM dbo.HCPROCTER TER
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=TER.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =TER.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON TER.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = TER.UFUCODIGO
 INNER JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = TER.CODPROSAL
 INNER JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = TER.CODESPECI
 INNER JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=ISNULL(CODDIAEGR,CODDIAING)
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =ING.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA (NOLOCK) ON HA.ID= ING.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =TER.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 WHERE IM.Agrupador='Terapias' AND CAST(TER.FECHISPAC AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
 --AND TER.NUMINGRES='118242    '
),

---*************************************************************************************************************************************************************************-----

CTE_CONSULTAS_TERAPIAS
AS
(
 SELECT 'VIE' 'FUENTE','3. HC CONSULTA EXTERNA' 'FUNCIONAL',CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',CON.IPCODPACI 'IDENTIFICACION',
 PAC.IPNOMCOMP 'PACIENTE',CON.NUMINGRES 'INGRESO', HIS.NUMEFOLIO 'FOLIO',CAST(CON.IPFECHCIT AS DATE) 'FECHA ORDEN',CIT.CODSERIPS 'CUPS',CUPS.[DESCRIPCION CUPS],
 CD.Name 'DESCRIPCION RELACIONADA',1 'CANTIDAD', 'NO' 'EXTRAMURAL', UNI.UFUDESCRI 'UNIDAD FUNCIONAL',
 CON.CODPROSAL 'ID PROFESIONAL',MED.NOMMEDICO 'PROFESIONAL',ESP.DESESPECI 'ESPECIALIDAD',DIA.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',TP.Nit AS NIT,TP.Name AS ENTIDAD,
 CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],'N/A' 'FACTURADO','N/A' 'NRO FACTURA',CON.CODCONCEC,HIS.GENSERVICEORDER 
 FROM DBO.adconcoex CON WITH (NOLOCK)
 INNER JOIN DBO.agasicita CIT WITH (NOLOCK) ON CON.NUMCONCIT=CODAUTONU
 INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.[CUPS]=CIT.[CODSERIPS]
 INNER JOIN REPORT.TableSocieties as IM WITH (NOLOCK) on IM.Code=CUPS.[CUPS]
 INNER JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =CON.IPCODPACI
 INNER JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON CON.NUMINGRES=ING.NUMINGRES
 INNER JOIN dbo.INUNIFUNC AS UNI WITH (NOLOCK) ON UNI.UFUCODIGO = CON.UFUCODIGO
 INNER JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = CON.CODPROSAL
 INNER JOIN dbo.INESPECIA AS ESP WITH (NOLOCK) ON ESP.CODESPECI = CON.CODESPECI
 INNER JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=ISNULL(ING.CODDIAEGR,ING.CODDIAING)
 INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =CON.GENCAREGROUP
 INNER JOIN Contract.HealthAdministrator HA WITH (NOLOCK) ON HA.ID= CON.GENCONENTITY
 INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =HA.ThirdPartyId
 LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =CON.IDDESCRIPCIONRELACIONADA  AND CUPS.Id=DESCR.CUPSEntityId 
 LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
 LEFT JOIN DBO.HCHISPACA AS HIS WITH (NOLOCK) ON HIS.Id=CON.IDHCHISPACA
 WHERE  IM.Agrupador='Terapias' AND CON.CONESTADO=3 AND CAST(CON.IPFECHCIT AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
),

---*************************************************************************************************************************************************************************-----

CTE_DATOS_CARGOS_TERAPIAS
AS
(
 SELECT 'VIE' 'FUENTE','4. ORDEN DE SERVICIO' 'FUNCIONAL',CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END 'AMBITO',PAC.IPCODPACI 'IDENTIFICACION',
 PAC.IPNOMCOMP 'PACIENTE',ISNULL(RC.AdmissionNumber,SO.AdmissionNumber) 'INGRESO', NULL 'FOLIO',CAST(SOD.ServiceDate AS DATE) 'FECHA ORDEN',CUPS.[CUPS],CUPS.[DESCRIPCION CUPS],
 CD.Name 'DESCRIPCION RELACIONADA',isnull(ID.InvoicedQuantity,SOD.InvoicedQuantity)'CANTIDAD', 'NO' 'EXTRAMURAL', FU.Name 'UNIDAD FUNCIONAL',
 MED.CODPROSAL 'ID PROFESIONAL',MED.NOMMEDICO 'PROFESIONAL',ESPMED.DESESPECI 'ESPECIALIDAD',DIA.CODDIAGNO 'CIE10',DIA.NOMDIAGNO 'DIAGNOSTICO',TP.Nit AS NIT,TP.Name AS ENTIDAD,
 CG.Code AS [CODIGO GRUPO ATENCION],CG.Name AS [GRUPO ATENCION],SOD.ID AUTO,SO.ID GENSERVICEORDER,I.InvoiceNumber 'NRO FACTURA'/* */
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN Payroll.CostCenter AS CC WITH (NOLOCK) ON CC.Id =SOD.CostCenterId
  INNER JOIN Payroll.FunctionalUnit AS FU WITH (NOLOCK) ON FU.Id = SOD.PerformsFunctionalUnitId
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  INNER JOIN Common.ThirdParty AS TP WITH (NOLOCK) ON TP.Id =SOD.ThirdPartyId
  INNER JOIN Contract.CareGroup AS CG WITH (NOLOCK) ON CG.Id =SOD.CareGroupId
  LEFT JOIN dbo.INPROFSAL AS MED  WITH (NOLOCK) ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
  LEFT JOIN dbo.INESPECIA AS ESPMED WITH (NOLOCK) ON ESPMED.CODESPECI = SOD.PerformsProfessionalSpecialty
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.Id
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.Id =ID.ServiceOrderDetailId
  LEFT JOIN dbo.INPACIENT AS PAC WITH (NOLOCK) ON PAC.IPCODPACI =ISNULL(RC.PatientCode,SO.PatientCode)
  LEFT JOIN dbo.ADINGRESO AS ING WITH (NOLOCK) ON CAST(ING.NUMINGRES  AS CHAR)=CAST(ISNULL(RC.AdmissionNumber,SO.AdmissionNumber) AS CHAR)
  LEFT JOIN dbo.INDIAGNOS AS DIA WITH (NOLOCK) ON DIA.CODDIAGNO=ISNULL(ING.CODDIAEGR,ING.CODDIAING)
  LEFT JOIN Contract.CUPSEntityContractDescriptions AS DESCR WITH (NOLOCK) ON DESCR.Id  =SOD.CUPSEntityContractDescriptionId  AND SOD.CUPSEntityId=DESCR.CUPSEntityId 
  LEFT JOIN Contract.ContractDescriptions AS CD WITH (NOLOCK) ON CD.ID=DESCR.ContractDescriptionId
  WHERE IM.Agrupador='Terapias' AND CAST(SOD.ServiceDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
  --AND ISNULL(RC.AdmissionNumber,SO.AdmissionNumber)='118242'
),

CTE_DATOS_CARGOS_EMPAQUETADO
AS
(
 SELECT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,so.status,SOD.CUPSEntityId,SOD.IPSServiceId,sod.PackageServiceOrderDetailId,
 ID.ID,I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CUPS2.[CUPS] 'CUPS PAQUETE',CUPS2.[DESCRIPCION CUPS] 'DESCRIPCION PAQUETE'
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.PackageServiceOrderDetailId
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.PackageServiceOrderDetailId =ID.ServiceOrderDetailId
  LEFT JOIN Billing.ServiceOrderDetail SODP WITH (NOLOCK) ON SODP.Id = sod.PackageServiceOrderDetailId
  LEFT JOIN CTE_CUPS AS CUPS2 WITH (NOLOCK) ON CUPS2.Id=SODP.CUPSEntityId
 WHERE SOD.RecordType=1 AND SOD.Packaging=1  and IM.Agrupador='Terapias' AND CAST(SOD.ServiceDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
 ),

CTE_DATOS_CARGOS_INCLUIDO
AS
(
 SELECT SOD.ServiceOrderId,sod.Id ServiceOrderDetailId,so.status,SOD.CUPSEntityId,SOD.IPSServiceId,SOD.SettlementType,SOD.IncludeServiceOrderDetailId,ID.ID 'Id_DetFacInc',
 I.InvoiceNumber 'NRO FACTURA',CAST(I.InvoiceDate AS DATE) 'FECHA FACTURA',CUPS2.[CUPS] 'CUPS INCLUIDO',CUPS2.[DESCRIPCION CUPS] 'DESCRIPCION INCLUIDO'
 FROM Billing.ServiceOrder AS SO WITH (NOLOCK)
  INNER JOIN Billing.ServiceOrderDetail SOD WITH (NOLOCK) ON SO.ID=SOD.ServiceOrderId
  INNER JOIN CTE_CUPS AS CUPS WITH (NOLOCK) ON CUPS.Id=SOD.CUPSEntityId
  INNER JOIN REPORT.TableSocieties as IM on IM.Code=CUPS.[CUPS] 
  LEFT JOIN Billing.ServiceOrderDetailDistribution sodd WITH (NOLOCK) on sodd.ServiceOrderDetailId = sod.IncludeServiceOrderDetailId
  LEFT JOIN Billing.RevenueControlDetail as RCD WITH (NOLOCK) ON RCD.Id=sodd.RevenueControlDetailId
  LEFT JOIN Billing.RevenueControl RC WITH (NOLOCK) ON  RC.Id=RCD.RevenueControlId and SO.AdmissionNumber=RC.AdmissionNumber
  LEFT JOIN Billing.Invoice AS I WITH (NOLOCK) ON I.AdmissionNumber=RC.AdmissionNumber AND I.RevenueControlDetailId=RCD.id
  LEFT JOIN Billing.InvoiceDetail AS ID WITH (NOLOCK) ON ID.InvoiceId=I.Id and SOD.IncludeServiceOrderDetailId =ID.ServiceOrderDetailId
  LEFT JOIN Billing.ServiceOrderDetail SODI WITH (NOLOCK) ON SODI.Id = sod.IncludeServiceOrderDetailId
  LEFT JOIN CTE_CUPS AS CUPS2 WITH (NOLOCK) ON CUPS2.Id=SODI.CUPSEntityId
  WHERE SOD.RecordType=1 AND SOD.SettlementType IN (2,3) and IM.Agrupador='Terapias' AND CAST(SOD.ServiceDate AS DATE) BETWEEN @FECHAINI AND  @FECHAFIN
)

---*************************************************************************************************************************************************************************-----

SELECT FUENTE,FUNCIONAL,AMBITO,IDENTIFICACION,PACIENTE,INGRESO,FOLIO,[FECHA ORDEN],CUPS,[DESCRIPCION CUPS],[DESCRIPCION RELACIONADA],CANTIDAD,EXTRAMURAL,[ID PROFESIONAL],
PROFESIONAL,ESPECIALIDAD,CIE10,DIAGNOSTICO,NIT,ENTIDAD,[CODIGO GRUPO ATENCION],[GRUPO ATENCION],[FACTURADO],[NRO FACTURA],AUTO,GENSERVICEORDER
FROM CTE_DATOS_ORDENES_TERAPIAS
UNION ALL
SELECT FUENTE,FUNCIONAL,AMBITO,IDENTIFICACION,PACIENTE,INGRESO,FOLIO,[FECHA ORDEN],CUPS,[DESCRIPCION CUPS],[DESCRIPCION RELACIONADA],CANTIDAD,EXTRAMURAL,[ID PROFESIONAL],
PROFESIONAL,ESPECIALIDAD,CIE10,DIAGNOSTICO,NIT,ENTIDAD,[CODIGO GRUPO ATENCION],[GRUPO ATENCION],[FACTURADO],[NRO FACTURA],CODCONSEC AUTO,GENSERVICEORDER
FROM CTE_DATOS_EJECUCION_TERAPIAS
UNION ALL
SELECT FUENTE,FUNCIONAL,AMBITO,IDENTIFICACION,PACIENTE,INGRESO,FOLIO,[FECHA ORDEN],CUPS,[DESCRIPCION CUPS],[DESCRIPCION RELACIONADA],CANTIDAD,EXTRAMURAL,[ID PROFESIONAL],
PROFESIONAL,ESPECIALIDAD,CIE10,DIAGNOSTICO,NIT,ENTIDAD,[CODIGO GRUPO ATENCION],[GRUPO ATENCION],[FACTURADO],[NRO FACTURA],CODCONCEC AUTO,GENSERVICEORDER
FROM CTE_CONSULTAS_TERAPIAS
UNION ALL
SELECT IMG.FUENTE,IMG.FUNCIONAL,IMG.AMBITO,IMG.IDENTIFICACION,IMG.PACIENTE,IMG.INGRESO,IMG.FOLIO,IMG.[FECHA ORDEN],IMG.CUPS,[DESCRIPCION CUPS],IMG.[DESCRIPCION RELACIONADA],
IMG.CANTIDAD,IMG.EXTRAMURAL,IMG.[ID PROFESIONAL],IMG.PROFESIONAL,IMG.ESPECIALIDAD,IMG.CIE10,IMG.DIAGNOSTICO,IMG.NIT,IMG.ENTIDAD,IMG.[CODIGO GRUPO ATENCION],
IMG.[GRUPO ATENCION],   IIF(ISNULL(IMG.[NRO FACTURA],ISNULL(PAQ.[NRO FACTURA],INC.[NRO FACTURA])) IS NULL,'NO','SI') 'FACTURADO',
ISNULL(IMG.[NRO FACTURA],ISNULL(PAQ.[NRO FACTURA],INC.[NRO FACTURA])) [NRO FACTURA],IMG.AUTO,IMG.GENSERVICEORDER 
FROM CTE_DATOS_CARGOS_TERAPIAS IMG
LEFT JOIN CTE_DATOS_CARGOS_EMPAQUETADO PAQ ON IMG.AUTO=PAQ.ServiceOrderDetailId
LEFT JOIN CTE_DATOS_CARGOS_INCLUIDO INC ON IMG.AUTO=INC.ServiceOrderDetailId

--ORDER BY FUNCIONAL



--SET STATISTICS TIME OFF;