-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_CIRUGIAS_REALIZADAS_V2
-- Extracted by Fabric SQL Extractor SPN v3.9.0






    /*******************************************************************************************************************
Nombre:[Report].UploadCubeVieClinicalQxProcedures
Tipo:View
Observacion: CIRUGIAS REALIZADAS
Profesional: ANDRES CABRERA
Fecha:
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico:Nilsson Galindo
Fecha: 05-02-2025
Observaciones:se agrega el ct de radicación para saber si una cx es ambulatoria
-------------------------------------------------------------------------------------------------------------------------------------
Version 3
Persona que modifico: Amira Gil Meneses
Fecha:26-05-2025
Observaciones: Se adidionan los campos solicitados FECHA INICIO QX,	HORA INICIO QX,
FECHA INICIAL QX, HORA FINAL QX, HORA INICIO DE ANESTESIA y	HORA FIN ANESTESIA 
Ticket 27311

***********************************************************************************************************************************/


CREATE PROCEDURE [Report].[IND_SP_V2_EHR_CIRUGIAS_REALIZADAS_V2]
@FECHAINI DATE,
@FECHAFIN DATE
AS

--DECLARE @FECHAINI DATE='2025-05-01';
--DECLARE @FECHAFIN DATE='2025-05-08';

WITH CTE_INFORME_QX
AS
(
  SELECT  DISTINCT INF.IPCODPACI [IDENTIFICACION],INF.NUMINGRES [INGRESO],INF.NUMEFOLIO [FOLIO QX],LEFT(CONVERT(VARCHAR,INF.FECHORINI, 120), 16) [FECHA QX],REA.CODSERIPS [CUPS],
  CUPS.Description [DESCRIPCION CUPS],
  CASE REA.QXPRINCIP WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END [QX PRINCIPAL],
  CASE INF.URGECIRUG WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END [QX URGENTE],
  CASE ING.TIPOINGRE WHEN '1' THEN 'AMBULATORIO' WHEN '2' THEN 'HOSPITALARIO' END [AMBITO],
  INF.SALACIRUG [SALA QX],UNI.UFUTIPUNI,
  INF.AUTO,
  INF.UFUCODIGO,
  INF.CODESPECI [CODIGO ESPECIALIDAD],
  ESP.[DESESPECI] [ESPECIALIDAD],
  REA.CONSECUQX,
  UNI.UFUDESCRI [UNIDAD INFORME QX],
  CASE CUPS.ServiceType WHEN 1 THEN 'LABORATORIO' WHEN 2 THEN 'PATOLOGIA' WHEN 3 THEN 'IMAGENES DIAGNOSTICAS' WHEN 4 THEN 'PROCEDIMIENTOS NO QX' 
  WHEN 5 THEN 'PROCEDIMIENTOS QX' WHEN 6 THEN 'INTERCONSULTAS' WHEN 7 THEN 'NINGUNO' WHEN 8 THEN 'CONSULTA EXTERNA' END [TIPO SERVICIO],
  HEA.HealthEntityCode [CODIGO ENTIDAD],
  HEA.NAME [NOMBRE ENTIDAD],
  ROW_NUMBER() OVER (PARTITION BY INF.NUMINGRES, INF.NUMEFOLIO ORDER BY REA.QXPRINCIP DESC, CUPS.ID ) AS [ORDEN CARGUE QX],
  CASE INF.TIPHERCIR WHEN 1 THEN 'Limpia' 
					  WHEN 2 THEN 'Limpia Contaminada'
					  WHEN 3 THEN 'Contaminada'
					  WHEN 4 THEN 'Sucia e Infectada'
					  WHEN 5 THEN 'Sucia'
					  WHEN 6 THEN 'Infectada'
					  WHEN 7 THEN 'No Aplica' END AS [TIPO HERIDA],
IAUTORIZA,
 CAST(INF.FECHORINI AS DATE) AS [FECHA INICIO CIRUGIA],
 FORMAT( INF.FECHORINI, 'hh:mm tt', 'es-CO') AS [HORA INICIO CIRUGIA], 
 CAST(INF.FECHORFIN AS DATE) AS [FECHA FINAL CIRUGIA],
 FORMAT(INF.FECHORFIN, 'hh:mm tt', 'es-CO') AS [HORA FINAL CIRUGIA],
 INF.NUMINGRES,
 INF.CODSERIPS,INF.FECHORINI,
 INF.CODDIAPRE ,INF.CODDIAPOS 

  FROM 
  dbo.HCQXINFOR INF WITH (NOLOCK)
  INNER JOIN dbo.HCQXREALI AS REA WITH (NOLOCK) ON INF.IPCODPACI=REA.IPCODPACI AND REA.NUMINGRES=INF.NUMINGRES AND REA.NUMEFOLIO=INF.NUMEFOLIO
  INNER JOIN Contract.CUPSEntity AS CUPS ON CUPS.CODE=REA.CODSERIPS
  INNER JOIN DBO.ADINGRESO AS ING ON ING.NUMINGRES=INF.NUMINGRES
  INNER JOIN DBO.INESPECIA AS ESP ON ESP.CODESPECI=INF.CODESPECI
  LEFT JOIN DBO.INUNIFUNC AS UNI ON REA.UFUCODIGO=UNI.UFUCODIGO
  LEFT JOIN Contract.HealthAdministrator AS HEA WITH (NOLOCK) ON ING.GENCONENTITY = HEA.Id
  WHERE cast(INF.FECHORINI as date) BETWEEN @FECHAINI AND @FECHAFIN 
--  AND INF.NUMINGRES ='148592    ' --- IN ('148954','145032')
),

CTE_ANESTESIA AS
 (
  SELECT
   ANE.NUMINGRES,
   ANE1.CODCIRUGI AS CUPS,
   FORMAT(ANE.HORINIANES, 'hh:mm tt', 'es-CO') AS [HORA INICIO ANESTESIA],
   FORMAT(ANE.HORFINANES, 'hh:mm tt', 'es-CO') AS [HORA FIN ANESTESIA],
   ANE.OBSERVACIO,
   RTRIM(PRO.CODPROSAL)+' - '+PRO.NOMMEDICO AS MEDICO
  FROM
   dbo.HCREGANES ANE
   INNER JOIN (SELECT MIN(IDANESTES) IDANESTES, NUMINGRES, RCX.CODCIRUGI 
               FROM 
			    dbo.HCREGANES ANE
				INNER JOIN dbo.HCREGICIR RCX ON ANE.IDANESTES=RCX.IDREGIANES 
			   GROUP BY NUMINGRES, RCX.CODCIRUGI ) ANE1 ON ANE1.IDANESTES = ANE.IDANESTES
   INNER JOIN dbo.INPROFSAL PRO ON PRO.CODPROSAL=ANE.CODPROSAL
 ),

CTE_ORDENES_HOSPITALARIAS  
AS
(
  SELECT Q.IPCODPACI [IDENTIFICACION],Q.NUMINGRES [INGRESO],Q.NUMEFOLIO [FOLIO ORDEN/RADICADO],LEFT(CONVERT(VARCHAR,Q.FECORDMED, 120), 16) [FECHA ORDEN/RADICADO],Q.CODSERIPS [CUPS],
  PRO.CODAUTONU,SAL.DESCRIPSAL [SALA],UNI.UFUDESCRI [UNIDAD FUNCIONAL],PRO.CODPROSAL [COD_PROFESIONAL],PRO.CODESPECI [COD_ESPECIALIDAD],'HOSPITALARIO' [AMBITO]
  ,CASE PRO.TIPOANESTESIA WHEN '1' THEN 'Local'
						 WHEN '2' THEN 'Regional' 
						 WHEN '3' THEN 'General'
						 WHEN '4' THEN 'Combinada' 
						 WHEN '5' THEN 'No aplica' 
						 END AS 'TIPO DE ANESTESIA'
  FROM DBO.HCORDPROQ Q 
   INNER JOIN 
   (
     SELECT Q.NUMINGRES,Q.CODSERIPS,MAX(Q.AUTO) AUTO
      FROM  DBO.HCORDPROQ Q
      INNER JOIN CTE_INFORME_QX AS ING ON Q.NUMINGRES=ING.INGRESO AND Q.CODSERIPS=ING.[CUPS] AND LEFT(CONVERT(VARCHAR,Q.FECORDMED, 120), 16) <= ING.[FECHA QX]
	  WHERE  MANEXTPRO=0 AND Q.CODANULA IS NULL
     GROUP BY Q.NUMINGRES,Q.CODSERIPS
   ) AS G ON G.AUTO=Q.AUTO
   LEFT JOIN DBO.AGEPROGQX PRO ON PRO.AUTOHCORDPROQ=Q.AUTO AND PRO.ORIGENQX=2 AND PRO.CODCAUCAN IS NULL
   LEFT JOIN dbo.AGENSALAC SAL ON PRO.AGENSALAC=SAL.CODCONCEC
   LEFT JOIN DBO.INUNIFUNC AS UNI ON SAL.UFUCODIGO=UNI.UFUCODIGO

   UNION ALL
    SELECT NQ.IPCODPACI [IDENTIFICACION],NQ.NUMINGRES [INGRESO],NQ.NUMEFOLIO [FOLIO ORDEN/RADICADO],LEFT(CONVERT(VARCHAR,NQ.FECORDMED, 120), 16) [FECHA ORDEN/RADICADO],NQ.CODSERIPS [CUPS],
     PRO.CODAUTONU,SAL.DESCRIPSAL [SALA],UNI.UFUDESCRI [UNIDAD FUNCIONAL],PRO.CODPROSAL [COD_PROFESIONAL],PRO.CODESPECI [COD_ESPECIALIDAD],'HOSPITALARIO' [AMBITO]
     ,CASE PRO.TIPOANESTESIA WHEN '1' THEN 'Local'
						 WHEN '2' THEN 'Regional' 
						 WHEN '3' THEN 'General'
						 WHEN '4' THEN 'Combinada' 
						 WHEN '5' THEN 'No aplica' 
						 END AS 'TIPO DE ANESTESIA'
	 FROM dbo.HCORDPRON NQ
     INNER JOIN 
     (
     SELECT NQ.NUMINGRES,NQ.CODSERIPS,MAX(NQ.AUTO) AUTO
     FROM dbo.HCORDPRON NQ
     INNER JOIN CTE_INFORME_QX AS ING ON NQ.NUMINGRES=ING.INGRESO AND NQ.CODSERIPS=ING.[CUPS] AND LEFT(CONVERT(VARCHAR,NQ.FECORDMED, 120), 16) <= ING.[FECHA QX]
     WHERE  MANEXTPRO=0 --AND NQ.ESTSERIPS<>5
     GROUP BY NQ.NUMINGRES,NQ.CODSERIPS
	 ) AS G ON G.AUTO=NQ.AUTO
	 LEFT JOIN DBO.AGEPROGQX PRO ON PRO.AUTOHCORDPRON=NQ.AUTO AND PRO.ORIGENQX=2 AND PRO.CODCAUCAN IS NULL
	 LEFT JOIN dbo.AGENSALAC SAL ON PRO.AGENSALAC=SAL.CODCONCEC
     LEFT JOIN DBO.INUNIFUNC AS UNI ON SAL.UFUCODIGO=UNI.UFUCODIGO
),

CTE_ORDENES_AMBULATORIAS
AS
(
  SELECT  Q.IPCODPACI [IDENTIFICACION],NULL [INGRESO],RAD.NUMRADICACION [FOLIO ORDEN/RADICADO],LEFT(CONVERT(VARCHAR,RAD.FECHARADIC, 120), 16) [FECHA ORDEN/RADICADO],Q.CODSERIPS [CUPS],
  Q.CODAUTONU,SAL.DESCRIPSAL [SALA],UNI.UFUDESCRI [UNIDAD FUNCIONAL],Q.CODPROSAL [COD_PROFESIONAL],Q.CODESPECI [COD_ESPECIALIDAD],'AMBULATORIO' [AMBITO]
   ,CASE Q.TIPOANESTESIA WHEN '1' THEN 'Local'
						 WHEN '2' THEN 'Regional' 
						 WHEN '3' THEN 'General'
						 WHEN '4' THEN 'Combinada' 
						 WHEN '5' THEN 'No aplica' 
						 END AS 'TIPO DE ANESTESIA'
  FROM  DBO.AGEPROGQX AS Q
   INNER JOIN 
    (
     SELECT  Q.IPCODPACI,Q.CODSERIPS,MAX(CODAUTONU) CODAUTONU
     FROM DBO.AGEPROGQX AS Q
     INNER JOIN CTE_INFORME_QX AS ING ON Q.IPCODPACI=ING.[IDENTIFICACION] AND Q.CODSERIPS=ING.[CUPS] AND LEFT(CONVERT(VARCHAR,Q.FECREGSIS, 120), 16) <= ING.[FECHA QX]
     GROUP BY Q.IPCODPACI,Q.CODSERIPS
	) AS G ON G.CODAUTONU=Q.CODAUTONU AND G.IPCODPACI=Q.IPCODPACI AND G.CODSERIPS=Q.CODSERIPS
	INNER JOIN DBO.ADRADICACIONQX as RAD ON RAD.ID=Q.IDRADICACIONQX
	LEFT JOIN dbo.AGENSALAC SAL ON Q.AGENSALAC=SAL.CODCONCEC
    LEFT JOIN DBO.INUNIFUNC AS UNI ON SAL.UFUCODIGO=UNI.UFUCODIGO
	WHERE Q.ORIGENQX=1
),
CTE_RADICACION AS 
(
SELECT INF.NUMINGRES 
FROM 
dbo.HCQXINFOR INF
INNER JOIN dbo.HCQXREALI AS REA ON REA.NUMINGRES=INF.NUMINGRES AND REA.NUMEFOLIO=INF.NUMEFOLIO
INNER JOIN dbo.AGEPROGQX AGE ON INF.IPCODPACI=AGE.IPCODPACI AND CAST(INF.FECHORINI AS DATE)=CAST(AGE.FECHORAIN AS DATE) AND REA.CODSERIPS=AGE.CODSERIPS
INNER JOIN dbo.ADRADICACIONQX RAD ON AGE.IDRADICACIONQX=RAD.ID
WHERE cast(INF.FECHORINI as date) BETWEEN @FECHAINI AND @FECHAFIN 
GROUP BY INF.NUMINGRES
)

SELECT CASE P.IPTIPODOC WHEN '1'  THEN 'CC'WHEN '2'  THEN 'CE'WHEN '3'  THEN 'TI'WHEN '4'  THEN 'RC'WHEN '5'  THEN 'PA'WHEN '6'  THEN 'AS'WHEN '7'  THEN 'MS'
WHEN '8'  THEN 'NU'WHEN '9'  THEN 'NV'WHEN '10' THEN 'CD'WHEN '11' THEN 'SC'WHEN '12' THEN 'PE' WHEN '13' THEN 'PT'WHEN '14' THEN 'DE'WHEN '15' THEN 'SI'END AS [TIPO IDENTIFICACION],
QX.[IDENTIFICACION],RTRIM(P.IPPRIAPEL) AS [PRIMER APELLIDO], RTRIM(P.IPSEGAPEL) AS [SEGUNDO APELLIDO], RTRIM(P.IPPRINOMB) AS [PRIMER NOMBRE], 
RTRIM(P.IPSEGNOMB) AS [SEGUNDO NOMBRE],CAST(P.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
CASE P.IPSEXOPAC WHEN '1' THEN 'H' WHEN '2' THEN 'M' END AS [SEXO],
QX.[INGRESO],QX.[CUPS],QX.[DESCRIPCION CUPS],IIF(ISNULL(ORD.[FECHA ORDEN/RADICADO],AMB.[FECHA ORDEN/RADICADO]) IS NULL,'NO','SI') [ORDEN CLINICA],
ISNULL(ORD.[FOLIO ORDEN/RADICADO],ISNULL(AMB.[FOLIO ORDEN/RADICADO],QX.[FOLIO QX])) [FOLIO ORDEN/RADICADO],
ISNULL(ORD.[FECHA ORDEN/RADICADO],ISNULL(AMB.[FECHA ORDEN/RADICADO],QX.[FECHA QX])) [FECHA ORDEN/RADICADO],IIF(QX.[FOLIO QX] IS NULL,'NO','SI') [CON INFORME QX],QX.[FOLIO QX],QX.[FECHA QX],
QX.[QX PRINCIPAL],QX.[QX URGENTE],
[ORDEN CARGUE QX],
[ESPECIALIDAD],
--IIF((ORD.[AMBITO] IS NULL AND AMB.[AMBITO] IS NULL), QX.[AMBITO],IIF(ORD.[AMBITO] IS NOT NULL,ORD.[AMBITO],IIF(AMB.[AMBITO] IS NOT NULL,AMB.[AMBITO],QX.[AMBITO]))) [AMBITO],
CASE WHEN RAD.NUMINGRES IS NULL THEN 'HOSPITALARIO' ELSE 'AMBULATORIO' END AS AMBITO,
[SALA QX],
IIF((ISNULL(ORD.[UNIDAD FUNCIONAL],AMB.[UNIDAD FUNCIONAL]) IS NULL AND QX.UFUTIPUNI=19),QX.[UNIDAD INFORME QX],ISNULL(ORD.[UNIDAD FUNCIONAL],AMB.[UNIDAD FUNCIONAL])) [UNIDAD FUNCIONAL SALA],   
QX.[UNIDAD INFORME QX] AS [UNIDAD FUNCIONAL INFORME QX],
QX.[TIPO SERVICIO],
DIG1.CODDIAGNO AS [CODIGO DX PRE OPEERATORIO],
 DIG1.NOMDIAGNO AS [DX PRE OPERATORIO],
 DIG2.CODDIAGNO AS [CODIGO DX POS OPERATORIO],
 DIG2.NOMDIAGNO AS [DX POS OPERATORIO],
[FECHA INICIO CIRUGIA],
 QX.[HORA INICIO CIRUGIA],
 QX.[FECHA FINAL CIRUGIA],
 QX.[HORA FINAL CIRUGIA],
 AMB.[TIPO DE ANESTESIA],
 ANE.[HORA INICIO ANESTESIA],
 ANE.[HORA FIN ANESTESIA],
DEP.depcodigo AS [CODIGO DEPARTAMENTO], DEP.nomdepart AS [NOMBRE DEPARTAMENTO RESIDENCIA], MUN.MUNCODIGO [CODIGO MUNICIPIO RESIDENCIA], 
MUN.MUNNOMBRE AS [NOMBRE MUNICIPIO RESIDENCIA],QX.[CODIGO ENTIDAD],QX.[NOMBRE ENTIDAD],QX.[TIPO HERIDA],
QX.IAUTORIZA AS [NUMERO AUTORIZACION] 
FROM CTE_INFORME_QX QX
INNER JOIN DBO.INPACIENT AS P ON P.IPCODPACI=QX.[IDENTIFICACION]
LEFT JOIN CTE_ORDENES_HOSPITALARIAS ORD ON QX.[INGRESO]=ORD.[INGRESO] AND QX.[CUPS]=ORD.[CUPS] AND QX.[FECHA QX]>=ORD.[FECHA ORDEN/RADICADO]
LEFT JOIN CTE_ORDENES_AMBULATORIAS AS AMB ON QX.[IDENTIFICACION]=AMB.[IDENTIFICACION]AND QX.[CUPS]=AMB.[CUPS] AND QX.[FECHA QX] >=AMB.[FECHA ORDEN/RADICADO]
LEFT JOIN INUBICACI AS UBI WITH (NOLOCK) ON P.AUUBICACI = UBI.AUUBICACI
LEFT JOIN INMUNICIP AS MUN WITH (NOLOCK) ON UBI.DEPMUNCOD = MUN.DEPMUNCOD
LEFT JOIN INDEPARTA AS DEP WITH (NOLOCK) ON DEP.depcodigo = MUN.DEPCODIGO
LEFT JOIN CTE_RADICACION RAD ON QX.INGRESO=RAD.NUMINGRES
LEFT JOIN CTE_ANESTESIA ANE ON QX.NUMINGRES=ANE.NUMINGRES --AND QX.CODSERIPS=ANE.CUPS
INNER JOIN dbo.INDIAGNOS DIG1 ON DIG1.CODDIAGNO=QX.CODDIAPRE 
 INNER JOIN dbo.INDIAGNOS DIG2 ON DIG2.CODDIAGNO=QX.CODDIAPOS 
 --where QX.[INGRESO]='173908'
ORDER BY QX.[INGRESO],QX.[FOLIO QX],[ORDEN CARGUE QX] 


