-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_PARAMETROS_INSUMOS_PRODUCTO
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE PROCEDURE [Report].[IND_SP_V2_EHR_PARAMETROS_INSUMOS_PRODUCTO] 

AS

SELECT PT.Name 'TIPO INSUMO',ISS.Code 'CODIGO INSUMO' ,ISS.SupplieName 'DESCRIPCION INSUMO',CASE ISS.PBSProduct WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END 'TECNOLOGIA PBS',
CASE ISS.OsteosynthesisMaterial WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END 'MATERIOA OSTEOSINTESIS',
CASE ISS.Consumption WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END 'CONSUMIBLE',
IPP.Code 'CODIGO PRODUCTO' ,IPP.Name 'DESCRIPCION PRODUCTO' ,IPP.CodeAlternative 'CODIGO ALTERNATIVO 1' ,IPP.CodeAlternativeTwo 'CODIGO ALTERNATIVO 2',
PG.Code 'CODIGO GRUPO INVENTARIO' ,RTRIM(PG.Name) 'GRUPO INVENTARIO',
PSG.Code 'CODIGO SUB GRUPO INVENTARIO',RTRIM(PSG.Name) 'SUB GRUPO INVENTARIO',BG.Code 'CODIGO GRUPO FACTURACION', RTRIM(BG.Name) 'GRUPO FACTURACION',
CASE IPP.HandlesHealthRegistration WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END 'REGISTRO INVIMA' ,IPP.HealthRegistration 'NRO REGISTRO INVIMA' ,
CAST(IPP.ExpirationDate AS DATE) 'VENCIMIENTO INVIMA',IPP.FinalProductCost 'ULTIMO COSTO COMPRA' ,IPP.ProductCost 'COSTO',IPP.SellingPrice 'PRECIO VENTA' ,
CASE IPP.Status  WHEN 1 THEN 'ACTIVO' WHEN 0 THEN 'INCATIVO' END 'ESTADO PRODUCTO'
FROM Inventory .InventoryProduct IPP WITH (NOLOCK)
INNER JOIN Inventory .ProductType AS PT  WITH (NOLOCK) ON PT.Id =IPP.ProductTypeId 
LEFT JOIN Inventory .InventorySupplie AS ISS WITH (NOLOCK) ON ISS.Id =IPP.SupplieId 
LEFT JOIN Inventory .ProductGroup AS PG WITH (NOLOCK) ON PG.Id =IPP.ProductGroupId 
LEFT JOIN Inventory .ProductSubGroup  AS PSG WITH (NOLOCK) ON IPP.ProductSubGroupId =PSG.Id 
LEFT JOIN Billing .BillingGroup AS BG WITH (NOLOCK) ON BG.Id  =IPP.BillingGroupId 
WHERE PT.Class <>2