-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_V2_SP_FAC_REPORTE_URGENCIAS_PENDIENTE_POR_RECONOCER
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE PROCEDURE [Report].[IND_V2_SP_FAC_REPORTE_URGENCIAS_PENDIENTE_POR_RECONOCER]
AS
SELECT 'HEMOCOMPONENTES' 'TIPO', cast(HOS.NUMINGRES as numeric)'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION]  ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'URGENCIAS' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA]  ,YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',ISNULL(HOS.CANSERIPS*HEM.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_HEMOCOMPONENTES_POR_RECONOCER_URG HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_HEMOCOMPONENTES_POR_RECONOCER_VALORIZADO AS HEM ON HEM.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'IMAGENES' 'TIPO', cast(HOS.NUMINGRES as numeric) 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'URGENCIAS' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA]  ,YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',ISNULL(HOS.CANSERIPS*IMG.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_IMAGENES_POR_RECONOCER_URG HOS
LEFT JOIN  [Report].[View_V2_FAC_REPORTE_IMAGENES_POR_RECONOCER_VALORIZADO] AS IMG ON IMG.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'LABORATORIOS' 'TIPO', cast(HOS.NUMINGRES as numeric) 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'URGENCIAS' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA],YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',ISNULL(HOS.CANSERIPS*LAB.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_LABORATORIOS_POR_RECONOCER_URG HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_LABORATORIOS_POR_RECONOCER_VALORIZADO AS LAB ON LAB.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'PATOLOGIAS' 'TIPO', cast(HOS.NUMINGRES as numeric) 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'URGENCIAS' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA],YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',ISNULL(HOS.CANSERIPS*PAT.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_PATOLOGIAS_POR_RECONOCER_URG HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_PATOLOGIAS_POR_RECONOCER_VALORIZADO AS PAT ON PAT.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'TERAPIAS' 'TIPO', cast(HOS.NUMINGRES as numeric) 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'URGENCIAS' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA],YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',ISNULL(HOS.CANSERIPS*TER.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_TERAPIAS_POR_RECONOCER_URG HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_PROCEDIMIENTOS_NO_QX_POR_RECONOCER_VALORIZADO AS TER ON TER.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'INTERCONSULTAS' 'TIPO', cast(HOS.NUMINGRES as numeric) 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'URGENCIAS' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA],YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',ISNULL(HOS.CANSERIPS*INT.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_INTERCONSULTAS_POR_RECONOCER_URG HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_INTERCONSULTAS_POR_RECONOCER_VALORIZADO AS INT ON INT.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'PROCEDIMIENTOS_NO_QX' 'TIPO', cast(HOS.NUMINGRES as numeric) 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'URGENCIAS' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA],YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',ISNULL(HOS.CANSERIPS*NOQX.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_PROCEDIMIENTOS_NO_QX_POR_RECONOCER_URG HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_PROCEDIMIENTOS_NO_QX_POR_RECONOCER_VALORIZADO AS NOQX ON NOQX.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'GASES' 'TIPO', cast(HOS.NUMINGRES as numeric) 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION]  ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA]  ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'URGENCIAS' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA],YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',ISNULL(HOS.CANSERIPS*GAS.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_GASES_POR_RECONOCER_URG HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_GASES_POR_RECONOCER_VALORIZADO AS GAS ON GAS.[CUPS]=HOS.CODSERIPS
UNION ALL
SELECT 'VALORACIONES' 'TIPO', cast(HOS.NUMINGRES as numeric) 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE' ,HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.[CANTIDAD ORDENADA],HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL',HOS.NUMCAMHOS 'CAMA' ,HOS.FECEGRESO 'FECHA EGRESO',
'URGENCIAS' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA],YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',0 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_VALORACIONES_POR_RECONOCER_URG HOS
UNION ALL
SELECT 'ESTANCIAS' 'TIPO', cast(HOS.NUMINGRES as numeric) 'INGRESO' ,HOS.IESTADOIN 'ESTADO',CAST(HOS.[FECHA INGRESO] AS date) [FECHA INGRESO],HOS.ENTIDAD ,HOS.[GRUPO ATENCION] ,HOS.IPCODPACI 'IDENTIFICACION' ,HOS.IPNOMCOMP 'NOMBRE',HOS.CODSERIPS 'CUPS' ,HOS.DESSERIPS 'DESCRIPCION CUPS',
HOS.CANSERIPS 'CANTIDAD ORDENADA' ,HOS.CANSERIPS 'CANTIDAD PENDIENTE DE CARGUE',HOS.UFUDESCRI 'UNIDAD FUNCIONAL' ,HOS.NUMCAMHOS 'CAMA',HOS.FECEGRESO 'FECHA EGRESO',   
'URGENCIAS' 'AMBITO',HOS.[CUPS CARGADO] , HOS.[CANTIDAD CARGADA] ,YEAR(HOS.[FECHA INGRESO]) 'AÑO INGRESO' ,month(HOS.[FECHA INGRESO]) 'MES INGRESO',ISNULL(HOS.CANSERIPS*EST.[VALOR UNITARIO],0) 'VALOR PROMEDIO'
FROM REPORT.View_V2_FAC_REPORTE_ESTANCIAS_POR_RECONOCER_URG HOS
LEFT JOIN REPORT.View_V2_FAC_REPORTE_ESTANCIAS_POR_RECONOCER_VALORIZADO AS EST ON EST.[CUPS]=HOS.CODSERIPS