-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_CAMAS_CONFIGURACION
-- Extracted by Fabric SQL Extractor SPN v3.9.0





CREATE PROCEDURE [Report].[IND_SP_V2_EHR_CAMAS_CONFIGURACION]
AS

SELECT  UNI.UFUDESCRI 'UNIDAD FUNCIONAL' , NUMCAMHOS 'CODIGO CAMA', DESCCAMAS 'DESCRIPCION CAMA',   
CASE CODCLAHAB WHEN 1  THEN 'Sala de Observacion' WHEN 2 THEN 'Sala de Procedimientos' WHEN 3 THEN 'Sala de Recuperacion' WHEN 4 THEN 'Habitacion 1 Cama' WHEN 5 THEN 'Habitacion 2 Camas'
WHEN 6 THEN 'Habitacion 3 Camas' WHEN 7 THEN 'Habitacion 4 Camas' WHEN 8 THEN 'Suite' WHEN 9 THEN 'Habitacion Especial' WHEN 10 THEN 'UCI' WHEN 11 THEN 'Otro' END 'CLASE HABITACION',
CASE CODCLACAM WHEN 1 THEN 'Observacion Urgencias' WHEN 2 THEN 'Recuperacion Post-Quirurgico' WHEN 3 THEN 'Hospitalaria' WHEN 4 THEN 'Cuna de Observación' END 'CLASE CAMA',
CASE ESTADCAMA WHEN 1 THEN 'Libre' WHEN 2 THEN 'Asignada' WHEN 3 THEN 'Inactiva' WHEN 4 THEN 'En Mantenimiento' WHEN 5 THEN 'Aislamiento' WHEN 6 THEN 'Reservada' WHEN 7
THEN 'Reservada Confirmada' END 'ESTADO',CASE CAMVIRTUA WHEN 0 THEN 'NO' ELSE 'SI' END 'CAMA VIRTUAL',CASE CODAISLAM WHEN 1 THEN 'Aerosol' WHEN 2 THEN 'Contacto'
WHEN 3 THEN 'Estandar' WHEN 4 THEN 'Gota' WHEN 5 THEN 'Protector' ELSE 'Ninguno' END 'TIPO AISLAMIENTO'
FROM            dbo.CHCAMASHO AS CAM
INNER JOIN DBO.ADCENATEN AS ATE ON ATE.CODCENATE= CAM.CODCENATE
INNER JOIN DBO.INUNIFUNC AS UNI ON UNI.UFUCODIGO=CAM.UFUCODIGO
ORDER BY CAM.UFUCODIGO
