-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_ERP_PRODUCTIVIDAD_PGP_HISTORICO
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE PROCEDURE [Report].[IND_SP_ERP_PRODUCTIVIDAD_PGP_HISTORICO]
 @ANO AS INT,
 @MES AS INT 
AS

--DECLARE @ANO AS INT = 2023;
--DECLARE @MES AS INT = 12;



WITH CTE_REGISTROS_SERVICIOS
AS
(
SELECT DISTINCT I.ID,I.AdmissionNumber,I.PatientCode,I.HealthAdministratorId,I.ThirdPartyId,I.CareGroupId,I.InvoiceNumber,I.InvoicedDate,
CAST(I.TotalInvoice AS NUMERIC) TotalInvoice
FROM
Billing.Invoice I 
WHERE I.DocumentType = 5 AND I.Status =1 AND YEAR(I.InvoiceDate)=@ANO AND MONTH(I.InvoiceDate)=@MES
),

CTE_ALTA_MEDICA_REGISTROS_SERVICIOS
AS
(
SELECT
EGR.NUMINGRES 'INGRESO',
EGR.IPCODPACI 'IDENTIFICACION',
EGR.FECALTPAC 'FECHA ALTA MEDICA'
FROM
HCREGEGRE EGR 
INNER JOIN (SELECT EGR.NUMINGRES 'INGRESO' ,EGR.IPCODPACI 'IDENTIFICACION' ,MAX(EGR.FECALTPAC) 'FECHA ALTA MEDICA'
FROM DBO.HCREGEGRE EGR  INNER JOIN CTE_REGISTROS_SERVICIOS AS ING ON EGR.NUMINGRES=ING.AdmissionNumber
GROUP BY EGR.NUMINGRES,EGR.IPCODPACI) AS G ON G.INGRESO=EGR.NUMINGRES AND G.[FECHA ALTA MEDICA]=EGR.FECALTPAC
)

SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
'REGISTROS DE SERVICIOS' [TIPO DOCUMENTO],
'' [CODIGO COMPROBANTE],
'' [COMPROBANTE CONTABLE],
'' [CONSECUTIVO CONTABLE],
ISNULL(ids.Id ,sod.Id) IDDETALLE,
'FACTURADO' AS ESTADO,
YEAR(UNI.InvoicedDate) AS AÑO,
MONTH(UNI.InvoicedDate) AS MES,
DAY(UNI.InvoicedDate) AS DIA,
TP.Nit AS NIT,
TP.Name AS ENTIDAD,
CG.Code AS [CODIGO GRUPO ATENCION],
CG.Name AS [GRUPO ATENCION],
I.PatientCode AS IDENTIFICACION,
RTRIM(PAC.IPNOMCOMP) AS PACIENTE,
I.AdmissionNumber AS INGRESO,
CAST(ING.IFECHAING AS DATE) AS [FECHA INGRESO],
CASE WHEN ING.TIPOINGRE =1 THEN CAST(ING.IFECHAING AS DATE) ELSE CAST(ALT.[FECHA ALTA MEDICA] AS DATE) END AS [FECHA EGRESO],
I.InvoiceNumber AS [NRO FACTURA],
CAST(I.InvoiceDate AS DATE) AS [FECHA FACTURA],
I.TotalInvoice AS [TOTAL FACTURA],
I.TotalPatientSalesPrice 'VALOR COPAGO/CUOTA FACTURA',------*****SE ADICIONO*******--------
CASE SOD.RecordType WHEN 1 THEN 'SERVICIOS'
WHEN 2 THEN 'PRODUCTOS' END AS [TIPO REGISTRO],
CASE CUPS.ServiceType WHEN 1 then 'Laboratorios'
WHEN 2 then 'Patologias'
WHEN 3 then 'Imagenes Diagnosticas'
WHEN 4 then 'Procedimeintos no Qx'
WHEN 5 then 'Procedimientos Qx'
WHEN 6 then 'Interconsultas'
WHEN 7 then 'Ninguno'
WHEN 8 then 'Consulta Externa' ELSE 'Otro' END AS [TIPO SERVICIO],
CASE SOD.Presentation WHEN 1 THEN 'NO QUIRURGICO'
WHEN 2 THEN 'QUIRURGICO'
WHEN 3 THEN 'PAQUETE' ELSE 'NO QUIRURGICO' END AS PRESENTACION,
ISNULL (PG.Code, BCT.Code) 'CODIGO CONCEPTO/GRUPO',
ISNULL (PG.Name, BCT.Name) 'NOMBRE CONCEPTO/GRUPO',
ICT.Name 'CATERGORIA FACTURA',
CAST(SOD.ServiceDate AS DATE) AS [FECHA SERVICIO],
ISNULL(CUPS.Code,IPR.Code) AS [CUPS/PRODUCTO],
ISNULL(CUPS.Description,IPR.Description ) AS DESCRIPCION,
ISNULL(IPS.Code, 'N/A') AS 'CODIGO DETALLE QX', SUBSTRING(ISNULL(RTRIM(IPS.Name), 'N/A'),1,60) AS 'DESCRIPCION DETALLE QX',
CD.Name 'DECRIPCION RELACIONADA',ISNULL(IDS.InvoicedQuantity,ID.InvoicedQuantity) 'CANTIDAD',
ISNULL(IDS.RateManualSalePrice,SOD.RateManualSalePrice) 'VALOR SERVICIO',SOD.CostValue 'COSTO SERVICIO',
ISNULL(IDS.RateManualSalePrice,ID.TotalSalesPrice) 'VALOR UNITARIO',
GLI.Name 'TARIFA IVA',
SOD.TaxValue 'VALOR IVA',
ID.SubTotalPatientSalesPrice 'VALOR COPAGO/CUOTA', ------*****SE ADICIONO*******--------
ISNULL(IDS.TotalSalesPrice,ID.GrandTotalSalesPrice+Id.ThirdPartyDiscount) 'VALOR TOTAL',
CASE SOD.IsPackage WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'ES PAQUETE',CASE SOD.Packaging WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'INCLUIDO EN PAQUETE',
CUPSP.Code 'CODIGO PAQUETE',CUPSP.Description 'NOMBRE PAQUETE',CASE SOD.SettlementType WHEN 1 THEN 'Por manual de tarifas' WHEN 2 THEN '% otro servicio cargado'
WHEN 3 THEN '100% incluido en otro servicio (No se cobra)' when 4 then '% del mismo servicio' else 'otro' end 'TIPO LIQUIDACION', CUPSI.Code 'CUPS QUE INCLUYE',
CUPSI.Description 'NOMBRE CUPS QUE INCLUYE', ISNULL(IDS.PerformsHealthProfessionalCode,ISNULL(MED.CODPROSAL,ISNULL(TPT.Nit,SOD.PerformsHealthProfessionalCode))) 'IDENTIFICACION PROFESIONAL',
RTRIM(ISNULL(MEDQX.NOMMEDICO,ISNULL(MED.NOMMEDICO,TPT.Name))) 'PROFESIONAL', ISNULL(ESPQX.DESESPECI,ESPMED.DESESPECI) 'ESPECIALIDAD',
FU.Code 'CODIGO UNIDAD SOLICITO' ,FU.Name 'UNIDAD SOLICITO',
COST.CODE 'CODIGO CC CONTABILIZO',
COST.Name 'CENTRO COSTO CONTABILIZO',
MA.Number 'NRO CUENTA CONTABILIZO',
MA.Name 'CUENTA CONTABILIZO',NULL 'FECHA ANULACION',
MFC.ContractName 'AGREMIACION',
SU.NOMUSUARI 'USUARIO',
ISNULL(SUSO.NOMUSUARI,'INDIGOBOT') 'USUARIO CREO ORDEN',
CAST(SO.CreationDate AS DATE) 'FECHA ORDEN',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM
Billing.Invoice AS I 
INNER JOIN CTE_REGISTROS_SERVICIOS AS UNI ON UNI.ID =I.Id
INNER JOIN Billing.InvoiceDetail AS ID  ON ID.InvoiceId =I.Id
INNER JOIN Billing.ServiceOrderDetail AS SOD  ON SOD.Id =ID.ServiceOrderDetailId
INNER JOIN Billing .ServiceOrder AS SO  ON SO.Id =SOD.ServiceOrderId
INNER JOIN Payroll.FunctionalUnit AS FU  ON FU.Id = SOD.PerformsFunctionalUnitId
INNER JOIN Payroll.CostCenter AS COST  ON COST.Id =SOD.CostCenterId
INNER JOIN dbo.ADINGRESO AS ING ON ING.NUMINGRES =I.AdmissionNumber
INNER JOIN Common .ThirdParty AS TP  ON TP.Id =I.ThirdPartyId
INNER JOIN Contract .CareGroup AS CG  ON CG.Id =I.CareGroupId
INNER JOIN dbo.INPACIENT AS PAC  ON PAC.IPCODPACI =I.PatientCode
LEFT JOIN Contract.CUPSEntity AS CUPS  ON CUPS.Id = SOD.CUPSEntityId
LEFT JOIN Billing.BillingConcept AS BCT  ON CUPS.BillingConceptId = BCT.Id
LEFT JOIN Inventory.InventoryProduct AS IPR  ON IPR.Id = SOD.ProductId
LEFT JOIN GeneralLedger.GeneralLedgerIVA GLI  ON GLI.Id = IPR.IVAId
LEFT JOIN Inventory.ProductGroup PG  ON PG.Id = IPR.ProductGroupId
LEFT JOIN Contract .CUPSEntityContractDescriptions AS DESCR  ON DESCR.Id =SOD.CUPSEntityContractDescriptionId AND SOD.CUPSEntityId=DESCR.CUPSEntityId
LEFT JOIN Contract .ContractDescriptions AS CD  ON CD.ID=DESCR.ContractDescriptionId
LEFT JOIN Billing .ServiceOrderDetail AS SODP  ON SODP.Id =SOD.PackageServiceOrderDetailId
LEFT JOIN Contract.CUPSEntity AS CUPSP  ON CUPSP.Id = SODP.CUPSEntityId
LEFT JOIN Billing .ServiceOrderDetail AS SODI  ON SODI.Id =SOD.IncludeServiceOrderDetailId
LEFT JOIN Contract.CUPSEntity AS CUPSI  ON CUPSI.Id = SODI.CUPSEntityId
LEFT JOIN dbo.INPROFSAL AS MED  ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
LEFT JOIN dbo.INESPECIA AS ESPMED  ON ESPMED.CODESPECI = SOD.PerformsProfessionalSpecialty
LEFT JOIN Common.ThirdParty AS TPT  ON TPT.Id =SOD.PerformsHealthProfessionalThirdPartyId
LEFT JOIN Billing .InvoiceDetailSurgical AS IDS  ON IDS.InvoiceDetailId =ID.Id AND IDS.OnlyMedicalFees = '0'
LEFT JOIN Contract .IPSService AS IPS  ON IPS.Id =IDS.IPSServiceId
LEFT JOIN dbo.INPROFSAL AS MEDQX  ON MEDQX.CODPROSAL = IDS.PerformsHealthProfessionalCode
LEFT JOIN dbo.INESPECIA AS ESPQX  ON ESPQX.CODESPECI = MEDQX.CODESPEC1
LEFT JOIN CTE_ALTA_MEDICA_REGISTROS_SERVICIOS AS ALT ON ALT.INGRESO =I.AdmissionNumber
LEFT JOIN GeneralLedger .MainAccounts AS MA  ON MA.Id =ISNULL(IDS.IncomeMainAccountId,SOD.IncomeMainAccountId)
LEFT JOIN MedicalFees.HealthProfessionalContract HPC  ON HPC.HealthProfessionalCode = ISNULL(IDS.PerformsHealthProfessionalCode,ISNULL(MED.CODPROSAL,TPT.Nit)) AND HPC.LiquidateDefault = 1
LEFT JOIN MedicalFees.MedicalFeesContract MFC  ON MFC.Id = HPC.MedicalFeesContractId
LEFT JOIN DBO.SEGusuaru SU  ON SU.CODUSUARI = i.InvoicedUser
LEFT JOIN DBO.SEGusuaru SUSO  ON SUSO.CODUSUARI = SO.CreationUser
LEFT JOIN Billing.InvoiceCategories ICT  ON ICT.Id = I.InvoiceCategoryId
where cg.LiquidationType In (2,5)

UNION ALL

------*** QUEDO PENDIENTE DE FACTURAR ***------
SELECT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
'PENDIENTE DE FACTURAR' as 'TIPO DOCUMENTO',
0 as 'CODIGO COMPROBANTE',
NULL as 'COMPROBANTE CONTABLE',
0 as 'CONSECUTIVO CONTABLE',
isnull(SODS.Id ,sod.Id) IDDETALLE,'RECONOCIDOS SIN FACTURAR' AS 'ESTADO',
@ANO 'AÑO',@MES 'MES', 1 'DIA',
TP.Nit 'NIT',TP.Name 'ENTIDAD',CG.Code 'CODIGO GRUPO ATENCION',
CG.Name 'GRUPO ATENCION',SO.PatientCode 'IDENTIFICACION',
RTRIM(PAC.IPNOMCOMP) 'PACIENTE',SO.AdmissionNumber 'INGRESO',
CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
G.[FECHA ALTA MEDICA] 'FECHA EGRESO',
'N/A' 'NRO FACTURA',NULL 'FECHA FACTURA',
'0' 'TOTAL FACTURA',
0 'VALOR COPAGO/CUOTA FACTURA',------*****SE ADICIONO*******--------
CASE SOD.RecordType WHEN 1 THEN 'SERVICIOS' WHEN 2 THEN 'PRODUCTOS' END 'TIPO REGISTRO',
CASE CUPS.ServiceType WHEN 1 then 'Laboratorios'WHEN 2 then 'Patologias'WHEN 3 then 'Imagenes Diagnosticas'WHEN 4 then 'Procedimeintos no Qx'WHEN 5 then 'Procedimientos Qx'
WHEN 6 then 'Interconsultas'WHEN 7 then 'Ninguno'WHEN 8 then 'Consulta Externa' ELSE 'Otro' end 'TIPO SERVICIO',
CASE SOD.Presentation WHEN 1 THEN 'NO QUIRURGICO' WHEN 2 THEN 'QUIRURGICO' WHEN 3 THEN 'PAQUETE' ELSE 'NO QUIRURGICO' END 'PRESENTACION',
'' as 'CODIGO CONCEPTO/GRUPO', '' as 'NOMBRE CONCEPTO/GRUPO', '' as 'CATERGORIA FACTURA',
CAST(SOD.ServiceDate AS DATE) 'FECHA SERVICIO',
ISNULL(CUPS.Code,IPR.Code)'CUPS/PRODUCTO',ISNULL(CUPS.Description,IPR.Description )'DESCRIPCION',ISNULL(IPS.Code, 'N/A') AS 'CODIGO DETALLE QX', SUBSTRING(ISNULL(RTRIM(IPS.Name),'N/A'),1,60) AS 'DESCRIPCION DETALLE QX',
CD.Name 'DECRIPCION RELACIONADA', ISNULL(SODS.InvoicedQuantity,SOD.InvoicedQuantity) 'CANTIDAD',ISNULL(SODS.RateManualSalePrice,SOD.RateManualSalePrice) 'VALOR SERVICIO',SOD.CostValue 'COSTO SERVICIO',
ISNULL(SODS.RateManualSalePrice,SOD.TotalSalesPrice) 'VALOR UNITARIO',
NULL as 'TARIFA IVA', 0 as 'VALOR IVA',
0 'VALOR COPAGO/CUOTA', ------*****SE ADICIONO*******--------
ISNULL(SODS.TotalSalesPrice,SOD.GrandTotalSalesPrice) 'VALOR TOTAL',
CASE SOD.IsPackage WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'ES PAQUETE',CASE SOD.Packaging WHEN 0 THEN 'NO' WHEN 1 THEN 'SI' END 'INCLUIDO EN PAQUETE',
CUPSP.Code 'CODIGO PAQUETE',CUPSP.Description 'NOMBRE PAQUETE',CASE SOD.SettlementType WHEN 1 THEN 'Por manual de tarifas' WHEN 2 THEN '% otro servicio cargado'
WHEN 3 THEN '100% incluido en otro servicio (No se cobra)' when 4 then '% del mismo servicio' else 'otro' end 'TIPO LIQUIDACION', CUPSI.Code 'CUPS QUE INCLUYE',
CUPSI.Description 'NOMBRE CUPS QUE INCLUYE',ISNULL(SODS.PerformsHealthProfessionalCode,ISNULL(MED.CODPROSAL,TPT.Nit))'IDENTIFICACION PROFESIONAL',
RTRIM(ISNULL(MEDQX.NOMMEDICO,ISNULL(MED.NOMMEDICO,TPT.Name))) 'PROFESIONAL',ISNULL(ESPQX.DESESPECI,ESPMED.DESESPECI) 'ESPECIALIDAD',
FU.Code 'CODIGO UNIDAD SOLICITO' ,
FU.Name 'UNIDAD SOLICITO',
COST.CODE 'CODIGO CC CONTABILIZO',
COST.Name 'CENTRO COSTO CONTABILIZO',
MA.Number 'NRO CUENTA CONTABILIZO',
MA.Name 'CUENTA CONTABILIZO',
NULL 'FECHA ANULACION',
MFC.ContractName 'AGREMIACION',
SU.NOMUSUARI 'USUARIO',
ISNULL(SUSO.NOMUSUARI,'INDIGOBOT') 'USUARIO CREO ORDEN',
CAST(SO.CreationDate AS DATE) 'FECHA ORDEN',
-- CASE ING.TIPOINGRE WHEN 1 THEN 'AMBULATORIO' WHEN 2 THEN 'HOSPITALARIO' END [TIPO INGRESO],
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM Contract.CareGroup cg 
INNER JOIN Billing.RevenueControlDetail rcd  ON cg.Id = rcd.CareGroupId
INNER JOIN Billing.RevenueControl rc on rc.Id = rcd.RevenueControlId
INNER JOIN Billing.ServiceOrderDetailDistribution sodd  on sodd.RevenueControlDetailId = rcd.Id
INNER JOIN Billing.ServiceOrderDetail sod  on sodd.ServiceOrderDetailId = sod.Id --AND YEAR(SOD.ServiceDate)=YEAR(GETDATE()) AND MONTH(SOD.ServiceDate)=MONTH(GETDATE())
INNER JOIN Billing.ServiceOrder AS SO  ON SO.Id =SOD.ServiceOrderId
INNER JOIN Payroll.FunctionalUnit fu  on fu.Id = sod.PerformsFunctionalUnitId
INNER JOIN Common .ThirdParty AS TP  ON TP.Id =RCD.ThirdPartyId
INNER JOIN DBO.INPACIENT AS PAC  ON PAC.IPCODPACI =SO.PatientCode
INNER JOIN DBO.ADINGRESO AS ING  ON ING.NUMINGRES =RC.AdmissionNumber
INNER JOIN Payroll.CostCenter AS COST  ON COST.Id =SOD.CostCenterId
LEFT JOIN Contract.CUPSEntity CUPS  on sod.CUPSEntityId = CUPS.Id
LEFT JOIN Billing.BillingConcept bc  on CUPS.BillingConceptId = bc.Id
LEFT JOIN Inventory.InventoryProduct ipr  on sod.ProductId = ipr.Id
LEFT JOIN Inventory.ProductGroup pg  ON ipr.ProductGroupId = pg.Id
LEFT JOIN Contract .CUPSEntityContractDescriptions AS DESCR  ON DESCR.Id =SOD.CUPSEntityContractDescriptionId AND SOD.CUPSEntityId=DESCR.CUPSEntityId
LEFT JOIN Contract .ContractDescriptions AS CD  ON CD.ID=DESCR.ContractDescriptionId
LEFT JOIN Billing.ServiceOrderDetailSurgical AS SODS  ON SODS.ServiceOrderDetailId =SOD.Id AND SODS.OnlyMedicalFees = '0' AND SODS.SurchargeApply <>1
LEFT JOIN Contract .IPSService AS IPS  ON IPS.Id =SODS.IPSServiceId
LEFT JOIN Billing .ServiceOrderDetail AS SODP  ON SODP.Id =SOD.PackageServiceOrderDetailId
LEFT JOIN Contract.CUPSEntity AS CUPSP  ON CUPSP.Id = SODP.CUPSEntityId
LEFT JOIN Billing .ServiceOrderDetail AS SODI  ON SODI.Id =SOD.IncludeServiceOrderDetailId
LEFT JOIN Contract.CUPSEntity AS CUPSI  ON CUPSI.Id = SODI.CUPSEntityId
LEFT JOIN dbo.INPROFSAL AS MED  ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
LEFT JOIN dbo.INESPECIA AS ESPMED  ON ESPMED.CODESPECI = SOD.PerformsProfessionalSpecialty
LEFT JOIN Common.ThirdParty AS TPT  ON TPT.Id =SOD.PerformsHealthProfessionalThirdPartyId
LEFT JOIN dbo.INPROFSAL AS MEDQX  ON MEDQX.CODPROSAL = SODS.PerformsHealthProfessionalCode
LEFT JOIN dbo.INESPECIA AS ESPQX  ON ESPQX.CODESPECI = MEDQX.CODESPEC1
LEFT JOIN GeneralLedger .MainAccounts AS MA  ON MA.Id =ISNULL(SODS.IncomeMainAccountId,SOD.IncomeMainAccountId)
LEFT JOIN MedicalFees.HealthProfessionalContract HPC  ON HPC.HealthProfessionalCode = ISNULL(MED.CODPROSAL,ISNULL(TPT.Nit,SOD.PerformsHealthProfessionalCode)) AND HPC.LiquidateDefault = 1
LEFT JOIN MedicalFees.MedicalFeesContract MFC  ON MFC.Id = HPC.MedicalFeesContractId
LEFT JOIN DBO.SEGusuaru SU  ON SU.CODUSUARI = ING.CODUSUCRE
LEFT JOIN DBO.SEGusuaru SUSO  ON SUSO.CODUSUARI = SO.CreationUser
LEFT JOIN
(SELECT
EGR.NUMINGRES 'INGRESO',
EGR.IPCODPACI 'IDENTIFICACION',
EGR.FECALTPAC 'FECHA ALTA MEDICA'
FROM
HCREGEGRE EGR 
INNER JOIN (SELECT EGR.NUMINGRES 'INGRESO' ,EGR.IPCODPACI 'IDENTIFICACION' ,MAX(EGR.FECALTPAC) 'FECHA ALTA MEDICA'
FROM DBO.HCREGEGRE EGR 
GROUP BY EGR.NUMINGRES,EGR.IPCODPACI) AS G ON G.INGRESO=EGR.NUMINGRES AND G.[FECHA ALTA MEDICA]=EGR.FECALTPAC
) as G ON G.INGRESO =SO.AdmissionNumber
WHERE
rcd.Status in (1,3) AND
sod.IsDelete = 0 AND
sod.SettlementType != 3 AND
sod.GrandTotalSalesPrice > 0 AND
cg.LiquidationType In (2,5) and iNG.IESTADOIN IN (' ', 'P')
