-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: IND_SP_V2_EHR_PARAMETROS_INSUMOS
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE PROCEDURE [Report].[IND_SP_V2_EHR_PARAMETROS_INSUMOS] 

AS

SELECT ISS.Code 'CODIGO INSUMO' ,ISS.SupplieName 'DESCRIPCION INSUMO',CASE ISS.PBSProduct WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END 'TECNOLOGIA PBS',
CASE ISS.OsteosynthesisMaterial WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END 'MATERIOA OSTEOSINTESIS',
CASE ISS.Consumption WHEN 1 THEN 'SI' WHEN 0 THEN 'NO' END 'CONSUMIBLE',
CASE ISS.SupplieStatus WHEN 1 THEN 'ACTIVO' WHEN 0 THEN 'INCATIVO' END 'ESTADO INSUMO'
FROM Inventory .InventorySupplie  ISS