-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: SP_GenerateResolucion4003_2008
-- Extracted by Fabric SQL Extractor SPN v3.9.0



--/*******************************************************************************************************************
--Nombre: [Report].[SP_GenerateResolucion4003_2008V2]
--Tipo:Procedimiento Almacenado
--Observacion:Procedimiento almacenado para la resolucion 4003 versión 2, se me jora la velocidad de la consulta en un 98% a la primera verción y
--			se corrigen errores de la primera.
--Profesional: Nilsson Miguel Galindo Lopez
--Fecha:15-09-2022
-----------------------------------------------------------------------------
--Modificaciones
--_____________________________________________________________________________
--Vercion 2
--Persona que modifico:Nilsson Miguel Galindo Lopez
--Fecha: 25-07-2023
--Ovservaciones: Se cambia la logica de los laboratorios.
----------------------------------------
--Vercion 3cre
--Persona que modifico:
--Fecha:
--***********************************************************************************************************************************/


CREATE PROCEDURE [Report].[SP_GenerateResolucion4003_2008]
 @FechaInicial date,
 @FechaFinal date
AS

--declare @FechaInicial date = '2022-07-01';
--declare @FechaFinal date = '2023-07-24';

/************------------PACIENTES CON HISTORIA CLINICA DE REIESGO CARDIO VASCULAR--------------------------------------------------*****************/
WITH CTE_PACIENTES_INFORMES
AS
(
SELECT 
ROW_NUMBER ( )   
OVER (PARTITION BY HIS.IPCODPACI  order by HIS.FECHISPAC DESC) 'NUMERO',
ID,NUMINGRES,NUMEFOLIO,IPCODPACI,FECHISPAC,CODPROSAL,CODESPTRA
FROM DBO.HCHISPACA AS HIS 
WHERE  HIS.IDMODELOHC = '14' AND (CAST(HIS.FECHISPAC AS DATE) BETWEEN  @fechainicial AND @FechaFinal)
),
--select * from PRMODELOHC
/********************------------------DIAGNOSTICOS RELACIONADOS-----------------------------------------------------------*********************/
CTE_DIAGNOSTICO_RELACIONADOS AS
(
select 
ROW_NUMBER ( )   
OVER (PARTITION BY IND.NUMINGRES  order by IND.NUMINGRES,IND.FECDIAGNO) 'NUMERO',
IND.NUMINGRES,
IND.CODDIAGNO,
DG.NOMDIAGNO
from 
INDIAGNOP IND INNER JOIN 
DBO.INDIAGNOS DG ON IND.CODDIAGNO=DG.CODDIAGNO INNER JOIN
CTE_PACIENTES_INFORMES HC ON IND.NUMINGRES=HC.NUMINGRES AND HC.NUMERO=1
WHERE IND.CODDIAPRI!=1
),
------------------------DIAGNOSTICOS PRINCIPALES------------------------------
CTE_DIAGNOSTICOS AS
(
SELECT
ROW_NUMBER ( )   
OVER (PARTITION BY IND.NUMINGRES  order by IND.NUMEFOLIO DESC) 'NUMERO',
IND.NUMINGRES,
IND.CODDIAGNO AS CODDIAGNO1,
DG.NOMDIAGNO AS NOMDIAGNO1,
IND.NUMEFOLIO
from 
INDIAGNOP IND INNER JOIN 
DBO.INDIAGNOS DG ON IND.CODDIAGNO=DG.CODDIAGNO AND IND.CODDIAPRI=1 INNER JOIN
CTE_PACIENTES_INFORMES HC ON IND.NUMINGRES=HC.NUMINGRES AND HC.NUMERO=1
),

/*******-----------------------------------LABORATORIOS SIN INTERFAZ-------------------------------------------********/
CTE_RESULTADOS_EXAMFISICO AS
(
SELECT 
CASE FIS.NOMBRE_VARIABLE WHEN 'Fecha de creatinina' THEN 1 
						 WHEN 'Resultado de creatinina' THEN 2 
						 WHEN 'Fecha de microalbuminuria' THEN 3 
						 WHEN 'Resultado de microalbuminuria' THEN 4
						 WHEN 'Fecha de Glicemia' THEN 5
						 WHEN 'Resultado de glicemia' THEN 6
						 WHEN 'Fecha de hemoglobina glicosilada' THEN 7
						 WHEN 'Resultado de hemoglobina glicosilada' THEN 8
						 WHEN 'Fecha de Colesterol Total' THEN 9
						 WHEN 'Resultado de colesterol total' THEN 10
						 WHEN 'Fecha de trigliceridos' THEN 11
						 WHEN 'Resultado de trigliceridos' THEN 12
						 WHEN 'Fecha de colesterol HDL' THEN 13
						 WHEN 'Resultado de colesterol HDL' THEN 14
						 WHEN 'Fecha de colesterol LDL' THEN 15
						 WHEN 'Resultado de colesterol LDL' THEN 16
						 WHEN 'Fecha de uroanálisis' THEN 17 
						 WHEN 'Resultado de uroanalisis' THEN 18 END AS ID,
FIS.NUMINGRES,FIS.IPCODPACI,FIS.VALOR 
FROM [Report].[TablaExamenFisico] FIS INNER JOIN CTE_PACIENTES_INFORMES HC ON FIS.IDHCHISPACA=HC.ID AND HC.NUMERO=1
where NOMBRE_VARIABLE IN ('Fecha de creatinina','Resultado de creatinina','Fecha de microalbuminuria','Resultado de microalbuminuria','Fecha de Glicemia',
'Resultado de glicemia','Fecha de hemoglobina glicosilada','Resultado de hemoglobina glicosilada','Fecha de Colesterol Total',
'Resultado de colesterol total','Fecha de trigliceridos','Resultado de trigliceridos','Fecha de colesterol HDL',
'Resultado de colesterol HDL','Fecha de colesterol LDL','Resultado de colesterol LDL','Fecha de uroanálisis')
--AND (CAST(FIS.FECHA AS DATE) BETWEEN  @fechainicial AND @FechaFinal)
),
/*****************----------LABORATORIOS CON INTERFAZ----------------*****************************/
CTE_RESULTADOS_INTERFAZ AS
(
select 
A.IPCODPACI,
A.FECRECMUE,
VAL.VALOR,
VAL.ANALITO,
VAL.[AUTO],
CASE A.CODSERIPS WHEN '903895' THEN 1 --CREATININA
				 WHEN '903026' THEN 2 WHEN '903027'THEN 2 WHEN '903028' THEN 2 --MICROALBUMINURIA
				 WHEN '903841' THEN 3 -- GLICEMIA
				 WHEN '903426' THEN 4 WHEN '903427' THEN 4 --GLICOSILADA
				 WHEN '903818' THEN 5 --COLESTEROL
				 WHEN '903868' THEN 6 --TRIGLICERIDOS
				 WHEN '903815' THEN 7 --HDL
				 WHEN '903817' THEN 8 WHEN '903816' THEN 8 --LDL
				 WHEN '907106' THEN 9  --UROANALISIS
				 END AS ID
from 
CTE_PACIENTES_INFORMES HC INNER JOIN
dbo.AMBORDLAB A ON HC.IPCODPACI=A.IPCODPACI AND A.FECRECMUE BETWEEN @FechaInicial AND @FechaFinal INNER JOIN
INTERLABD VAL ON A.AUTO=VAL.AUTOLABOR
WHERE 
A.CODSERIPS IN('903895','903026','903027','903028','903841','903426','903427','903818','903868','903815','903817','903816','907106') AND A.ESTSERIPS!=6 AND 
(VAL.ANALITO LIKE '%CREATININA%'OR VAL.ANALITO LIKE '%MICROALBUMINURIA%' OR VAL.ANALITO LIKE '%GLUCOSA%' OR VAL.ANALITO LIKE '%GLICOSILADA%'OR VAL.ANALITO LIKE '%COLESTEROL%' OR
VAL.ANALITO LIKE '%COLESTEROL%' OR VAL.ANALITO LIKE '%TRIGLICERIDOS%' OR VAL.ANALITO LIKE '%HDL%' OR VAL.ANALITO LIKE '%LDL%' or VAL.ANALITO LIKE '%PH%')
UNION ALL
select
A.IPCODPACI,
A.FECRECMUE,
VAL.VALOR,
VAL.ANALITO,
VAL.[AUTO],
CASE A.CODSERIPS WHEN '903895' THEN 1 --CREATININA
				 WHEN '903026' THEN 2 WHEN '903027'THEN 2 WHEN '903028' THEN 2 --MICROALBUMINURIA
				 WHEN '903841' THEN 3 -- GLICEMIA
				 WHEN '903426' THEN 4 WHEN '903427' THEN 4 --GLICOSILADA
				 WHEN '903818' THEN 5 --COLESTEROL
				 WHEN '903868' THEN 6 --TRIGLICERIDOS
				 WHEN '903815' THEN 7 --HDL
				 WHEN '903817' THEN 8 WHEN '903816' THEN 8 --LDL
				 WHEN '907106' THEN 9  --UROANALISIS
				 END AS ID
FROM
CTE_PACIENTES_INFORMES HC INNER JOIN
dbo.HCORDLABO A ON HC.IPCODPACI=A.IPCODPACI AND A.FECRECMUE BETWEEN @FechaInicial AND @FechaFinal INNER JOIN
INTERLABD VAL ON A.AUTO=VAL.AUTOLABOR
WHERE 
A.CODSERIPS IN('903895','903026','903027','903028','903841','903426','903427','903818','903868','903815','903817','903816','907106') AND A.ESTSERIPS!=6 AND 
(VAL.ANALITO LIKE '%CREATININA%'OR VAL.ANALITO LIKE '%MICROALBUMINURIA%' OR VAL.ANALITO LIKE '%GLUCOSA%' OR VAL.ANALITO LIKE '%GLICOSILADA%'OR VAL.ANALITO LIKE '%COLESTEROL%' OR
VAL.ANALITO LIKE '%COLESTEROL%' OR VAL.ANALITO LIKE '%TRIGLICERIDOS%' OR VAL.ANALITO LIKE '%HDL%' OR VAL.ANALITO LIKE '%LDL%' or VAL.ANALITO LIKE '%PH%')
),
/***************----------------ESCALA FRAMMINGHAM----------------************/
CTE_FRAMMINGHAM
	AS
	(
		SELECT 
	ROW_NUMBER ( )   
		OVER (PARTITION BY FR.NUMINGRES  order by FR.NUMEFOLIO DESC) 'NUMERO',
		FR.NUMINGRES,FR.NUMEFOLIO,
		CASE WHEN FR.RESULTADO<15 THEN 'BAJO'
			 WHEN FR.RESULTADO >=15 AND FR.RESULTADO<20 THEN 'MODERADO'
		     WHEN FR.RESULTADO >=20 AND FR.RESULTADO<30 THEN 'ALTO'
		     WHEN FR.RESULTADO>30 THEN 'MUY ALTO' END 'RIESGO FRAMMINGHAN'
		from HCESCALAS FR
		where TIPOESCALA=6 AND  CAST(FR.FECHAREGISTRO AS DATE) BETWEEN @FechaInicial AND @FechaFinal
		GROUP BY FR.NUMINGRES, FR.RESULTADO,FR.NUMEFOLIO
	),
/**********************------------MODALIDAD-------------------******************/
CTE_MODALIDAD AS
(
SELECT DISTINCT
HC.NUMINGRES,
CASE AGA.MODALIDAD WHEN 0 THEN 'PRESENCIAL'
				   WHEN 1 THEN 'TELECONSULTA' END AS MODALIDAD
FROM 
CTE_PACIENTES_INFORMES HC LEFT JOIN
ADCONCOEX EX ON HC.NUMINGRES=EX.NUMINGRES LEFT JOIN
AGASICITA AGA ON EX.NUMCONCIT=AGA.CODAUTONU 
WHERE AGA.MODALIDAD IS NOT NULL
),
CTE_CONTROL AS
(
SELECT 
ROW_NUMBER ( )   
OVER (PARTITION BY CON.NUMINGRES order by CON.NUMEFOLIO DESC) 'NUMERO',
CON.NUMINGRES,CON.NUMCONTRL,CON.UNICONTRL
FROM dbo.HCDESCOEX CON INNER JOIN CTE_PACIENTES_INFORMES HC ON CON.NUMINGRES=HC.NUMINGRES AND HC.NUMERO=1
)

/**********************------------CONSULTA 4003----------------*****************/

SELECT DISTINCT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
--ROW_NUMBER ( )   
--OVER (PARTITION BY HC.IPCODPACI  order by HC.FECHISPAC DESC) 'NUMERO',
HC.NUMINGRES,
CASE PAC.IPTIPODOC WHEN 1 THEN 'CC'  
				   WHEN 2 THEN 'CE'  
				   WHEN 3 THEN 'TI'  
				   WHEN 4 THEN 'RC'  
				   WHEN 5 THEN 'PA'  
				   WHEN 6 THEN 'AS'  
				   WHEN 7 THEN 'MS'  
				   WHEN 8 THEN 'NU'  
				   WHEN 9 THEN 'CN'  
				   WHEN 10 THEN 'CD'  
				   WHEN 11 THEN 'SC'
				   WHEN 12 THEN 'PE'
				   WHEN 13 THEN 'PT'
				   WHEN 14 THEN 'PD' END AS [TIPO DOCUMENTO],
PAC.IPCODPACI AS IDENTIFICACION,
PAC.IPNOMCOMP AS [NOMBRE COMPLETO],
PAC.IPPRINOMB AS [PRIMER NOMBRE],
PAC.IPSEGNOMB AS [SEGUNDO NOMBRE],
PAC.IPPRIAPEL AS [PRIMER APELLIDO],
PAC.IPSEGAPEL AS [SEGUNDO APELLIDO],
CAST(PAC.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECHISPAC , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS EDAD,
CASE PAC.IPSEXOPAC WHEN 1 THEN 'MASCULINO' WHEN 2 THEN 'FEMENINO' END AS SEXO,
CAST(FIS.PESOPACIE/1000 AS FLOAT) AS PESO,
FIS.TALLAPACI AS TALLA,
MUN.MUNNOMBRE AS MUNICIPIO,
UBI.UBINOMBRE AS BARRIO,
PAC.IPTELEFON AS [TELEFONO FIJO],
PAC.IPTELMOVI AS [TELEFONO MOVIL],
EAPB.HealthEntityCode AS [CODIGO EAPB],
EAPB.Name AS EAPB,
CAST(HC.FECHISPAC AS DATE) AS [FECHA DE ATENCION],
PRO.NOMMEDICO AS [NOMBRE PROFESIONAL],
ESP.DESESPECI AS [ESPECIALIDAD TRATANTE],
DIA.CODDIAGNO1 AS [CIE10 PRINCIPAL],
DIA.NOMDIAGNO1 AS [DIAGNOSTICO PRINCIPAL],
RE.CODDIAGNO AS [CIE10 DIAGNOSTICO RELACIONADO 1],
RE.NOMDIAGNO AS [NOMBRE DIAGNOSTICO RELACIONADO 1],
REL.CODDIAGNO AS [CIE10 DIAGNOSTICO RELACIONADO 2],
REL.NOMDIAGNO AS [NOMBRE DIAGNOSTICO RELACIONADO 2],
'CONSULTA RIESGO CARDIOVASCULAR' AS [TIPO CONSULTA],
FIS.TENARTSIS AS [TENSION SISTOLICA],
FIS.TENARTDIA AS [TENSION DIASTOLICA],
FIS.ESTADIO,
IIF(FIS.TFG='999','',FIS.TFG) TFG, 
FIS.NEOPERABD AS [PERIMETRO ABDOMINAL],
FRA.[RIESGO FRAMMINGHAN],
CONVERT(varchar, TRY_CAST (ISNULL(CONVERT(VARCHAR(10),FAZ1.FECRECMUE,111),LAB1.VALOR) as date), 23) AS [FECHA DE CREATININA],
ISNULL(CONVERT(VARCHAR(MAX),FAZ1.VALOR),LAB2.VALOR) AS [RESULTADO DE CREATININA],
CONVERT(varchar, TRY_CAST (ISNULL(CONVERT(VARCHAR(10),FAZ2.FECRECMUE,111),CONVERT(VARCHAR(10),LAB3.VALOR,111)) as date), 23) AS [FECHA DE MICROALBUMINURIA],
ISNULL(CONVERT(VARCHAR(MAX),FAZ2.VALOR),LAB4.VALOR) AS [RESULTADO DE MICROALBUMINURIA],
CONVERT(varchar, TRY_CAST (ISNULL(CONVERT(VARCHAR(10),FAZ3.FECRECMUE,111),CONVERT(VARCHAR(10),LAB5.VALOR,111)) as date), 23) AS [FECHA DE GLICEMIA],
ISNULL(CONVERT(VARCHAR(MAX),FAZ3.VALOR),LAB6.VALOR) AS [RESULTADO DE GLICEMIA],
CONVERT(varchar, TRY_CAST (ISNULL(CONVERT(VARCHAR(10),FAZ4.FECRECMUE,111),CONVERT(VARCHAR(10),LAB7.VALOR,111)) as date), 23) AS [FECHA DE HEMOGLOBINA GLICOSILADA],
ISNULL(CONVERT(VARCHAR(MAX),FAZ4.VALOR),LAB8.VALOR) AS [RESULTADO DE HEMOGLOBINA GLICOSILADA],
CONVERT(varchar, TRY_CAST (ISNULL(CONVERT(VARCHAR(10),FAZ5.FECRECMUE,111),CONVERT(VARCHAR(10),LAB9.VALOR,111)) as date), 23) AS [FECHA DE COLIESTEROL TOTAL],
ISNULL(CONVERT(VARCHAR(MAX),FAZ5.VALOR),LAB10.VALOR) AS [RESULTADO DE COLIESTEROL TOTAL],
CONVERT(varchar, TRY_CAST (ISNULL(CONVERT(VARCHAR(10),FAZ6.FECRECMUE,111),CONVERT(VARCHAR(10),LAB11.VALOR,111)) as date), 23) AS [FECHA DE TRIGLICERIDOS],
ISNULL(CONVERT(VARCHAR(MAX),FAZ6.VALOR),LAB12.VALOR) AS [RESULTADO DE TRIGLICERIDOS],
CONVERT(varchar, TRY_CAST (ISNULL(CONVERT(VARCHAR(10),FAZ7.FECRECMUE,111),CONVERT(VARCHAR(10),LAB13.VALOR,111)) as date), 23) AS [FECHA DE COLESTEROL HDL],
ISNULL(CONVERT(VARCHAR(MAX),FAZ7.VALOR),LAB14.VALOR) AS [RESULTADO DE COLESTEROL HDL],
CONVERT(varchar, TRY_CAST (ISNULL(CONVERT(VARCHAR(10),FAZ8.FECRECMUE,111),CONVERT(VARCHAR(10),LAB15.VALOR,111)) as date), 23) AS [FECHA DE COLESTEROL LDL],
ISNULL(CONVERT(VARCHAR(MAX),FAZ8.VALOR),LAB16.VALOR) AS [RESULTADO DE COLESTEROL LDL],
CONVERT(varchar, TRY_CAST (ISNULL(CONVERT(VARCHAR(10),FAZ9.FECRECMUE,111),CONVERT(VARCHAR(10),LAB17.VALOR,111)) as date), 23) AS [FECHA DE UROANALISIS],
ISNULL(CONVERT(VARCHAR(MAX),FAZ9.VALOR),LAB18.VALOR) AS [RESULTADO DE UROANALISIS],
CONVERT(varchar, TRY_CAST (CASE CTR.UNICONTRL WHEN '1' THEN CAST(CONVERT(NVARCHAR,DATEADD(DAY,CTR.NUMCONTRL,HC.FECHISPAC),112) AS DATE)
				   WHEN '2' THEN CAST(CONVERT(NVARCHAR, DATEADD(MONTH,CTR.NUMCONTRL,HC.FECHISPAC),112) AS DATE) ELSE NULL END as date), 23)  [FECHA PROX CONTROL],
MO.MODALIDAD,
CAST (HC.FECHISPAC as date) 'FECHA BUSQUEDA',
YEAR(HC.FECHISPAC) AS 'AÑO FECHA BUSQUEDA',
MONTH(HC.FECHISPAC) AS 'MES AÑO FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(HC.FECHISPAC), '00') ,' - ', 
	   CASE MONTH(HC.FECHISPAC) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) AS 'MES NOMBRE FECHA BUSQUEDA',
DAY(HC.FECHISPAC) AS 'DIA FECHA BUSQUEDA',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
--into report.p
FROM
DBO.INPACIENT PAC INNER JOIN
CTE_PACIENTES_INFORMES HC ON HC.NUMERO=1 AND PAC.IPCODPACI=HC.IPCODPACI INNER JOIN
DBO.INUBICACI AS UBI ON PAC.AUUBICACI=UBI.AUUBICACI INNER JOIN
DBO.INMUNICIP AS MUN ON UBI.DEPMUNCOD=MUN.DEPMUNCOD INNER JOIN
DBO.HCEXFISIC AS FIS ON HC.NUMINGRES=FIS.NUMINGRES AND HC.NUMEFOLIO=FIS.NUMEFOLIO INNER JOIN
DBO.ADINGRESO AS ING ON HC.NUMINGRES=ING.NUMINGRES INNER JOIN
Contract.HealthAdministrator AS EAPB ON ING.GENCONENTITY=EAPB.Id INNER JOIN
DBO.INPROFSAL AS PRO ON HC.CODPROSAL=PRO.CODPROSAL INNER JOIN
INESPECIA AS ESP ON HC.CODESPTRA=ESP.CODESPECI INNER JOIN
CTE_DIAGNOSTICOS DIA ON HC.NUMINGRES=DIA.NUMINGRES AND DIA.NUMERO=1 LEFT JOIN
CTE_DIAGNOSTICO_RELACIONADOS RE ON HC.NUMINGRES=RE.NUMINGRES AND RE.NUMERO=1 LEFT JOIN
CTE_DIAGNOSTICO_RELACIONADOS REL ON HC.NUMINGRES=REL.NUMINGRES AND REL.NUMERO=2 LEFT JOIN
CTE_FRAMMINGHAM FRA ON HC.NUMINGRES=FRA.NUMINGRES AND FRA.NUMERO=1 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB1 ON HC.NUMINGRES=LAB1.NUMINGRES AND LAB1.ID = 1 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB2 ON HC.NUMINGRES=LAB2.NUMINGRES AND LAB2.ID = 2 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB3 ON HC.NUMINGRES=LAB3.NUMINGRES AND LAB3.ID = 3 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB4 ON HC.NUMINGRES=LAB4.NUMINGRES AND LAB4.ID = 4 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB5 ON HC.NUMINGRES=LAB5.NUMINGRES AND LAB5.ID = 5 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB6 ON HC.NUMINGRES=LAB6.NUMINGRES AND LAB6.ID = 6 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB7 ON HC.NUMINGRES=LAB7.NUMINGRES AND LAB7.ID = 7 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB8 ON HC.NUMINGRES=LAB8.NUMINGRES AND LAB8.ID = 8 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB9 ON HC.NUMINGRES=LAB9.NUMINGRES AND LAB9.ID = 9 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB10 ON HC.NUMINGRES=LAB10.NUMINGRES AND LAB10.ID = 10 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB11 ON HC.NUMINGRES=LAB11.NUMINGRES AND LAB11.ID = 11 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB12 ON HC.NUMINGRES=LAB12.NUMINGRES AND LAB12.ID = 12 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB13 ON HC.NUMINGRES=LAB13.NUMINGRES AND LAB13.ID = 13 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB14 ON HC.NUMINGRES=LAB14.NUMINGRES AND LAB14.ID = 14 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB15 ON HC.NUMINGRES=LAB15.NUMINGRES AND LAB15.ID = 15 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB16 ON HC.NUMINGRES=LAB16.NUMINGRES AND LAB16.ID = 16 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB17 ON HC.NUMINGRES=LAB17.NUMINGRES AND LAB17.ID = 17 LEFT JOIN
CTE_RESULTADOS_EXAMFISICO LAB18 ON HC.NUMINGRES=LAB18.NUMINGRES AND LAB18.ID = 18 LEFT JOIN
CTE_RESULTADOS_INTERFAZ FAZ1 ON HC.IPCODPACI=FAZ1.IPCODPACI AND FAZ1.ID=1 AND FAZ1.AUTO=(SELECT MAX(A.AUTO) FROM CTE_RESULTADOS_INTERFAZ A WHERE HC.IPCODPACI=A.IPCODPACI AND A.ID=1) LEFT JOIN
CTE_RESULTADOS_INTERFAZ FAZ2 ON HC.IPCODPACI=FAZ2.IPCODPACI AND FAZ2.ID=2 AND FAZ2.AUTO=(SELECT MAX(A.AUTO) FROM CTE_RESULTADOS_INTERFAZ A WHERE HC.IPCODPACI=A.IPCODPACI AND A.ID=2) LEFT JOIN
CTE_RESULTADOS_INTERFAZ FAZ3 ON HC.IPCODPACI=FAZ3.IPCODPACI AND FAZ3.ID=3 AND FAZ3.AUTO=(SELECT MAX(A.AUTO) FROM CTE_RESULTADOS_INTERFAZ A WHERE HC.IPCODPACI=A.IPCODPACI AND A.ID=3) LEFT JOIN
CTE_RESULTADOS_INTERFAZ FAZ4 ON HC.IPCODPACI=FAZ4.IPCODPACI AND FAZ4.ID=4 AND FAZ4.AUTO=(SELECT MAX(A.AUTO) FROM CTE_RESULTADOS_INTERFAZ A WHERE HC.IPCODPACI=A.IPCODPACI AND A.ID=4) LEFT JOIN
CTE_RESULTADOS_INTERFAZ FAZ5 ON HC.IPCODPACI=FAZ5.IPCODPACI AND FAZ5.ID=5 AND FAZ5.AUTO=(SELECT MAX(A.AUTO) FROM CTE_RESULTADOS_INTERFAZ A WHERE HC.IPCODPACI=A.IPCODPACI AND A.ID=5) LEFT JOIN
CTE_RESULTADOS_INTERFAZ FAZ6 ON HC.IPCODPACI=FAZ6.IPCODPACI AND FAZ6.ID=6 AND FAZ6.AUTO=(SELECT MAX(A.AUTO) FROM CTE_RESULTADOS_INTERFAZ A WHERE HC.IPCODPACI=A.IPCODPACI AND A.ID=6) LEFT JOIN
CTE_RESULTADOS_INTERFAZ FAZ7 ON HC.IPCODPACI=FAZ7.IPCODPACI AND FAZ7.ID=7 AND FAZ7.AUTO=(SELECT MAX(A.AUTO) FROM CTE_RESULTADOS_INTERFAZ A WHERE HC.IPCODPACI=A.IPCODPACI AND A.ID=7) LEFT JOIN
CTE_RESULTADOS_INTERFAZ FAZ8 ON HC.IPCODPACI=FAZ8.IPCODPACI AND FAZ8.ID=8 AND FAZ8.AUTO=(SELECT MAX(A.AUTO) FROM CTE_RESULTADOS_INTERFAZ A WHERE HC.IPCODPACI=A.IPCODPACI AND A.ID=8) LEFT JOIN
CTE_RESULTADOS_INTERFAZ FAZ9 ON HC.IPCODPACI=FAZ9.IPCODPACI AND FAZ9.ID=9 AND FAZ9.AUTO=(SELECT MAX(A.AUTO) FROM CTE_RESULTADOS_INTERFAZ A WHERE HC.IPCODPACI=A.IPCODPACI AND A.ID=9) LEFT JOIN
CTE_CONTROL CTR ON HC.NUMINGRES=CTR.NUMINGRES AND CTR.NUMERO=1 LEFT JOIN
CTE_MODALIDAD MO ON HC.NUMINGRES=MO.NUMINGRES 
--WHERE pac.ipcodpaci='10057387'
