-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: SP_GenerateAdicionalGestionRiesgo
-- Extracted by Fabric SQL Extractor SPN v3.9.0









----/*******************************************************************************************************************
----Nombre: [Report].[SPAdicionalGestionRiesgo]
----Tipo:Vista
----Observacion:SP MENSUAL PARA EL INFORME DE GESTIÓN DEL RIESGO
----Profesional: Nilsson Miguel Galindo Lopez
----Fecha:24-04-2023
-------------------------------------------------------------------------------
----Modificaciones
----_____________________________________________________________________________
----Version 1
----Persona que modifico:
----Fecha:
----Ovservaciones:
------------------------------------------
----Version 2
----Persona que modifico:
----Fecha:
----***********************************************************************************************************************************/

CREATE PROCEDURE [Report].[SP_GenerateAdicionalGestionRiesgo]
 @MES varchar(2),
 @ANIO varchar(4)
AS

BEGIN

DECLARE @FechaInicial date = CAST (@ANIO || '-' || @MES || '-01' as date );
DECLARE @FechaFinal date =	EOMONTH (@FechaInicial);

/*******************************************************************************************************************/
---------------------------------------SE DECLARA LAS VARIABLES TABLA
/*******************************************************************************************************************/
---------------------------------------SE DECLARA LAS VARIABLES TABLA

DECLARE @TBL_POBLACION AS TABLE (IPCODPACI VARCHAR(25),
								 AÑO INT,
								 MES INT,
								 NUMINGRES CHAR(10),
								 NUMEFOLIO INT,
								 NOMCENATE CHAR(100));
DECLARE @TBL_FACTURACION AS TABLE(VARIABLE INT,
								  IPCODPACI VARCHAR(25),
								  SERVICEDATE DATE,
								  AÑO INT,
								  MES INT);
DECLARE @TBL_ANTECEDENTES AS TABLE(VARIABLE INT,
								   IPCODPACI VARCHAR (25),
								   VALOR VARCHAR (5000),
								   AÑO INT,
								   MES INT);
DECLARE @TBL_EXAMEN_FISICO AS TABLE(VARIABLE INT,
									IPCODPACI VARCHAR(25),
									VALOR VARCHAR (5000),
									FOLIO INT,
									AÑO INT,
									MES INT);
DECLARE @TBL_DISPENSACIONES AS TABLE (VARIABLE INT,
									  [FECHA DISPENSACION] DATE,
									  [ID TERCERO/PACIENTE] VARCHAR (25),
									  CANTIDAD INT);
DECLARE @TBL_DISPENSACION_PRESERVATIVOS AS TABLE ([FECHA DISPENSACION] DATE,
												  [ID TERCERO/PACIENTE] VARCHAR(25),
												  [COD.PRODUCT] CHAR (20),
												  CANTIDAD INT,
												  AÑO INT,
												  MES INT);
DECLARE @TBL_NOTAS_ADMINISTRATIVAS AS TABLE (IPCODPACI VARCHAR(25),
											 VARIABLE INT,
											 VALOR VARCHAR (5000),
											 AÑO INT,
											 MES INT);
DECLARE @TBL_ALIMENTACION_SALUDABLE AS TABLE (IPCODPACI VARCHAR(25),
											  VALORITEMSELECCIONADO INT,
											  AÑO INT,
											  MES INT);
DECLARE @TBL_REVICION_SISTEMA AS TABLE (IPCODPACI VARCHAR(25),
										VARIABLE INT,
										VALOR VARCHAR (5000),
										FECHISPAC DATE,
										AÑO INT,
										MES INT);
DECLARE @TBL_FISICO AS TABLE(IPCODPACI VARCHAR (25),
							 NUMEFOLIO INT,
							 NEOPERABD INT,
							 PB numeric(4,1),
							 NEOPERCEF INT,
							 REGSO2PAC CHAR(10),
							 TENARTDIA INT,
							 TENARTSIS INT,
							 PESO VARCHAR(4),
							 TALLA INT,
							 AÑO INT,
							 MES INT);
DECLARE @TBL_ESCALAS AS TABLE(IPCODPACI VARCHAR(25),
							  RESULTADO INT,
							  TIPOESCALA INT,
							  FOLIO INT,
							  AÑO INT,
							  MES INT);
DECLARE @TBL_LABORATORIO AS TABLE (IPCODPACI VARCHAR(25),
								  FECHA DATE,
								  VALOR VARCHAR(MAX),
								  [AUTO] INT,
								  VARIABLE INT,
								  AÑO INT,
								  MES INT);
/*********************************************INICIO DE CTE*********************************************************/
--POBLACION SUJETA AL REPORTE
INSERT INTO @TBL_POBLACION
SELECT
	ING.IPCODPACI,
	YEAR(ING.IFECHAING) AS AÑO,
	MONTH(ING.IFECHAING) AS MES,
	ING.NUMINGRES,
	HIS.NUMEFOLIO,
	CEN.NOMCENATE
FROM 
dbo.ADINGRESO ING INNER JOIN
dbo.HCHISPACA HIS ON ING.NUMINGRES=HIS.NUMINGRES AND ING.TIPOINGRE=1 
												 AND CAST(ING.IFECHAING AS DATE) BETWEEN @FechaInicial AND @FechaFinal 
												 AND ING.NUMINGRES=(SELECT MAX(A.NUMINGRES) FROM dbo.ADINGRESO A WHERE ING.IPCODPACI=A.IPCODPACI AND A.TIPOINGRE=1
																																				 AND CAST(A.IFECHAING AS DATE) BETWEEN @FechaInicial AND @FechaFinal)
												 AND HIS.NUMEFOLIO=(SELECT MAX(A.NUMEFOLIO) FROM HCHISPACA A WHERE HIS.NUMINGRES=A.NUMINGRES) INNER JOIN
dbo.ADCENATEN CEN ON ING.CODCENATE=CEN.CODCENATE;
---------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO @TBL_FACTURACION
SELECT 
	CASE WHEN CUPS.Code IN ('990101','990102','990103','990104','990105','990106','990107','990108','990109','990110','990111','990112','990113') THEN 1 --GRUPO DE EDUCACIÓN GRUPAL
		 WHEN CUPS.Code IN ('990201','990202','990203','990204','990205','990206','990207','990208','990209','990210','990211','990212','990213','990221','990222','990223','990224') THEN 2 --GRUPO DE EDUCACIÓN INDIVIDUAL
		 WHEN CUPS.Code IN ('990201','990202','990203','990204','990205','990206','990207','990208','990209','990210','990211','990212','990213','990221','990222','990223','990224') THEN 3 --GRUPO DE EDUCACION FAMILIAR
		 END VARIABLE,
	ING.IPCODPACI,
	CAST(DOS.ServiceDate AS DATE) AS ServiceDate,
	YEAR(DOS.ServiceDate) AS AÑO,
	MONTH(DOS.ServiceDate) AS MES
FROM 
	@TBL_POBLACION POB INNER JOIN
	ADINGRESO ING ON POB.IPCODPACI=ING.IPCODPACI INNER JOIN
	BILLING.INVOICE F ON ING.NUMINGRES=F.AdmissionNumber AND ING.TIPOINGRE=1 INNER JOIN
	BILLING.INVOICEDETAIL DF ON F.ID=DF.INVOICEID INNER JOIN 
	BILLING.SERVICEORDERDETAIL DOS ON DOS.ID = DF.SERVICEORDERDETAILID INNER JOIN 
	CONTRACT.CUPSENTITY CUPS ON CUPS.ID = DOS.CUPSENTITYID
WHERE CUPS.Code IN ('990101','990102','990103','990104','990105','990106','990107','990108','990109','990110','990111','990112',
'990113','990201','990202','990203','990204','990205','990206','990207','990208','990209','990210','990211','990212','990213',
'990221','990222','990223','990224','990201','990202','990203','990204','990205','990206','990207','990208','990209','990210',
'990211','990212','990213','990221','990222','990223','990224') AND F.Status =1
AND CAST(DOS.ServiceDate AS DATE) BETWEEN @FechaInicial AND @FechaFinal
GROUP BY CUPS.Code,ING.IPCODPACI,CAST(DOS.ServiceDate AS DATE),YEAR(DOS.ServiceDate),MONTH(DOS.ServiceDate);

/***********************************************************************************************************************
---------------------------------------ANTECEDENTES--------------------------------------------------------------------
************************************************************************************************************************/
INSERT INTO @TBL_ANTECEDENTES
SELECT 
CASE WHEN ANT.VARIABLE='¿Por cuánto tiempo (meses) fue exclusiva?' THEN 1 
	 WHEN ANT.VARIABLE IN ('Alcoholismo','Consume alcohol','Edad de inicio del consumo de alcohol','Frecuencia del consumo de alcohol') THEN 2 --ALCOHOLISMO
	 WHEN ANT.VARIABLE='Sedentarismo' THEN 3 END AS VARIABLE, --sedentarismo
ANT.IPCODPACI,
ANT.VALOR,
YEAR(ANT.FECHISPAC) AS AÑO,
MONTH(ANT.FECHISPAC) AS MES
FROM 
[Report].[TablaAntecedentes] ANT 
WHERE ANT.VARIABLE IN ('¿Por cuánto tiempo (meses) fue exclusiva?','Alcoholismo','Consume alcohol','Edad de inicio del consumo de alcohol',
'Frecuencia del consumo de alcohol','Sedentarismo')

/********************************************************************************************************************************************
----------------------------------------------EXAMEN FISICO-------------------------------------------------------------------------------
********************************************************************************************************************************************/

INSERT INTO @TBL_EXAMEN_FISICO
SELECT 
CASE FIS.NOMBRE_VARIABLE WHEN 'Resultado de PSA' THEN 1 WHEN 'Fecha de realización de PSA' THEN 1-- EVALUCIÓN TAMIZAJE CANCER DE PROSTATA
						 WHEN 'Fecha de uroanálisis' THEN 2 --RIESGO UROANALISIS
						 WHEN 'Fecha de Colesterol Total' THEN 3 --FECHA COLESTEROL TOTAL
						 WHEN 'Resultado de colesterol total' THEN 4 --RESULTADO COLESTEROL TOTAL
						 WHEN 'Fecha de colesterol HDL' THEN 5 --FECHA HDL
						 WHEN 'Resultado de colesterol HDL' THEN 6 --RESULTADO HDL
						 WHEN 'Fecha de colesterol LDL' THEN 7 --FECHA LDL
						 WHEN 'Resultado de colesterol LDL' THEN 8 --RESULTADO LDL
						 WHEN 'Fecha de creatinina' THEN 9 --FECHA CREATININA
						 WHEN 'Resultado de creatinina' THEN 10 --RESULTADO CREATININA
						 WHEN 'Fecha de trigliceridos' THEN 11 --FECHA TRIGLICERIDOS
						 WHEN 'Resultado de trigliceridos' THEN 12 --RESULTADO TRIGLICERIDOS
						 WHEN 'Fecha de Glicemia' THEN 13 --FECHA GLICEMIA
						 WHEN 'Resultado de glicemia' THEN 14 --RESULTADO DE GLICEMIA
						 WHEN 'Fecha de Hematocrito' THEN 15 --Fecha de Hematocrito
						 WHEN 'Resultado Hematocrito' THEN 16 -- RESULTADO DE HEMAROCRITO
						 WHEN 'Riesgo Cardiovascular' THEN 17 --RIESGO CARDIOVASCULAR
						 WHEN 'FECHA BX PROSTATA' THEN 18 --FECHA PROSTATA
						 WHEN 'RESULTADO BX PROSTATA' THEN 19 -- RESULTADO PROSTATA
						 WHEN 'EXAMEN CLINICO DE MAMA' THEN 20 --EXAMEN CLINICO MAMA
						 WHEN 'Resultado Prueba de Embarazo' THEN 21 --PRUEBA DE EMBARAZO
						 WHEN 'Agudeza visual OD' THEN 22 --AGUDEZA VISUAL
						 WHEN 'Agudeza visual OI'THEN 23-- AGUDEZA VISUAL
						 WHEN 'Tacto Rectal' THEN 24 WHEN 'Descripcion Tacto rectal' THEN 24
						 END AS VARIABLE,
FIS.IPCODPACI,
FIS.VALOR,
FIS.NUMEFOLIO,
YEAR(FIS.FECHA) AS AÑO,
MONTH(FIS.FECHA) AS MES
FROM 

[REPORT].[TablaExamenFisico] FIS 
WHERE NOMBRE_VARIABLE IN ('Descripcion Tacto rectal','Resultado de PSA','Fecha de realización de PSA','Fecha de uroanálisis',
'Fecha de Colesterol Total','Resultado de colesterol total','Fecha de colesterol HDL','Resultado de colesterol HDL','Fecha de colesterol LDL',
'Resultado de colesterol LDL','Fecha de creatinina','Resultado de creatinina','Fecha de trigliceridos','Resultado de trigliceridos','Fecha de Glicemia','Resultado de glicemia',
'Fecha de Hematocrito','Resultado Hematocrito','Riesgo Cardiovascular','FECHA BX PROSTATA','RESULTADO BX PROSTATA','Resultado Prueba de Embarazo','Agudeza visual OD',
'Agudeza visual OI')
AND CAST(FIS.FECHA AS DATE) BETWEEN @FechaInicial AND @FechaFinal
/**********************************************************************************************************
---------------------------------LABORATORIOS-------------------------------------------------------------
***********************************************************************************************************/
INSERT INTO @TBL_LABORATORIO
SELECT 
A.IPCODPACI,
CAST(ISNULL(A.FECRECMUE,A.FECORDMED) AS DATE)AS FECHA,
VAL.VALOR,
VAL.[AUTO],
CASE A.CODSERIPS WHEN '903818' THEN 1 --COLESTEROL TOTAL
				 WHEN '903815' THEN 2 --HDL
				 WHEN '903817' THEN 3 WHEN '903816' THEN 3--LDL
				 WHEN '903895' THEN 4 --CREATININA
				 WHEN '903868' THEN 5 --TRIGLICERIDOS
				 WHEN '903841' THEN 6 --GLICEMIA
				 WHEN '902211' THEN 7 --HEMATOCRITO
				 WHEN '904508' THEN 8 --PRUEBA DE EMBARAZO
END AS VARIABLE,
YEAR(ISNULL(A.FECRECMUE,A.FECORDMED))AS AÑO,
MONTH(ISNULL(A.FECRECMUE,A.FECORDMED))AS MES
from 
@TBL_POBLACION POB INNER JOIN
dbo.AMBORDLAB A ON POB.IPCODPACI=A.IPCODPACI AND CAST(A.FECRECMUE AS DATE) BETWEEN @FechaInicial AND @FechaFinal INNER JOIN
INTERLABD VAL ON A.AUTO=VAL.AUTOLABOR
WHERE A.CODSERIPS IN('903818','903815','903817','903895','903868','903841','902211','904508') AND A.ESTSERIPS!=6 
																							  AND VAL.ANALITO IN ('COLESTEROL TOTAL','COLESTEROL HDL','COLESTEROL LDL','CREATININA','PRUEBA DE EMBARAZO CUALITATIVA')
UNION ALL
select
A.IPCODPACI,
CAST(ISNULL(A.FECRECMUE,A.FECORDMED) AS DATE)AS FECHA,
VAL.VALOR,
VAL.[AUTO],
CASE A.CODSERIPS WHEN '903818' THEN 1 --COLESTEROL TOTAL
				 WHEN '903815' THEN 2 --HDL
				 WHEN '903817' THEN 3 WHEN '903816' THEN 3--LDL
				 WHEN '903895' THEN 4 --CREATININA
				 WHEN '903868' THEN 5 --TRIGLICERIDOS
				 WHEN '903841' THEN 6 --GLICEMIA
				 WHEN '902211' THEN 7 --HEMATOCRITO
				 WHEN '904508' THEN 8 --PRUEBA DE EMBARAZO
END AS VARIABLE,
YEAR(ISNULL(A.FECRECMUE,A.FECORDMED))AS AÑO,
MONTH(ISNULL(A.FECRECMUE,A.FECORDMED))AS MES
from 
@TBL_POBLACION POB INNER JOIN
dbo.HCORDLABO A ON POB.IPCODPACI=A.IPCODPACI AND CAST(A.FECRECMUE AS DATE) BETWEEN @FechaInicial AND @FechaFinal INNER JOIN
INTERLABD VAL ON A.AUTO=VAL.AUTOLABOR
WHERE A.CODSERIPS IN('903818','903815','903817','903895','903868','903841','902211','904508') AND A.ESTSERIPS!=6 
																							  AND VAL.ANALITO IN ('COLESTEROL TOTAL','COLESTEROL HDL','COLESTEROL LDL','CREATININA','PRUEBA DE EMBARAZO CUALITATIVA');
/*******************************************************************************************************
---------------------------------DISPENSACIONES--------------------------------------------------------
*******************************************************************************************************/
INSERT INTO @TBL_DISPENSACIONES
SELECT
CASE WHEN GRU.ID IN (22,31) THEN 1 --DIDPENSACION ANTIPARASITARIOS
	 WHEN GRU.ID=88 THEN 2 --DIDPENSACION MICRONUTRIENTES
	 WHEN ATC.CODE='A11CA0101' THEN 3 --DIDPENSACION VINAMINA A
	 WHEN ATC.CODE IN ('B03AA0701','B03AA0702','B03AA0703','B03AC0201') THEN 4 --DIDPENSACION HIERRO
	 WHEN ATC.CODE IN ('A12AA0401','A11AA0201','A02AC0101') THEN 5 --DIDPENSACION CALCIO
	END AS VARIABLE,
CAST(PDD.SERVICEDATE AS DATE) AS [FECHA DISPENSACION], 
PER.IDENTIFICATIONNUMBER AS [ID TERCERO/PACIENTE], 
PDD.QUANTITY AS CANTIDAD
FROM 
INVENTORY.PHARMACEUTICALDISPENSING PD INNER JOIN 
INVENTORY.PHARMACEUTICALDISPENSINGDETAIL PDD ON PD.ID=PDD.PHARMACEUTICALDISPENSINGID INNER JOIN 
COMMON.THIRDPARTY TER ON PDD.THIRDPARTYID=TER.ID INNER JOIN 
COMMON.PERSON PER ON TER.PERSONID=PER.ID INNER JOIN 
INVENTORY.INVENTORYPRODUCT PRO ON PRO.ID=PDD.PRODUCTID INNER JOIN 
INVENTORY.ATC ATC ON PRO.CODE=ATC.CODE INNER JOIN 
INVENTORY.PHARMACOLOGICALGROUP GRU ON ATC.PHARMACOLOGICALGROUPID=GRU.ID
WHERE GRU.ID IN (22,31,88) OR ATC.CODE IN ('A11CA0101','B03AA0701','B03AA0702','B03AA0703','B03AC0201','A12AA0401','A11AA0201','A02AC0101','DM00801')
AND CAST(PDD.SERVICEDATE AS DATE) BETWEEN @FechaInicial AND @FechaFinal;


INSERT INTO @TBL_DISPENSACION_PRESERVATIVOS
	SELECT  
	CAST(PDD.SERVICEDATE AS DATE) AS 'FECHA DISPENSACION',
	PER.IDENTIFICATIONNUMBER 'ID TERCERO/PACIENTE',
	PRO.CODE 'COD. PRODUCTO',
	SUM(PDD.QUANTITY) AS 'CANTIDAD',
	YEAR(PDD.SERVICEDATE) AS AÑO,
	MONTH(PDD.SERVICEDATE) AS MES
	FROM INVENTORY.PHARMACEUTICALDISPENSING PD
	INNER JOIN INVENTORY.PHARMACEUTICALDISPENSINGDETAIL PDD ON PDD.PHARMACEUTICALDISPENSINGID=PD.ID
	INNER JOIN INVENTORY.INVENTORYPRODUCT PRO ON PRO.ID=PDD.PRODUCTID
	INNER JOIN COMMON.THIRDPARTY TER ON TER.ID=PDD.THIRDPARTYID
	INNER JOIN COMMON.PERSON PER ON PER.ID=TER.PERSONID
	INNER JOIN CONTRACT.HEALTHADMINISTRATOR HA ON HA.ID=PDD.HEALTHADMINISTRATORID
	WHERE PRO.CODE IN ('DM00801') AND CAST(PDD.SERVICEDATE AS DATE) BETWEEN @FechaInicial AND @FechaFinal
	GROUP BY CAST(PDD.SERVICEDATE AS DATE),PER.IDENTIFICATIONNUMBER,PRO.CODE,YEAR(PDD.SERVICEDATE),	MONTH(PDD.SERVICEDATE)

INSERT INTO @TBL_NOTAS_ADMINISTRATIVAS 
SELECT
NOTA.IPCODPACI,
CASE CAV.NOMBRE WHEN 'Resultado Ecografia de Mama' THEN 1--Resultado Ecografia de Mama
				WHEN 'Rersultado Examen Mamá' THEN 2 --RESULTADO DE EXAMEN DE MAMA
				WHEN 'Colposcopia' THEN 3 -- RESULTADO COLPOSCOPIA
				WHEN 'Clasificacion Riesgo Cardiovascular' THEN 4
				END AS VARIABLE,
NOAD.VALOR AS VALOR,-- CONVERT(DATE,CONVERT(NCHAR(10),NOAD.VALOR),103) AS [96],
YEAR(NOTA.FECHACREACION) AS AÑO,
MONTH(NOTA.FECHACREACION) AS MES
FROM
NTNOTASADMINISTRATIVASC NOTA INNER JOIN
NTADMINISTRATIVAS CAV ON NOTA.IDNOTAADMINISTRATIVA=CAV.ID LEFT JOIN
NTNOTASADMINISTRATIVASD NOAD ON NOTA.ID=NOAD.IDNTNOTASADMINISTRATIVASC LEFT JOIN
NTVARIABLESL LIS ON NOAD.IDITEMLISTA=LIS.ID
WHERE CAV.NOMBRE IN ('Resultado Ecografia de Mama','Rersultado Examen Mamá','Colposcopia','Clasificacion Riesgo Cardiovascular');

INSERT INTO @TBL_ALIMENTACION_SALUDABLE
Select 
ESC.IPCODPACI,
ITEM.VALORITEMSELECCIONADO, 
YEAR(ESC.FECHAREGISTRO) AS AÑO,
MONTH(ESC.FECHAREGISTRO) AS MES
from HCESCALAS ESC
INNER JOIN HCESCALASRESULTITEMS ITEM ON ITEM.IDHCESCALAS=ESC.ID
WHERE TIPOESCALA=8 AND ITEM.TAGPREGUNTA='005' AND CAST(ESC.FECHAREGISTRO AS DATE) BETWEEN @FechaInicial AND @FechaFinal

INSERT INTO @TBL_REVICION_SISTEMA
SELECT
SIS.ipcodpaci,
CASE SIS.VARIABLE WHEN 'Asesoría Pre y Post VIH' THEN 1 --Asesoría Pre y Post VIH
				  WHEN 'Fecha Test Autonomia' THEN 2
				  WHEN 'Fecha Test Derechos sexuales y reproductivos' THEN 3
				  WHEN 'Fecha Test de Identidad' THEN 4
END AS VARIABLE,
SIS.valor,
CAST(SIS.FECHISPAC AS DATE) AS FECHISPAC,
YEAR(SIS.FECHISPAC) AS AÑO,
MONTH(SIS.FECHISPAC) AS MES
FROM [Report].[TablaRevisionXSistema] SIS 
WHERE SIS.VARIABLE IN ('Asesoría Pre y Post VIH','Fecha Test Autonomia','Fecha Test Derechos sexuales y reproductivos','Fecha Test de Identidad') 
AND CAST(SIS.FECHISPAC AS DATE) BETWEEN @FechaInicial AND @FechaFinal;
----------------------------------------------------------------------------------------------------------------------------------------------
SELECT
POB.IPCODPACI,
POB.NOMCENATE AS [CENTRO DE ATENCION],
CARE.NAME AS [GRUPO DE ATENCION],
HA.NAME AS EAPB,
CASE PAC.IPTIPODOC WHEN '1' THEN 'CC' 
				   WHEN '2' THEN 'CE'
				   WHEN '3' THEN 'TI'
				   WHEN '4' THEN 'RC'	
				   WHEN '5' THEN 'PA'	
				   WHEN '6' THEN 'AS'
				   WHEN '7' THEN 'MS'
				   WHEN '8' THEN 'NU'
				   WHEN '9' THEN 'CN'
				   WHEN '10' THEN 'CD'	
				   WHEN '11' THEN 'SC' 
				   WHEN '12' THEN 'PE'
				   WHEN '13' THEN 'PT'
				   WHEN '14' THEN 'DE' ELSE 'N/A'END AS [TIPO DOCUMENTO],
HIS.FECHISPAC,
PAC.IPNOMCOMP AS [NOMBRE PACIENTE],
CAST(PAC.IPFECNACI AS DATE) AS [FECHA DE NACIMIENTO],
FLOOR((CAST(CONVERT(VARCHAR(8), GETDATE() , 112) AS INT)-CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS [EDAD (AÑOS)],
CASE WHEN PAC.IPSEXOPAC=1 THEN 'MASCULINO' ELSE 'FEMENINO' END [SEXO PACIENTE],
MODE.NOMBRE,
POB.AÑO,
POB.MES
INTO #TBL_PACIENTES
FROM
@TBL_POBLACION POB INNER JOIN 
dbo.INPACIENT PAC ON POB.IPCODPACI=PAC.IPCODPACI INNER JOIN 
dbo.ADINGRESO ING ON POB.NUMINGRES=ING.NUMINGRES INNER JOIN
dbo.HCHISPACA HIS ON POB.NUMINGRES=HIS.NUMINGRES AND POB.NUMEFOLIO=HIS.NUMEFOLIO INNER JOIN
CONTRACT.CAREGROUP CARE ON ING.GENCAREGROUP=CARE.ID INNER JOIN 
CONTRACT.HEALTHADMINISTRATOR HA ON HA.ID=ING.GENCONENTITY LEFT JOIN 
PRMODELOHC MODE ON HIS.IDMODELOHC=MODE.ID;
/********************************************************************************************************************************************
---------------------------------------------EXAMEN FISICO NO PARAMETRIZADO (NORMAL)--------------------------------------------------------
*********************************************************************************************************************************************/
INSERT INTO @TBL_FISICO
SELECT
FIS.IPCODPACI,
FIS.NUMEFOLIO,
FIS.NEOPERABD,
FIS.PB,
FIS.NEOPERCEF,
FIS.REGSO2PAC,
FIS.TENARTDIA,
FIS.TENARTSIS,
IIF(FIS.PESOPACIE=0,'0.00',IIF(FIS.PESOPACIE<=999,CONVERT(VARCHAR(4),FORMAT(FIS.PESOPACIE,'##.##')),CONVERT(VARCHAR(4),FORMAT(FIS.PESOPACIE/1000,'##.##')))) AS PESO,
IIF(FIS.TALLAPACI=0,'0',CAST(FIS.TALLAPACI AS INT)) AS TALLA,
POB.AÑO,
POB.MES
FROM 
@TBL_POBLACION POB INNER JOIN
dbo.HCEXFISIC FIS ON POB.IPCODPACI=FIS.IPCODPACI AND POB.AÑO=YEAR(FIS.FECREGITE) 
												 AND POB.MES=MONTH(FIS.FECREGITE) 
												 AND FIS.NUMINGRES IS NOT NULL
												 AND FIS.NUMEFOLIO  IS NOT NULL;
------------------------------------------------------------------------------------------------------------------------------------------------------------
--DEPURAR EL EXAMEN FISICO
SELECT * 
INTO #TBL_FISICO_DEPURADO
FROM 
@TBL_FISICO FIS 
WHERE FIS.NUMEFOLIO=(SELECT MAX(F.NUMEFOLIO) FROM dbo.HCEXFISIC F WHERE FIS.IPCODPACI=F.IPCODPACI);

----------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO @TBL_ESCALAS
SELECT 
ESC.IPCODPACI,
ESC.RESULTADO,
ESC.TIPOESCALA,
ESC.NUMEFOLIO,
YEAR(ESC.FECHAREGISTRO) AS AÑO,
MONTH(ESC.FECHAREGISTRO) AS MES
FROM 
HCESCALAS ESC INNER JOIN
ADINGRESO ING ON ESC.NUMINGRES=ING.NUMINGRES AND ING.TIPOINGRE=1 AND CAST(ESC.FECHAREGISTRO AS DATE) BETWEEN @FechaInicial AND @FechaFinal
UNION ALL
SELECT
ESC.IPCODPACI,
ESC.RESULTADO,
1010 AS TIPOESCALA,
ESC.NUMEFOLIO,
YEAR(ESC.FECHAREGISTRO) AS AÑO,
MONTH(ESC.FECHAREGISTRO) AS MES
FROM
dbo.ESCALAVALE ESC INNER JOIN
ADINGRESO ING ON ESC.NUMINGRES=ING.NUMINGRES AND ING.TIPOINGRE=1 AND CAST(ESC.FECHAREGISTRO AS DATE) BETWEEN @FechaInicial AND @FechaFinal
/***********************************************************************************************************************************/
-------------------------------------------------------CONSULTA FINAL----------------------------------------------------------------
/***********************************************************************************************************************************/

SELECT
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
POB.[CENTRO DE ATENCION],
POB.[GRUPO DE ATENCION],
POB.EAPB,
POB.[TIPO DOCUMENTO],
POB.IPCODPACI AS [ID PACIENTE],
POB.[NOMBRE PACIENTE],
POB.[FECHA DE NACIMIENTO],
POB.[EDAD (AÑOS)],
POB.[SEXO PACIENTE],
POB.FECHISPAC AS [FECHA ATENCION], 
FIS.TALLA AS [TALLA CM],
FIS.PESO AS [PESO KG],
ISNULL(POB.NOMBRE,'Consulta Externa') AS [TIPO DE ATENCION],
IIF(POB.[SEXO PACIENTE]='MASCULINO' OR POB.[EDAD (AÑOS)] BETWEEN 10 AND 60,'1845-01-01'
																		  ,IIF(POB.NOMBRE='Atencion Preconcepcional',POB.FECHISPAC,'1800-01-01')) AS [ATENCION PRECONCEPCIONAL],
'Parametrizar educacion familiar en HCL' AS [EDUCACION FAMILIAR],
ISNULL(GRU.ServiceDate,'1800-01-01') AS [FECHA EDUCACION GRUPAL], --FECHA EDUCACION GRUPAL
ISNULL(IND.ServiceDate,'1800-01-01') AS [FECHA EDUCACION INDIVIDUAL], --FECHA EDUCACION INDIVIDUAL
ISNULL(FAM.ServiceDate,'1800-01-01') AS [FECHA EDUCACION FAMILIAR], --FECHA EDUCACION FAMILIAR
IIF(POB.[EDAD (AÑOS)]<10,'1845-01-01',IIF(VIH2.VALOR IS NULL,'1800-01-01'
									 ,IIF(VIH2.VALOR=1,VIH2.FECHISPAC,'1800-01-01'))) AS [PRE TEST ELISA], 
IIF(POB.[EDAD (AÑOS)]<10,'1845-01-01',IIF(VIH2.VALOR IS NULL,'1800-01-01'
									 ,IIF(VIH2.VALOR=2,VIH2.FECHISPAC,'1800-01-01'))) AS [POS TEST ELISA], 
IIF(SAL.VALORITEMSELECCIONADO IS NULL,'NO EVALUADO',CASE WHEN SAL.VALORITEMSELECCIONADO='0' THEN '1' ELSE '2' END) AS [ALIMENTACION SALUDABLE],  
IIF(ALC.VALOR IS NULL OR ALC.VALOR='0','1','2') AS [CONSUMO DE ALCOCHOL],
IIF(POB.[EDAD (AÑOS)]>=6,'NO APLICA',ISNULL(CONVERT(VARCHAR(12),LAC.VALOR),'NO EVALUADO')) AS [EDAD LACTANCIA EXLUSIVA],
IIF(POB.[EDAD (AÑOS)]< 5,'NO APLICA',ISNULL(CASE WHEN SED.VALOR=1 THEN '1' ELSE '2' END,'NO EVALUADO')) AS SEDENTARISMO,
IIF(POB.[SEXO PACIENTE]='FEMENINO' OR POB.[EDAD (AÑOS)]<45,'NO APLICA',CASE WHEN PROS.VALOR IS NOT NULL THEN '1' ELSE '2' END) AS [FACTOR RIESGO CAPPRÓSTATA],
CASE WHEN PAR.[CANTIDAD] IS NULL THEN 0 ELSE PAR.[CANTIDAD] END AS [ANTIPARASITARIO],
CASE WHEN MIC.[CANTIDAD] IS NULL THEN 0 ELSE MIC.[CANTIDAD] END AS [MICRONUTRIENTES_POLVO], 
CASE WHEN VIT.[CANTIDAD] IS NULL THEN 0 ELSE VIT.[CANTIDAD] END AS [VITAMINA A],
CASE WHEN HIE.[CANTIDAD] IS NULL THEN 0 ELSE HIE.[CANTIDAD] END AS [SULFATO FERROSO], 
CASE WHEN CAL.[CANTIDAD] IS NULL THEN 0 ELSE CAL.[CANTIDAD] END AS CALCIO, 
CASE WHEN CON.[CANTIDAD] IS NULL THEN 0 ELSE CON.[CANTIDAD] END AS PRESERVATIVOS,
IIF(POB.[EDAD (AÑOS)]<18,'1845-01-01',ISNULL(CONVERT(VARCHAR(10),CONVERT(DATE,CONVERT(NCHAR(10),URO.VALOR),103),23),'1800-01-01')) AS [FECHA UROANALISIS],
IIF(POB.[EDAD (AÑOS)]<18,'1845-01-01',IIF(LABCOL.VALOR IS NULL,ISNULL(CONVERT(VARCHAR(10),CONVERT(DATE,CONVERT(NCHAR(10),COL.VALOR),103),23),'1800-01-01'),LABCOL.VALOR)) AS [FECHA COLESTEROL TOTAL],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',IIF(LABCOL.FECHA IS NULL,ISNULL(CONVERT(VARCHAR(12),RESCOL.VALOR),'NO EVALUADO'),LABCOL.VALOR)) AS [RESULTADO COLESTEROL TOTAL],
IIF(POB.[EDAD (AÑOS)]<18,'1845-01-01',IIF(LABHDL.FECHA IS NULL,ISNULL(CONVERT(VARCHAR(10),CONVERT(DATE,CONVERT(NCHAR(10),FECHDL.VALOR),103),23),'1800-01-01'),LABHDL.FECHA)) AS [FECHA HDL],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',IIF(LABHDL.VALOR IS NULL,ISNULL(CONVERT(VARCHAR(12),RESHDL.VALOR),'NO EVALUADO'),LABHDL.VALOR)) AS [RESULTADO HDL],
IIF(POB.[EDAD (AÑOS)]<18,'1845-01-01',IIF(LABLDL.FECHA IS NULL,ISNULL(CONVERT(VARCHAR(10),CONVERT(DATE,CONVERT(NCHAR(10),FECLDL.VALOR),103),23),'1800-01-01'),LABLDL.FECHA)) AS [FECHA LDL],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',IIF(LABLDL.VALOR IS NULL,ISNULL(CONVERT(VARCHAR(12),RESLDL.VALOR),'NO EVALUADO'),LABLDL.VALOR)) AS [RESULTADO LDL],
IIF(POB.[EDAD (AÑOS)]<18,'1845-01-01',IIF(LABCRE.FECHA IS NULL,ISNULL(CONVERT(VARCHAR(10),CONVERT(DATE,CONVERT(NCHAR(10),FECCREA.VALOR),103),23),'1800-01-01'),LABCRE.FECHA)) AS [FECHA CREATININA],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',IIF(LABCRE.VALOR IS NULL,ISNULL(CONVERT(VARCHAR(12),RESCREA.VALOR),'NO EVALUADO'),LABCRE.VALOR)) AS [RESULTADO CREATININA],
IIF(POB.[EDAD (AÑOS)]<18,'1845-01-01',IIF(LABTRI.FECHA IS NULL,ISNULL(CONVERT(VARCHAR(10),CONVERT(DATE,CONVERT(NCHAR(10),FECTRIGLI.VALOR),103),23),'1800-01-01'),LABTRI.FECHA)) AS [FECHA TRIGLICERIDOS],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',IIF(LABTRI.VALOR IS NULL,ISNULL(CONVERT(VARCHAR(12),RESTRIGLI.VALOR),'NO EVALUADO'),LABTRI.VALOR)) AS [RESULTADO TRIGLICERIDOS],
IIF(POB.[EDAD (AÑOS)]<18,'1845-01-01',IIF(LABGLI.FECHA IS NULL,ISNULL(CONVERT(VARCHAR(10),CONVERT(DATE,CONVERT(NCHAR(10),FECGLI.VALOR),103),23),'1800-01-01'),LABGLI.FECHA)) AS [FECHA GLICEMIA],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',IIF(LABGLI.VALOR IS NULL,ISNULL(CONVERT(VARCHAR(12),RESGLI.VALOR),'NO EVALUADO'),LABGLI.VALOR)) AS [RESULTADO GLICEMIA],
IIF(POB.[SEXO PACIENTE]='MASCULINO' OR (POB.[EDAD (AÑOS)]<10 AND POB.[EDAD (AÑOS)]>17),'1845-01-01'
																					  ,IIF(LABHEM.FECHA IS NULL,ISNULL(CONVERT(VARCHAR(10),CONVERT(DATE,CONVERT(NCHAR(10),FECHEMA.VALOR),103),23),'1800-01-01'),LABHEM.FECHA)) AS [FECHA HEMATOCRITO],
IIF(POB.[SEXO PACIENTE]='MASCULINO' OR (POB.[EDAD (AÑOS)]<10 AND POB.[EDAD (AÑOS)]>17),'NO APLICA',IIF(LABHEM.VALOR IS NULL,ISNULL(RESHEMA.VALOR,'NO EVALUADO'),LABHEM.VALOR)) AS [RESULTADO HEMATOCRITO],
IIF(POB.[EDAD (AÑOS)]<29,'1845-01-01',ISNULL(CONVERT(VARCHAR(10),CONVERT(DATE,CONVERT(NCHAR(10),PROST.VALOR),103),23),'1800-01-01')) AS [FECHA BIOPSIA PROSTATA],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',ISNULL(CONVERT(VARCHAR(12),BXPROS.VALOR),'NO EVALUADO')) AS [RESULTADO BIOPSIA PROSTATA],
TACR.VALOR AS [RESULTADO TACTO RECTAL],
IIF(POB.[SEXO PACIENTE]='MASCULINO'OR POB.[EDAD (AÑOS)]<9,'NO APLICA',ISNULL(ECOMAMA.VALOR,'NO EVALUADO')) AS [ECO_MAMA],
ISNULL(FIS.NEOPERABD,'0') AS [PERIMETRO ABDOMINAL],
IIF(POB.[EDAD (AÑOS)]>=6,'0',ISNULL(FIS.PB,'0')) AS [PERIMETRO BRAQUIAL],
IIF(POB.[EDAD (AÑOS)]>=6,'0',ISNULL(FIS.NEOPERCEF,'0')) AS [PERIMETRO CEFALICO],
IIF(DATEDIFF(DAY,POB.[FECHA DE NACIMIENTO],POB.FECHISPAC)>=29,'0',ISNULL(FIS.REGSO2PAC,'0')) AS [TAMIZAJE_OXIMETRIA],
ISNULL(FIS.TENARTDIA,'0') AS [TA DIASTOLICA], 
ISNULL(FIS.TENARTSIS,'0') AS [TA SISTOLICA], 
IIF(DIAGRA.TIPODIAGRAMA=1 AND DIAGRA.FECHACREACION IS NOT NULL,CAST(DIAGRA.FECHACREACION AS DATE),'1800-01-01') AS ECOMAPA,
IIF(DIAGRA.TIPODIAGRAMA=2 AND DIAGRA.FECHACREACION IS NOT NULL,CAST(DIAGRA.FECHACREACION AS DATE),'1800-01-01') AS FAMILIOGRAMA,
IIF(POB.[SEXO PACIENTE]='MASCULINO'OR POB.[EDAD (AÑOS)]<10,'NO APLICA',IIF(LABEMB.VALOR IS NULL,ISNULL(GES.VALOR,'NO EVALUADO'),LABEMB.VALOR)) AS [EXAMEN CLINICO MAMA],--CAMBIAR POR PRUEBA DE EMBARAZO
OD.VALOR AS [AGUDEZA VISUAL O.D],
OI.VALOR AS [AGUDEZA VISUAL O.I],
CASE WHEN ESC2.RESULTADO BETWEEN '13' AND '16' THEN '1'
	 WHEN ESC2.RESULTADO BETWEEN '10' AND '12' THEN '2'
	 WHEN ESC2.RESULTADO <= '9' THEN '3'
	 WHEN ESC2.RESULTADO BETWEEN '17' AND '20' THEN '4' ELSE 'NO EVALUADO' END AS [TEST APGAR FAMILIAR],
CASE WHEN ESC60.RESULTADO <=3 THEN '5'
	 WHEN ESC60.RESULTADO BETWEEN '4' AND '26' THEN '6'
	 WHEN ESC60.RESULTADO >= '27' THEN '4' ELSE 'NO EVALUADO' END [TEST ASSIST],
CASE WHEN ESC54.RESULTADO <=7 THEN '5'
	 WHEN ESC54.RESULTADO BETWEEN '8' AND '15' THEN '6'
	 WHEN ESC54.RESULTADO BETWEEN '16' AND '19' THEN '3'
	 WHEN ESC54.RESULTADO >= '20' THEN '4' ELSE 'NO EVALUADO' END [TEST AUDIT],
IIF(POB.[EDAD (AÑOS)]<18,'1800-01-01',ISNULL(CONVERT(VARCHAR(10),CONVERT(DATE,CONVERT(NCHAR(10),AUT.VALOR),103),23),'1845-01-01')) AS [TEST AUTONOMIA],
IIF(POB.[EDAD (AÑOS)]<60,'NO APLICA',CASE WHEN ESC35.RESULTADO BETWEEN '96' AND '100' THEN '5'
										  WHEN ESC35.RESULTADO BETWEEN '91' AND '95' THEN '4'
										  WHEN ESC35.RESULTADO BETWEEN '60' AND '90' THEN '3'
										  WHEN ESC35.RESULTADO BETWEEN '16' AND '59' THEN '3'
										  WHEN ESC35.RESULTADO <= '15' THEN '1' ELSE 'NO EVALUADO' END) AS [TEST BARTHEL],
IIF(POB.[EDAD (AÑOS)]<18,'1845-01-01',ISNULL(CONVERT(VARCHAR(10),CONVERT(DATE,CONVERT(NCHAR(10),SSR.VALOR),103)),'1800-01-01')) AS [TEST DERECHOS SSR],
IIF(POB.[EDAD (AÑOS)]<60 ,'NO APLICA',CASE WHEN ESC19.RESULTADO <'10' THEN '2' 
										   WHEN ESC19.RESULTADO >='10' THEN '1'
										   WHEN ESC19.RESULTADO IS NULL THEN 'NO EVALUADO' END) AS [TEST EPOC],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',ISNULL(CASE WHEN RCV.VALOR ='001' THEN '5'  
												 WHEN RCV.VALOR ='002' THEN '6' 
												 WHEN RCV.VALOR ='003' THEN '4' 
												 WHEN RCV.VALOR ='004' THEN '3' ELSE 'EXTREMADA ALTA' END,'NO EVALUADO')) AS [TEST_ESTRATIFICACION_OMS_(CARDIOVASCULAR)],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',CASE WHEN ESC8.RESULTADO BETWEEN '0' AND '7' THEN '5' 
										  WHEN ESC8.RESULTADO BETWEEN '8' AND '11' THEN '6' 
										  WHEN ESC8.RESULTADO >'11' THEN ''
										  WHEN ESC8.RESULTADO IS NULL THEN 'NO EVALUADO' END) AS [TEST FINDRISK (METABOLICO)],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',CASE WHEN ESC6.RESULTADO <'10' THEN '5' 
										  WHEN ESC6.RESULTADO BETWEEN '10' AND '20' THEN '6'
										  WHEN ESC6.RESULTADO >'20' THEN '4'
										  WHEN ESC6.RESULTADO IS NULL THEN 'NO EVALUADO' END) AS [TEST FRAMINGHAM (CARDIOVASCULAR)],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',ISNULL(IDE.VALOR,'1800-01-01')) AS [TEST_IDENTIDAD],
IIF(POB.[EDAD (AÑOS)]<60,'NO APLICA',ISNULL(CASE WHEN ESC56.RESULTADO ='1' THEN '1'
												 WHEN ESC56.RESULTADO BETWEEN '6' AND '7' THEN '4'
												 WHEN ESC56.RESULTADO BETWEEN '4' AND '5' THEN '3'
												 WHEN ESC56.RESULTADO BETWEEN '2' AND '3' THEN '2'
												 WHEN ESC56.RESULTADO >'8' THEN '5' ELSE 'NO EVALUADO' END ,'NO EVALUADO')) AS [TEST LAWTON_BRODY (DEPENDENCIA)],
IIF(POB.[EDAD (AÑOS)]<60,'NO APLICA',ISNULL(CASE WHEN ESC55.RESULTADO='0' THEN '3' 
												 WHEN ESC55.RESULTADO BETWEEN '1' AND '2' THEN '1'
												 WHEN ESC55.RESULTADO BETWEEN '3' AND '5' THEN '2'END ,'NO EVALUADO')) AS [TEST LINDA FRIED (FRAGILIDAD)],
CASE WHEN DATEDIFF(MONTH, POB.[FECHA DE NACIMIENTO],POB.FECHISPAC) <16 THEN 'NO APLICA'
	 WHEN DATEDIFF(MONTH, POB.[FECHA DE NACIMIENTO],POB.FECHISPAC) >30 THEN 'NO APLICA'	
	 WHEN ESC52.RESULTADO BETWEEN '3' AND '7' THEN '6'
	 WHEN ESC52.RESULTADO BETWEEN '0' AND '2' THEN '5'
	 WHEN ESC52.RESULTADO >='8' THEN '4'
	 WHEN ESC52.RESULTADO IS NULL THEN 'NO EVALUADO' END [TEST_M_CHAT_(AUTISMO)],
IIF(POB.[EDAD (AÑOS)] BETWEEN 5 AND 15,'NO APLICA',CASE WHEN ESC43.RESULTADO ='0' THEN 'Negativo'
														WHEN ESC43.RESULTADO = '1'THEN 'Positivo' END) AS [TEST_RQC_S_MENTAL(5-15)],
IIF(POB.[EDAD (AÑOS)]>16,'NO APLICA',ISNULL(CASE WHEN ESC51.RESULTADO ='0' THEN 'Negativo'
												 WHEN ESC51.RESULTADO ='1'THEN 'Positivo' END,'NO EVALUADO')) AS [TEST_SQR_S_MENTAL(16+)],
IIF(POB.[EDAD (AÑOS)]<13 AND POB.[EDAD (AÑOS)]>17,'NO APLICA',ISNULL(CASE WHEN TANNER.RESULTADO ='1' THEN '1-Estadio 1'
																		  WHEN TANNER.RESULTADO ='2' THEN '2-Estadio 2'
																		  WHEN TANNER.RESULTADO ='3' THEN '3-Estadio 3'
																		  WHEN TANNER.RESULTADO ='4' THEN '4-Estadio 4'
																		  WHEN TANNER.RESULTADO ='5' THEN '5-Estadio 5' END,'NO EVALUADO')) AS [TEST TANNER],
IIF(POB.[EDAD (AÑOS)]<10,'NO APLICA',ISNULL(CASE WHEN COLP.VALOR='001' THEN '1'
												 WHEN COLP.VALOR='002' THEN '2' END,'NO EVALUADO')) AS COLPOSCOPIA,
IIF(POB.[EDAD (AÑOS)]<6 AND POB.[EDAD (AÑOS)]>12,'NO APLICA',ISNULL(CASE WHEN ESC20.RESULTADO BETWEEN '0' AND '19' THEN 'Discapacidad Intelectual Profunda'
																		 WHEN ESC20.RESULTADO BETWEEN '20' AND '49' THEN 'Discapacidad Intelectual Severa'
																		 WHEN ESC20.RESULTADO BETWEEN '50' AND '69' THEN 'Discapacidad Intelectual Moderada'
																		 WHEN ESC20.RESULTADO BETWEEN '70' AND '79' THEN 'Discapacidad Intelectual Leve'
																		 WHEN ESC20.RESULTADO BETWEEN '80' AND '89' THEN 'Limitrofe'
																		 WHEN ESC20.RESULTADO BETWEEN '90' AND '109' THEN 'Normal o Media'
																		 WHEN ESC20.RESULTADO BETWEEN '110' AND '119' THEN 'Superior'
																		 WHEN ESC20.RESULTADO BETWEEN '120' AND '139' THEN 'Muy Superior'
																		 WHEN ESC20.RESULTADO = '140' THEN 'Casi Genialidad'
																		 WHEN ESC20.RESULTADO = '150' THEN 'Genialidad'END,'NO EVALUADO')) AS [TEST GOODENOUGH],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',ISNULL(CASE WHEN ESC53.RESULTADO = '0' THEN 'Sin Riesgo'
  												 WHEN ESC53.RESULTADO = '1' OR ESC53.RESULTADO = '2' THEN 'Riesgo de Depresion' END,'NO EVALUADO')) AS [TEST WHOOLEY],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',ISNULL(CASE WHEN ESC57.RESULTADO BETWEEN '0' AND '10' THEN 'Sin Riesgo de Ansiedad'
												 WHEN ESC57.RESULTADO > '10' THEN 'Riesgo de Ansiedad' END,'NO EVALUADO')) AS [TEST GAD],
IIF(POB.[EDAD (AÑOS)]<18,'NO APLICA',ISNULL(CASE WHEN ESC42.RESULTADO BETWEEN '0' AND '46' THEN 'Ausencia de Sobrecarga'
												 WHEN ESC42.RESULTADO BETWEEN '47' AND '55' THEN 'Sobrecarga Ligera'
												 WHEN ESC42.RESULTADO >= '56' THEN 'Sobrecarga Intensa' END,'NO EVALUADO')) AS [TEST ZARIT],
IIF(POB.[EDAD (AÑOS)]<60,'NO APLICA',ISNULL(CASE WHEN ESC9.RESULTADO BETWEEN '0' AND '13' THEN 'Deterioro Grave'
												 WHEN ESC9.RESULTADO BETWEEN '14' AND '18' THEN 'Deterioro Moderado'
												 WHEN ESC9.RESULTADO BETWEEN '19' AND '23' THEN 'Deterioro Leve'
												 WHEN ESC9.RESULTADO > '23' THEN 'Normal'END,'NO EVALUADO')) AS [TEST MINIMENTAL],
CASE ESCVAL.RESULTADO WHEN 1 THEN 'POSITIVO' ELSE 'NEGATIVO' END AS [ESCALA VALE],
1 as 'CANTIDAD',
CAST(POB.FECHISPAC AS date) AS 'FECHA BUSQUEDA',
MONTH(POB.FECHISPAC) AS 'MES BUSQUEDA',
CONCAT(FORMAT(MONTH(POB.FECHISPAC), '00') ,' - ', 
	   CASE MONTH(POB.FECHISPAC) 
	        WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END) 'MES NOMBRE BUSQUEDA',
YEAR(POB.FECHISPAC) AS 'AÑO BUSQUEDA',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
#TBL_PACIENTES POB LEFT JOIN 
@TBL_FACTURACION GRU ON POB.IPCODPACI=GRU.IPCODPACI AND GRU.VARIABLE=1 LEFT JOIN --EDUCACION GRUPAL
@TBL_FACTURACION IND ON POB.IPCODPACI=IND.IPCODPACI AND IND.VARIABLE=2 LEFT JOIN --EDUCACION INDIVIDUAL
@TBL_FACTURACION FAM ON POB.IPCODPACI=FAM.IPCODPACI AND FAM.VARIABLE=3 LEFT JOIN --ESDUCACION FAMILIAR
@TBL_ANTECEDENTES LAC ON POB.IPCODPACI=LAC.IPCODPACI AND LAC.VARIABLE=1 AND POB.AÑO=LAC.AÑO AND POB.MES=LAC.MES LEFT JOIN --LACTANCIA MATERNA
@TBL_ANTECEDENTES ALC ON POB.IPCODPACI=ALC.IPCODPACI AND ALC.VARIABLE=2 AND POB.AÑO=ALC.AÑO AND POB.MES=ALC.MES LEFT JOIN --ALCOHOLISMO
@TBL_ANTECEDENTES SED ON SED.IPCODPACI=POB.IPCODPACI AND SED.VARIABLE=3 AND POB.AÑO=SED.AÑO AND POB.MES=SED.MES LEFT JOIN --SEDENTARISMO
@TBL_DISPENSACIONES PAR ON POB.IPCODPACI=PAR.[ID TERCERO/PACIENTE] AND POB.MES=MONTH(PAR.[FECHA DISPENSACION]) AND PAR.VARIABLE=1 LEFT JOIN --ANTIPARASITARIOS
@TBL_DISPENSACIONES MIC ON POB.IPCODPACI=MIC.[ID TERCERO/PACIENTE] AND POB.MES=MONTH(MIC.[FECHA DISPENSACION]) AND MIC.VARIABLE=2 LEFT JOIN --MICRONUTRIENTES
@TBL_DISPENSACIONES VIT ON POB.IPCODPACI=VIT.[ID TERCERO/PACIENTE] AND POB.MES=MONTH(VIT.[FECHA DISPENSACION]) AND VIT.VARIABLE=3 LEFT JOIN --VITAMINA A
@TBL_DISPENSACIONES HIE ON POB.IPCODPACI=HIE.[ID TERCERO/PACIENTE] AND POB.MES=MONTH(HIE.[FECHA DISPENSACION]) AND HIE.VARIABLE=4 LEFT JOIN --HIERRO
@TBL_DISPENSACIONES CAL ON POB.IPCODPACI=CAL.[ID TERCERO/PACIENTE] AND POB.MES=MONTH(CAL.[FECHA DISPENSACION]) AND CAL.VARIABLE=5 LEFT JOIN --CALCIO
@TBL_DISPENSACION_PRESERVATIVOS CON ON CON.[ID TERCERO/PACIENTE]=POB.IPCODPACI AND POB.AÑO=CON.AÑO AND POB.MES=CON.MES LEFT JOIN --DISPENSACIONES DE PRESERVATIVOS
@TBL_LABORATORIO LABCOL ON POB.IPCODPACI=LABCOL.IPCODPACI AND LABCOL.VARIABLE=1 AND POB.AÑO=LABCOL.AÑO AND POB.MES=LABCOL.MES AND LABCOL.AUTO=(SELECT MAX(A.AUTO) FROM @TBL_LABORATORIO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																																						  AND POB.MES=A.MES
																																																						  AND A.VARIABLE=1) LEFT JOIN --LABORATORIO COLESTEROL TOTAL
@TBL_LABORATORIO LABHDL ON POB.IPCODPACI=LABHDL.IPCODPACI AND LABHDL.VARIABLE=2 AND POB.AÑO=LABHDL.AÑO AND POB.MES=LABHDL.MES AND LABHDL.AUTO=(SELECT MAX(A.AUTO) FROM @TBL_LABORATORIO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																																						  AND POB.MES=A.MES
																																																						  AND A.VARIABLE=2) LEFT JOIN --LABORATORIO HDL
@TBL_LABORATORIO LABLDL ON POB.IPCODPACI=LABLDL.IPCODPACI AND LABLDL.VARIABLE=3 AND POB.AÑO=LABLDL.AÑO AND POB.MES=LABLDL.MES AND LABLDL.AUTO=(SELECT MAX(A.AUTO) FROM @TBL_LABORATORIO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																																						  AND POB.MES=A.MES
																																																						  AND A.VARIABLE=3) LEFT JOIN --LABORATORIO LDL
@TBL_LABORATORIO LABCRE ON POB.IPCODPACI=LABCRE.IPCODPACI AND LABCRE.VARIABLE=4 AND POB.AÑO=LABCRE.AÑO AND POB.MES=LABCRE.MES AND LABCRE.AUTO=(SELECT MAX(A.AUTO) FROM @TBL_LABORATORIO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																																						  AND POB.MES=A.MES
																																																						  AND A.VARIABLE=4) LEFT JOIN --LABORATORIO CREATININA
@TBL_LABORATORIO LABTRI ON POB.IPCODPACI=LABTRI.IPCODPACI AND LABTRI.VARIABLE=5 AND POB.AÑO=LABTRI.AÑO AND POB.MES=LABTRI.MES AND LABTRI.AUTO=(SELECT MAX(A.AUTO) FROM @TBL_LABORATORIO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																																						  AND POB.MES=A.MES
																																																						  AND A.VARIABLE=5) LEFT JOIN --LABORATORIO TRIGLICERIDOS
@TBL_LABORATORIO LABGLI ON POB.IPCODPACI=LABGLI.IPCODPACI AND LABGLI.VARIABLE=6 AND POB.AÑO=LABGLI.AÑO AND POB.MES=LABGLI.MES AND LABGLI.AUTO=(SELECT MAX(A.AUTO) FROM @TBL_LABORATORIO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																																						  AND POB.MES=A.MES
																																																						  AND A.VARIABLE=6) LEFT JOIN --LABORATORIO GLICEMIA
@TBL_LABORATORIO LABHEM ON POB.IPCODPACI=LABHEM.IPCODPACI AND LABHEM.VARIABLE=7 AND POB.AÑO=LABHEM.AÑO AND POB.MES=LABHEM.MES AND LABHEM.AUTO=(SELECT MAX(A.AUTO) FROM @TBL_LABORATORIO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																																						  AND POB.MES=A.MES
																																																						  AND A.VARIABLE=7) LEFT JOIN --LABORATORIO HEMATOCRITO
@TBL_LABORATORIO LABEMB ON POB.IPCODPACI=LABEMB.IPCODPACI AND LABEMB.VARIABLE=8 AND POB.AÑO=LABEMB.AÑO AND POB.MES=LABEMB.MES AND LABEMB.AUTO=(SELECT MAX(A.AUTO) FROM @TBL_LABORATORIO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																																						  AND POB.MES=A.MES
																																																						  AND A.VARIABLE=8) LEFT JOIN --LABORATORIO PRUEBA DE EMBARAZO
@TBL_EXAMEN_FISICO PROS ON POB.IPCODPACI=PROS.IPCODPACI AND PROS.VARIABLE=1 AND PROS.FOLIO=(SELECT MAX(A.FOLIO) FROM @TBL_EXAMEN_FISICO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																									  AND POB.MES=A.MES
																																									  AND A.VARIABLE=1) LEFT JOIN --EVALUCIÓN TAMIZAJE CANCER DE PROSTATA
@TBL_EXAMEN_FISICO TACR ON POB.IPCODPACI=TACR.IPCODPACI AND TACR.VARIABLE=24 AND PROS.FOLIO=(SELECT MAX(A.FOLIO) FROM @TBL_EXAMEN_FISICO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																									  AND POB.MES=A.MES
																																									  AND A.VARIABLE=24) LEFT JOIN --TACTO RECTAL
@TBL_EXAMEN_FISICO URO ON POB.IPCODPACI=URO.IPCODPACI AND URO.VARIABLE=2 AND URO.FOLIO=(SELECT MAX(A.FOLIO) FROM @TBL_EXAMEN_FISICO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																									  AND POB.MES=A.MES
																																									  AND A.VARIABLE=2) LEFT JOIN --UROANALISIS
@TBL_EXAMEN_FISICO COL ON POB.IPCODPACI=COL.IPCODPACI AND COL.VARIABLE=3 AND POB.AÑO=COL.AÑO AND POB.MES=COL.MES LEFT JOIN --FECHA COLESTEROL TOTAL
@TBL_EXAMEN_FISICO RESCOL ON POB.IPCODPACI=RESCOL.IPCODPACI AND RESCOL.VARIABLE=4 AND POB.AÑO=RESCOL.AÑO AND POB.MES=RESCOL.MES LEFT JOIN --RESULTADO COLESTEROL TOTAL
@TBL_EXAMEN_FISICO FECHDL ON POB.IPCODPACI=FECHDL.IPCODPACI AND FECHDL.VARIABLE=5 AND POB.AÑO=FECHDL.AÑO AND POB.MES=FECHDL.MES LEFT JOIN --FECHA HDL
@TBL_EXAMEN_FISICO RESHDL ON POB.IPCODPACI=RESHDL.IPCODPACI AND RESHDL.VARIABLE=6 AND POB.AÑO=RESHDL.AÑO AND POB.MES=RESHDL.MES LEFT JOIN --RESULTADO HDL
@TBL_EXAMEN_FISICO FECLDL ON POB.IPCODPACI=FECLDL.IPCODPACI AND FECLDL.VARIABLE=7 AND POB.AÑO=FECLDL.AÑO AND POB.MES=FECLDL.MES LEFT JOIN --FECHA LDL
@TBL_EXAMEN_FISICO RESLDL ON POB.IPCODPACI=RESLDL.IPCODPACI AND RESLDL.VARIABLE=8 AND POB.AÑO=RESLDL.AÑO AND POB.MES=RESLDL.MES LEFT JOIN --RESULTADO LDL
@TBL_EXAMEN_FISICO FECCREA ON POB.IPCODPACI=FECCREA.IPCODPACI AND FECCREA.VARIABLE=9 AND POB.AÑO=FECCREA.AÑO AND POB.MES=FECCREA.MES LEFT JOIN --FECHA CREATININA
@TBL_EXAMEN_FISICO RESCREA ON POB.IPCODPACI=RESCREA.IPCODPACI AND RESCREA.VARIABLE=10 AND POB.AÑO=RESCREA.AÑO AND POB.MES=RESCREA.MES LEFT JOIN --RESULTADO CREATININA
@TBL_EXAMEN_FISICO FECTRIGLI ON POB.IPCODPACI=FECTRIGLI.IPCODPACI AND FECTRIGLI.VARIABLE=11 AND POB.AÑO=FECTRIGLI.AÑO AND POB.MES=FECTRIGLI.MES  LEFT JOIN --FECHA TRIGLICERIDOS
@TBL_EXAMEN_FISICO RESTRIGLI ON POB.IPCODPACI=RESTRIGLI.IPCODPACI AND RESTRIGLI.VARIABLE=12 AND POB.AÑO=RESTRIGLI.AÑO AND POB.MES=RESTRIGLI.MES LEFT JOIN --RESULTADO TRIGLICERIDOS
@TBL_EXAMEN_FISICO FECGLI ON POB.IPCODPACI=FECGLI.IPCODPACI AND FECGLI.VARIABLE=13 AND FECGLI.FOLIO=(SELECT MAX(A.FOLIO) FROM @TBL_EXAMEN_FISICO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																												   AND POB.MES=A.MES
																																												   AND A.VARIABLE=13) LEFT JOIN-- FECHA DE GLICEMIA
@TBL_EXAMEN_FISICO RESGLI ON POB.IPCODPACI=RESGLI.IPCODPACI AND RESGLI.VARIABLE=14 AND RESGLI.FOLIO=(SELECT MAX(A.FOLIO) FROM @TBL_EXAMEN_FISICO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																												   AND POB.MES=A.MES
																																												   AND A.VARIABLE=14) LEFT JOIN--RESULTADO DE GLICEMIA
@TBL_EXAMEN_FISICO FECHEMA ON POB.IPCODPACI=FECHEMA.IPCODPACI AND FECHEMA.VARIABLE=15 AND FECHEMA.FOLIO=(SELECT MAX(A.FOLIO) FROM @TBL_EXAMEN_FISICO A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																																													   AND POB.MES=A.MES
																																													   AND A.VARIABLE=15) LEFT JOIN --FECHA DE HEMATOCRITO
@TBL_EXAMEN_FISICO RESHEMA ON POB.IPCODPACI=RESHEMA.IPCODPACI AND RESHEMA.VARIABLE=16 AND POB.AÑO=RESHEMA.AÑO AND POB.MES=RESHEMA.MES LEFT JOIN --RESULTADO DE HATOCRITO
@TBL_EXAMEN_FISICO PROST ON POB.IPCODPACI=PROST.IPCODPACI AND PROST.VARIABLE=17 AND POB.AÑO=PROST.AÑO AND POB.MES=PROST.MES LEFT JOIN -- FECHA PROSTATA
@TBL_EXAMEN_FISICO BXPROS ON POB.IPCODPACI=BXPROS.IPCODPACI AND BXPROS.VARIABLE=18 AND POB.AÑO=BXPROS.AÑO AND POB.MES=BXPROS.MES LEFT JOIN --RESULTADO PROSTATA
--CTE_EXAMEN_FISICO EXMAMA ON POB.IPCODPACI=EXMAMA.IPCODPACI AND BXPROS.VARIABLE=19 AND POB.AÑO=EXMAMA.AÑO AND POB.MES=EXMAMA.MES  LEFT JOIN -- EXAMEN CLINICO DE MAMÁ
@TBL_EXAMEN_FISICO GES ON POB.IPCODPACI=GES.IPCODPACI AND GES.VARIABLE=20 AND POB.AÑO=GES.AÑO AND POB.MES=GES.MES LEFT JOIN -- PRUEBA DE EMBARAZO
@TBL_EXAMEN_FISICO OD ON POB.IPCODPACI=OD.IPCODPACI AND OD.VARIABLE=22 AND POB.AÑO=OD.AÑO AND POB.MES=OD.MES LEFT JOIN --TAMIZAJE VISUAL OD
@TBL_EXAMEN_FISICO OI ON POB.IPCODPACI=OI.IPCODPACI AND OI.VARIABLE=23 AND POB.AÑO=OI.AÑO AND POB.MES=OI.MES LEFT JOIN --TAMIZAJE VISUAL OI
@TBL_NOTAS_ADMINISTRATIVAS ECOMAMA ON ECOMAMA.IPCODPACI=POB.IPCODPACI AND ECOMAMA.VARIABLE=1 LEFT JOIN --RESULTADO ECOGRAFIA DE MAMA
@TBL_NOTAS_ADMINISTRATIVAS EXAMAMA ON EXAMAMA.IPCODPACI=POB.IPCODPACI AND EXAMAMA.VARIABLE=2 LEFT JOIN --RESULTADO DE EXAMEN DE MAMA 
@TBL_NOTAS_ADMINISTRATIVAS COLP ON COLP.IPCODPACI=POB.IPCODPACI AND COLP.VARIABLE=3 AND POB.AÑO=COLP.AÑO AND POB.MES=COLP.MES LEFT JOIN --RESULTADO DE COPOSCOPIA
@TBL_NOTAS_ADMINISTRATIVAS RCV ON RCV.IPCODPACI=POB.IPCODPACI AND RCV.VARIABLE=4 LEFT JOIN-- RIESGO CARDIOVASCULAR
@TBL_REVICION_SISTEMA VIH2 ON POB.IPCODPACI=VIH2.ipcodpaci AND VIH2.VARIABLE=1  LEFT JOIN --Asesoría Pre y Post VIH
@TBL_REVICION_SISTEMA AUT ON POB.IPCODPACI=AUT.ipcodpaci AND AUT.VARIABLE=2 LEFT JOIN -- Fecha Test Autonomia
@TBL_REVICION_SISTEMA SSR ON POB.IPCODPACI=SSR.IPCODPACI AND SSR.VARIABLE=3  LEFT JOIN --Fecha Test Derechos sexuales y reproductivos
@TBL_REVICION_SISTEMA IDE ON POB.IPCODPACI=IDE.IPCODPACI AND IDE.VARIABLE=4  LEFT JOIN --Fecha Test de Identidad
@TBL_ALIMENTACION_SALUDABLE SAL ON POB.IPCODPACI=SAL.IPCODPACI AND POB.AÑO=SAL.AÑO AND POB.MES=SAL.MES LEFT JOIN --ALIMENTACIÓN SALUDABLE
#TBL_FISICO_DEPURADO FIS ON POB.IPCODPACI=FIS.IPCODPACI LEFT JOIN --EXAMEN FISICO
HCDIAGRAMAS DIAGRA ON  DIAGRA.IPCODPACI=POB.IPCODPACI AND CAST(FECHACREACION AS DATE) BETWEEN @FechaInicial AND @FechaFinal LEFT JOIN
@TBL_ESCALAS ESC2 ON ESC2.TIPOESCALA=2 AND POB.IPCODPACI=ESC2.IPCODPACI 
									   AND ESC2.FOLIO=(SELECT MAX(A.FOLIO) FROM @TBL_ESCALAS A WHERE POB.IPCODPACI=A.IPCODPACI AND POB.AÑO=A.AÑO 
																															   AND POB.MES=A.MES
																															   AND A.TIPOESCALA=2) LEFT JOIN
@TBL_ESCALAS ESC60 ON ESC60.TIPOESCALA=60 AND POB.IPCODPACI=ESC60.IPCODPACI AND POB.AÑO=ESC60.AÑO AND POB.MES=ESC60.MES LEFT JOIN
@TBL_ESCALAS ESC54 ON ESC54.TIPOESCALA=54 AND POB.IPCODPACI=ESC54.IPCODPACI AND POB.AÑO=ESC54.AÑO AND POB.MES=ESC54.MES LEFT JOIN
@TBL_ESCALAS ESC35 ON ESC35.TIPOESCALA=35 AND POB.IPCODPACI=ESC35.IPCODPACI AND POB.AÑO=ESC35.AÑO AND POB.MES=ESC35.MES LEFT JOIN
@TBL_ESCALAS ESC19 ON ESC19.TIPOESCALA=19 AND POB.IPCODPACI=ESC19.IPCODPACI AND POB.AÑO=ESC19.AÑO AND POB.MES=ESC19.MES LEFT JOIN
@TBL_ESCALAS ESC6 ON ESC6.TIPOESCALA=6 AND POB.IPCODPACI=ESC6.IPCODPACI AND POB.AÑO=ESC6.AÑO AND POB.MES=ESC6.MES LEFT JOIN
@TBL_ESCALAS ESC8 ON ESC8.TIPOESCALA=8 AND POB.IPCODPACI=ESC8.IPCODPACI AND POB.AÑO=ESC8.AÑO AND POB.MES=ESC8.MES LEFT JOIN
@TBL_ESCALAS ESC56 ON ESC56.TIPOESCALA=56 AND POB.IPCODPACI=ESC56.IPCODPACI AND POB.AÑO=ESC56.AÑO AND POB.MES=ESC56.MES LEFT JOIN
@TBL_ESCALAS ESC55 ON ESC55.TIPOESCALA=55 AND POB.IPCODPACI=ESC55.IPCODPACI AND POB.AÑO=ESC55.AÑO AND POB.MES=ESC55.MES LEFT JOIN
@TBL_ESCALAS ESC52 ON ESC52.TIPOESCALA=52 AND POB.IPCODPACI=ESC52.IPCODPACI AND POB.AÑO=ESC52.AÑO AND POB.MES=ESC52.MES LEFT JOIN
@TBL_ESCALAS ESC43 ON ESC43.TIPOESCALA=43 AND POB.IPCODPACI=ESC43.IPCODPACI AND POB.AÑO=ESC43.AÑO AND POB.MES=ESC43.MES LEFT JOIN
@TBL_ESCALAS ESC51 ON ESC51.TIPOESCALA=51 AND POB.IPCODPACI=ESC51.IPCODPACI AND POB.AÑO=ESC51.AÑO AND POB.MES=ESC51.MES LEFT JOIN
@TBL_ESCALAS TANNER ON TANNER.TIPOESCALA IN (11,12,13,14) AND POB.IPCODPACI=TANNER.IPCODPACI AND POB.AÑO=TANNER.AÑO AND POB.MES=TANNER.MES LEFT JOIN
@TBL_ESCALAS ESC20 ON ESC20.TIPOESCALA=20 AND POB.IPCODPACI=ESC20.IPCODPACI AND POB.AÑO=ESC20.AÑO AND POB.MES=ESC20.MES LEFT JOIN
@TBL_ESCALAS ESC53 ON ESC53.TIPOESCALA=53 AND POB.IPCODPACI=ESC53.IPCODPACI AND POB.AÑO=ESC53.AÑO AND POB.MES=ESC53.MES LEFT JOIN
@TBL_ESCALAS ESC57 ON ESC57.TIPOESCALA=57 AND POB.IPCODPACI=ESC57.IPCODPACI AND POB.AÑO=ESC57.AÑO AND POB.MES=ESC57.MES LEFT JOIN
@TBL_ESCALAS ESC42 ON ESC42.TIPOESCALA=42 AND POB.IPCODPACI=ESC42.IPCODPACI AND POB.AÑO=ESC42.AÑO AND POB.MES=ESC42.MES LEFT JOIN
@TBL_ESCALAS ESC9 ON ESC9.TIPOESCALA=9 AND POB.IPCODPACI=ESC9.IPCODPACI AND POB.AÑO=ESC9.AÑO AND POB.MES=ESC9.MES LEFT JOIN
@TBL_ESCALAS ESCVAL ON ESCVAL.TIPOESCALA=1010 AND POB.IPCODPACI=ESCVAL.IPCODPACI AND POB.AÑO=ESCVAL.AÑO AND POB.MES=ESCVAL.MES;

DROP TABLE #TBL_PACIENTES
DROP TABLE #TBL_FISICO_DEPURADO
--WHERE POB.IPCODPACI='1037236100'
END
