-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: SP_INV_DASHBOARD_SOLICITUDES_CON_EGRESO_CAMA
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE PROCEDURE [Report].[SP_INV_DASHBOARD_SOLICITUDES_CON_EGRESO_CAMA]
AS
WITH CTE_INGRESOS_CONSOLIDDOS
AS
(
   SELECT DISTINCT DIS.IPCODPACI ,DIS.NUMINGRES   FROM DBO.HCFARMEPC DIS
   WHERE ORDESTADO =1
   UNION ALL
   SELECT DISTINCT  DEV.IPCODPACI ,DEV.NUMINGRES  FROM DBO.HCDEVMEDC  DEV
   WHERE DEVESTADO =1
),
CTE_INGRESOS_UNICOS
AS
(
  SELECT DISTINCT * FROM CTE_INGRESOS_CONSOLIDDOS 
),
CTE_INGRESOS_UNICOS_DIS
AS
(
   SELECT DISTINCT DIS.IPCODPACI ,DIS.NUMINGRES   FROM DBO.HCFARMEPC DIS
   WHERE ORDESTADO =1
),
CTE_INGRESOS_UNICOS_DEV
AS
(
   SELECT DISTINCT  DEV.IPCODPACI ,DEV.NUMINGRES  FROM DBO.HCDEVMEDC  DEV
   WHERE DEVESTADO =1
),
CTE_ULTIMA_CAMAS_OCUPADA
----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
AS
(
    SELECT EGR.IPCODPACI ,EGR.NUMINGRES,EGR.FECINIEST ,EGR.FECFINEST ,EGR.CODICAMAS,CAM.NUMCAMHOS ,FUN.UFUDESCRI  ,FUN.UFUTIPUNI ,FUN.UFUCODIGO, EGR.CODTIPEST, TIP.DESTIPEST, EGR.GENESTLIQ
    FROM CHREGESTA EGR with (nolock)
    INNER JOIN
    (
       SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR with (nolock)
       INNER JOIN CTE_INGRESOS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES) AS G ON G.ID =EGR.ID
    INNER JOIN CHCAMASHO AS CAM with (nolock) ON CAM.CODICAMAS =EGR.CODICAMAS
    INNER JOIN DBO.INUNIFUNC AS FUN with (nolock) ON CAM.UFUCODIGO =FUN.UFUCODIGO
	INNER JOIN CHTIPESTA TIP ON TIP.CODTIPEST=EGR.CODTIPEST
),
CTE_ALTA_MEDICA
----CTE PARA IDENTIFICAR LA FECHA DE ALTA MEDICA DE LA HOSPITALIZACION
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECALTPAC, EGR.NUMEFOLIO, CASE EGR.ESTPACEGR WHEN 1 THEN 'VIVO' WHEN 2 THEN 'VIVO' WHEN 3 THEN 'MUERTO' 
WHEN 4 THEN 'VIVO' WHEN 5 THEN 'VIVO' ELSE 'VIVO' END 'ESTADO PACIENTE EGRESO', EGR.CODPROSAL
FROM HCREGEGRE EGR with (nolock)
INNER JOIN
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECALTPAC) 'ALTA MEDICA'
 FROM HCREGEGRE EGR with (nolock)
 INNER JOIN CTE_INGRESOS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES=EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.[ALTA MEDICA] =EGR.FECALTPAC
),
CTE_EGRESO_CAMA_HOS
----CTE PARA IDENTIFICAR LA FECHA DE EGRESO DE LA CAMA
AS
(
SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,EGR.FECEGRESO
FROM CHREGEGRE EGR
INNER JOIN
(
 SELECT EGR.NUMINGRES ,EGR.IPCODPACI ,MAX(EGR.FECEGRESO) EGRESO
 FROM CHREGEGRE EGR
 INNER JOIN CTE_INGRESOS_UNICOS AS UNI with (nolock) ON UNI.NUMINGRES =EGR.NUMINGRES
 GROUP BY EGR.NUMINGRES ,EGR.IPCODPACI ) AS G ON G.NUMINGRES=EGR.NUMINGRES AND G.IPCODPACI =EGR.IPCODPACI AND G.EGRESO =EGR.FECEGRESO
),
CTE_DISPENSACIONES
AS
(
  SELECT 'DISPENSACIONES' TIPO,DIS.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE' ,DIS.NUMINGRES 'INGRESO' ,DIS.FECHAORDE 'FECHA ORDEN',UNI.UFUDESCRI 'UNIDAD FUNCIONAL',
  USU.NOMMEDICO 'PROFESIONAL',CASE DIS.ORDTRANUE  WHEN 1 THEN 'TRATAMIENTO NUEVO' ELSE 'TRATAMIENTO ANTIGUO' END 'ORDENAMIENTO',
  CASE DIS.ORDENQUIMIO WHEN 1 THEN 'SI' ELSE 'NO' END 'QUIMIOTERAPIA',CASE WHEN DIS.IDAGEPROGQX IS NULL THEN 'NO' ELSE 'SI' END 'QUIRURGICO','PENDIENTE' 'ESTADO ORDEN'
  FROM DBO.HCFARMEPC AS DIS
  INNER JOIN CTE_INGRESOS_UNICOS_DIS AS ING ON ING.NUMINGRES =DIS.NUMINGRES 
  INNER JOIN DBO.INPACIENT AS  PAC ON PAC.IPCODPACI =DIS.IPCODPACI 
  INNER JOIN DBO.INUNIFUNC AS UNI ON UNI.UFUCODIGO =DIS.UFUCODIGO 
  INNER JOIN DBO.INPROFSAL  AS USU ON USU.CODPROSAL  =DIS.CODPROSAL 
  WHERE DIS.ORDESTADO =1
),
CTE_DEVOLUCIONES
AS
(
  SELECT 'DEVOLUCIONES' TIPO, DIS.IPCODPACI 'IDENTIFICACION',PAC.IPNOMCOMP 'PACIENTE'  ,DIS.NUMINGRES 'INGRESO' ,DIS.FECREGISTR 'FECHA ORDEN',UNI.UFUDESCRI 'UNIDAD FUNCIONAL',
  USU.NOMMEDICO 'PROFESIONAL',CASE DIS.ORIDEVMED WHEN 1 THEN 'TRASLADO' WHEN 2 THEN 'EGRESO' WHEN 3 THEN 'SUSPESION ENFERMERIA' WHEN 4 THEN 'ENFERMERIA'
  WHEN 5 THEN 'DEVOLUCION HOJA QX' WHEN 6 THEN 'DEVOLUTIVO PARCIAL'  END 'ORDENAMIENTO','NO' 'QUIMIOTERAPIA','' 'QUIRURGICO','PENDIENTE' 'ESTADO ORDEN'
  FROM DBO.HCDEVMEDC  AS DIS
  INNER JOIN CTE_INGRESOS_UNICOS_DIS AS ING ON ING.NUMINGRES =DIS.NUMINGRES 
  INNER JOIN DBO.INPACIENT AS  PAC ON PAC.IPCODPACI =DIS.IPCODPACI 
  INNER JOIN DBO.INUNIFUNC AS UNI ON UNI.UFUCODIGO =DIS.UFUCODIGO 
  INNER JOIN DBO.INPROFSAL  AS USU ON USU.CODPROSAL  =DIS.CODPROSAL 
  WHERE DIS.DEVESTADO  =1
)

SELECT DIS.*,CAM.FECEGRESO 'FECHA EGRESO CAMA' FROM CTE_DISPENSACIONES DIS
INNER JOIN CTE_EGRESO_CAMA_HOS CAM  ON DIS.INGRESO =CAM.NUMINGRES where DIS.[FECHA ORDEN] < DATEADD(HOUR,-24,GETDATE())
UNION ALL
SELECT DEV.*,CAM.FECEGRESO 'FECHA EGRESO CAMA' FROM CTE_DEVOLUCIONES AS DEV
INNER JOIN CTE_EGRESO_CAMA_HOS CAM  ON DEV.INGRESO =CAM.NUMINGRES where DEV.[FECHA ORDEN] < DATEADD(HOUR,-24,GETDATE())

