-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: SPAutorizacionesHospitalariasSolicitudes
-- Extracted by Fabric SQL Extractor SPN v3.9.0

    /*******************************************************************************************************************
Nombre:[Report].SPAutorizacionesHospitalariasSolicitudes
Tipo:Procedimeiento Almacendo
Observacion: Solicitudes de autorizaciones hospitalarias basada en la vista ViewAutorizacionesHospitalariasSolicitudes
Profesional: Nilsson Galindo
Fecha:17-10-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico:
Fecha:
Observaciones:
-------------------------------------------------------------------------------------------------------------------------------------
Version 3
Persona que modifico:
Fecha:
Observaciones:
***********************************************************************************************************************************/

CREATE PROCEDURE [Report].[SPAutorizacionesHospitalariasSolicitudes] 
@FechaInicial DATE,
@FechaFinal DATE
AS
BEGIN

--DECLARE @FechaInicial DATE='2023-10-17'
--DECLARE @FechaFinal DATE='2023-10-17'

-------FUNCIONES ELIMINADAS
--[Authorization].ObtenerFechaMaximaSolicitud
--dbo.ClaseCama
--dbo.CLaseHabitacion
--dbo.TipoAislamiento

------*****3. SCRIPS LISTADO DE PACIENTES DASHBOAR AUTORIZACIONES HOSPITALARIA - GESTION RESOLUCION 3047 - SOLICTUD LISTA DE SOLICITUDES v2*******-------


----DECLARAR VARIABLES TABLA
DECLARE @ObtenerFechaMaximaSolicitud TABLE (NUMINGRES CHAR(10),
											REGDATE DATETIME);
DECLARE @TBLAutorizacionesHospitalarias TABLE([CENTRO DE ATENCION] CHAR(100) NULL,
											  EGRESO CHAR(100) NULL,
											  ALERTA CHAR(10) NULL,
											  CAMA CHAR(50) NULL,
											  [CLASE HABITACION] CHAR(30) NULL,
											  [CLASE DE CAMA] CHAR(30) NULL,
											  IDENTIFICACION VARCHAR(25) NULL,
											  INGRESO CHAR(10) NULL,
											  AISLAMIENTO CHAR(15) NULL,
											  [TIPO ESTANCIA] CHAR (50) NULL,
											  PACIENTE CHAR (250) NULL,
											  CONSECUTIVO NUMERIC(18,0) NULL,
											  [MUESTRA ALERTA] BIT NULL,
											  [DESCRIPCION ESPECIALIDAD] CHAR (60),
											  [FECHA INGRESO] DATE NULL,
											  [UNIDAD FUNCIONAL ACTUAL] CHAR(80) NULL,
											  [FECHA EGRESO] VARCHAR(11) NULL,
											  [FECHA NACIMIENTO] DATE NULL,
											  EDAD INT NULL,
											  [ENTIDAD PACIENTE] CHAR(160) NULL,
											  ID INT NULL,
											  [FECHA INGRESO ESTANCIA] DATETIME NULL,
											  [FECHA EGRESO ESTANCIA] DATETIME NULL
											  );
DECLARE @TBLresolucion3047 TABLE([FECHA INFORME] DATETIME NULL,
								 [TIPO DOCUMENTO] CHAR(30) NULL,
								 ESTADO CHAR(30) NULL,
								 [ENVIADO POR] CHAR(50) NULL,
								 CODCONCEC NUMERIC(18,0) NULL,
								 LLAVE CHAR(10) NULL,
								 CODCENATE CHAR(10) NULL,
								 ID_RES CHAR(15) NULL,
								 IPCODPACI VARCHAR (25) NULL,
								 NUMINGRES CHAR(10) NULL,
								 CONSECU NUMERIC(18,0) NULL);
DECLARE @TBLResolucion3047Detallado TABLE([CODIGO CUPS] CHAR(20) NULL,
										  SERVICIO CHAR (255) NULL,
										  CANTIDAD INT NULL,
										  ESTADO CHAR (25) NULL,
										  [CANTIDAD AUTORIZADA] INT NULL,
										  [CONSECUTIVO INTERNO] NUMERIC (18,0) NULL,
										  IPCODPACI VARCHAR(25) NULL,
										  NUMINGRES CHAR(10) NULL);
DECLARE @EVENTOS TABLE (FECREGEVE DATETIME NULL,
						TIPREPENT CHAR (20) NULL,
						NOMUSUARI CHAR (200) NULL,
						ADAUTSERID INT NULL,
						IPCODPACI VARCHAR(25) NULL,
						NUMINGRES CHAR(10) NULL,
						ESTADO INT NULL);
-------ESTA TABLA REMPLAZA LA FUNCIÓN [Authorization].ObtenerFechaMaximaSolicitud
INSERT INTO @ObtenerFechaMaximaSolicitud
SELECT 
C.NUMINGRES,
A.FECREGIST AS REGDATE
FROM 
dbo.CHREGESTA C INNER JOIN
[Authorization].PatientConfirmation PC ON C.NUMINGRES=PC.AdmisionNumber AND CAST(C.FECINIEST AS DATE) BETWEEN @FechaInicial AND @FechaFinal INNER JOIN
dbo.ADAUTOSER A ON C.NUMINGRES=A.NUMINGRES AND PC.ConfirmationDate>A.FECREGIST
WHERE A.FECREGIST IS NOT NULL 
GROUP BY C.NUMINGRES,A.FECREGIST 
UNION ALL
SELECT 
C.NUMINGRES,
C.FECINIEST AS REGDATE
FROM 
dbo.CHREGESTA C INNER JOIN
[Authorization].PatientConfirmation PC ON (C.NUMINGRES=PC.AdmisionNumber) AND (C.FECINIEST>PC.ConfirmationDate) AND (CAST(C.FECINIEST AS DATE) BETWEEN @FechaInicial AND @FechaFinal)
WHERE C.FECINIEST IS NOT NULL
GROUP BY C.NUMINGRES,C.FECINIEST
UNION ALL 
SELECT 
C.NUMINGRES,
RC.FECINFORM AS REGDATE
FROM 
dbo.CHREGESTA C INNER JOIN
[Authorization].PatientConfirmation PC ON C.NUMINGRES=PC.AdmisionNumber AND CAST(C.FECINIEST AS DATE) BETWEEN @FechaInicial AND @FechaFinal INNER JOIN
dbo.ADAUTOSER A ON C.NUMINGRES=A.NUMINGRES INNER JOIN
dbo.ADAUTSERC RC ON C.NUMINGRES=RC.NUMINGRES AND A.CODCONCEC=RC.CODCONCEC AND PC.ConfirmationDate>RC.FECINFORM
WHERE RC.FECINFORM IS NOT NULL
GROUP BY C.NUMINGRES,RC.FECINFORM;


---AUTORIZACINES HOSPITALARIAS
INSERT INTO @TBLAutorizacionesHospitalarias
---CONSULTA CON CAMAS ASIGNADAS Y ESTANCIA ACTIVA
SELECT 
D.NOMCENATE AS [CENTRO DE ATENCION],
CASE WHEN I.NUMINGRES IS NULL THEN '3- Pacientes en la unidad' ELSE '2- Pacientes alta medica' END AS EGRESO,
CASE J.SERSUSCEP WHEN 1 THEN 'Alerta' ELSE 'Normal' END AS ALERTA, 
RTRIM(A.DESCCAMAS) AS Cama,
CASE A.CODCLAHAB WHEN 1 THEN 'Sala de Observacion'
				 WHEN 2 THEN 'Sala de Procedimientos'
				 WHEN 3 THEN 'Sala de Recuperacion' 
				 WHEN 4 THEN 'Habitacion 1 Cama'
				 WHEN 5 THEN 'Habitacion 2 Camas'
				 WHEN 6 THEN 'Habitacion 3 Camas'
				 WHEN 7 THEN 'Habitacion 4 Camas'
				 WHEN 8 THEN 'Suite'
				 WHEN 9 THEN 'Habitacion Especial'
				 WHEN 10 THEN 'UCI 11' ELSE 'Otro' END AS [CLASE HABITACION],
CASE A.CODCLACAM WHEN 1 THEN 'Observacion Urgencias'
				 WHEN 2 THEN 'Recuperacion Post-Quirurgico'
				 WHEN 3 THEN 'Hospitalaria' 
				 WHEN 4 THEN 'Cuna de Observación' END AS [CLASE DE CAMA], 
C.IPCODPACI AS IDENTIFICACION,
C.NUMINGRES AS INGRESO, 
CASE A.CODAISLAM WHEN 1 THEN 'Aerosol'
				 WHEN 2 THEN 'Contacto'
				 WHEN 3 THEN 'Estandar'
				 WHEN 4 THEN 'Gota' 
				 WHEN 5 THEN 'Protector' END AS AISLAMIENTO,
RTRIM(DESTIPEST) AS [TIPO ESTANCIA],
RTRIM(IPNOMCOMP) AS PACIENTE, 
A.CODCONCEC AS CONSECUTIVO,
CAST('' as bit) AS [MUESTRA ALERTA],
RTRIM(K.DESESPECI) AS [DESCRIPCION ESPECIALIDAD],
CAST(IFECHAING AS DATE) AS [FECHA INGRESO], 
RTRIM(J.UFUACTPAC) + ' - ' + RTRIM(U.UFUDESCRI) AS [UNIDAD FUNCIONAL ACTUAL],
CASE WHEN FECHEGRESO IS NULL THEN 'Sin egreso' ELSE CONVERT(VARCHAR, (FORMAT(FECHEGRESO, 'dd/MM/yyyy'))) END AS [FECHA EGRESO], 
CAST(H.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
FLOOR((CAST(CONVERT(VARCHAR(8), J.IFECHAING , 112) AS INT) - CAST(CONVERT(VARCHAR(8), H.IPFECNACI, 112) AS INT)) / 10000) AS EDAD,
RTRIM(P.CODENTIDA) + '-'+ RTRIM(P.NOMENTIDA) AS [ENTIDAD PACIENTE],
C.ID ,
C.FECINIEST AS [FECHA INGRESO ESTANCIA],
C.FECFINEST AS [FECHA EGRESO ESTANCIA]
FROM dbo.CHCAMASHO A INNER JOIN 
dbo.ADcenaten D ON A.CODCENATE=D.CODCENATE AND A.ESTADCAMA=2 INNER JOIN 
dbo.INUNIFUNC E ON A.UFUCODIGO=E.UFUCODIGO INNER JOIN 
dbo.CHREGESTA C ON A.CODICAMAS=C.CODICAMAS AND C.REGESTADO = 1 AND (CAST(C.FECINIEST AS DATE) BETWEEN @FechaInicial AND @FechaFinal) INNER JOIN 
dbo.CHTIPESTA G ON C.CODTIPEST=G.CODTIPEST INNER JOIN 
dbo.INPacient H ON C.IPCODPACI=H.IPCODPACI INNER JOIN 
dbo.ADINGRESO J ON C.NUMINGRES=J.NUMINGRES INNER JOIN 
dbo.INESPECIA K ON J.CODESPTRA=K.CODESPECI INNER JOIN 
dbo.INUNIFUNC U ON J.UFUACTPAC=U.UFUCODIGO LEFT JOIN 
dbo.INENTIDAD P ON H.CODENTIDA=P.CODENTIDA LEFT JOIN 
dbo.HCREGEGRE I ON C.NUMINGRES=I.NUMINGRES
WHERE NOT EXISTS (SELECT 1 FROM @ObtenerFechaMaximaSolicitud FN WHERE C.NUMINGRES=FN.NUMINGRES)
---------------------------------------------------------------------------------------------------------------------
UNION ALL
---------------------------------------------------------------------------------------------------------------------
--CONSULTA CON ESTADO DE CAMAS PENDIENTE POR LIQUIDAR Y SERVICIOS SUSCEPTIBLE DE AUTORIZACION.
SELECT
D.NOMCENATE AS [CENTRO DE ATENCION],
'4- Pacientes egresados' AS EGRESO,
CASE J.SERSUSCEP WHEN 1 THEN 'Alerta' ELSE 'Normal' END as ALERTA, 
RTRIM(A.DESCCAMAS) AS CAMA,
CASE A.CODCLAHAB WHEN 1 THEN 'Sala de Observacion'
				 WHEN 2 THEN 'Sala de Procedimientos'
				 WHEN 3 THEN 'Sala de Recuperacion' 
				 WHEN 4 THEN 'Habitacion 1 Cama'
				 WHEN 5 THEN 'Habitacion 2 Camas'
				 WHEN 6 THEN 'Habitacion 3 Camas'
				 WHEN 7 THEN 'Habitacion 4 Camas'
				 WHEN 8 THEN 'Suite'
				 WHEN 9 THEN 'Habitacion Especial'
				 WHEN 10 THEN 'UCI 11' ELSE 'Otro' END AS [CLASE HABITACION],
CASE A.CODCLACAM WHEN 1 THEN 'Observacion Urgencias'
				 WHEN 2 THEN 'Recuperacion Post-Quirurgico'
				 WHEN 3 THEN 'Hospitalaria' 
				 WHEN 4 THEN 'Cuna de Observación' END AS [CLASE DE CAMA],  
C.IPCODPACI AS IDENTIFICACION,
C.NUMINGRES AS INGRESO, 
CASE A.CODAISLAM WHEN 1 THEN 'Aerosol'
				 WHEN 2 THEN 'Contacto'
				 WHEN 3 THEN 'Estandar'
				 WHEN 4 THEN 'Gota' 
				 WHEN 5 THEN 'Protector' END AS AISLAMIENTO,
RTRIM(DESTIPEST) AS [TIPO ESTANCIA],
RTRIM(IPNOMCOMP) AS PACIENTE,
A.CODCONCEC AS CONSECUTIVO,
CAST('' as bit) AS [MUESTRA ALERTA],
RTRIM(K.DESESPECI) AS [DESCRIPCION ESPECIALIDAD],
CAST(IFECHAING AS DATE) AS [FECHA INGRESO],
RTRIM(J.UFUACTPAC) + ' - ' + RTRIM(U.UFUDESCRI) AS [UNIDAD FUNCIONAL ACTUAL],
CASE WHEN FECHEGRESO IS NULL THEN 'Sin egreso' ELSE CONVERT(VARCHAR, (FORMAT(FECHEGRESO, 'dd/MM/yyyy'))) END AS [FECHA EGRESO], 
CAST(H.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
FLOOR((CAST(CONVERT(VARCHAR(8), J.IFECHAING , 112) AS INT) - CAST(CONVERT(VARCHAR(8), H.IPFECNACI, 112) AS INT)) / 10000) AS EDAD,
RTRIM(P.CODENTIDA) + '-'+ RTRIM(P.NOMENTIDA) as [ENTIDAD PACIENTE],
C.ID,
C.FECINIEST AS [FECHA INGRESO ESTANCIA],
C.FECFINEST AS [FECHA EGRESO ESTANCIA]
FROM dbo.CHCAMASHO A
INNER JOIN dbo.ADcenaten D ON A.CODCENATE=D.CODCENATE
INNER JOIN dbo.INUNIFUNC E ON A.UFUCODIGO=E.UFUCODIGO
LEFT JOIN dbo.CHREGESTA C ON A.CODICAMAS=C.CODICAMAS AND C.REGESTADO = 2 AND (CAST(C.FECINIEST AS DATE) BETWEEN @FechaInicial AND @FechaFinal)
LEFT JOIN dbo.CHTIPESTA G ON G.CODTIPEST=C.CODTIPEST
LEFT JOIN dbo.INPacient H ON C.IPCODPACI=H.IPCODPACI
LEFT JOIN dbo.INENTIDAD P ON H.CODENTIDA=P.CODENTIDA
LEFT JOIN dbo.HCREGEGRE I ON C.NUMINGRES=I.NUMINGRES
LEFT JOIN dbo.ADINGRESO J ON C.NUMINGRES=J.NUMINGRES AND J.SERSUSCEP = 1
LEFT JOIN dbo.INESPECIA K ON J.CODESPTRA=K.CODESPECI
LEFT JOIN dbo.INUNIFUNC U ON J.UFUACTPAC=U.UFUCODIGO
AND NOT EXISTS (SELECT 1 FROM @ObtenerFechaMaximaSolicitud FN WHERE C.NUMINGRES=FN.NUMINGRES)
-------------------------------------------------------------------------------------------------------
UNION ALL
-------------------------------------------------------------------------------------------------------
--CONSULTA DE INGRESOS DE URGENCIAS SIN NUMERO DE CAMA, CON EL ESTADO DEL INGRESO SIN DEFINIR Y CON DESTINO DEL PACIENTE ('2','3','4','5','6','18','19','20','21')
SELECT
D.NOMCENATE AS [CENTRO DE ATENCION],
'1- Pacientes Urgencias con orden de hospitalizacion' as EGRESO,
CASE C.SERSUSCEP WHEN 1 THEN 'Alerta' ELSE 'Normal' END as Alerta,'' as Cama,'Sin Clase' AS [CLASE HABITACION],
'Sin Clase' AS 'Clase de Cama', 
C.IPCODPACI AS IDENTIFICACION,
C.NUMINGRES AS INGRESO, 
'' AS AISLAMIENTO, 
CASE HC.INDICAPAC WHEN '2' THEN 'Trasladar a Observacion'
				  WHEN '3' THEN 'Trasladar a Hospitalizacion'
				  WHEN '4' THEN 'Trasladar a UCI Adulto '
				  WHEN '5' THEN 'Trasladar a UCI Pediatrica'
				  WHEN '6' THEN 'Trasladar a UCI Neonatal'
				  WHEN '18' THEN 'Estancia Con la Madre'
				  WHEN '19' THEN 'U.Cuidado Intermedio'
				  WHEN '20' THEN 'U.Basica'
				  WHEN '21' THEN 'Hospitalización Pediatría' END AS [TIPO ESTANCIA],
RTRIM(IPNOMCOMP) AS PACIENTE,
0 AS CONSECUTIVO,
CAST('' as bit) AS [MUESTRA ALERTA],
RTRIM(K.DESESPECI) AS [DESCRIPCION ESPECIALIDAD],
CAST(IFECHAING AS DATE) AS [FECHA INGRESO],
RTRIM(C.UFUACTPAC) + ' - ' + RTRIM(U.UFUDESCRI) AS [UNIDAD FUNCIONAL ACTUAL],
CASE WHEN FECHEGRESO IS NULL THEN 'Sin egreso' ELSE CONVERT(VARCHAR, (FORMAT(FECHEGRESO, 'dd/MM/yyyy'))) END AS [FECHA EGRESO], 
CAST(H.IPFECNACI AS DATE) AS [FECHA NACIMIENTO],
FLOOR((CAST(CONVERT(VARCHAR(8), C.IFECHAING , 112) AS INT) - CAST(CONVERT(VARCHAR(8), H.IPFECNACI, 112) AS INT)) / 10000) AS EDAD,
RTRIM(P.CODENTIDA) + '-'+ RTRIM(P.NOMENTIDA) AS [ENTIDAD PACIENTE],
'' AS ID ,
C.IFECHAING AS FECINIEST ,
C.FECHEGRESO AS FECFINEST
FROM dbo.ADINGRESO C INNER JOIN 
dbo.ADcenaten D ON C.CODCENATE=D.CODCENATE AND (CAST(C.IFECHAING AS DATE) BETWEEN @FechaInicial AND @FechaFinal) AND C.CODICAMHO IS NULL AND C.IESTADOIN = '' INNER JOIN 
dbo.INUNIFUNC E ON C.UFUCODIGO=E.UFUCODIGO AND E.UFUTIPUNI = '1' INNER JOIN
dbo.INPacient H ON C.IPCODPACI=H.IPCODPACI INNER JOIN
dbo.INENTIDAD P ON H.CODENTIDA=P.CODENTIDA INNER JOIN
dbo.INESPECIA K ON C.CODESPTRA=K.CODESPECI INNER JOIN
dbo.INUNIFUNC U ON C.UFUACTPAC = U.UFUCODIGO AND U.UFUTIPUNI = 1 INNER JOIN
dbo.HCHISPACA HC ON C.NUMINGRES=HC.NUMINGRES AND HC.ID=(SELECT MAX(H.ID) FROM dbo.HCHISPACA H WHERE HC.NUMINGRES=H.NUMINGRES AND H.INDICAPAC IN ('2','3','4','5','6','18','19','20','21')) 
WHERE NOT EXISTS (SELECT 1 FROM @ObtenerFechaMaximaSolicitud FN WHERE C.NUMINGRES=FN.NUMINGRES);
-----------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO @TBLresolucion3047
-----******SCRIPS RESOLUCION 3047********------
---REGISTRO DE INCONSISTENCIAS
SELECT 
FECINFORM AS [FECHA INFORME],
'Inconsistencias' AS [TIPO DOCUMENTO],
CASE ESTTRANSA WHEN '1' THEN 'En Proceso de Envio' WHEN '2' THEN 'Envio Satisfactorio' WHEN '3' THEN 'Envio Fallido' END AS ESTADO,
RTRIM(NOMUSUARI) AS [ENVIADO POR],
CODCONCEC,'1-' + CAST(CODCONCEC AS CHAR) AS LLAVE,
A.CODCENATE,
'' AS ID_RES ,
A.IPCODPACI ,
'' AS 'NUMINGRES',
A.CODCONCEC 'CONSECU'
FROM dbo.ADINCBASD A INNER JOIN 
dbo.SEGusuaru B On A.CODUSUARI = B.CODUSUARI INNER JOIN 
@TBLAutorizacionesHospitalarias AS AUT ON AUT.Identificacion=A.IPCODPACI
UNION
---REGISTRO DE ATENCION INICIAL DE URGENCIAS
SELECT 
FECINFORM AS [FECHA INFORME],
'Atencion Inicial Urgencias' AS [TIPO DOCUMENTO],
CASE ESTTRANSA WHEN '1' THEN 'En Proceso de Envio' 
			   WHEN '2' THEN 'Intento de Envio 1' 
			   WHEN '3' THEN 'Intento de Envio 2' 
			   WHEN '4' THEN 'Intento de Envio 3' 
			   WHEN '5' THEN 'Intento de Envio DTL' 
			   WHEN '6' THEN 'Intento de Envio DTD' 
			   WHEN '7' THEN 'Envio Satisfactorio' END AS ESTADO,
RTRIM(NOMUSUARI) AS [ENVIADO POR],
CODCONCEC,'2-' + CAST(CODCONCEC AS CHAR) AS LLAVE,
--CODCONCEC AS 'Consecutivo Interno',
--NUMINFORM AS 'Numero Informe',
A.CODCENATE,
CASE C.TIPOTRAZA WHEN 1 THEN 'AI - ' + RTRIM(CONVERT(CHAR, C.ADAUTSERID)) WHEN 2 THEN 'AS - ' + RTRIM(CONVERT(CHAR, A.CODCONCEC)) END AS ID_RES,
A.IPCODPACI,
A.NUMINGRES,
A.CODCONCEC AS CONSECU
FROM dbo.ADATEINIU A INNER JOIN 
dbo.SEGusuaru B ON A.CODUSUARI=B.CODUSUARI INNER JOIN 
@TBLAutorizacionesHospitalarias AS AUT ON A.NUMINGRES=AUT.Ingreso LEFT OUTER JOIN 
dbo.ADAUTEVEN C ON A.CODCONCEC=C.ADAUTSERID
WHERE (C.TIPOTRAZA IS NULL OR C.TIPOTRAZA = 1)
UNION
---REGISTRO DE CABECERA DE AUTORIZACION DE SERVICIOS
SELECT 
FECINFORM AS [FECHA INFORME],
'Autorizacion de Servicios' AS [TIPO DOCUMENTO],
CASE ESTTRANSA WHEN '1' THEN 'En Proceso de Envio' 
			   WHEN '2' THEN 'Intento de Envio 1' 
			   WHEN '3' THEN 'Intento de Envio 2' 
			   WHEN '4' THEN 'Intento de Envio 3' 
			   WHEN '5' THEN 'Intento de Envio DTL' 
			   WHEN '6' THEN 'Intento de Envio DTD' 
			   WHEN '7' THEN 'Envio Satisfactorio' END AS ESTADO,
RTRIM(NOMUSUARI) AS [ENVIADO POR],
CODCONCEC,'3-' + CAST(CODCONCEC AS CHAR) AS LLAVE,
A.CODCENATE,'AS - ' + RTRIM(CONVERT(CHAR, A.CODCONCEC)) AS ID_RES,
A.IPCODPACI ,
A.NUMINGRES ,
A.CODCONCEC AS CONSECU
FROM dbo.ADAUTSERC A INNER JOIN 
dbo.SEGusuaru B ON A.CODUSUARI = B.CODUSUARI INNER JOIN 
@TBLAutorizacionesHospitalarias AS AUT ON AUT.Ingreso =A.NUMINGRES;
-------------------------------------------------------------------------------------------------------------------------------

INSERT INTO @TBLResolucion3047Detallado
SELECT
A.CODSERIPS AS 'Codigo CUPS',
RTRIM(DESSERIPS) AS Servicio,
CANSERIPS AS Cantidad,
CASE ESTATUSER WHEN '1' THEN 'Autorizado' 
			   WHEN '2' THEN 'No Autorizado' 
			   WHEN '3' THEN 'Pendiente de Autorizacion' END AS Estado,
A.CANSERAUT AS 'Cantidad Autorizada',
A.CODCONCEC AS 'Consecutivo Interno',
A.IPCODPACI,
A.NUMINGRES
FROM dbo.ADAUTSERD A
INNER JOIN dbo.INCUPSIPS B ON A.CODSERIPS=B.CODSERIPS
INNER JOIN @TBLresolucion3047 AS RES ON A.NUMINGRES=RES.NUMINGRES AND RES.CONSECU =A.CODCONCEC
UNION
-----TABLA DETALLE AUTORIZACION DE SERVICIOS MEDICAMENTOS
SELECT
A.CODSERIPS AS 'Codigo CUPS', 
RTRIM(DESPRODUC) AS Servicio, 
CANSERIPS AS Cantidad,
CASE ESTATUSER WHEN '1' THEN 'Autorizado' WHEN '2' THEN 'No Autorizado' WHEN '3' THEN 'Pendiente de Autorizacion' END AS Estado,
A.CANSERAUT AS 'Cantidad Autorizada', 
A.CODCONCEC AS 'Consecutivo Interno',
A.IPCODPACI,
A.NUMINGRES
FROM dbo.ADAUTSERD A
INNER JOIN dbo.IHLISTPRO B On A.CODSERIPS=B.CODPRODUC
INNER JOIN @TBLresolucion3047 AS RES ON A.NUMINGRES=RES.NUMINGRES AND RES.CODCONCEC =A.CODCONCEC;
-------------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO @EVENTOS
SELECT DISTINCT
FECREGEVE,
CASE TIPREPENT WHEN '1' THEN 'Llamada Telefonica' WHEN '2' THEN 'Envio FAX' WHEN '3' THEN 'Registro Pagina Web' END TIPREPENT,
RTRIM(NOMUSUARI) AS NOMUSUARI,
A.ADAUTSERID,
A.IPCODPACI,
A.NUMINGRES,
a.ESTADO
FROM
dbo.ADAUTEVEN A INNER JOIN 
dbo.SEGusuaru B ON A.CODUSUARI = B.CODUSUARI INNER JOIN 
dbo.INENTIDAD C ON A.CODENTIDA = C.CODENTIDA INNER JOIN 
@TBLresolucion3047 AS RES ON RES.NUMINGRES =A.NUMINGRES AND RES.CONSECU =A.ADAUTSERID LEFT OUTER JOIN 
dbo.ADAUTSERD E ON E.CODCONCEC = A.ADAUTSERID LEFT OUTER JOIN 
dbo.INCUPSIPS I ON I.CODSERIPS = E.CODSERIPS;
-----------------------------------------------------------------------------------------------------------------

SELECT --top 100
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 AUT.* ,
 RES.ID_RES,RES.[Fecha Informe],
 RES.[Tipo Documento], RES.Estado [Estado RESOL], 
 RES.[Enviado Por],DET.[Codigo CUPS],
 DET.Servicio,
 DET.Cantidad ,
 DET.[Cantidad Autorizada], 
 DET.Estado [Estado RESOL DET], 
 EVE.FECREGEVE 'Evento fecha Registro',
 EVE.TIPREPENT 'Evento Tipo de Reporte',
 EVE.NOMUSUARI 'Evento Enviado Por',
 EVE.ESTADO,
 CAST(AUT.[FECHA INGRESO ESTANCIA] AS date) AS 'FECHA BUSQUEDA',
 YEAR(AUT.[FECHA INGRESO ESTANCIA]) AS 'AÑO FECHA BUSQUEDA',
 MONTH(AUT.[FECHA INGRESO ESTANCIA]) AS 'MES FECHA BUSQUEDA',
 CASE MONTH(AUT.[FECHA INGRESO ESTANCIA]) 
	WHEN 1 THEN 'ENERO'
	WHEN 2 THEN 'FEBRERO'
	WHEN 3 THEN 'MARZO'
	WHEN 4 THEN 'ABRIL'
	WHEN 5 THEN 'MAYO'
	WHEN 6 THEN 'JUNIO'
	WHEN 7 THEN 'JULIO'
	WHEN 8 THEN 'AGOSTO'
	WHEN 9 THEN 'SEPTIEMBRE'
	WHEN 10 THEN 'OCTUBRE'
	WHEN 11 THEN 'NOVIEMBRE'
	WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
  FORMAT(DAY(AUT.[FECHA INGRESO ESTANCIA]), '00') AS 'DIA FECHA BUSQUEDA',
  CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM @TBLAutorizacionesHospitalarias AS AUT LEFT JOIN 
@TBLresolucion3047 AS RES ON AUT.Identificacion =RES.IPCODPACI LEFT JOIN 
@TBLResolucion3047Detallado AS DET ON RES.NUMINGRES=DET.NUMINGRES AND RES.CODCONCEC=DET.[Consecutivo Interno] LEFT JOIN 
@EVENTOS AS EVE ON RES.NUMINGRES=EVE.NUMINGRES AND RES.CONSECU=EVE.ADAUTSERID AND AUT.Identificacion = EVE.IPCODPACI


END


