-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: SPFacturacionNetaXEmpresa
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE PROCEDURE [Report].[SPFacturacionNetaXEmpresa] 
AS
 
DECLARE @ID_COMPANY VARCHAR(9)=(CAST(DB_NAME() AS VARCHAR(9)));
DECLARE @TIPOFACTURA INT,@TIPOFACTURA2 INT,@TIPOANULACION INT,@TIPOANULACION2 INT,@RECONOCIMIENTO INT;
DECLARE @LIBRO AS INT = (Select top(1) id from GeneralLedger.LegalBook where OfficialBook=1 and Status=1)

IF @ID_COMPANY='INDIGO001' BEGIN SET @TIPOFACTURA=1 SET @TIPOANULACION=106 SET @RECONOCIMIENTO=00 END --TOCANCIPA
IF @ID_COMPANY='INDIGO003' BEGIN SET @TIPOFACTURA=9 SET @TIPOANULACION=9 SET @RECONOCIMIENTO=00 END --RED HUMANA
IF @ID_COMPANY='INDIGO004' BEGIN SET @TIPOFACTURA=11 SET @TIPOANULACION=14 SET @RECONOCIMIENTO=00 END --UROCAQ
IF @ID_COMPANY='INDIGO006' BEGIN SET @TIPOFACTURA=60 SET @TIPOANULACION=61 SET @RECONOCIMIENTO=00 END --TOCANCIPA
IF @ID_COMPANY='INDIGO007' BEGIN SET @TIPOFACTURA=60 SET @TIPOANULACION=61 SET @RECONOCIMIENTO=00 END --HOSPITAL SAN JULINA
IF @ID_COMPANY='INDIGO008' BEGIN SET @TIPOFACTURA=60 SET @TIPOANULACION=61 SET @RECONOCIMIENTO=00 END --SAN VICENTE DEL PAUL
IF @ID_COMPANY='INDIGO009' BEGIN SET @TIPOFACTURA=60 SET @TIPOANULACION=61 SET @RECONOCIMIENTO=00 END --LA CANDELARIA
IF @ID_COMPANY='INDIGO010' BEGIN SET @TIPOFACTURA=60 SET @TIPOANULACION=61 SET @RECONOCIMIENTO=00 END --LA INMACULADA
IF @ID_COMPANY='INDIGO012' BEGIN SET @TIPOFACTURA=60 SET @TIPOANULACION=61 SET @RECONOCIMIENTO=00 END --IPS MEDICI
IF @ID_COMPANY='INDIGO013' BEGIN SET @TIPOFACTURA=60 SET @TIPOANULACION=61 SET @RECONOCIMIENTO=00 END --HOSPITAL SAN JOAQUIN
IF @ID_COMPANY='INDIGO014' BEGIN SET @TIPOFACTURA=60 SET @TIPOANULACION=61 SET @RECONOCIMIENTO=00 END --HOSPITAL SANTA MARIA
IF @ID_COMPANY='INDIGO015' BEGIN SET @TIPOFACTURA=60 SET @TIPOANULACION=61 SET @RECONOCIMIENTO=00 END --HOSPITAL HORACIO MUÑOZ
IF @ID_COMPANY='INDIGO023' BEGIN SET @TIPOFACTURA=110 SET @TIPOANULACION=14 SET @RECONOCIMIENTO=00 END --CASANARE
IF @ID_COMPANY='INDIGO024' BEGIN SET @TIPOFACTURA=9 SET @TIPOANULACION=10 SET @RECONOCIMIENTO=00 END --MIOCARDIO
IF @ID_COMPANY='INDIGO025' BEGIN SET @TIPOFACTURA=8 SET @TIPOANULACION=10 SET @RECONOCIMIENTO=00 END --JERSALUD
IF @ID_COMPANY='INDIGO022' BEGIN SET @TIPOFACTURA=8 SET @TIPOFACTURA2=29 SET @TIPOANULACION=9 SET @TIPOANULACION2=10 SET @RECONOCIMIENTO=00 END --MIOMED
IF @ID_COMPANY='INDIGO026' BEGIN SET @TIPOFACTURA=8 SET @TIPOFACTURA2=30 SET @TIPOANULACION=00 SET @RECONOCIMIENTO=00 END --MIOCARDIO
IF @ID_COMPANY='INDIGO030' BEGIN SET @TIPOFACTURA=23 SET @TIPOANULACION=24 SET @RECONOCIMIENTO=00 END --SAN ANDRES
IF @ID_COMPANY='INDIGO032' BEGIN SET @TIPOFACTURA=36 SET @TIPOANULACION=38 SET @RECONOCIMIENTO=00 END --MEDICALFLY
IF @ID_COMPANY='INDIGO033' BEGIN SET @TIPOFACTURA=11 SET @TIPOANULACION=13 SET @RECONOCIMIENTO=00 END --MEDISALUD
IF @ID_COMPANY='INDIGO035' BEGIN SET @TIPOFACTURA=8 SET @TIPOANULACION=9 SET @RECONOCIMIENTO=00 END --IMO
IF @ID_COMPANY='INDIGO036' BEGIN SET @TIPOFACTURA=116 SET @TIPOANULACION=14 SET @RECONOCIMIENTO=53 END --HOMI
IF @ID_COMPANY='INDIGO038' BEGIN SET @TIPOFACTURA=14 SET @TIPOANULACION=17 SET @RECONOCIMIENTO=53 END --AEROMAS
IF @ID_COMPANY='INDIGO039' BEGIN SET @TIPOFACTURA=50 SET @TIPOANULACION=51 SET @RECONOCIMIENTO=55 END --CIEGOS Y SORDOS
IF @ID_COMPANY='INDIGO040' BEGIN SET @TIPOFACTURA=29 SET @TIPOANULACION=30 SET @RECONOCIMIENTO=92 END--HOSPITAL SAN JOSE
IF @ID_COMPANY='INDIGO041' BEGIN SET @TIPOFACTURA=68 SET @TIPOANULACION=69 SET @RECONOCIMIENTO=73 END; --SAN FRANCISCO
IF @ID_COMPANY='INDIGO043' BEGIN SET @TIPOFACTURA=27 SET @TIPOANULACION=26 SET @RECONOCIMIENTO=46 END; --SAN ANTONIO DE PITALITO



WITH CTE_FACTURADOS_TOTAL_UNICOS_NETO
AS
(
	SELECT DISTINCT YEAR(JV.VoucherDate) 'AÑO',MONTH(JV.VoucherDate) 'MES' ,sum(CAST(JVD.CreditValue AS NUMERIC(20,0))) VALOR
	FROM GeneralLedger.JournalVouchers JV 
	INNER JOIN GeneralLedger .JournalVoucherDetails AS JVD  ON JVD.IdAccounting =JV.Id
	INNER  JOIN Billing.Invoice AS F  ON F.Id =JV.EntityId
	INNER JOIN GeneralLedger.JournalVoucherTypes AS JVT WITH (NOLOCK) ON JVT.Id =JV.IdJournalVoucher
	WHERE YEAR(JV.VoucherDate) >=2024 AND JV.LegalBookId =@LIBRO AND jv.EntityName IN ('Invoice','DocumentInvoiceProductSales') --,'DocumentInvoiceProductSales'
	AND IdJournalVoucher IN (@TIPOFACTURA,@TIPOFACTURA2) AND JV.Detail like 'Factura%'
	GROUP BY year(JV.VoucherDate), MONTH(JV.VoucherDate)

  UNION ALL
    
	SELECT DISTINCT YEAR(JV.VoucherDate) 'AÑO',MONTH(JV.VoucherDate) 'MES' ,-sum(CAST(JVD.CreditValue AS NUMERIC(20,0))) VALOR
	FROM GeneralLedger.JournalVouchers JV 
	INNER JOIN GeneralLedger .JournalVoucherDetails AS JVD  ON JVD.IdAccounting =JV.Id
	INNER  JOIN Billing .Invoice AS F  ON F.Id =JV.EntityId
	INNER JOIN GeneralLedger.JournalVoucherTypes AS JVT WITH (NOLOCK) ON JVT.Id =JV.IdJournalVoucher
	WHERE YEAR(JV.VoucherDate) >=2024 AND JV.LegalBookId =@LIBRO AND jv.EntityName IN ('Invoice','DocumentInvoiceProductSales') --,'DocumentInvoiceProductSales'
	AND IdJournalVoucher in (@TIPOANULACION,@TIPOANULACION2) AND JV.Detail like 'Anulación%'
	--AND JV.EntityCode='HSJS52150'
	GROUP BY year(JV.VoucherDate), MONTH(JV.VoucherDate)

 UNION ALL

   	SELECT DISTINCT YEAR(JV.VoucherDate) 'AÑO',MONTH(JV.VoucherDate) 'MES' ,sum(CAST(JVD.CreditValue AS NUMERIC(20,0))) VALOR
	FROM 
	GeneralLedger.JournalVouchers JV 
	INNER JOIN GeneralLedger.JournalVoucherDetails AS JVD ON JV.Id=JVD.IdAccounting
	INNER JOIN Billing.InvoiceEntityCapitated AS IEC ON IEC.Id=JV.EntityId
	INNER JOIN Billing.Invoice AS F ON F.Id=IEC.InvoiceId	
	INNER JOIN GeneralLedger.JournalVoucherTypes AS JVT ON JV.IdJournalVoucher=JVT.Id
	INNER JOIN GeneralLedger.MainAccounts AS MA ON JVD.IdMainAccount=MA.Id
	WHERE YEAR(JV.VoucherDate) >=2024 AND JV.LegalBookId =@LIBRO AND jv.EntityName='InvoiceEntityCapitated' AND IdJournalVoucher IN (@TIPOFACTURA,@TIPOFACTURA2)
	GROUP BY  year(JV.VoucherDate), MONTH(JV.VoucherDate)

  UNION ALL

   	SELECT  DISTINCT YEAR(JV.VoucherDate) 'AÑO',MONTH(JV.VoucherDate) 'MES' ,-sum(CAST(JVD.CreditValue AS NUMERIC(20,0))) VALOR
	FROM 
	GeneralLedger.JournalVouchers JV 
	INNER JOIN GeneralLedger.JournalVoucherDetails AS JVD ON JV.Id=JVD.IdAccounting
	INNER JOIN Billing.InvoiceEntityCapitated AS IEC ON IEC.Id=JV.EntityId
	INNER JOIN Billing.Invoice AS F ON F.Id=IEC.InvoiceId	
	INNER JOIN GeneralLedger.JournalVoucherTypes AS JVT ON JV.IdJournalVoucher=JVT.Id
	INNER JOIN GeneralLedger.MainAccounts AS MA ON JVD.IdMainAccount=MA.Id
	WHERE YEAR(JV.VoucherDate) >=2024 AND JV.LegalBookId =@LIBRO AND jv.EntityName ='InvoiceEntityCapitated' AND IdJournalVoucher in (@TIPOANULACION,@TIPOANULACION2)
	GROUP BY  year(JV.VoucherDate), MONTH(JV.VoucherDate)

)--,

select @ID_COMPANY AS ID_COMPANY,(SELECT TOP(1) INDNUMIDE FROM DBO.INEMPRESU) NIT, (SELECT TOP(1) INDNOMEMP FROM DBO.INEMPRESU) EMMPRESA ,AÑO,MES,SUM(VALOR) 'VALOR FACTURADO NETO',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
from CTE_FACTURADOS_TOTAL_UNICOS_NETO
GROUP BY AÑO,MES

--SELECT * FROM GeneralLedger.LegalBook

--SELECT * FROM GeneralLedger.JournalVouchers JV WHERE jv.EntityName IN ('InvoiceEntityCapitated') AND YEAR(VOUCHERDATE)>=2024
--SELECT * FROM GeneralLedger.JournalVouchers JV WHERE jv.EntityName IN ('Invoice') AND YEAR(VOUCHERDATE)>=2024
--SELECT * FROM GeneralLedger.JournalVouchers JV WHERE jv.EntityName IN ('DocumentInvoiceProductSales') AND YEAR(VOUCHERDATE)>=2024

--SELECT * FROM Common.OperatingUnit U

--SELECT * FROM DBO.INEMPRESU

--SELECT * FROM GeneralLedger.JournalVoucherDetails  WHERE  IdAccounting=1484547
--1484316
--1484547