-- Workspace: SQLServer
-- Item: INDIGO040 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: SPInventarioHistoricoPrescripcion
-- Extracted by Fabric SQL Extractor SPN v3.9.0






    /*******************************************************************************************************************
Nombre: [Report].[SPInventarioHistoricoPrescripcion]
Tipo:Procedimiento Almacenado
Observacion:Historico de ordenes y despensaciones de medicamentos e insumos.
Profesional: Nilsson Miguel Galindo Lopez
Fecha:19-12-2023
---------------------------------------------------------------------------
Modificaciones
_____________________________________________________________________________
Version 2
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:2024-11-05
Ovservaciones:Se convierte el autonumerico de la hoja de medicamento, en char ya que estaba en numeric
--------------------------------------------------------------------------------
Version 3
Persona que modifico:
Observacion:
Fecha:
***********************************************************************************************************************************/
--exec [Report].[SPInventarioHistoricoPrescripcion]'2024-10-01','2024-10-31'



CREATE PROCEDURE [Report].[SPInventarioHistoricoPrescripcion]
@FechaInicial date,
@FechaFinal date
AS
BEGIN

--DECLARE @FechaInicial DATE = '2024-10-01';
--DECLARE @FechaFinal DATE = '2024-10-31';	

/**************************************************************************************************
------------------------SE CREAN LAS VARIABLES TABLA------------------------------------------------
****************************************************************************************************/

DECLARE @TBL_INGRESO AS TABLE([NUMINGRES] [char](10) NOT NULL,
					   [FECHEGRESO] [datetime] NULL,
					   [DESCCAMAS] [char](50) NOT NULL);

DECLARE @TBL_DEVOLUCION_DISPENSACION AS TABLE([DispensacionDetalleId] [int] NOT NULL,
											  [CodigoDevolucionDispensacion] [varchar](20) NOT NULL,
											  [FechaDevolucion] [datetime] NULL,
											  [Regente] [char](60) NOT NULL,
											  [Cantidad] [int] NOT NULL,
											  [NOMMEDICO] [char](60) NULL,
											  [PROFESION] [varchar](19) NULL,
											  [FECREGISTR] [datetime] NULL);

DECLARE @TBL_DETALLE_FARMACIA AS TABLE ([CODCONCEC] [numeric](18, 0) NOT NULL,
										[NUMINGRES] [char](10) NOT NULL,
										[CODPRODUC] [char](20) NOT NULL,
										[CODUNIMED] [varchar](20) NULL,
										[ID] [int] NOT NULL,
										[DOSISPROD] [numeric](18, 2) NULL,
										[FRECUENCI] [int] NULL,
										[UNIFRECUE] [char](1) NULL,
										[DURACIDOS] [char](20) NOT NULL,
										[CANPEDPRO] [int] NOT NULL,
										[CANTAPLICADA] [nvarchar](4) NULL);

DECLARE @TBL_LIQUIDOS AS TABLE([ID] [int] NOT NULL,
							   [FECHA] [datetime] NOT NULL,
							   [ESTADO] [varchar](19) NOT NULL,
							   [NUMINGRES] [char](10) NOT NULL,
							   [UFUCODIGO] [char](10) NOT NULL,
							   [NUMEFOLIO] [nchar](10) NOT NULL,
							   [IPCODPACI] [varchar](25) NOT NULL,
							   [CODPRODUC] [char](20) NOT NULL,
							   [DOSIS] [numeric](18, 2) NULL,
							   [MEDIDA] [varchar](20) NULL,
							   [FRECUENCIA] [int] NULL,
							   [TIEMPO] [varchar](7) NULL,
							   [ADMINISTRACION] [varchar](11) NOT NULL,
							   [DURACION] [char](20) NOT NULL,
							   [TRATAMIENTO] [int] NULL,
							   [CANTIDAD] [int] NOT NULL,
							   [PROFESIONAL] [char](20) NOT NULL);

--TABLA DE INGRESO, DONDE TAMBIEN NOS VA AYUDAR PARA APLICAR EL FILTRO DE LA FECHA
INSERT INTO @TBL_INGRESO
SELECT ING.NUMINGRES,ING.FECHEGRESO,CAM.DESCCAMAS
FROM 
dbo.ADINGRESO ING 
INNER JOIN dbo.CHCAMASHO CAM ON ING.CODCAMACT=CAM.CODICAMAS
WHERE ING.IFECHAING BETWEEN @FechaInicial AND @FechaFinal
GROUP BY ING.NUMINGRES,ING.FECHEGRESO,CAM.DESCCAMAS;

--DEVOLUCION DE DISPENSACION TENIENDO EN CUENTA LA TABLA DE INGRESO
INSERT INTO @TBL_DEVOLUCION_DISPENSACION
SELECT
DISD.Id AS DispensacionDetalleId,
DD.Code AS CodigoDevolucionDispensacion,
DD.ConfirmationDate as FechaDevolucion,
USU.NOMUSUARI AS Regente,
DDD.Quantity AS Cantidad,
--in v3
PRO.NOMMEDICO,
CASE PRO.TIPPROFES WHEN 1 THEN 'Medico General' 
				   WHEN 2 THEN 'Medico Especialista' 
				   WHEN 3 THEN 'Enfermera'
				   WHEN 4 THEN 'Auxiliar Enfermeria' 
				   WHEN 16 THEN 'Terapeuta'
				   WHEN 21 THEN 'Instrumentador' END PROFESION,
FECREGISTR
--fn v3
FROM
Inventory.PharmaceuticalDispensingDevolutionDetail DDD 
INNER JOIN Inventory.PharmaceuticalDispensingDetailBatchSerial BAT ON DDD.PharmaceuticalDispensingDetailBatchSerialId=BAT.Id 
INNER JOIN Inventory.PharmaceuticalDispensingDetail DISD ON BAT.PharmaceuticalDispensingDetailId=DISD.Id 
INNER JOIN Inventory.PharmaceuticalDispensing DIS ON DISD.PharmaceuticalDispensingId=DIS.Id
INNER JOIN @TBL_INGRESO ING ON DIS.AdmissionNumber=ING.NUMINGRES
INNER JOIN Inventory.PharmaceuticalDispensingDevolution DD ON DDD.PharmaceuticalDispensingDevolutionId=DD.Id AND DD.Status=2 
INNER JOIN dbo.SEGusuaru USU ON DD.ConfirmationUser=USU.CODUSUARI 
LEFT JOIN dbo.HCDEVMEDC DEV ON DD.EntityId=DEV.CODCONCEC 
LEFT JOIN dbo.INPROFSAL PRO ON DEV.CODPROSAL=PRO.CODPROSAL;
---------------------------------------------------------------------------------------------------------------
--DETALLE DE FARMACIA, PARA QUE PODAMOS DETECTAR LA ORDEN INICIAL CUANDO LA SOLICITUD LA REALIZA ENFERMERIA.
INSERT INTO @TBL_DETALLE_FARMACIA
SELECT 
D.CODCONCEC,A.NUMINGRES,A.CODPRODUC,D.CODUNIMED,D.ID,
ISNULL(A.DOSISPROD,D.DOSISPROD)AS DOSISPROD,A.FRECUENCI,A.UNIFRECUE,A.DURACIDOS,D.CANPEDPRO,
K.CANPRODUCT AS CANTAPLICADA
FROM 
@TBL_INGRESO ING
INNER JOIN dbo.HCFARMEPC C ON ING.NUMINGRES=C.NUMINGRES
INNER JOIN dbo.HCFARMEPD D ON C.CODCONCEC=D.CODCONCEC
INNER JOIN dbo.HCPRESCRA A ON A.NUMINGRES= D.NUMINGRES and A.CODPRODUC=D.CODPRODUC and (C.FECHAORDE>=A.FECINIDOS and C.FECHAORDE<=A.FECFINDOS)
LEFT JOIN dbo.HCHOJAMED H ON A.CODCONCEC=H.CONSECPRESCRA
LEFT JOIN dbo.HCKARDPAC k ON CONVERT(CHAR(10),H.CONSECUTI)=K.HCCTRAPLN AND  K.TIPORIREG=11
UNION ALL
SELECT 
D.CODCONCEC,A.NUMINGRES,A.CODPRODUC,D.CODUNIMED,D.ID,
ISNULL(A.DOSISPROD,D.DOSISPROD)AS DOSISPROD,A.FRECUENCI,A.UNIFRECUE,A.DURACIDOS,D.CANPEDPRO,
K.CANPRODUCT AS CANTAPLICADA
FROM 
@TBL_INGRESO ING
INNER JOIN dbo.HCFARMEPC C ON ING.NUMINGRES=C.NUMINGRES
INNER JOIN dbo.HCFARMEPD D ON C.CODCONCEC=D.CODCONCEC
INNER JOIN dbo.HCPRESCRA A ON A.NUMINGRES=D.NUMINGRES AND A.CODPRODUC=D.CODPRODUC AND C.FECHAORDE>=A.FECINIDOS and A.PREESTADO NOT IN (2,4,5,6,7)
LEFT JOIN dbo.HCHOJAMED H ON A.CODCONCEC=H.CONSECPRESCRA
LEFT JOIN dbo.HCKARDPAC k ON CONVERT(CHAR(10),H.CONSECUTI)=K.HCCTRAPLN AND  K.TIPORIREG=11
----------------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO @TBL_LIQUIDOS
SELECT 
FAR.ID,
ISNULL(FAR.FECINIDOS,A.FECHAINIC) AS FECHA,
CASE A.PREESTADO WHEN 1 THEN 'TRATAMIENTO NUEVO'ELSE 'TRATAMIENTO ANTIGUO'END AS ESTADO,
A.NUMINGRES,
A.UFUCODIGO,
A.NUMEFOLIO,A.IPCODPACI,
FAR.CODPRODUC,
FAR.DOSISPROD AS DOSIS,
CASE WHEN D.UNIMEDBOL IS NOT NULL THEN D.UNIMEDBOL
	 WHEN D.UNIMEDINF IS NOT NULL THEN D.UNIMEDINF 
	 WHEN D.UNIMEDDIL IS NOT NULL THEN D.UNIMEDDIL END AS MEDIDA,
FAR.FRECUENCI AS FRECUENCIA,
CASE FAR.UNIFRECUE WHEN 1 THEN 'MINUTOS'
				   WHEN 2 THEN 'HORAS'
				   WHEN 3 THEN 'DIAS' END AS TIEMPO,
'INTRAVENOSA' as ADMINISTRACION,
ISNULL(D.DURACIINF,'Dosis Unica')as DURACION,
CASE D.DURACIINF WHEN 'Tratamiento Continuo' THEN DATEDIFF(DAY,A.FECHAINIC,GETDATE()) END AS TRATAMIENTO,
D.CANPROCAL AS CANTIDAD,
A.CODPROSAL AS PROFESIONAL
FROM 
@TBL_INGRESO ING
INNER JOIN dbo.HCFARMEPD FAR ON ING.NUMINGRES=FAR.NUMINGRES
INNER JOIN dbo.HCINFLIQA A ON FAR.IdSourceTable=A.CONSECUTI AND FAR.SourceTable='HCINFLIQA' 
INNER JOIN dbo.HCINFLIQD D ON A.CODCONCEC=D.CODCONCEC;

/************************************************************************************************************
------------------------------CONSULTA DE LAS ORDENES FARMACEUTICAS-----------------------------------------
*************************************************************************************************************/
SELECT DISTINCT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
FAR.FECHAORDE AS [FECHA DE LA ORDEN],
CASE FAR.ORDTRANUE WHEN 1 THEN 'TRATAMIENTO NUEVO' 
				   WHEN 2 THEN 'TRATAMIENTO ANTIGUO'
				   WHEN 3 THEN 'CODIGO AZUL' END AS [TIPO DE ORDEN],
FAR.NUMINGRES AS [NUMERO DE INGRESO],
FAR.NUMEFOLIO AS [NUMERO DE FOLIO],
PAC.IPCODPACI AS [ID PACIENTE],
PAC.IPNOMCOMP AS PACIENTE,
FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
ING.DESCCAMAS AS CAMA,
FARD.CODPRODUC AS [CODIGO DE PRODUCTO],
INV.Name AS PRODUCTO,
TIP.Name AS [TIPO DE PRODUCTO],
GFA.Name AS [GRUPO FARMACOLOGICO],
ISNULL(FARD.DOSISPROD,'0.00') AS DOSIS,
UM.Name AS MEDIDA,
FARD.FRECUENCI AS FRECUENCIA,
CASE UNIFRECUE WHEN 1 THEN 'MINUTOS'
			   WHEN 2 THEN 'HORAS'
			   WHEN 3 THEN 'DIAS' END AS TIEMPO,
ADM.NAME AS [VIA DE ADMINISTRACION],
DURACIDOS AS DURACION,
FARD.CANPEDPRO AS [CANTIDAD FORMULADA],
CASE HC.CONCILIACIONMED WHEN 'TRUE' THEN 'SI' 
						WHEN 'FALSE' THEN 'NO' END AS [CONCILIACION MEDICAMENTOSA],
DISD.Quantity AS [CANTIDAD DISPENSADA],
CAST(FARD.CANTAPLICADA as nvarchar) AS [CANTIDAD APLICADA],
DD.Cantidad AS [CANTIDAD DEVUELTA],
DIS.Code AS [CODIGO DE DISPENSACION],
DIS.ConfirmationDate AS [FECHA Y HORA DISPENSACION],
USU.NOMUSUARI AS [USUARIO CONFIRMACION],
--in v3
DD.NOMMEDICO AS [USUARIO DE DEVOLUCION],
DD.PROFESION AS [CARGO DE DEVOLUCION],
DD.FECREGISTR AS [REGISTRO DE DEVOLUCIÓN],
--fn v3
DD.CodigoDevolucionDispensacion AS [CODIGO DEVOLUCION DISPENSACION],
DD.FechaDevolucion AS [FECHA Y HORA DEVOLUCION DISPENSACION],
DD.Regente AS [USUARIO CONFIRMA DEVOLUCION],
ENT.NOMENTIDA AS ENTIDAD,
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro'
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado' 
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [GRUPO DE ATENCION],
CASE WHEN ING.FECHEGRESO IS NULL THEN 'HOSPITALIZADO' ELSE 'EGRESADO' END AS ESTADO,
PRO.NOMMEDICO AS [PROFESIONAL QUE ORDENO],
INV.ProductCost AS [COSTO PROMEDIO],
CAST(FAR.FECHAORDE AS date) AS 'FECHA BUSQUEDA',
YEAR(FAR.FECHAORDE) AS 'AÑO FECHA BUSQUEDA',
MONTH(FAR.FECHAORDE) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(FAR.FECHAORDE), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(FAR.FECHAORDE), '00') ,' - ', 
CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE'END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
dbo.HCFARMEPC FAR INNER JOIN
@TBL_DETALLE_FARMACIA FARD ON FAR.CODCONCEC=FARD.CODCONCEC INNER JOIN
DBO.INPACIENT PAC ON FAR.IPCODPACI=PAC.IPCODPACI INNER JOIN
DBO.INUNIFUNC FUN ON FAR.UFUCODIGO=FUN.UFUCODIGO INNER JOIN
Inventory.ATC ATC ON FARD.CODPRODUC=ATC.Code INNER JOIN
Inventory.InventoryProduct INV ON ATC.ID= INV.ATCId AND INV.STATUS=1 INNER JOIN
Inventory.ProductType TIP ON INV.ProductTypeId=TIP.Id LEFT JOIN
Inventory.PharmacologicalGroup GFA ON ATC.PharmacologicalGroupId=GFA.Id LEFT JOIN
Inventory.InventoryMeasurementUnit UM ON FARD.CODUNIMED=UM.Code LEFT JOIN
Inventory.AdministrationRoute ADM ON ATC.AdministrationRouteId=ADM.Id LEFT JOIN
Inventory.PharmaceuticalDispensingDetail DISD ON FARD.ID=DISD.EntityId LEFT JOIN
Inventory.PharmaceuticalDispensing DIS ON DISD.PharmaceuticalDispensingId=DIS.Id AND DIS.Status=2 LEFT JOIN
dbo.SEGusuaru USU ON DIS.ConfirmationUser=USU.CODUSUARI LEFT JOIN
dbo.INENTIDAD ENT ON PAC.CODENTIDA=ENT.CODENTIDA LEFT JOIN
@TBL_INGRESO ING ON FAR.NUMINGRES=ING.NUMINGRES LEFT JOIN
dbo.INPROFSAL PRO ON FAR.CODPROSAL=PRO.CODPROSAL LEFT JOIN
@TBL_DEVOLUCION_DISPENSACION DD ON DISD.Id=DD.DispensacionDetalleId LEFT JOIN
dbo.HCHISPACA HC ON FAR.NUMINGRES=HC.NUMINGRES AND FAR.NUMEFOLIO=HC.NUMEFOLIO

UNION ALL

-----------mezclas y liquidos---------------------------------------------------
SELECT DISTINCT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
FAR.FECHA AS [FECHA DE LA ORDEN],
FAR.ESTADO AS [TIPO DE ORDEN],
FAR.NUMINGRES AS [NUMERO DE INGRESO],
FAR.NUMEFOLIO AS [NUMERO DE FOLIO],
PAC.IPCODPACI AS [ID PACIENTE],
PAC.IPNOMCOMP AS PACIENTE,
FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
ING.DESCCAMAS AS CAMA,
FAR.CODPRODUC AS [CODIGO DE PRODUCTO],
INV.Name AS PRODUCTO,
'MEZCLAS/LIQUIDOS' AS [TIPO DE PRODUCTO],
GFA.Name AS [GRUPO FARMACOLOGICO],
FAR.DOSIS,
UM.Name AS MEDIDA,
FAR.FRECUENCIA,
FAR.TIEMPO,
ADM.NAME AS [VIA DE ADMINISTRACION],
FAR.DURACION,
FAR.CANTIDAD AS [CANTIDAD FORMULADA],
NULL AS [CONCILIACION MEDICAMENTOSA],
DISD.Quantity AS [CANTIDAD DISPENSADA],
CAST(0 as nvarchar) AS [CANTIDAD APLICADA],
DD.Cantidad AS [CANTIDAD DEVUELTA],
DIS.Code AS [CODIGO DE DISPENSACION],
DIS.ConfirmationDate AS [FECHA Y HORA DISPENSACION],
USU.NOMUSUARI AS [USUARIO CONFIRMACION],
DD.NOMMEDICO AS [USUARIO DE DEVOLUCION],
DD.PROFESION AS [CARGO DE DEVOLUCION],
DD.FECREGISTR AS [REGISTRO DE DEVOLUCIÓN],
DD.CodigoDevolucionDispensacion AS [CODIGO DEVOLUCION DISPENSACION],
DD.FechaDevolucion AS [FECHA Y HORA DEVOLUCION DISPENSACION],
DD.Regente AS [USUARIO CONFIRMA DEVOLUCION],
ENT.NOMENTIDA AS ENTIDAD,
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro'
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado' 
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [GRUPO DE ATENCION],
CASE WHEN ING.FECHEGRESO IS NULL THEN 'HOSPITALIZADO' ELSE 'EGRESADO' END AS ESTADO,
PRO.NOMMEDICO AS [PROFESIONAL QUE ORDENO],
INV.ProductCost AS [COSTO PROMEDIO],
CAST(FAR.FECHA AS date) AS 'FECHA BUSQUEDA',
YEAR(FAR.FECHA) AS 'AÑO FECHA BUSQUEDA',
MONTH(FAR.FECHA) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(FAR.FECHA) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(FAR.FECHA), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(FAR.FECHA), '00') ,' - ', 
CASE MONTH(FAR.FECHA) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE'END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
@TBL_LIQUIDOS FAR INNER JOIN
DBO.INPACIENT PAC ON FAR.IPCODPACI=PAC.IPCODPACI INNER JOIN
DBO.INUNIFUNC FUN ON FAR.UFUCODIGO=FUN.UFUCODIGO INNER JOIN
Inventory.ATC ATC ON FAR.CODPRODUC=ATC.CODE INNER JOIN
Inventory.InventoryProduct INV ON ATC.ID=INV.ATCID AND INV.STATUS=1 INNER JOIN
Inventory.ProductType TIP ON INV.ProductTypeId=TIP.Id AND TIP.Name='MEDICAMENTOS' LEFT JOIN
Inventory.PharmacologicalGroup GFA ON ATC.PharmacologicalGroupId=GFA.Id LEFT JOIN
Inventory.InventoryMeasurementUnit UM ON FAR.MEDIDA=UM.Code LEFT JOIN
Inventory.AdministrationRoute ADM ON ATC.AdministrationRouteId=ADM.Id LEFT JOIN
Inventory.PharmaceuticalDispensingDetail DISD ON FAR.ID=DISD.EntityId AND EntityName='HCFARMEPD' LEFT JOIN
Inventory.PharmaceuticalDispensing DIS ON DISD.PharmaceuticalDispensingId=DIS.Id AND DIS.Status=2 LEFT JOIN
dbo.SEGusuaru USU ON DIS.ConfirmationUser=USU.CODUSUARI LEFT JOIN
dbo.INENTIDAD ENT ON PAC.CODENTIDA=ENT.CODENTIDA LEFT JOIN
@TBL_INGRESO ING ON FAR.NUMINGRES=ING.NUMINGRES LEFT JOIN
dbo.INPROFSAL PRO ON FAR.PROFESIONAL=PRO.CODPROSAL LEFT JOIN
@TBL_DEVOLUCION_DISPENSACION DD ON DISD.Id=DD.DispensacionDetalleId  
UNION ALL 
-----------------------------------SELECT CUANDO LAS SOLICITUDES SON SUMINISTROS MEDICOS----------------------------------
SELECT DISTINCT
CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
FAR.FECHAORDE AS [FECHA DE LA ORDEN],
'' AS [TIPO DE ORDEN],
FAR.NUMINGRES AS [NUMERO DE INGRESO],
FAR.NUMEFOLIO AS [NUMERO DE FOLIO],
PAC.IPCODPACI AS [ID PACIENTE],
PAC.IPNOMCOMP AS PACIENTE,
FUN.UFUDESCRI AS [UNIDAD FUNCIONAL],
ING.DESCCAMAS AS CAMA,
FARD.CODPRODUC AS [CODIGO DE PRODUCTO],
INV.Name AS PRODUCTO,
'SUMINISTROS' AS [TIPO DE PRODUCTO],
'' AS [GRUPO FARMACOLOGICO],
ISNULL(FARD.DOSISPROD,'0.00') AS DOSIS,
'' AS MEDIDA,
FARD.FRECUENCI AS FRECUENCIA,
CASE UNIFRECUE WHEN 1 THEN 'MINUTOS'
			   WHEN 2 THEN 'HORAS'
			   WHEN 3 THEN 'DIAS' END AS TIEMPO,
'' AS [VIA DE ADMINISTRACION],
DURACIDOS AS DURACION,
FARD.CANPEDPRO AS [CANTIDAD FORMULADA],
NULL AS [CONCILIACION MEDICAMENTOSA],
DISD.Quantity AS [CANTIDAD DISPENSADA],
CAST(0 as nvarchar) AS [CANTIDAD APLICADA],
DD.Cantidad AS [CANTIDAD DEVUELTA],
DIS.Code AS [CODIGO DE DISPENSACION],
DIS.ConfirmationDate AS [FECHA Y HORA DISPENSACION],
USU.NOMUSUARI AS [USUARIO CONFIRMACION],
DD.NOMMEDICO AS [USUARIO DE DEVOLUCION],
DD.PROFESION AS [CARGO DE DEVOLUCION],
DD.FECREGISTR AS [REGISTRO DE DEVOLUCIÓN],
DD.CodigoDevolucionDispensacion AS [CODIGO DEVOLUCION DISPENSACION],
DD.FechaDevolucion AS [FECHA Y HORA DEVOLUCION DISPENSACION],
DD.Regente AS [USUARIO CONFIRMA DEVOLUCION],
ENT.NOMENTIDA AS ENTIDAD,
CASE PAC.IPTIPOPAC WHEN 1 THEN 'Contributivo'
				   WHEN 2 THEN 'Subsidiado'
				   WHEN 3 THEN 'Vinculado'
				   WHEN 4 THEN 'Particular'
				   WHEN 5 THEN 'Otro'
				   WHEN 6 THEN 'Desplazado Reg. Contributivo'
				   WHEN 7 THEN 'Desplazado Reg. Subsidiado' 
				   WHEN 8 THEN 'Desplazado No Asegurado' END AS [GRUPO DE ATENCION],
CASE WHEN ING.FECHEGRESO IS NULL THEN 'HOSPITALIZADO' ELSE 'EGRESADO' END AS ESTADO,
PRO.NOMMEDICO AS [PROFESIONAL QUE ORDENO],
INV.ProductCost AS [COSTO PROMEDIO],
CAST(FAR.FECHAORDE AS date) AS 'FECHA BUSQUEDA',
YEAR(FAR.FECHAORDE) AS 'AÑO FECHA BUSQUEDA',
MONTH(FAR.FECHAORDE) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA',
FORMAT(DAY(FAR.FECHAORDE), '00') AS 'DIA FECHA BUSQUEDA',
CONCAT(FORMAT(MONTH(FAR.FECHAORDE), '00') ,' - ', 
CASE MONTH(FAR.FECHAORDE) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE'END) MES_LABEL_BUSQUEDA,
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
@TBL_INGRESO ING 
INNER JOIN dbo.HCFARMEPC FAR ON ING.NUMINGRES=FAR.NUMINGRES 
INNER JOIN dbo.HCFARMEPD FARD ON FAR.CODCONCEC=FARD.CODCONCEC 
INNER JOIN DBO.INPACIENT PAC ON FAR.IPCODPACI=PAC.IPCODPACI 
INNER JOIN DBO.INUNIFUNC FUN ON FAR.UFUCODIGO=FUN.UFUCODIGO 
INNER JOIN Inventory.InventorySupplie INS ON FARD.CODPRODUC=INS.CODE 
INNER JOIN Inventory.InventoryProduct INV ON INS.ID=INV.SupplieId AND INV.STATUS=1
LEFT JOIN Inventory.PharmaceuticalDispensingDetail DISD ON FARD.ID=DISD.EntityId 
LEFT JOIN Inventory.PharmaceuticalDispensing DIS ON DISD.PharmaceuticalDispensingId=DIS.Id AND DIS.Status=2 
LEFT JOIN dbo.SEGusuaru USU ON DIS.ConfirmationUser=USU.CODUSUARI 
LEFT JOIN dbo.INENTIDAD ENT ON PAC.CODENTIDA=ENT.CODENTIDA 
LEFT JOIN dbo.INPROFSAL PRO ON FAR.CODPROSAL=PRO.CODPROSAL 
LEFT JOIN @TBL_DEVOLUCION_DISPENSACION DD ON DISD.Id=DD.DispensacionDetalleId  

END
