-- Workspace: SQLServer
-- Item: INDIGO043 [SQL]
-- ItemId: SPN
-- Schema: Report
-- Object: HDSAP_AGENDAMIENTOVSHOSPITALIZACION
-- Extracted by Fabric SQL Extractor SPN v3.9.0



CREATE PROCEDURE [Report].[HDSAP_AGENDAMIENTOVSHOSPITALIZACION]  
	@FECHA_INICIAL AS DATETIME
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE 	@FECHA_FINAL AS DATETIME=DATEADD(DAY,1,@FECHA_INICIAL);
WITH CENSO
AS 
(
SELECT	UF.UFUDESCRI AS Servicio, C.DESCCAMAS AS Cama, I.NUMINGRES AS NumeroIngreso, 
        I.IFECHAING AS FechaIngreso, DATEDIFF(d, I.IFECHAING, GETDATE()) AS DiasHospital, E.IPCODPACI AS Identificación, P.IPNOMCOMP AS NombrePaciente, 
        RTRIM(LTRIM(dbo.Edad(TRY_CAST(P.IPFECNACI AS DATE), TRY_CAST(GETDATE() AS DATE)))) AS Edad, 
        CASE WHEN P.IPSEXOPAC = '1' THEN 'Masculino' WHEN P.IPSEXOPAC = '2' THEN 'Femenino' END AS Sexo, D.CODDIAGNO AS CodDiag, V.NOMDIAGNO AS DiagnosticoPpal, 
        P.IPDIRECCI AS Direccion, P.IPTELEFON AS Telefono, P.IPTELMOVI AS Movil, CONVERT(varchar, E.FECINIEST, 100) AS IngresoCama, 
        DATEDIFF(d, E.FECINIEST, GETDATE()) AS DiasCama, A.NOMENTIDA AS Entidad, I.IAUTORIZA AS NumeroAutorizacion, I.IOBSERVAC AS Observaciones 
    FROM   dbo.CHCAMASHO AS C  INNER JOIN 
        dbo.ADCENATEN AS CA  ON CA.CODCENATE = C.CODCENATE INNER JOIN 
        dbo.INUNIFUNC AS UF  ON UF.UFUCODIGO = C.UFUCODIGO INNER JOIN 
        dbo.CHREGESTA AS E  ON E.CODICAMAS = C.CODICAMAS AND E.REGESTADO = 1 INNER JOIN 
        dbo.CHTIPESTA AS TE  ON TE.CODTIPEST = E.CODTIPEST INNER JOIN 
        dbo.ADINGRESO AS I  ON I.NUMINGRES = E.NUMINGRES INNER JOIN 
        dbo.INPACIENT AS P  ON P.IPCODPACI = E.IPCODPACI INNER JOIN
        dbo.INENTIDAD AS A  ON A.CODENTIDA = I.CODENTIDA LEFT OUTER JOIN 
        dbo.INDIAGNOP AS D  ON D.NUMINGRES = E.NUMINGRES AND D.IPCODPACI = E.IPCODPACI AND D.CODDIAPRI = 1 LEFT OUTER JOIN 
        dbo.INDIAGNOS AS V  ON V.CODDIAGNO = D.CODDIAGNO 
    WHERE (C.CODCENATE = '001') AND (C.ESTADCAMA = 2)
),
UE
AS
(
SELECT ES.IPCODPACI, ES.NUMINGRES AS NumIngreso, ES.FECINIEST AS InicioEstancia, 
		CASE ES.FECFINEST WHEN '19000101' THEN '30000101' ELSE ES.FECFINEST END FinEstancia, DIAG.NombreDx AS DiagnosticoPpalEstancia,
		Qx.DescripcionQxPpal, Qx.FechaQx 
	FROM dbo.CHREGESTA AS ES  LEFT OUTER JOIN
		.HCQXINFOR AS Q  ON Q.NUMINGRES=ES.NUMINGRES OUTER APPLY
			(SELECT TOP(1) Q.NUMINGRES AS NumIngreso , Q.IPCODPACI AS IdPaciente, Q.CODSERIPS AS CodProced, 
				PR.DESSERIPS AS DescripcionQxPpal, Q.FECHORFIN AS FechaQx
				FROM .HCQXINFOR AS Q  
					INNER JOIN . INCUPSIPS AS PR  ON Q.CODSERIPS = PR.CODSERIPS
				WHERE Q.NUMINGRES=ES.NUMINGRES ORDER BY Q.FECHORINI DESC) AS Qx OUTER APPLY
			(SELECT TOP(1) CIE.NOMDIAGNO AS NombreDx
				FROM dbo.INDIAGNOH AS DX  
					INNER JOIN dbo.INDIAGNOS AS CIE  ON DX.CODDIAGNO=CIE.CODDIAGNO
				WHERE DX.CODDIAPRI=1 AND DX.NUMINGRES=ES.NUMINGRES
				ORDER BY DX.NUMEFOLIO DESC) AS DIAG
	WHERE ES.FECFINEST='19000101' OR ES.FECFINEST > DATEADD(DAY,-45,CURRENT_TIMESTAMP)
)
SELECT       
	dbo.TipDocR256(INP.IPTIPODOC) AS TipoDocumen, INP.IPCODPACI AS Identificacion, RTRIM(INP.IPNOMCOMP) + CONCAT(' (', INP.IPTELEFON + ' - ', INP.IPTELMOVI,')') AS  Nombre, 
	US.NOMUSUARI AS UsuarioAsigna, AGA.FECHORAIN AS FechaConsulta, DATENAME(MONTH, AGA.FECHORAIN) + '/' + CAST(YEAR(AGA.FECHORAIN) AS varchar) AS MesConsulta,
	DATENAME(YEAR, AGA.FECHORAIN) AS AñoConsulta,
	CASE AGA.CODESTCIT
		WHEN 0 THEN  'Asignada'  
		WHEN 1 THEN  'Cumplida' 
		WHEN 2 THEN  'Incumplida' 
		WHEN 3 THEN  'PreAsignada'
		WHEN 4 THEN  'Cita Cancelada'
	END AS EstadoCita,
	INE.NOMENTIDA AS EntidadPaciente,
	CASE AGA.CODTIPCIT
		WHEN 0 THEN 'Primera Vez' 
		WHEN 1 THEN 'Control' 
		WHEN 2 THEN 'PostOperatorio' 
	END AS Tipo,
	INPR.CODPROSAL AS CodMedico, INPR.NOMMEDICO AS NombreMedico, INES.DESESPECI AS Especialidad, 
	INP.IPSEXOPAC AS Sexo, CAST(INP.IPFECNACI as date)AS FNacimiento,
	dbo.Edad(TRY_CAST(INP.IPFECNACI AS DATE), TRY_CAST(AGA.FECHORAIN AS DATE))AS Edad,
	IPTIPOPAC  AS TipoRegimen,
	INP.IPDIRECCI AS Direccion, INMU.MUNNOMBRE AS Municipio, AGAC.DESACTMED AS Actividad,
	CENSO.Servicio AS Hospitalización, CENSO.Cama, CENSO.DiasHospital, HCP.FECINIATE AS FechaParto, HCP.TERTRAPAR AS TipoParto,
	UE2.InicioEstancia AS InicioEstanciaUltimos45d, UE2.FinEstancia, UE2.DiagnosticoPpalEstancia, UE2.DescripcionQxPpal, UE2.FechaQx
FROM            dbo.INPACIENT AS INP  INNER JOIN
	dbo.INENTIDAD AS INE  ON INP.CODENTIDA = INE.CODENTIDA INNER JOIN
	dbo.AGASICITA AS AGA  ON INP.IPCODPACI = AGA.IPCODPACI INNER JOIN
	dbo.INUBICACI AS INU  ON INP.AUUBICACI = INU.AUUBICACI INNER JOIN
	dbo.INMUNICIP AS INMU  ON INU.DEPMUNCOD = INMU.DEPMUNCOD INNER JOIN
	dbo.SEGusuaru AS US  ON AGA.CODUSUASI=US.CODUSUARI INNER JOIN 
	dbo.AGACTIMED AS AGAC  ON AGA.CODACTMED = AGAC.CODACTMED LEFT OUTER JOIN
	dbo.SEGusuaru AS US2  ON AGA.CANCELUSU = US2.CODUSUARI LEFT OUTER JOIN
	dbo.AGCAUCANC AS CC  ON AGA.CODCAUCAN = CC.CODCAUCAN LEFT OUTER JOIN
	dbo.INPROFSAL AS INPR  ON AGA.CODPROSAL = INPR.CODPROSAL LEFT OUTER JOIN
	dbo.INESPECIA AS INES  ON AGA.CODESPECI= INES.CODESPECI LEFT OUTER JOIN
	dbo.AGCITESPE AS AGCI  ON AGA.CODESPECI = AGCI.CODESPECI AND AGA.IPCODPACI = AGCI.IPCODPACI LEFT OUTER JOIN
	CENSO ON CENSO.Identificación=INP.IPCODPACI LEFT OUTER JOIN
	dbo.HCATINPAR AS HCP ON (HCP.IPCODPACI = INP.IPCODPACI AND HCP.FECINIATE > DATEADD(DAY,-45,@FECHA_INICIAL)) OUTER APPLY
		(SELECT TOP(1) UE.InicioEstancia, CASE UE.FinEstancia WHEN '30000101' THEN NULL ELSE UE.FinEstancia END AS FinEstancia, 
			UE.DiagnosticoPpalEstancia, UE.DescripcionQxPpal, UE.FechaQx
			FROM UE WHERE UE.IPCODPACI=AGA.IPCODPACI ORDER BY UE.FinEstancia DESC ) AS UE2
WHERE AGA.FECHORAIN >= @FECHA_INICIAL AND AGA.FECHORAIN < @FECHA_FINAL AND AGA.CODESTCIT <> 4
ORDER BY AGA.FECHORAIN;
END

