-- Workspace: HOMI
-- Item: DataWareHouse_RCM [Warehouse]
-- ItemId: 834d5676-5644-4a78-a5e2-f198281d02d0
-- Schema: Report
-- Object: SP_FAC_PRODUCTIVIDAD_FACTURACION_FACTUADO_MAS_PENDIENTE_CONSOLIDADO
-- Extracted by Fabric SQL Extractor SPN v3.9.0

CREATE PROCEDURE Report.SP_FAC_PRODUCTIVIDAD_FACTURACION_FACTUADO_MAS_PENDIENTE_CONSOLIDADO
	@FechaInicial Datetime ,
	@FechaFinal Datetime 
AS

--declare @FechaInicial date = '2022-06-01';
--declare @FechaFinal date = '2022-10-31';

WITH CTE_CONSOLIDADO_FACTURADO
AS
(
    SELECT FAC.ENTIDAD ,FAC.GRUPO ,FAC.SUBGRUPO ,FAC.CUPS ,FAC.[DESCRIPCION CUPS] ,
    IIF(CUPS.ServiceType ='5','1',SUM(FAC.CANTIDAD)) CANTIDAD ,CASE CUPS.ServiceType WHEN 1 THEN 'Laboratorios' WHEN 2 THEN 'Patologias' WHEN 3 THEN 'Imagenes Diagnosticas'
    WHEN 4 THEN 'Procedimeintos no Qx' WHEN 5 THEN 'Procedimientos Qx' WHEN 6 THEN 'Consultas/Interconsultas' WHEN 7 THEN 'Ninguno' WHEN 8 THEN 'Consulta Externa' ELSE 'Productos' END 'TIPO SERVICIO',
    SUM(FAC.[VALOR TOTAL]) TOTAL ,FAC.INGRESO ,FAC.[TIPO REGISTRO],FAC.[FECHA SERVICIO]
    FROM [DataWareHouse_RCM].[Report].[VW_VIEW_FAC_TOTAL_FACTURADO_FINAL_POR_FACTURA_DETALLADO_PRODUCTIVIDAD] FAC
    LEFT JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON FAC.CUPS =CUPS.Code 
    where CAST(FAC.[FECHA SERVICIO] AS DATE) BETWEEN @FechaInicial AND @FechaFinal --and [TIPO REGISTRO] ='Servicios' --AND INGRESO ='36158' AND CUPS IN ('020401','883522','890475','541102')
    GROUP BY FAC.ENTIDAD ,FAC.GRUPO ,FAC.SUBGRUPO ,FAC.CUPS ,FAC.[DESCRIPCION CUPS],FAC.INGRESO ,FAC.[TIPO REGISTRO],CUPS.ServiceType, FAC.[FECHA SERVICIO]
    --36158     
),
CTE_CONSOLIDADO_PENDIENTE
AS
(
    SELECT FAC.ENTIDAD ,FAC.GRUPO ,FAC.SUBGRUPO ,FAC.CUPS ,FAC.[DESCRIPCION CUPS] ,
    IIF(CUPS.ServiceType ='5','1',SUM(FAC.CANTIDAD)) CANTIDAD ,CASE CUPS.ServiceType WHEN 1 THEN 'Laboratorios' WHEN 2 THEN 'Patologias' WHEN 3 THEN 'Imagenes Diagnosticas'
    WHEN 4 THEN 'Procedimeintos no Qx' WHEN 5 THEN 'Procedimientos Qx' WHEN 6 THEN 'Consultas/Interconsultas' WHEN 7 THEN 'Ninguno' WHEN 8 THEN 'Consulta Externa' ELSE 'Productos' END 'TIPO SERVICIO',
    SUM(FAC.[VALOR TOTAL]) TOTAL ,FAC.INGRESO ,FAC.[TIPO REGISTRO], FAC.[FECHA SERVICIO]
    FROM [DataWareHouse_RCM].[Report].[VW_VIEW_FAC_TOTAL_PENDIENTE_FACTURAR_FINAL_POR_INGRESO_DETALLADO_PRODUCTIVIDAD] FAC
    LEFT JOIN INDIGO036.Contract.CUPSEntity AS CUPS ON FAC.CUPS =CUPS.Code 
    where CAST(FAC.[FECHA SERVICIO] AS DATE) BETWEEN @FechaInicial AND @FechaFinal --and [TIPO REGISTRO] ='Servicios' --AND INGRESO ='36158' AND CUPS IN ('020401','883522','890475','541102')
    GROUP BY FAC.ENTIDAD ,FAC.GRUPO ,FAC.SUBGRUPO ,FAC.CUPS ,FAC.[DESCRIPCION CUPS],FAC.INGRESO ,FAC.[TIPO REGISTRO],CUPS.ServiceType, FAC.[FECHA SERVICIO]
    --36158     
),
CTE_FINAL_FACTURADO
AS
(
    SELECT C.[TIPO REGISTRO] ,C.[TIPO SERVICIO] ,C.ENTIDAD ,C.GRUPO ,C.SUBGRUPO ,C.CUPS ,C.[DESCRIPCION CUPS] ,SUM(C.CANTIDAD) CANTIDAD,SUM(C.TOTAL) TOTAL,C.[FECHA SERVICIO]   
    FROM CTE_CONSOLIDADO_FACTURADO C
    GROUP BY C.[TIPO REGISTRO],C.ENTIDAD ,C.GRUPO ,C.SUBGRUPO ,C.CUPS ,C.[DESCRIPCION CUPS],C.[TIPO SERVICIO],C.[FECHA SERVICIO]
),
CTE_FINAL_PENDIENTE
AS
(
    SELECT C.[TIPO REGISTRO] ,C.[TIPO SERVICIO] ,C.ENTIDAD ,C.GRUPO ,C.SUBGRUPO ,C.CUPS ,C.[DESCRIPCION CUPS] ,SUM(C.CANTIDAD) CANTIDAD,SUM(C.TOTAL) TOTAL, C.[FECHA SERVICIO]   
    FROM CTE_CONSOLIDADO_PENDIENTE C
    GROUP BY C.[TIPO REGISTRO],C.ENTIDAD ,C.GRUPO ,C.SUBGRUPO ,C.CUPS ,C.[DESCRIPCION CUPS],C.[TIPO SERVICIO], C.[FECHA SERVICIO]
),
CTE_TOTAL_FINAL
AS
(
    SELECT * FROM CTE_FINAL_FACTURADO 
    UNION ALL
    SELECT * FROM CTE_FINAL_PENDIENTE 
)

SELECT C.[TIPO REGISTRO] ,C.[TIPO SERVICIO] ,C.ENTIDAD ,C.GRUPO ,C.SUBGRUPO ,C.CUPS ,C.[DESCRIPCION CUPS] ,SUM(C.CANTIDAD) CANTIDAD,SUM(C.TOTAL) TOTAL,C.[FECHA SERVICIO]
FROM CTE_TOTAL_FINAL C
GROUP BY C.[TIPO REGISTRO],C.ENTIDAD ,C.GRUPO ,C.SUBGRUPO ,C.CUPS ,C.[DESCRIPCION CUPS],C.[TIPO SERVICIO], C.[FECHA SERVICIO]
