-- Workspace: HOMI
-- Item: DataWareHouse_RCM [Warehouse]
-- ItemId: 834d5676-5644-4a78-a5e2-f198281d02d0
-- Schema: Report
-- Object: SP_FAC_NIIF_TOTAL_FACTURADO
-- Extracted by Fabric SQL Extractor SPN v3.9.0


CREATE PROCEDURE Report.SP_FAC_NIIF_TOTAL_FACTURADO
@FECINI Datetime,
@FECFIN Datetime 

AS

-------NIIF SERVICIOS FACTURADOS -----
WITH CTE_FACTURACION_CABECERA AS (
	SELECT
		F.Id ID_FACTURA,
		CASE
			F.DocumentType
			WHEN '1' THEN 'FACTURA EAPB CON CONTRATO'
			WHEN '2' THEN 'FACTURA EAPB SIN CONTRATO'
			WHEN '3' THEN 'FACTURA PARTICULAR'
			WHEN '4' THEN 'FACTURA CAPITA'
			WHEN '5' THEN 'CONTROL CAPITACION'
			WHEN '6' THEN 'FACTURA BASICA'
			WHEN '7' THEN 'FACTURA VENTA PRODUCTOS'
		END 'TIPO REGISTRO',
		CASE
			PAC.IPTIPODOC
			WHEN '1' THEN 'CEDULA DE CIUDADANIA'
			WHEN '2' THEN 'CEDULA DE EXTRANJERIA'
			WHEN '3' THEN 'TARJETA DE IDENTIDAD'
			WHEN '4' THEN 'REGISTRO CIVIL'
			WHEN '5' THEN 'PASAPORTE'
			WHEN '6' THEN 'ADULTO SIN IDENTIFICACION'
			WHEN '7' THEN 'MENOR SIN IDENTIFICACION'
			WHEN '8' THEN 'NUMERO UNICO DE IDENTIFICACION'
			WHEN '9' THEN 'CERTIFICADO NACIDO VIVO'
			WHEN '10' THEN 'CARNET DIPLOMATICO'
			WHEN '11' THEN 'SALVOCONDUCTO'
			WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA'
			WHEN '13' THEN 'PERMISO TEMPORAL DE PERMANENCIA'
			WHEN '14' THEN 'DOCUMENTO EXTRANJERO'
			WHEN '15' THEN 'SIN IDENTIFICACION'
			ELSE 'N/A'
		END AS 'TIPO IDENTIFICACION',
		ISNULL(F.PatientCode, 0) AS 'IDENTIFICACION',
		CASE
			WHEN RTRIM(PAC.IPNOMCOMP) IS NULL
			AND F.DocumentType LIKE '4' THEN 'N/A'
			WHEN PAC.IPNOMCOMP IS NULL
			AND F.DocumentType LIKE '6' THEN 'N/A'
			ELSE RTRIM(PAC.IPNOMCOMP)
		END AS 'PACIENTE',
		F.AdmissionNumber 'INGRESO',
		CAST(ING.IFECHAING AS DATE) 'FECHA INGRESO',
		CAST(ISNULL(ING.FECHEGRESO, ING.IFECHAING) AS DATE) 'FECHA EGRESO',
		F.InvoiceNumber 'NRO FACTURA',
		CAST(F.InvoiceDate AS DATE) 'FECHA FACTURA',
		F.TotalInvoice 'TOTAL FACTURA',
		F.ThirdPartySalesValue AS 'VR TOTAL ENTIDAD',
		F.ThirdPartyDiscountValue AS 'VR TOTAL DESCUENTO',
		F.TotalPatientSalesPrice AS 'VR TOTAL CUOTA RECUPERACION',
		CASE
			F.Status
			WHEN '1' THEN 'FACTURADO'
			WHEN '2' THEN 'ANULADO'
		END AS 'ESTADO FACTURA',
		F.HealthAdministratorId 'ID ENTIDAD',
		RTRIM(T.Nit) 'NIT ENTIDAD',
		RTRIM(HA.Code) 'CODIGO ENTIDAD',
		RTRIM(HA.Name) 'ENTIDAD',
		RTRIM(CG.Code) 'CODIGO GRUPO',
		RTRIM(CG.Name) 'GRUPO DE ATENCION',
		CASE
			WHEN HA.EntityType LIKE '1' THEN 'EPS CONTRIBUTIVO'
			WHEN HA.EntityType LIKE '2' THEN 'EPS SUBSIDIADO'
			WHEN HA.EntityType LIKE '3' THEN 'ET VINCULADO MUNICIPIO'
			WHEN HA.EntityType LIKE '4' THEN 'ET VINCULADOS DAPARTAMENTO'
			WHEN HA.EntityType LIKE '5' THEN 'ARL RIESGO LABORALES'
			WHEN HA.EntityType LIKE '6' THEN 'MP MEDICINA PREPAGADA'
			WHEN HA.EntityType LIKE '7' THEN 'IPS PRIVADA'
			WHEN HA.EntityType LIKE '8' THEN 'IPS PUBLICA'
			WHEN HA.EntityType LIKE '9' THEN 'REGIMEN ESPECIAL'
			WHEN HA.EntityType LIKE '10' THEN 'ACCIDENTE DE TRANSITO'
			WHEN HA.EntityType LIKE '11' THEN 'FOSYGA'
			WHEN HA.EntityType LIKE '12' THEN 'OTROS'
			WHEN HA.EntityType IS NULL
			AND F.DocumentType LIKE '4' THEN 'N/A'
			WHEN HA.EntityType IS NULL
			AND F.DocumentType LIKE '6' THEN 'N/A'
		END AS [TIPO REGIMEN],
		CASE
			WHEN ING.TIPOINGRE = 1 THEN 'AMBULATORIO'
			WHEN ING.TIPOINGRE = 2 THEN 'HOSPITALARIO'
			WHEN ING.TIPOINGRE IS NULL
			AND F.DocumentType LIKE '1' THEN 'FACTURA EAPB CON CONTRATO'
			WHEN ING.TIPOINGRE IS NULL
			AND F.DocumentType LIKE '2' THEN 'FACTURA EAPB SIN CONTRATO'
			WHEN ING.TIPOINGRE IS NULL
			AND F.DocumentType LIKE '3' THEN 'FACTURA PARTICULAR'
			WHEN ING.TIPOINGRE IS NULL
			AND F.DocumentType LIKE '4' THEN 'FACTURA CAPITA'
			WHEN ING.TIPOINGRE IS NULL
			AND F.DocumentType LIKE '5' THEN 'CONTROL CAPITACION'
			WHEN ING.TIPOINGRE IS NULL
			AND F.DocumentType LIKE '6' THEN 'FACTURA BASICA'
			WHEN ING.TIPOINGRE IS NULL
			AND F.DocumentType LIKE '7' THEN 'FACTURA VENTA PRODUCTOS'
		END AS 'TIPO AMBITO INGRESO',
		USU.NOMUSUARI 'USUARIO FACTURO',
		CAST(F.InvoicedDate AS DATE) 'FECHA REGISTRO',
		ISNULL(DIA.CODDIAGNO, DIAG.CODDIAGNO) 'CODIGO CIE10',
		ISNULL(RTRIM(DIA.NOMDIAGNO), RTRIM(DIAG.NOMDIAGNO)) 'DIAGNOSTICO',
		CASE
			WHEN ING.IAUTORIZA IS NULL
			AND F.DocumentType LIKE '4' THEN 'N/A'
			WHEN ING.IAUTORIZA IS NULL
			AND F.DocumentType LIKE '6' THEN 'N/A'
			WHEN ING.IAUTORIZA LIKE ' ' THEN 'N/A'
			ELSE ING.IAUTORIZA
		END AS 'AUTORIZACION',
		ISNULL(
			IIF (
				F.DocumentType = 6,
				LTRIM(FU2.Code) + ' - ' + FU2.Name,
				ISNULL(
					FU.Code + ' - ' + FU.Name,
					LTRIM(ING.UFUCODIGO) + ' - ' + UF.Name
				)
			),
			'N/A'
		) AS [UNIDAD FUNCIONAL EGRESO],
		C.Name 'CATEGORIA FACTURA',
		F.AnnulmentDate 'FECHA ANULACION',
		CASE
			F.Status
			WHEN '1' THEN CAST(F.InvoiceDate AS DATE)
			WHEN '2' THEN CAST(F.AnnulmentDate AS DATE)
		END AS 'FECHA BUSQUEDA'
	FROM
		INDIGO036.Billing.Invoice AS F 
		INNER JOIN [INDIGO036].[dbo].[ADINGRESO] AS ING  ON ING.NUMINGRES = F.AdmissionNumber
		INNER JOIN [INDIGO036].[dbo].[INPACIENT] AS PAC  ON PAC.IPCODPACI = F.PatientCode
		INNER JOIN INDIGO036.Contract.HealthAdministrator AS HA  ON HA.Id = F.HealthAdministratorId
		INNER JOIN INDIGO036.Contract.CareGroup AS CG  ON CG.Id = F.CareGroupId
		INNER JOIN INDIGO036.Common.ThirdParty AS T  ON T.Id = F.ThirdPartyId
		INNER JOIN INDIGO036.Billing.InvoiceCategories AS C  ON C.Id = F.InvoiceCategoryId
		LEFT JOIN [INDIGO036].[dbo].[SEGusuaru] AS USU  ON USU.CODUSUARI = F.InvoicedUser
		LEFT JOIN [INDIGO036].[dbo].[INDIAGNOS] AS DIA  ON DIA.CODDIAGNO = ISNULL(ING.CODDIAEGR, ING.CODDIAING)
		LEFT JOIN INDIGO036.Payroll.FunctionalUnit AS UF  ON UF.Code = ING.UFUCODIGO
		LEFT JOIN INDIGO036.Payroll.FunctionalUnit AS FU  ON ING.UFUEGRMED = FU.Code
		LEFT JOIN INDIGO036.Billing.BasicBilling AS BB  ON BB.InvoiceId = F.Id
		LEFT JOIN INDIGO036.Payroll.FunctionalUnit AS FU2  ON BB.FunctionalUnitId = FU2.Id
		LEFT JOIN [INDIGO036].[dbo].[INDIAGNOS] AS DIAG  ON DIAG.CODDIAGNO = F.OutputDiagnosis --where CAST(F.InvoiceDate AS DATE) BETWEEN '2022-05-01' AND '2022-05-31'
	where
		(
			CASE
				F.Status
				WHEN '1' THEN CAST(F.InvoiceDate AS DATE)
				WHEN '2' THEN CAST(F.AnnulmentDate AS DATE)
			END
		) between @FECINI
		and @FECFIN
),
CTE_ALTA_MEDICA AS (
	SELECT
		EGR.NUMINGRES,
		EGR.IPCODPACI,
		MAX(FECALTPAC) 'FECHA ALTA'
	FROM
		[INDIGO036].[dbo].[HCREGEGRE] EGR
		INNER JOIN CTE_FACTURACION_CABECERA AS PEN ON PEN.INGRESO = EGR.NUMINGRES
	GROUP BY
		EGR.NUMINGRES,
		EGR.IPCODPACI
),
CTE_HISTORIAS_AMBULATORIAS AS (
	SELECT
		HIS.NUMINGRES,
		HIS.IPCODPACI,
		MAX(FECHISPAC) AS 'FECHA ALTA'
	FROM
		[INDIGO036].[dbo].[HCHISPACA] HIS
		INNER JOIN CTE_FACTURACION_CABECERA AS PEN ON PEN.INGRESO = HIS.NUMINGRES
	WHERE
		HIS.GENCONEXT = 1
	GROUP BY
		HIS.NUMINGRES,
		HIS.IPCODPACI
),
CTE_FACTURA_DETALLE AS (
	SELECT
		CAST(DB_Name() AS VARCHAR(9)) AS ID_COMPANY,
		FCAB.[NIT ENTIDAD],
		SUBSTRING(FCAB.ENTIDAD, 1, 50) 'ENTIDAD',
		FCAB.[CODIGO GRUPO],
		FCAB.[GRUPO DE ATENCION],
		FCAB.INGRESO,
		FCAB.[FECHA INGRESO],
		FCAB.[FECHA EGRESO],
		FCAB.[TIPO IDENTIFICACION],
		FCAB.IDENTIFICACION,
		FCAB.PACIENTE,
		FCAB.[ESTADO FACTURA],
		FCAB.[NRO FACTURA],
		FCAB.[FECHA FACTURA],
		FCAB.[TOTAL FACTURA],
		FCAB.[VR TOTAL DESCUENTO],
		FCAB.[VR TOTAL ENTIDAD],
		FCAB.[VR TOTAL CUOTA RECUPERACION],
		SO.Code 'CAB_ORD_NRO',
		SO.OrderDate 'CAB_ORD_FECHA_ORDEN',
		CASE
			SOD.RecordType
			WHEN 1 THEN 'Servicios'
			WHEN 2 THEN 'Medicamentos'
			ELSE 'N/A'
		END 'DET_ORD_TIPO',
		ISNULL(GF.Name, GF2.Name) AS 'DET_ORD_GRUPO FACTURACION',
		ISNULL(
			CGR.Code + '-' + CGR.Name,
			PG.Code + '-' + PG.Name
		) 'DET_ORD_GRUPO',
		ISNULL(
			CSG.Code + '-' + CSG.Name,
			PSG.Code + '-' + PSG.Name
		) 'DET_ORD_SUBGRUPO',
		CASE
			SOD.Presentation
			WHEN 1 THEN 'No quirurgico'
			WHEN 2 THEN 'Quirurgico'
			WHEN 3 THEN 'Paquete'
			ELSE 'PRODUCTO'
		END 'DET_ORD_PRESENTACION',
		ISNULL(CUPS.Code, 'N/A') 'DET_ORD_CUPS',
		SUBSTRING(ISNULL(RTRIM(CUPS.Description), 'N/A'), 1, 60) 'DET_ORD_DESCRIPCION_CUPS',
		ISNULL(RTRIM(IPS.Code), RTRIM(IPR.Code)) 'DET_ORD_CODIGO_SERVICIO/PRODUCTO',
		SUBSTRING(ISNULL(RTRIM(IPS.Name), RTRIM(IPR.Name)), 1, 60) 'DET_ORD_DESCRIPCION_SERVICIO/PRODUCTO',
		ISNULL(SERVICIOSIPSQ.Code, 'N/A') AS 'DET_ORDQX_SUBCODIGO',
		SUBSTRING(ISNULL(RTRIM(SERVICIOSIPSQ.Name), 'N/A'), 1, 60) AS 'DET_ORDQX_SUBNOMBRE',
		'' 'DET VISUALIZA FACTURA',
		CASE
			SOD.IsPackage
			WHEN 1 THEN 'PAQUETE (INCLUYE OTROS SERVICIOS)'
			WHEN 0 THEN 'NO ES PAQUETE'
			ELSE 'N/A'
		END 'DET_ORD_PAQUETE',
		CASE
			SOD.Packaging
			WHEN 1 THEN 'INCLUIDO EN PAQUETE'
			WHEN 0 THEN 'NO INCLUIDO EN PAQUETE'
			ELSE 'N/A'
		END 'DET_ORD_INCLUIDO_EN_PAQUETE',
		ISNULL(CUPS_PAQ.Code, 'N/A') 'DET_ORD_CUPS_PAQUETE',
		SUBSTRING(ISNULL(RTRIM(CUPS_PAQ.Description), 'N/A'), 1, 60) 'DET_ORD_DESCRIPCION_CUPS_PAQUETE',
		CASE
			SOD.SettlementType
			WHEN 1 THEN 'Por manual de tarifas'
			WHEN 2 THEN '% de otro servicio cargado'
			WHEN 3 THEN '100% incluido dentro de otro servicio (No se cobra nada)'
			WHEN 4 THEN '% del mismo servicio'
			ELSE 'N/A'
		END 'DET_ORD_TIPO_LIQUIDACION',
		ISNULL(CUPS_INC.Code, 'N/A') 'DET_ORD_CUPS_INCLUIDO',
		SUBSTRING(ISNULL(RTRIM(CUPS_INC.Description), 'N/A'), 1, 60) 'DET_ORD_DESCRIPCION_CUPS_INCLUIDO',
		FU.Code 'DET_ORD_CODIGO_UNIDAD_FUNCIONAL',
		RTRIM(FU.Name) 'DET_ORD_UNIDAD_FUNCIONAL_PRESTO_SERVICIO',
		COST.Code 'DET_ORD_COD_CENTRO_COSTO',
		RTRIM(COST.Name) 'DET_ORD_CENTRO_COSTO',
		RTRIM(
			ISNULL(
				DQ.PerformsHealthProfessionalCode,
				ISNULL(MED.CODPROSAL, '000')
			)
		) 'DET_ORD_IDENTIFICACION_PROFESIONAL',
		RTRIM(
			ISNULL(MEDQX.NOMMEDICO, ISNULL(MED.NOMMEDICO, 'N/A'))
		) 'DET_ORD_PROFESIONAL',
		RTRIM(
			ISNULL(ESPQX.DESESPECI, ISNULL(ESPMED.DESESPECI, 'N/A'))
		) 'DET_ORD_ESPECIALIDAD',
		ISNULL(DQ.InvoicedQuantity, SOD.InvoicedQuantity) 'DET_ORD_CANTIDAD',
		ISNULL(DQ.RateManualSalePrice, SOD.RateManualSalePrice) 'DET_ORD_VALOR_SERVICIO',
		ISNULL(DQ.TotalSalesPrice, SOD.TotalSalesPrice) 'DET_ORD_VALOR_UNITARIO',
		ISNULL(DQ.TotalSalesPrice, SOD.GrandTotalSalesPrice) 'DET_ORD_VALOR_TOTAL',
		CASE
			ISNULL(IPS.POS, IPR.POSProduct)
			WHEN 1 THEN 'PBS'
			ELSE 'NO PBS'
		END 'DET_ORD_TECNOLOGIA_PBS',
		--FCAB.[TIPO AMBITO INGRESO],
		IIF(
			FCAB.[TIPO AMBITO INGRESO] = 'HOSPITALARIO',
			ALT.[FECHA ALTA],
			ISNULL(AMB.[FECHA ALTA], FCAB.[FECHA INGRESO])
		) 'FECHA ALTA MEDICA',
		FCAB.[FECHA ANULACION],
		'' 'CAMA ACTIVA',
		SOD.Id 'ID_ORDE_DETALLE',
		FCAB.ID_FACTURA,
		FCAB.[ID ENTIDAD],
		FCAB.[TIPO REGISTRO],
		SOD.AuthorizationNumber 'NUMERO AUTORIZACION',
		FCAB.[FECHA BUSQUEDA],
		CAST(SOD.ServiceDate AS DATE) 'FECHA SERVICIO BUSQUEDA',
		'SI' 'FACTURADO',
		FCAB.[USUARIO FACTURO]
	FROM
		INDIGO036.Billing.InvoiceDetail AS ID 
		INNER JOIN CTE_FACTURACION_CABECERA AS FCAB  ON FCAB.ID_FACTURA = ID.InvoiceId
		INNER JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD  ON SOD.Id = ID.ServiceOrderDetailId
		INNER JOIN INDIGO036.Billing.ServiceOrder AS SO  ON SO.Id = SOD.ServiceOrderId
		INNER JOIN INDIGO036.Payroll.FunctionalUnit AS FU  ON FU.Id = SOD.PerformsFunctionalUnitId
		INNER JOIN INDIGO036.Contract.CareGroup AS CG  ON CG.Id = SOD.CareGroupId
		INNER JOIN INDIGO036.Contract.HealthAdministrator AS HA  ON HA.Id = ISNULL(SOD.HealthAdministratorId, FCAB.[ID ENTIDAD])
		LEFT JOIN [INDIGO036].[Inventory].[InventoryProduct] AS PR  ON PR.Id = SOD.ProductId
		LEFT JOIN INDIGO036.Contract.CUPSEntity AS CUPS  ON CUPS.Id = SOD.CUPSEntityId
		LEFT JOIN INDIGO036.Contract.IPSService AS IPS  ON IPS.Id = SOD.IPSServiceId
		LEFT JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD_PAQ  ON SOD_PAQ.Id = SOD.PackageServiceOrderDetailId
		LEFT JOIN INDIGO036.Contract.CUPSEntity AS CUPS_PAQ  ON CUPS_PAQ.Id = SOD_PAQ.CUPSEntityId
		LEFT JOIN [INDIGO036].[Inventory].[InventoryProduct] AS IPR  ON IPR.Id = SOD.ProductId
		LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] AS MED  ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
		LEFT JOIN [INDIGO036].[dbo].[INESPECIA] AS ESPMED  ON ESPMED.CODESPECI = MED.CODESPEC1
		LEFT JOIN INDIGO036.Payroll.CostCenter AS COST  ON COST.Id = SOD.CostCenterId
		LEFT JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD_INC  ON SOD_INC.Id = SOD.IncludeServiceOrderDetailId
		LEFT JOIN INDIGO036.Contract.CUPSEntity AS CUPS_INC  ON CUPS_INC.Id = SOD_INC.CUPSEntityId
		LEFT JOIN [INDIGO036].[Inventory].[ProductGroup] AS PG  ON PG.Id = IPR.ProductGroupId
		LEFT JOIN [INDIGO036].[Inventory].[ProductSubGroup] AS PSG  ON PSG.Id = IPR.ProductSubGroupId
		LEFT JOIN INDIGO036.Contract.CupsSubgroup AS CSG  ON CSG.Id = CUPS.CUPSSubGroupId
		LEFT JOIN INDIGO036.Contract.CupsGroup AS CGR  ON CGR.Id = CSG.CupsGroupId
		LEFT JOIN INDIGO036.Billing.BillingGroup AS GF  ON GF.Id = CUPS.BillingGroupId
		LEFT JOIN INDIGO036.Billing.BillingGroup AS GF2  ON GF2.Id = IPR.BillingGroupId
		LEFT JOIN INDIGO036.Billing.ServiceOrderDetailSurgical AS DQ  ON DQ.ServiceOrderDetailId = SOD.Id
		AND DQ.OnlyMedicalFees = '0'
		LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] AS MEDQX  ON MEDQX.CODPROSAL = DQ.PerformsHealthProfessionalCode
		LEFT JOIN [INDIGO036].[dbo].[INESPECIA] AS ESPQX  ON ESPQX.CODESPECI = MEDQX.CODESPEC1
		LEFT JOIN INDIGO036.Contract.IPSService AS SERVICIOSIPSQ  ON SERVICIOSIPSQ.Id = DQ.IPSServiceId
		LEFT JOIN CTE_ALTA_MEDICA AS ALT  ON ALT.NUMINGRES = FCAB.INGRESO
		LEFT JOIN CTE_HISTORIAS_AMBULATORIAS AS AMB  ON AMB.NUMINGRES = FCAB.INGRESO
	WHERE
		SOD.InvoicedQuantity <> '0'
),
CTE_ORDENES_FACTURADA_PAQUETE AS (
	SELECT
		CAST(DB_Name() AS VARCHAR(9)) AS ID_COMPANY,
		ORDF.[NIT ENTIDAD],
		SUBSTRING(ORDF.ENTIDAD, 1, 50) 'ENTIDAD',
		ORDF.[CODIGO GRUPO],
		ORDF.[GRUPO DE ATENCION],
		ORDF.INGRESO,
		ORDF.[FECHA INGRESO],
		ORDF.[FECHA EGRESO],
		ORDF.[TIPO IDENTIFICACION],
		ORDF.IDENTIFICACION,
		ORDF.PACIENTE,
		ORDF.[ESTADO FACTURA],
		ORDF.[NRO FACTURA],
		ORDF.[FECHA FACTURA],
		ORDF.[TOTAL FACTURA],
		ORDF.[VR TOTAL DESCUENTO],
		ORDF.[VR TOTAL ENTIDAD],
		ORDF.[VR TOTAL CUOTA RECUPERACION],
		SO.Code 'CAB_ORD_NRO',
		SO.OrderDate 'CAB_ORD_FECHA_ORDEN',
CASE
			SOD.RecordType
			WHEN 1 THEN 'Servicios'
			WHEN 2 THEN 'Medicamentos'
			ELSE 'N/A'
		END 'DET_ORD_TIPO',
		ISNULL(GF.Name, GF2.Name) AS 'DET_ORD_GRUPO FACTURACION',
		ISNULL(
			CGR.Code + '-' + CGR.Name,
			PG.Code + '-' + PG.Name
		) 'DET_ORD_GRUPO',
		ISNULL(
			CSG.Code + '-' + CSG.Name,
			PSG.Code + '-' + PSG.Name
		) 'DET_ORD_SUBGRUPO',
		CASE
			SOD.Presentation
			WHEN 1 THEN 'No quirurgico'
			WHEN 2 THEN 'Quirurgico'
			WHEN 3 THEN 'Paquete'
			ELSE 'PRODUCTO'
		END 'DET_ORD_PRESENTACION',
		ISNULL(CUPS.Code, 'N/A') 'DET_ORD_CUPS',
		SUBSTRING(ISNULL(RTRIM(CUPS.Description), 'N/A'), 1, 60) 'DET_ORD_DESCRIPCION_CUPS',
		ISNULL(RTRIM(IPS.Code), RTRIM(IPR.Code)) 'DET_ORD_CODIGO_SERVICIO/PRODUCTO',
		SUBSTRING(ISNULL(RTRIM(IPS.Name), RTRIM(IPR.Name)), 1, 60) 'DET_ORD_DESCRIPCION_SERVICIO/PRODUCTO',
		ISNULL(SERVICIOSIPSQ.Code, 'N/A') AS 'DET_ORDQX_SUBCODIGO',
		ISNULL(RTRIM(SERVICIOSIPSQ.Name), 'N/A') AS 'DET_ORDQX_SUBNOMBRE',
		'' 'DET VISUALIZA FACTURA',
		CASE
			SOD.IsPackage
			WHEN 1 THEN 'PAQUETE (INCLUYE OTROS SERVICIOS)'
			WHEN 0 THEN 'NO ES PAQUETE'
			ELSE 'N/A'
		END 'DET_ORD_PAQUETE',
		CASE
			SOD.Packaging
			WHEN 1 THEN 'INCLUIDO EN PAQUETE'
			WHEN 0 THEN 'NO INCLUIDO EN PAQUETE'
			ELSE 'N/A'
		END 'DET_ORD_INCLUIDO_EN_PAQUETE',
		ISNULL(CUPS_PAQ.Code, 'N/A') 'DET_ORD_CUPS_PAQUETE',
		SUBSTRING(ISNULL(RTRIM(CUPS_PAQ.Description), 'N/A'), 1, 60) 'DET_ORD_DESCRIPCION_CUPS_PAQUETE',
		CASE
			SOD.SettlementType
			WHEN 1 THEN 'Por manual de tarifas'
			WHEN 2 THEN '% de otro servicio cargado'
			WHEN 3 THEN '100% incluido dentro de otro servicio (No se cobra nada)'
			WHEN 4 THEN '% del mismo servicio'
			ELSE 'N/A'
		END 'DET_ORD_TIPO_LIQUIDACION',
		ISNULL(CUPS_INC.Code, 'N/A') 'DET_ORD_CUPS_INCLUIDO',
		SUBSTRING(ISNULL(RTRIM(CUPS_INC.Description), 'N/A'), 1, 60) 'DET_ORD_DESCRIPCION_CUPS_INCLUIDO',
		FU.Code 'DET_ORD_CODIGO_UNIDAD_FUNCIONAL',
		RTRIM(FU.Name) 'DET_ORD_UNIDAD_FUNCIONAL_PRESTO_SERVICIO',
		COST.Code 'DET_ORD_COD_CENTRO_COSTO',
		RTRIM(COST.Name) 'DET_ORD_CENTRO_COSTO',
		RTRIM(
			ISNULL(
				DQ.PerformsHealthProfessionalCode,
				ISNULL(MED.CODPROSAL, '000')
			)
		) 'DET_ORD_IDENTIFICACION_PROFESIONAL',
		RTRIM(
			ISNULL(MEDQX.NOMMEDICO, ISNULL(MED.NOMMEDICO, 'N/A'))
		) 'DET_ORD_PROFESIONAL',
		RTRIM(
			ISNULL(ESPQX.DESESPECI, ISNULL(ESPMED.DESESPECI, 'N/A'))
		) 'DET_ORD_ESPECIALIDAD',
		ISNULL(DQ.InvoicedQuantity, SOD.InvoicedQuantity) 'DET_ORD_CANTIDAD',
		ISNULL(DQ.RateManualSalePrice, SOD.RateManualSalePrice) 'DET_ORD_VALOR_SERVICIO',
		ISNULL(DQ.TotalSalesPrice, SOD.TotalSalesPrice) 'DET_ORD_VALOR_UNITARIO',
		ISNULL(DQ.TotalSalesPrice, SOD.GrandTotalSalesPrice) 'DET_ORD_VALOR_TOTAL',
		CASE
			ISNULL(IPS.POS, IPR.POSProduct)
			WHEN 1 THEN 'PBS'
			ELSE 'NO PBS'
		END 'DET_ORD_TECNOLOGIA_PBS',
		ORDF.[FECHA ALTA MEDICA],
		ORDF.[FECHA ANULACION],
		'' 'CAMA ACTIVA',
		SOD.Id 'ID_ORDE_DETALLE',
		ORDF.ID_FACTURA,
		ORDF.[ID ENTIDAD],
		ORDF.[TIPO REGISTRO],
		SOD.AuthorizationNumber 'NUMERO AUTORIZACION',
		ORDF.[FECHA BUSQUEDA],
		CAST(SOD.ServiceDate AS DATE) 'FECHA SERVICIO BUSQUEDA',
		'SI' 'FACTURADO',
		ORDF.[USUARIO FACTURO]
	FROM
		INDIGO036.Billing.ServiceOrder AS SO 
		INNER JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD  ON SO.Id = SOD.ServiceOrderId
		INNER JOIN CTE_FACTURA_DETALLE AS ORDF  ON SOD.PackageServiceOrderDetailId = ORDF.ID_ORDE_DETALLE
		INNER JOIN INDIGO036.Payroll.FunctionalUnit AS FU  ON FU.Id = SOD.PerformsFunctionalUnitId
		INNER JOIN INDIGO036.Contract.CareGroup AS CG  ON CG.Id = SOD.CareGroupId
		INNER JOIN INDIGO036.Contract.HealthAdministrator AS HA  ON HA.Id = ISNULL(SOD.HealthAdministratorId, ORDF.[ID ENTIDAD])
		LEFT JOIN [INDIGO036].[Inventory].[InventoryProduct] AS PR  ON PR.Id = SOD.ProductId
		LEFT JOIN INDIGO036.Contract.CUPSEntity AS CUPS  ON CUPS.Id = SOD.CUPSEntityId
		LEFT JOIN INDIGO036.Contract.IPSService AS IPS  ON IPS.Id = SOD.IPSServiceId
		LEFT JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD_PAQ  ON SOD_PAQ.Id = SOD.PackageServiceOrderDetailId
		LEFT JOIN INDIGO036.Contract.CUPSEntity AS CUPS_PAQ  ON CUPS_PAQ.Id = SOD_PAQ.CUPSEntityId
		LEFT JOIN [INDIGO036].[Inventory].[InventoryProduct] AS IPR  ON IPR.Id = SOD.ProductId
		LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] AS MED  ON MED.CODPROSAL = SOD.PerformsHealthProfessionalCode
		LEFT JOIN [INDIGO036].[dbo].[INESPECIA] AS ESPMED  ON ESPMED.CODESPECI = MED.CODESPEC1
		LEFT JOIN INDIGO036.Payroll.CostCenter AS COST  ON COST.Id = SOD.CostCenterId
		LEFT JOIN INDIGO036.Billing.ServiceOrderDetail AS SOD_INC  ON SOD_INC.Id = SOD.IncludeServiceOrderDetailId
		LEFT JOIN INDIGO036.Contract.CUPSEntity AS CUPS_INC  ON CUPS_INC.Id = SOD_INC.CUPSEntityId
		LEFT JOIN [INDIGO036].[Inventory].[ProductGroup] AS PG  ON PG.Id = IPR.ProductGroupId
		LEFT JOIN [INDIGO036].[Inventory].[ProductSubGroup] AS PSG  ON PSG.Id = IPR.ProductSubGroupId
		LEFT JOIN INDIGO036.Contract.CupsSubgroup AS CSG  ON CSG.Id = CUPS.CUPSSubGroupId
		LEFT JOIN INDIGO036.Contract.CupsGroup AS CGR  ON CGR.Id = CSG.CupsGroupId
		LEFT JOIN INDIGO036.Billing.BillingGroup AS GF  ON GF.Id = CUPS.BillingGroupId
		LEFT JOIN INDIGO036.Billing.BillingGroup AS GF2  ON GF2.Id = IPR.BillingGroupId
		LEFT JOIN INDIGO036.Billing.ServiceOrderDetailSurgical AS DQ  ON DQ.ServiceOrderDetailId = SOD.Id
		AND DQ.OnlyMedicalFees = '0'
		LEFT JOIN [INDIGO036].[dbo].[INPROFSAL] AS MEDQX  ON MEDQX.CODPROSAL = DQ.PerformsHealthProfessionalCode
		LEFT JOIN [INDIGO036].[dbo].[INESPECIA] AS ESPQX  ON ESPQX.CODESPECI = MEDQX.CODESPEC1
		LEFT JOIN INDIGO036.Contract.IPSService AS SERVICIOSIPSQ  ON SERVICIOSIPSQ.Id = DQ.IPSServiceId
	WHERE
		SOD.PackageServiceOrderDetailId IS NOT NULL
)
SELECT
	*,
	1 as 'CANTIDAD',
	YEAR([FECHA BUSQUEDA]) AS 'AÑO FECHA BUSQUEDA',
	MONTH([FECHA BUSQUEDA]) AS 'MES AÑO FECHA BUSQUEDA',
	CASE
		MONTH([FECHA BUSQUEDA])
		WHEN 1 THEN 'ENERO'
		WHEN 2 THEN 'FEBRERO'
		WHEN 3 THEN 'MARZO'
		WHEN 4 THEN 'ABRIL'
		WHEN 5 THEN 'MAYO'
		WHEN 6 THEN 'JUNIO'
		WHEN 7 THEN 'JULIO'
		WHEN 8 THEN 'AGOSTO'
		WHEN 9 THEN 'SEPTIEMBRE'
		WHEN 10 THEN 'OCTUBRE'
		WHEN 11 THEN 'NOVIEMBRE'
		WHEN 12 THEN 'DICIEMBRE'
	END AS 'MES NOMBRE FECHA BUSQUEDA',
	FORMAT(DAY([FECHA BUSQUEDA]), '00') AS 'DIA FECHA BUSQUEDA',
	CONCAT(
		FORMAT(MONTH([FECHA BUSQUEDA]), '00'),
		' - ',
		CASE
			MONTH([FECHA BUSQUEDA])
			WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END
	) MES_LABEL_BUSQUEDA
FROM
	CTE_FACTURA_DETALLE FAC
UNION
ALL
SELECT
	*,
	1 as 'CANTIDAD',
	YEAR([FECHA BUSQUEDA]) AS 'AÑO FECHA BUSQUEDA',
	MONTH([FECHA BUSQUEDA]) AS 'MES AÑO FECHA BUSQUEDA',
	CASE
		MONTH([FECHA BUSQUEDA])
		WHEN 1 THEN 'ENERO'
		WHEN 2 THEN 'FEBRERO'
		WHEN 3 THEN 'MARZO'
		WHEN 4 THEN 'ABRIL'
		WHEN 5 THEN 'MAYO'
		WHEN 6 THEN 'JUNIO'
		WHEN 7 THEN 'JULIO'
		WHEN 8 THEN 'AGOSTO'
		WHEN 9 THEN 'SEPTIEMBRE'
		WHEN 10 THEN 'OCTUBRE'
		WHEN 11 THEN 'NOVIEMBRE'
		WHEN 12 THEN 'DICIEMBRE'
	END AS 'MES NOMBRE FECHA BUSQUEDA',
	FORMAT(DAY([FECHA BUSQUEDA]), '00') AS 'DIA FECHA BUSQUEDA',
	CONCAT(
		FORMAT(MONTH([FECHA BUSQUEDA]), '00'),
		' - ',
		CASE
			MONTH([FECHA BUSQUEDA])
			WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
		END
	) MES_LABEL_BUSQUEDA
FROM
	CTE_ORDENES_FACTURADA_PAQUETE PAQ --where cast([FECHA BUSQUEDA] as date) between @FECINI AND @FECFIN